### ISSUE TITLE
Direct VMDK manipulation investigation

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1]
Investigate how we can directly manipulate VMDKs on ESX. The following high level tasks are of specific interest:
- Extract tar archive onto VMDK - presuming ext4 as the filesystem format should be suitable for linux rootfs
- Expand VMDK capacity, followed by resize filesystem - this should be a "rare" operation so could be handled via a block device attach to a service VM, but we should know if it's viable via direct operation.

**Comment by gigawhitlocks** [comment]
Is this still relevant? @hickeng

**Comment by hickeng** [comment]
@gigawhitlocks still relevant, just not in plan for the near future - this requires an ESX agent and should be deferred until we have got the VMCI/vSocket communication work in place (that will supply the necessary basics and is higher priority).
