### ISSUE TITLE
Document that vic-machine suggests valid resource pools

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1007]
Per https://github.com/vmware/vic/issues/1004.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1004 was merged in PR https://github.com/vmware/vic/issues/1102.

**Comment by stuclem** [comment]
Added the following to the topic on `vic-machine create` options:

"You specify the `compute-resource` option in the following circumstances:

- A vCenter Server instance includes multiple instances of standalone hosts or clusters, or a mixture of standalone hosts and clusters.
- An ESXi host includes multiple resource pools. 
- You want to deploy the virtual container host to a specific resource pool in your environment. 

If you do not specify the `compute-resource` option and multiple possible resources exist, `vic-machine create` fails and suggests valid targets for `compute-resource` in the failure message. "

@andrewtchin is this OK? Thanks!

**Comment by andrewtchin** [comment]
looks good also ran it by emma 👍

**Comment by stuclem** [comment]
Great, thanks @andrewtchin and @emlin!
