### ISSUE TITLE
Need to support users sending support bundles (logs) in a non-public way.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1013]
When users run into an issue and want to submit logs to assist with debugging, we may need a way to support accepting log/support bundles that have potentially sensitive information that the user may not want to load into a public github issue.

**Comment by mlh78750** [comment]
Adding @mdubya66

**Comment by mdubya66** [comment]
Adding to VIC GA release. Need to get an owner so moving to backlog too. Assigning to @hickeng to start.

**Comment by hickeng** [comment]
@mdubya66 I've no idea how this can be accomplished but GSS level 1/2 support should have a standard process. Is the scope of this including sanitizing log bundles for OSS support usage?
To meet #904 we shouldn't be logging sensitive data anyway - the question is what is sensitive.
I believe @bradmeiseles is talking to GSS currently and may be able to provide a contact.

**Comment by mdubya66** [comment]
With GSS, closing this as will not fix
