### ISSUE TITLE
Support running `tether` standalone, locally, when it isn't `PID 1`

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#102]
To simulate interaction with the `daemon`, we should support being able to run the `tether` and the `daemon` locally.  This means making the tether skip `fork()` via the `rpctool` when it isn't `PID 1`.  This also means we need to implement some kind of IPC mechanism between it and the `daemon` in order to simulate the serial/SSH connection.

**Comment by dougm** [comment]
@fdawg4l with the tether testing provided by PR #518 and issue #480 , do you think we'll still need this?

**Comment by hickeng** [comment]
We can close this as the larger requirements around tether testing have been addressed and #480 covers the integration with model testing.
