### ISSUE TITLE
Document authentication for vic-admin 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1023]
Per https://github.com/vmware/vic/issues/1013

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/2342 for the implementation of authentication in vic-admin.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1013 was closed as won't fix. Changing the scope of this one to match https://github.com/vmware/vic/issues/2342. Moving back to backlog, as https://github.com/vmware/vic/issues/2342 is not in progress yet.

**Comment by stuclem** [comment]
Looks like this is implemented in PR https://github.com/vmware/vic/pull/2645.

**Comment by hickeng** [comment]
FYI #2629 generates a `pfx` client certificate which can be imported into a client browser for certificate based access, or the `cert.pem` and `key.pem` files can be passed to `wget` or `curl` for programmatic download.

**Comment by stuclem** [comment]
The remainder of https://github.com/vmware/vic/issues/2342 is implemented in PR https://github.com/vmware/vic/pull/2691.

**Comment by stuclem** [comment]
This is now addressed in two PRs:

- PR https://github.com/vmware/vic/issues/2705 adds a sign-in page for VIC Admin.
- PR https://github.com/vmware/vic/pull/2691 adds certificate-based authentication for VIC Admin.

PR https://github.com/vmware/vic/pull/2645 was closed in favour of the two PRs above.

**Comment by stuclem** [comment]
PR #2691 was merged then reverted. Certificate-based authentication for VIC Admin is now implemented in PR https://github.com/vmware/vic/issues/2741.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/pull/2741 is now merged.

**Comment by stuclem** [comment]
Authentication of access to VIC Admin using VC credentials is merged in PR https://github.com/vmware/vic/pull/2883.

**Comment by stuclem** [comment]
If your VCH has `TLSVERIFY` enabled, attempting to access VCH Admin results in the following warning (Chrome):

```
This site can’t provide a secure connection
10.153.199.195 didn’t accept your login certificate, or your login certificate may have expired.
Try contacting the system admin.
ERR_BAD_SSL_CLIENT_AUTH_CERT
```

**Comment by stuclem** [comment]
IE:

```
This page can’t be displayed

•Make sure the web address https://vch_address:2378 is correct.
•Look for the page with your search engine.
•Refresh the page in a few minutes.
```
Firefox:

```
Secure Connection Failed

An error occurred during a connection to 10.153.199.195:2378. SSL peer cannot verify your certificate. (Error code: ssl_error_bad_cert_alert)

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by stuclem** [comment]
We need to provide details about how to provide the certificate.

**Comment by stuclem** [comment]
Updated [Access the Administration Portal for a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/access_vicadmin.md) to include uploading the cert as a prereq, if you use TLS verify. Could only get the cert import to work in Firefox, so stated that other browsers don't work. @gigawhitlocks is this OK? Thanks!

@gigawhitlocks says that this behavior will change for GA, in that you will use the vSphere credentials rather than the cert to access the portal. So, move this one back to backlog once approved.

**Comment by mobla** [comment]
Tried cert import steps mentioned in https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/access_vicadmin.md to my Windows7 desktop, but fails with an error "An error occurred during the addition of a certificate to the Trusted Root Certification Authorities store."

**Comment by stuclem** [comment]
Hi @mobla,

Apologies for the delayed response. At what stage did you get this error?

Thanks

**Comment by mobla** [comment]
@stuclem: When importing the CA cert (.pfx) generated during VCH creation into my browser (Windows7 and Firefox browser v50.0)

![image](https://cloud.githubusercontent.com/assets/3538999/20403062/230099ae-acb4-11e6-82a2-70223e1cbea2.png)

Later tried CURL option and got "alert bad certificate". OpenSSL cert read/verify is ok.

root@photon-lJUA39j42 [ ~ ]# curl -k -key=./vic/vic/VCHTLS1/key.pem -cert=./vic/vic/VCHTLS1/cert.pem https://wdc-qead-dhcp-10-139-23-239.eng.vmware.com:2378/logs/vicadmin.log
curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
