### ISSUE TITLE
Improper error message on unknown image during create

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1036]
Docker returns:
```
docker create fakeimage
Unable to find image 'fakeimage:latest' locally
Pulling repository docker.io/library/fakeimage
Error: image library/fakeimage not found
```
VIC returns:
```
docker -H 192.168.254.215:2375 create fakeimage
Error response from daemon: Container look up failed
```

**Comment by hickeng** [comment]
This could well be the reason we have issues with #474 and #354

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-4-Docker-Create.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by jzt** [comment]
@mhagen-vmware is it only the error message that we are interested in?

**Comment by mhagen-vmware** [comment]
For the original issue, yes.  Not sure how it relates to the issues that @hickeng  mentioned.
