### ISSUE TITLE
Refactor Port Layer

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1043]
The execution part of the Port Layer is a somewhat opaque piece of code that many of us depend on. Any operation that has anything to do with container life-cycle or querying container state goes through the Port Layer. The code as it currently stands is confusing. This is for the most part because it seems like the original design intentions were not necessarily adhered to; and with no public interface or documentation, it's difficult for anyone not intimately familiar with it to figure out how to invoke it or modify it. In addition to that, I don't believe that enough consideration has been placed on caching, locking, logging and other fundamentals.

Given that this code is at the core of what we do, I propose to refactor it as a matter of priority with the following first and second order goals:

**First order goals**

1) The Port Layer should be container-engine agnostic. There should be no references to Docker data structures, APIs, packages or anything in the code.

2) It should have a golang interface that is well-commented and explains how a client should use it

3) Dependencies should have well-defined interfaces. The dependency on govmomi is a good example; the architecture document shows a govmomi gateway which should be represented by an interface. Scheduling is another example - if we have a dumb scheduler, it should be pluggable

4) We need to agree on a model of how a client has conversations with the PL and make sure that it's enforced. The original intent for a Create -> Modify -> Commit or Get -> Modify -> Commit got lost along the way. There are some significant benefits to this model, described as goals (5) (11) and (8). The downside is that the model is unintuitive unless it's well-documented.

5) The Port Layer must minimize the number of round-trips to the govmomi gateway. Caching and events are a critical part of how this should be done

6) It should have a well-defined and well-documented caching policy

7) It should be optimized for concurrent operations. The bottleneck for any calls to the PL should always be the vmomi gateway. In order to meet goal (5), there may need to be some bulk calls (deleting 100 containers will likely be more efficiently achieved with a single call to the govmomi gateway than 100 goroutines trying to delete 1. That said, if the single operation is likely to timeout or cause problems, the latter solution may actually be preferable). The only way to determine this is through experimentation.

8) The way in which concurrent operations are executed on the PL should be clearly defined, because it has an impact on the caching and locking. Eg. Should it be possible for more than one port layer client to make a modification to the same container. In particular, how should a client behave if a is in a transitional state? Client A starts a container and blocks until it's finished. Client B wants to do something on that container. Should B also be blocked? What if it's just querying state?

9) We should be able to shut down and restart the PL and it should come back up and rebuild all of its internal state quickly and efficiently via the vmomi gateway.

10) We need to decide which state changes performed by the VC client need to be reflected in the port layer. This is not black and white. Even if we don't officially support this behavior, if you power off a containerVM, this should be reflected in the PL.

**Second order goals**

11) We should be able to distribute each part of the port layer a a separate service if we want to. This is not essential, but would be a better "12-factor" approach to what is basically each namespace.

**Asserting the goals have been met**

1) I have spec'd up a trivial container engine (TCE #1044) that only makes use of the execution part of the port layer. It has been designed with no assumptions about the port layer API in mind and we need to make sure that the PL API is adaptable enough to serve the needs of this container engine. It will also be a great example of how this lower layer can be integrated into 3rd party products.

2) The interface should be exportable via RPC and a client should be able to drive it directly. This will help significantly with functional testing of the Port Layer particularly when combined with TCE as a client and vcsim on the back end.

3) The interfaces need to be well-designed and flexible enough to meet the needs of the product

4) This needs to be spec'd up and agreed to. It would also be very helpful to model some common scenarios. This is where TCE can really help.

5) This cuts across the design of the gateway API, the design of the PL API and the design of the caching. The way to assert it though is simple; if there is ever more than 2 round-trips to govmomi for any single PL call, we need to investigate whether it's really necessary.

6) We should have an Issue in which the caching policy is discussed, specified and agreed upon. I already have a proposal in #1000 for this.

7/8) Again, these are cross-cutting considerations. For each PL call, we need to consider the following:
- What state pre-conditions need to be met?
- Is there anything which might cause us to need to block?
- What data needs to be locked in order for us to read/write state and how long are we holding the lock for
  The vcsim will massively help in designing tests which assert common scnearios

9) TCE and vcsim should massively help in testing for and asserting that this works

10) This should be a separate issue and discussion point. We should again easily be able to assert these conditions with vcsim, but only if it implements an events interface.

11) This may require dummy stub/network storage services for function testing and would have a wider scope on those APIs. For now this should be considered unnecessarily disruptive, but we should be designing for it

**Comment by hickeng** [comment]
#82 was the initial issue for this - closing it as this has a much more fleshed out set of requirements.

**Comment by corrieb** [comment]
I've set the estimate for this at 8. I think with 8 solid days of work, this could be done with a reasonable degree of testing. I plan to re-start work on this ASAP and will post updates to this epic as I go.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mdubya66** [comment]
I'm marking this as high. Many upstream efforts depend on this getting completed sooner than later.
