### ISSUE TITLE
Setup CI environment in the canadian datacenter

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1052]
As an engineer, I need a reliable CI system that can be run all any code commits/merges to verify that no regressions have occurred.

As a quality engineer, I need a CI system that is easily manageable and is simple to fix/maintain/add new tests to.

We need 1 server that can act as a test system with ESXi running on it so that we can install the VIC appliance on it.

We need 1 server that can act as the test scheduler/executor.  It needs to have network access to the ESXi server and any VMs that the ESXi server creates in order to be able to run tests off of the VIC appliance installed and containers that are created.

The test scheduler/executor server also needs to have a public IP address so that we can hook it into github to poll for repo changes as well as publish results and view the results of testing easily.

**Comment by mdubya66** [comment]
Is this just for the test portion. I thought the drone setup was bigger than that and that we are moving the entire ci.vmware.run to it?

Also, does it need a public IP to connect to github, that seems wrong. For the reporting, yes. but let's get real specific on the network connectivity.

**Comment by mhagen-vmware** [comment]
this is done and working now
