### ISSUE TITLE
Persistent storage of container output

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#106]
We need a way to persistently store container output that is not tied to the VCH appliance VM.
We could make use of the VMCI/"serial-to-file-on-host" mechanisms to log directly to the datastore, but the question is could we download it as stream direct from the host, as described here: http://www.virtuallyghetto.com/2014/06/how-to-efficiently-transfer-files-to-datastore-in-vcenter-using-the-vsphere-api.html

The reasoning for doing this via means other than the direct tty interaction mechanism is so that logs are preserved and updated even when the VCH is down for maintanence.

**Comment by dougm** [comment]
Current containers use serial to host for logging to the datastore.

**Comment by hickeng** [comment]
@dougm do you know if a streaming read of a file from a datastore is viable? This is now directly applicable to #433. There is no log persistence for `docker exec` containers at this point.

**Comment by dougm** [comment]
iirc, the datastore http interface always sends a Content-Length.  I can see if there's a way to use chunked encoding, but haven't seen it in the past here.

**Comment by hickeng** [comment]
closing in favour of #433 which is to obtain the persisted logs.
