### ISSUE TITLE
Configure drone workers in drone-server

### ISSUE THREAD

**Issue by casualjim** [vmware/vic#1069]

**Comment by mdubya66** [comment]
ivan, would it be possible to document each step? it could be useful when things fall down in the future. doing so in the issues for each should be good. what commands you ran, setup that was needed and potentially any output

**Comment by casualjim** [comment]
on some machine configured for govc to talk to the esx running a drone worker 
```
govc vm.create -c 2 -m 4096 -net.adapter=vmxnet3 -disk=ubuntu-base -g=ubuntu64Guest drone-worker-$RANDOM
```

get a vpn going and get to the reachstacker repo in the repo root:

```
ansible-playbook -i '<private ip of new host>,' --vault-password-file ~/Private/reachstacker-vault.txt ansible/common.yml
```

The traling comma in the -i parameter is important
