### ISSUE TITLE
Implement the vic-machine env command.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1085]
Today we output something like this during install of the VCH:

INFO[2016-06-13T18:18:16Z] Connect to docker:
INFO[2016-06-13T18:18:16Z] docker -H 10.143.2.176:2376 --tls --tlscert='./ZzZ-cert.pem' --tlskey='./ZzZ-key.pem' info 

We should add something like this to help with usability after install:
INFO[2016-06-13T18:18:16Z] Connect to docker:
INFO[2016-06-13T18:18:16Z] docker -H 10.143.2.176:2376 --tls --tlscert='./ZzZ-cert.pem' --tlskey='./ZzZ-key.pem' info
INFO[2016-06-13T18:18:16Z] or set DOCKER_OPTS with the following line:
INFO[2016-06-13T18:18:16Z] DOCKER_OPTS="-H 10.143.2.176:2376 --tls --tlscert='./ZzZ-cert.pem' --tlskey='./ZzZ-key.pem'"

**Comment by caglar10ur** [comment]
I personally prefer creating a file with DOCKER_OPTS so that we can source it and use as we want (like openstack)

**Comment by mlh78750** [comment]
I think we could do both. I like the idea of writing a file that can be sourced. And @emlin points out we could handle platform differences with the printed lines or the files as well.

**Comment by mlh78750** [comment]
There is an argument to be made to print all the different env source stuff regardless of platform vic-machine was run upon. Admin might make VCH from windows and pass that INFO …. page to the developer who is on linux via an email

**Comment by mlh78750** [comment]
And maybe this is just a matter of implementing vic-machine env similar to docker-machine env.

**Comment by mlh78750** [comment]
After thinking about this a bit, I think we can still print DOCKER_OPTS in the INFO lines, but the use that folks may be used to is to just use the "env" command for vic-machine just like docker-machine currently works.

**Comment by hickeng** [comment]
@mlh78750 we used to always have the DOCKER_HOST printed, and we still do for non-tls. No idea why this was changed. I've restored the DOCKER_HOST output for TLS in #1127 but it doesn't do DOCKER_OPTS.
Bear in mind that the docker-machine workflow is assuming that it's the user running it, whereas we're assuming the opposite. A file that can be sourced is convenient - we should definitely do that to support shell usage of a freshly provisioned VCH which should be useful in our tests.
We should also print those environment variables.

For a viadmin to pass to a user however we should provide a bundle.
That can include the file to source, but should also include certificates - preferably not the same ones used for TLS on the appliance, but another pair generated from the same CA - that way we can provide for -tlsverify

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mdubya66** [comment]
1.1 request for UX improvements in vic-machine. medium

**Comment by emlin** [comment]
@mdubya66 what's the UX request for this?

**Comment by zjs** [comment]
`vic-machine create` generates an environment file and `vic-machine inspect` allows easy access to this information subsequently. Together, this is sufficient for now.
