### ISSUE TITLE
Restarting a stopped container fails with "already bound"

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1086]
Once a container has stopped due to exit of the main container process (as opposed to via an explicit stop command), restarting that container will fail with "already bound". Container can still be started successfully directly via UI or govc.
To work around this call stop on the container - this will return an error currently, but will allow a subsequent start operation to succeed:

work around:
```
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls start -ai eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
Error response from daemon: container eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c already bound
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls stop eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
Error response from daemon: server error from portlayer
Error: failed to stop containers: [eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c]
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls start  eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
vagrant@devbox:~/vic/bin$
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls attach eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
/ # 
``` 

Error case:
```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z create -it golang
b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z start b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z attach b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
root@b372c1a48391:/go#
root@b372c1a48391:/go# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  4.4  0.0   4336   680 tty1     Ss+  18:37   0:01 /bin/sh /.tether/tether
[...]root       209  1.4  0.7 225916 14792 tty1     Sl+  18:37   0:00 /.tether/tether-bin
root       214  0.0  0.1  20248  3200 pts/0    Ss   18:37   0:00 /bin/bash
root       219  0.0  0.0  17500  2052 pts/0    R+   18:37   0:00 ps aux
root@b372c1a48391:/go# exit

[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z start b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
Error response from daemon: container b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07 already bound
Error: failed to start containers: b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
```

started to observe after https://github.com/vmware/vic/pull/1029

**Comment by hmahmood** [comment]
Bind and Unbind container should be idempotent operations.

**Comment by hickeng** [comment]
@hasan Agreed they should be - do we even call unbind on container exit at the moment? I'm not sure we always know when a container exits without the vsphere event stream.

If we don't unbind then we're going to rapidly hit address space exhaustion until we do and that's an issue that must be documented. @stuclem

**Comment by hmahmood** [comment]
We do an unbind on a container stop, not exit. Yes, we need that event stream to be able to properly release ip addresses.

**Comment by hickeng** [comment]
@mdubya66 @karthik-narayan I don't think addressing this is viable in a TP3 timeframe. While we may have the VC event stream if @cgtexmex gets the time I don't think we'll have the time to glue it into the networkPL.

**Comment by mdubya66** [comment]
Moving to onsite milestone. this depends on future work.

**Comment by corrieb** [comment]
Will need to doc for TP3. Fix for onsite

**Comment by stuclem** [comment]
@corrieb, for TP3 we have this as a known issue in the release notes.

**Comment by corrieb** [comment]
This should be a high priority for onsite IMHO as it's a highly visible issue that folks are likely to fall over.

**Comment by corrieb** [comment]
This should be a P0 candidate. It's been flagged by the Bellevue team as an issue and we identified it in mid-July as a significant UX problem

**Comment by mdubya66** [comment]
making a p0 as this is more prevalent that originally thought

**Comment by mdubya66** [comment]
Required by Admiral

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
