### ISSUE TITLE
Docker API Server: Cleanup strings handling

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1099]
We're currently adding in strings ad hoc, much like how Docker does it.  This is bad practice.  We should look into handling strings in a more structured way.

**Comment by hickeng** [comment]
@sflxn can you give an example? We have a message catalogue mechanism that should be used for most user facing strings - this includes the error messages returned from the Docker API - they are a soft part of the API as people _will_ search for specific strings in command output.

**Comment by mdubya66** [comment]
making low. is this still needed? @sflxn
