### ISSUE TITLE
vic-machine install-ui

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#1101]
This describes the deployment process for installing the UI plugin via `vic-machine`

### Overview
* User downloads VIC tarball and successfully runs `vic-machine create`
    * Tarball includes VIC UI plugin server container and VIC UI plugin zip
    * Plugin server container is added to imagec
* User runs `vic-machine install-ui`
    * Run a plugin server container that serves the VIC UI plugin zip over HTTP
    * Obtain the IP of the container
    * Generate the plugin manifest with the URL of the VIC UI plugin on the plugin server container
    * Upload the manifest to vSphere (registers the plugin)
    * Trigger the plugin install by logging into the UI

### Requirements
* Must be able to install the UI plugin without internet access (many customers do not have internet access in their datacenter)

### Known work
* Translate plugin registration (jar exists) to govmomi commands

### Research
* How to distribute a container image in the VIC tarball
* How to put container image directly into imagec
* How to get vic-machine to login to the UI to trigger plugin install

### Example command
```vic-machine install-ui --target <vSphere IP> --user <username> --password <password> --vch-ip <VCH IP>```

**Comment by hickeng** [comment]
What was the reasoning behind using a webserver to do the deployment rather than provisioning the jar directly to vCenter - I know that mechanism existed in 5.0/5.1/5.5 as it's what EM4J used; is it now deprecated?

**Comment by hickeng** [comment]
If the webserver doesn't need to be there continuously we can embed an http server in vic-machine (at it's most basic it's a literal one line change) - we already require that there's a route between vic-machine and VC.

**Comment by jzt** [comment]
> Plugin server container is added to imagec

vic-machine would use the swagger portlayer client to call the portlayer's `WriteImage()` function here and have it added to the image store.

Example:  https://github.com/vmware/vic/blob/master/cmd/imagec/storage.go#L124

**Comment by hickeng** [comment]
@jzt @andrewtchin what actually occurs in the `plugin server container` - I've seen the various web portal plugin deployment pages, but what is the actual detail workflow there once a user has specified the IP and credentials for VC?

**Comment by emlin** [comment]
@hickeng A few comments here.
>What was the reasoning behind using a webserver to do the deployment rather than provisioning the jar directly to vCenter - I know that mechanism existed in 5.0/5.1/5.5 as it's what EM4J used; is it now deprecated?
Josh Kim mentioned one solution not to use http server for plugin download. But that is to copy plugin zip file directly to virgo server plugin cache.
That means we need to scp the file to one specific directory of local file system. The concern of here is that the VC can be deployed to different OS, e.g. Windows, that means SCP does not work, and probably the file directory is not fixed. And we don't know if there are other different deployment, which has different file system, with different file permissions setting.
So we decided not go to with that option.

**Comment by emlin** [comment]
> If the webserver doesn't need to be there continuously we can embed an http server in vic-machine (at it's most basic it's a literal one line change) - we already require that there's a route between vic-machine and VC.

We didn't think about this option. Are you talking about a service vic-machine? Does that mean user need to launch one process in their own env, to run vic-machine?

**Comment by emlin** [comment]
>@jzt @andrewtchin what actually occurs in the plugin server container - I've seen the various web portal plugin deployment pages, but what is the actual detail workflow there once a user has specified the IP and credentials for VC?

Sorry for we didn't update any document for plugin installation yet. We had a meeting yesterday with @karthik-narayan @mdubya66 and @jooskim, @jak-atx  to discuss the plugin installation options, and we decided not to go with cache file update option, which should be described by Josh Kim in the document, I think.
Currently, we only have a roughly idea for how to do that. Here is the workflow.
- vic-machine create at least one VCH
- vic-machine install ui-plugin, which is one separate command
--vic-machine call port-layer-server api to upload local ui plugin image, so imagec will not talk with docker hub or any other public docker registry, cause customer might not have internet connection.
-- vic-machine call port-layer-server api, to create container with the uploaded image, so there will have a https server launched in that container.
-- vic-machine call VC to register the UI plugin, which will have previously created container endpoint as the plugin zip file download URL.
-- At this time, we still cannot stop the container VM, cause UI does not download zip file, until there is UI user login to VC UI.

Personally, I think this workflow looks reasonable, and since we have port-layer-server api, so we don't have to talk with docker hub, and also don't have to package docker CLI.
But we still didn't validate if the above functions are actually supported. Sorry for planed to talk with you for it, @hickeng, but still didn't get chance.

**Comment by jooskim** [comment]
Just to add another note here in the deployment process assuming the web server is up and serving UI bundle files, the server needs to be alive until the user hits the Virgo server (Web Client server) that will get the contents from the other server. I need to see if authenticating via curl is possible. If not, we need to make sure the server does not go away until the plugin is deployed.

Below I attached the document I used in yesterday's meeting.

[vic_ui_plugin_deployment.docx](https://github.com/vmware/vic/files/316328/vic_ui_plugin_deployment.docx)

**Comment by jooskim** [comment]
Apparently being able to log in via a simple curl command means a lot of security problems. Instead vSphere Web Client SDK allows for logging in through [vSphere Management API - SessionManager object](http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.SessionManager.html)

**Comment by emlin** [comment]
I think this is for VC API login only.

**Comment by jooskim** [comment]
I thought that would be sufficient, as long as what we need is to trigger the Extension check, but it may not be doing more than returning the UserSession object. I'll ask the SDK team what the exact steps are that trigger the extension check. Meanwhile I just found another relevant page but let me first figure out the extension check stuff.

**Comment by andrewtchin** [comment]
> If the webserver doesn't need to be there continuously we can embed an http server in vic-machine (at it's most basic it's a literal one line change) - we already require that there's a route between vic-machine and VC.

That's an option I considered, but would depend on our ability to trigger the extension check so that the plugin zip is downloaded from the server we're running before `vic-machine install-ui` terminates along with the server. If we had a container running the server we could just keep that running. 

I would definitely prefer if we had a way to kick the extension check so we don't have to wait for the user to login.

**Comment by emlin** [comment]
OKey, so this is one instant web server, just running during vic-machine install-ui. If we can solve the plugin download issue from VC web server, this one is definitely a better choice.

**Comment by jooskim** [comment]
Just talked Laurent from the serenity team and there is a method to check (and download new) plugins, but that's a private method. I need to figure this out with Petar in Sofia.

**Comment by hickeng** [comment]
@jooskim wouldn't be the first private API method we've used, although none of them are in the VIC code currently.

@emma @andrewtchin Does that mean it's viable to have vic.vmware.com host the plugin for example (in the case where they have internet connectivity)?

**Comment by jooskim** [comment]
Bad news. I just heard that their internal API would not be applicable after they reviewed our use case.

**Comment by hickeng** [comment]
@jooskim does that mean it's not part of the vmodl sdk? or simply a private part of it?

**Comment by jooskim** [comment]
@hickeng It's not part of the vmodl SDK. I didn't get much detail except that another plugin has to be installed. Having to install a prerequisite plugin to automate one aspect of the UI installation process kills its own purpose.

**Comment by hickeng** [comment]
@jooskim concur.
@corrieb I really dislike the idea of shipping a container image to act as our installer for the UI. While I also dislike the idea of adding a web server into the appliance to do this work I dislike it less. I'm really unsure about embedded a webserver into the installer - I think that could actually be the cleanest, but haven't spent enough time thinking about it.

It's starting to seem as though a direct upload of the files is actually the least complex - with the proviso that someone has to enable scp on the appliance. Do you have an instinct?

**Comment by hickeng** [comment]
@emlin @andrewtchin I can see you've been making most of the comments here from the vic-machine side. Can you assign this to yourself if you own it - it's with emma by default for vic-machine work currently.
Please grab some time with me tomorrow or tuesday so we can go over this in depth and settle on an approach. We will produce the outline of a design doc covering the chosen approach (noting the discussion here as to alternatives) and I'll ask you to add detail prior to starting detail work.

**Comment by corrieb** [comment]
This has been sitting for quite a while now. Sounds like this is not going to be an onsite deliverable, unless we're clear on what needs to happen and it can happen quickly.

**Comment by jooskim** [comment]
This issue is still active, and is nearing completion. As for plugin registration with VC see issue #1336 and #1513 for UI deliverables including portlet source code and installers.

**Comment by mdubya66** [comment]
GA feature from SSOD
