### ISSUE TITLE
Crash in session_test.go

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1108]
Line is defer session.Logout(ctx). Seems like session can be nil in the case of an error

+ go test -v -covermode=count -coverprofile=/drone/src/github.com/vmware/vic/.cover/github.com-vmware-vic-pkg-vsphere-session.cover github.com/vmware/vic/pkg/vsphere/session
=== RUN   TestSessionDefaults
--- FAIL: TestSessionDefaults (0.00s)
	session_test.go:37: Failed to connect to https://$$VIC_ESX_TEST_URL/sdk: Post https://$$VIC_ESX_TEST_URL/sdk: dial tcp: lookup $$VIC_ESX_TEST_URL: invalid domain name
	session_test.go:39: Failed to connect to https://$$VIC_ESX_TEST_URL/sdk: Post https://$$VIC_ESX_TEST_URL/sdk: dial tcp: lookup $$VIC_ESX_TEST_URL: invalid domain name
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4894f8]

goroutine 5 [running]:
panic(0xee2da0, 0xc820012190)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc82007a090)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0xee2da0, 0xc820012190)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/pkg/vsphere/session.TestSessionDefaults(0xc82007a090)
	/drone/src/github.com/vmware/vic/pkg/vsphere/session/session_test.go:44 +0x368
testing.tRunner(0xc82007a090, 0x197b2c0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
exit status 2
FAIL	github.com/vmware/vic/pkg/vsphere/session	0.012s
make: *** [test] Error 1
Makefile:201: recipe for target 'test' failed
[info] build failed (exit code 2)

**Comment by hickeng** [comment]
@corrieb you wanted something small to get you back into the coding, right? ;)

**Comment by anchal-agrawal** [comment]
Closing as this was fixed by @corrieb in #1461.
