### ISSUE TITLE
Failed to write to image store: context deadline exceeded

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1116]
This was one of the failures on the 151 E2E build (see #1117 for potential related issue):
alpine: Pulling from library/nginx
a3ed95caeb02: Pulling fs layer
d0ca440e8637: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Pulling fs layer
e8514e64aa40: Pulling fs layer
1913fe8f0af9: Pulling fs layer
0a07e46b6020: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
1913fe8f0af9: Verifying Checksum
1913fe8f0af9: Download complete
0a07e46b6020: Verifying Checksum
0a07e46b6020: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
d0ca440e8637: Verifying Checksum
d0ca440e8637: Download complete
e8514e64aa40: Verifying Checksum
e8514e64aa40: Download complete
d0ca440e8637: Pull complete
a3ed95caeb02: Pull complete
a3ed95caeb02: Pull complete
a3ed95caeb02: Pull complete
a3ed95caeb02: Pull complete
e8514e64aa40: Pull complete
1913fe8f0af9: Pull complete
Failed to write to image store: context deadline exceeded

Unfortunately, we don't have much more information at this time, but at a minimum we need to improve that error message.

**Comment by mhagen-vmware** [comment]
The test log:
[log.html.zip](https://github.com/vmware/vic/files/318361/log.html.zip)

**Comment by mhagen-vmware** [comment]
Additional information:
Pulling different images immediately before and after succeeded as well.

**Comment by hickeng** [comment]
@mhagen-vmware we're going to need the log bundles to diagnose any failures like this - please add the log collection to the Robot framework for all tests.

**Comment by mdubya66** [comment]
@mhagen-vmware please retest this to see if it re-occurs.

**Comment by mhagen-vmware** [comment]
Closing as this hasn't been seen in a while, I believe this was fixed with #1191
