### ISSUE TITLE
Failed to write image store: Cannot complete the operation because the file or folder already exists

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1117]
This is the other failure from build 151 on E2E (see #1116 for the other, potentially related bug):
alpine: Pulling from library/nginx
d0ca440e8637: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
e8514e64aa40: Already exists
1913fe8f0af9: Already exists
a3ed95caeb02: Pulling fs layer
0a07e46b6020: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
0a07e46b6020: Verifying Checksum
0a07e46b6020: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc8200f7210 Message:ServerFaultCode: Cannot complete the operation because the file or folder [datastore1] VIC/564d2c23-cd7d-5c2d-94e7-0cd594a6de22/deb3c8163916314905ff20306d1b3c3de33fd6c95b34be6b1451d4280a539483 already exists}

**Comment by mhagen-vmware** [comment]
The test log:
[log.html.zip](https://github.com/vmware/vic/files/318360/log.html.zip)

**Comment by mhagen-vmware** [comment]
Additional information:
Pulling different images immediately before and after succeeded as well.

**Comment by mhagen-vmware** [comment]
[VCH-2328-container-logs.tar.gz](https://github.com/vmware/vic/files/330225/VCH-2328-container-logs.tar.gz)

**Comment by mhagen-vmware** [comment]
@fdawg4l

**Comment by hickeng** [comment]
@fdawg4l The logs in the previous comment show a failure pulling alpine (from log.html):
```
Using default tag: latest
latest: Pulling from library/mongo
a3ed95caeb02: Pulling fs layer
8ceedfe606fc: Pulling fs layer
a3ed95caeb02: Pulling fs layer
de56a622d4ac: Pulling fs layer
6f6965220a2d: Pulling fs layer
a3ed95caeb02: Pulling fs layer
290580b9cb91: Pulling fs layer
a3ed95caeb02: Pulling fs layer
74518025c1d4: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Pulling fs layer
3be42c3d566b: Pulling fs layer
1f3f56933a51: Pulling fs layer
9a2e0c784afa: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a600166aa315: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Pulling fs layer
<snip>
8ceedfe606fc: Pull complete
a3ed95caeb02: Pull complete
de56a622d4ac: Pull complete
6f6965220a2d: Pull complete
a3ed95caeb02: Pull complete
290580b9cb91: Pull complete
a3ed95caeb02: Pull complete
74518025c1d4: Pull complete
a3ed95caeb02: Pull complete
a3ed95caeb02: Pull complete
3be42c3d566b: Pull complete
1f3f56933a51: Pull complete
9a2e0c784afa: Pull complete
a3ed95caeb02: Pull complete
a600166aa315: Pull complete
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc82033c050 Message:Operation failed: File /vmfs/volumes/5757bac7-a013ba9c-9e33-000c2954b342/VIC/parentMap.tmp was not found}
```

then subsequent retries show:
```
Using default tag: latest
latest: Pulling from library/mongo
8ceedfe606fc: Already exists
a3ed95caeb02: Already exists
de56a622d4ac: Already exists
6f6965220a2d: Already exists
a3ed95caeb02: Already exists
290580b9cb91: Already exists
a3ed95caeb02: Already exists
74518025c1d4: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
3be42c3d566b: Already exists
1f3f56933a51: Already exists
9a2e0c784afa: Already exists
a3ed95caeb02: Already exists
a600166aa315: Already exists
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc8201426a0 Message:ServerFaultCode: Cannot complete the operation because the file or folder [datastore1] VIC/564d9f95-c588-f5a9-dba4-17c5f78eb422/images/95480a0fc5baccf094d2cfbb3f98bac80e17fc1054a4c3ddc0223dc463b6a2dc already exists}
```

@caglar10ur @jzt Any idea why we've got what looks like multiple pulls of a3ed95caeb02? Is that just an imagec status reporting quirk or an actual repetition? Will push an update to restore imagec.log by default.

**Comment by caglar10ur** [comment]
a3ed95caeb02 could be the scratch layer's id so any step that doesn't change fs layer should use that.I'm guessing that's why we have multiple

**Comment by jzt** [comment]
`a3ed` is the blobsum (sha256 of the compressed empty 1024-byte tgz) of an empty layer (one that, as @caglar10ur said does not alter the filesystem in any way). Many images have several instances of that in their layers list. Although I believe the `scratch` layer has id `deadbeef`. @fdawg4l?

**Comment by fdawg4l** [comment]
Is this still happening after @emlin's change this morning (https://github.com/vmware/vic/pull/1191)?

If someone can get me recent logs (after the change pushed above) exhibitting the same symptoms, I'll take a look.

@jzt `deadbeef` isn't used anywhere in the storage code.  Never *ever* use deadbeef in production code anywhere.  It's too likely to have a collision somewhere because it's such a frequently used MAGIC value.
