### ISSUE TITLE
Docker API: Docker image tag

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1120]
Implement image tagging support:

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#tag-an-image-into-a-repository

Was originally integration test failure issue.

> Another requirement to implement if we want to be able to run docker integration tests.

**Comment by hickeng** [comment]
@mhagen-vmware this isn't likely to be there for GA and definitely not in the closer term. What percentage of the tests are not viable if we don't have this implemented?

**Comment by mhagen-vmware** [comment]
Unfortunately, I can't tell for the time being.  The full suite does not execute, just a chunk of it because it times out due to our myriad of failures.  As we get closer to a fuller implementation I think I can give you a fuller picture.

**Comment by jzt** [comment]
We may potentially need to explicitly test for the issue in #3692 in the event that there is more going on than just the client automatically attempting to tag an image. I have a feeling that there isn't, but it would be nice to make sure.

**Comment by mhagen-vmware** [comment]
lgtm
