### ISSUE TITLE
Port Layer: Create swagger definitions for getting container metadata and list of containers

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1122]
We need some portlayer definitions that allows us to get container metadata (for docker inspect container) and get a list of containers (for docker ps).

related to #798 and #388

**Comment by sflxn** [comment]
@cgtexmex and I were discussing how we're going to pass data back and forth.  With image metadata, we stored this data as blobs in the storage port layer.  For container metadata, that doesn't appear to be appropriate.  Most of this data are runtime data so the port layer must interact with this data.  We are thinking it's best to create operations very similar to what we currently have with containers and scope.  In other words, we define operations such as GET /containers/{handle}/info that returns specific attributes about the container.  The personality server would query this, and build up the appropriate docker structure to return to the caller.

**Comment by hickeng** [comment]
@sflxn please talk to @corrieb in the office tomorrow - he and I just wrapped up a 2h call about the exec/query portions of the API. Not so much the details around the content of the structure, but the separation of data with different TTLs. @corrieb said he's going to push updates as a write up but in person will help.

**Comment by sflxn** [comment]
@hickeng I just chatted with @corrieb.  He doesn't want us to wait for the port layer refactoring.  It's not optimal, but once he's done, we'll have to refactor again, but at least it won't hold up progress.  I agree with this path.  Container inspect and docker ps are really important for just usability, docker integration tests, and the efforts by the performance team.
