### ISSUE TITLE
Attach should time out if connection cannot be established

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1128]
Just tried attaching to a container without having appropriate firewall config (2377 was not open on ESX for outbound). The attach hung - as can been seen from the timestamps for the port-layer there was a significant period of time between the attempt and the success (after I corrected the firewall config).

We see context deadlines expiring for resize, but not for the initial attach. I know that the attach deadline is set high on the port layer (and that we need to figure out with @casualjim how to make it infinite), but we need to look at having separate timeouts for the HTTP 200 response to the attach (call it 15sec) vs the consumption of the body (until closed).

From port-layer.log:
```
time="2016-06-17T07:32:17Z" level=info msg="Attempting to get ssh session for container f8db066558f2f1220fc1f01c74a1742f0b85dd7c893b56455d271e4fdbb56d55 stdin" 
time="2016-06-17T07:35:09Z" level=info msg="Received incoming connection" 
```

From personality:
```
time="2016-06-17T07:31:41Z" level=info msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] ContainerCreate" 
time="2016-06-17T07:31:41Z" level=info msg="config.Config = &{Hostname: Domainname: User: AttachStdin:true AttachStdout:true AttachStderr:true ExposedPorts:map[] PublishService: Tty:true OpenStdin:true StdinOnce:true Env:[] Cmd:[/bin/ash] ArgsEscaped:false Image:busybox Volumes:map[] WorkingDir: Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal:}" 
time="2016-06-17T07:31:44Z" level=info msg="v1 = {ID:437595becdebaaaf3a4fc3db02c59a980f955dee825c153308c670610bb694e1 Config:{Hostname:156e10b83429 Domainname: User: AttachStdin:false AttachStdout:false AttachStderr:false ExposedPorts:map[] PublishService: Tty:false OpenStdin:false StdinOnce:false Env:[] Cmd:[sh] ArgsEscaped:false Image:56ed16bd6310cca65920c653a9bb22de6b235990dcaa1742ff839867aed730e5 Volumes:map[] WorkingDir: Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal:}}" 
time="2016-06-17T07:31:44Z" level=info msg="ContainerCreate config' = {Name:condescending_boyd Config:0xc820144c60 HostConfig:0xc820336a80 NetworkingConfig:0xc82001c668 AdjustCPUShares:false}" 
time="2016-06-17T07:31:44Z" level=info msg="dockerContainerCreateParamsToPortlayer = &{Args:[] Env:[TERM=xterm] Image:0xc8204acca0 ImageStore:0xc8204acce0 Name:0xc8204accb0 NetworkDisabled:0xc8204acbf8 Path:0xc8204accc0 Tty:0xc8204acbf9 WorkingDir:0xc8204accf0}" 
time="2016-06-17T07:31:44Z" level=info msg="container.ContainerCreate succeeded.  Returning container handle {ec8d26bb3f3dd7bc4866f9dbc5e265e7 f8db066558f2f1220fc1f01c74a1742f0b85dd7c893b56455d271e4fdbb56d55}" 
time="2016-06-17T07:31:44Z" level=info msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [2.834317626s] ContainerCreate" 
time="2016-06-17T07:31:44Z" level=info msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] ContainerAttach" 
time="2016-06-17T07:31:44Z" level=info msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] ContainerStart" 
time="2016-06-17T07:31:56Z" level=info msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] [11.869013407s] ContainerStart" 
time="2016-06-17T07:31:56Z" level=info msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerResize] ContainerResize" 
time="2016-06-17T07:32:26Z" level=info msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerResize] [30.000596954s] ContainerResize" 
time="2016-06-17T07:32:26Z" level=error msg="Handler for POST /v1.23/containers/f8db066558f2f1220fc1f01c74a1742f0b85dd7c893b56455d271e4fdbb56d55/resize returned error: Unknown error from the interaction port layer: context deadline exceeded" 
```

@sflxn for comments

**Comment by casualjim** [comment]
you can set a transport on the runtime with a connect timeout configured, something like this

```go
func Init(portLayerAddr string) error {
	_, _, err := net.SplitHostPort(portLayerAddr)
	if err != nil {
		return err
	}

	t := httptransport.New(portLayerAddr, "/", []string{"http"})
	t.Transport = &http.Transport{Dial: connectTimeoutDialer(10 * time.Second)}
	portLayerClient = client.New(t, nil)
	portLayerServerAddr = portLayerAddr
	return nil
}

func connectTimeoutDialer(timeout time.Duration) func(net, addr string) (c net.Conn, err error) {
	return func(netw, addr string) (net.Conn, error) {
		conn, err := net.DialTimeout(netw, addr, timeout)
		if err != nil {
			return nil, err
		}
		return conn, nil
	}
}
```

If you need this on a per request basis we can come up with a solution
The simplest solution would be to just instantiate another client for requests that deviate from the default. These clients are fairly cheap to create.  But that's just one possible solution, there are many others

**Comment by sflxn** [comment]
@casualjim What @hickeng is saying is that on a request, the time we wait to get an HTTP status is one timeout and then their is the "timeout" for how long we hold onto the connection.  Are you saying we set a timeout on the connection for the client and shorten the context timeout for the request?  We're already creating a client for each stream as the requests are blocking.  I can add this timeout to the transport if it resolves our issue.

**Comment by casualjim** [comment]
What I have here is a timeout (by default there is none) for establishing a connection. So a separate one from the request timeout.  There are typically 2 timeouts you need a read/write timeout this is generally configurable per request and a timeout for establishing a connection. 
What I have here is for the latter, this typically a configuration per host / service not so much per request.

I think you leave the request timeout as is because you still want kind of infinite behavior when streaming data

**Comment by hickeng** [comment]
@casualjim I'm not sure what you mean by establishing the connection (whether you're talking about TCP, HTTP header response or something else) so to detail at a high level what would be ideal for us (rephrasing of @sflxn comment):
```
timeout = 30sec
get http header response
if response is not 200 or 30sec expires
  return

timeout = infinite
read response body until connection closes
```

**Comment by casualjim** [comment]
By establishing a connection that is about the TCP connection, this is to avoid hanging connections when the other end accepts connections but doesn't do anything with them otherwise. 
Then currently the default golang http client does not make a distinction between reading headers and reading the response body. 

Thanks for that little story, so you want the tcp read timeout to be split into 2 timeouts, so that you can timeout quickly if no response is ever given, but when the headers are received and the body has started you want to have a much larger timeout?

Would a sliding timeout that gets reset every time data is received work better? This would mean to get infinite timeout the server end would have to write something to the connection once in awhile. 

Anyway the behavior you're after would be plugged in, in the same way I described above and you can find it in this library: https://github.com/mreiferson/go-httpclient/blob/master/httpclient

**Comment by hickeng** [comment]
sliding timeout would be great! It's not a direct behavioral mapping for docker, but for us it's ideal as an active attach inhibits vMotion.

**Comment by hickeng** [comment]
marking this as both user-doc and bug as it'll need documenting for TP3
