### ISSUE TITLE
Customize VCH appliance and container VM icons

### ISSUE THREAD

**Issue by emlin** [vmware/vic#113]
To differentiate VIC elements in the vSphere UIs we will register custom icons for the VCH and containerVMs. This allows quick visual identification of VIC elements within a mixed environment.

vic-machine will need to:
- [ ] register an extension if not already present
- [ ] install custom icons for the extension
- [ ] associate new VCHs with the appropriate extension ID
- [ ] pass the extension ID to the VCH for use when creating containerVMs.

There's some thought required about extension/VIC versions and how we handle those. We may wish to register a new extension version, and change icons for old versions to have an orange flag so that it's easy to see which VCH/containerVMs are running on backlevel code.
-- hickeng

**Comment by jak-atx** [comment]
@hickeng is this referring to having custom icons (for containerVM and vch) in the left nav tree in the web client?

**Comment by mdubya66** [comment]
making low for now, may get raised based on UX input
