### ISSUE TITLE
Cant deploy vic with nimbus vc if nimbus esx previously deployed vic. 

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#1133]
Want to make sure these order of events won't cause issue to anyone.

**Comment by hickeng** [comment]
@sgairo can you add some more detail please - what's the vic-machine output at a minimum.

**Comment by hickeng** [comment]
@emlin We should add this as a scenario to vic-machine validation tests, either ensuring we can deploy or ensuring that there's a useful message explaining why not.
