### ISSUE TITLE
Docker persona should update image cache in background to avoid restarts

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1138]
**Expected behavior:**
The persona should not exit if the update does not succeed. It should retry some number of times and then warn.

**Actual behavior:**
Currently the persona exits when the cache is not updated at startup. This happens a couple of times at startup until the portlayer is up and serving requests.

**Comment by hickeng** [comment]
@jzt How long is this going to take to fix? #1127 doesn't yet do restart - I deliberately delayed it as I figured we should be discovering when components crash instead of having the watchdog bring them back up silently.
We will be broken after that merges until this is addressed.
