### ISSUE TITLE
Docker API: Container Inspect

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1144]
This is the parallel to #388.  It is part of docker inspect, but it is implemented in the container backend.  This has a dependency on the container metadata work in the portlayer.

**Comment by hickeng** [comment]
@sflxn how is this going? IMO the most crucial bits of runtime state from the container that need to be reported are the IP address and the process status (exit code, successfully launched, et al). Let me know if there's anything holding you up w.r.t. getting hold of that information.

**Comment by sflxn** [comment]
We now have a swagger definition, and I just updated it.  I've implemented a first rev of container inspect on the personality server side.  Until the portlayer returns those swagger definitions I created, container inspect is still blocked.  I'm going to create some dummy code on the portlayer side to test with the personality server while I wait for @cgtexmex to populate those data fields.

**Comment by sflxn** [comment]
Closing due to duplicate of #370.
