### ISSUE TITLE
Separate output mechanism for vic-machine console

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1148]
We are currently having issues because we're using the standard logging in vic-machine and reusing library packages that are logging using Info/Warn/Error.

vic-machine output intended for the user should use a separate logger that can be configured appropriately - the logging from packages should go into a file.
#726 has been closed in favour of this - there is also some code added by #1127 into the trace package that should be backed out once this is done.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage
