### ISSUE TITLE
Improve image cache availability and locking

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1154]
Currently the docker personality has no information about an image that it pulls. It delegates to imagec, who pulls an image and pushes it to the storage portlayer and quits. This requires the docker persona to send an update request to the cache, which makes a request to the portlayer to get a list of all layers currently stored in the portlayer. It then must iterate through that list, unmarshal the metadata for each layer to find layers that represent images, and cache the metadata for each image it finds.

Additionally, access to the cache is disallowed during this process as it remains locked until the update completes. This is problematic in situations where a read access to the cache is attempted which must block until the cache update is complete. In the case of a docker host with hundreds or thousands of images, this wait would be evident.

This process can be improved with two changes: 

1. imagec could be updated to provide information to the docker persona about the image it just pulled. The docker persona can then add this information (metadata) to the cache without having to trigger another request to the portlayer that will have to iterate over the entire layer list to find anything it needs to cache.

2. The full cache update can now be run just once when the docker persona starts, and can lock the cache only when it actually finds something in the list of layers that it needs to add to the cache. This would allow read/write access to the cache while the update is in progress.

**Comment by corrieb** [comment]
@jzt I believe this is related to your work on making imagec into a library. Should this remain an onsite target?
