### ISSUE TITLE
Refactor/rename: lib/metadata

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1156]
Metadata is a misleading name for the package as it's primarily the configuration structures for VCH and cVMs. This needs to be renamed and those configuration structures placed in a separate package from the various shared metadata structures that are getting placed in there.
This will help avoid the situation where we're pulling in large numbers of supplementary packages during compilation of tether.

**Comment by hickeng** [comment]
There is a WIP PR that includes this: #1466

**Comment by mdubya66** [comment]
Closing per @hickeng
