### ISSUE TITLE
vic-machine: usability enhancements

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1157]
@cormachogan Provided some feedback on the current vic-machine usage:

Thoughts on vic-machine from rolling out the latest master version this morning.

1. Can we reduce some of the arguments to single letters. We have this for username (-u), password (-p) and target (-t), but not for most of the other arguments. This would save a lot of  typing.

2. Highlight which arguments are required and which arguments are optional. Place them in different help output sections if that makes sense. For example, many of the network entries are optional, and that is not clear from the help.

3. For compute-resource path, give an example for both ESXi and VC. The example provided is for VC only. We should show examples of using whole cluster, individual host and an actual resource pool. This is the area that is mostly complicated in my opinion, so the more we can do to explain it in the help, the better.

4. Do we really want people to visit hub.docker.com to figure out what an external network is? Can we not simply add an explanation here? Is it the VM network?

5. I’m not sure I understand what management network is from the description? What does “provides route to target hosting vSphere” imply? Is this how the VCH can reach the ESXi or VC? Is it only needed when VCH does not have a path to ESXi or VC from the VM network?

6. Resource path is still an issue - it is not intuitive from the help what needs to be added. In the case of ESXi, we should not make it a requirement to include this and use  default. We should simply use all the host’s resources. I had to specify compute-resource of “/" to continue with ESXi. Is that correct?

7. When trying to deploy to ESXi that is managed by VC, the install does not fail gracefully:
```
# ./vic-machine-linux create --image-datastore datastore1 --container-datastore datastore1 --name vch -u root -p password -t esx.fqdn --compute-resource /         
INFO[2016-06-21T12:53:30Z] ### Installing VCH ####                      
INFO[2016-06-21T12:53:30Z] Generating certificate/key pair - private key in ./vch-key.pem 
INFO[2016-06-21T12:53:32Z] Validating supplied configuration            
INFO[2016-06-21T12:53:32Z] Creating a Resource Pool                     
ERRO[2016-06-21T12:53:32Z] Creating resource pool failed: ServerFaultCode: Access to resource settings on the host is restricted to the server that is managing it: 'vcenter.fqdn'. 
INFO[2016-06-21T12:53:32Z] Creating VirtualSwitch                       
INFO[2016-06-21T12:53:32Z] Creating Portgroup                           
INFO[2016-06-21T12:53:33Z] Creating appliance on target                 
INFO[2016-06-21T12:53:33Z] Network role client is sharing NIC with external 
INFO[2016-06-21T12:53:33Z] Network role management is sharing NIC with external 
vic-machine-linux failed:  runtime error: invalid memory address or nil pointer dereference
```

8. Can we do some pre-checks that name resolution is working correctly? This looks like a hard and fast requirement for a successful deploy (uploading of images), and DNS may not be available in all dev environments.

9. when the distributed port group is created, but you select a host that does not have an attachment to the DVS, it fails weirdly:
```
# ./vic-machine-linux create --image-datastore datastore1 --container-datastore datastore1 --name vch -u administrator@vsphere.local -p password -t vcenter.fqdn --compute-resource resource/pool --bridge-network BridgeDPG
INFO[2016-06-21T12:59:33Z] ### Installing VCH ####                      
INFO[2016-06-21T12:59:33Z] Generating certificate/key pair - private key in ./vch-key.pem 
INFO[2016-06-21T12:59:36Z] Validating supplied configuration            
INFO[2016-06-21T12:59:37Z] Creating a Resource Pool                     
INFO[2016-06-21T12:59:37Z] Creating appliance on target                 
INFO[2016-06-21T12:59:37Z] Network role client is sharing NIC with external 
INFO[2016-06-21T12:59:37Z] Network role management is sharing NIC with external 
ERRO[2016-06-21T12:59:37Z] Operation failed: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid - (&{{} %!!(MISSING)s(*types.InvalidArgument=&{{{<nil> [{{} com.vmware.vim.vpxd.dvs.nonHostMember.label [{{} host <snip>} {{} dvs DSwitch}] Host <snip> is not a member of VDS DSwitch}]}} spec.deviceChange.device.port.switchUuid}) A specified parameter was not correct: spec.deviceChange.device.port.switchUuid}) 
ERRO[2016-06-21T12:59:37Z] Unable to create appliance VM: Operation failed: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid - (&{{} %!s(*types.InvalidArgument=&{{{<nil> [{{} com.vmware.vim.vpxd.dvs.nonHostMember.label [{{} host <snip>} {{} dvs DSwitch}] Host <snip> is not a member of VDS DSwitch}]}} spec.deviceChange.device.port.switchUuid}) A specified parameter was not correct: spec.deviceChange.device.port.switchUuid}) 
INFO[2016-06-21T12:59:37Z] Collecting a0522635-224e-4171-92b1-7edaf726b39f vpxd.log 
vic-machine-linux failed:  Creating the appliance failed with Operation failed: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid - (&{{} %!s(*types.InvalidArgument=&{{{<nil> [{{} com.vmware.vim.vpxd.dvs.nonHostMember.label [{{} host <snip>} {{} dvs DSwitch}] Host <snip> is not a member of VDS DSwitch}]}} spec.deviceChange.device.port.switchUuid}) A specified parameter was not correct: spec.deviceChange.device.port.switchUuid}). Exiting...
```

10. vic-machine -v doesn’t show any versioning.

**Comment by hickeng** [comment]
@cormachogan requesting clarification:

> Can we reduce some of the arguments to single letters. We have this for username (-u), password (-p) and target (-t), but not for most of the other arguments. This would save a lot of typing.

The issue here is that with a large number of arguments the letter mappings become convoluted. We can provide them easily for some of the most commonly used options, but would tab completion be a preferable solution?

> Do we really want people to visit hub.docker.com to figure out what an external network is? Can we not simply add an explanation here? Is it the VM network?

External network is purely a VIC thing - agree that the help can be clarified. What about:
`The network on which forwarded ports will be exposed`
The hub.docker.com is actually more about there being a route to the wider world - it's expected that'll be the external network but there's no reason it has to be.

> I’m not sure I understand what management network is from the description? 
You're correct - this is the network the VCH will use to talk to the vCenter or ESX that's hosting it. It's only needed if that cannot be done via another network that's specified. I've raised #1160 to track the error cases here.

> Resource paths ....

This now has sensible default behaviour and will recommend valid paths if an incorrect one is specified. My feeling is that adding all the details about default, recommendations, differences between vCenter and ESX to the help output isn't viable and it should be in the documentation. We will rely heavily on you for vetting the help output for this flag.

> Can we do some pre-checks that name resolution is working correctly?

DNS shouldn't be a hard requirement - if you're specifying IP addresses for ESX/vCenter that should function - what behaviour are you seeing?

**Comment by hickeng** [comment]
@emlin I'm prompting this to an epic and assigning this to you - please can you break out the individual items into issues. I'm happy to help with phrasing help descriptions, but our best bet may be to explain to @cormachogan what the intent of each flag is (as partially done above) and have him make suggestions as a Customer0. A couple of iterations will hopefully give us something sufficient for TP3.

**Comment by cormachogan** [comment]
George,
Re:
>>
>>   Can we do some pre-checks that name resolution is working correctly?
>>
> DNS shouldn't be a hard requirement - if you're specifying IP addresses for ESX/vCenter that should function - what behaviour are you seeing?

My management network is on a completely different network to my VMs. When trying to deploy using IP addresses, my guess is that VC is resolving these to an FQDN, which is unresolvable on the VM network. e.g. 
root@photon-NaTv5i8IA [ /workspace/vic/bin ]# ./vic-machine-linux create --image-datastore isilion-nfs-01 --container-datastore esxi-hp-08-local --name cor-VCH-01 -u administrator@vsphere.local -p VMware123! -t 10.27.51.103 --compute-resource Mgmt/VCH-RP --bridge-network Bridge-DPG
INFO[2016-06-21T13:02:37Z] ### Installing VCH ####                      
INFO[2016-06-21T13:02:37Z] Generating certificate/key pair - private key in ./cor-VCH-01-key.pem 
INFO[2016-06-21T13:02:41Z] Validating supplied configuration            
INFO[2016-06-21T13:02:41Z] Creating appliance on target                 
INFO[2016-06-21T13:02:41Z] Network role client is sharing NIC with external 
INFO[2016-06-21T13:02:41Z] Network role management is sharing NIC with external 
INFO[2016-06-21T13:02:44Z] Uploading images for container               
INFO[2016-06-21T13:02:44Z] 	bootstrap.iso                               
INFO[2016-06-21T13:02:44Z] 	appliance.iso                               
ERRO[2016-06-21T13:02:44Z] 		Upload failed for appliance.iso, Put https://esxi-hp-08.rainpole.com/folder/cor-VCH-01/appliance.iso?dsName=isilion-nfs-01: dial tcp: lookup esxi-hp-08.rainpole.com on 10.16.142.110:53: no such host 
ERRO[2016-06-21T13:02:44Z] 		Upload failed for bootstrap.iso, Put https://esxi-hp-05.rainpole.com/folder/cor-VCH-01/bootstrap.iso?dsName=isilion-nfs-01: dial tcp: lookup esxi-hp-05.rainpole.com on 10.16.142.110:53: no such host 
INFO[2016-06-21T13:02:44Z] Collecting a0522635-224e-4171-92b1-7edaf726b39f vpxd.log 
vic-machine-linux failed:  Uploading images failed with Put https://esxi-hp-08.rainpole.com/folder/cor-VCH-01/appliance.iso?dsName=isilion-nfs-01: dial tcp: lookup esxi-hp-08.rainpole.com on 10.16.142.110:53: no such host. Exiting...

I resolved it by placing entries for the ESXi hosts in the /etc/hosts file on my deployment VM. I'm guessing the VM network must be able to resolve the ESXi hostnames, no?

**Comment by hickeng** [comment]
@cormachogan @dougm any idea what's happening here? I'm guessing this is related to datastore browser upload going directly to ESX and obtaining that address from VC. If that's the case it's an issue given there's no assurance that vic-machine has a route directly to ESX hosts, even if they can be resolved.

**Comment by hickeng** [comment]
@reddolan @mdubya66 has asked me to add you to this issue for usability commentary.

**Comment by emlin** [comment]
@cormachogan @hickeng 

> The issue here is that with a large number of arguments the letter mappings become convoluted. We can provide them easily for some of the most commonly used options, but would tab completion be a preferable solution?

Agree with George. And if we check docker command line, it's same.

> Highlight which arguments are required and which arguments are optional. Place them in different help output sections if that makes sense. For example, many of the network entries are optional, and that is not clear from the help.

This is one issue, but simply separate them is not easy. A set of options should be set, if other set of options are not there. For example, the --user and --password are required, only when the --target does not include them. and interactive input is required, if non password specified in these two options.
But we might add "Optional" in the argument description message.

**Comment by dougm** [comment]
We recently started using the SessionManagerGenericServiceTicket.HostName field for datastore http access: http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.SessionManager.GenericServiceTicket.html

You can revert to the old behavior for now with the following environment variable:
```
export GOVMOMI_USE_SERVICE_TICKET_HOSTNAME=false
```

We can change the default to the old behavior and have an option to enable it if needed.

**Comment by emlin** [comment]
> We recently started using the SessionManagerGenericServiceTicket.HostName field for datastore http access: http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.SessionManager.GenericServiceTicket.html
> 
> You can revert to the old behavior for now with the following environment variable:
> 
> export GOVMOMI_USE_SERVICE_TICKET_HOSTNAME=false
> 
> We can change the default to the old behavior and have an option to enable it if needed.

Then if host is connected with ip address, without dns name, will there have problem to upload file?

**Comment by cormachogan** [comment]
I suspect that will work.

Could we try using the hostname first, and if that has a resolution issue, revert to using IP addresses?

**Comment by cormachogan** [comment]
Oops - sorry. I stand corrected. My hosts are already added with IP addresses, but it looks like VC is resolving their hostnames. So yes, it still happens when hosts are connected with IP addresses @emlin

**Comment by dougm** [comment]
@cormachogan can you try the workaround above when you have a chance, in your shell before running vic-machine:
```
export GOVMOMI_USE_SERVICE_TICKET_HOSTNAME=false
```

**Comment by cormachogan** [comment]
Yes - that does indeed work @dougm

**Comment by hickeng** [comment]
@dougm is it possible to have VC relay the file upload? I'm sure there are circumstances in which you have a route to VC but not to the ESX hosts (I'm sure I've asked this before but don't recall the answer). If we cannot then we'll need to doc it very clearly and provide a helpful error message in the case of routing failure, preferably one that references the precise documentation

**Comment by stuclem** [comment]
@cormachogan, I've just read through this one again. I think that a lot of your initial observations are covered in the doc that I wrote for the vic-machine create options. Can you please take a look at https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md and let me know what you think? Thanks!

**Comment by cormachogan** [comment]
Thanks @stuclem - yes, there is a lot of good detail here. Unfortunately, we find customers only turn to the docs when they've tried things out a few times for themselves. I guess what I'm trying to do here is make sure the initial experience is really good, and provide as much detail up front so they can be successful. Good warning/erros messages related to configuration and a good help output in the CLI will go along way towards that.

**Comment by stuclem** [comment]
Could there be a way to link to the doc from the help output?

**Comment by corrieb** [comment]
Since a number of the issues linked here are tagged as GA, this epic should also be tagged as GA. We should do what we can for offsite, but the detail should be captured in the linked issues.

**Comment by reddolan** [comment]
I just want to make sure I am supporting you guys as much as needed. Please let me know if there is something(s) here I should look at or work with someone on. With the Onsite coming up quickly, I want to make sure I am doing all that I can to help

**Comment by mdubya66** [comment]
For onsite we should verify with Karthik what he wants for feedback. IMO mockups for vicadmin would be sufficient.

Sent from my iPhone

On Jul 15, 2016, at 12:10 PM, reddolan <notifications@github.com<mailto:notifications@github.com>> wrote:


I just want to make sure I am supporting you guys as much as needed. Please let me know if there is something(s) here I should look at or work with someone on. With the Onsite coming up quickly, I want to make sure I am doing all that I can to help

-
