### ISSUE TITLE
Deploy status reporting

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#116]
There are two mechanisms:
1. Uses property collector to get status updates - no polling
2. Records status in a manner that doesn't overwrite prior status - full action log available for access.

**Comment by hickeng** [comment]
@emlin we have some status reporting from vic-machine, but I'm unconvinced it's sufficient to diagnose all probably failure paths.

**Comment by mdubya66** [comment]
This needs an estimate

**Comment by emlin** [comment]
@mdubya66 Still need more clarification for what to do.
@hickeng We already did lots of validation, status report in vic-machine, not quite sure if this is still necessary at this time.

**Comment by emlin** [comment]
@hickeng Please help to confirm on this issue. thanks
