### ISSUE TITLE
vic-machine: useful error if VCH appliance cannot connect to the target

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1160]
If the VCH appliance cannot connect to the target, but vic-machine can, then we need a useful error. It should direct the user at the `--management-network` option as it's likely that either:
a. the VCH cannot get an IP address on the management network.
b. the VCH does not have a route to the specified target.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage. Needs release note.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by mdubya66** [comment]
Prioritizing this for 1.1. It will help reduce customer calls.

**Comment by emlin** [comment]
close this issue as it rely on 3479, and can be fixed together
