### ISSUE TITLE
Create utility function to GetHost and refactor docker personality to use it.  

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#1162]
The below code is used in many places in the docker-engine-server(and will be used many more times) and should be moved to a utility function that can be used by all functions. This is an issue of quality, as moving forward we do not want to have to modify the same section of code a bunch of times. 

**Code**

```
	host, err := guest.UUID()
	if host == "" {
		host, err = os.Hostname()
	}
	if err != nil {
		return result,
			derr.NewErrorWithStatusCode(fmt.Errorf("Volume.CreateVolume got unexpected error getting hostname : %s", err),
				http.StatusInternalServerError)
	}


```

**Expected behavior:**
host,err := GetHost()

**Actual behavior:**
see above code section.

**Comment by matthewavery** [comment]
This may no longer be an issue. We have moved from using hostnames to more appropriate behavior.

**Comment by mdubya66** [comment]
@matthewavery since you opened it and if you can confirm it's no longer an issue, please close it.

**Comment by mdubya66** [comment]
ping @matthewavery

**Comment by matthewavery** [comment]
Looks like this is an old ticket. I do not think we used host names
