### ISSUE TITLE
vic-machine options enhancement

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1165]
- Add single letter option for common arguments
- Add "Optional" explicitly into the flag description if it is optional all the time

**Comment by emlin** [comment]
@cormachogan This issue is to address the usability issue you raised previously.
Currently, we had few short name options for vic-machine create. Is there any more options need short name you think?
And I checked the options, almost all of them are optional, except --target and --image-datastore, so I gonna use a easiest way to show them as "Required" as the start of flag usage information. How do you think about that?

**Comment by emlin** [comment]
@cormachogan @hickeng Would you think it's good to add acronym as the flag short name?
for example, --container-network-gateway, to -cng?
It's not that easy to have auto-complete for all options for Windows, I think. So I'm wondering one efficient short name for all options might work.

**Comment by cormachogan** [comment]
Both those recommendations work for me @emlin

**Comment by emlin** [comment]
@cormachogan Thanks for your confirmation
