### ISSUE TITLE
Add volume creation and attach functionality to docker container create

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#1169]
Add support for volume operations to container create. So that volumes can be attached to containers, and anonymous volumes functionality will be added in.

**Comment by mdubya66** [comment]
Tied to #806. Might need to turn it into an epic.

**Comment by corrieb** [comment]
Review with George: George to follow up with @matthewavery and @fdawg4l for TP3 drop/not decision

**Comment by fdawg4l** [comment]
Pretty sure this is done.  @matthewavery, please reopen if you feel this isn't done.
