### ISSUE TITLE
Persist appliance init.log

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1183]
We need to be able to preserve the appliance init.log across reboots or we cannot tell if components are being restarted, failing to start, etc.
We also need to ensure that vicadmin log serving **always** has a fall-back so we don't end up in a scenario where we cannot access the logs.

**Comment by corrieb** [comment]
Sounds like a little bit of design work is required here. However, anything related to logs or ease of triage should be a high priority for onsite. Need to assign

**Comment by hickeng** [comment]
component restart counts are now persisted in the extraconfig, along with last 5 exit codes. I'd love to have a last x lines of stderr or similar, but that's real work.

I don't think hardening vicadmin is an onsite task.

**Comment by caglar10ur** [comment]
can't we add a new serial for init.log and dump it there?

**Comment by mdubya66** [comment]
who should take this on @hickeng?

**Comment by matthewavery** [comment]
Duplicate of #2079
