### ISSUE TITLE
vic-machine: static ip addresses for appliance

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1184]
We should allow users to specify static IP addresses for the appliance networks.

@hmahmood has code to validate that networks do not overlap/conflict/et al, but if that's not easy to consume then we can skip the validation for TP3 timeframe and open a second issue to add that.

**Comment by flamby** [comment]
+1 as dhcp is regularly forbidden for external network in telco

**Comment by andrewtchin** [comment]
Assign static IP address to the VCH interface on client and external networks
Add `vic-machine` flags
