### ISSUE TITLE
Support pull by image digest

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#1186]
Currently imagec is only able to pull images by tag.  For example:

```
docker pull busybox:1.24.2
```

We need to provide support for pulling images via image digest:

```
docker pull busybox@sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
```

While vic (via imagec) will attempt a pull when a user provides a digest, it's not pulling via the digest -- it's actually pulling via the latest tag.  Since the digest is ignored the wrong image might be pulled.

Depends on #1484

**Comment by hickeng** [comment]
Needed to support even client side notary use.

**Comment by cgtexmex** [comment]
Here's an example of pulling the wrong image:
```
docker pull nginx@sha256:ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f
Pulling from library/nginx
36a46ebd5019: Pull complete
a3ed95caeb02: Pull complete
57168433389f: Pull complete
332ec8285c50: Pull complete
Digest: sha256:c15f1fb8fd55c60c72f940a76da76a5fccce2fefa0dd9b17967b9e40b0355316
Status: Downloaded newer image for library/nginx:latest
```
Notice the sha256 that's requested is `ebd2b85803e78100a582385f7eac56cd367561f0f2bab005f784cda95818d41f`, but what is actually returned is `c15f1fb8fd55c60c72f940a76da76a5fccce2fefa0dd9b17967b9e40b0355316`. The returned images is the current latest image.  

From my perspective this should move up in priority since it's not only wrong, but masks the issue and gives the illusion of working.

**Comment by hickeng** [comment]
adjusting labels based on @cgtexmex comment - I had thought it was unavailable, not available but incorrect; agree that this is bad.
