### ISSUE TITLE
Downloading container-logs.tar.gz gives an incomplete tar.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1202]
Installed build 2151 on a fresh esx. Tried run busybox and its not working so I went to look at logs. And the log I downloaded is incomplete.

**VIC Version:**

build 2151

**Code**

```
tar zxfv ../container-logs.tar.gz
x %2Fproc%2Fmounts
x uptime
x df
x free
x ip+link
x ip+addr
x ip+route
x lsmod
x ls+-l+%2Fdev%2Fdisk%2Fby-path
x ls+-l+%2Fdev%2Fdisk%2Fby-label
x docker-personality.log
x port-layer.log
x vicadmin.log: Truncated input file (needed 313 bytes, only 0 available)
tar: Error exit delayed from previous errors.

```

**Expected behavior:**
Complete tar.
**Actual behavior:**
Truncated vicadmin.log error.

**Comment by mdubya66** [comment]
FYI I saw similar issues using hello-world. https://docs.docker.com/engine/getstarted/step_one/ and build 2151 on ESX running in fusion.

**Comment by mdubya66** [comment]
(mwilliamson) dubs:~/Downloads/vic 3 $ docker --tls run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
a3ed95caeb02: Pull complete
a9d36faac0fe: Pull complete
Digest: sha256:ff215bfe287b986dba232bc82892d636b0e1b1c1ae42f779202caced61f6376b
Status: Downloaded newer image for library/hello-world:latest

^C

^ZError response from daemon: vSphere Integrated Containers 0.3 does not implement container.ContainerWait
(mwilliamson) dubs:~/Downloads/vic 3 $ fg

**Comment by hickeng** [comment]
@mlh78750 @mdubya66 This should be addressed by #1150 (PR is #1217).

@mdubya66 We don't implement wait. If @cgtexmex gets in the stretch goal of vc events for our VMs this coming week then we have a mechanism by which to do so, but there still won't be the necessary glue to implement Wait,

**Comment by mlh78750** [comment]
@hickeng We should still likely handle the failure of gathering those logs better than we are. Seems the truncated file was actually vicadmin.log. So I'm not sure this will be fixed by #1150.

```
$ tar zxfv ../container-logs.tar.gz
x %2Fproc%2Fmounts
x uptime
x df
x free
x ip+link
x ip+addr
x ip+route
x lsmod
x ls+-l+%2Fdev%2Fdisk%2Fby-path
x ls+-l+%2Fdev%2Fdisk%2Fby-label
x docker-personality.log
x port-layer.log
x vicadmin.log: Truncated input file (needed 261 bytes, only 0 available)
tar: Error exit delayed from previous errors.
```

**Comment by hickeng** [comment]
@mlh78750 I've not seen this myself and have no real way of diagnosing it. Was it re-creatable?
#1150 altered the code that actually provides the data to the tar, however I would have expected to see extra data issues (and used to consistently) where the log had increased in size. I've never seen truncated.

**Comment by mlh78750** [comment]
@hickeng I'm unable to reproduce with 2416 build with normal configuration. I think when I did this originally the firewall was enabled on the host. 

So this was likely an artifact of the fact that the appliance was running on a host with the firewall active. I'll close since I can't reproduce.
