### ISSUE TITLE
docker run does not attach

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1205]
Fresh install of build 2151 on 6.0u2. 

Ran run -ti busybox and it hangs my terminal. Due to #1202 I couldn't collect the logs the normal way so I grabbed them from the data store.

[7e7bb0a6ad9c003ef1b6273576880a3fc8afc810ef78ef69cfd46a9ac5d4356d.log.txt](https://github.com/vmware/vic/files/332525/7e7bb0a6ad9c003ef1b6273576880a3fc8afc810ef78ef69cfd46a9ac5d4356d.log.txt)
[7e7bb0a6ad9c003ef1b6273576880a3fc8afc810ef78ef69cfd46a9ac5d4356d.debug.txt](https://github.com/vmware/vic/files/332526/7e7bb0a6ad9c003ef1b6273576880a3fc8afc810ef78ef69cfd46a9ac5d4356d.debug.txt)
[container-logs.tar.gz](https://github.com/vmware/vic/files/332527/container-logs.tar.gz)
[logs1.tar.gz](https://github.com/vmware/vic/files/332528/logs1.tar.gz)

**VIC Version:**

build 2151

**Code**

```
$ docker -H 172.16.252.150:2376 --tls run -ti busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
```

**Expected behavior:**

**Actual behavior:**

**Comment by mlh78750** [comment]
Looks like the attach doesn't work. The console on my VM showed this: 
![screen shot 2016-06-24 at 3 27 10 pm](https://cloud.githubusercontent.com/assets/16670605/16349756/2da88094-3a20-11e6-80c2-87856e4e6f9d.png)

**Comment by hickeng** [comment]
@mlh78750 There's no indication of even an attempted connection back to the port layer. I suspect that you're ESX firewall is blocking the connection, or somehow the containerVM is attempting to connect back to an incorrect IP.

**Comment by mlh78750** [comment]
@hickeng: Yup. New esx install and I failed to setup the firewall correctly. I'll close this and open and enhancement for vic-admin like we discussed this morning.
