### ISSUE TITLE
vic-machine output says to set DOCKER_OPTS but it seems to be ignored.

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#1207]
VIC Version:
https://bintray.com/vmware/vic-repo/download_file?file_path=vic_2151.tar.gz

ESX version
VMware-VMvisor-Installer-6.0.0-3634798.x86_64 installed with all defaults in Fusion.

Docker version
(mwilliamson) dubs:~/Downloads/vic 3 $ docker --version
Docker version 1.11.1, build 5604cbe

**Expected behavior:**
vic-machine suggests these settings

INFO[2016-06-24T13:39:26-07:00] DOCKER_HOST=172.16.127.143:2376
INFO[2016-06-24T13:39:26-07:00] DOCKER_OPTS="-H 172.16.127.143:2376 --tls"
INFO[2016-06-24T13:39:26-07:00]
INFO[2016-06-24T13:39:26-07:00] Connect to docker:
INFO[2016-06-24T13:39:26-07:00] docker -H 172.16.127.143:2376 --tls info
INFO[2016-06-24T13:39:26-07:00] Installer completed successfully
 

**Actual behavior:**
When I run docker commands it seems to require that we also add the --tls. That is confusing.

(mwilliamson) dubs:~/Downloads/vic 3 $ env | grep DOCKER
DOCKER_HOST=172.16.127.143:2376
DOCKER_OPTS=-H 172.16.127.143:2376 --tls

(mwilliamson) dubs:~/Downloads/vic 3 $ docker run hello-world
docker: Post http://172.16.127.143:2376/v1.23/containers/create: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16".
* Are you trying to connect to a TLS-enabled daemon without TLS?.
See 'docker run --help'.

**Comment by hickeng** [comment]
Should triage for TP3. This is not expected behaviour, but it is also entirely out of our control as the docker client is unmodified. We should be able to doc the case however.
@mdubya66 what version is your docker client?

**Comment by mdubya66** [comment]
1.11.1. See the output at the top of this issue.

**Comment by hickeng** [comment]
Judging by the list here: https://docs.docker.com/engine/reference/commandline/cli/ DOCKER_OPTS is not actually consumed by the client, but is most likely processed by the /etc/default/docker or comparable service scripts.
We should remove the DOCKER_OPTS line from the vic-machine output.

**Comment by emlin** [comment]
Move to in progress per George's request
