### ISSUE TITLE
docker run hello-world hangs 

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#1208]
VIC Version:
https://bintray.com/vmware/vic-repo/download_file?file_path=vic_2151.tar.gz

ESX version
VMware-VMvisor-Installer-6.0.0-3634798.x86_64 installed with all defaults in Fusion.

Docker version
(mwilliamson) dubs:~/Downloads/vic 3 $ docker --version
Docker version 1.11.1, build 5604cbe

Installed b2151 and went to run the hello-world container and the shell locked up. My terminal is hung after running the below command. The logs are attached.

(mwilliamson) dubs:~/Downloads/vic 3 $ ./vic-machine-darwin create --target 172.16.127.129 --user root --password 'virtualized' --image-datastore datastore1
INFO[2016-06-24T13:39:11-07:00] ### Installing VCH ####
INFO[2016-06-24T13:39:11-07:00] Generating certificate/key pair - private key in ./docker-appliance-key.pem
INFO[2016-06-24T13:39:11-07:00] Validating supplied configuration
INFO[2016-06-24T13:39:11-07:00] Creating Resource Pool docker-appliance
INFO[2016-06-24T13:39:11-07:00] Creating VirtualSwitch
INFO[2016-06-24T13:39:11-07:00] Creating Portgroup
INFO[2016-06-24T13:39:12-07:00] Creating appliance on target
INFO[2016-06-24T13:39:12-07:00] Network role client is sharing NIC with external
INFO[2016-06-24T13:39:12-07:00] Network role management is sharing NIC with external
INFO[2016-06-24T13:39:12-07:00] Uploading images for container
INFO[2016-06-24T13:39:12-07:00] 	bootstrap.iso
INFO[2016-06-24T13:39:12-07:00] 	appliance.iso
INFO[2016-06-24T13:39:15-07:00] Waiting for IP information
INFO[2016-06-24T13:39:26-07:00] Waiting for major appliance components to launch
INFO[2016-06-24T13:39:26-07:00] Initialization of appliance successful
INFO[2016-06-24T13:39:26-07:00]
INFO[2016-06-24T13:39:26-07:00] SSH to appliance (default=root:password)
INFO[2016-06-24T13:39:26-07:00] ssh root@172.16.127.143
INFO[2016-06-24T13:39:26-07:00]
INFO[2016-06-24T13:39:26-07:00] Log server:
INFO[2016-06-24T13:39:26-07:00] https://172.16.127.143:2378
INFO[2016-06-24T13:39:26-07:00]
INFO[2016-06-24T13:39:26-07:00] DOCKER_HOST=172.16.127.143:2376
INFO[2016-06-24T13:39:26-07:00] DOCKER_OPTS="-H 172.16.127.143:2376 --tls"
INFO[2016-06-24T13:39:26-07:00]
INFO[2016-06-24T13:39:26-07:00] Connect to docker:
INFO[2016-06-24T13:39:26-07:00] docker -H 172.16.127.143:2376 --tls info
INFO[2016-06-24T13:39:26-07:00] Installer completed successfully

(mwilliamson) dubs:~/Downloads/vic 3 $ docker --tls run hello-world

^C^Z^Z

^C^C^C^C^C^Z^Z^Z^Z^Z
^X^X^Z^Z^Z

It eventually timed out with 
read tcp 172.16.127.1:52078->172.16.127.143:2376: read: operation timed out

[logs.tar.gz](https://github.com/vmware/vic/files/332583/logs.tar.gz)

**Comment by mdubya66** [comment]
Second time I ran it it hung for a long time then exited with

(mwilliamson) dubs:~/Downloads/vic 3 $ docker --tls run hello-world
Error response from daemon: vSphere Integrated Containers 0.3 does not implement container.ContainerWait

**Comment by mdubya66** [comment]
time="2016-06-24T20:58:49Z" level=info msg="Refreshing image cache..." 
time="2016-06-24T20:58:49Z" level=info msg="TLS enabled" 
time="2016-06-24T20:58:49Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\" 
time="2016-06-24T20:58:49Z" level=info msg="Listener created for HTTP on TCP 0.0.0.0:2376" 
time="2016-06-24T20:58:49Z" level=info msg="API listen on [::]:2376" 
time="2016-06-24T20:58:52Z" level=info msg="Image cache updated successfully" 
2016/06/24 21:03:54 http: TLS handshake error from 172.16.127.1:52370: tls: first record does not look like a TLS handshake
2016/06/24 21:04:21 http: TLS handshake error from 172.16.127.1:52378: tls: oversized record received with length 21536
time="2016-06-24T21:04:27Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] ContainerCreate" 
time="2016-06-24T21:04:27Z" level=info msg="config.Config = &{Hostname: Domainname: User: AttachStdin:false AttachStdout:true AttachStderr:true ExposedPorts:map[] PublishService: Tty:false OpenStdin:false StdinOnce:false Env:[] Cmd:[] ArgsEscaped:false Image:hello-world Volumes:map[] WorkingDir: Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal:}" 
time="2016-06-24T21:04:29Z" level=info msg="v1 = {ID:2cc48731dfffcdcb266501fb3b8eaf330a026827753f3b51a38cb5cdea5b536f Config:{Hostname:f7c17ad0cec6 Domainname: User: AttachStdin:false AttachStdout:false AttachStderr:false ExposedPorts:map[] PublishService: Tty:false OpenStdin:false StdinOnce:false Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Cmd:[/hello] ArgsEscaped:false Image:sha256:90c0b2441723b5f249063d242af2b0c222f921545efcd0c3c65d979c647b70f7 Volumes:map[] WorkingDir: Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal:}}" 
time="2016-06-24T21:04:29Z" level=info msg="ContainerCreate config' = {Name:angry_shirley Config:0xc82049be60 HostConfig:0xc820333c00 NetworkingConfig:0xc82001c3b8 AdjustCPUShares:false}" 
time="2016-06-24T21:04:29Z" level=info msg="dockerContainerCreateParamsToPortlayer = &{Args:[] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Image:0xc8200d3a50 ImageStore:0xc8200d3ab0 Name:0xc8200d3a70 NetworkDisabled:0xc8200d3948 Path:0xc8200d3a90 Tty:0xc8200d3949 WorkingDir:0xc8200d3ac0}" 
time="2016-06-24T21:04:29Z" level=info msg="container.ContainerCreate succeeded.  Returning container handle {1171f163898a0f32d65e7b43f20a5d80 8bc0ac3a83d5ba19e72a10817286801e737219744cad784e9ed3d0122f6b784d}" 
time="2016-06-24T21:04:29Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [2.529057226s] ContainerCreate" 
time="2016-06-24T21:04:29Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] ContainerAttach" 
time="2016-06-24T21:04:29Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] ContainerStart" 
time="2016-06-24T21:04:38Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] [8.766907276s] ContainerStart" 
time="2016-06-24T21:14:29Z" level=info msg="Attach stream closed" 
time="2016-06-24T21:14:29Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] [10m0.081910261s] ContainerAttach" 
time="2016-06-24T21:14:29Z" level=error msg="Handler for POST /v1.23/containers/8bc0ac3a83d5ba19e72a10817286801e737219744cad784e9ed3d0122f6b784d/attach returned error: Unknown error from the interaction port layer: Get http://127.0.0.1:8080/interaction/8bc0ac3a83d5ba19e72a10817286801e737219744cad784e9ed3d0122f6b784d/stderr: EOF" 
2016/06/24 21:14:29 http: response.WriteHeader on hijacked connection
2016/06/24 21:14:29 http: response.Write on hijacked connection
time="2016-06-24T21:15:30Z" level=error msg="Handler for POST /v1.23/containers/8bc0ac3a83d5ba19e72a10817286801e737219744cad784e9ed3d0122f6b784d/wait returned error: vSphere Integrated Containers 0.3 does not implement container.ContainerWait"

**Comment by hickeng** [comment]
This is #1129 with the specific scenario in #1176. The former definitely needs addressing for TP3 if remotely possible. Closing as dup.
