### ISSUE TITLE
vic-machine: create parent directory for images and volumes

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1210]
Parse the file directory configured by user, and create root directory if does not exist.
Persist the root directory to guestinfo, so that vic-machine delete can use that.

If on VSAN, and the root directory is name space, persist the name space uuid, to make sure next time we can delete the directory successfully.

**Comment by hickeng** [comment]
@stuclem @npakrasi For TP3 we should document behaviour when specifying a directory that doesn't exit, and one that does but isn't empty.
The critical point is what occurs when `vic-machine delete` is run as that cleans up images and volumes with the assumption that all files in the directories are fair game.

**Comment by gigawhitlocks** [comment]
`vic-machine delete` feature is in PR #1410 -- parsing and persistence to GuestInfo at install time are already on master at this time. VSAN features I'm not sure about -- I think those are still TBD

**Comment by fdawg4l** [comment]
We've abstracted the datastore type (vsan or otherwise) so that is no longer a concern.  For volumes, the path indicated for the volume store will either be used if it exists or created.  For images, this work is still TBD.

**Comment by stuclem** [comment]
This issue is included as a known issue in the release notes for TP3.

**Comment by corrieb** [comment]
Latest update from Faiyaz: "for clarity, the images directory on the datastore should be specified via vic-machine and used in the port layer like we are for volumes. volumes is A-OK". Sounds like this needs to remain open and move to onsite.

**Comment by gigawhitlocks** [comment]
Is this issue able to be closed after my PR here https://github.com/vmware/vic/pull/1678 is merged?

**Comment by fdawg4l** [comment]
@gigawhitlocks yes.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
