### ISSUE TITLE
Appliance SSH status and password

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1218]
Should we, or should we not, leave SSH installed and enabled on the appliance for TP3? If we do it should be a backup to the vicadmin log collection otherwise we will not improve that where it's lacking.

Irrespective, the root password for the appliance needs to be altered and we need to document how to determine what the password is - standard seems to be randomly generate and echo on the VM console.

**TP3 update:**
SSH is disabled by default on the appliance. To re-enable:
1. log into the appliance VM console using root/password
2. run `systemctl start sshd`

This will persist until appliance is rebooted.

**Comment by cormachogan** [comment]
Hey George, 

so a lot of the VMW appliances that we roll out set the initial root password as "changeme" and then it needs to be changed to something different the first time "root" logs in. Can we do something similar?

**Comment by mdubya66** [comment]
@gigawhitlocks : get with george and we can look at the options for this.

**Comment by corrieb** [comment]
Review with George: Letting this go out as TP3 in its current state is unacceptable.
Options:

**Comment by corrieb** [comment]
Decision made to disable SSH access in the TP3 tagged build. You can get to the log server without the need to authenticate.

**Comment by corrieb** [comment]
PR #1456 will temporarily remove default access to the appliance. We will doc how to re-enable it

**Comment by corrieb** [comment]
Moving this to onsite. First order of business is to restore the SSH capability. Second order is to figure out if we have any more elegant solution for onsite.

**Comment by hickeng** [comment]
@stuclem updated the description with instructions for re-enabling.

**Comment by gigawhitlocks** [comment]
Path forward: randomly generate a password at install time and echo it to the console at the end of the `vic-machine` installation? I can do this and re-enable SSH access to the appliance in one pull request once that strategy gets a 👍

**Comment by hickeng** [comment]
SSH should be enabled only for debug. Now that we have toolbox capabilities we can use govmomi guest operations to launch sshd "on-demand".

My preference at this time is for a vic-machine sub-option to `update` or whatever we call that:
`vic-machine update --enable-ssh=<password>`

This completely sidesteps all of the issues around default password config, persistent storage, encryption, etc as it's enabled by explicitly request with the desired password and only active until the appliance is restarted.

**Comment by hickeng** [comment]
Currently using the following to enable ssh and set passwd:
```
govc guest.start -k -vm=vmid passwd hello
govc guest.start -k -vm=vmid enable-ssh `cat ~/.ssh/authorized_keys`
```

The default allows no login at all.

**Comment by stuclem** [comment]
@hickeng the info in https://github.com/vmware/vic/issues/1218#issuecomment-249328522 is internal, correct? Can end users do this?
