### ISSUE TITLE
docker network ls --no-trunc returning only 32 characters

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1225]
Returns a 32 character id instead of the expected 64 character id:

Actual:
NETWORK ID                         NAME                DRIVER
991173cb084ac45cf0da448d820471c5   bridge              bridge 

Expected:
NETWORK ID                                                         NAME                DRIVER
06eccd2198d8b0f6cd22e95e6a129311b66aae1de6381caaebd1e2168a776e60   bridge              bridge              
87aaaf922156242fb10deb27e2a2829e9b7103ec6483a1ed5d336558fbc83f63   host                host                
aebb24318f10428cfd28569868a5d9c44dc7cc55d6b88c15e16e0dab68c4247b   none                null

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-16-Docker-Network-LS.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
