### ISSUE TITLE
Add "healthy" setup checks into vic-admin web page.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1229]
I recently setup a new ESX and forgot to change my firewall rules so VIC was not working properly. I would be nice to be able to go to the vicadmin web page and get a "red/yellow/green" indicator of the setup of VIC in that environment. I'm thinking of something where it shows if all the hosts have the firewall rules set properly, the available space in the datastore being used, ability to connect to public repos, etc.. 

So in my case: If I'd gone to the vicadmin page to pull logs because attach was not working I would have seen an ESX listed as not having a correct firewall configuration and I would have known my issue was my configuration. 

Having this information would also be useful for the log bundles to provide context of how "healthy" the environment is at the time.

**Comment by lweitzman** [comment]
this sounds like great data for the VIC overview page. but from what i understand, the overview page is not part of v1.0.

**Comment by mdubya66** [comment]
we've asked our crack group of interns to take a look at vicadmin. we will, opportunistically, improve the interface for 1.0 but will not hold the release.
