### ISSUE TITLE
Provide structured approach to finding the ControllerKey for VolumeJoin

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#1241]
A structured way of find the Controller key should be added instead of hardcoding the 100 value. The value will already be contained in the DeviceChanged slice within the config spec of the handle. Some code to look through the slice for a controller and extract the key should be a sufficient fix. 

**Code**

```
            ...
            ControllerKey: 100, //FIXME: This is hardcoded for now and should be located from the config spec in the future.
            ...
```

**Expected behavior:**

```
ControllerKey: GetControllerKey(specConfig)
```

**Actual behavior:**
See above code section

**Comment by matthewavery** [comment]
This should be doable by locating the ControllerManager object for a vm. Looks like the image mounting already is aware of where this is. Use that as an example for the volume joins and build the helper to be used everywhere where we need to locate the controller key.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by corrieb** [comment]
@matthewavery Changing this to kind/debt. Clearly in the code this is still there. Can you explain what the potential impact of this might be to a customer?
