### ISSUE TITLE
Add pprof logging for all appliance components

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1243]
#1217 adds an easy mechanism for collecting pprof debug data from all components, however we need to:
a. enable pprof on a know port for each component
b. add those addresses to the array in vicadmin

**Comment by hickeng** [comment]
@mdubya66 @mhagen-vmware I've added this to TP3 as it's a simple piece of work but would significantly enhance our ability to diagnose deadlocks/livelocks/memory leaks in any of the appliance components. Tentatively assigning to @kjplatz  - will go over how it's done with him.

**Comment by mdubya66** [comment]
👍

**Comment by kjplatz** [comment]
As I understand this, this will require the following changes:
   1) Configure the following programs to provide pprof data on a well-defined port:
       vch-init (already done)
       imagec
       vicadmin
       docker personality
       portlayer

    2) Modify the vicadmin utility to pull from each of those sources
