### ISSUE TITLE
Portlayer becomes zombie after signal

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1244]
Sending a signal to the port-layer turns it into a zombie - it shuts down as a server, but the process doesn't exit so it's never relaunched.

```
time="2016-06-26T06:58:39Z" level=debug msg="Shutting down udpserver" 
time="2016-06-26T06:58:39Z" level=debug msg="Shutting down tcpserver" 
time="2016-06-26T06:58:39Z" level=debug msg="UDP server exited" 
time="2016-06-26T06:58:39Z" level=debug msg="TCP server exited" 
```

**Comment by hickeng** [comment]
@caglar10ur is this a result of the recent DNS changes and alteration to cmd/port-layer?

**Comment by caglar10ur** [comment]
Hmm, it could be an issue with the signal handling in the main.

**Comment by caglar10ur** [comment]
https://github.com/vmware/vic/blob/master/cmd/port-layer-server/main.go#L61 is the addition, I'm not sure how it was handling signals before as I see no direct code in the main

**Comment by caglar10ur** [comment]
I think I see what's happening. We are getting the signal and acting on it but swagger seems to be using something called gracefull and that expects the handle signals by itself. Maybe we can raise the signal again with following (not tested)

```
[conur@vir:/opt/go/src/github.com/vmware/vic(link)] git diff
diff --git a/cmd/port-layer-server/main.go b/cmd/port-layer-server/main.go
index 6ea34bb..ed98f99 100644
--- a/cmd/port-layer-server/main.go
+++ b/cmd/port-layer-server/main.go
@@ -70,7 +70,9 @@ func main() {
        signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

        go func() {
-               <-sig
+               s := <-sig
+               process, _ := os.FindProcess(os.Getpid())
+               process.Signal(s)
                dnsserver.Stop()
        }()
```

**Comment by corrieb** [comment]
Added kind/bug here. Seems related to #1267 so making this @dougm problem

**Comment by corrieb** [comment]
@dougm can you assess this for priority for onsite please

**Comment by hickeng** [comment]
@corrieb #1267 is for the Signal API implementation on the port layer, this is having delivered an OS signal to the portlayer process itself. If anything it's likely swagger related - bouncing to @caglar10ur as the main impact here is from DNS shut down but the process doesn't exit so we don't restart.

**Comment by caglar10ur** [comment]
@hickeng they are shutting down cleanly here, how are you testing?

**Comment by caglar10ur** [comment]
As far as I see it's not becoming a zombie, it's just not starting another one until a request comes. That lay initialization part must be coming from go-swagger part cause I just tried it with a DNS disabled port-layer and had the same effect. 

I'm keen to close this as I'm not seeing a zombie process, it's just old one is waiting a request to come to start new one. @hickeng?
