### ISSUE TITLE
docker: Error response from daemon: server error from portlayer.

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1246]
**VIC Version:**

0.1 / master / commit ID

This was a master build downloaded at 01:00am PST on June 28th. I'm afraid I did not take note of the commit ID.

**Code**

```ts
// A self-contained demonstration of the problem follows...

My environment is physical. VC 6.0U2 with a single ESXi host also running 6.0U2.
VCH deploys without issue.

When trying to deploy a container, it fails with Error response from daemon: server error from portlayer.

root@photon-NaTv5i8IA [ /workspace/vic-master/vic/bin ]#  docker -H 10.27.33.121:2376 --tls run busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
docker: Error response from daemon: server error from portlayer.


The only interesting thing I could fine in the logs is as follows:

port-layer.log
time="2016-06-28T08:56:28Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesListAll] ScopesListAll"
time="2016-06-28T08:56:28Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesListAll] [17.755µs] ScopesListAll"
time="2016-06-28T08:56:46Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesDelete] ScopesDelete"
time="2016-06-28T08:56:46Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesDelete] [5.574µs] ScopesDelete"
time="2016-06-28T08:57:34Z" level=error msg="Property collector error: context deadline exceeded"
time="2016-06-28T08:57:34Z" level=error msg="Unable to wait for extra config property guestinfo..sessions|3a25c6b9d4a6a03bedcc8c773e50f516f0caa86b55c9be7fff215b0a16864c3a.started: context deadline exceeded"
time="2016-06-28T08:57:34Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).start] [3m1.460222441s] Container.start"
time="2016-06-28T08:57:34Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] [3m1.92883148s] Committing handle"
time="2016-06-28T08:57:34Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler] [3m1.929599593s] Containers.CommitHandler"
time="2016-06-28T09:04:32Z" level=error msg="id:3a25c6b9d4a6a03bedcc8c773e50f516f0caa86b55c9be7fff215b0a16864c3a: context deadline exceeded"


The firewall on my target ESXi host (there is only one in my VC cluster) is unloaded/disabled, so all connections are set to PASS.

@mwilliamson said that this might be a dupe, but to file it anyway.

```

**Expected behavior:**
That I should be able to deploy a container.

**Actual behavior:**
As described above.

**Comment by mdubya66** [comment]
@caglar10ur can you please take a look at this for root cause and if it's a known issue?

**Comment by cormachogan** [comment]
[container-logs.tar.gz](https://github.com/vmware/vic/files/337278/container-logs.tar.gz)

**Comment by cormachogan** [comment]
Folks - I can give you access to my environment if you wish - say the word.

**Comment by caglar10ur** [comment]
is that a nested env? "context deadline exceeded" suggests that your env. is slow to complete the operation and timed out

**Comment by cormachogan** [comment]
Nope - physical

Sent from my iPhone

On 28 Jun 2016, at 18:11, S.?a?lar Onur <notifications@github.com<mailto:notifications@github.com>> wrote:


is that a nested env? "context deadline exceeded" suggests that your env. is slow to complete the operation and timed out

-

**Comment by cormachogan** [comment]
I don't know if this helps or not, but I changed from using VC as a target to using that ESXi host directly as a target, and now trying to run containers (such as busybox, and hello-world) seem to hang.

**Comment by cormachogan** [comment]
Here are the logs from the most recent attempt to run containers with the target set to a physical ESXi host. 
[container-logs.tar.gz](https://github.com/vmware/vic/files/339388/container-logs.tar.gz)

**Comment by cormachogan** [comment]
Interestingly, after what appears to be maybe 10-15 minutes, this error is reported:

cormac@cs-dhcp32-29:~$  docker -H 10.27.33.181:2376 --tls run hello-world
Error response from daemon: vSphere Integrated Containers does not implement container.ContainerWait

**Comment by cormachogan** [comment]
OK - Matt directed me to pull down the latest build from bintray (2347) and test using applications such as busybox and whalesay). There are working successfully. Apparently there might be a dependency still on "docker ps" for hello-world. Anyway, I'm good now so I am going to close this issue.

**Comment by ibrahimabedalghafer** [comment]
Hi All,

I am also having the same issue, I run my VC on a physical machine and when I finished the deployment I run the command below :
docker run ubuntu 
and I get the below
Error response from daemon: Server error from portlayer: Start failed with: Server error from portlayer: unable to wait for process launch status: 
and when open a console to check I get 
INFO waiting clear signal to launch ......

any advise ??

**Comment by matthewavery** [comment]
@ibrahimabedalghafer we will need more info than that. providing a log bundle if you can would be very helpful. using the `vic-admin` endpoint in the output from the vch creation run. Also what version of VIC are you trying to deploy? what is the rough topology of your VC?(things like are you using VSAN, HA, etc...). We would definitely be glad to help you out!

**Comment by mdubya66** [comment]
thread has moved to a new issue, #7345
