### ISSUE TITLE
vic-machine in github build

### ISSUE THREAD

**Issue by carsonpadawon** [vmware/vic#1247]
This may be a duplicate, but submitting at request to be sure it is seen.

**VIC Version:**

0.1 / master / commit ID (not sure, downloaded 8am EST on 28 June 2016)

the "vic-machine" binary is in the /bin directory after the build.

**Comment by mdubya66** [comment]
need to look at this after our TP3 push.

**Comment by mdubya66** [comment]
@carsonpadawon could you add a description on how you built and on what OS?

**Comment by carsonpadawon** [comment]
Yes, sorry.  Using Photon OS v1.0.  I have this in HOL vPOD.  I have been using this same install for about 2 months.  This morning, I did a github.com pull and then a docker run -v $(pwd):/go/src/github.com/vmware/vic -w /go/src/github.com/vmware/vic golang:1.6 make all.  When this process complete I check the "bin" directory and vic-machine is there.
![vicls](https://cloud.githubusercontent.com/assets/13767357/16420507/8b43fd08-3d1f-11e6-9fdd-4434613a0749.jpg)

**Comment by carsonpadawon** [comment]
sorry, reopening this issue

**Comment by mdubya66** [comment]
hi @carsonpadawon. We won't be fixing this. You should run make clean and it should delete the bin directory.

**Comment by hickeng** [comment]
@carsonpadawon if you run `make clean` then it'll delete the bin directory. There's no `make distclean` so we've no way to clear everything but the yum cache and iso staging.
