### ISSUE TITLE
Document that container VMs only support root user

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1258]
Per https://github.com/vmware/vic/issues/725.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/1279 for the future implementation of support of non-root users in container VMs.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1279 is now in the icebox. We do mention that only root user is supported in the release notes for TP3, but if this is going to be the final behaviour for 1.0, we need to mention it in the main docs rather than in RNs. 

@mdubya66 can you please confirm that we'll only support root user in VIC 1.0 GA? Thanks!

**Comment by stuclem** [comment]
For inclusion in a Limitations topics in the App Dev book.

**Comment by npakrasi** [comment]
Adding to the Limitations topic.
