### ISSUE TITLE
vic-machine create.log not providing the right information on failure

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1262]
In the case when I put the wrong IP address in and vic-machine cannot connect to ESX system at all:

Expected error (what is printed to screen):
vic-machine-linux failed:  Failed to connect to https://192.168.1.1/sdk: Post https://192.168.1.1/sdk: dial tcp 192.168.1.1:443: i/o timeout' does not contain 'Installer completed successfully'

Actual create.log error:
INFO[2016-06-29T09:41:47-05:00] ### Installing VCH ####                      
INFO[2016-06-29T09:41:47-05:00] Generating certificate/key pair - private key in ./VCH-local-9017-key.pem 
ERRO[2016-06-29T09:42:17-05:00] Creation cannot continue: failed to create validator

**Comment by emlin** [comment]
Interesting. We didn't actually log out every errors we got before return to main method.
