### ISSUE TITLE
Document how to change root password of VCH appliance

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1264]
Per https://github.com/vmware/vic/issues/1218.

**Comment by stuclem** [comment]
@gigawhitlocks, since you are the owner of https://github.com/vmware/vic/issues/1218, do you have any info on how we can change the VCH appliance SSH root password?

Thanks!

**Comment by corrieb** [comment]
@stuclem The problem is that nothing persists in the appliance, so we don't currently having a way of changing the password in a manner that persists beyond reboots. We still need to solve that

**Comment by stuclem** [comment]
@corrieb, so, what do we need to document right now? That the pw is randomly generated with each reboot?

**Comment by stuclem** [comment]
@corrieb, is https://github.com/vmware/vic/issues/1218 going to be resolved for onsite beta?

**Comment by stuclem** [comment]
SSH is reenabled in PR https://github.com/vmware/vic/pull/1622.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1622 is still open, pending further investigations/changes.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1622 was dropped in favour of https://github.com/vmware/vic/pull/2555 (merged)

**Comment by hickeng** [comment]
@stuclem FYI, it's not so much changing the root password as it is setting it temporarily. If the appliance is rebooted, root login will be disable again and there will be no password.

running vic-machine debug has the following effects, which combine:
```
--rootpwd # sets the root password and enables console login
--authorized-key # places the contents of the specified file into /root/.ssh/authorized-keys
--enable-ssh # enables ssh server - must be combined with one of the above to have an effect
```

**Comment by stuclem** [comment]
Closing this one in favour of https://github.com/vmware/vic/issues/2678.
