### ISSUE TITLE
Command line for container persists in subsequent creates with the same image

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1265]
`docker create -it busybox /bin/ip addr`

And then run the subsequently created container.

Now create another container:
`docker create -it busybox`
(sans the command)

Run the container, and it runs the command from the previous run of the first container.

**Comment by sflxn** [comment]
I think I know what this is.  It's tied to #1144.  Once that is complete.  This issue should go away.

**Comment by sflxn** [comment]
Talked to @mdubya66.  Closing this issue as it exist because #1144 was not done.  We can call it a duplicate also.  All semantics.

**Comment by hickeng** [comment]
Bugs should stay open until they have been validated as fixed.

**Comment by mdubya66** [comment]
load balancing the team, passing this to @jzt
