### ISSUE TITLE
Dockerfile STOPSIGNAL support

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1268]
Use the dockerfile STOPSIGNAL value as the signal to deliver to the container.
If the container doesn't stop after `docker personality defined timeout` (I believe that was 15s) then send SIGTERM.

**Comment by corrieb** [comment]
@dougm assigning to you for assessment and priority as part of the signal work

**Comment by dougm** [comment]
@hickeng and I are going to pair up on this one tomorrow, should be straightforward.
