### ISSUE TITLE
Milestone: non-root users inside containers

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1279]
Currently we only support root users inside containers. @stuclem: We should document why this is not a high priority. Ping myself or @hickeng for info.

**Comment by mdubya66** [comment]
Moving to Backlog. This needs more details and needs to be documented.

**Comment by stuclem** [comment]
This issue is included as a known issue in the release notes for TP3.

**Comment by compendius** [comment]
Is  --cap-drop supported? For example  --cap-drop ALL . This would limit root capabilities in a container

**Comment by hickeng** [comment]
@compendius The containers are isolated VMs so --cap-drop doesn't add additional security from the point of view of container isolation as that's provided by the hypervisor, not the kernel.

You could use it _within_ the scope of a container if wanting to isolate processes further for some reason.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by hickeng** [comment]
This was closed by #4385
