### ISSUE TITLE
Create guest package for vsphere

### ISSUE THREAD

**Issue by dougm** [vmware/vic#128]
Within the existing bonneville-daemon repo we have several places where vsphere objects are mapped to devices within the guest.  This functionality is not docker specific and can be moved to vic/pkg/vsphere/guest.

See bonneville-daemon/daemon/modules/vmware/driver.go for the existing code.

It should be possible to implement unit tests for these functions without a vsphere connection.  See govmomi/object/virtual_device_list_test.go for examples.

Let's start with these:
- [ ] vSphere port group/switch to guest network interface (See "// determine which nic is on the container network")
- [ ] vSphere port group/switch to guest IP address - (See "// figure out our ip address")
- [ ] VMDK to guest /dev node (See verifyParavirtualScsiController)

**Comment by hickeng** [comment]
The mapping of vNIC to pci slot is currently in the tether util code - if this is split out into a separate package (and it should be) then that package should be very limited and not include govmomi code (the tether should not need any govmomi constructs as it doesn't talk to a vmomi API) - this will help keep size and compile times down.

**Comment by mdubya66** [comment]
making medium for incusion in 1.1. it could get moved out

**Comment by dougm** [comment]
This work has been done already, either ended up as separate issues or PRs without mention of this issue.
