### ISSUE TITLE
Document how to set up an offline registry with Harbour

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1282]
Following email discussion with Karthik and the Harbour team, we might need to bundle [Harbour](https://github.com/vmware/harbor) with VIC, to allow customers who do not have an external internet connection to use a private, offline Docker registry.

Notes from call with Stuart, Bobby (Jun) Zhang (@bobbyjunzhang) and Henry (Haining) Zhang (@hainingzhang)  on 2016-06-30:
- VIC needs an offline Docker registry for users who do not have a connection to the external internet.
- Bundling Harbour with VIC is a potential solution.
- Harbour is based on the Docker registry, with enterprise features on top, such as access control and a UI.
- Question for @karthik-narayan: do we want to include the Harbour bits alongside the VIC bits, in the VIC download?
- Docs are in Github at https://github.com/vmware/harbor/tree/master/docs. 
- Docs are currently for online installation – we need docs for offline install. 
- Question for @karthik-narayan: do we want to include the docs for offline installation of Harbour in the VIC docs, or just reference them from the VIC docs? Either way, they need to be written, it’s just a question of where we post them. I vote for bundling with VIC.

**Comment by karthik-narayan** [comment]
@stuclem We should point to the Harbor bits, but should not own the responsibility of uploading or maintaining them. 

I'm okay either way when it comes to bundling. That said, when we generate a PDF, I'd like this included in there.

**Comment by mdubya66** [comment]
IMO this should be post GA

**Comment by karthik-narayan** [comment]
That's how I've been imaging it, although in the examples we give I'd like to say if you are using harbor here is how you'd create a a VCH to point to it. Similarly when you run your first container - if you are using harbor, it comes bundled with image x and this is how you'd run it. Otherwise point the user to the harbor docs for setup and install etc.

**Comment by stuclem** [comment]
OK, thanks @karthik-narayan and @mdubya66. Will do.

**Comment by bobbyjunzhang** [comment]
@stuclem Thank you for the great summary.
@karthik-narayan We, the Harbor team, will own the responsibility of uploading and maintaining the Harbor bits. I believe for an environment without Internet connection, it makes sense to bundle the VIC and Harbor for better usability.

Our team can start to: i) work on an offline installer for Harbor and ii) deploy Harbor to VIC and see how it works. Harbor follows the micro-services architecture and an instance creates 5 to 6 containers by default. We want to make sure this works well with VIC.

Please let us know if this plan sounds okay to you. Understanding that the VIC team is busy with the GA, we would like to make it a priority and drive this effort as much as possible from our side.

**Comment by stuclem** [comment]
Per https://github.com/vmware/vic/issues/1745, Harbour integration might not happen for GA.

**Comment by bobbyjunzhang** [comment]
More discussions at #1745 to re-consider Harbor for VIC GA.

**Comment by mdubya66** [comment]
adding @corrieb and @karthik-narayan

**Comment by stuclem** [comment]
See https://github.com/vmware/vic-product/tree/master/docs/setup/alpha for some preliminary docs about Harbor/Admiral by @corrieb.

**Comment by stuclem** [comment]
@sflxn added an example of an insecure registry in https://github.com/vmware/vic/pull/2738.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/2846

**Comment by stuclem** [comment]
According to @hainingzhang (by email) the only requirement for Harbor deployment is: "Since Harbor is an OVA, the only requirement is VC 5.x+, and some disk space in the datastore. "

**Comment by hainingzhang** [comment]
@stuclem Here is a more formal requirement description:

1. VC 5.x+
2. Two(2) vCPUs, 4GB memory
3. 100GB disk space in datastore for OVA and image data
4. An external network that Harbor VM can connect to.

**Comment by hainingzhang** [comment]
@stuclem  We have created a draft of OVA deployment and configuration guide. This can be useful for your information: (To be merged to Harbor's repo)
https://github.com/ywk253100/harbor/blob/dd70dc89d347062202c08c15d8728264cdd6367e/docs/installation_guide_ova.md

Also Harbor's install guide and user guide are helpful for writing the document:
https://github.com/vmware/harbor/blob/master/docs/user_guide.md
https://github.com/vmware/harbor/blob/master/docs/installation_guide.md

**Comment by stuclem** [comment]
Fabulous, thank you very much @hainingzhang !

**Comment by stuclem** [comment]
Removing Harbor from the Docs for 0.7 milestone as we are currently covered by the doc by @mreferre on github. Integration of Harbor into the VIC docs will happen for GA. Decision confirmed by Karthik and Jyothi.

**Comment by mdubya66** [comment]
if the plan is to convert the VIC engine docs into VIC Product docs we should probably look at, post GA, moving the docs to the vic-product repo.

**Comment by stuclem** [comment]
Moving the discussion about where to publish the docs to https://github.com/vmware/vic/issues/2792, since this issue is about Harbor.

**Comment by stuclem** [comment]
Not required for 0.7, so moving back to backlog.

**Comment by stuclem** [comment]
We can base the Harbor section of the VIC docs on the following docs by Massimo:

- [Installing and configuring Harbor](https://github.com/vmware/vic-product/blob/master/docs/setup/beta/install-configure-harbor.md)
- [Using Harbor](https://github.com/vmware/vic-product/blob/master/docs/setup/beta/using-harbor.md)

**Comment by stuclem** [comment]
See https://github.com/vmware/vic/pull/3225 for engineering docs about setting up Harbor.

**Comment by stuclem** [comment]
See PR https://github.com/vmware/vic/pull/3304 for more updates to the engineering docs for Harbor.

**Comment by stuclem** [comment]
@npakrasi will take the Using Harbor info and incorporate it into Admin, @stuclem will do the install part.

**Comment by stuclem** [comment]
Note that the official name for Harbor is **vSphere Integrated Containers Registry**.

**Comment by npakrasi** [comment]
Added topics to address private registry using Harbor: https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_admin/private_registry_with_harbor.md
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/deploy_vic_with_harbor.md

**Comment by stuclem** [comment]
Want to make another pass over this and probably expand. Needs to tie in with the overall strategy for Harbor doc.

**Comment by stuclem** [comment]
This will be rendered redundant once we have the unified installer.
