### ISSUE TITLE
Failed to get default registry endpoint from daemon

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1287]
Saw the following error from build 2411 and VCH-2411-3467:

Warning: failed to get default registry endpoint from daemon (An error occurred trying to connect: Get https://192.168.31.142:2375/v1.21/info: tls: oversized record received with length 20527). Using system default: https://index.docker.io/v1/
An error occurred trying to connect: Post https://192.168.31.142:2375/v1.21/images/create?fromImage=busybox%3Alatest: tls: oversized record received with length 20527

[integration_test_logs_2411_1467259822.zip](https://github.com/vmware/vic/files/341566/integration_test_logs_2411_1467259822.zip)

**Comment by mdubya66** [comment]
This is in code that's not merged.
