### ISSUE TITLE
Document TP3 workaround for docker kill

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1310]
Per an email exchange between @mdubya66 and @karthik-narayan, docker kill will not be implemented in TP3. So, we need to document an alternate means of stopping containers in TP3.

Apparently, @hickeng has the info.

**Comment by hickeng** [comment]
@stuclem `docker stop` works currently, but directly powers down the VM which may result in filesystem corruption (should be fixed on next boot, but still an issue). We are still aiming to get a polite form of stop in over the weekend, but don't know if we'll make it - this depends on #1267 and the actual milestone is #438 

The lack of `docker kill` means a user cannot send arbitrary signals to the container process. There is no workaround available.

**Comment by stuclem** [comment]
@hickeng, thanks. 

@npakrasi, can you please add this to the app dev doc? Thanks!

**Comment by stuclem** [comment]
The workaround for TP3 is in https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md. Moving this to Onsite Beta for the proper implementation of docker kill.

**Comment by stuclem** [comment]
Actually, the doc for the proper implementation of docker kill is tracked in https://github.com/vmware/vic/issues/954. This one was for the TP3 workaround. Marking as fixed.
