### ISSUE TITLE
docker rm to a running container returns incorrect output

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1311]
Actual:
Error response from daemon: server error from portlayer

Expected:
Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-11-Docker-RM.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by corrieb** [comment]
I'd like to see this fixed for onsite. It's highly visible
