### ISSUE TITLE
force remove of a running container fails

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1312]
Trying to force remove a running container:
docker ${params} rm -f ${container}

Actual:
Error response from daemon: server error from portlayer

Expected:
Container should be removed

**Comment by hickeng** [comment]
@mdubya66 Does this have to be TP3? We're running short on time and bodies.

**Comment by mdubya66** [comment]
flag it for documentation?

**Comment by hickeng** [comment]
@mdubya66 yup. Given the separate commands function. We're thrashing enough at the moment getting the remaining PRs in that I'd rather save what spare time we have for bugs.

**Comment by mdubya66** [comment]
@stuclem @npakrasi please add this to the document in release notes list

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-11-Docker-RM.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by stuclem** [comment]
This issue is included as a known issue in the release notes for TP3.

**Comment by corrieb** [comment]
@fdawg4l unless this is relatively trivial to implement, I don't feel this is high priority for onsite. Please assess

**Comment by fdawg4l** [comment]
I honestly couldn't tell you one way or the other.  Will take a look when cycles appear.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
