### ISSUE TITLE
Removal of a stopped container results in the datastore not being cleaned

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1313]
docker ${params} pull busybox
docker ${params} create busybox ls
docker ${params} start ${container}
docker ${params} rm ${container}

Results in the vm being removed but the datastore doesn't get cleaned up.

**Comment by cgtexmex** [comment]
This appears to be caused by the fact that we create a container VM specific log and debug file upon container start -- I believe these are created and managed by the tether.  esx is deleting from disk all the files it's aware of and since it's unaware of those it leaves them behind.

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-11-Docker-RM.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by hickeng** [comment]
@corrieb could you try re-enabling this in your local integration build? I'm in the middle of redeploying dev box but this should now be fixed by #1441

**Comment by corrieb** [comment]
@hickeng will do

**Comment by matthewavery** [comment]
@corrieb I am closing this after confirming that it is resolved by #1441.

**Comment by andrewtchin** [comment]
the build is broken! :trollface:

**Comment by matthewavery** [comment]
The test has now be re-enabled in master.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
