### ISSUE TITLE
docker network rm using the ID of the network returns success but doesn't remove the network

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1318]
'docker -H 192.168.254.184:2376 --tls network rm 2a1d449948b4b46a03e963ee7c35086a'
${rc} = 0 	
${output} = 

'NETWORK ID          NAME                DRIVER
893616515284        bridge              bridge              
2a1d449948b4        test-network3       bridge

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-18-Docker-Network-RM.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by corrieb** [comment]
@hmahmood can you comment on whether this is still an issue?

**Comment by hmahmood** [comment]
@corrieb still an issue
