### ISSUE TITLE
Stopping a never started container throws an error

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1319]
Actual:
Error response from daemon: container 5fe44c11c131cc04fcf595cfabc0722e9aa77cd2f55db07e7d0d7d46d1cf1e74 not found

Expected:
Non-VIC docker just returns without error.

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-7-Docker-Stop.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx
