### ISSUE TITLE
Stopping a container without a -t flag should default to 10 seconds

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1320]
Currently stopping a container does so immediately, docker defaults to 10 seconds before stopping a container unless you specify -t flag.

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-7-Docker-Stop.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by dougm** [comment]
Depends on #1268

**Comment by dougm** [comment]
Note that 'docker stop' does send the stop signal (default is SIGTERM) immediately.  The -t flag is a grace period between sending the stop signal and sending a SIGKILL.  So, if SIGTERM does not stop the container, it will wait 10 seconds by default before sending a SIGKILL.
