### ISSUE TITLE
Stop does not honor -t flag

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1321]
Running docker -t 2 should stop a running container in about 2 seconds.  Currently, VIC stops the container immediately and returns success regardless of what you specify in the -t flag.

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-7-Docker-Stop.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by dougm** [comment]
See #1320 - the '-t' flag does not wait to stop, it is a grace period between SIGTERM and SIGKILL.
Though we should still test that the flag is honored in this case.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
