### ISSUE TITLE
Integrate VC event stream with Exec Layer

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1329]
We need to integrate the VC event stream for the following:
* network
  * unbind of IP address on power off
  * update of DNS
* exec
  * implementation of Wait
  * efficient reporting of container state
* interaction
  * reject pending requests for attach sessions

**Comment by hickeng** [comment]
assigned to clint for initial integration - exec as a testbed.

**Comment by cgtexmex** [comment]
Since this initial event stream will only deal with the exec layer, I've changed the name of the issue.  Subsequent issues for the other layers will be created.
