### ISSUE TITLE
Easily identify relationship between VCH <-> container <-> volume

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1339]
**VIC Version:**

0.1 / master / 2513

**Code**

``` ts
Opening this issue based on a conversation with Faiyaz and others to see if we can easily identify the relationship between VCH <-> Containers <-> Volumes. Matt W asked me to file it. Here is the crux of the request:

"I’m a vSphere Admin, and I have 50 developers. I’ve deployed 50 VCHs, each with their own folder on my single VSAN datastore. One of these developers have come back to me and said that some of his containers no longer have access to the persistent volume that he created.

Now I need to engage GSS, and they tell me to gather the logs from the environment (could be 5 ESXi hosts)."

So now we need the GSS guy/girl to focus in quickly, so they are not going back and forth with simplistic questions about the relationship between VCH <-> container <-> volume. Can we help them to quickly understand:

Which VCH?
Which ESXi host is the VCH?
Which containers?
Which folder on the VSAN datastore?
Which volumes in that folder?

I was just thinking how we could easily track the relationship amongst the above set of constituent objects for troubleshooting purposes?

```

**Expected behavior:**

That from the logs, one should quickly be able to determine the relationship between a VCH, its containers and the volumes used by those containers.

**Actual behavior:**

Right now, if the folder name is not specified for the volume, the folder is given the same name as the actual datastore on which it resides. I think this may lead to complexity issues if an admin deploys lots of VCHs but deploys volumes all on the same datastore.

**Comment by mdubya66** [comment]
This seems like a pretty common usecase and one we should try to address for VIC GA. @hickeng to evaluate the potential. @karthik-narayan to validate the requirement for GA

**Comment by hickeng** [comment]
@cormachogan One of the primary purposes of vicadmin is to furnish information that allows for this style of correlation. I spent a small chunk of time on friday with @reddolan going over why vicadmin exists and its purpose.

There are two things we can do here immediately however:
1. add data to docker info that allows a viadmin to identify the VCH in vSphere.
2. capture those parts of the VCH configuration that do not hold credentials in the log bundle.

**Comment by cormachogan** [comment]
Sounds good @hickeng - once a support person has all they need in one log capture, then we're good to go. There is nothing worse than going forward and back to a customer for snippets of info.

**Comment by zjs** [comment]
Closing as all children have been resolved. Further improvement may be valuable, but should be driven by more recent user feedback.
