### ISSUE TITLE
vic-machine: register extension failed for "incorrect parameter"

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1346]
←[31mERRO←[0m[2016-07-05T18:20:52+03:00] vic-machine-windows failed: Error registering VCH vSphere extension: ServerFaultCode: A general system error occurred: The parameter is incorrect.

The VC is one windows VC, still not sure if it's a common Windows VC issue or specific to @stuclem env.

**Comment by dougm** [comment]
The govc extension test works against Stuart's env (see https://github.com/vmware/govmomi/blob/master/govc/test/extension.bats#L19-L29)

```
id=com.vmware.test
govc extension.register $id <<EOS
  {
    "Description": {
      "Label": "govc",
      "Summary": "Go interface to vCenter"
    },
    "Key": "${id}",
    "Company": "VMware, Inc.",
    "Version": "0.2.0"
  }
EOS
govc extension.info com.vmware.test
...
govc extension.unregister com.vmware.test
```

Note that you can use 'govc extension.info' without an argument to list all extensions.  For example, in this env:
```
govc extension.info | grep com.vmware.vic
Name:                   com.vmware.vic.420cbc34-fba7-9f3e-8d11-00e3a1c60ba9
Name:                   com.vmware.vic.420c49f2-ad38-1faf-d9f1-e5bb9317c22a
Name:                   com.vmware.vic.420cfaae-6365-b1cf-bae7-de0bd0cc6eba
```

**Comment by gigawhitlocks** [comment]
This should be fixed now.

**Comment by stuclem** [comment]
Yep, deployment to a Windows-based VC now works for me. Thanks @gigawhitlocks!
