### ISSUE TITLE
Document VIC implementations of docker run and docker create in finer detail

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1355]
Per comment by @mdubya66 in PR https://github.com/vmware/vic/pull/1352, we need to provide more granular descriptions of what is supported for each Docker command, along the lines of the following files (created by @sflxn):

https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/CLI-COMPATIBILITY.md
https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/API-COMPATIBILITY.md
https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/COMPOSE-COMPATIBILITY.md

**Comment by stuclem** [comment]
@npakrasi please can you work with @sflxn (Loc) to obtain this info for TP3/Onsite Beta?

**Comment by stuclem** [comment]
Volume creation and attach functionality is added to docker container create in https://github.com/vmware/vic/issues/1169

**Comment by stuclem** [comment]
Some progress made here, but moving this to GA for further work.

**Comment by stuclem** [comment]
We already have separate sections for `volume create` and `network create` (although network create needs more work):
- [Volumes](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md)
- [Networks](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/network_use_cases.md)

What we need are new topics that provide more details about the differences between VIC and Docker for the following Docker commands:
- `docker create`, inspired by the table in [Loc's doc](https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/CLI-COMPATIBILITY.md#create).
- [`docker run`](https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/CLI-COMPATIBILITY.md#run), if this is not already covered in the topic on supported operations.
- `docker compose`, when it's implemented, but that's covered by https://github.com/vmware/vic/issues/831.

**Comment by stuclem** [comment]
Changed title to be more specific to the required task.

**Comment by stuclem** [comment]
According to @hickeng in https://github.com/vmware/vic/issues/2764, we do not support  `docker run --net=host`.

**Comment by npakrasi** [comment]
Instead of creating a separate file with details on parameters, I'm including them in the Supported Docker Commands table. Loc's doc for docker create is out of date.

**Comment by npakrasi** [comment]
Added to docker run that --net=host is not supported.

**Comment by stuclem** [comment]
New Docker options/parameters will be tracked in new issues. Closing.

**Comment by hickeng** [comment]
@stuclem @npakrasi We do not support `--net=host`, but there should be a reference to the use of `--container-network` vic-machine option as a possible alternative approach.

**Comment by stuclem** [comment]
@npakrasi can you please update accordingly, and link to https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--container-network? Thanks!

**Comment by stuclem** [comment]
Actually, I wanted to push an update to github.io, so I went in and did this. 

https://github.com/stuclem/vic/commit/21cbcd9dd58086bea31e7d47a1a8c78c28c2528a
