### ISSUE TITLE
vicadmin logs include vsphere login credentials

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1359]
build 2588.

init.log in vicadmin contains entries with vsphere login credentials.

example: 
`time="2016-06-18T02:35:41Z" level=info msg="Launching command []string{\"/sbin/port-layer-server\", \"--host=localhost\", \"--port=8080\", \"--insecure\", \"--sdk=https://root:Vmware%2123@172.16.252.131/sdk\", \"--datacenter=ha-datacenter\", \"--cluster=/ha-datacenter/host/localhost.localdomain\", \"--pool=/ha-datacenter/host/localhost.localdomain/Resources\", \"--datastore=datastore1\", \"--vch=vic-demo\"}" `

Let's scrub vsphere login creds from all logs.

**Comment by hickeng** [comment]
There's only one way to resolve this easily for now - squash the logging of the detail command that's being launched.
This should be corrected in a GA timeframe by moving the session package to a usage pattern closer to that of logrus, namely you include it then use the package as a connection directly.

**Comment by hickeng** [comment]
Added #1387 to track the correct fix for this - this is integral to the remainder of the extraconfig migration work.
