### ISSUE TITLE
Port mapping data for UI

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#1360]
Please provide the guestInfo key to pull the port mapping data when ready. This will be displayed on the "Container" portlet under the VM summary section.

**Comment by corrieb** [comment]
Assigning to @hmahmood. This should be trivial, but needs an owner

**Comment by jooskim** [comment]
Confirmed with Hasan that port mapping info is now available in the extraConfig array. Will finish the Container VM Portlet soon.

**Comment by jooskim** [comment]
Done
