### ISSUE TITLE
vic-machine certificate related parameters

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1363]
Currently we use --generate-cert/--key and --cert parameters but they are little bit confusing instead I suggest following;

* vic-machine ....
   will generate self signed certificate and enable TLS
* vic-machine --no-tls
   will disable TLS support
* vic-machine --cert ... --key ...
   will use the provided cert/key pair

**Comment by mdubya66** [comment]
agreed. making an Onsite requirement
