### ISSUE TITLE
Add VCH info to `docker info` output to identify VCH

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1364]
Provide a VIC user with enough information that they can unambiguously identify the VCH they're using to a viadmin (VCH name in the docker info output will do for now).

**Comment by corrieb** [comment]
I'd nominate this as a relatively important thing to have for onsite.

@fdawg4l assigning to you to give this an owner, but can easily reassign if necessary

**Comment by fdawg4l** [comment]
@caglar10ur i nominate you.  You can go ahead and nominate someone else if you feel like it.

**Comment by sflxn** [comment]
Hey, how is this different from #1390?  It appears this sounds very similar and is nearly done.  You all can look in #1390 to see what values is now retrieved from the VCH and exposed to docker info.  If the data are the same, then we should just close this issue as a duplicate.

**Comment by sflxn** [comment]
PR #1572 takes care of #1390.  If this issue is different, then we can add the additional information on top of #1572.

**Comment by fdawg4l** [comment]
```
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker -H 192.168.8.131:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Storage Driver: vSphere Integrated Containers Backend Engine
vSphere Integrated Containers Backend Engine: RUNNING
 VCH mhz limit: 4484 Mhz
 VCH memory limit: 840 MiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.0.0
Execution Driver: vSphere Integrated Containers Backend Engine
Plugins: 
 Volume: voluums
 Network: bridge
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 4484
Total Memory: 840 MiB
Name: virtual-container-host  <<< -  Looks like we're doing this now.
ID: vSphere Integrated Containers
Docker Root Dir: 
Debug mode (client): false
Debug mode (server): false
Registry: registry-1.docker.io
```

**Comment by fdawg4l** [comment]
I think we have enough info to close this but leaving it to you @caglar10ur to make the call.

**Comment by mdubya66** [comment]
Closing per @hickeng
