### ISSUE TITLE
Multiple unit test failures against VC unless Datacenter is called "ha-datacenter" 

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1365]
We are currently unable to run our unit tests cleanly against a custom VC target because "/ha-datacenter" has been hard-coded in a variety of places as the root of resources, assuming ESX or a specific datacenter name in VC. The tests work, provided a datacenter is created with the appropriate name, but we need to be testing against realistic targets in which this won't be the case.

The correct solution to this is to pass in resource location URIs as environment variables.

@dougm has suggested that if we're making changes to these tests, that we also make sure that they function correctly with vcsim.

Tests impacted:
lib/install/validate/validator_test.go
pkg/vsphere/session/session_test.go
pkg/vsphere/test/test.go
pkg/vsphere/compute/rp_test.go
lib/spec/spec_test.go

Our test cleanup scripts also assume this here:
tests/resources/Util.robot

Workaround is to simply create a test Datacenter with the assumed name, which is easy, but a currently undocumented prerequisite. Correct fix is to make the tests more flexible.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage
