### ISSUE TITLE
Add sanitized VCH config into the log bundle.

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1366]
We need to be able to identify the VCH in vsphere, the containers it's responsible for, and the volumes/images it has created.  GSE will grab these bundles and it'll be up to us to figure out the topology.  

Create a debug or `.bundle` log which can list the topology in order to debug container / image / volume issues per vch.  Sanitize the output to remove any sensitive info (keys, IPs, etc) if necessary.

**Comment by emlin** [comment]
Supposed this is to add more information to current log zip file, including VCH and container relationship, and sanitized VCH configuration.

@fdawg4l Is the container configuration included here?

**Comment by emlin** [comment]
@fdawg4l @hickeng Could you please help to confirm on this issue? thanks

**Comment by fdawg4l** [comment]
@emlin I'm not sure what you're asking.  Apologies.  

For clarity, I think we want a file in the log bundle that includes the output of `docker ps -a`, `docker images`, and `docker volume ls`.  Then, in another file, `docker inspect` for each container we found in `ps -a`.

@hickeng do you agree?

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by zjs** [comment]
This is a valid request, but has not to our knowledge prevented debugging. As such, it's unlikely that it would be fixed except perhaps as a broader effort.
