### ISSUE TITLE
vic-machine gives misleading error message when command is omitted

### ISSUE THREAD

**Issue by kjplatz** [vmware/vic#1369]
When running vic-machine-<arch> and specify options without a command, the error message given to the user is misleading; it indicates that a flag is provided but not defined.  This is particularly frustrating when issuing a very long command string and the error message does not correctly identify the user error.

**Expected behavior:**
ken@sager:~/vic/src/github.com/vmware/vic$ bin/vic-machine-linux --target=10.160.30.179

Error: No command provided.

**Actual behavior:**
ken@sager:~/vic/src/github.com/vmware/vic$ bin/vic-machine-linux --target=10.160.30.179
Incorrect Usage.

NAME:
   vic-machine-linux - Create and manage Virtual Container Hosts

USAGE:
   vic-machine-linux [global options] command [command options] [arguments...]
   
VERSION:
   -
   
COMMANDS:
     create   Deploy VCH
     delete   Delete VCH and associated resources
     inspect  Inspect VCH
     version  Show VIC version information

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
   
ERRO[0000] vic-machine-linux failed: flag provided but not defined: -target

**Comment by emlin** [comment]
I think this might be not easy to understand for one never use vic-machine, but the error message does show the correct information.
If no command specified, global options are only --version and --help, all others are wrong.
@kjplatz How do you think?

**Comment by emlin** [comment]
> Error: No command provided.

For this error message, actually it's wrong, cause we also support global option, --version and --help. It will be ok without any command specified.

**Comment by emlin** [comment]
Closed for it's by design.
