### ISSUE TITLE
Create an informative page consistent with VMware branding and identity

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#1373]
This issue involves:
-Creating an HTML template with Go
-Leveraging Clarity UI into the HTML template

**Comment by sgairo** [comment]
This issue involves:
-creating an HTML template with Go
-Leveraging Clarity UI into the HTML template

**Comment by stuclem** [comment]
Hi @sgairo, is this for the Summary page in the vSphere Web Client, or for some other Web presence?

**Comment by mdubya66** [comment]
it's for vicadmin

**Comment by reddolan** [comment]
Graphic prototype: https://github.com/vmware/vic-ux/blob/master/VIC-Admin/dashboard.png

**Comment by reddolan** [comment]
Coded prototype: https://github.com/vmware/vic-ux/blob/master/VIC-Admin/dashboard.html

Currently, it is only using pure Bootstrap with CDN hook-ins while the Clarity site is having issues. Once the site is back up, I will be working on getting more accurate source and tying in the styling from the Graphic proto.
