### ISSUE TITLE
Deleting the last container of an image on VC leads to subsequent create error

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1383]
This looks possibly like a tagging issue, but not sure. It only occurs on VC, not ESX.

Problem is that if you do a docker rm on a container that uses busybox, the next container to try to use busybox fails saying "Unable to find image 'busybox:latest' locally", but then faulting to "already exists" 

Here is how to reproduce:
```
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.67.145:2376 --tls pull busybox
Using default tag: latest
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete 
8ddc19f16526: Pull complete 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.67.145:2376 --tls create busybox
b9b4780b3bc307091720cf17d78d4b19c47bd9ee2bab5d34e77a7534765e8507
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.67.145:2376 --tls rm b9b4780b3bc307091720cf17d78d4b19c47bd9ee2bab5d34e77a7534765e8507
b9b4780b3bc307091720cf17d78d4b19c47bd9ee2bab5d34e77a7534765e8507
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.67.145:2376 --tls create busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
8ddc19f16526: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Image is up to date for library/busybox:latest
Error: No such image: busybox
```

**Comment by corrieb** [comment]
Exact same build on an ESX host:

vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.69.219:2376 --tls pull busybox
Using default tag: latest
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete 
8ddc19f16526: Pull complete 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.69.219:2376 --tls create busybox date
3590dd9f520d3e242a5a3ed7ad36143e63a2da4f5dc1471aa6d22b3e59c8854d
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.69.219:2376 --tls rm 3590dd9f520d3e242a5a3ed7ad36143e63a2da4f5dc1471aa6d22b3e59c8854d
3590dd9f520d3e242a5a3ed7ad36143e63a2da4f5dc1471aa6d22b3e59c8854d
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.69.219:2376 --tls create busybox date
17d540586dc622081e8e3b87f157fc492c68ac9b25ab4e417e8442e13aea952a
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.69.219:2376 --tls rm 17d540586dc622081e8e3b87f157fc492c68ac9b25ab4e417e8442e13aea952a
17d540586dc622081e8e3b87f157fc492c68ac9b25ab4e417e8442e13aea952a
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.69.219:2376 --tls create busybox date
8cf90c7ec3016520b577a4738efcdb7467027fdf2d461e41df10702c378d2853
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ sudo ./vic-machine-linux delete --target=10.118.68.168 --user root --compute-resource /ha-datacenter/host/TestCluster/Resources/deploy-test --pa

**Comment by corrieb** [comment]
Interesting to note also that if you create two containers and rm one of them, you can create more. The error only seems to be evident when you've deleted the last container to use the image.

```
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls pull busybox
Using default tag: latest
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete 
8ddc19f16526: Pull complete 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls create busybox date
2b7f851ae241c7249634c1d969d9cd664263e93f787a65089a4a08b76b06621d
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls create busybox date
2d798327400e8213f9fa35ca1b655174f8b2310a0f8c4b5aceafbdc9e3998e74
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls rm 2d798327400e8213f9fa35ca1b655174f8b2310a0f8c4b5aceafbdc9e3998e74
2d798327400e8213f9fa35ca1b655174f8b2310a0f8c4b5aceafbdc9e3998e74
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls create busybox date
f405f5fc1e85be3c741d026fe69fcd6ee7ca9dc4c80a8c789c4b0cf04a961578
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls rm f405f5fc1e85be3c741d026fe69fcd6ee7ca9dc4c80a8c789c4b0cf04a961578
f405f5fc1e85be3c741d026fe69fcd6ee7ca9dc4c80a8c789c4b0cf04a961578
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls rm 2b7f851ae241c7249634c1d969d9cd664263e93f787a65089a4a08b76b06621d
2b7f851ae241c7249634c1d969d9cd664263e93f787a65089a4a08b76b06621d
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic/bin$ docker -H 10.118.66.254:2376 --tls create busybox date
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
8ddc19f16526: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Image is up to date for library/busybox:latest
Error: No such image: busybox
```

**Comment by mdubya66** [comment]
Moving to To Do for evaluation. If pervasive this might be a TP3 stopper. assigning to @hickeng for initial eval

**Comment by fdawg4l** [comment]
cc @cgtexmex (because I think you're familiar with how the name cache works).  Please ping if the image storage piece is lying somewhere about an image not existing when it actually does.  The map is immutable but that doesn't mean there isn't possibly a bug.

**Comment by cgtexmex** [comment]
@jzt has been working the most closely with the image cache, so ping...

**Comment by hickeng** [comment]
This is due to the use of vm.Destroy while disks are still attached. When run against VC that causes a disk chain to be deleted rather than just the leaf. We have two options:
First is:
1. reconfigure VM to remove the disks
2. delete the VM
3. delete the leaf

Second is:
1. Add LowLevelProvisioningManager to govmomi
2. Call deleteVM with whitelist of disks to delete.

**Comment by corrieb** [comment]
Note that this would have been caught by the integration tests that's currently not running because #1313 is not yet closed

**Comment by corrieb** [comment]
@hickeng What did Bonneville do here? Any reason to do anything different?

Seems like Option 2 will be more efficient and more flexible

**Comment by corrieb** [comment]
George will get this done today
