### ISSUE TITLE
Turn session package into vmomi gateway

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1387]
There is a component in the architecture called [vmomi gateway](https://github.com/vmware/vic/blob/master/doc/design/components.md#vmomi-gateway). This hides the manipulation and access of credentials from the rest of the appliance components, and eventually allows them to be moved out of the appliance entirely.

The session package is being abused in various ways throughout the code and should be used as the base for vmomi gateway for now. This is not an ideal separation but is a functional one that allows for easy migration to an authenticating agent in the future.

**Comment by mdubya66** [comment]
@hickeng who should take this on?

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mdubya66** [comment]
related to port layer refactor, medium
