### ISSUE TITLE
Docker Info should get container count

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1389]
Docker info should use the docker ps infrastructure to get container count info.

**Comment by sflxn** [comment]
I have this done.  A PR can be issued and merged in for TP3 if desired.

**Comment by mdubya66** [comment]
before approving for TP3 i'd need an assessment of risk in pulling it in

**Comment by sflxn** [comment]
I don't see any risk in pulling this in.  It's just gathering data and displaying it.

**Comment by mdubya66** [comment]
OK, pull it in

**Comment by sflxn** [comment]
Just talked to @hickeng.  Given the load on our CI system right now, we're pushing this lower in priority since there are higher priority PR struggling to get through our CI system now.

**Comment by corrieb** [comment]
Now we're past TP3, let's get this closed out

**Comment by sflxn** [comment]
It's been merged.
