### ISSUE TITLE
Docker info should get reasonable values for vch info

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1390]
Docker info currently does not populate core count or memory limits.  The OS values are also data for the appliance VM itself.  We should get this info from guestinfo and govmomi.

depends on #861

**Comment by mdubya66** [comment]
Moving to Onsite Beta

**Comment by hickeng** [comment]
depends on #861

**Comment by sflxn** [comment]
Almost done with this.  Getting VCH mhz, memory limit.  Also getting vch os, version, and name from AboutInfo.  This is now in portlayer's misc section of portlayer.
