### ISSUE TITLE
docker: Failed to ping portlayer

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1397]
**VIC Version:**

0.1 / master / #2626

**Code**

On trying to test new build #2626, I hit the following problem when running docker cmds:
```
docker -H 10.27.33.118:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
docker: Failed to ping portlayer: Get http://127.0.0.1:8080/_ping: dial tcp 127.0.0.1:8080: getsockopt: connection refused.
See 'docker run --help'.
```

I could not connect to the logs via a browser either, but I could SSH.
Some log snippets:

init.log
```
time="2016-07-07T14:33:54Z" level=info msg="Launching command []string{\"/sbin/port-layer-server\", \"--host=localhost\", \"--port=8080\", \"--insecure\", \"--sdk=https://administrator%40vsphere.local@10.27.51.103\", \"--datacenter=CNA-DC\", \"--cluster=/CNA-DC/host/Mgmt\", \"--pool=/CNA-DC/host/Mgmt/Resources/COR_RP\", \"--datastore=isilion-nfs-01\", \"--vch=docker-appliance\"}"
time="2016-07-07T14:33:54Z" level=info msg="port-layer exit code: 1"
time="2016-07-07T14:33:54Z" level=error msg="unable to encode []*metadata.ExitLog (slice) for guestinfo..sessions|port-layer.diagnostics.exitlogs: *metadata.ExitLog is an unhandled type"
time="2016-07-07T14:33:54Z" level=info msg="Reload triggered"
time="2016-07-07T14:33:54Z" level=info msg="Triggered reload"
time="2016-07-07T14:33:54Z" level=info msg="Loading main configuration"
time="2016-07-07T14:33:54Z" level=info msg="Loaded executor config"
time="2016-07-07T14:33:54Z" level=info msg="setting ip address 10.27.33.118/20 for link client"
time="2016-07-07T14:33:54Z" level=warning msg="address 10.27.33.118/20 already set on interface client"
time="2016-07-07T14:33:54Z" level=info msg="setting ip address 10.27.33.118/20 for link client"
time="2016-07-07T14:33:54Z" level=warning msg="address 10.27.33.118/20 already set on interface client"
time="2016-07-07T14:33:54Z" level=info msg="setting ip address 10.27.33.118/20 for link client"
time="2016-07-07T14:33:54Z" level=warning msg="address 10.27.33.118/20 already set on interface client"
root@docker-appliance [ /var/log/vic ]#
```

portlayer.log
```
time="2016-07-07T14:29:12Z" level=info msg="Launching portlayer server server on 127.0.0.1:6063"
time="2016-07-07T14:29:12Z" level=fatal msg="configure_port_layer ERROR: Failed to connect to https://10.27.51.103/sdk: Post http
s://10.27.51.103/sdk: dial tcp 10.27.51.103:443: connect: network is unreachable"
```

I will copy down the full logs and attached them shortly.

**Expected behavior:**

**Actual behavior:**

**Comment by cormachogan** [comment]
So it looks like I can't get the logs from the VCH. However SSH is available if anyone wishes to log in.
```
ssh root@10.27.33.118
```

I'll leave it in place overnight.

**Comment by mlh78750** [comment]
`root@docker-appliance [ /var/log ]# ifconfig -a
bridge    Link encap:Ethernet  HWaddr 00:50:56:86:63:b9
          inet6 addr: fe80::250:56ff:fe86:63b9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:120 (120.0 B)  TX bytes:868 (868.0 B)

client    Link encap:Ethernet  HWaddr 00:50:56:86:20:93
          inet addr:10.27.33.118  Bcast:0.0.0.0  Mask:255.255.240.0
          inet6 addr: fe80::250:56ff:fe86:2093/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:66250 errors:0 dropped:2493 overruns:0 frame:0
          TX packets:3142 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5040413 (5.0 MB)  TX bytes:3196910 (3.1 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:12681 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12681 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:963290 (963.2 KB)  TX bytes:963290 (963.2 KB)`

**Comment by mlh78750** [comment]
`root@docker-appliance [ /var/log ]# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
10.27.32.0      0.0.0.0         255.255.240.0   U         0 0          0 client`

**Comment by mlh78750** [comment]
[var.log.vic.zip](https://github.com/vmware/vic/files/352464/var.log.vic.zip)

**Comment by mlh78750** [comment]
Looks like the network didn't get setup correctly for whatever reason. There was no default route and I had to add one to extract the logs

**Comment by hickeng** [comment]
vicadmin is listening on port 2378:
```
root@docker-appliance [ /tmp ]# netstat -an | grep 2378
tcp6       0      0 :::2378                 :::*                    LISTEN
```

I can curl from it from the appliance, but not connect to it from outside:
```
root@docker-appliance [ /tmp ]# curl -k https://10.27.33.118:2378
<html><head><title>VIC Admin</title></head><body><pre>
<a href="/logs.tar.gz">/logs.tar.gz</a><br/>
<a href="/container-logs.tar.gz">/container-logs.tar.gz</a><br/>
<a href="/logs/tail">/logs/tail</a><br/>
<a href="/logs/docker-personality.log">/logs/docker-personality.log</a><br/>
<a href="/logs/tail/docker-personality.log">/logs/tail/docker-personality.log</a><br/>
<a href="/logs/imagec.log">/logs/imagec.log</a><br/>
<a href="/logs/tail/imagec.log">/logs/tail/imagec.log</a><br/>
<a href="/logs/port-layer.log">/logs/port-layer.log</a><br/>
<a href="/logs/tail/port-layer.log">/logs/tail/port-layer.log</a><br/>
<a href="/logs/vicadmin.log">/logs/vicadmin.log</a><br/>
<a href="/logs/tail/vicadmin.log">/logs/tail/vicadmin.log</a><br/>
<a href="/logs/init.log">/logs/init.log</a><br/>
<a href="/logs/tail/init.log">/logs/tail/init.log</a><br/>
<a href="/">/</a><br/>
</pre></body></html>
```

Regarding the port-layer issue:
```
time="2016-07-07T15:12:01Z" level=fatal msg="configure_port_layer ERROR: Failed to connect to https://10.27.51.103/sdk: Post https://10.27.51.103/sdk: dial tcp 10.27.51.103:443: connect: network is unreachable"
time="2016-07-07T15:12:02Z" level=info msg="Launching portlayer server server on 127.0.0.1:6063"
time="2016-07-07T15:12:02Z" level=fatal msg="configure_port_layer ERROR: Failed to connect to https://10.27.51.103/sdk: Post https://10.27.51.103/sdk: dial tcp 10.27.51.103:443: connect: network is unreachable"
time="2016-07-07T15:12:02Z" level=info msg="Launching portlayer server server on 127.0.0.1:6063"
time="2016-07-07T15:12:02Z" level=debug msg="Logging into extension com.vmware.vic.420678b8-d938-de2c-535b-c29c3a1f5814"
time="2016-07-07T15:12:02Z" level=debug msg="Session Environment Info: " API Type=VirtualCenter API Version=6.0 Build=3634794 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=a0522635-224e-4171-92b1-7edaf726b39f Vendor="VMware, Inc." Version=6.0.0
time="2016-07-07T15:12:02Z" level=debug msg="vSphere resource cache populating..."
time="2016-07-07T15:12:02Z" level=debug msg="Cached dc: CNA-DC"
time="2016-07-07T15:12:02Z" level=debug msg="Cached cluster: /CNA-DC/host/Mgmt"
time="2016-07-07T15:12:02Z" level=debug msg="Cached ds: isilion-nfs-01"
time="2016-07-07T15:12:04Z" level=debug msg="Cached pool: /CNA-DC/host/Mgmt/Resources/COR_RP"
time="2016-07-07T15:12:04Z" level=debug msg="vSphere resource cache populated..."
```

The port layer suddenly came up cleanly after 5789 restart attempts.

**Comment by mlh78750** [comment]
@hickeng It came up because I manually added a default route. I wanted to pull the logs off the machine. If you look at the initial comments I posted you can see the network setup as I found it. After I captured that I added the route and started poking around. So I think this is something install/network related.

**Comment by cormachogan** [comment]
Command line used to create the VCH:

```
./vic-machine-linux create  --bridge-network Bridge-DPG --image-datastore isilion-nfs-01 -t 'administrator@vsphere.local:VMware123!@10.27.51.103'  --compute-resource Mgmt/COR_RP
```

**Comment by sgairo** [comment]
Is --external-network not needed here?

**Comment by cormachogan** [comment]
Should default to VM Network if not set. At least, it has been up to this build.

**Comment by hickeng** [comment]
@cormachogan yup - should still be the case. The virtual hardware config is correct as seen by the fact that it functions when the routing was repaired.

**Comment by mlh78750** [comment]
Looks like the external network defaulted and ended up on one a DPG. vic-machine should be checking for a valid setup including the use of DPG on networks when targeting a VC.

**Comment by mdubya66** [comment]
@hmahmood hasan is taking point on this. it may get moved out based on his investigations

**Comment by emlin** [comment]
vic-machine will check if the network exists, and will verify if bridge network is DPG, but not for all other networks.
This failure is not actually related to standard network or DPG, as long as the network is configured correctly, and reachable from outside, it should work well.
I verified with this version in my env, to install with both standard switch and DPG, the VCH works.
I will look at a little bit more for Cormac's VC, to see what's wrong.

**Comment by hmahmood** [comment]
The external/client interfaces are connected to a standard switch, as far as I can tell. But that network definitely has access to a DHCP server, since we get a DHCP assigned address. Something else is amiss here; continuing to investigate.

**Comment by hmahmood** [comment]
Here's the problem:
```
time="2016-07-07T14:29:11Z" level=info msg="DHCP response: IP=10.27.33.118, SubnetMask=fffff000, Gateway=<nil>, DNS=[], Lease Time=192h0m0s"
```
The gateway we get back from the DHCP server is nil, and there are no DNS servers. Maybe looking at the wrong options in the DHCP packet. If I had access to the console of the VCH I could debug this a little further, but we can't get to the VC web UI from here.

**Comment by hmahmood** [comment]
I switched the vch over to using systemd's DHCP client, and it got a different address, as well as the correct gateway/DNS. I think the problem is multiple DHCP servers on client network, and our client just picks the first offer we get, without verifying that we have a "router" in the packet.

**Comment by cormachogan** [comment]
Add the following to your local /etc/hosts to access the VC web UI:

10.27.51.103    vcsa-03.rainpole.com    vcsa-03

That should give you web access, and console access. VC login is administrator@vsphere.local/VMware123!

I have also asked the local IT team whether or not there could be other DHCP servers on the network. Since this is a network shared by all of GSS in Cork, it is a possibility.

**Comment by cormachogan** [comment]
Guys - I feel that this is more likely an issue with the dhcp client, and not DHCP servers.

I reverted back to VIC #2513, and tried to roll out busybox. Now this did not succeed, due to #2513 not having Doug's fix to include "export GOVMOMI_USE_SERVICE_TICKET_HOSTNAME=false" on the appliance. However, it had no issues trying to pull down the image.

Here are the differences:
#2513
```
root@photon-NaTv5i8IA [ /workspace/vic25 ]# docker -H 10.27.33.187:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Download complete
8ddc19f16526: Extracting [==================================================>] 667.6 kB/667.6 kB
docker: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc8201ff3f8 Message:Cannot complete the operation because the file or folder [isilion-nfs-01] VIC/42066555-578e-fa32-bc0c-0ef17fa49316/images/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd/4185ddbe03f83877b631b5e271a02f6f232de744ae4bfc48ce44216c706cb7fd.vmdk already exists}.
See 'docker run --help'.
root@photon-NaTv5i8IA [ /workspace/vic25 ]#
```

Now here is a test from #2626 - same environment, same command, same everything:

```
root@photon-NaTv5i8IA [ /workspace/vic26 ]# docker -H 10.27.33.189:2376 --tls run -it busybox                                          Unable to find image 'busybox:latest' locally
docker: Failed to ping portlayer: Get http://127.0.0.1:8080/_ping: dial tcp 127.0.0.1:8080: getsockopt: connection refused.
See 'docker run --help'.
root@photon-NaTv5i8IA [ /workspace/vic26 ]# 
```

I honestly think this changes to a regression in the client between #2513 and #2626.

**Comment by hmahmood** [comment]
@cormachogan you are right that the client behavior changed, since we implemented our own instead of using the one provided by systemd (don't want to go into reasons why we did this, but it was justified). The systemd client gets an IP address lease on a completely different subnet, which is why I think there is more than one dhcp server on the network. 

The proper fix is to fix our client code, but that demands some time. For now, I will fix the code so that it looks at all DHCP offers, and not just the first one. I will verify that this fixes the issue.

**Comment by hmahmood** [comment]
The client was not setting its client id in the discovery and request packets to the dhcp server. I believe some dhcp servers will not issue IP leases if this is not set. In addition, the parameter request list (option 55) was not set. Adding both these, I was able to get the gateway, dns, subnet mask and IP from the server.
```
root@docker-appliance [ ~ ]# ip route
default via 10.27.47.254 dev client
10.27.32.0/20 dev client  proto kernel  scope link  src 10.27.32.84
172.16.0.0/16 dev bridge  proto kernel  scope link  src 172.16.0.1
root@docker-appliance [ ~ ]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: client: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:86:7a:ed brd ff:ff:ff:ff:ff:ff
    inet 10.27.32.84/20 scope global client
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe86:7aed/64 scope link
       valid_lft forever preferred_lft forever
3: bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:86:af:c3 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/16 scope global bridge
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe86:afc3/64 scope link
       valid_lft forever preferred_lft forever
root@docker-appliance [ ~ ]# more /etc/resolv.conf
nameserver 10.16.142.110
nameserver 10.16.142.111
root@docker-appliance [ ~ ]# ping -c3 yahoo.com
PING yahoo.com (98.138.253.109) 56(84) bytes of data.
64 bytes from ir1.fp.vip.ne1.yahoo.com (98.138.253.109): icmp_seq=1 ttl=46 time=140 ms
64 bytes from ir1.fp.vip.ne1.yahoo.com (98.138.253.109): icmp_seq=2 ttl=46 time=140 ms
64 bytes from ir1.fp.vip.ne1.yahoo.com (98.138.253.109): icmp_seq=3 ttl=46 time=140 ms

--- yahoo.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 140.232/140.316/140.366/0.436 ms
```
