### ISSUE TITLE
Docker API Server:  Write a tool to help validate the docker swagger spec's models (not operations)

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#142]
From my experience with Docker pull and Swagger so far, I think I need some tool to help validate the correctness of the swagger spec we got (which originated from the dockerphp project) with actual requests coming from the Docker CLI and curl.  The current spec has so many mistakes that it would be too time consuming to address them and issues in go-swagger as we encounter them.

The proposal is a simple webserver that reads the swagger spec and waits for requests from either the docker cli or curl and outputs any conflicts in type expected, missing properties, etc.

**Comment by hickeng** [comment]
no longer using swagger to generate personality
