### ISSUE TITLE
Make imagec work as a library

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1439]
Currently the docker personality has no information about an image that it pulls. It delegates to imagec, who pulls an image and pushes it to the storage portlayer and quits. This requires the docker persona to send an update request to the cache, which makes a request to the portlayer to get a list of all layers currently stored in the portlayer. It then must iterate through that list, unmarshal the metadata for each layer to find layers that represent images, and cache the metadata for each image it finds.

imagec should be updated to work as a standalone binary or as a library. As a library, imagec could provide information to the docker persona about the image it just pulled. The docker persona can then add this metadata to the cache without having to trigger another request to the portlayer that will have to iterate over the entire layer list to find anything it needs to cache.

It needs to be refactored to use functions defined on a struct that can be instantiated once for each client making a call. This should solve any concurrency issues previously seen when two calls are trying to share the same progress output. Related to #1298.

**Comment by mdubya66** [comment]
@hickeng should this have been prioritized above some of the other Onsite work? It needs a milestone.

**Comment by jzt** [comment]
Most of the work on this is done, but there are two major issues left to be fixed:

1. There is a race condition that I am currently trying to track down wherein pulling an image with many layers results in a client-side `unexpected EOF`.

2. Docker handles multiple concurrent pulls of the same set of layers by sharing the progress update with each client. It keeps track of transfers currently in progress and signals each client with updates as needed. It's not necessarily trivial to add support for this, but we might be able to get away with using Docker's [xfer](https://github.com/docker/docker/tree/master/distribution/xfer) package. @hickeng do you have a particular preference for how to handle this in the meantime?
