### ISSUE TITLE
'stop' and 'rm' not working on Short container ids

### ISSUE THREAD

**Issue by carlsone** [vmware/vic#1446]
Running 'docker stop' and 'docker rm' on short container IDs gives the following error on VIC versions 2675 and 2745: 
 
Error response from daemon: No such container: <id>
 
$ ./docker/docker -H xxx:2376 --tls ps -a
...
1138c6349ed6        ubuntu              "sleep 20000"       19 hours ago        Stopped                                 desperate_bassi
5bc308a2a9f7        ubuntu              "sleep 20000"       19 hours ago        Running                                 fervent_shaw
 
$ ./docker/docker -H xxx:2376 --tls rm 1138c6349ed6
Error response from daemon: No such container: 1138c6349ed6
$ ./docker/docker -H xxx:2376 --tls stop 5bc308a2a9f7
Error response from daemon: No such container: 5bc308a2a9f7
 
The same commands work fine on long container ids.

**Comment by jzt** [comment]
I believe this was fixed in #1434, @caglar10ur can you confirm?

**Comment by mdubya66** [comment]
Assinging to @caglar10ur for confirmation of above comment. Please re-assign if inappropriate.

**Comment by caglar10ur** [comment]
They work now (just tested) so closing
