### ISSUE TITLE
Throttle port layer server restarts

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1450]
Related to #1430. Unless we throttle restarts, an unrecoverable error can end up generating alerts in vCenter due to CPU consumption

**Comment by mdubya66** [comment]
assigning to hickeng for initial triage and re-assignment.

**Comment by hickeng** [comment]
A simple exponential backoff with a cap of maybe 10sec should suffice for this.
It may require an update to the death records to log the time of death - inspecting the set of death records should make it evident if it's a new failure or we're in a backoff state.

**Comment by hickeng** [comment]
There's now a 3sec delay between restart attempts. Incredibly basic, but enough to stop soaking up arbitrary amounts of CPU.
