### ISSUE TITLE
Sometimes, after a fresh vic-machine install, containers starts up and shuts down immediately

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1457]
A couple of time testing docker attach on 'quiet' apps (one that doesn't output anything to stdout for a long period of time) after a fresh vic-machine install, the container vm starts up and shuts down immediately.

Sometimes, it will settle down after a few minutes.  Other times, I have to reinstall with vic-machine again.

Steps to repro:
- install with vic-machine.  my install params:

```
./vic-machine-linux create --target=192.168.218.207 --image-datastore=datastore1 --name=vic-docker --user=root --password=<xxxx> --compute-resource="/ha-datacenter/host/esxbox.localdomain/Resources" --bridge-network=vic-network
```
- execute docker --tls run busybox /bin/sh -c 'sleep 40; /bin/top'

**Comment by sflxn** [comment]
[logs.tar.gz](https://github.com/vmware/vic/files/360536/logs.tar.gz)
[container-logs.tar.gz](https://github.com/vmware/vic/files/360537/container-logs.tar.gz)

**Comment by mdubya66** [comment]
This needs an estimate @sflxn

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by mlh78750** [comment]
Anyone still seeing this? Marking as no-repro.. @sflxn if this is still an issue, please reopen.
