### ISSUE TITLE
Update kernel version

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1458]
For advanced routing in the case of containers with externally mapped networks we need a more involved routing setup:

> Multiple IP tables feature is available in linux-esx >= 4.4.8-7
> From yesterday daily build: 
> linux-esx-4.4.8-7.ph1.x86_64.rpm

FYI @caglar10ur @hmahmood

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by renmaosheng** [comment]
we already use latest photon os.
