### ISSUE TITLE
Link/Alias test insufficient

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1464]
The integration test for link support is insufficient. It tests that the command lines are considered valid and not rejected during start, but doesn't actually test the functionality.
Running through the link/alias command manually (having created the `first` container):
```
vagrant@devbox:~/vic$ docker --tls create --link first:1st -it busybox
0020e5fba191ba3b3c558a0123176b5080d84d2fb53244467bc03910bba4f534
vagrant@devbox:~/vic$ docker --tls start -ai 0020e5fba191ba3b3c558a0123176b5080d84d2fb53244467bc03910bba4f534
/ # ping first
PING first (172.16.0.2): 56 data bytes
64 bytes from 172.16.0.2: seq=0 ttl=64 time=4.790 ms
^C
--- first ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 4.790/4.790/4.790 ms
/ # ping 1st
ping: bad address '1st'
/ #
```

**Comment by hickeng** [comment]
assigned to @mhagen-vmware for fix or reassignment if necessary.

**Comment by caglar10ur** [comment]
we could start using docker run once https://github.com/vmware/vic/issues/1514 is resolved

**Comment by corrieb** [comment]
These tests also fail quite regularly FWIW - have never had time to diagnose

**Comment by caglar10ur** [comment]
Assigning myself as I started to change them
