### ISSUE TITLE
Document how to set static IP addresses for appliance

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1470]
Per https://github.com/vmware/vic/issues/1184.

**Comment by Simon321vmware** [comment]
@stuclem Does the Static IP for Appliance mean literally the VCH ? ;)

I have been recently trying to find a method to provide VCH with static IP, but I was unfortunate to find that so far only DHCP is working :(

**Comment by stuclem** [comment]
Hi @Simon321vmware yes, that means static IPs for the VCH. 

My understand at present is that only DHCP is supported, and that static IP will be in place for GA. @hmahmood, can you please confirm?

**Comment by mdubya66** [comment]
we plan to include #1184 for the GA

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1184 is now in progress.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1184 is implented in PR https://github.com/vmware/vic/pull/2548.

**Comment by andrewtchin** [comment]
This has been merged :-) 
Some notes for the doc:
* Specified static IP address and gateway must both be in CIDR format e.g. `1.1.1.1/24`
* User specified DNS servers (`--dns-server`) are ignored if a static IP is not specified for any networks and we use the DHCP provided DNS servers
* If using a mix of static IP addresses with user specified DNS servers and DHCP addresses, the VCH will have both the user specified DNS servers and DHCP provided DNS servers.
* Only one static IP address may be assigned to a port group. If more than one of client, external, or management networks share a port group, the user may only specify an IP address for one of those and the same address will be automatically used for the networks that share the port group
* Assigning the same subnet to multiple port groups is unsupported as this can cause routing problems. `vic-machine` warns if it detects this configuration from the user's static IP arguments.

**Comment by stuclem** [comment]
Fabulous, thanks @andrewtchin!

**Comment by stuclem** [comment]
The following new settings exist for `vic-machine create`:

-  `--client-network-gateway`
- `--client-network-ip`
- `--external-network-gateway`
- `--external-network-ip`
- `--management-network-gateway `
- `--management-network-ip`
- `--dns-server `

**Comment by stuclem** [comment]
Doc updates are in PR https://github.com/vmware/vic/pull/2714.

**Comment by stuclem** [comment]
Reviewed by @andrewtchin and closed in PR https://github.com/vmware/vic/issues/2714.

**Comment by hickeng** [comment]
@stuclem I don't find that the urfave/cli package is clear about which flags can be specified mulitple times and form a list of values (e.g. --dns) and which cannot and override the previous value.
This is an FYI that such flags exist and they are not clearly marked in the help output rather than anything more useful
