### ISSUE TITLE
Document that VIC supports pulling images via image digest

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1475]
Per https://github.com/vmware/vic/issues/1186.

**Comment by stuclem** [comment]
This should go into the topic on container use.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1186 is in the icebox.

**Comment by stuclem** [comment]
Actually, if #1186 is in the icebox, we should document that this version does not support pulling images via image digest. To be added in https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_limitations.md.

**Comment by npakrasi** [comment]
Added to container_limitations.md: This version of vSphere Integrated Containers does not support pulling images via image digest.
