### ISSUE TITLE
After executing invalid command on container all future containers with tty hang the terminal and do not attach

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1478]
Build 2840.

Installed in empty nested ESX6u2 on fusion.
installed with => ./vic-machine-darwin create --target 172.16.252.131 --image-datastore datastore1 --name vic-demo --user root --password 'Vmware!23'  --compute-resource /ha-datacenter/host/*/Resources

then in one terminal:
docker -H 172.16.252.132:2376 --tls run -it --name foo busybox

In another I ran:
docker -H 172.16.252.132:2376 --tls run -it --name cat busybox "/bin/sh -c 'ping -c 40 foo'"
and got:
docker: Error response from daemon: server error from portlayer.

Then ran:
docker -H 172.16.252.132:2376 --tls run -it --name dog busybox

And it started the container but did not attach. 

output from ps -a:
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
def05b2d7d7f        busybox             "sh"                     3 weeks ago         Running                                 foo
75776b6316ed        busybox             "/bin/sh -c 'ping -c "   3 weeks ago         Stopped                                 cat
d305b2345fae        busybox             "sh"                     3 weeks ago         Running                                 dog

**Comment by fdawg4l** [comment]
@mlh78750 I think something is wrong with your command invocation.

> docker -H 172.16.252.132:2376 --tls run -it --name cat busybox "/bin/sh -c 'ping -c 40 foo'"


On a standard docker host (*not* VIC), I get the following.
```
$ docker  run -it --name cat busybox "/bin/sh -c 'ping -c 40 foo'"
docker: Error response from daemon: Container command '/bin/sh -c 'ping -c 40 foo'' not found or does not exist..
```

**Comment by fdawg4l** [comment]
@mlh78750 I think you likely wanted to do the following (again, on a standard docker host, *not* VIC)

```
$ docker run -it busybox /bin/sh -c -- 'ping -c 40 foo'
ping: bad address 'foo'
```

**Comment by mlh78750** [comment]
@fdawg4l Good point. That's not a valid command, but regardless, that should not hang the system for all future commands. In other words, I don't care if I have a command that actually works or not.

**Comment by mlh78750** [comment]
Interestingly, It actually caused the previously working terminal on foo container to stop responding as well.

**Comment by mlh78750** [comment]
[container-logs.tar.gz](https://github.com/vmware/vic/files/362041/container-logs.tar.gz)

**Comment by hickeng** [comment]
I've not seen it cause the other containers to stop. I have seen it fail to get output from the container or useful output in the logs.

**Comment by fdawg4l** [comment]
I'm having trouble repro'ing locally but i havent synced since last night.  Will rebuild and give it a whirl.

**Comment by mlh78750** [comment]
From the container that I try to launch last (dog)

INFO[0000] Processing config for session d305b2345fae6650f8b729b95f7a5e2f835e9b0544c3de7f52bf71fca6292968
INFO[0000] Session d305b2345fae6650f8b729b95f7a5e2f835e9b0544c3de7f52bf71fca6292968 is configured for attach
INFO[0000] Reaped zombie process PID 74

INFO[0000] Reaped zombie process PID 82

INFO[0000] Reaped zombie process PID 97

INFO[0000] Reaped zombie process PID 122

INFO[0000] Reaped zombie process PID 157

INFO[0000] Reaped zombie process PID 159

INFO[0000] Reaped zombie process PID 162

INFO[0000] Reaped zombie process PID 167

INFO[0000] Reaped zombie process PID 169

INFO[0000] server: received ack: 0x060c == 0x060c

INFO[0000] lossiness check PASSED
INFO[0000] ready to service attach requests
INFO[0000] received global request type container-ids
INFO[0000] accepting incoming channel for d305b2345fae6650f8b729b95f7a5e2f835e9b0544c3de7f52bf71fca6292968

**Comment by mlh78750** [comment]
And this is from the container that had a failing command.

INFO[0000] Launching process for session 75776b6316edec5dbdb55bb5e196ded501d2e4b50e665cd86658692a5de13960
INFO[0000] opening ttyS2 for session logging
ERRO[0000] Path lookup failed for /bin/sh -c 'ping -c 40 foo': stat /bin/sh -c 'ping -c 40 foo': no such file or directory
ERRO[0000] failed to launch /bin/sh -c 'ping -c 40 foo' for 75776b6316edec5dbdb55bb5e196ded501d2e4b50e665cd86658692a5de13960: stat /bin/sh -c 'ping -c 40 fo
INFO[0000] Shutting down reaper
INFO[0000] Stopping extension Attach

**Comment by mlh78750** [comment]
Going to try and repro with correct command invocation.

**Comment by mlh78750** [comment]
If the command is correct it doesn't leave things in a hung state. It also doesn't show the output from the command.

Fresh install
in one terminal:
docker -H 172.16.252.132:2376 --tls run -it --name foo1 busybox

In another:
(mikeh) Bauxite:~ $ docker -H 172.16.252.132:2376 --tls run -it --name bar busybox /bin/sh -c -- 'ping -c 1 foo1'
(mikeh) Bauxite:~ $ docker -H 172.16.252.132:2376 --tls run -it --name dog busybox
/ #

So it worked, but I didn't see the output from "bar". And I was able to launch dog.

**Comment by sflxn** [comment]
I just tried your test.  I can repro your original result.  It appears the second run causes problems for VIC and puts the portlayer in a bad state.  If you just run 1 and 3, it is fine.  If you run with the correct command invocation, it is fine.  If step 2 is incorrect, the port layer gets borked.  Not sure if it's temporary or permanent.

**Comment by mlh78750** [comment]
@sflxn: i think it's permanent. In fact after I left mine in that state for a while the command 1 terminal locked up as well.

**Comment by sflxn** [comment]
Note, it gets borked if step 2 is incorrect invocation and attach is hung forever on a container that already exited.

**Comment by sflxn** [comment]
Did some more diagnosis.  If you bring up a 4th terminal and stop every container and remove them (docker ps, docker stop, docker rm), some operations work again.  However,

1. attempting step 1 again is now hosed with the same tether messages in the container console.
2. attempting docker run -it busybox /bin/top does cause a container to start up properly but the client tty is hosed.

**Comment by fdawg4l** [comment]
@hickeng has discovered a deadlock in our port layer side attach.  We're working on a canonical test and a potential fix.

**Comment by sflxn** [comment]
https://github.com/vmware/vic/pull/1480 will fix this.  I am curious to see if the deadlock also is needed as @hickeng explained that it fixes a scenario where simultaneous containers are started.

**Comment by fdawg4l** [comment]
It's not "simultaneous containers".  It's a timing hole.  You just need a waiting attach request and a new container to start.  Piling up waiting containers increases the likelihood of the deadlock.
