### ISSUE TITLE
Incorrect image digest format sent to docker client

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#1484]
When pull image via digest is supported ( #1186 ) we need to ensure that the digest format is sent to the client correctly.  

Currently the function to format the digest for the client will return the following formatted digest:

repo@sha:digest (i.e. busybox@sha:1235453303)

If should instead return:

repo@sha256:digest (i.e. busybox@sha256:121212121213)

A simple change, but one that must be made so that `docker images --digests` is supported.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by hickeng** [comment]
@cgtexmex Do you know if this is still an issue? Follow up from #1186

**Comment by cgtexmex** [comment]
I'm not sure that this is valid anymore -- this was created prior to the repository cache being created, so that might have taken care of it.  

We certainly need to format the message on download correctly, but that should be handled by #1186 and would require changes to imagec -- specifically here:
https://github.com/vmware/vic/blob/master/lib/imagec/download.go#L207

So I think it's safe to close this issue.
