### ISSUE TITLE
Allow whitelist of insecure registries

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1486]
Currently we have all or nothing when it comes to allowing insecure registries, and that's not currently exposed as a configuration opinion in any way.

This should add:
- vic-machine arguments for whitelisted registries. If no registry arguments are specified, docker hub should be permitted, if any registry arguments are specified the docker hub must also be added explicitly.
- imagec should check the registry whitelist for permission and check the registry for secure/insecure config before pulling.

**Comment by hickeng** [comment]
assigned to @jzt initially as I know he's looking at imagec currently.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage. Needs release note

**Comment by hickeng** [comment]
There is already a vic-machine argument `--docker-insecure-registry value` which is essentially whitelisting insecure registries.

@emlin @jzt Is that argument glued through to the appliance and honored by imagec code?

**Comment by emlin** [comment]
@hickeng the insecure registry is passed into docker persona service, and is used to configure insecure registry. The should be the func you mentioned.
But for imagec work, I would leave @jzt to confirm.

**Comment by jzt** [comment]
@hickeng @emlin It looks like the persona is making use of it here:

```go
	insecureRegistries := InsecureRegistries()
	for _, registry := range insecureRegistries {
		if registry == ref.Hostname() {
			options.InsecureAllowHTTP = true
			break
		}
	}
```

`InsecureRegistries()` is defined in `backends.go`:
```go
func InsecureRegistries() []string {
	registries := make([]string, len(insecureRegistries))
	for _, reg := range insecureRegistries {
		registries = append(registries, reg)
	}

	return registries
}
```

 and called by `Init()`:
```go
	serviceOptions := registry.ServiceOptions{}
	for _, registry := range insecureRegs {
		insecureRegistries = append(insecureRegistries, registry.Path)
	}
	if len(insecureRegistries) > 0 {
		serviceOptions.InsecureRegistries = insecureRegistries
	}
	log.Debugf("New registry service with options %#v", serviceOptions)
	RegistryService = registry.NewService(serviceOptions)
```

which is called from docker's `main.go`:

```go
	if err := vicbackends.Init(cli.portLayerAddr, productName, &vchConfig, vchConfig.InsecureRegistries); err != nil {
		log.Fatalf("failed to initialize backend: %s", err)
	}
```

Hope this helps.

**Comment by hickeng** [comment]
#2620 demonstrates that this is not currently functioning. Either it's a regression or it never actually functioned as expected.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by mlh78750** [comment]
Dup #2620

**Comment by mlh78750** [comment]
cc @mhagen-vmware
