### ISSUE TITLE
Need a better way to handle the Swagger errors from the portlayer

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#1489]
There are several places in the docker engine server where we get responses back from the portlayer and they are packed in swagger objects. 

instead of handling them inline we should have a utility function package for handling all of our swagger responses. This will drastically reduce the amount of redundant code that exists in the docker engine server. 

current behavior:

res, err := client.containers.get(<handle>)

if err != nil{
  switch err := err.(type){
    ....
  }
}

expected behavior: 
res, err := client.containers.get(<handle>)
err := processContainerGetError(err) 
if err != nil {
   return derr.ErrorWithStatusCode(http.SomeStatusCode, err)
}

Note: the scenario is just a pseudo case. some docker calls have a more complex return than displayed.

**Comment by mdubya66** [comment]
I'm putting this into Backlog and GA for now. This is a candidate for the tech debt relief.

**Comment by mdubya66** [comment]
@vburenin can you add commentary?
