### ISSUE TITLE
vic-machine: make the volume-store ordering consistent with container-network

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1490]
The volume-store argument to vic-machine is currently inconsistent with container-network - it takes the internal name first, with the vsphere path second. This may have been done deliberately to simplify splitting around the first : however it should be consistent and we should be splitting on the last : in the value.
The logic for having vsphere name first is [here](https://github.com/vmware/vic/blob/master/doc/design/vic-machine.md#usage-examples)

When fixed:
```
--volume-store=datastore1/path/to/volumes:mydata
--volume-store=ds://datastore (1)/path/to/data:otherdata
```

Requires the follow before closing:
- [ ] implementation
- [ ] doc update

**Comment by corrieb** [comment]
Assigning to @emlin
