### ISSUE TITLE
Document how to configure insecure registries

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1499]
Per https://github.com/vmware/vic/issues/1486

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1486 is now in the icebox, but insecure registries are allowed in PR https://github.com/vmware/vic/pull/1487. Moving to To Do.

**Comment by stuclem** [comment]
Apparently the `--docker-insecure-registry` option is already present in `vic-machine create`. It had passed me by!

**Comment by stuclem** [comment]
The `--docker-insecure-registry` option was implemented in PR https://github.com/vmware/vic/pull/2105, and was part of issue https://github.com/vmware/vic/issues/368.

**Comment by stuclem** [comment]
Added info about using insecure registries in the following places:

- [Examples of Deploying a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#docker-insecure-registry)
- [Virtual Container Host Deployment Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#docker-insecure-registry)
- [Using Insecure Registry Servers with vSphere Integrated Containers Engine](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/using_insecure_registries_with_vic.md)

@sflxn and @mreferre, does this cover it? Thanks!

**Comment by stuclem** [comment]
Approved by @mreferre via Slack.

**Comment by sflxn** [comment]
Yes, that's all that's needed.

**Comment by stuclem** [comment]
I added info about ports in the 3 topics:
- [Examples of Deploying a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#deploy-a-virtual-container-host-and-authorize-access-to-an-insecure-registry)
- [Virtual Container Host Deployment Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#docker-insecure-registry)
- [Using Insecure Registry Servers with vSphere Integrated Containers Engine](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/using_insecure_registries_with_vic.md)

**Comment by stuclem** [comment]
@sflxn, following your comment in https://github.com/vmware/vic-product/pull/3#pullrequestreview-2002942, I have added the following notes to the 3 topics above:

**NOTE**: The current builds of vSphere Integrated Containers do not yet support private registry servers that you secure by using TLS certificates.

To reiterate @mreferre 's question in https://github.com/vmware/vic-product/pull/3#discussion_r81101110, which "public" private registries do we support?

**Comment by mlh78750** [comment]
I'm confused. Can we use all secure (with proper certs configured) registries in .6?

**Comment by stuclem** [comment]
@mlh78750, from what I understand, we cannot currently use private (i.e. in-house) registries that are secured with TLS. External registries are fine, even if they use TLS. Internal registries with self-signed certs are OK if you set the docker-insecure-registry flag on the VCH.

@sflxn is this assessment correct?

**Comment by mlh78750** [comment]
That's confusing. If we can use external registries with good certs, I don't see why we couldn't use local registries if their certs were also good.

**Comment by stuclem** [comment]
@mlh78750, according to @sflxn in https://github.com/vmware/vic-product/pull/3#discussion_r81385602:  "There is the scenario where a secure private registry uses self generated certificates. We don't have a way to upload those certificates to the VCH yet. Also, we're not yet verifying CA issues certificates yet. These should be resolved soon, but I just wanted to bring attention to the fact that they aren't working properly yet."
