### ISSUE TITLE
Cannot use Control-C to kill a container

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1501]
**VIC Version:**

0.1 / master / v0.4.0

I've noticed a different in behaviour when running docker on my MAC v. running docker in VIC.

On my MAC, I can Control-C a running container such as Nginx. I cannot do this in VIC.

In the init.log I see the following:

```
time="2016-07-14T10:46:58Z" level=debug msg="[0xc8202ec800] writing \"time=\"2016-07-14T10:46:58Z\" level=error msg=\"Handler for POST /v1.23/containers/22dc30065c48072df48aacee816da04126158808155b904b4f4a523e35fb072c/kill returned error: Cannot kill container 22dc30065c48072df48aacee816da04126158808155b904b4f4a523e35fb072c: vSphere Integrated Containers does not implement container.ContainerKill\" \n\" to 2 writers" 
time="2016-07-14T10:47:57Z" level=debug msg="[0xc820328640] writing \"time=\"2016-07-14T10:47:57Z\" level=debug msg=\"[BEGIN] [main.(*server).index]\" \ntime=\"2016-07-14T10:47:57Z\" level=debug msg=\"[ END ] [main.(*server).index] [35.392µs] \" \n\" to 2 writers" 
```

**Expected behavior:**

Note sure: This could be by design. However potential customers may expect to be able to Control-C a running container, so we should document this difference if it is by design.

/cc @stuclem

**Comment by hickeng** [comment]
@cormachogan It's dependent on #1267 and #378 - only not present because of time. Should be documented - thought it was in the known issues at one point.

**Comment by cormachogan** [comment]
@stuclem - can we capture this for v0.4.0?

**Comment by stuclem** [comment]
Added at the end of the list of known issues: https://github.com/vmware/vic/releases/tag/v0.4.0

@cormachogan, is this OK?

**Comment by cormachogan** [comment]
LGTM

**Comment by mdubya66** [comment]
@hickeng please triage and assign to appropriate team

**Comment by dougm** [comment]
Captured in v0.4.0's list of known issues.  This will be supported when #1267 and #378 are implemented.
