### ISSUE TITLE
Document change in volume-store syntax

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1502]
Per https://github.com/vmware/vic/issues/1490

**Comment by hickeng** [comment]
@stuclem I've added a user-doc label to #1490 and a set of checkboxes that includes implementation and documentation requirements. Is that a viable mechanism of associating a need for doc update with an issue? It makes it a little more overt to the developer that there's a doc impact.

**Comment by stuclem** [comment]
@hickeng, yes, I think that this is a good idea. Thanks!

**Comment by stuclem** [comment]
@gigawhitlocks I have updated the example command in the doc to:

`--volume-store <i>datastore_name</i>/<i>path</i>:<i>volume_store_name</i>`

See https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#datastore.

Is this OK?

**Comment by stuclem** [comment]
Reviewed by @gigawhitlocks via Slack.
