### ISSUE TITLE
Volumes: specify capacity units on command line

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1503]
Current behaviour has default units. Which default units are unclear because it looks like it's MB in the code, but error messages say GB. This should be implemented in such a manner that other components (e.g. install) can make use of the code.

Use KB internally for stored values - this aligns with vSphere and also allows for config of small resources such as nvram or tiny unikernels in the future.

As a very quick alternative if this cannot be addressed in time for onsite - change the Capacity option to CapacityMB which makes it explicit.

On completion of this issue a user should be able to specify units for the capacity:

```
volume create --opt Capacity=1024 # MB by default
volume create --opt Capacity=1024KB
volume create --opt Capacity=1024MB
volume create --opt Capacity=1024GB
volume create --opt Capacity=1024TB
```

Requires the follow before closing:
- [x] implementation
- [ ] doc update

**Comment by hickeng** [comment]
@matthewavery I see that an error message specifies the units as GB, however it looks like it's treated as MB in the code: https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/volume.go#L141

**Comment by mdubya66** [comment]
Marking this as Onsite, it can probably move to GA but a fix would be nice.

**Comment by matthewavery** [comment]
This is already fixed @hickeng. `return fmt.Errorf("Capacity must be an integer value. The unit is MB: %s", convErr)` I believe it made it in with creat w/ volumes.

**Comment by matthewavery** [comment]
@stuclem There is now a PR out to address this(PR #1782). And we will need to update the documentation on this driver argument. Now the format is <integer><unit>. where the `integer` must be positive. and the unit can be `mb`,`mB`,`MB`,`Mb`(and so on for `gb` and `tb`). If we want that to be more restrictive just let me know.

**Comment by stuclem** [comment]
Thanks @matthewavery, I have moved the associated doc issue (https://github.com/vmware/vic/issues/1526) into the To Do queue.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by matthewavery** [comment]
Both the Doc issue and the PR were merged. There are integration tests in place to prove functionality and guard against regression now. Closing the issue.
