### ISSUE TITLE
Add ListStores to volume layer of port layer

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1506]
Return a list of volume store names.

**Comment by hickeng** [comment]
It's a blurring of the layers but the full VCH config is available to the personality - the personality could directly list this information if time constraints interfere with doing this via API.

**Comment by fdawg4l** [comment]
Hmm..  That's basically where the port layer is getting this info.  Not sure what the best approach here is.  I can return the list of configured volume store names which we cache in the volume cache anyway, or we can skip this step and get this same info from the VCHconfig.
