### ISSUE TITLE
Incorrect personality exit codes

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1514]
Vanilla docker

```
[vagrant@devbox:~] docker run -it busybox /bin/true
[vagrant@devbox:~] echo $?
0
[vagrant@devbox:~] docker run -it busybox /bin/false
[vagrant@devbox:~] echo $?
1
[vagrant@devbox:~] docker run -it busybox /bin/z
docker: Error response from daemon: Container command '/bin/z' not found or does not exist..
 [vagrant@devbox:~] cecho $?
127
```

They follow the chroot standard for exit codes.
Exit status:
125 if 'docker run' itself fails
126 if contained command cannot be invoked
127 if contained command cannot be found
the exit status otherwise

VIC

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] docker run -it busybox /bin/true
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] echo $?
0
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] docker run -it busybox /bin/false
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] echo $?
0
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] docker run -it busybox /bin/z
docker: Error response from daemon: server error from portlayer.
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] echo $?
125
```

**Comment by caglar10ur** [comment]
looks like client is getting the exit code via inspect

https://github.com/docker/docker/blob/506234e3f0f6d8f8a0629e09f38dfe96ada025c2/api/client/container/run.go

https://github.com/docker/docker/blob/ee8c512dc32117fbd327b4a19da0ffefe47abfcd/api/client/container/utils.go

**Comment by caglar10ur** [comment]
Looks like tether needs to fill in State part of this struct

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] docker inspect 1e
[
    {
        "Id": "1e877c77862d6a25fb677903f0ee432022911a30aac97c3d276503311f6b3704",
        "Created": "2016-07-14 19:01:49 +0000 UTC",
        "Path": "/bin/z",
        "Args": [
            "/bin/z"
        ],
        "State": {
            "Status": "stopped",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "",
            "FinishedAt": ""
        },
...
```

**Comment by cgtexmex** [comment]
I see this as the vic comparable data (https://github.com/vmware/vic/blob/master/lib/metadata/container_vm.go#L58) , but when writing containerInfo I didn't see it getting populated..

**Comment by cgtexmex** [comment]
@sflxn when I implemented containerinfo I didn't see it getting populated.  It's defined, but didn't appear tether was populating...or possibly I missed it.

**Comment by mdubya66** [comment]
Since this is in Progress I am marking it required for Onsite. IMO it could be a candidate for GA instead.
