### ISSUE TITLE
Support -c and -m parameters for containerVMs

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1517]
Right now they are hardcoded as 

```
        NumCPUs:  2,
        MemoryMB: 2048,
```

https://github.com/vmware/vic/blob/master/lib/portlayer/exec/handle.go#L209

**Comment by mdubya66** [comment]
assigning to @hickeng for initial triage and more detail.

**Comment by hickeng** [comment]
This requires:
a. personality processing these values
b. port layer exec.Create accepting memory and cpu parameters
c. port layer passing these through to the VM config spec used for creation

This does not encompass the runtime alteration of cpu/memory - there is no hotadd support in the containers at this time.

**Comment by mdubya66** [comment]
re-assigning to hickeng to decide who should take it on

**Comment by jzt** [comment]
Update:

Docker is deprecating `-c` in favor of `--cpu-shares`, and will warn the user with an associated message along those lines. A current approach would be to use the input provided to `--cpuset-cpus` in the form of `"x,y"` to mean x = `numCoresPerSocket` and y = `numCPUs`.  Additionally, `-m` can be used to specify the amount of memory, in the form of `<number>[<unit>])`. Number is a positive integer. Unit can be one of b, k, m, or g. To be consistent with Docker, we should probably have a hard minimum (they use 4MB).

We should also consider what to use for our defaults if no memory or cpu configuration is supplied.  Currently we default to 2 CPUs, 2GB memory. Docker defaults to unlimited memory, but we should decide if that is ideal for our environment.
