### ISSUE TITLE
Document docker volume delete

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1521]
Per https://github.com/vmware/vic/issues/1511

**Comment by stuclem** [comment]
Looks like https://github.com/vmware/vic/issues/1511 is complete.

**Comment by stuclem** [comment]
Actually, this is for GA.

**Comment by stuclem** [comment]
This is still in To Do on the dev side, so moving this one back to backlog.

**Comment by stuclem** [comment]
Docker volume rm is implemented in PR https://github.com/vmware/vic/pull/2526.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/2526 is now merged.

**Comment by npakrasi** [comment]
Added to Supported Docker commands and deleted the note that it's not implemented in the Using Volumes with Vic topic.
