### ISSUE TITLE
Document docker volume ls 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1522]
Per https://github.com/vmware/vic/issues/917

**Comment by stuclem** [comment]
Partial implementation is in https://github.com/vmware/vic/pull/1552. Full implem is for GA, but it looks like some of it will be there for onsite.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md)

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/917 is fixed in PR https://github.com/vmware/vic/pull/1601 (merged).

**Comment by stuclem** [comment]
New functionality proposed in https://github.com/vmware/vic/issues/1679.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1705 adds the name of the volume store that a volume is on to the output of volume ls.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1679 and PR https://github.com/vmware/vic/pull/1705 were abandoned, as `docker volume inspect` will provide the volume store info.

**Comment by stuclem** [comment]
Reviewed by @matthewavery in https://github.com/vmware/vic/issues/1809.

**Comment by stuclem** [comment]
Merged in https://github.com/vmware/vic/pull/1809
