### ISSUE TITLE
Add links to docs to the vic-machine help output

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1525]
Following email discussion with @cormachogan, it might be an idea to include a link to the appropriate doc topic to the help output for `vic-machine create`, `delete`, `inspect`, etc. The doc topics allow us to include more information than can be comfortably included in the `--help` output.

For example, in the help output for `vic-machine create`, we could include a line that says something like the following 

`For more information about the options of vic-machine create, see https://vmware.github.io/vic/assets/files/html/vic_installation/vch_installer_options.html.`

I have not yet created corresponding topics for delete, inspect, version, but will do so very soon and will post the URLs here when they are up on github.io.

@emlin, @hickeng, @corrieb do you think that this is a good idea?

**Comment by mdubya66** [comment]
In my experience this can be stale fairly quickly unless API's are used instead of static locations. I'm moving this to Icebox for now.

**Comment by stuclem** [comment]
OK, fair enough.
