### ISSUE TITLE
container networking not working

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1529]
**VIC Version:**

0.1 / master / v0.4.0

It looks like there are some issues with creating container networks outside of the bridge network.
As you can see there are some encoding errors around DNS that are thrown when a separate container network is requested.

```
root@photon-NaTv5i8IA [ /workspace/vic ]# ./vic-machine-linux create  --bridge-network Bridge-DPG --image-datastore isilion-nfs-01 -t 'administrator@vsphere.local:VMware123!@10.27.51.103'  --compute-resource Mgmt --external-network "VMNW51" --container-network con-nw --container-network-gateway con-nw:192.168.100.0/24 --container-network-dns con-nw:192.168.100.1 --container-network-ip-range con-nw:192.168.100.0/24
INFO[2016-07-15T11:47:44Z] ### Installing VCH ####
INFO[2016-07-15T11:47:44Z] Generating certificate/key pair - private key in ./virtual-container-host-key.pem
INFO[2016-07-15T11:47:45Z] Validating supplied configuration
INFO[2016-07-15T11:47:45Z] Firewall status: DISABLED on /CNA-DC/host/Mgmt/10.27.51.8
INFO[2016-07-15T11:47:45Z] Firewall configuration OK on hosts:
INFO[2016-07-15T11:47:45Z]   /CNA-DC/host/Mgmt/10.27.51.8
INFO[2016-07-15T11:47:45Z] License check OK on hosts:
INFO[2016-07-15T11:47:45Z]   /CNA-DC/host/Mgmt/10.27.51.8
INFO[2016-07-15T11:47:45Z] DRS check OK on:
INFO[2016-07-15T11:47:45Z]   /CNA-DC/host/Mgmt/Resources
INFO[2016-07-15T11:47:46Z] Creating Resource Pool virtual-container-host
INFO[2016-07-15T11:47:46Z] Creating appliance on target
ERRO[2016-07-15T11:47:46Z] unable to encode []net.IP (slice) for guestinfo./container_networks|con-nw/dns: net.IP is an unhandled type
INFO[2016-07-15T11:47:46Z] Network role client is sharing NIC with external
INFO[2016-07-15T11:47:46Z] Network role management is sharing NIC with external
ERRO[2016-07-15T11:47:46Z] unable to encode []net.IP (slice) for guestinfo./container_networks|con-nw/dns: net.IP is an unhandled type
INFO[2016-07-15T11:47:47Z] Uploading images for container
INFO[2016-07-15T11:47:47Z]      bootstrap.iso
INFO[2016-07-15T11:47:47Z]      appliance.iso
INFO[2016-07-15T11:47:52Z] Registering VCH as a vSphere extension
INFO[2016-07-15T11:47:57Z] Waiting for IP information
INFO[2016-07-15T11:48:26Z] Waiting for major appliance components to launch
INFO[2016-07-15T11:48:26Z] Initialization of appliance successful
INFO[2016-07-15T11:48:26Z]
INFO[2016-07-15T11:48:26Z] Log server:
INFO[2016-07-15T11:48:26Z] https://10.27.51.56:2378
INFO[2016-07-15T11:48:26Z]
INFO[2016-07-15T11:48:26Z] DOCKER_HOST=10.27.51.56:2376
INFO[2016-07-15T11:48:26Z]
INFO[2016-07-15T11:48:26Z] Connect to docker:
INFO[2016-07-15T11:48:26Z] docker -H 10.27.51.56:2376 --tls info
INFO[2016-07-15T11:48:26Z] Installer completed successfully
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.51.56:2376 --tls ps -a
Error response from daemon: Error invoking GetContainerList: Get http://127.0.0.1:8080/containers/list?all=true: dial tcp 127.0.0.1:8080: getsockopt: connection refused
root@photon-NaTv5i8IA [ /workspace/vic ]#
```
Now if one attempts a simple "ps -a", it fails as follows:

```
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.51.56:2376 --tls ps -a
Error response from daemon: Error invoking GetContainerList: Get http://127.0.0.1:8080/containers/list?all=true: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

I have also tried to omit the container-network-dns part of the command, but I get the same error when running a "ps -a" command.

On logging onto the console of the VCH, I don't see any of my container network entries. The bridge network (with the default 172.16 network is in place), as is eth0, but nothing related to my requested container network. See attached screenshot.

![vch-screenshot](https://cloud.githubusercontent.com/assets/18258500/16873577/2100602e-4a8c-11e6-8a33-6a3877b2391f.png)

If the container network is omitted from the VCH create command, everything works fine.

Apologies in advance if I am doing something incorrectly. Logs attached.

**Comment by cormachogan** [comment]
Had a brief chat with @emlin - syntax of command seems ok. Looks like it might be a bug.

**Comment by hmahmood** [comment]
Looks like the port layer server went down. @cormachogan do you still have the logs from the VCH?

**Comment by hmahmood** [comment]
The IP range specified for the container network is 192.168.100.0/24, and the port layer cannot reserve this full range because it has already allocated the gateway and broadcast addresses from the same pool. This is a bug; we need to allow an exception for this case. The case where the pool does not include the gateway and broadcast addresses works. So on the vic-machine command line `--container-network-ip-range con-nw:192.168.100.2-192.168.100.254` would work.

**Comment by hickeng** [comment]
The encoding errors are misleading - that's a handled path. We can drop the log level to DEBUG however. And we really, really need to not use the default logger for stdout to user in vic-machine (#1148)

**Comment by cormachogan** [comment]
Confirmed that using a range that excludes gw works.
It would be good if we did a pre-check on the CLI to state that we cannot use a particular CIDR since we are already reserving addresses on it.

**Comment by cormachogan** [comment]
unfortunately, I still cannot consume a non-default container network - https://github.com/vmware/vic/issues/1542

**Comment by mdubya66** [comment]
marking for Onsite as it's in Progress. this and #1542 need to be followed up on with more details.
