### ISSUE TITLE
Document the location and content of the vicadmin portal

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1530]
The vicadmin portal will include basic health status, logs, VCH information and resource usage. See PR https://github.com/vmware/vic/pull/1515, and epic https://github.com/vmware/vic/issues/1372.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1372 is for GA.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1515 is now merged.

**Comment by stuclem** [comment]
The VCH Admin portal is visible at https://`vch_address`:2378 after you deploy a VCH. 

![vicadmin](https://cloud.githubusercontent.com/assets/16718369/17250941/d1874f28-55a6-11e6-84e6-f8cd9a25d151.png)

**Comment by stuclem** [comment]
@kjplatz and @sgairo, I see in the screencap above that my network connectivity is showing up as orange. I assume that this means that these squares can be green (OK), orange (something's dodgy), or red (it's dead). It would be good if in the docs we could point people to some clues as to what they need to do to make their squares green, if some of them are orange/red. 

So, are there any design docs anywhere that you can point us to that list the conditions under which each of these statuses appears as either orange or red? 

Thanks!

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1744 will change the output of vic-machine create to include the vicadmin address (currently says `Log Server`). Requires an update in the topic on deploying a VCH.

**Comment by sgairo** [comment]
@stuclem We are currently still working out what categorizes a status as green/orange/red for each health report. We will surely send it your way once we have it.

**Comment by stuclem** [comment]
@sgairo thanks!

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1744 is merged in PR https://github.com/vmware/vic/issues/1811. Install output now says `vic-admin portal` instead of `Log server`.

**Comment by stuclem** [comment]
Marking this one as done. Will include info about what turns statuses from green to yellow in https://github.com/vmware/vic/issues/1317.
