### ISSUE TITLE
vic-machine: resource pool limits

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1538]
Provide arguments to configure the VCH size (resource pool reservations, limits, and shares) when deploying a VCH:

```
--memory-limits=reservation:limit
--cpu-limits=reservation:limit
```
e.g. specify both reservation and limit, and shares
```
--memory-limits=800MB:8GB
--memory-shares=2000
```

e.g. specify only limit (note the leading ':')
```
--cpu-limits=:20GHz
```

e.g. specify only reservation (note the trailing ':')
```
--cpu-limits=500MHz:
```

On completion vic-machine should configure the resource pool created for the VCH with reservation and limits specified. It does *NOT* need to sanity check the figures against the parent pool configuration initially.

**Comment by hickeng** [comment]
@emlin assigned to you for imlpementation or reassignment.

**Comment by hickeng** [comment]
@cormachogan @reddolan Please comment +/- on the format of the CLI arguments. This seems a good balance of consise and clear, also following the : separator that we've used elsewhere, but I'm not always good at assessing these things.

**Comment by stuclem** [comment]
@hickeng and @emlin, since we already have the `--appliance-memory` and `--appliance-cpu` options, shouldn't we make it clearer in the names that these options apply to resource pools? My first reaction on seeing this issue was "don't we already have these?", so unless it's completely obvious to vSphere admins who are more experienced than I am that these ones are for resource pools, I think that there's a potential for confusion.

How about the following, just to be completely unambiguous?:
```
--pool-memory-limits=reservation:limit
--pool-cpu-limits=reservation:limit
```

**Comment by cormachogan** [comment]
I have to agree with @stuclem - this can be a bit confusing and we need to make it a little clearer.

I think what we are trying to say is that the "pool" resources are for VCH and containers, but we can also control the amount of resources that that VCH "appliance" can consume in the pool. I think "pool" and "appliance" are good enough differentiators in the help output.

**Comment by stuclem** [comment]
Ignore the reference to this issue from 1356 - cut n paste error.

**Comment by hickeng** [comment]
@stuclem @cormachogan I'd honestly rather not have the --appliance arguments in there at all. I don't think they add any value and have the potential for significant confusion amongst custmoers.
The _only_ reason for changing CPU/memory for the appliance outside of debugging is to allow for caching of larger image layers (ramfs) during pull and that could be accomplished via the vsphere UI if absolutely necessary.

**Comment by emlin** [comment]
@hickeng if we don't allow the configuration of appliance, what number is the preferred default value for appliance?
Still 1 cpu, 2048 memory?
