### ISSUE TITLE
Remove the vsphere datastore information from docker info plugin

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1540]
The Plugins section of info is leaking vSphere topology data.
```
vagrant@devbox:~/vic$ docker -H 192.168.78.216:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Storage Driver: vSphere Integrated Containers Backend Engine
vSphere Integrated Containers Backend Engine: RUNNING
Execution Driver: vSphere Integrated Containers Backend Engine
Plugins:
 Volume: ds://@datastore1/%5Bdatastore1%5D%20volumes-extra
 Network: bridge external
Kernel Version: 4.4.8-esx
```

When fixed this should show:
Plugins:
  Volume: default extra
  Network: bridge external

This **must not** show vsphere datastore paths

**Comment by hickeng** [comment]
@fdawg4l I'm assigning this to you as you're currently working on the volume store list portion

**Comment by sflxn** [comment]
Where should 'default' come from?  Just a constant or is that saved in guestinfo?

**Comment by fdawg4l** [comment]
@sflxn "default" needs to be a specified volumestore label when the VCH is created otherwise you can't use anonymous volumes.  @matthewavery has more details, but i believe you're suppose to get an info message when you create a vch without one.

**Comment by fdawg4l** [comment]
@hickeng  Re- "not showing the datastore + path" (paraphrased)

Why?  There's an operational burden now on the docker (client) user now having to seek out the person who installed the VCH to map the store name to the datastore + path when requiring help.  Right?

**Comment by hickeng** [comment]
@fdawg4l the operational burden falls to the person who deployed the VCH to map the volume store name to the datastore, not to the user; the manner by which this is accomplished is part of what we want to assess in the onsite.
As for why - we had the datastore path and VC path in the docker info for bonneville and had explicit requests from customers to remove it because it leaked internal data about the infrastructure due to naming conventions and structure.
