### ISSUE TITLE
Document vic-machine options for resource pool limits

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1543]
Per https://github.com/vmware/vic/issues/1538

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1538 is implemented in https://github.com/vmware/vic/pull/1576.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1576 is merged

**Comment by stuclem** [comment]
Added the following to the topic on `vic-machine create` options:

### `pool-memory-reservation` ###

Reserve a quantity of memory for use by the vApp or resource pool that contains the virtual container host. Specify the memory reservation value in MB. If not specified, `vic-machine create` sets the reservation to 0 (unlimited).

<pre>--pool-memory-reservation 1024</pre>

### `pool-memory-limit` ###

Limit the amount of memory that the vApp or resource pool that contains the virtual container host can use. Specify the memory limit value in MB. If not specified, `vic-machine create` sets the limit to 0 (unlimited).

<pre>--pool-memory-limit 1024</pre>

### `pool-memory-shares` ###

Set memory shares on the vApp or resource pool that contains the virtual container host. Specify the share value as a level or a number, for example `high`, `normal`, `low`, or `163840`. If not specified, `vic-machine create` sets the share to `nil` (unlimited).

<pre>--pool-memory-shares low</pre>

### `pool-cpu-reservation` ###

Reserve a quantity of CPU capacity for use by the vApp or resource pool that contains the virtual container host.  Specify the CPU reservation value in MHz. If not specified, `vic-machine create` sets the reservation to 0 (unlimited).

<pre>--pool-cpu-reservation 1024</pre>

### `pool-cpu-limit` ###

Limit the amount of CPU capacity that the vApp or resource pool that contains the virtual container host can use. Specify the CPU limit value in MHz. If not specified, `vic-machine create` sets the reservation to 0 (unlimited).

<pre>--pool-cpu-limit 1024</pre>

### `pool-cpu-shares` ###

Set CPU shares on the vApp or resource pool that contains the virtual container host. Specify the share value as a level or a number, for example `high`, `normal`, `low`, or `163840`. If not specified, `vic-machine create` sets the share to `nil` (unlimited).

<pre>--pool-cpu-shares low</pre>

@emlin, is this OK?

Note: I left the `appliance-memory` and `appliance-cpu` options in the doc, as they are still present in `create`.

**Comment by emlin** [comment]
Yeah, I didn't get confirmation to remove them. While those are removed, the above parameters might be renamed as well.
btw, by default, the memory and cpu reservation are all 1, instead of 0, because govmomi does not allow 0 value right now.
and if share is not set, the value will be "normal".

everything else looks good.

**Comment by stuclem** [comment]
Fixed. Thanks!
