### ISSUE TITLE
Document vic-machine create use-rp option

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1544]
Added in PR https://github.com/vmware/vic/pull/1536. This is a temporary solution just for onsite beta.

**Comment by stuclem** [comment]
Added the following in the topic on `vic-machine` create options:

Deploy the virtual container host to a resource pool rather than to a vApp. If you specify this option, `vic-machine create` creates a resource pool with the same name as the virtual container host.

@emlin, why exactly would a user want to do this? Thanks!

**Comment by emlin** [comment]
@stuclem as @hickeng mentioned, this is a temporary option, so we can collect user feedback, for if they really want VirtualApp represent VCH.
So I assume we don't need to document this option, or maybe just doc for OnSite.

**Comment by stuclem** [comment]
Reopening this one to track whether this option stays or goes....

**Comment by stuclem** [comment]
@emlin and @hickeng, I see that `--use-rp` is still there in the extended help for `vic-machine create`. Are we keeping it? Under what circumstances would someone actually need/want to use it?

**Comment by hickeng** [comment]
@stuclem I've no idea when someone would want to use it - we had mention from some of the field facing folk that vApps were not in favour. This option was added to allow people to chose how it presents but I'm not sure it's even tested at this time.
@emlin I think we should remove this option now unless it's got decent tests to ensure it remains functional.

**Comment by emlin** [comment]
#3090 is filed to remove --use-rp option.
In theory, this option should work well, as we're using resource pool directly, unless there is different interface for vApp, e.g. create vm.
But obviously, we don't have enough test to cover that, so we might remove the option, but leave the function there.

**Comment by stuclem** [comment]
@emlin  do you mean remove it from the doc and hide it in the help output, rather than removing it completely?

**Comment by stuclem** [comment]
The discussion about whether to keep this option is going on https://github.com/vmware/vic/issues/3090. The `--use-rp` option is currently documented. Closing this one, and will open a new issue if https://github.com/vmware/vic/issues/3090 concludes that we do want to remove the issue.
