### ISSUE TITLE
Status created does not exist

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1546]
Actual behavior:
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
9d928c7aad55        busybox             "ls"                11 minutes ago      Stopped                                 lonely_kare
```

Expected behavior:
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
115184175ef9        busybox             "ls"                8 minutes ago       Created                                 admiring_minsky
```

**Comment by mdubya66** [comment]
Marking this as Onsite for now. @hickeng it needs an owner

**Comment by cgtexmex** [comment]
FTR - we have a number of issues around the state machine of vic and how it's presented via the docker client.  This is one manifestation of that -- IMO we need to define the valid states in VIC and then map the translation to docker.  This will need to take into account VM state & tether (extra configuration) information.

While I was in Austin with @hickeng we discussed this a bit.  If this can wait until later this week I could pick it up and knock this out with some of the other state issues.

**Comment by mdubya66** [comment]
Thanks @cgtexmex - i still need to determine if this is a requirement for onsite. later this week would push it out.

**Comment by cgtexmex** [comment]
I have a change I'm waiting to push -- have a couple other changes in front of it.  This change will provide a "Created" status.  It will use the existing ps functionality (going to the infrastructure and not cache), so will require some minor refactoring in the future..

I think we need a separate issue to identify the overall state needs for the PL, etc..
