### ISSUE TITLE
vic-machine ls

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1550]
Usage sample:
```
vic-machine ls
-FROM=https://root@****:vcenter/

ID        Path                                Notes
vm-239    mycluster/edw-pool/web/edw-web      Notes from the VCH config
vm-2372   mycluster/random/someother          Another VCH in the random pool
+vm-15    mycluster/xyz                       VCH in the root of the cluster
```
The following example lists VCHs under a specific resource
```
vic-machine ls
-FROM=https://root@****:vcenter/example-datacenter/host/mycluster/Resources/edw-pool/
```

**Comment by emlin** [comment]
Note, if we have vic-machine ls show VCH ID, we'd better to support vic-machine inspect --id, to help user show VCH in details.
@hickeng which VCH ID is your preference? VM mob id or RP/vApp mob id?

**Comment by emlin** [comment]
@hickeng @stuclem 
For the ls command, what information is required at this moment?
My plan is to go with this format:
```
ID                       path                                   name                     
resourcegroup-001        mycluster                              virtual-container-host         
resourcegroup-002        mycluster/edw-pool/web/edw-web1        virtual-container-host1      
```

**Comment by emlin** [comment]
So far, user is not allowed to enter notes during VCH creation, so we cannot get back any notes during "vic-machine ls"

**Comment by stuclem** [comment]
Looks good to me!
