### ISSUE TITLE
VIC does not support creating a volume with auto-generated name

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1560]
Actual behavior:
Error response from daemon: Server error from Portlayer: Name in body is required

Expected behavior:
anon@anon-Latitude-E7450:~/vic$ docker volume create 
d3a0986406196224a06f4592c3ef730f97646a0cc920c31d9656ee16b3ecfd20

**Comment by matthewavery** [comment]
This was closed in a previous PR but the ticket was missed in the actual pr. pr #2058 is reenabling the test for this case which shows that we do in fact support uuid random names of volumes now.

**Comment by matthewavery** [comment]
This has been resolved.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
