### ISSUE TITLE
When specifying capacity of a volume, volume create does not handle invalid input correctly

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1562]
Actual behavior:
```
1. anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.149:2376 --tls volume create --opt Capacity=0  --name test5
Error response from daemon: Server error from Portlayer: Capacity in body is required
2. anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.149:2376 --tls volume create --opt Capacity=-1  --name test6
test6
3. anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.149:2376 --tls volume create --opt Capacity=99999999999999999999999999  --name test7
Error response from daemon: Bad Driver Arg: Capacity must be an integer value. The unit is MB: strconv.ParseInt: parsing "99999999999999999999999999": value out of range
4. anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.149:2376 --tls volume create --opt Capacity=2147483647  --name test8
Error response from daemon: Server error from Portlayer: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:0xc82021ab58 Message:File [datastore1] mike-test/VIC/volumes/test8/test8.vmdk is larger than the maximum size supported by datastore 'datastore1}
5. anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.149:2376 --tls volume create --opt Capacity=9147483647  --name test9
Error response from daemon: Server error from Portlayer: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:0xc8201fc848 Message:File [datastore1] mike-test/VIC/volumes/test9/test9.vmdk is larger than the maximum size supported by datastore 'datastore1}
6. anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.149:2376 --tls volume create --opt Capacity=100  --name test4
Error response from daemon: Server error from Portlayer: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:0xc8201fca48 Message:file already exists}
```

Expected behavior:
We need to clean up most of the wording of these errors, additionally:
1. Don't indicate an optional parameter is required, just indicate it is invalid output
2. Don't create volume when capacity is specified as -1
3. Just need error language cleanup
4. Just need error language cleanup
5. Error from 3 indicates we only support int, but this somehow parses and just returns too big error?
6. Just need error language cleanup

**Comment by mdubya66** [comment]
Needs triage. Flagging for Onsite for now. May be related to #1503

**Comment by matthewavery** [comment]
I need to update the integration tests for the `docker volume` call to check this.

**Comment by matthewavery** [comment]
@mhagen-vmware loooks like the standard docker approach would be to return `invalid size: %s` is this a better string to look for?

**Comment by mhagen-vmware** [comment]
That are like 6 scenarios up there, for which scenario(s) do you propose printing invalid size: %s?

**Comment by matthewavery** [comment]
Almost all of them really. It would fit both the negative and the 0 value inputs. The really large inputs we could possibly look for a different value too. perhaps a `Capacity range out of bounds: %s` on the number?

**Comment by matthewavery** [comment]
For number 6 we may already have better message handling now. This ticket has been around for a little while. and some changes have occurred since then.

**Comment by mhagen-vmware** [comment]
It works for me, if we can match docker output, should be fine.
