### ISSUE TITLE
Volume create name parameter needs input checking

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1563]
Actual behavior:
anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.149:2376 --tls volume create --opt Capacity=100  --name test???
test???

Expected behavior:
anon@anon-Latitude-E7450:~/vic$ docker volume create --name test???
Error response from daemon: create test???: "test???" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

**Comment by fdawg4l** [comment]
@matthewavery looks related to other sanitation that I think you're looking at.
