### ISSUE TITLE
Volume create with a bad driver specified results in success

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1564]
Actual behavior:
Running command 'docker -H 192.168.254.168:2376 --tls volume create -d fakeDriver --name=test2'
${rc} = 0 	
${output} = test2

Expected behavior:
Error looking up volume plugin fakeDriver: plugin not found

**Comment by matthewavery** [comment]
@mhagen-vmware currently we are really just ignoring the driver argument. I will look at this, shouldn't be a hard fix. Then we can assume the `default` driver and the ` vsphere` driver are the targets. I have this marked as lower priority in my list.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
