### ISSUE TITLE
When you create volume, the capacity is not reported by govc

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1565]
Not sure if this is expected or not but when I create a volume with capacity of 100, then run a test on it using govc I receive the following:
```
'[{"Datastore":{"Type":"Datastore","Value":"573f3c77-f5dc6515-f2ad-000c2938cb96"},"FolderPath":"[datastore1] test/VIC/volumes/test4","File":[{"Path":"test4-flat.vmdk","FileSize":0,"Modification":null,"Owner":""},{"Path":"test4.vmdk","FileSize":0,"Modification":null,"Owner":""}]}]' does not contain '"FileSize":100'
```

**Comment by matthewavery** [comment]
@mhagen-vmware We use sparse disks so until they are written to they will not "inflate" so the Filesize will not be 100 even though the disk allocated should have a capacity of 100.  cc @fdawg4l thoughts?

**Comment by fdawg4l** [comment]
@mhagen-vmware im not following how you can create a volume and use govc to test it.  Can you post a link to the test and the govc invocation?

**Comment by fdawg4l** [comment]
Also, @matthewavery is right.  The size of the disk will only include the data written to it.

**Comment by mhagen-vmware** [comment]
@fdawg4l This is tested in:
Docker volume create with specific capacity
In the 1-19-Docker-Volume-Create.robot test suite. 

@matthewavery Sparse is fine, I can write it out to inflate it and test it I guess...

**Comment by fdawg4l** [comment]
Inflating it is likely not the best way to find out the size.  If, for test purposes, you create a container with a given size, you should probably just attach to the container and `du -h` the device.  Inflating has it's own issues and actually verifying the volume is created, attached, of the correct size, AND mounted, is likely the best approach.

**Comment by matthewavery** [comment]
@mhagen-vmware here is the solution for checking disk sizes. `${disk-size}=  Run  docker ${params} logs $(docker ${params} start $(docker ${params} create -v ${output}:/mydata busybox /bin/df -Ph) && sleep 10) | grep by-label | awk '{print $2}' `

the mount will show the actualy size of the disk.
