### ISSUE TITLE
Enable govmomi context timeouts

### ISSUE THREAD

**Issue by dougm** [vmware/vic#157]
We are currently using a single Context.Background for all govmomi operations.  We should look at using the context to provide a default timeout for vsphere oprations and more fine grained timeouts as needed.

https://godoc.org/golang.org/x/net/context

https://blog.golang.org/context

**Comment by dougm** [comment]
Looks like the context package will be included with Go 1.7: https://github.com/golang/go/issues/14660

**Comment by mdubya66** [comment]
low for now.

**Comment by dougm** [comment]
We are using Context timeouts/deadlines now where appropriate.
