### ISSUE TITLE
cannot enable tty mode on non tty input

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1582]
Our integration tests are now failing on the link test.  It works locally when running robot directly, but I am able to reproduce when I run using drone locally, so it appears to be some sort of nested container/drone related issue.

**Comment by mhagen-vmware** [comment]
@caglar10ur :

https://github.com/docker/toolbox/issues/136

Removing -t seems to eliminate that issue, but now causes:
Error response from daemon: vSphere Integrated Containers does not implement container.ContainerWait

**Comment by mhagen-vmware** [comment]
This is now a dupe of: #384

**Comment by caglar10ur** [comment]
reopening this and referring from disabled tests
