### ISSUE TITLE
Shrink/expand image layers to delta disk

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#159]
Currently (in b-ville), each layer is created on a delta disk with a static size (8GB IIRC).  The disks are sparse and grow as data is actually written, but this poses interesting issues when moving images between datastores that don't have enough physical space relative to the provisioned VMDK size.

Instead, we should set the vmdk size after creating the delta disk relative to the size of that layer's physical size.  Barring files with wholes in them (sparse files), this will mirror the tar size.

**Comment by hickeng** [comment]
For TP3: @stuclem we need to document the default base disk size.
For GA: @fdawg4l we need to allow configuration of the base disk size for images for GA.

The other elements are post-GA.

**Comment by stuclem** [comment]
This issue is included as a known issue in the release notes for TP3.

**Comment by fdawg4l** [comment]
Created #1781 to track the ask for GA.  Removing the GA label for this issue and using #1781 instead.

**Comment by stuclem** [comment]
Fixed. Removing the kind/note tag.
