### ISSUE TITLE
Session cannot resolve to multiple hosts for "/ha-datacenter/host/*/*"

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1595]
There are multiple places in the unit tests where we don't successfully resolve multiple hosts in the case where they exist. See comment I added to session_test.go for #1461

```
// FIXME: session.Create incorporates Populate which loses the type of any original error from vmomi
// In the case where the test is run on a cluster with multiple hosts, find.MultipleFoundError
// gets rolled up into a generic error in Populate. As such, the best we can do is just grep for the string, which is lame
// The test shouldn't fail if it's run on a cluster with multiple hosts. However, it won't test for anything either.
```
This also impacts vm_test.go. When run against a system with multiple hosts, it fails in vsphere/test/test.go line 46

```
	s, err := session.NewSession(config).Create(ctx)
```
The test is clearly intended to pick a random host, but it never gets there.

```
=== RUN   TestVMFailureWithTimeout
--- FAIL: TestVMFailureWithTimeout (1.09s)
	test.go:47: ERROR: Failure finding host (/ha-datacenter/host/*/*): path '/ha-datacenter/host/*/*' resolves to multiple hosts
=== RUN   TestVMAttributes
--- FAIL: TestVMAttributes (1.27s)
	test.go:47: ERROR: Failure finding host (/ha-datacenter/host/*/*): path '/ha-datacenter/host/*/*' resolves to multiple hosts
```

It's not clear to me how we should go about resolving this, so we should put in a workaround for now as a WIP. This issue should remain open though until we've resolved it.

**Comment by dougm** [comment]
dup of #1365 - in that the inventory paths in these tests assuming running against ESX.
