### ISSUE TITLE
Document the VCH info returned by Docker info

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1598]
Probably just a nice to have, but it might be worth listing the VCH details that docker info now returns, per https://github.com/vmware/vic/issues/1390 and PR https://github.com/vmware/vic/pull/1572.

**Comment by stuclem** [comment]
We should also doc that docker info does not reveal datastore paths, which might include sensitive vSphere information, per https://github.com/vmware/vic/issues/1540.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1572 is merged.

**Comment by stuclem** [comment]
The VCH specific information listed in https://github.com/vmware/vic/issues/1390 and PR https://github.com/vmware/vic/pull/1572 should go into the description column in the [Supported Operations](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md) table. We should also add the note about vSphere datastore paths.

**Comment by stuclem** [comment]
See also PR https://github.com/vmware/vic/pull/1732.

**Comment by npakrasi** [comment]
Updated Docker info in Supported Docker Commands table to include VCH info and not reveal vSphere datastore paths.
