### ISSUE TITLE
Document vic-machine option to specify bridge network range

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1599]
Implemented in PR https://github.com/vmware/vic/pull/1589. Can't find an associated dev issue.

**Comment by stuclem** [comment]
Looks like  PR #1589 wasn't merged in time for onsite beta.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/pull/1589 is now merged.

**Comment by stuclem** [comment]
Added the following to the descriptions of the vic-machine create options. @hmahmood, is this OK?

### `bridge-network-range` ###

Short name: `--bnr`

The range of IP addresses that container VMs can use if the network that you specify in the `bridge-network` option does not support DHCP. If you do not specify this option, the IP range for container VMs is 172.16.0.0/12.

When you specify the bridge network IP range, you specify the IP range as a CIDR.

<pre>--bridge-network-range 192.168.100.0/24</pre>

**Comment by stuclem** [comment]
You can see this doc in situ here: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#bridge-network-range

**Comment by hmahmood** [comment]
A couple of comments: bridge networks never use DHCP, so that should not be mentioned. Also, the IP range is for bridge networks only; bridge networks are allocated from this range. For example, given a range of 172.16.0.0/12, the following ranges will be allocated to bridge networks: 172.16.0.0/16, 172.17.0.0/16, and so on, up to 172.31.0.0/16 (up to 16 networks can be created).

**Comment by stuclem** [comment]
Updated the doc as follows:

### `bridge-network-range` ###

Short name: `--bnr`

The range of IP addresses that additional bridge networks can use when container application developers use `docker network create` to create new bridge networks. If you do not specify the `bridge-network-range` option, the IP range for bridge networks is 172.16.0.0/12.

When you specify the bridge network IP range, you specify the IP range as a CIDR.

<pre>--bridge-network-range 192.168.100.0/24</pre>

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#bridge-network-range

**Comment by hmahmood** [comment]
@stuclem 👍

**Comment by stuclem** [comment]
Thanks @hmahmood
