### ISSUE TITLE
Docker rm fails on vSAN with "no such container"

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1624]
```
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker -H 10.118.67.44:2376 --tls pull busybox
Using default tag: latest
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete 
8ddc19f16526: Pull complete 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker -H 10.118.67.44:2376 --tls run -it  busybox
/ # exit
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# 
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker -H 10.118.67.44:2376 --tls run -it  busybox
/ # exit
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker -H 10.118.67.44:2376 --tls create -it  busybox
8c551104faaf394ce96209ec54263c3250f3235c9bcd7f586145f43d240d7276
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker -H 10.118.67.44:2376 --tls ps -a              
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
8c551104faaf        busybox             "sh"                3 seconds ago        Stopped                                 jovial_booth
6b00b8a114ea        busybox             "sh"                55 seconds ago       Stopped                                 dreamy_panini
e502fb06f782        busybox             "sh"                About a minute ago   Stopped                                 tender_darwin
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker rm 8c551104faaf 6b00b8a114ea
Error response from daemon: No such container: 8c551104faaf
Error response from daemon: No such container: 6b00b8a114ea
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker rm 8c551104faaf             
Error response from daemon: No such container: 8c551104faaf
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# docker rm 8c551104faaf394ce96209ec54263c3250f3235c9bcd7f586145f43d240d7276
Error response from daemon: No such container: 8c551104faaf394ce96209ec54263c3250f3235c9bcd7f586145f43d240d7276
root@photon-machine [ ~/vic/src/github.com/vmware/vic/bin ]# 
```

**Comment by corrieb** [comment]
I'm not yet sure whether it was a combination of things or what, but this really doesn't work

**Comment by mdubya66** [comment]
seems to work on my setup which is fusion running ESX. I did see the timeout issue though.
(mwilliamson) dubs:~/Downloads/vic $ docker --tls pull busybox
Using default tag: latest
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
(mwilliamson) dubs:~/Downloads/vic $ docker --tls run -it busybox
/ # exit
(mwilliamson) dubs:~/Downloads/vic $ docker --tls run -it busybox
docker: Error response from daemon: server error from portlayer : context deadline exceeded.
(mwilliamson) dubs:~/Downloads/vic $ docker --tls create -it busybox
7148ae46adf5ec05c4af2484b6e94e45877db2ee8e411b4f1dd90c3019c2687b
(mwilliamson) dubs:~/Downloads/vic $ docker --tls run -it busybox
/ # exit
(mwilliamson) dubs:~/Downloads/vic $ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
034a99328d98        busybox             "sh"                2 weeks ago         Stopped                                 insane_engelbart
7148ae46adf5        busybox             "sh"                2 weeks ago         Stopped                                 sick_mccarthy
e99157ac18a4        busybox             "sh"                2 weeks ago         Stopped                                 drunk_sammet
b8ad90b0f983        busybox             "sh"                2 weeks ago         Stopped                                 insane_heyrovsky
(mwilliamson) dubs:~/Downloads/vic $ docker --tls rm 034a99328d98 7148ae46adf5
034a99328d98
7148ae46adf5
(mwilliamson) dubs:~/Downloads/vic $ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
e99157ac18a4        busybox             "sh"                2 weeks ago         Stopped                                 drunk_sammet
b8ad90b0f983        busybox             "sh"                2 weeks ago         Stopped                                 insane_heyrovsky
(mwilliamson) dubs:~/Downloads/vic $

**Comment by mdubya66** [comment]
Stopper for Onsite. @matthewavery is investigating

**Comment by corrieb** [comment]
This is me being tired. Notice in the output above, I'm using the docker on my host linux to try to delete images on a remote system. Stand down everyone. Sorry
