### ISSUE TITLE
Insecure private registry

### ISSUE THREAD

**Issue by carsonpadawon** [vmware/vic#1625]
Using VIC v.0.4.0 / build 2868

I am trying to pull images from a private registry.  The registry is on a separate PhotonOS linux box, setup as a
[logs.tar.gz](https://github.com/vmware/vic/files/378241/logs.tar.gz)
 insecure registry using v2 (registry:2).

I have created a VCH using the following command 

 ./vic-machine-linux create -t vcsa-01a.corp.local -u administrator -p VMware1! -r VIC -i ds-site01-iscsi -bridge-network VM-Site01-vDS-Bridge --container-network VM-Site01-vDS-Container -n VCH-Dev --no-tls

After setting the DOCKER_HOST=tcp://192.168.100.246:2375, I issue the following command with the following error:

docker pull 192.168.120.20:5000/busybox
Using default tag: latest
Error while pulling image: Head https://192.168.120.20:5000/v2/: http: server gave HTTP response to HTTPS client

I have another Photon OS setup to run the docker daemon locally and it works as expected with the above docker pull command.

Log files attached. 

[logs.tar.gz](https://github.com/vmware/vic/files/378243/logs.tar.gz)

**Comment by caglar10ur** [comment]
that's expected @carsonpadawon as we added the required flag after the 0.4.0 tag, can you try a recent build? I tried exactly doing that 2 days ago and as far as I see everything works fine on our end

**Comment by carsonpadawon** [comment]
I just tried build 3248 and have the same results.  This causes an issue with the docker run command.  When I issue "docker --tls run -it 192.168.120.20:5000/busybox" it will pull the image from the private registry but won't run because there is not tag on the image.  so I have to do a pull then a run with just busybox as the image name.

**Comment by caglar10ur** [comment]
This is a different issue (related with tagging) passing the baton to @cgtexmex

**Comment by cgtexmex** [comment]
related to...if not duplicated by #1638

**Comment by reasonerjt** [comment]
@caglar10ur 

> that's expected @carsonpadawon as we added the required flag after the 0.4.0 tag, can you try a recent build? I tried exactly doing that 2 days ago and as far as I see everything works fine on our end


Do you mean in 0.4.0 VIC it support option like "--incesure-registry"?
If this is the case, how can I set it?  I'm also trying to pull image from a http registry.

**Comment by caglar10ur** [comment]
@reasonerjt does not support insecure registries. We added that support after we release 0.4.0. And looks like latest builds can pull the image but cannot run them due to #1638

**Comment by reasonerjt** [comment]
@caglar10ur Thanks for the reply.
So could you let me know what flag is needed?  Just checked the code seems there's flag in imagec:
> flag.BoolVar(&options.insecureAllowHTTP, "insecure-allow-http", false, i18n.T("Uses unencrypted connections when fetching images"))
But did not find how's that referenced in apiserver.

btw, I'm new to vic, could you let me know if there's a way to patch a deployed VCH?  Or do I have to rebuild the appliance.iso and re-deploy using vic-machine?

**Comment by mdubya66** [comment]
>btw, I'm new to vic, could you let me know if there's a way to patch a deployed VCH? Or do I have to rebuild the appliance.iso and re-deploy using vic-machine?

Delete the VCH and re-install is the current method for patching.

**Comment by reasonerjt** [comment]
Thanks @mdubya66

**Comment by caglar10ur** [comment]
closing this as required arguments are in and #1638 tracking the tagging issue

**Comment by mdubya66** [comment]
@ reasonerjt is harbor blocked from working with vic because of this or #1638?

**Comment by stuclem** [comment]
RN tracked in #1638. Removing kind/note.
