### ISSUE TITLE
container-logs does not have container logs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1626]
This is a followup issue from #1542 

In that issue the container-logs.tar.gz bundles supplied by @cormachogan do **not** have the container debug logs that would be critical for diagnosing this. There is an error in the vicadmin log:
```
time="2016-07-20T08:38:41Z" level=error msg="failed to connect: Failed to log in to https://10.27.51.103/sdk: ServerFaultCode: Cannot complete login due to an incorrect user name or password." 
```

This needs to be looked into ASAP as collection of container logs is crucial to our ability to diagnose problems.

**Comment by hickeng** [comment]
@kjplatz assigned to you for assessment. Please confirm whether or not you get container logs in our VC environments.

If not then please look at this as a matter of urgency, otherwise please work with @cormachogan to figure out why we're seeing this in only his environment.

**Comment by kjplatz** [comment]
Attempting to replicate the configuration using https://bintray.com/vmware/vic-repo/build/3164 -- when I specify the container-network-gateway of 192.168.100.0/24, this is now disallowed in the current build with the error:

ERRO[2016-07-25T09:51:51-05:00] Gateway 192.168.100.0 is not a routable address 

Will continue attempting to replicate.

**Comment by kjplatz** [comment]
It would appear that the problem is related to logging into the vSphere sdk:  "Failed to log in to https://<IP address> due to incorrect user name or password."  Continuing to research
