### ISSUE TITLE
Document the default PATH when not specified in image

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1628]
Per https://github.com/vmware/vic/issues/1509, https://github.com/vmware/vic/issues/1594 and PR https://github.com/vmware/vic/pull/1608

Info from Zach via Slack:

basically we are following the docker convention of adding a default PATH when someone builds a container image without one. vmware/photon is a good example - the dockerfile is very very minimal and doesn't include a path

the dockerfile looks like this:

```
FROM scratch
MAINTAINER tliaqat@vmware.com

ADD stage/photon-rootfs-$PHOTON_RELEASE_VERSION-$PHOTON_BUILD_NUMBER.tar.bz2 /

VOLUME /var/lib/docker

CMD ["bash", "--login"]
```

as you can see, they didn't supply a path of any kind so when you try to start a container with something like `docker run -it vmware/photon` it tries to run `bash --login` but there's no PATH defined so it can't find it. here's docker's docs about that:  https://docs.docker.com/engine/reference/run/#/env-environment-variables

**Comment by stuclem** [comment]
For the section on container use.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1608 was merged aeons ago. Moving to To Do.

**Comment by npakrasi** [comment]
Added to container_limitations.md:
- When you do not configure a PATH environment variable, or create a container from an image that does not supply a PATH, vSphere Integrated Containers Engine provides a default PATH.

**Comment by stuclem** [comment]
Covered by global doc review. Closing.
