### ISSUE TITLE
/etc/hosts should be 644 in container images

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1644]
The generated /etc/hosts file in the container image should be created with mode 644 so that applications such as postgres that launch as non-root users can resolve hostnames correctly.

**Comment by mdubya66** [comment]
assigning to @anchal-agrawal for initial evaluation

**Comment by anchal-agrawal** [comment]
Can reproduce on a busybox container. `/etc/hosts` has mode 600.

This is where `/etc/hosts` is being created: https://github.com/vmware/vic/blob/master/lib/etcconf/etcconf.go#L64

To assign the correct permissions to `/etc/hosts`, I can `chmod` it after it has been created here.

**Comment by mdubya66** [comment]
should we not have a way to create the file(s) with the correct permissions to begin with?

**Comment by anchal-agrawal** [comment]
The files seem to be created with 0644 here: https://github.com/vmware/vic/blob/master/lib/etcconf/etcconf.go#L43

**Comment by mdubya66** [comment]
@hmahmood any input on this?

**Comment by hmahmood** [comment]
In [`save`](https://github.com/vmware/vic/blob/master/lib/etcconf/etcconf.go#L64) we actually create a temp file before renaming it to `/etc/hosts`. The temp file may not be created with 644. A simple fix would be to change the permissions on /etc/hosts after rename.

**Comment by anchal-agrawal** [comment]
Thanks @hmahmood. I'm trying out this fix.

**Comment by anchal-agrawal** [comment]
Closed via #1663
