### ISSUE TITLE
Tether DHCP client is deficient

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1653]
Several issues need to be fixed:
- the DHCP client state machine is not implemented, see http://www.tcpipguide.com/free/t_DHCPGeneralOperationandClientFiniteStateMachine.htm
- handling of what parameters to request from the server: which parameters to request based on config
- use an external library for the dhcp client: we really should not be writing our own dhcp client. The code in place right now is not tested extensibly, and there are several corner cases that we have not accounted for that other seasoned dhcp clients already have. The dhcp client also needs to be more modular.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage
