### ISSUE TITLE
Use external dhcp library to implement client

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1655]
DHCP has several corner cases that we cannot possibly account for in our code in the time we have. Existing libraries/clients may be considerably more seasoned, and so we should consider using them. One possibility: systemd's DHCP client code. It is available here: https://github.com/systemd/systemd/blob/master/src/systemd/sd-dhcp-client.h . However, this is not available as a separate (shared) library, and so we would have to build it ourselves.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mhagen-vmware** [comment]
Too big, should be decomposed
