### ISSUE TITLE
Not enough information in build logs to debug container issues 

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1659]
Currently only the log from the container and vmware.log are present in the build log for a failed build. This currently does not give enough information, for instance, to debug networking issues. We need a way get more information about the container in the build logs. Maybe a dump of guestinfo, and other commands like we do for the VCH.

**Comment by hickeng** [comment]
Agree for containers - the guestinfo is extremely useful. You should get this dumped if debug >= 1.
We cannot just dump the raw guestinfo for the appliance as it contains passwords - this is actually still a concern for containers as people may well be passing credentials in the environment.
