### ISSUE TITLE
Bash shell is not accessible through SSH to VCSA

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#1668]
This is an urgent issue for VIC UI installation. For the onsite beta today Karthik tried installing the VIC UI plugin using the installer script, where there are (at least for now) two SSH connections to the target VCSA (one for `scp` and the other for `chown`) But the installer failed saying `Unknown command: scp` because the default shell was not Bash for the VCSA used for demo. (see below) I was able to install the plugin by launching the Bash terminal but this is clearly not the instruction we want the users to follow.

![image](https://cloud.githubusercontent.com/assets/3834071/17119529/14a6e624-528c-11e6-9719-9049de245ec8.png)

Using a Docker image prepared for the VIC UI plugin installation might be the most preferable solution, as it allows us to stick with the standard plugin deployment procedure thus not requiring  scp or ssh. It could contain a simple HTTP server which hosts the plugin bundle file and the VC extension data that would be consumed by the `vic-ui` command. For example, the UI installation could be simplified by firing up a Docker container:

`docker -H {VCH_IP} run --name vic-ui-installer -d -p 8081:80 {VIC_UI_INSTALLER_IMAGE}`

Then the plugin URL and extension info (e.g. version) could be queried by the container's web server and then passed to the `vic-ui` command.

What needs to be figured out is, 1) if this is an acceptable solution in the first place, and 2) which registry should this image be hosted in.

**Comment by andrewtchin** [comment]
This looks like part of the way to what we were talking about in early discussions about `vic-machine install-ui` with some manual steps to start the UI installer container and have the user log out of the web UI to trigger the install. I like this approach as it will remove some of the junk in the install script and make it more platform independent. 

How will the user get the image if there's no internet connection though?

**Comment by jooskim** [comment]
Right. I remember there's a way to import a bundle to create an image. [https://docs.docker.com/engine/reference/commandline/import/](https://docs.docker.com/engine/reference/commandline/import/)

**Comment by emlin** [comment]
we should have docker import image function ready, then no need to download registry from internet

**Comment by jooskim** [comment]
Will come up with a temporary solution which involves the exact step I took above. However, this issue definitely needs to be revisited soon.
