### ISSUE TITLE
Implement vic-machine integration test plan

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#1671]
https://github.com/vmware/vic/pull/1661 added the test plan and we have some basic tests, but we need to add the remaining tests. 

As a customer of VIC, I would like to have confidence that vic-machine utility has been thoroughly tested in a variety of scenarios.

As an engineer of VIC, I would like to have a set of vic-machine tests that are complete so that I can have confidence when I make a change to vic-machine then the tests will capture and possible errors.

**Comment by mhagen-vmware** [comment]
@andrewtchin Hey Andrew, if you haven't made any significant progress on this yet, let me and @rajanashok work on it so you can focus on bug fixes over the next 2 weeks.

**Comment by mhagen-vmware** [comment]
Talked with @andrewtchin - @rajanashok and I are going to take this over after he merges his current PR for this:  #3009

**Comment by andrewtchin** [comment]
@mhagen-vmware @rajanashok #3009 was merged you're good to go

**Comment by mhagen-vmware** [comment]
Bulk of this is done, but it is a huge story, moving the rest to work on it over the next few weeks.

**Comment by zjs** [comment]
Is there specific remaining work that this is tracking? Group 6 now seems to have a variety of tests for `vic-machine`.

**Comment by mhagen-vmware** [comment]
Just grep for:
    Pass execution  Test not implemented
Within Group 6.
