### ISSUE TITLE
docker volume create only takes default as label name

### ISSUE THREAD

**Issue by carsonpadawon** [vmware/vic#1672]
Build 3248

vicadmin@vicMgr [ ~/vic ]$ ./vic-machine-linux create -t vcsa-01a.corp.local -u administrator -p VMware1! -r VIC -i ds-site01-iscsi -b VM-Site01-vDS-Bridge --container-network VM-Site01-vDS-Container:containerNet --container-network-gateway containerNet:192.168.120.1/16 --container-network-dns containerNet:192.168.110.10 --container-network-ip-range containerNet:192.168.120.75-100 --volume-store ds-site01-iscsi/HOL1730DockerVols:dockerVols -n VCH-volume
INFO[2016-07-26T15:03:03Z] ### Installing VCH ####
INFO[2016-07-26T15:03:03Z] Generating certificate/key pair - private key in ./VCH-volume-key.pem
INFO[2016-07-26T15:03:04Z] Validating supplied configuration
INFO[2016-07-26T15:03:04Z] Firewall status: ENABLED on "/CloudNativeApps/host/VIC/esx-01a.corp.local"
INFO[2016-07-26T15:03:04Z] Firewall status: ENABLED on "/CloudNativeApps/host/VIC/esx-02a.corp.local"
INFO[2016-07-26T15:03:04Z] Firewall configuration OK on hosts:
INFO[2016-07-26T15:03:04Z]   "/CloudNativeApps/host/VIC/esx-01a.corp.local"
INFO[2016-07-26T15:03:04Z]   "/CloudNativeApps/host/VIC/esx-02a.corp.local"
INFO[2016-07-26T15:03:04Z] License check OK on hosts:
INFO[2016-07-26T15:03:04Z]   "/CloudNativeApps/host/VIC/esx-01a.corp.local"
INFO[2016-07-26T15:03:04Z]   "/CloudNativeApps/host/VIC/esx-02a.corp.local"
INFO[2016-07-26T15:03:04Z] DRS check OK on:
INFO[2016-07-26T15:03:04Z]   "/CloudNativeApps/host/VIC/Resources"
INFO[2016-07-26T15:03:05Z] Creating virtual app "VCH-volume"
INFO[2016-07-26T15:03:05Z] Datastore path is [ds-site01-iscsi] HOL1730DockerVols
INFO[2016-07-26T15:03:05Z] Creating appliance on target
INFO[2016-07-26T15:03:05Z] Network role "management" is sharing NIC with "client"
INFO[2016-07-26T15:03:05Z] Network role "external" is sharing NIC with "client"
INFO[2016-07-26T15:03:06Z] Uploading images for container
INFO[2016-07-26T15:03:06Z]      "bootstrap.iso"
INFO[2016-07-26T15:03:06Z]      "appliance.iso"
INFO[2016-07-26T15:03:13Z] Registering VCH as a vSphere extension
INFO[2016-07-26T15:03:19Z] Waiting for IP information
INFO[2016-07-26T15:03:45Z] Waiting for major appliance components to launch
INFO[2016-07-26T15:03:45Z] Initialization of appliance successful
INFO[2016-07-26T15:03:45Z]
INFO[2016-07-26T15:03:45Z] Log server:
INFO[2016-07-26T15:03:45Z] https://192.168.100.129:2378
INFO[2016-07-26T15:03:45Z]
INFO[2016-07-26T15:03:45Z] DOCKER_HOST=192.168.100.129:2376
INFO[2016-07-26T15:03:45Z]
INFO[2016-07-26T15:03:45Z] Connect to docker:
INFO[2016-07-26T15:03:45Z] docker -H 192.168.100.129:2376 --tls info
INFO[2016-07-26T15:03:45Z] Installer completed successfully
vicadmin@vicMgr [ ~/vic ]$ docker -H 192.168.100.129:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Storage Driver: vSphere Integrated Containers Backend Engine
vSphere Integrated Containers Backend Engine: RUNNING
 VCH mhz limit: 7096 Mhz
 VCH memory limit: 5.162 GiB
 VMware Product: VMware vCenter Server
 VMware OS: linux-x64
 VMware OS version: 6.0.0
Execution Driver: vSphere Integrated Containers Backend Engine
Plugins:
 Volume: dockerVols
 Network: containerNet bridge
Operating System: linux-x64
OSType: linux-x64
Architecture: x86_64
CPUs: 7096
Total Memory: 5.162 GiB
Name: VCH-volume
ID: vSphere Integrated Containers
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
Registry: registry-1.docker.io
vicadmin@vicMgr [ ~/vic ]$ docker -H 192.168.100.129:2376 --tls volume create --name web
Error response from daemon: Server error from Portlayer: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:0xc8204233b8 Message:file already exists}
vicadmin@vicMgr [ ~/vic ]$

```

Would like to be able to attach any label to the volume name

ONLY works with "default" as the label.
[logs (1).tar.gz](https://github.com/vmware/vic/files/384143/logs.1.tar.gz)

**Comment by cormachogan** [comment]
I think you are missing the following option from the docker volume create command:

--opt VolumeStore=<label>

So in your case you need the following:

--opt VolumeStore=dockerVols

**Comment by fdawg4l** [comment]
@carsonpadawon, Can you try the same command with the flag Cormac suggests?  Unless specified, our volume layer will try to create volumes on the "default" volume store and it sounds like that's what's happening here.  Thanks!

**Comment by carsonpadawon** [comment]
vicadmin@vicMgr [ ~/vic ]$ docker -H 192.168.100.129:2376 --tls volume create --name web --opt VolumeStore=dockerVols                                 Error response from daemon: Server error from Portlayer: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:0xc82000fa78 Message:file already exists}
vicadmin@vicMgr [ ~/vic ]$

**Comment by cormachogan** [comment]
This suggests that there is a volume called web already in the volume store. Can you check via the files view on the datastore if that is the case?

**Comment by carsonpadawon** [comment]
That was my fault, there was a volume already there with "web".  I was able to create with the --opt VolumeStore=.  THANK YOU.  Is there a list of commands somewhere for --opt

**Comment by cormachogan** [comment]
There are only 2 right now:

--opt Capacity="size in MB" 
--opt VolumeStore="label"

**Comment by fdawg4l** [comment]
@carsonpadawon Sounds like you're up and running.  I'm going to close the issue.  Thanks!
