### ISSUE TITLE
Failed to find slot for NIC when more than 3 interfaces are added to VCH

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1674]
I ran into this when I created a VCH that had 4 NICs. We use slot numbers to lookup up interfaces in the tether code. The slot numbers are assigned by vic-machine. However, there is no guarantee that vsphere will honor these slot numbers. This is what happened here; vsphere assigned a different slot number to the one we set in guestinfo.

We need to stop using slot numbers to identify interfaces, and move to using device labels instead. Device labels are named Ethernet0, Ethernet1, and so on, in the order NICs are added to the VM's config.

**Comment by hickeng** [comment]
@emlin As a temporary workaround we should check for this in vic-machine and report and error.
This is not a fix, just a guard against broken VCHs for the beta.

**Comment by hickeng** [comment]
#2802 has more detail, but this one has age precedence.

**Comment by emlin** [comment]
@hickeng do we need to keep this issue open after the workaround?
