### ISSUE TITLE
avoid the attach/detach path for empty layers

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1688]
Currently we are attaching/detaching disks for those layers which are metadata only. In a fast environment that doesn't add too much time to a pull, however yesterday in a very slow env I saw a significant amount of time being spent with attach/detach of the 32B metadata layers.

If possible we should add an optimization which skips this path for those layers which have no files to extract.

Assigning to @fdawg4l for estimate - not putting it in scope for GA for now.

**Comment by fdawg4l** [comment]
@hickeng How, in the storage layer, do we know if the layer is a metadata layer?  This can only be discovered and marked as such from the docker server, no?

**Comment by fdawg4l** [comment]
@jzt I think you mentioned you had an appropriate issue / change for this specific issue.  Should we keep this issue open (in case you need storage level changes)?

**Comment by jzt** [comment]
@fdawg4l I have a fix coming for image ID consistency through proper handling of empty layer metadata, but I haven't added anything to prevent disk creation/attach/detach for empty layers. I think this will be a relatively straightforward fix, so if you want to toss it in the backlog, I'm happy to grab it this sprint as part of my image ID work. My estimation would probably be a 1, 2 if we want to conservatively account for any potential unknowns or unforeseen hurdles.

**Comment by fdawg4l** [comment]
Ok, I think the requirements are clear but the implementation and components involved need to be worked out.  Lets create an epic for the ask (which is to skip empty images, but store their relevant info somewhere), and then issues in the epic for storage and for imagec with the things we need to do to get the epic done.

**Comment by mdubya66** [comment]
low for now as not implicit for 1.1

**Comment by hickeng** [comment]
#4763 looks like it might be the flip side of this - speculation as I've not looked at it in depth, but it's definitely related to repeated behaviour/output around the metadata only layer case.

**Comment by hickeng** [comment]
Closing this having found #4168 which has significantly more detailed discussion in it.
