### ISSUE TITLE
Add RBAC constraints to the ID that's used by the VCH.

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1689]
The extension that is registered per VCH has unrestricted admin access currently. We need to apply RBAC constraints to this extension ID if that is possible.
- [X] determine if it is possible to apply RBAC to an extension ID
  - NOT POSSIBLE, RBAC REQUIRES USER
- [x] determine what RBAC privileges need to be specified for a VCH
  - [x] confirm VCH function with non-admin user
  - [x] confirm VCH function with RBAC constrained user
  - [x] document required privileges
- [ ] add tests to assert correctness of privilege docs #3951 

Optionally:
- [ ] programmatically apply RBAC privileges when creating VCH.

https://bugzilla.eng.vmware.com/show_bug.cgi?id=1729956

**Comment by mdubya66** [comment]
who should get this one?

**Comment by hickeng** [comment]
Added #2875 for supplying the creds of a separate operations user (precreated service account)

**Comment by dougm** [comment]
govmomi PR: vmware/govmomi#628

**Comment by dougm** [comment]
With the PR mentioned above, next steps would be in vic-machine:

* We can create a new role using govmomi object.AuthorizationManager.AddRole (see govc/role/create.go for reference)

* Role privilege set still TBD, but can be limited to specific entities in the step below (vs all managed entities as the Admin role is).  Note that the full privilege set can be viewed using `govc role.ls Admin`

* Use govmomi object.AuthorizationManager.SetEntityPermissions to grant principal (-op-username) role permission on the VCH vapp/resource-pool entity (see govc/permission/set.go for reference)

**Comment by hickeng** [comment]
Started running through the necessary permissions.

For ESX:
* assign role to entire host - needed for finder operation or cannot discover cluster, pool, datastore, etc.
* low level file control - needed for KV store creation
* host->system management - needed for session ticket/file upload/download
* vm->configuration->add new disk

Going to drop this for now and just add the PR for a separate operations user

**Comment by hickeng** [comment]
Dumping the RBAC config from a working VCH deployed on vCenter 6.5:

```
vagrant@devbox:~$ for i in "VCH - vcenter" "VCH - datacenter" "VCH - datastore" "VCH - network" "VCH - endpoint"; do  echo ======= Role $i ============;echo "******" Configuration; govc role.ls "$i"; echo;echo "******" Usage; govc role.usage "$i"; echo;echo;done  | grep -v '^System\.'
======= Role VCH - vcenter ============
****** Configuration
Datastore.Config

****** Usage
Role           Entity  Principal          Propagate
VCH - vcenter  /       VSPHERE.LOCAL\ops  No


======= Role VCH - datacenter ============
****** Configuration
Datastore.Config
Datastore.FileManagement

****** Usage
Role              Entity  Principal          Propagate
VCH - datacenter  /dc1    VSPHERE.LOCAL\ops  No


======= Role VCH - datastore ============
****** Configuration
Datastore.AllocateSpace
Datastore.Browse
Datastore.Config
Datastore.DeleteFile
Datastore.FileManagement
Host.Config.SystemManagement

****** Usage
Role             Entity                        Principal          Propagate
VCH - datastore  /dc1/datastore/vsanDatastore  VSPHERE.LOCAL\ops  No
VCH - datastore  /dc1/host/cluster1            VSPHERE.LOCAL\ops  Yes


======= Role VCH - network ============
****** Configuration
Network.Assign

****** Usage
Role           Entity                                  Principal          Propagate
VCH - network  /dc1/network/netFolder/InternalNetwork  VSPHERE.LOCAL\ops  No


======= Role VCH - endpoint ============
****** Configuration
DVPortgroup.Create
DVPortgroup.Delete
DVPortgroup.Modify
DVPortgroup.PolicyOp
DVPortgroup.ScopeOp
VApp.AssignVM
VirtualMachine.Config.AddNewDisk
VirtualMachine.Config.AdvancedConfig
VirtualMachine.Config.EditDevice
VirtualMachine.Config.RemoveDisk
VirtualMachine.GuestOperations.Execute
VirtualMachine.Interact.DeviceConnection
VirtualMachine.Interact.PowerOff
VirtualMachine.Interact.PowerOn
VirtualMachine.Inventory.Create
VirtualMachine.Inventory.Delete
VirtualMachine.Inventory.Register
VirtualMachine.Inventory.Unregister

****** Usage
Role            Entity                                     Principal          Propagate
VCH - endpoint  /dc1/host/cluster1/Resources/ghicken-vc65  VSPHERE.LOCAL\ops  Yes
```

Additionally, `Read-Only, with Propagate to Children` is required on the parent of any Distributed vSwitch's that are used by the VCH. To avoid adding Read-Only to the datacenter, you may create a network inventory folder and place the DVS in that.
```

**Comment by hickeng** [comment]
Revised privileges, again against 6.5 - the main difference being the addition of VirtualMachine.Config.Rename:
```
======= Role VCH - vcenter ============
****** Configuration
Datastore.Config

****** Usage
Role           Entity  Principal          Propagate
VCH - vcenter  /       VSPHERE.LOCAL\ops  No


======= Role VCH - datacenter ============
****** Configuration
Datastore.Config
Datastore.FileManagement

****** Usage
Role              Entity  Principal          Propagate
VCH - datacenter  /dc1    VSPHERE.LOCAL\ops  No


======= Role VCH - datastore ============
****** Configuration
Datastore.AllocateSpace
Datastore.Browse
Datastore.Config
Datastore.DeleteFile
Datastore.FileManagement
Host.Config.SystemManagement

****** Usage
Role             Entity                        Principal          Propagate
VCH - datastore  /dc1/datastore/vsanDatastore  VSPHERE.LOCAL\ops  No
VCH - datastore  /dc1/host/cluster1            VSPHERE.LOCAL\ops  Yes


======= Role VCH - network ============
****** Configuration
Network.Assign

****** Usage
Role           Entity                                  Principal          Propagate
VCH - network  /dc1/network/netFolder/InternalNetwork  VSPHERE.LOCAL\ops  No


======= Role VCH - endpoint ============
****** Configuration
DVPortgroup.Modify
DVPortgroup.PolicyOp
DVPortgroup.ScopeOp
VApp.AssignVM
VirtualMachine.Config.AddNewDisk
VirtualMachine.Config.AdvancedConfig
VirtualMachine.Config.EditDevice
VirtualMachine.Config.RemoveDisk
VirtualMachine.Config.Rename
VirtualMachine.GuestOperations.Execute
VirtualMachine.Interact.DeviceConnection
VirtualMachine.Interact.PowerOff
VirtualMachine.Interact.PowerOn
VirtualMachine.Inventory.Create
VirtualMachine.Inventory.Delete
VirtualMachine.Inventory.Register
VirtualMachine.Inventory.Unregister

****** Usage
Role            Entity                                     Principal          Propagate
VCH - endpoint  /dc1/host/cluster1/Resources/ghicken-vc65  VSPHERE.LOCAL\ops  Yes
```

**Comment by hickeng** [comment]
As @dougm has mentioned, govmomi has the calls to support this now. The estimate is for:
* creating the appropriate roles if missing
* adding ops-user/role as a permission on the relevent inventory paths for the new VCH

Question - should the role have a VIC version associated so we can easily alter permissions, or should the roles be the most permissive combination of privileges required of current configured privileges and those necessary for the deployment?

**Comment by mdubya66** [comment]
This is an opportunistic for 1.2 otherwise we get it into 1.3 @karthik-narayan

**Comment by karthik-narayan** [comment]
@mdubya66 I don't believe that this was in the 1.2 asks, so I'm okay with it being opportunistic.

**Comment by lcastellano** [comment]
Replaced by: https://github.com/vmware/vic/issues/6492
