### ISSUE TITLE
Document docker login and authentication

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1697]
Per https://github.com/vmware/vic/issues/368.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/368 is (partially?) implemented in PR https://github.com/vmware/vic/pull/2105. Check with @sflxn whether we can claim full support.

**Comment by stuclem** [comment]
According to @mdubya66 in [this comment](https://github.com/vmware/vic/issues/368#issuecomment-242209799), issue https://github.com/vmware/vic/issues/368 is required for 0.5.5

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/2105 is now merged.

**Comment by npakrasi** [comment]
Added to Docker commands table.
