### ISSUE TITLE
Document docker save

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1699]
Doc the docker command to get a tarball of images, per https://github.com/vmware/vic/issues/501.

**Comment by npakrasi** [comment]
Added to Supported Docker Commands table under Future Release and will move it to Supported in GA when it is.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/501 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#104
