### ISSUE TITLE
Embed MoRef in URL for datastore in storage layer and vchConfig

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1709]
We're using URLs to represent the `[datastoreName] path/to/dir`.  For clarity this becomes

`
u := &url.URL{
     Scheme: "ds",
     Host: "datastoreName",
     Path: "path/to/dir"
}
`

The issue is the datastore name may include characters (spaces) that the URL spec doesn't support.  Also, we don't want to use names where we can use MoRefs.

We need to create a `struct` that either embeds the URL or has a reference to one, includes a member for the managed object reference, and has helpers to get between the datastore string format, the `object.Datastore` + path, and a URL representation (of the form `ds://<mo-ref>/path/to/thing`).

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by hickeng** [comment]
Fixed by update to use govmomi DatastorePath structure.
