### ISSUE TITLE
Implement volume ls filtering

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1718]
Expected:
docker volume ls -f name=test
Error response from daemon: Invalid filter 'name'

Actual:
DRIVER VOLUME NAME
 vsphere test
1. Not sure if we want to actually block filtering based on name or not, it would seem to be a nice feature that docker doesn't actually support.
2. We seem to be ignoring the filter completely, as no matter what I put in there it actually returns all volumes.

1 is a choice we can make, 2 is more egregious.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by mhagen-vmware** [comment]
lgtm
