### ISSUE TITLE
Creating 75 containers fails due to connection reset

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1723]
This is from Erin on the performance team. One of the tests she has it to start 75 containers simultaneously, and she is reporting over 50 of the starts failing. Attached are the logs from the tests. It seems like we are dropping the sdk connection at some point, and subsequent starts fail.

[esxtop.csv.gz](https://github.com/vmware/vic/files/388881/esxtop.csv.gz)
[results.txt](https://github.com/vmware/vic/files/388879/results.txt)
[vic_esx_docker-personality.txt](https://github.com/vmware/vic/files/388880/vic_esx_docker-personality.txt)
[vic_esx_install.txt](https://github.com/vmware/vic/files/388878/vic_esx_install.txt)
[vic_esx_logs.tar.gz](https://github.com/vmware/vic/files/388882/vic_esx_logs.tar.gz)
[vic_esx_run.txt](https://github.com/vmware/vic/files/388883/vic_esx_run.txt)

**Comment by corrieb** [comment]
I feel like we should learn to walk before we can run here. How do we do with 5 or 10 or 20? Our existing 30 second timeout is going to probably be insufficient at a far smaller number than 75

**Comment by carlsone** [comment]
The same test consistently succeeds with 10 parallel containers.

**Comment by corrieb** [comment]
I feel we should focus on #1724 first. Solving that - or at least improving it - would help significantly here. As a second order concern, we should adapt vcsim so that we can simulate creating containers very fast. This will help us figure out where the bottlenecks are in our control plane. Created #1731

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by gigawhitlocks** [comment]
Volunteered for this but was given something higher priority before I could get started; sorry for the assignee / pipeline spam above.

**Comment by karthik-narayan** [comment]
@mdubya66 Can we bump the priority on this one for the next sprint? Both the performance and scale teams will be working close to these limits and will be blocked if we are not able to fix this.

**Comment by mdubya66** [comment]
I think we should consider it for inclusion into 1.2 but for 1.1 this would be too risky for the final sprint, IMO. @karthik-narayan. Setting to medium

**Comment by karthik-narayan** [comment]
@mdubya66 Apologies. I meant to say for 1.2, not 1.1.

**Comment by anishmehta1** [comment]
This is a blocker for the perf team in 1.2. It needs to be prioritized for a fix early in the 1.2 dev cycle. We suspect this may impact the Systems Test team too.

**Comment by mdubya66** [comment]
Perf blocker for 1.2

**Comment by rameshya-vmw** [comment]
has this defect been resolved or being worked on? this is a perf blocker and performance team is waiting to have this fixed

**Comment by caglar10ur** [comment]
@rameshya-vmw still working on this. I ended up finding problems in both esxi and vic code bases. I'll update this ticket as soon as we have a solution/workaround.

**Comment by rameshya-vmw** [comment]
is there an ETA for the fix?

**Comment by caglar10ur** [comment]
@rameshya-vmw I'm testing it right now. I can provide you an experimental build to test if you want?

**Comment by rameshya-vmw** [comment]
i think that might help Erin, from performance team to do her testing

**Comment by caglar10ur** [comment]
sure, will follow up with an email in couple of hours

**Comment by rameshya-vmw** [comment]
thanks !

**Comment by caglar10ur** [comment]
The fix is in so closing this
