### ISSUE TITLE
Modify vcsim to allow for testing control plane concurrent performance

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#1731]
If we could drive our control plane (both the docker personality and the port layer) against vcsim for basic container lifecycle operations (create, start, ps, delete) and if vcsim could simulate sub-second container start-times, we could get a really good sense of where the bottlenecks are in our current control plane.

Take #1723 as an example. Figuring out how much of the issues are due to hostd, how much of it is due to I/O contention and how much of it is down to locking/timing issues in the control plane is almost impossible to determine without such a simulator.

As such, I consider this an important test for both finding concurrent bugs, stress-testing the control plane and looking for low-hanging fruit in terms of performance

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage
