### ISSUE TITLE
Container logs need to have timestamp or a mechanism to index by timestamp

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1738]
Container logs currently do not have any timestamps.  For full docker logs functionality, the logs must have some mechanism for associating log lines with a timestamp.

As a developer on admiral, I need VIC to implement timestamps on docker logs in order for admiral to work with VIC.

**Comment by corrieb** [comment]
+1 this is annoying

**Comment by mdubya66** [comment]
Moving this to ToDo as it's a feature and needed for admiral

**Comment by mdubya66** [comment]
moving to todo as this was forgotten during sprint planning. we should not do this :)

**Comment by jzt** [comment]
See #3971 for details around the design approach.
