### ISSUE TITLE
Historical stdout and stderr must be kept for complete docker logs functionality

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1739]
To have complete docker log functionality, we must have some way to keep historical stdout and stderr for a container, and they need to be timestamped.  If you execute docker logs --since=<timestamp> you can extract all container logs, container stdout, container stderr up to that timestamp.  This implies docker is keeping that data around.  Today, when we attach to the tether, it returns all stdout and stderr starting from that point, and there are no timestamps.

Initial docker logs will not keep that historical logs nor support timestamps, but if we want complete compatibility in the future, the tether will need to store these two streams around.

**Comment by sflxn** [comment]
It appears docker is always persisting stdout and stderr by default to a json file.  Format of the file here,

```
{"log":"line 1\n","stream":"stdout","time":"2016-07-29T21:53:16.497927342Z"}
{"log":"line 2\n","stream":"stdout","time":"2016-07-29T21:53:17.498191741Z"}
{"log":"line 3\n","stream":"stdout","time":"2016-07-29T21:53:18.499047896Z"}
{"log":"line 4\n","stream":"stdout","time":"2016-07-29T21:53:19.499568038Z"}
{"log":"line 5\n","stream":"stdout","time":"2016-07-29T21:53:20.500413505Z"}
{"log":"line 6\n","stream":"stdout","time":"2016-07-29T21:53:21.500956192Z"}
```

When I first perform an attach, it simply output output from this point in time on.

**Comment by sflxn** [comment]
After chatting with @hickeng on Friday, I realized the container logs already has all historical outputs of stdout and stderr.  It's just not tagged by stream and not timestamped.

**Comment by dougm** [comment]
Closing as we already have the complete history and we have #1738 to track timestamp support.
