### ISSUE TITLE
ERROR: 404 page not found while running docker-compose voting app

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1745]
```
Creating network "test_default" with the default driver
Building vote
ERROR: 404 page not found
```

Logs attached:
[VCH-0-8726-container-logs.tar.gz](https://github.com/vmware/vic/files/390881/VCH-0-8726-container-logs.tar.gz)

**Comment by hickeng** [comment]
We do not and will not support docker build directly.

@caglar10ur @mreferre @cormachogan Do you think that the lack of build support is going to cripple the use of compose?

**Comment by cormachogan** [comment]
My only concern is if we want to support deploying project harbor via VIC?

If so, then we would need to support compose build.

Sent from my iPhone

On 29 Jul 2016, at 18:50, George Hicken <notifications@github.com<mailto:notifications@github.com>> wrote:


We do not and will not support docker build directly.

@caglar10ur<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_caglar10ur&d=CwMCaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=ys6LqVsV5QiNhPLPoZGFfdrRMM6_ugU-8w_yuLbjC5c&m=dByzQX8P1luTV5_laqu53dTlfKhpRUZ9tnDueYtY0uM&s=mq0zehojb2psnUkyV-eZHURRPSv1oqKd3IG5LWH_hlU&e=> @mreferre<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mreferre&d=CwMCaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=ys6LqVsV5QiNhPLPoZGFfdrRMM6_ugU-8w_yuLbjC5c&m=dByzQX8P1luTV5_laqu53dTlfKhpRUZ9tnDueYtY0uM&s=MZiagFIhKXk7G7v-7vSPdcGfyvVgnlVKBbz_SYwZuJI&e=> @cormachogan<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cormachogan&d=CwMCaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=ys6LqVsV5QiNhPLPoZGFfdrRMM6_ugU-8w_yuLbjC5c&m=dByzQX8P1luTV5_laqu53dTlfKhpRUZ9tnDueYtY0uM&s=z72_TWmcdsqk9UZQfjrH-UKT0WkgeXtLFGsngtUlMGM&e=> Do you think that the lack of build support is going to cripple the use of compose?

-

**Comment by caglar10ur** [comment]
I think we can't support all the compose yml files without build support but we can still bring up compositions if they just refer to an image on somewhere.

**Comment by mdubya66** [comment]
Removing VIC GA. If this does get pulled into the release to support Harbor then we can have that discussion.

**Comment by bobbyjunzhang** [comment]
In another work stream targeting VMworld US, the Harbor team is actively working on deploying Harbor to VIC via docker run (instead of docker compose.) Very likely we will have a working solution by August. If this timeline works for you, the VIC team should certainly consider to include Harbor in VIC GA.

**Comment by mdubya66** [comment]
adding @corrieb and @karthik-narayan

**Comment by sflxn** [comment]
I just copied my comments from the parent issue (docker-compose up):

```
One comment. The lack of support for mapped volumes (vs named or anonymous data volumes) really restricts what applications can be deployed. Most real applications do want some configuration to be given to it during deployment. Usually, these config are not baked into the application. We do not yet support docker cp so we cannot get config files to the data volumes. Without mapped volumes, there is no other way to get a config file to the application other than via docker build (baking config into the application).

I am still trying to get docker build to work via DIND, but so far, I have not figure out how to do this since the dockerfile and all pertinent files are on the local machine and not the VCH. If this can't be done with DIND, customers will have to bake in their config into their apps with regular docker, upload to a registry, and deploy from that registry.

Another option is to recommend customers build 12-factor apps (config via env variables) or recommend they build containers that take config via command line options.
```

So, without 1) docker cp, 2) docker build, 3) mapped volumes, 4) alias/link, VIC's support for compose will be very limited.  This will be their workflow:

1) create app that takes args from env var or commandline options (no config files)
2) use regular docker to build containers of them
3) push to registry
4) Create compose yml that does not use aliases/links
5) deploy

We're going to spend a lot of time advising customers to use this narrow path.

**Comment by sflxn** [comment]
I have a lot more comments in the parent issue (compose up).  If you want to follow, I'd recommend reading that issue.

**Comment by sflxn** [comment]
I think we can forget about the current voting app and create our own custom multi-tier app examples.  One of which can use the existing voting app as the basis.

**Comment by emlin** [comment]
We have compose function running in test https://github.com/vmware/vic/blob/master/tests/test-cases/Group3-Docker-Compose/3-02-Docker-Compose-Voting-App.robot

**Comment by mhagen-vmware** [comment]
Should this be in the Sprint 4 milestone?

**Comment by corrieb** [comment]
I've been encouraging the team to focus on the simple docker-compose examples on Docker's website as their acceptance criteria for Compose work. Seems like we're already running the voting app. I would defer to @sflxn on this

**Comment by sflxn** [comment]
I'm moving to close.

**Comment by sflxn** [comment]
@emlin I was about to close this issue but I went to check out our robot scripts.  It currently only checks if the container is running.  Back last year, we were curling the server, but curl was causing problems in our CI.  In other words, although, I believe this is not an issue anymore, we should verify that we can bring up the voting app and hit the page.

**Comment by mhagen-vmware** [comment]
Well, my bigger concern here @sflxn is that we are not actually running the standard voting app, we are running a modified voting app right? So that if we run the standard voting app we would still see this either way because we don't and aren't going to implement build right? That puts us in a bad position, because just returning ERROR: 404 when a customer tries to run the standard voting app is not a good story. If we aren't going to actually support what it takes to run the standard voting app, we need to at least provide a reasonable error not some random page not found error...

**Comment by emlin** [comment]
@mhagen-vmware what about we open another issue to track the docker build issue? So if you're okay with the change for integration test, we can close this issue.

**Comment by sflxn** [comment]
@mhagen-vmware I've had this discussion with Ben and George many times.  Right now, all we can do is to say our recommended workflow is to use a registry for production deployment.  Use standard docker for development workflow.

**Comment by emlin** [comment]
Leave this bug open to track the missing function of docker build, and the impact for docker compose.
Move it back to backlog, and use new issue #4220 to track verification requirement

**Comment by corrieb** [comment]
Reading back through this bug, we have a few issues that are conflated.

1) The error message if "build" is used in a docker file. That's now improved. You now get:
"ERROR: build path <path>/vote either does not exist, is not accessible, or is not a valid URL."
Would it be nice to get a "VIC engine does not support build"? Yes, but we could say that for everything in a compose file we don't support.

2) The notion we have to change a compose file to use it with VIC. That's a given at this point - at the very least, the version needs to be "2" - it's mostly "3" in online samples now.

3) The voting app now works with VIC, albeit with modifications. I'm currently addressing the documentation issues around explaining the differences.

Closing this as I don't see what else we can do.
