### ISSUE TITLE
The Tailf function does not check if the file exists before trying to open it

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#1754]
A check is needed so that we do not try to open and seek a non existent file. Which could happen in certain use case scenarios of VIC. 

line 306 of `cmd/vicadmin/logs.go 
`f, err := os.Open(file)`

**Comment by hagenmt** [comment]
Make sure to address any of the other issues pointed out by George in #1722 as well

**Comment by hickeng** [comment]
Consider using the hpcloud/tail package or similar rather than writing from scratch.
