### ISSUE TITLE
Contianers do not start {portlayer : context deadline exceeded.}

### ISSUE THREAD

**Issue by Bonn93** [vmware/vic#1768]
**VIC Version:** 0.5.0 

**ESX Version:** ESXi 6.0.0 2494585 

**Description:** After installing and inspecting a/ verifying the install, I cannot start any containers. I perform the docker pull busybox, and then attempt a run busybox, the contain appears to be created and initially boots, however after a few seconds, the container is powered off. 

I've attached the logs that I can find/see relevant. Please advise if you require more detail. I've only just started playing with VIC, so bare with me. :-)

**In the docker log server**;

`time="2016-08-02T03:28:24Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/portlayer.(*ContainerProxy).CommitContainerHandle] ContainerProxy.CommitContainerHandle" 
time="2016-08-02T03:28:26Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/portlayer.(*ContainerProxy).CommitContainerHandle] [2.097867095s] ContainerProxy.CommitContainerHandle" 
time="2016-08-02T03:28:26Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).containerCreate] [2.117238647s] Container.containerCreate" 
time="2016-08-02T03:28:26Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [2.117360994s] ContainerCreate" 
time="2016-08-02T03:28:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] ContainerAttach" 
time="2016-08-02T03:28:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] ContainerStart" 
time="2016-08-02T03:28:45Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerKill] ContainerKill" 
time="2016-08-02T03:28:45Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerKill] [1.065376ms] ContainerKill" 
time="2016-08-02T03:28:56Z" level=error msg="container attach: stdout (18b3c289ee778620efdad906b13d144e517762b7d564175d2451b5c2f98b6424): Unknown error from the interaction port layer: ByteStreamConsumer can only deal with io.Writer" 
time="2016-08-02T03:28:56Z" level=error msg="container attach: stderr (18b3c289ee778620efdad906b13d144e517762b7d564175d2451b5c2f98b6424): Unknown error from the interaction port layer: context canceled" 
time="2016-08-02T03:28:56Z" level=info msg="container attach:  cleaned up connections to 18b3c289ee778620efdad906b13d144e517762b7d564175d2451b5c2f98b6424." 
time="2016-08-02T03:28:56Z" level=error msg="container attach error: Unknown error from the interaction port layer: ByteStreamConsumer can only deal with io.Writer" 
time="2016-08-02T03:28:56Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] [30.000908724s] ContainerAttach" 
time="2016-08-02T03:28:56Z" level=error msg="Handler for POST /v1.23/containers/18b3c289ee778620efdad906b13d144e517762b7d564175d2451b5c2f98b6424/attach returned error: Unknown error from the interaction port layer: ByteStreamConsumer can only deal with io.Writer" 
2016/08/02 03:28:56 http: response.WriteHeader on hijacked connection
2016/08/02 03:28:56 http: response.Write on hijacked connection
time="2016-08-02T03:28:56Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] [30.002552233s] ContainerStart" 
time="2016-08-02T03:28:56Z" level=error msg="Handler for POST /v1.23/containers/18b3c289ee778620efdad906b13d144e517762b7d564175d2451b5c2f98b6424/start returned error: server error from portlayer : context deadline exceeded" `

**Docker-Personaility.log;**

`time="2016-08-02T03:37:37Z" level=info msg="container attach:  cleaned up connections to 4ba45950ae20cb62b246d39fbe43fe686faf4770999dff51d9eb491716e8563c." 
time="2016-08-02T03:37:37Z" level=error msg="container attach error: Unknown error from the interaction port layer: ByteStreamConsumer can only deal with io.Writer" 
time="2016-08-02T03:37:37Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] [30.000648724s] ContainerAttach" 
time="2016-08-02T03:37:37Z" level=error msg="Handler for POST /v1.23/containers/4ba45950ae20cb62b246d39fbe43fe686faf4770999dff51d9eb491716e8563c/attach returned error: Unknown error from the interaction port layer: ByteStreamConsumer can only deal with io.Writer" 
2016/08/02 03:37:37 http: response.WriteHeader on hijacked connection
2016/08/02 03:37:37 http: response.Write on hijacked connection
time="2016-08-02T03:37:37Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] [30.002597367s] ContainerStart" 
time="2016-08-02T03:37:37Z" level=error msg="Handler for POST /v1.23/containers/4ba45950ae20cb62b246d39fbe43fe686faf4770999dff51d9eb491716e8563c/start returned error: server error from portlayer : context deadline exceeded" `

**Comment by mdubya66** [comment]
@hickeng please triage and re-assign to appropriate team member

**Comment by Bonn93** [comment]
I've setup a Jenkins job to rebuild this each day, it seems to be fixed and working today.

`Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      0.4.0
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   175304a
 Built:        Mon Aug  8 02:53:48 2016
 OS/Arch:      linux/amd64
 Experimental: true`

Deploying the VCH machine does fail randomly, however might be a DHCP issue. 

Happy to close for now.
