### ISSUE TITLE
Document that vic-machine checks datastore connection

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1771]
Per https://github.com/vmware/vic/issues/1166.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1166 is implemented in PR https://github.com/vmware/vic/pull/2005.

**Comment by stuclem** [comment]
If datastores are not accessible from all of the hosts, `vic-machine create` fails with the following error:

`No single host can access all of the requested datastores. Installation cannot continue.`

Create a troubleshooting topic about this.

**Comment by stuclem** [comment]
![ds-check](https://cloud.githubusercontent.com/assets/16718369/18583271/dcf6f33e-7c09-11e6-9fcb-6088d57f5e00.png)

**Comment by stuclem** [comment]
If only one host in a cluster can access the designated datastore, `vic-machine create` succeeds with the warning:` Only one host can access all of the image/container/volume datastores. This may be a point of contention/performance degradation and HA/DRS may not work as intended.`

**Comment by stuclem** [comment]
Added this info in two new bullets in the [Datastore Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#datastore) section of the topic on `vic-machine create` options.

@andrewtchin is this correct? Thanks!

**Comment by andrewtchin** [comment]
Those 2 points look correct to me. @gigawhitlocks is the one who made the new message about HA/DRS

**Comment by stuclem** [comment]
OK, thanks @andrewtchin.
