### ISSUE TITLE
Allow admin to set capacity for base disk (scratch) via vic-machine

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1781]
We need to allow the admin to set the base disk capacity via `vic-machine`.  Currently we use 8gb for the base disk and it's not tunable by the user.

**Comment by matthewavery** [comment]
cc @fdawg4l can you comment briefly on what reopened this issue?

**Comment by fdawg4l** [comment]
I believe the change was reverted. Also, I believe @sgairo reopened it. She may have more details.

**Comment by sgairo** [comment]
Correct, Matt W. asked that I revert and reopen last Thursday.



On Aug 29, 2016, at 9:26 AM, Faiyaz Ahmed <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe the change was reverted. Also, I believe @sgairo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sgairo&d=CwMCaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=tCZwlfDcXCdCpz3_ppVAqoiM28k06Nbbnu9QsMcIJfo&m=od5_QCsq3rd9C6nMJOUcnA9o4l86u31S8172RP1bj-c&s=-S43djhZ74SA7bxsQmHLl_xk8aR5RRJ-fbihdkbAfSQ&e=> reopened it. She may have more details.

-

**Comment by gigawhitlocks** [comment]
This was reopened due to a failing integration test that I checked in. The test is fixed and the feature has been in master for a few days now, so I'm closing this.
