### ISSUE TITLE
vic-machine delete leaving containers behind

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1787]
I'm seeing container remnants left on several of the CI systems. Some of them cannot easily be identified as they are tagged as _invalid_, meaning that the corresponding datastore files have been deleted directly.

I'm also seeing empty VCH-X-Y resource pools left lying around on the systems, and containerVMs that have been orphaned (resource pool deleted before the VMs)

However some of them are named _webserver-xxx_ from the pretty name PR. This suggests to me that something related to the network port mapping tests could be the culprit. A quick check of that test suite showed nothing obvious however.

![image](https://cloud.githubusercontent.com/assets/3923729/17353389/01653e4e-58f4-11e6-984f-88312f3aad8b.png)

![image](https://cloud.githubusercontent.com/assets/3923729/17353423/4f37338e-58f4-11e6-9ee6-e8d0968dbab9.png)

![image](https://cloud.githubusercontent.com/assets/3923729/17353431/67466b34-58f4-11e6-83e4-36a6a8c4e23c.png)

**Comment by emlin** [comment]
@mdubya66 We'll need more triage for it, to make correct estimation.

**Comment by andrewtchin** [comment]
I reproed this on a nimbus esx and in this case found that this is a manifestation of the invalid state bug in #1823 
```
⇒  bin/vic-machine-linux delete --target root:e2eFunctionalTest@10.160.125.59 --name VCH-0-8447 --force
Error opening logfile vic-machine.log: open vic-machine.log: permission denied
INFO[2016-08-23T10:24:51-07:00] ### Removing VCH ####                        
INFO[2016-08-23T10:24:52-07:00]                                              
INFO[2016-08-23T10:24:52-07:00] VCH ID: VirtualMachine:214                   
INFO[2016-08-23T10:24:53-07:00] Removing VMs                                 
ERRO[2016-08-23T10:24:53-07:00] Operation failed: The attempted operation cannot be performed in the current state (Powered off). - (&{{} %!!(MISSING)s(*types.InvalidPowerState=&{{{{<nil> []}}} poweredOff poweredOff}) The attempted operation cannot be performed in the current state (Powered off).}) 
INFO[2016-08-23T10:24:53-07:00] Specify --force to force delete              
INFO[2016-08-23T10:24:53-07:00] Collecting ha-host hostd.log                 
ERRO[2016-08-23T10:24:54-07:00] Failed to destroy vm "VirtualMachine:218": Operation failed: The attempted operation cannot be performed in the current state (Powered off). - (&{{} %!s(*types.InvalidPowerState=&{{{{<nil> []}}} poweredOff poweredOff}) The attempted operation cannot be performed in the current state (Powered off).}) 
ERRO[2016-08-23T10:24:54-07:00] --------------------                         
ERRO[2016-08-23T10:24:54-07:00] vic-machine-linux failed: delete failed
```

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
