### ISSUE TITLE
vic-machine update volume-store

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1797]
Had one discussion with @matthewavery this afternoon. 
So far, customer has to carefully design their volume store usage during VCH deployment. After deployment, if user didn't have any volume store configured, or consumed too many volume store capacity, there is no way to add any other volume store into existing VCH.

So this issue is to track volume-store update requirement for vic-machine.
User should be able to run vic-machine command to update volume store configuration for one specific VCH.

**Comment by mdubya66** [comment]
@hickeng should this be post GA?

**Comment by mdubya66** [comment]
Putting this in the Icebox for now. We can look at pulling it out if we get the time.

**Comment by mdubya66** [comment]
VCH reconfigure is a 1.1 feature

**Comment by emlin** [comment]
Duplicate with #4512, close this one
