### ISSUE TITLE
ContainerStop should implement timeout

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1813]
Currently VIC's `docker stop -t <timeout in seconds>` does not honor the timeout.

We need to add a timeout parameter to the portlayer `Commit` call and use it in places where a timeout can be supplied.

**Comment by mhagen-vmware** [comment]
dupe of https://github.com/vmware/vic/issues/1321 ?

**Comment by jzt** [comment]
Yep, closing.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
