### ISSUE TITLE
Error response from daemon: server error from portlayer : context deadline exceeded 

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#1822]
I am using a recent build (1 week) old and I keep hitting what appears to be timeout issues. 

This is a good example of it: 

     root@ubuntu:/go/src/github.com/vmware/vic/bin# docker --tls run -d vmwarecna/nginx
     561914bca648562c43df58c5b513693be422c13776bd9f1d6192c0b15cd3ec56
     root@ubuntu:/go/src/github.com/vmware/vic/bin# docker --tls run -d vmwarecna/nginx
     f646d5b158813f77af2a4ac0fe13bd36dc616397d35af515aed54ede7f0da64b
     root@ubuntu:/go/src/github.com/vmware/vic/bin# docker --tls run -d vmwarecna/nginx
     4578cfe14f4e8e1dd279a2ff445b5d5d3090ffb34aaad226db65f91bf7b6b474
     docker: Error response from daemon: server error from portlayer : context deadline exceeded.

When this happens (randomly) that container appears to be running (ps) but you can't do much with it (can't stop, can't rm, etc). The only workaround I found is to power it off in the vSphere UI, at which point you can rm it (or even start it!). 

Gut feeling is that this happens more often with bigger images (perhaps the deployment time takes longer than expected and it times out?). 

Everything else keeps working fine (docker info, docker ps, docker images, etc). Only container operations on containers that experienced that issue will fail. 

I am using a nested environment (with a VM providing shared storage via NFS). I know it could be slow but I am not looking for performance, just functionalities.

**Comment by mreferre** [comment]
After further testing in my (nested) environment I am leaning to conclude that the problem is due to using the NFS shared storage (provided by a VM running alongside the ESXi hosts). 

To exercise the setup I am using a script that deploys 10 containers: 

      for i in {0..9}
      do 
      echo -n "instantianting container: nginx$i - " & docker --tls run -d -p 8$i:80 --name nginx$i vmwarecna/nginx
      done


This is the result of a text script that deployes 10 x nginx when the VCH is on the NFS shared storage:

      root@ubuntu:~# ./multiple-containers-create.sh 
      instantianting container: nginx0 - c730cc6f18ded6584f1171afbf202922982db9e2e033a310a808f27109e6123a
      instantianting container: nginx1 - f869a1ff2ee46d75402baa60211ee53fc2772be711a4e12c8fc37e979d425a32
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.
      instantianting container: nginx2 - d80f91e4795d793ae4312a9007194339fbe5e678f81d8f2eaceef8304a33c610
      instantianting container: nginx3 - 82411be185267459e2a654459bd18d687e5b290ed2ceda24fcf82a64328e1b4d
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.
      instantianting container: nginx4 - fceb066fe06f5d3f2d147cd9d972ea6f9c81ee0429d4932f45847b04ff571f45
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.
      instantianting container: nginx5 - bb6b7dfbf30457339dc235de82f09f3d5c913f8cd7ceab63ecdd270519ae5a3a
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.
      instantianting container: nginx6 - 5832a774d98a3f0c7fea717ce6e4382c398fbaac7d303d1f2e857b33418a5634
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.
      instantianting container: nginx7 - 7fe0bd27b56ca137c195d8032f1e3c4aa7cfa78b842f19409a6fbaf3cfcd7f01
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.
      instantianting container: nginx8 - 0030efdb7eef4979f026859154145d0bdd582a968a0c821084c00cdb14fe0d14
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.
      instantianting container: nginx9 - db238c6758fedd0e705aea904b8e842f877b6aed85b9972e600231554bb43b5e
      docker: Error response from daemon: server error from portlayer : context deadline exceeded.

8 out 10 containers fail to initialize. 

This is the result when the VERY same script is executed against a VCH that has been deployed on a local disk of an ESX server (running nested):

       root@ubuntu:~# ./multiple-containers-create.sh 
       instantianting container: nginx0 - a792336bf97cfc4a845bd2efe6696f194a7ef2b7da2ba67e2ff940b2d378525e
       instantianting container: nginx1 - 88717aa3f67af220c4c2207973480c2db02f4f3dd69a6c5e662c8ea029dfa650
       instantianting container: nginx2 - 88af2d07ad8c2a3c5560424450a31451773a13e18b05861a2aeb9c53c9203314
       instantianting container: nginx3 - 056fadf8d043b54a1972b6d737f39f5900e84159bc00fc09ebf3de915db42105
       instantianting container: nginx4 - 35ec77124a0f42500d590d4cb472bd182e0ce9e358b273778b6dc24b0c757e64
       instantianting container: nginx5 - c7302b45c9d63e32853d00011d32a241272bea5fc3370b7fc5357eb386f33104
       instantianting container: nginx6 - bbc769708fa72d69409d570744c3402202af3bcda4c2354aab492cc3584f427f
       instantianting container: nginx7 - b32ec21b7ee83f7d71226bdee02e047cbcefd4ce01d74843801d86138e449972
       instantianting container: nginx8 - 0b2d6b14fc7a2c0714c3214ee6363214d77eebee2596c9039c1ddbc3d5272279
       instantianting container: nginx9 - 8e07230400d9b1688514d122a3195e524e7baf105ea8f41b4634d2ee386f3072

In this specific case it would be important to understand if we could find a workaround (given how pervasive the usage of nested setup for testing purposes is in the core VMware community). 

More broadly I think this also opens up a question of what the storage requirements are for production workloads. 

VIC seems to be (perhaps too much?) sensitive to storage performance. I get that we want to provide a good experience but we shouldn't make the call whether or not it's acceptable on behalf of the user.

**Comment by mdubya66** [comment]
@hickeng for triage

**Comment by mhagen-vmware** [comment]
Still being seen in CI:
[integration_test_logs_3709_1470439492.zip](https://github.com/vmware/vic/files/407049/integration_test_logs_3709_1470439492.zip)

**Comment by mdubya66** [comment]
This is a blocker to CI functioning correctly. Raising it's priority. @hmahmood will you take point on this and the other issues in this list?

#1878, #1870, #1822, #1823, #1109

**Comment by jzt** [comment]
@mhagen-vmware those don't seem to be the logs corresponding to this problem, but instead to the `docker kill` problem that I believe @dougm is already addressing.

**Comment by jzt** [comment]
@mreferre, are you still able to reproduce this? I have attempted it but have been unsuccessful. I believe @caglar10ur's fix that went in last night may have solved this problem. I will test against a known slow/overused VC in our office to see if I can reproduce there.

Here is my output from my local ESX using NFS storage from a local VM (I hit the 8 VM limit on my ESX though, so there are fewer attempts. 😄 ):

```
vagrant@devbox /U/z/g/s/g/v/vic ❯❯❯ ./multiple-containers-create.sh
instantianting container: nginx0 - Unable to find image 'vmwarecna/nginx:latest' locally
Pulling from vmwarecna/nginx
6fa7100a2613: Pull complete
a3ed95caeb02: Pull complete
b6f2388a20dd: Pull complete
a305e4b888ce: Pull complete
80596a504ef3: Pull complete
99c028eff2a4: Pull complete
a1cee46bc434: Pull complete
9bd9868012b9: Pull complete
Digest: sha256:f73bbae0f31823c06478b1fa5efb4957bc25239802fd5ea94e4442c0a6090d23
Status: Downloaded newer image for vmwarecna/nginx:latest
b0cd1490870dd35cb798e91b790094052142c06ebea31c6b26439e79b4f57b34
instantianting container: nginx1 - 4a3e11ab2489277305b1e3ab270d81677429378584841701665f4443b2df7d19
instantianting container: nginx2 - 27592531111d0d3d45c2bf5af7191f09583aacbd8566b931fbd840cd746c1533
instantianting container: nginx3 - 0cb1a755f5c87e63e5e6500a94596649c96922a378b8a8636fd799ed696d4d0f
instantianting container: nginx4 - 630cd120c3cb2542adc5ba10c93dc75c2d3b11ff8a7f8d2d3572138d0af86713
instantianting container: nginx5 - b56539b372718615efc819ff501681702396b0f575b3e66bdc35ee92d5afca70
instantianting container: nginx6 - 34409b6c96b99d768745f65c4b2c467d10ea0c49f27aaa6f45fa30cdcb91b568
instantianting container: nginx7 - 159b3f54b5ec893486ab8629377d163aca370b04c92ed93d10a2ba7c250a8f52
```

**Comment by mreferre** [comment]
I am attaching the logs of a similar occurrence (using build 3991). 
[container-logs.zip](https://github.com/vmware/vic/files/419185/container-logs.zip)

root@ubuntu:~# ./multiple-containers-create.sh 
instantianting container: nginx0 - c18c8cd7c127c77b001918d34f49d305a5e49010806d6802b96092de5296ae6e
instantianting container: nginx1 - 3c289d3d7e65c14df2b7ed22d596335a00dce416a3d56a7478e63b0059ebc44d
instantianting container: nginx2 - 90cc1615a57ad41678a1d55d9bbe87657f3dedffd9fef26bbf3ce88a0d3da77b
instantianting container: nginx3 - ff9002e96ce0ba38f01bad8a874aab6ac0bdaef6be96123f30039879a39d6f1b
instantianting container: nginx4 - 814b443cb63b2779dd09308d2dd9fc7ce55c81a471bd51075086e2a64aa9df15
instantianting container: nginx5 - 3aaa3f4fa52a07087cd986d53352cf4434008558e35e9b42acedb155173a9d03
instantianting container: nginx6 - 9562a82a4fb2293099ddaa0f0a12072e87d0ac1b0a75331f8d91ea135db5a82a
instantianting container: nginx7 - 5ed97bc736632732946e69377b8a964a325a1822f566d77de11ed2cb2850cd36
instantianting container: nginx8 - 980911f867f51569b9294e3b30c78627912673102c9ef355c93f6b40ebbe9f55
instantianting container: nginx9 - 60c22589fc5c53370242cec12fa4ba405b88a87bb81a6d47cf2debe80cfe1352
docker: Error response from daemon: server error from portlayer : context deadline exceeded.

root@ubuntu:~# docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
60c22589fc5c        nginx               "nginx -g daemon off;"   2 minutes ago       Running                                 nginx9
980911f867f5        nginx               "nginx -g daemon off;"   3 minutes ago       Running                                 nginx8
5ed97bc73663        nginx               "nginx -g daemon off;"   4 minutes ago       Running                                 nginx7
9562a82a4fb2        nginx               "nginx -g daemon off;"   5 minutes ago       Running                                 nginx6
3aaa3f4fa52a        nginx               "nginx -g daemon off;"   6 minutes ago       Running                                 nginx5
814b443cb63b        nginx               "nginx -g daemon off;"   7 minutes ago       Running                                 nginx4
ff9002e96ce0        nginx               "nginx -g daemon off;"   8 minutes ago       Running                                 nginx3
90cc1615a57a        nginx               "nginx -g daemon off;"   9 minutes ago       Running                                 nginx2
3c289d3d7e65        nginx               "nginx -g daemon off;"   9 minutes ago       Running                                 nginx1
c18c8cd7c127        nginx               "nginx -g daemon off;"   10 minutes ago      Running                                 nginx0

root@ubuntu:~# docker --tls rm -f 60
Error response from daemon: No such container: 60

root@ubuntu:~# docker --tls rm -f 98
98

**Comment by sflxn** [comment]
I just looked at the code.  I really think this is a timeout issue and not a portlayer issue.  If the portlayer is also using docker's truncindex code then it is possible that there is a problem there, but as far as I know, it is not.

ContainerRm() looks up the full container ID (using the short name which is 60 in this case) as the first operation.  If it cannot find the container partial id, then it will pass that partial id to the portlayer.  As far as I know, the portlayer uses full id for its container cache.

**Comment by mhagen-vmware** [comment]
Saw this again on a build from yesterday;

[integration_logs_4015_81e1bdb20765d0148cb96b27bdee095989de893a_1471297550.zip](https://github.com/vmware/vic/files/420785/integration_logs_4015_81e1bdb20765d0148cb96b27bdee095989de893a_1471297550.zip)

**Comment by mreferre** [comment]
Interestingly, I am now seeing the "no such container" problem even when trying to delete containers that have been previously deployed just fine. 

Here it is what I mean: 

        root@lab-vic01:~# docker --tls ps 
        CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
        623137ef7262        mreferre/haproxy       "/haproxy-start"         3 minutes ago       Running                                 loadbalancer
        ab95dd069d0a        mreferre/go-frontend   "/go/bin/app /bin/sh"    3 minutes ago       Running                                 go-frontend-3
        7a8a8306e7e4        mreferre/go-frontend   "/go/bin/app /bin/sh"    4 minutes ago       Running                                 go-frontend-2
        9417bf702fe1        mreferre/go-frontend   "/go/bin/app /bin/sh"    4 minutes ago       Running                                 go-frontend-1
        e5e7b8605a1b        mongo                  "/entrypoint.sh mongo"   4 minutes ago       Running                                 mongodb-backend

        root@lab-vic01:~# docker --tls rm -f $(docker --tls ps -q)
        623137ef7262
        ab95dd069d0a
        9417bf702fe1
        e5e7b8605a1b
        Error response from daemon: You cannot remove a running container. Stop the container before attempting removal or use -f
        
        root@lab-vic01:~# docker --tls ps -q

        root@lab-vic01:~# docker --tls ps -a
        CONTAINER ID        IMAGE                  COMMAND                 CREATED             STATUS              PORTS               NAMES
        7a8a8306e7e4        mreferre/go-frontend   "/go/bin/app /bin/sh"   16 minutes ago      Stopped                                 go-frontend-2

        root@lab-vic01:~# docker --tls rm -f 7a
        Error response from daemon: No such container: 7a

        root@lab-vic01:~# docker --tls ps -a
        CONTAINER ID        IMAGE                  COMMAND                 CREATED             STATUS              PORTS               NAMES
        7a8a8306e7e4        mreferre/go-frontend   "/go/bin/app /bin/sh"   24 minutes ago      Stopped                                 go-frontend-2

        root@lab-vic01:~# docker --tls stop 7a
        Error response from daemon: No such container: 7a
 
In the vSphere UI I see the container VM shutdown. 

So right now I have seen the "no such container" problem in a couple of scenarios:
1) as a result of a create failure ("context deadline exceeded") 
2) as a result of a delete failure ("Error response from daemon: You cannot remove a running container. Stop the container before attempting removal or use -f") 

I fear there are multiple potential problems here (some of which are interdependent)

**Comment by mdubya66** [comment]
I saw the "no such container" today after I borked the portlayer when I found #2021

**Comment by caglar10ur** [comment]
happened just now

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(retry)] docker run -t postgres
Error: No such container: f77c27594d60c5266266c8867ec34a32d927d3f8592ce93b6a8b3bc7352f0035
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(retry)] docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
f77c27594d60        postgres            "/docker-entrypoint.s"   3 minutes ago       Running                                 focused_mclean
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(retry)]
```

**Comment by caglar10ur** [comment]
[logs.zip](https://github.com/vmware/vic/files/423673/logs.zip)

**Comment by jzt** [comment]
It makes sense to me that, if a context deadline was exceeded in a swagger call during the write step on the portlayer, the container would actually get created but not cached on the persona side, resulting in the ability to see the container in a `ps` but not act upon it except within persona operations that use the portlayer as the source of truth with regard to container existence.

That being said, I'm having trouble reproducing this. I can't force context deadlines to expire (I guess I could hardcode an unrealistic timeout?), and attempting to remove a running container is working as expected (that particular code path seems to check out as well). I'm curious to know what your environments are like, e.g. what builds, whether or not you are still using NFS storage, etc.

Side note:  @mreferre I'm curious to know how `7a8a8306e7e4` was stopped. If you haven't left out any commands between the initial attempt to `rm -f` and the `ps -a` showing it as stopped, I wonder if that's another bug worth looking into.

**Comment by mhagen-vmware** [comment]
Seen also in 8-1 tests here:
[integration_logs_4295_5a80961523980906b45050c2fd07a40463833faf_1471982194.zip](https://github.com/vmware/vic/files/433445/integration_logs_4295_5a80961523980906b45050c2fd07a40463833faf_1471982194.zip)

**Comment by jzt** [comment]
Disregarding those latest logs, as they appear to be caused by the disk space issues created during a merge that has since been reverted.

**Comment by mhagen-vmware** [comment]
See also:
[integration_logs_4428_bce85a24b725d0283f21db7e59b450586419eee0_1472228331.zip](https://github.com/vmware/vic/files/439685/integration_logs_4428_bce85a24b725d0283f21db7e59b450586419eee0_1472228331.zip)

**Comment by hmahmood** [comment]
From the last log bundle it appears that the container VM powered off on its own. My suspicion is a  tether initiated VM shutdown on panic or error. I couldn't find any tether logs in the bundle for the container VM though. @hickeng in what case would we not persist the tether log? From the code it appears we always send the logs over a serial port.

**Comment by mhagen-vmware** [comment]
See also:
[integration_logs_4591_81d1cd58325fb627441f7340b646c208a70b9a20_1472837750.zip](https://github.com/vmware/vic/files/452707/integration_logs_4591_81d1cd58325fb627441f7340b646c208a70b9a20_1472837750.zip)

**Comment by mhagen-vmware** [comment]
Another bundle:
[container-logs.zip](https://github.com/vmware/vic/files/459411/container-logs.zip)

**Comment by mhagen-vmware** [comment]
Another bundle:
[integration_logs_4679_db9538f1627fda3c2a5230f78922f141c9c0dd8c_1473299917.zip](https://github.com/vmware/vic/files/462153/integration_logs_4679_db9538f1627fda3c2a5230f78922f141c9c0dd8c_1473299917.zip)

**Comment by jzt** [comment]
Container commit is currently the only path through container to the PL that has a timeout (aside from attach, but for different reasons). The commit timeout is 1 minute, but commit may call start in the exec portlayer, whose context when waiting for extraconfig to update has a 3 minute deadline (which will never be reached since the parent context's deadline is 1 minute).

@mhagen-vmware is in favor of removing timeouts altogether, but there are concerns of stability issues arising from doing so, in the form of orphaned resources (for example) that may have a negative effect on VC.

@hickeng, @cgtexmex, @mhagen-vmware, @sflxn who wants to put their foot down?

**Comment by jzt** [comment]
Putting up a middle-ground PR for now. Changing commit's timeout to 3min, and removing the timeout/child context from exec's `start`.

We can see if we spot this in CI again.

**Comment by jzt** [comment]
Removed the container start & create timeouts altogether.  The main culprit seems to be `start`, so this should hopefully resolve any CDE's during container operations from here on.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
