### ISSUE TITLE
Update devbox to Ubuntu 16.04

### ISSUE THREAD

**Issue by dougm** [vmware/vic#183]
PR #177 added devbox based on Ubuntu 15.04

There is a 15.10 box, but it currently 403s: boxcutter/ubuntu#47

**Comment by dougm** [comment]
If the boxcutter images aren't publishing vmware_desktop images anymore, let's find another that does.  Any vanilla ubuntu image should do, we can provision docker ourselves if needed.  Just want to avoid building/uploading our own packer images for vanilla ubuntu.

**Comment by cgtexmex** [comment]
There is an open bug w/vagrant in regards to Ubuntu 15.10 and greater.  I'm seeing this with 15.10 & 16.04 -- for now I'll leave the vagrant boxes on 15.04

Vagrant Bug:
https://github.com/mitchellh/vagrant/issues/6683

**Comment by jzt** [comment]
I changed the base box to use `cbednarski/ubuntu-1604`, which fixes all the vagrant problems (HGFS kernel module, wrong ethernet device number, etc).
