### ISSUE TITLE
docker info shows misleading information on a CPU/RAM manually capacity-limited VCH. 

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#1838]
I have deployed a VCH in the root of the cluster. 

if I do a docker info it shows the whole capacity of the cluster in terms of CPU (say 13.000 Mhz) and RAM (say 127GB). 

I opened the properties of the VCH vApp, unflag unlimited and I set limits for CPU and RAM (say 5.000 and 20GB). 

I was expecting docker info to report now 5.000Mhz and 20GB of RAM but it keeps reporting 13.000/127GB. 

Is this the expected behavior? If yes, how do we expect to segment cluster capacity? By nesting the VCH vApp into a regular vSphere RP (where we set those limits)?

**Comment by hickeng** [comment]
@mreferre This is not expected behaviour - it should show the limits if set.

**Comment by hickeng** [comment]
For some reason the CPU and Memory values of the pool are being treated as constant and cached.

**Comment by mreferre** [comment]
Ah!

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mreferre** [comment]
I have been testing with the latest build as of today (6302). I seem to be at least able to size properly a VCH at deployment time using the new --cpu and --memory options for vic-machine. 

Changing values in the properties of the vApp still does not work (because of this bug).

**Comment by anchal-agrawal** [comment]
I believe this was fixed by #2898. @mreferre could you please verify? Thanks!

**Comment by mreferre** [comment]
I will test and report @anchal-agrawal. thanks.

**Comment by mreferre** [comment]
@anchal-agrawal I tested it with 6507 and it works like a charm. 

Thanks.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.
