### ISSUE TITLE
Failed to stop - tools is not running in this virtual machine

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1839]
Failed to stop container via tools: https://ci.vmware.run/vmware/vic/3709
Logs: https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_test_logs_3709_1470439492.tar?authuser=1

From the port-layer log:
```
time="2016-08-05T23:12:16Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] Committing handle" 
time="2016-08-05T23:12:16Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop] Container.stop" 
time="2016-08-05T23:12:16Z" level=warning msg="ShutdownGuest 84feb04eb73110237b6b45fcf4990c204b315f061ae50107132cbc43db3ecf2c failed: ServerFaultCode: Cannot complete operation because VMware Tools is not running in this virtual machine." 
time="2016-08-05T23:12:16Z" level=debug msg="caught EOF" 
time="2016-08-05T23:12:16Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop] [916.358002ms] Container.stop" 
time="2016-08-05T23:12:17Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] [1.275672261s] Committing handle" 
```

**Comment by hickeng** [comment]
@dougm assigned to you with initial estimate. I've not done enough triage to determine whether this is a containerVM side issue or related to timing in the portlayer. We really shouldn't be returning from start until the process is launched so we definitely shouldn't be doing so prior to tools initialization.
We could potentially hit this on the stop path if tools is shut down by main process exit just before we invoke stop from the PL.

**Comment by dougm** [comment]
This test is re-enabled with #2425 - there's been a number of related fixes since this issue was opened.
