### ISSUE TITLE
client is newer than server (client API version: 1.24, server API version: 1.23)

### ISSUE THREAD

**Issue by mbenachour** [vmware/vic#1842]
running this on OSx 10.11.1
docker client version : Docker version 1.12.0, build 8eab29e, experimental

when I run a docker --tls ps 
I get : Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)

the target is a esxi host .

**Comment by mdubya66** [comment]
Try setting DOCKER_API_VERSION=1.23

**Comment by mdubya66** [comment]
VIC currently supports 1.11 but will work with 1.12 with the above workaround. @stuclem do we document the version of docker we rely on?

**Comment by stuclem** [comment]
@mdubya66, I thought that we did, but it's not there any more (maybe that was just for tech preview). Will make sure that we do before we publish doc for 0.5.

**Comment by mdubya66** [comment]
Closing this as a workaround exists and 1.23 is the planned supported API version
