### ISSUE TITLE
Missing functions in vcSim currently found in vic-machine unit test

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1859]
Here list the missing functions required by vic-machine unit test:
- [x] VirtualDeviceList.FindIDEController
- [x] Host.ConfigManager.NetworkSystem, and create distributed virtual switch and distributed port group
- [x] Read and write VM guestinfo
- [x] HostDatastoreBrowser:hostdatastorebrowser-34 does not implement: SearchDatastoreSubFolders_Task
- [x] SearchIndex. Error message: "no such object: SearchIndex:ha-searchindex"

**Comment by emlin** [comment]
@dougm I opened one bug for you, to list all issues I met for vic-machine unit test. Just for your reference.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by dougm** [comment]
"Finder.ObjectReference does not return find.NotFoundError" - also the case against real ESX/VC, the method returns types.ManagedObjectNotFound in both cases.  I'm fixing the code/test to check for that.

"SearchDatastore does not return FileNotFound error" - it does, but the test was using an InvalidDatastorePath - upcoming PR fixes the test.

**Comment by dougm** [comment]
I removed CreateVApp from the list above, since vic-machine handles that case gracefully and we may move away from VApps anyhow.  We can have another story to implement VApp methods if needed.

**Comment by mhagen-vmware** [comment]
lgtm
