### ISSUE TITLE
vic-machine return nil error

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1860]
If there are multiple VC clusters exists, and user didn't specify a correct compute-resource, vic-machine create return error message like following:

invalid memory address or nil pointer dereference

**Comment by emlin** [comment]
Andrew, assign to you for this error comes from check VDS code.
thanks

**Comment by andrewtchin** [comment]
offending line https://github.com/vmware/vic/blob/master/lib/install/validate/network.go#L320
