### ISSUE TITLE
After vic initial install, log server unresponsive

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1868]
Just built VIC (master) and installed on my nested ESX environment.  What I found is the log sever was unresponsive.  I pulled the vic-init log, and I saw the following panic:

Aug 08 21:49:59 vic-docker vic-init[138]: 2016/08/08 21:49:59 http: panic serving 192.168.218.1:55286: runtime error: invalid memory address or nil pointer
 dereference
Aug 08 21:49:59 vic-docker vic-init[138]: goroutine 24 [running]:
Aug 08 21:49:59 vic-docker vic-init[138]: net/http.(*conn).serve.func1(0xc82026b980)
Aug 08 21:49:59 vic-docker vic-init[138]: /usr/local/go/src/net/http/server.go:1389 +0xc1
Aug 08 21:49:59 vic-docker vic-init[138]: panic(0x1076240, 0xc82000e080)
Aug 08 21:49:59 vic-docker vic-init[138]: /usr/local/go/src/runtime/panic.go:443 +0x4e9
Aug 08 21:49:59 vic-docker vic-init[138]: github.com/vmware/vic/lib/install/validate.(*Validator).sessionValid(0xc8201b9260, 0x13d47f0, 0x16, 0x0)
Aug 08 21:49:59 vic-docker vic-init[138]: /home/loc/go/src/github.com/vmware/vic/lib/install/validate/validator.go:221 +0x63
Aug 08 21:49:59 vic-docker vic-init[138]: github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall(0xc8201b9260, 0x7f6485e1dde8, 0xc82000ef38)
Aug 08 21:49:59 vic-docker vic-init[138]: /home/loc/go/src/github.com/vmware/vic/lib/install/validate/config.go:48 +0x1ea
Aug 08 21:49:59 vic-docker vic-init[138]: github.com/vmware/vic/lib/vicadmin.NewValidator(0x7f6485e1dde8, 0xc82000ef38, 0x1e36320, 0x0, 0x0)
Aug 08 21:49:59 vic-docker vic-init[138]: /home/loc/go/src/github.com/vmware/vic/lib/vicadmin/validate.go:62 +0x63d
Aug 08 21:49:59 vic-docker vic-init[138]: main.(*server).index(0xc820237400, 0x7f6485e2a2d8, 0xc82045a5b0, 0xc8201b8d20)
Aug 08 21:49:59 vic-docker vic-init[138]: /home/loc/go/src/github.com/vmware/vic/cmd/vicadmin/server.go:259 +0x174
Aug 08 21:49:59 vic-docker vic-init[138]: main.(*server).(main.index)-fm(0x7f6485e2a2d8, 0xc82045a5b0, 0xc8201b8d20)
Aug 08 21:49:59 vic-docker vic-init[138]: /home/loc/go/src/github.com/vmware/vic/cmd/vicadmin/server.go:136 +0x3e
Aug 08 21:49:59 vic-docker vic-init[138]: net/http.HandlerFunc.ServeHTTP(0xc820245ff0, 0x7f6485e2a2d8, 0xc82045a5b0, 0xc8201b8d20)
Aug 08 21:49:59 vic-docker vic-init[138]: /usr/local/go/src/net/http/server.go:1618 +0x3a
Aug 08 21:49:59 vic-docker vic-init[138]: net/http.(*ServeMux).ServeHTTP(0xc820274690, 0x7f6485e2a2d8, 0xc82045a5b0, 0xc8201b8d20)
Aug 08 21:49:59 vic-docker vic-init[138]: /usr/local/go/src/net/http/server.go:1910 +0x17d
Aug 08 21:49:59 vic-docker vic-init[138]: net/http.serverHandler.ServeHTTP(0xc82026a300, 0x7f6485e2a2d8, 0xc82045a5b0, 0xc8201b8d20)
Aug 08 21:49:59 vic-docker vic-init[138]: /usr/local/go/src/net/http/server.go:2081 +0x19e
Aug 08 21:49:59 vic-docker vic-init[138]: net/http.(*conn).serve(0xc82026b980)
Aug 08 21:49:59 vic-docker vic-init[138]: /usr/local/go/src/net/http/server.go:1472 +0xf2e
Aug 08 21:49:59 vic-docker vic-init[138]: created by net/http.(*Server).Serve
Aug 08 21:49:59 vic-docker vic-init[138]: /usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by mdubya66** [comment]
could this be a dupe of #1836

**Comment by sflxn** [comment]
Yes, it does look similar.  Closing as duplicate.
