### ISSUE TITLE
Incorrect datetime format used

### ISSUE THREAD

**Issue by lazarin** [vmware/vic#1874]
**VIC Version:**

0.4 / build #3411

**Code**

Getting information about container (via docker cli or using remote api) returns the date fields (created, startedat, finishedat) in format different from the RFC3399Nano used by docker daemon : [docker code](https://github.com/docker/docker/blob/master/daemon/inspect.go) / [api](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/)

That breaks the clients parsing the date.

Reproduce:
```ts
docker inspect <container>
```
or
```ts
GET /containers/<container>/json
```

**Expected behavior:**
```
...
"Created": "2016-08-09T06:45:35.903440398Z"
...
```

**Actual behavior:**
```
...
"Created": "2016-08-09 06:45:35 +0000 UTC"
...
```

**Comment by mdubya66** [comment]
We should get this fixed for 1.0
