### ISSUE TITLE
Document how to obtain a VCH address

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1877]
We need to tell container application developers how to obtain the address of their VCH.

**Comment by stuclem** [comment]
@karthik-narayan, what should we document here? We cannot guarantee that the container app developers will have access to either `vic-machine` (to run `ls` then `inspect`),  or to vSphere. Do we just tell them to ask their vSphere admins for the address of their VCH? Thanks!

**Comment by stuclem** [comment]
Added a very brief topic to the App Dev doc: [Obtain a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/obtain_vch.md), more as an exercise in setting customer expectations than anything else. 

@karthik-narayan, @mdubya66, @mreferre, is this enough?

**Comment by stuclem** [comment]
Container developers can also use the `env` file that `vic-machine create` now generates. See also https://github.com/vmware/vic/issues/2676.

**Comment by mreferre** [comment]
In general I think that if an organization is only using VIC, they need to have some sort of internal process to flow the information from the provider (who runs the ` vic-machine create...` ) to the consumer (who runs the ` docker -H <VCH_IP> run... `). The process could be as basic as an email exchange or as advanced as a custom automation process with a portal/API end-point. 

Using vRA on top of VIC would be a way to provide a self-service flow where a consumer can request a VCH (through the portal or through APIs) and the portal (or the APIs) would communicate the VCH IP address at the end of the provisioning process.

**Comment by stuclem** [comment]
@mreferre how's this?

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/obtain_vch.md

**Comment by mreferre** [comment]
Yeah that would make sense. I'd like @karthik-narayan to bless the wording though.

**Comment by karthik-narayan** [comment]
LGTM. Only suggestion is that I'd start the first sentence with "Currently, ".

**Comment by stuclem** [comment]
Done, except I didn't put it at the beginning :)

"vSphere Integrated Containers Engine does not **currently** provide an automated means of obtaining virtual container hosts."
