### ISSUE TITLE
Add ability to change  user/password in ESXi environment

### ISSUE THREAD

**Issue by kjplatz** [vmware/vic#1879]
In certain environments, ESX administers are required to change infrastructure passwords periodically (90 days being the norm).  However, since VIC uses user/password to authenticate against ESX, this password change will effectively break VIC, since there is no means to update these credentials in the VIC appliance.

We should add some means to update these credentials without requiring us to deploy a new appliance.

**Comment by mdubya66** [comment]
Assigning to @gigawhitlocks

**Comment by hickeng** [comment]
This is exactly the same issue as any other form of vic-machine reconfigure so don't think of it as just 'update credentials'

**Comment by gigawhitlocks** [comment]
Right, this is actually pretty tricky of an issue, especially w/o some form of vic-machine update in place.

The way I imagine this working is adding the ability to do something like `vic-machine update --vch-user=root --vch-password=newpassword` and have `vic-machine` do the reconfiguration. 

It should also be noted that this is only an issue for ESX targets -- VC targets use the extension keypair so VC installs of VIC should not be affected.

**Comment by gigawhitlocks** [comment]
Yeah this is actually fairly complex, especially while we don't have a `vic-machine update` or `reconfigure` sub-command (or something similar) in place or in progress

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by gigawhitlocks** [comment]
I believe this is no longer relevant since we added shell access to `debug` in `vic-machine`

**Comment by hickeng** [comment]
@gigawhitlocks debug does not address this. This should be addressed by our "VCH - reconfigure" item.

**Comment by emlin** [comment]
Duplicate with #4495, using that one to track requirement
