### ISSUE TITLE
Cleanup Volume Create Integration Tests

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#1881]
Capacity unit support is now available and we need to adjust the integration tests to pass different size arguments to through. a

**Comment by fdawg4l** [comment]
@matthewavery "cleanup" or do you mean implement?

**Comment by matthewavery** [comment]
@fdawg4l just now taking a look at this. They are already implemented, however none of them take advantage of units. I intend to modify a few to use units since we should be able to detect if that ever breaks.
