### ISSUE TITLE
Network config should not be applied when a session process exits on the VCH

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1886]
Currently a "reload" is triggered when a process on the VCH crashes, which in turn reconfigures the network. This should not happen if it succeeded the first time around. Only the process launch should be attempted again.

**Comment by hickeng** [comment]
It should run through the network Apply call again - that was supposed to be idempotent... if it's already named appropriately it's not renamed. If it's already got an address then no new address is acquired.
