### ISSUE TITLE
Integ test failure in docker create w/ volume

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#1898]
Spotted two integration test failures in master build [3776](https://ci.vmware.run/vmware/vic/3776):

* [Create with volume](https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-4-Docker-Create.robot#L22) in `1-4-Docker-Create`

[VCH-3776-4397-container-logs.tar.gz](https://github.com/vmware/vic/files/410256/VCH-3776-4397-container-logs.tar.gz)

Snippet from `docker-personality.log`:

```
time="2016-08-09T22:57:39Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [49.081µs] ContainerCreate" 
time="2016-08-09T22:57:39Z" level=error msg="Handler for POST /v1.21/containers/create returned error: No command specified" 
```

* [Basic docker container stop](https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-7-Docker-Stop.robot#L30) in `1-7-Docker-Stop` 

[VCH-3776-5089-container-logs.tar.gz](https://github.com/vmware/vic/files/410257/VCH-3776-5089-container-logs.tar.gz)

Snippet from `docker-personality.log`:

```
time="2016-08-09T23:11:40Z" level=error msg="Handler for POST /v1.21/containers/6ae8a390934f7710c74d0c8aacb72b18265661934a8f76637dbea7dd9101736f/stop returned error: server error from portlayer : context deadline exceeded " 
```

**VIC Version:**

master / de936c6

**Comment by mdubya66** [comment]
assigning to @hickeng for triage.

**Comment by anchal-agrawal** [comment]
Both are transient failures, they didn't show up in [3781](https://ci.vmware.run/vmware/vic/3781).

**Comment by anchal-agrawal** [comment]
Closing this as the first test hasn't been repro'd since and #1822 is an umbrella ticket for CDE errors.

**Comment by anchal-agrawal** [comment]
Reopening as `Create with volume` in `1-4-Docker-Create` failed in a recent master build: https://ci.vmware.run/vmware/vic/4752.

[Test-Cases.Group1-Docker-Commands.1-4-Docker-Create-VCH-4752-3213-container-logs.zip](https://github.com/vmware/vic/files/470809/Test-Cases.Group1-Docker-Commands.1-4-Docker-Create-VCH-4752-3213-container-logs.zip)

**Comment by anchal-agrawal** [comment]
False alarm. Upon closer inspection of the logs, the test failed due to a CDE error. Since there's already a ticket for that, I'm closing this again.
