### ISSUE TITLE
Write test to measure memory overhead and run it as part of CI

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#19]
We should use the STREAM test [here](https://blogs.vmware.com/performance/2014/10/docker-containers-performance-vmware-vsphere.html).

This should assess the total consumed memory (preferably with breakdown of ESX/VM/guest) in:
- the template
- a minimal live container (snapshot X seconds after start)
- a minimal live container (idle over time)
- a minimal live container (defined workload over time)

This will allow us to track not only direct memory usage, but also page breaking behaviour.

**Comment by hickeng** [comment]
@mhagen-vmware please factor this into your plans - it may be something that Erin can take on, but unsure.
