### ISSUE TITLE
Research H5 Client for VIC UI migration

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#1904]
Fling: https://labs.vmware.com/flings/vsphere-html5-web-client#instructions

**Comment by jooskim** [comment]
Some observations and thoughts about H5 Client and SDK:
* Regarding the known limitation in the Flex client's capability to show an HTML-based portlet in the Summary view, we now have a workaround that will make it possible to display the HTML version for the H5 client and Flex version for the Flex client, in one plugin package.
* Knowing that H5C works with VC 6.0 and will be shipped with 6.5, there's a need to sync up with Karthik to clarify the following:
  * It now seems possible to pack the both versions of the plugin in one package. Will this affect how we want to handle the backwards compatibility with the Flex client?
  * Any other next milestones?

**Comment by mdubya66** [comment]
Don't forget that we have to support 5.5 as well. Not sure if it matters

**Comment by jooskim** [comment]
I've already made the Flex version work with 5.5. HTML version will only work on H5 Client though. The two versions (Flex and HTML) could be put into one package each of which will be loaded depending on which client you're on.

**Comment by jooskim** [comment]
This was done a while ago.. closing.
