### ISSUE TITLE
lib/guest unit tests require an ESX to run

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1910]
Unit tests should not reach to external resources like an ESX. Currently the tests under `lib/guest` all require an ESX URL to be set:

```
HMAHMOOD-MBPRO:guest hmahmood$ go test . -v
=== RUN   TestNewLinuxGuest
--- SKIP: TestNewLinuxGuest (0.00s)
	env.go:27: Skipping: No test ESX URL defined
PASS
ok  	github.com/vmware/vic/lib/guest	0.014s
```
The tests should be rewritten to mock out the external resources, or we should move them to integration tests, or we could use vcsim for them.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage
