### ISSUE TITLE
Investigate concurrent use of govmomi session for multiple property collectors

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1915]
We need to confirm the behaviour of the underlying transport when running concurrent operations across the same vmomi session. This is primarily of interest for property collectors which require a persistent stream response. This may be related to #1878 

There are two main combinations of interest:
- [ ] property collector established and streaming, followed by govmomi operations such as power off. Does the property collector persist
- [ ] two property collectors running using the same session - does this function as expected?

**Comment by cgtexmex** [comment]
We are sharing a limited number of sessions but we are not sharing property collectors.  The govmomi library protects the caller of a property.Wait operation by creating a new property collector by default.  That property collector is destroyed when the wait is complete.

The specific code is here:  https://github.com/vmware/govmomi/blob/master/property/collector.go#L57

To answer the questions in the issue subject:

1.  A property collector will persist until the criteria is met for the wait function.  At that point the property collector will be destroyed and available for garbage collection.  (govmomi as well as vsphere)

2.  Multiple property collectors running using the same session are completely acceptable and will function with no issues.
