### ISSUE TITLE
vic-machine: no default datastore for volume-store when only one datastore available

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1928]
Running vic-machine with `--volume-store=/volumes:default` (note the leading /) - expected this to work in the same way that `--compute-resource=/` works when there's a single cluster.

This is also a very misleading error message - what is the datastore hostname? What should the person invoking vic-machine do to set the hostname of the datastore?

```
INFO[2016-08-11T17:49:35Z] ### Installing VCH ####
INFO[2016-08-11T17:49:35Z] Generating certificate/key pair - private key in ./ghicken-test-key.pem
INFO[2016-08-11T17:49:35Z] Validating supplied configuration
INFO[2016-08-11T17:49:35Z] Suggesting valid values for --volume-store based on "*:default"
INFO[2016-08-11T17:49:35Z] Suggested values for --volume-store:
INFO[2016-08-11T17:49:35Z]   "datastore1:default"
INFO[2016-08-11T17:49:35Z] Firewall status: DISABLED on "/ha-datacenter/host/office1-sfo2-dhcp51.localdomain/office1-sfo2-dhcp51.localdomain"
INFO[2016-08-11T17:49:35Z] Firewall configuration OK on hosts:
INFO[2016-08-11T17:49:35Z]   "/ha-datacenter/host/office1-sfo2-dhcp51.localdomain/office1-sfo2-dhcp51.localdomain"
INFO[2016-08-11T17:49:35Z] License check OK
INFO[2016-08-11T17:49:35Z] DRS check SKIPPED - target is standalone host
ERRO[2016-08-11T17:49:35Z] --------------------
ERRO[2016-08-11T17:49:35Z] datastore hostname empty
ERRO[2016-08-11T17:49:35Z] Create cannot continue: configuration validation failed
ERRO[2016-08-11T17:49:35Z] --------------------
ERRO[2016-08-11T17:49:35Z] vic-machine-linux failed: validation of configuration failed
```

On fix:
- [ ] error message doesn't mention hostname. Perhaps "volume-store must specify datastore, e.g. datastore1/path"
- [ ] if there's only a single datastore associated with the host/cluster then that can be used as a default.

**Comment by hickeng** [comment]
Original estimate was just for correcting the error message, but this should also alter behaviour.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by matthewavery** [comment]
The default volume store should not be based on just hosts. It must also be based on available datastores. If there is one host and it has one datastore connected then we might look at making the root of that datastore the default volume store. There is also pending feedback from PM surrounding what we might want our expected behavior of the default volume store creation to be. The error message clean up portion is already part of PR #3713

**Comment by zjs** [comment]
Closing as this would simplify life only for trivial deployments (i.e., where you have one datastore).
