### ISSUE TITLE
vicadmin reports incorrect storage availability

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1939]
Build 3910 (8/11/16)

installed on VC but pointed to specific datastore on host for image-store.

Install command:
./vic-machine-darwin create --target 10.161.25.72 --image-store ds1 --name vic-test-mike3 --user Administrator@vsphere.local --password 'Admin!23'  --compute-resource /ha-datacenter/host/10.161.236.25/Resources --bridge-network bridge --external-network vm-network

Datastore ds1 has around 23.06GB free. 

VIC admin page reports:
Virtual Container Host Info
Docker Endpoint: 10.161.230.180:2376
Storage: 420GB Remaining

**Comment by kjplatz** [comment]
The "420G remaining" was a placeholder carryover from the mockup.  I have submitted a PR to correctly populate this.
