### ISSUE TITLE
Image management deviates from standard docker engine.

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#1942]
I have experimenting a bit around docker pulls and I noticed a weird behavior with VIC in the way it manages references to images by their full path (i.e. including the registry piece). 

More details and an exemple is provided in the PPTX attached but in a nutshell the key point is that a standard docker host is able to pull by image or by registry/image and keep said name when querying the docker host (with "docker images"). 

Subsequently, when running a "docker run" against that image using a different pattern than what's being used in the pull, the docker host can immediately auto-tag that image with the new pattern and instantiate it fine. 

VIC has a different behavior:

1) if you pull an image with the pattern "registry/image" a "docker images" shows the item with only the image name (stripping out the registry part).
2) if try to "docker run" that image using the pattern "registry/image" VIC seems to recognize the image is already there and that it only needs to "auto tag" it. It seems to be auto-tagging it fine BUT the docker run fails with an "image not found". 

More examples in the PPTX attached. 
[docker image name when pulled with VIC.pptx](https://github.com/vmware/vic/files/414897/docker.image.name.when.pulled.with.VIC.pptx)

**Comment by mreferre** [comment]
BTW this <may> be due to the fact the build I am using doesn't support yet "tagging".

**Comment by corrieb** [comment]
You may be right about tagging. Imagec seems to be fine here, but docker run doesn't recognize the image we're talking about

root@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic-n# docker pull registry.hub.docker.com/library/nginx
Using default tag: latest
Pulling from library/nginx
a3ed95caeb02: Pull complete 
51f5c6a04d83: Pull complete 
51d229e136d0: Pull complete 
bcd41daec8cc: Pull complete 
Digest: sha256:9dff4680bc81db31be8f4d6a3323080948282048c432b36c2593d8d8014255bf
Status: Downloaded newer image for library/nginx:latest
root@ubuntu-1604-vmware:~/vic/src/github.com/vmware/vic-n# docker run -d registry.hub.docker.com/library/nginx
Unable to find image 'registry.hub.docker.com/library/nginx:latest' locally
Pulling from library/nginx
51f5c6a04d83: Already exists 
a3ed95caeb02: Already exists 
51d229e136d0: Already exists 
bcd41daec8cc: Already exists 
Digest: sha256:9dff4680bc81db31be8f4d6a3323080948282048c432b36c2593d8d8014255bf
Status: Image is up to date for library/nginx:latest
docker: Error: No such image: registry.hub.docker.com/library/nginx.
See 'docker run --help'.

**Comment by hickeng** [comment]
@mreferre This should have been addressed along with #1638. I'm closing as a dup - can you confirm.
