### ISSUE TITLE
Document that vic-machine defaults to datastore if only one exists

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1969]
Per https://github.com/vmware/vic/issues/1206. Implemented in PR https://github.com/vmware/vic/pull/1957.

**Comment by stuclem** [comment]
Incidentally, once https://github.com/vmware/vic/pull/1957 is merged, then the --image-store option will no longer be mandatory, so I'll need to move it out of the section on mandatory options.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/pull/1957 is now merged.

**Comment by stuclem** [comment]
Added the following in the section on `image-store` in the topic on [`vic-machine create` options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#image-store):

"The `image-store` option is **mandatory** if there is more than one datastore in your vSphere environment, If there is only one datastore in your vSphere environment, the `image-store` option is not required." 

Even though the `image-store` option is no longer strictly mandatory because of this change, I have left it in the section on mandatory options, with the comment above, as I think that in most cases it will be required.

@emlin, do you agree?

**Comment by emlin** [comment]
agree 👍
