### ISSUE TITLE
Error response from daemon: [POST /storage/volumes/][500] createVolumeInternalServerError &{Code:0xc82000f540 Message:volumestore (http://VCH-0-8191/storage/volumes/default) not found}

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1974]
Saw this issue on the latest attempt to test the build on VC in nimbus.  Here is the log bundle:
[VCH-0-8191-container-logs.zip](https://github.com/vmware/vic/files/418319/VCH-0-8191-container-logs.zip)

**Comment by mhagen-vmware** [comment]
This was seemingly caused by an inaccurate compute-resource being specified in the vic-machine create command.  We need to handle that better. Either 1. fail the install if the compute resource doesn't work out, 2. does volume-store create really need a compute resource in order to be successful?

**Comment by matthewavery** [comment]
cc @gigawhitlocks

**Comment by gigawhitlocks** [comment]
Assigning myself to have a look at this once I finish #1982

**Comment by mhagen-vmware** [comment]
Was able to reproduce this locally while trying to run concurrently 4 integration test runs:
[VCH-0-4678-container-logs.zip](https://github.com/vmware/vic/files/423718/VCH-0-4678-container-logs.zip)

Making this back into a p0 as it will block the ability to run concurrent builds on an ESX system.

**Comment by hickeng** [comment]
This appears to be failing because the 'default' volume store returns not found. Initial investigation suggests this is because the VolumeLocation entry for default is:
Host: "datastore1"
Path: "[datastore1] test"

It's possible that this is intentional, but that's not the URL structure we were using the last time I looked.
Will attempt to validate the URL construction logic

@mhagen-vmware do you have a record of the vic-machine command line you used?

**Comment by mhagen-vmware** [comment]
Possibly seen here as well:
[integration_logs_4631_39f4838045c15e930c2935abb98695e1acbb2181_1473201704.zip](https://github.com/vmware/vic/files/459529/integration_logs_4631_39f4838045c15e930c2935abb98695e1acbb2181_1473201704.zip)

**Comment by matthewavery** [comment]
@hickeng Looks like the `vic-machine create` command can be found in the /tests/resources/util.robot file. The volume store looks like `--volume-store=%{TEST_DATASTORE}/test:${vol}`

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
