### ISSUE TITLE
Research spike:  Investigate the correct timeouts for all portlayer calls

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1989]
Currently, all calls outside of attach uses the default swagger timeout of 30s.  We should re-examine what the correct timeouts for each individual calls to the portlayer.  For instance, docker start does not appear to have a set timeout from a quick skim of Docker's code.  For docker start, we might want to have an infinite timeout?  #1733 is an existing issue to add an infinite timeout for attach.  We could use the same for docker start.  For other operations, we should come up with an agreed upon timeout value and change the current swagger calls to use these timeouts.

Note, when the swagger client times out, that does not indicate the portlayer returned an error.  It indicates the swagger client timed out.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage
