### ISSUE TITLE
vic-admin free space remaining incorrect

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2010]
vic-admin status page says 420GB remaining yet datastore total capacity is 30.5GB and free is 20.12GB.

Reality:
![image](https://cloud.githubusercontent.com/assets/3923729/17713991/8c510e02-63b2-11e6-87cc-2819ea103f37.png)

vic-admin:
![image](https://cloud.githubusercontent.com/assets/3923729/17714009/a13a9c84-63b2-11e6-87ca-48d421d90294.png)

**Comment by kjplatz** [comment]
@hickeng Can you verify this against the current build?  PR #1972 should have addressed this yesterday.

**Comment by sgairo** [comment]
^^ Correct, this was a placeholder value while we implemented it, which should have been merged yesterday.

**Comment by kjplatz** [comment]
Corrected in #1972
