### ISSUE TITLE
Failed to fetch OAuth token: Get https://auth.docker.io/token?scope=repository%!A(MISSING)library%!F(MISSING)busybox%!A(MISSING)pull&service=registry.docker.io: dial tcp:

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2015]
Saw this failure on a recent CI build:

[integration_logs_4080_5685722d6a53cec1a6f3a82c7d2fc5664b06a35b_1471382669.zip](https://github.com/vmware/vic/files/421318/integration_logs_4080_5685722d6a53cec1a6f3a82c7d2fc5664b06a35b_1471382669.zip)

**Comment by mhagen-vmware** [comment]
From imagec.log:
```
time="2016-08-16T21:17:49Z" level=debug msg="URL: https://registry-1.docker.io/v2/library/busybox/manifests/latest" 
time="2016-08-16T21:17:49Z" level=debug msg="URL: https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io" 
time="2016-08-16T21:17:59Z" level=fatal msg="Failed to fetch OAuth token: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 192.168.31.1:53: read udp 192.168.31.147:49586->192.168.31.1:53: i/o timeout" 
```

**Comment by mhagen-vmware** [comment]
From docker-personaliy.log:
```
time="2016-08-16T21:17:48Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).VCHInfo] [594.377µs] VCHInfo" 
time="2016-08-16T21:17:48Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).SystemInfo] [18.057181ms] SystemInfo" 
time="2016-08-16T21:17:48Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).PullImage] PullImage" 
time="2016-08-16T21:17:59Z" level=error msg="imagec exit code: exit status 1" 
time="2016-08-16T21:17:59Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).PullImage] [10.741797998s] PullImage"
```

**Comment by caglar10ur** [comment]
ok so I  think this clearly shows that dns lookup failed while trying to resolve auth.docker.io not sure what to do. Suggestions?

**Comment by mhagen-vmware** [comment]
Seen in this build as well:
[integration_logs_4111_62f785f9155a6b9de0d1696df2096a6917acf084_1471450142.zip](https://github.com/vmware/vic/files/423176/integration_logs_4111_62f785f9155a6b9de0d1696df2096a6917acf084_1471450142.zip)

**Comment by mhagen-vmware** [comment]
Seen in this build as well:
[integration_logs_4108_874f5840ed1e42f06dca17d602cdc3c68a7ec0e1_1471448360.zip](https://github.com/vmware/vic/files/423183/integration_logs_4108_874f5840ed1e42f06dca17d602cdc3c68a7ec0e1_1471448360.zip)

**Comment by mhagen-vmware** [comment]
[integration_logs_4106_ad928bba496805bc2a9a7fce1364b3b5dfcf8e24_1471444627.zip](https://github.com/vmware/vic/files/423207/integration_logs_4106_ad928bba496805bc2a9a7fce1364b3b5dfcf8e24_1471444627.zip)

**Comment by mhagen-vmware** [comment]
Seen in this build also:
[integration_logs_4097_816441ecbb71d6974ee234c320e7dc3f6c82f452_1471389864.zip](https://github.com/vmware/vic/files/423214/integration_logs_4097_816441ecbb71d6974ee234c320e7dc3f6c82f452_1471389864.zip)
