### ISSUE TITLE
secrets.yml needs to be versioned

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2033]
Or at least contain a comment on the top of the file like SOA where we can increase every time we edit it. Otherwise it's impossible to know who uses which version.

As an engineer on the project I would like to see secrets.yml be versioned in order to avoid different developers overwriting each others changes.

**Comment by mhagen-vmware** [comment]
I have spent probably a bit too much time investigating this and talking with Fabio, unfortunately this is going to have to be iceboxed until we move to drone 0.5, as there is not really any good way to do this until then.

**Comment by mhagen-vmware** [comment]
Once we move to drone 0.5 they have moved the secrets to a db from the yml file and we will be able to much better maintain consistent secrets and prevent reversion.

**Comment by caglar10ur** [comment]
in the meantime can't we add a comment in the top of the file 

````
# Version: 1
...
``` 

and increment it (manually) whenever someone changes something in it?

**Comment by mhagen-vmware** [comment]
I did consider that, but what does it really buy us? Without a programmatic solution, it is just another variable that may or may not get updated properly and won't really solve the problem will it?

**Comment by caglar10ur** [comment]
At least we can refer it with something, no? In the past I used old secrets.yml file to update secret file without realizing it. So we could ask are you using version X questions. But of course manual updating is error prone so not sure...

**Comment by mhagen-vmware** [comment]
Yea, not really any good solution here at all at this point that I can see, as I am loathe to add yet another update item to the secrets file that already has so many problems. I am just fairly certain that if we add a comment like that, it is just going to not get updated or people will just still revert to old versions because it is just so easy to do and completely easy to ignore still.

**Comment by mhagen-vmware** [comment]
This will be, at least until we upgrade to drone 0.5, covered in #4186
