### ISSUE TITLE
${output} = Error response from daemon: server error from portlayer : Operation failed: The attempted operation cannot be performed in the current state (Powered off). - (&{{} %!s(*types.InvalidPowerState=&{{{{<n...	

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2038]
Saw this in a recent CI build:
[integration_logs_4112_c61b35292f46740fc318eab050a8fde3a426853b_1471463307.zip](https://github.com/vmware/vic/files/423662/integration_logs_4112_c61b35292f46740fc318eab050a8fde3a426853b_1471463307.zip)

**Comment by hmahmood** [comment]
The code to handle this error is already in `Container.stop`, but is not run because `tasks.WaitForResult` does not preserve the error from govmomi. 

@matthewavery is already working on fixing `WaitForResult` as part of #2013, so assigning it to him.

**Comment by matthewavery** [comment]
Solved in pr #2141 due to the previous implementation of `WaitForResult` the fault's were getting squashed and never made it back to the callers. This has been fixed, and the fault checks on errors are now valid is this area.
