### ISSUE TITLE
docker: Error response from daemon: error mapping ports: port <xyz> is not available.

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#2042]
Currently using rel 0.5. 

I have a script that instantiate 5 containers and exposes them on some ports (-p x:y) 

I have noticed that sometimes the script fails like this:

         967a2a33a1ab1657a58975a485bfac0c72d5413d6524c4183ed5e77e4d077e33
         docker: Error response from daemon: error mapping ports: port 8001 is not available.
         8fe14151060ddd24091b1b69a336d23c4491dd1e9057f96e5f5a6c1196f74d5d
         docker: Error response from daemon: error mapping ports: port 8002 is not available.
         ed2f89a7e0fdd85b6718095237cfbc0510b44b592dc1b91469e726f31bebfa33
         docker: Error response from daemon: error mapping ports: port 8003 is not available.
         ebcadc90a3184f486173683f045cdd01f56c6f0eb296c014e4bc9d502c9faf30   
         docker: Error response from daemon: error mapping ports: port 9998 is not available.

As far as I can say the problem above seems to be happening when the removal of these containers doesn't succeed (the failure on removal issue is documented here: https://github.com/vmware/vic/issues/1822#issuecomment-240412793). 

Note I see the port mapping issue when the system is "clean" (or supposedly so) that is... after I was able to REMOVE completely all stuck containers (in a way that ```ps -a``` wouldn't show anything). 

It's like the removal didn't remove everything (nee the port mapping). Interestingly even some of the ports of containers that seemed to have been removing fine (using ```docker --tls rm -f $(docker --tls ps -a -q)``` as described in the other issue) have mapping problems. 

The only way to recover is to shutdown and restart the VCH (when in clean state or supposedly so).

**Comment by andrewtchin** [comment]
I believe this may be resolved when this PR is merged https://github.com/vmware/vic/pull/2795

**Comment by andrewtchin** [comment]
@mreferre the fix for this has been merged so now containers that are not powered on no longer hold onto their port bindings. Please reopen this issue if you see this again.
