### ISSUE TITLE
ensureComponentsInitialize is not using ctx

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2059]
it should either be longer than 10sec or needs to honor timeout option

**Comment by anchal-agrawal** [comment]
#1992

**Comment by hickeng** [comment]
@anchal-agrawal @caglar10ur 's point is not addressed in #1992 - currently there is a hardcoded delay rather than making use of the remaining duration from the vic-machine `--timeout` option.

**Comment by anchal-agrawal** [comment]
@hickeng Yep, my comment was just a placeholder to tag the related PR. I'm working on this right now.
