### ISSUE TITLE
Remove call to CreateImageStore from docker image cache and imagec

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#2069]
From #2053

`CreateImageStore` should be called from the docker personality on startup and not on every interaction with the storage layer involving images.  Right now, `imagec` and the image cache call this function (mostly due to legacy). 

I don't understand why the image cache is calling this at all.  If you guys can clarify, I can remove this first.

**Comment by hickeng** [comment]
This is currently blocking #2054 / #2061

**Comment by jzt** [comment]
I should be able to refactor the image store creation step out of the cache `Update`.

**Comment by fdawg4l** [comment]
Rawk.  Thanks @jzt!

**Comment by fdawg4l** [comment]
Looks like we're still racing on the image cache creation logic.  Can you guys remove the create call from the image cache asap?  #2092 seems to manifest this.

**Comment by jzt** [comment]
PR should be up momentarily, just waiting on these tests to finish!
