### ISSUE TITLE
Remove image from image cache when rmi is called

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#2070]
`docker rmi` will remove images from the image store.  However, something needs to purge the entry from the image cache (in the docker daemon) if the image store call is successful.

**Comment by fdawg4l** [comment]
This is related to #2064 (image cache isn't persisting anything).  Since images (and their metadata) are immutable, this "up-call" to freshen the image cache is needed.

**Comment by mdubya66** [comment]
Merge request opened. Moving to ToDo and assigning to vburenin
