### ISSUE TITLE
Document which ports are used by internal VIC services

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2072]
Per https://github.com/vmware/vic/issues/2006, which is implemented in PR https://github.com/vmware/vic/pull/2056.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/pull/2056 is merged.

**Comment by stuclem** [comment]
@hmahmood, are there any other ports that need to be open, or just 2377? Thanks!

**Comment by hmahmood** [comment]
That's the only requirement right now for VIC.

**Comment by stuclem** [comment]
Thanks @hmahmood. In that case, this one is done.
