### ISSUE TITLE
Documentation: update vic-machine create examples

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2074]
A lot of new stuff has been added to `vic-machine create` since  I last updated the examples. They definitely need refreshing and expansion with new examples.

**Comment by stuclem** [comment]
Updated the [Examples of Deploying a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md) to reflect the latest state of `vic-machine create`.

-  @emlin please can you take a look at all of them?
- @hmahmood please can you look at the network examples?
  - [Deploy a Virtual Container Host to a Cluster and Specify External, Management, Client, and Container Networks](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#networks)
  - [Deploy a Virtual Container Host and Configure a Non-DHCP Container Network](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#ip-range)
- @hickeng and @mhagen-vmware, are there other use-cases that need an example that I have omitted?

**Comment by stuclem** [comment]
If @mreferre could take a look too, that would be fab.

**Comment by emlin** [comment]
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#deploy-a-virtual-container-host-directly-on-an-esxi-host-with-no-resource-pools-and-a-single-datastore

vic-machine create one standard vSwitch, instead of distributed vSwitch.
user can only create dvSwitch through VC.

**Comment by emlin** [comment]
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#deploy-a-virtual-container-host-to-a-cluster-and-specify-external-management-client-and-container-networks

we probably can mention if container network alias is not specified, vsphere network name will be used

**Comment by emlin** [comment]
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#deploy-a-virtual-container-host-and-specify-an-image-store-folder-and-a-different-datastore-for-container-vm-files

container-store is still not supported

**Comment by emlin** [comment]
Overall looks good, with few minor comments/questions. 👍

**Comment by stuclem** [comment]
Distributed switch vs. tandard switch: fixed

Container network descriptive name: Added " If you do not specify a descriptive name, Docker uses the vSphere network name." Also added this in the topic on `vic-machine create` options.

Container store: I have been including it in the options and examples topics, but with the note "**NOTE**: In the current builds of vSphere Integrated Containers Engine, the `container-store` option is not enabled. Container VM files are stored in the datastore that you designate as the image store." When container store is supported, I will remove the notes throughout the doc.

Thanks for the review, @emlin !

**Comment by emlin** [comment]
👍
