### ISSUE TITLE
Persist appliance log bundle on shutdown

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2079]
Currently when the appliance shuts down, all of the logs are dropped due to stateless filesystem. Generally this isn't an issue as they can be pulled via vicadmin however it leaves a hole between VM poweron and vicadmin initialization during which we're unable to tell what has occurred.

The log bundle is the contents of /var/log/vic/ at a minimum - ideally it would include the rest of the local contents from the full vic-admin log bundle.

The most simplistic approach is exactly the one used for the containers - leverage a file backed serial port and write the log bundle to that. In this scenario we would configure the port with Replace instead of Append.

On completion:
- [ ] appliance log bundle is persisted on shutdown

**Comment by matthewavery** [comment]
some info included in the above reference of issue #1183

**Comment by caglar10ur** [comment]
@vburenin do you wanna take this as well now that you are working on appliance logs?

**Comment by chengwang86** [comment]
Update:

0) We choose to only persist the init.log

1) init.log has duplications with portlayer.log and docker-personality.log; so remove the duplication from the init.log 

2) add a serial port for init.log (to vic-machine)

3) change vic-init code to redirect its stdout and stderr to that serial port
