### ISSUE TITLE
Document how vic-machine validates the DPG  for container-network-xx  options 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2086]
Per https://github.com/vmware/vic/issues/1602, which is implemented in https://github.com/vmware/vic/pull/2075 (not merged yet).

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/2075 is now merged.

**Comment by stuclem** [comment]
Updated the entries for the container-network-xxx options to mention that the DPG is validated:

- [gateway](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#container-network-gateway)
- [DNS] (https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#container-network-dns)
- [IP range](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#container-network-ip-range)

@emlin, is this OK? Thanks!

**Comment by emlin** [comment]
looks good.

**Comment by stuclem** [comment]
Thanks @emlin!
