### ISSUE TITLE
Language review of all customer visible strings

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2087]
I saw a couple of error messages in a PR today that needed a bit of cleaning up, language-wise. This is undoubtedly true for other customer-visible texts. Since we don't have a lot of UI, this exercise is probably limited to error messages, vic-machine output and log messages. 

@mdubya66, how should we proceed? If messages are included in resource files rather than hardcoded, that will make life a lot easier for all of us.

I put this under kind/enhancement, but I'm not sure whether that's the correct label.

**Comment by mdubya66** [comment]
@stuclem we should review these as best we can. Not everything is in a resource file, unfortunately. @emlin @hickeng can we help out here by figuring out a way to extract customer visible texts?

**Comment by anchal-agrawal** [comment]
Related: #2093

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mdubya66** [comment]
@stuclem let's take a stab at this for 1.1. making medium

**Comment by zjs** [comment]
This would be great to do, but if we haven't gotten to it yet it seems unlikely to be a priority going forward.
