### ISSUE TITLE
VIC returns container command doubled

### ISSUE THREAD

**Issue by lazarin** [vmware/vic#2091]
**VIC Version:**

0.4.0 / build #4031

**Code**
1. Create alpine container
2. Inspect the container CLI / Rest API
3. Cmd element has the content doubled

```ts
$ docker run -i -t -d --name cont1 alpine sh -c 'echo string'
$ docker inspect cont1
```

**Expected behavior (as returned from regular docker host) :**
```
...
"Config": {
    ...
    "Cmd": [
        "sh",
        "-c",
        "echo string"
    ],
    ...
},
...
```
**Actual behavior:**
```
...
"Config": {
    ...
    "Cmd": [
        "sh",
        "-c",
        "echo string",
        "sh",
        "-c",
        "echo string"
    ],
    ...
},
...
```

**Comment by corrieb** [comment]
It's not unreasonable to ask someone who's raising a bug to try against the latest released version - 0.5.0. 0.4.0 is now pretty old.
