### ISSUE TITLE
vIC error when using a private insecure registry 

### ISSUE THREAD

**Issue by vmtocloud** [vmware/vic#2102]
**VIC Version:**

0.5.0 / master 

**Code**
// A self-contained demonstration of the problem follows...

When trying to pull an image from a private registry I get an error. When testing on a host with Docker running locally the same registry runs fine. 

Here is the command that I run:
docker -H 192.168.100.170:2376 --tls pull reg.corp.local/library/myblog:latest

**Expected behavior:**
Image pulled and see results of layers being pulled.

**Actual behavior:**
Failed to fetch OAuth token: parsing time "1800" as ""2006-01-02T15:04:05Z07:00"": cannot parse "1800" as """

**Comment by anchal-agrawal** [comment]
Closing as this was resolved in #2154.
