### ISSUE TITLE
Support custom CA roots for registry validation

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2103]
We need to be able to upload a self generated ca certificate to the appliance's in order to handle private registries using TLS with self-signed certificates.  This is for docker login and docker pull.

The docker personality server must also be able to use this certificate.

**Comment by sflxn** [comment]
I'm unsure, but it appears we may not need to put the CA certs in the appliance keychain.  Documentation seems to indicate only adding the CA certs into /etc/docker/certs.d/<FQDN>/ca.crt should be enough.  I'll have to verify this.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mdubya66** [comment]
Needed by Harbor and Admiral

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by sflxn** [comment]
When I install manually, I appended the self generated CA cert to the appliance's CA bundle and restarted the docker personality server.  That was the workaround.  If we proceed to implement this issue, we cannot just append the CA bundle as we will need the personality server to restart.  Golang loads the system certs when the personality server starts.

I'm going to approach this by having vic-machine add the cert into our guest info and have the personality programmatically load the cert.

**Comment by sflxn** [comment]
For GA, Harbor 0.5.0 will not be done in time for us to put it into our CI due to https://github.com/vmware/harbor/issues/1051.  I had a discussion with @mlh78750 and @mhagen-vmware, and we decided to proceed and get this issue in, manually test it, and add Harbor 0.5+ into our CI post-GA.

**Comment by mdubya66** [comment]
do we need to be concerned about an upgrade path once the cert is inserted into guest info?

**Comment by mlh78750** [comment]
@mdubya66 yes, but I assume that @sflxn will implement so that when the upgraded personality server starts it will see the cert and append. And for that matter if the server restarts for any reason (including upgrade)

**Comment by sflxn** [comment]
I'm looking to piggyback on existing cert work we already have in vic-machine.  Looking to verify my assumptions.  If vic-machine currently already handles certs correctly on upgrade, then there might not be anything I need to do.  We already have a mechanism to import CA certs, our help wording may need to change a little, but I can piggy back on that existing mechanism or add a duplicate path that forces user to acknowledge a CA cert will be used exclusively for registries.
