### ISSUE TITLE
vic-machine: delete should use tasks.Retry

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2107]
vic-machine delete should use the tasks.Retry call instead of tasks.Wait so that we can still delete VMs in the case where there are operations still finalizing.

https://ci.vmware.run/vmware/vic/4295 is the build that illustrated the problem

**Comment by emlin** [comment]
George, @andrewtchin reproduced #1787 in nimbus env, but in the vic-machine log, there is no TaskInProgress error found. So I'm wondering where to use the retry.

The delete logic is like following:
Power Off Task->Task Finished->Destroy Task->Task Finished no error->Delete datastore files
                                                                             ->With error->fail vic-machine delete

I assume vSphere return task finish earlier than it the power status change. If we think we should not check power status through property collector as well. As you said, we can try to UnregisterVM after vm destroy failed.

Please let me know if I misunderstand anything.

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by emlin** [comment]
Retry and WaitForResult is merged to one, so close it for not applicable now.
