### ISSUE TITLE
Need a way to share portlayer endpoint information with docker server and other clients

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#212]
Currently the portlayer server binds to a random port on launch, and the imagec binary uses the -host parameter to discover that port. We need a consistent and reliable way to communicate information about the portlayer's endpoint to its clients.

Some proposals:
* fix the portlayer port
* use unix domain sockets, and fix the path
* pass the endpoint information as a parameter to clients

**Comment by dougm** [comment]
Taken care of by the installer
