### ISSUE TITLE
Document that DPG for bridge network cannot be shared by multiple VCHs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2138]
Per comment from Hasan via Slack:

"sharing a dpg (or switch) between VCH’s may be a problem since it may lead to two containers getting the same IP address

[5:22]  
bridge networks allocate ip’s from the same pool (172.16.0.0/12) by default, so potentially two VCH’s on the same port group may allocate the same IP for two containers

[5:23]  
since they are on the same physical network, that could cause havoc"

**Comment by stuclem** [comment]
Updated the section on [bridge-network](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#bridge-network)

**Comment by stuclem** [comment]
@hmahmood can you please take a look at  [bridge-network](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#bridge-network), specifically the note about not sharing the DPG?

**Comment by hmahmood** [comment]
@stuclem I believe just having a separate distributed port group may not be enough. The DPG would also need to have a unique VLAN id. I am not sure if when creating a new DPG, a VLAN id is specified, but I believe this is necessary so that the bridge network is isolated.

**Comment by stuclem** [comment]
Thanks @hmahmood. I updated the following topics to include the VLAN ID:

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md#network-requirements

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#bridge-network

Does this cover it?

Thanks!

**Comment by hmahmood** [comment]
@stuclem that should do it. Thanks.

**Comment by stuclem** [comment]
Thanks @hmahmood
