### ISSUE TITLE
Get a base private registry running in VIC

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2140]
We need a private registry running on VIC for use with our CI system.  We need one that allows pushing of images on it.  An idea is to use a DIND container with a registry.  If that doesn't work, find out why.

**Comment by sflxn** [comment]
I quickly tried the following:

```
docker --tls -H 192.168.218.136:2376 run -d -p 5000:5000 --name registry registry:2.0
docker --tls -H 192.168.218.136:2376 run -d -p 2400:2400 docker:dind --insecure-registry=registry:5000 -H tcp://0.0.0.0:2400
loc@linuxdev:~/docker-registry$ docker --tls -H 192.168.218.136:2400 info
An error occurred trying to connect: Get https://192.168.218.136:2400/v1.23/info: http: server gave HTTP response to HTTPS client
```

It's using the DIND container to allow pushing images to the registry.  Haven't investigated why it failed.  Should investigate further.

**Comment by mdubya66** [comment]
why wouldn't we use harbor?

**Comment by dougm** [comment]
Related: #250
