### ISSUE TITLE
Document that VCH must get IP address from DHCP

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2151]
Per this [SocialCast thread](https://vmware-com.socialcast.com/messages/31530057), we must confirm that you can't currently set a static IP on a VCH.

**Comment by stuclem** [comment]
Added that VCH IP must come from DHCP in https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md#network-requirements

**Comment by hmahmood** [comment]
@stuclem 👍

**Comment by stuclem** [comment]
Thanks @hmahmood !

**Comment by emlin** [comment]
👍
