### ISSUE TITLE
Putting username but not password into vic-machine create --target doesn't allow you to enter password

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2152]
If you insert a username into `vic-machine create --target` but do not add the password, `vic-machine create` prompts you for the password but does not give you an opportunity to enter it. The deployment of the VCH fails with an incorrect username/password error.

For example:

```
$ vic-machine-windows create --target 'Administrator@vsphere.local'@vc_ip_address --name vch2 --bridge-network 'vic bridge' --image-store datastore1
INFO[2016-08-26T14:35:08+03:00] Please enter ESX or vCenter password:
INFO[2016-08-26T14:35:08+03:00] ### Installing VCH ####
INFO[2016-08-26T14:35:08+03:00] Generating certificate/key pair - private key in ./vch2-key.pem
ERRO[2016-08-26T14:35:11+03:00] Create cannot continue: failed to create validator
ERRO[2016-08-26T14:35:11+03:00] --------------------
ERRO[2016-08-26T14:35:11+03:00] vic-machine-windows.exe failed: Failed to log in to https://10.153.199.35/sdk: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

There is no pause between the lines `Please enter ESX or vCenter password:` and `### Installing VCH ####`. 

Same behaviour for deployment to both VC and ESXi hosts.

Note that this was on Windows. I haven't tested Mac OS or Linux.

**Comment by emlin** [comment]
also reproduced on Linux. should be platform irrelevant.

**Comment by mdubya66** [comment]
I was prompted on MacOS in v0.5.0 and B4384

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by anchal-agrawal** [comment]
Works fine on Linux for me and on Windows for @chengwang86 with build 7569 (master).

@stuclem please re-open this issue if you can repro it.
