### ISSUE TITLE
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc8204163c8 Message:Invalid configuration for device '0'.}

### ISSUE THREAD

**Issue by terpsho** [vmware/vic#2156]
[vic.zip](https://github.com/vmware/vic/files/440029/vic.zip)

**VIC Version:**

0.5

**Code**
Error code: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc8204163c8 Message:Invalid configuration for device '0'.}

```ts
// A self-contained demonstration of the problem follows...
This issue occurred after I docker run -it hello-world. After the execution, I received "No such container" error. After that, this WriteImage default error is generated. I could not find anyway to make it disappear but install a new VCH. 
```

**Expected behavior:**
Should pull image successfully
**Actual behavior:**
Fails to pull image

**Comment by terpsho** [comment]
[vic.zip](https://github.com/vmware/vic/files/440027/vic.zip)

**Comment by fdawg4l** [comment]
Hi @terpsho!  Many changes have been made to address issues like this.  Have you seen this lately?  Also, and I know this was a long time ago, if you have logs, it'll help us identify which issue/fix we can match this to.

**Comment by hickeng** [comment]
@fdawg4l there's a minimal log set attached to the issue (vic.zip)

**Comment by fdawg4l** [comment]
Thanks @hickeng!

```
time="2016-08-26T19:13:01Z" level=info msg="Create/attach vmdk [NFSDatastore] shawnVIC01/images/VIC/4221e815-6836-81b8-da7e-9a9e788aac92/images/3690474eb5b4b26fdfbd89c6e159e8cc376ca76ef48032a30fa6aafd56337880/36904    74eb5b4b26fdfbd89c6e159e8cc376ca76ef48032a30fa6aafd56337880.vmdk from parent [NFSDatastore] shawnVIC01/images/VIC/4221e815-6836-81b8-da7e-9a9e788aac92/images/scratch/scratch.vmdk" 
time="2016-08-26T19:13:01Z" level=error msg="vmdk storage driver failed to attach disk: Invalid configuration for device '0'." 
```

**Comment by hickeng** [comment]
I have just seen `Invalid configuration on device '1'`, which resulted from `opID=e9031439 user=root] Parent file doesn't exist, or the user has no permission to access.`

This was during https://ci.vmware.run/vmware/vic/6045 which was something of a fiasco, see #2817 and related. Test was `Test-Cases.Group6-VIC-Machine.6-5-Create-Validation-VCH-6045-7171` if you want to compare.

This may not be related to the original problem as I suspect @terpsho was not running `vic-machine` operations concurrently with his pull.

**Comment by fdawg4l** [comment]
@hickeng there isnt anything to go on here.  In favor of closing.

**Comment by terpsho** [comment]
I asked on Slack about this issue before and I was told that VIC 0.5 does not support one of the docker command yet (I forget which). They wanted me to open a case here to make sure it will be resolved. That's all I remember.

**Comment by hickeng** [comment]
@fdawg4l #2856 seems to be able to recreate the initial `Invalid configuration` problem reliably.

**Comment by fdawg4l** [comment]
There's insufficient information to identify this problem.  We do have open issues for the related issues with more detail.  Also if it happens again, we've added more to the log bundle to help us identify if this is a new issue or an existing one to DUP this to.  

So closing this for now.  Please reopen if you can repro on a more recent build which will give us more info in the bundle.
