### ISSUE TITLE
vic-admin: strip vmware.log

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2164]
vmware.log for the appliance contains the extraconfig entries for the VM - this needs to be sanitized by vic-admin prior to bundling.

https://bugzilla.eng.vmware.com/show_bug.cgi?id=1727636

**Comment by sgairo** [comment]
@hickeng Could you show a snapshot of an example please?

**Comment by sgairo** [comment]
@hickeng Would it be appropriate to remove all of the guestinfo from this log?

**Comment by hickeng** [comment]
@sgairo That's better than leaving it in and is significantly more fail-safe than targeted stripping of values across VCH versions.

While it leaves us without knowledge of the underlying VCH config from the logs we can always ask GSS to request a sanitized form of that data via manual means.

**Comment by hickeng** [comment]
@caglar10ur This is specifically for stripping credentials but is part of the log sanitzation work.

**Comment by sgairo** [comment]
@hickeng Will your WIP take care of this issue by Monday? Should I go ahead and merge my PR or close it out and reassign to you?

**Comment by sgairo** [comment]
UPDATE: Going for a simpler option - don't collect the vmware.log file for the applianceVM. We can get GSS to request it explicitly if we need it.

Taken care of by #2784
