### ISSUE TITLE
docker ps shows stale data after exiting from busybox shell

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#2187]
With 0.5.5 release, I observe the following:

```
vmware@office1-sfo2-dhcp270:~/vic/vic$ docker --tls run -it --name mybusybox2 busybox
/ # exit
vmware@office1-sfo2-dhcp270:~/vic/vic$ docker --tls run -it --name mybusybox2 busybox
/ # exit
vmware@office1-sfo2-dhcp270:~/vic/vic$ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
30a8115a377a        busybox             "sh"                     2 minutes ago       Running                                 mybusybox2
71da9aedebb0        nginx               "nginx -g daemon off;"   3 minutes ago       Running                                 mynginx
dd5d62cda8e6        busybox             "sh"                     4 minutes ago       Stopped                                 mybusybox
vmware@office1-sfo2-dhcp270:~/vic/vic$ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
30a8115a377a        busybox             "sh"                     2 minutes ago       Running                                 mybusybox2
71da9aedebb0        nginx               "nginx -g daemon off;"   3 minutes ago       Running                                 mynginx
dd5d62cda8e6        busybox             "sh"                     5 minutes ago       Stopped                                 mybusybox
```

Docker ps is continuing to show the container as running, when it has in fact stopped. This should be very easy to reproduce. Here is the command I used to install the VCH:

```
./vic-machine-linux create --name VCH1 --target 10.118.67.35 --user drone@vsphere.local --password xxx --bridge-network test-internal-network --external-network test-external-network --image-store iSCSI-nas-2
```

**Comment by corrieb** [comment]
[container-logs.zip](https://github.com/vmware/vic/files/444173/container-logs.zip)

**Comment by gigawhitlocks** [comment]
This looks like a duplicate of #2271

**Comment by cgtexmex** [comment]
From my perspective this is the nature of the system.  The port layer hasn't received the VmPoweredOff event until the VM has completely powered off.  AFAIK there is no VmPoweringOff event -- there is a GuestShutdown event that happens before PoweredOff that might provide quicker notice and we can set to Stopping and then Stopped when PoweredOff is received.  

The reality is sometimes it will power off gracefully (Shutdown --> PoweredOff) other times it will be a hard power off...so always a possibility of some short term state inconsistency.

**Comment by jzt** [comment]
@corrieb OK to close this issue?

**Comment by mhagen-vmware** [comment]
Under a heavily loaded system is that "short term state inconsistency" possibly really long?

**Comment by hickeng** [comment]
@mhagen-vmware It shouldn't be unless you're massively over-committed. Sending a signal is a synchronous affair so if we succeed on that path, the guest shutdown should be relatively rapid on it's clean path.
We do have an issue about stop being slow #2568 that @caglar10ur was looking into.

@jzt I'm going to icebox this and we can revisit @cgtexmex's mention of GuestShutdown event at a later date. I personally don't have a problem with closing it, but it's one of those cases where customer opinion will weigh heavily.

**Comment by mhagen-vmware** [comment]
priority low as this is generally working as expected at this point, but there might be one small improvement possible with the GuestShutdown event

**Comment by corrieb** [comment]
This is no longer a bug. We don't return out of the shell until the container has properly exited.
