### ISSUE TITLE
Document that vic-machine inspect shows VCH version and upgrade status

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2188]
Per https://github.com/vmware/vic/issues/2181. Related to https://github.com/vmware/vic/issues/843.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/2181 is implemented in PR https://github.com/vmware/vic/pull/2286.

**Comment by stuclem** [comment]
Updated https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/inspect_vch.md with the new output of vic-machine inspect.

@emlin, is this OK? Thanks!

**Comment by emlin** [comment]
👍

**Comment by stuclem** [comment]
Thanks @emlin!
