### ISSUE TITLE
Document support for vSphere 6.5

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2192]
No single engineering issue for this. 

@mhagen-vmware, are we in a position where we can currently claim support for 6.5 beta? Thanks!

**Comment by mhagen-vmware** [comment]
Adding test support for it right now, not quite ready for claimed full support.

**Comment by stuclem** [comment]
OK, thanks @mhagen-vmware. I'll leave it at 5.5 and 6.0 for now.

**Comment by stuclem** [comment]
@mhagen-vmware same question as before. How close are we to announcing support for 6.5? Should we wait until 6.5 GA?

**Comment by mhagen-vmware** [comment]
We have test 6.5 now, so I am comfortable claiming 6.5 support but confirm with @mdubya66 when he wants to announce it.

**Comment by mlh78750** [comment]
We announced VIC Engine and Harbor as part of the announcement for vSphere 6.5 a month ago. It's fine to show that we support it now.

**Comment by stuclem** [comment]
OK, thanks @mhagen-vmware and @mlh78750

**Comment by stuclem** [comment]
Added 6.5 to the prereqs topic. Changes are in https://github.com/stuclem/vic/commit/c1e0b2189298708250ea5a8b822084b0eba7173b.
