### ISSUE TITLE
[vsan] file operations are failing

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2196]
This happens after a fresh deployment

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(1578)] docker run -d busybox /bin/top
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
a3ed95caeb02: Download complete
8ddc19f16526: Extracting [==================================================>] 667.6 kB/667.6 kB
docker: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc420200998 Message:parent (scratch) doesn't exist in http://ZzZ/storage/images/420ade67-4a13-bde0-f361-f8dab4b551e6: cannot stat '[vsanDatastore] ZzZ/VIC/420ade67-4a13-bde0-f361-f8dab4b551e6/images/scratch/manifest': No such file}.
See 'docker run --help'.
```

I can create vms and attach disks to that VM using UI, vic-machine also works fine.

**Comment by matthewavery** [comment]
I was not able to reproduce this again. I tested against a nested VSAN, and all operations performed as expected. @fdawg4l is it possible you could also confirm this? then we can put this ticket to rest if you cannot repr as well.

**Comment by caglar10ur** [comment]
Try installing and then removing couple times via vic-machine and then run some docker operations

**Comment by fdawg4l** [comment]
Nested.

I'm reluctant to verify or report anything on nested since we lack confidence in nested vsan environments.  Doing nothing on a nested VSAN env (no vic, or anything) renders it belly up after a while (I've seen as little as an hour). 

I'd rather we leave this open until we can verify on a real vsan system (not nested).

**Comment by caglar10ur** [comment]
agreed, we should leave it open until we have a real vsan to test

**Comment by mdubya66** [comment]
I'm going to remove the p0. I'll re-assign to mhagen. He's working on getting a "real vsan" up and going and will either close or update the issue.

**Comment by fdawg4l** [comment]
Thanks @mhagen-vmware and @mdubya66.  That sounds good.

**Comment by mhagen-vmware** [comment]
Closing as un-reproducible. I have been using a hardware VSAN for almost a week now without issue and Longevity on it ran for almost 4 hours today without a VSAN related issue.

**Comment by fdawg4l** [comment]
FANTASTIC NEWS!!  Thanks @mhagen-vmware!!

**Comment by vmwarelab** [comment]
i m using a datastore on a local disk and i getting the same issue 
https://github.com/vmware/vic/issues/3031

**Comment by fdawg4l** [comment]
@vmwarelab #3031 is unrelated to this issue.  Let's stick to updating 3031 until we can root cause it.
