### ISSUE TITLE
Add user authentication to the personality

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2197]
The default docker mechanism is TLSVERIFY. This would entail:
a. modification to vic-machine to supply CA certificate to validate clients

There is also the extended docker authorization plugin mechanism which presumably requires that the client send user credentials (or session identifier) with each request. I do not know the details of this mechanism and a quick search of the remote API 1.24 docs didn't make it clear.

Tagged as vic-machine because any approach will require vic-machine changes for configuration. Estimate is for TLSVERIFY - see vicadmin for current mechanism.

https://bugzilla.eng.vmware.com/show_bug.cgi?id=1727625

**Comment by mdubya66** [comment]
Moving to Icebox. GA is pretty packed.

**Comment by hickeng** [comment]
Tooks significantly longer than expected primarily due to:
* requirement for DNS resolution of VCH or static IP
* updating tests to function correctly in a mix of environments where tlsverify is or isn't viable

**Comment by hickeng** [comment]
Moving back to in-progress for the following refinement:
* do not overwrite certs unless --force
* generate pkf certificate if openssl is available
* if certs exist in vch-name/... then see if they permit --cname (if specified), and use them. If not fall back to generate path (with the behaviour above) and log warning about certificate reuse

The first avoids mistakenly destroying your CA and invalidating all client certs.
The second makes the initial portion of #2342 much more usable as there's a cert that can be directly imported into browsers.

**Comment by mdubya66** [comment]
Moving to To Do. Not originally Dev Complete

**Comment by andrewtchin** [comment]
Looks like when I install a VCH with existing certificates (generated previously by a VCH install) the installer doesn't have a client cert to poll the status of services so the install times out. The VCH though seems to work fine so this should just be a vic-machine issue.
```bin/vic-machine-linux create --target root:password@192.168.218.129 --name chin-vic-11 --tls-cname 192.168.218.200 --external-network-ip 192.168.218.200/24 --external-network-gateway 192.168.218.2/24 --thumbprint 50:13:2A:8F:4D:9F:2C:69:AC:F2:47:38:AF:64:93:F2:CE:91:56:5D --tls-ca="./chin-vic-11/ca.pem" --cert="./chin-vic-11/server-cert.pem" --key="./chin-vic-11/server-key.pem" --debug 1```
```
time=2016-11-02T09:24:25.073302925-07:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CreateVCH:37] [18.868305378s] chin-vic-11 
time=2016-11-02T09:24:25.073312296-07:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:670] 
DEBU[2016-11-02T09:24:25-07:00] Loading CAs for client auth                  
DEBU[2016-11-02T09:24:25-07:00] CA configured on appliance but no client certificate available 
DEBU[2016-11-02T09:24:25-07:00] connection refused                           
DEBU[2016-11-02T09:24:26-07:00] Components not yet initialized, retrying     
DEBU[2016-11-02T09:24:26-07:00] connection refused                           
DEBU[2016-11-02T09:24:27-07:00] Components not yet initialized, retrying     
DEBU[2016-11-02T09:24:27-07:00] connection refused                           
DEBU[2016-11-02T09:24:28-07:00] Components not yet initialized, retrying     
DEBU[2016-11-02T09:24:28-07:00] connection refused                           
DEBU[2016-11-02T09:24:29-07:00] Components not yet initialized, retrying     
ERRO[2016-11-02T09:24:29-07:00] Connection failed with TLS error "bad certificate" - check for clock skew on the host 
time=2016-11-02T09:24:29.102143647-07:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:670] [4.028826067s]  
time=2016-11-02T09:24:29.102162953-07:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:165] 
INFO[2016-11-02T09:24:29-07:00] Collecting ha-host hostd.log                 
INFO[2016-11-02T09:24:29-07:00] ha-host hostd.log rolled over                
time=2016-11-02T09:24:29.121059021-07:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:165] [18.88791ms]  
ERRO[2016-11-02T09:24:29-07:00] --------------------                         
ERRO[2016-11-02T09:24:29-07:00] vic-machine-linux failed: tls: bad certificate
```
info and pull busybox work
```
docker -H 192.168.218.200:2376 --tlsverify --tlscacert="./chin-vic-11/ca.pem" --tlscert="./chin-vic-11/cert.pem" --tlskey="./chin-vic-11/key.pem" info
```

**Comment by hickeng** [comment]
We have the following code in appliance.go:
```
						errmsg := root.Error()
						if errmsg == badTLSCertificate {
							// TODO: programmatic check for clock skew on host
							log.Errorf("Connection failed with TLS error \"bad certificate\" - check for clock skew on the host")
						} else if tlsErrExpected {
							log.Warnf("Expected TLS error without client certificate, received error: %s", errmsg)
						} else {
							log.Errorf("Connection failed with error: %s", root)
						}

						return root
```

We should reverse the `badTLSCertificate` and `tlsErrExpected` clauses.
We _could_/?should? return nil in that scenario rather than the error
