### ISSUE TITLE
UI plugin install: confusing doc around running install.bat

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2207]
Reading through the docs for how to install the UI plugin:
```
9. Run the installer.
       install.bat
    Make sure that you use the correct account to run install.bat.
       * If vCenter Server uses the local system account, run install.bat with the local system account.
       * If vCenter Server uses a different user account, run install.bat with that account.
10. Enter the user name and password for the vCenter Server administrator account.
```

This reads as if install.bat needs to be run on the vCenter system as the administrator account.
The note about using the correct account is associated with point 10, not point 9.

This is an issue in all of the plugin install sections

**Comment by stuclem** [comment]
Removed the lines about the VC account from the "Run the installer" step in the topics on deployment to a Windows VC from :
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vc_no_sftp_or_web.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vc_sftp.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vc_web.md

This does not affect the topics on deployment to VCSA.

@hickeng and @jooskim, is this OK?

**Comment by stuclem** [comment]
Incidentally, I am dealing with the cross-platform deployment issue in https://github.com/vmware/vic/issues/2210, so let's keep that discussion there.

**Comment by stuclem** [comment]
Merged in https://github.com/vmware/vic/issues/2227.
