### ISSUE TITLE
Document workarounds for cross-platform installation of client plug-in

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2210]
This applies to all of the UI plugin installation paths, but using this one as an example:
https://vmware.github.io/vic/assets/files/html/vic_installation/plugin_vcsa_no_web.html

The install script (install.sh or install.bat) is run on the client system where the VIC package was unpacked. This system could be linux, OSX, or Windows and that has no correlation with the type of vCenter server we're deploying to.

The documentation is written with the assumption that if you're deploying to a Windows based vCenter then the client system is Windows based and therefore we use `install.bat`, `SET`, et al.

**Comment by stuclem** [comment]
Hi @hickeng. You're quite right that the doc assumes that if you're running a Windows VC then you need to run the Windows installer script on a Windows machine, and that if you're running VCSA then you need to run the Mac/Linux installer script on Mac/Linux. However, having played about a bit this morning, I think that the doc actually reflects the reality of the UI installer scripts as they are currently. Basically:

- If your VC is a VCSA, you have to update the `vic/ui/VCSA/configs` file with the VC info.
- If your VC is Windows-based, you have to update the `vic/ui/vCenterForWindows/configs` file with the VC info.
- The `vic/ui/VCSA/install.sh` script gets its VC info from the `vic/ui/VCSA/configs` file.
- The `vic/ui/vCenterForWindows/install.bat` script gets its VC info from the `vic/ui/vCenterForWindows/configs` file.
- The contents of the `vic/ui/VCSA/configs` and `vic/ui/vCenterForWindows/configs` and the `install.sh` and `install.bat` files are obviously different.

So, for example, you cannot point `install.bat` to `vic/ui/VCSA/configs`. I tested this by copying `install.bat` into the `vic/ui/VCSA/` folder and running it. I also tried configuring `vic/ui/VCSA/configs` with info about a VCSA that I deployed in Nimbus, ran `vic/ui/VCSA/install.sh` in a bash shell on Windows, and got the following error:
`install.sh: line 137: ../../vic-ui-linux: cannot execute binary file: Exec format error`

So, I edited `install.sh` to change 

```
if [[ $(echo $OS | grep -i "darwin") ]] ; then
    PLUGIN_MANAGER_BIN="../../vic-ui-darwin"
else
    PLUGIN_MANAGER_BIN="../../vic-ui-linux"
```

to 

```
if [[ $(echo $OS | grep -i "darwin") ]] ; then
    PLUGIN_MANAGER_BIN="../../vic-ui-darwin"
else
    PLUGIN_MANAGER_BIN="../../vic-ui-windows"
```

Then the installation from a Windows machine to a VCSA worked. 

I imagine that the opposite would also work for deployments from a Linux/Mac machine to a Windows VC, but haven't tested it yet. Namely, edit `install.bat` to point `SET plugin_manager_bin=%parent%..\..\vic-ui-windows.exe` to `vic-ui-linux` or `vic-ui-darwin`, and then run `install.bat` on Mac/Linux in a Windows terminal emulator.

I can document these as workarounds for deploying the UI to a VCSA from Windows and vice-versa. However, I think that a better solution might be to produce two new scripts that users can run directly without editing. 

Namely, add: 

- `vic/ui/VCSA/install.bat` that deploys from Windows to VCSA 
- `vic/ui/vCenterForWindows/install.sh` that deploys from Mac/Linux to a Windows VC 

@jooskim, what do you think? Is the assessment above correct, or have I missed something that is blindingly obvious that would allow Windows to VCSA deployments (and the reverse) without editing the scripts and using emulators?

**Comment by stuclem** [comment]
Added instructions about how to deploy the UI from a Windows machine to a VCSA in the following files:

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_web.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_no_web.md

**Comment by jooskim** [comment]
Hi Stuart, that's a great point. Actually only if we can provide a working web server that hosts the plugin bundle file then there is no need for further work to be done except for running the vic-ui binary. However, from multiple inputs and meetings we assume there's no web server to get started with, so we're covering all possible scenarios in each platform.

Obviously such scenarios are different between Windows and Linux / macOS platforms and I am afraid 'the other OS terminal' emulator won't work as expected compared to its original counterpart. Let me further investigate this.

**Comment by jooskim** [comment]
@hickeng I am aware that the installer scripts do not detect which system it is deploying the plugin to (VCSA or vCenter Windows) If the user is using a web server for deployment though, this could be simply ignored as there's installer will stop as soon as the extension is registered with VC. However with the other case where we don't assume a web server, things get complicated. For example, trying to run the install.sh file on a Linux machine to deploy the plugin to a vCenter Windows instance will fail, as the vCenter for Windows doesn't have an SSH daemon, and vice versa.

I do agree that we should have a unified, or at least the most acceptable solution to this. One I can think of is to make the script fail gracefully and display manual steps to follow in the conditions aforementioned. 

@stuclem I see that in Step 8 of the plugin_vcsa_web.md document that you altered the variable to vic ui binary from 'vic-ui-linux' to 'vic-ui-windows'. I wonder what terminal emulator you used exactly here. If you used Cygwin or Git Bash then that will work. However if you ran it in the native Bash in Windows 10 (which might be the case for some users) then the Windows binary won't work. We probably want to make it clear in this regard.

**Comment by stuclem** [comment]
Hi @jooskim, I used Git Bash, and it did work. I updated the doc to make that clear:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_web.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_no_web.md

**Comment by jooskim** [comment]
Further thoughts here for each cross-OS scenario:

1. Deploying to VCSA from Windows
VCSA is a Linux box and if the VIC UI is deployed without a web server, access to `ssh` and `scp` is absolutely needed, so the user needs to run the `install.sh` file in a terminal emulator that supports those commands correctly. Also which vic-ui binary to use needs to be taken into account now that we have Windows 10 Bash. 

2. Deploying to vCenter from Unixy OS
Not sure if it's even possible to run batch files in Linux/macOS. If it's possible I feel it would be a lot more difficult than to run the Windows script on a Windows machine.

**Comment by jooskim** [comment]
@stuclem Thanks. The docs look good now. As far as the terminal emulator supports `ssh` and `scp` correctly like I just said in the comment above it should be all good for deploying the plugin to VCSA from a Windows machine.

**Comment by stuclem** [comment]
Thanks @jooskim. I have updated the VCSA topics to say that the shell must support SSH and SCP:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_web.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_no_web.md

I also updated the Windows VC topics to state that you can only run the script from Windows systems:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vc_no_sftp_or_web.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vc_sftp.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vc_web.md
