### ISSUE TITLE
Unit Test CI Failure: recipe for target 'test-job-github.com/vmware/vic/pkg' failed

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2218]
As seen on build: https://ci.vmware.run/vmware/vic/4532

# github.com/vmware/vic/pkg/vsphere/session
compile: reading input: EOF
Makefile:227: recipe for target 'test-job-github.com/vmware/vic/pkg' failed
make: *** [test-job-github.com/vmware/vic/pkg] Error 2
make: *** Waiting for unfinished jobs....

**Comment by andrewtchin** [comment]
no repro on more recent builds e.g. https://ci.vmware.run/vmware/vic/4609
`ok  	github.com/vmware/vic/pkg/vsphere/session	1.651s	coverage: 73.1% of statements`

**Comment by andrewtchin** [comment]
closing no repro
