### ISSUE TITLE
Imagec failure in CI test - Verify Logfile Test

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2219]
As seen in build:
https://ci.vmware.run/vmware/vic/4533

Logs:
[integration_logs_4533_13537f464b6a9078e6a31385e83a4c9a820c353b_1472684150.zip](https://github.com/vmware/vic/files/449722/integration_logs_4533_13537f464b6a9078e6a31385e83a4c9a820c353b_1472684150.zip)

```

17:33:54.364	INFO	Starting process:
/drone/src/github.com/vmware/vic/bin/imagec -standalone -reference photon -logfile /tmp/foo.log -destination /tmp/images	
17:33:54.372	INFO	Waiting for process to complete.	
17:34:04.874	INFO	Process completed.	
17:34:04.874	INFO	${result} = <result object with rc 1>
```

**Comment by jzt** [comment]
@mhagen-vmware since this issue is intermittent, and since the error comes from actual docker code, I'm going to add a `log.Warn` in our code when we get it, describing the error in detail. We can already see that the reference becomes `""` somewhere in the path, and I suspect it may happen somewhere in docker's code (since we are clearly passing in `photon` as the reference during the integration test). This log message should hopefully shine some light on what's going on next time it happens. I also am going to enable debug output in imagec for this particular test.

Sound ok?  If so, let me know and I'll toss up a PR.

**Comment by mhagen-vmware** [comment]
Yep, that sounds reasonable.

**Comment by jzt** [comment]
Just checking in since It's been about a week. @mhagen-vmware have you seen any occurrences of this bug lately?

**Comment by emlin** [comment]
https://ci.vmware.run/vmware/vic/4799 failed for imagec command:
```
 ${bin-dir}/imagec -standalone -reference photon -destination foo, shell=True, cwd=/
```

**Comment by dougm** [comment]
@emlin more context on where you see that command failing in build 4799?

Build 4799 fails in Test-Cases.Group1-Docker-Commands.1-1-Docker-Info, client error is:
```
Using default tag: latest
Pulling from library/busybox
Error while pulling image manifest: download cancelled during download
```

imagec.FetchImageManifest() configures  NewURLFetcher with a 10 second timeout, as you can see from the docker-personality.log timestamps, we exceed that timeout:

```
time="2016-09-15T02:41:24Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).PullImage] PullImage" 
time="2016-09-15T02:41:24Z" level=debug msg="PullImage: ref = busybox:latest, metaheaders = map[]\n" 
time="2016-09-15T02:41:24Z" level=debug msg="PullImage: cmd = imagec [-reference busybox:latest -host 127.0.0.1:2377 -destination /tmp]\n" 
time="2016-09-15T02:41:34Z" level=error msg="imagec exit code: exit status 1" 
```

**Comment by dougm** [comment]
@emlin maybe you were referring to build 4798?  Looks like the same issue, just happening in different tests.

**Comment by dougm** [comment]
Why is FetchImageManifest configured with such a short (10 second) timeout ?  When everything else in imagec, afaict, is using `DefaultHTTPTimeout = 3600 * time.Second` ?

**Comment by dougm** [comment]
@jzt You said above "the error comes from actual docker code".  Which error?  What code?

**Comment by dougm** [comment]
Note that the message "download cancelled during download" is returned as an error here: https://github.com/vmware/vic/blob/fbf84f21bd2fa75082c3783a25b9e903a44040c5/cmd/imagec/fetcher.go#L134

It isn't logged.  The imagec stdout/stderr streams are piped directly to the docker client.
We'll need code changes to see if these imagec test failures are indeed  the same problem as build 4799.  Simple change would be to have test include the output (Run And Return Output): tests/test-cases/Group2-Imagec/2-9-Verify-Image.robot - That way, we see any output in the log.html

**Comment by dougm** [comment]
To summarize, @jzt since this is assigned to you, my suggestions are:

- fixup the imagec robot tests so all command output is included in the log.html

- remove that short 10 second timeout, let it default to DefaultHTTPTimeout

**Comment by emlin** [comment]
@dougm yes, this is the one I mentioned:
https://ci.vmware.run/vmware/vic/4798

thanks for found that.

**Comment by jzt** [comment]
@dougm In the imagec log, I saw 

`time="2016-08-31T22:34:04Z" level=fatal msg="Error parsing reference: \"\" is not a valid repository/tag"`

Which I found [here](https://github.com/docker/docker/blob/9ba5e0fa725e3ffa592473283d9a52213dc09638/reference/reference.go#L58).

I don't know if this is related to the FetchImageManifest timeout, though. Looking now.

**Comment by jzt** [comment]
@mhagen-vmware have you seen this lately?

**Comment by jzt** [comment]
Closing as fixed.
