### ISSUE TITLE
vic-machine delete leaves custom path behind

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2223]
+    ${output}=  Run  bin/vic-machine-linux create --name=${vch-name} --target=%{TEST_URL} --user=%{TEST_USERNAME} --password=%{TEST_PASSWORD} --image-store=%{TEST_DATASTORE}/long/weird/path

After this test is run and vic-machine delete is run, it leaves behind:

/long/weird

Only the leaf was deleted.

**Comment by gigawhitlocks** [comment]
Isn't this the desired behavior? @hickeng can you clarify this? I was aware that this is how `vic-machine delete` behaves and thought it was to spec.

I can change this to, alternatively, prune any empty directories along `/long/weird/path` and stop if we find one that's not empty after removal of images (or volumes, as I believe this will apply to volume stores as well)

**Comment by hickeng** [comment]
@gigawhitlocks Leave the directories behind. If we're going to be very polite we can add a warning about an empty directory tree, but we cannot tell whether those directories are used by other code and just happen to be empty _when we check_.

**Comment by gigawhitlocks** [comment]
That's what I thought :+1:
