### ISSUE TITLE
Spurious integration test failure

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#2236]
Build failed in https://ci.vmware.run/vmware/vic/4586

Test case removing container out of band gave 
```${output} = govc: The attempted operation cannot be performed in the current state (Powered off)```

Forked the build and it passed https://ci.vmware.run/vmware/vic/4588

The CI is flaky! This is the first time I've seen this so might be hard to repro

Mike says p0

**Comment by mdubya66** [comment]
assigning to Doug M to investigate govc issue

**Comment by mhagen-vmware** [comment]
Fixed with #2268

**Comment by mhagen-vmware** [comment]
The issue was that the name of the container was a bit too generic so if there was any issue elsewhere deleting containers then it would cause this test to fail because there were multiple containers named 'test*', so I made it more specific to the test itself.
