### ISSUE TITLE
Allow subscriptions to all events

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#2252]
Currently the event manager only allows for subscriptions to a single event.  So if a component would like to receive all events from the manager then a subscription for each concrete event would need to be created.  

The current subscription logic should be changed to allow for subscription to all events with a single subscribe call.

**Comment by mdubya66** [comment]
medium for 1.1 as we need events

**Comment by sflxn** [comment]
This issue has become important for docker 1.13's docker run.  Docker has moved from using docker wait to using docker events to monitor for a container exit.

**Comment by sflxn** [comment]
Moved this to high priority as it will be a customer facing issue.

**Comment by cgtexmex** [comment]
@sflxn with the current code you can subscribe to all the published container events.  I would think that would satisfy the `docker events` requirement.  Thoughts?

**Comment by cgtexmex** [comment]
@sflxn now granted the current code is constrained to container events -- so it wouldn't fully satisfy `docker events` but would be a start...

**Comment by cgtexmex** [comment]
I spoke with @sflxn and explained the original intent of this issue.  It was intended to cover the subscription process within the PortLayer.  @sflxn is most concerned about exposing events to the persona via an API call.  That's a different issue that will require some design work.  I'll open an issue for that design work and begin that effort.

As for the original intent of this issue -- It will be satisfied when we move to the vmomi Gateway.  At that point the event code will be refactored and this will be one of the work items.  So, I'm closing this issue as it will be implemented via the vmomi effort.
