### ISSUE TITLE
Deploys - Timed Out Waiting for Appliance Components

### ISSUE THREAD

**Issue by betazep** [vmware/vic#2290]
Daily: vic_4712.tar.gz

**Expected behavior:**
Works

**Actual behavior:**
Timed Out.  Increased timeout to 10min and still timed out.
-------------

[root@ZZ vic]# vic-machine-linux create -t XXXXXX/GDC-Lab -i GDC-004Lab-VMAX1-01 -u XXXXXXXXXXX --bridge-network "VICBridge" --external-network "VLAN 402" --name TESTVIC --no-tls
INFO[2016-09-09T12:40:25-07:00] Please enter ESX or vCenter password:
INFO[2016-09-09T12:40:29-07:00] ### Installing VCH ####
WARN[2016-09-09T12:40:29-07:00] Configuring without TLS - to enable drop --no-tls or use --key/--cert parameters
INFO[2016-09-09T12:40:30-07:00] Validating supplied configuration
INFO[2016-09-09T12:40:30-07:00] vDS configuration OK on "VICBridge"
INFO[2016-09-09T12:40:30-07:00] Firewall status: ENABLED on "/GDC-Lab/host/GDC Lab Cluster/XXXXXXXXXXXX"
INFO[2016-09-09T12:40:30-07:00] Firewall status: ENABLED on "/GDC-Lab/host/GDC Lab Cluster/YYYYYYYYYYYY"
INFO[2016-09-09T12:40:30-07:00] Firewall configuration OK on hosts:
INFO[2016-09-09T12:40:30-07:00]   "/GDC-Lab/host/GDC Lab Cluster/XXXXXXXXXXXX"
INFO[2016-09-09T12:40:30-07:00]   "/GDC-Lab/host/GDC Lab Cluster/YYYYYYYYYYYY"
INFO[2016-09-09T12:40:30-07:00] License check OK on hosts:
INFO[2016-09-09T12:40:30-07:00]   "/GDC-Lab/host/GDC Lab Cluster/XXXXXXXXXXXX"
INFO[2016-09-09T12:40:30-07:00]   "/GDC-Lab/host/GDC Lab Cluster/YYYYYYYYYYYY"
INFO[2016-09-09T12:40:30-07:00] DRS check OK on:
INFO[2016-09-09T12:40:30-07:00]   "/GDC-Lab/host/GDC Lab Cluster/Resources"
WARN[2016-09-09T12:40:31-07:00] Disabling 4A7C52BE-9255-4926-B471-3252D5F0B11A vpxd.log collection (ServerFaultCode: A specified parameter was not correct: key)
INFO[2016-09-09T12:40:31-07:00] Creating virtual app "TESTVIC"
INFO[2016-09-09T12:40:31-07:00] Creating appliance on target
INFO[2016-09-09T12:40:31-07:00] Network role "management" is sharing NIC with "client"
INFO[2016-09-09T12:40:31-07:00] Network role "external" is sharing NIC with "client"
INFO[2016-09-09T12:40:32-07:00] Uploading images for container
INFO[2016-09-09T12:40:32-07:00]         "bootstrap.iso"
INFO[2016-09-09T12:40:32-07:00]         "appliance.iso"
INFO[2016-09-09T12:40:35-07:00] Registering VCH as a vSphere extension
INFO[2016-09-09T12:40:42-07:00] Waiting for IP information
INFO[2016-09-09T12:41:15-07:00] Waiting for major appliance components to launch
ERRO[2016-09-09T12:43:29-07:00] --------------------
ERRO[2016-09-09T12:43:29-07:00] vic-machine-linux failed: Create timed out: use --timeout to add more time

**Comment by betazep** [comment]
![image](https://cloud.githubusercontent.com/assets/22081672/18400947/f25345de-768c-11e6-9131-5b4d7d8395de.png)

![image](https://cloud.githubusercontent.com/assets/22081672/18400898/af576c60-768c-11e6-814d-12109543b7da.png)

**Comment by mhagen-vmware** [comment]
@betazep Does it eventually work if you set the timeout to something like 20 or 30 min?

**Comment by betazep** [comment]
Tried 10.  I will set it to longer.

**Comment by betazep** [comment]
@mhagen-vmware Is it possible to know the Photon VCH root pwd? Maybe I can determine what process is killing the CPU.

**Comment by betazep** [comment]
Yeah... not working.  CPU of VCH stays pegged and even though I got the IP address during Debug (and could ping it), the deployment failed to complete.  

![image](https://cloud.githubusercontent.com/assets/22081672/18403066/932701a8-7697-11e6-8544-d08748a27885.png)


I jumped back a month and randomly picked 3711, and it deployed fine.

![image](https://cloud.githubusercontent.com/assets/22081672/18403055/8028a37c-7697-11e6-944b-ee3a0ffb11e0.png)

**Comment by MedavieGuy** [comment]
Can you elaborate on the ... I jumped back a month and randomly picked 3711, and it deployed fine... 
I'm having the exact same issue.  What do you mean you jumped back a month?

**Comment by betazep** [comment]
@MedavieGuy 

I downloaded one of the earlier daily builds here:  https://bintray.com/vmware/vic-repo/build/view#files

Unfortunately 3711 didn't work even though it did deploy properly.  

I also performed a build of the current source and deployed it with the same result.  (even though the build shouldn't necessarily matter as the appliance iso should be able to run in vSphere 6.0U1 without pegging the CPU forever)

I tried with and without TLS to no avail.  I tried a few different network configurations. Restarted VCH as the client was trying to find initialization (it came back up with 100% CPU). Also tried connecting to docker host directly on running VCH (but no docker host was found).  Late day Friday and ended up shutting down for some fresh eyes on Monday.

If any of the developers want to work with me on Monday via screen share, let me know.  I have to suspect it is something in my lab configuration (Firewall? ... though it should be open, and passes the check)

**Comment by emlin** [comment]
The firewall looks ok. The problem is that VCH services are not launched correctly, so we need log messages to see what happens there.
As you already got ip address, you might check vicadmin from here: http://<ip>:2378, or ssh directly to VCH appliance vm through root:password. Log files are located in /var/log/vic

**Comment by betazep** [comment]
K building, deploying, checking...

**Comment by betazep** [comment]
Is there a requirement for a full cert (not self-signed) on the https://vcenter/sdk site?

**Comment by hickeng** [comment]
@betazep currently there's a default password of `password` - be warned, this goes away when we're not configured for dev convenience so best if we can debug via the log files. Did you get a log bundle from the vic-admin server? It's on port 2378 of the VCH appliance as @emlin mentioned.
We can see from the debug output that the various components were started, so the basic launch was successful, however it looks like component initialization was not.

There is no requirement for full cert on the vSphere side.

**Comment by betazep** [comment]
Quick note per comment that just came in from @hickeng  :  The port wasn't listening. You can replicate the condition by way of the explanation below. I understand on the password: I had expected VMWare1! or equivalent. :)


Okay.  I think I figured it out. My client accepts a shortname and appends the dns suffix (through dns suffix search) to connect to vCenter.  When the VCH appliance comes up, it is unable to find the vcenter/sdk connection because it cannot resolve the vCenter server. (it doesn't have the suffix search info) 

![image](https://cloud.githubusercontent.com/assets/22081672/18447646/6aba3c70-78dc-11e6-820a-591637753a65.png)

I had missed that the help clearly states use VC-FQDN at the end of the --target line. Though, it might be a good idea to have the installer **require** an FQDN format for VC connection because the installer does allow you to shoot yourself in the foot in this regard.  (not saying it wasn't my own fault... heheh)

![image](https://cloud.githubusercontent.com/assets/22081672/18447699/9ae7532e-78dc-11e6-83a1-db20852c3793.png)

Good news is... I am in business!  Thanks for your help.
![image](https://cloud.githubusercontent.com/assets/22081672/18447764/e42954ba-78dc-11e6-8da6-d2d0f69eb4ff.png)

![image](https://cloud.githubusercontent.com/assets/22081672/18447779/fa36e682-78dc-11e6-85ea-d233ca527fe0.png)
