### ISSUE TITLE
VCH unresponsive after HA event

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2298]
New test, installs a VCH into a cluster with DRS and HA enabled and powers off the host that it resides on.  Afterwards, it is expected to start working again but it becomes completely unresponsive - can't ping or SSH to it however govc reports that the VM is powered on and has the same IP address.

Only log bundle I could get was from VC:

[vc-sc2-rdops-vm02-dhcp-89-209.eng.vmware.com-2016-09-12--19.04.zip](https://github.com/vmware/vic/files/468151/vc-sc2-rdops-vm02-dhcp-89-209.eng.vmware.com-2016-09-12--19.04.zip)

This is possibly just related to the fact we don't support restart-ability yet.

**Comment by mhagen-vmware** [comment]
Note: We do not support HA or restart of VCH yet.

**Comment by mdubya66** [comment]
HA was not an MVP0 requirement.

**Comment by stuclem** [comment]
@mdubya, so does that mean that we won't be supporting HA at GA? What about Fault Tolerance?

**Comment by mdubya66** [comment]
Correct. I can't answer to Fault Tolerance but the only feature we agreed to support in this area was VMotion.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by ryandotclair** [comment]
I'm curious, what's the level of effort to get this supported? Perhaps I'm naive, but this seems like a simple feature to implement. 

Also, do we support HA for the container VM's?

**Comment by mdubya66** [comment]
@ryandotclair we haven't investigated the level of effort.  it's been prioritized by PM as a requirement for our next VIC Product release and will be addressed for that release. No dates are currently available for that release.

**Comment by ryandotclair** [comment]
Thanks @mdubya66, what about supporting HA for the running containers? Assuming the VCH isn't running on the ESX server that goes down, will vSphere HA kick in for the running container and work as expected? Or will the container get "killed"?

**Comment by mdubya66** [comment]
I'll defer to @hickeng for this last comment

**Comment by corrieb** [comment]
Let's separate the effort of triage from the effort of fixing/supporting. This bug is now baked into @mreferre's PPT on VIC.

The original test failure was 3 months ago and seems like we don't know what the cause of it was. Maybe we do, but if so, I'd like to see some analysis here. 

Those of us who have tried it ad-hoc have seen it work. Can we at least prioritize figuring out what is/was broken here. Once we've done that, we can make a cost/value analysis of fixing it.

**Comment by mdubya66** [comment]
agreed. prioritizing medium and moving to backlog

**Comment by mhagen-vmware** [comment]
moving up to high now, as we are targeting HA support ASAP.

**Comment by mhagen-vmware** [comment]
Still seeing this on the latest code:

[5-4-High-Availability-VCH-0-6700-container-logs.zip](https://github.com/vmware/vic/files/748726/5-4-High-Availability-VCH-0-6700-container-logs.zip)

**Comment by mhagen-vmware** [comment]
Closing this, no longer an issue. With restart support, and making sure to find if the VCH got a new IP address this is no longer being seen.  However, there is another issue I will be filing.

**Comment by ryandotclair** [comment]
@mhagen-vmware A few questions:
- Do you know what this particular issue was?
- Is no longer an issue with the 0.8.0/GA (1.0.0) bits, or some later release? 
- I'm assuming until the #744 is closed, we aren't going to officially support vSphere HA?

Thanks!

**Comment by mhagen-vmware** [comment]
This issue was really old and likely a combination of any and all of the below:
1. We hadn't finished supporting even restart on VCH yet at the time
2. My test didn't use a shared datastore
3. I may not have gotten the correct new IP address after the HA event in my test

**Comment by mhagen-vmware** [comment]
And correct until #744 is closed, we can't really say we support HA successfully.
