### ISSUE TITLE
Shared data volumes

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#2303]
## Promoted to epic
There is a general requirement for shared volumes with concurrent access across multiple containers.
Some basic usages are in the conversation below and we should confirm those are addressed by however this feature is implemented.

Delivered feature design should cover at least:
1. Where the shared data is hosted (in appliance, container, or out-of-band)
2. How volume store is specified during VCH creation and operation, including credentials if necessary
3. What failure modes exist and how failures are addressed
4. Lifecycle of data vs vmdk based volume stores

####  Original detail by @anchal-agrawal:
Follow-up of #2281 and #2291

We should add support for mounting directories as a volume on containers with the `-v` option.

**Expected behavior:**

```
$ docker -H 192.168.77.131:2375 run -it -v ~/myapp:/myapp busybox
/ # ls
bin    dev    etc    home   myapp  proc   root   sys    tmp    usr    var
```

**Actual behavior:**

```
$ docker -H 192.168.77.131:2375 run -it -v ~/myapp:/myapp busybox
docker: Error response from daemon: path /storage/volumes/home/anchala/myapp was not found.
See 'docker run --help'.
```

**Comment by hickeng** [comment]
@anchal-agrawal This just isn't going to work with vic as there's no mechanism available to us to share that local directory with the remote container.
Even with regular docker I don't think it has value beyond either:
* volume create (if a name is required), or
* anonymous volume
unless docker have added a mechanism to upload the contents of the client's directory to the server.
In your example, what is in the myapp directory when you're in the container?

**Comment by anchal-agrawal** [comment]
Gotcha, thanks George. In my example, the `myapp` dir contains an empty file. Running `docker run -it -v ~/myapp:/myapp busybox` with vanilla docker, any changes inside `myapp` from the host are synced to the container.

**Comment by hickeng** [comment]
Changes from the _host_ are reflected in the contianer, not change from the _client_ - I'm assuming they're separate systems?

**Comment by anchal-agrawal** [comment]
Sorry, in my example, the host system and the client are the same system. I see that adding support for NFS volumes would achieve the intended goal.

**Comment by mdubya66** [comment]
Moving to Icebox

**Comment by mreferre** [comment]
@hickeng this is coming up more and more as of late. I think we should prioritize this work (NFS driver support) if possible. 

/cc @corrieb

**Comment by npakrasi** [comment]
Added to 0.7.0 release notes known issues.

**Comment by hickeng** [comment]
@mreferre Are there specific use cases that keep repeating, a general request for shared volumes, or something else entirely?

**Comment by mreferre** [comment]
@hickeng last I heard was a customer that needed to have credentials inside containers and that mapping a volume that had such credentials was how they were doing it. 

Provided we all agree it's a hack and you should never have persistent information on docker hosts (that you have to manually sync etc etc) let alone credentials.... this is how they are doing it with docker today (and can't be done with VIC). 

I sense/feel there is a general need for being able to pass information into the container (e.g. configuration files etc) at run time where an NFS mount may be a good way vehicle.

**Comment by hmiller997** [comment]
@hickeng  As far as use cases go; without the ability to mount some form of an external volume, how would the data from a stateful application / service, such as MySQL data files, logs, etc,,  persist after an image update or stop/restart? Or is it recommended practice that VIC containers only be utilized for stateless applications / services and create normal VMware VMs for stateful apps?

**Comment by mlh78750** [comment]
@hmiller997 We have support for docker volumes which will answer your use case. We do not support shared volumes and adding support for something like NFS would allow containers to share a filesystem. The example that was used in the original comment for this issue was trying to use host volumes which we do not support either. However, basic volume support does work. You just cannot at this time have two containers share a filesystem at the same time.

**Comment by matthewavery** [comment]
@hmiller997 Please let me know if you have further questions, or you feel that our documentation on the volume support could be improved.

**Comment by hmiller997** [comment]
@matthewavery, @mlh78750 Thanks for your replies. I am in the process of testing out the VMware volume store method now. Documentation seems pretty straight forward. I am familiar with some of the Docker volume plugins available like this: https://github.com/gondor/docker-volume-netshare.git but I didn't realize you had one to access the VMware data stores directly already built in. Thanks.

**Comment by matthewavery** [comment]
as of now we are linking this historical ticket to ticket #3622 This will be the initial research into adding in NFS shared volume support to VIC.

**Comment by matthewavery** [comment]
It is important to note that the example above `docker -H 192.168.77.131:2375 run -it -v ~/myapp:/myapp busybox` is requesting a volume mount from the daemons filesystem to the container. so it would be requesting ~/myapp from 192.168.77.131:2375 to be mounted into the container.

**Comment by mdubya66** [comment]
Added to admiral's list. Promoting to High

**Comment by mdubya66** [comment]
From the admiral wiki
Shared data volumes is work in progress in VIC. The use case where 2 containers are attached to the same volume is not yet working (resulting in error
"Server error from portlayer: Failed to lock the file."

**Comment by stuclem** [comment]
After conversation with @mshipkovenski, this is for inclusion in the release notes for both VIC Engine and Admiral.

**Comment by stuclem** [comment]
Proposed release note entry:

-----

- <b>Shared data volumes are not supported. [#2303](https://github.com/vmware/vic/issues/2303)</b><br> vSphere Integrated Containers Engine does not support shared data volumes.

-----

@anchal-agrawal @matthewavery  @mshipkovenski please feel free to provide more info in this issue. Thanks!

**Comment by mshipkovenski** [comment]
The issue describes a limitation of VIC: multiple containers cannot share a common "vsphere" volume. The impact for Admiral is that provisioning apps with containers sharing volumes on VIC will fail with "Server error from portlayer: Failed to lock the file.". Users should not design or import such templates in Admiral and try to deploy apps based on them on VIC.

**Comment by stuclem** [comment]
Thanks @mshipkovenski, this helps a lot!

**Comment by stuclem** [comment]
New proposed release note:

-----

- <b>Shared data volumes are not supported. [#2303](https://github.com/vmware/vic/issues/2303)</b><br> vSphere Integrated Containers Engine does not support shared data volumes, meaning that multiple containers cannot share a common vSphere volume. As a consequence, using vSphere Integrated Containers Management Portal to provision applications that include containers that share volumes fails when using vSphere Integrated Containers Engine, with the error `Server error from portlayer: Failed to lock the file`. Do not design or import such templates in vSphere Integrated Containers Management Portal and do not attempt to deploy applications based on such templates when using vSphere Integrated Containers Engine.


------

@mshipkovenski does this cover it? Once approved, and once I have permission to do so, I will also add this to https://github.com/vmware/admiral/releases/tag/vic_v1.1.0. Thanks!

**Comment by matthewavery** [comment]
Looks good @stuclem

**Comment by stuclem** [comment]
Also added as a known issue in https://github.com/vmware/admiral/releases/tag/vic_v1.1.0, now that I have editing rights on that page.

**Comment by mhagen-vmware** [comment]
closing this as the last story, integration testing is now done

**Comment by martin-borisov** [comment]
Do you have plans to support shared volumes in 1.3?

**Comment by stuclem** [comment]
@martin-borisov support for shared NFS datastores was added in 1.2.

**Comment by mshipkovenski** [comment]
@stuclem what Martin actually had in mind was whether VIC 1.2 supports containers sharing a volume on the default datastore1. The error I get when trying to provision such app is:
`{"message":"Server error from portlayer: unable to wait for process launch status: container VM has unexpectedly powered off"}` Is this expected or am I doing something wrong?

**Comment by mlh78750** [comment]
@martin-borisov the only supported shared volumes are from NFS datastores. You cannot share any other type of volume across containerVMs since the volumes are vmdks and you can't mount the same vmdk on more than 1 VM. You can do it if the backing is NFS.

**Comment by mlh78750** [comment]
@mshipkovenski We should have a better error message than what you got. I opened #6531 to track that. If you get a chance, can you please update that issue with the steps that led to you getting that error message? Thanks!

**Comment by matthewavery** [comment]
@mlh78750 I will add some triaging into #6531 This error message is definitely not good, and it should be made to be more useful. Thanks for creating a ticket!
