### ISSUE TITLE
Inconsistent license check reporting between vic-machine and vic-admin

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2305]
When deploying to a nimbus testbed - from the installer:

```
INFO[2016-09-12T22:22:08Z] License check OK on hosts:
INFO[2016-09-12T22:22:08Z]   "/vcqaDC/host/cls/10.160.163.156"
INFO[2016-09-12T22:22:08Z]   "/vcqaDC/host/cls/10.160.185.119"
```

from vic-admin:

```
License
License does not meet minimum requirements to use VIC
```

I've not yet tracked down which is correct, but I am finding that while I can create containers I cannot get an active connection to them.

**Comment by hickeng** [comment]
Assigning to you initially, @andrewtchin, as you did the vic-machine license work.

**Comment by hickeng** [comment]
This may be because part of my build is out of date. Rebuilding from clean master.

**Comment by andrewtchin** [comment]
I just checked on an ESX and it was OK. I'll check on vC later

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.
