### ISSUE TITLE
Document shared data volumes

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2306]
Per https://github.com/vmware/vic/issues/2303. We should add support for mounting directories as a volume on containers with the `-v` option.

```
$ docker -H 192.168.77.131:2375 run -it -v ~/myapp:/myapp busybox
/ # ls
bin    dev    etc    home   myapp  proc   root   sys    tmp    usr    var
```

Requires an update in the App Dev doc, if implemented. No milestone yet.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/2303 is now in the icebox. We should probably document that mounting directories as a volume is not supported in this release.

**Comment by stuclem** [comment]
Actually, we do already state that mounting directories is not supported:

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#create-a-container-and-attach-it-to-an-anonymous-or-named-volume

**Comment by mdubya66** [comment]
good idea. i added kind/note to it. Should we have a different way to track planned features?

**Comment by stuclem** [comment]
@mdubya66 I think that the current method is working, so let's leave things as they are.

**Comment by stuclem** [comment]
Documented that this is not supported in 1.0, so moving this issue back to icebox to track the doc for the implementation in a future release.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/2303 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#77
