### ISSUE TITLE
Document how Docker container remove discerns between anonymous and regular volumes

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2307]
Per https://github.com/vmware/vic/issues/364#issuecomment-232805849

**Comment by stuclem** [comment]
@matthewavery do we actually need to document anything here?

**Comment by matthewavery** [comment]
`docker rm` does not discern between anonymous and regular volumes. The volumes attached to a container that is removed should still be viewable via `docker volume ls` and `docker volume inspect <id>`. The only way a volume should be able to be removed is through a `docker volume rm`. Even if you continually invoke a `docker create` command that makes more and more anonymous volumes, those volumes will be left behind after each subsequent removal of that container.

**Comment by stuclem** [comment]
Great, thanks @matthewavery. @npakrasi can you please update the volumes topic?

**Comment by matthewavery** [comment]
@npakrasi Sorry I forgot to mention one of the flags of `docker rm`. There is a flag for container remove which specifies that volumes should be removed as well. we do no support `docker rm -v`. If it is specified it will be ignored currently.

**Comment by npakrasi** [comment]
Added to container_operations.md and using_volumes_with_vic.md.

**Comment by stuclem** [comment]
Covered by global doc review. Closing.
