### ISSUE TITLE
Simple Container - No nginx

### ISSUE THREAD

**Issue by betazep** [vmware/vic#2316]
I had this working at some point yesterday, but I have not been able to get back though a reasonable set of tests that work. (for some reason)  If anyone has a moment, I put together a quick doc of what I ran, and then I grabbed a log bundle.  I am sure it is something silly... but please let me know if I am just missing something.  

**Expected behavior:**
From Client: Deploy VCH. Change Docker_Host.  docker run nginx with port config (-p 80:80).  Connect to nginx splash screen .

**Actual behavior:**
![image](https://cloud.githubusercontent.com/assets/22081672/18494018/97a70c08-79c8-11e6-810f-c272d4344ab5.png)

[SimpleTest.docx](https://github.com/vmware/vic/files/470918/SimpleTest.docx)
[container-logs.zip](https://github.com/vmware/vic/files/470917/container-logs.zip)

**Comment by betazep** [comment]
This version works...

[root@N01APL4196 vic]# ./vic-machine-linux  -v
vic-machine-linux version v0.5.5-4633-dcd3c4f

**Comment by betazep** [comment]
Reproduced: No route to host in this version.  Guess a recent push broke container network connectivity?  

[root@N01APL4196 vic]# wget 192.168.11.154
--2016-09-14 12:02:07--  http://192.168.11.154/
Connecting to 192.168.11.154:80... failed: No route to host.
[root@N01APL4196 vic]# ./vic-machine-linux --version
vic-machine-linux version v0.5.5-4744-52183f3

**Comment by betazep** [comment]
In a twist of testing, what appears to be happening....  (still about to confirm and write up a better explanation)... 

1. When you deploy the VCH if the first docker command uses a port (docker run --name TestnginxPort -p 80:80 -d nginx) the network fails on the container and any subsequent container.
2. If you deploy VCH and the first docker command does not use a port (docker run --name Testnginx -d nginx) docker commands with ports work going forward.

**Comment by betazep** [comment]
I can't seem to get consistency with failure.  It is intermittent... even within the same version. Here are 4 runs of the exact same commands. (in order of run)  In this case, only 1 failed to work... but what I have found is that when it is in that state, no containers can be created with valid network going forward.

VIC was deployed from the same zip extraction using the below **create** command and then cleaned up afterward using the below **delete** command.  I didn't pull logs, but if you want... I can run the same test with logs for any failures if you cannot duplicate. 

For my purposes, I am just looking for a stable enough version to run a preview demonstration for my team.  I think there is great potential in this project.

---CREATE----
./vic-machine-linux create -t VC-FQDN/GDC-Lab -n TESTVICNOTLS --user ME -i GDC-004Lab-VMAX1-01 --external-network "VLAN 402" --bridge-network "VICBridge" --no-tls
---DELETE----
./vic-machine-linux delete -t VC-FQDN/GDC-Lab -n TESTVICNOTLS --user ME --force


VER: v0.5.5-4744-52183f3
--------------

WORKED
--------------
![image](https://cloud.githubusercontent.com/assets/22081672/18528900/bafa6ed6-7a7f-11e6-8dc5-3afadc3d926e.png)

DIDN'T WORK
--------------
![image](https://cloud.githubusercontent.com/assets/22081672/18529143/c5a244ac-7a80-11e6-9fcf-75c0806d4153.png)

WORKED
---------------
![image](https://cloud.githubusercontent.com/assets/22081672/18529509/3bc639e4-7a82-11e6-9840-fa2c792776d4.png)

WORKED
----------------
![image](https://cloud.githubusercontent.com/assets/22081672/18529946/01ca3e6e-7a84-11e6-85b3-e91e0a79b1dc.png)

**Comment by anchal-agrawal** [comment]
Hi @betazep, I can't reproduce this issue after several tries. @hmahmood mentioned that nginx sometimes takes a little while to come up. Can you retry hitting that endpoint a few times if you get a `no route to host` error and let us know if you're still getting that error? Also, if you get `no route to host`, please post the output of `ping $vch-ip`.

To ease debugging, you can `rm -f` the container and spin up a new one instead of deleting and recreating a VCH.

**Comment by betazep** [comment]
Adding one with logs.  Also, the network connectivity issue is from the virtual container host to the container.  (couple screenshots explaining)

DIDN'T WORK (but pings to VCH)
---------------
![image](https://cloud.githubusercontent.com/assets/22081672/18530695/9588f052-7a87-11e6-865c-ea1a32014bff.png)

VCH Cannot Ping Container (or subsequent containers)
---------------
![image](https://cloud.githubusercontent.com/assets/22081672/18530921/7ef9df62-7a88-11e6-8311-ef9e87016faf.png)

![image](https://cloud.githubusercontent.com/assets/22081672/18530947/9e13720a-7a88-11e6-8546-6cbdd9f59402.png)

[192.168.11.134 with container.zip](https://github.com/vmware/vic/files/473499/192.168.11.134.with.container.zip)

**Comment by anchal-agrawal** [comment]
Please confirm whether you're still getting `no route to host` after several `wget` attempts. Thanks!

**Comment by betazep** [comment]
@anchal-agrawal 

I was actually posting some more information as you posted.  I think I answered the ping question.  Once it is in a bad state, no further containers will get network.  So though I can remove the container and redeploy (as well as deploy new containers with a different port) none of them get network between VCH and the container... and all of them fail to expose the port through the VCH.

I have to redeploy the entire VCH in order to get things working again.... but once working, everything behaves as expected.  I can can log into VCH and ping the containers (with valid response) as well as get to my data/service through the port translation.

**Comment by betazep** [comment]
>>>Please confirm whether you're still getting no route to host after several wget attempts. Thanks!

Yep. The container isn't accessible from VCH on the bridge network.  In a good deployment, I can ping the container after logging into VCH with the root/password.

**Comment by betazep** [comment]
Threw up an httpd container on port 81 and one without a port.
![image](https://cloud.githubusercontent.com/assets/22081672/18531607/fc5c2520-7a8b-11e6-9561-c0780e160d6c.png)

![image](https://cloud.githubusercontent.com/assets/22081672/18531645/36c4a5de-7a8c-11e6-8317-f0fb66f7f9c4.png)

![image](https://cloud.githubusercontent.com/assets/22081672/18531705/81413ed8-7a8c-11e6-808d-925de8d395ad.png)

**Comment by betazep** [comment]
![image](https://cloud.githubusercontent.com/assets/22081672/18532181/56497aee-7a8f-11e6-8db3-b4fbfcddd0da.png)

**Comment by anchal-agrawal** [comment]
Thanks for the updates, @betazep. Can you go to the VC UI and check if the container has a MAC address listed? Like so:

<img width="550" alt="screen shot 2016-09-14 at 17 35 16" src="https://cloud.githubusercontent.com/assets/4361620/18532421/a7af147c-7aa1-11e6-9582-e806ad8d6eff.png">

**Comment by betazep** [comment]
Virtual Center thinks so...

![image](https://cloud.githubusercontent.com/assets/22081672/18532738/ee1b8166-7a92-11e6-89f6-145a0608d993.png)

**Comment by hmahmood** [comment]
@betazep are the two port groups ("VLAN 402" and "VICBridge) using different VLAN ids?

**Comment by betazep** [comment]
Yes.  402 is using 402.  VICBridge is using 64 (non-routed).

But I deployed another distributed port group called VICBridge2 and stood up another VCH using that bridge so I can compare.  The first time I deployed VCH, it failed with the same condition.  I deleted VCH and redeployed (like demonstrated before) and it came up fine. 

On VICBridge2 I am not using a VLAN tag.  (VLAN 0)

![image](https://cloud.githubusercontent.com/assets/22081672/18533177/f51a0cc8-7a95-11e6-9f6c-61423fd3a04c.png)

**Comment by betazep** [comment]
Bummer.  I figured it out. Apparently we have an infrastructure problem in our Lab vsphere cluster.  Sometimes the containers were landing on a different host.  When the containers are moved to the same host, everything works as expected.  Thanks for the assist.

**Comment by Sevyls** [comment]
@betazep Did you ever find a solution to use balanced VM pools with docker container networking working ?
