### ISSUE TITLE
docker create doesn't handle creation of named data volume

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2317]
Docker-compose cannot work with compose files that uses named data volumes because we are not creating the named data volume in ContainerCreate.  This was an unexpected path.

**Comment by matthewavery** [comment]
@sflxn: can you give an example of what you mean by a named data volume on a `docker create -v` opeartion?

**Comment by sflxn** [comment]
@matthewavery:  Correct.  However, in docker-compose create, it performs the named data volume creation within the docker create call.  Our ContainerCreate() isn't calling VolumeCreate() to create the named data volume if it doesn't exist.
