### ISSUE TITLE
Client API version: 1.24, server API version: 1.23

### ISSUE THREAD

**Issue by MedavieGuy** [vmware/vic#2318]
Deployed VIC and trying to run a simple docker command.
docker -H 167.74.140.201:2375 info
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)

Very new to docker... How do I proceed...

**Comment by anchal-agrawal** [comment]
`export DOCKER_API_VERSION=1.23` will resolve this. Please see https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/ts_docker_version_error.md.

**Comment by prat3ik** [comment]
Thanks for answer,
`export DOCKER_API_VERSION=1.23`
This really resolved my issue.
