### ISSUE TITLE
Docker inspect container does not have container network info

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2328]
Docker container inspect does not currently retrieve the container's IP address.  For a production deployment, this is going to be important.

**Comment by sflxn** [comment]
Estimate 3 but probably a 2.  Not sure yet.  If all goes well, a PR tonight.

**Comment by sflxn** [comment]
I have an implementation of this, but it then broke docker-compose because of issues around network alias.

**Comment by mdubya66** [comment]
Moving back to backlog. We can get by without this for dev complete.

**Comment by anchal-agrawal** [comment]
> ... broke docker-compose because of issues around network alias.

Is that related to #2592, @sflxn?

**Comment by sflxn** [comment]
```
        for network, netdefs in self.networks.items():
            if network in connected_networks:
                if short_id_alias_exists(container, network):
                    continue

                self.client.disconnect_container_from_network(
                    container.id,
                    network)
```

This is the docker-compose code that causing us problem.  We currently aren't persisting alias in the location I'm pulling from (guestinfo).  The reason the code above is failing is because with my implementation, we're adding network information in docker inspect.  Without the network information, docker-compose was ignoring the above code.  With the network info in inspect, compose then goes and checks the alias info, and in some scenario, it will attempt to disconnect the container from a network, which we currently do not yet support.

This is very unfortunate since the IP and network info in docker inspect would have been extremely useful.  There is an alternative way to get this info.  Docker network inspect <network>.  The only problem with that alternative method is that you must know which network a container is connected to, and if a container is connected to multiple networks, how do you look that up?  Unfortunately, there is no way right now.

**Comment by sflxn** [comment]
@anchal-agrawal No, it's not related.  This issue is actually simpler than that.  The above explains the issue.

**Comment by sflxn** [comment]
More additional color to the explanation above.  Root cause is this, when we perform docker create --network-alias _blah_, we are not persisting this info into the guest info, which I believe we should.

Yeah, I know, everything is tied together.  How did adding IP and network info for inspect pull in involvement of docker-compose, docker create, and guestinfo.  Yup.

**Comment by hickeng** [comment]
Related to #2586 ?

**Comment by sflxn** [comment]
@hickeng Unfortunately, no.  The problem is that the alias info are not being persisted.  It appears docker-compose creates network aliases and if doesn't see it during container inspect (because we don't persist it), it will then try to disconnect the container from the network.

Hasan suggested getting the network data from the scopes PL, but it's not working yet.  That would appear to be a bandaid.  Since we create the alias during docker create, we should persist the alias info at that time.  It doesn't appear we're persisting them.

**Comment by hickeng** [comment]
Sounds dependent on @cgtexmex 's work on #2580

**Comment by caglar10ur** [comment]
yep, I believe that's true

**Comment by sflxn** [comment]
It doesn't appear we're persisting aliases for links or networks at all.  Alias in the execconfig is never populated.  Alias in scopes PL is only valid if the container is running, and that doesn't help us for inspecting.  Instead of trying to fix alias persistence in this issue, I'm opening up a new issue and will use the cached alias information in the personality server.  I think it's worth having some data rather than no data at this time.  Without this, it'll be hard for the user to tell which networks a container is attached to at this time.

**Comment by hmahmood** [comment]
@sflxn what about this: https://github.com/vmware/vic/blob/92027e2e54aa5ccfed421e73049a4e85b466f591/lib/portlayer/network/context.go#L949

**Comment by sflxn** [comment]
Update, I was wrong about the alias not being there.  It's there.

**Comment by mdubya66** [comment]
We don't use the Done Pipeline. Please keep items in In Progress until they are merged.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
