### ISSUE TITLE
Create multi-tier app compose examples

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2331]
We need to create multi-tier app examples in docker-compose and update our current docs.  Our current targeted feature set for 1.0 is lacking some very big feature set for a production deployment.  Most applications will not deploy without these.

1. mapped data volume
2. docker cp
3. docker build

However there is a workflow that will allow them to deploy an app using docker-compose.  In order to show how to develop and deploy a containerized app on VIC, we should build some examples.  One of which can be the current docker voting app.

The propose develop/deploy workflow is as follows,

1) create app that takes args from env var or commandline options (no config files)
2) use regular docker to build containers of them
3) push to a private registry
4) create compose yml that does not use aliases/links or mapped volumes
5) deploy to vic from the private registry

**Comment by stuclem** [comment]
Added the user-doc label to this one, even though it's a dev issue, so that I can keep a regular eye on it.

**Comment by mdubya66** [comment]
moving to in progress as @chengwang86 is working on this now

**Comment by chengwang86** [comment]
Fixed by PR #2635 and #2680
