### ISSUE TITLE
vic-machine ls crashes with nil pointer dereference

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#2337]
`vic-machine ls` crashes on build 4802 and 4762. It works fine on one of the older builds, for example 4659.

**Code**
`vic-machine-(linux/darwin/windows) ls --target 0.0.0.0 --user a@v.l --password p`

**Expected behavior:**
Should list all VCHs installed on the target.

**Actual behavior:**
```
INFO[2016-09-15T11:45:40-05:00] ### Listing VCHs ####                        
INFO[2016-09-15T11:45:40-05:00] Validating target                            
ERRO[2016-09-15T11:45:41-05:00] --------------------                         
ERRO[2016-09-15T11:45:41-05:00] vic-machine-darwin failed: runtime error: invalid memory address or nil pointer dereference
```

**Comment by mhagen-vmware** [comment]
@jooskim Is this still happening? I need to know for release notes. Thanks!

**Comment by jooskim** [comment]
@mhagen-vmware Sorry I didn't respond yesterday; I was out for the university recruiting event. I'll check that out today.

**Comment by jooskim** [comment]
@mhagen-vmware Seems it's now fixed. Not sure which PR fixed it, but since it's now fixed I'm closing the issue.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
