### ISSUE TITLE
vic-admin: add authentication/authorization check to vic-admin for log collection

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2342]
Currently vic-admin allows un-authenticated users to download log bundles.

At a minimum we should be adding authentication (and preferably authorization) for log access. We _might_ want to provide some of the health status to unauthenticated users.

vic-admin should try authZ in the following manner:
1. use an http form (http basic auth is strongly discouraged) for user/pass
2. if a connection to vsphere is available, request vsphere creds:
  a. authenticate against vsphere with supplied credentials.
  b. confirm access permissions to the vch appliance VM for those credentials.
3. if no connection to vsphere is available, fall back to authenticating with the VCH OS
  a. this is _not_ a fallback for auth failure against vSphere, only for if no net connection is available
  b. no user will be enabled for login on the appliance unless --enable-ssh=<password> has been supplied as in #1218 

Addresses: https://bugzilla.eng.vmware.com/show_bug.cgi?id=1727628

**Comment by hickeng** [comment]
@gigawhitlocks I recommend approaching this as follows:

1. enable client certificate auth initially (code is already in personality for the API endpoint)
2. the rest of it

For linux and mac I think they can use the separate cert/key files directly.
For windows you need to have generated the .pfx combined cert:
`openssl pkcs12 -export -out cert.pfx -inkey key.pem -in cert.pem -certfile ca.pem`

These can then be used with wget or imported into a browser for access.

**Comment by gigawhitlocks** [comment]
Breaking this into two tasks, as referenced by @hickeng above. This issue now only applies to 1), certificate authentication, which will be present in `master` when #2691 is merged. The issue representing 2) above is #2705

**Comment by gigawhitlocks** [comment]
Completed with closure of #2883
