### ISSUE TITLE
Persist labels on portlayer side

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2355]
We're now caching labels on the personality server side so that docker-compose will work.  We need to persist them on the portlayer side.  This will be a per container k/v map.  We have plans on creating a global per VCH k/v store, but that may not come for awhile.  We may need an intermediate solution.

**Comment by mdubya66** [comment]
Iceboxed for now

**Comment by sflxn** [comment]
I submitted a PR for this.  I tested with docker-compose.
