### ISSUE TITLE
Fix the LEMP test

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2357]
The LEMP test have problems with VIC.  It need to be updated to actually work by removing the mapped volume.  Also, it cannot run until link/alias are working again.

**Comment by sflxn** [comment]
depends on #2294

**Comment by sflxn** [comment]
Unfortunately, attempting to fix this test has exposed another feature we need for docker-compose, volume inspect.

**Comment by sflxn** [comment]
#2522

**Comment by sflxn** [comment]
I think we need to backlog this issue.  There is no way to share files between the nginx and the php container with VIC right now.  We can tell users they need to roll their own image that contains both nginx and php together.

**Comment by mdubya66** [comment]
Backlogged

**Comment by chengwang86** [comment]
This is fixed by #3145 and #3153
