### ISSUE TITLE
Logging: log authentication failures when using TLSVERIFY 

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2361]
When TLSVERIFY is enabled (i.e. user authentication for DOCKER_API) we should be logging connection attempts without appropriate certificates and the originating IP address.

https://bugzilla.eng.vmware.com/show_bug.cgi?id=1727631

Depends on: #2197

**Comment by gigawhitlocks** [comment]
<pre>~/go/src/github.com/vmware/vic master*
❯ wget -v --certificate=ian-other-vch/cert.pem --private-key=ian-other-vch/key.pem --no-check-certificate https://willie.eng.vmware.com:2378/logs/vicadmin.log
--2016-11-08 12:09:05--  https://willie.eng.vmware.com:2378/logs/vicadmin.log
Resolving willie.eng.vmware.com (willie.eng.vmware.com)... 10.17.109.220, 10.17.109.220
Connecting to willie.eng.vmware.com (willie.eng.vmware.com)|10.17.109.220|:2378... connected.
OpenSSL: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
Unable to establish SSL connection.

~/go/src/github.com/vmware/vic master*
❯ wget -v --certificate=ian-vch/cert.pem --private-key=ian-vch/key.pem --no-check-certificate https://willie.eng.vmware.com:2378/logs/vicadmin.log
--2016-11-08 12:09:10--  https://willie.eng.vmware.com:2378/logs/vicadmin.log
Resolving willie.eng.vmware.com (willie.eng.vmware.com)... 10.17.109.220, 10.17.109.220
Connecting to willie.eng.vmware.com (willie.eng.vmware.com)|10.17.109.220|:2378... connected.
WARNING: cannot verify willie.eng.vmware.com's certificate, issued by ‘O=ian-vch’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 10670 (10K) [text/plain]
Saving to: ‘vicadmin.log.2’

vicadmin.log.2            100%[=====================================>]  10.42K  --.-KB/s    in 0s      

2016-11-08 12:09:10 (132 MB/s) - ‘vicadmin.log.2’ saved [10670/10670]


~/go/src/github.com/vmware/vic master*
❯ grep Error vicadmin.log.2

~/go/src/github.com/vmware/vic master*
❯ grep -i fail vicadmin.log.2
2016/11/08 03:38:16 http: TLS handshake error from 10.17.109.162:59328: tls: failed to verify client's certificate: x509: certificate signed by unknown authority
</pre>
