### ISSUE TITLE
Tether handleSessionExit not persisting the process ExitTime

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#2366]
A container start / stop will execute against a session in the tether code.  This session is the process that is started / stopped by the tether.  

When stopping the session the tether should record the exit time.  That is currently not being persisted to the vmx file.  The following line is where the session is updated:

https://github.com/vmware/vic/blob/master/lib/tether/tether.go#L329

This ExitTime data is needed for various functions across the project (container list, inspect, etc)

This part of #1899

**Comment by mhagen-vmware** [comment]
Note: docker inspect, list, etc commands will not include the exit time for containers at this time.

**Comment by cgtexmex** [comment]
When I created the issue I though we wanted to capture the exit time in the Diagnostics / ExitLog.  Instead we will capture as an attribute of the session.  So this is essentially a duplicate of #1899...thus closing.

**Comment by stuclem** [comment]
This is fixed in #1899. Removing kind/note.
