### ISSUE TITLE
Update docker personality to latest API version

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2368]
The docker personality is currently tied to API 1.23, which corresponds to CLI 1.11.  We need to update to API 1.24 or the latest for GA.

**Comment by mdubya66** [comment]
This is not a requirement for our MVP. At this time I think we should hold off on moving to 1.12 unless there is something we can't do with API version 1.23

**Comment by mdubya66** [comment]
Moving to Icebox and removing from 1.0

**Comment by sflxn** [comment]
Closing as duplicate to #3415
