### ISSUE TITLE
CI integration test failure: Docker logs with follow

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#2380]
A recent master build (https://ci.vmware.run/vmware/vic/4894) failed with:

```
==============================================================================
Test-Cases.Group1-Docker-Commands.1-8-Docker-Logs :: Test 1-8 - Docker Logs   
==============================================================================
192.168.31.12

Installing VCH to test server...
Installer completed successfully: VCH-4894-7713...
------------------------------------------------------------------------------
Docker logs with follow                                               | FAIL |
4 != 5
```

[integration_logs_4894_4ff1388a89826e58202dda9ffd0247f8acbfe156_1474309503.zip](https://github.com/vmware/vic/files/481020/integration_logs_4894_4ff1388a89826e58202dda9ffd0247f8acbfe156_1474309503.zip)

**Comment by mhagen-vmware** [comment]
@anchal-agrawal Can you initial triage this for me? We need to know the general problem here in order to release note it.  Thanks!

**Comment by anchal-agrawal** [comment]
This test prints 5 lines to stdout in the container, but `logs --follow` is able to grab only 4 in this failure. Since this failure is intermittent, it might indicate a timing issue. A `sleep` of a few seconds before issuing the `logs` command should resolve the issue.
