### ISSUE TITLE
VSphere users should be able to monitor containers

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#24]
VSphere users should be able to easily monitor containers in the UI. This may initially just mean monitoring the same set of things that can be monitored for a VM.

**Comment by hickeng** [comment]
Pretty sure this is there by default, but moving it to icebox for further consideration post release

**Comment by sgairo** [comment]
Readdressing this issue, does this take care of it:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/container_portlet_ui.md

**Comment by hickeng** [comment]
@mdubya66 @sgairo I think presentation of container details such as image or ports is a different concern. Given this is solely about monitoring performance at a vsphere level I'm closing it - existing vm monitoring mechanisms are available.
