### ISSUE TITLE
Add a warning in the UI installer for vCenter 5.5 users

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#2416]
Now that we're not supporting vSphere 5.5 in MVP GA any warning or comment in scripts as well as UI code regarding vCenter 5.5 should be removed.

**Comment by mdubya66** [comment]
are they harming anything? what if we decided we wanted to add support again in the future?

**Comment by jooskim** [comment]
There isn't much that will break or harm to any existing environment we have here, as the only difference I had to accommodate for v5.5 was the installation path of the Web Client plugin. The plugin code itself will remain the same. If we want to bring this back in the future for VC 5.5 (by when it would look and behave exactly the same still), I can put the existing version into a separate branch that I could freeze.

**Comment by jooskim** [comment]
@mdubya66 Following up with your latest email, we can keep the scripts as they are. I was wondering if we needed to remove anything that slightly makes the user feel v5.5 is supported, say, by having the installer script ask "Are you running vSphere 5.5?".

**Comment by mdubya66** [comment]
let's play it by ear. if you want to remove the UI plugins that should be ok but i'd like to keep vic-machine working on 5.5 since we don't have anything to prevent it from operating. Customers just won't get support.

**Comment by jooskim** [comment]
Ok, what I could do is leave the code (actual plugin code and installer) as it is, but add a warning that VC 5.5 is not officially supported and that it should be used with their own risk. As you may know the plugin itself actually works anyway. It's just the lack of automated test framework that was being a problem.

**Comment by mdubya66** [comment]
whatever you are comfortable with. thanks.
