### ISSUE TITLE
Add per personality labels

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2424]
Docker supports labels per daemon (as opposed to per container labels).

Example use case

$> ./docker-personality-server <opts> --label com.vmware.environment="production"
$> docker info

The label would show up in docker info.  It's a way to label a server.

Since this is passed to the daemon on startup, there doesn't really seem to be a need to persist this data.  In memory cache may be enough.

**Comment by mdubya66** [comment]
Iceboxed for next Release

**Comment by zjs** [comment]
A comment field or labels may be useful for expressing the intended use of a VCH. However, keeping this issue around is unlikely to result in the implementation of this functionality.
