### ISSUE TITLE
Document that volume store is not created by default

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2430]
Per Slack chat with @mreferre, customers might assume that if you don't specifiy `vic-machine create --volume-store` then a volume store is created by default in the image store datastore (which is the DS that is used if `container-store` is not specified). We should state clearly in the doc that if you don't specify `volume-store`, then no volume store is created.

**Comment by stuclem** [comment]
Added an IMPORTANT note to https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#volume-store.

@mreferre does this cover it?

**Comment by mreferre** [comment]
LGTM

**Comment by stuclem** [comment]
Approved by @mreferre via slack.
