### ISSUE TITLE
Docker ps Remove container OOB fails on VC

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2432]
govc ls vm:
```
 /not-ha-datacenter/vm/VCH-0-2964/naughty_morse-25d8d03283b0cd311e507b4fa893f1504063cc2132baf74d4ace16a767ad9007
/not-ha-datacenter/vm/VCH-0-2964/high_wing-06a01fbd29011c6ffbac972a8ce3813a511a60077dcd9f5b908ca985e6e7775f
/not-ha-datacenter/vm/VCH-0-2964/adoring_poincar-6977d223ac22fc7e83ad8cd63b80841e37c938a63859ac5d773f2b112b044f45
/not-ha-datacenter/vm/VCH-0-2964/VCH-0-2964
/not-ha-datacenter/vm/VCH-0-7378/VCH-0-7378
```

ps -aq:
```
10:02:04.045 	INFO 	Running command 'docker -H 10.160.243.80:2375 ps -aq 2>&1'. 	
10:02:04.149 	INFO 	${rc} = 0 	
10:02:04.150 	INFO 	${output} = e62bc350d490
25d8d03283b0
06a01fbd2901
6977d223ac22
```
```
jojo-e62bc350d4907e18f4c1035f950f0f79644cd289d1392e2f0eef5674c09a0f5e
```
is the container that was removed OOB, but as you can see ps -aq still reports the e62bc350d490 container.

[1-10-Docker-PS-VCH-0-2964-container-logs.zip](https://github.com/vmware/vic/files/487624/1-10-Docker-PS-VCH-0-2964-container-logs.zip)

**Comment by cgtexmex** [comment]
Currently monitor the resource pool for events -- in the case of standalone ESXi that's sufficient.  For a vSphere cluster we'll need to move up to the cluster or datacenter to ensure we capture all of the events.
