### ISSUE TITLE
Document content of the different log bundles 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2435]
We should describe what's in each of the log bundles that you can download from vic-admin.

**Comment by stuclem** [comment]
I think that we should also call out explicitly what kinds of info are included in the other types of log, with one bullet for each:

- Docker Personality
- Docker Image Resolution
- Port Layer Service
- VCH Initialization & Startup
- VIC Admin Server

**Comment by hickeng** [comment]
@stuclem The Image Resolution has now been rolled into the Personality.

**Comment by stuclem** [comment]
Thanks @hickeng. I deleted it from the list above.
