### ISSUE TITLE
Intermittent failure with docker logs --follow

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#2445]
Related to #2380 

Upon more debugging for the failure of the [`docker logs --follow `](https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-8-Docker-Logs.robot#L38) integration test, I noticed that the container's log file in ESX contains all 5 lines:
 ```
[root@localhost:/vmfs/volumes/57e03107-a8be19a3-6681-000c29cc0d29] cat con-95405365b738ae3fc737709a2f0d3259dfccc527fea1347ad7fee4a09f573d16/95405365b738ae3fc737709a2f0d3259df
ccc527fea1347ad7fee4a09f573d16.log 
line 1
line 2
line 3
line 4
line 5
```
However, the `docker logs --follow` command returned only 4:
```
$ docker -H 192.168.77.225:2375 create --name con busybox sh -c 'for i in $(seq 1 5) ; do sleep 1 && echo line $i; done'
$ docker -H 192.168.77.225:2375 start con
$ docker -H 192.168.77.225:2375 logs --follow con
line 1
line 2
line 3
line 4
```

This failure is intermittent; I was able to repro it locally once every few tries.

**Comment by anchal-agrawal** [comment]
Assigning to @dougm per my conversation with @sflxn.

**Comment by dougm** [comment]
Port layer closes the log follower (io.Reader) when the container shuts down, likely happening before the last line was read.  Swapping the sleep and echo to `echo line $i && sleep 1` would probably avoid this in the test.  Or just another `sleep 1` after the loop.  But we may want to delay closing the log follower a bit.  I'll look into it more tomorrow.

**Comment by dougm** [comment]
vmware/govmomi#598
