### ISSUE TITLE
Restarting docker container after it exited from an attach is not waiting for full initialization

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#2453]
After docker create-start-attach, I exit the container. Then the next time I want to attach to the same container, "docker attach" returns immediately without any err or warning messages. The status of the container is "**running**" since I run "docker start" before "docker attach." However, the "docker attach" can proceed successfully after around 5 seconds. 

**Expected behavior:**
$ docker -H 192.168.60.130:2376 --tls start 53d7f4c43cf1
53d7f4c43cf1
$ docker -H 192.168.60.130:2376 --tls attach 53d7f4c43cf1
root@53d7f4c43cf1:/#

**Actual behavior:**
$ docker -H 192.168.60.130:2376 --tls start 53d7f4c43cf1
53d7f4c43cf1
$ docker -H 192.168.60.130:2376 --tls attach 53d7f4c43cf1
$ docker -H 192.168.60.130:2376 --tls attach 53d7f4c43cf1
$ docker -H 192.168.60.130:2376 --tls attach 53d7f4c43cf1
$ docker -H 192.168.60.130:2376 --tls attach 53d7f4c43cf1
$ docker -H 192.168.60.130:2376 --tls attach 53d7f4c43cf1
$ docker -H 192.168.60.130:2376 --tls attach 53d7f4c43cf1
root@53d7f4c43cf1:/#

If the "docker attach" cannot proceed, it should hang or at least output a message telling the user to try after several seconds instead of returning without a notice.

**Comment by anchal-agrawal** [comment]
What's the `create` command for this container?

**Comment by chengwang86** [comment]
docker -H 192.168.60.130:2376 --tls create -it ubuntu

**Comment by sflxn** [comment]
Can you attach the logs?

**Comment by chengwang86** [comment]
[container-logs.zip](https://github.com/vmware/vic/files/494193/container-logs.zip)

Here is what I did:

1. create a fresh VCH
bin/vic-machine-linux ls --target root:pwd@192.168.60.129
2. create a busybox container
docker -H 192.168.60.132:2376 --tls create -it busybox
3. start container
docker -H 192.168.60.132:2376 --tls start container_ID
4. attach to it
docker -H 192.168.60.132:2376 --tls attach container_ID
5. exit from within the container: errors occur (see below)
time="2016-09-22T15:49:46Z" level=info msg="container attach: stdout (01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339) done: %!s(MISSING)" 
time="2016-09-22T15:49:46Z" level=**error** msg="container attach: stdin (01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339): context canceled" 
time="2016-09-22T15:49:46Z" level=**error** msg="container attach: stderr (01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339): Server error from portlayer: net/http: request canceled" 
time="2016-09-22T15:49:46Z" level=info msg="container attach:  cleaned up connections to 01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339." 
time="2016-09-22T15:49:46Z" level=**error** msg="container attach error: context canceled" 
time="2016-09-22T15:49:46Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] [7.162342772s] 01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339" 
time="2016-09-22T15:49:46Z" level=error msg="Handler for POST /v1.23/containers/01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339/attach returned error: context canceled" 
2016/09/22 15:49:46 http: response.WriteHeader on hijacked connection
2016/09/22 15:49:46 http: response.Write on hijacked connection
time="2016-09-22T15:49:46Z" level=error msg="container attach: stdin err: read tcp 192.168.60.132:2376->192.168.60.128:39720: use of closed network connection" 
time="2016-09-22T15:49:46Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerInspect] 01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339" 
time="2016-09-22T15:49:46Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerInspect] [602.451µs] 01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339"

**Comment by sflxn** [comment]
@chengwang86 You really need to look at the portlayer logs to see what's going on.  Based on what I'm seeing there, it's a little confusing.  Stdin is disconnecting, and I see some suspicious logs.

```
time="2016-09-22T15:49:46Z" level=info msg="Done copying stdin" 
time="2016-09-22T15:49:46Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*InteractionHandlersImpl).ContainerSetStdinHandler] [1.279090544s] 01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339" 
time="2016-09-22T15:49:46Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerInfoHandler] Containers.GetContainerInfoHandler" 
time="2016-09-22T15:49:46Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerInfoHandler] [10.649µs] Containers.GetContainerInfoHandler" 
time="2016-09-22T15:49:46Z" level=debug msg="Found 1 subscribers to vsphere.VmEvent: gigantic_tesla-01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339 on  localhost.localdomain in ha-datacenter is powered off" 
time="2016-09-22T15:49:46Z" level=debug msg="Event manager calling back to exec" 
time="2016-09-22T15:49:46Z" level=debug msg="Container(01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339) state set to Stopped via event activity" 
time="2016-09-22T15:49:46Z" level=debug msg="Container(01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339) closing 0 log followers" 
time="2016-09-22T15:49:46Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Update] Container.Update" 
time="2016-09-22T15:49:46Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Update] [20.428795ms] Container.Update" 
time="2016-09-22T15:49:46Z" level=debug msg="Found 1 subscribers to events.ContainerEvent: Container 01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339 PoweredOff" 
time="2016-09-22T15:49:46Z" level=debug msg="Event manager calling back to netCtx(0xc420385040)" 
```

The container powered off... if I am reading this right.  That would explain the stdin connection getting dropped.

**Comment by sflxn** [comment]
@chengwang86 When I look in the vmware.log for that container, I see the following:

```
2016-09-22T15:49:26.897Z| vcpu-1| I120: TOOLS Received tools.set.version rpc call, version = 2147483647.
2016-09-22T15:49:26.897Z| vcpu-1| I120: TOOLS setting legacy tools version to '2147483647', manifest status is 8
2016-09-22T15:49:26.897Z| vcpu-1| I120: ToolsSetVersionWork: Updating the Tools Version in the disk
2016-09-22T15:49:26.914Z| vcpu-1| I120: ToolsSetVersionWork: Done updating the Tools Version in the disk
2016-09-22T15:49:26.914Z| vcpu-1| I120: VMXVmdb_SetToolsVersionStatus: status value set to 'unmanaged', 'unmanaged', install possible
2016-09-22T15:49:26.928Z| vcpu-1| I120: TOOLS state change 3 returned status 1
2016-09-22T15:49:26.928Z| vcpu-1| I120: Vix: [98871 mainDispatch.c:4210]: VMAutomationReportPowerStateChange: Reporting power state change (opcode=2, err=0).
2016-09-22T15:49:27.017Z| vmx| A115: ConfigDB: Setting extendedConfigFile = "01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339.vmxf"
2016-09-22T15:49:27.239Z| vcpu-0| I120: VMXNET3 user: Ethernet0 Driver Info: version = 17040640 gosBits = 2 gosType = 1, gosVer = 0, gosMisc = 0
2016-09-22T15:49:27.643Z| vcpu-0| A115: ConfigDB: Setting guestinfo.vice..sessions|01a8a997e540923998517784bd842c2ddf8a30b5d4eac17acfc277bf8f1fb339.started = "true"
2016-09-22T15:49:46.712Z| vcpu-1| I120: GuestRpc: Reinitializing Channel 0(toolbox)
2016-09-22T15:49:46.928Z| vcpu-0| I120: PIIX4: PM Soft Off.  Good-bye.
2016-09-22T15:49:46.928Z| vcpu-0| I120: Chipset: Issuing power-off request...
2016-09-22T15:49:46.928Z| vcpu-0| A115: ConfigDB: Setting softPowerOff = "TRUE"
2016-09-22T15:49:46.951Z| vmx| I120: Stopping VCPU threads...
2016-09-22T15:49:46.952Z| vcpu-0| I120: VMMon_WaitForExit: vcpu-0: worldID=98863
```

Not really sure why the chipset is requesting a power off.  Not sure if the toolbox is causing this or not.  Maybe @dougm has some insights.

**Comment by chengwang86** [comment]
[container-logs.zip](https://github.com/vmware/vic/files/494329/container-logs.zip)

Attached is the full log with extra steps:

6. start container by "docker start container_ID"
7. re-attach to container by "docker attach container_ID" (failed)
8. re-attach to container by "docker attach container_ID" (succeeded)

**Comment by sflxn** [comment]
Ok, after slacking with @chengwang86, it's clear the issue needs updating.  The issue is attaching to an exited container that was restarted.

Ignore all the logs above.  I can reproduce this.  The issue is a restart of a container that was exited returns before the container fully initializes.  The initial start took about 9sec.  After the container exited, the restart occurred in 1sec.  Not realistic.  I was watching the container console when I did the restart.  It was still initializing.

The place to look is ContainerStart().

**Comment by sflxn** [comment]
@chengwang86 I would look in ContainerStart() and add some more logging to see if you can't find a code issue.  The problem may end up being in the portlayer, but start in the personality code.  Unfortunately, our logging is super terse in this area.

```
time="2016-09-22T11:43:16Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart:440] 6d97ac0f81741d310c84332aee0597453437e06e96e62f402ca8dc4f56621945" 
time="2016-09-22T11:43:25Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart:440] [8.794190414s] 6d97ac0f81741d310c84332aee0597453437e06e96e62f402ca8dc4f56621945" 
```

I would examine why ContainerStart takes awhile on the first start but finishes up so quickly on restarts.  If we can't find a way to make exiting code wait till the container is fully initialize.  If that's not easy, we can attempt to use ContainerWait() at the end of start, but I have doubts that will work.  After a restart, I did a quick docker ps and it believes the container is running.  ContainerWait will probably think it's running.

I hope it doesn't end up being work in the tether.  Probably will.

**Comment by mdubya66** [comment]
Moving to Backlog.

**Comment by hickeng** [comment]
I believe this is occurring because subsequent `start`s are not blocking for actual process launch - because the Session.Started field is still set to true.

There is an issue somewhere to address the problems with ExitCode/Started as a pair (state/status provides much more flexibility and correctness), however I cannot seem to find it.

**Comment by vburenin** [comment]
are there any reliable repro-steps? I just can't get into this situation.

**Comment by chengwang86** [comment]
Update:

After using "git bisect", I find that this PR On demand serial port #2584 solves this issue. It does not occur anymore after this PR. Need to discuss with @caglar10ur about further details.
