### ISSUE TITLE
Document changes to UI deployment process following drop of 5.5 support

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2465]
Per https://github.com/vmware/vic/issues/2416 and PR https://github.com/vmware/vic/pull/2434.

**Comment by stuclem** [comment]
PR #2434 is merged.

**Comment by stuclem** [comment]
Updated the topics on deploying the UI to the VCSA with the new step for VC 5.5:

- [Install the vSphere Integrated Containers Engine Plug-In on a vCenter Server Appliance by Using a Web Server](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_web.md)
- [Install the vSphere Integrated Containers Engine Plug-In on a vCenter Server Appliance Without Access to a Web Server](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_no_web.md)

@jooskim does this cover it? There's no impact on the Windows VC deployment, is there?

Thanks!

**Comment by jooskim** [comment]
@stuclem As far as we know now we are not officially supporting VC 5.5 (at least for the upcoming GA) so I wonder if it's preferable to have it in the doc. As you probably saw  in another Github issue you raised, I made it clear that VC 5.5 is not supported officially and therefore should be used with the user's own risk. What do you think?

**Comment by jooskim** [comment]
@stuclem Oh actually you did mention that. Sorry about that, I've been out of sync on these recently. Overall those look good to me, but maybe it would be better to make it more explicit by changing it to something like `is not officially supported`

**Comment by stuclem** [comment]
Reworded from "is unsupported" to "is not officially supported":

- [Install the vSphere Integrated Containers Engine Plug-In on a vCenter Server Appliance by Using a Web Server](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_web.md)
- [Install the vSphere Integrated Containers Engine Plug-In on a vCenter Server Appliance Without Access to a Web Server](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_no_web.md)

Thanks @jooskim!
