### ISSUE TITLE
Attempt to stop a container that has been started out of band fails on VC

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2473]
Assert Kill Signal results in the container still reporting as poweredOn when this test is run on VC.  It works with a Sleep, but I think that we should not return from the stop docker command until the vm is actually poweredOff?

The name of the container that had the problem is:
9b21175b95cfdc74818582e0140d573fdb5141b813510472c8065689e8765a51

[1-7-Docker-Stop-VCH-0-1880-container-logs.zip](https://github.com/vmware/vic/files/494063/1-7-Docker-Stop-VCH-0-1880-container-logs.zip)

**Comment by cgtexmex** [comment]
- I've attempted to recreate on nimbus w/o success -- when the client returns the VM has stopped
- When the stop command is issued the state of the container is set to "stopping" -- IMO that's sufficient.  A user can easily see that the container is in the process of stopping.  Here's an example:

I've issued a stop and then ctrl-c out of the client and did a ps
```
532e4ef66c8d        busybox             "/bin/top"          About a minute ago   Stopping                                          berserk_jang
```
Then a second or so later:

```
532e4ef66c8d        busybox             "/bin/top"          About a minute ago   Exited (143) 9 seconds ago                        berserk_jang
```

**Comment by cgtexmex** [comment]
Possibly I misunderstood the issue -- I was testing with `docker stop` -- @mhagen-vmware did you issue a `docker kill` ?

**Comment by mhagen-vmware** [comment]
Nope it was a docker stop.

Attempt to stop a container that has been started out of band

In 1-7-Docker-Stop.robot

**Comment by cgtexmex** [comment]
@mhagen-vmware ok - so from your perspective is "Stopping" acceptable?

**Comment by cgtexmex** [comment]
This appears to be strictly a timing issue.  

I'm only able to **intermittently** recreate the issue when running the test directly with pybot.  I've never been able to recreate when called via drone.  Additionally I don't think we've seen this in the "proper" CI environment.  

Finally, the previous comments of a status of "stopping" should avoid confusion for users, etc..

For now I'm closing.
