### ISSUE TITLE
Error response from daemon: Server error from portlayer: The virtual machine is not suspended.

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2482]
On build:
https://ci.vmware.run/vmware/vic/5174

[integration_logs_5174_817e9b897eafaab0d8cbaecf3aa5d948771a5b9d.zip](https://github.com/vmware/vic/files/495942/integration_logs_5174_817e9b897eafaab0d8cbaecf3aa5d948771a5b9d.zip)

**Comment by mhagen-vmware** [comment]
Also,
https://ci.vmware.run/vmware/vic/5175

[integration_logs_5175_5cf377667b750afd432d79ad40abd95ea2c5506f.zip](https://github.com/vmware/vic/files/496113/integration_logs_5175_5cf377667b750afd432d79ad40abd95ea2c5506f.zip)

container - f2c16f0f09d77b6eb1b684966a58a915c0f66aaef85d7857c71aa3fcf5f2aa56

**Comment by anchal-agrawal** [comment]
I'm looking into #2483.

**Comment by anchal-agrawal** [comment]
Closing as dup of #2533. I've posted my findings there.
