### ISSUE TITLE
Volumes: volume disks not presenting in containers

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2485]
I have seen, only once that I'm aware of, a container fail to start due to the volume it expects not being present in /dev/disk/by-label when it comes to time to mount it.

I do not have the log bundle for this failure unfortunately. My estimation is that switch-root occurred before systemd-udev had created the link. While `[systemd-udev]` appears in the process list for the containerVM after switchroot but is defunct, so isn't going to be processing netlink messages after the switch.

One possible option is to wait to switch-root until there's the same number of entries in /dev/disk/by-label as in /sys/block - **SPECULATIVE FIX - definitely needs confirmation of problem and validation of solution**

#blkid #udev

**Comment by hickeng** [comment]
https://github.com/ctdk/sbinfo/tree/6eaed7001b5a904ad86e3598ddd797eb82050e18 would allow us to walk /sys/block directly to look for the device in question

**Comment by matthewavery** [comment]
The current plan is to look over all attached block devices and attempt to decode them. from there we will output a map that maps label to block device path. This way we can remove systemd altogether(atleast for udev support) and that will also have the added side effect of trimming down the bootstrap size as well.

**Comment by hickeng** [comment]
Failing build:
https://ci.vmware.run/vmware/vic/5543/1

Failing container:
furious_hoover-aac7a248a4461e6d88dc26ade300802f715d00b45b14e80bab473a1e2554b857

[VCH-5543-8010-container-logs.zip](https://github.com/vmware/vic/files/517810/VCH-5543-8010-container-logs.zip)

**Comment by hickeng** [comment]
@matthewavery 
I suggest the following for testing. This could be scripted with `govc` but try it manually first.

1. create containerVM with volume
2. use govc/vSphere client to edit VM and remove (but not delete) the volume disk
3. power on containerVM, via govc/vsphere (otherwise you'll have docker timing out on you)
4. check that the containerVM is blocking in boot (you may need to update the `echo` statements in the bootstrap script to `tee` to stdout), but no tether output could suffice
5. use govc/vSphere client to edit VM and attach the volume disk (hotadd)
6. check that tether is launched
