### ISSUE TITLE
Diagnostics: logging from bootstrap scripts not present in debug log

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2487]
The messages in isos/bootstrap/bootstrap script are not present in the containerVM debug logs. We have the ISOLINUX message from the bootloader and the messages from the tether, but nothing in between.

**Comment by mdubya66** [comment]
Serviceability issue. Flagging for GA.

**Comment by hickeng** [comment]
This should be very simple, but seeing as I have no idea why it's not already functional having looked at the code I'm estimating 2 - some investigation required.

**Comment by hickeng** [comment]
I think this is because we cannot use file redirection in a systemd unit file. We should be redirecting stdout/stderr directly in `bootstrap`

**Comment by hickeng** [comment]
Pulling in as dependency of #5018 - estimate adjusted to reflect above comment.

**Comment by hickeng** [comment]
@lcastellano this was fixed by you wasn't it? Please close if so.
