### ISSUE TITLE
Docker API: Volume Inspect

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2493]
Volume is the only API primitive that we support that currently does not have inspect support.  We need this for docker-compose.  It's used to determine existence.

**Comment by fdawg4l** [comment]
cc @matthewavery

**Comment by matthewavery** [comment]
I am not sure of all the meta data we have for the volumes most of what is there should be sufficient though. @sflxn is it just that the call needs to succeed or are you looking for a specific piece of metadata?

**Comment by sflxn** [comment]
Compose, itself, does not look for any real metadata.  It uses inspect as a check for volume inspect.

**Comment by hickeng** [comment]
If implementing this specifically for `compose up`, and that uses it only to check for 200 or 404 response, then this can be a mostly empty json struct.

I expect filling in at least some of the struct from the VolumeGet response should be straight forward, but no need to jump through hoops for the less accessible/applicable data.
