### ISSUE TITLE
Document docker volume inspect

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2495]
Per https://github.com/vmware/vic/issues/2493. Required for `docker compose up`.

**Comment by stuclem** [comment]
Docker volume inspect is implemented in PR https://github.com/vmware/vic/pull/2506 (not merged yet).

**Comment by stuclem** [comment]
As well as adding this to the table of supported Docker commands, it should also be included in a section in [Using Volumes with vSphere Integrated Containers Engine](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md)

**Comment by stuclem** [comment]
https://github.com/vmware/vic/pull/2506 is now merged

**Comment by npakrasi** [comment]
Added to Supported Docker commands table.

**Comment by npakrasi** [comment]
Also added section on obtaining info about a volume in Using Volumes with VIC.
