### ISSUE TITLE
Create trackable, automated benchmarks that compares VIC with Docker 

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#25]
We need an automated way to benchmark the following Docker workflows with VIC.  We also need a way to track changes in these workflow with our CI builds.

Docker Create
Docker Start
Docker Stop
Docker Delete

**Comment by hickeng** [comment]
@mhagen-vmware this is in-progress by Erin

**Comment by mhagen-vmware** [comment]
@sflxn I need help on this one, does the current CI testing satisfy the original intent of this story or is there something else you are looking for? Specifically, what does "benchmark" mean in your comment - performance based? or something else?
