### ISSUE TITLE
GuestRpcSendTimedOut trying to set started = true

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2504]
From https://ci.vmware.run/vmware/vic/5224 for the failure in 1-25-Docker-Port-Map:

```
2016-09-28T18:27:19.480Z| vcpu-1| A115: ConfigDB: Setting guestinfo.vice..sessions|a7bfc579cd7ba230afa527dd1914ad7d1a25fe5851117735c911d83fd4f8ba0c.started = "true"
2016-09-28T18:28:18.727Z| vmx| I120: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
```

[integration_logs_5224_fa57322b9366817a8e73e66bc11882cc6302d1fa.zip](https://github.com/vmware/vic/files/499079/integration_logs_5224_fa57322b9366817a8e73e66bc11882cc6302d1fa.zip)

**Comment by dougm** [comment]
Those two messages are not related.  "dnd" is "Drag-N-Drop".  The dnd tools service isn't in the container VMs, so the vmx will just give up trying to talk to it.. doesn't cause any issues that I'm aware of other than that annoying message.

**Comment by anchal-agrawal** [comment]
The integration test from `1-25-Docker-Port-Map`:

```
Create container with port mappings                                   | FAIL |
4 != 0
```

failed because `wget` returned 4, which happens due to a network failure. I'm going to put up a PR that logs the complete output from `wget` during the test so we can see what exactly is going on.

**Comment by anchal-agrawal** [comment]
Closing as this is the same failure as #2354. I've reopened that ticket.
