### ISSUE TITLE
Document all required external interfaces, ports, and services

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2513]
The VIC security reference requires a list of all external interfaces, ports, and services and which ones need to be open or enabled for proper operation of the product.

**Comment by stuclem** [comment]
@hmahmood, I have asked you this before in a different context, but is port 2377 really the only port that customers need to know about? What about 2378 for vic-admin?

**Comment by hmahmood** [comment]
As far configuring or disabling the firewall is concerned, that is only due to port 2377.

Other ports that are open on the appliance:
* 2375 if no tls is deployed
* 2376 for tls
* 2378 vicadmin
* 22 ssh, for debugging purposes but this may be taken out
* 53 dns server

**Comment by stuclem** [comment]
Fabulous, thank you @hmahmood!

**Comment by npakrasi** [comment]
Added this list to the security reference topic.
