### ISSUE TITLE
Document all resources that need to be protected 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2514]
The VIC Security reference requires a list of all resources that need to be protected, such as security-relevant configuration files and passwords and the recommended access controls for secure operation.

**Comment by stuclem** [comment]
@hickeng, are there any such files that customers need to know about?

**Comment by stuclem** [comment]
Not required for 0.7, so moving back to backlog.

**Comment by npakrasi** [comment]
From George via email OCt 26:
The VM's VMX file is used to store configuration, allowing most of the configuration to be read-only by the guest. The endpoint VM is the one that holds VIC specific configuration. The container VMs may hold sensitive application data (environment variables for processes, command arguments, etc).
We do not currently have a list of the required RBAC privileges needed for the VCH user - it's on our todo list.

**Comment by stuclem** [comment]
Added this to the [Security Reference](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_security/security_reference.md#data).

Change is in https://github.com/stuclem/vic/commit/de84d91f5c17969981b4dca8c8152e5cbaaeea33.

@hickeng does this cover it?

**Comment by cgtexmex** [comment]
In **External Interfaces, Ports and Services** debug is misspelled at the 3rd bullet point:

`22 SSH when enabled with vic-machine deubg`

**Comment by stuclem** [comment]
Fixed. Taking this as an LGTM otherwise. Thanks @cgtexmex !
