### ISSUE TITLE
Document security related log messages

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2515]
The VIC Security reference requires the location of log files and descriptions of how to interpret security related log messages.

**Comment by stuclem** [comment]
@sgairo, are you the person who knows about this kind of thing?

**Comment by sgairo** [comment]
@stuclem No, sorry, I'm not the best person to give descriptions of how to interpret security logs. I would ask @hickeng or @corrieb

**Comment by npakrasi** [comment]
From George via email Oct 26: 
Security related log messages - these will show up in docker-personality.log and vicadmin.log, however we will need to extract samples of those logs for reference. We do not have a separate security event log at this time.
Those logs are accessed via the vic-admin portal - we have an open issue to alter the way these logs are persisted as they will currently be erased when the endpoint VM is restarted.

**Comment by stuclem** [comment]
I think that we can just state that there is no dedicated security log, and that security info is in the two logs quoted above.

**Comment by npakrasi** [comment]
Added to the security topic: vSphere Integrated Containers security related information appears in docker-personality.log and vicadmin.log that you can access from the VCH Admin portal.
