### ISSUE TITLE
Document accounts created during system install

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2516]
The VIC Security reference requires a list of the log-on ID of accounts created during system install/bootstrap and instructions on how to change defaults.

**Comment by stuclem** [comment]
@gigawhitlocks, https://github.com/vmware/vic/issues/635 got iceboxed, so do we need to document anything here?

**Comment by stuclem** [comment]
The Security doc is based on a standard(ish) template that is used (inconsistently) across VMware docs, so maybe we should still include a topic on service accounts that simply states that VIC does not create any.

**Comment by stuclem** [comment]
@gigawhitlocks is the statement above true?

**Comment by npakrasi** [comment]
Added a section in the security reference topic about service accounts.

**Comment by hickeng** [comment]
#1689 is likely to come into play here.
It is unlikely that we will create an account, but we may well request one be provided that we can reconfigure.

**Comment by stuclem** [comment]
Moving this back to backlog pending implementation of https://github.com/vmware/vic/issues/1689.

**Comment by stuclem** [comment]
This is covered by the review of the security reference in https://github.com/vmware/vic/issues/3404. Closing.
