### ISSUE TITLE
Document privileges assigned to “service” users

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2517]
The VIC Security reference requires the list of privileges assigned to “service” users.

**Comment by stuclem** [comment]
@gigawhitlocks, same question as for https://github.com/vmware/vic/issues/2516: #635 got iceboxed, so do we need to document anything here?

**Comment by npakrasi** [comment]
Added a section in the security reference about privileges that none are assigned.

**Comment by hickeng** [comment]
#1689 is the issue remaining in GA timeframe for privilege constraints.

**Comment by stuclem** [comment]
Moving this one back to backlog pending the implementation of https://github.com/vmware/vic/issues/1689.

**Comment by stuclem** [comment]
PR #3262, that is a part of #1689, adds an optional Operations User, which is separate from the Admin user that performs the VIC installation. Address this issue in conjunction with .

**Comment by stuclem** [comment]
@hickeng added info about the ops user to the security reference in https://github.com/vmware/vic/issues/3404. This issue is no longer needed.
