### ISSUE TITLE
Document how to obtain and apply security updates/patches

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2518]
The VIC Security reference requires information on how customers can obtain and apply the latest security updates/patches.

**Comment by stuclem** [comment]
@emlin, do we have a plan for how we'll do patches?

**Comment by emlin** [comment]
@stuclem not yet atm. @hickeng ^^^

**Comment by marcohelmerich** [comment]
We are Betatesting at the moment, and a well defined way how to patch the environment will be essential for productive use. Update of VCH(important) and update of the Photon Kernel (very important, because of CVEs and stuff)

**Comment by stuclem** [comment]
According to @mdubya66 via email, security patches will be made available as new versions of vic-machine. So, you obtain new versions (i.e. "patches") via the usual download channel (MyVMware?) and apply them by running `vic-machine upgrade`. 

@npakrasi, I think that this should be enough for the security doc.

**Comment by mdubya66** [comment]
I was asking a question in that email. Nothing is decided. 

"I agree we need to get this documented ASAP. Wouldn’t just using vic-machine upgrade work? When/if there is a CVE we release a “patch” release that is a VIC Machine upgrade.
 
Ties into the whole branch strategy of course."

**Comment by npakrasi** [comment]
From George via email OCt 26: 
I've actually no idea about how people will obtain security updates - that's related to how the formal VMware binary releases are provided; my assumption is via My VMware, but it's only an assumption.
There's not really any such thing as a patch to be applied - instead it's a version update, for which we have 'vic-machine upgrade'. It's a somewhat untested path at the moment, so I'm not going to go into more depth than the help supplies.

**Comment by stuclem** [comment]
We currently document that you should download a new vic and run upgrade:
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_security/security_reference.md#apply-security-updates-and-patches
