### ISSUE TITLE
Exited time for container is incorrect when time in container is incorrect

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#2527]
During testing I ran into this:

```
hmahmood@zeta:~/go/src/github.com/vmware/vic$ docker -H 172.16.154.136:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                  PORTS               NAMES
111162ab74ab        busybox             "sh"                About a minute ago   Exited (0) 9 days ago                       cranky_euclid
ce8fc0c71887        busybox             "sh"                2 minutes ago        Exited (0) 9 days ago                       elated_torvalds
```

The time exited is 9 days ago, yet the containers were created a few minutes ago. I ran another container:

```
docker run -it busybox date
```

Output was indeed 9 days behind. However, container start/run/exit time should be tracked separately and should not depend on what time it is in the container. 

Acceptance:
* verify container time is tracked regardless of time that is set in container, and is accurate

**Comment by cgtexmex** [comment]
This happens because the tether is setting the time on exit.  Since tether runs in the containerVM it's setting the only time it knows.

**Comment by mdubya66** [comment]
Backlogged for post dev complete

**Comment by cgtexmex** [comment]
Currently the containerVM gets it's time from the host it's running on ...if that host doesn't have NTP configured or NTP is misconfigured then the containerVM time will be incorrect.  I think this is the correct way to handle time on the containerVM and any tracking outside of the containerVM would be fraught with peril.  

Potentially in the future we could provide custom NTP options for a VCH, but I'm skeptical of its value.  Another alternative would be to see if NTP is configured when installing and provide a warning via vic-machine.

I'm open to suggestions, but I don't think we should currently make changes to how containerVM time is tracked.  We could highlight symptoms of misconfigured NTP / Time in a troubleshooting wiki but I don't believe anything further at this juncture would be worthwhile.

cc @hmahmood

**Comment by mhagen-vmware** [comment]
NTP should be configured on each of our tests systems at this point. Can we create an integration test that verifies this works as expected then?

**Comment by cgtexmex** [comment]
Yep -- I was thinking that we had one that checked that exit time, but I was wrong...I'll create one.
