### ISSUE TITLE
Handle deletes of images

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#253]
On a standard docker based setup, deleting of images is protected by the graph driver which has a representation of which images are in use (either directly or via inheritance) by containers.  For instance

```
scratch -> layer1 -> layer2 -> layer3 -> RW_layer -> container
                          \--> layer2' -> layer3' 
```

Since `container` is live, none of the layers in its hierarchy can be deleted.  However, `layer2'` and `layer3'` are good to be reclaimed.

VIC doesn't have a graph driver.  In fact, all we have is a list of VMDK disks and their immediate parents.  We could walk the list of running VMs, introspect their attached disks, identify their hierarchies, then select the set of VMDKs which are not related and allow those to be deleted for _every delete image request_ (since we're stateless and dont want to do any runtime accounting with transaction semantics).

Alternatively, we could mark each leaf image we create as a leaf.  Then when we go to delete a given image, we simply check if the given VMDK is marked and proceed if it's not marked.  We would then have to unmark each image when they become parents of images or are used (via RW_layer inheritance) by a VM.  

This avoids needing to construct a graph driver in memory and maintains the stateless nature of the port layer.  Also, since we cannot rely on ESX to give us this level of introspection, maintains correctness.  

CC: @hickeng

**Comment by hickeng** [comment]
This is not part of `vic-machine delete` - that is being accomplished with zero knowledge of the disk structures by deleting the entire image store.
