### ISSUE TITLE
IDs returned by docker images doesn't match VIC vs vanilla docker

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#2530]
```
# VIC
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker -H 192.168.8.129:2376 --tls pull ubuntu
Using default tag: latest
Pulling from library/ubuntu
a3ed95caeb02: Pull complete 
cad964aed91d: Pull complete 
3a80a22fea63: Pull complete 
50de990d7957: Pull complete 
61e032b8f2cb: Pull complete 
9f03ce1741bf: Pull complete 
Digest: sha256:c8d92743cd9933fc7bb085dafd4df600cd09d835c95a98c1ea05b504369d9654
Status: Downloaded newer image for library/ubuntu:latest
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker -H 192.168.8.129:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              827eb99e90cf        3 days ago          127 MB


# Vanilla
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/infra/machines/vcsa$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
cad964aed91d: Pull complete 
3a80a22fea63: Pull complete 
50de990d7957: Pull complete 
61e032b8f2cb: Pull complete 
9f03ce1741bf: Pull complete 
Digest: sha256:28d4c5234db8d5a634d5e621c363d900f8f241240ee0a6a978784c978fe9c737
Status: Downloaded newer image for ubuntu:latest
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/infra/machines/vcsa$ docker images
REPOSITORY                                              TAG                 IMAGE ID            CREATED             SIZE
ubuntu                                                  latest              c73a085dc378        3 days ago          127.1 MB

```

Looks like whatever ID we're using to represent images in the personality's image cache isn't the same as  whatever vanilla docker uses.

UPDATE from @hickeng:
We also seem to have two possible image IDs that we present, with the second appearing after a layer has been deleted and you re-pull:
```
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls pull ubuntu
Using default tag: latest
Pulling from library/ubuntu
a3ed95caeb02: Pull complete
cad964aed91d: Pull complete
3a80a22fea63: Pull complete
50de990d7957: Pull complete
61e032b8f2cb: Pull complete
9f03ce1741bf: Pull complete
Digest: sha256:c8d92743cd9933fc7bb085dafd4df600cd09d835c95a98c1ea05b504369d9654
Status: Downloaded newer image for library/ubuntu:latest
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              827eb99e90cf        3 days ago          127 MB
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls rmi 82
Deleted: 827eb99e90cf3732f9c12267e14d434722020d1cec632629d3e97e913bbc354d
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls pull ubuntu
Using default tag: latest
Pulling from library/ubuntu
cad964aed91d: Already exists
3a80a22fea63: Already exists
50de990d7957: Already exists
61e032b8f2cb: Already exists
9f03ce1741bf: Already exists
a3ed95caeb02: Pull complete
Digest: sha256:c8d92743cd9933fc7bb085dafd4df600cd09d835c95a98c1ea05b504369d9654
Status: Downloaded newer image for library/ubuntu:latest
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              527756be3eb9        3 days ago          0 B
ubuntu              latest              827eb99e90cf        3 days ago          127 MB
```

**Comment by fdawg4l** [comment]
cc @mdubya66 this is probably something we need for GA.

**Comment by anchal-agrawal** [comment]
I believe this is because we support schema v1 manifests for images, which have an empty layer - `a3ed95caeb02 ` - as seen in VIC's output above. Docker switched to using v2 manifests recently ([see comment](https://github.com/vmware/vic/issues/524#issuecomment-237719105)), which omits this layer.

This is why our image IDs differ from docker's. @jzt can confirm.

**Comment by hickeng** [comment]
@anchal-agrawal That may be part of it, however there's additional behaviour that isn't in @fdawg4l's example:

```
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls pull ubuntu
Using default tag: latest
Pulling from library/ubuntu
a3ed95caeb02: Pull complete
cad964aed91d: Pull complete
3a80a22fea63: Pull complete
50de990d7957: Pull complete
61e032b8f2cb: Pull complete
9f03ce1741bf: Pull complete
Digest: sha256:c8d92743cd9933fc7bb085dafd4df600cd09d835c95a98c1ea05b504369d9654
Status: Downloaded newer image for library/ubuntu:latest
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              827eb99e90cf        3 days ago          127 MB
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls rmi 82
Deleted: 827eb99e90cf3732f9c12267e14d434722020d1cec632629d3e97e913bbc354d
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls pull ubuntu
Using default tag: latest
Pulling from library/ubuntu
cad964aed91d: Already exists
3a80a22fea63: Already exists
50de990d7957: Already exists
61e032b8f2cb: Already exists
9f03ce1741bf: Already exists
a3ed95caeb02: Pull complete
Digest: sha256:c8d92743cd9933fc7bb085dafd4df600cd09d835c95a98c1ea05b504369d9654
Status: Downloaded newer image for library/ubuntu:latest
vagrant@devbox:~/vic$ docker -H 192.168.78.132:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              527756be3eb9        3 days ago          0 B
ubuntu              latest              827eb99e90cf        3 days ago          127 MB
```

As you can see in the above output, the second pull of ubuntu results in a **different** image ID.

**Comment by fdawg4l** [comment]
> UPDATE from @hickeng:
> We also seem to have two possible image IDs that we present, with the second appearing after a layer > has been deleted and you re-pull:

This is likely due to #2070

**Comment by jzt** [comment]
It looks like the `rmi` didn't delete all the layers. In fact, it looks as though only the empty layer was removed judging by the re-download indicated by the `Pull complete` in the second attempt.

I have a feeling the problem lies with the image ID being calculated only using layers that were actually pulled. https://github.com/vmware/vic/blob/master/cmd/imagec/imagec.go#L500

Looks like a fairly straightforward fix - we would need to keep hold of the existing layers identified in the manifest that we already have, and use those in addition to those we download in order to calculate the ID.

**Comment by fdawg4l** [comment]
> It looks like the rmi didn't delete all the layers.

@jzt We chatted about his over the phone last week, but the storage layer can't delete all of the layers in the branch unless you give it an endpoint and we decided we needed to know what the next (well..previous) tag to delete up to is.  We also decided we couldn't do that until the cache was persistent.  

Please let me know if I'm wrong or you see an alternative to what we're doing now.  The only thing we can do now is delete the leaf unless you'd like to go all the way to root as long as the intermediate nodes have no branches.

**Comment by fdawg4l** [comment]
>  The only thing we can do now is delete the leaf unless you'd like to go all the way to root as long as the intermediate nodes have no branches.

Ps.  I'm not averse to this.  Its really easy to implement given our `index` pkg.  I just wanted to be conservative.

**Comment by cgtexmex** [comment]
We persist and reference the layers by their layerID -- iirc this is a uniquely generated uuid for each image layer -- the layerID is not the content addressable storage identifier.  So in our current implementation if an image is able to be removed then all layers of that image could / should be removed.

If and when we start using the content addressable storage identifier then we would need to be concerned about intermediate layers having branches

**Comment by jzt** [comment]
@cgtexmex what about branching in our current implementation? For example, golang 1.6 and golang 1.7 share some base layers.

I think the big problem here is how we generate the image ID. We assume on every pull that the layers we are downloading are the complete image, but now that `rmi` is in, this is no longer the case if you `rmi` an image and then re-pull it.

**Comment by cgtexmex** [comment]
@jzt yeah..I was saying in our current implementation I didn't think we branched.  That each layer would be unique for it's specific image.  This is apparently false as your example golang 1.6 & 1.7 share some layer ids -- so I just added noise to the issue. :-)

Apologies
