### ISSUE TITLE
Attach stalls and then target container cannot be found

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#2531]
1. Container create with volume attached `docker create -it -v volume:/mount ubuntu`
2. start that container. 
3. Attach (this hung for a long time and then fails with no such container)
4. docker ps -a -> this shows the container running.
4. Every command targeting said container now fails with no such container found.

**Comment by matthewavery** [comment]
<img width="633" alt="screen shot 2016-09-30 at 9 38 06 am" src="https://cloud.githubusercontent.com/assets/8620942/18995669/c9397652-86f2-11e6-84a8-899899a12b03.png">

**Comment by mdubya66** [comment]
Pulling this into the dev complete target milestone. If a workaround is found then can be post dev complete

**Comment by anchal-agrawal** [comment]
Can't repro. I'm gonna hold off on this till @caglar10ur's changes go in.

**Comment by hickeng** [comment]
This should have been fixed by recent changes to the attach error codes. Confirm

**Comment by anchal-agrawal** [comment]
Can't repro. Closing.
