### ISSUE TITLE
Add proxy support to the appliance

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2537]
There is currently no persistent mechanism for configuring a proxy server. While /etc/sysconfig/proxy can be modified it will not persist across reboot.

I'm unsure how much code, if any, in the appliance is necessary to support this or whether the Go http stack handles this transparently.

If we have to provide different proxies for the different networks it will get involved, if only from a command line args perspective. The raw number of options to vic-machine is steadily bumping the importance of the manifest support.

This is at the request of a customer via @cormachogan

**Comment by mdubya66** [comment]
We will need to address this post GA. @karthik-narayan

**Comment by hickeng** [comment]
To make changes to the applianceVM and a recent build of VIC then you can run the following to enable console login until reboot with the password you specify:
```vic-machine-<os> debug --target=... --rootpw=somepassword``` 

If you also add `--enable-ssh` argument then it will start sshd until next reboot. If you'd prefer to automate, you can combine it with `--authorized-key=<file>` to set the provided file as the authorized keys for root in the applianceVM.

This can allow for editing of system configuration files, non-persistently, that are not yet exposed for configuration via vic-machine.

**Comment by mldmld68** [comment]
I have the  VCH version: v0.6.0-4890-4f98611, AFAIK it's the last one
# ./vic-machine-linux --version
vic-machine-linux version v0.6.0-4890-4f98611
and when I enter 
#./vic-machine-linux debug -t  "https://vc-eval.pocx86.tstwinx.net/Cloud Foundry" --user myuser --password mypass --name virtual-container-host   
It answers : No help topic for 'debug'
Thanks

**Comment by hickeng** [comment]
@mldmld68 if you're on tagged builds rather than from HEAD then 0.7 will introduce the debug command but it's not tagged yet. 0.6 you can use `password` if it's unchanged.

Part of the 0.7 work is shifting to a less dev friendly, more deploy friendly set of defaults (including adding tlsverify support #2197 and certificate based auth to the logs #2691)

**Comment by karthik-narayan** [comment]
@stuclem Could we also document the fix for adding proxy support. It looks like we've documented the SSH access, but not the details to set the proxy.

**Comment by hickeng** [comment]
@karthik-narayan there's likely code changes needed to pick up the proxy configuration, even if you do get onto the appliance and configure various settings. If proxy support is needed for 0.8 it needs to be pulled in immediately.

**Comment by karthik-narayan** [comment]
@hickeng My concern was that the workaround, though non-persistent, needs to be documented for GA. I've had a few customers who've asked for this, but it can wait for the following release.

**Comment by mdubya66** [comment]
@stuclem let's get the workaround documented for assigning a proxy. 

We need to provide it for the use case of pulling from dockerhub as well as pushing to harbor.

**Comment by stuclem** [comment]
@hickeng @mdubya66 @karthik-narayan the doc for this issue is tracked in https://github.com/vmware/vic/issues/2542, which I have moved out of Icebox and moved back into To Do and the GA milestone. 

Once you're logged into the endpoint VM via SSH, I assume that you need to do something like the following: https://justintung.com/2013/04/25/how-to-configure-proxy-settings-in-linux/

Correct?

**Comment by dougm** [comment]
My comments from slack:

Looks like imagec needs a change to support proxy: https://github.com/vmware/vic/blob/master/pkg/fetcher/fetcher.go#L101Transport.Proxy is not set, so env vars will be ignored

govmomi does for example: https://github.com/vmware/govmomi/blob/master/vim25/soap/client.go#L114-L123
 
Need http.ProxyFromEnvironment: https://github.com/golang/go/blob/release-branch.go1.7/src/net/http/transport.go#L39

Then env vars can be used: https://golang.org/pkg/net/http/#ProxyFromEnvironment

**Comment by mlh78750** [comment]
@dougm: Looks like we need to make sure the env gets passed to the port layer/docker personality here: https://github.com/vmware/vic/blob/master/lib/install/management/appliance.go#L516-L534

I editing the vic-init systemd files to set the proxy env vars for your patch earlier today, but the creation of those sub-processes doesn't pass those env vars along and they don't ever try to use the proxy settings.

**Comment by dougm** [comment]
I see.  We could add an env passthrough whitelist that includes `HTTP_PROXY` and `HTTPS_PROXY` for now.  Or go ahead and add a generic vic-machine create `-e` flag to set any environment variable(s).  I'd rather do the latter as it is more user-friendly and not much more effort to implement.  If folks agree, I can get it done in the morning.

**Comment by stuclem** [comment]
Doc is tracked in https://github.com/vmware/vic/issues/2542. Removing the kind/user-doc flag.

**Comment by stuclem** [comment]
This is fixed and documented in core doc. Removing kind/note tag.
