### ISSUE TITLE
After adding VIC host the stats (mem&cpu) are empty.

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#2540]
Getting statistics from the host is implemented as a call to the system container. However, we do not have it on VIC hosts, so stats shows N/A.
VIC: Any suggestions of how to get the total memory and the currently used memory? Any APIs or something like that? This is not part of Docker Remote API either but we were able to get it by using the container agent. 

See https://github.com/vmware/vic-bundle/issues/45

**Comment by sgairo** [comment]
Vic-Admin reports Capacity and Free Space of each individual datastore used in a VCH and could easily provide one sum number. Is this the kind of information needed?

**Comment by hickeng** [comment]
> We currently have this data in docker info. The limits and usage should be dynamic and reflect adjustments to the resource pool limits:

> vSphere Integrated Containers v0.8.0-0-8e2cf50 Backend Engine: RUNNING
```
 VCH CPU limit: 8705 MHz
 VCH memory limit: 6.324 GiB
 VCH CPU usage: 230 MHz
 VCH memory usage: 987.6 MiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.0.0
```
>I do not recall whether it's possible for usage to be over limit (i.e. whether limit is hard or soft), or what is displayed when resource pool shares are set.

> This was added in vmware/vic#3874 and vmware/vic#2898
