### ISSUE TITLE
Document how to configure VCH endpoint VM to support proxy servers 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2542]
Per https://github.com/vmware/vic/issues/2537.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/2537 will not be implemented for GA, but we need to document the workaround for setting a proxy. 

The workaround is to use vic-machine debug to permit SSH access to the VCH endpoint VM. Then you must edit configuration files in the endpoint VM to permit proxy access.

@hickeng, what are the exact edits that need to be made in the endpoint VM? Would these instructions apply? https://justintung.com/2013/04/25/how-to-configure-proxy-settings-in-linux/

**Comment by stuclem** [comment]
Proxy support was uniceboxed has been implemented in PR https://github.com/vmware/vic/pull/2980. Adding this to the 0.7 doc milestone.

**Comment by stuclem** [comment]
Added sections on configuring a proxy server:

- [vic-machine options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#options-to-configure-virtual-container-hosts-to-use-proxy-servers)
- [VCH deployment examples](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#configure-a-proxy-server)

@hickeng is this OK?

**Comment by stuclem** [comment]
Putting this back to In Progress, as I would like a review by @hickeng.

**Comment by hickeng** [comment]
@stuclem 
We should make it explicit that this proxy is solely for pulling images - it is not used in any other workflow at this time.

In "Configure a proxy server" the --tls-xxx options are irrelevant - I would remove the following bullet as it seems to imply some coupling:
`Uses the --no-tlsverify option to implement TLS authentication with self-signed untrusted certificates, with no client verification.`

**Comment by stuclem** [comment]
Added blurb in the options and examples topics to state that "The proxy that you specify serves exclusively for pulling images into the virtual container host from an external source, and is not used for any other purpose."

Removed the bullet about `--no-tlsverify` from all examples, as I agree that it's confusing overkill. Added a blurb at the beginning to state that all examples use it unless stated otherwise.

Changes are in https://github.com/stuclem/vic/commit/b6edc3db2fb0ea495eca4d749cf13ac0c946485c. @hickeng is this OK now? Thanks!

**Comment by stuclem** [comment]
Reviewed as part of global doc review. Closing.
