### ISSUE TITLE
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc42017c910 Message:Another task is already in progress.}

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2549]
Docker integration tests currently fail with the above error

[4-1-Docker-Integration-VCH-0-1352-container-logs.zip](https://github.com/vmware/vic/files/507051/4-1-Docker-Integration-VCH-0-1352-container-logs.zip)

**Comment by mhagen-vmware** [comment]
```
 	'INFO: Testing against a local daemon
--- FAIL: Test (26.15s)
	fixtures_linux_daemon.go:22: REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
		debian              <none>              a7da131cf6a1        10 days ago         123 MB
		busybox             <none>              332de81782ef        3 months ago        1.093 MB
		 0 <nil>
	fixtures_linux_daemon.go:23: Pulling from library/hello-world
		a3ed95caeb02: Pulling fs layer
		c04b14da8d14: Pulling fs layer
		a3ed95caeb02: Verifying Checksum
		a3ed95caeb02: Download complete
		c04b14da8d14: Verifying Checksum
		c04b14da8d14: Download complete
		c04b14da8d14: Pull complete
		Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc420100250 Message:Another task is already in progress.}
		: exit status 1
		github.com/docker/docker/integration-cli/fixtures/load.pullImages.func1
			/go/src/github.com/docker/docker/integration-cli/fixtures/load/frozen.go:123
		runtime.goexit
			/usr/local/go/src/runtime/asm_amd64.s:2086
		github.com/docker/docker/integration-cli/fixtures/load.FrozenImagesLinux
			/go/src/github.com/docker/docker/integration-cli/fixtures/load/frozen.go:56: error pulling image list
FAIL
exit status 1
FAIL	github.com/docker/docker/integration-cli	26.195s' does not contain 'DockerSuite.Test'
```

**Comment by fdawg4l** [comment]
There *was* a lock in bonneville around the reconfigure operation.  The lock was only acquired if a bool was true and it never was, so we never copied this chunk over.  Anyway, if we can repro this behavior reliably with this test, I can test if adding this lock will lower the frequency of this error happening.

**Comment by fdawg4l** [comment]
After adding the lock and implementing our own unit test, I can confirm the Task in Progress error goes away.  Also this test now fails in a different way.  Will push a PR to at least address the reported issue.

**Comment by hickeng** [comment]
@fdawg4l IIRC the bville code had that lock as a hold over from before the docker daemon code had that synchronization. No issue with adding a lock, but we should be able to handle this error cleanly regardless, along with others  from heavily loaded systems - (forgive me but I don't recall the specific messages).

**Comment by fdawg4l** [comment]
We are handling the Task In Progress error in the task package.  But adding the lock for the instance we know of in the disk package (where detach and attach cannot call reconfigure concurrently), a lock seems appropriate, no?
