### ISSUE TITLE
make check target is not catching golint warnings

### ISSUE THREAD

**Issue by dougm** [vmware/vic#2589]
Our code should be golint clean, noticed a few examples in this PR #2583 where we are not catching warnings from golint.
Looks like there are more such golint warnings that snuck into the code too.

**Comment by dougm** [comment]
@vburenin can you take a look?

**Comment by dougm** [comment]
We still need to fix the Makefile so our 'make check' target catches these in CI via the golint target.  There are also golint warnings that have snuck in other than what we noticed with #2583

**Comment by vburenin** [comment]
supposed to be fixed by #2642
