### ISSUE TITLE
VCH tmp partition filles up with large container. 

### ISSUE THREAD

**Issue by MattAtTTU** [vmware/vic#2595]
**VIC Version:**

0.6.0

**Code**

``` ts
// A self-contained demonstration of the problem follows...

```

When pulling an image which is 2.91GB in size from Harbor to a VCH, we receive an error that ends with "no space left on device".  After logging into the VCH while the pull is happening, I can see that the /tmp partition on the VCH server fills up precisely when the error occurs.  

Full error:

``` ts
docker: Failed to fetch image blob: weblogic/test_domain/sha256:3bf21a5a3fdf6586732efc8c64581ae1b4c75e342b210c1b6f799a64bffd7924 returned download failed: write /tmp/3bf21a5a3fdf346188145: no space left on device.
```

**Expected behavior:**

Pull should work without issue.

**Actual behavior:**

Pull fails due to /tmp partition reaching capacity.

**Comment by mdubya66** [comment]
George, please take a look. Looks like we are hitting a memory size problem.

**Comment by hickeng** [comment]
@mdubya66 @fdawg4l I think #156 was the result of raising this possibility, but it's obviously a placeholder given the few details. There's only one real solution, and that's to stream the base layer at any point in time to sPL.WriteImage as they download, with buffering on disk for dependent layers being managed so as to never consume all the mem.

There is a sort of workaround available which would be to add a non-persistent disk to use as buffer, but the same issue will occur when that's exhausted as well (it's just that a disk could be significantly larger than memory footprint).

**Comment by fdawg4l** [comment]
@hickeng if an image is 1 layer and it happens to be greater than the available memory for the VCH (see Microsoft's `windowsservercore` for a hilariously large single layer example) and available network bandwidth is greater than disk bandwidth, the same thing will happen whether or not we write to the `spl`.  

I think back-pressure is required here. Since we're using physical memory anyway (because `tmpfs`) there's really no reason to avoid using a circular with a sane size.  The client will naturally backoff when the buffer is full.  Meanwhile, we can stream the result to the `spl` asynchronously and drain the buffer.

**Comment by mdubya66** [comment]
Workaround: deploy the vch with --appliance-memory=4096 which bumps the appliance memory configuration.

**Comment by mdubya66** [comment]
Iceboxing for first release.

**Comment by MattAtTTU** [comment]
The documentation indicates the –appliance-memory option should only be used by support.  Will all containers deployed to the VCH share the amount of memory specified with this argument if it is used?  Will we also be restricted to only the host where the memory is being used?

**Comment by hickeng** [comment]
@MattAtTTU the `--appliance-memory` option only adjusts the memory available to the appliance, not for containers. That extra memory is _only_ used for buffering images before they're written to a vmdk (of course linux page cache may get involved, so not 100% sure what committed memory graphs will show)

docker uses `create -m=X` to specify the memory for a given container - we have not yet glued that through to the backend, so containers are themselves created with a default #1517

**Comment by MattAtTTU** [comment]
Thank you.  I can confirm that the –apliance-memory directive being used to supply more memory to the appliance is a valid workaround.  It worked without issue in our environment.

**Comment by fdawg4l** [comment]
We're currently buffering `imagec` pulls to `tmpfs` before writing them to the PL.   We want to replace this with a (buffer pool) [https://github.com/djherbis/buffer] which can use a tmpfile (if vmdk attached to the VCH) or a page of physical memory.  We need to allocate pages from this buffer pool for each pull to work with, pulling to the buffer until full, and blocking until space is made available.  The `pull` operation should pull to the buffer and push to the PL so as to keep draining the buffer.

The expectation is if the user has a high bandwidth link, and is pulling an image with size smaller than that of vch's physical memory, the `pull` will be fast.  By and large, most images fit in this criteria.  

Also, and more importantly, pulling a large image should not cause OOM.

**Comment by npakrasi** [comment]
Added to 0.7.0 release notes known issues.

**Comment by mlh78750** [comment]
Caveat that you cannot pull large images into the VCH for the .8 release. Or that you need to use the  –appliance-memory option in the VCH if you plan to use large images.

Pushing to .9.

**Comment by jzt** [comment]
Closing this as it is capture by #3624 and subsequent follow-on tasks.
