### ISSUE TITLE
Docker kill not actually killing containers

### ISSUE THREAD

**Issue by ericsmalling** [vmware/vic#2617]
**VIC Version:**

0.6.0 / build 5551 from BinTray

**Expected behavior:**
Running `docker kill` should stop the container passed

**Actual behavior:**
`docker ps` shows container still running and subsequent `docker rm` command fails as such.  The only workaround I find is to use `docker rm -f`

[logs.zip](https://github.com/vmware/vic/files/517933/logs.zip)

**Comment by ericsmalling** [comment]
example commands and output to go with attached logs:
```
$ docker --tls ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                        NAMES
f657043e1cc3        vmwarecna/nginx     "nginx -g daemon off;"   2 minutes ago       Up 2 minutes        192.168.140.103:80->80/tcp   nginx0

$ docker --tls kill nginx0
nginx0

$ docker --tls rm nginx0
Error response from daemon: You cannot remove a running container. Stop the container before attempting removal or use -f

$ docker --tls ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                        NAMES
f657043e1cc3        vmwarecna/nginx     "nginx -g daemon off;"   6 minutes ago       Up 6 minutes        192.168.140.103:80->80/tcp   nginx0

$ docker --tls kill nginx0
Error response from daemon: Cannot kill container nginx0: Server error from portlayer: [POST /containers/{id}/signal][500] containerSignalInternalServerError  &{Code:<nil> Message:ServerFaultCode: A general system error occurred: vix error codes = (1, 0).
}

$ docker --tls rm -f nginx0
nginx0

**Comment by mdubya66** [comment]
backlog for post dev complete push.

**Comment by sflxn** [comment]
I can fix this.  I know the fix.  It was on my list of todos.  We send a signal to the container, but it doesn't die.  It seems specific to nginx.

**Comment by hickeng** [comment]
@sflxn It's possible that nginx isn't correctly specifying a STOPSIGNAL or that we're not using it and nginx is ignoring SIGTERM (default).

@ericsmalling if you run `ps` after killing, is the container still running? if you kill with SIGKILL does it behave differently?

@dougm expected?

**Comment by mdubya66** [comment]
@sflxn : we can fix it once we get your todo and in progress list cleared. it has a workaround.

**Comment by sflxn** [comment]
I have the fix ready.  It will now call Stop() if signaling the container fails to kill it.  I think we may want to look at this example with nginx a little more in the future.  When I run docker kill on nginx with regular docker, it kills it immediately.  If nginx was hard to kill, the docker code seems to indicate a 10 seconds delay before the container is killed.  The fix I have is a last resort kill, but maybe this last resort attempt masks something else?
