### ISSUE TITLE
VIC allowing access to insecure registry even when it shouldn't

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2620]
1. Install VIC, using vic-machine without --docker-insecure-registry in VCH 1
2. Install docker registry in VCH 2 as an insecure registry
3. Push a docker image to the registry on VCH 2 using regular docker
4. Using VCH 1, attempt to pull the image from VCH 2 down to VCH 1

Expected:

VCH 1 should not be able to pull the image from VCH 2

Actual:

VIC is allowing VCH 1 to pull images from VCH 2

**Comment by mdubya66** [comment]
please verify

**Comment by mhagen-vmware** [comment]
Currently providing the following error:
Error response from daemon: Head https://172.17.0.1:5000/v2/: http: server gave HTTP response to HTTPS client

While less critical, that error isn't very helpful
