### ISSUE TITLE
Hide secrets from read-only API

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2630]
We need to hide appliance secrets from the read-only API, while still having them be persistent through vic-machine reconfigure operations.

The problem here is that if the API cannot see them then it cannot re-hydrate those fields in the config before doing a VM reconfigure operation. We're looking at using guestinfo.ovfEnf for hiding from the API, however we must confirm what happens if you update the Extraconfig of a VM that has a guestinfo.ovfEnv specified via API reconfigure, but without again specifying that data - if it's overwritten hen we need a more involved approach.

The alternative to embedding all secrets in one key is that we use the same model drone does and embed a private key in guestinfo.ovfEnv and use that to encrypt any secrets that are stored in a normal fashion.

**Comment by dougm** [comment]
Confirmed that guestinfo.ovfEnv survives restarts and can only be read from within the guest.

Have the basics ready: https://github.com/vmware/vic/compare/master...dougm:secrets

Will integrate once PR #2784 is merged.
