### ISSUE TITLE
Document changes to help output

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2634]
Per https://github.com/vmware/vic/issues/2633.

**Comment by hickeng** [comment]
@stuclem this is still very much WIP - please do comment if you think it's an improvement, regression, etc.
From a formatting and presentation perspective we're somewhat constrained however we should do what we can within that,

**Comment by mdubya66** [comment]
@lweitzman might want to chime in as well.

**Comment by stuclem** [comment]
The reorg of the help output (including changing some option names) is in PR https://github.com/vmware/vic/pull/2707 (not merged yet).

**Comment by stuclem** [comment]
PR #2707 is now merged.

**Comment by stuclem** [comment]
Reorganization of the options to match the basic and advanced help has been done. Writing up the TLS options is ongoing, in https://github.com/vmware/vic/issues/2217.
