### ISSUE TITLE
docker run -itd busybox dmesg hangs and truncates

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2660]
End's mid log message:
[    0.114184] TCP bind hash table entries: 16384 (order: 6, 262144 bytes)
[    0.114198] TCP: Hash tables configured (established 16384 bind 16384)
[    0.114209] UDP hash table entries: 1024 (order: 3, 32768 bytes)
[    0.114212] UDP-L

Docker, prints all and returns.

Attaching to the container just hangs, and doing a log on the container just prints the same output.  This also happens when directly attaching with run -it.

This is running on our new hardware VC cluster.

**Comment by hickeng** [comment]
@caglar10ur think this is related to the VC migration issues we were seeing in the logs yesterday?

@mhagen-vmware any chance of a log bundle?

**Comment by mhagen-vmware** [comment]
@hickeng find attached:
[container-logs.zip](https://github.com/vmware/vic/files/524822/container-logs.zip)

**Comment by mhagen-vmware** [comment]
Hmm, maybe related to #2330 ?
```
time="2016-10-12T06:40:09Z" level=debug msg="Inspecting children with status change" 
time="2016-10-12T06:40:09Z" level=debug msg="No more child processes to reap" 
time="2016-10-12T06:40:09Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/tether.(*tether).cleanup:150] main tether cleanup" 
time="2016-10-12T06:40:09Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/tether.(*tether).stopReaper:127] Shutting down child reaping" 
time="2016-10-12T06:40:09Z" level=info msg="Shutting down reaper" 
time="2016-10-12T06:40:09Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/tether.(*tether).stopReaper:127] [1.992184ms] Shutting down child reaping" 
time="2016-10-12T06:40:09Z" level=info msg="Stopping extension Attach" 
time="2016-10-12T06:40:09Z" level=debug msg="[BEGIN] [main.(*attachServerSSH).Stop:94] stop attach server" 
time="2016-10-12T06:40:09Z" level=debug msg="[BEGIN] [main.(*attachServerSSH).stop:151] stop attach server"
```

**Comment by hmahmood** [comment]
Possibly seen in: https://ci.vmware.run/vmware/vic/5688

**Comment by caglar10ur** [comment]
Could be a side effect of one of the races in the tether. Let's see whether #2702 will help or not

**Comment by caglar10ur** [comment]
closing this now that #2702, we can re-open if we observe again

**Comment by mhagen-vmware** [comment]
https://ci.vmware.run/vmware/vic/6138

**Comment by mhagen-vmware** [comment]
more truncation, not sure if it is the same issue or not

**Comment by hickeng** [comment]
@mhagen-vmware #2669 is the issue that occured in the 6138 build - there's truncation, but no hang and the log has full contents if retrieved directly without --follow.
I think#2669 should be a higher priority and we can then see if any dmesg issues occur subsequently.

**Comment by caglar10ur** [comment]
I think we identified the underlying issue with @hickeng today, we are simply powering off the vm before we finish our writes. 

Something like following should help
```
--- a/pkg/dio/writer.go
+++ b/pkg/dio/writer.go
@@ -19,6 +19,7 @@ import (
        "io"
        "os"
        "sync"
+       "sync/atomic"

        log "github.com/Sirupsen/logrus"
 )
@@ -34,7 +35,8 @@ type DynamicMultiWriter interface {
 type multiWriter struct {
        mutex sync.Mutex

-       writers []io.Writer
+       writers  []io.Writer
+       inflight int32
 }

 func (t *multiWriter) Write(p []byte) (int, error) {
@@ -55,6 +57,9 @@ func (t *multiWriter) Write(p []byte) (int, error) {
        copy(wTmp, t.writers)
        t.mutex.Unlock()

+       atomic.AddInt32(&t.inflight, 1)
+       defer atomic.AddInt32(&t.inflight, -1)
+
        eof := 0
        // possibly want to add buffering or parallelize this
        for _, w := range wTmp {
@@ -107,6 +112,10 @@ func (t *multiWriter) Close() error {
        t.mutex.Lock()
        defer t.mutex.Unlock()

+       for atomic.LoadInt32(&t.inflight) == 0 {
+               log.Debugf("Waiting inflight writes to finish")
+       }
+
        log.Debugf("[%p] Close on writers", t)
        for _, w := range t.writers {
                // squash closing of stdout/err if bound
```

**Comment by caglar10ur** [comment]
Ehehe we need to remove log.Debugf line as it creates a loop as we write tether output :)

**Comment by caglar10ur** [comment]
we need the same loop in the remove as well. Interestingly after that I started to get the output twice

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(runblock)] docker run -i busybox /bin/date
Thu Oct 27 00:39:24 UTC 2016
Thu Oct 27 00:39:24 UTC 2016
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(runblock)] docker run -i busybox uname
Linux
Linux
```

**Comment by caglar10ur** [comment]
```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(runblock)] docker run -i busybox uname 2> /dev/null
Linux
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(runblock)] docker run -i busybox uname > /dev/null
Linux
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(runblock)]
```

**Comment by caglar10ur** [comment]
Grrr, forgot to add -t (still -i alone shouldn't dump it twice but that's a different bug)

**Comment by hmahmood** [comment]
Great that you guys found this. Couple of points on the code diff above:
1. There is a busy wait; use sync.WaitGroup
2. There is still a race between Write and Close, in which if Close wins, your writes will still not go through.

**Comment by caglar10ur** [comment]
Agreed we should use sync.WaitGroup but not sure how to control the caller as in this case its exec.Cmd

**Comment by hickeng** [comment]
#2894 should be closed when this is closed - this should re-enable the ps tests

**Comment by mdubya66** [comment]
re-opening so test can be fixed
Test 1-6-Docker-Run.robot needs to be updated now that Issue #2660 has been resolved
