### ISSUE TITLE
Container wait race

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#2661]
I ran into this while running integration tests locally. exec.WaitForContainerStop will time out if the container stops while that code is executing (specifically before we subscribe to the powered off event). We do a check higher up in the stack in the ContainerWait handler, but that fails since the container is still running at that point.

**Comment by vburenin** [comment]
It seems like there a pretty significant design flaw regarding to a container status handling. It is race conditional by container status implementation. There are two ways to solve it: correct one - will impact many places related to a container status and the "hack-ish" one which I would consider as a code smell. For now I will go with the hackish one, however an appropriate TODO will be added.
