### ISSUE TITLE
vic-admin imageC.log 404

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#2668]
The introduction of ImageC as a library #2587 moved the imageC logging from it's own file to the docker personality log.  The admin currently displays a 404 for the old (now obsolete) imageC log link.

**Comment by sgairo** [comment]
@cgtexmex so to clarify, imagec log is  obsolete and should be removed, yes?

**Comment by hickeng** [comment]
@sgairo yes

**Comment by cgtexmex** [comment]
@sgairo yes..it's obsolete...apologies for the lack of clarity

**Comment by sgairo** [comment]
@cgtexmex thank you, you were clear, I just thought I should double check that I was interpreting it correctly before I went and deleted it :)
