### ISSUE TITLE
Failure in build 5688 - cross container ping

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2669]
Cross container ping test is failing. It's expecting `2 packets transmitted, 2 packets received` but the test isn't seeing it.

The tether logs shows us writing it (to both the console and the log):

```
time="2016-10-12T00:27:01Z" level=debug msg="[0xc4201a7e00] write \"64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms\\n\\n--- cross1-container ping statistics ---\\n2 packets transmitted, 2 packets received, 0% packet loss\\nround-trip min/avg/max = 0.170/0.210/0.251 ms\\n\" to 2 writers (err: <nil>)" 
```

output.xml

```
<msg timestamp="20161012 00:29:18.982" level="INFO">Running command 'docker -H 192.168.31.210:2375 network connect cross1-network2 084b85f3cbc9457ec277c16603c4441cad79e505bf8f43631f70509f7e8a6b47 2&gt;&amp;1'.</msg>
<msg timestamp="20161012 00:29:19.129" level="INFO">${rc} = 0</msg>
<msg timestamp="20161012 00:29:19.129" level="INFO">${output} = </msg>
<status status="PASS" endtime="20161012 00:29:19.129" starttime="20161012 00:29:18.979"></status>
</kw>
<kw name="Should Be Equal As Integers" library="BuiltIn">
<doc>Fails if objects are unequal after converting them to integers.</doc>
<arguments>
<arg>${rc}</arg>
<arg>0</arg>
</arguments>
<msg timestamp="20161012 00:29:19.130" level="INFO">Argument types are:
&lt;type 'int'&gt;
&lt;type 'unicode'&gt;</msg>
<status status="PASS" endtime="20161012 00:29:19.130" starttime="20161012 00:29:19.130"></status>
</kw>
<kw name="Run And Return Rc And Output" library="OperatingSystem">
<doc>Runs the given command in the system and returns the RC and output.</doc>
<arguments>
<arg>docker ${params} start ${containerID}</arg>
</arguments>
<assign>
<var>${rc}</var>
<var>${output}</var>
</assign>
<msg timestamp="20161012 00:29:19.133" level="INFO">Running command 'docker -H 192.168.31.210:2375 start 084b85f3cbc9457ec277c16603c4441cad79e505bf8f43631f70509f7e8a6b47 2&gt;&amp;1'.</msg>
<msg timestamp="20161012 00:29:30.371" level="INFO">${rc} = 0</msg>
<msg timestamp="20161012 00:29:30.371" level="INFO">${output} = 084b85f3cbc9457ec277c16603c4441cad79e505bf8f43631f70509f7e8a6b47</msg>
<status status="PASS" endtime="20161012 00:29:30.371" starttime="20161012 00:29:19.131"></status>
</kw>
<kw name="Should Be Equal As Integers" library="BuiltIn">
<doc>Fails if objects are unequal after converting them to integers.</doc>
<arguments>
<arg>${rc}</arg>
<arg>0</arg>
</arguments>
<msg timestamp="20161012 00:29:30.372" level="INFO">Argument types are:
&lt;type 'int'&gt;
&lt;type 'unicode'&gt;</msg>
<status status="PASS" endtime="20161012 00:29:30.372" starttime="20161012 00:29:30.371"></status>
</kw>
<kw name="Run And Return Rc And Output" library="OperatingSystem">
<doc>Runs the given command in the system and returns the RC and output.</doc>
<arguments>
<arg>docker ${params} logs --follow cross1-container2</arg>
</arguments>
<assign>
<var>${rc}</var>
<var>${output}</var>
</assign>
<msg timestamp="20161012 00:29:30.374" level="INFO">Running command 'docker -H 192.168.31.210:2375 logs --follow cross1-container2 2&gt;&amp;1'.</msg>
<msg timestamp="20161012 00:29:32.507" level="INFO">${rc} = 0</msg>
<msg timestamp="20161012 00:29:32.508" level="INFO">${output} = PING cross1-container (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.251 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms

--- cros</msg>
<status status="PASS" endtime="20161012 00:29:32.508" starttime="20161012 00:29:30.372"></status>
</kw>
<kw name="Should Be Equal As Integers" library="BuiltIn">
<doc>Fails if objects are unequal after converting them to integers.</doc>
<arguments>
<arg>${rc}</arg>
<arg>0</arg>
</arguments>
<msg timestamp="20161012 00:29:32.508" level="INFO">Argument types are:
&lt;type 'int'&gt;
&lt;type 'unicode'&gt;</msg>
<status status="PASS" endtime="20161012 00:29:32.508" starttime="20161012 00:29:32.508"></status>
</kw>
<kw name="Should Contain" library="BuiltIn">
<doc>Fails if ``container`` does not contain ``item`` one or more times.</doc>
<arguments>
<arg>${output}</arg>
<arg>2 packets transmitted, 2 packets received</arg>
</arguments>
<msg timestamp="20161012 00:29:32.509" level="FAIL">'PING cross1-container (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.251 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms

--- cros' does not contain '2 packets transmitted, 2 packets received'</msg>
<status status="FAIL" endtime="20161012 00:29:32.509" starttime="20161012 00:29:32.509"></status>
</kw>
<status status="FAIL" endtime="20161012 00:29:32.510" critical="yes" starttime="20161012 00:29:05.776">'PING cross1-container (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.251 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms

--- cros' does not contain '2 packets transmitted, 2 packets received'</status>
</test>
<test id="s1-s1-s9-t5" name="Connect containers to multiple networks non-overlapping">
<kw name="Run And Return Rc And Output" library="OperatingSystem">
```

@matthewavery we do not have the `output.log` file **winces** so we cannot say whether this was an issue with `logs --follow` or a data flushing problem to the datastore. We should add that back in for `debug > 2` - collecting application level state is a serious change in behaviour so shouldn't be:

```
debug==1 # increase in verbosity of logging
debug==2 # slight changes in runtime behaviour
```

@dougm @sflxn Do you know what impact the container shutting down will have on the logs command? I assume there is logic to end `logs` when the container powers off, but I don't know if we do one last call to the datastore after to ensure we got all of the data. @dougm I remember you mentioning a final attempt but not the details.

[Test-Cases.Group1-Docker-Commands.1-17-Docker-Network-Connect-VCH-5688-6570-container-logs.zip](https://github.com/vmware/vic/files/523447/Test-Cases.Group1-Docker-Commands.1-17-Docker-Network-Connect-VCH-5688-6570-container-logs.zip)

[output.zip](https://github.com/vmware/vic/files/523451/output.zip)

**Comment by hickeng** [comment]
We should be adding a test to check for the log truncation if container stops while running `--folllow`

**Comment by dougm** [comment]
Yes, we close the log followers when the container stops.  We did make a change in #2425 to allow for one more read.

**Comment by hickeng** [comment]
@caglar10ur says that there are serious issues with busybox ping - it occasionally hangs indefinitely or drops packets. This was observed with bonneville as well.

Ubuntu ping was the solution.

**Comment by anchal-agrawal** [comment]
Seen on https://ci.vmware.run/vmware/vic/6093.

**Comment by jzt** [comment]
https://ci.vmware.run/vmware/vic/6138

**Comment by hickeng** [comment]
At least part of the problem here is that dio.Writer.Close() doesn't wait for in-flight Write's to complete for all output paths before closing the underlying Writers.

This was a deliberate choice when initially writing dio as the expectation was higher level concurrency guards would be protecting against closing while a Write was still in progress.
Unfortunately exec.Cmd uses io.Copy in goroutines under the covers and does not guarantee that those have completed before Wait4 will return, so there is no avenue to provide higher level constraints.

Two possibilities:
1. don't call close - instead allow EOF to trigger close on the write path => requires a ReadFrom implementation only
2. coordinate between Close and Write to block Close from closing the underlying Writers until in-flight Write calls have completed.

**Comment by caglar10ur** [comment]
https://github.com/vmware/vic/issues/2660#issuecomment-256513239 might be 2

**Comment by jzt** [comment]
This can also be seen in the `Connect containers to multiple networks non-overlapping` and `Connect containers to multiple networks non-overlapping with a bridge container` tests.

I've disabled all three for now, pending closure of this issue.

**Comment by hickeng** [comment]
Currently investigating the os/exec package - the Cmd.Wait mechanism uses two parts to determine when to return:
1. Process.Wait()
2. range over channels for the io.Copy's for stdin/stdout/stderr

(1) causes some issues for us because there's a global Wait4 running that will harvest SIGCHILD events, (2) should still block.

It's not clear yet why calling Close on the stdin reader is causing us to lose the remainder of the inflight data - that sleeping for 5s means we get all of it suggests that it's timing related.

Questions:
1. is the reader.Close allowing us out of the blocking loop (exec.go:442), therefore processing closeAfterWait file descriptors - potentially this is purging buffered data?
2. If we don't call wait at all, do we get the output? With sleep? Without sleep?

**Comment by hickeng** [comment]
As a side note, I was unable to recreate this behaviour in the unit tests. A pipe with a bandwidth throttle may cause it to present but it's not clear that it will at this time.

**Comment by hickeng** [comment]
The current focus of the investigation is the PTY handling - it _appears_ on first glance that the Close from the process exit never causes the PTY to close it's output, and that blocks us from shutting down if we wait on it.
Of note - I've never managed to recreate the log truncation when run with just `-d` - no data yet on `-dt` or `-dit`
