### ISSUE TITLE
Document that a time skew in the VCH appliance VM breaks tlsverify

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2670]
Per https://github.com/vmware/vic/issues/2659. Deserves a troubleshooting topic,

**Comment by hickeng** [comment]
#2703 attempts to warn if clock skew may be a problem:
https://github.com/vmware/vic/pull/2703/files#diff-13cb124a8b8b2d0e7744466165fd84ffR782

**Comment by stuclem** [comment]
This is addressed in PR https://github.com/vmware/vic/pull/2703 (merged), which also checks for liveliness of the API endpoint.

**Comment by stuclem** [comment]
This depends on https://github.com/vmware/vic/issues/2678 (document `vic-machine debug`) as you need to SSH into the VCH for the workaround.

**Comment by stuclem** [comment]
I just hit this issue. The error is as follows:

```
ERRO[2016-11-03T13:09:52+02:00] Connection failed with TLS error "bad certificate" - check for clock skew on the host
INFO[2016-11-03T13:09:52+02:00] Collecting host-227 hostd.log
ERRO[2016-11-03T13:09:52+02:00] --------------------
ERRO[2016-11-03T13:09:52+02:00] vic-machine-windows.exe failed: tls: bad certificate
```

**Comment by stuclem** [comment]
Added troubleshooting topic: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/ts_clock_skew.md

We're missing the error that appears when you run Docker commands against a skewed VCH. 

@hickeng do you know what error is returned by Docker? Is the topic otherwise OK? Thanks!

**Comment by stuclem** [comment]
Leaving this one in To Do because I need further info from @hickeng.

**Comment by hickeng** [comment]
@stuclem I think with docker client you'll just get the "bad certificate" portion, maybe the "tls: " prefix as well as that's added by Go code.
I've opened #3086 to add the endpointVM system time to the vic-admin pages.

**Comment by stuclem** [comment]
Fixed in https://github.com/stuclem/vic/commit/47ab9c3fde057696e5ff0dd887445dcaa4a46fbe. Thanks @hickeng. 

Opened https://github.com/vmware/vic/issues/3094 to track the doc update for https://github.com/vmware/vic/issues/3086.
