### ISSUE TITLE
Successful UI client installation message is a bit misleading

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2672]
When you successfully deploy or upgrade the Web client plug-in for VIC Engine, you see the following message:

![ui_install](https://cloud.githubusercontent.com/assets/16718369/19306304/568f4b36-9075-11e6-8092-1f3208444b45.png)

The presence of the big message about copying the files to VC initially made me think that the deployment hadn't worked. Could we make the message a little clearer that the installation succeeded?

For example:

```
Installing plugin
Installation of UI plugin succeeded

====
NOTE: With the current version of VIC, if you have not done so already, you have to manually copy ....
etc.
====
```

By adding the words `succeeded`, `NOTE`, and `if you have not done so already`, I think that this makes it clearer that the deployment worked. @jooskim, what do you think?

**Comment by jooskim** [comment]
This makes sense to me as well. I'll make appropriate changes.

**Comment by stuclem** [comment]
@jooskim cool, thanks!

**Comment by jooskim** [comment]
@stuclem how about rephrasing `NOTE` to `NEXT STEP` so that it stands out more?

**Comment by stuclem** [comment]
@jooskim yes, I saw thart in the PR and I like it.
