### ISSUE TITLE
vicadmin: collect additional logs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2675]
I'm attempting to diagnose a problem with the volume tests in https://ci.vmware.run/vmware/vic/5693

I need the following additional logs to be able to make a proper determination of where the problem is:
1. dmesg/all the journald output
~~2. ls -l /dev/disk/*/*-~~
3. if not in (1) then the systemd-udevd unit output

It's of note that the appliance vmware.log was instrumental in determining that the hotadd had happened in a timely fashion from a hardware perspective - we really should try to keep that in the bundle - worth noting in #2164 

In the course of this I discovered the following in the log bundle should be added or fixed:
1. all file handles, not just /proc/self - no one should be leaking file handles, but...
~~2. contents of /dev/disk (not inside the entries, but all the links)~~
3. process listing (cannot actually tell if there are other unexpected processes running in there currently)
4. systemd log output (mentioned in the initial list)
5. top style snapshot for both Mem and CPU

Update: We've already got the disk-by-label and disk-by-path

**Comment by fdawg4l** [comment]
@hickeng looking at the bundle for 5693, i don't see `disk-by-label` or path.  `by-uuid` would be helpful too.
