### ISSUE TITLE
Document that TLS variables are saved in an env file

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2676]
As shown below:
![env](https://cloud.githubusercontent.com/assets/16718369/19310808/2cf68502-908c-11e6-9ee8-f67ba5222751.png)

We need to doc what this `env` file is that is created when you run `vic-machine create`.

**Comment by stuclem** [comment]
Currently, the env file just includes the address of the VCH:   `DOCKER_HOST=10.153.199.167:2376`

**Comment by hickeng** [comment]
It will also include the following if using TLS:
DOCKER_CERT_PATH

and also this if using full TLS verify (which requires either --tls-cname=... or --client-network-ip):
DOCKER_TLS_VERIFY

**Comment by stuclem** [comment]
Added info about the env file in [Obtain a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/obtain_vch.md), in the context of https://github.com/vmware/vic/issues/1877. 

**TBD**: 

- Update the verify deployment topics to mention the `env` file.
- Create a task topic in app dev about how to use the `env` file.

**Comment by stuclem** [comment]
Mentioned the `env` file in the descriptions of [--tls-cname](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--tls-cname) and [--no-tlsverify](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--no-tlsverify).

This is enough for 0.7. Moving this one back to Backlog and out of the 0.7 milestone Epic for now, pending the TBDs below. 

**TBD**: 

- Update the verify deployment topic to mention the `env` file.
- Create a task topic in app dev about how to use the `env` file. Potential title: Configure Your Docker Client for Use with vSphere Integrated Containers.

**Comment by stuclem** [comment]
Moving TLS stuff back into To Do.

**Comment by stuclem** [comment]
Done in https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/obtain_vch.md.

@hickeng @corrieb is this OK? Thanks!

**Comment by stuclem** [comment]
This review will be covered in the context of https://github.com/vmware/vic/issues/3448. Closing this one.
