### ISSUE TITLE
Document SSH access and changing root password (vic-machine debug)

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2678]
A new vic-machine debug command has appeared in build 5641.

**Comment by hickeng** [comment]
@stuclem `vic-machine debug` was added as part of #1218 - this is the mechanism by which:
1. ssh can be enabled on the endpoint VM
2. console login can be enabled
3. root password and authorized_keys can be set

**Comment by stuclem** [comment]
Ah, OK, thanks @hickeng. In that case I now have 3 issues open in relation to https://github.com/vmware/vic/issues/1218: https://github.com/vmware/vic/issues/1264, https://github.com/vmware/vic/issues/2350, and this one. Will merge them into this one and close the others as dups.

**Comment by stuclem** [comment]
See https://github.com/vmware/vic/issues/1264#issuecomment-253093183 for more info.

**Comment by stuclem** [comment]
@hickeng provides some information in https://github.com/vmware/vic/issues/2537#issuecomment-253511287.

**Comment by stuclem** [comment]
Added topics in `vic-machine debug`:

- [Authorize SSH Access to the Virtual Container Host Endpoint VM](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/vch_ssh_access.md)
- [Virtual Container Host Debug Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/debug_vch_options.md)

@hickeng, does this cover it? 
(Incidentally, I did follow your suggestion and cleared all of the common options out of the topics for delete, inspect, ls, debug, upgrade and into a common options topic. Much tidier!)
