### ISSUE TITLE
Vch toolbox returns the wrong client interface address

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#2688]
Seen here: https://ci.vmware.run/vmware/vic/5678 (test 8-1-GuestTools)

The problem seems to be that we have `client` as an alias to the `external` interface; `ip link` output on the VCH:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:a4:82:70 brd ff:ff:ff:ff:ff:ff
3: external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:a4:82:7a brd ff:ff:ff:ff:ff:ff
    alias client
```
Usually it is the opposite: external is aliased to client.

A potential fix would be to not use the Go apis to get the interface address, and use the [netlink](https://github.com/vishvananda/netlink) library.

**Comment by hickeng** [comment]
I think the correct fix here has to be not to report the client address until it's set in vic-init.
That may well need us to move this specific code into `cmd/vic-init` from `/lib/tether`

**Comment by hmahmood** [comment]
I think the address is set already; the problem may be the Go apis not finding the "client" alias.
