### ISSUE TITLE
vSphere Event filtering

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#269]
Provide the ability to filter the event stream from vSphere via govmomi.  The available filters should be:

- Event Type: i.e. com.vmware.vim.VmPoweredOnEvent
- Severity: i.e. info, warning, etc
- Event Time Frame
- User Name: vSphere user responsible for event

Ideally, the filters would be available independently and collectively -- for example  filter by event type and severity.

**Comment by dougm** [comment]
Spoke w/ Clint, this is no longer needed.
