### ISSUE TITLE
Add logic to cleanup dangling VMs that double checks that the delete succeeded

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2696]
need to go through any VMs/resources and datastore items to make sure the delete succeeded.

As an engineer of VIC, I would like to see that when we clean up dangling VMs in the CI and when we do cleanup the danglings VMs we verify that it succeeded and report when the delete did not succeed so that we know when something went wrong and we can fix it and file a bug if necessary.

**Comment by hickeng** [comment]
And raise a test failure if it didn't completely clean up.
