### ISSUE TITLE
faild to start docker container after vm enter into invalid state

### ISSUE THREAD

**Issue by emlin** [vmware/vic#2698]
Upgrade tests hit this while trying to power a VM back on.

https://ci.vmware.run/vmware/vic/5693

As this is an issue different with #1823, open a new issue here.
@hickeng @chengwang86

**Comment by hickeng** [comment]
#2021 also hits this underlying VM_STATE_INVALID_CONFIG issue.

**Comment by hmahmood** [comment]
Seen here: https://ci.vmware.run/vmware/vic/5993

**Comment by hmahmood** [comment]
See here: https://ci.vmware.run/vmware/vic/6243
