### ISSUE TITLE
Incorporating the EULA in the install workflow. 

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic#270]
We need to incorporate the appropriate EULA into the install workflow. This currently exists for the UI install, but does not exist for the CLI.

**Comment by hickeng** [comment]
@karthik-narayan For consumption from github is the EULA the same as LICENSE file? Is this even necessary if built from github?

**Comment by karthik-narayan** [comment]
Confirmed that EULA is the same as the LICENSE file.

**Comment by hickeng** [comment]
assigning to emma as milestone lead - can be reassigned to a specific individual when it moves to in progress.

**Comment by mdubya66** [comment]
Didn't this get resolved with the publishing of the license to bintray? Do we need a "accept EULA" step?

**Comment by hickeng** [comment]
@karthik-narayan can you answer whether the bintray license suffices? I've moved this out of the milestone for now as it's not critical path.

**Comment by mdubya66** [comment]
the bintray license is sufficient.

**Comment by karthik-narayan** [comment]
Agree with @mdubya66 the bintray license is sufficient.

**Comment by hickeng** [comment]
@karthik-narayan do we even have an EULA that needs agreement?
