### ISSUE TITLE
VCH how to set proxy settings ?

### ISSUE THREAD

**Issue by mldmld68** [vmware/vic#2709]
Hi,
I'm evaluating VIC. But I encounter an issue to add an app in a docker container : 

I think I need to add in a conf file of the appliance 
HTTP_PROXY='http://user:pass@myproxy.corp:port'
HTTPS_PROXY='http://user:pass@myproxy.corp:port'
But I'm unable to connect to the VCH as I don't know a user/pass and I read root password is changed on reboot.

Thank you
Best regards

**Comment by hickeng** [comment]
@mldmld68 if this is a recent build of VIC then you can run the following to enable console login until reboot with the password you specify:
```vic-machine-<os> debug --target=... --rootpw=somepassword``` 

If you also add `--enable-ssh` argument then it will start sshd until next reboot. If you'd prefer to automate, you can combine it with `--authorized-key=<file>` to set the provided file as the authorized keys for root in the applianceVM.

At the moment there is no mechanism to persistently set a proxy, but you can do so temporarily with that mechanism.

I'm going to close this as a combination of #1218 and #2537 and duplicate this comment in there. @mldmld68 Please would you post any addition proxy related comments/requests/usecases into #2537; that will help when we implement persistent support.
