### ISSUE TITLE
Advise to set the DOCKER_API_VERSION variable 

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#2711]
As part of the output of `vic-machine create` where we also show how to query the VCH (e.g. `docker -H 192.168.1.251:2375 info`) we may also need to suggest to set the `DOCKER_API_VERSION` variable as part of the output (in case you have to set that cause you have a docker client that is > api 1.23). 

If you don't set it (and you have a very recent docker client) you are going to get something similar to:

```
docker -H 192.168.1.251:2375 info
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
```

There is no obvious way for the user to know that they need to set the API_DOCKER_VERSION variable. Yes we have it in the docs but we may hint this in the create output as well IMO.

**Comment by mreferre** [comment]
I'd like to bring this up again because it keeps coming up as a setup that causes friction in the consumption. While this isn't a big deal (if you know about it!) I am starting to question about the value of explicitly exposing that the API version we honor is 1.23. 

We are not 100% compatible with that API version (due to missing stuff VIC doesn't yet implement) and at the same time we do things that a traditional docker engine does. So setting an arbitrary value seems to be 1) useless and at the same time 2) causing consumption issues. 

Shouldn't we just expose an interface version that honors the higher client interface one user could install? Yes we may not honor 1.24 (or 1.25 or 1.2x...) but VIC doesn't honor 1.23 either so..... 

Or am I missing something more profound here? 

/cc @mdubya66

**Comment by stuclem** [comment]
We do link to the topic on setting DOCKER_API_VERSION in the places in the doc where you first run Docker commands against your VCH:

- Install (for vSphere Admins): https://vmware.github.io/vic-product/assets/files/html/0.8/vic_installation/verify_vch_deployment.html
- Application devs: https://vmware.github.io/vic-product/assets/files/html/0.8/vic_app_dev/container_operations.html

I'm looking at adding the link in other places too. Probably worth including the link in every topic in App Dev in which you run Docker commands, just to make sure that people don't miss it.

**Comment by stuclem** [comment]
Adding user-doc to this issue too.

**Comment by stuclem** [comment]
@sflxn isn't this made redundant by the fact that we now support v1.25?

**Comment by hickeng** [comment]
`DOCKER_API_VERSION` functions but is not a supported variable. It doesn't do anything but lie about the API version.
