### ISSUE TITLE
VCH portlet broke because of a change in extraConfig

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#2717]
Previously `guestinfo.vice..init.networks|client.ip.IP` was used to display the VCH's Docker endpoint information as well as vicadmin portal, but the key seems to have changed. I first noticed it from Joel's report in our Gitter channel. I was able to reproduce the same problem as follows:

![image](https://cloud.githubusercontent.com/assets/3834071/19358217/b70c5984-913a-11e6-8be2-3f4a22c5e87b.png)

I also found that `guestinfo.vice..init.networks|client.ip.IP` is now called `guestinfo.vice..init.networks|client.assigned.IP`.

**Comment by jooskim** [comment]
@hmahmood Could you confirm that I could use it and that it won't change in the future?

**Comment by mdubya66** [comment]
This needs a regression test.

**Comment by jooskim** [comment]
The UI tests are not integrated yet, which I have been working on for the couple past days. If the tests were implemented this would've been caught. I'll continue to work on integrating UI tests into the nightly test suite as soon. This needs to be merged though as soon as possible. @hmahmood @emlin could you please review?
