### ISSUE TITLE
Document major vSphere features that are not supported

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2730]
Per https://github.com/vmware/vic/issues/2729. For inclusion in the interop topic once we get an answer.

**Comment by stuclem** [comment]
@hickeng confirms that SDRS is not supported in https://github.com/vmware/vic/issues/2729#issuecomment-254315049. We should probably provide a list of major features like SDRS that are not supported.

**Comment by stuclem** [comment]
Major vSphere features that are not supported:

- Storage DRS (but DRS _is_ supported)
- High Availability
- Fault Tolerance

@mhagen-vmware, should we add anything else to this list? Thanks!

**Comment by npakrasi** [comment]
Added a section in the Interop topic about features VIC does not support.

**Comment by stuclem** [comment]
Reopening as @mdubya66 might have more info that we need to add.

**Comment by stuclem** [comment]
We might have to include information of a "not supported, but works with" type nature. @mdubya66 made the following comment in https://github.com/vmware/vic/issues/2821#issuecomment-255182736 "While we don't support HA we do support deploying to systems setup with HA ..."

**Comment by npakrasi** [comment]
Added note that VIC supports deploying to systems that are set up with HA.

**Comment by stuclem** [comment]
According to @hickeng in https://github.com/vmware/vic/pull/2939#discussion_r85871552, VIC does not support vVols (aka [VMware vSphere&reg; Virtual Volumes&trade;](http://productnames.eng.vmware.com/details/VMware%20vSphere%20Virtual%20Volumes/). 

@npakrasi can you please add it to the list? Thanks!

**Comment by npakrasi** [comment]
Added vVols to the Not Supported list.

**Comment by stuclem** [comment]
Will track other unsupported features through separate issues. Closing this one.
