### ISSUE TITLE
Doc: Break up vic-machine create options file into sub-files?

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2731]
@emlin, @hickeng, @mdubya66, the [Virtual Container Host Deployment Options](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md) file is now massive. I currently have grouped the options into sections, with a jump list at the top of the topic, but am considering breaking the file up into sub-files, so as to reduce the amount of scrolling required. 

I asked @mreferre what he thought and he said that multiple sub-files will be more confusing than one massive one. So, this is a quick poll to find out what you all think. Break it up or leave it as it is?

**Comment by hickeng** [comment]
@stuclem My preference is for massive - there's nothing more frustrating than not being able to leverage `Ctrl-f` and type a fragment to jump to where you want in the help.

I think we can likely be more concise with the help.

As an example with the static IP options. 

### Static IP addresses for the Endpoint VM

The endpoint VM may be deployed with static IP addresses for any or all of it's interfaces, with DHCP being used for any interface without an IP specified. See the <link to docs> on how to configure network interfaces to determine how many distinct interfaces you have and which interface roles are sharing interfaces with others.

When providing a static IP you must also furnish a gateway address, and may supply one or more DNS server addresses. The IP is in CIDR format or a resolvable FQDN (the latter using the netmask from the gateway):
```
--client-network-ip=192.168.0.10/24 --client-network-gateway=192.168.0.254/24 --dns=172.16.10.10 --dns=172.16.10.11
```
or
```
--client-network-ip=vch27-team-a.internal.domain.com --client-network-gateway=192.168.0.254/24 --dns=172.16.10.10 --dns=172.16.10.11
```

**Comment by stuclem** [comment]
I have condensed the static IP settings as a part of https://github.com/vmware/vic/issues/2634. This issue was about breaking up the options file, so closing this one since we decided not to do that.
