### ISSUE TITLE
Imagec binary does not work outside of standalone mode

### ISSUE THREAD

**Issue by jzt** [vmware/vic#2734]
https://github.com/vmware/vic/pull/2097 introduced a bug where the imagec binary will not work outside of standalone mode.

Since image store creation now occurs during docker persona startup, running imagec directly from the binary (as opposed to having the persona launch it), outside of standalone mode, it will get a 404 from the portlayer when attempting to list images from the nonexistant image store.

We either need to move away from the binary completely, removing all imagec binary tests, or we need to add some logic in imagec to recognize when it is run outside the persona and create an imagestore if needed.

**Actual behavior:**

**Comment by hickeng** [comment]
The binary was intended as two things:
1. a complementary component to runc that we could contribute back to OCI
2. a method for testing registry interaction without the full system.

I've no issue with dropping imagec binary that directly interacts with the portlayer.
