### ISSUE TITLE
docker run -ti ubuntu doesn't receive notification that VM is already started.

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#2758]
"docker run -ti ubuntu" waits forever for VM to start even though that parallel "docker ps" shows that ubuntu container is up and running already. 
If I press "ctrl+c" it drops me into attached console session.

**Comment by vburenin** [comment]
After digging into the problem, it happened so that client didn't receive bash prompt giving an impression it just stuck.

**Comment by mdubya66** [comment]
Verified this against b5940.

```(mwilliamson) dubs:~/vic/src/github.com/vmware/vic (master)$ docker run -ti ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
6bbedd9b76a4: Pull complete
fc19d60a83f1: Pull complete
de413bb911fd: Pull complete
2879a7ad3144: Pull complete
668604fde02e: Pull complete
Digest: sha256:2d44ae143feeb36f4c898d32ed2ab2dffeb3a573d2d8928646dfc9cb7deb1315
Status: Downloaded newer image for ubuntu:latest
root@5dbc05d21271:/#
(mwilliamson) dubs:~ $ docker -H 10.17.109.147:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
c426a25d90da        ubuntu              "/bin/bash"         59 seconds ago      Up About a minute                       high_thompson
(mwilliamson) dubs:~ $ docker run -ti ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
6bbedd9b76a4: Pull complete
fc19d60a83f1: Pull complete
de413bb911fd: Pull complete
2879a7ad3144: Pull complete
668604fde02e: Pull complete
Digest: sha256:2d44ae143feeb36f4c898d32ed2ab2dffeb3a573d2d8928646dfc9cb7deb1315
Status: Downloaded newer image for ubuntu:latest
root@7f7b54cbc70d:/#```

**Comment by mdubya66** [comment]
subsequent attach also hangs
[container-logs.zip](https://github.com/vmware/vic/files/534310/container-logs.zip)
.
(mwilliamson) dubs:~ $ docker -H 10.17.109.147:2376 --tls attach c

**Comment by mdubya66** [comment]
Ooh, wait. I typed Control-C and it dropped me into the bash shell.

**Comment by hickeng** [comment]
This is an artifact of us not doing run blocking when launching with `run`. #1578

**Comment by vburenin** [comment]
I no longer see this behavior. @caglar10ur, Is it already fixed?

**Comment by mlh78750** [comment]
https://github.com/vmware/vic/pull/2874 fixed it I believe.

**Comment by caglar10ur** [comment]
yep, I think we can close it now (and re-open if we hit with it again). CLosing
