### ISSUE TITLE
appliance-memory and appliance-cpu option names are completely misleading

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2760]
We have agreed upon the following nomenclature:
- The vApp (on VC) or resource pool (on ESX) that contains the VCH and container VMs = the **VCH appliance**
- The VM inside the vApp/RP = the **VCH endpoint VM**

The `vic-machine create --memory`, `vic-machine create --cpu` and associated reservation/shares settings adjust memory/CPU settings on the vApp/RP, i.e. on the whole appliance.

The old `vic-machine create --appliance-memory` and `vic-machine create --appliance-cpu` settings adjust memory/cpu settings on the VM inside the appliance, i.e. the VCH endpoint VM.

Now that the word `pool`has been removed from the `cpu`and `memory`option names, the naming of the old options `--appliance-memory` and `--appliance-cpu` is even more misleading than it was previously.

There was talk at one point of completely removing these older options. Should we do so?

**Comment by hickeng** [comment]
@stuclem I removed the `pool` prefix because it's nonsensical unless people know both that a vApp extends a resource pool AND what the pool is used for in VIC.

We can easily change the appliance suffix to something else - suggestions welcome.

**Comment by stuclem** [comment]
@hickeng how about `--endpointvm-memory` and `--endpointvm-cpu`?

**Comment by mreferre** [comment]
I agree. I thought we settled on calling that VM the "Docker end-point VM" so the name appliance-xxx is misleading IMO.

**Comment by hickeng** [comment]
@stuclem I think the `vm` in `--endpointvm-x` is somewhat redundant and would go with `--endpoint-x` myself, but so long as it matches with the doc naming it's not a strong opinion.

**Comment by stuclem** [comment]
@hickeng I agree that the `vm` is redundant.

**Comment by mhagen-vmware** [comment]
lgtm
