### ISSUE TITLE
Document how bridge network uses DHCP

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2762]
Following a Slack chat with @andrewtchin, which is based on a real live chat that he had with @hmahmood:

Stuart Clements [4:53 PM]  
Hi Andrew, following the addition of the options to set a static IP on the external, client, and managment networks, is bridge-network still DHCP-only? Is there a technical reason for this? Thanks!

Andrew Chin [5:11 PM]  
so bridge is DHCP in the sense that the IP that the container gets is managed by default by the VCH, but you can set a static IP on the container by doing `--ip` on container create

[5:12]  
bridge network isn't "real" dhcp in that there's no server giving out addresses, we just manage the ip addrs inside the VCH

**Comment by npakrasi** [comment]
Added --ip to set a static IP in the Supported Docker Commands table.
