### ISSUE TITLE
Context deadline exceeded on CI build

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2767]
https://ci.vmware.run/vmware/vic/5951

```
ContainerWaitHandler(3a9c65336c8d107d94b96a78e589147ca5791a8de1e1db4fc474d642b2245077) Error: context deadline exceeded' cannot be converted to an integer: ValueError: invalid literal for int() with base 10: 'errorresponsefromdaemon:servererrorfromportlayer:containerwaithandler(3a9c65336c8d107d94b96a78e589147ca5791a8de1e1db4fc474d642b2245077)error:contextdeadlineexceeded'
```

**Comment by mhagen-vmware** [comment]
[integration_logs_5951_da17da842e71a09f12c97980e158f8ec77152db3.zip](https://github.com/vmware/vic/files/534713/integration_logs_5951_da17da842e71a09f12c97980e158f8ec77152db3.zip)

**Comment by matthewavery** [comment]
This appears to be some sort of issue with `ContainerWait`. From the logs the volume was added properly and the actualy container seems to have executed properly. Additionally, some of the container logs the target container appear to be missing making it hard to tell exactly what happened directly on the container.

**Comment by matthewavery** [comment]
Marking as no repro, after several attempts to do so. I will be adding more logging and referencing this ticket in the PR.

**Comment by matthewavery** [comment]
Closing this. pr #2949 added additional logging to help us determine what causes these kinds of errors in the future. Additionally We have not seen one like this for a little while and it is possible that it has been fixed. We should definitely reopen this ticket if we seen a context deadline exceeded from the build again, along with the updated logs that go along with that failure.
