### ISSUE TITLE
Documentation: Restructure docs on github.io to allow for multiple concurrent releases

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2792]
Currently, each time we tag a release on Github, we publish a version of the doc on https://vmware.github.io/vic/ that reflects that tagged release. At the moment, the doc for each new tagged release overwrites the doc for the previous tagged release. So, there is only ever one version of the doc on https://vmware.github.io/vic/ at a time, that has a version number that matches the latest tagged release hard-coded into the doc. As such, the MD doc files in the Github repo reflect more recent builds than the HTML/PDF docs on  https://vmware.github.io/vic/. Which is exactly what we need currently.

But, since we are also going to use https://vmware.github.io/vic/ as the publication channel for the official GA docs, we are going to have to start including multiple versions of the doc on https://vmware.github.io/vic/. For example, there will come a point when the latest tagged open-source release is more recent than the latest official release. Namely, we will tag new releases in Github after we have officially released the GA, but we won’t release these new tagged versions officially. We also need to keep an archive of the docs for each official release for customers who don't upgrade to newer official versions straightaway. 

I propose the following:
- Publish the docs for the latest tagged Github releases under https://vmware.github.io/vic/assets/files/user_doc/latest/. Each version of the doc in here will reflect the latest tagged release and will overwrite the previous version. As such, URLs will remain valid when we release new tagged releases on Github/bintray.
- Publish the docs for official releases under https://vmware.github.io/vic/assets/files/user_doc/_version_number_/. There will be one such folder for each official release. 

This problem will go away once we find a way of migrating the MD docs into the official VMware doc publication mechanism, but in the immediate future this is how we will have to handle things. It does mean that we're going to have to break a lot of existing links, which presumably will affect @mreferre and @karthik-narayan.

**Comment by stuclem** [comment]
A further idea would be to publish the docs for official releases at https://vmware.github.io/vic_product/ and continue to publish the docs for tagged releases on https://vmware.github.io/vic/. 

@karthik-narayan and @mreferre, how hideously confusing would that be?

**Comment by mreferre** [comment]
I wouldn't start mixing vic-engine stuff with vic-product stuff. I suggest vic-engine related publications should stay in https://vmware.github.io/vic/. Your original idea LGTM.

**Comment by stuclem** [comment]
OK, thanks @mreferre. I'll start on the reorg after 0.7.

**Comment by karthik-narayan** [comment]
Agree with Massimo. In the future we could have folks using just the engine.

**Comment by stuclem** [comment]
@karthik-narayan, @mreferre, @corrieb, @mlh78750, what do you think of the proposal above? In short, continue to maintain the VIC Engine Markdown files (along with the small amount of Harbor doc) in `/vic`, but publish the generated HTML/PDF via `/vic-product`.

**Comment by stuclem** [comment]
Not required for 0.7, so moving back to backlog.

**Comment by mreferre** [comment]
It's fine as long as this is the GO-TO place for VIC documentation. if we will have to publish documentation on vmware.com as well then it becomes a bit of an overkill to maintain docs in their own repos and consolidating them in two places. My 2 cents.

**Comment by stuclem** [comment]
@mreferre yes - this will be the one and only go-to place for doc. If we publish the doc under https://vmware.github.io/vic-product then I will remove it from https://vmware.github.io/vic/. We will not publish a duplicate doc on vmware.com for this release.

**Comment by karthik-narayan** [comment]
That sounds like a plan as long as we add a link to the other two repo's and point it to vic-product.

**Comment by stuclem** [comment]
@karthik-narayan, absolutely!

**Comment by stuclem** [comment]
In preparation for publishing the docs for 0.8 RC 2, I have done the following on github.io (note that all URLs include stuclem.github.io, not vmware.github.io, as the changes are currently only in my fork rather than on master): 

- Uploaded the HTML and PDF docs to https://stuclem.github.io/vic-product/index.html#getting-started. Note that is this is the VIC Product site on github.io, not the VIC Engine site, which is where the docs have been hosted until now.
- Included `/0.8` in the URLs to the docs, in preparation for being able to publish multiple versions of the docs, i.e. keep the 0.8 docs online after we publish 0.9. For example, https://stuclem.github.io/vic-product/assets/files/html/0.8/vic_installation/index.html.
- Removed the doc links from https://stuclem.github.io/vic/index.html#getting-started and added a link to the new docs on the VIC Product site.
- In case anyone has bookmarked any of the HTML files on the VIC Engine page, I have inserted redirects into each HTML file to send people to the doc section of the VIC Product page. For example, https://stuclem.github.io/vic/assets/files/html/vic_installation/vch_installer_options.html.
- Because github.io doesn't support directory-level redirects (at least not without a lot of faff), replaced the PDFs on the VIC Engine site with a one-line PDF that includes a link to the VIC Product site. For example, https://stuclem.github.io/vic/assets/files/pdf/vic_installation.pdf.

When we release 0.9 to bintray, I'll add a `/latest` directory alongside the `/0.8` directory. Docs for all OSS releases will go into `/latest`, so that for example, docs for 0.9 will overwrite 0.8, , 0.10 will overwrite 0.9, and so on. Official VMware releases will live forever in `/0.8`, `/1.0`, etc., until such time as we can find a way to convert our MD source files into something that the usual VMware doc publication mechanism can handle.

@karthik-narayan, @mreferre, @mdubya66, @corrieb, @mlh78750 does this arrangement look OK for 0.8 GA? I personally find the PDF redirects a bit amateurish, but they are better than a broken link or (worse) a link to an out-dated doc.

**Comment by stuclem** [comment]
These changes are now live. 

- VIC Product page, with working doc links: https://vmware.github.io/vic-product/ 
- VIC Engine page, with links to VIC Product https://vmware.github.io/vic/
- Example of old HTML doc page on VIC Engine site, with redirect to VIC Product: https://vmware.github.io/vic/assets/files/html/vic_installation/vch_installer_options.html
- Example of old PDF file, with link to VIC Product: https://vmware.github.io/vic/assets/files/pdf/vic_installation.pdf

**Comment by stuclem** [comment]
This reorg was discussed extensive by email. Closing.
