### ISSUE TITLE
Inconsistent naming of VIC Admin between vic-machine and UI plug-in

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2804]
We currently use two completely different names for VIC Admin:
- The output of `vic-machine create` refers to the `vic-admin portal`.
- The Virtual Container Host portlet in the UI plug-in refers to `Docker log`.

The names used in both places should be consistent. Furthermore, trademarking rules dictate that we should avoid using the VIC acronym in customer-visible text wherever possible. 

So, could we use "VCH Admin Portal" throughout? I think that this reflects the purpose of the portal more accurately than "VIC Admin" and avoids abbreviating the product name.

**Comment by mdubya66** [comment]
To file a new bug against the portlet.

**Comment by mdubya66** [comment]
need to get input from @karthik-narayan on what to call it. Current vote is VCH Admin

**Comment by stuclem** [comment]
Filed https://github.com/vmware/vic/issues/2806 for the UI update.

**Comment by karthik-narayan** [comment]
Agree with @mdubya66 "VCH Admin Portal" works.

**Comment by stuclem** [comment]
Updated doc to use "VCH Admin Portal" throughout.
