### ISSUE TITLE
vicadmin fails to return data if connection to vsphere fails

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2811]
If the [session.Connect call](https://github.com/vmware/vic/blob/master/cmd/vicadmin/vicadm.go#L391) fails then the Validator [created here](https://github.com/vmware/vic/blob/master/cmd/vicadmin/server.go#L272) is invalid (the session is nil) and there are multiple panics.

If altering [the creation of the validator](https://github.com/vmware/vic/blob/master/lib/vicadmin/validate.go#L80) to check for validity of the session and return `nil, fmt.Errorf("invalid session")` then nothing is rendered.

This failure to connect could be:
- incorrect thumbprint
- network outage
- firewall config issue
- vsphere credentials have changed
- ... (multitude of options)

Adding this to the backlog for GA as it significantly impacts our ability to diagnose some of the most common connectivity issues.

**Comment by mlh78750** [comment]
Logs from #3082 
[logs.zip](https://github.com/vmware/vic/files/584611/logs.zip)

The reproduce steps is to configure a VCH and ensure it can't reach the VC.

**Comment by anchal-agrawal** [comment]
Thanks @mlh78750! I've root-caused the panic and can confirm that #3106 resolves this.
