### ISSUE TITLE
Bad error message on vic-machine delete command.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#2813]
build 5368.

$ ./vic-machine-darwin delete --target 10.162.29.163  --name virtual-container-host --user Administrator@vsphere.local --password 'Admin!23'  --compute-resource /ha-dc/host/10.192.97.2/Resources
INFO[2016-10-19T16:58:10-05:00] ### Removing VCH ####
INFO[2016-10-19T16:58:15-05:00]
INFO[2016-10-19T16:58:15-05:00] VCH ID: VirtualMachine:vm-89
ERRO[2016-10-19T16:58:15-05:00] --------------------
ERRO[2016-10-19T16:58:15-05:00] vic-machine-darwin failed: runtime error: index out of range

**Comment by mlh78750** [comment]
possibly caused by vic-machine being a different version than what was installed.

**Comment by mdubya66** [comment]
See #2719

**Comment by emlin** [comment]
Fixedd by #2719 and verified with latest version
