### ISSUE TITLE
Trying to run two busybox on one VCH and second does not attach

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#2815]
Build 6035

ran "docker -H 10.192.98.93:2376 --tls run -ti busybox" three times. First one connected second two did not.

[container-logs (1).zip](https://github.com/vmware/vic/files/540453/container-logs.1.zip)

**Comment by mlh78750** [comment]
This was on recent 6.5 release using VC and one ESX.

**Comment by mdubya66** [comment]
I couldn't reproduce this on 6.5 ESXi RC1 and VIC b6035.

[container-logs (1).zip](https://github.com/vmware/vic/files/540495/container-logs.1.zip)

**Comment by mlh78750** [comment]
Cannot reproduce with VIC 6085 and ESX build 4531672 and vc 4531673.

**Comment by mlh78750** [comment]
Closing as not reproducible.
