### ISSUE TITLE
Error message mentions HA when we don't support HA

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2821]
Deploying a VCH to a cluster when only one host can access the designated datastores results in the error:

`Only one host can access all of the image/container/volume datastores. This may be a point of contention/performance degradation and HA/DRS may not work as intended. `

The milestone for HA support (https://github.com/vmware/vic/issues/744) went into the Icebox, so we don't actually support HA in this release. We should probably remove `HA `from the error message.

**Comment by mdubya66** [comment]
While we don't support HA we do support deploying to systems setup with HA and this warning should be heeded. I'm going to close this as will not fix.

**Comment by stuclem** [comment]
@mdubya66 good to know. Will update our interop docs accordingly. Thanks!
