### ISSUE TITLE
docker run busybox date fails

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2827]
On ESX it gives a context deadline exceeded, on VC it returns quickly but doesn't print the date.

```
docker -H 192.168.254.164:2375 run busybox date
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
56bec22e3559: Pull complete 
a3ed95caeb02: Extracting     32 B/32 B
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
a3ed95caeb02: Pull complete 
Status: Downloaded newer image for library/busybox:latest
Error response from daemon: Server error from portlayer: ContainerWaitHandler(fe674a49c95b2d628c786546ca016433077f8608b649ef221b8770b232f9be0b) Error: context deadline exceeded
```

[container-logs.zip](https://github.com/vmware/vic/files/542451/container-logs.zip)

**Comment by mhagen-vmware** [comment]
Running multiple times on ESX, it doesn't give context deadline exceeded every time, but still doesn't print the date.

**Comment by mhagen-vmware** [comment]
dmesg and ls also have this issue.

**Comment by anchal-agrawal** [comment]
I can repro this locally. We don't get the output of short-lived commands on the container.

However, I did a `run busybox ls` and the container's `output.log` file on the ESX host has the output:

```
$ cat output.log 
bin
dev
etc
home
lib
lost+found
mnt
proc
root
run
sbin
sys
tmp
usr
var
```

Looks like we're not capturing stdout correctly for short-lived commands during a `run`.

**Comment by anchal-agrawal** [comment]
Closing as dup of #1578 per conversation with @caglar10ur.
