### ISSUE TITLE
Disable TLS 1.0 in any 6.5 vsphere testing

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2831]
In the "Advanced settings" pane on the right edit the "UserVars.ESXiVPsDisabledProtocols" option value and set it to "sslv3,tlsv1,tlsv1.1"

**Comment by rwkjones** [comment]
I've just spent three hours wrestling with the VMWare documentation on this, only to find your one line instruction that does the job. Thank you very much indeed!
