### ISSUE TITLE
Cannot pull images after restart of VCH vApp.

### ISSUE THREAD

**Issue by smaithani** [vmware/vic#2833]
Cannot pull images after restart of VCH vApp.

During my testing the host PSOD'ed and I had to reboot to get it up and running. The VCH (viz. VCH2) was powered off and I powered it on.
The vApp and the VMs under it came up fine. But pull is failing:

> > DOCKER_HOST=tcp://10.192.89.44:2375 
> > docker pull busybox 
> > Using default tag: latest
> > Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
> > Cannot connect to the Docker daemon. Is the docker daemon running on this host?

I deploy a new VCH, which seems to be working fine.
[container-logs.zip](https://github.com/vmware/vic/files/542911/container-logs.zip)

**Comment by mdubya66** [comment]
@jzt @hmahmood please take a look

**Comment by hmahmood** [comment]
The port layer server is failing to start, and vic-init is restarting it infinitely. From port-layer.log:
```
time="2016-10-20T20:55:52Z" level=debug msg="Error count populating vSphere cache: (2)" 
time="2016-10-20T20:55:52Z" level=fatal msg="configure_port_layer ERROR: Failure finding cluster (/vcqaDC/host/New Cluster2): compute resource '/vcqaDC/host/New Cluster2' not found\nFailure finding pool (/vcqaDC/host/New Cluster2/Resources): resource pool '/vcqaDC/host/New Cluster2/Resources' not found" 
```

**Comment by hickeng** [comment]
#3490 could be a possibility, but looks like we're using the paths not the morefs.
