### ISSUE TITLE
Can't run docker container or pull new images: Message:NotAuthenticated

### ISSUE THREAD

**Issue by smaithani** [vmware/vic#2835]
Could be some issue with configuration. But this was working for me like 5 mins ago.

> > docker -H 10.192.89.142 pull redis
> > Using default tag: latest
> > Pulling from library/redis
> > 6a5a5368e0c2: Extracting [==================================================>] 51.35 MB/51.35 MB
> > a3ed95caeb02: Download complete 
> > 2f1103ce5ca9: Download complete 
> > 086a40c85e01: Download complete 
> > 9a5e9d112ec4: Download complete 
> > dadc4b601bb4: Download complete 
> > b8066982e7a1: Download complete 
> > 2bcdfa1b63bf: Download complete 
> > Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc420ef7858 Message:NotAuthenticated}
> > 
> > docker  -H 10.192.89.142 run -it --name buz6  busybox
> > docker: Error response from daemon: Server error from portlayer: [POST /scopes/{scope}/containers][500] addContainerInternalServerError  &{Code:<nil> Message:NotAuthenticated}.
> > See 'docker run --help'.

The host has just one nic
[container-logs.zip](https://github.com/vmware/vic/files/542959/container-logs.zip)
![screen shot 2016-10-20 at 2 32 15 pm](https://cloud.githubusercontent.com/assets/22692494/19578857/86c359d8-96d2-11e6-968c-348532581767.png)

**Comment by mdubya66** [comment]
@jzt please take a look

**Comment by anchal-agrawal** [comment]
Possibly related to #2305 as @smaithani's vic-admin page showed a possible license issue:

<img width="493" alt="screen shot 2016-10-20 at 16 24 17" src="https://cloud.githubusercontent.com/assets/4361620/19583475/ba44688a-9702-11e6-92a5-bc4238e6f3dd.png">

**Comment by hmahmood** [comment]
```
time="2016-10-20T21:24:48Z" level=error msg="Error uploading 4220fb6c-7618-e2c6-9025-b6dd2fe8f9c1/parentMap.tmp: NotAuthenticated" 
time="2016-10-20T21:24:48Z" level=error msg="ImageCache error: WriteImage of d0c4f1eb7dc8f4dae2b45fe5c0cf4cfc70e5be85d933f5f5f4deb59f134fb520 failed with: NotAuthenticated" 
```

**Comment by hmahmood** [comment]
Uploads to the datastore are failing. Are the credentials passed to vic-machine (via `--user` and `--password`) valid for the `--image-store` passed in?

**Comment by chengwang86** [comment]
Update:

Before "docker pull redis", Sundeep did a snapshot for a containerVM created before. However, I couldn't reproduce this issue by doing a snapshot. This "NotAuthenticated" msg may not be related to "snapshot".

Instead, I find that govmomi keeps a session with vSphere which may expire if disconnected for long enough time. "Re-authentication" is needed the next time govmomi sets up a connection with vSphere. If not "re-auth", the error of "Not Authenticated" may be thrown. 

It is possible that Sundeep's vCenter was heavily loaded or not responsive for a while, and the govmomi session was corrupted or the connection was down.

I plan to add "re-auth" if govmomi connection returns with "Not Authenticated".

**Comment by chengwang86** [comment]
This comment from another issue seems related:

https://github.com/vmware/vic/issues/1878#issuecomment-244170456

**Comment by chengwang86** [comment]
Here is the work flow to reproduce the problem:

1. on VC, start a VCH
2. reboot the VC
3. docker pull/create/run (any operation that needs to communicate with vSphere would fail with the same error msg of "NotAuthenticated").

Although Sundeep didn't mention if there was a downtime for his VC, so far this is the only way I can reproduce the problem.
