### ISSUE TITLE
Need to update registry workflow doc to use Harbor

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#2846]
https://github.com/vmware/vic/blob/master/doc/application_workflow/private_registry.md

needs to be updated to use Harbor as the primary example for this type of workflow.

**Comment by sflxn** [comment]
This has been resolved with https://github.com/vmware/vic/pull/3225.  Docs for using Harbor with VIC Engine is in <vic>/doc/application_workflow/harbor_registry/
