### ISSUE TITLE
Cannot remove a container after "snapshot"

### ISSUE THREAD

**Issue by smaithani** [vmware/vic#2850]
> > docker -H 10.161.6.241  rm buz8  -f
> > Error response from daemon: Server error from portlayer: [DELETE /containers/{id}][500] containerRemoveInternalServerError

The VCH seems to be fine:

> > docker -H 10.161.6.241  info
> > Containers: 1
> >  Running: 0
> >  Paused: 0
> >  Stopped: 1
> > Images: 1
> > Server Version: v0.6.0-6020-2988a94
> > Storage Driver: vSphere Integrated Containers v0.6.0-6020-2988a94 Backend Engine
> > VolumeStores: 
> > vSphere Integrated Containers v0.6.0-6020-2988a94 Backend Engine: RUNNING
> >  VCH mhz limit: 6216 Mhz
> >  VCH memory limit: 10.63 GiB
> >  VMware Product: VMware vCenter Server
> >  VMware OS: linux-x64
> >  VMware OS version: 6.5.0
> > Plugins:
> >  Volume: 
> >  Network: bridge
> > Swarm: 
> >  NodeID: 
> >  Is Manager: false
> >  Node Address: 
> > Security Options:
> > Operating System: linux-x64
> > OSType: linux-x64
> > Architecture: x86_64
> > CPUs: 6216
> > Total Memory: 10.63 GiB
> > Name: VCH1
> > ID: vSphere Integrated Containers
> > Docker Root Dir: 
> > Debug Mode (client): false
> > Debug Mode (server): false
> > Registry: registry-1.docker.io

Vm console of the container shows  some errors:
![screen shot 2016-10-21 at 12 49 10 pm](https://cloud.githubusercontent.com/assets/22692494/19609572/cc82e546-978c-11e6-9355-167a5b895c9f.png)

![screen shot 2016-10-21 at 12 50 09 pm](https://cloud.githubusercontent.com/assets/22692494/19609596/ef9e678a-978c-11e6-9c9f-e7d269fc05d7.png)

[container-logs.zip](https://github.com/vmware/vic/files/545089/container-logs.zip)

**Comment by anchal-agrawal** [comment]
@smaithani What was the `create`/`run` command for this container? Also, please redact your docker endpoint for security.

**Comment by anchal-agrawal** [comment]
From `docker-personality.log`:

```
time="2016-10-21T19:36:27Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm:378] buz8" 
time="2016-10-21T19:36:27Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm:378] [949.583721ms] buz8" 

...

time="2016-10-21T19:46:41Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm:378] buz8" 
time="2016-10-21T19:46:42Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm:378] [725.267442ms] buz8" 
time="2016-10-21T19:46:42Z" level=error msg="Handler for DELETE /v1.23/containers/buz8 returned error: Server error from portlayer: [DELETE /containers/{id}][500] containerRemoveInternalServerError " 
time="2016-10-21T19:46:53Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm:378] buz8" 
time="2016-10-21T19:46:53Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm:378] [541.125407ms] buz8" 
time="2016-10-21T19:46:53Z" level=error msg="Handler for DELETE /v1.23/containers/buz8 returned error: Server error from portlayer: [DELETE /containers/{id}][500] containerRemoveInternalServerError "
```

Looks like `buz8` was `rm`'d successfully before, however, subsequent `rm buz8` commands should have returned a `No such container` error instead of `containerRemoveInternalServerError`.

**Comment by anchal-agrawal** [comment]
I can repro this on @smaithani's VCH.

```
$ sudo docker -H <host> ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
570b2f085494        busybox             "sh"                About an hour ago   Created                                 buz8
$ sudo docker -H <host> rm buz8
Error response from daemon: Server error from portlayer: [DELETE /containers/{id}][500] containerRemoveInternalServerError
$ sudo docker -H <host> rm -f buz8
Error response from daemon: Server error from portlayer: [DELETE /containers/{id}][500] containerRemoveInternalServerError
```

PL logs for the rm commands:

```
time="2016-10-21T20:59:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:233] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e" 
time="2016-10-21T20:59:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).refresh:237] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e" 
time="2016-10-21T20:59:26Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).refresh:237] [51.663252ms] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e" 
time="2016-10-21T20:59:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Remove:641] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e" 
time="2016-10-21T20:59:26Z" level=debug msg="Setting container 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e state: Removing" 
time="2016-10-21T20:59:27Z" level=error msg="task failed: The attempted operation cannot be performed in the current state (Powered on)." 
time="2016-10-21T20:59:27Z" level=debug msg="Fault while attempting to destroy vm: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:\"poweredOff\", ExistingState:\"poweredOn\"}" 
time="2016-10-21T20:59:27Z" level=debug msg="Setting container 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e state: Created" 
time="2016-10-21T20:59:27Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Remove:641] [679.665391ms] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e" 

...

time="2016-10-21T21:01:27Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Remove:641] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e" 
time="2016-10-21T21:01:27Z" level=debug msg="Setting container 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e state: Removing" 
time="2016-10-21T21:01:28Z" level=error msg="task failed: The attempted operation cannot be performed in the current state (Powered on)." 
time="2016-10-21T21:01:28Z" level=debug msg="Fault while attempting to destroy vm: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:\"poweredOff\", ExistingState:\"poweredOn\"}" 
time="2016-10-21T21:01:28Z" level=debug msg="Setting container 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e state: Created" 
time="2016-10-21T21:01:28Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Remove:641] [728.600066ms] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e" 
time="2016-10-21T21:01:28Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:233] [752.197246ms] 570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e"
```

**Comment by chengwang86** [comment]
This seems related to #1823 with the same error msg.

However, the hostd log corresponding to when the error happens is missing. So I couldn't tell if it is due to invalid state or something else. If it is in "invalid state", maybe Emma's ongoing workaround could fix it.

**Comment by chengwang86** [comment]
Duplicate of #1823 .

**Comment by hickeng** [comment]
This may look the same as #1823 but I think the original cause is different. I see container `570b2f0854946b10481df626ae34050acb3744b78a34e17255547a00a9defe7e` being created but no evidence of it being started by VIC.

Of particular note I also do __not__ see an event about an out-of-band power-on, yet vSphere reports it as being powered on when we try to power it on via the VCH.

I see no evidence of it being powered __off__ before attempting to remove it, which I would expect to fail as it is.

I would like to know what the sequence of operations was that resulted in this state because we **should** be able to handle out-of-band power on.

**Comment by chengwang86** [comment]
@smaithani could you please tell us the exact sequence of operation for this VM?

**Comment by chengwang86** [comment]
Update: @hickeng @mdubya66 

According to @smaithani , this is the sequence of operations that causes this issue:

- docker create -it busybox
- docker start container_id
- "snapshot"
- docker rm -f container_id

This issue can always be reproduced by the above operations. Even if I do "docker stop" after "snapshot", and "docker stop" returns w/o error msg (no error from portlayer or docker-personality logs), the subsequent "docker rm" still fails.

**Comment by chengwang86** [comment]
This relates to #2900

**Comment by mdubya66** [comment]
see the conversation in #2856

**Comment by mdubya66** [comment]
@mlh78750 @fdawg4l this one seems related to #2856 too. Should we consider moving it out of the way given the decision to disable snapshots and resolve with the bigger fix?

**Comment by fdawg4l** [comment]
I think its a DUP and we have enough information in 2856.  I'll close this and we can work on 2856 to address the short term fix.

**Comment by chengwang86** [comment]
@fdawg4l  Although we still don't know the root cause, a workaround might be just removing the containerVM from disk from the vSphere Web UI.

**Comment by fdawg4l** [comment]
@chengwang86 can you confirm that works? I suspect it wont but have not tried it.  Also its likely the vch will need to be restarted if it does work.

**Comment by chengwang86** [comment]
@fdawg4l I tried it three times, and I can always delete them from the web ui. Then a follow-up "docker ps -a" shows that these containerVMs have been removed. 

My flow is: create->start->snapshot->stop->rm

**Comment by fdawg4l** [comment]
Right, but can you try creating a new container with the same image after you deleted the first container?

```
docker run busybox /bin/top
# snapshot vm
docker rm

# then do it again
```

**Comment by chengwang86** [comment]
@fdawg4l After the first "docker rm", I see the error msg of "Error response from daemon: Server error from portlayer: [DELETE /containers/{id}][500] containerRemoveInternalServerError".

Then I repeat your operations; I can run the container with the same image but still see the same error msg. 

Albeit the err msg, it seems that the containerVM is already "stopped" and "powered off" from the web ui, and I can still "remove from disk"

**Comment by fdawg4l** [comment]
Odd.  But this works for you?

> My flow is: create->start->snapshot->stop->rm

Can you do that if it does but do it twice?  The second create will likely fail.

**Comment by mlh78750** [comment]
See #2928.

**Comment by chengwang86** [comment]
No, the second one didn't fail. Here is my flow:
docker create -it busybox
docker start ...
snapshot
docker stop ...
docker rm ... (err msg)

docker create -it busybox
docker start ...
docker stop ...

**Comment by mdubya66** [comment]
The plan is to document that doing out of band operations on containers like snapshot and delete is problematic.

**Comment by stuclem** [comment]
The doc update is handled by https://github.com/vmware/vic/issues/2886.

**Comment by mhagen-vmware** [comment]
Can we close this as the doc issue is being tracked elsewhere or is there more to do here?

**Comment by smaithani** [comment]
Sure, thanks for taking care of this
