### ISSUE TITLE
If VCH creations fails for some reason we should delete the vApp

### ISSUE THREAD

**Issue by smaithani** [vmware/vic#2853]
The user tester does not have permissions to modify networks. When I use this user to create a VCH, the creation fails but leaves behind a vApp. 

./vic-machine-darwin create --name VCH2 --target x.x.x.x --user tester@vsphere.local --password 'Admin!23'  --force --image-store local-0  --bridge-network DPortGroup --no-tls --compute-resource cls
WARN[2016-10-21T15:13:51-07:00] Configuring without TLS - all communications will be insecure 
INFO[2016-10-21T15:13:51-07:00] ### Installing VCH ####  
INFO[2016-10-21T15:13:51-07:00] Validating supplied configuration  
INFO[2016-10-21T15:13:51-07:00] vDS configuration OK on "DPortGroup"  
INFO[2016-10-21T15:13:51-07:00] Firewall status: DISABLED on "/vcqaDC/host/cls/sc-rdops-vm09-dhcp-3-202.eng.vmware.com" 
WARN[2016-10-21T15:13:51-07:00] Firewall configuration will be incorrect if firewall is reenabled on hosts: 
WARN[2016-10-21T15:13:51-07:00]   "/vcqaDC/host/cls/sc-rdops-vm09-dhcp-3-202.eng.vmware.com" 
WARN[2016-10-21T15:13:51-07:00] Firewall must permit 2377/tcp outbound if firewall is reenabled 
INFO[2016-10-21T15:13:52-07:00] License check OK on hosts:  
INFO[2016-10-21T15:13:52-07:00]   "/vcqaDC/host/cls/sc-rdops-vm09-dhcp-3-202.eng.vmware.com" 
INFO[2016-10-21T15:13:52-07:00] DRS check OK on:  
INFO[2016-10-21T15:13:52-07:00]   "/vcqaDC/host/cls/Resources"  
WARN[2016-10-21T15:13:52-07:00] Only one host can access all of the image/container/volume datastores. This may be a point of contention/performance degradation and HA/DRS may not work as intended. 
INFO[2016-10-21T15:13:52-07:00]  
WARN[2016-10-21T15:13:52-07:00] Disabling 4fe81e67-e624-40e0-95b0-a60b977b9fd0 vpxd.log collection (ServerFaultCode: Permission to perform this operation was denied.) 
WARN[2016-10-21T15:13:52-07:00] Disabling host-14 hostd.log collection (ServerFaultCode: Permission to perform this operation was denied.) 
INFO[2016-10-21T15:13:52-07:00] Creating virtual app "VCH2"  
INFO[2016-10-21T15:13:52-07:00] Creating appliance on target  
INFO[2016-10-21T15:13:52-07:00] Network role "client" is sharing NIC with "external" 
INFO[2016-10-21T15:13:52-07:00] Network role "management" is sharing NIC with "external" 
ERRO[2016-10-21T15:13:52-07:00] task failed: ServerFaultCode: Permission to perform this operation was denied. 
ERRO[2016-10-21T15:13:52-07:00] Unable to create appliance VM: ServerFaultCode: Permission to perform this operation was denied. 
ERRO[2016-10-21T15:13:52-07:00] --------------------  
ERRO[2016-10-21T15:13:52-07:00] vic-machine-darwin failed: Creating the appliance failed with ServerFaultCode: Permission to perform this operation was denied.. Exiting...

**Comment by mdubya66** [comment]
@hickeng I believe the idea to remove the vApp was looked at and we determined to leave it. Can you confirm.

**Comment by mdubya66** [comment]
Iceboxing this for post GA

**Comment by npakrasi** [comment]
Added to 0.7.0 release notes known issues.

**Comment by hickeng** [comment]
@smaithani I'm not seeing any evidence that the vApp was actually created - in fact it looks as though it was not given the errors.

**Comment by smaithani** [comment]
The vApp does get created, I checked from UI

**Comment by mdubya66** [comment]
Closing as CNR.
