### ISSUE TITLE
Cannot run a container instance after out of band vSphere ops (snapshot/delete)

### ISSUE THREAD

**Issue by smaithani** [vmware/vic#2856]
I am not able to run a container instance:

> > docker -H x.x.x.x  run -it --name buz2  busybox
> > Unable to find image 'busybox:latest' locally
> > Pulling from library/busybox
> > 56bec22e3559: Already exists 
> > a3ed95caeb02: Already exists 
> > Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
> > Status: Image is up to date for library/busybox:latest
> > docker: Error: No such image: busybox.
> > See 'docker run --help'.
> > 
> > docker -H x.x.x.x pull busybox
> > Using default tag: latest
> > Pulling from library/busybox
> > 56bec22e3559: Already exists 
> > a3ed95caeb02: Already exists 
> > Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
> > Status: Image is up to date for library/busybox:latest
> > 
> > docker -H x.x.x.x  run -it --name buz2  busybox
> > Unable to find image 'busybox:latest' locally
> > Pulling from library/busybox
> > 56bec22e3559: Already exists 
> > a3ed95caeb02: Already exists 
> > Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
> > Status: Image is up to date for library/busybox:latest
> > docker: Error: No such image: busybox.
> > See 'docker run --help'.

The VCH was created by:
./vic-machine-darwin create --name VCH2 --target x.x.x.x --insecure-registry 10.139.23.226:80  --user tester@vsphere.local --password 'Admin!23'  --force --image-store sharedVmfs-1  --bridge-network DPortGroup --no-tls --compute-resource cls

I was able to run busybox once. But after that this issue started showing up. Each time there is an attempt to create a container VM, I can see "Invalid configuration for device '1'." on VC UI

[container-logs.zip](https://github.com/vmware/vic/files/545404/container-logs.zip)

![screen shot 2016-10-21 at 4 31 25 pm](https://cloud.githubusercontent.com/assets/22692494/19614629/ef388946-97ab-11e6-80b4-b964c54c7a72.png)

![screen shot 2016-10-21 at 4 34 56 pm](https://cloud.githubusercontent.com/assets/22692494/19614665/54d5816e-97ac-11e6-9535-5c79e7f86311.png)

**Comment by mdubya66** [comment]
@fdawg4l please triage.

**Comment by hickeng** [comment]
portlayer - this is where the initial error happens:
```
time="2016-10-24T19:13:04Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Remove:641] 653a644dcb993b01182d5be72a4a594599d0d90d6ef4e4724d850e7ae04e441e" 
time="2016-10-24T19:13:04Z" level=debug msg="Setting container 653a644dcb993b01182d5be72a4a594599d0d90d6ef4e4724d850e7ae04e441e state: Removing" 
time="2016-10-24T19:13:04Z" level=error msg="task failed: Invalid configuration for device '0'." 
time="2016-10-24T19:13:04Z" level=debug msg="Fault while attempting to destroy vm: &types.InvalidDeviceSpec{InvalidVmConfig:types.InvalidVmConfig{VmConfigFault:types.VmConfigFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage{types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"com.vmware.vim.vm.error.removeDiskAfterVMSnapshot\", Arg:[]types.KeyAnyValue(nil), Message:\"Cannot remove virtual disk from the virtual machine because it or one of its parent disks is part of a snapshot of the virtual machine.\"}}}}}, Property:\"virtualDeviceSpec.operation\"}, DeviceIndex:0}" 
time="2016-10-24T19:13:04Z" level=debug msg="Setting container 653a644dcb993b01182d5be72a4a594599d0d90d6ef4e4724d850e7ae04e441e state: Stopped" 
time="2016-10-24T19:13:04Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Remove:641] [123.708101ms] 653a644dcb993b01182d5be72a4a594599d0d90d6ef4e4724d850e7ae04e441e" 
```

The container is then explicitly deleted via vSphere due to #2850, resulting in the following state:

Can see in hostd that the subsequent Invalid configuration for device '1' is actually "Parent file doesn't exist, or the user has no permission to access." for 9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee.vmdk


The datastore shows that this disk has legitimately gone, but the metadata and entry in the parent map are still there. 
```
[root@sc-rdops-vm09-dhcp-3-84:~] ls -l /vmfs/volumes/58093209-733a9a96-7018-020012c9f1d7/VCH2/VIC/42262192-dec7-28f0-06c0-9b2b7d9e9317/images/9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee/9967c5ad88de8c101809f7f22d4774b6791
fe46ac3033d57abf7ebb1dd8e36ee.vmdk
ls: /vmfs/volumes/58093209-733a9a96-7018-020012c9f1d7/VCH2/VIC/42262192-dec7-28f0-06c0-9b2b7d9e9317/images/9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee/9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee.vmdk: No such file or directory
[root@sc-rdops-vm09-dhcp-3-84:~] ls -l /vmfs/volumes/58093209-733a9a96-7018-020012c9f1d7/VCH2/VIC/42262192-dec7-28f0-06c0-9b2b7d9e9317/images/9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee/
total 8
drwxr-xr-x    1 root     root           420 Oct 24 19:07 imageMetadata
-rw-r--r--    1 root     root             0 Oct 24 19:07 manifest
[root@sc-rdops-vm09-dhcp-3-84:~] ls -l /vmfs/volumes/58093209-733a9a96-7018-020012c9f1d7/VCH2/VIC/42262192-dec7-28f0-06c0-9b2b7d9e9317/images/9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee/imageMetadata/
total 8
-rw-r--r--    1 root     root          2024 Oct 24 19:07 metaData
[root@sc-rdops-vm09-dhcp-3-84:~] cat /vmfs/volumes/58093209-733a9a96-7018-020012c9f1d7/VCH2/VIC/42262192-dec7-28f0-06c0-9b2b7d9e9317/images/9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee/imageMetadata/metaData
{"id":"9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee","parent":"a61cd723bcf2b0ccaaa3b8f779dfca17040bd459d9e615b82a7ea17993ec59f2","created":"2016-10-07T21:03:58.469866982Z","container":"8bb318a3b4672c53a1747991c95fff3306eea13ec308740ebe0c81b56ece530f","container_config":{"Hostname":"4a74292706a0","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh","-c","#(nop) ","CMD [\"sh\"]"],"Image":"sha256:1679bae2167496818312013654f5c66a16e185d0a0f6b762b53c8558014457c6","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{}},"docker_version":"1.12.1","config":{"Hostname":"4a74292706a0","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["sh"],"Image":"sha256:1679bae2167496818312013654f5c66a16e185d0a0f6b762b53c8558014457c6","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{}},"architecture":"amd64","os":"linux","Size":1093484,"image_id":"e292aa76ad3bb2067cf5c1e0ffc6e6fe92d4d8fd638b8f9e3907c76d7c7f3114","digests":["sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c"],"tags":["latest"],"name":"library/busybox","diff_ids":{"sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef":"9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee","sha256:e88b3f82283bc59d5e0df427c824e9f95557e661fcb0ea15fb0fb6f97760f9d9":"a61cd723bcf2b0ccaaa3b8f779dfca17040bd459d9e615b82a7ea17993ec59f2"},"history":[{"created":"2016-10-07T21:03:58.16783626Z","created_by":"/bin/sh -c #(nop) ADD file:ced3aa7577c8f970403004e45dd91e9240b1e3ee8bd109178822310bb5c4a4f7 in / "},{"created":"2016-10-07T21:03:58.469866982Z","created_by":"/bin/sh -c #(nop)  CMD [\"sh\"]"}],"registry":"busybox:latest"}
```

**Comment by hickeng** [comment]
Recreation:
1. create container VM
2. snapshot containerVM
3. run `docker rm` on containerVM - will be `Invalid configuration for device '0'`
4. delete containerVM directly via vSphere
5. try to create new container off same image
--> VMDKs in that image tree are missing but we don't recover.

**Comment by matthewavery** [comment]
Our proposed solution to this for now is to disable snapshots of all containerVMs.

**Comment by mlh78750** [comment]
Need to fix the root issue here and not just disable snapshots.

**Comment by fdawg4l** [comment]
@mlh78750 
> and not just disable snapshots.

Absolutely we need and intend to fix the root issue.  Would you rather we leave this open, not disable snapshots, and allow this to happen again while we discuss/implement a fix?

cc @hickeng

**Comment by fdawg4l** [comment]
Chatted with @mlh78750 out of band and came up with a game plan.  The summary is we need to fix this on a whole.  As mentioned above we can get into this kind of a failure by deleting container VMs via vsphere (vc or esx, etc), creating snapshots, and likely other fairly standard vi-admin operations.  The common thread is they're all done outside the VCH/docker via vc or esx.  We'll get that working, but for now it's too large a fix for the short term.

In the interim, we intend to disable snapshots.  As far as deleting the container vm via vc/esx, we can document that the operation is not supported.  If we can find a way to allow the viadmin to disable the vm without destroying the image store, we can implement that too.  I suspect there is a workaround and I'll document it after trying it.

Lets create issues for each of the TODO items for the longer term solution, link it to this issue, and close this issue once the TODO items have been addressed.  Meanwhile the short term solution of disabling snapshots can link to this item but not close it.

**Comment by mlh78750** [comment]
See #2928

**Comment by mlh78750** [comment]
We will fix this with a fix to #2928. And current limitations will be documented in #2927 along with snapshot limitations. Moving this out of GA and to the icebox.

**Comment by corrieb** [comment]
#2928 was closed as fixed and in my recent tests, it seems like OOB delete works correctly. However, while OOB delete doesn't block future container creation, it does seem that the name is not purged from the cache.

**Comment by corrieb** [comment]
Created #5760. Closing this
