### ISSUE TITLE
Document how to set log size caps

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2860]
Per https://github.com/vmware/vic/issues/2848.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/2848 is implemented in PR https://github.com/vmware/vic/pull/3105.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/pull/3105 is merged.

**Comment by npakrasi** [comment]
@vburenin is this accurate?
Setting the Log Size Cap
The log size cap is set at 20MB and rotates automatically if the size exceeds 20 MB. Log rotation depends on the amount of memory you allocate when you configure a VCH and the debug level you set.

**Comment by npakrasi** [comment]
Reviewed by Vlad: The log size cap is set at 20MB. If the size exceeds 20 MB, then vSphere Integrated Containers Engine compresses the files and saves a history of the last two rotations. These files are rotated:

`/var/log/vic/port-layer.log` <br>
`/var/log/vic/init.log` <br>
`/var/log/vic/docker-personality.log` <br>
`/var/log/vic/vicadmin.log`

**Comment by stuclem** [comment]
Reviewed as part of global doc review. Closing.
