### ISSUE TITLE
Feature request: standard machine parseable output from vic-machine

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2861]
Admiral team has request that we at least provide an option to toggle the output from vic-machine to some standard parseable format like json.

Acceptance criteria:
1. We provide either by default or with a parameter to allow the output from vic-machine to be machine parseable.

**Comment by mdubya66** [comment]
We will need to look at this post GA.

**Comment by emlin** [comment]
@mhagen-vmware what result from vic-machine should be machine parseable? I don't think all output from vic-machine create is useful if user just want to get VCH information. So here we need to clarify what is needed.

**Comment by mdubya66** [comment]
This is not a 1.1 ask. Making low priority.

**Comment by mhagen-vmware** [comment]
@emlin For the purposes of this story pretty much everything needs to be machine parseable as even debug information and logging should be returned because the goal of this is to get Admiral to be able to deploy VCHs in an automated fashion and when something goes wrong they would need to bubble that up to their interface likely.  But on that note, the priority has been lowered as we are not planning on supporting this deployment mechanism at this time.

**Comment by mdubya66** [comment]
it's also probably much larger than a 2, probably a 5. API's are needed.

**Comment by emlin** [comment]
Okay, if API is required, this will be a different story, cause server could keep failed deployment log, and which will be some structure, instead of current console output.
But we'll need to revisit this at that time

**Comment by renmaosheng** [comment]
closing this as not got this request from admiral recently.
