### ISSUE TITLE
5-5-Heterogenous tests fails on the nightly run

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#2878]
Hetro tests are failing with a govc error in nimbus. The tests are using 6.5 version of the EXS/VC.

'govc: product/version specific feature not supported by target' should be empty.

5-5-Heterogenous-ESXi.Test
Start / End / Elapsed:  20161026 23:37:13.266 / 20161026 23:46:58.392 / 00:09:45.126
Status: FAIL (critical)
Message:    'govc: product/version specific feature not supported by target' should be empty.
00:00:00.008KEYWORD BuiltIn . Log To Console \nStarting test...
00:04:54.016KEYWORD ${esx1}, ${esx1-ip} = Nimbus-Util . Deploy Nimbus ESXi Server %{NIMBUS_USER}, %{NIMBUS_PASSWORD}
00:00:00.001KEYWORD BuiltIn . Set Suite Variable ${ESX1}, ${esx1}
00:04:51.098KEYWORD ${esx2}, ${esx2-ip} = Nimbus-Util . Deploy Nimbus ESXi Server %{NIMBUS_USER}, %{NIMBUS_PASSWORD}, 3029944
Start / End / Elapsed:  20161026 23:42:07.294 / 20161026 23:46:58.392 / 00:04:51.098
00:00:00.003KEYWORD ${name} = BuiltIn . Evaluate 'ESX-' + str(random.randint(1000,9999)), modules=random
00:00:00.003KEYWORD BuiltIn . Log To Console \nDeploying Nimbus ESXi server: ${name}
00:00:00.001KEYWORD SSHLibrary . Open Connection %{NIMBUS_GW}
00:00:05.744KEYWORD SSHLibrary . Login ${user}, ${password}
00:04:43.467KEYWORD ${out} = SSHLibrary . Execute Command nimbus-esxdeploy ${name} --disk=48000000 --ssd=24000000 --memory=8192 --nics 2 ${version}
00:00:00.002KEYWORD BuiltIn . Should Contain ${out}, To manage this VM use
00:00:00.002KEYWORD @{out} = String . Split To Lines ${out}
00:00:01.199FOR ${item} IN [ @{out} ]
00:00:00.008KEYWORD @{gotIP} = String . Split String ${line}, ${SPACE}
00:00:00.001KEYWORD ${ip} = String . Remove String @{gotIP}[5], ,
00:00:00.001KEYWORD OperatingSystem . Remove Environment Variable GOVC_PASSWORD
00:00:00.000KEYWORD OperatingSystem . Remove Environment Variable GOVC_USERNAME
00:00:00.001KEYWORD OperatingSystem . Set Environment Variable GOVC_INSECURE, 1
00:00:00.001KEYWORD OperatingSystem . Set Environment Variable GOVC_URL, root:@${ip}
00:00:00.656KEYWORD ${out} = OperatingSystem . Run govc host.account.update -id root -password e2eFunctionalTest
00:00:00.002KEYWORD BuiltIn . Should Be Empty ${out}
Documentation:  
Verifies that the given item is empty.
Start / End / Elapsed:  20161026 23:46:58.389 / 20161026 23:46:58.391 / 00:00:00.002
23:46:58.390    INFO    Length is 62  
23:46:58.391    FAIL    'govc: product/version specific feature not supported by target' should be empty.

**Comment by dougm** [comment]
Works for me against 6.5:

```
% govc host.account.update -id root -password password-for-esx65                                                                                                                                                                                   
% govc about
Name:         VMware ESXi
Vendor:       VMware, Inc.
Version:      6.5.0
Build:        4564106
OS type:      vmnix-x86
API type:     HostAgent
API version:  6.5
Product ID:   embeddedEsx
UUID:         
```

Could be that the host account manager hasn't started yet at that point, or is disabled somehow.  If you can send me the GOVC_URL for a system in this state, I'll take a look.

**Comment by rajanashok** [comment]
Will get a test environment ready, but here is some more information on where exactly we hit this issue in the test code.

Log To Console  \nStarting test...
${esx1}  ${esx1-ip}=  Deploy Nimbus ESXi Server  %{NIMBUS_USER}  %{NIMBUS_PASSWORD}
Set Suite Variable  ${ESX1}  ${esx1}
${esx2}  ${esx2-ip}=  Deploy Nimbus ESXi Server  %{NIMBUS_USER}  %{NIMBUS_PASSWORD}  3029944
Set Suite Variable  ${ESX2}  ${esx2}
${esx3}  ${esx3-ip}=  Deploy Nimbus ESXi Server  %{NIMBUS_USER}  %{NIMBUS_PASSWORD}  4240417
Set Suite Variable ${ESX3} ${esx3}

5-5-Heterogenous-ESXi :: Test 5-1 - Distributed Switch                        
==============================================================================
Test                                                                  
Starting test...

Deploying Nimbus ESXi server: ESX-1667
Successfully deployed new ESXi server - rashok-ESX-1667

Deploying Nimbus ESXi server: ESX-1229
| FAIL |
'govc: product/version specific feature not supported by target' should be empty.
------------------------------------------------------------------------------
5-5-Heterogenous-ESXi :: Test 5-1 - Distributed Switch                | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /drone/src/github.com/vmware/vic/5-5-Heterogenous-ESXi/output.xml
Log:     /drone/src/github.com/vmware/vic/5-5-Heterogenous-ESXi/log.html
Report:  /drone/src/github.com/vmware/vic/5-5-Heterogenous-ESXi/report.html

**Comment by rajanashok** [comment]
I think this where the issue shows up for build 3029944

${esx2} ${esx2-ip}= Deploy Nimbus ESXi Server %{NIMBUS_USER} %{NIMBUS_PASSWORD} 3029944
Set Suite Variable ${ESX2} ${esx2}

**Comment by dougm** [comment]
Build 3029944 is branch vsphere55u3 - that command requires 6.0 or higher, 5.5 is "not supported" as the error message says.  VIC doesn't support 5.5 either, so that build should just be removed from the test.

**Comment by mhagen-vmware** [comment]
This is specifically the heterogenous ESX under VC test, which tests what vmware's support stance is - 3 versions back.  So while VIC doesn't specifically support 5.5, we could install into a 6.5 VC with DRS on and get placed on a 5.5 ESX. We won't necessarily support that still, but we need to test it. Is there a workaround to set the password on a 5.5 ESX server?  Maybe just through ssh?

**Comment by dougm** [comment]
The accountManager field we use was added in 6.0: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.ConfigManager.html#field_detail

I can look for another way using the API, but won't get to it until next week.

**Comment by dougm** [comment]
See also vmware/govmomi#602 - @mhagen-vmware had said no to 5.5, didn't realize 5.5 was in fact still in the test mix.

**Comment by dougm** [comment]
Have it working with 5.5: vmware/govmomi#620

Catch is it only works when connected directly to ESX, not via VC - but looks like that should be ok in this case.

**Comment by mhagen-vmware** [comment]
This is working now
