### ISSUE TITLE
Document how VCH handles snapshots

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2886]
Per https://github.com/vmware/vic/issues/2879.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/2879 is in the icebox, so we must document that that VCH does not support having snapshots taken of it. To add in the list of unsupported vSphere features in the interop topic.

**Comment by npakrasi** [comment]
Added snapshots to the unsupported features.

**Comment by stuclem** [comment]
Per PR  https://github.com/vmware/vic/pull/2900, we should clarify that taking snapshots is disabled for container VMs.

**Comment by npakrasi** [comment]
Revised to say taking snapshots of the VCH and container VMs is disabled.

**Comment by mdubya66** [comment]
@npakrasi we did not disable snapshots. the issue was closed as will not fix. we need to document that out of band snapshots and vm stop operations will break the docker personality @matthewavery can fill you in further

**Comment by npakrasi** [comment]
Rephrased: Performing out of band snapshots and vm stop operations breaks the Docker personality.

**Comment by stuclem** [comment]
I'm not sure that customers would know what you mean by "out-of-band snapshots" and "Docker personality". vic-machine does take a snapshot of the VCH during upgrade, so I imagine that's an "in-band" type of snapshot, but taking snaps yourself is what Matt means by "out-of-band".  Stopping a VM is a different issue to taking a snapshot. I would break this into two bullets:

- Creating  snapshots of the virtual container host endpoint VM or container VMs can cause vSphere Integrated Containers Engine not to function correctly. 
-  Powering on, powering off, or deleting the virtual container host endpoint VM or container VMs can cause vSphere Integrated Containers Engine not to function correctly.

**Comment by npakrasi** [comment]
Done!
