### ISSUE TITLE
docker attach tests are flaky

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#2896]
Attach sometimes takes a long time or fails to return which causes problems for the tests. The fifo method we were using to input to an attached container seems to no longer work. Checking the status of a previously attached container using `ps -a` sometimes shows status as `Stopped` instead of `Exited`

Current tests in 
`tests/test-cases/Group1-Docker-Commands/1-25-Docker-Port-Map.robot`
`test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot`

**Comment by vburenin** [comment]
This one might be partially related #2889. Negotiation between port-layer and tether time sometimes takes forever, especially on loaded system.
