### ISSUE TITLE
Create VCH should create a 'default' volume store (esp for the images which has built with dockerfile)

### ISSUE THREAD

**Issue by mobla** [vmware/vic#2899]
I faced this issue when playing with VIC-Harbor integration testing.
Steps:
1. Create VCH - with insecure-registry - harbor registry (with no default volume store)
root@photon-yhNySW7sg [ ~/vic ]# ./vic-machine-linux create --name VCH2 --target 10.139.23.227 --compute-resource cls --user administrator@vsphere.local --password 'Admin!23' --bridge-network vicDVPG --image-store sharedVmfs-0 --no-tls --insecure-registry 10.139.23.226:80
2. Do docker login
3. Pull an image to local registry
4. Tag and Push that image to Harbor registry
5. Now, Pull it back from Harbor
6. Run the application
docker -H 10.139.23.221:2375 run --name nginxharbor 10.139.23.226:80/heimdall/nginx:1.9.0

**VIC Version:**
root@photon-yhNySW7sg [ ~/vic ]# ./vic-machine-linux version
vic-machine-linux version v0.6.0-4890-4f98611
Server:
 Version:      0.6.0
 API version:  1.23

**Expected behavior:**
VCH should either create a default volume store or fail in validation to ask user to create a default volume store

**Actual behavior:**
Running the application fails with "docker: Error response from daemon: No volume store named (default) exists."

**Comment by matthewavery** [comment]
Prospective solution will be to flip the default volume store flag so that it is `--no-default-volumestore` for vic-machine. Then vic machine can create a default volume store on the same datastore that the VCH will live on. This should eliminate the need to set any volume related flags on a standard `VIC` deployment.

**Comment by mreferre** [comment]
I agree with this approach @matthewavery. By default it should use the VCH datastore so if you happen to use volumes you can. 

Then the user should be offered to the choice to 1) optimize the placement (by specifying a different datastore) or 2) disable volumes (by deploying the VCH with an explicit flag to disable volumes) 

Ideally.

**Comment by fdawg4l** [comment]
Ping @hickeng in case he has thoughts on this.

@matthewavery, I think that's a good approach.

**Comment by fdawg4l** [comment]
Copying @hickeng from slack.

```The reason we don't create one by default is because we're targeting production usage. Generally a weakening of restrictions should be explicit - if you want to be able to run containers that use volumes without being explicit about where that persisted data is stored then you create a "default" volume store. If you want to ensure that you know where data is going then you can omit that and people will have to explicitly assign volumes to match VOLUME commands in images.```

**Comment by matthewavery** [comment]
From the point of view of production anything that involves the consumption of resources should be explicit in my opinion so I agree with the above statement. However, if this is going to consistently be an issue for people attempting deployments then another solution might be to enable a way to create a default store without a redeployment.

**Comment by hickeng** [comment]
@matthewavery The significance of this should be reduced drastically when reconfigure is available.

**Comment by mreferre** [comment]
According to @hickeng it seems like now the VCH is able to inspect the image metadata and search for any VOLUME statement. If they are present VIC will create automatically said volumes and map them to the containerVM. An example of this is the vmware/admiral image. 

If we don't have volumes enabled all these images fail to instantiate. I think this will be a usability nightmare. With all the meaningful defaults we are putting into vic-machine-create (which are awesome) I do think we need to have a "default" volume store. To my previous point I do believe we should: 
- provide a meaningful default (such as this perhaps? https://github.com/vmware/vic/issues/3046#issuecomment-259092274) 
- provide a flag to explicitly remove volume support for the VCH 
- provide a flag to optimize placement of the volume store.

**Comment by hickeng** [comment]
Optimized placement is already present - that's the current `volume-store` option.

If we place the volumes into the VCH applianceVM folder then they'll be deleted with the VM on vSAN, or they would persist and prevent us from reusing that folder name when recreating a VCH, which prevents easy re-use of volumes (we would need to know and specify the foldername of the previous VCH, which is not necessarily the vch name).
Using the datastore from either applianceVM or image store means that VCHs using the same datastores are likely to have collisions with their "default" volume stores which is unsupported (and not guarded against currently).

An alternative is to refuse to create a VCH without either:
* default volume store explicitly specified
* default volume store explicitly disabled

**Comment by mreferre** [comment]
@hickeng I like the idea of making volume store explicitly configured or disabled. 

However, when users choose to configure it, shouldn't we check / enforce that they use a unique directory at this point? 

My understanding is that if they either specify no directory or if they specify the same directory we will end up in the problem described in https://github.com/vmware/vic/issues/3046

**Comment by mreferre** [comment]
So I was playing with this a bit more (with 0.7.0)  

I created two VCHs (VCH1 and VCH2). 

I had `--volume-store sharedstorage/VCH1volumes:default` for the first one and `--volume-store sharedstorage/VCH2volumes:default` for the second one.

This created two different directories on the `sharedstorage` datastore. Both VCHs could create volumes in their respective folders. 

I deleted VCH1 with the `--force` flag. This resulted in:
```
INFO[2016-11-10T14:04:06Z] Deleting volume store "default" on Datastore "sharedstorage" at path "VCH1volumes" 
```
This has indeed deleted both the VCH1 as well as the VCH1volumes folder on the `sharedstorage` datastore. 

VCH2 could still create volumes (thus I am not seeing issue https://github.com/vmware/vic/issues/3046). 

I deleted VCH2 with the `--thumbprint` flag. This resulted in:
```
WARN[2016-11-10T14:18:59Z] Since --force was not specified, the following volume stores will not be removed. Use the vSphere UI to delete content you do not wish to keep.
	default: [sharedstorage] VCH2volumes
```
This has indeed NOT deleted the VCH2volumes folder on the `sharedstorage` datastore. It did delete the VCH2 volume (image store). 

In a bold move... I recreated VCH1 and I did specify `--volume-store sharedstorage/VCH2volumes:default` as the volume store (not a typo the name of the VCH is VCH1 and the name of the volume store is sharedstorage/VCH2volumes:default). 

This created VCH1 and a `docker volume ls` against it would show the volumes I have previously created onto VCH2. 

Are we onto something? 

/cc @hickeng @emlin

**Comment by matthewavery** [comment]
@hickeng @emlin so this has showed up again in the set 0.9.0 and I am looking into it right now. Looks like @mreferre 's last post appears to have displayed #3046 as working now(I remember adding fixes for it in 0.7.0). I will attempt the recreation steps, but I suspect that #3046 ticket is closable. I believe I lost track of this one since I was out for an emergency in November, I will wrap this one up if you guys have no more added changes for this. @hickeng did we want a ticket requesting explicit requirement of disabling volume's or having a default defined? or do you want me to add include it in the work on this ticket?

**Comment by mdubya66** [comment]
we should probably get UX input for any new options.

**Comment by matthewavery** [comment]
We are waiting for input from customers + Karthik as to how to proceed with this issue.

**Comment by zjs** [comment]
Closing this as creating a default volume store is not something we'd want to do without a good reason, and have not received sufficient information from users to justify that behavior (https://github.com/vmware/vic/issues/2899#issuecomment-275739238). This problem may be partially mitigated by the UI.
