### ISSUE TITLE
Server error from portlayer vmdk was not found

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#2901]
https://ci.vmware.run/vmware/vic/6230

```
ERROR: for redis  Cannot start service redis: Server error from portlayer: File /vmfs/volumes/57ebe686-bd795ca7-1c5d-0050569c86f0/test/volumes/9096a523-9ae9-11e6-846c-000c2965802e/9096a523-9ae9-11e6-846c-000c2965802e.vmdk was not found
```

Seems to be related to volumes. Mike sees this often locally.

**Comment by matthewavery** [comment]
I have been looking into this as well. It is my top priority after I wrap up my other two PRs.

**Comment by anchal-agrawal** [comment]
Possibly a dup of #2285.

**Comment by mlh78750** [comment]
Only seen once and possibly related to #2285 which we pushed to .9. We'll close as no-repo.
