### ISSUE TITLE
Does VCH need to wait to power on all VMs in a vApp before it can start creating new container hosts

### ISSUE THREAD

**Issue by smaithani** [vmware/vic#2902]
Deploy a VCH
Create 25 container VMs (all powered on)
Power off the vApp
Power on the vApp
Try to create a new container VM (this call gets stuck)

> > docker -H x.x.x.x   run -it --name buz28  busybox 

Also when we power on the vApp, DRS kicks in migrating VMs around which can slow down the power on sequence, further delaying the time in which a user can start creating container VMs

[container-logs.zip](https://github.com/vmware/vic/files/551771/container-logs.zip)

**Comment by mlh78750** [comment]
Needs triage post 0.8 release

**Comment by hickeng** [comment]
The vApp should not be configured to power on the containerVMs. If containerVMs are configured with restart then those should be relaunched, _by the endpointVM_ as part of it's restoration of state.

**Comment by andrewtchin** [comment]
We've moved away from vApp, closing.
https://github.com/vmware/vic-product/issues/1523
