### ISSUE TITLE
Flag --force skips thumbprint validation.

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#2915]
--force should not skip thumbprint validation, to skip it VIC should be using a different flag, for example --no-thumbprint or something. Otherwise it is easy to make mistake.

Current help for create string says this:

```
   --force, -f                             Force the install, removing existing if present
```

**Comment by mlh78750** [comment]
related to #3118

**Comment by hickeng** [comment]
I think this ties in with general error handling in vic-machine. We should really identify errors via a constant so they can both be i18n _and_ we can supply a set of errors to ignore instead of a single flag.

**Comment by hickeng** [comment]
Closing in favour of #3118
