### ISSUE TITLE
Failed to find slot for NIC when more than 3 interfaces are added to VCH

### ISSUE THREAD

**Issue by emlin** [vmware/vic#2922]
VIC should support four ports in VCH appliance VM.

hmahmood commented on Jul 26
I ran into this when I created a VCH that had 4 NICs. We use slot numbers to lookup up interfaces in the tether code. The slot numbers are assigned by vic-machine. However, there is no guarantee that vsphere will honor these slot numbers. This is what happened here; vsphere assigned a different slot number to the one we set in guestinfo.

We need to stop using slot numbers to identify interfaces, and move to using device labels instead. Device labels are named Ethernet0, Ethernet1, and so on, in the order NICs are added to the VM's config.
#1674 is the temporary workaround for this issue

**Comment by emlin** [comment]
@mdubya66

**Comment by caglar10ur** [comment]
Fixed with #7b54d345055c9135df17e25c217473ae0115263c
