### ISSUE TITLE
Create a test for running container removed OOB

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2925]
okay… thanks guys.. do we have a test for deleting a vm using vsphere and then relaunching  a new container with same image? and that runs on 6.5? see above.

**Comment by MHagen** [comment]
Wrong mhagen.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Oct 27, 2016 at 1:41 PM -0700, "Mikkel Hagen" <notifications@github.com<mailto:notifications@github.com>> wrote:


okay... thanks guys.. @mhagen<https://github.com/mhagen> do we have a test for deleting a vm using vsphere and then relaunching a new container with same image? and that runs on 6.5? see above.

-
