### ISSUE TITLE
Document that power operations and deletion of container VMs should not be done through the vSphere interfaces.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#2927]
This will be addressed in the future, but may leave the VCH in an bad state in the current release.

**Comment by mlh78750** [comment]
Those operations should be done through the docker client.

**Comment by stuclem** [comment]
Requires an update in the limitations topic in App Dev and also needs to be mentioned somewhere in Admin.

**Comment by stuclem** [comment]
Added the following disclaimer to all 3 of the above files:

----

**IMPORTANT**: Do not use the vSphere Client or vSphere Web Client to perform operations on virtual container host appliances or container VMs. Specifically, using the vSphere Client or vSphere Web Client to power off, power on, or delete virtual container host appliances or container VMs can cause vSphere Integrated Containers Engine to not function correctly. Always use vic-machine to perform operations on virtual container hosts. Always use Docker commands to perform operations on containers.

----

@mlh78750 does this cover it? Thanks!
