### ISSUE TITLE
Postgres 9.4 does not run on VIC

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2929]
I am pretty sure it used to run.  It is part of the compose voting app.  It refuses to run now.

docker run -d postgres:9.4

Docker logs don't show postgres outputting any errors.  It just quits half way through starting up.

VIC pre 0.7.0.

**Comment by sflxn** [comment]
[container-logs (1).zip](https://github.com/vmware/vic/files/557141/container-logs.1.zip)

**Comment by caglar10ur** [comment]
check https://github.com/vmware/vic/commit/7633e162a7242f19b86c69731fe85ea7b8e60611

**Comment by sflxn** [comment]
This turned out to be a postgres specific issue.  @hickeng tracked this down to their init scripts. Their dockerfile creates an anonymous volume and maps it to /var/lib/postgres/data.  Since the anonymous volume is a disk, it has a lost+found folder.  The init script in the postgres container won't run if the data folder it's started with has an existing folder (e.g. lost+found) in it.

There is a work around.  Postgres looks for the data folder in an environment variable PGDATA.  As long as PGDATA points to a folder that does not container any other folder, it will startup fine.  By default PGDATA is set to /var/lib/postgresql/data.  Override that via

docker run -d -e PGDATA=/var/lib/postgresql/data/data postgres:9.4

The folder override specifified does not need to exist.

**Comment by caglar10ur** [comment]
or we could delete it?

**Comment by sflxn** [comment]
We could delete it, but this really is a postgres specific issue.  I suspect a volume driver that mounts a disk onto regular docker will also have the same issue with postgres.  Since regular docker will unlikely try to delete that folder, we probably should just keep it as is.  I know EMC has a volume plugin.  It would be curious to know if they've run into this same issue with regular docker.

**Comment by kacole2** [comment]
@sflxn taken from one of the engineers. "that's why we create a `/data` directory on the volume so the database software see a completely clean directory and not an artifact of ext4"

You're going to run into this issue with any Dockerfile that has `VOLUME` listed in it. Give Redis a try and see what happens. https://github.com/dockerfile/redis/blob/master/Dockerfile#L28
