### ISSUE TITLE
Document support for multi-VLAN env in VC

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2935]
Per https://github.com/vmware/vic/issues/2560 and PR https://github.com/vmware/vic/pull/2908.

**Comment by stuclem** [comment]
Not required for 0.7, so moving back to backlog.

**Comment by stuclem** [comment]
To add to the supported vSphere features topic.

**Comment by npakrasi** [comment]
Added to Interop topic: You can deploy and run Docker commands against a virtual container host on a vCenter appliance that has multiple portgroups on different VLANs within the datacenter.
