### ISSUE TITLE
Document  alias / unalias for docker --tls 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2937]
Per beta-feedback sent by @karthik-narayan via email.

@mdubya66 and @karthik-narayan, do you have more details? Thanks!

**Comment by karthik-narayan** [comment]
Customers who setup a VCH are often times frustrated that they have to type "docker --tls". On OSX you could use "alias dkr = "docker --tls"" to simplify this. I'm sure that this exists for Windows and Linux as well. It'd be good to document this as this isn't a command that customers use on a regular basis. "unalias" removes the alias. HTH.

**Comment by mdubya66** [comment]
I'd be hesitant to document this. It varies on the shell you are using. There is DOCKER_OPTS but those have been reported to not work in some cases.

**Comment by karthik-narayan** [comment]
@mdubya66 That makes sense. In that case, I'll start collecting data on how customers feel about a default non-TLS endpoint with the option of enabling it via. a CLI option.

**Comment by stuclem** [comment]
@mdubya66 should we close this one?

**Comment by mlh78750** [comment]
yes.

**Comment by stuclem** [comment]
Thanks @mlh78750
