### ISSUE TITLE
root password for the virtual container host

### ISSUE THREAD

**Issue by mbenachour** [vmware/vic#2952]
what is the password for root user in the VCH (photon os)  created with vic-machine ?
root/changeme is not working

**Comment by mdubya66** [comment]
This as changed with https://github.com/vmware/vic/issues/1218

The issue to document how to enable ssh and the root password can be found here https://github.com/vmware/vic/issues/2678

**Comment by mdubya66** [comment]
Closing as duplicate of #2678
