### ISSUE TITLE
VIC cannot install into a NSX-T system: error not implemented for type mo.OpaqueNetwork

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2968]
bin/vic-machine-linux create --target 1.2.3.4 --user root --password xxxxx --no-tls --name VCH-1234-4355 --force
WARN[2016-11-01T14:11:28-05:00] Configuring without TLS - all communications will be insecure 
INFO[2016-11-01T14:11:28-05:00] ### Installing VCH ####                      
INFO[2016-11-01T14:11:30-05:00] Validating supplied configuration            
INFO[2016-11-01T14:11:30-05:00] Using default datastore: local-0             
ERROR unknown Action error: not implemented for type mo.OpaqueNetwork. See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by dougm** [comment]
This is coming from govmomi: https://github.com/vmware/govmomi/blob/master/list/lister.go#L95

I can add the case to handle mo.OpaqueNetwork, but don't have an NSX-T env to test against.

**Comment by dougm** [comment]
With vmware/govmomi#622 I was able to vic-machine create, pull + run busybox date.  Trying to run regression tests but keep getting dropped off the vpn.  Will try again later this evening.

**Comment by dougm** [comment]
Regression tests pass against the env @mhagen-vmware gave me access to.  I'll open a PR to bump the vendor'd govmomi.
