### ISSUE TITLE
Implement `rmi` up to last tag in SPL

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#2973]
We're currently only deleting leaf images when an `rmi` is called on a given `repository:tag`.  Until recently we couldn't have more than 1 tag on a given image ID, but the personality's image cache now supports multiple tags and untagging on `rmi`.  We need to integrate this into the PL delete mechanism to delete upto the next image, thereby actually deleting more than just the last image.

Without this change, pull of an image (tag:repo) which you just deleted will show there's nothing to do because the majority of the data is still in the datastore.  (We picked this to be conservative until the personality's image cache had this tagging/persistance-of-tags which it has now.)

**Comment by fdawg4l** [comment]
@mdubya66, @hickeng and I want to get this into GA because it's fairly important.  Pretty sure we can wrap this up quickly.  Just FYI.

**Comment by mdubya66** [comment]
Do it :)
