### ISSUE TITLE
vic-machine delete: cannot recognize vch not fully created

### ISSUE THREAD

**Issue by emlin** [vmware/vic#2981]
Solution is to create a constant VCH ID, represent not fully created VCH, so vic-machine delete can go ahead to delete that vm.

**Comment by mhagen-vmware** [comment]
@emlin Iceboxing, I am assuming that the user can manually clean up any partial install then move on.  Is that right?

**Comment by emlin** [comment]
@mhagen-vmware yes, you're right. In this single case, user will have one vapp and partial vch vm created, without any datastore consumption. 
The only exception is the bridge network in esxi, that will not be deleted, if user just delete the vch vm and resource pool. But that still can be reused next time to deploy same name vch.

**Comment by stuclem** [comment]
Just noticed the kind/note flag. Added the following to the RNs:

- <b>vic-machine delete does not recognize virtual container hosts that were not fully created. [#2981](https://github.com/vmware/vic/issues/2981)</b><br>`vic-machine delete` fails when you run it on a virtual container host that was not fully created.

  Workaround: Manually delete any components of a partial installation, for example, the virtual container host vApp, the endpoint VM, and datastore folders.

@emlin does this cover it? Thanks!

**Comment by corrieb** [comment]
I don't believe this is still a bug. I just tried with the latest master to force vic-machine create to timeout midway through and then delete it. Seems to work just fine on ESX and VC. 

@emlin should this be closed? If so, we should also close #3241 and re-enable the timeout test.

**Comment by mdubya66** [comment]
Closing this as CNR.
