### ISSUE TITLE
Documentation: create troubleshooting topic about certificate thumbprints

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2996]
Create a TS topic that lists the errors that result when vic-xxx thumbprint is required but not specified and what to do. 

Two such errors are, but there are possibly more:

- `Failed to verify certificate for target=<i>vcenter_or_esxi_host</i> (thumbprint=<i>thumbprint</i>)`
- `Certificate has no IP SANS specified` if trying to connect via IP address.

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic/issues/3268

**Comment by stuclem** [comment]
Thanks @andrewtchin. So, if we are removing CIDR notation for the IP settings (associated doc update tracked in https://github.com/vmware/vic/issues/3278), do we still need to document anything here?

**Comment by stuclem** [comment]
Ah, just noticed that https://github.com/vmware/vic/issues/3268 is for 0.9. What should we do about this one? Document that people shouldn't use CIDR, even though it's supported?

**Comment by andrewtchin** [comment]
I think that's the best idea for now to avoid most people messing up the certificate generation as in 3268

**Comment by stuclem** [comment]
Done. Change is in https://github.com/stuclem/vic/commit/856930aca1d356bbb410e29bc5bcac0475593757.

Leaving this issue open as it is actually about the VC certs rather than the ones used to verify Docker clients.

**Comment by stuclem** [comment]
Added [VCH Deployment Fails with a Certificate Verification Error](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/ts_thumbprint_error.md)

Change is in https://github.com/stuclem/vic/commit/4fe4efe036e327e59b7288bcc54969cb937a8d61.

**Comment by stuclem** [comment]
Reviewed as part of global doc review. Closing.
