### ISSUE TITLE
Documentation: update doc for image-store to reflect new folder structure

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2997]
The folders that vic-machine creates in the image-store have changed, so the [image-store doc](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--image-store) needs to be updated.

Also, we currently state that you can share an image store between VCHs, but @mreferre states in https://github.com/vmware/vic/issues/2995 that this does not work. Whether this is by design or a bug is TBC. Either way, we need to update the doc for 0.7 and possibly beyond.

**Comment by mlh78750** [comment]
Looks like there is a bug now tracked in #3003 with using the same image store. It should be supported (and work after that bug closes). 

So a few things we may want to do.. Document the new namespacing scheme we use to allow multiple VCH to use the same path. Also for the .7.0 release document the problem in #3003 and recommend not using the same path for multiple VCH until it is resolved.

**Comment by stuclem** [comment]
Updated the section on `--image-store` to reflect the new folder organization. I do not mention the `kvstore `folder yet, but will do so after 0.7 when https://github.com/vmware/vic/pull/3005 is merged. With regards to sharing the image store folder, I document the behaviour as it should be, but with a caveat that it doesn't work in the current builds. See https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--image-store

@mlh78750 and @fdawg4l is the section above now correct? Thanks!

**Comment by stuclem** [comment]
Logged https://github.com/vmware/vic/issues/3013 to remove the caveat after 0.7, when https://github.com/vmware/vic/pull/3005 is merged.

**Comment by mlh78750** [comment]
That looks correct to me. But @fdawg4l is the authority on it.

**Comment by fdawg4l** [comment]
>  Container image files are made available to all of the virtual container hosts that use that image store.

@hickeng and I went back and forth on this feature several times and we decided that the best course of action is to prevent implicit sharing of images across VCHs.  Rather, we intend to make available an offline process (perhaps with a tool or a tick box in a web ui) which allows sharing of specific images across VCHs.  It should be up to the VI admin / container admin to decide what data should be shared with whom and on what VCHs.

So as it is, using the same `--image-store` path across VCHs will *not* allow VCHs to share.

That being said, the issue (#3003) makes even using the same image store path across VCHs a problem due to a bug.  The caveat added to the doc looks great.  Thank you for doing that.

**Comment by stuclem** [comment]
@mlh78750  and @fdawg4l , I reworded as follows:

-----

By specifying the path to a datastore folder in the `--image-store` option, you can designate the same datastore folder as the image store for multiple virtual container hosts. In this way, `vic-machine create` creates only one `VIC` folder in the datastore, at the path that you specify. The `VIC` folder contains one <code><i>vch_uuid</i>/images</code> folder for each virtual container host that you deploy. By creating one <code><i>vch_uuid</i>/images</code> folder for each virtual container host, vSphere Integrated Containers Engine limits the potential for conflicts of image use between virtual container hosts, even if you share the same image store folder between multiple hosts.

**NOTE**: In the current builds of vSphere Integrated Containers Engine, sharing an image store folder between multiple virtual container hosts can lead to inconsistent behavior. Designate a different folder for the image store for each virtual container host, or omit the datastore folder from the `--image-store` option.

----

Thanks for mentioning that the gobbledygook between `VIC` and `images` is the UUID :)

**Comment by fdawg4l** [comment]
@stuclem that sounds great.  Thank you for updating and thanks for closing the loop on this.  Much appreciated.

**Comment by stuclem** [comment]
Thanks @fdawg4l
