### ISSUE TITLE
Spec for container command & control operations

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3]
This may be swagger, swagger used solely for specification rather than generation, or something else.

Currently the ssh server code is the spec for our communication. This is fragile and makes testing awkward when the client/server code are separated, particularly when it comes to the data structures that pass over the wire.

When specifying this, consider it to be a definition of the data that needs to pass from the VCH to the containerVM, not how it's passed. For example, we could pass an IP directly via ssh, or we can place it into the guestinfo for the containerVM so that it's persisted in an infrastructure visible fashion (the latter is preferred).

**Comment by mdubya66** [comment]
@sflxn still relevant?

**Comment by mdubya66** [comment]
marking medium as updated API version is a next release feature

**Comment by hickeng** [comment]
This should be rolled into #3618 and the spec is part of the portlayer component design.
Closing
