### ISSUE TITLE
kvstore susceptible to races when two VCH use same image store directory

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3003]
See #2995. In the investigation to #2995 @fdawg4l found a race issue for kvstore. See comment https://github.com/vmware/vic/issues/2995#issuecomment-258231620

I'm closing #2995 as won't fix, but the kvstore issue found needs to be fixed and will be tracked in this bug.

**Comment by fdawg4l** [comment]
Echo'ing the conversation we're having in #2995.  I think we need to get the fix for this issue in to 0.7.0.

**Comment by mlh78750** [comment]
Will the work around of using separate paths for each VCH installed on the same datastore solve the problem for now? 

If so, I recommend we doc this for 0.7 and mustfix for .8.

**Comment by mreferre** [comment]
@stuclem

**Comment by mlh78750** [comment]
@stuclem for docs this is related to #2995. For the .7.0 docs we need to caveat that you cannot use the same path on a datastore for multiple VCH installs. After this issue is resolved, this limitation will go away.

**Comment by fdawg4l** [comment]
> Will the work around of using separate paths for each VCH installed on the same datastore solve the problem for now?

Yup.  That's exactly right @mlh78750. 

Using different paths is a perfectly good work around.

**Comment by stuclem** [comment]
Adding this to the queue for the release notes. Will also include the caveat in the core docs (to be removed once fixed) as a part of https://github.com/vmware/vic/issues/2997.
