### ISSUE TITLE
Typo in vic-machine help? 

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#3010]
Using build 6507 

In the vic-machine extended help there is: 

`--container-network-gateway value, --cng value   Gateway for the container network's subnet in CONTAINER-NETWORK:SUBNET format, e.g. vsphere-net:172.16.0.0/16.`

Shouldn't the example 172.16.0.1? Also, why do we need to specify the subnet for the GW as well? We already specify it with the `--container-network-ip-range` parameter. 

All in all I would have expected the e.g. to be something like: 

`e.g. vsphere-net:172.16.0.1.`

**Comment by mreferre** [comment]
To be clear, and more precise... 

If I use `172.16.0.0/16` in the GW definition I get:

`Gateway 172.16.0.0 is not a routable address`

So there is indeed just a typo in the help that should say `.1`.

However the code seems to require the `/24` because if I only type `--container-network-gateway 172.16.0.1`

I get:

`Error parsing container network parameter PG2:172.16.0.1: invalid CIDR address: 172.16.0.1`

For the command to work I have to type `--container-network-gateway 172.16.0.1/24` (which isn't very intuitive IMO).

**Comment by hickeng** [comment]
Confirm that the gateway example is incorrect.

**Comment by mlh78750** [comment]
Agreed. And adding to GA.

**Comment by emlin** [comment]
@hickeng is the format correct? I mean if subnet is required

**Comment by mreferre** [comment]
Are we also removing the need to have the network class (e.g. /24) specified for the GW?

**Comment by mlh78750** [comment]
@hmahmood can you take a look at this one and recommend the changes needed.

**Comment by hmahmood** [comment]
#1741 already tracks removing specifying gateway in CIDR notation. As @hickeng pointed out, the gateway example is not correct. The ip range can be specified multiple ways, with CIDR notation, or as a range. In the latter case, figuring out the subnet correctly may not be possible. We could put out a warning from vic-machine saying the calculated subnet mask may not be correct. Here is the current implementation of this: https://github.com/vmware/vic/blob/master/pkg/ip/ip.go#L58

**Comment by mdubya66** [comment]
should we put this in the release notes for 0.7.0?

**Comment by mlh78750** [comment]
@hmahmood But do you need to specify the gateway value with the /XX CIDR. in this specific value it seems redundant. Correct?

**Comment by mlh78750** [comment]
@mdubya66 Yes. But let's make sure we're all on the same page as to what it should be. :)

**Comment by hmahmood** [comment]
@mlh78750 in the case where the ip range is specified in CIDR notation, it is redundant, yes.

**Comment by mlh78750** [comment]
@hmahmood yea. it's a bit strange. Most networking configurations put CIDR on the ip address or the "network" address (the all 0's of the mask address) and I've not normally seen it on the gateway.

Cool. We'll fix the removal of the gateway CIDR and track it with issue #1741 

We will use this issue to track fixing the incorrect documentation that vic-machine spits out.

Release notes for 0.7.0: The help text for vic-machine's option --container-network-gateway value, --cng incorrectly gives the example of a network range instead of the actual gateway address. A more proper example is e.g. vsphere-net:172.16.1.1/16.  In additon, please note that we will be removing the CIDR specification from the gateway configuration in a future release. That removal is tracked in #1741

**Comment by hickeng** [comment]
IIRC this was to keep the number of options you must specify as low as possible (given how many there are). If it's DHCP you only need to provide `--container-network`.
If it's non-dhcp you must provide a gateway, however it's it's a full subnet you add `--container-network-gateway=x,x,x,x/yy` and nothing else.
If you need to supply a range that is not the full subnet (e.g. when wanting to have containerVMs present on the same network as non-containerVMs or systems), then you can add `--container-network-ip-range` as an additional restriction.

@mreferre if we remove the CIDR notation, then we need to provide it somewhere else - likely by requiring the range parameter every time.

For reference:
```
   --container-network value, --cn value            vSphere network list that containers can use directly with labels, e.g. vsphere-net:backend. Defaults to DCHP - see advanced help (-x). (default: "VMExternal:external")
   --container-network-gateway value, --cng value   Gateway for the container network's subnet in CONTAINER-NETWORK:SUBNET format, e.g. vsphere-net:172.16.0.0/16.
   --container-network-ip-range value, --cnr value  IP range for the container network in CONTAINER-NETWORK:IP-RANGE format, e.g. vsphere-net:172.16.0.0/24, vsphere-net:172.16.0.10-20.
   --container-network-dns value, --cnd value       DNS servers for the container network in CONTAINER-NETWORK:DNS format, e.g. vsphere-net:8.8.8.8. Ignored if no static IP assigned.
```

**Comment by mreferre** [comment]
Oh I see @hickeng. That's clever. However I fear it may be too over-engineered / optmized. 

As a user (not an engineer) I would have expected (for non DHCP) the range to be a requirement (along with the GW). The current method allows you to specify only the GW (with the netmask) and that's it (which is awesome now that I realize it) but I am wondering if this is what the users expect. 

I would say (again, as a user of these tools) that for fixed IP you would usually need to input both the range (with the mask) as well as the GW. So requiring to have the range isn't a big deal (it's actually more intuitive IMO).

**Comment by stuclem** [comment]
Added to release notes. Removing kind/note tag.
