### ISSUE TITLE
Log the vic-machine command line used to install a VCH in the logs.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3037]
We commonly would like to see the command line options used by vic-machine to install the VCH. We should log this so it is in one of the logs that download from vic-machine. We should also log command line changes from things like vic-machine debug etc.

This is going to be very useful for quickly resolving customer found issues.

**Comment by vburenin** [comment]
This type of log data might be sensitive, since it may include username/password, etc. I am going to replace such sensitive information with "********", however, I would like you to list things you may think are also sensitive. e.g. topology related info, such as IP addresses, host names, etc.

**Comment by mdubya66** [comment]
@hickeng I think we have this kind of detail from our security review. can you comment for @vburenin?

**Comment by vburenin** [comment]
reassigned to @mhagen-vmware on request.

**Comment by hickeng** [comment]
Updated again in #3248 for neatness, completeness and moved to Debug level
