### ISSUE TITLE
Port Layer crash if local and shared datastores specified

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#3039]
I created a VCH with the image store on a local datastore and the volume store on a shared datastore. This should be a supported configuration AFAIK. The result is a port layer crash. Details attached below.

Note that although the log says that it can't find the shared volume datastore, it's fine if you install everything that datastore.

----- Cmd line -----

./vic-machine-linux create --name=0.7.0 --target=10.118.69.238 --thumbprint=<thumb> --user=Administrator@vsphere.local --image-store=datastore1 --password=<pwd> --no-tls --bridge-network=InternalNetwork --external-network=ExternalNetwork --compute-resource=MyCL --timeout 60s --volume-store=iSCSI-nas-2/test:default

----- Vic machine output -----

vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/0.7.0$ ./create-crash.sh 
WARN[2016-11-07T18:08:55Z] Configuring without TLS - all communications will be insecure 
INFO[2016-11-07T18:08:55Z] ### Installing VCH ####                      
INFO[2016-11-07T18:08:55Z] Validating supplied configuration            
INFO[2016-11-07T18:08:55Z] vDS configuration OK on "InternalNetwork"    
INFO[2016-11-07T18:08:55Z] Firewall status: ENABLED on "/MyDC/host/MyCL/10.118.69.200" 
INFO[2016-11-07T18:08:55Z] Firewall configuration OK on hosts:          
INFO[2016-11-07T18:08:55Z]   "/MyDC/host/MyCL/10.118.69.200"            
INFO[2016-11-07T18:08:55Z] License check OK on hosts:                   
INFO[2016-11-07T18:08:55Z]   "/MyDC/host/MyCL/10.118.69.200"            
INFO[2016-11-07T18:08:55Z] DRS check OK on:                             
INFO[2016-11-07T18:08:55Z]   "/MyDC/host/MyCL/Resources"                
WARN[2016-11-07T18:08:55Z] Only one host can access all of the image/container/volume datastores. This may be a point of contention/performance degradation and HA/DRS may not work as intended. 
INFO[2016-11-07T18:08:56Z]                                              
INFO[2016-11-07T18:08:56Z] Creating virtual app "0.7.0"                 
INFO[2016-11-07T18:08:56Z] Creating directory [iSCSI-nas-2] test        
INFO[2016-11-07T18:08:56Z] Datastore path is [iSCSI-nas-2] test         
INFO[2016-11-07T18:08:56Z] Creating appliance on target                 
INFO[2016-11-07T18:08:56Z] Network role "management" is sharing NIC with "client" 
INFO[2016-11-07T18:08:56Z] Network role "external" is sharing NIC with "client" 
INFO[2016-11-07T18:08:58Z] Uploading images for container               
INFO[2016-11-07T18:08:58Z] 	"appliance.iso"                             
INFO[2016-11-07T18:08:58Z] 	"bootstrap.iso"                             
INFO[2016-11-07T18:09:03Z] Registering VCH as a vSphere extension       
INFO[2016-11-07T18:09:09Z] Waiting for IP information                   
INFO[2016-11-07T18:09:29Z] Waiting for major appliance components to launch 
INFO[2016-11-07T18:09:55Z] Collecting ef12b4d1-2cee-4d1a-a054-288a59860df9 vpxd.log 
ERRO[2016-11-07T18:09:55Z] Failed to collect ef12b4d1-2cee-4d1a-a054-288a59860df9 vpxd.log: context deadline exceeded 
WARN[2016-11-07T18:09:55Z] No log data for ef12b4d1-2cee-4d1a-a054-288a59860df9 vpxd.log 
ERRO[2016-11-07T18:09:55Z] --------------------                         
ERRO[2016-11-07T18:09:55Z] vic-machine-linux failed: Create timed out: use --timeout to add more time

----- stack trace -----

time="2016-11-07T18:12:16Z" level=panic msg="Cannot instantiate the Volume Lookup cache: error listing vols: Invalid datastore path '[iSCSI-nas-2] test/volumes'." 
time="2016-11-07T18:12:16Z" level=info msg="Shutting down port-layer-server" 
panic: (*logrus.Entry) (0x1075780,0xc4206e4f00)

goroutine 1 [running]:
panic(0x1075780, 0xc4206e4f00)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.Entry.log(0xc420010840, 0xc420237110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4205dd900, 0xc420379c00, ...)
	/drone/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x3b7
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc4205dd9a8, 0xc4205dd948, 0x1, 0x1)
	/drone/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/entry.go:158 +0x111
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.(*Entry).Panicf(0xc4205dd9a8, 0x10cfa2b, 0x2e, 0xc4205ddb68, 0x1, 0x1)
	/drone/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/entry.go:206 +0x101
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.(*Logger).Panicf(0xc420010840, 0x10cfa2b, 0x2e, 0xc4205ddb68, 0x1, 0x1)
	/drone/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/logger.go:116 +0xe7
github.com/vmware/vic/vendor/github.com/Sirupsen/logrus.Panicf(0x10cfa2b, 0x2e, 0xc4205ddb68, 0x1, 0x1)
	/drone/src/github.com/vmware/vic/vendor/github.com/Sirupsen/logrus/exported.go:147 +0x5f
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).Configure(0xc4204454c0, 0xc420441800, 0xc42041e208)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go:98 +0x1022
github.com/vmware/vic/lib/apiservers/portlayer/restapi.configureAPI(0xc420441800, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/configure_port_layer.go:118 +0x437
github.com/vmware/vic/lib/apiservers/portlayer/restapi.(*Server).ConfigureAPI(0xc42052df40)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/server.go:31 +0x3e
main.main()
	/drone/src/github.com/vmware/vic/cmd/port-layer-server/main.go:64 +0x2d6

[logs.zip](https://github.com/vmware/vic/files/576231/logs.zip)

**Comment by hickeng** [comment]
Adding the entire log portion for the handler.Configure for context.
```
time=2016-11-07T18:09:23.143696286Z level=debug msg=op=237.3 (delta:3.599µs): [NewOperation] op=237.3 (delta:1.631µs) [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).Configure:52] 
time="2016-11-07T18:09:23Z" level=debug msg="Looking for scsi controller with label SCSI0" 
time="2016-11-07T18:09:23Z" level=debug msg="Found pvscsi controller directory: 0000:03:00.0" 
time="2016-11-07T18:09:23Z" level=debug msg="Disk location format: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:%d:0" 
time="2016-11-07T18:09:23Z" level=info msg="Creating directory [datastore1] 0.7.0/VIC" 
time="2016-11-07T18:09:23Z" level=info msg="Datastore path is [datastore1] 0.7.0/VIC" 
time="2016-11-07T18:09:23Z" level=debug msg="Looking for scsi controller with label SCSI0" 
time="2016-11-07T18:09:23Z" level=debug msg="Found pvscsi controller directory: 0000:03:00.0" 
time="2016-11-07T18:09:23Z" level=debug msg="Disk location format: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:%d:0" 
time="2016-11-07T18:09:23Z" level=info msg="Adding volume store default ([iSCSI-nas-2] test)" 
time="2016-11-07T18:09:23Z" level=info msg="Creating directory [iSCSI-nas-2] test/volumes" 
time="2016-11-07T18:09:23Z" level=info msg="Refreshing volume cache." 
time="2016-11-07T18:09:23Z" level=panic msg="Cannot instantiate the Volume Lookup cache: error listing vols: Invalid datastore path '[iSCSI-nas-2] test/volumes'." 
time="2016-11-07T18:09:23Z" level=info msg="Shutting down port-layer-server" 
panic: (*logrus.Entry) (0x1075780,0xc42003f100)
```

@fdawg4l

**Comment by fdawg4l** [comment]
@corrieb the path has to exist for volumes.  I took the liberty of logging in to your VC and the path does not exist.  Can you create the directory on that datastore and try again?

We create the path you supply for images if it doesn't exist.  We don't do that for volumes.  I don't remember the merits of the argument to not create the directory for volumes, but I do remember chatting with @hickeng about it.  If we want to create the directory, it would be a trivial change.

**Comment by fdawg4l** [comment]
ah, not a bug :-)

**Comment by fdawg4l** [comment]
> @corrieb the path has to exist for volumes. 

Scratch that.  We definitely create the directory if its not there.

**Comment by fdawg4l** [comment]
I can repro locally and im getting the same timeout.  I don't have iscsi either.

```
$ ./vic-machine-linux create -f -p "" -t 192.168.8.128 --user root --no-tlsverify --image-store=datastore1/test --volume-store=datastore2/testes:default
INFO[2016-11-07T11:39:21-08:00] Generating self-signed certificate/key pair - private key in ./virtual-container-host/key.pem 
WARN[2016-11-07T11:39:21-08:00] Configuring without TLS verify - client authentication disabled 
WARN[2016-11-07T11:39:21-08:00] iso file "appliance.iso" version "v0.4.0-0-831887f" inconsistent with installer version "v0.7.0-0-bbc7370" 
WARN[2016-11-07T11:39:21-08:00] iso file "bootstrap.iso" version "v0.4.0-0-831887f" inconsistent with installer version "v0.7.0-0-bbc7370" 
INFO[2016-11-07T11:39:21-08:00] ### Installing VCH ####                      
INFO[2016-11-07T11:39:21-08:00] Validating supplied configuration            
INFO[2016-11-07T11:39:21-08:00] Firewall status: ENABLED on "/ha-datacenter/host/localhost.localdomain/localhost.localdomain" 
INFO[2016-11-07T11:39:21-08:00] Firewall configuration OK on hosts:          
INFO[2016-11-07T11:39:21-08:00]   "/ha-datacenter/host/localhost.localdomain/localhost.localdomain" 
WARN[2016-11-07T11:39:21-08:00] Evaluation license detected. VIC may not function if evaluation expires or insufficient license is later assigned. 
INFO[2016-11-07T11:39:21-08:00] License check OK                             
INFO[2016-11-07T11:39:21-08:00] DRS check SKIPPED - target is standalone host 
INFO[2016-11-07T11:39:21-08:00]                                              
INFO[2016-11-07T11:39:21-08:00] Creating Resource Pool "virtual-container-host" 
INFO[2016-11-07T11:39:22-08:00] Creating VirtualSwitch                       
INFO[2016-11-07T11:39:22-08:00] Creating Portgroup                           
INFO[2016-11-07T11:39:22-08:00] Creating directory [datastore2] testes       
INFO[2016-11-07T11:39:22-08:00] Datastore path is [datastore2] testes        
INFO[2016-11-07T11:39:22-08:00] Creating appliance on target                 
INFO[2016-11-07T11:39:22-08:00] Network role "client" is sharing NIC with "external" 
INFO[2016-11-07T11:39:22-08:00] Network role "management" is sharing NIC with "external" 
INFO[2016-11-07T11:39:22-08:00] Uploading images for container               
INFO[2016-11-07T11:39:22-08:00]         "appliance.iso"                             
INFO[2016-11-07T11:39:22-08:00]         "bootstrap.iso"                             
INFO[2016-11-07T11:39:27-08:00] Waiting for IP information                   
INFO[2016-11-07T11:39:41-08:00] Waiting for major appliance components to launch 
INFO[2016-11-07T11:42:21-08:00] Collecting ha-host hostd.log                 
ERRO[2016-11-07T11:42:21-08:00] Failed to collect ha-host hostd.log: context deadline exceeded 
WARN[2016-11-07T11:42:21-08:00] No log data for ha-host hostd.log            
ERRO[2016-11-07T11:42:21-08:00] --------------------                         
ERRO[2016-11-07T11:42:21-08:00] vic-machine-linux failed: Create timed out: use --timeout to add more time
```

**Comment by fdawg4l** [comment]
Doh!  I made a booboo.  All datastores for volumes point to the default datastore :-).  Because that's helpful.  

I'll take care of this.  Easy fix.
