### ISSUE TITLE
Migrate imagec/portlayer integration test to use ESX

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#304]
The current integration test (see `tests/imagec.bats`) runs the port layer daemon and imagec, tries to retrieve the photon container, and verifies the image downloaded is as expected.  In order for this test to pass after #294 is merged, the port layer will need to run in a VM (appliance vm?) on an esx instance which it can than attach and detach vmdks as layers are written.

We need an integration setup that installs an appliance vm with the port layer installed, provides creds to it (or stands up an authenticated agent with which the PL passes vmomi commands through it to esx), and works through the tests like we do currently with the local store.

**Comment by hickeng** [comment]
Bringing this back to TODO now that the new drone deployment is almost complete.

**Comment by fdawg4l** [comment]
Closing this as the robot test framework subsumes this.
