### ISSUE TITLE
govc-adding an ESX 5.5 host to distributed switch fails

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#3052]
VC_VERSION  4531673
ESX_VERSION 3029944

nimbus-esxdeploy ${name} --disk=48000000 --ssd=24000000 --memory=8192 --nics 2 3029944

KEYWORD Nimbus-Util . Add Host To Distributed Switch /ha-datacenter/host/cls
Start / End / Elapsed: 	20161107 12:12:42.842 / 20161107 12:12:44.009 / 00:00:01.167
00:00:00.000 KEYWORD BuiltIn . Log To Console \nAdd host(s) to the distributed switch
00:00:01.163 KEYWORD ${out} = OperatingSystem . Run govc dvs.add -dvs=${dvs} -pnic=vmnic1 ${host}
00:00:00.002 KEYWORD BuiltIn . Should Contain ${out}, OK
Documentation: 	

Fails if container does not contain item one or more times.
Start / End / Elapsed: 	20161107 12:12:44.007 / 20161107 12:12:44.009 / 00:00:00.002
12:12:44.009 	FAIL 	'
[K[07-11-16 20:12:43] adding 3 hosts to dvs /ha-datacenter/network/test-ds... 
[K[07-11-16 20:12:43] adding 3 hosts to dvs /ha-datacenter/network/test-ds... (0%)
[K[07-11-16 20:12:44] adding 3 hosts to dvs /ha-datacenter/network/test-ds... Error: The operation is not supported on the object.
govc: The operation is not supported on the object.' does not contain 'OK'

**Comment by rajanashok** [comment]
Drone Test execution log

[DRONE] starting job #1
[info] Pulling image vmware-docker-ci-repo.bintray.io/integration/vic-test:1.14
$ pybot -d 5-5-Heterogenous-ESXi tests/manual-test-cases/Group5-Functional-Tests/5-5-Heterogenous-ESXi.robot
==============================================================================
5-5-Heterogenous-ESXi :: Test 5-1 - Distributed Switch                        
==============================================================================
Test                                                                  
Starting test...

Deploying Nimbus ESXi server: ESX-6193

Disable TLS on the host
Successfully deployed new ESXi server - svc.victestuser-ESX-6193

Deploying Nimbus ESXi server: ESX-7194

Disable TLS on the host
Successfully deployed new ESXi server - svc.victestuser-ESX-7194

Deploying Nimbus ESXi server: ESX-2955

Disable TLS on the host
Successfully deployed new ESXi server - svc.victestuser-ESX-2955

Deploying Nimbus vCenter server: VC-5815
Successfully deployed new vCenter server - svc.victestuser-VC-5815
Create a datacenter on the VC
Create a cluster on the VC
Add ESX host to the VC

Create a distributed switch

Create three new distributed switch port groups for management and vm network traffic

Add host(s) to the distributed switch
| FAIL |
[07-11-16 23:57:16] adding 3 hosts to dvs /ha-datacenter/network/test-ds... Error: The operation is not supported on the object.
govc: The operation is not supported on the object.' does not contain 'OK'
------------------------------------------------------------------------------
5-5-Heterogenous-ESXi :: Test 5-1 - Distributed Switch                | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /drone/src/github.com/vmware/vic/5-5-Heterogenous-ESXi/output.xml
Log:     /drone/src/github.com/vmware/vic/5-5-Heterogenous-ESXi/log.html
Report:  /drone/src/github.com/vmware/vic/5-5-Heterogenous-ESXi/report.html
[info] build failed (exit code 1)
[DRONE] finished job #1
[DRONE] exit code 1
[DRONE] job #1 failed
[DRONE] build failed

**Comment by rajanashok** [comment]
${vc} = svc.victestuser-VC-5815 	
${vc-ip} = 10.160.5.57

**Comment by dougm** [comment]
vmware/govmomi#626

**Comment by dougm** [comment]
Created a new release that includes the fix: https://github.com/vmware/govmomi/releases/tag/v0.11.3

Will leave it to you guys to update the image and add the flag to the robot calls.
