### ISSUE TITLE
Document that volume stores should not be shared.

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3054]
Per https://github.com/vmware/vic/issues/3046#issuecomment-258979301. Probably merits updating the 0.7 / beta 2 docs.

**Comment by stuclem** [comment]
Added note to say that volume stores should not be shared, and fixed the descriptions of the resulting folder layouts.

Changes are in https://github.com/stuclem/vic/commit/417a8dea2577753f0a7fe3dce509ea9a92b7b045.

@emlin, is this OK? Thanks!

**Comment by hickeng** [comment]
lgtm
