### ISSUE TITLE
Documentation: rename --external-network to --public-network

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3056]
Per discussion in https://github.com/vmware/vic/issues/3008.

**Comment by stuclem** [comment]
Mostly done in https://github.com/vmware/vic/commit/9ec82fffc9bed2bd32e7955766a596388fe519d4. 

The remaining area of confusion is in https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/network_use_cases.md, which refers to both the VIC public network (the network formerly known as "external") and the Docker version of "external networks", which correspond to VIC's container networks.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3008 was initially implemented in PR https://github.com/vmware/vic/pull/3164, but that PR was closed without merging. 

I have reverted the docs back to external network in https://github.com/stuclem/vic/commit/2abc80053813bda3a76b440b9f0d9b4e31e958f7. Moving back to backlog pending the implementation of https://github.com/vmware/vic/issues/3008.

**Comment by mlh78750** [comment]
We will be merging the changes from #3164 in eventually. We needed to fix upgrade and test that as well as the changes in #3164 before we commit it. You can expect that before 0.8.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3008 is now implemented in PR https://github.com/vmware/vic/pull/3214 (not merged yet).

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/3214 is now merged.

**Comment by stuclem** [comment]
Fix is in https://github.com/stuclem/vic/commit/5880f4eaa676af4bcda5a864ed8fab2f151acdc3.
