### ISSUE TITLE
Fixed IP VCH vm configuration does not honour the default DNS 

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#3060]
version 0.7.0

When setting a static IP address to the VCH, when the flag `--dns-server` is not populated we set the DNS to the GW specified (Vs. 8.8.8.8 as the help suggests): 

```
--dns-server value                               DNS server for the client, external, and management networks. Defaults to 8.8.8.8 and 8.8.4.4 when not using DHCP 
```

Workaround: when setting a fixed IP explicitly use `--dns-server 8.8.8.8`

**Comment by mlh78750** [comment]
@stuclem: can we add this to the release notes for 0.7.0 please.

**Comment by bbrundert** [comment]
The install guide (https://vmware.github.io/vic/assets/files/pdf/vic_installation.pdf) also has a documentation bug on page 32. ```--dns-server```is the official flag but in the example it says 
```
--dns=172.16.10.10
--dns=172.16.10.11
```

**Comment by mlh78750** [comment]
Adding kind/docs for https://github.com/vmware/vic/issues/3060#issuecomment-259260958

**Comment by stuclem** [comment]
@bbrundert I have fixed the typo for `--dns-server`. I'll publish an update shortly. Thanks! @mlh78750 I'll add this to the release notes now.

**Comment by stuclem** [comment]
Release notes updated: https://github.com/vmware/vic/releases/edit/v0.7.0 (see first entry under Known Issues).

**Comment by stuclem** [comment]
Doc update published to github.io:
https://vmware.github.io/vic/assets/files/html/vic_installation/vch_installer_options.html#static-ip

**Comment by stuclem** [comment]
Updated the doc on the beta site too.
