### ISSUE TITLE
Documentation: create a glossary of major terms

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3072]
@hickeng suggests a glossary of terms, to include descriptions of the key components/terms of VIC. Candidates for the list include:

- Each type of network
- Published ports 
- Port layer
- Tether?

Some of these descriptions exist, but they are scattered through the doc. It would be good to consolidate them into one reference.

**Comment by stuclem** [comment]
Moving to 0.9 for lack of time. The overview covers a lot of the major terms.

**Comment by hickeng** [comment]
Issue moved to [vmware/vic-product #183](https://github.com/vmware/vic-product/issues/183) via [**ZenHub**](https://www.zenhub.com/)
