### ISSUE TITLE
Documentation: Explain placement of volumes folder 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3073]
Per @emlin in https://github.com/vmware/vic/issues/3046#issuecomment-259162554:

------

...the reason for volume not to use same solution with image store, is just because user will need to reuse volumes created by other VCH.
Though we still didn't really reuse same volume vmdk between two different container vms.

The case is like user created one VCH, and then created volumes and write data into those volumes from containers. 
But later on, this VCH can be removed with volumes still there. Those volumes with data can be reused by later created VCH, with specified volume store point to existing datastore folder.

In this process, we don't want to dynamically create folder, to make sure the old volumes vmdk can be find by new VCH.

------

This should go in the description of the `--volume-store` option.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/2899#issuecomment-259312380

**Comment by stuclem** [comment]
Added the following in the description of `--volume-store`:

-----

The `vic-machine create` creates command creates the `volumes` folder independently of the folder for the VCH files so that you can share volumes between VCHs. If you delete a VCH, any volumes that the VCH managed will remain available in the datastore unless you specify the `--force` option when you delete the VCH.  You can then assign an existing volume store that already contains data to a newly created VCH. 

-----

@emlin, is this OK? Thanks!

We also include the following statement, which seems to contradict what you said in your comment above:

----

**IMPORTANT**: If multiple VCHs will use the same datastore for their volume stores, specify a different datastore folder for each VCH. Do not designate the same datastore folder as the volume store for multiple VCHs.

----

@emlin should I remove the statement above?

**Comment by emlin** [comment]
The description for volume-store is good. Just it's slightly contradict with the notes. What about at a definition in the note, that is to say if multiple vchs will use the same datastore for their volume stores at the same time, then specify different datastore.

**Comment by stuclem** [comment]
Reviewed as part of global doc review. Closing.
