### ISSUE TITLE
vic-admin should work even it can't speak to vsphere.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3082]
When the customer hit #3081 the port layer would just quit when it couldn't connect to the target. tether/vic-init would restart it and it would just quit again. During this time you could connect to vic-admin but it never returned any data. When the rest of the system is not working we need vic-admin the most. See also #3079.

**Comment by mlh78750** [comment]
@corrieb reports that when he was in a similar situation it did work.

**Comment by mlh78750** [comment]
Turns out the log show that vic-admin was crashing from it's inability to reach vsphere. Dup of #2811.

**Comment by anchal-agrawal** [comment]
@mlh78750 Those logs would be very helpful to ensure that I'm addressing this particular issue as part of #2811. Do we still have access to them?

**Comment by mlh78750** [comment]
[logs.zip](https://github.com/vmware/vic/files/584610/logs.zip)
