### ISSUE TITLE
vicadmin leaking vSphere sessions

### ISSUE THREAD

**Issue by dougm** [vmware/vic#3083]
With #2883 hitting the vicadmin page in chrome, even without logging in, creates 2 vSphere sessions.  Hitting the page with curl creates 1 session.  Example:

```
% govc session.ls | wc -l
6
```

Open vicadmin in Chrome w/o login, e.g. https://172.16.124.186:2378/authentication

```
% govc session.ls | wc -l
8
```

Reload the page:

```
% govc session.ls | wc -l
10
```

Hit it with curl:

```
% curl -sk https://172.16.124.186:2378/authentication >/dev/null
% govc session.ls | wc -l
11
```

Note that PR #2993 sets the User-Agent header, so you can see which vic component is creating the session(s).

**Comment by dougm** [comment]
@hickeng mentioned @anchal-agrawal was looking at removing a call to the validator, which could be related.

**Comment by anchal-agrawal** [comment]
@dougm Yes, I'm removing the validator requirement from the login page, so we should see fewer sessions being created/leaked.

**Comment by hickeng** [comment]
Adding this to 0.8 as it both a potential DoS path against vSphere and impacts diagnostics

**Comment by gigawhitlocks** [comment]
I will look into this while I address #3088

**Comment by gigawhitlocks** [comment]
This should be resolved, at least for the most part. Need to verify that we don't still spawn a session each time that a user w/ cert auth hits a protected endpoint, but w/r/t browser-based users now, only one session will be created per login and this session will be destroyed automatically after 24 hours or if the user logs out.

**Comment by hmahmood** [comment]
@gigawhitlocks Should we close this issue?

**Comment by mdubya66** [comment]
Closing based on the above.
