### ISSUE TITLE
Improve customer facing documentation for networking.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3085]
Will edit details in a bit.

two things, config options for vic-machine and the firewall requirements for the vc/hosts

**Comment by stuclem** [comment]
@mlh78750 we do have https://github.com/vmware/vic/issues/3006 open already to improve the network overview doc (and diagrams) but if you have specific comments about the `vic-machine create` networking options and the required ports, let's keep this one open too. Thanks!

**Comment by stuclem** [comment]
Dup of https://github.com/vmware/vic/issues/3006
