### ISSUE TITLE
vic-admin: use vim session cookie and depend on vsphere session management

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3088]
Update vicadmin to store the govmomi session cookie as the cached credentials, instead of the user supplied credentials.
This allow us to match the session expiration behaviour configured for vSphere and to honor explicit cancellation of an individual session by a viadmin.

It may be viable to address #3083 at the same time.

This is follow on work to #2883

**Comment by dougm** [comment]
govc persists session by default, it does so on disk but vic-admin can do it in memory.  The only piece it should need is session cookie, example from govc:

```
% <~/.govmomi/sessions/008ef12fdbbd831054672b36dcd1710def345b27 jq .SoapClient.Cookies
[
  {
    "Name": "vmware_soap_session",
    "Value": "9318c3b7515e2ed6a8f6425160f31cdc6932fb33",
     ...
  }
]
```

You can test if a session cookie is still valid like so: https://github.com/vmware/govmomi/blob/master/govc/flags/client.go#L356
If that fails, will need to Login again.

**Comment by hickeng** [comment]
@gigawhitlocks I've also noticed that with chrome I'm getting redirected to the login page, even if my client certificate is correct.
It doesn't happen if I open an anonymous window and use that - I'm not sure if the certificate isn't being offered or whether chrome is for some reason caching the temporary redirection, but something to be aware of.

**Comment by gigawhitlocks** [comment]
If Chrome is caching the redirect that's misbehavior on Chrome's part, which would surprise me. I'll test that after I've got a couple of bugfixes on my branch that may be related.
