### ISSUE TITLE
vic-machine create: remove --use-rp

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3090]
No customer specifically requires resource pool, instead of vApp to manage vch, so remove the option.

**Comment by cgtexmex** [comment]
Is this only in regards to documentation or are we going to remove functionality?  As I mentioned to you @emlin I don't care for our use (from my perspective misuse) of the vApp -- I'd be a customer utilizing resource pools.

**Comment by stuclem** [comment]
@cgtexmex, both. In the first instance, I wanted to know whether we should remove it from the doc, but @emlin and @hickeng see no reason to keep it at all.

**Comment by emlin** [comment]
tbh, I'm fine with both options. @hickeng mentioned no other customer, prefer to use this feature.
Another thing is that although we make the option hidden, we're not using hidden options exactly hidden from customer, instead, we're using that as advanced options.
So --use-rp gonna be something have to be explained in document.
but let's open this issue for discussion. If our final decision is to keep this option, we can add integration test cases to make sure it works.

**Comment by hickeng** [comment]
Was a dup of #5117 - closing for the same reason (we now need this option and resource pool is explicit customer preference for at least one customer).
