### ISSUE TITLE
Document how to collect logs manually if VCH Admin is offline

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3093]
Per https://github.com/vmware/vic/issues/3079. Workaround for now is the enable SSH with `vic-machine debug` and then capture the logs with `scp -r` to the VCH. If https://github.com/vmware/vic/issues/3079 doesn't make it into GA, then we'll remove workaround and document the new process via `vic-machine debug`.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3079 won't be in GA, so we do need to write up the workaround.

**Comment by npakrasi** [comment]
Added to the log bundle topic: If the VCH Admin portal is offline, use `vic-machine debug` to enable ssh and `scp -r` to capture the logs to the virtual container host.
