### ISSUE TITLE
Document that VCH Admin includes system time of endpoint VM 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3094]
Per https://github.com/vmware/vic/issues/3086, which is flagged for 0.9 but is also currently In Progress.

**Comment by stuclem** [comment]
Just saw the system time in the VCH Admin portal. Updated the following topics:

-[Access the Administration Portal for a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/access_vicadmin.md)
-[Connections Fail with Certificate Errors when Using Full TLS Authentication with Trusted Certificates](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/ts_clock_skew.md)

@anchal-agrawal does this cover it? Thanks!

Changes are in https://github.com/stuclem/vic/commit/ba242aae1a5389cc045f13a49c637490438b8b7b.

**Comment by anchal-agrawal** [comment]
Perfect, thanks @stuclem! Apologies for the delay.

**Comment by stuclem** [comment]
Reviewed as part of global doc review. Closing.
