### ISSUE TITLE
NSX deployment and distributed port group creation

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#31]
We need to have well documented workflow for NSX deployment and DPG creation:
1. manual steps initially
2. automated for nested test topologies
3. automation for _docker network_ integration

This investigation should document at least (1) and generate additional issues for (2) and (3)

**Comment by hickeng** [comment]
post GA

**Comment by stuclem** [comment]
@npakrasi, looks like we should remove NSX from https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_admin/interop.md.

**Comment by mdubya66** [comment]
not a 1.1 requirement. making low
