### ISSUE TITLE
Document using Harbor with VIC Engine using self signed certs

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3102]
We don't have a method to upload certs to VIC Engine to use with Harbor.  For 0.8.0, we need to document how to manually perform this as a workaround.

**Comment by sflxn** [comment]
https://github.com/vmware/harbor/issues/1063

**Comment by mobla** [comment]
Yes, this is very important!. At present we are able to do 
a. Windows7-Toolbox/Linux (photon) docker works fine with Harbor https (Public CA signed) cert
b. Windows7-Toolbox/Linux (photon) docker works fine with Harbor https (Self-Signed CA) cert
    - gotcha: need to have certs under /etc/docker/certs.d/<FQDN>/ca.cert and restart docker
c. VIC Linux (photon) (VCH-TLS) - Harbor https (Public CA signed) cert works ok

Waiting to try out the VCH-TLS with Self Signed CA cert to private registry. Thanks Loc for looking into this..

Thanks,
Murali

**Comment by stuclem** [comment]
Actually, this is the user doc issue. The docs that @sflxn merged in https://github.com/vmware/vic/pull/3225 are design/engineering docs. Reopening this issue for conversion of @sflxn 's doc into user doc.

**Comment by stuclem** [comment]
I'm pretty certain that this issue is covered by https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/deploy_vch_harbor.md.

@sflxn can you please confirm?
