### ISSUE TITLE
Document that vic-machine checks firewall compliance for specified networks

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3119]
Per https://github.com/vmware/vic/issues/2748, which is implemented in PR https://github.com/vmware/vic/pull/3111 (not merged yet).

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/3111 is now merged.

**Comment by stuclem** [comment]
Added the following to the Networking options:

----

When you specify different network interfaces for the different types of traffic, `vic-machine create` checks that the firewalls on the ESXi hosts allow connections to port 2377 from those networks. If access to port 2377 on one or more ESXi hosts is subject to IP address restrictions, and if those restrictions block access to the network interfaces that you specify, `vic-machine create` fails with a firewall configuration error:
<pre>Firewall configuration incorrect due to allowed IP restrictions on hosts: 
"/ha-datacenter/host/localhost.localdomain/localhost.localdomain" 
Firewall must permit dst 2377/tcp outbound to the VCH management interface
</pre>

----

@andrewtchin, is this correct? Would this apply to all of the management/client/container/bridge/external networks, or just management, as in the example? 

Change is in https://github.com/stuclem/vic/commit/322f22fd3877623234643133ec0a48a53a40e0d2

**Comment by andrewtchin** [comment]
@stuclem this check only applies to the management network. I would also document that if the management interface is set to use DHCP, we don't know the VCH's IP address at the time when this check is performed, so we are unable to fully assess whether the firewall would permit tether traffic with allowed IPs. (see the last sample output in the PR)

**Comment by stuclem** [comment]
Thanks @andrewtchin. Moved this out of the general section on networks and into the management network section. Updated as follows:

---


When you create a virtual container host, `vic-machine create` checks that the firewall on ESXi hosts allows connections to port 2377 from the management network of the virtual container host. If access to port 2377 on ESXi hosts is subject to IP address restrictions, and if those restrictions block access to the management network interface, `vic-machine create` fails with a firewall configuration error:
<pre>Firewall configuration incorrect due to allowed IP restrictions on hosts: 
"/ha-datacenter/host/localhost.localdomain/localhost.localdomain" 
Firewall must permit dst 2377/tcp outbound to the VCH management interface
</pre>

**NOTE**: If the management network uses DHCP, `vic-machine` checks the firewall status of the management network before the virtual container host receives an IP address. It is therefore not possible to fully assess whether the firewall permits the IP address of the virtual container host. 


-----

**Comment by andrewtchin** [comment]
maybe include in the NOTE an example of the warning?
```WARN[2016-11-10T15:58:16-06:00] Unable to fully verify firewall configuration due to DHCP use on management network 
WARN[2016-11-10T15:58:16-06:00] VCH management interface IP assigned by DHCP must be permitted by allowed IP settings 
WARN[2016-11-10T15:58:16-06:00] Firewall allowed IP configuration may prevent required connection on hosts: 
WARN[2016-11-10T15:58:16-06:00] 	"/ha-datacenter/host/localhost.localdomain/localhost.localdomain" 
INFO[2016-11-10T15:58:16-06:00] Firewall must permit dst 2377/tcp outbound to the VCH management interface```

**Comment by stuclem** [comment]
Thanks @andrewtchin. Added the warning under the NOTE. Closing!
