### ISSUE TITLE
Document that logs include vic-machine command used to deploy VCH

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3120]
Per https://github.com/vmware/vic/issues/3037.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3037 is merged in PR https://github.com/vmware/vic/issues/3132.

**Comment by npakrasi** [comment]
Added to log_bundles.md:
Logs also include vic-machine commands used during VCH installation to help you resolve issues.

**Comment by stuclem** [comment]
Covered by global doc review. Closing.
