### ISSUE TITLE
Document remaining aspects of docker compose up

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3122]
Per https://github.com/vmware/vic/issues/431

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/431 is in 0.9

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3648 adds support for docker compose bundle

**Comment by sflxn** [comment]
@stuclem Was this an issue you wrote for yourself?

**Comment by stuclem** [comment]
@sflxn yes it was, for doc tracking purposes.

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#81
