### ISSUE TITLE
OT, apologies. IRC channel?

### ISSUE THREAD

**Issue by zchef2k** [vmware/vic#3144]
Is there an active IRC community in which you all participate? As a customer and advocate of containerizing enterprise workloads I'd love to communicate with you all. Unfortunately I can't find a great entry point other than with reps and SE's.

**VIC Version:**

0.1 / master / commit ID

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by anchal-agrawal** [comment]
Hi @zchef2k, please feel free to get in touch via Gitter at https://gitter.im/vmware/vic.

**Comment by mdubya66** [comment]
https://github.com/vmware/vic/blob/master/CONTRIBUTING.md also points out our Slack channel. It requires registering though so we kept the gitter open as well.
