### ISSUE TITLE
Document how and when to specify a gateway routing destination for client and management networks

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3149]
Per https://github.com/vmware/vic/issues/3081 and https://github.com/vmware/vic/issues/3125, that are fixed in https://github.com/vmware/vic/pull/3129 (merged).

**Comment by stuclem** [comment]
@mlh78750 and @hmahmood, I'm having a hard time getting this to work. I'm trying to set a static IP on the client network (which incidentally is the only way in which I can implement and test `TLSVERIFY`, because the network on which I am deploying my VCHs doesn't have a DNS server) but am being stumped by the new requirement to specify the default route in `--client-network-gateway`. I know the address of my default gateway, but (due to ignorance of networking) I have no idea how to work out/guess what the routing destination should be based on that gateway address or the static IP that I am trying to set. I tried a few things based on the examples given in `vic-machine create -x` and in https://github.com/vmware/vic/issues/3081, but each time end up with `Unable to determine address to use with remote certificate, skipping API liveliness checks`, which is the message that I always see when I have issues with addresses (including when I try to set `--tls-cname`, but that's another story). So, how do I find out what the routing destination for my network should be?

Another thing: the heading of https://github.com/vmware/vic/issues/3125 is "When **client interface not shared with external**, clients may not be able to connect". In my setup, the client network and external network _do_ share a NIC. From the title of issue https://github.com/vmware/vic/issues/3125, I would guess that this would mean that I wouldn't hit the default route issue anyway. So, if the default route only poses a problem when the client/management networks are not sharing a NIC with the external network, isn't it making things overly complicated to require that a routing destination be set in all cases, even when the NIC is shared? Like I said before, my networking knowledge is shaky at best, so I might be barking in entirely the wrong forest, let alone up the wrong tree....

**Comment by mlh78750** [comment]
@stuclem, If client and external networks are sharing NIC then the default route on the external interface will allow you to connect without specifying a gateway for the client network. You simply don't need the client-gateway if you are sharing with the external interface. Make sure and set the gateway for the public (used to be called external) network and everything should work. And that gateway setting does not require routes since it is the default route. If you'd like to discuss this morning, give me call and we can walk through the way it works.

**Comment by stuclem** [comment]
Thanks @mlh78750 I'll have a play and see how it goes.

**Comment by stuclem** [comment]
The original implementation of this change to `--management/client-network-gateway` is being modified in https://github.com/vmware/vic/issues/3197. Gateway will now only need to be specified when client/management networks are not sharing a NIC with the external network. So, I will make the doc update once https://github.com/vmware/vic/issues/3197 is fixed, listing the circumstances in which you need to specify the routing destination and the circumstances in which you don't.

**Comment by stuclem** [comment]
Actually, since I had already half-written this up yesterday while battling with the issues described in https://github.com/vmware/vic/issues/3197, and while it's all fresh in my head, I have attempted to write up how `vic-machine` will behave once https://github.com/vmware/vic/issues/3197 is fixed.

@hmahmood and @mlh78750, please can you take a look at the whole of the section [Options for Specifying a Static IP Address for the Virtual Container Host Endpoint VM](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#options-for-specifying-a-static-ip-address-for-the-virtual-container-host-endpoint-vm)? Thanks!

**Comment by stuclem** [comment]
The implementation of https://github.com/vmware/vic/issues/3197 has changed, and is in PR https://github.com/vmware/vic/pull/3220. 

See https://github.com/vmware/vic/issues/3197#issuecomment-261282083 and https://github.com/vmware/vic/issues/3197#issuecomment-261283334 for details. Moved back to In Progress.

**Comment by stuclem** [comment]
Updated  [Options for Specifying a Static IP Address for the Virtual Container Host Endpoint VM](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#options-for-specifying-a-static-ip-address-for-the-virtual-container-host-endpoint-vm) and the example [Set a Static IP Address on the Different Networks](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#set-a-static-ip-address-on-the-different-networks) to take the new implementation into account.

Changes are in https://github.com/stuclem/vic/commit/4ce430126dc61a1b4b0191c34d55180cd838323a.

@mlh78750, @andrewtchin and @hmahmood can you please take a look? Thanks!

**Comment by andrewtchin** [comment]
For paragraph two on https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#options-for-specifying-a-static-ip-address-for-the-virtual-container-host-endpoint-vm
#3197 requires the user to specify the static IP for any network roles (client, external, management) that share a port group with external through the `--external-network-*` options:
```
You can only specify one static IP address on a given port group. If more than one of the client, external, or management networks shares a port group, you can only specify an IP address on one of those networks. The same address is then used for all of the networks that share that port group. 
If any network roles (client or management) share a port group with external network, the static IP must be specified on the external network.
```
Feel free to reword that or discuss with me - that's difficult to convey. 

Now that I'm getting to the fifth paragraph that does better convey the requirement. Also the default value for `--tls-cname` is *not* available when specifying `--external-network` so the user *must* explicitly provide that as a result of #3197
```
If the client network shares a port group with the external network you cannot set a static IP address for the endpoint VM on the client network. In this case, to use a static IP you MUST set a static IP address on the external network and also specify `--tls-cname` to generate trusted CA certificates (or use one of the other TLS options).
```

**Comment by andrewtchin** [comment]
See my latest 2 comments on #3197 for example vic-machine output

**Comment by stuclem** [comment]
Thanks @andrewtchin. Duly updated with your comments. Changes are in https://github.com/stuclem/vic/commit/048a962a3e4d68dae48bbe65ddc2751cc6efd04f, but since I have juggled content around a bit, I would really appreciate it if you would look at the following sections again in their entirety:

- [Options for Specifying a Static IP Address for the Virtual Container Host Endpoint VM](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#options-for-specifying-a-static-ip-address-for-the-virtual-container-host-endpoint-vm)
- [Example: Set a Static IP Address for the Virtual Container Host Endpoint VM on the Different Networks](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#set-a-static-ip-address-for-the-virtual-container-host-endpoint-vm-on-the-different-networks)

Thanks!

**Comment by stuclem** [comment]
More changes to `--cert-path` and static IPs are in PR https://github.com/vmware/vic/pull/3306. Moving back to In Progress to check.

**Comment by stuclem** [comment]
@andrewtchin, looking at https://github.com/vmware/vic/pull/3306, it looks like @hickeng has fixed things so that you can set a static IP on public without also having to specify `--tls-cname`. I just tested this with build 7234 from yesterday and it worked a charm. So, I have removed the requirement to specify `--tls-cname` when specifying a static IP on the public network.

Changes are in https://github.com/stuclem/vic/commit/8a2e5dba4ae1869b29f4857d5e4549484e0a2736.

**Comment by stuclem** [comment]
Reviewed as part of global doc review. Closing.
