### ISSUE TITLE
VCH name is title-cased on vicadmin

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3158]
For a VCH named `vch-7`, vicadmin shows

<img width="468" alt="vicadmin" src="https://cloud.githubusercontent.com/assets/4361620/20275594/cc364cba-aa5e-11e6-82b6-4a767d58dfff.png">

We should preserve the case supplied by the user.

**Comment by mdubya66** [comment]
cosmetic but should be fixed in v0.8 if we can get to it
