### ISSUE TITLE
Document recent changes to VCH admin's dashboard page

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3174]
Per #3106, there have been a few changes to VCH admin's dashboard page.

* `Network Connectivity` has been renamed to `Registry and Internet Connectivity`.
* If the VCH is unable to connect to vSphere:
  * The VCH status icon is yellow and a message explaining why the VCH is unable to connect to vSphere is displayed below it.
  * Firewall and License status checks are disabled because we can't correctly determine their validity without a vSphere session connection.
  * Datastore info is not displayed in the `Virtual Container Host Info` card.
  * Logs that require a vSphere connection are disabled and an error message is displayed. The user can still download the log bundle (w/o container logs) to troubleshoot the issue.

This might require changes to `doc/user_doc/vic_admin/vicadmin_status_ref.md` and related docs.

**Comment by stuclem** [comment]
Thanks @anchal-agrawal, I missed these changes. This also affects https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/log_bundles.md. 

@npakrasi can you please take a look?

**Comment by npakrasi** [comment]
Added to log bundles topic: If the virtual container host is unable to connect to vSphere, logs that require a vSphere connection are disabled, and you get an error message. You can download the log bundle to troubleshoot the error.

**Comment by stuclem** [comment]
Updates are still required in doc/user_doc/vic_admin/vicadmin_status_ref.md per Anchal's first comment. Reopening.

**Comment by stuclem** [comment]
Updated the following topics:

- []()
- []()
- []()

**Comment by anchal-agrawal** [comment]
Looks good, thanks Stuart!

**Comment by anchal-agrawal** [comment]
Closing as the changes are in.
