### ISSUE TITLE
Need to add an upgrade test to full-ci test suite.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3175]
I'd like for us to add at least one test where the previous OSS released version is installed and then upgraded to the current build. We should then do a some basic use case tests with the upgraded install.

**Comment by mlh78750** [comment]
cc: @mhagen-vmware

**Comment by mdubya66** [comment]
We currently have https://github.com/vmware/vic/blob/master/tests/test-cases/Group11-Upgrade/11-01-Upgrade.md

**Comment by mdubya66** [comment]
which appears to need some TLC since #2554 was fixed

**Comment by mlh78750** [comment]
And it didn't catch the external network to public network conversion issue when @hmahmood made the changes for #3008. So if nothing else, we need to see if we can beef up the post upgrade tests.

**Comment by mlh78750** [comment]
The fact that #3180 just got found as @hmahmood was trying to fix #3008 shows that we need to have this in the test suites. Moving this into 0.8.

**Comment by mhagen-vmware** [comment]
This blocked on existing issues that @hmahmood is fixing.  Right now upgrade does not really work.
