### ISSUE TITLE
Create VCH on physical ESX 6.0 (GA-#2494585) host hangs from windows client machine (100% reproducible)

### ISSUE THREAD

**Issue by mobla** [vmware/vic#3192]
Windows 7, Docker Toolbox 
Docker Version
Client (windows/amd64): 1.12.2
Server (linux/amd64): 1.12.3
Docker machine version: 0.8.2 build e18a919
**VIC: v0.7.0-6507-6c4627d**
vSphere 6.0 GA: ESX ob-2494585

> ./vic-machine-windows.exe create --name VCH1 --target 10.xx --user root --password 'ca$hc0w' --no-tls  --image-store w1-vimcat24-local --vol
ume-store=w1-xx-local/registry:default --insecure-registry 10.xxx:80 --thumbprint C9:6F:ED:44:54:48:D9:F6:B6:6A:3B:13:46:55:F0:45:15:F8:
51:3B
←[33mWARN←[0m[2016-11-15T16:21:50-08:00] Configuring without TLS - all communications will be insecure
←[34mINFO←[0m[2016-11-15T16:21:50-08:00] ### Installing VCH ####
←[34mINFO←[0m[2016-11-15T16:21:51-08:00] Validating supplied configuration
←[34mINFO←[0m[2016-11-15T16:21:51-08:00] Firewall status: DISABLED on "/ha-datacenter/host/w1-vim-cat-24.eng.vmware.com/w1-vim-cat-24.eng.vmware.com"
←[33mWARN←[0m[2016-11-15T16:21:51-08:00] Firewall configuration will be incorrect if firewall is reenabled on hosts:
←[33mWARN←[0m[2016-11-15T16:21:52-08:00]   "/ha-datacenter/host/w1-vim-cat-24.eng.vmware.com/w1-vim-cat-24.eng.vmware.com"
←[33mWARN←[0m[2016-11-15T16:21:52-08:00] Firewall must permit 2377/tcp outbound if firewall is reenabled
←[34mINFO←[0m[2016-11-15T16:21:52-08:00] License check OK
←[34mINFO←[0m[2016-11-15T16:21:52-08:00] DRS check SKIPPED - target is standalone host
←[34mINFO←[0m[2016-11-15T16:21:52-08:00]
←[34mINFO←[0m[2016-11-15T16:21:52-08:00] Creating Resource Pool "VCH1"
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Creating VirtualSwitch
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Creating Portgroup
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Creating directory [w1-xx-local] registry
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] datastore root [w1-xx-local] registry already exists
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Datastore path is [w1-xx-local] registry
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Creating appliance on target
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Network role "client" is sharing NIC with "external"
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Network role "management" is sharing NIC with "external"
←[34mINFO←[0m[2016-11-15T16:21:53-08:00] Uploading images for container
←[34mINFO←[0m[2016-11-15T16:21:53-08:00]        "appliance.iso"
←[34mINFO←[0m[2016-11-15T16:21:53-08:00]        "bootstrap.iso"

It hangs at this point and it is 100% reproducible! Same command works fine from photon linux..

Attached Hostd.log: 
[hostd.tar.gz](https://github.com/vmware/vic/files/593459/hostd.tar.gz)

Can provide the live env on a need basis..

**Comment by mobla** [comment]
After 8 mins of wait, 'Create timed out' and Failed to collect ha-host hostd.log: context deadline exceeded

> $ ./vic-machine-windows.exe create --name VCH1ESX --target 10.xxx --user root --password 'ca$hc0w' --no-tls  --image-store w1-xx-local --
volume-store=w1-xx-local/registry:default --insecure-registry 10.xxx:80 --thumbprint C9:6F:ED:44:54:48:D9:F6:B6:6A:3B:13:46:55:F0:45:15:
F8:51:3B
←[33mWARN←[0m[2016-11-15T16:32:01-08:00] Configuring without TLS - all communications will be insecure
←[34mINFO←[0m[2016-11-15T16:32:02-08:00] ### Installing VCH ####
←[34mINFO←[0m[2016-11-15T16:32:10-08:00] Validating supplied configuration
←[34mINFO←[0m[2016-11-15T16:32:12-08:00] Firewall status: DISABLED on "/ha-datacenter/host/w1-xx.eng.vmware.com/w1-xx.eng.vmware.com"
←[33mWARN←[0m[2016-11-15T16:32:12-08:00] Firewall configuration will be incorrect if firewall is reenabled on hosts:
←[33mWARN←[0m[2016-11-15T16:32:12-08:00]   "/ha-datacenter/host/w1-xxx.eng.vmware.com/w1-xxx.eng.vmware.com"
←[33mWARN←[0m[2016-11-15T16:32:12-08:00] Firewall must permit 2377/tcp outbound if firewall is reenabled
←[34mINFO←[0m[2016-11-15T16:32:12-08:00] License check OK
←[34mINFO←[0m[2016-11-15T16:32:12-08:00] DRS check SKIPPED - target is standalone host
←[34mINFO←[0m[2016-11-15T16:32:12-08:00]
←[34mINFO←[0m[2016-11-15T16:32:13-08:00] Creating Resource Pool "VCH1ESX"
←[34mINFO←[0m[2016-11-15T16:32:13-08:00] Creating VirtualSwitch
←[34mINFO←[0m[2016-11-15T16:32:13-08:00] Creating Portgroup
←[34mINFO←[0m[2016-11-15T16:32:14-08:00] Creating directory [w1-xx-local] registry
←[34mINFO←[0m[2016-11-15T16:32:14-08:00] datastore root [w1-xx-local] registry already exists
←[34mINFO←[0m[2016-11-15T16:32:14-08:00] Datastore path is [w1-xx-local] registry
←[34mINFO←[0m[2016-11-15T16:32:14-08:00] Creating appliance on target
←[34mINFO←[0m[2016-11-15T16:32:15-08:00] Network role "client" is sharing NIC with "external"
←[34mINFO←[0m[2016-11-15T16:32:15-08:00] Network role "management" is sharing NIC with "external"
←[34mINFO←[0m[2016-11-15T16:32:20-08:00] Uploading images for container
←[34mINFO←[0m[2016-11-15T16:32:20-08:00]        "bootstrap.iso"
←[34mINFO←[0m[2016-11-15T16:32:20-08:00]        "appliance.iso"
←[34mINFO←[0m[2016-11-15T16:40:26-08:00] Collecting ha-host hostd.log
←[31mERRO←[0m[2016-11-15T16:44:03-08:00] Failed to collect ha-host hostd.log: context deadline exceeded
←[33mWARN←[0m[2016-11-15T16:44:03-08:00] No log data for ha-host hostd.log
←[31mERRO←[0m[2016-11-15T16:44:03-08:00] --------------------
←[31mERRO←[0m[2016-11-15T16:44:03-08:00] vic-machine-windows.exe failed: Create timed out: use --timeout to add more time

**Comment by mobla** [comment]
May be it be due to slowness in the network on the windows client machine. ESXi host is in WDC (wanachee datacenter lab) and windows client machine is in PA network. We are trying with --timeout option now..

**Comment by mlh78750** [comment]
The ISO upload can take a long time. Also make sure that the datastore has room for the ISOs.

**Comment by mlh78750** [comment]
related to #2163.

**Comment by mdubya66** [comment]
@mobla you mention this works with the linux client. is the linux client on the same network as the windows client?
@emlin for visibility

**Comment by mobla** [comment]
@mobla you mention this works with the linux client. is the linux client on the same network as the windows client?
Yes.
with --timeout 30 mins it worked. Closing the issue. We could document that "if the vSphere and Client machine are not on the same network, use --timeout flag when creating VCH..

Thanks,
Murali
