### ISSUE TITLE
delete VCH does not remove the bridge network if it was created with a custom name

### ISSUE THREAD

**Issue by mobla** [vmware/vic#3193]
VIC: v0.7.0-6507-6c4627d
vSphere 6.0 GA: ESX ob-2494585

Steps
1. Create VCH with --bridge-network 'vswitch' flag
> ./vic-machine-linux create --name VCHESX --target w1-vim-cat-24.eng.vmware.com --user root --password 'ca$hc0w' --no-tls --image-store w1-vimcat24-local --volume-store=w1-vimcat24-local/registry:default --insecure-registry 10.160.162.65:80 --thumbprint C9:6F:ED:44:54:48:D9:F6:B6:6A:3B:13:46:55:F0:45:15:F8:51:3B --bridge-network 'vswitch2'

2. Delete the VCH --name VCHESX  flag & with --force or without force 
Delete always searches the bridge-network name as VCH name and fails to delete.

This is a simple issue, but it leaves the dangling network in vSphere :-)

**Comment by mdubya66** [comment]
@andrewtchin can you triage this?

**Comment by mdubya66** [comment]
Probably not critical for v0.8.0 but I'd like more details before moving it out.

**Comment by andrewtchin** [comment]
This is a valid bug. I'm testing a fix now.

**Comment by mdubya66** [comment]
pulling from ga. esx only and workaround exists

**Comment by andrewtchin** [comment]
fix is here https://github.com/andrewtchin/vic/tree/3193/remove-custom-bridge-network

**Comment by stuclem** [comment]
Added the following to the release notes for 0.8 RC2:

---

- <b>Deleting a VCH from an ESXi host does not remove the bridge network if it was created with a custom name. [#3193](https://github.com/vmware/vic/issues/3193)</b><br>If you deploy a VCH to an ESXi host and use the `--bridge-network` option to create a bridge network with a custom name, `vic-machine delete` does not remove the bridge network if you delete the VCH.

  Workaround: Manually delete the bridge network from the ESXi host.

-----

@andrewtchin is this OK? Thanks!

**Comment by andrewtchin** [comment]
Looks good 👍
