### ISSUE TITLE
network validation does not block wrong bridge ip range

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3212]
This is one beta customer reported issue. They set bridge ip range, but portlayer network initialization failed with following error message
```
could not initialize port layer: bridge mask is not compatible with bridge pool mask
```

For this issue, at least vic-machine create should fail the deployment with reasonable error message. 
And right now bridge ip range is exposed, but bridge ip width is not, which can be exposed as well, to leave user more flexibility to configure bridge network.

**Comment by andrewtchin** [comment]
As a customer I want VCH install to validate my network settings so that I get a correctly configured deployment or receive an error message if my configuration is incorrect.

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by andrewtchin** [comment]
follow up issue is https://github.com/vmware/vic/issues/3771
