### ISSUE TITLE
Document bridge pool mask error

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3227]
Per https://communities.vmware.com/message/2631924#2631924, document that error `msg="could not initialize port layer: bridge mask is not compatible with bridge pool mask"` in the logs is due to the fact that bridge networks are /16 by default and you likely specified a `--bridge-network-range` that cannot accommodate a /16 network. By default the range is 172.16.0.0/12, which can accept 16 /16 networks.

**Comment by npakrasi** [comment]
Added TS topic: https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_installation/ts_bridge_pool_mask_error.md

**Comment by stuclem** [comment]
My mistake - this belongs in App Dev rather than in Install.

**Comment by stuclem** [comment]
Confirmed that the topic is now in Ap Dev.
