### ISSUE TITLE
Test-Cases.Group6-VIC-Machine.6-04-Create-Basic.Basic timeout fails 

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3241]
Seen first in https://ci.vmware.run/vmware/vic/7080
[integration_logs_7080_46458709ad234ca67984bd07df54cbcee8a59c3f.zip](https://github.com/vmware/vic/files/601733/integration_logs_7080_46458709ad234ca67984bd07df54cbcee8a59c3f.zip)
	
Test-Cases.Group6-VIC-Machine.6-04-Create-Basic.Basic timeout
Start / End / Elapsed:	20161119 12:02:44.753 / 20161119 12:03:41.339 / 00:00:56.586
Status:	FAIL (critical)
Message:	'[34mINFO[0m[2016-11-19T18:03:18Z] ### Removing VCH ####                        
[34mINFO[0m[2016-11-19T18:03:18Z]                                              
[34mINFO[0m[2016-11-19T18:03:18Z] VCH ID: VirtualMachine:11947                 
[34mINFO[0m[2016-11-19T18:03:18Z] Removing VMs                                 
[34mINFO[0m[2016-11-19T18:03:18Z] Removing image stores                        
[34mINFO[0m[2016-11-19T18:03:18Z] Removing appliance VM network devices        
[31mERRO[0m[2016-11-19T18:03:18Z] Failed to power off existing appliance for The attempted operation cannot be performed in the current state (Powered on). 
[34mINFO[0m[2016-11-19T18:03:18Z] Bridge network was not created during VCH deployment, leaving it there 
[34mINFO[0m[2016-11-19T18:03:18Z] Collecting ha-host hostd.log                 
[31mERRO[0m[2016-11-19T18:03:18Z] The attempted operation cannot be performed in the current state (Powered on). 
[31mERRO[0m[2016-11-19T18:03:18Z] --------------------                         
[31mERRO[0m[2016-11-19T18:03:18Z] vic-machine-linux failed: delete failed
     ' does not contain 'Completed successfully

**Comment by hickeng** [comment]
The corresponding install fails with the vsphere connection validation timing out.
```
[34mINFO[0m[2016-11-19T07:20:03Z] ### Installing VCH ####                      
[34mINFO[0m[2016-11-19T07:20:03Z] Generating CA certificate/key pair - private key in ./VCH-7080-6414/ca-key.pem 
[34mINFO[0m[2016-11-19T07:20:03Z] Generating server certificate/key pair - private key in ./VCH-7080-6414/server-key.pem 
[34mINFO[0m[2016-11-19T07:20:03Z] Generating client certificate/key pair - private key in ./VCH-7080-6414/key.pem 
[34mINFO[0m[2016-11-19T07:20:03Z] Generated browser friendly PFX client certificate - certificate in ./VCH-7080-6414/cert.pfx 
[34mINFO[0m[2016-11-19T07:20:03Z] Supplied install parameters: --compute-resource { VCH-7080-6414} --image-store datastore1 --volumes map[] --bridge-network VCH-7080-6414-bridge --client-network { [] {<nil> <nil>} {<nil> <nil>}} --external-network {VM Network [] {172.16.5.1 ffffff00} {172.16.5.5 ffffff00}} --http-proxy <nil> --https-proxy <nil> 
[34mINFO[0m[2016-11-19T07:20:04Z] Validating supplied configuration            
[34mINFO[0m[2016-11-19T07:20:04Z] Configuring static IP for additional networks using port group "VM Network" 
[34mINFO[0m[2016-11-19T07:20:04Z] Firewall status: DISABLED on "/ha-datacenter/host/vic-esx-02.ci.drone.local/vic-esx-02.ci.drone.local" 
[33mWARN[0m[2016-11-19T07:20:04Z] Firewall configuration will be incorrect if firewall is reenabled on hosts: 
[33mWARN[0m[2016-11-19T07:20:04Z] 	"/ha-datacenter/host/vic-esx-02.ci.drone.local/vic-esx-02.ci.drone.local" 
[34mINFO[0m[2016-11-19T07:20:04Z] Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled 
[34mINFO[0m[2016-11-19T07:20:04Z] License check OK                             
[34mINFO[0m[2016-11-19T07:20:04Z] DRS check SKIPPED - target is standalone host 
[34mINFO[0m[2016-11-19T07:20:04Z]                                              
[34mINFO[0m[2016-11-19T07:20:04Z] Creating Resource Pool "VCH-7080-6414"       
[34mINFO[0m[2016-11-19T07:20:04Z] Creating appliance on target                 
[34mINFO[0m[2016-11-19T07:20:04Z] Network role "client" is sharing NIC with "external" 
[34mINFO[0m[2016-11-19T07:20:04Z] Network role "management" is sharing NIC with "external" 
[34mINFO[0m[2016-11-19T07:20:04Z] Uploading images for container               
[34mINFO[0m[2016-11-19T07:20:04Z] 	"/drone/src/github.com/vmware/vic/bin/bootstrap.iso" 
[34mINFO[0m[2016-11-19T07:20:04Z] 	"/drone/src/github.com/vmware/vic/bin/appliance.iso" 
[34mINFO[0m[2016-11-19T07:20:11Z] Waiting for IP information                   
[34mINFO[0m[2016-11-19T07:20:22Z] Waiting for major appliance components to launch 
[34mINFO[0m[2016-11-19T07:20:23Z] Checking VCH connectivity with vSphere target 
[31mERRO[0m[2016-11-19T07:20:33Z] Failed to access target vSphere API https://192.168.31.4: context deadline exceeded 
[34mINFO[0m[2016-11-19T07:20:33Z] Collecting ha-host hostd.log                 
[31mERRO[0m[2016-11-19T07:20:33Z] Failed to collect ha-host hostd.log: context deadline exceeded 
[33mWARN[0m[2016-11-19T07:20:33Z] No log data for ha-host hostd.log            
[31mERRO[0m[2016-11-19T07:20:33Z] --------------------                         
[31mERRO[0m[2016-11-19T07:20:33Z] vic-machine-linux failed: Create timed out: if slow connection, increase timeout with --timeout
```

Given this is repeatable and in the surrounding installs the validation takes <2s I'd say there's something broken in the validation code and it's interaction with the installer context.

**Comment by hickeng** [comment]
The delete failure may be related to #2981

**Comment by mdubya66** [comment]
@vburenin please keep triaging this. We need to know the depth of the problem

**Comment by corrieb** [comment]
We should at the very least triage this to see if it's still a problem. The test is still not running as a result of this festering bug.

**Comment by corrieb** [comment]
Added a comment to #2981. If we can close that bug, we can almost certainly close this one and re-enable the test.

**Comment by mdubya66** [comment]
Closing. The test is enabled and has been passing for a while. https://github.com/vmware/vic/commit/3067cc84cc6daecc9ac2322746b82832ac6dedff#diff-4ccba6286ed5b7bc45a0d2309bb13014
