### ISSUE TITLE
vic-admin unable to get logs from VC after initial download of log bundle

### ISSUE THREAD

**Issue by jzt** [vmware/vic#3259]
If you authenticate with vic admin and then download the log bundle + container logs, it will contain vpxd.log and container logs. If you immediately download the log bundle again, vpxd.log and container logs are missing from the archive. This happens for each subsequent log bundle download until you re-authenticate.

Logs show the following:

```
time=2016-11-19T00:44:10.629604061Z level=debug msg=[BEGIN] [main.findDatastoreLogs:383] 
time=2016-11-19T00:44:10.629644459Z level=debug msg=[BEGIN] [main.listVMPaths:283] 
time="2016-11-19T00:44:10Z" level=error msg="Unable to get children vm of resource pool : NotAuthenticated" 
time=2016-11-19T00:44:10.639456084Z level=debug msg=[ END ] [main.listVMPaths:283] [9.843807ms]  
time="2016-11-19T00:44:10Z" level=error msg="unable to perform datastore log collection due to failure looking up paths: NotAuthenticated" 
time=2016-11-19T00:44:10.639496807Z level=debug msg=[ END ] [main.findDatastoreLogs:383] [9.891966ms]  
time="2016-11-19T00:44:10Z" level=warning msg="error searching datastore: unable to perform datastore log collection due to failure looking up paths: NotAuthenticated" 
```

**Comment by anchal-agrawal** [comment]
We are currently logging out of the session after the first bundle collection: https://github.com/vmware/vic/blob/master/cmd/vicadmin/server.go#L447

Removing that fixes this issue, and I no longer see #3258 as well.

**Comment by emlin** [comment]
vicadmin override session client https://github.com/vmware/vic/blob/master/cmd/vicadmin/vicadm.go#L455
which will not include session keepalive, and then will cause user session timeout after longtime no operation. 
If we need to override client anyway, keepalive should be set similar to what we did in session
https://github.com/vmware/vic/blob/master/pkg/vsphere/session/session.go#L189

**Comment by mdubya66** [comment]
Closing as #3270 was merged
