### ISSUE TITLE
Upgrade status shows in vic-machine ls and inspect output

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3277]
The upgrade option has been hidden in version 0.8, but the upgrade status still appears in the output of `vic-machine ls` and `vic-machine inspect` if you have older VCHs. This is misleading, as no upgrade to 0.8 is available.

Seen with version `v0.8.0-rc1-7157-260dbce`.

**Comment by mdubya66** [comment]
@emlin we should fix this in rc2.
