### ISSUE TITLE
Doc: state that there is no plug-in for the vSphere 6.5 HTML 5 client 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3282]

**Comment by stuclem** [comment]
Added a bullet in the prereqs for all topics that mention the plug-in, to state that the HTML5 client is not supported.

Changes are in https://github.com/stuclem/vic/commit/6c0b8e077edd37b2b154771f5bfb028c2a250e2a.

@jooskim is this OK? Thanks!

**Comment by jooskim** [comment]
Thanks for bringing this up @stuclem. I've been working on HTML5 plugin which, according to Matt's plan, will come in v0.9.0. So while I think it's reasonable to say H5 client is not supported, it would be nice to mention the plugin for H5 client will be released soon.

**Comment by mdubya66** [comment]
I'm not comfortable with saying it's not supported. it's supported as far as working with any other VM within it is supported. @mikeh @karthik-narayan @hickeng feel free to chime in here.

**Comment by stuclem** [comment]
@mdubya66, @jooskim, @mlh78750, @karthik-narayan, @hickeng, to be clear, we're talking about the doc for 0.8 here. Should I rephrase to say that support for the H5 client is coming soon, rather than just bluntly stating that it's not supported?

**Comment by stuclem** [comment]
Ah, @mdubya66 I see the confusion, due to some clumsy wording on my part in both the doc and in the heading of this issue. I wasn't trying to suggest that we don't support the HTML5 client at all, just that there isn't a VIC plug-in for it yet. 

Reworded as follows: 

----

If you deployed the virtual container host to a vCenter Server 6.5 instance, use the Flash-based vSphere Web Client to view the vSphere Web Client plug-in for vSphere Integrated Containers Engine. vSphere Integrated Containers Engine does not currently provide a plug-in for the new HTML5 vSphere Client.


-----

Changes are in https://github.com/stuclem/vic/commit/f3f01d312477ed855e72e32cef595c28f81d894f

**Comment by stuclem** [comment]
Covered by global doc review. Closing.
