### ISSUE TITLE
Create a specific quick deployment example

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3283]
Following discussion with @karthik-narayan, based on beta feedback, customers are saying the docs go into deep detail and they want a Quick Start Guide. QSGs are notoriously hard for a product like VIC, given the dependence on the exact configuration of the customers' environment, but what we can do is repurpose the existing topic [Deploy a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/install_vic_cli.md), (which is currently so vague as to be useless), into two precise examples of deploying to an ESX and to a VC in a specific, basic configuration.

**Comment by stuclem** [comment]
Added two basic deployment examples, one for ESX, one for clusters, and generally reorganized the deployment info:

- [Deploy a Virtual Container Host to an ESXi Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/deploy_vch_esxi.md)
- [Deploy a Virtual Container Host to a vCenter Server Cluster](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/deploy_vch_vcenter.md)

@karthik-narayan, do these meet the requirement as Quick Start topics?

**Comment by karthik-narayan** [comment]
Absolutely! Thanks @stuclem

**Comment by stuclem** [comment]
Reviewed as part of global doc review. Closing.
