### ISSUE TITLE
Integration test failure: docker logs with follow and tail

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3301]
```
==============================================================================
Test-Cases.Group1-Docker-Commands.1-08-Docker-Logs :: Test 1-08 - Docker Logs 
==============================================================================
Docker logs with follow and tail                                      | FAIL |
5 != 15
```

Seen in CI builds https://ci.vmware.run/vmware/vic/7196 and https://ci.vmware.run/vmware/vic/7214

**Logs:**

[Test-Cases.Group1-Docker-Commands.1-08-Docker-Logs-VCH-7196-4503-container-logs.zip](https://github.com/vmware/vic/files/609621/Test-Cases.Group1-Docker-Commands.1-08-Docker-Logs-VCH-7196-4503-container-logs.zip)

Can't seem to upload the entire log bundle or log.html since they're very large, so here's a screenshot of the failure from log.html:

![failure](https://cloud.githubusercontent.com/assets/4361620/20573044/9e16ab92-b173-11e6-96e2-933f976738cc.png)

**Comment by hmahmood** [comment]
This appears to be a race between HUP and the logs command following it. I tried this with regular docker, and put a sleep right after the `docker signal -s HUP` line in the test, and I get the same failure. It looks like there is a delay between sending the HUP and running `docker logs`, which would allow the `seq 11 20` to run through; the `docker logs` command would then just get the last five lines, with the `--follow` having missed the rest of the output.

I think a more reasonable assertion for the test would be to assert >= 5 lines in the output, and not exactly 15 lines.
