### ISSUE TITLE
make -j3 test failure: at "attach" functionality

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3313]
Happened during CI run.
[fail.log.zip](https://github.com/vmware/vic/files/612066/fail.log.zip)

**Comment by hickeng** [comment]
@vburenin which CI run - please put a link in here so that we have it for reference.

**Comment by anchal-agrawal** [comment]
Closing as we don't use `-j3` anymore (https://github.com/vmware/vic/pull/5256).
