### ISSUE TITLE
Document what happens if you deploy to ESX then move that host into a cluster.

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3316]
Per https://github.com/vmware/vic/issues/3190. I think that the best approach is to tell people not to do it.

**Comment by stuclem** [comment]
Added this to the Caveats and Limitations section of [Environment Prerequisites for VCH Deployment](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md):

- If you deploy a virtual container host (VCH) onto an ESXi host that is not managed by vCenter Server, and you then move that host into a cluster, the VCH might not function correctly..

Couldn't think of anywhere better to put it.

Change is in https://github.com/stuclem/vic/commit/a21794d6d6d6758f193434cd7b214163a5753ddb.

@mdubya66 is this OK?

**Comment by cgtexmex** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @cgtexmex
