### ISSUE TITLE
Doc Review: VCH Deployment Fails with a Certificate Verification Error

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3319]
More causes.
1. User may be using incorrect CA certificate on his machine.
2. Security problem: Connection might be spoofed.

**Comment by vburenin** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_thumbprint_error.md

**Comment by stuclem** [comment]
Thanks @vburenin. Updated version here: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/ts_thumbprint_error.md

Changes are in https://github.com/stuclem/vic/commit/ebfdda95a8d8ebeb3fc95f6b097c12580f73f954.

Is this OK now? What solution should we propose for a suspected spoofing attack? Call your sysadmin?

**Comment by vburenin** [comment]
@stuclem That's much better. There is a typo problem in last sentence after comma.
"check you that you have"

**Comment by hickeng** [comment]
> When you use vic-machine create to deploy a virtual container host (VCH), the installation fails with a certificate verification error.

When you use `vic-machine` create to deploy a VCH, the installation fails with a certificate verification error, noting that it "failed to create validator".

## Cause ##

The certificate configured on the vCenter Server or ESXi host specified by the `--target` option cannot be validated on the client system.

## Solution ##

- If the certificate was signed by a certificate authority (CA), add that CA to the trusted roots for the client system.
- If the CA should not be generally trusted, or the certificate is self-signed:
  *  If no thumbprint was specified in the failing vic-machine options and the server is trusted, specify the `--thumbprint` option using the thumbprint from the error message.
  *  Remove the thumbprint from the vic-machine options as it does not match the server certificate. **WARNING: this could mean the server you have connected to is not the intended target and may be spoofed**
      Validate that the change in server certificate is legitimate, then re-run vic-machine having updated the thumbprint option appropriately

**Comment by stuclem** [comment]
Thanks @hickeng ! Comments integrated. Changes are in https://github.com/stuclem/vic/commit/5c033d51294f3c204bd2fc8f3c50d4704cd4d90a.

**Comment by stuclem** [comment]
Took @hickeng's version with minor stylistic changes. Closing.
