### ISSUE TITLE
Doc Review: Download vSphere Integrated Containers Engine

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3320]
Review https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/download_vic_engine.md 

request any changes in this issue. Update https://github.com/vmware/vic/wiki/VIC-Doc-Review once completed.

**Comment by mdubya66** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/download_vic_engine.md#official-releases
I think we should add a note that full support requires the vSphere Enterprise Plus license and that all support requests should be opened via the VMware Global Support path.

**Comment by mdubya66** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/download_vic_engine.md#open-source-builds
add to the Important line a blurb that community support is still available via github issues. And maybe point to https://github.com/vmware/vic/blob/master/CONTRIBUTING.md#reporting-bugs-and-creating-issues

Maybe change the first bullet to:
To obtain a tagged version of vSphere Integrated Containers Engine that has been tested and released to the community, but may not not reflect the most up-to-date version of the code, go to https://github.com/vmware/vic/releases.

And the second bullet:
To obtain the latest built binaries of vSphere Integrated Containers Engine, go to https://bintray.com/vmware/vic-repo/build. Builds usually happen after every successful merge into the source code. These builds have been minimally tested for integration.

And the third bullet:
To build from the latest source version of vSphere Integrated Containers Engine, for example to include changes that you have made since the last daily build, build the vSphere Integrated Containers Engine binaries from the source code. See https://github.com/vmware/vic/blob/master/README.md#building for details.

**Comment by stuclem** [comment]
Thanks @mdubya66.

- Added info about the Enterprise License and VMware Global Support.
- Added Community support and link to contributing doc.
- Took your suggestions for the 3 bullets (almost) verbatim.

Changes are in https://github.com/stuclem/vic/commit/1909851e1d4c6897e34dcf976544a146cbb05902

**Comment by stuclem** [comment]
Questions for @karthik-narayan :

- Will the Harbor download be in the same place as the VIC Engine download, e.g. http://www.vmware.com/go/download-vic?
- Will VIC have a presence on https://www.vmware.com/support/product-support-centers.html ?

Thanks!

**Comment by karthik-narayan** [comment]
@stuclem 

All components of VIC will be available for download from the same location.For GA this will be the engine and Harbor. 

I'm not sure of who generates that page, is this critical?

**Comment by stuclem** [comment]
Thanks @karthik-narayan.  I included the link to the support page, as I think that this is the main entry point to Support.

I have updated the page to include Harbor. 

Changes are in https://github.com/stuclem/vic/commit/dc1d3deb8906543617ce7f5f5d051fa4589f1f9f and https://github.com/stuclem/vic/commit/bb2841d043dde35fd5207f4af15350f386ea2bfe.

Updated page is here: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/download_vic.md

Please take another look. @hainingzhang can you also please verify this page? Thanks!

**Comment by karthik-narayan** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks @karthik-narayan. Leaving open for @hainingzhang.

**Comment by stuclem** [comment]
Think that the reviews we have are good enough. Closing.
