### ISSUE TITLE
Epic: Docathon for GA

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3321]

**Comment by mlh78750** [comment]
For issues in this epic, please add the issue number to the review wiki https://github.com/vmware/vic/wiki/VIC-Doc-Review. 

Please use one issue per section and the multiple reviewers can add to that issue.

**Comment by stuclem** [comment]
Docathon is over. A few straggling issues remain, but I'm tracking them by milestone rather than in this Epic. Closing.
