### ISSUE TITLE
Doc Review: Firewall Validation Error

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3323]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_firewall_error.md#problem

> Firewall must permit 2377/tcp outbound to use VIC.

I think the current version of this error msg is different from the old one:

```
Firewall must permit dst 2377/tcp outbound to the VCH management interface
```

The rest of this doc looks fine. I have verified these steps on my local setup and they worked as expected.

**Comment by stuclem** [comment]
Thanks @chengwang86 !

I updated the error message with your version above. 

Change is in https://github.com/stuclem/vic/commit/a46ff8103a635aaaf4e70bef936be164261bcb4e
