### ISSUE TITLE
Doc Review: Deleting or Inspecting a VCH Fails with a Resource Pool Error

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3325]
I don't see the error msg mentioned in the doc here

> Failed to get VCH resource pool "/ha-datacenter/host/localhost./Resources/vch_name": 
resource pool '/ha-datacenter/host/localhost./Resources/vch_name' not found

I run these cmds with a VC and an ESXi server on Nimbus.

1. create a VCH: 
```bin/vic-machine-linux create --name=test1 ...(--target=vcenter_credentials) ```
The VCH is created successfully.

2. inspect the VCH:
```bin/vic-machine-linux inspect --name=test1  ... (--target=esx_credentials)```
```
INFO[2016-11-29T08:44:15-08:00] ### Inspecting VCH ####                      
ERRO[2016-11-29T08:44:16-08:00] Not a VCH                                    
ERRO[2016-11-29T08:44:16-08:00] Failed to get Virtual Container Host test1   
ERRO[2016-11-29T08:44:16-08:00] Not a VCH                                    
ERRO[2016-11-29T08:44:16-08:00] --------------------                         
ERRO[2016-11-29T08:44:16-08:00] vic-machine-linux failed: inspect failed
```

3. delete the VCH:
```bin/vic-machine-linux delete --name=test1  ... (--target=esx_credentials)```
```
INFO[2016-11-29T08:44:56-08:00] ### Removing VCH ####                        
ERRO[2016-11-29T08:44:57-08:00] Not a VCH                                    
ERRO[2016-11-29T08:44:57-08:00] Failed to get Virtual Container Host test1   
ERRO[2016-11-29T08:44:57-08:00] Not a VCH                                    
ERRO[2016-11-29T08:44:57-08:00] --------------------                         
ERRO[2016-11-29T08:44:57-08:00] vic-machine-linux failed: delete failed
```

4. inspect the VCH without the VCH name: (so I guess the default name "virtual-container-host" was used)
```bin/vic-machine-linux inspect  ... (--target=esx_credentials)```
```
INFO[2016-11-29T08:43:07-08:00] ### Inspecting VCH ####                      
ERRO[2016-11-29T08:43:09-08:00] Failed to get VCH resource pool "/ha-datacenter/host/10.160.107.155/Resources/virtual-container-host": resource pool '/ha-datacenter/host/10.160.107.155/Resources/virtual-container-host' not found 
ERRO[2016-11-29T08:43:09-08:00] Failed to get Virtual Container Host virtual-container-host 
ERRO[2016-11-29T08:43:09-08:00] resource pool '/ha-datacenter/host/10.160.107.155/Resources/virtual-container-host' not found 
ERRO[2016-11-29T08:43:09-08:00] --------------------                         
ERRO[2016-11-29T08:43:09-08:00] vic-machine-linux failed: inspect failed
```

5. delete the VCH without the VCH name:
Same error msg as 4.

The solution looks good to me.

**Comment by stuclem** [comment]
Thanks @chengwang86. Updated the error messages for both inspect and delete.

Change is in https://github.com/stuclem/vic/commit/80c9af02d8d0d6ffa323bb8b96fa5d96be304b26

Straightforward change.
Closing

**Comment by jzt** [comment]
I get conflicting output based on which ESX target I use in my cluster:

I create the VCH:

```bash
TARGET=$VCENTER_IP
./bin/vic-machine-linux create \
        --target=$TARGET \
        --image-store="datastore1" \
        --name=VCH \
        --user=Administrator@vsphere.local \
        --password=Admin\!23 \
        --compute-resource="/dc1/host/c1/Resources" \
        --bridge-network vm-network \
        --force \
        --no-tls \
        --debug 2 \
        --volume-store datastore1/default:default \
        --no-tlsverify
```

Inspect the VCH using an ESX host that is a member of my VC cluster as the target:

```
$ ./bin/vic-machine-linux inspect --name=VCH --target=$ESX1_IP --user=root --password=$ESX1_PASS --thumbprint=A7:3F:F7:B6:E4:9B:27:12:5C:39:BF:0E:CA:81:F2:D3:2C:FE:97:F2
INFO[2016-12-05T17:45:39Z] ### Inspecting VCH ####
ERRO[2016-12-05T17:45:41Z] Failed to get VCH resource pool "/ha-datacenter/host/sc-rdops-vm17-dhcp-11-66.eng.vmware.com/Resources/VCH": resource pool '/ha-datacenter/host/sc-rdops-vm17-dhcp-11-66.eng.vmware.com/Resources/VCH' not found
ERRO[2016-12-05T17:45:41Z] Failed to get Virtual Container Host VCH
ERRO[2016-12-05T17:45:41Z] resource pool '/ha-datacenter/host/sc-rdops-vm17-dhcp-11-66.eng.vmware.com/Resources/VCH' not found
ERRO[2016-12-05T17:45:41Z] --------------------
ERRO[2016-12-05T17:45:41Z] vic-machine-linux failed: inspect failed
```

Using the other ESX host within the cluster as the target:

```
$ ./bin/vic-machine-linux inspect --name=VCH --target=$ESX2_IP --user=root --password=$ESX2_PASS --thumbprint=45:1E:23:D9:DE:5D:7D:A9:FD:33:D1:A0:96:4D:E5:75:CD:96:54:AA
INFO[2016-12-05T17:50:27Z] ### Inspecting VCH ####
ERRO[2016-12-05T17:50:29Z] Not a VCH
ERRO[2016-12-05T17:50:29Z] Failed to get Virtual Container Host VCH
ERRO[2016-12-05T17:50:29Z] Not a VCH
ERRO[2016-12-05T17:50:29Z] --------------------
ERRO[2016-12-05T17:50:29Z] vic-machine-linux failed: inspect failed
```

It appears the output is affected by which target you supply and whether or not the VCH is running within.

**Comment by chengwang86** [comment]
@stuclem Based on my discussion with @jzt , if there are multiple ESXi hosts in the VC cluster, and if you specify "--target" using the ESX host on which your VCH is running, you would see the error msg as in his second case; otherwise, you would see the error msg in the first case (your VCH is not running on that ESXi host).

I think maybe we need to add both cases to this topic for completeness.

**Comment by stuclem** [comment]
Thanks @jzt and @chengwang86. I updated the topic accordingly. Changes are in https://github.com/stuclem/vic/commit/92fc5dc6b8dc8b03ea5994278bcef19402548c19.

Moving to done pending LGTMs from you both, before closing.

**Comment by chengwang86** [comment]
@stuclem I have done with my pass and added some comments in that file. Thanks for your efforts :)  LGTM

**Comment by jzt** [comment]
LGTM 👍

**Comment by stuclem** [comment]
Thanks!
