### ISSUE TITLE
Correction/suggestions for "Networks Used by vSphere Integrated Containers Engine" doc page

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3326]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/networks.md

> A VCH supports a maximum of 3 distinct networks. Because the bridge and container networks require their own distributed port groups, at least two of the public, client, and management networks must share a network.

"A VCH supports connecting to a maximum of 3 network port groups. Because the bridge and container networks require their own port groups, at least two of the public, client, and management networks must share a network port group."

**Comment by stuclem** [comment]
Thanks @hmahmood, updated per your suggestion. Change is in https://github.com/stuclem/vic/commit/bdc504101bda5c43c3c78ed125ff4cb84eb01b1c. 

Moving to In Progress pending review by Mike.

**Comment by stuclem** [comment]
I have overhauled the networking overview at [Networks Used by vSphere Integrated Containers Engine](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/networks.md), including a big new graphic that has been approved by @mlh78750.

@hmahmood, @mlh78750 and @hickeng can you please take a look?

Thanks!
s

**Comment by hickeng** [comment]
> The network for communication between the VCH and vCenter Server and ESXi hosts. The VCH uses this network to communicate with the container VMs.

While correct, this may be misleading as forwarded ports do _not_ use this network - they use the bridge network. "The VCH uses this network to provide the _attach_ function of the Docker API"

**Comment by hickeng** [comment]
> IMPORTANT: Do not use the bridge network for any other VM workloads. The bridge network should not use DHCP.

Do not use the bridge network for any other VM workloads, or as a bridge for more than one VCH.

**Comment by hickeng** [comment]
> Finally, container developers can create isolated networks that containers can only use to communicate with other containers by specifying --isolated when they run docker network create. These isolated networks are not connected to either the bridge or any other network, or to the VCH.

@hmahmood do we support this? While it could easily be done using a container network I don't recall a PR that added --isolated support.

**Comment by hmahmood** [comment]
The part of the diagram where the container networks are depicted is a little confusing. It makes it look like the container networks hang off of the public network, when that may not be the case. I would say move the two lines from "Container Network 1" and "Container Network 2" to connect to the "cloud" and not to "Public Network"

**Comment by hmahmood** [comment]
@hickeng I don't believe we support `--isolated`.

**Comment by hickeng** [comment]
> Container application developers can also use docker network create to create additional bridge networks.

@stuclem We may (or may not) wish to note that additional bridge networks are created by IP address segregation and are not new port groups; we do intend to allow for portgroup creation in future releases. It may be that this is too much detail for this overview and confuses matters.

**Comment by hickeng** [comment]
> Container Networks

@stuclem Note that container communication on these networks is not routed through the VCH as with port forwarding via the bridge network. The diagram shows this but it should be explicitly pointed out as well - this is how we suggest removing the endpointVM as a single-point-of-failure for network traffic.

**Comment by hickeng** [comment]
> Overlay network -> Not supported

The bridge network can be considered an overlay network as it spans all of the hosts in a cluster.

**Comment by stuclem** [comment]
All comments integrated. Changes are in https://github.com/stuclem/vic/commit/dc1e74fa704d4ece532fe78ed664a61d47d7b634.

Marking as done pending your LGTMs. Thanks @hmahmood and @hickeng !

**Comment by hmahmood** [comment]
lgtm

**Comment by mlh78750** [comment]
@hmahmood : under Public network: "Container developers can deploy containers directly on the public interface." That is not true right? They ports that they expose with -p when connected to the default bridge network will be available on the public interface of the endpoint VM via NAT, but I don't think we let the containers directly attach to the public network unless it was mapped in via a container network.

**Comment by mlh78750** [comment]
@stuclem: Sorry for misleading you on the isolated networks. I thought we supported them already.

**Comment by hmahmood** [comment]
@mlh78750 that is correct; unless they add the public network as a "container network", containers will not be able to directly connect to it.

**Comment by mlh78750** [comment]
@stuclem : please see https://github.com/vmware/vic/issues/3326#issuecomment-265764422 for changing the wording for containers and public network

**Comment by mlh78750** [comment]
@stuclem: For the table: I'm not sure Docker has an equiv for our container networks. All of the network access for containers goes through the docker host in docker. 

Text for the "Container Network" section:

The container network allow the vSphere Admin the ability to make vSphere networks directly available to the containers. This is done during install by providing a mapping of the vSphere network name to an alias that will be used inside the endpoint VM and that will show through the docker API. `docker network ls` will show these networks and they can be attached to containers in the normal way using commands like `docker run (or create) --network=_mapped-network-name_` or `docker network connect`. The containers connected to container networks will be directly connected and traffic will not route though the endpoint VM using network address translation.

**Comment by mlh78750** [comment]
@stuclem There are many subtle issues with the table at the end. I propose we scrap it. If you'd like to keep it, let me know and I'll type up something for each of the rows, but it's not going to be short and pithy. :)

**Comment by stuclem** [comment]
Thanks @hmahmood and @mlh78750. I had already ditched the para about isolated networks and have now dropped them from the graphic too. Changes are in https://github.com/stuclem/vic/commit/78a389e9d843f06db43baa7eb45a03043cb68729 and https://github.com/stuclem/vic/commit/48c664f27213cc411347342500f1f0a430d8e741.

**Comment by stuclem** [comment]
Regarding the docker/VIC comparison table, this is something that I threw together mostly for my own benefit. I think that it's definitely worthwhile including it when we can clean it up. Post-GA...

**Comment by mlh78750** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks @mlh78750
