### ISSUE TITLE
Doc Review: Contents of the vSphere Integrated Containers Engine Binaries

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#3328]
lgtm

**Comment by stuclem** [comment]
Moving to In Progress pending review by George.

**Comment by hickeng** [comment]
> The ISO from which a virtual container host (VCH) appliance boots.

The Photon based boot image for the virtual container host endpoint VM
_Thought we were using endpoint/endpointVM, replace it with appropriate terminology? Is there a glossary...?_

> A Photon OS kernel from which container VMs boot.
The Photon based boot image for the container VMs

> The Mac OS command line utility for the installation and management of VCHs.
The OSX command line ...

> If you build the vSphere Integrated Containers Engine binaries manually, you find the ISO files and the vic_machine utility in the <git_installation_dir>/vic/bin folder.

If you build the vSphere Integrated Containers Engine binaries manually, you find the ISO files and the vic_machine utility in <git_clone_dir>/bin - see <instructions to build>

**Comment by stuclem** [comment]
Thanks @hickeng.

- Re: "Thought we were using endpoint/endpointVM, replace it with appropriate terminology?" We are. This one was a stray. 
- Re: "Is there a glossary...?" Not yet. https://github.com/vmware/vic/issues/3072.
- Other comments taken verbatim.
- Removed the line about building the binaries. Our primary audience is VMware customers, not the OSS community. We mention building the binaries and link to the instructions in the [Download vSphere Integrated Containers Engine](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/download_vic_engine.md) topic anyway.

Changes in https://github.com/stuclem/vic/commit/5ba5d65cf6152e3ec00d09ab2443c24d06ccecc8.

No further review required. Closing.
