### ISSUE TITLE
Comments/suggestions for "Options for Specifying a Static IP Address for the VCH Endpoint VM"

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3332]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#static-ip

**Comment by hmahmood** [comment]
> If the client and management networks both use the same network, and the public network does not use that network, you can set a static IP address for the endpoint VM on either or both of the client and management networks.

Inconsistency between use of "network" and "port group" here. I think "port group" would be better here.

**Comment by mlh78750** [comment]
> If either or both of the client or management networks do not use the same network as the public network

If either or both of the client or management networks do not use the same port group as the public network

**Comment by mlh78750** [comment]
> The public, management, and client networks route traffic through the VCH endpoint VM to vSphere. The default route to vSphere through the endpoint VM is assigned to the public network. 

replace with: 

The default route for the VCH endpoint VM is always on the public network.

**Comment by mlh78750** [comment]
> --management-network-gateway routing_destination_1/subnet,
routing_destination_2/subnet:
gateway_address/subnet
--client-network-gateway routing_destination_1/subnet,
routing_destination_2/subnet:
gateway_address/subnet

replace all subnet with subnet_mask

**Comment by mlh78750** [comment]
> In the following example, --management-network-gateway informs the VCH that it can reach all of the Docker clients that are in the ranges 192.168.3.0-255 and 192.168.128.0-192.168.131.255 by sending packets to the gateway at 192.168.2.1

Since this is the management network this is actually talking about the ability for the VCH endpoint VM to talk to vSphere management. Replace Docker clients with vSphere management endpoints..

**Comment by mlh78750** [comment]
I'm done with the review.

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--dns-server
should be: 
A DNS server to use for the VCH endpoint VM on the client, public, or management networks.

**Comment by andrewtchin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @hmahmood, @mlh78750 and @andrewtchin !

- Changed "network" to "port group"
- Added "When you specify an address, `vic-machine create` uses the netmask from the gateway" to the bottom of the bulleted list, and removed it from the FQDN statement.
- Used "The default route for the VCH endpoint VM is always on the public network" verbatim
- Replaced "subnet" with "subnet_mask" in the gateway example.
- Changed "Docker clients" to "vSphere management endoints".
- Used "A DNS server for the VCH endpoint VM to use on the client, public, or management networks."

Changes are in https://github.com/stuclem/vic/commit/2a07d041567a0f58895c77a4cd42a43fdd8f6dad.
Straightforward changes. Closing.
