### ISSUE TITLE
Doc Review: Appliance Deployment Options

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#3333]
review: https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#deployment

**Comment by emlin** [comment]
```
A name for the VCH appliance. If not specified, vic-machine sets the name of the VCH to virtual-container-host. If a VCH of the same name exists on the ESXi host or in the vCenter Server inventory, or if a folder of the same name exists in the target datastore, the deployment of the VCH fails.
```
If the datastore already has a folder same to VCH name, vic-machine will not fail the installation. Instead the new vch folder will be renamed to something like ```<vchname>_1```
There also has one minor issue open https://github.com/vmware/vic/issues/3365

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--force
is the second `--force` extra?

**Comment by andrewtchin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @andrewtchin and @emlin. Added the detail about <vchname>_1. 

Minor change, closing.
