### ISSUE TITLE
Should document vic-machine create timeout issue

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3335]
Now vic-machine create timeout is for the whole creation process, so anything takes longer time might exceed the default time 3 minutes, the error message looks like
```
vic-machine-linux failed: Create timed out: if slow connection, increase timeout with --timeout
```

But there actually have several different reasons could cause the same error message. Here is the issues we found by far.
- Slow network
  vic-machine need to upload iso files to target vsphere datstore, if network is too slow, the iso files uploading gonna take long time. User might get following error message in such case:
```
INFO[2016-11-28T20:18:33Z] Uploading images for container               
INFO[2016-11-28T20:18:33Z] 	"bootstrap.iso"                             
INFO[2016-11-28T20:18:33Z] 	"appliance.iso"                             
INFO[2016-11-28T20:18:39Z] Collecting edc9abdd-4470-4502-9a26-b0d781461081 vpxd.log 
ERRO[2016-11-28T20:18:39Z] Failed to collect edc9abdd-4470-4502-9a26-b0d781461081 vpxd.log: context deadline exceeded 
WARN[2016-11-28T20:18:39Z] No log data for edc9abdd-4470-4502-9a26-b0d781461081 vpxd.log 
ERRO[2016-11-28T20:18:39Z] Failed to power on appliance context deadline exceeded. Exiting... 
ERRO[2016-11-28T20:18:39Z] --------------------                         
ERRO[2016-11-28T20:18:39Z] vic-machine-linux failed: Create timed out: if slow connection, increase timeout with --timeout
```
For this issue, longer timeout, e.g. 10m, 20m, can help on it.
- Cannot get ip address
If user has reasonable timeout set, and after image uploading, after some time waiting, still cannot get ip address. 
If user is using DHCP to get ip, they'll need to check DHCP service, to see if there is ip address available.

- Got ip address, but service is not started, or cannot connect docker API.
In this case, vic-machine return the same final error message, but increase timeout does not help on this.
There is one issue #3227 open for static ip case.
But for this kind of error, it is hard for user to triage directly. But there is some possible ways to get back vch service log.
  * Try to connect https://<vch ip>:2378. If vic admin is started, user can get logs from there directly.
  * If vic admin is unreachable, run vic-machine debug --enable-ssh to enable ssh connection to vch vm, and then ssh to vch vm, check logs located in /var/log/vic dir.

**Comment by anchal-agrawal** [comment]
I've added this to the https://github.com/vmware/vic/issues/3367 epic.

**Comment by stuclem** [comment]
Added new troubleshooting topic: https://github.com/stuclem/vic/blob/08-docs/doc/user_doc/vic_installation/ts_vch_deployment_timeout.md

Change is in https://github.com/vmware/vic/pull/3947/commits/6e6a0d08b5250fc6377b7e8922b8bab319c9d433.

**Comment by stuclem** [comment]
Reviewed by @emlin in https://github.com/vmware/vic/issues/3947
