### ISSUE TITLE
Manual cleanup of VCH fails

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3337]
I cannot delete the datastore items from a failed VCH, walking down the path manually I can get all artifacts to work until I get to scratch:

```
vmware@vmware-virtual-machine:~/vic$ govc datastore.rm VCH-0-8250/VIC/4220ab33-932f-fcda-5829-5352e5083d69/images/scratch
govc: Cannot delete file [vsanDatastore] VCH-0-8250/VIC/4220ab33-932f-fcda-5829-5352e5083d69/images/scratch
```

I don't see this elsewhere, might be related to VC+VSAN.

**Comment by mhagen-vmware** [comment]
[vmware-logs.zip](https://github.com/vmware/vic/files/617506/vmware-logs.zip)

**Comment by emlin** [comment]
if this is vsan, delete directory sometimes will fail. The workaround is to delete recursively, like what we did in vic production code.

**Comment by hickeng** [comment]
@mhagen-vmware have you deleted the other images directories before trying to delete scratch? I'm not sure how `deletable=false` presents on vSAN - could easily be a filesystem level prohibition against deleting a vmdk that still has a disk chain referencing it.

**Comment by emlin** [comment]
Even we deleted the child vmdk, the parent vmdk is still not deletable, cause file manager is not responsible to change that attribute, and not looks like anybody else is triggered the the children file deletion.
So no matter it's vc 6.5, or vSAN, the only workaround is to nuke the folder first and then delete folder.

**Comment by mdubya66** [comment]
Closing as will-not-fix. workaround exists.
