### ISSUE TITLE
Comments/suggestions for "Options for Configuring a Non-DHCP Network for Container Traffic"

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3338]

**Comment by hmahmood** [comment]
> When you specify the container network gateway, you must use the distributed port group that you specify in the container-network option. If you specify container-network-gateway but you do not specify container-network, or if you specify a different distributed port group to the one that you specify in container-network, vic-machine create fails with an error.

"port group" instead of "distributed port group"

**Comment by hmahmood** [comment]
> When you specify the container network DNS server, you must use the distributed port group that you specify in the container-network option. You can specify container-network-dns multiple times, to configure multiple DNS servers. If you specify container-network-dns but you do not specify container-network, or if you specify a different distributed port group to the one that you specify in container-network, vic-machine create fails with an error.

Same comment as above.

**Comment by stuclem** [comment]
Thanks @hmahmood. Removed both instances of "distributed", and did the same in the section on `--container-network`.

Changes are in https://github.com/stuclem/vic/commit/c46f776959c84a193a613034e1f56f8e65cefcb9. Is this OK?

**Comment by andrewtchin** [comment]
lgtm

**Comment by stuclem** [comment]
Needs an LGTM from @hmahmood before I close.

**Comment by hmahmood** [comment]
@stuclem line 697 still says "distributed port group".

**Comment by hmahmood** [comment]
Same for line 699

**Comment by stuclem** [comment]
Fixed the distributeds. Change is in https://github.com/stuclem/vic/commit/518bedd1537a8ddb668fd052185c9773d7d528c1. Closing.

Thanks @hmahmood !

**Comment by hmahmood** [comment]
lgtm
