### ISSUE TITLE
Doc Review: List VCHs and Obtain Their IDs

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3341]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/list_vch.md

**Comment by anchal-agrawal** [comment]
> * The VERSION value includes the version of vic-machine that was used to create the VCH, the build number of this version, and a hashtag to identify the build.

The VERSION value **shows** the version of vic-machine that was used to create the VCH. **It includes the release version, the build number and the git commit checksum.**

**Comment by emlin** [comment]
> You have deployed at least one VCH.

If there is no VCH deployed, vic-machine ls will return no VCH, but it's still fine to run it.

**Comment by emlin** [comment]
> The PATH value depends on where the VCH is deployed:

It might worth to mention that this PATH can be used in vic-machine command for parameter --compute-resource. @hickeng to confirm if we want to expose this absolution path for compute resource. If otherwise, we might enhance vic-machine ls to show relative path here.

**Comment by stuclem** [comment]
Thanks @anchal-agrawal and @emlin !

- Took the VERSION sentence verbatim.
- Updated the prereq to "You have deployed a VCH. If you have not deployed a VCH, `vic-machine ls` returns an empty list."
- Added "You can use the information in PATH in the --compute-resource option of vic-machine commands."

Changes are in https://github.com/stuclem/vic/commit/9fec91e23e50e81bbad3eca4605c9fc331d10e5e.

Leaving in In Progress pending review by @gigawhitlocks.

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by stuclem** [comment]
Moving to Done pending review by @gigawhitlocks.

**Comment by gigawhitlocks** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks!
