### ISSUE TITLE
Doc Review: Delete a VCH

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3342]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/remove_vch.md

**Comment by anchal-agrawal** [comment]
The following example at the bottom of the page

```
$ vic-machine-darwin-linux-windows delete
--target vcenter_server_username:password@vcenter_server_address
--name cluster_name
--force
```

should say `--name vch_name` instead of `--name cluster_name`.

**Comment by emlin** [comment]
> If the delete operation fails with a message about container VMs that are powered on, run vic-machine delete again with the --force option.

Run docker stop to stop any running containers is another option here. As --force is not recommended, we'd better to have another option here.

**Comment by stuclem** [comment]
Added docker stop and recommended against using --force. 

Changes are in https://github.com/stuclem/vic/commit/c970690c30930ffec22e47665d6f6960f03b3d15. 

Leaving in Done pending your LGTMs. Thanks @anchal-agrawal and @emlin !

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by emlin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @anchal-agrawal and @emlin !

**Comment by gigawhitlocks** [comment]
LGTM
