### ISSUE TITLE
Doc Review: Obtain VCH Information

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3343]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/inspect_vch.md

**Comment by anchal-agrawal** [comment]
> ```
> Installer version: vic_machine_version-vic_machine_build-tag
> VCH version: vch_version-vch_build-tag
> ```

For the last part of the version format, we could say `git_commit` instead of `tag`.

**Comment by emlin** [comment]
> vic-admin portal:

should be 
```VCH Admin Portal: ```

**Comment by emlin** [comment]
> VCH with TLS authentication with untrusted self-signed certificates or no TLS authentication:
docker -H vch_address:2376 --tls info

I think this is not for no TLS authentication case, that is covered by the next sample

**Comment by stuclem** [comment]
Thanks @anchal-agrawal and @emlin. All comments integrated.

Changes are in https://github.com/stuclem/vic/commit/19e2c52338ec20064c2c3f81ae6248a593f17c96

Leaving this In Progress pending review by @gigawhitlocks

**Comment by emlin** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks @anchal-agrawal and @emlin. Moving to Done pending review by @gigawhitlocks.

**Comment by stuclem** [comment]
Thanks!
