### ISSUE TITLE
Doc Review: Docker Commands Fail with a Docker API Version Error

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3344]
Review https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_docker_version_error.md

**Comment by mdubya66** [comment]
LGTM - No changes required.

**Comment by hickeng** [comment]
> (client API version: 1.24, server API version: 1.23).

This is an example - we could xxx out the client version as that's what will be changing


> Open a Docker client terminal.

We need to define what is meant by "Docker client terminal" - it's a terminal on a system that has a docker client installed, but the way this is phrased makes it sound to me like a completely separate terminal client of some kind.

_Provide an example docker info command that does not have --tls_
`docker -H virtual_container_host_address:2375 info`

**Comment by stuclem** [comment]
All done. Replicated the changes in the sister topic in the App Dev pub. Changes are in https://github.com/stuclem/vic/commit/6200c1b6a85d3786d4e189c312be799ccef865b2 and https://github.com/vmware/vic/commit/4b1537bbc958a99a8065adc09b1dd9a12eb6da13

**Comment by stuclem** [comment]
Minor changes. Closing.
