### ISSUE TITLE
Doc Review: VCH Delete Options

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3346]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/delete_vch_options.md

**Comment by anchal-agrawal** [comment]
There seems to be an extra `--force` at the bottom of the page.

LGTM otherwise.

**Comment by emlin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @anchal-agrawal and @emlin !

The extra force is the example of usage. I admit that it looks a bit weird here because there are no arguments and this is the only option, but this is in keeping with the other topics.

Leaving in In Progress pending review by @gigawhitlocks.

**Comment by stuclem** [comment]
Moving to Done  pending review by @gigawhitlocks.

**Comment by stuclem** [comment]
Thanks all!
