### ISSUE TITLE
Doc Review: Specify One Or More Volume Stores

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3347]

**Comment by fdawg4l** [comment]
https://github.com/vmware/vic/blob/90fae4fdf6c905d1bd1d1b0d337f7e118595b0f8/doc/user_doc/vic_installation/vch_installer_examples.md#volume-stores

Looks fine.  I actually didnt even know you could single quote the datastore but it seems to work, so thanks for that!

**Comment by stuclem** [comment]
Thanks @fdawg4l. Leaving this in In Progress pending review by @matthewavery.

**Comment by matthewavery** [comment]
@stuclem Looks great to me! LGTM

**Comment by stuclem** [comment]
Thanks @matthewavery and @fdawg4l . Closing.
