### ISSUE TITLE
Doc Review: Using Volumes with vSphere Integrated Containers Engine

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3348]

**Comment by jzt** [comment]
Link to doc:  https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md

**Comment by cgtexmex** [comment]
Until there's some resolution with #2899 we need to document that volume store creation, thus volume usage capabilities, are dependent on the VCH install.  I think this should be highlighted in the first paragraph with a link to [volume-store install](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--volume-store)

**Comment by anchal-agrawal** [comment]
For these examples at the bottom of https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#create-a-volume-in-a-volume-store:

```
docker -H virtual_container_host_address:2376 --tls 
create -v /volume_name busybox

docker -H virtual_container_host_address:2376 --tls 
run -v /volume_name busybox
```

I think they should say:

```
docker -H virtual_container_host_address:2376 --tls 
create -v volume_name:/directory busybox

docker -H virtual_container_host_address:2376 --tls 
run -v volume_name:/directory busybox
```

The former creates an anonymous volume for the container and mounts it at `/volume_name` in the container, while the latter uses the `volume_name` volume that was created earlier, which I believe is the intention in the example.

**Comment by matthewavery** [comment]
under the `Create a Volume in a Volume Store` we should probably reword the need for a `default` volumestore. It should be moved to the intro to the section on create. 

currently it says 
```
If you or the vSphere Administrator set the volume store label to default when running vic-machine create, you do not need to specify --opt VolumeStore.
```

we should not really mentioned the --opt VolumeStore at all here. and the volume store creation time is a totally separate event that the creation of a volume. volume stores are created at VCH creation time.

**Comment by anchal-agrawal** [comment]
We should rephrase the following to more clearly state how volume mounting works.



In section https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#create-a-container-and-attach-it-to-an-anonymous-or-named-volume:

> For example, to create a busybox container that is mounted to the volumes folder of an anonymous volume in the default volume store, run the following command:

   For example, to create a busybox container that **uses an anonymous volume in the default volume store mounted to `/volumes` in the container**, run the following command:

> For example, to create a busybox container that is mounted to the volumes folder of a volume named volume_1 (in the default volume store with default capacity), run the following command:

  For example, to create a busybox container that **mounts `volume_1` (in the default volume store with default capacity) to the `/volumes` directory**, run the following command:

---

In section https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#mount-an-existing-volume-on-a-container:

> * Mounts the myData folder of a volume named volume1 on that container, starts the container, and attaches to it.
> * After performing operations in volume1:/myData then stopping and detaching container1, creates container2 from the ubuntu image and mounts the myData folder of volume1 on it.

* Mounts the **volume named `volume1` to the `myData` folder** on that container, starts the container, and attaches to it.
* After performing operations in `volume1:/myData` **and** then stopping and detaching `container1`, creates `container2` from the `ubuntu` image and mounts **`volume1` to the `myData` folder** on it.

@matthewavery are these edits better?

**Comment by fdawg4l** [comment]
@anchal-agrawal @matthewavery I don't like the words "attach" / "detach" in our docs when referring to storage without a qualifier.  When a docker user sees "detach", I worry that they would think that means running the container in detached mode.

Also, we don't support detaching of a container whether the container is running or powered off.  The only way to support that workflow of using a vol in container1 and attaching it to container2 is if you destroy container1 first and the vol is a named vol and *not* anonymous.

**Comment by fdawg4l** [comment]
I should mention docker itself doesn't support detaching volumes from containers (regardless of the containers' state of running or killed)

**Comment by fdawg4l** [comment]
Other than the above comments, the rest of the doc looks fine to me.

**Comment by stuclem** [comment]
Thanks @cgtexmex, @matthewavery, @anchal-agrawal and @fdawg4l !

@cgtexmex, I did actually state that the volume store must be added to the VCH at creation time, but I don't think that I said it strongly enough. So, I have called this out in an IMPORTANT note and laid it on a bit thicker:

----

**IMPORTANT**: To use container volume capabilities with vSphere Integrated Containers Engine, you or the vSphere Administrator must configure the virtual container host (VCH) appropriately at the moment of deployment of the VCH. When you create or the vSphere Administrator creates a VCH, you or the Administrator must specify the datastore to use to store container volumes in the `vic-machine create --volume-store` option. You cannot currently add volume stores, and therefore volume capabilities, to a VCH after its initial deployment. For information about how to use the `vic-machine create --volume-store` option, see the section on `volume-store` in [VCH Deployment Options](../vic_installation/vch_installer_options.html#volume-store) in *vSphere Integrated Containers Engine Installation*.  

----

**Comment by stuclem** [comment]
@anchal-agrawal, I changed the example in https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#create-a-volume-in-a-volume-store as follows:

----

After you create a volume by using docker volume create, you can mount it in a container by running either of the following commands:

<pre>docker -H <i>virtual_container_host_address</i>:2376 --tls 
create -v <i>volume_name</i>:/<i>folder</i> busybox</pre>
<pre>docker -H <i>virtual_container_host_address</i>:2376 --tls 
run -v <i>volume_name</i>:/<i>folder</i> busybox</pre>

In the examples above, Docker mounts the volume <code><i>volume_name</i></code> in the container at the location that you specify in <code><i>folder</i></code>.

----

**Comment by stuclem** [comment]
@matthewavery, regarding "we should not really mention the --opt VolumeStore at all here and the volume store creation time is a totally separate event that the creation of a volume":

Unless I am misreading your comment, I think that is what I was trying to say, but perhaps not very clearly. I think that we really do need to mention `--opt VolumeStore` here. I have fleshed out the two bullets in [Create a Volume in a Volume Store](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#create-a-volume-in-a-volume-store) to try to make this clearer:

----

- If you or the vSphere Administrator created the VCH with one or more volume stores, but none of the volume stores is named `default`, you must specify the name of an existing volume store in the `--opt VolumeStore` option. If you do not specify `--opt VolumeStore`, `docker volume create` searches for a volume store named `default`, and returns an error if no such volume store exists.

  <pre>docker -H <i>virtual_container_host_address</i>:2376 --tls volume create 
  --opt VolumeStore=<i>volume_store_label</i> 
  --name <i>volume_name</i></pre>

- If you or the vSphere Administrator created the VCH with a volume store named `default`, you do not need to specify `--opt VolumeStore` in the `docker volume create` command. If you do not specify a volume store name, the `docker volume create` command automatically uses the `default` volume store if it exists.

  <pre>docker -H <i>virtual_container_host_address</i>:2376 --tls volume create 
  --name <i>volume_name</i></pre>

----

Hopefully this is clearer now, in combination with the fact that I have now clarified that the volume store must be created when you (or the Admin) run `vic-machine create` in the IMPORTANT call-out at the top of this topic, per the comment from @cgtexmex,. Bear in mind that this topic is for the container app devs. Information for the creator of the VCHs about creating a volume store named `default` is included in the installation doc, in the description of [`vic-machine create --volume-store`](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--volume-store).

**Comment by stuclem** [comment]
@anchal-agrawal, I pretty much rewrote the section on mounting named or anonymous volumes. See ADD LINK HERE ONCE COMMITTED for the new version.

For [Mount an Existing Volume on a Container](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#mount-an-existing-volume-on-a-container), I took your suggestions but broke them up into more bullets, for clarity:

----

This example performs the following operations:

- Creates a container named `container1` from the `busybox` image.
- Mounts the volume named `volume1` to the `myData` folder on that container, starts the container, and attaches to it.
- After performing operations in `volume1:/myData`, stops and detaches `container1`.
- Creates a container named `container2` from the Ubuntu image.
- Mounts `volume1` to the `myData` folder on `container2`.

----

**Comment by stuclem** [comment]
@fdawg4l I replaced "attach" with "mount" wherever I thought appropriate. The only use of "attach" should now be when we're talking about `docker attach`, rather than mounting a volume.

Regarding mounting existing volumes on containers, and those volumes having to be named rather than anonymous, I reworded the intro to [Mount an Existing Volume on a Container] as follows:

-----

## Mount an Existing Volume on a Container ##
Mounting existing volumes on containers is subject to the following limitations:

- vSphere Integrated Containers Engine currently supports mounting a volume on only one container at a time. 
- Docker not support unmounting a volume from a container, whether that container is running or not. When you mount a volume on a container by using `docker create -v`,  that volume remains mounted on the container until you remove the container. When you have removed the container you can mount the volume onto a new container.
- If you intend to create and mount a volume on one container, remove that container, and then mount the same volume on another container, you must use a named volume. You cannot mount an anonymous volume on one container, remove that container, and then mount the anonymous volume on another container.
----

**Comment by stuclem** [comment]
Thank you @matthewavery, @cgtexmex, @anchal-agrawal and @fdawg4l! Given the extent of the changes in this topic, I'd really appreciate it if you would give the topic another once-over and then add LGTM in this issue (or not, if it doesn't look good).

Changes are in https://github.com/stuclem/vic/commit/4071c0fbdaf5f92e896c4aa9cb93c382f64eb796.
More readable version is here: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md (my fork, as not merged into master yet)

**Comment by matthewavery** [comment]
@fdawg4l an anonymous volume can be reused on another container once the originally container that created it has been removed. The user just has to know the UUID name that we gave the volume. It is not ideal, but it is a possibility.

**Comment by matthewavery** [comment]
`If you or the vSphere Administrator created the VCH with one or more volume stores, but none of the volume stores is named default...` *is* should be *are*.

`Docker not support unmounting a volume from a container, whether that container is running or not...` beginning should probably read *Docker does snot support...* 

`If you intend to create and mount a volume on one container, remove that container, and then mount the same volume on another container, you must use a named volume. You cannot mount an anonymous volume on one container, remove that container, and then mount the anonymous volume on another container.` -> The volume does not have to be named, an anonymous volume can be mounted to another container after the creating container is removed. I agree it is unlikely to happen, but it can. The user would also have to know which anon volume was theirs. Not sure what to say there about it. personally, I think we should say that you can remount anon volumes too, but that we do no recommend it.

**Comment by matthewavery** [comment]
Other than those, it looks good to me.

**Comment by anchal-agrawal** [comment]
Thanks Stuart. A tiny suggestion about https://github.com/vmware/vic/issues/3348#issuecomment-263824674 - the last line can be made clearer:

> In the examples above, Docker mounts the volume volume_name in the container at the location that you specify in folder.

In the examples above, Docker mounts the volume `volume_name` **to `/folder` in the container**.

LGTM otherwise!

**Comment by jzt** [comment]
@matthewavery `snot support`?? When did this feature go in?

**Comment by stuclem** [comment]
@fdawg4l and @matthewavery, regarding anon vols, I reworded thusly: " If you intend to create and mount a volume on one container, remove that container, and then mount the same volume on another container, use a named volume. It is possible to mount an anonymous volume on one container, remove that container, and then mount the anonymous volume on another container, but it is not recommended to do so."

@matthewavery, re "none .. is" and "none ... are", it turns out that I am not only a linguistic pedant, but also wrong in this case. Always thought that "none ... is" is more grammatically correct, but it seems that the OED disagrees with me: http://www.onlinegrammar.com.au/top-10-grammar-myths-none-always-takes-a-singular-verb/ Changed "is" to "are". Also added the missing "does".

@anchal-agrawal, I took your rewording verbatim. 

@jzt, snot support. I'm sure that we can come up with some new feature with the appropriate acronym. Answers on a postcard please!

Changes are in https://github.com/stuclem/vic/commit/aa26e816546afc74411d10900ebd43b4c0126890.

Am considering this one LGTM'd, so closing.
Thanks all!

**Comment by jzt** [comment]
Doc looks good to me.
