### ISSUE TITLE
Doc Review: Installing the vSphere Web Client Plug-in for vSphere Integrated Containers Engine

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#3349]
Doc: https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/install_vic_plugin.md

**Comment by jooskim** [comment]
In the procedure section for installing the plugin with a web server (both in vCenter for Windows and VCSA) it would be nice to say the thumbprint should be colon-delimited instead of space. Google Chrome displays it colon-delimited.

**Comment by jooskim** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_web.md
Including something like "Bash shell emulator such as Cygwin or Git Bash" as a prerequisite will be more helpful for those who run `vic-machine` in Windows against VCSA

**Comment by jooskim** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/plugin_vcsa_no_web.md
First prerequisite is missing a bullet point.

**Comment by stuclem** [comment]
Thanks @jooskim!

- Added colon-delimitation in the two Web server topics
- I already mentioned to use Cygwin or Git bash in the two VCSA topics, in the step in which you run `install.sh`.
- Fixed the missing bullet.

Changes are in https://github.com/stuclem/vic/commit/2c2ac7a92002e7ec4c7ea00154fbbec56a38af49. Is this OK?

**Comment by jooskim** [comment]
@stuclem Looks good to me!

**Comment by stuclem** [comment]
Thanks @jooskim. Leaving this as In Progress pending review by @jak-atx

**Comment by stuclem** [comment]
Moving to Done pending review by @jak-atx

**Comment by stuclem** [comment]
The work was done by @jooskim, so his review is good enough. Closing.
