### ISSUE TITLE
Doc Review: Plug-In Does Not Appear in the vSphere Web Client

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#3352]
Doc: https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_ui_not_appearing.md

**Comment by jooskim** [comment]
For those running VCSA 6.5, commands to stop and start the vSphere Web Client service are different from those for VCSA 6.0:

`service-control --stop vsphere-client` and then
`service-control --start vsphere-client`

**Comment by stuclem** [comment]
Thanks @jooskim. Done. Changes in https://github.com/stuclem/vic/commit/0c89d8067612221af1266cc817236251302a7dde.

Does this look OK now?

**Comment by jooskim** [comment]
@stuclem Looks good to me. Thanks!

**Comment by stuclem** [comment]
Thanks!
