### ISSUE TITLE
Doc Review: Supported Docker Commands

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3353]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md

**Comment by sflxn** [comment]
There is quite a bit of mixing of docker command references with docker API references.  The API references aren't applicable to most users and seem inappropriate for this document.  For instance, docker inspect reference links takes me to the API reference.  You can see from the URL that it's pointing to remote api docs.  Some of the reference links are correctly pointing to docker command URL, but it seems very random.

**Comment by sflxn** [comment]
For List Images, we only support --no-trunc and -q/--quiet options at the current time.

**Comment by sflxn** [comment]
For docker rmi, we do not support any options at the current time.

Also, VIC will not untag an image when a user uses docker rmi if there is a container running, using that image.  We do not yet support tag/untag operations.

**Comment by sflxn** [comment]
Container list is the same thing as ps.  Remove container list operation.

For container ps, VIC currently only support -a/--all, --no-trunc, and -q/--quiet option.

**Comment by sflxn** [comment]
There is no container resize command.  That is an API operation.

**Comment by sflxn** [comment]
We really need to make clear there is a difference between docker command (as executable with the docker command line program) and the docker APIs.  The docker APIs are probably not important to our users, and do not seem important in the context of this doc.  The 1.23 comment is important but we should make clear to readers that this document refers to docker commands and not APIs.

**Comment by sflxn** [comment]
For docker create, we do not support most of the standard options.  It's probably best to list all the options that we DO support.

-a, --attach
--cpuset-cpus
-e, --env
--ip
-m, --memory
-i, --interactive
--link
-l, --label
--network,
--tty
-v, --volume

@hmahmood @matthewavery, can you guys check the network and volume parameters?

**Comment by sflxn** [comment]
For docker logs, "which are not yet supported."  Add yet.

For docker rm, -f/--force is supported.

For docker stop, "Yes.  It attempts to politely stop the container.  If that fails, it will power down the VM."

For docker login, "Yes."  Remove the rest.  It is used to access public and private registries.

For docker pull, "Yes."  It supports pulling from public and private registries, secure or insecure.

**Comment by sflxn** [comment]
For network command, @hmahmood should comment on network connect and network create options

For volume create options, @matthewavery should comment.

For volume inspect, "Yes."  Remove the comments about compose.  It can be use for many things.

**Comment by sflxn** [comment]
I would add Docker compose commands if you're going to include a comment about Swarm.

**Comment by sflxn** [comment]
For docker run, I would do the same as with docker create, list all the options we actually DO support instead.  These includes all docker create options listed above and the following additional ones:

-d, --detach
--detach-keys
--dns (I believe.  @hmahmood should verify)

**Comment by caglar10ur** [comment]
Minimum memory is 512MB, maximum unlimited. If unspecified, default is 2GB.

Is misleading, should we refer to esxi maximum values?

**Comment by matthewavery** [comment]
All Volume Create options are supported. We might include a link to our doc for using volumes in VICe with the volume section since we do have specific driver arguments.

**Comment by matthewavery** [comment]
Volume ls -> Yes. --filter is not supported.

**Comment by matthewavery** [comment]
For volume rm I think that a simple "Yes." might be simpler. While it is true that `docker rm -v` does remove volumes and we do not support it yet, It is not really related to `docker volume rm`. I think it works either way, sorry if this seems knit picky.

**Comment by stuclem** [comment]
Thanks all. @npakrasi can you please address?

**Comment by npakrasi** [comment]
Incorporated comments. Thank you everyone.

**Comment by npakrasi** [comment]
@sflxn, @matthewavery, @caglar10ur, @hmahmood if the doc looks ok, can you LGTM this issue so I can close it? Thanks! https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md

**Comment by sflxn** [comment]
Docker stop has "Yes. Yes."  We should correct that.

**Comment by chengwang86** [comment]
In the "general container operations" table, how do we decide whether a docker cmd is put there or not? Several important docker cmds (though not yet supported) are missing, e.g., "docker build", "docker commit".

**Comment by sflxn** [comment]
Ok, I didn't notice the change till I saw Cheng's comments.  It does look like we removed a lot more than I thought.  The doc was previously following the same format as https://docs.docker.com/engine/reference/commandline/.  Why did we change?

Also, we should have a comment about not supporting Swarm at this time.

**Comment by hmahmood** [comment]
For "Network Operations": `network connect` is not supported for running containers.

**Comment by npakrasi** [comment]
Made the edits and added the missing commands. Not sure  why I missed them but they're in now. :)

**Comment by stuclem** [comment]
@sflxn, @npakrasi and @chengwang86. Hmm, I did do a reorg of the Docker commands table a little while ago, to match the organization on https://docs.docker.com/engine/reference/commandline/. I also added all of the ones from the Docker site that we didn't list. Looks like that reorg has been eaten by a git merge problem. I'll investigate and see if I can reinstate the reorg.

**Comment by stuclem** [comment]
Looks like this is the PR where the reorg got overwritten: https://github.com/vmware/vic/pull/3405/files.

Should hopefully be easy enough to fix.

**Comment by stuclem** [comment]
I have manually merged the latest updates to the table cells into the reorganized tables. See here:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md

@sflxn, @chengwang86, @matthewavery and @npakrasi, please can you check that your latest updates are present in this version? 

Thanks!

**Comment by stuclem** [comment]
Looking at PR https://github.com/vmware/vic/pull/3405/files, I'm the one who LGTM'd and merged it :)

**Comment by stuclem** [comment]
@chengwang86, @sflxn and @matthewavery can you all please take one final look at the [Supported Docker Commands](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md) and give us your LGTMs? 

Sorry to bug you repeatedly about this, but it's vital that we get this topic absolutely spot-on. Thanks!

**Comment by stuclem** [comment]
And @caglar10ur too (see comment above). Thanks!

**Comment by chengwang86** [comment]
LGTM

**Comment by matthewavery** [comment]
LGTM - Looks Great!

**Comment by stuclem** [comment]
Good enough. Closing!
