### ISSUE TITLE
Doc review: Basic Deploy a VCH to an ESXi Host

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3354]
review https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/deploy_vch_esxi.md

**Comment by emlin** [comment]
```
If your vSphere environment does not use trusted certificates that have been signed by a Certificate Authority (CA), obtain the thumbprint of the vCenter Server or ESXi host certificate.
```
I think user might wondering how to it if they're not that familiar with vsphere. And vic-machine create actually can return the server's thumbprint, should we mention that here as well?

**Comment by emlin** [comment]
```
Because the ESXi host only has one one network, and one datastore, vic-machine create automatically detects and uses those resources.
```
For network, it's slightly different. Now we default public network to "VM Network", if user does not specify that parameter. But if user has one single network, with different network name, vic-machine cannot use that network without explicitly specify the public network option.

**Comment by emlin** [comment]
vic-machine create successful information is slightly changed
```
vic-admin portal:
```
should be
```
VCH Admin Portal:
```

**Comment by mhagen-vmware** [comment]
Setting the path env variable after downloading the bundle is a bit overkill, I would think most people would just go into the directory after open the tarball and run the command from within the folder.

**Comment by mhagen-vmware** [comment]
The basic ESX install currently requires the thumbprint option or --force option now as well.  I think to keep it as simple as possible, I would add the --force option over the --thumbprint option at this point.

**Comment by stuclem** [comment]
@emlin and @mhagen-vmware, thanks!
 
- For the thumbprint, I deleted both the bullet from the **Prerequisites** section and the link to the topic on obtaining the thumbprint from **Result**, because I like Mike's idea of specifying `--force` instead, since this is a simple example.
- Changed the network bullet to "The default VM Network and no other networks"
- Fixed VCH Admin Portal
- Removed the bullet about setting the path.

Changes are in https://github.com/stuclem/vic/commit/14ce8242d5254ccb8615f64b319ac89074df40cf. Is this OK now? Thanks!

**Comment by emlin** [comment]
We actually do not care if there is other network or not, we simply default to "VM Network", that might change in the future though. I mention this is because we'll create bridge network for each vch deployed, if user already had one VCH deployed, another deployment gonna violate this precondition, and that might be a little bit confusing.

**Comment by stuclem** [comment]
Thanks @emlin. I changed "The default VM Network and no other networks" to "The VM Network is present". I don't think that we should over-complicate the example right now. If the behaviour changes in the future we'll update the example then.

Change is in https://github.com/stuclem/vic/commit/88a8da2308d6a6b6f1f8967db136438e428572bd.

@karthik-narayan we just need a review from you and we can close this one. Thanks!

**Comment by emlin** [comment]
lgtm

**Comment by stuclem** [comment]
Needs an LGTM from @mhagen-vmware and @karthik-narayan before I close.

**Comment by karthik-narayan** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @mhagen-vmware and @karthik-narayan !
