### ISSUE TITLE
Doc Review: Access the VCH Administration Portal

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3355]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/access_vicadmin.md

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by sgairo** [comment]
Should we include the potential "site not secure/connection not secure" in the procedure? Where the user must click advance anyway, etc. Or is this more of a common user problem that shouldn't be included in our documentation?

**Comment by sgairo** [comment]
Also unless we are intending to mean different things here : 

If you deployed the VCH to vCenter Server, copy the address from the Summary tab for the vSphere Integrated Containers Engine endpoint VM in **the vSphere Web Client.**

If you deployed the VCH to an ESXi host, copy the address from the Summary tab for the vSphere Integrated Containers Engine endpoint VM in **the vSphere Client.**

We should be consistent with what we call it, probably vSphere Web Client

**Comment by stuclem** [comment]
Thanks @anchal-agrawal and @sgairo.

- Regarding vSphere Web Client vs. vSphere Client, these are two separate things which are very badly named. AFAIK, you can't connect vSphere Web Client to an ESXi host. For this you have to use the old C#-based desktop client, which is officially named the vSphere Client. Which is the same as the official name for the new H5 client in 6.5. It's not the official name, but I changed **vSphere Client** to **desktop vSphere Client**.
- Regarding the not secure connection, added the following: "If prompted about an insecure or not private connection, click Advanced and follow the prompts to proceed to the portal."
- One question: I thought that you only needed to supply the VC user/password if you deployed the VCH with full TLS. But I just deployed VCHs with --no-tls and --no-tlsverify and had to log in in both cases. @gigawhitlocks is it now the case that you always have to provide VC credentials to access VCH Admin? 

Changes are in https://github.com/stuclem/vic/commit/b46ad7ba012889f952d17112858ebe0bbe2f4bb4. Other than the outstanding question about logging in, is this OK?

**Comment by gigawhitlocks** [comment]
https://github.com/vmware/vic/pull/3394

**Comment by gigawhitlocks** [comment]
@stuclem didn't see your question here until just now, but I've updated the docs to be correct in the above PR, which should answer your question. Your understanding is reversed -- username/password is required _without_ full TLS and certs can be used optionally _with_ full TLS. Authentication through one method or the other is always required, no matter what.

**Comment by stuclem** [comment]
@gigawhitlocks no problem at all. I've been swamped anyway. I have pulled your PR into my local, and will probably split your new info out into another topic tomorrow. Thanks for doing this!

**Comment by stuclem** [comment]
@gigawhitlocks I broke this up into 3 topics:

- [Access the Administration Portal for a VCH](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/access_vicadmin.md) (the original topic)
- [Browser-Based Certificate Login](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/browser_login.md)
- [Command Line Certificate Login](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/cmdline_login.md)

Changes are in https://github.com/stuclem/vic/commit/abe4edfdaf041b6ac29303dbcfb00ad1970ba636.

Is this OK? Thanks!

**Comment by gigawhitlocks** [comment]
Formatting looks a little messed up on the Command Line Certificate Login page but otherwise LGTM (including the actual content on that one)

**Comment by stuclem** [comment]
Hum, it didn't like my <pre> tags, for some reason. Fixed. A more beautiful version is here:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/cmdline_login.md

Thanks!
