### ISSUE TITLE
Doc Review: Access Log Bundles

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3357]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/log_bundles.md

**Comment by anchal-agrawal** [comment]
>    * Admin Server includes logs for the admin server

Admin Server includes logs for the **VCH** admin server

> Live logs can help you to see how any current changes you make might affect the logs. For example, when you try to troubleshoot an issue, you can see if your attempt worked or failed by looking at the live logs.
> You can share the non-live version of the logs with administrators or VMware Support to help you to solve issues.


**Live logs can help you see information about current commands/changes as you perform them.** For example, **when you are troubleshooting** an issue, you can see if your **command** worked or failed by looking at the live logs.
You can share the non-live version of the logs with administrators or VMware Support to help you **resolve** issues.

**Comment by npakrasi** [comment]
Thanks! Made the edits to the topic.

**Comment by sgairo** [comment]
LGTM with @anchal-agrawal 's edits

**Comment by stuclem** [comment]
Moving this to In Progress pending review by @hickeng

**Comment by hickeng** [comment]
> Initialization & watchdog reports network configuration, component launch status for the VCH Admin portal and the port layer, records if they fail, and relaunches them if they do. The binary vic-init launches the components and redirects their output to the log files in /var/log/vic/. At higher debug levels, the component output is duplicated in that log file, so init.log includes a superset of the log data.

This is mixing details about what the vic-init component does with what the log contains.

Initialization & watchdog reports:
* network configuration
* component launch status for the other components
* reports component failure and restart counts
* at higher debug levels, the component output is duplicated in this log file, so init.log includes a superset of the log data.
* this log file is duplicated on the datastore in the endpointVM folder, and is named `tether.debug` - this is to allow debugging of early stage initialization and network configuration issues.

**Comment by npakrasi** [comment]
Thanks George. Added your edits to the file.

**Comment by stuclem** [comment]
Made a couple of minor edits in https://github.com/stuclem/vic/commit/f74b89c4077bca22a5027a63c93deb06581c742e.

Changes are in. Don't think that this needs another pass. Closing.
