### ISSUE TITLE
Doc Review: Obtain vic-machine Version Information

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3358]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/vic_machine_version.md#obtain-vic-machine-version-information

> $ vic-machine-darwin-linux-windows version

Do we still have this? I don't find "vic-machine-darwin-linux-windows" under bin.

**Comment by chengwang86** [comment]
> vic-machine--darwin-linux-windows.exe 
version vic_machine_version-vic_machine_build-tag

When I run "vic-machine-windows.exe version", I get
```
C:\Users\wangcheng\Downloads\vic_7257.tar\vic>vic-ui-windows.exe version
vic-ui-windows.exe version 7257-95539591cc1acda3565e5ebb3911a9c5d8dc609b
```

When I run "vic-machine-linux version" with the same build (7257), I get 
```
./vic-machine-linux version
vic-machine-linux version v0.8.0-rc2-7257-9553959
```

So it seems that the rule "vic_machine_version-vic_machine_build-tag" only works for "vic-machine-linux version". Not sure about darwin.

If what I find makes sense, maybe we just need to replace "vic-machine-darwin-linux-windows" with "vic-machine-linux" in the doc as an example of "vic-machine version".

**Comment by anchal-agrawal** [comment]
> * `tag` is the hashtag of this build.

   * `tag` is the short git commit checksum for the latest commit for this build.

**Comment by stuclem** [comment]
Thanks @chengwang86 and @anchal-agrawal!

@chengwang86 I just ran `vic-machine-windows.exe` version and got the following:

```
$ vic-machine-windows version
vic-machine-windows.exe version v0.8.0-rc2-7234-191d796
```

However, I agree that including vic-machine-_darwin_-_linux_-_windows_ is ugly and confusing, so I have changed this to vic-machine-<i>operating_system</i> throughout the doc.

@anchal-agrawal I added the short git checksum info.

Changes are in https://github.com/stuclem/vic/commit/e39b898e9ed36f6625db68b4e8b00b1132c51620. Is this OK?

**Comment by anchal-agrawal** [comment]
LGTM, thanks Stuart.

**Comment by chengwang86** [comment]
LGTM

**Comment by emlin** [comment]
> version vic_machine_version-vic_machine_build-tag

The description for these three parts are all right now. But the name are kind of confusing. Cause vic-machine-version currently is actually github tag, and the tag is actually github commit hash. It would be confusing if customer knows the github naming convention.

**Comment by stuclem** [comment]
Thanks @emlin. Changed `tag` to `git_commit` both here and in the topic on `ls`.

Changes are in https://github.com/stuclem/vic/commit/a01efee27e8ac829f295e9b7de563cf7c98ad5c2.

Minor change. Think it's safe to close.
