### ISSUE TITLE
Doc Review: Insecure Private Registry

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3363]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_insecure_registries_with_vic.md

**Comment by sflxn** [comment]
```
An insecure private registry server is a private registry server that is secured by self-signed certificates rather than by TLS.
```
That's not correct.  Here is the correct version.

```
An insecure private registry server is a private registry server that is not secured by TLS (accessible with HTTP instead of HTTPS).
```

**Comment by sflxn** [comment]
```If your Docker environment stores Docker images in an insecure private registry server, you or the vSphere administrator must have set the vic-machine create --insecure-registry option when creating the virtual container host (VCH). Setting the insecure-registry option on a VCH informs that VCH that it is permitted to pull images from the designated insecure registry server.```

Change to

```If you setup a private registry with no certificates, you or the vSphere administrator must use the vic-machine create option "--insecure-registry" when creating the VCH.
```

**Comment by sflxn** [comment]
```
NOTE: The current builds of vSphere Integrated Containers do not yet support private registry servers that you secure by using TLS certificates.
```

This isn't true anymore.  Actually, we should change this entire page.  VIC GA supports both secure and insecure registries now.

**Comment by sflxn** [comment]
Change the page title to "Using Private Registry Servers with vSphere Integrated Containers Engine".  Also, we should add information on how to use secure private registries.  The vic-machine option is --registry-ca.

Also, certificates are used a lot in this document.  We should somehow clarify that there is certificate between the docker client and the VCH and then there is certificate between the VCH and registries.  I don't think neither our vic-machine options nor our documentation has been thorough about explaining this.  You can use one without the other.  For instance, you can disable client TLS use but still specify certificate for registry use.  Then there is certificate for vic-admin.

It's a confusing topic.  If you want to slack me, I can explain the private registry permutations.

**Comment by sflxn** [comment]
The examples you show will be confusing to users given my last comment.  In your example, the user is using client certificate to access an insecure private registry.  It is also possible to not use client certificate and insecure registry.  Here's the permutations:

1. no-tls for VCH, insecure private registry (with TLS, --insecure-registry)
2. no-tls for VCH, secure private registry (with TLS, --registry-ca)
3. TLS for VCH (from Advanced Security section), insecure private registry (with TLS, --insecure-registry)
4. TLS for VCH (from Advanced Security section), secure private registry (with TLS, --registry-ca)

As you can see, client certificate usage and private registry's certificate usage are independent of each other.

**Comment by hickeng** [comment]
concur with @sflxn - we should have two sections on this page:
1. secure private registry example
2. insecure private registry example

> For simplicity, the examples in this topic assume that the VCHs implement TLS authentication with self-signed untrusted certificates, with no client verification.

I think this line adds more confusion than clarity.

**Comment by stuclem** [comment]
Thanks @sflxn and @hickeng.

This resulted in a total rewrite, so I won't enumerate the changes that I have made. Also touched on the descriptions of the registry options, based on things that you said here.

Changes in https://github.com/stuclem/vic/commit/02c7d53ef06053c1f6fce5091bda106ee4bb97fd

This definitely needs another pass.

**Comment by hickeng** [comment]
reviewed with comments.

**Comment by stuclem** [comment]
Thanks @hickeng . Took your comments from https://github.com/stuclem/vic/commit/02c7d53ef06053c1f6fce5091bda106ee4bb97fd

Updates are in https://github.com/stuclem/vic/commit/5440ffd335c9a0ae9b7cd08e89b0f8abb5aa051a.

Think that we can close this one now.
