### ISSUE TITLE
Doc Review: VCH Debug Options

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3372]
--authorized-key description sounds a bit weird.

Current:

> Upload a public key file to /root/.ssh/authorized_keys folder in the endpoint VM to implement public authentication when accessing the VCH endpoint VM. Include the name of the *.pub file in the path

The problem with phrasing is this is not a public authentication, it is a public key that can be safely disclosed to anybody, so I could use my private key to authenticate myself.

Should be something like this:

> Upload a public key file to /root/.ssh/authorized_keys to enable SSH key authentication for the root user.

**Comment by stuclem** [comment]
Thanks @vburenin and @hickeng!
Took your phrasing directly. 
Change is in https://github.com/stuclem/vic/commit/9288fe414fc91d5241ec1eefb75e84fec66c3353

Simple change, so closing.
