### ISSUE TITLE
Doc Review:  Connections Fail with Certificate Errors when Using Full TLS Authentication with Trusted Certificates

### ISSUE THREAD

**Issue by jzt** [vmware/vic#3375]

**Comment by jzt** [comment]
@stuclem This doc looks good to me. I tested it locally by intentionally skewing the time to get the documented error message. Changing it back according to the instructions fixed the problem as documented.

It might be worth explaining the time window that is allowed (currently 1 day skew tolerance), which could indicate a different certificate error than time skew.

Given that, it may also be worth documenting the format that `date` expects. The two I would probably consider most useful are:

- Unix Time Stamp:  `date --set='@1480969133'`  
- YYYYMMDD HH:MM format:   `date --set="20161205 14:31"`

**Comment by stuclem** [comment]
Thanks @jzt.  Done. Changes are in https://github.com/stuclem/vic/commit/bbd9f0116f7f531c4cbab225eb950a51a97c00ed.

Leaving Done pending your LGTM!

**Comment by jzt** [comment]
LGTM 👍

**Comment by stuclem** [comment]
Thanks!
