### ISSUE TITLE
Doc Review: General deployment examples

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3378]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#general

**Comment by mhagen-vmware** [comment]
Gonna need thumbprint or --force in these examples as well. Again --force would be simpler.

**Comment by emlin** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#deploy-to-a-resource-pool-on-an-esxi-host

I think we also need to specify --image-store for this case, cause no pre-requisition said that there is only datastore attached to the target esxi host.

**Comment by stuclem** [comment]
Thanks @mhagen-vmware and @emlin !

- Added "For simplicity, these examples use the `--force` option to disable the verification of the vCenter Server certificate, so the `--thumbprint` option is not specified" at the very top of the topic and added `--force` to all examples.
- Added image-store to the ESX resource pool example.

Changes are in https://github.com/stuclem/vic/commit/c635903595bb77a1c35342df2ed029aa86b3c38c. 

Leaving in In Progress pending review by Murali.

**Comment by stuclem** [comment]
Moving to done pending LGTMs from @mhagen-vmware and @emlin

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by emlin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @mhagen-vmware and @emlin !
