### ISSUE TITLE
Doc Review: Use and Limitations of Containers in vSphere Integrated Containers Engine

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3381]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/container_limitations.md

**Comment by mhagen-vmware** [comment]
Probably put in the default volume requirement here?  Not sure if you have that listed elsewhere, but also limitation that we don't support mapping local folders into the containers also.

**Comment by sflxn** [comment]
https://github.com/vmware/vic/tree/master/doc/application_workflow discusses a lot of limitations pertinent for production deployment.

**Comment by npakrasi** [comment]
Default volume is documented in https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md

**Comment by npakrasi** [comment]
Added info from the workflow doc.

**Comment by npakrasi** [comment]
@sflxn can you please LGTM this issue if the doc looks ok? https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/container_limitations.md

After GA we will put the workflow guidelines into a separate file.

**Comment by stuclem** [comment]
BTW, I have removed the workflow section and am working on it in another topic.

**Comment by stuclem** [comment]
Can we get a LGTM or final comments from @mhagen-vmware and @sflxn please?

Thanks!

**Comment by stuclem** [comment]
Also from @corrieb and @hickeng?

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by sflxn** [comment]
I think we should add a message in vic-machine to tell users to upgrade to 1.13 CLI or add DOCKER_API_VERSION=1.23 in their environment.

**Comment by stuclem** [comment]
I'm happy with review by just QE. Closing.
