### ISSUE TITLE
Doc Review: Environment Prerequisites for VCH Deployment

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3382]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md

**Comment by mlh78750** [comment]
>The vSphere Integrated Containers Engine installation and management utility, vic-machine, has been tested and verified on the following 64-bit OS, Windows, Mac OS, and Photon OS systems

We don't list any photon OS systems, but we do list a Linux OS. I'd recommend replacing Photon OS with Linux in this line.

**Comment by mlh78750** [comment]
> Deploying vSphere Integrated Containers Engine to vSphere 5.5 environments works but is unsupported.

Change to:
Deploying vSphere Integrated Containers Engine to vSphere 5.5 environments should work but is unsupported and may break at any time.

**Comment by mlh78750** [comment]
>The firewall on all ESXi hosts must be configured to allow connections on the back channel and to allow outbound connections on port 2377

The firewall on all ESXi hosts must be configured to allow outbound connections on port 2377.

**Comment by mlh78750** [comment]
>ESXi Host Requirements

This section includes both ESX and VC requirements. Perhaps we want to break this into two sections. One for stand alone ESX and another for ESX managed by VC.

**Comment by mlh78750** [comment]
>All ESXi hosts must be attached to any mapped vSphere networks.

All ESXi hosts must be attached to any container-networks used during the install of the VCH.

**Comment by mlh78750** [comment]
I think they combined ent and ent+ licenses going forward. @karthik-narayan might want to chime in, but we are only supporting folks on ent+ as far as I know. So I'd change the https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md#license-requirements section to just list that enterprise plus is required.

**Comment by mlh78750** [comment]
I think Role and Permissions Requirements has changed, but I don't know how to document. Need @hickeng to help with that one.

**Comment by mlh78750** [comment]
Done with review.

**Comment by hickeng** [comment]
> You can install vSphere Integrated Containers Engine in the following vSphere setups

List the supported configs in the same order as in the Deploy VCH page, given it's a duplication but with version details.

> Deploying vSphere Integrated Containers Engine to vSphere 5.5 environments works but is unsupported.

Remove this

> Deploying vSphere Integrated Containers Engine to a nested ESXi host, namely ESXi running in a virtual machine, is not supported in production environments. Deploying vSphere Integrated Containers Engine to a nested ESXi host is acceptable for testing purposes only.

Suggest a link or noting that this is because nested ESXi isn't supported, rather than a VICE limitation.

> Deploying vSphere Integrated Containers Engine to a vCenter Server instance that is running in Enhanced Linked Mode is fully supported.

This is neither a caveat nor a limitation - @mhagen-vmware do we support deploying to the non-primary whatever in ELM?


> ESXi host requirements

1. Suggest we add a _Storage Requirements_ section for consistency, and move the shared storage details there.
2. "back channel" has not been introduced as a concept - suggest we drop the why, and just state the host firewall requirements:
  * 2377 outgoing to the endpointVM
  * port 443 incoming from the endpointVM (https)

So I suggest:
```
## General ESXi Host Requirements ##

To be valid targets for virtual container hosts (VCHs) and container VMs ESXi hosts must have the following firewall configuration:
  - allow outbound tcp traffic to port 2377 on the endpointVM (used interactive container shell)
  - allow inbound HTTPS/tcp traffic on port 443 (used for datastore upload/download)

For instruction about how to open port 2377 on ESXi hosts, see VCH Deployment Fails with Firewall Validation Error.

## ESXi Host Requirements for vCenter clusters ##

If a host in a cluster does not meet the following requirements then it will not be utilized by the VCH:
- attached to storage used for image store and volume stores (see --image-store and --volume-store)
- attached to Distributed Port Groups used for the VCH bridge network and any mapped container networks (see --bridge-network and --container-network)

As such utilization of more than a single host in a cluster requires that shared storage be available.

For more information about distributed virtual switches, see Network Requirements below.
```

We desperately need a network diagram that identifies network roles, traffic flows, etc. I'll put one together once I've finished the rest of the doc reviews.

Roles and Permissions are still TBD - working through the breakdown in #1689

**Comment by stuclem** [comment]
Thanks @mlh78750 and @hickeng. 

- Removed Photon (I think that it was @mreferre who asked that we add Photon, but I defer to you).
- vSphere 5.5 support: added "and might not work in the future" per @mlh78750. @hickeng recommends removing this line completely, but I remember @mdubya66 saying that we shouldn't totally alienate the bulk of our customers who are still on 5.5. Furthermore, the procedures for deploying the UI plug-in to VCSA have a specific step for 5.5 users. To limit the support statement to 6.0 and 6.5 and then mention 5.5 in a later topic would be weird, in my opinion.
- Nested hosts: Reworded to "VMware does not support the use of nested ESXi hosts, namely running ESXi in virtual machines. Deploying vSphere Integrated Containers Engine to a nested ESXi host is acceptable for testing purposes only."
- License: Removed the table and just stated "vSphere Integrated Containers Engine requires a vSphere Enterprise Plus license." 
- Roles: commented this section out at the moment as it is no longer valid.
- ESX/Network requirements: Given all of your comments above, I have broken this into "ESXi Host Firewall Requirements", "ESXi Host Storage Requirements for vCenter Server Clusters", "General Network Requirements", and  "vCenter Server Network Requirements". This is quite a hefty rewrite/reorg, and definitely requires another pass. 

Changes are in https://github.com/stuclem/vic/commit/08a5f867bb20c643bad64b4e842f3d36d98d4b29.

Updated topic is here: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md (my fork, as not merged yet).

Thanks again!

**Comment by mdubya66** [comment]
IMO we should remove 5.5 completely.. @karthik-narayan should make the final call. The UI plugin should not reference 5.5 at all however. It does not work and is not being actively developed.

**Comment by stuclem** [comment]
OK, @mdubya66 I went ahead and removed all mention of 5.5. The step in the UI plugin procedures that mentions 5.5 is optional, and if you don't do it then the installer assumes that you're on 6.0/6.5. So, it's safe to remove those steps. I can easily reinstate them if @karthik-narayan says to do so.

Change is in https://github.com/stuclem/vic/commit/8ab4c66cf06a4578f71a4353ffa82b014c9c76d7.

**Comment by karthik-narayan** [comment]
Yes please, we do not officially support 5.5 and we should remove all mention of it.

**Comment by stuclem** [comment]
@karthik-narayan, done!

**Comment by hickeng** [comment]
@stuclem I've added comments to https://github.com/stuclem/vic/commit/08a5f867bb20c643bad64b4e842f3d36d98d4b29

**Comment by stuclem** [comment]
Thanks @hickeng. Updated the network prereqs per your comments above. Changes are in https://github.com/stuclem/vic/commit/130e0c0d5e9b2bbe583e361a283efc6c754673b7. 

Regarding your comment "We should check, but I believe that a portgroup is fundamentally isolated at in IP address level, even if using a private VLAN, so long as they use different VLAN ids", about the statement "If you are not using private VLANs, assign a VLAN ID to the port groups, to ensure that the bridge network and mapped container networks are isolated" @mlh78750 and @hmahmood should we remove or update this statement? Thanks!

**Comment by stuclem** [comment]
@mhagen-vmware could you also please take a look at https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md?

Thanks!

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mlh78750** [comment]
for https://github.com/vmware/vic/issues/3382#issuecomment-264847108 I think it just needs to say that they need to be isolated and using separate vlans is one way to do that.

**Comment by stuclem** [comment]
Added "Isolate the bridge network and any mapped container networks. You can isolate networks by using a separate VLAN for each network."

Change is in https://github.com/stuclem/vic/commit/f4e6bc48288584dc6d2e14d8f5e0c1ceda367ad3.

Moving to Done pending LGTMs from @mlh78750 and @hickeng.

**Comment by mlh78750** [comment]
lgtm

**Comment by stuclem** [comment]
Good enough. Closing!
