### ISSUE TITLE
Doc Review: Options to Configure VCHs to Use Proxy Servers

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3384]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#proxy

**Comment by mlh78750** [comment]
> If your network access is controlled by a proxy server, you must configure a VCH to connect to the proxy server when you deploy it.

If access to the internet or your private image registries requires use of a proxy server, you must configure a VCH to connect to the proxy server when you deploy it.

**Comment by mlh78750** [comment]
> The address of the HTTP proxy server through which the VCH accesses the network.

The address of the HTTP proxy server through which the VCH accesses image registries using HTTP.

> The address of the HTTPS proxy server through which the VCH accesses the network.

The address of the HTTPS proxy server through which the VCH accesses image registries using HTTPS.

**Comment by mlh78750** [comment]
I'm done with my review.

**Comment by hickeng** [comment]
> The proxy that you specify serves exclusively for pulling images into the VCH from an external source, and is not used for any other purpose.

The proxy is used only when pulling images, not for any other purpose.

_NOTE: put the https proxy first as it's both the more secure option and the one more likely to be used_

**Comment by stuclem** [comment]
Thanks @mlh78750 and @hickeng ! Comments integrated. Changes are in https://github.com/stuclem/vic/commit/537bc2d4bc81c5734ab5a5bcd5da788ea6ddb022. 

Straightforward cut-n-paste job, no need for another pass. Closing.
