### ISSUE TITLE
Move vic-ui-<os> binaries into ui folder

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3388]
If these binaries are not intended to be run directly (as per [the documentation](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/contents_of_vic_binaries.md#contents-of-the-vsphere-integrated-containers-engine-binaries)) then there's no benefit to having them in the root of the package. Having them there adds clutter and is misleading.

**Comment by jak-atx** [comment]
Done in #6543
