### ISSUE TITLE
Doc review: env prereqs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3392]
> You can install vSphere Integrated Containers Engine in the following vSphere setups

List the supported configs in the same order as in the Deploy VCH page, given it's a duplication but with version details.

> Deploying vSphere Integrated Containers Engine to vSphere 5.5 environments works but is unsupported.

Remove this

> Deploying vSphere Integrated Containers Engine to a nested ESXi host, namely ESXi running in a virtual machine, is not supported in production environments. Deploying vSphere Integrated Containers Engine to a nested ESXi host is acceptable for testing purposes only.

Suggest a link or noting that this is because nested ESXi isn't supported, rather than a VICE limitation.

> Deploying vSphere Integrated Containers Engine to a vCenter Server instance that is running in Enhanced Linked Mode is fully supported.

This is neither a caveat nor a limitation - @mhagen-vmware do we support deploying to the non-primary whatever in ELM?

> ESXi host requirements

1. Suggest we add a _Storage Requirements_ section for consistency, and move the shared storage details there.
2. "back channel" has not been introduced as a concept - suggest we drop the why, and just state the host firewall requirements:
  * 2377 outgoing to the endpointVM
  * port 443 incoming from the endpointVM (https)

So I suggest:
```
## General ESXi Host Requirements ##

To be valid targets for virtual container hosts (VCHs) and container VMs ESXi hosts must have the following firewall configuration:
  - allow outbound tcp traffic to port 2377 on the endpointVM (used interactive container shell)
  - allow inbound HTTPS/tcp traffic on port 443 (used for datastore upload/download)

For instruction about how to open port 2377 on ESXi hosts, see VCH Deployment Fails with Firewall Validation Error.

## ESXi Host Requirements for vCenter clusters ##

If a host in a cluster does not meet the following requirements then it will not be utilized by the VCH:
- attached to storage used for image store and volume stores (see --image-store and --volume-store)
- attached to Distributed Port Groups used for the VCH bridge network and any mapped container networks (see --bridge-network and --container-network)

As such utilization of more than a single host in a cluster requires that shared storage be available.

For more information about distributed virtual switches, see Network Requirements below.
```

We desperately need a network diagram that identifies network roles, traffic flows, etc. I'll put one together once I've finished the rest of the doc reviews.

**Comment by mhagen-vmware** [comment]
@hickeng Wasn't able to get to that point yet, just have a test that has ELM and install into either of the VCs works, but I don't know how to programattically or manually install across the ELM.
