### ISSUE TITLE
Resolver issue

### ISSUE THREAD

**Issue by carsonpadawon** [vmware/vic#3395]
VIC:  vic-machine-darwin version v0.8.0-rc2-7257-9553959

 ./vic-machine-darwin create -t vcsa6.carsontux.net -u administrator@carsontux.net -p VMware1! -r VIC -i datastore1 -b Bridge -n vch1 --pn Public --mn Public --cn Client --no-tlsverify --thumbprint 4B:22:A1:7F:2E:CA:DB:33:C3:57:96:E1:11:61:E0:0C:B8:D1:B8:15 --dns-server 172.16.78.2

Error Message:
WARN[2016-11-29T14:53:12-05:00] vSphere API Test: https://vcsa6.carsontux.net vSphere API target failed to respond to the query 
INFO[2016-11-29T14:55:37-05:00] Collecting 57a4c4c8-4081-4656-9c15-cbcd3d6d750c vpxd.log 
ERRO[2016-11-29T14:55:37-05:00] Failed to collect 57a4c4c8-4081-4656-9c15-cbcd3d6d750c vpxd.log: context deadline exceeded 
WARN[2016-11-29T14:55:37-05:00] No log data for 57a4c4c8-4081-4656-9c15-cbcd3d6d750c vpxd.log 
INFO[2016-11-29T14:55:37-05:00] Collecting host-10 hostd.log                 
ERRO[2016-11-29T14:55:37-05:00] Failed to collect host-10 hostd.log: context deadline exceeded 
WARN[2016-11-29T14:55:37-05:00] No log data for host-10 hostd.log            
ERRO[2016-11-29T14:55:37-05:00] --------------------                         
ERRO[2016-11-29T14:55:37-05:00] vic-machine-darwin failed: Create timed out: if slow connection, increase timeout with --timeout

Logs that shows the resolver issue:
root@vch1 [ /var/log/vic ]# /sbin/port-layer-server --sdk vcsa6.carsontux.net/sdk
INFO[0000] Launching portlayer server pprof server on 127.0.0.1:6063 
FATA[0000] configure_port_layer ERROR: Failed to connect to vcsa6.carsontux.net: Post https://vcsa6.carsontux.net/sdk: dial tcp: lookup vcsa6.carsontux.net on 172.16.78.2:53: too many redirects 
root@vch1 [ /var/log/vic ]# GODEBUG=netdns=cgo /sbin/port-layer-server --sdk vcsa6.carsontux.net/sdk
INFO[0000] Launching portlayer server pprof server on 127.0.0.1:6063 
FATA[0003] configure_port_layer ERROR: Failed to log in to vcsa6.carsontux.net: ServerFaultCode: Cannot complete login due to an incorrect user name or password.

**Comment by hmahmood** [comment]
This [go's built-in resolver](https://golang.org/pkg/net/) flakiness. Overriding to use the c resolver fixes the issues are indicated by the last command line above.

**Comment by mdubya66** [comment]
We should close this as will not fix. @hmahmood

**Comment by hmahmood** [comment]
I am fine with closing this; Fusion is to blame for this behavior. The Go resolver also consumes less resources (i.e. one go routine vs. one thread for the C resolver), so is preferable. There has been a bug filed for Fusion.
