### ISSUE TITLE
Doc review: cname mismatch

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3399]
## Cause ##

`vic-machine create` attempts to re-use certificates found in `--cert-path`. The default value of `--cert-path` derives from the `--name` value, so if you are deploying a VCH from the same location and with the same name as a prior VCH it will reuse the old certificates. This behaviour is to allow easy redeployment of a VCH without needing to re-issue client certificates to users.

Before reusing the existing certificates, `vic-machine` confirms that the existing certificate is valid given the options supplied for the new deployment. The options that influence this in order of priority are:
* --tls-cname if specified, or
* --client-ip-address, or 
* --public-ip-address if client and public network roles are sharing an interface

The error message means that the existing certificate has a Common Name attribute that differs from the value derived from the options detailed above.

## Solution ##

If you intend to reuse the certificates directly:
* change `--tls-cname`, `--client-ip-address`, or `--public-ip-address` to match the Common Name found in the existing certificate

If you wish to reuse the Certificate Authority so client certificates remain valid, but need to provide a different IP address:
* manually generate the server certificates using `openssl`, signed with the existing CA and supply the newly generated certs via the `--cert` and `--key` options

If you do _not_ wish to reuse the certificates:
* change the directory from which you run `vic-machine` - this will alter the default `--cert-path`
* change the value of `--name` - this will alter the default `--cert-path`
* specify `--cert-path` explicitly
* delete the existing certificates from `--cert-path`

**Comment by hickeng** [comment]
We can provide an openssl command to use for generating new server certificates from an existing CA if it becomes a common question.

**Comment by stuclem** [comment]
Took your rewrites almost verbatim, with a bit of formatting. 

Change is in https://github.com/stuclem/vic/commit/0c07e11d881f9195ea7c3e5e7f05d2bbb4d6781b. 

Think it's safe to close this one.
