### ISSUE TITLE
Doc review: api version error

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3400]
> (client API version: 1.24, server API version: 1.23).

This is an example - we could xxx out the client version as that's what will be changing

> Open a Docker client terminal.

We need to define what is meant by "Docker client terminal" - it's a terminal on a system that has a docker client installed, but the way this is phrased makes it sound to me like a completely separate terminal client of some kind.

_Provide an example docker info command that does not have --tls_
`docker -H virtual_container_host_address:2375 info`

**Comment by stuclem** [comment]
Dup of https://github.com/vmware/vic/issues/3344
