### ISSUE TITLE
Doc Review: Advanced Security Options

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3402]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#adv-security

**Comment by sflxn** [comment]
Need to add --registry-ca for self-signed secured registries.

Short name: --rc

```
The path to a self-generated CA certificate, mainly used for testing purposes.  This certificate allows the VCH to validate a registry that is using a certificate and private key signed with the self-generated CA certificate.  There may be more than 1 CA certificate specified.  The use of these certificates are independent of the client security options.  In other words, it is possible to disable TLS (via --no-tls) for client authentication and upload CA certificates to the VCH during installation.
```

**Comment by hickeng** [comment]
I think the --registry-ca should be in the main Security Options, paired with --insecure-registry, grouped under a "Private registry" section. This is likely to be a common configuration.

**Comment by hickeng** [comment]
> It also uses the IP address or FQND of the VCH as the organization if you set a static IP address by using the --client-network-ip and --client-network-gateway options

It uses the IP configured on the _client_ interface if set - that can be either via --client-network-ip or --public-network-ip (the latter if they're sharing an interface). Client and public sharing an interface is going to be the common case for this release as we have 4 roles but only allow 3 distinct networks currently.

**Comment by hickeng** [comment]
Cert Path:
> A folder in which to store auto-generated certificates. If the path to the folder that you specify does not already exist, vic-machine create creates it. If not specified, vic-machine create stores auto-generated certificates in a folder with the same name as the VCH, in the folder from which you run vic-machine create.
> When you deploy a VCH, vic-machine create checks for existing certificates, either in the default location or in the folder that you specify in --cert-path.

I think this would have a cleaner phrasing if we say:

By default `--cert-path` is a folder in the current directory, named by the value of the `--name` option. `vic-machine create` checks in `--cert-path` for existing certificates with the standard names and will use those certificates if present:
* `server-cert.pem` and `server-key.pem`
* `ca.pem`

Certificates will be generated if not found with the standard names in `--cert-path` or specified directly via `--cert`, `--key`, and `--tls-ca` options. Generated certificates will be saved in `--cert-path` with the standard names above, and additionally:
* `cert.pem` and `key.pem` - client certificate if needed
* `ca-key.pem` - the private key for the certificate authority

**Comment by stuclem** [comment]
Thanks @sflxn and @hickeng.

- Added new section, Private Registry Options, under the main Security Options section. 
- Included @sflxn's writeup of `--registry-ca`, with some tweaks.
- Updated `--insecure-registry` with comments made by @hickeng in https://github.com/vmware/vic/issues/3416.
- Took @hickeng 's suggestion for `--organization`.
- Took @hickeng 's suggestions for `--cert-path`, with tweaks.
- Updated --cert and --key based on @hickeng's comments in https://github.com/vmware/vic/issues/3416.

Changes are in https://github.com/stuclem/vic/commit/726675e60a83953cbecc246338602547e9ab93f1. 

This definitely needs another pass, so leaving in In Progress.

**Comment by hickeng** [comment]
@stuclem Updates as comments in https://github.com/stuclem/vic/commit/726675e60a83953cbecc246338602547e9ab93f1

**Comment by stuclem** [comment]
Thanks @hickeng . Implemented your comments from https://github.com/stuclem/vic/commit/726675e60a83953cbecc246338602547e9ab93f1.

Updates are in https://github.com/stuclem/vic/commit/5440ffd335c9a0ae9b7cd08e89b0f8abb5aa051a. Think that we can close this one now.
