### ISSUE TITLE
Doc review: security reference

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3404]
## Network Security ##

It is highly recommended for VIC 0.8 that a secure management network be used. The containerVMs communicate with the endpoint VM over the management network when an interactive shell is required - while the communication is encrypted, the public keys are not validated which leaves scope for man-in-the-middle attacks. This connection is _only_ used for the interactive console when enabled (stdin/out/err), and _not_ for any other purpose.

### Endpoint VM ###
Client interface:
* 2375 - insecure port for Docker API access (if deployed with `--no-tls`)
* 2376 - TLS secured port for Docker API access
* 22 - SSH (when enabled via `vic-machine debug`)
* 2378 - VIC admin server - health and log access (HTTPS)
* 6060 - pprof debug data (when enabled via --debug levels)

Management interface:
* 2377 - incoming connections on the management interface from containerVMs
* outgoing connections are established to:
  * vSphere target (port 443)
  * ESX hosts (port 443)

Bridge interface:
* 53 - DNS server for container name resolution

Public interface:
* any port not listed as used elsewhere may be forwarded to a containerVM

### Container VM ###
* 6060 - pprof debug data (when enabled via --debug levels)
* when not configured for debug, no ports are used by VIC

**Comment by hickeng** [comment]
Still working through the service accounts and privileges in #1689

**Comment by stuclem** [comment]
Thank you @hickeng. @npakrasi, this one's for you :)

**Comment by npakrasi** [comment]
Incorporated first set of comments. Thanks George!

**Comment by npakrasi** [comment]
@hickeng If the doc looks ok, can you please give an LGTM here so I can close the issue?
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_security/security_reference.md
Thanks!

**Comment by dougm** [comment]
We don't create vCenter Extensions anymore.  usage.md mentions the ops-user/ops-password options, should probably mention that here too.  otherwise, LGTM

**Comment by npakrasi** [comment]
Thanks @dougm. I added this: The `--ops-user` and `--ops-password` options allow a VCH to operate with less-privileged credentials than those that are required for deploying a new VCH.

**Comment by hickeng** [comment]
@stuclem LGTM - I still need to provide a more minimal RBAC configuration to be added here.

**Comment by stuclem** [comment]
Thanks @hickeng . Moving this back into To Do.

**Comment by stuclem** [comment]
Also added a section on Sensitive Data, per https://github.com/vmware/vic/issues/2514.

**Comment by stuclem** [comment]
@hickeng added info about RBAC in https://github.com/vmware/vic/issues/1689#issuecomment-266613074.

**Comment by stuclem** [comment]
Reviewed by @cgtexmex in https://github.com/vmware/vic/issues/2514.
