### ISSUE TITLE
Strip network mask from IP address for cert check.

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3410]
At the moment if --tls-cname is not specified vic-machine automatically takes clientNetworkIP/publicNetworkIP/managementNetworkIP as a value for cname. Unfortunately, it also means that it will automatically include a network mask that is not a part of a host name.
If user run this command second time with pre-generated certificates, it is going to fail since ip/mask is not equal IP.

**Comment by mdubya66** [comment]
This needs further discussion. Backlogging

**Comment by vburenin** [comment]
Fixed in #3519
