### ISSUE TITLE
Port map tests on VC: Can't curl the nginx server

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3414]
Both:
Create container with port mappings
and 
Container to container traffic via VCH public interface

Are the only tests in this suite that actually curl the endpoint and they both fail on that step. I increased the timeout significantly up to 3 minutes, but still the connection is refused.

[port-map.zip](https://github.com/vmware/vic/files/622721/port-map.zip)

**Comment by anchal-agrawal** [comment]
I can't repro this on a nimbus VC 6.5 with one host. Could we have had multiple VCHs on the same bridge network (https://github.com/vmware/vic/issues/2354) where this failure occurred?

**Comment by anchal-agrawal** [comment]
From the hostd logs, we found multiple VCHs on the host. They appear to be using the same bridge network based on the suite setup steps.

The failure occurred on `VCH-0-9827` and there are other live VCHs:

<img width="656" alt="screen shot 2016-11-30 at 17 12 38" src="https://cloud.githubusercontent.com/assets/4361620/20775396/4d562fcc-b720-11e6-96bf-f4172ce1e72e.png">

**Comment by mhagen-vmware** [comment]
Appears to be the dupe issue @anchal-agrawal mentioned.  Passed this morning.
