### ISSUE TITLE
Doc review: security examples

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3416]
> You can deploy a VCH that implements two-way authentication with trusted auto-generated TLS certificates that are signed by a CA. To automatically generate a trusted CA certificate, you provide information that vic-machine create uses to populate the fields of a certificate request

We do not create a certificate request (CSR):
To automatically generate a server certificate that can pass client verification you must specify the CommonName (CN) for the certificate via the `--tls-cname` option. The CN should be the server's FQDN, IP address, or domain with wildcard and must match the name or address that clients will used to connect to the server. You may use the `--organization` option to add basic descriptive detail to the server certificate - this will be visible to clients if they inspect the server certificate.
If you specify an existing CA file with which to validate clients, then you must also provide an existing server certificate that is compatible with the `--tls-cname` value or IP address for the client interface.

@stuclem can we make `via the --tls-cname option` a link to the section that docs it?

The example will most likely deploy an invalid VCH as it will be using DHCP for the client interface. Instead:

Specifies the user, password, datacenter, image store, cluster, bridge network, and name for the VCH.
Specifies a folder in which to store the auto-generated certificates.
Provides a wildcard domain *.example.org as the FQDN for the VCH, for use as the Common Name in the certificate. This assumes that there is a DHCP server offering IP addresses on "VM Network" (the default portgroup name) and those addresses have corresponding DNS entries such as `dhcp-a-b-c.example.com`
```
vic-machine-darwin-linux-windows create
--target 'Administrator@vsphere.local:password@vcenter_server_address/dc1'
--compute-resource cluster1
--image-store datastore1
--bridge-network vch1-bridge
--tls-cname *.example.org
--cert-path path_to_cert_folder
--name vch1
```
The Docker API for this VCH would then be accessed at https://dhcp-a-b-c.example.com:2376

**Comment by hickeng** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md#use-custom-trusted-ca-certificates

This is incorrect. This example is for a custom _server certificate_, not a custom CA - this is the same approach one would take if wanting to use a _server_ certificate signed by Verisign (or another public root).

**Comment by hickeng** [comment]
> An insecure private registry server is a private registry server for Docker images that is secured by self-signed certificates rather than by TLS.

A self-signed certificate doesn't allow you to confirm the identity of the remote system, but still provides TLS (encrypted communication). As such you are protected from an attacker sniffing your network traffic, but not from man-in-the-middle attacks.

**Comment by stuclem** [comment]
Thanks @hickeng. Took your suggestions almost verbatim. 

Changes are in https://github.com/stuclem/vic/commit/db87cc89addc7fa9b15412fe049fe3692e13863a. 

I'd appreciate another pass before closing. Thanks!

**Comment by hickeng** [comment]
Minor comment, otherwise LGTM

**Comment by stuclem** [comment]
Thanks @hickeng. Closing.
