### ISSUE TITLE
Create VCH with static IP fails with "Could not run VCH vSphere API target check due to ServerFaultCode: A general system error occurred: vix error codes = (3016, 0)."

### ISSUE THREAD

**Issue by mobla** [vmware/vic#3417]
**hickeng update: 28/04/2017**
The is the result of the vSphere API check taking longer than the guest tools ping interval - this results in an incorrect report that guest tools is not running (vix error 3016).
We also saw this symptom while diagnosing #4961 which, like @cormachogan, was a DNS issue resulting in being unable to resolve VC.

There are two parts to addressing this:
- [ ] implement the async portion of guest operations
- [ ] ensure that actual, useful, user actionable error messages result

This may require #4961 be fixed to allow for easy testing of the name resolution failure.
@dougm Estimate is for you working on this.

**original**
vic version: vic-machine-linux version v0.8.0-rc2-7257-9553959 (rc3 build)
vSphere 6.0: GA build# 2656761
ESX 6.0 (physical):  GA build# 2809209

Steps:
a. Create VCH with Static IP below is the command
b. Fails with Could not run VCH vSphere API target check due to ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).
 
```
root@photon-lJUA39j42 [ ~/vic/vic ]# ./vic-machine-linux create --name VCH-NW-1 --target corevcqe-pod.eng.vmware.com/vcqaDC --user root --password 'Admin!23' --compute-resource 1vic-cluster --image-store shared-iscsi-220 --volume-store=shared-iscsi-220/registry:default --tls-cname="*.eng.vmware.com" --thumbprint F0:53:BB:23:44:2D:5C:19:4F:3D:72:64:60:37:EA:F5:4E:76:10:AF --bridge-network vic-bridge-nw --client-network vic-client-mgmt-nw --client-network-gateway 1.1.1.0/24:10.172.64.62/26 --client-network-ip 10.172.64.7/26 --management-network vic-client-mgmt-nw --public-network vic-public-nw --public-network-gateway 10.172.64.126/26 --public-network-ip 10.172.64.70 --dns-server 10.172.40.1 --dns-server 10.172.40.2 --timeout 10m
INFO[2016-12-01T00:59:45Z] ### Installing VCH ####
WARN[2016-12-01T00:59:45Z] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2016-12-01T00:59:45Z] Generating CA certificate/key pair - private key in VCH-NW-1/ca-key.pem
INFO[2016-12-01T00:59:45Z] Generating server certificate/key pair - private key in VCH-NW-1/server-key.pem
INFO[2016-12-01T00:59:46Z] Generating client certificate/key pair - private key in VCH-NW-1/key.pem
INFO[2016-12-01T00:59:46Z] Generated browser friendly PFX client certificate - certificate in ./VCH-NW-1/cert.pfx
INFO[2016-12-01T00:59:47Z] Validating supplied configuration
INFO[2016-12-01T00:59:47Z] Configuring static IP for additional networks using port group "vic-client-mgmt-nw"
INFO[2016-12-01T00:59:47Z] Configuring static IP for additional networks using port group "vic-public-nw"
INFO[2016-12-01T00:59:47Z] vDS configuration OK on "vic-bridge-nw"
INFO[2016-12-01T00:59:47Z] Firewall status: DISABLED on "/vcqaDC/host/1vic-cluster/sc2-haas01-esx0081.eng.vmware.com"
INFO[2016-12-01T00:59:47Z] Firewall status: DISABLED on "/vcqaDC/host/1vic-cluster/sc2-haas01-esx0082.eng.vmware.com"
WARN[2016-12-01T00:59:47Z] Firewall configuration will be incorrect if firewall is reenabled on hosts:
WARN[2016-12-01T00:59:47Z]      "/vcqaDC/host/1vic-cluster/sc2-haas01-esx0081.eng.vmware.com"
WARN[2016-12-01T00:59:47Z]      "/vcqaDC/host/1vic-cluster/sc2-haas01-esx0082.eng.vmware.com"
INFO[2016-12-01T00:59:47Z] Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
INFO[2016-12-01T00:59:47Z] License check OK on hosts:
INFO[2016-12-01T00:59:47Z]   "/vcqaDC/host/1vic-cluster/sc2-haas01-esx0081.eng.vmware.com"
INFO[2016-12-01T00:59:47Z]   "/vcqaDC/host/1vic-cluster/sc2-haas01-esx0082.eng.vmware.com"
INFO[2016-12-01T00:59:47Z] DRS check OK on:
INFO[2016-12-01T00:59:47Z]   "/vcqaDC/host/1vic-cluster/Resources"
INFO[2016-12-01T00:59:47Z]
INFO[2016-12-01T00:59:48Z] Creating virtual app "VCH-NW-1"
INFO[2016-12-01T00:59:48Z] Creating directory [shared-iscsi-220] registry
INFO[2016-12-01T00:59:48Z] Datastore path is [shared-iscsi-220] registry
INFO[2016-12-01T00:59:48Z] Creating appliance on target
INFO[2016-12-01T00:59:48Z] Network role "management" is sharing NIC with "client"
INFO[2016-12-01T01:00:08Z] Uploading images for container
INFO[2016-12-01T01:00:08Z]      "bootstrap.iso"
INFO[2016-12-01T01:00:08Z]      "appliance.iso"
INFO[2016-12-01T01:01:03Z] Waiting for IP information
INFO[2016-12-01T01:02:44Z] Waiting for major appliance components to launch
INFO[2016-12-01T01:02:44Z] Checking VCH connectivity with vSphere target
WARN[2016-12-01T01:03:44Z] Could not run VCH vSphere API target check due to ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).
```
screenshot: 
![vic-vch-static-ip-nw](https://cloud.githubusercontent.com/assets/3538999/20778481/dbd5e2d6-b722-11e6-8fd9-63c761dab56f.png)

attached the vpxd log: 
[vpxd.tar.gz](https://github.com/vmware/vic/files/623498/vpxd.tar.gz)

vm vmware.log:
[vmware.tar.gz](https://github.com/vmware/vic/files/623513/vmware.tar.gz)

**Comment by mobla** [comment]
![vic-vch-static-ip-nw](https://cloud.githubusercontent.com/assets/3538999/20778384/2589ed88-b722-11e6-8d22-5e1564f8e57e.png)

**Comment by mobla** [comment]
vpxd log snippet
------------------
```
2016-12-01T00:25:38.327Z info vpxd[7FF7FA08A700] [Originator@6876 sub=Default opID=2c5c4399] [VpxLRO] -- ERROR task-internal-19412314 -- guestOperationsProcessManager -- vim.vm.guest.ProcessManager.startProgram: vmodl.fault.SystemError:
--> Result:
--> (vmodl.fault.SystemError) {
-->    faultCause = (vmodl.MethodFault) null,
-->    reason = "vix error codes = (3016, 0).
--> ",
-->    msg = "Received SOAP response fault from [<cs p:00007ff7e40f6900, TCP:sc2-haas01-esx0082.eng.vmware.com:443>]: startProgram
--> Received SOAP response fault from [<cs p:1f35f9d0, TCP:localhost:8307>]: startProgram
--> A general system error occurred: vix error codes = (3016, 0).
--> "
--> }
--> Args:
-->
--> Arg vm:
--> 'vim.VirtualMachine:vm-4'
--> Arg auth:
--> (vim.vm.guest.NamePasswordAuthentication) {
-->    interactiveSession = false,
-->    username = "",
-->    password = (not shown)
--> }
--> Arg spec:
--> (vim.vm.guest.ProcessManager.ProgramSpec) {
-->    programPath = "test-vc-api",
-->    arguments = "https://corevcqe-pod.eng.vmware.com",
-->    workingDirectory = "/",
--> }
2016-12-01T00:25:44.171Z info vpxd[7FF7FA009700] [Originator@6876 sub=vpxLro opID=171a7e08] [VpxLRO] -- BEGIN task-internal-19412366 -- SessionManager -- vim.SessionManager.sessionIsActive -- 52b3e2b6-8aa3-1cd0-600b-3ed7a9435e7b(520a0515-4c29-01c8-b399-23b6390ddb32)
```

**Comment by mlh78750** [comment]
This configuration is not supported. The ip address ranges should not overlap on the two networks. 

That being said, I don't think we should have this vpx issue.

**Comment by mobla** [comment]
If you notice, I have made client nw and public nw in a different subnet (see the gateways, they are different separate VLAN). This is a valid networking configuration which works for "vCenter HA" configuration without any issues..

--client-network-gateway 1.1.1.0/24:10.172.64.62/26 
--client-network-ip 10.172.64.7/26 

--public-network vic-public-nw 
--public-network-gateway 10.172.64.126/26 
--public-network-ip 10.172.64.70

**Comment by mlh78750** [comment]
Can a VM attached to vic-client-mgmt-nw port group reach the VC at corevcqe-pod.eng.vmware.com without routing? If corevcqe-pod.eng.vmware.com resolves to anything that is not L2 adjacent to the VCH, then it will need to be entered in the destinations for the gateway. I know we used 1.1.1.1 to get around the limitation of having to supply it, but if corevcqe-pod.eng.vmware.com is in another IP space, you need to specify that IP space in the gateway destinations for the client network. 

I'll get on the VPN and resolve that hostname so I can see if that is the problem.

**Comment by mlh78750** [comment]
Name:	corevcqe-pod.eng.vmware.com
Address: 10.138.64.31

Which means you need to add that to the destinations for the client IP gateway. 

Something like --client-network-gateway 10.138.64.0/24:10.172.64.62/26   
and that assumes that 10.138.64.0 is a /24 and that there is a router at 10.172.64.62 that knows how to get there.

You'll likely need to introduce another router in your setup to get this to work.

**Comment by hickeng** [comment]
It looks like the error is because toolbox isn't running. This suggests a problem with vic-init. Can you check the tether.debug file in the endpointVM directory on the data store.

**Comment by gonghuahill** [comment]
same error on 0.8.0.rc3
vsphere 6.0 3620759 vcenter 6.0 3634794
[root@web-01a vic]# more c3.sh
./vic-machine-linux create  --target vcsa-01a.corp.local --force --image-store RegionA01-ISCSI01
-COMP01  --user administrator@vsphere.local --bridge-network dvPortGroup-bridge   --compute-reso
urce  RegionA01-COMP01 -p VMware1!  -name vch4 --no-tls --public-network dvPortGroup-ext --publi
c-network-ip 192.168.110.72/24 --public-network-gateway 192.168.110.1/24  --management-network dvPortGroup-ext  --client-network dvPortGroup-ext  --dns-server 8.8.8.8
[root@web-01a vic]# ./c3.sh
INFO[2016-12-01T11:12:08-08:00] ### Installing VCH ####
WARN[2016-12-01T11:12:08-08:00] Using administrative user for VCH operation - us                                                                                                 e --ops-user to improve security (see -x for advanced help)
WARN[2016-12-01T11:12:08-08:00] Configuring without TLS - all communications wil                                                                                                 l be insecure
INFO[2016-12-01T11:12:08-08:00] Validating supplied configuration
INFO[2016-12-01T11:12:08-08:00] Configuring static IP for additional networks us                                                                                                 ing port group "dvPortGroup-ext"
INFO[2016-12-01T11:12:08-08:00] vDS configuration OK on "dvPortGroup-bridge"
INFO[2016-12-01T11:12:08-08:00] Firewall status: DISABLED on "/RegionA01/host/Re                                                                                                 gionA01-COMP01/esx-01a.corp.local"
INFO[2016-12-01T11:12:08-08:00] Firewall status: DISABLED on "/RegionA01/host/Re                                                                                                 gionA01-COMP01/esx-02a.corp.local"
WARN[2016-12-01T11:12:08-08:00] Firewall configuration will be incorrect if fire                                                                                                 wall is reenabled on hosts:
WARN[2016-12-01T11:12:08-08:00]         "/RegionA01/host/RegionA01-COMP01/esx-01                                                                                                 a.corp.local"
WARN[2016-12-01T11:12:08-08:00]         "/RegionA01/host/RegionA01-COMP01/esx-02                                                                                                 a.corp.local"
INFO[2016-12-01T11:12:08-08:00] Firewall must permit dst 2377/tcp outbound to VC                                                                                                 H management interface if firewall is reenabled
INFO[2016-12-01T11:12:09-08:00] License check OK on hosts:
INFO[2016-12-01T11:12:09-08:00]   "/RegionA01/host/RegionA01-COMP01/esx-01a.corp                                                                                                 .local"
INFO[2016-12-01T11:12:09-08:00]   "/RegionA01/host/RegionA01-COMP01/esx-02a.corp                                                                                                 .local"
INFO[2016-12-01T11:12:09-08:00] DRS check OK on:
INFO[2016-12-01T11:12:09-08:00]   "/RegionA01/host/RegionA01-COMP01/Resources"
INFO[2016-12-01T11:12:09-08:00]
INFO[2016-12-01T11:12:09-08:00] Creating virtual app "vch4"
INFO[2016-12-01T11:12:09-08:00] Creating appliance on target
INFO[2016-12-01T11:12:09-08:00] Network role "management" is sharing NIC with "c                                                                                                 lient"
INFO[2016-12-01T11:12:09-08:00] Network role "public" is sharing NIC with "clien                                                                                                 t"
INFO[2016-12-01T11:12:11-08:00] Uploading images for container
INFO[2016-12-01T11:12:11-08:00]         "appliance.iso"                                                                                                                          
INFO[2016-12-01T11:12:11-08:00]         "bootstrap.iso"                                                                                                                          
INFO[2016-12-01T11:12:23-08:00] Waiting for IP information
INFO[2016-12-01T11:12:43-08:00] Waiting for major appliance components to launch                                                                                                 
INFO[2016-12-01T11:12:53-08:00] Checking VCH connectivity with vSphere target
WARN[2016-12-01T11:13:53-08:00] Could not run VCH vSphere API target check due t                                                                                                 o ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).

**Comment by gonghuahill** [comment]
And then modify the dns to real server 192.168.110.10  ,and add record about 192.168.110.72  vch4.corp.local ,pass the create action

[root@web-01a vic]# more c3.sh
./vic-machine-linux create  --target vcsa-01a.corp.local --force --image-store RegionA01-ISCSI01-COMP01  --user administrator@vsphere.local --bridge-network dvPortGroup-bridge
 --compute-resource  RegionA01-COMP01 -p VMware1!  -name vch4 --no-tls --public-network dvPortGroup-ext --public-network-ip 192.168.110.72/24 --public-network-gateway 192.168.11
0.1/24  --management-network dvPortGroup-ext  --client-network dvPortGroup-ext  --dns-server 192.168.110.10
INFO[2016-12-01T11:30:24-08:00] ### Installing VCH ####
WARN[2016-12-01T11:30:24-08:00] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
WARN[2016-12-01T11:30:24-08:00] Configuring without TLS - all communications will be insecure
INFO[2016-12-01T11:30:25-08:00] Validating supplied configuration
INFO[2016-12-01T11:30:25-08:00] Configuring static IP for additional networks using port group "dvPortGroup-ext"
INFO[2016-12-01T11:30:25-08:00] vDS configuration OK on "dvPortGroup-bridge"
INFO[2016-12-01T11:30:25-08:00] Firewall status: DISABLED on "/RegionA01/host/RegionA01-COMP01/esx-01a.corp.local"
INFO[2016-12-01T11:30:25-08:00] Firewall status: DISABLED on "/RegionA01/host/RegionA01-COMP01/esx-02a.corp.local"
WARN[2016-12-01T11:30:25-08:00] Firewall configuration will be incorrect if firewall is reenabled on hosts:
WARN[2016-12-01T11:30:25-08:00]         "/RegionA01/host/RegionA01-COMP01/esx-01a.corp.local"
WARN[2016-12-01T11:30:25-08:00]         "/RegionA01/host/RegionA01-COMP01/esx-02a.corp.local"
INFO[2016-12-01T11:30:25-08:00] Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
INFO[2016-12-01T11:30:25-08:00] License check OK on hosts:
INFO[2016-12-01T11:30:25-08:00]   "/RegionA01/host/RegionA01-COMP01/esx-01a.corp.local"
INFO[2016-12-01T11:30:25-08:00]   "/RegionA01/host/RegionA01-COMP01/esx-02a.corp.local"
INFO[2016-12-01T11:30:25-08:00] DRS check OK on:
INFO[2016-12-01T11:30:25-08:00]   "/RegionA01/host/RegionA01-COMP01/Resources"
INFO[2016-12-01T11:30:25-08:00]
INFO[2016-12-01T11:30:25-08:00] Creating virtual app "vch4"
INFO[2016-12-01T11:30:25-08:00] Creating appliance on target
INFO[2016-12-01T11:30:25-08:00] Network role "client" is sharing NIC with "public"
INFO[2016-12-01T11:30:25-08:00] Network role "management" is sharing NIC with "public"
INFO[2016-12-01T11:30:27-08:00] Uploading images for container
INFO[2016-12-01T11:30:27-08:00]         "bootstrap.iso"
INFO[2016-12-01T11:30:27-08:00]         "appliance.iso"
INFO[2016-12-01T11:30:43-08:00] Waiting for IP information
INFO[2016-12-01T11:31:11-08:00] Waiting for major appliance components to launch
INFO[2016-12-01T11:31:11-08:00] Checking VCH connectivity with vSphere target
INFO[2016-12-01T11:31:11-08:00] vSphere API Test: https://vcsa-01a.corp.local vSphere API target responds as expected
INFO[2016-12-01T11:31:17-08:00] Initialization of appliance successful
INFO[2016-12-01T11:31:17-08:00]
INFO[2016-12-01T11:31:17-08:00] VCH Admin Portal:
INFO[2016-12-01T11:31:17-08:00] https://192.168.110.72:2378
INFO[2016-12-01T11:31:17-08:00]
INFO[2016-12-01T11:31:17-08:00] Published ports can be reached at:
INFO[2016-12-01T11:31:17-08:00] 192.168.110.72
INFO[2016-12-01T11:31:17-08:00]
INFO[2016-12-01T11:31:17-08:00] Docker environment variables:
INFO[2016-12-01T11:31:17-08:00] DOCKER_HOST=192.168.110.72:2375
INFO[2016-12-01T11:31:17-08:00]
INFO[2016-12-01T11:31:17-08:00] Environment saved in vch4/vch4.env
INFO[2016-12-01T11:31:17-08:00]
INFO[2016-12-01T11:31:17-08:00] Connect to docker:
INFO[2016-12-01T11:31:17-08:00] docker -H 192.168.110.72:2375 info
INFO[2016-12-01T11:31:17-08:00] Installer completed successfully

**Comment by mobla** [comment]
@hickeng: Not sure if vic-init is failing due to incorrect route or DNS. For @gonghuahill, when DNS is set correctly, seem to have worked. But in my case, I have the DNS set correctly. As @mlh78750 mentioned, I need to add route to VC's (corevcqe-pod.eng.vmware.com) network..

Attached the tether debug log
[tether.debug.tar.gz](https://github.com/vmware/vic/files/625648/tether.debug.tar.gz)
Snippet
```
all stderr redirected to debug logall stdout redirected to debug logtime="2016-12-01T02:20:15Z" level=info msg="Registering tether extension Toolbox" 
time="2016-12-01T02:20:15Z" level=info msg="Registering tether extension logrotate" 
time="2016-12-01T02:20:15Z" level=info msg="opening /var/log/vic/init.log for debug log" 
time="2016-12-01T02:20:15Z" level=info msg="Started reaping child processes" 
time="2016-12-01T02:20:15Z" level=info msg="Launching vch-init pprof server on 127.0.0.1:6060" 
time="2016-12-01T02:20:15Z" level=info msg="Starting extension logrotate" 
time="2016-12-01T02:20:15Z" level=info msg="Starting extension Toolbox" 
time="2016-12-01T02:20:15Z" level=info msg="toolbox: waiting for initialization" 
time="2016-12-01T02:20:15Z" level=info msg="dispatching power op \"OS_PowerOn\"" 
time="2016-12-01T02:20:15Z" level=info msg="toolbox: service is ready (power on event received)" 
time="2016-12-01T02:20:15Z" level=info msg="Loading main configuration" 
time="2016-12-01T02:20:15Z" level=info msg="setting ip address 10.172.64.7/26 for link eth1" 
time="2016-12-01T02:20:15Z" level=info msg="Added nameservers: [10.172.40.1 10.172.40.2]" 
time="2016-12-01T02:20:15Z" level=info msg="successfully applied config for network management" 
time="2016-12-01T02:20:16Z" level=info msg="Renaming link eth0 to public" 
time="2016-12-01T02:20:16Z" level=info msg="setting ip address 10.172.64.70/26 for link public" 
time="2016-12-01T02:20:16Z" level=info msg="Setting default gateway to 10.172.64.126" 
time="2016-12-01T02:20:16Z" level=info msg="updated default route to public interface, gateway: 10.172.64.126" 
time="2016-12-01T02:20:16Z" level=info msg="Added nameservers: [10.172.40.1 10.172.40.2]" 
time="2016-12-01T02:20:16Z" level=info msg="successfully applied config for network public" 
time="2016-12-01T02:20:16Z" level=info msg="Renaming link eth2 to bridge" 
time="2016-12-01T02:20:16Z" level=info msg="successfully applied config for network bridge" 
time="2016-12-01T02:20:16Z" level=info msg="Renaming link eth1 to client" 
time="2016-12-01T02:20:16Z" level=info msg="setting ip address 10.172.64.7/26 for link client" 
time="2016-12-01T02:20:16Z" level=warning msg="address 10.172.64.7/26 already set on interface client" 
time="2016-12-01T02:20:16Z" level=info msg="Added nameservers: [10.172.40.1 10.172.40.2]" 
time="2016-12-01T02:20:16Z" level=info msg="successfully applied config for network client" 
time="2016-12-01T02:20:16Z" level=info msg="opening /var/log/vic/vicadmin.log for session logging" 
time="2016-12-01T02:20:16Z" level=info msg="opening /var/log/vic/docker-personality.log for session logging" 
time="2016-12-01T02:20:16Z" level=info msg="opening /var/log/vic/port-layer.log for session logging" 
time="2016-12-01T02:20:16Z" level=info msg="Launching process for session docker-personality" 
time="2016-12-01T02:20:16Z" level=info msg="Launching process for session port-layer" 
time="2016-12-01T02:20:16Z" level=info msg="Launching process for session vicadmin" 
time="2016-12-01T02:20:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2016-12-01T02:21:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2016-12-01T02:21:24Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2016-12-01T02:21:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2016-12-01T02:22:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2016-12-01T02:22:48Z" level=warning msg="Wait returned waitid: no child processes" 
time="2016-12-01T02:22:52Z" level=info msg="Reload triggered" 
time="2016-12-01T02:22:52Z" level=info msg="Triggered reload" 
time="2016-12-01T02:22:52Z" level=info msg="Loading main configuration" 
time="2016-12-01T02:22:52Z" level=info msg="skipping applying config for network bridge as it has been applied already" 
time="2016-12-01T02:22:52Z" level=info msg="skipping applying config for network client as it has been applied already" 
time="2016-12-01T02:22:52Z" level=info msg="skipping applying config for network management as it has been applied already" 
time="2016-12-01T02:22:52Z" level=info msg="skipping applying config for network public as it has been applied already" 
time="2016-12-01T02:22:52Z" level=info msg="opening /var/log/vic/docker-personality.log for session logging" 
time="2016-12-01T02:22:52Z" level=info msg="opening /var/log/vic/port-layer.log for session logging" 
time="2016-12-01T02:22:52Z" level=info msg="opening /var/log/vic/vicadmin.log for session logging" 
time="2016-12-01T02:22:53Z" level=warning msg="Re-launching process for session port-layer (count: 1)" 
time="2016-12-01T02:25:23Z" level=warning msg="Wait returned waitid: no child processes" 
time="2016-12-01T02:25:26Z" level=info msg="Reload triggered" 
time="2016-12-01T02:25:26Z" level=info msg="Triggered reload" 
time="2016-12-01T02:25:26Z" level=info msg="Loading main configuration" 
time="2016-12-01T02:25:26Z" level=info msg="skipping applying config for network client as it has been applied already" 
time="2016-12-01T02:25:26Z" level=info msg="skipping applying config for network management as it has been applied already" 
time="2016-12-01T02:25:26Z" level=info msg="skipping applying config for network public as it has been applied already" 
time="2016-12-01T02:25:26Z" level=info msg="skipping applying config for network bridge as it has been applied already" 
time="2016-12-01T02:25:27Z" level=info msg="opening /var/log/vic/docker-personality.log for session logging" 
time="2016-12-01T02:25:27Z" level=info msg="opening /var/log/vic/port-layer.log for session logging" 
time="2016-12-01T02:25:27Z" level=info msg="opening /var/log/vic/vicadmin.log for session logging" 
time="2016-12-01T02:25:27Z" level=warning msg="Re-launching process for session port-layer (count: 2)" 
time="2016-12-01T02:27:57Z" level=warning msg="Wait returned waitid: no child processes" 
time="2016-12-01T02:28:01Z" level=info msg="Reload triggered" 
time="2016-12-01T02:28:01Z" level=info msg="Triggered reload" 
time="2016-12-01T02:28:01Z" level=info msg="Loading main configuration"
.....
```

**Comment by mlh78750** [comment]
I want someone to look at this right away. I just saw this with @mobla on a ESX only install with all static IP and a correct routing configuration.

**Comment by vburenin** [comment]
just FYI: snippet provided by @mobla is compressed by rar, not gz.

**Comment by vburenin** [comment]
Interesting part of the log.
```
time="2016-12-01T02:20:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:24Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:22:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:20:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:24Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:22:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"time="2016-12-01T02:20:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:24Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:21:44Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2016-12-01T02:22:04Z" level=error msg="op=186.2: Query error: Get https://corevcqe-pod.eng.vmware.com/sdk/vimService.wsdl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by vburenin** [comment]
gzipped version.
[tether.debug.gz](https://github.com/vmware/vic/files/628133/tether.debug.gz)

**Comment by mlh78750** [comment]
Looks like this VIX error only occurs when DNS is not available for the VCH.

**Comment by hmahmood** [comment]
Do we know why the port layer is existing? Is it because of the vix error?

**Comment by hickeng** [comment]
@hmahmood I would guess that it's exiting because it cannot connect to vsphere, but without the logs we cannot tell.

**Comment by mlh78750** [comment]
@mobla when you get a chance, can you recreate this and grab the logs from the VCH as well please.

**Comment by mobla** [comment]
attached the logs for VIX error from VCH deployed on ESXi host.
[vch-esx-logs.tar.gz](https://github.com/vmware/vic/files/628591/vch-esx-logs.tar.gz)

**Comment by MasashiTeruya** [comment]
In my case solved by putting FQDN in vic-machine-linux --target option.

**Comment by hmahmood** [comment]
@mobla I looked through the logs; there are a couple of big jumps in timestamps, but I am not sure what they are about. It doesn't seem like they have anything to do with VIC though.

**Comment by tigerhawk6** [comment]
I'm getting the same error on vic_0.8.0-7315-c8ac999 if I use DHCP for public network.  It seems to deploy fine as I can still check its info via docker -H x.x.x.x info.  If I assign a static IP address I do not get this error.  Using DHCP works fine in 0.7.0 though.

**Comment by karthik-narayan** [comment]
We have a customer who has hit this issue and we need a workaround. 

Logs have been uploaded to the internal Google drive and can be found at https://drive.google.com/drive/u/1/folders/0B_qdwU92L7BiSlViTVVJRjNBbGM

**Comment by hmahmood** [comment]
@karthik-narayan do you have the vic-machine command line they ran? Also the log bundle from the appliance would help. Have they tried setting the dns server using the --dns-server option to the vic-machine create as suggested by some users above?

**Comment by mlh78750** [comment]
Generally, this error shows when the VCH management network cannot resolve the hostname for the API target (the VC or ESX if host only install) or it cannot reach the API over the network. 

If the install command line is using a hostname for the target, then that hostname needs to be resolved on the management network configured for the VCH. If DNS is not available, or the DNS server doesn't have an answer you will get this error. Also, if there is a firewall or connectivity problem blocking access to the API endpoint from the management network on the VCH, then you will get this error as well.

Recommend we improve the error message as part of closing this issue.

**Comment by karthik-narayan** [comment]
@hmahmood Forwarding the details via email

**Comment by hmahmood** [comment]
For reference: 
```
3016 – VIX_E_TOOLS_NOT_RUNNING
Guest tools is not running.
```
Not sure what this has to do with network resolution. Maybe we are blocking RPC request handling somehow with the reachability tests?

**Comment by karthik-narayan** [comment]
I wanted to provide an update on the customer issue. The problem was traced to a physical network issue. Support worked with the customer to identify the issue and has them successfully setup. They are also in the process of filing issues for doc updates.

**Comment by stuclem** [comment]
@karthik-narayan please ask them to include @stuclem and the label `kind/user-docs` for the doc update issues, so that I don't miss them. Thanks!

**Comment by cormachogan** [comment]
I just noticed something as well - don't know if it helps.

I initially included the --dns-server option in the command line, although I was picking up a DHCP address. The VCH create failed as described here.

When I removed the --dns-server option from the command line, it succeeded.

**Comment by hickeng** [comment]
The is the result of the VIC check taking longer than the guest tools ping interval - this results in an incorrect report that guest tools is not running.
We also saw this symptom while diagnosing #4961 which, like @cormachogan, was a DNS issue resulting in being unable to resolve VC.

There are two parts to addressing this:
- [ ] implement the async portion of guest operations
- [ ] ensure that actual, useful, user actionable error messages result

This may require #4961 be fixed to allow for easy testing of the name resolution failure.
