### ISSUE TITLE
Document support for Docker API version > 1.23

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3419]
Per https://github.com/vmware/vic/issues/3415.

**Comment by stuclem** [comment]
Might come sooner, but must be in 1.0.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/3756 adds support for Docker API 1.25 / Docker 1.13. This PR doesn't have a milestone, but I assume that it's in sprint 1.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3415 is in Sprint 2.

**Comment by stuclem** [comment]
#3145 is merged in PR https://github.com/vmware/vic/pull/3756.

**Comment by stuclem** [comment]
Updated [Supported Docker Commands](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md) with the following statement:
----
vSphere Integrated Containers Engine 0.9 supports Docker 1.13. The supported version of the Docker API is 1.25. 
---
Changes are in https://github.com/vmware/vic/compare/master...stuclem:master#diff-3c44a5edaaa309c520ea32678c2fef4a. 


Also updated the troubleshooting topics in https://github.com/vmware/vic/commit/5509eb9ebdc8f204b789f14e0139e6c2d92674ac. 

@chengwang86 are these these OK? Thanks!

**Comment by rajanashok** [comment]
Verified by @chengwang86 and @rajanashok, closing.
