### ISSUE TITLE
vic-admin can not grab file lock in /var/run/lock/logrotate_run.lock

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3425]
vic-admin runs under account of a not a privileged user (vicadmin), so this user can't grab the lock on the file that is owned by root.

Users can see this error in log files when they try to export the log bundle in vicadmin:

time="2016-12-01T22:33:19Z" level=error msg="Failed to acquire logrotate lock: open /var/run/lock/logrotate_run.lock: permission denied"

**Comment by sgairo** [comment]
related to #3251 , will close and keep original issue

**Comment by anchal-agrawal** [comment]
Closing as dup of #3251

**Comment by vburenin** [comment]
It is not a dup of #3251 
adding vicadmin into sudoers will not solve the problem.
We need a special group to run all out VIC related services so we can manage permissions for that group only.
