### ISSUE TITLE
Move --registry-ca out of extended help

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3429]
At the moment, `--insecure-registry` is in the standard output of `vic-machine-os create --help`, but `--registry-ca` is in `vic-machine-os create --extended-help`. According to @hickeng in https://github.com/vmware/vic/issues/3402#issuecomment-264024089, `--registry-ca` should be documented together with `--insecure-registry` in the standard options. If  `--registry-ca` is likely to be a commonly used option, it should move out of the extended help.

**Comment by hickeng** [comment]
This option is likely to be needed in deployments using harbor.

**Comment by gigawhitlocks** [comment]
I did this while adding `--registry-ca` to `configure`.
