### ISSUE TITLE
Docker ps displays "poweredoff" container on build 7299

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3434]
**VIC version:**

 v0.8.0-rc3-7299-5373289

**Deployment details:**

ci build 7299 running on local ESXi host. 

**Steps to reproduce:**

I cannot reproduce it on my local setup by running the test steps manually.

**Expected behavior:**

In "Test-Cases.Group1-Docker-Commands.1-10-Docker-PS", we started a container running "ls" and expected "docker ps" would not display this container, since it should have exited after "ls".

**Actual behavior:**

"docker ps" displayed the information of the container running "ls", even if we did "docker ps" after "Wait Until VM Powers Off". The power state information was obtained by using govc, the output of which indicated that the VM had been powered off before "docker ps".

**Logs:**
[Test-Cases.Group1-Docker-Commands.1-10-Docker-PS-VCH-7299-7088-container-logs.zip](https://github.com/vmware/vic/files/628096/Test-Cases.Group1-Docker-Commands.1-10-Docker-PS-VCH-7299-7088-container-logs.zip)

Error:
```
Full Name:	Test-Cases.Group1-Docker-Commands.1-10-Docker-PS.Docker ps only running containers
Start / End / Elapsed:	20161202 10:02:31.810 / 20161202 10:03:06.693 / 00:00:34.883
Status:	FAIL (critical)
Message:	Length of '[
u'CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES', 
u'ffad9b735eaa        busybox             "/bin/top"          3 minutes ago       Up 11 seconds                           cocky_franklin', 
u'd95aaea998e4        busybox             "ls"                4 minutes ago       Up 24 seconds                           serene_euclid
']' should be 2 but is 3.
```

From hostd.log
```
2016-12-02T15:59:12.244Z info hostd[5DCC2B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/577fceda-9b1fac4c-110b-0050569ccda1/serene_euclid-d95aaea998e492179b3dd012e55f665cdaa7be72acb5a8165ec7122431621634/serene_euclid-d95aaea998e492179b3dd012e55f665cdaa7be72acb5a8165ec7122431621634.vmx] State Transition (VM_STATE_ON -> VM_STATE_OFF)
2016-12-02T15:59:12.244Z warning hostd[5DCC2B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/577fceda-9b1fac4c-110b-0050569ccda1/serene_euclid-d95aaea998e492179b3dd012e55f665cdaa7be72acb5a8165ec7122431621634/serene_euclid-d95aaea998e492179b3dd012e55f665cdaa7be72acb5a8165ec7122431621634.vmx] Failed to find activation record, event user unknown.
2016-12-02T15:59:12.245Z info hostd[5DCC2B70] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 228400 : serene_euclid-d95aaea998e492179b3dd012e55f665cdaa7be72acb5a8165ec7122431621634 on  vic-esx-05.ci.drone.local in ha-datacenter is powered off
```

In port-layer.log, I was expecting msg like ```Setting container d95aaea998e492179b3dd012e55f665cdaa7be72acb5a8165ec7122431621634 state: Stopped```, but it didn't exist.

**Additional comments**

In the same test, we had another container "f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903" running the same "ls" command. I was able to find the expected log information for port-layer.log:
```
time=2016-12-02T15:59:43.140259876Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).StateChangeHandler:155] handle(9bc7faa30726212822615a4a649a683a) 
time=2016-12-02T15:59:43.140273079Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).StateChangeHandler:155] [13.844µs] handle(9bc7faa30726212822615a4a649a683a) 
time=2016-12-02T15:59:43.140555832Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:223] handle(9bc7faa30726212822615a4a649a683a) 
time=2016-12-02T15:59:43.141172789Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] 49ddbf9356302740eb35cba46d5d1817b1c32a70c792fb0d23266b8defd8ae2d 
time="2016-12-02T15:59:43Z" level=debug msg="ChangeVersion is 2016-12-02T15:59:43.780538Z" 
time="2016-12-02T15:59:43Z" level=debug msg="Found 2 subscribers to vsphere.VMEvent: trusting_volhar-f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 on  vic-esx-05.ci.drone.local in ha-datacenter is powered off" 
time="2016-12-02T15:59:43Z" level=debug msg="Event manager calling back to exec" 
time="2016-12-02T15:59:43Z" level=debug msg="Event manager calling back to registeredVMEvent" 
time=2016-12-02T15:59:43.496223956Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Refresh:272] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time=2016-12-02T15:59:43.496279686Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:98] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time="2016-12-02T15:59:43Z" level=debug msg="get vm properties [config runtime] of vm VirtualMachine:13835" 
time="2016-12-02T15:59:43Z" level=debug msg="properties: [config runtime summary.runtime.connectionState]" 
time=2016-12-02T15:59:43.636387757Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:98] [140.10558ms] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time=2016-12-02T15:59:43.642072871Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Refresh:272] [145.840463ms] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time="2016-12-02T15:59:43Z" level=debug msg="Setting container f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 state: Stopped" 
time="2016-12-02T15:59:43Z" level=debug msg="Container(f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903) closing 0 log followers" 
time="2016-12-02T15:59:43Z" level=debug msg="Container(f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903) state set to Stopped via event activity" 
time="2016-12-02T15:59:43Z" level=debug msg="Found 1 subscribers to events.ContainerEvent: Container f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 PoweredOff" 
time="2016-12-02T15:59:43Z" level=debug msg="Event manager calling back to netCtx(0xc420779d40)" 
time=2016-12-02T15:59:43.642256517Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Refresh:272] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time=2016-12-02T15:59:43.642265660Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:98] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time="2016-12-02T15:59:43Z" level=debug msg="get vm properties [config runtime] of vm VirtualMachine:13835" 
time="2016-12-02T15:59:43Z" level=debug msg="properties: [config runtime summary.runtime.connectionState]" 
time=2016-12-02T15:59:43.691853204Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:98] [49.583697ms] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time=2016-12-02T15:59:43.691869820Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Refresh:272] [49.614651ms] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
time=2016-12-02T15:59:43.692309204Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).UnbindContainer:802] 
time=2016-12-02T15:59:43.692319836Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).container:788] 
time=2016-12-02T15:59:43.692330884Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).container:788] [10.13µs]  
time=2016-12-02T15:59:43.692380585Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).UnbindContainer:802] [71.25µs]  
time=2016-12-02T15:59:43.692687435Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] f254e65e68a0791ce46352b7e0201761a3b2bcccfb51027d2575dab6d7113903 
```

**Comment by cgtexmex** [comment]
I'd venture to say this is a timing issue.  The time it will take for a container to "automatically" power off is dependent on the load on the esxi host -- this variable time will increase on a loaded environment, which happens more frequently in a nested environment like our CI environment.

**Comment by chengwang86** [comment]
@cgtexmex Before we do "ls", the ci checks the vm power state by using govc on the esxi host to make sure the container VM has been powered off. However, the portlayer may not know this power state change when we do "ls"; so I think what you mentioned might make sense.

I also find the containerWait() function in both portlayer and backend. It seems like containerwait can block other processes until the container exits or is stopped. I thought "ls" should have been blocked until the power state change has been appropriately propagated to the portlayer so that "ls" would not display exited containers. Could you please provide some your thoughts on this?

**Comment by cgtexmex** [comment]
containerWait is used to monitor the state of the containerVM via the docker client -- it would / does block the client calls until it's been notified that the containerVM has been powered off.  Even in the case of containerWait we could see a state disparity between the vic components (docker backend / portlayer) and the source of truth vSphere.  

In this specific example the test is dependent on the event level communication between vSphere and the portlayer.  The poweredOff event must fire in vSphere and then be propagated to the portlayer.  In a heavily loaded environment (again much like we see in the nested CI) this event propagation can be delayed / slowed.  When this happens we could see a temporary state divergence between vSphere and vic.

**Comment by chengwang86** [comment]
@cgtexmex Thanks to your explanation. Now I think I understand better what might have happened that resulted in this issue. 

But now I'm having a hard time understanding whether it is (i) a potential race condition that should be avoided so that customers do not see inconsistent data about the power state of the container (output of docker ps vs. the actual power state of the container on esx), or (ii) an expected scenario which the customers have to handle according to their own logic. Any thoughts?

**Comment by cgtexmex** [comment]
I view the state model of vic as eventually consistent and as such this is an expected scenario.  That doesn't mean it might not be confusing to folks, so we should probably have some documentation on the scenario in a general overview or faq.

**Comment by chengwang86** [comment]
I like the term "eventual consistency", although some customers might prefer a stronger consistency model. I will need to discuss with @mhagen-vmware about how/whether to improve the test to avoid such test failure.

**Comment by mhagen-vmware** [comment]
If we accept the concept of eventual consistency, then the test just needs a:
Wait Until Keyword Succeeds  20x  5 seconds  Run  docker ps

**Comment by dougm** [comment]
Seen in build: https://ci.vmware.run/vmware/vic/8911
