### ISSUE TITLE
When reusing static IPs for VCH reinstall, you may need to flush arp cache for gateways.

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#3437]
This is usually hit in a lab environment.

If you install a VCH using a static IP (for example 10.1.1.10) and then delete the VCH and reinstall another using the same static IP be aware that the second VCH will use a new MAC address. This may cause the second VCH to have connectivity problems until the arp cache in the gateway (or any other host communicating with the VCH) expires. You can mitigate this by using different IP addresses for each install (in the case of a lab environment) and/or by flushing the arp cache on your gateway router/firewall for the IP address associated with any of the VCH interfaces.

**Comment by mlh78750** [comment]
@stuclem: Ran into this and thought we should document.

**Comment by mlh78750** [comment]
Adding this as an enhancement to see if the tether or something else can force the endpoint VM to issue an unsolicited ARP reply to hopefully update any stale info.

**Comment by mdubya66** [comment]
Found in End  to end testing.

**Comment by mdubya66** [comment]
@vburenin please triage this further

**Comment by mlh78750** [comment]
First reported in #2932.

Closing as a dup.
