### ISSUE TITLE
Doc review: Obtain a VCH

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3448]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/obtain_vch.md

**Comment by stuclem** [comment]
Unreviewed, so leaving open. @corrieb, @karthik-narayan and @hickeng could you please take a look?

**Comment by karthik-narayan** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks @karthik-narayan. I'm happy with review by PM, so closing.
