### ISSUE TITLE
Implement Docker Search

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3449]
This might become an Epic.

https://docs.docker.com/engine/reference/commandline/search/

Reported in VIC Engine beta.

According to the documentation vic_app_dev.pdf commands like search or stats should work.
However, when I run these commands I get an error
Stats is working but not if I specify a container
 
Error response from daemon: vSphere Integrated Containers does not implement container.ContainerStats
 
Search is not working
 
Error response from daemon: vSphere Integrated Containers does not implement image.SearchRegistryForImages

This issue is to track docker search.

container stats is tracked under https://github.com/vmware/vic/issues/386

**Comment by hickeng** [comment]
@karthik-narayan It's possible we should be considering this as a follow-on to the notary work as restricting the images available (by author of vuln scanning or similar) makes being able to query available images more important.

**Comment by karthik-narayan** [comment]
@hickeng I agree and have added it to the backlog

**Comment by hickeng** [comment]
Estimate is to break down what's required for `docker search` support. The deliverable is either:
* convert this to an epic with estimated subissues in the backlog
* update the estimate for this issue if it doesn't warrant further decomposition.

**Comment by anchal-agrawal** [comment]
Closing as dup of https://github.com/vmware/vic/issues/6221.
