### ISSUE TITLE
vic-machine gateway option should not be required for client and management networks when using static ips

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3453]
Currently, to configure static IPs for client and management networks, a corresponding gateway is required (via the `--<network>-gateway` options). This also forces the user to specify at least one destination for routing through the gateway, even though no gateway should be required if the network in question is L2 adjacent. 

The fix should be to make the gateway options optional for client and management networks only. If gateway is specified, the requirement to specify at least one routing destination should remain.

**Comment by stuclem** [comment]
Created https://github.com/vmware/vic/issues/3501 to track the doc update, so removing kind/user-doc from this one. Thanks for the heads-up, @hmahmood.
