### ISSUE TITLE
Container workflow - pull image, create, start -ai container does not work where as pull, run -it works

### ISSUE THREAD

**Issue by mobla** [vmware/vic#3474]
VIC build# 7315
Harbor: 0.5.0 GA
Steps:
1. On local docker Pull am image (busybox)
2. Tag and push it to Harbor registry
3. Create VCH on ESXi 6.5 (physical) - does not matter
4. Pull the busybox image from Harbor registry
5. Create a container using the image name or image ID
```root@photon-lJUA39j42 [ ~/vic/vic ]# docker -H wdc-vcqa-dhcp61-77.eng.vmware.com:2376 --tlsverify --tlscacert="VCH1ESX/ca.pem" --tlscert="VCH1ESX/cert.pem" --tlskey="VCH1ESX/key.pem" create --name lc1-busybox-create sc-rdops-vm18-dhcp-60-67.eng.vmware.com/project1/busybox:1.0 /bin/sh```
9360e9ff4d226d08579cd4bd655eb06df4f41492c236c33fd0e20df9dd80a50b

--- container creates successfully

```
root@photon-lJUA39j42 [ ~/vic/vic ]# docker -H wdc-vcqa-dhcp61-77.eng.vmware.com:2376 --tlsverify --tlscacert="VCH1ESX/ca.pem" --tlscert="VCH1ESX/cert.pem" --tlskey="VCH1ESX/key.pem" ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@photon-lJUA39j42 [ ~/vic/vic ]# docker -H wdc-vcqa-dhcp61-77.eng.vmware.com:2376 --tlsverify --tlscacert="VCH1ESX/ca.pem" --tlscert="VCH1ESX/cert.pem" --tlskey="VCH1ESX/key.pem" ps -a
CONTAINER ID        IMAGE                                                              COMMAND             CREATED             STATUS                         PORTS               NAMES
9360e9ff4d22        sc-rdops-vm18-dhcp-60-67.eng.vmware.com/project1/busybox:1.0       "/bin/sh"           36 minutes ago      Created                                            lc1-busybox-create
```

6. Start the container with -ai or without -ai option
`root@photon-lJUA39j42 [ ~/vic/vic ]# docker -H wdc-vcqa-dhcp61-77.eng.vmware.com:2376 --tlsverify --tlscacert="VCH1ESX/ca.pem" --tlscert="VCH1ESX/cert.pem" --tlskey="VCH1ESX/key.pem" start 9360e9ff4d22`
9360e9ff4d22

`root@photon-lJUA39j42 [ ~/vic/vic ]# docker -H wdc-vcqa-dhcp61-77.eng.vmware.com:2376 --tlsverify --tlscacert="VCH1ESX/ca.pem" --tlscert="VCH1ESX/cert.pem" --tlskey="VCH1ESX/key.pem" start -ai 9360e9ff4d22`

---- container fails to power on! (busybox does not attach to the terminal)

Whereas  with run -it option, container comes up fine and subsequent start -ai or start, attach works fine 
```
root@photon-lJUA39j42 [ ~/vic/vic ]# docker -H wdc-vcqa-dhcp61-77.eng.vmware.com:2376 --tlsverify --tlscacert="VCH1ESX/ca.pem" --tlscert="VCH1ESX/cert.pem" --tlskey="VCH1ESX/key.pem" run -it --name lc1-bb-run sc-rdops-vm18-dhcp-60-67.eng.vmware.com/project1/busybox:1.0
/ # ls
```

Uploaded the hostd log: 
[hostdlog.tar.gz](https://github.com/vmware/vic/files/640823/hostdlog.tar.gz)

logbundle with container logs: 
[container-logs.tar.gz](https://github.com/vmware/vic/files/640819/container-logs.tar.gz)

**Comment by hmahmood** [comment]
@mobla you are missing `-t` option to create. If you include that, `start -ai` should attach.

**Comment by sflxn** [comment]
I commented on Slack that I think 'sh' is shutting down if there is no terminal.  The tether detects that and starts to shutdown the container infrastructure around it.  I didn't see anything out of the ordinary in the logs.

**Comment by mobla** [comment]
Closing this as a user error. 

Works if the container is created with -t flag and start with -ai which is in par with the behavior standard with docker

Thanks,
Murali
