### ISSUE TITLE
Upon docker run: "No volume store named (default) exists."

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic#3475]
```
#docker -H 10.117.5.129:2375 info|grep Engine
Storage Driver: vSphere Integrated Containers v0.8.0-7315-c8ac999 Backend Engine
vSphere Integrated Containers v0.8.0-7315-c8ac999 Backend Engine: RUNNING

#docker -H 10.117.5.129:2375 run --name mynginx -d 10.117.4.66:80/library/nginx:1.9
docker: Error response from daemon: No volume store named (default) exists.
```

Please let me know if this is due to misconfiguration, I don't see how volume store is required for docker run in the installation guide, maybe I missed some bit?

**Comment by mlh78750** [comment]
@reasonerjt: Does the nginx image you are running require a volume? By default a volume store is not required during install with vic-machine. But if you want to use containers that require volumes, then you will need to specify a volume store with `vic-machine create` so that one is available for the containers to use.

**Comment by reasonerjt** [comment]
@mlh78750 Yes.
```
docker inspect 10.117.4.66/library/nginx:1.9|jq '.[0].Config.Volumes'
{
  "/var/cache/nginx": {}
}
```
And I did some search I think I'm facing the same issue as #2899 
I'll subscribe to #2899 and close this issue.

**Comment by mlh78750** [comment]
@reasonerjt have you tried to install the VCH with a volume store specified? If you do,  I suspect things will work for you. See https://github.com/vmware/vic/blob/42a0624ce67d2c03b1d42ea74cd0cf8a13f78ad9/doc/user_doc/vic_installation/vch_installer_examples.md#specify-volume-stores

**Comment by reasonerjt** [comment]
@mlh78750 
Yes, I did, and it worked.  
However this may confuse the users as they may or may not know if there's a "implicit" volume in the docker image.
esp. when there's parents of the docker image (FROM xxxxx in Dockerfile).
He will have to user docker inspect to figure out himself.  
And he may not know what to do by reading the error message...

**Comment by mlh78750** [comment]
totally agree. And we need to do a better job which, as you pointed out, is being tracked in #2899. I just wanted to make sure you should have a path forward.

**Comment by stuclem** [comment]
Created doc issue https://github.com/vmware/vic/issues/3499 to add this as a troubleshooting topic, as I guess that a lot of people are going to hit it.
