### ISSUE TITLE
What VMware license is required to use this? (slack channel not available)

### ISSUE THREAD

**Issue by bkcsfi** [vmware/vic#3476]
What VMWare  license is needed to use VIC?  Since it uses DRS, I suspect "VMWare Essentials Plus" is not going to work as DRS is not supported under this license.

Can someone confirm?

Thanks

I would ask this question on slack but I cannot login .. I do not have an @vmware email address.

**Comment by mdubya66** [comment]
@bkcsfi Enterprise Plus or greater is required for vCenter to work and to get support. http://www.vmware.com/products/vsphere.html highlights this. It's also mentioned in the FAQ on https://www.vmware.com/products/vsphere/integrated-containers.html

Having a VMware email is not required for code.vmware.com but figuring that out is not intuitive. Go here to request a sign in. https://code.vmware.com/slack/

**Comment by bkcsfi** [comment]
Thanks for the info, sorry I didn't  arrive at VIC via vmware.com website but rather came pretty much straight to github from carmac's blog.

I think docker-volume-vsphere  will meet my needs now that it has persistent storage option.
