### ISSUE TITLE
Open session with container in DRS cluster blocks host maintenance mode

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#3492]
So I know we're aware of this limitation in the team, but I wonder whether we've doing enough to document or deal with the potential fallout from this limitation.

It's one thing to say that an open session inhibits intentional vMotion. In that scenario, it fails immediately, you get a nice message from vSphere saying you have an open serial port and you know that it's *this* VM you can't vMotion at this time.

However, in the case where a vSphere admin wants to put a host into maintenance mode, a single containerVM with an open session can block it indefinitely with no message and there's no way to tell which containerVM is responsible. If the user exits the session, the live migration completes and the host enters maintenance mode.

This is pretty ugly behavior, since a user is effectively able to block the day-to-day operations of the admin. This is not something you could argue a user could do in a non-VIC scenario, since they typically won't have access to configure VMs.

In addition, there's the bug Caglar found about file-backed serial ports not being re-connected after vMotion #3243 which means that logs will simply stop functioning.

**Comment by corrieb** [comment]
We can discuss how we want to mitigate this, but I think at the very least, we need to clearly document this limitation. It may be a deal breaker for some vSphere Admins. 

We may want to say that vMotion support is experimental for 0.8 for this reason and #3243. I think this is acceptable for a 0.8 version. We don't want GSS getting hit with this issue.

I think this increases the priority of moving away from the serial ports. It's not possible for us to notify the Admin of which VM is preventing maintenance mode. We should investigate whether its feasible for us to terminate open sessions if we detect impending vMotion. That's not nice behavior for the users, but it's less bad than what we have right now.

**Comment by corrieb** [comment]
@stuclem note the doc impact here

**Comment by stuclem** [comment]
@corrieb it looks to me like this is more than just a release note issue. Probably needs to be called out in https://vmware.github.io/vic-product/assets/files/html/0.8/vic_admin/interop.html too. 

Flagging this one as kind/note for the release notes, and will create a separate issue for the user doc.

**Comment by stuclem** [comment]
Unless of course this is likely to get fixed in 0.9, in which case maybe a release note is enough.
