### ISSUE TITLE
vicadmin leaks sessions if cookies are disabled in browser

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#3495]
If you attempt to log in to vicadmin with cookies disabled, it fails to redirect, but at the back-end it appears to open 10+ vSphere sessions.

`
vagrant@ubuntu-1604-vmware:~$ govc session.ls | grep vic-admin | wc -l
56
`
reload the page
`
vagrant@ubuntu-1604-vmware:~$ govc session.ls | grep vic-admin | wc -l
67
`

**Comment by gigawhitlocks** [comment]
@corrieb fwiw I was able to replicate this issue w/ a successfully authenticated session (only through the browser) & cookies disabled on the client, but a failed authentication generates no sessions (as I originally thought).

Seems to be related to a redirect loop that occurs when a user POSTs valid login data but cannot store the resulting cookie (and then the browser tries again.. and again.. and again..)

Addressing this issue now.

**Comment by corrieb** [comment]
Thanks @gigawhitlocks. Yea the fact that it only occurs on successful auth makes this far less significant than it would otherwise be.

**Comment by gigawhitlocks** [comment]
This is only open because we still want to do testing. Marking it medium priority.

**Comment by mhagen-vmware** [comment]
@gigawhitlocks Based on your last comment, closing this as we will track the testing requirement in #3520
