### ISSUE TITLE
Portgroup is not found even though it is previously created as DVS Portgroup

### ISSUE THREAD

**Issue by mchenetz** [vmware/vic#3498]
**VIC version:**
v0.8.0-7315-c8ac999

x.y.z / master / commit ID

**Deployment details:**
not deployed
What was the vic-machine create command used to deploy the VCH?
vic-machine-windows.exe create --image-store "hx-dstore-02" --bridge-network "vic-bridge" --target "https://mchenetz:Password@10.28.45.30/dc-lab" --compute-resource "cluster-lab-01/Resources/VCH" --no-tlsverify --thumbprint "28:BF:8E:11:41:4C:B8:90:2A:B3:B5:A0:5C:D1:74:2C:3C:68:81:F0" --debug=1
**Steps to reproduce:**
run above command
**Actual behavior:**
cannot validate
**Expected behavior:**

**Logs:**

(
time=2016-12-13T16:35:57.361843100-05:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:133] [993µs]
time=2016-12-13T16:35:57.361843100-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188]
time=2016-12-13T16:35:57.362844900-05:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188] [1.0018ms]
time=2016-12-13T16:35:57.362844900-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188]
time=2016-12-13T16:35:57.363847300-05:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188] [1.0024ms]
time=2016-12-13T16:35:57.363847300-05:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:162] [2.9972ms]
time=2016-12-13T16:35:57.364849800-05:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).CheckImagesFiles:77] [16.0412ms]
time=2016-12-13T16:35:57.364849800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:86]
[37mDEBU[0m[2016-12-13T16:35:58-05:00] Session Environment Info:                     [37mAPI Type[0m=VirtualCenter [37mAPI Version[0m=6.0 [37mBuild[0m=3634794 [37mName[0m=VMware vCenter Server [37mOS Type[0m=linux-x64 [37mProduct ID[0m=vpx [37mUUID[0m=6140efa4-3ca7-4879-80c6-37a095bf9219 [37mVendor[0m=VMware, Inc. [37mVersion[0m=6.0.0
[37mDEBU[0m[2016-12-13T16:35:58-05:00] vSphere resource cache populating...
[37mDEBU[0m[2016-12-13T16:35:58-05:00] Cached dc: /dc-lab
[37mDEBU[0m[2016-12-13T16:35:58-05:00] Error count populating vSphere cache: (3)
time=2016-12-13T16:35:58.580030300-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:86] [1.2151805s]
time=2016-12-13T16:35:58.588051300-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).Validate:241]
[34mINFO[0m[2016-12-13T16:35:58-05:00] Validating supplied configuration
time=2016-12-13T16:35:58.592059400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).basics:279]
[37mDEBU[0m[2016-12-13T16:35:58-05:00] Setting scratch image size to 8000000 KB in VCHConfig
time=2016-12-13T16:35:58.595068700-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).basics:279] [3.0093ms]
time=2016-12-13T16:35:58.601077800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).target:323]
time=2016-12-13T16:35:58.603139300-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC:330]
time=2016-12-13T16:35:58.604087400-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC:330] [948.1µs]
time=2016-12-13T16:35:58.605092500-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).target:323] [4.0147ms]
time=2016-12-13T16:35:59.267834900-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).compute:37]
time=2016-12-13T16:35:59.268857400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper:79] cluster-lab-01/Resources/VCH
time=2016-12-13T16:35:59.271865600-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).computePathToInventoryPath:584] cluster-lab-01/Resources/VCH
time=2016-12-13T16:35:59.271865600-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).computePathToInventoryPath:584] [0s] cluster-lab-01/Resources/VCH
[37mDEBU[0m[2016-12-13T16:35:59-05:00] Converted original path "cluster-lab-01/Resources/VCH" to "/dc-lab/host/cluster-lab-01/Resources/Resources/VCH"
[37mDEBU[0m[2016-12-13T16:35:59-05:00] Selected compute resource "/dc-lab/host/cluster-lab-01/Resources/VCH"
time=2016-12-13T16:35:59.412725100-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper:79] [143.8677ms] cluster-lab-01/Resources/VCH
time=2016-12-13T16:35:59.419710400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).inventoryPathToCluster:653] /dc-lab/host/cluster-lab-01/Resources/VCH
time=2016-12-13T16:35:59.420716900-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).inventoryPathToCluster:653] [1.0065ms] /dc-lab/host/cluster-lab-01/Resources/VCH
time=2016-12-13T16:35:59.551305100-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).compute:37] [283.4702ms]
time=2016-12-13T16:35:59.551305100-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).storage:35]
time=2016-12-13T16:35:59.556581500-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).DatastoreHelper:71] hx-dstore-02
time=2016-12-13T16:35:59.632232900-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).DatastoreHelper:71] [75.6514ms] hx-dstore-02
time=2016-12-13T16:35:59.632232900-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).storage:35] [80.9278ms]
time=2016-12-13T16:35:59.637751800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).network:190]
time=2016-12-13T16:35:59.639756800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).portGroupConfig:89]
time=2016-12-13T16:35:59.641296800-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).portGroupConfig:89] [1.54ms]
time=2016-12-13T16:35:59.643266400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).checkPortGroups:116]
time=2016-12-13T16:35:59.644805300-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).checkPortGroups:116] [1.5389ms]
time=2016-12-13T16:35:59.646775300-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).configureSharedPortGroups:167]
time=2016-12-13T16:35:59.653799600-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).configureSharedPortGroups:167] [7.0243ms]
time=2016-12-13T16:35:59.654803200-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getEndpoint:40]
time=2016-12-13T16:35:59.656838800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper:458] VM Network
time=2016-12-13T16:35:59.657839400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] VM Network
[37mDEBU[0m[2016-12-13T16:35:59-05:00] no such network "VM Network"
time=2016-12-13T16:35:59.742619200-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] [84.7798ms] VM Network
time=2016-12-13T16:35:59.742619200-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper:458] [85.7804ms] VM Network
time=2016-12-13T16:35:59.743622800-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getEndpoint:40] [88.8196ms]
time=2016-12-13T16:35:59.744122400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] --public-network
[34mINFO[0m[2016-12-13T16:35:59-05:00] Suggesting valid networks for --public-network
[34mINFO[0m[2016-12-13T16:35:59-05:00] Suggested values for --public-network:
[34mINFO[0m[2016-12-13T16:35:59-05:00]   "none"
[34mINFO[0m[2016-12-13T16:35:59-05:00]   "vmservice-vshield-pg"
time=2016-12-13T16:35:59.823241000-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] [79.1186ms] --public-network
time=2016-12-13T16:35:59.825278800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getEndpoint:40]
time=2016-12-13T16:35:59.826252100-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper:458] VM Network
time=2016-12-13T16:35:59.826252100-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] VM Network
[37mDEBU[0m[2016-12-13T16:35:59-05:00] no such network "VM Network"
time=2016-12-13T16:35:59.899639600-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] [73.3875ms] VM Network
time=2016-12-13T16:35:59.901647100-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper:458] [75.395ms] VM Network
time=2016-12-13T16:35:59.902646300-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getEndpoint:40] [77.3675ms]
time=2016-12-13T16:35:59.903653500-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] --client-network
[34mINFO[0m[2016-12-13T16:35:59-05:00] Suggesting valid networks for --client-network
[34mINFO[0m[2016-12-13T16:35:59-05:00] Suggested values for --client-network:
[34mINFO[0m[2016-12-13T16:35:59-05:00]   "none"
[34mINFO[0m[2016-12-13T16:35:59-05:00]   "vmservice-vshield-pg"
time=2016-12-13T16:35:59.983155800-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] [79.5023ms] --client-network
time=2016-12-13T16:35:59.984128400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getEndpoint:40]
time=2016-12-13T16:35:59.986150500-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper:458] VM Network
time=2016-12-13T16:35:59.988138700-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] VM Network
[37mDEBU[0m[2016-12-13T16:36:00-05:00] no such network "VM Network"
time=2016-12-13T16:36:00.062390800-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] [74.2521ms] VM Network
time=2016-12-13T16:36:00.064395000-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper:458] [78.2445ms] VM Network
time=2016-12-13T16:36:00.066414900-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getEndpoint:40] [82.2865ms]
time=2016-12-13T16:36:00.067403600-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] --management-network
[34mINFO[0m[2016-12-13T16:36:00-05:00] Suggesting valid networks for --management-network
[34mINFO[0m[2016-12-13T16:36:00-05:00] Suggested values for --management-network:
[34mINFO[0m[2016-12-13T16:36:00-05:00]   "none"
[34mINFO[0m[2016-12-13T16:36:00-05:00]   "vmservice-vshield-pg"
time=2016-12-13T16:36:00.149474900-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] [82.0713ms] --management-network
[37mDEBU[0m[2016-12-13T16:36:00-05:00] Network configuration:
time=2016-12-13T16:36:00.151489400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).dpgHelper:497] vic-bridge
time=2016-12-13T16:36:00.151981700-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] vic-bridge
[37mDEBU[0m[2016-12-13T16:36:00-05:00] no such network "vic-bridge"
time=2016-12-13T16:36:00.221210000-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork:440] [69.2283ms] vic-bridge
time=2016-12-13T16:36:00.225188300-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).dpgHelper:497] [73.6989ms] vic-bridge
time=2016-12-13T16:36:00.226188900-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] --bridge-network
[34mINFO[0m[2016-12-13T16:36:00-05:00] Suggesting valid networks for --bridge-network
[34mINFO[0m[2016-12-13T16:36:00-05:00] No valid networks found
time=2016-12-13T16:36:00.301500400-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestNetwork:577] [75.3115ms] --bridge-network
time=2016-12-13T16:36:00.309518800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).checkVDSMembership:530]
time=2016-12-13T16:36:00.426805100-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).checkVDSMembership:530] [117.2863ms]
time=2016-12-13T16:36:00.426805100-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).nicNumbers:421]
time=2016-12-13T16:36:00.431857300-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).nicNumbers:421] [5.0522ms]
time=2016-12-13T16:36:00.433824400-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).network:190] [796.0726ms]
time=2016-12-13T16:36:00.437373000-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall:87]
[37mDEBU[0m[2016-12-13T16:36:00-05:00] Checking firewall with management network IP {<nil> <nil>}
[34mINFO[0m[2016-12-13T16:36:00-05:00] Firewall status: ENABLED on "/dc-lab/host/cluster-lab-01/10.28.45.22"
[37mDEBU[0m[2016-12-13T16:36:00-05:00] filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc04236b200}]
[37mDEBU[0m[2016-12-13T16:36:00-05:00] filtered IPs: [127.0.0.1] networks: [] allIP: false rule: nfsClient
[37mDEBU[0m[2016-12-13T16:36:00-05:00] fw unknown (dhcp) with fw enabled "/dc-lab/host/cluster-lab-01/10.28.45.22"
[33mWARN[0m[2016-12-13T16:36:00-05:00] Firewall configuration on "/dc-lab/host/cluster-lab-01/10.28.45.22" may prevent connection on dst 2377/tcp outbound with allowed IPs: [127.0.0.1]
[34mINFO[0m[2016-12-13T16:36:01-05:00] Firewall status: ENABLED on "/dc-lab/host/cluster-lab-01/10.28.45.23"
[37mDEBU[0m[2016-12-13T16:36:01-05:00] filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc0423d2480}]
[37mDEBU[0m[2016-12-13T16:36:01-05:00] filtered IPs: [127.0.0.1] networks: [] allIP: false rule: nfsClient
[37mDEBU[0m[2016-12-13T16:36:01-05:00] fw unknown (dhcp) with fw enabled "/dc-lab/host/cluster-lab-01/10.28.45.23"
[33mWARN[0m[2016-12-13T16:36:01-05:00] Firewall configuration on "/dc-lab/host/cluster-lab-01/10.28.45.23" may prevent connection on dst 2377/tcp outbound with allowed IPs: [127.0.0.1]
[34mINFO[0m[2016-12-13T16:36:01-05:00] Firewall status: ENABLED on "/dc-lab/host/cluster-lab-01/10.28.45.21"
[37mDEBU[0m[2016-12-13T16:36:01-05:00] filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc0423ab100}]
[37mDEBU[0m[2016-12-13T16:36:01-05:00] filtered IPs: [127.0.0.1] networks: [] allIP: false rule: nfsClient
[37mDEBU[0m[2016-12-13T16:36:01-05:00] fw unknown (dhcp) with fw enabled "/dc-lab/host/cluster-lab-01/10.28.45.21"
[33mWARN[0m[2016-12-13T16:36:01-05:00] Firewall configuration on "/dc-lab/host/cluster-lab-01/10.28.45.21" may prevent connection on dst 2377/tcp outbound with allowed IPs: [127.0.0.1]
[33mWARN[0m[2016-12-13T16:36:01-05:00] Unable to fully verify firewall configuration due to DHCP use on management network
[33mWARN[0m[2016-12-13T16:36:01-05:00] VCH management interface IP assigned by DHCP must be permitted by allowed IP settings
[33mWARN[0m[2016-12-13T16:36:01-05:00] Firewall allowed IP configuration may prevent required connection on hosts:
[33mWARN[0m[2016-12-13T16:36:01-05:00]        "/dc-lab/host/cluster-lab-01/10.28.45.22"
[33mWARN[0m[2016-12-13T16:36:01-05:00]        "/dc-lab/host/cluster-lab-01/10.28.45.23"
[33mWARN[0m[2016-12-13T16:36:01-05:00]        "/dc-lab/host/cluster-lab-01/10.28.45.21"
[34mINFO[0m[2016-12-13T16:36:01-05:00] Firewall must permit dst 2377/tcp outbound to the VCH management interface
time=2016-12-13T16:36:01.387152800-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall:87] [950.2893ms]
[34mINFO[0m[2016-12-13T16:36:01-05:00] License check OK on hosts:
[34mINFO[0m[2016-12-13T16:36:01-05:00]   "/dc-lab/host/cluster-lab-01/10.28.45.22"
[34mINFO[0m[2016-12-13T16:36:01-05:00]   "/dc-lab/host/cluster-lab-01/10.28.45.23"
[34mINFO[0m[2016-12-13T16:36:01-05:00]   "/dc-lab/host/cluster-lab-01/10.28.45.21"
time=2016-12-13T16:36:01.715753800-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckDrs:494]
[34mINFO[0m[2016-12-13T16:36:01-05:00] DRS check OK on:
[34mINFO[0m[2016-12-13T16:36:01-05:00]   "/dc-lab/host/cluster-lab-01/Resources/VCH"
time=2016-12-13T16:36:01.757155100-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckDrs:494] [41.4013ms]
time=2016-12-13T16:36:01.758157600-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).certificate:413]
time=2016-12-13T16:36:01.759661800-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).certificate:413] [1.5042ms]
time=2016-12-13T16:36:01.760165100-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).certificateAuthorities:432]
[37mDEBU[0m[2016-12-13T16:36:01-05:00] Configuring without client verification due to empty certificate authorities
time=2016-12-13T16:36:01.762168600-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).certificateAuthorities:432] [2.0035ms]
time=2016-12-13T16:36:01.762671900-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).registries:457]
time=2016-12-13T16:36:01.763672500-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).registries:457] [1.0006ms]
time=2016-12-13T16:36:01.764173900-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).compatibility:477]
time=2016-12-13T16:36:01.908740400-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).checkDatastoresAreWriteable:528]
time=2016-12-13T16:36:02.172635700-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).checkDatastoresAreWriteable:528] [263.8953ms]
time=2016-12-13T16:36:02.172635700-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).compatibility:477] [408.4618ms]
time=2016-12-13T16:36:02.177624000-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:216]
[31mERRO[0m[2016-12-13T16:36:02-05:00] --------------------
[31mERRO[0m[2016-12-13T16:36:02-05:00] Error checking network for --public-network: network 'VM Network' not found
[31mERRO[0m[2016-12-13T16:36:02-05:00] Error checking network for --client-network: network 'VM Network' not found
[31mERRO[0m[2016-12-13T16:36:02-05:00] Error checking network for --management-network: network 'VM Network' not found
[31mERRO[0m[2016-12-13T16:36:02-05:00] An existing distributed port group must be specified for bridge network on vCenter: network 'vic-bridge' not found
time=2016-12-13T16:36:02.180619400-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:216] [2.9954ms]
time=2016-12-13T16:36:02.181621900-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).Validate:241] [3.5935706s]
[31mERRO[0m[2016-12-13T16:36:02-05:00] Create cannot continue: configuration validation failed
[31mERRO[0m[2016-12-13T16:36:02-05:00] --------------------
[31mERRO[0m[2016-12-13T16:36:02-05:00] vic-machine-windows.exe failed: validation of configuration failed

C:\Users\mchen\Downloads\vic_0.8.0-7315-c8ac999.tar\vic_0.8.0-7315-c8ac999\vic>
* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

**Comment by mdubya66** [comment]
First reported in #vic-engine slack channel. This was on NSX. @hmahmood for triage

**Comment by hmahmood** [comment]
vic-machine will assume `VM Network` for `--public-network` option if it is not specified. This is what is happening above, and I assume there is no port group named `VM Network` in the target environment. The output above does include suggestions for the port groups to use (vic-machine will discover port groups in the cluster). @mchenetz if you run without the `--debug` option you will see these a little clearly, as the output is not nearly as verbose.

**Comment by hmahmood** [comment]
@mchenetz we do filter out uplink port groups; is `vic-bridge` an uplink port group?

**Comment by hmahmood** [comment]
@mchenetz is this issue still occurring for you?

**Comment by mchenetz** [comment]
hmahmood I haven't tried it since then. I will probably try it again next week.

**Comment by hmahmood** [comment]
@mchenetz have you had a chance to try this out again?

**Comment by hmahmood** [comment]
I am closing this since have not heard back from @mchenetz. @mchenetz please feel free to re-open if you run into this again.
