### ISSUE TITLE
Documentation: create troubleshooting topic for "No volume store named (default) exists"

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3499]
Per https://github.com/vmware/vic/issues/3475.

**Comment by npakrasi** [comment]
Created new troubleshooting topic" https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_installation/ts_volume_store_error.md

**Comment by stuclem** [comment]
My mistake - this belongs in App Dev rather than in Install.

**Comment by stuclem** [comment]
The topic has been moved to App Dev.
