### ISSUE TITLE
Document that open session with container in DRS cluster blocks host maintenance mode

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3500]
Per https://github.com/vmware/vic/issues/3492, which might be satisfactorily covered in release notes if the fix is going to come soon, otherwise it needs to be documented in the core docs as expected behaviour.

**Comment by npakrasi** [comment]
added info to vmotion and maintenance mode sections: https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_admin/interop.md

**Comment by caglar10ur** [comment]
https://github.com/vmware/vic/commit/63fd97ed5864bfa78a2dad1f7c203a2c65566ad1 fixed the issue but we still need to document the fact that putting an ESXi host into the maintenance mode will;

- for the containers with active sessions; power off containers on that host
- for the containers without active sessions and if vmotion is enabled; migrate containers to other hosts

**Comment by stuclem** [comment]
https://github.com/vmware/vic/commit/63fd97ed5864bfa78a2dad1f7c203a2c65566ad1 was part of PR https://github.com/vmware/vic/pull/3558, which merged after 0.8 GA. So,  @caglar10ur 's update in https://github.com/vmware/vic/issues/3500#issuecomment-270504153 is for 0.9.

**Comment by stuclem** [comment]
Need to update the sentences that mention open sessions in the sections on vMotion and  Maintenance Mode in https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/interop.md with @caglar10ur 's comments from 4th Jan.

**Comment by alextopuzov** [comment]
Updates are in: https://github.com/alextopuzov/vic/commit/2fdd05749639468037b24664cd82935e73a19c99
@caglar10ur can you please review the changes?
Thanks.

**Comment by caglar10ur** [comment]
LGTM
