### ISSUE TITLE
Log bundle HOWTO

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#3529]
Stuart/Nandita,

I'm wondering if we can clarify how to collect a log bundle.

This has how to access vicadmin.
https://vmware.github.io/vic-product/assets/files/html/0.8/vic_admin/access_vicadmin.html

And this has what logs are available.
https://vmware.github.io/vic-product/assets/files/html/0.8/vic_admin/log_bundles.html

The `log_bundles` page is under Troubleshooting, but it's not clear how to get to vicadmin from there.

Can we add a link back to `access_vicadmin` from `log_bundles`?  Specifically, I think the following just needs to be a hyperlink.

> vSphere Integrated Containers Engine provides log bundles that you can download from the VCH Admin portal for a virtual container host (VCH).

I think if we make `VCH Admin portal` a link to `access_vicadmin`, that should help.

The, in `access_vicadmin` the line which reads,

> If the VCH is unable to connect to vSphere, logs that require a vSphere connection are disabled, and you see an error message. You can download the log bundle to troubleshoot the error.

can we make the `If...messages.` a _Note_ under the *Log Bundle with container logs* bullet?

Also, "You can download the log bundle to troubleshoot the errror" can be made more general, I think. 

---
To aid in troubleshooting errors, you can download the log bundle by
* Going to the VIC Admin portal (link to access_vicadmin)
* And selecting one of the following links
   -  Log Bundle
       _Contains logs that relate specifically to the VCH that you created_
    - Log Bundle with container logs 
        _Contains the logs for the VCH and also includes the logs regarding the containers that the VCH manages._
        _NOTE_: If the VCH is unable to...

**Comment by stuclem** [comment]
Thanks @fdawg4l - I missed this until now. These are all good observations. We'll get this into a doc refresh for 0.8 (i.e. before 0.9).

**Comment by fdawg4l** [comment]
Awesome.  Thanks Stuart!

**Comment by stuclem** [comment]
Not essential doc this for 0.9. Moving to 1.1.

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#52
