### ISSUE TITLE
vmware.github.io/vic doesn't render some content correctly on mobile

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3534]
The top navigation bar and the Fork button don't render correctly on mobile browsers.

On the mobile site, the nav bar appears as a grey Menu button that's not clearly visible. Also, the Fork button doesn't spread across the entire text:

![mobile-site](https://cloud.githubusercontent.com/assets/4361620/21288609/abce29d0-c44d-11e6-8281-a5e6ac0c44ae.png)

On the desktop site from a mobile browser, the nav bar isn't clearly visible:

![desktop-site](https://cloud.githubusercontent.com/assets/4361620/21288608/abce0bf8-c44d-11e6-8735-8483c4cbe406.png)

Repro'd on Chrome and Firefox on Android 7.1.1 with vmware.github.io/vic and vmware.github.io/vic-product.

**Comment by anchal-agrawal** [comment]
Assigned to @stuclem for triage.

**Comment by stuclem** [comment]
@anchal-agrawal sorry for the delay - only just noticed this one. I just this checked on Safari and Chrome on iOS 10.2.1 and, other than the menu bar at the top being grey on grey, it doesn't suffer from the other problems that you describe on Android.

However, I checked https://vmware.github.io/harbor and https://vmware.github.io/admiral on iOS and they both have the menu bars with a grey background, so something is wrong with my tagging somewhere.  

Thanks for spotting this!

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#82

**Comment by stuclem** [comment]
Closing as migrating all doc issues to vic-product.
