### ISSUE TITLE
Unpredictable combined create&pull behaviour

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#354]
I just saw the following:
```
vagrant@devbox:~/vic$ docker -H 192.168.78.189:2376 --tls --tlscert='tests-cert.pem' --tlskey='tests-key.pem' create busybox /bin/sleep 200
Unable to find image 'busybox:latest' locally
Error response from daemon: exit status 1
vagrant@devbox:~/vic$ docker -H 192.168.78.189:2376 --tls --tlscert='tests-cert.pem' --tlskey='tests-key.pem' create busybox /bin/sleep 200
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
bc744c4ab376: Pull complete
56ed16bd6310: Pull complete
Status: Downloaded newer image for library/busybox:latest
9683c9cbdc07bd6aced1896ef3c833033e1576e4f284f81da8ad426ee5993d5a
vagrant@devbox:~/vic$
```
where I've had the create command work fine previously without a pre-pulled image.
[create-pull.gz](https://github.com/vmware/vic/files/197303/create-pull.gz)

**Comment by mdubya66** [comment]
closing this as no longer reproducible. 

(mwilliamson) dubs:~/Downloads/vic $ docker -H 172.16.127.148:2376 --tls create busybox /bin/sleep 200
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
542c1648628cbe496389685a4491d12bc723f94569a3fe1a9954a055f6f11838
