### ISSUE TITLE
Adding ROBO SKU tests to nightly tests

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic#3545]
User statement: As a part of expanding coverage, we should add support for the vSphere ROBO Advanced SKU to our nightlies. 

Details:  Need to find the build number on build web for this SKU or play with the license if it is just the regular build number - govc can set licensing

Acceptance Criteria:
1. Nightly test runs a build using ROBO SKU each night.

**Comment by hickeng** [comment]
My understanding is that ROBO doesn't include support for DRS or network serial port.
