### ISSUE TITLE
broken link to Deploying vSphere Integrated Container Engine with vSphere Integrated Containers Registry (Harbor)

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3548]
Following the directions in https://vmware.github.io/vic-product/assets/files/html/0.8/vic_app_dev/using_vic_with_harbor.html

Pull the busybox container image from the docker hub to your machine, which you have updated with the CA certificate earlier. See Deploying vSphere Integrated Container Engine with vSphere Integrated Containers Registry (Harbor) for more information on updating certificates.

Results in a 404 for https://vmware.github.io/vic-product/assets/files/html/0.8/vic_installation/deploy_vic_with_harbor.html

**Comment by mhagen-vmware** [comment]
@mdubya66 This looks like a vic-product issue, as both links are /vic-product/ I think we should close this and open an issue in the project?

**Comment by mhagen-vmware** [comment]
Please re-open if you disagree

**Comment by mdubya66** [comment]
The source for this file is in the vic engine code, https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_vic_with_harbor.md

adding user-doc and re-opening.

**Comment by stuclem** [comment]
Link is fixed online: https://vmware.github.io/vic-product/assets/files/html/0.8/vic_app_dev/using_vic_with_harbor.html
