### ISSUE TITLE
MySQL+WordPress containers not restarting correctly.

### ISSUE THREAD

**Issue by omegaharvest** [vmware/vic#3551]
**VIC version:**
0.8

**Deployment details:**
I am deploying a VCH to run two containers, one for MySQL and another for WordPress. The WordPress Container uses the MySQL container as a back end. Initial deployment of the VCH and containers is fine and everything works. However, if I shut down the vApp using 'shutdown' on the vApp itself, then start it up again the WordPress container starts for about a minute, then stops. It looks like it cannot resolve the MySQL container. Examining the logs of the WordPress container gives the following repeatedly:

`Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 19`

`MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known`

What was the vic-machine create command used to deploy the VCH?
`vic-machine-windows.exe create --name muo-vch-001 --target muo-svr-006.muon.com --user "Administrator@VSPHERE.LOCAL" --password VMware1! --compute-resource "muo-hst-004.muon.com" --bridge-network "muo-vch-001-bridge" --management-network "Management-002" --client-network "Management-002" --public-network "Management-002" --public-network-ip 10.0.101.14 --public-network-gateway 10.0.101.2/24 --dns-server 10.0.101.2 --image-store DS001-muo-hst-004 --volume-store DS001-muo-hst-004:default --no-tlsverify --force`

**Steps to reproduce:**
First I create a Busybox container to access the volume's filesystem I'll use for MySQL. This is to remove the 'lost+found' folder which stops MySQL from starting if it is present:

`docker -H 10.0.101.14:2376 --tls run -v vol002:/var/lib/mysql -it busybox`
`rm -r /var/lib/mysql/lost+found`
`exit`

Next I deploy MySQL:

`docker -H 10.0.101.14:2376 --tls run --restart=always --net=bridge --name mysql001 -v vol002:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=passw0rd! -e MYSQL_DATABASE=wordpress -e MYSQL_USER=wordpress_user -e MYSQL_PASSWORD=p@ssw0rd1 -p 3306:3306 -d mysql:latest`

Followed by WordPress:

`docker -H 10.0.101.14:2376 --tls run --restart=always --net=bridge --name wordpress001 -v vol001:/var/www/html/wp-content -e WORDPRESS_DB_HOST=mysql001:3306 -e WORDPRESS_DB_NAME=wordpress -e WORDPRESS_DB_USER=wordpress_user -e WORDPRESS_DB_PASSWORD=p@ssw0rd1 -p 80:80 -d wordpress`

Finally, I go to the IP of the VCH on port 80 and run through the initial setup of WordPress which completes fine and I can edit the site. No SQL issues.

**Actual behavior:**
Everything works fine. I then shutdown the vApp and start it back up again. I only do this from the vApp object. The VCH and MySQL container start back up fine, and checking the logs of MySQL shows it ready to accept connections again. WordPress fails to start with the aforementioned errors. Perhaps the WordPress container is unable to resolve the MySQL container after a restart of the vApp? Obviously MySQL is not dependent on resolving other container hostnames to start up so it runs fine.

**Expected behavior:**
Both containers should start up and behave as they did when they were originally created.

**Logs:**
[container-logs.zip](https://github.com/vmware/vic/files/680054/container-logs.zip)

**Additional details as necessary:**
I also tried deleting and re-creating the WordPress container by running the same command. This however gives the following unexpected error:

`Error response from daemon: Unable to find container "cba076de6c78ff4529f9cbb12ed6bc5f4b088191484bbe4bae39a285e1ff3811" in the cache, unable to get power state`

I have to create many WordPress sites at the University where I work so being able to use this method instead would be awesome. However I need to make sure everything functions correctly after a restart of the vApp first, then test this against our backup system. Any help would be great!

P.S. This is just a dev setup running on my laptop so I've left the passwords in.

**Comment by anchal-agrawal** [comment]
Hi @omegaharvest, the `Error response from daemon: Unable to find container "cba076de6c78ff4529f9cbb12ed6bc5f4b088191484bbe4bae39a285e1ff3811" in the cache, unable to get power state` issue is being tracked in #3465.

**Comment by omegaharvest** [comment]
Thanks, glad to see the later is a known issue. However, I do not think this is causing the WordPress container to fail to load on a vApp restart. This bug only occurs if I remove and recreate the WordPress container completely.

Good to know regardless though as being able to re-create the containers is also crucial for us.

**Comment by chengwang86** [comment]
@omegaharvest Did you "shutdown" the wordpress container from the vsphere web client or did you use "docker stop"?

**Comment by omegaharvest** [comment]
I shutdown the entire vApp object whilst the VCH and 2 containers were running.

**Comment by mdubya66** [comment]
This could be related to #2856 and/or #3257

**Comment by chengwang86** [comment]
This may relate to #3769 and #3137

**Comment by anchal-agrawal** [comment]
Hi @omegaharvest, thanks for your patience.

There are two variables in this scenario, and I will address them both:
* `--restart=always`

   We currently don't support `--restart` policies. I've created a new issue to track that work - #4781.

* vApp restart

    The current behavior on a vApp restart (power off+on) is that the VCH powers on first, followed by containers. However, that needs to be addressed - we should only power on the VCH because powering on containers out-of-band may lead to IP/alias conflicts. This work is tracked in #4779. In the correct behavior, the VCH will be powered on after a vApp restart, and containers can then be started using Docker operations - name/alias resolution in a scenario such as MySQL+Wordpress will work in that case. You can refer to https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/interop.md#performing-operations-on-vchs-and-container-vms-in-vsphere for documentation on what happens to the VCH and containers with direct vSphere operations.

I'm closing this issue, but please feel free to reopen/comment if you have questions. Thanks!
