### ISSUE TITLE
Failed to create VCH with error

### ISSUE THREAD

**Issue by tovinayv** [vmware/vic#3552]
**VIC version:**

vic_0.8.0-7315-c8ac999

**Deployment details:**
Deploying on ESX 6.0

What was the vic-machine create command used to deploy the VCH?
```
vic>vic-machine-windows create --target 10.112.81.203 --user root --password "ca$hc0w" --no-tlsverify --force --name 'vch1'
INFO[2017-01-03T15:43:58+05:30] ### Installing VCH ####
WARN[2017-01-03T15:43:58+05:30] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2017-01-03T15:43:58+05:30] Loaded server certificate 'vch1'\server-cert.pem
WARN[2017-01-03T15:43:58+05:30] Configuring without TLS verify - certificate-based authentication disabled
INFO[2017-01-03T15:43:58+05:30] Validating supplied configuration
INFO[2017-01-03T15:43:58+05:30] Using default datastore: datastore1 (4)
INFO[2017-01-03T15:43:58+05:30] Firewall status: DISABLED on "/ha-datacenter/host/blr-3rd-2-dhcp458.eng.vmware.com/blr-3rd-2-dhcp458.eng.vmware.com"
WARN[2017-01-03T15:43:58+05:30] Firewall configuration will be incorrect if firewall is reenabled on hosts:
WARN[2017-01-03T15:43:58+05:30]         "/ha-datacenter/host/blr-3rd-2-dhcp458.eng.vmware.com/blr-3rd-2-dhcp458.eng.vmware.com"
INFO[2017-01-03T15:43:58+05:30] Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
INFO[2017-01-03T15:43:58+05:30] License check OK
INFO[2017-01-03T15:43:58+05:30] DRS check SKIPPED - target is standalone host
INFO[2017-01-03T15:43:58+05:30]
INFO[2017-01-03T15:43:58+05:30] Creating Resource Pool "'vch1'"
INFO[2017-01-03T15:43:58+05:30] Creating VirtualSwitch
INFO[2017-01-03T15:43:58+05:30] Creating Portgroup
INFO[2017-01-03T15:43:58+05:30] Creating appliance on target
INFO[2017-01-03T15:43:58+05:30] Network role "management" is sharing NIC with "client"
INFO[2017-01-03T15:43:58+05:30] Network role "public" is sharing NIC with "client"
INFO[2017-01-03T15:43:59+05:30] Uploading images for container
INFO[2017-01-03T15:43:59+05:30]         "bootstrap.iso"
INFO[2017-01-03T15:43:59+05:30]         "appliance.iso"
INFO[2017-01-03T15:44:03+05:30] Waiting for IP information
INFO[2017-01-03T15:44:18+05:30] Waiting for major appliance components to launch
INFO[2017-01-03T15:44:18+05:30] Checking VCH connectivity with vSphere target
INFO[2017-01-03T15:44:18+05:30] vSphere API Test: https://10.112.81.203 vSphere API target responds as expected
INFO[2017-01-03T15:46:58+05:30] Collecting ha-host hostd.log
ERRO[2017-01-03T15:46:58+05:30] Failed to collect ha-host hostd.log: Post https://10.112.81.203/sdk: net/http: request canceled while waiting for connection
WARN[2017-01-03T15:46:58+05:30] No log data for ha-host hostd.log
ERRO[2017-01-03T15:46:58+05:30] --------------------
ERRO[2017-01-03T15:46:58+05:30] vic-machine-windows failed: Create timed out: if slow connection, increase timeout with --timeout
```
**Steps to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Logs:**

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

**Comment by tovinayv** [comment]
Attaching logs
[logs.zip](https://github.com/vmware/vic/files/682081/logs.zip)
[vicadmin.log.txt](https://github.com/vmware/vic/files/682083/vicadmin.log.txt)
[docker-personality.log.txt](https://github.com/vmware/vic/files/682085/docker-personality.log.txt)
[init.log.txt](https://github.com/vmware/vic/files/682086/init.log.txt)
[port-layer.log.txt](https://github.com/vmware/vic/files/682084/port-layer.log.txt)
[container-logs.zip](https://github.com/vmware/vic/files/682082/container-logs.zip)

**Comment by tovinayv** [comment]
I tried with increasing timeout with 60 min.. But same result..

**Comment by chengwang86** [comment]
@tovinayv From the port layer log, I find the following error msg:
```
time="2017-01-03T10:49:30Z" level=fatal msg="could not initialize port layer: Ambiguous datastore path format encountered from input: [david1] 'vch1'_1."
```
By default, "datastore1" is used if no other datastore path is specified in the "vic-machine create" cmd. 
```
INFO[2017-01-03T15:43:58+05:30] Validating supplied configuration
INFO[2017-01-03T15:43:58+05:30] Using default datastore: datastore1 (4)
INFO[2017-01-03T15:43:58+05:30] Firewall status: DISABLED on "/ha-datacenter/host/blr-3rd-2-dhcp458.eng.vmware.com/blr-3rd-2-dhcp458.eng.vmware.com"
```
Could you please verify if you have "datastore1"?

**Comment by vburenin** [comment]
I think we need to return any error that is significant from the portlayer to a vic-machine to be displayed for the user. Since we have such direct communication channel, it should not be problematic.

**Comment by tovinayv** [comment]
Attaching new set of logs where datastore1 is present.. With same issue..
[vicadmin.log.txt](https://github.com/vmware/vic/files/683930/vicadmin.log.txt)
[container-logs.zip](https://github.com/vmware/vic/files/683931/container-logs.zip)
[docker-personality.log.txt](https://github.com/vmware/vic/files/683932/docker-personality.log.txt)
[init.log.txt](https://github.com/vmware/vic/files/683934/init.log.txt)
[logs.zip](https://github.com/vmware/vic/files/683933/logs.zip)
[port-layer.log.txt](https://github.com/vmware/vic/files/683935/port-layer.log.txt)

I think issue is when we specify container host name with --name option
vic>vic-machine-windows create --target 10.112.81.203 --user root --password "ca$hc0w" --no-tlsverify --force --name 'vch1'

Without specifying --name, the vch creation successfull with default name 'virtual-container-host'. 

Do we need to mandatorily override datastore path if we are specifying --name for vch?

**Comment by hickeng** [comment]
@tovinayv It's quite possible that it's the name string that's the issue. If using cmd.exe as the shell then `'` are not stripped. Simply omitting the quotes should eliminate this error (it's normally seen with the password argument when copying from a linux command line).

@andrewtchin We should add additional input sanitization/checking for unsupported characters in the name as that's getting used for datastore paths.
