### ISSUE TITLE
Container VM Tools doesn't report IP correctly, breaking NSX DFW functionality

### ISSUE THREAD

**Issue by yfauser** [vmware/vic#3553]
**VIC version:**

Master, commit ce9e90cfc5299a9560311024198be7f2404b50a3

**Deployment details:**

```shell
export VCHOST='administrator@vsphere.local':'secret'@myvc.local
export VCTHUMB=<thumbprint>
export VCCLUSTER=management/Resources
export IMSTORE=NFS-Filer
export NSXNET=vxw-dvs-23-virtualwire-237-sid-5000-test_ls
export PNET=vlan40
export VCHIP=172.19.209.57/27
export DEFGW=172.19.209.33
export DNSIP=172.19.209.36
export VCHNAME=vch-tpmlab

export NSXNET2=vxw-dvs-23-virtualwire-250-sid-5005-web1:web
export NSXNET3=vxw-dvs-23-virtualwire-251-sid-5006-db1:db

./vic-machine-linux create --target $VCHOST --thumbprint $VCTHUMB --compute-resource $VCCLUSTER --image-store $IMSTORE --bridge-network $NSXNET --public-network $PNET --public-network-ip $VCHIP --public-network-gateway $DEFGW --management-network $PNET --client-network $PNET --dns-server $DNSIP --name $VCHNAME --container-network $NSXNET2 --container-network $NSXNET3 --timeout 20m
```

**Steps to reproduce:**

1) Configure DHCP and Routing on with NSX on the Networks 2 and 3
2) Deploy the following container at least 2 times

```shell
docker run -d --net=web yfauser/nsx-demo
```

This container has a port-scan app included (https://github.com/yfauser/sample-flask-container)

3) Now configure an NSX security group with a static membership including the NSX logical switch 'web'

4) Configure a NSX DFW rule dropping traffic between Web VMc/Containers using the security group created in 3

5) Connect to one of the Web Server Containers and Use the containers port scan app to scan for open ports in neigbour containers

**Actual behavior:**

The DFW rule does not match the traffic from the Container/VM, the port-scan can see all containers on the same NSX Network

**Expected behavior:**

The DFW rule should match and the port-scan traffic should be dropped

**Logs:**

[container-logs.zip](https://github.com/vmware/vic/files/682659/container-logs.zip)

**Additional details as necessary:**

The issue lies with VM Tools. For the NSX Distributed Firewall to work, it needs a way to retrieve the IP Address of the VM. There are two ways for NSX to get the IP from VC; The first through VM Tools, and the other through 'IP Discovery' - looking for ARP requests or DHCP requests. The second 'snooping' way needs to be enabled explicitly.

The VM Tools option is preferred, especially in the case of VIC, as the containers are usually 'quiet' when they start so the ARP snooping might not get the IP of the VIC Container VM fast enough.

However, NSX-v gets the IPs of the VMs from vCenter through the 'net' Object of Type GuestNicInfo[] in the guest object of the VM.
In the VIC Container/VM case the 'net' Object is Unset. And this causes the issue that NSX-v is not able to read the IPs from the Container/VM, breaking the DFW functionality.

***VIC Container VM as seen in the vCenter Managed Object Browser***

****VIC Container VM (guest):****

|NAME|TYPE|VALUE|
|---|---|---|
|NAME|TYPE|VALUE|
|appHeartbeatStatus|string|"appStatusGray"|
|appState|string|"none"|
|disk|GuestDiskInfo[]|Unset|
|generationInfo|GuestInfoNamespaceGenerationInfo[]|Unset|
|guestFamily|string|Unset|
|guestFullName|string|""|
|guestId|string|Unset|
|guestKernelCrashed|boolean|Unset|
|guestOperationsReady|boolean|true|
|guestState|string|"running"|
|guestStateChangeSupported|boolean|true|
|hostName|string|""|
|interactiveGuestOperationsReady|boolean|false|
|ipAddress|string|"172.24.0.16"|
|ipStack|GuestStackInfo[]|Unset|
|net|**GuestNicInfo[]**|**Unset**|
|screen|GuestScreenInfo|screen|
|toolsRunningStatus|string|"guestToolsRunning"|
|toolsStatus|VirtualMachineToolsStatus|"toolsOk"|
|toolsVersion|string|"2147483647"|
|toolsVersionStatus|string|"guestToolsUnmanaged"|
|toolsVersionStatus2|string|"guestToolsUnmanaged"|

**Comment by caglar10ur** [comment]
I believe we don't fill GuestNicInfo struct right now adding @dougm to confirm

**Comment by dougm** [comment]
Right, we only report ipAddress currently.  I had started looking into this, will see about getting back to it in the upcoming milestone.

**Comment by mhagen-vmware** [comment]
Acceptance criteria:
1. Using a distributed firewall rule in NSX should match traffic and port scan traffic should be dropped.
2. Provide a test for the above behavior.

**Comment by hickeng** [comment]
@dougm did you fix this?

**Comment by dougm** [comment]
We do report the NicInfo now (#3824), but don't think anyone has confirmed that NSX is happy with the data we're including yet.  It should be ok with the 1.1 release, @yfauser please re-open if you still have issues here.
