### ISSUE TITLE
Not friendly authentication error screen

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3564]
# Actual
Entering wrong credentials ended up with this screen on vic-admin page.

![image](https://cloud.githubusercontent.com/assets/4350891/21661826/e1c0e51c-d29b-11e6-8c8a-d9e65d0a7de6.png)

# Expected

User should be returned to a login page.

**Comment by mhagen-vmware** [comment]
User statement: As a user of VIC, if I fail to login to vic-admin I would like to be redirected back to the login page with a clear error message about why.

Details: Change to a redirect and leave the fields filled in, highlight the field that is wrong with red?

Acceptance criteria:
1. Redirect behavior on failed login
2. Test created to verify
