### ISSUE TITLE
CI: Cannot authenticate. This is an outdated version of Coverage and is expired. Please upgrade. 

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#3570]
Uploading file 1 bin/vic_7522.tar.gz to https://api.bintray.com/content/vmware/vic-repo/build/7522/vic_7522.tar.gz
Result: success
[info] Pulling image plugins/drone-coverage:latest
Drone Coverage Plugin built from 06590b3
Parsing coverage file /drone/src/github.com/vmware/vic/.cover/cover.out
Cannot authenticate. This is an outdated version of Coverage and is expired. Please upgrade.

**Comment by anchal-agrawal** [comment]
Closing as resolved per https://ci.vmware.run/vmware/vic/7523.

**Comment by mdubya66** [comment]
Ivan upgraded the container to fix this
