### ISSUE TITLE
VCH does not pick up volumes created by other VCHs when sharing a volume store

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3571]
This was found when confirming that #3046 is no longer around. 

reproduction: 

1. Create two VCHs sharing the same volume store. 

2. Create a volume using each VCH.

3. do `docker volume ls` for both VCHs and note that they do not display the other's volume.

4. attempt to mount the volume from the other VCH, a internal server error on the portlayer will occur saying `file not found` 

When two VCHs share a volume store there is a potential cache inconsistency issue. One possible solution is to listen for volume creation events from the vsphere event queue. 

Additionally, the portlayer error is incorrect. The file does exist in the portlayer, but for some reason we do not detect it.

**Comment by matthewavery** [comment]
<img width="1801" alt="screen shot 2017-01-05 at 1 11 13 pm" src="https://cloud.githubusercontent.com/assets/8620942/21694113/4280806c-d349-11e6-832b-61315b963d52.png">

**Comment by fdawg4l** [comment]
@mathewavery we don't support that use case. We don't support sharing of volume locations.

**Comment by matthewavery** [comment]
This ticket will stay open as an informational ticket.
