### ISSUE TITLE
Multiple-VLAN test for nightly fails during teardown

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#3583]
This is a test issue, nimbus cleanup during the suite tear down needs update.

![image](https://cloud.githubusercontent.com/assets/21340516/21778822/99610540-d66a-11e6-8dd2-fffb6af0b228.png)

**Comment by mhagen-vmware** [comment]
I have some free time, I can do this one.

**Comment by rajanashok** [comment]
I've started on this, have a fix, will send a PR shortly.

**Comment by rajanashok** [comment]
I also noticed this recently. There is vMotion Container test that requires rework during teardown. Currently, we do a kill '*' instead of the specific VM list on this test.

**Comment by mhagen-vmware** [comment]
Good catch:
https://github.com/vmware/vic/issues/3699
