### ISSUE TITLE
VCH installation fails to find datastore if located within a vCenter folder

### ISSUE THREAD

**Issue by wolruf** [vmware/vic#3590]
**VIC version:**

0.8.0GA

**Deployment details:**

vSphere 6.0U2 is used with vCenter 6.0U2 as well.
Storage is using NFS.

**Steps to reproduce:**

Have VM Network, VMKernel in a vCenter folder, see screenshot below.
![screenshot](https://cloud.githubusercontent.com/assets/13536363/21851760/c900d2d8-d810-11e6-9cac-797e0a77b093.png)

**Actual behavior:**

Installation fails

**Expected behavior:**

Ability to specify datastore folder in the installation parameters

**Logs:**

root@template-wheezy64:~/vic# ./vic-machine-linux create --target pcc-10-255-1-53.ovh.com/pcc-10-255-1-53_datacenter2368 --image-store "pcc-005573" --user administrator@vsphere.local --bridge-network container1 --compute-resource Cluster1  --no-tlsverify --timeout 1200s --management-network VMKernel --management-network-ip 172.16.24.101 --management-network-gateway 172.16.24.0/23:172.16.24.2/23
INFO[2017-01-11T12:54:43+01:00] ### Installing VCH ####
INFO[2017-01-11T12:54:43+01:00] vSphere password for administrator@vsphere.local:
WARN[2017-01-11T12:54:52+01:00] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2017-01-11T12:54:52+01:00] Loaded server certificate virtual-container-host/server-cert.pem
WARN[2017-01-11T12:54:52+01:00] Configuring without TLS verify - certificate-based authentication disabled
INFO[2017-01-11T12:54:52+01:00] Validating supplied configuration
INFO[2017-01-11T12:54:53+01:00] Configuring static IP for additional networks using port group "VMKernel"
INFO[2017-01-11T12:54:53+01:00] Suggesting valid networks for --public-network
INFO[2017-01-11T12:54:53+01:00] Suggested values for --public-network:
INFO[2017-01-11T12:54:53+01:00]   "Local PortGroup"
INFO[2017-01-11T12:54:53+01:00]   "none"
INFO[2017-01-11T12:54:53+01:00] Suggesting valid networks for --client-network
INFO[2017-01-11T12:54:53+01:00] Suggested values for --client-network:
INFO[2017-01-11T12:54:53+01:00]   "Local PortGroup"
INFO[2017-01-11T12:54:53+01:00]   "none"
INFO[2017-01-11T12:54:53+01:00] Suggesting valid networks for --management-network
INFO[2017-01-11T12:54:53+01:00] Suggested values for --management-network:
INFO[2017-01-11T12:54:53+01:00]   "Local PortGroup"
INFO[2017-01-11T12:54:53+01:00]   "none"
INFO[2017-01-11T12:54:53+01:00] Suggesting valid networks for --bridge-network
INFO[2017-01-11T12:54:53+01:00] No valid networks found
INFO[2017-01-11T12:54:53+01:00] Firewall status: DISABLED on "/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.50"
WARN[2017-01-11T12:54:53+01:00] Firewall configuration on "/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.50" may prevent connection on dst 2377/tcp outbound with allowed IPs: [172.16.24.11 172.16.24.10]
INFO[2017-01-11T12:54:53+01:00] Firewall status: DISABLED on "/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.51"
WARN[2017-01-11T12:54:53+01:00] Firewall configuration on "/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.51" may prevent connection on dst 2377/tcp outbound with allowed IPs: [172.16.24.11 172.16.24.10]
WARN[2017-01-11T12:54:53+01:00] Unable to fully verify firewall configuration due to DHCP use on management network
WARN[2017-01-11T12:54:53+01:00] VCH management interface IP assigned by DHCP must be permitted by allowed IP settings
WARN[2017-01-11T12:54:53+01:00] Firewall configuration may be incorrect if firewall is reenabled on hosts:
WARN[2017-01-11T12:54:53+01:00] 
"/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.50"
WARN[2017-01-11T12:54:53+01:00] 
"/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.51"
INFO[2017-01-11T12:54:53+01:00] Firewall must permit dst 2377/tcp outbound to the VCH management interface if firewall is reenabled
INFO[2017-01-11T12:54:53+01:00] License check OK on hosts:
INFO[2017-01-11T12:54:53+01:00]   "/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.50"
INFO[2017-01-11T12:54:53+01:00]   "/pcc-10-255-1-53_datacenter2368/host/Cluster1/172.16.24.51"
INFO[2017-01-11T12:54:53+01:00] DRS check OK on:
INFO[2017-01-11T12:54:53+01:00]   "/pcc-10-255-1-53_datacenter2368/host/Cluster1/Resources"
ERRO[2017-01-11T12:54:53+01:00] --------------------
ERRO[2017-01-11T12:54:53+01:00] Error checking network for --public-network: network 'VM Network' not found
ERRO[2017-01-11T12:54:53+01:00] Error checking network for --client-network: network 'VM Network' not found
ERRO[2017-01-11T12:54:53+01:00] Error checking network for --management-network: network 'VMKernel' not found
ERRO[2017-01-11T12:54:53+01:00] An existing distributed port group must be specified for bridge network on vCenter: network 'container1' not found
ERRO[2017-01-11T12:54:53+01:00] Create cannot continue: configuration validation failed
ERRO[2017-01-11T12:54:53+01:00] --------------------
ERRO[2017-01-11T12:54:53+01:00] vic-machine-linux failed: validation of configuration failed

**Comment by bezorrao** [comment]
What i did to make the command work was to run the command with 'folder_name/dvs_name' instead of only 'dvs_name' on the "--bridge-network" option

**Comment by wolruf** [comment]
You're right, folders work for portgroups. We tested again.
We have only the issue left with datastores located in folders.

mdestrez@desk:~/VIC/vic$ ./vic-machine-linux create --target
pcc-37-187-228-16.ovh.com/pcc-37-187-228-16_CePasCeluiLaQueTuViensDeCreer
--image-store "Shared Network/pcc-003899" --user mdestrez
--bridge-network vic-portgroup  --tls-cname=pcc-37-187-228-16.ovh.com
--compute-resource Management3
INFO[2016-11-22T12:17:18+01:00] Please enter ESX or vCenter password:        
INFO[2016-11-22T12:17:24+01:00] Generating CA certificate/key pair -
private key in ./virtual-container-host/ca-key.pem
INFO[2016-11-22T12:17:24+01:00] Generating server certificate/key pair -
private key in ./virtual-container-host/server-key.pem
INFO[2016-11-22T12:17:24+01:00] Generating client certificate/key pair -
private key in ./virtual-container-host/key.pem
INFO[2016-11-22T12:17:24+01:00] Generated browser friendly PFX client
certificate - certificate in ./virtual-container-host/cert.pfx
INFO[2016-11-22T12:17:24+01:00] ### Installing VCH ####                      
INFO[2016-11-22T12:17:26+01:00] Validating supplied configuration            
INFO[2016-11-22T12:17:26+01:00] Suggesting valid values for
--image-store based on "Shared Network/pcc-003899"
INFO[2016-11-22T12:17:26+01:00] Suggested values for --image-store:          
INFO[2016-11-22T12:17:26+01:00]   "iso-linux"                                
INFO[2016-11-22T12:17:26+01:00]   "iso-windows"                              
INFO[2016-11-22T12:17:26+01:00]   "templates-linux"                          
INFO[2016-11-22T12:17:26+01:00]   "templates-windows"                        
INFO[2016-11-22T12:17:26+01:00] Suggesting valid networks for
--bridge-network
INFO[2016-11-22T12:17:26+01:00] No valid networks found                      
ERRO[2016-11-22T12:17:27+01:00] Firewall check SKIPPED                      
ERRO[2016-11-22T12:17:27+01:00]   datastore not set                          
ERRO[2016-11-22T12:17:27+01:00] License check SKIPPED                        
ERRO[2016-11-22T12:17:27+01:00]   datastore not set                          
ERRO[2016-11-22T12:17:27+01:00] DRS check SKIPPED                            
ERRO[2016-11-22T12:17:27+01:00]   datastore not set                          
ERRO[2016-11-22T12:17:27+01:00] Compatibility check SKIPPED                  
ERRO[2016-11-22T12:17:27+01:00]   datastore not set                          
ERRO[2016-11-22T12:17:27+01:00] --------------------                        
ERRO[2016-11-22T12:17:27+01:00] datastore 'Shared Network' not found        
ERRO[2016-11-22T12:17:27+01:00] An existing distributed port group must
be specified for bridge network on vCenter: network 'vic-portgroup' not
found
ERRO[2016-11-22T12:17:27+01:00] Firewall check SKIPPED                      
ERRO[2016-11-22T12:17:27+01:00] License check SKIPPED                        
ERRO[2016-11-22T12:17:27+01:00] DRS check SKIPPED                            
ERRO[2016-11-22T12:17:27+01:00] Compatibility check SKIPPED                  
ERRO[2016-11-22T12:17:27+01:00] Create cannot continue: configuration
validation failed
ERRO[2016-11-22T12:17:27+01:00] --------------------                        
ERRO[2016-11-22T12:17:27+01:00] vic-machine-linux failed: validation of
configuration failed

**Comment by bezorrao** [comment]
I'm stuck on the same problem... seems they already know of this... https://github.com/vmware/vic/issues/773

**Comment by wolruf** [comment]
Thanks for finding it! I'm closing this issue, this is indeed the same issue.
