### ISSUE TITLE
Add https://vmware.github.io/vic to the GitHub repo description/link

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3591]
We should link to our github.io site on the repo like Harbor does:

<img width="841" alt="harbor" src="https://cloud.githubusercontent.com/assets/4361620/21856541/010e246a-d7e8-11e6-8cdb-7d00a937c180.png">

Assigning to @mdubya66 since admin permissions are needed to do so.

**Comment by mdubya66** [comment]
Updated the landing page.
