### ISSUE TITLE
Add git pre-commit hook to check commit message

### ISSUE THREAD

**Issue by dougm** [vmware/vic#360]
https://github.com/vmware/vic/blob/master/CONTRIBUTING.md#format-of-the-commit-message

In particular, we should be able to enforce the first 4 of the seven rules of a great git commit message:
- http://chris.beams.io/posts/git-commit/#separate
- http://chris.beams.io/posts/git-commit/#limit-50
- http://chris.beams.io/posts/git-commit/#capitalize
- http://chris.beams.io/posts/git-commit/#end

To see why we want the first 2, run `git log --oneline`

hickeng: This should also strip the `[specific ci...]` and similar messages that we are currently using in PRs.

**Comment by anchal-agrawal** [comment]
I found a helpful section from the Pro Git book for this: https://git-scm.com/book/en/v2/Customizing-Git-An-Example-Git-Enforced-Policy

**Comment by mhagen-vmware** [comment]
https://www.npmjs.com/package/husky
https://github.com/conventional-changelog/validate-commit-msg
https://github.com/m1foley/fit-commit
