### ISSUE TITLE
Research spike: Investigate CI work

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3600]
As a QE on the project, I need to understand what work needs to be done in order to advance the story on improving our CI infrastructure so that I can work on the issues in future sprints.  The stories generated from this research spike need to be ready to work on in future sprints.

CI Requirements
=============
In priority:
Reliable  - Trust the results
Available - CI During work hours
Production Ready - Reliable storage, recreate environment easily
Reporting - Trend Analysis
Performance - <1hr to completion
Scalable - Should handle Bursts
Easy to Use - Job Control(inc cancel, start job, pipelining, specify bersion target)
Monitoring - Job feedback. Did I break something? System monitoring
Publishing - Tagging

**Comment by sgairo** [comment]
Does #1952 fall here under requirements?

**Comment by mhagen-vmware** [comment]
Naw. Could be part of the ultimate epic, but this is just a research spike.

**Comment by mhagen-vmware** [comment]
Please review:
 https://github.com/vmware/vic/issues/3676
