### ISSUE TITLE
Upgrade data migration design

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3607]
As a developer, I need a data migration design document to make sure my implementation does not violate initial design, and I need a developer guideline, so while I need to change configurations, includes vch, container configuration and key/value stores, I know how to do to make the data migrated to newer version.

**Comment by emlin** [comment]
Design doc: #3430 
framework proto: #3477 
still need to write developer guidline for how to add upgrade plugin for any VCH or container configuration change, or key/value store change.

**Comment by mhagen-vmware** [comment]
lgtm
