### ISSUE TITLE
Integrate, setup, and start using PullApprove

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#3613]
https://about.pullapprove.com/

## Requirements
Require component owners to sign-off on changes to particular components.  This should prevent changes (PRs) from being merged until those parties have approved the change.

## Work items
- [ ] Split repo into components by paths.  Each component can map to many paths.
- [ ] Configure the paths identified above to be approved in the PullApprove config file by their component owners

We want to put this into production asap.  Given the features we require, we'll need to provide a credit card to setup our PullApprove account.  The expense will need to be approved by @mdubya66.

cc @hickeng

**Comment by mdubya66** [comment]
Talk to me about who to check with on what it will take to plug this in.

**Comment by gigawhitlocks** [comment]
Waiting on reply from Clarity team
