### ISSUE TITLE
Implement custom log formatter

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3615]
Acceptance:
* log formatter should conform to the logurs [Formatter](https://github.com/sirupsen/logrus/blob/master/formatter.go) interface
* all uses of logrus in VIC engine use the new formatter

**Comment by fdawg4l** [comment]
I just want to be clear on the terms here.  

> log formatter should conform to logrus interface

The log formatter is an interface in the `logrus` package.  Do you mean implement a logger that the logging interface used by `logrus`?  Specifically `Infof, Errorf, Debugf, etc`?  Or do you mean implement the log formatter to be used by `logrus`?

**Comment by hmahmood** [comment]
@fdawg4l see updated acceptance criteria.

**Comment by fdawg4l** [comment]
Are we certain we want to use `logrus`?  All of the advanced features aren't important to us.  Infact the `tty` handling ruins formatting because it's trying to be too smart.  And unless we're planning on stream logs via JSON, I don't see us using a custom logger other than to disable their cruft.

**Comment by fdawg4l** [comment]
In case you need it, i tried to merge a change upstream which turns the tty handling into a tunable.

https://github.com/fdawg4l/logrus/commit/90b75b9b53ad8c4a7268618f63d34dafbb9e245b
