### ISSUE TITLE
Support inventory folders when creating new resources

### ISSUE THREAD

**Issue by dougm** [vmware/vic#3619]
As a customer, I want to use vCenter inventory folders to organize inventory resources created by VIC so that I can apply management operations at the inventory folder level, such as RBAC.

Both vic-machine and VCH should support creating resources within inventory folders for existing types:

* VirtualApp

* VirtualMachine

And consider type we may create in the future, such as:

* DistributedVirtualPortgroup

At a minimum, we should support the use of existing inventory folders, but could also support creating inventory folders as a convenience.

**Comment by stuclem** [comment]
Proposed text for 0.9 release notes:

----

- <b>`vic-machine` and VCH do not support creation of resources within inventory folders. [#3619](https://github.com/vmware/vic/issues/3619)</b><br>This capability will be added in a future release.

-----

@dougm does this cover it?

**Comment by stuclem** [comment]
Thanks @dougm. Removing kind/note.

**Comment by matthewavery** [comment]
Converting this to an epic. There are three things that need to be done for this issue. Issues are being made for these and added now. @pdaigle

**Comment by matthewavery** [comment]
There appears to be a dependency chain here as well. Looks like #7032 must be done first, then #7025. Then #4326. This is due to the fact that the VCH is not created under it's own folder. noted from PR #6772 commit named `Update tests to support resource pool based VCH`

**Comment by zjs** [comment]
It seems like this and #773 are both epics, but it's not clear to me what's tracked by one vs. the other.

**Comment by hickeng** [comment]
Adding to 1.4 as this will be an organisational issue for large numbers of containerVMs at scale, and also impacts the granularity with which we can apply security permissions.

**Comment by hickeng** [comment]
left #4326 as a child of only #773 - it is likely to be fixed by this work, but isn't technically part of it. It's a bug in _existing_ support, not part of new function.

**Comment by mdubya66** [comment]
All issues completed. Closing.
