### ISSUE TITLE
Docker API: Docker Attach

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#362]
Implement the ability to stream an interactive session with the running process in a container.  This work is integrating our implementation of the engine-api servr to our interaction port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#attach-to-a-container
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#attach-to-a-container-websocket

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by hickeng** [comment]
@sflxn please add an estimate

**Comment by sflxn** [comment]
I've ported the Docker code to do attach.  The original code is vendored, but the modified version will sit in vic/pkg/docker.  The code is actually very simple, and I considered just writing it myself, but they seem to have a lot more code than seems to be necessary.  I must assume they have all that code to handle edge cases.  That's the primary reason for reusing their code instead of rewriting well known code patterns.

**Comment by sflxn** [comment]
The attach code in the docker api server has some issue with tty input.  This is the tty input that's set up by the client side CLI.  I suspect the issue may be around either the resize operation or setting to raw mode.

I've taken a break from this to work on code to make a connection to the port layer.  I haven't yet decided to reuse docker's code for this or just write my own.  Again, this is really simple code and Docker's code in the CLI takes a very circuitous path.  Way more involved than it seems like it should.  It should just be an HTTP call and grabbing the conn, but their code makes dozens and dozens of call.  Perhaps it's all needed.  I don't know.  I'm going to take a second look at it.

**Comment by sflxn** [comment]
One last update, the attach code on the api server side was more involved than originally thought.  Attach on the CLI side is actually a composition of calls to inspect, resize, and attach.  Inspect wasn't originally in the scope of this milestone.  I know from looking at docker's code that the CLI doesn't expect much from the metadata sent back from inspect.  We do not need to fully implement inspect to demonstrate attach.  For the first pass, I am dummying data in inspect.  If I have time today, I will add inspect to the port layer side, but that is very optimistic.  I'll see if I can't add that over the weekend.

**Comment by sflxn** [comment]
I'm currently testing the entire integration.  Right now, I am stuck.  The call to get the ssh session to the VM hangs.  @fdawg4l and I have talked about this.  I'm going to do some debugging to make sure it's definitely that code.  What I plan to do is use a test binary on the portlayer side and see if I didn't break anything in the last 2 days.  Then I'll run the unit tests for the ssh session code.  If everything points to that, then I will need to get @fdawg4l and @hickeng help debugging that since I didn't work on that code.  I know in theory how it work, but it will take time for me to get up to speed with how to debug that code.

**Comment by sflxn** [comment]
We got attach working, reusing some of docker's code and modifying it.  However, we've been looking at trying a Swagger based stream handling approach, a design I've been calling '3 streams'.  We've hit a little snag.  The go-swagger code generator generates some code that prevents us from exposing stdout, stderr from the portlayer side to the docker personality.

We're attempting to figure out a fix for the code generator.

https://github.com/go-swagger/go-swagger/issues/533

**Comment by sflxn** [comment]
Reworked the personality code for attach to use 3 streams + swagger.  However, I am having a lot of difficulties with cancellation.  I can cancel stdin, stdout.  Stderr cancellation isn't working.  I suspect stdout cancellation will also not work if there isn't a constant stream of data being pumped from the portlayer to the personality server.

I wrote an iowriter that implements ReadFrom that allowed me to cancel, and it worked well for stdout if there is a stream of data coming out.  It failed on stderr.  @casualjim and I investigated adding go's context to swagger request.  Again, it works great for stdout but not stderr.

Studying golang's ctxhttp, client, and request code to see why it's not working.

**Comment by sflxn** [comment]
I will also add that before the 3 streams design, I was establishing a connection directly to the portlayer and not going through swagger.  It was very easy to do cancellation in that design.

**Comment by fdawg4l** [comment]
@sflxn IIRC that design had other issues. 

Would not using swagger help here? I don't understand how 3 streams is coupled with swagger. It shouldn't be.

**Comment by sflxn** [comment]
@fdawg4l Using Swagger makes some things easier for sure, but with Swagger in between, you do not have direct access to the net.conn.  Before, it was as simple as closing the connection.  Now, we need to cancel in a round and about way, which I haven't really found yet.

**Comment by sflxn** [comment]
Not handling the stderr cancellation results in re-attachment to eventually fail.  That might be something to look into, but I'd rather get the cancellation working.

**Comment by sflxn** [comment]
Got it resolved.  It was 2 bugs that were introduced in the recent swagger update adding context to request.  It's all fixed.
