### ISSUE TITLE
H5 UI Plugin won't show up in vSphere Client of vCenter 6.5 for Windows

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#3621]
User statement: The local-cache approach for deploying the plugin doesn't work with H5 Client running on vCenter 6.5 for Windows. HTML SDK team mandates that we always use a web server to deploy the plugin. This will potentially be solved once VIC later has REST API server but for now we could circumvent the problem by embedding an HTTPS server in `vic-ui-*` which will be fired and killed automatically by an installer script.

Once this issue is resolved, fix will be included in a PR for the H5 Client Plugin

Details: Two options being decided - either a 2nd web server or piggy back on vic-admin web server

Acceptance criteria:
1. H5 ui plugin works when running on vcenter 6.5 for windows
2. Test is created that verifies the behavior

**Comment by mhagen-vmware** [comment]
Can you please add an estimate?   And acceptance criteria, I am having difficulty understanding the deliverable here - is the deliverable to provide a HTTPS server?

**Comment by jooskim** [comment]
This depends on #3668, so I would rather give this the same estimate of 3

**Comment by jooskim** [comment]
This has slightly changed since the last sync-up meeting where we could use the VIC Admin web server rather than have an extra server. See my latest comment on #3668 for details.

**Comment by corrieb** [comment]
@jooskim Is this still an issue? If so, is it a must-fix for 1.2?

**Comment by jooskim** [comment]
@corrieb This was also addressed around when we started to have the VIC OVA. Should've kept my eyes on some out of sync issues like this.
