### ISSUE TITLE
Research Spike: NFS Shared Volumes

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3622]
Faiyaz and I need to go over what the requirements for NFS Shared Volumes are. We need to do the following.

- [ ] Look at how customers would like to use shared volumes and verify that their expectations can be met. E.g.  explore docker's implementation and usage model and how we can make it fit ours.
- [ ] Decide on how it will be implemented by coming up with an interface and straw-man implementation.
  - [ ] Identify failure modes and how they will be handled
  - [ ] Specify how the NFS volume stores are described via vic-machine and the necessary validation steps
- [ ] Design integration tests and, if possible, unit tests to prove that the implementation will work.

Open questions
  Do we want to address #3482?  That is, do we want to address mounting a volume in a container's directory when that directory has data on it.  In docker, the contents of the dir gets copied to the volume.  But any change to support this on NFS will need to be supported with vmdk backed volumes as well, so the issue and implementation can be kept out of this spike.

**Comment by fdawg4l** [comment]
https://docs.docker.com/engine/reference/commandline/volume_create/#/driver-specific-options

**Comment by fdawg4l** [comment]
@matthewavery #2303 is about mounting a volume with the contents of the local system.  I don't see how that should be related to NFS (other than the fact that the conversation devolved into talking about NFS in the issue).  Lets not conflate things that aren't related at this point.

**Comment by fdawg4l** [comment]
OK, @hickeng clarified there's valuable conversation in that issue with regards to NFS shared storage so I see why it's worth mentioning here.  But, now we're ratholing around whether or not this issue is a dup of that one or vice versa since they're both going to be closed by 1 PR.

**Comment by matthewavery** [comment]
@fdawg4l well... it would be a local filesystem mount from the appliance really which is not a useful feature for use to include. Unless there is some other file system we want to mount from? docker mounts from the "local" filesystem of the daemon. So in a local docker deployment that is the same filesystem, but a remote docker would use the remote server's filesystem which is likely not a very useful thing to do with VIC. Is this what you are referring too?

**Comment by fdawg4l** [comment]
The expectation is the customer provide an nfs endpoint to include as a volume.

**Comment by fdawg4l** [comment]
```
$ docker volume create --driver local --opt type=nfs --opt o=addr=172.17.0.1,rw --opt device=:/home/fahmed/src --name fdawg4lsrc
fdawg4lsrc

$ docker run -v fdawg4lsrc:/src -it busybox                                                                                                                   
/ # mount
...
:/home/fahmed/src on /src type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=172.17.0.1,mountvers=3,mountproto=tcp,local_lock=none,addr=172.17.0.1)
...
/ # ls -l /src
total 84040
...
drwxrwxr-x    5 1000     1000          4096 Jan 11 16:52 vic
...
/ # 

$ docker volume ls
DRIVER              VOLUME NAME
local               fdawg4lsrc
```

**Comment by fdawg4l** [comment]
So from a customer requirements point of view given the above terminal snapshot we need to

- [ ] Allow the docker user to add a fully qualified NFS target as a volume
- [ ] Allow the dorker user to create containers with the above volume mounted to the given destination

**Comment by fdawg4l** [comment]
We need to identify if "NFS" means NFSv3 and/or NFSv4.  

NFSv3 is the simplest to implement / get working in our model since access control is based on a CIDR address (which can be a host or a range of IPs).   The client only needs to `mount` the given nfs target, and the server takes care of validating the host.  Configuration on our side is therefore just passing the `host + mount` path to the client.  Validation is somewhat tricky, however; we'd need to validate both network connectivity to the endpoint and see if our container is in the ACL for the path on the given target.

NFSv4 *can* use kerberos.  This means passing keys to the client in order for the mount to succeed.  It's not required, but cert based auth and extended attributes are really the only reasons to use NFSv4, in my opinion.  I'll chat with @karthik-narayan to see how much we need this.  There is a lot of overlap between NFSv4 and CIFS, so the implementation of one will make the other easier.

**Comment by hickeng** [comment]
@fdawg4l Given this is the design phase, consider the various ways in which we could do credential injection. I cannot think of a simple way to prevent the credentials being visible to container workloads, but maybe there's something we can finesse.

Regarding the user consumption of NFS volumes I think there's two primary use cases:
1. Straight up NFS volume, with the person creating the container knowing everything necessary to connect to that NFS share
2. NFS volume stores - in this case it's providing a shared storage mechanism, but _without_ the Docker API user needing to know anything about the infrastructure.

I think we need to look at both, but I'd actually rate the latter as a better match for our general approach of minimal infra knowledge required by the user of the API.

**Comment by fdawg4l** [comment]
@hickeng 

> 2. NFS volume stores - in this case it's providing a shared storage mechanism, but without the Docker API user needing to know anything about the infrastructure.

I don't follow.  Can you give me an example of how that would look?  Start with I have an nfs server running on `myhost:/path/to/share`.

**Comment by fdawg4l** [comment]
I had to think about this for a bit, but I think I'm following.  I think what you're getting at is (1) when a user wants to share a directory on a server somewhere between containers and the host and path are known to the user and (2) when the user just wants to share a (new) volume between containers.  In (1), that's more traditional file server stuff;  a blessed path with important data is known and setup is just a matter of passing the right params to the user.  In (2), nothing is known and the location is empty (if it even exists).  In that case, we'd treat a given server and path as a volume store and create volumes as top level directories and allow the user to share them between containers.

Am I on the right track?

**Comment by fdawg4l** [comment]
Looks like there's a `go` nfs client that would be appropriate for (2) should we decide that's the way to go.  https://github.com/davecheney/nfs/blob/master/example/lsmount/main.go

**Comment by fdawg4l** [comment]
Spec in progess.  https://github.com/fdawg4l/vic/blob/nfsvol/doc/design/volumes/nfsvolumestores.md
