### ISSUE TITLE
Docker API: Docker Container Stop

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#363]
Implement docker stop operation in our docker engine-api server.  Integrate it with the exec portlayer server.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#stop-a-container
https://docs.docker.com/engine/reference/commandline/stop/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by matthewavery** [comment]
An initial implementation is being tested now, @sflxn is taking a look at the code I have written so far as a first pass.
