### ISSUE TITLE
Docker API: Docker Container Remove

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#364]
Implement the docker container remove operation (docker rm from CLI) in our docker engine-api server and integrate that with the storage port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#remove-a-container

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by matthewavery** [comment]
Minimal work has been completed on this Issue, all that is left is providing support for the options.

**Comment by mdubya66** [comment]
@matthewavery is this complete?

**Comment by matthewavery** [comment]
This is just pending the flag support for container removal. Currently there is no way to gracefully remove the containers.

**Comment by matthewavery** [comment]
According to ticket #436 we will need a way to discern between anonymous and regular volumes. Then we will need `docker volume rm` to work for us to remove anonymous volumes with the container that is associated with it. additionally for the `docker rm -f` we should be using kill to send signals to the tether. So this is dependent on the `docker kill` functionality being in place.

**Comment by hickeng** [comment]
@matthewavery is this still TBD?

**Comment by mdubya66** [comment]
Closing. @matthewavery if this is incorrect please talk to @hickeng and reopen
