### ISSUE TITLE
Design: vApp removal

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3644]
PM has asked us to move away from the vApp based deployment, as the use of a vApp is a potentially confusing construction for a VCH.

Results:
- [ ] identification of the specific reasons behind the request
- [ ] validation that shifting from vApp addresses those reasons
- [ ] identification of alternative approaches
- [ ] creation of follow on issue for detailed breakdown of alternative.

**Comment by emlin** [comment]
Latest message got from vSphere team:
"Currently we haven't started yet and we haven't defined our requirements yet. It's currently something we are wanting to work toward but as you can see, we are still quite a ways out. I'd say sometime in 2018 at the very very earliest."

**Comment by emlin** [comment]
Looks like it is not a critical feature in vSphere, and we do not know what gonna be the replacement. What about we postpone our feature as well?
@hickeng @mdubya66 @karthik-narayan

**Comment by hickeng** [comment]
Let's defer this until we have a concrete approach for an alternative in the H5 client.

**Comment by mdubya66** [comment]
Agreed on change in priority

**Comment by andrewtchin** [comment]
We've already moved away from vApp, closing.
https://github.com/vmware/vic-product/issues/1523
