### ISSUE TITLE
Phone home: determine permissible approaches

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3645]
We have some constraints around using the current phonehome libraries in OSS. We need to follow up with the PhoneHome team and determine exactly what approaches are available to us at this time and in the next few months.

Output:
- [ ] Initial design doc for phone home integration detailing approaches and areas of concern if any

**Comment by sflxn** [comment]
After a lengthy email thread discussion, the best approach is to modify our toolbox to provide the OS fullname, which is simply a string that we can populate with any text we need.  We can provide "Photon OS - VCH" as the OS fullname for the VCH VM and "Photon OS - Pico" as the OS fullname of the container VM.

vSphere is already getting the OS fullname from a VM guest tools and there is already a collector sending this to VAC.  Our toolbox has not been reporting this.  Once we provide this, the VAC team can create queries on this field to differentiate VMs that are VCH and container VMs.

@karthik-narayan has a list of metrics he wants to gather.  Most of those metrics are already getting gathered.  Some information such as docker command frequency, most commonly used images, and others are currently not capture.  We will need to add further code outside of the toolbox to push this information up to VAC.

I will create an initial design doc for the OS fullname work and outline whether we currently get the data for the metrics Karthik needs.  Another issue will be created for future work in future sprints to address the metrics that we currently do not retrieve and address adding code to upload those metrics to VAC.

**Comment by sflxn** [comment]
Output of this research spike:

#3774 is the initial design PR
#3775 was created as the implementation follow up.

I have a meeting with the VAC team to figure out how to extend the data set we will want to collect in the future.

**Comment by mdubya66** [comment]
#180 adding for tracking purposes

**Comment by mdubya66** [comment]
#119 for tracking purposes

Added this to 119. 

1.1 feature request.
From @karthik-narayan via email
Our tools needs to return a custom value - “Photon OS – VCH “ and “Photon OS – Pico” or some such thing.

Here is the data from phone home that I’d like to see per deployment:
Number of ESX hosts in the cluster
Version number of ESX hosts
Version number of VC hosts
Presence of Harbor or Admiral with version number
Total number of VMs
Total number of VCHs
Total number of container VMs
Number of VCHs per host
Number of container VMs per VCH
Average lifetime of the Container VMS
Most common images deployed
Image source
Most common list of docker commands used
Is port mapping used, if so how often
Except for 11,12,13 and 14, I believe that all other data can be auto generated / collected by VAC, if we are able to update our tools. 11,12,13 and 14 are nice to have for the Q1 release.

**Comment by mdubya66** [comment]
#23 for tracking purposes
#200 was the original PR that included this

**Comment by sflxn** [comment]
Thanks for adding these @mdubya66.  I wasn't sure whether I should go ahead and add those here.

Metrics 1-9 can be handled very readily (with exception of the Harbor and Admiral version) today.  Exposing a custom OS full name for the VCH and container VM will provide us items 5-9.  Item 10 needs to be verified for container VMs stopped and restarted.  Items 11-14 will require more work beyond OS full name update in the toolbox.

**Comment by sflxn** [comment]
After further investigation, the proposal to use the toolbox did not work.  However, it may be possible to use alternateGuestName in the vm configspec instead.  I have deployed a VCH with this change and updated the VAC collector on my VC to push updates more often.  I am awaiting verification that this will work for us.

**Comment by sflxn** [comment]
I've verified that alternate guest name works well.  The data has been uploaded to VAC, and I see it now.

**Comment by sflxn** [comment]
@karthik-narayan I am not sure common docker command will make sense.  It only serves us during the lifetime of the personality server.  Once we move over to containerd, we will get out of the business of adding code to the API server that directly serves the CLI so we will no longer get this data.

**Comment by sflxn** [comment]
After discussion with @karthik-narayan, we have trimmed the minimum data set for phone home.

**Comment by karthik-narayan** [comment]
Thanks for getting this done @sflxn.
