### ISSUE TITLE
Phone home: minimum data set indentification

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3646]
We need to determine what our minimum data set is - it's not worth adding additional customer complexity if we cannot meet the minimum needed to generate useful metrics.

Output:
- [ ] determine the minimum data set that adds value for product management
- [ ] determine minimum data set that adds value for the dev team

**Comment by mdubya66** [comment]
Need to setup a meeting with the PH team. Whoever takes his please ping me for the names.

**Comment by sflxn** [comment]
After discussion with Karthik and the VAC team, we have come up with the following list minimum data set for phone home:

1. Number of ESX hosts in the cluster
2. Version number of ESX hosts
3. Version number of VC hosts
4. Presence of Harbor or Admiral with version number
5. Total number of VMs
6. Total number of VCHs
7. Total number of container VMs
8. Number of VCHs per host
9. Number of container VMs per VCH
10. Average lifetime of the Container VMS

@karthik-narayan You can lgtm if you're in agreement.

**Comment by mdubya66** [comment]
lgtm for karthik. moving to close
