### ISSUE TITLE
Milestone: Exec

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3649]
As a VIC user, I should be able to exec a secondary command in a current running container.

Create a design for Container Exec.

**Comment by sflxn** [comment]
#3048

**Comment by sflxn** [comment]
There is ongoing work to design the tether and redesign the portlayer apis.  This exec design work should probably wait till the first draft of the portlayer redesign.

**Comment by hickeng** [comment]
Coarse steps for configure (tentative):
* Personality API for exec
* Portlayer API for exec (join task, bind task)
  * suggests that container config could have multiple joined tasks when created, but necessarily bound so not launched
  * Reconfigure container with new session
  * Trigger reload in tether
* Tether support
  * reload trigger
  * tasks in configuration that are not launched by default?
