### ISSUE TITLE
Docker API: Docker Image Remove

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#365]
Implement docker image remove (docker rmi from CLI) in our docker engine-api server and integrate that with the storage portlayer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#remove-an-image

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by corrieb** [comment]
Moving out of onsite to GA, given that #437 got moved
