### ISSUE TITLE
Docker Compose support in VIC 1.1

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3657]
Track all features and issues needed to complete VIC 1.1's support for Docker Compose.

**Comment by chengwang86** [comment]
Research spike for compose: #3635 

Docker-compose cmds related: 
- bundle: #3648 
- kill: #3707
- build: 
- exec: #3649 
- pause: #381
- unpause: #382 
- events: #2252 
- scale: #432 
- Milestone: compose up #431

 
Docker-compose file syntax related:
- docker network create --ipam: #3737 
- docker network create --internal: #3736 
- docker network create --labels: #3738 
- docker inspect not showing correct volume information: #3740 

Docker daemon support:
- rename: #380 
- filter: #1676, #3650 
- shared data volumes: #2303

Other dependent issues:
- #2525 docker compose complains if there are orphan containers
- #1745: 404 page not found while running docker-compose voting app 
- #2522: Server error from portlayer: Failed to lock the file 

Docker-compose docs:
#3762 #3122 #879

**Comment by mdubya66** [comment]
@chengwang86 please add these as issues under the Epic so we can see the progress

**Comment by sflxn** [comment]
Cleaned up the epic.  Streamlined it just for VIC 1.1.  Any issue we pushed out to 1.2 and beyond, I have created a new epic:

https://github.com/vmware/vic/issues/4115
