### ISSUE TITLE
Docker API: Docker Container Logs

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#366]
Add docker log operation to our engine-api server and integrate that with the interaction portlayer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#get-container-logs
https://docs.docker.com/engine/reference/commandline/logs/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by dougm** [comment]
@jzt is going to take on the API/PortLayer piece, I'm taking the vSphere datastore file streaming piece (#1682)

**Comment by sflxn** [comment]
Separated the last few docker operations into personality and portlayer work to follow the pattern we've been using on this project.

**Comment by sflxn** [comment]
This will use a similar mechanism on the portlayer rest side as attach.  The same goes for the personality server side.  My estimates for this includes both the personality server and portlayer rest server.

In addition to container logs, docker logs also requires getting the stdout and stderr.  We should be able to attach to the tether and get those as well as get the container logs from the datastore log streaming in #1682.

**Comment by sflxn** [comment]
@hickeng @dougm and I just had a good conversation about docker logs. Docker logs can do 2 things that we cannot currently do at this point. The first is to tag all log lines with a timestamp. The second is to be able to grab all log since a timestamp. The importance of the latter may not be apparent immediately. Docker logs interleaves containers logs, stdout, stderr into the output. The tether returns the stdout and stderr streams at the point that we ask for data. To fully support the docker logs behavior, we will need to keep stdout and stderr around as we do the container logs, and we need to do so with timestamp.

It was decided at this meeting that we would go with what we have right now. Timestamps and historical stdout & stderr requires significant plumbing and will need to come later.

@stuclem What this means is that the docker logs options --timestamps (also -t) and --since options will not work initially.

**Comment by sflxn** [comment]
I noticed something very peculiar with docker logs.  I was trying to figure out how they delimit their log lines.  They are delimiting their logs with either /n or /r/n.

If you run

```
docker run -it busybox /bin/sh -c 'a=1; while [ $a -gt 0 ]; do echo "line $a"; a=`expr $a + 1`; sleep 1; done;'
```

their json log file looks normal.  However, if instead of echo, I use printf (no newline), their json log files never gets updated nor can I get the logs of the container until I quit the running session.  At that point, it just dumps out everything from stdout as one log line with the timestamp of that time.

```
docker run -it busybox /bin/sh -c 'a=1; while [ $a -gt 0 ]; do echo "printf $a"; a=`expr $a + 1`; sleep 1; done;'
```

**Comment by sflxn** [comment]
In my WIP PR, I am checking for the end of log streaming by waiting on Swagger to receive an EOF.  This is an area we may have to tweak.

**Comment by sflxn** [comment]
I am going to make the docker personality output the following errors if user uses --timestamps (also -t) or --since.

"vSphere Integrated Container does not yet support timestampped logs."

**Comment by stuclem** [comment]
@sflxn you're missing an S at the end of "vSphere Integrated Container**s**" (just in case you cut and paste this into the code from your comment above).

**Comment by mdubya66** [comment]
This cannot be closed until the other half of the work in #1682 is merged and tested together.

**Comment by mdubya66** [comment]
while this part is merged it is not done as it can't really be tested without #1682.

**Comment by dougm** [comment]
I need to update a couple more tests referencing this issue before closing.
