### ISSUE TITLE
Research Spike: Investigate how to deploy VIC UI using standard method

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#3668]
User statement: First off, I found a critical issue with deploying the UI plugin to H5 Client with vCenter 6.5 for Windows. The current way of deploying the plugin involves directly copying the plugin contents into the Client's plugin cache folder. While this works for H5 Client with vCSA 6.5, the Windows counterpart no longer works. Also the HTML SDK team strongly advised against this practice and told us to stick with the standard procedure where a permanent web server serves the plugin zip file.

So as a developer, I need to see which options we have to host the plugin zip files (one for Flex Client and the other for the HTML Client) in a permanent manner. Furthermore, what was brought up in a relevant meeting is that we need to ask the vSphere team to collaborate with us to possibly ship VIC with vSphere (because VIC is part of vSphere) while having the ability to update VIC on its own. @karthik-narayan agreed to reach out to the vSphere team to start an initial conversation.

Details: To summarize, I need to figure out:

- [ ] What possible options are
  1. Use VIC Admin web server to host the Client plugin zip files
  2. Ship Client plugin zip files with vSphere (needs info from Karthik and vSphere team)
- [ ] How to architect the deployment procedure such that upgrade can happen out of band

Acceptance criteria:
1. Design doc for the new deployment arch
2. VIC UI can deploy using the standard method of deploying plugins
3. Test is created that verifies the expected behavior

**Comment by jooskim** [comment]
Added Sophie to discuss in detail further requirements to follow for using VIC Admin web server to host the plugin files

**Comment by mhagen-vmware** [comment]
Can you add an estimate please?

**Comment by jooskim** [comment]
I have to give this about 3, but it depends on further investigation with the vSphere team and our internal review on [Using VIC Admin web server to deploy VIC UI plugin.docx](https://onevmw-my.sharepoint.com/personal/kjosh_vmware_com/Documents/Using%20VIC%20Admin%20web%20server%20to%20deploy%20VIC%20UI%20plugin.docx?d=w1dbad3ff895c4e02b799ce68ca4225e9&e=4%3A2ac2e77aec3c4a3bad3071b84af67659)

**Comment by jooskim** [comment]
Closing the issue as it is now resolved
