### ISSUE TITLE
Docker API: Docker Container Event Subscription

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#367]
Implement docker even subscription in the engine-api server and integrate it with issue #81.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#monitor-docker-s-events

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by sflxn** [comment]
Events are needed for docker 1.13's RUN support.  They've switched from using docker wait to docker events in 1.13 to monitor a container's exit.

**Comment by sflxn** [comment]
Moved this to high priority as it will be a customer facing issue.

**Comment by mdubya66** [comment]
This is still a medium. It's not a blocker and doesn't meet the criteria of a high priority. replacing with medium

**Comment by cgtexmex** [comment]
@sflxn are you going to create a design doc for docker events?
