### ISSUE TITLE
Design and order the new servers through OVH

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3671]
User statement:  As an engineer on VIC, I want systems that have the performance and reliability of dedicated servers so that we don't have to rely on unsupported nested ESXi testing that sometimes causes problems.

Details:  Smaller dedicated server with vrack support from OVH should suffice, likely something as basic as:  https://www.ovh.com/us/dedicated-servers/details-servers-range-HOST-id-2016-HOST-32L.xml

Acceptance criteria:
1. All servers are ordered and ready to be configured

**Comment by jakedsouza** [comment]
CC @casualjim

**Comment by mhagen-vmware** [comment]
Completed by @casualjim
