### ISSUE TITLE
Initial build of a reporting server

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3674]
User statement: As an engineer on VIC, I would like a reporting server that I can easily access to monitor trends and current status of our CI system so that I can understand testing trends like specific tests that have started failing and for how long have they been failing.

Details:  Probably a simple web server with some pulls and scripts that download the test results and parse the robot results for smart monitoring.

Acceptance criteria:
1. A web server that allows anyone on the team to login and observe the current state of the testing including PASS/FAIL trends on individual suites or tests.

**Comment by jakedsouza** [comment]
Reporting servers are available on 

https://vic-logs.vcna.io/
https://vic-dashboard.vcna.io/

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
@rajanashok Can you verify this as well, for a 2nd pair of eyes please?

**Comment by rajanashok** [comment]
@jakedsouza I get prompted for login when I access the reporting servers, couldn't login using my network creds though. Do we use a different authentication mechanism for this?

**Comment by mhagen-vmware** [comment]
I gave him it on slack

**Comment by rajanashok** [comment]
LGTM. One comment on the log reporting. It would be nice to have a shortcut link to the log bundle to help troubleshoot a failure.

**Comment by mhagen-vmware** [comment]
Verified by both @rajanashok and myself. @jakedsouza Once you have LGTMs for either one of us and at least one other, you can close.
