### ISSUE TITLE
CI Improvements

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3676]
User Statement: As an engineer working on VIC, I want a CI system that is reliable, available, production ready, reporting, high performance, scalable, easy to use, provides monitoring, and can do publishing so that I can reliably do my job.

Details: In order to accomplish these goals I believe we need to move away from a nested big ESX server in OVH to smaller dedicated ESX servers, and some changes to our test infrastructure will also be needed in order to provide the monitoring and publishing capabilities.

Acceptance Criteria:
1. Current CI infra is switched over to using dedicated servers
2. A full CI build takes < 1hr
3. Documentation or a script is provided to recreate the infrastructure easily
4. Monitoring system is provided to show trend analysis
5. New CI system can handle bursts of workload reliably
6. Each of the systems are monitored and report when something is going wrong in the infra
7. At the completion of a successful tagged build, the CI will publish the build without additional input needed

**Comment by caglar10ur** [comment]
Would it possible to run current test suite against a dedicated server that we have in the lab and compare the results? I'm also confident that nested ESXi is the biggest culprit here but having some numbers could prove whether all this time (and money) will worth the effort.

**Comment by mhagen-vmware** [comment]
A pilot program would be nice, but we already have essentially what you are asking for with out dedicated setup in the building here for longevity/stress and it works fine when I run the full suite on it. I think we aren't going to get much more information out of the system without deploying the entire setup, otherwise it is just me running the full suite on a dedicated system which works just as well as when I manually run a full suite against the current CI infra and it works also.

**Comment by mhagen-vmware** [comment]
And for that matter I can run the entire suite against nimbus nested and it works fine too, it is just really hard to suss out intermittent load based failures without wholly switching over I think.

**Comment by rajanashok** [comment]
This looks good to me. One of the risk we run moving away from the hosted model is the maintenance and support overhead. If we can think through this well in advance and make sure this model will scale and works in the long run we should be good.

**Comment by fdawg4l** [comment]
I don't know if my question is in the scope of this epic, but will the new CI system address different installation environments?  E.g. a testbed to run CI w/ NFS, iSCSI, VSAN based VI environments, different vsphere versions, etc.

**Comment by mhagen-vmware** [comment]
I have vsphere version in here, I do not have nfs/iscsi/vsan because I thought we were good with existing nimbus based testing on that front?

**Comment by fdawg4l** [comment]
nfs and iscsi are likely fine on nimbus.  But VSAN is a definite no since the nimbus setup is nested and VSAN is notorious for behaving erratically in such an environment.  We don't get false positives, but we do get false negatives running VSAN nested in that way.

**Comment by mhagen-vmware** [comment]
@fdawg4l https://github.com/vmware/vic/issues/3683

**Comment by mhagen-vmware** [comment]
All subsequent issues moved to CI Improvements v3 or closed.
