### ISSUE TITLE
Docker API: Docker Registry Authenticate

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#368]
Implement the docker registry authentication operation in the engine-api server.  Right now, imagec does all of our image pulling.  I would assume this auth has some TTL attribute.

https://docs.docker.com/engine/reference/commandline/login/
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#check-auth-configuration

Please note, this functionality exist in the CLI but not the API.  For all we know, this might be handled in the docker CLI.  If that is the case, there might not be any work for us to do.

**Comment by frapposelli** [comment]
Please implement authentication via central server[0] too, it is required to support registries with more complex authn/authz models.

[0] https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md

**Comment by mdubya66** [comment]
@hickeng let's get this one assigned.

**Comment by corrieb** [comment]
Finger in the air initial sizing:

Need to implement System.AuthenticateToRegistry. Estimate at least a day for initial impl and testing. Beyond that, there may be implications on the transport. To implement the authentication via central server could easily take a week to test and implement, depending on the experience of the engineer.

**Comment by sflxn** [comment]
While I don't think this is going to take long, it's not exactly a day.  The good news is that we can reuse some of Docker's code.  The bad news is that it may or may not be compatible with how we authenticate in imagec today.  The documentation says we can pull using either credentials or token.  Imagec today, relies on credentials.  That's not the OAuth2 way.  Fine, I can resolve that.  There are a few questions that I am still trying to figure out.

1) When using credential based auth (which docker pull allows), how does the CLI ever send over the username/password?  Or is this an API-mode use case only?  I think it's the latter.  When using the CLI, it appears Docker wants to use token based auth (using OAuth2).

2) Docker's datatype code and docs has an identity token and a registry token.  When I read the server code to authenticate, it retrieves the OAuth2 bearer token and saves it to the identity token.  On docker pull, it's attempting to use the registry token, which is never populated during auth.  I suspect these are the same and Docker never cleaned up their code.  I need to figure out where this registry token comes from.

**Comment by sflxn** [comment]
Here is a breakdown of the work I believe that is needed to get docker login completed.  It's a rough estimate based on initial investigation.

1. Investigate the TLS and insecure path for login for VIC  (est 2 days)
  - Most of this is debugging and tracing docker and harbor (e.g. getting Harbor up and going with TLS or tracing docker behavior for insecure auth).  I do not believe there is a lot of code for the login.
2. Update docker pull to use the OAuth2 bearer token (< 1 day)
3. Update imagec to accept OAuth2 bearer token and do a pull (1-2 days)
4. Tests.  There are a few scenarios we will need to test.
    a. TLS enabled Harbor
    b. insecure Harbor
    c. Docker hub?

Questions that need to be answered:

1. Do we focus on Harbor now or do we also need to handle docker hub?
2. Is insecure pull important?  For enterprise, probably not.

**Comment by mdubya66** [comment]
@karthik-narayan please comment on @sflxn's questions. @corrieb

**Comment by sflxn** [comment]
I was able to do a docker login with VIC and an insecure Harbor server.  I'm having some difficulty getting Harbor up with TLS. Digging into that tonight.  Please note, that although I can login, the token handling in docker pull and imagec hasn't been touched yet.  The above estimate for number 1 still holds.

**Comment by sflxn** [comment]
I now have a pretty good understanding of how this all works. and what needs to be done.  First, I was able to login with VIC to an insecure Harbor server as mentioned above.  I was not able to pull any images or create any after logging in.  Here are some notes:

1. After logging on, the CLI creates ~/.docker/config.json with credentials or token.  With my current setup, it is saving credentials but not token.
2. On docker pull, these credentials are read by the CLI and passed onto the personality server.
3. The personality server passes the credentials to imagec.
4. Imagec has no parameters for OAuth2 token.
5. imagec appears to not perform authentication/authorization properly.  On pull, I get
```
Failed to fetch OAuth token: parsing time "1800" as ""2006-01-02T15:04:05Z07:00"": cannot parse "1800" as """
```
6. All my tests so far has been apparently with only credentials and not token.  I am not sure why the config.json hasn't been populated with an auth token yet.  Here are some theories:
 - Perhaps storing token only occurs when using a separate credential store (e.g. OS X keychain).
 - Perhaps I don't have Harbor set up correctly to output tokens.  I assume it is an OAuth2 compliant authorization server.  Curling a request for a token to Harbor isn't returning an auth token so maybe I don't have something set up correctly.  Maybe I am not sending it the right scope.
 - Perhaps token are not stored on login (authentication).  Perhaps token are only stored on pull or push (authorization).  This would make sense.
7. I am not able to set scope (e.g. pull or push auth privileges) in Harbor.  If I can't set privileges, what do I specify for scope.  I'm going to need some help from Harbor team on this.

**Comment by sflxn** [comment]
### To Dos:

Here are more detail info on what needs to be done.

1. Add flag to personality server to accept insecure registry (very easy)
2. Add code to login to personality server (very easy)
3. Figure out scopes in Harbor
4. Test with an external credential store
5. Look at imagec authentication and authorization code and fix it
6. Verify OAuth2 tokens are used for docker pull
7. Write lots of tests

**Comment by reasonerjt** [comment]
Hi, for configure Harbor with TLS, please refer to:
https://github.com/vmware/harbor/blob/master/docs/configure_https.md

Essentially, it's setup https on nginx and make docker engine/vic engine trust that cert.

**Comment by reasonerjt** [comment]
And for 10) we'll vendor docker/distribution 2.5.0 with Harbor.

**Comment by corrieb** [comment]
@sflxn, this is really great investigation work and I want to thank you for having that ready for our call this morning.

Do please reach out to the harbor team whenever you need assistance - they're keen to help.

To answer your questions above
> Do we focus on Harbor now or do we also need to handle docker hub?
Harbor is the principal focus and priority. Curious as to how docker login to docker hub different?
> Is insecure pull important? 
If it's a stepping stone on the way to our ultimate goal, then it could be important as a fall-back if there are unexpected complexities getting full integration.

@reasonerjt Could you help @sflxn with his (3) TODO above, please.

How that you're the expert, Loc, I'd like us to break down the above into a series of small functional milestones, if possible. I'm hoping the Harbor team can help with some of the testing. I can certainly help get these functional milestones defined. For each one, I'd like us to be able to clearly articulate a use-case enabled by the milestone. The reason for this is that there's significant scrutiny on us delivering the integration and we need to be able to know what the risk is if we don't make a particular milestone.

**Comment by mdubya66** [comment]
@corrieb would it make sense to get insecure login working as the first milestone?

**Comment by corrieb** [comment]
Subject to Loc's confirmation, I would say yes. Once we have this in our back pocket, this issue is no longer the blocker it once was

**Comment by sflxn** [comment]
Yeah, insecure login is a good milestone.  Secure vs insecure isn't what I am currently worried about.  Docker login is actually quite easy.  I already have VIC logging in with insecure Harbor.  It's also logging into docker hub over secure https (hopefully that means logging into a secure Harbor just works).  It's updating docker pull and imagec to correctly handle OAuth that may take awhile.  Hopefully not.  I'm looking at that now.

**Comment by sflxn** [comment]
The OAuth workflow in imagec is broken.  Fixed a few bugs.  I have another day for imagec's auth code to be fixed.  It doesn't appear the docker pull code needs a lot of changes other than to allow for insecure registries.

**Comment by mdubya66** [comment]
I'd suggest iterating on this instead of one big pull request.

**Comment by sflxn** [comment]
I'll be issuing a PR either end of today or early tomorrow.  I have code to fix the OAuth workflow in imagec.

There is a new wrinkle.  It's back to secure vs non-secure.  Non-secure registry has a vic installation implication.  It needs to know the non-secure registry at startup because we are using docker's distribution code to perform the login.  This was extra work I did not anticipate so I investigated secure login today.  I was able to get Harbor working with TLS.  Upon trying the login with the secure registry, it did not work with the self-generated certs.  It needs the self-generated ca.crt to be installed on the appliance machine, which is also a vic installation issue.  Seeing that both have installation implication, I will go back to non-secure login.

**Comment by sflxn** [comment]
I created a new issue for the ca certificates for self generated ca.crt for secured private registries.  The PR for this issue can close this issue.  The new issue affects vic-machine.  The docker personality should work with secure registries (I tried against docker.io).  Vic-machine just needs to upload the ca.cert to the appliance.
#2103

**Comment by sflxn** [comment]
Working on robot scripts right now to test docker login/pull against a base private docker registry.  It's going to take awhile.  While it is easy to run a private registry, it's more tedious to do it with robot (because of lack of experience).

**Comment by mdubya66** [comment]
@mhagen-vmware can you help loc here. this is critical for next week
