### ISSUE TITLE
Build failure: unrecognized input header: 69

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3681]
Found in this build: https://ci.vmware.run/vmware/vic/7586

```
11:51:43.148	INFO	Running command 'docker -H dhcp-192-168-31-141.ci.drone.local:2376 --tls logs f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 2>&1'.	
11:51:43.476	INFO	${rc} = 1	
11:51:43.476	INFO	${output} = Unrecognized input header: 69
```

Could be related to: https://github.com/docker/docker/issues/21902

**Comment by hmahmood** [comment]
Dup of #3682

**Comment by mlh78750** [comment]
ASCII 69 == 'E'

Likely where it was expecting something we're sending the text "Error..." or something else that starts with a cap E.
