### ISSUE TITLE
Docker API: Docker Container List

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#369]
Implement the docker container list operation (docker images from the CLI) and integrate with the storage port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#list-containers

Please note, the engine-api's rest server already packaging these json struct into golang structs.  The url above is just for reference on what the operation should do.

**Comment by jzt** [comment]
This issue is currently blocked until we get something in place that stores container metadata. See #498, #457.
