### ISSUE TITLE
VIC needs to support image.Tag for notary

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic#3692]
I setup an notary and tried using VIC to pull image from registry:
```
root@jt-dev:~/vic# env|grep TRUST
DOCKER_CONTENT_TRUST=1
DOCKER_CONTENT_TRUST_SERVER=https://10.117.4.142:4443

root@jt-dev:~/vic# docker pull 10.117.4.142/library/hello-world:1.0
Pull (1 of 1): 10.117.4.142/library/hello-world:1.0@sha256:4296e66dfc9390cd3fd39d56baa66a6f70014e36a01304fcb3183f2c52ee3050
Pulling from library/hello-world
a3ed95caeb02: Pull complete
03f4658f8b78: Pull complete
Digest: sha256:d33937a324dbf3f8815dca035d5124aa81931bfb5c97559ff3a28827fdca4cb7
Status: Downloaded newer image for library/hello-world:latest
Tagging 10.117.4.142/library/hello-world@sha256:4296e66dfc9390cd3fd39d56baa66a6f70014e36a01304fcb3183f2c52ee3050 as 10.117.4.142/library/hello-world:1.0
Error response from daemon: vSphere Integrated Containers does not implement image.Tag
```

I didn't check the code of docker but seems the process of pulling a image when CONTENT TRUST is enabled is different.

**Comment by reasonerjt** [comment]
version info:

```
root@jt-dev:~# docker info|grep -i sphere
Storage Driver: vSphere Integrated Containers v0.8.0-7315-c8ac999 Backend Engine
vSphere Integrated Containers v0.8.0-7315-c8ac999 Backend Engine: RUNNING
ID: vSphere Integrated Containers
```

**Comment by mhagen-vmware** [comment]
@jzt Hey Zach, I think we are tracking this elsewhere - if so, please ref that story and close this.  Thanks!

**Comment by mhagen-vmware** [comment]
User statement:  As a customer of VIC I want to use VIC with notary, but VIC needs to support image.tag in order for me to be able to use it.

Details:  Probably needed for our other work including push/commit and compose work.

Acceptance criteria:
1. Design doc for image.tag implementation
2. image.tag works with notary
3. Test that verifies it works is included

**Comment by jzt** [comment]
I believe the docker client is doing most of the work here, in that it will prohibit you from pulling unsigned images if `DOCKER_CONTENT_TRUST` is set. If you do pull a signed image, it auto-tags it with your  In that case, all we would need to do is implement `image.TagImage` and the client would do the rest.

This is captured by #1120 - I'll close those and reference it there.

**Comment by jzt** [comment]
Closing as captured by #1120.
