### ISSUE TITLE
Clean up PXE folder on each of the nimbus tests

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3694]
User statement: As an engineer on VIC, I do not want to see nimbus failures because the PXE folder has become full and it has a small quota.

Detail:  Might be able to just put it in the existing nimbus cleanup keyword.

Acceptance criteria:
1. Each of the tests cleans up the pxe folder on the nimbus account after deploying any test VMs

**Comment by rajanashok** [comment]
Closing as this is already implemented and is functional as part of the test resources.
https://github.com/vmware/vic/blob/ff1db6e7a540ed614cba4ca97d4ed7f3b1f7fc68/tests/resources/Nimbus-Util.robot#L222
