### ISSUE TITLE
Update vic-machine to tell users to upgrade their CLI to 1.13

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3697]
As a VIC admin, I should be informed by vic-machine to upgrade to Docker CLI 1.13 or add DOCKER_API_VERSION=1.23 to my environment variables.

As a bonus, we can try to detect their current installed docker version.  However, that may not be crucial as the admin who install VIC may not be the user of VIC.  In the case where the admin is separate from the developer/dev-ops, the message should be informative enough for the admin to tell the end user.

**Comment by mhagen-vmware** [comment]
Acceptance criteria:
1. VIC recommends to user to upgrade to 1.13 when they run a docker command
2. Write an integration test to verify
3. Doc issue for Stuart created

**Comment by sflxn** [comment]
This won't solve the versioning issue.  Closing.
