### ISSUE TITLE
Re-work vmotion manual cases to not use kill * anymore 

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3699]
User statement: As an engineer on VIC, I want to be able to parallelize testing more, so it is important that any manual nimbus tests do not blow away VMs unrelated to their own test

Details: - need to utilize the list variable and cleanup only the vms associated with this test

Acceptance Criteria:
1. nimbus cleanup keyword no longer uses '*'

**Comment by rogeliosanchez** [comment]
Work for this has been done in #4208.

**Comment by mhagen-vmware** [comment]
LGTM
