### ISSUE TITLE
Docker API: Docker Inspect Container

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#370]
Implement the docker inspect operation (docker inspect from CLI) in the engine-api server and integrate with the interaction port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#inspect-a-container
https://docs.docker.com/engine/reference/commandline/inspect/

Please note, the engine-api's rest server already packaging these json struct into golang structs.  The url above is just for reference on what the operation should do.

**Comment by hickeng** [comment]
Portions of this are necessary for attach to work properly

**Comment by mdubya66** [comment]
@sflxn is this being worked on under another issue?

**Comment by sflxn** [comment]
It is. #1144.  I will close the other one as duplicate, as there is more info here.

**Comment by sflxn** [comment]
We now have a swagger definition, and I just updated it. I've implemented a first rev of container inspect on the personality server side. Until the portlayer returns those swagger definitions I created, container inspect is still blocked. I'm going to create some dummy code on the portlayer side to test with the personality server while I wait for @cgtexmex to populate those data fields.

Related to #1276

**Comment by sflxn** [comment]
I submitted a PR yesterday, but it shouldn't be merged until the portlayer side is done.  The PR will override the work that was done for the inspect for attach.  If this PR gets approved and merged without the portlayer side, attach will no longer work.

**Comment by cgtexmex** [comment]
@sflxn do we have a portlayer story regarding the data to return or the API that will return it?  I implemented the GetContainerListHandler for ps, but am not aware of another issue for the remaining data needed for inspect...
