### ISSUE TITLE
Feature request: NSX automation

### ISSUE THREAD

**Issue by flamby** [vmware/vic#3708]
Hi,

Use-case is to re-use tenant's existing NSX Edge and Logical Switches (VXLAN) for containerVMs.
As such, there is not NAT through VCH, but on the edge.

The goal is to have the minimum of specific arguments at the `docker run` command level. 
So notion of 
- default network (ideally like the behavior of containerVM connected to bridge network)
- automatic IP (à la vCloud Director 'IP Pool')
- public IP (edge secondary IPs) NAT / FW (different from DFW which is more suitable for E/W traffic)

**Comment by mdubya66** [comment]
This is good feedback. Adding to PM queue for prioritization in the future.

**Comment by mhagen-vmware** [comment]
This will need to be decomposed and needs PM feedback before we can pull into the backlog.

**Comment by renmaosheng** [comment]
the nsx-t epic will cover the discussion. closing this for now.
