### ISSUE TITLE
Test for relative accuracy in docker run tests

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3710]
In 1-06-Docker-Run:
Docker run verify container start and stop time

We should try and check additionally that we are at least within the ballpark of accuracy. See https://github.com/vmware/vic/pull/3690

I like it, but can we do a bit better? Something like:
containerStart-cmdStart <= 100 ( or something reasonably close, I don't know what the units here are - I would say it should be within 20 or 30 seconds )

maybe:
containerStop - cmdStart <= 60 or 70 seconds

**Comment by cgtexmex** [comment]
I'd still like to understand your definition of _accurracy_ --- that a command executes in less than _n_ seconds could show how vic responds to load on a system, but I don't believe it determines accuracy.

**Comment by mhagen-vmware** [comment]
If we assume that our "properly" configured NTP setup is accurate to within 1 second (as NTP should be when configured properly), and accounting for load and delays, I think that 1 minute would be fair, but I am not looking for super accuracy here, just that is in within the same ballpark (i.e. not an entire day off) so a reasonable bar to jump over should be 10 minutes.

**Comment by dougm** [comment]
Seen in: https://ci.vmware.run/vmware/vic/9229
