### ISSUE TITLE
Research the implication of Swarm coupling in 1.13 for VIC

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3712]
As a VIC user, if VIC supports docker 1.13 (API 1.25), I should expect no change in network usage from the version of VIC that supported API 1.23.

---

In the current docker code base, they have tied the networking code to Swarm at the REST API layer instead of the network backend.  Since we use the REST API layer as is, we are now forced to include the Swarm code.

We need to research what 1.13's Swarm integration in the network backend means for VIC.  If we integrate the Docker 1.13 code base, we will need to hook up the Swarm cluster manager and daemon backend in our personality server's setup code (main()).  These are new components for VIC, and we should not blindly hook them up without understanding what it implies.

**Comment by sflxn** [comment]
The API 1.25 PR passes all the networking integration tests.  My opinion is that it should justify closing this issue.

**Comment by hmahmood** [comment]
Closing this in lieu of #3756
