### ISSUE TITLE
Time is not syncing on the ESX servers in the CI

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3714]
Need to look into it, both the host ESX which is baremetal and the nested ESX are not syncing properly, they have at least a minute or more of drift while claiming to be synced.

**Comment by mlh78750** [comment]
if this is internal, the internal network doesn't allow outbound ntp. You'll need to use an time server on our network.

**Comment by mhagen-vmware** [comment]
well, there you go... :( I configured all the ESX servers to point to time.vmware.com but that is not accessible from OVH! Grrrr...

**Comment by mhagen-vmware** [comment]
On that note, ESX just happily took the time server info and never reported any issue!

**Comment by mhagen-vmware** [comment]
And immediately is synced once I changed the server.

**Comment by mhagen-vmware** [comment]
Fixed, by moving our ESX servers to a public time server
