### ISSUE TITLE
[v1.13] docker client hangs

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#3720]
running ``` docker run hello-world``` using 1.13 client ends up with a hung client.  The underlying VM starts and then powers off as expected. Tether, portlayer and personality logs shows no errors. Looking at the pporf output suggests that the client waits an event. Using v1.12 client works as expected.

**Comment by caglar10ur** [comment]
[logs.zip](https://github.com/vmware/vic/files/728360/logs.zip)

**Comment by caglar10ur** [comment]
This could be related with the API version piece as client seems to waiting docker events to arrive. Raising another one for documenting the fact that we don't support new client versions.

**Comment by mdubya66** [comment]
did hello world ever work? iirc we had problems all along with the default one.

**Comment by caglar10ur** [comment]
Yes, hello-world works fine with older clients

**Comment by stuclem** [comment]
Added proposed release note entry in https://github.com/vmware/vic/issues/3734.

**Comment by sflxn** [comment]
I've identified the new code that is causing the hang.  The 1.13 CLI changed the run code to now subscribe to events, which we have not yet implemented.  It's waiting on an event from the daemon that says the container died, detach, or destroyed.

The only way to fix this is to implement events subscription.

**Comment by stuclem** [comment]
Removing kind/note from this one as the RN update is being tracked in https://github.com/vmware/vic/issues/3734.

**Comment by sflxn** [comment]
#2252 for event subscription manager on portlayer side
#367 for event subscription on personality side

Acceptance criteria for events will be new docker command robot scripts for events.  Specifically, for docker run, we need to check for "die", "detach", and "destroy".

**Comment by mhagen-vmware** [comment]
lgtm
