### ISSUE TITLE
Fails with generic error when specifying wrong dns server

### ISSUE THREAD

**Issue by senk** [vmware/vic#3724]
**VIC version:**

master / 6305970d

**Deployment details:**

./vic-machine-darwin create \
--target vclab.vmware.fh-muenster.de \
--user 'Administrator@vsphere.local' \
--password '***' \
--bridge-network 'vch-bridge' \
--image-store 'VM_LAB_NFS01' \
--compute-resource 'Cl-Lab' \
--no-tlsverify \
--force \
--public-network 'dc-vm-lab' \
--public-network-ip '10.42.13.43/24' \
--public-network-gateway '10.42.13.1' \
--client-network 'dc-vm-lab' \
--management-network 'dc-vm-lab' \
--dns-server '194.93.10.10'

DNS IP is non-existent

**Steps to reproduce:**

Specify a wrong dns-server / non-existent DNS Server and try to deploy

**Actual behavior:**

INFO[2017-01-25T07:56:18+01:00] Checking VCH connectivity with vSphere target
WARN[2017-01-25T07:57:18+01:00] Could not run VCH vSphere API target check due to ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).

3016 is VIX_E_TOOLS_NOT_RUNNING

**Expected behavior:**

Error indicating something more specific like "Specified DNS Server not found" 

**Logs:**

**Additional details as necessary:**

**Comment by dougm** [comment]
Fixed in #5348
