### ISSUE TITLE
docker network create --internal does not work

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3736]
As a VIC and docker compose user, I should be able to create a network with the `--internal` flag.

Acceptance Criteria: Robot scripts that create a network with `--internal` and verify that containers connected to that network have restricted access to the external network.

---

**VIC version:**

0.8

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

bin/vic-machine-linux create --name=vch-3  --target=root:pwd@192.168.60.162 --thumbprint=.. --volume-store=datastore1/test:default --no-tlsverify --no-tls

**Steps to reproduce:**

docker -H ... network create --internal=true mynet

**Actual behavior:**
```
docker -H 192.168.60.133:2375 network inspect mynet
[
    {
        "Name": "mynet",
        "Id": "f777e23965ffd34e2fb51099dc9be9436076bc7ff844dc7dd3ae9db7d890534e",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```

**Expected behavior:**
"Internal": true

This is needed for the syntax "internal" in the docker-compose file. See https://github.com/vmware/vic/issues/3635#issuecomment-275496609

**Comment by sflxn** [comment]
This is all in the inspect code.
