### ISSUE TITLE
docker network --label is not supported

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3738]
**VIC version:**

0.8

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
bin/vic-machine-linux create --name=vch-3 --target=root:pwd@192.168.60.162 --thumbprint=... --volume-store=datastore1/test:default --no-tlsverify --no-tls

**Steps to reproduce:**
docker -H 192.168.60.130:2375 network create --label="aaa=bbb" test1

**Actual behavior:**
```
docker -H 192.168.60.130:2375 network inspect test1
[
    {
        "Name": "test1",
        "Id": "f02bfaf65276440d951f17d5a7a80747b0d8168ff3dfad7928901d2b04fd9025",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```
**Expected behavior:**
```
"Labels": {
            "aaa": "bbb"
        }
```

This is needed by the "label" syntax in the docker-compose file. See https://github.com/vmware/vic/issues/3635#issuecomment-275496609

**Comment by hmahmood** [comment]
This would be a new field in https://github.com/vmware/vic/blob/master/lib/portlayer/network/scope.go#L30

**Comment by mhagen-vmware** [comment]
lgtm
