### ISSUE TITLE
Docker API: Volumes Operation (Parent Issue)

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#374]
Implement all the volumes operations that VIC support in the engine-api server. Here are the list of image volumes and any issue number for them.

- [ ] #917 List volumes
- [ ] #915 Create a volume
- [ ] Inspect a volume
- [ ] #916 Remove a volume

**Comment by fdawg4l** [comment]
The first 3 are done.  The last one is TBD.  In any case, this is a dup of the issues mentioned.  Closing.
