### ISSUE TITLE
Docker API: Networks Operations (Parent Issue)

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#375]
Implement all the image operations that VIC support in the engine-api server. Here are the list of image operations and any issue number for them.

- [x] List networks
- [x] Inspect network
- [x] #111 Create a network
- [x] #703 Connect a container to a network
- [ ] Disconnect a container from a network
- [x] Remove a network

**Comment by mdubya66** [comment]
Closing, Tracked in other ways.
