### ISSUE TITLE
Implement the Containers tab of VIC object workspace

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#3752]
As a UI engineer I need to provide full implementation of the Containers tab detailed out in the mockup.

Details:
Mockup: https://vmware.invisionapp.com/share/DA9NSB8CE#/screens/210384819

Acceptance Criteria:

Fully functional Containers page as shown in the mockup

**Comment by mdubya66** [comment]
Fell below the cut line. Removing from 1.2

**Comment by jooskim** [comment]
@mdubya66 Wait, I thought I had my own stories to work on towards v1.2? Have you confirmed with @karthik-narayan ?

**Comment by jooskim** [comment]
Adjusting the estimate point from 5 to 3 because I realized that this feature depends a lot on backend code of #3751
