### ISSUE TITLE
Docker API: Container Export

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#376]
Implement container export operation (docker save in the CLI) in the engine-api server and integrate with the storage port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#export-a-container
https://docs.docker.com/engine/reference/commandline/save/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by mdubya66** [comment]
not a .next requirement
