### ISSUE TITLE
Document new VIC objects that appear in vSphere H5 client

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3760]
Per https://github.com/vmware/vic/issues/3748. See also the [mockup](https://vmware.invisionapp.com/share/DA9NSB8CE#/screens/210384795) by the UX team.

**Comment by jooskim** [comment]
Just so you know Stuart, this design doc is for internal consumption and reference by UI development. So the items you referenced here would not be exposed directly to the users but are critical building blocks for me. Aside from the design doc, I will need to create a user doc for which I will get back to you with more user-friendly terms and concepts.

**Comment by stuclem** [comment]
Will be covered by https://github.com/vmware/vic-product/issues/94. Don't think that we need this issue too.
