### ISSUE TITLE
Document that vic-machine validates bridge network range subnet mask

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3761]
Per https://github.com/vmware/vic/issues/3212, which is implemented in PR https://github.com/vmware/vic/pull/3746. Affects the entry on [bridge-network-range](https://vmware.github.io/vic-product/assets/files/html/0.8/vic_installation/vch_installer_options.html#bridge-range) in VCH Deployment Options and might be mentioned elsewhere.

This is for Sprint 1.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/3746 is merged.

**Comment by stuclem** [comment]
@andrewtchin if this bridge network range is now validated during deployment, is this troubleshooting topic now redundant?
https://vmware.github.io/vic-product/assets/files/html/0.8/vic_app_dev/ts_bridge_pool_mask_error.html

Thanks!

**Comment by stuclem** [comment]
Change is in https://github.com/vmware/vic/pull/4175/commits/a42b93791224c59481daabf5cd9f795b1f341e82

**Comment by andrewtchin** [comment]
I would say that the troubleshooting page is now redundant

**Comment by stuclem** [comment]
Removed in https://github.com/vmware/vic/pull/4196/commits/cb849d30f6707075b55286019857ed342fc4640f
