### ISSUE TITLE
vic-machine upgrade --rollback

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3765]
As vic admin, I want to upgrade my existing VCH endpoint VM to latest version. But after upgrade, if there is anything incompatible with my application, or script, I would like to roll back the previous upgrade, to make sure my workload is not impacted, and then I get some more time to update my script/application first.

And if there is any unexpected interrupt happens during upgrade, which make the upgrade stop failed and not roll back, this command should help me to roll back the VCH endpoint services. 

Limitation in this story: only one step roll back is supported.

**Comment by emlin** [comment]
Change to low cause this is not required in 0.9.0

**Comment by emlin** [comment]
back to high to make it done in next sprint

**Comment by gigawhitlocks** [comment]
![gif demos the above feature](https://github.com/gigawhitlocks/vic/blob/upgrade-rollback/2017-03-07T17:41:43.gif?raw=true)
