### ISSUE TITLE
vic-machine upgrade --resume

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3766]
As a vic admin, I would like to be able to resume my interrupted upgrade, which could be caused by unexpected VC connection broken. If the resumed upgrade is not success eventually, the old version of VCH endpoint API should be recovered.
So that I can still run my workload based on the VCH endpoind API.

**Comment by emlin** [comment]
@karthik-narayan @mdubya66 @hickeng @mhagen-vmware

**Comment by zjs** [comment]
Closing in favor of #6899.
