### ISSUE TITLE
enhancement for vic-machine network check

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3767]
This is reported from VMware{code} slack

VIC version: 0.8.0

**Deployment details:**
If without DVS, even if user want to deploy one single ESXi, vic-machine create still requires DVS for bridge network.

**Actual behavior:**
```
Jan 30 2017 13:52:34.780-05:00 ERROR An existing distributed port group must be specified for bridge network on vCenter: "vchPortGroup" is not a Distributed Port Group
Jan 30 2017 13:52:34.780-05:00 ERROR Create cannot continue: configuration validation failed
```
**Expected behavior:**
vic-machine create succeeds with standard vSwitch if deploy to ESXi host, which is managed in VC as one single host.

**Details**
marrotte [1:38 PM] 
that's a showstopper for me where I'm working on a legacy system where that's not an option
marrotte [1:39 PM] 
I can't mess with any of the pre-existing switching, I have to use the vSwitches and port group already defined by the standalone esxi servers

**Comment by emlin** [comment]
To fix this issue, we need to verify if the resource is for single host only. If that's the case, we follow the same assumption while we targeting one ESXi host

**Comment by marrotte** [comment]
True story!  Thanks for opening the issue Emlin.

**Comment by zjs** [comment]
Closing as this appears to be inactive and a niche request; it applies only to stand-alone ESXi hosts (i.e., not in a cluster) which are managed by VC, where the networking configuration can't be modified.

@marrotte, if this is still needed please reach out and we can re-open and prioritize.
