### ISSUE TITLE
container not connected to network after restarting the VCH vapp on vc

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3769]
**VIC version:**

0.8

**VC versoin.**

Same behavior on VC 6.0 and 6.5

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
```
bin/vic-machine-linux create --target=10.160.194.20 --user= --volume-store=datastore1/test:default --image-store=datastore1 --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password= --force=true --bridge-network=bridge --compute-resource=/ha-datacenter/host/10.160.2.172/Resources --public-network=vm-network --name=vch-1 --no-tlsverify --no-tls --debug 1
```
**Steps to reproduce:**
1. docker -H ... run -d -p 81:80 --name n1 nginx
2. docker inspect bridge
```
docker -H ... network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "14c6dd8b00491c4d6404349ce7121a2da2e8bdf4c8afdd406861a49919824219",
        ... ...
        "Containers": {
            "096d1076fe5920717548d4e032c0461ec3e4895e14e4b832d5f61495f209b56b": {
                "Name": "n1",
                "EndpointID": "096d1076fe5920717548d4e032c0461ec3e4895e14e4b832d5f61495f209b56b",
                "MacAddress": "",
                "IPv4Address": "172.16.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

3. on the vsphere web client, power off the VCH vapp and then power on the vapp.
4. After the task of "powering on the vapp" is completed and "docker ps" shows "n1" is running, do "docker network inspect bridge" again.

**Actual behavior:**
```
{
        "Name": "bridge",
        "Id": "f20f1d0604061c2fa35df216b40d5f177759a917beff327064d1f9a6b8fb7471",
        ... ...
        "Containers": {},
        ... ...
    }
```
So n1 is not on the bridge network anymore, which makes the nginx web page not accessible. However, "docker inspect n1" shows that n1 is still on the bridge network.

**Expected behavior:**
The container n1 still connects to the bridge network.

**Logs:**

[container-logs.zip](https://github.com/vmware/vic/files/740356/container-logs.zip)

This issue relates to #3137 and #3644 .

The same network behavior is observed if the container is created by "docker run -it busybox".

**Comment by hmahmood** [comment]
This appears to be a race on startup between the vch's network layer initializing it cache about the containers in the vApp, and the container changing its state. The vch initialization code (https://github.com/vmware/vic/blob/master/lib/portlayer/network/network.go#L146) assumes that the container vms' states don't change while that code is getting executed. This is not true here. 

This brings up the question of whether we should support restarting the vapp as a whole. @chengwang86 already verified that restarting _just_ the vch works. @hickeng @mdubya66

**Comment by chengwang86** [comment]
I couldn't reproduce this on my vc setup. Waiting for massimo's log bundle (if any) or whether he can reproduce it.

**Comment by chengwang86** [comment]
After I power on the vapp as a whole as mentioned above (both the VCH and the containers are running), if I manually restart only the VCH from the web client without bothering the containers, the containers would be working again. "docker network inspect bridge" shows all the containers as expected.

**Comment by andrewtchin** [comment]
We've moved away from vApp, closing.
https://github.com/vmware/vic-product/issues/1523
