### ISSUE TITLE
Docker API: Container Restart

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#377]
Implement container restart operation in the engine-api server and integrate with the exec port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#restart-a-container
https://docs.docker.com/engine/reference/commandline/restart/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by caglar10ur** [comment]
this is already in, closing
