### ISSUE TITLE
Allow configuration of bridge network range smaller than /16

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#3771]
As a user I would like to be able to use a bridge network smaller than /16 based on the value from `--bridge-network-range`.

See https://github.com/vmware/vic/pull/3746
Currently port layer uses default size of /16 so bridge network range must be at least /16. If the user inputs a network smaller than /16, propagate that through to the port layer in the bridge width.  

**Acceptance Criteria:**
Able to create VCH with `--bridge-network-range` smaller than /16. 
Add integration tests
Remove integration test added in #3746

**Comment by hmahmood** [comment]
@mdubya66 this really needs to be fixed for 1.3.1 as people are running into it frequently.
