### ISSUE TITLE
Update build instructions on our github page or update drone in our CI

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3773]
As a developer, I should be able to download a released version of drone and build VIC from the sources on github.

---
The version of drone we're using is old and no longer appears to be available on drone.io.  We're supposedly using one based on 0.4.2, but our version is different from the v0.4.2 tag from github.com/drone/drone and github.com/drone/drone-cli.  Our github page doesn't mention which version we use, and the link we provide is no longer accessible.  We should either make the version we're using available, find the actual sha that the binary is built from, or update our CI to use a newer version of drone.  Using a drone binary built from sources or pulling pre-built drone binaries using instructions on their website will not work.

**Comment by mhagen-vmware** [comment]
This issue is captured in more detailed stories within the epic that Jake has been working on.
