### ISSUE TITLE
Update vic-machine and portlayer to provide custom full OS names for the VCH and container VMs

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3775]
As the owner of VIC, I should be able to get reports on various metrics about the deployed base of VIC in the field for customers who opt into CEIP.
As a user of VIC, I should see a custom name for the VCH and container VMs created with VIC.

Acceptance criteria:  Robot scripts that verify the custom name of the VMs using govc.

---

Update the VIC toolbox to provide the OS full name for the VCH and container VMs.  Examples,

VCH - "Photon OS - VCH 0.9.0"
Container - "Photon OS - Pico 0.9.0"

**Comment by dougm** [comment]
Related to #3553 - both use the SetGuestInfo RPC to update the vmdb.

**Comment by mhagen-vmware** [comment]
Please add a priority and a user statement explaining what this gives us.

**Comment by mdubya66** [comment]
1.1 feature request

**Comment by sflxn** [comment]
Resolved with https://github.com/vmware/vic/pull/3774
