### ISSUE TITLE
Docker API: Container Kill

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#378]
Implement the docker kill operation (docker kill from CLI) in the engine-api server and integrate with the exec port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#kill-a-container
https://docs.docker.com/engine/reference/commandline/kill/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by hickeng** [comment]
depends on #1267

**Comment by corrieb** [comment]
George/Ben review: Polite stop is the more important piece. This is a second-order effect. Not high priority.

**Comment by mdubya66** [comment]
GA feature from SSOD

**Comment by dougm** [comment]
@jzt are you available to work on the API/PortLayer portion of this?  The tether/toolbox related work I'll be doing for #1268 will end up being used here to deliver the signals here.  The API work can be done in parallel.

**Comment by dougm** [comment]
Assigning this to @jzt for the API/PortLayer portion.  I'll be implementing the tether/toolbox portion in #1267 and will hook it into the PortLayer handler.

**Comment by mdubya66** [comment]
since @sflxn's remaining feature 854 was closed he is free to work on this with you @dougm

**Comment by dougm** [comment]
ok thanks @mdubya66

**Comment by sflxn** [comment]
Initial code is in, but it still needs the ContainerWait infrastructure to wait for the container to exit.  There is another way to perform the wait, but I don't think it's the way to go.  We can create a new swagger client, use a roundtripper that doesn't timeout and make the call to the portlayer wait till the container exits.  The call would become blocking.  We would also need to add a parameter to make the call non-blocking for non sigkill signals.  It's evident that waiting for ContainerWait is a much better choice.  ContainerWait is #384.
