### ISSUE TITLE
Re-run and update HA test

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3784]
As a customer of VIC, I want to know that HA operations on the VCH and containers has been tested and verified to work so that I can deploy my appliance and use VIC in an environment that HA could happen.

Acceptance Critera:
1. HA test is run and working and included in nightlies

**Comment by dougm** [comment]
The test needs to use a datastore that can be accessed by all hosts for VM HA to work.  But it looks like the test is using a host local datastore ("datastore1").
