### ISSUE TITLE
Docker API: Container Update

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#379]
Implement the docker update operation (docker update from CLI) in the engine-api server and integrate with the exec port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#update-a-container
https://docs.docker.com/engine/reference/commandline/update/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by mdubya66** [comment]
not a .next requirement
