### ISSUE TITLE
Acceptability of 1st party VIB for configuring firewall

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3801]
As a customer of VIC, I do not want to have to apply per ESX host firewall configuration.
As an enterprise customer I have strict processes for approving which VIBs may be deployed to hosts and appreciate alternative solutions

Using a VIB to configure firewall rules means:
* viadmin should confirm that ESX firewall rule update will be applied to cluster hosts
* viadmin will need to ensure that VIB is applied to all new hosts before they're added to the cluster (VUM, manual, or otherwise)

Question:
- [ ] is VIB based firewall config acceptable as the only solution?
- [ ] is there a specific customer segment for whom VIBs in general could/would be an issue?
- [ ] is there a specific customer segment for whom needing to add VIBs to new cluster hosts before hosts become viable VIC targets could/would be an issue?

Related: #3643

**Comment by andrewtchin** [comment]
I talked to a TMM and a SE and they believe VIBs are acceptable - customers can deploy them using VUM

**Comment by andrewtchin** [comment]
If there are customers who don't want to install a VIB they can enable the ruleset `remoteSerialPort` that's in the default firewall config, which opens all outbound TCP
If they want to open the VIC specific port only, the VIB is the only way to make it persist

**Comment by karthik-narayan** [comment]
While VIB based options are widely used by our customers, these are often subject to security certifications that take a lot of time. Having an alternate option to using VIBs is very important IMO.

**Comment by andrewtchin** [comment]
I think this can be closed since we're going to make the VIB and also will have a `vic-machine` option
