### ISSUE TITLE
Design Container Pause

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#381]
As a VIC user, I should be able to pause a running container.
As a docker compose user, I should be able to pause a running compose service.

---
Implement the docker pause operation (docker pause from CLI) in the engine-api server and integrate with the exec port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#pause-a-container
https://docs.docker.com/engine/reference/commandline/pause/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by mdubya66** [comment]
@hickeng please review and re-assign or icebox

**Comment by anchal-agrawal** [comment]
Moving to low priority as this is not in 1.1 scope.

**Comment by zjs** [comment]
Closing as this is unlikely to be addressed, except as a part of a comprehensive project (in which case a new issue can be created).
