### ISSUE TITLE
Update Vic-Machine Volume Store flag to handle NFS volume stores

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3810]
Vic-Machine will now need to distinguish between vsphere datastores and NFS servers as volume store targets. The new nfs targets will need a validation strategy as well as commented [here](https://github.com/vmware/vic/blob/master/doc/design/volumes/nfsvolumestores.md) to make sure that at VCH install time we can reach the intended target. 

This should not involve any major changes to the --volume-store flag. It should however require a change to how we parse the flag as well as a new distinction field for volume stores indicating the type that we need to be creating. Most of this work should occur in the `Storage Validator` and the `processVolumeStores` function located [here](https://github.com/vmware/vic/blob/84bf428e80da5e6bb61c82834fdc235240ac4d17/cmd/vic-machine/create/create.go#L867-L879). There will also need to be changes to the addVolumeStore functions which occur after validation. Some of this work will likely be contained in parts of the managment portion(dispatcher section) of vic-machine([here](https://github.com/vmware/vic/blob/84bf428e80da5e6bb61c82834fdc235240ac4d17/lib/install/management/create.go#L71-L73)) as well as a new pkg/nfs may need to be written for adding volume store directories to the nfs target before the VCH is installed similar to [this](https://github.com/vmware/vic/blob/84bf428e80da5e6bb61c82834fdc235240ac4d17/pkg/vsphere/datastore/datastore.go) vsphere pkg library.

**Comment by matthewavery** [comment]
For a possible validation approach, we can try and reach the target nfs server. If we cannot we can warn the user with some message like `Unable to validate nfs volume store target, advancing without validated nfs server (%q)`. Otherwise we could check that we can communicate with the server if it is reachable. Just a thought.

**Comment by fdawg4l** [comment]
That's a good start, but we need to think about how we're going to address mounting the target via the (container network)[https://github.com/vmware/vic/pull/3819].  Please see the text added to the spec and the conversation we're having in the PR.  The result will change what we need to modify in vic-machine.

**Comment by matthewavery** [comment]
Consider UID and GID.
