### ISSUE TITLE
NSX-v testbed setup for nightlies

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#3816]
As a QE working on automating the NSX install, I would like to first manually set this up and understand the OVFTool usage.

Acceptance criteria:
1. Have a manual NSX setup and working, so we understand the NSX configuration settings required during the test automation implementation.

**Comment by mhagen-vmware** [comment]
For the deliverable on this, can you please write up a quick test design doc like I did for kubernetes work?  And let's try to get this wrapped up today/tomorrow morning.

**Comment by rajanashok** [comment]
Sounds good, I am in the process of upgrading the govc to check if I can list the switches I created from NSX Manager. I will go ahead and create a design doc as soon as I am done with this.

**Comment by rajanashok** [comment]
Closing. Adding the test design doc for the NSX nightlies #3930

**Comment by mhagen-vmware** [comment]
Can't close until the doc is merged.

**Comment by rajanashok** [comment]
The merged test design doc is applicable to NSX-T, the customers in the real world use the vsphere NSX, also known as NSX-v. There is some work already done by Amanda Feng that we can use to leverage this. 
https://confluence.eng.vmware.com/pages/viewpage.action?pageId=209964551

**Comment by rajanashok** [comment]
Updated the NSX test steps on how to setup the environment in Nimbus, also robot test updated to run the NSX test.
https://github.com/vmware/vic/pull/4207
https://github.com/vmware/vic/pull/4188
