### ISSUE TITLE
Design Docker Unpause

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#382]
As a VIC user, I should be able to unpause a paused container.
As a docker compose user, I should be able to unpause a paused compose service.

---
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#unpause-a-container
https://docs.docker.com/engine/reference/commandline/unpause/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by anchal-agrawal** [comment]
Moving to low priority as this is not in 1.1 scope.

**Comment by zjs** [comment]
Closing as this is unlikely to be addressed, except as a part of a comprehensive project (in which case a new issue can be created).
