### ISSUE TITLE
Docker API: Container Wait

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#384]
Implement the docker wait operation in the engine-api server and integrate with interaction port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#wait-a-container
https://docs.docker.com/engine/reference/commandline/wait/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by mdubya66** [comment]
See also #1329. Assigning to @cgtexmex and @corrieb per @hickeng. Pulling this into GA as it is a limiting factor in our ability to test appropriately.

**Comment by sflxn** [comment]
When you guys get an idea on what this api looks like in the portlayer or utility function in the personality layer, can you post in #378?  Docker kill will need to use this mechanism to wait for the container to shutdown.

**Comment by anchal-agrawal** [comment]
Reopened because there's an integration test that needs to be updated: https://github.com/vmware/vic/blob/master/tests/test-cases/Group6-VIC-Machine/6-4-Create-Basic.robot#L22
