### ISSUE TITLE
Follow on: need to add HA to nightly still once the bug is addressed

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3846]
Could not completely finish #3784 since I am blocked on bug #3845 

This is a small follow on story to finish the deliverable on #3784 and include the test in the nightlies once the bug is fixed.

**Comment by corrieb** [comment]
Mike, it's not clear whether the test is testing for just High Availability of the appliance or also for HA of any running containerVMs. I'm conducting a review of requirements in #744 and I think we need a little clarity around requirements.

**Comment by mhagen-vmware** [comment]
this is done, HA is currently in nightlies now
