### ISSUE TITLE
Document support for volume ls filtering

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3849]
Per https://github.com/vmware/vic/issues/1718, which is implemented in PR https://github.com/vmware/vic/pull/3834.

**Comment by stuclem** [comment]
Fixed in PR https://github.com/vmware/vic/issues/3849, which is merged.

**Comment by anchal-agrawal** [comment]
@stuclem I'll be happy to provide a summary of this functionality for docs, please let me know when this ticket is in progress.

**Comment by stuclem** [comment]
Removed statement that `--filter` is not a supported option for `docker volume ls` in [Supported Docker Commands](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md).
