### ISSUE TITLE
Docker API: Copy files or folder

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#385]
Implement the docker wait operation in the engine-api server and integrate with interaction port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#copy-files-or-folders-from-a-container
https://docs.docker.com/engine/reference/commandline/cp/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by matthewavery** [comment]
I have picked this up for sprint 10. We will need further discussion on how we want to design the changes for this. For us it is ideal to get the docker persona endpoint in shape to stream the targeted data to the portlayer. The portlayer api design for `docker cp` is located here #4106 (that ticket will design and implement the target for this docker endpoint). in the past it has been discussed that if possible we should directly stream the data to the portlayer endpoint, from there what the portlayer does will be determined in the aforementioned ticket.

**Comment by matthewavery** [comment]
`name` must be validated as an existing container else a `404` needs to be returned. Verification that the `docker CLI` checks the path string or validation of the `path` string must also occur before communication to portlayer for a file operation occurs.

**Comment by matthewavery** [comment]
copy from container header:
`ContainerArchivePath(name string, path string) (content io.ReadCloser, stat *types.ContainerPathStat, err error)`

**Comment by matthewavery** [comment]
copy to container header: 
`ContainerExtractToDir(name, path string, noOverwriteDirNonDir bool, content io.Reader) error `

**Comment by sflxn** [comment]
Container copy will also need ContainerStatPath.

**Comment by sflxn** [comment]
Moved back to "to do" as there have been some big design changes to the way this works on the portlayer side that will affect the personality server.  Till it's clear what the changes are, I'm going to go help out on push till cp is completely figured out.
