### ISSUE TITLE
Doc: edit ts_docker_api_check_error.md 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3850]
@andrewtchin added doc/user_doc/vic_installation/ts_docker_api_check_error.md as part of https://github.com/vmware/vic/pull/3828. This needs an editorial review. Also, the issue exists in 0.8 but the error message was added in Sprint 1 for 0.9. So, I need to create two versions of the topic.

**Comment by stuclem** [comment]
I have edited the topic and created two versions, one for 0.8 and one for 0.next. 

0.8: https://github.com/vmware/vic/blob/08-docs/doc/user_doc/vic_installation/ts_docker_api_check_error.md 

0.next: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/ts_docker_api_check_error.md (pending merge in https://github.com/vmware/vic/issues/3894).

@andrewtchin can you please verify both versions?

Thanks!

**Comment by andrewtchin** [comment]
@stuclem 0.8 docs look good and approved #3894
