### ISSUE TITLE
Document how to combine vendor supplied server certificate and self-generated Docker client certificates

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3851]
Comments from @hickeng in https://github.com/vmware/vic/issues/3745 could serve as a useful example in the docs.

**Comment by stuclem** [comment]
#3745 is implemented in PR https://github.com/vmware/vic/pull/4068.

**Comment by andrewtchin** [comment]
For the user to supply their own certificate that will be used on the VCH to serve the Docker API and VCH administration web interface (I don't know what the official name for vicadmin is now), they should supply `--key` and `--cert` for the key PEM and cert PEM files respectively. The provided certificate may be signed by a CA that is trusted by the system running the `vic-machine` installer and by users of the VCH that is being created. If the supplied certificate is signed by a CA that is not trusted by the system, the installer will not be able to validate the certificate chain and `vic-machine create` output will contain a warning similar to: 
```
Server certificate hostname doesn't match: x509: cannot validate certificate for 10.17.109.182 because it doesn't contain any IP SANs
```
The user should specify the `--tls-cname` value to match the common name specified in the provided server certificate.
With the above options specified, the installer will generate self signed certificates for Docker client authentication. 

George should also review the PR you put up for the docs :-)

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/4068 is merged. Thanks for the write-up, @andrewtchin !

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#44
