### ISSUE TITLE
Docker API: Container Stats

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#386]
Implement the docker stats operation in the engine-api server and integrate with interaction port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#get-container-stats-based-on-resource-usage
https://docs.docker.com/engine/reference/commandline/stats/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

As a developer on admiral, I need VIC to implement container stats in order for admiral to work properly with VIC.

**Comment by mdubya66** [comment]
Required by Admiral

**Comment by mdubya66** [comment]
Moving into 1.0 timeframe. target v0.10.0 for now

**Comment by cgtexmex** [comment]
Partially completed with #4413 -- will open a new issue for remaining stats
