### ISSUE TITLE
Clarify doc for datastore cluster support 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3861]
Per https://github.com/vmware/vic/issues/2729#issuecomment-273323188.

**Comment by stuclem** [comment]
Updated https://github.com/stuclem/vic/blob/08-docs/doc/user_doc/vic_admin/interop.md as follows:

- vSphere Storage DRS&trade;: You cannot configure VCHs to use Storage DRS datastore clusters. However, you can specify the path to a specific datastore within a Storage DRS datastore clusters by specifying the full inventory path to the datastore in the `vic-machine create --image-store` option. For example, `--image-store /dc1/datastore/my-storage-pod/datastore1`.

Change is in https://github.com/vmware/vic/pull/3947/commits/4140359b865577ea52ee47b4a8e7dc95e46d5f21.

@dougm is this OK for 0.8? Thanks!

**Comment by dougm** [comment]
@stuclem yes that's fine.  The path can also be relative to the Datacenter's datastore folder: `my-storage-pod/datastore1`.

**Comment by stuclem** [comment]
Thanks @dougm. Added this detail in https://github.com/vmware/vic/pull/3947/commits/b03793d4328b2582cbf7e1b362a2fc2eab465939. Think it's safe to close this one.
