### ISSUE TITLE
Failed to write to image store / http: panic serving <ip:port> runtime error: invalid memory address or nil pointer dereference when pulling docker image

### ISSUE THREAD

**Issue by mark49808** [vmware/vic#3868]
Running VIC GA, trying to pull docker image of any significant size

root@hostname:~# docker -l debug  -H IP:2376 --tls pull mysql
Using default tag: latest
Pulling from library/mysql
5040bd298390: Already exists
a3ed95caeb02: Pull complete
55370df68315: Pull complete
fad5195d69cc: Pull complete
a1034a5fbbfc: Extracting [==================================================>]    114 B/114 B
17f3570b42ae: Download complete
6bf4b16e5339: Download complete
9700c9731729: Download complete
f2fea9c5b632: Download complete
2f8101f5336d: Download complete
0dc8f8a1031a: Download complete
a1b9627588c7: Download complete
Failed to write to image store: Post http://127.0.0.1:2377/storage/42110c2c-b135-9684-da61-3c048bc6741b?image_id=cdffeafa2fc29fe77b2d2160c9aa6afec302ec8c8aad809e519a0c82082bd2d0&metadatakey=metaData&metadataval=%7B%22id%22%3A%22cdffeafa2fc29fe77b2d2160c9aa6afec302ec8c8aad809e519a0c82082bd2d0%22%2C%22parent%22%3A%22c91cff46a946e10efe9b4ae882a8165881cd65920ecaca79b4a8c8bb576970ca%22%2C%22created%22%3A%222017-01-17T17%3A16%3A36.095838769Z%22%2C%22container_config%22%3A%7B%22Cmd%22%3A%5B%22%2Fbin%2Fsh+-c+mkdir+%2Fdocker-entrypoint-initdb.d%22%5D%7D%7D&parent_id=c91cff46a946e10efe9b4ae882a8165881cd65920ecaca79b4a8c8bb576970ca&sum=sha256%3Aa1034a5fbbfc91073603066f2801c0705ed3b2ac81976f560b4854a5a1262f29: read tcp 127.0.0.1:57586->127.0.0.1:2377: read: connection reset by peer

**Details:**
Attaching port-layer log. 
[port-layer - redacted.txt](https://github.com/vmware/vic/files/758258/port-layer.-.redacted.txt)

```
time=2017-02-03T18:40:00.387416003Z level=debug msg=op=250.206 (delta:38.982µs): Getting image 462d7794600a87463c4e2f905b4e026c6267da74aa906a75254611b919f35c3b from http://VCHtest/storage/images/42110c2c-b135-9684-da61-3c048bc6741b 
time=2017-02-03T18:40:00.387486147Z level=debug msg=op=250.206 (delta:108.956µs): Getting image 47b860004a0c5ad9434d93b93f69309057c1e532835256c2426ad02786791e0d from http://VCHtest/storage/images/42110c2c-b135-9684-da61-3c048bc6741b 
time=2017-02-03T18:40:00.387537976Z level=debug msg=op=250.206 (delta:160.974µs): Image 47b860004a0c5ad9434d93b93f69309057c1e532835256c2426ad02786791e0d not in cache, retreiving from datastore 
time=2017-02-03T18:40:00.387565933Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/storage/vsphere.(*ImageStore).GetImage:445] http://VCHtest/storage/images/42110c2c-b135-9684-da61-3c048bc6741b 
time=2017-02-03T18:40:00.421307222Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/storage/vsphere.(*ImageStore).GetImage:445] [33.737813ms] http://VCHtest/storage/images/42110c2c-b135-9684-da61-3c048bc6741b 
time="2017-02-03T18:40:00Z" level=info msg="Saving parent map (42110c2c-b135-9684-da61-3c048bc6741b/parentMap)" 
time="2017-02-03T18:40:00Z" level=info msg="Moving [TEST-VMFS02] VCHtest/VIC/42110c2c-b135-9684-da61-3c048bc6741b/parentMap.tmp to [TEST-VMFS02] VCHtest/VIC/42110c2c-b135-9684-da61-3c048bc6741b/parentMap" 
2017/02/03 18:40:00 http: panic serving IP:58380: runtime error: invalid memory address or nil pointer dereference
goroutine 66053 [running]:
net/http.(*conn).serve.func1(0xc4209eb580)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xec2640, 0xc420010050)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.(*taskCallback).fn(0xc4205d73c0, 0x0, 0x0, 0x0, 0xc4205d77e0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:74 +0x29f
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.(*taskCallback).(github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.fn)-fm(0x0, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:121 +0x48
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.Wait.func1(0xc420a75b48, 0x4, 0xc420a75b60, 0xa, 0x0, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:69 +0x43
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.waitLoop(0x1ac0520, 0xc4207b6a40, 0xc420707d10, 0xc420c28e68, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:142 +0x1e5
github.com/vmware/vic/vendor/github.com/vmware/govmomi/property.Wait(0x1ac0520, 0xc4207b6a40, 0xc420c28fd8, 0xc420a751b0, 0x4, 0xc420a751d0, 0xa, 0xc420a75200, 0x1, 0x1, ...)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/property/wait.go:70 +0x30a
github.com/vmware/vic/vendor/github.com/vmware/govmomi/task.Wait(0x1ac0520, 0xc4207b6a40, 0xc420a751b0, 0x4, 0xc420a751d0, 0xa, 0xc420c28fd8, 0x0, 0x0, 0x0, ...)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/task/wait.go:121 +0x152
github.com/vmware/vic/vendor/github.com/vmware/govmomi/object.(*Task).WaitForResult(0xc4209a61c0, 0x1ac0520, 0xc4207b6a40, 0x0, 0x0, 0x0, 0x1, 0xc42062f090)
	/drone/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/object/task.go:52 +0x135
github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult(0x1ac0520, 0xc4207b6a40, 0xc420c29258, 0xc420c291f8, 0x2, 0x2)
	/drone/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:67 +0x2ca
github.com/vmware/vic/pkg/vsphere/tasks.Wait(0x1ac0520, 0xc4207b6a40, 0xc420c29258, 0x2, 0x2)
	/drone/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:49 +0x3f
github.com/vmware/vic/pkg/vsphere/datastore.(*Helper).Mv(0xc420297d10, 0x1ac0520, 0xc4207b6a40, 0xc4207b6880, 0x32, 0xc4203a1b30, 0x2e, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/pkg/vsphere/datastore/datastore.go:239 +0x317
github.com/vmware/vic/lib/portlayer/storage/vsphere.(*parentM).Save(0xc4203a1ad0, 0x1abee60, 0xc4203a0c30, 0xc420853980, 0x1, 0x1, 0xc42074f050, 0x7, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/portlayer/storage/vsphere/parent.go:110 +0x4e3
github.com/vmware/vic/lib/portlayer/storage/vsphere.(*ImageStore).WriteImage(0xc4202d0200, 0x1abee60, 0xc4203a0c30, 0xc420853980, 0x1, 0x1, 0xc42074f050, 0x7, 0xc4203a0cf0, 0xc4209def3c, ...)
	/drone/src/github.com/vmware/vic/lib/portlayer/storage/vsphere/image.go:249 +0x16f
github.com/vmware/vic/lib/portlayer/storage.(*NameLookupCache).WriteImage(0xc4202d0240, 0x1abee60, 0xc4203a0c30, 0xc420853980, 0x1, 0x1, 0xc42074f050, 0x7, 0xc420c297c8, 0xc4209def3c, ...)
	/drone/src/github.com/vmware/vic/lib/portlayer/storage/image_cache.go:218 +0x1f3
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).WriteImage(0xc420445450, 0xc420b19860, 0x1abc0e0, 0xc420853840, 0xc4209def3c, 0x40, 0xc42074efc0, 0xc42074efd0, 0xc4209df163, 0x40, ...)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go:277 +0x3dc
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).WriteImage-fm(0xc420b19860, 0x1abc0e0, 0xc420853840, 0xc4209def3c, 0x40, 0xc42074efc0, 0xc42074efd0, 0xc4209df163, 0x40, 0xc4209def0e, ...)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go:107 +0x65
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage.WriteImageHandlerFunc.Handle(0xc42085b610, 0xc420b19860, 0x1abc0e0, 0xc420853840, 0xc4209def3c, 0x40, 0xc42074efc0, 0xc42074efd0, 0xc4209df163, 0x40, ...)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage/write_image.go:17 +0x59
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage.(*WriteImage).ServeHTTP(0xc4208432c0, 0x1abe220, 0xc420f9add0, 0xc420b19860)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/storage/write_image.go:51 +0x276
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1abe220, 0xc420f9add0, 0xc420b19860)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc42085bc30, 0x1abe220, 0xc420f9add0, 0xc420b19860)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1abe220, 0xc420f9add0, 0xc420b19860)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc4205cd700, 0x1abe220, 0xc420f9add0, 0xc420b19860)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1abe220, 0xc420f9add0, 0xc420b19860)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc42050ebe0, 0x1abe220, 0xc420f9add0, 0xc420b19860)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc42024ee00, 0x1abe220, 0xc420f9add0, 0xc420b19860)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4209eb580, 0x1abeda0, 0xc420b33440)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

Reproducable always. Tried recreating VCH VM from scratch. Same problem. I cannot reliably pull a docker image. Always happens during the extract. Plenty of storage available.  No network issues otherwise.

**Comment by mhagen-vmware** [comment]
@mark49808 It is unclear from your comments, does this only happen with larger images? Does it work for you with smaller images like busybox?

Also, thanks for attaching the port layer log, but would it be possible to attach a full log bundle downloaded from vic admin portal?

**Comment by mhagen-vmware** [comment]
@mark49808 Also, what kind of storage are you backing this with?

**Comment by mark49808** [comment]
It seems to happen more often on larger images, nearly 100% of the time. If i retry enough times it eventually works (10 failures to get mysql to work) . Smaller images like Busybox it rarely, if ever happens on. I will add the full log bundle

Storage is a iscsi Nimble array, fully used in production without issues. 


[logs (1).zip](https://github.com/vmware/vic/files/758374/logs.1.zip)
[container-logs.zip](https://github.com/vmware/vic/files/758375/container-logs.zip)

**Comment by caglar10ur** [comment]
@mark49808 I identified and fixed couple of issues on VIC side but the underlying cause still unknown to me. There is a gap in the logs so wondering whether you deployed the VCH on Feb 3rd and then reported the bug on 7th? If so do you mind repeating the same exercise again and providing another log bundle? The timing gap resulted hostd logs to be rotated by ESXi and without them we have no real way to see what went wrong.

**Comment by mark49808** [comment]
Sure, i'll redo and post logs. Thanks for your attention to this matter.

**Comment by mark49808** [comment]
Attached are log files from a newly-deployed VCH
[container-logs (3).zip](https://github.com/vmware/vic/files/781541/container-logs.3.zip)
[logs (3).zip](https://github.com/vmware/vic/files/781540/logs.3.zip)

**Comment by caglar10ur** [comment]
Perfect, thank you so much @mark49808 will update you as soon as I find something

**Comment by caglar10ur** [comment]
couple of questions @mark49808 

1. Are there multiple VCH installations in that environment?
2. If so are they sharing anything?
3. Would you mind sharing your vic-machine command line arguments? (after removing password or other sensitive information)
4. Would you be able to try a custom build? I can create a custom one for you to test which solves the above panic

**Comment by mark49808** [comment]
1. Yes, but only because I was attempting to troubleshoot this issue. It occurs when there is only 1. The others exist only because I wanted to start fresh and see if that eliminated the issue. It did not.

2. Sharing esx hosts and back-end storage, networks, etc. But again, removing the other instances does not change the behavior. 

3. Here it is with some things generalized:
/vic-machine-linux create --no-tlsverify --target 'myvcenter/mydatacenter' --user 'domain\user' --password 'redacted' --name VCHtest --compute-resource cluster-test --image-store vmfs/VCHtest --bridge-network dvPortGroup-internal --force --public-network 133 --client-network 133 --management-network 133 --insecure-registry <ip> --volume-store vmfs/vchtest-vs:default

4. Yes.

**Comment by caglar10ur** [comment]
@mark49808 would you mind trying https://storage.googleapis.com/experimental-vic-builds/3afc753.tar.gz when you have a chance? Please note this is an experimental build from the latest revision of the code (+govmomi fixes) for you to test. It supposed to solve the panic that you are observing but since this is an experimental build there could be other issues. I tried deploying it to a vCenter cluster with 3 ESXi hosts that uses vSan and pulled ubuntu and tomcat images before giving it to you.

```
# docker pull ubuntu
Using default tag: latest
Pulling from library/ubuntu
8aec416115fd: Pull complete
695f074e24e3: Pull complete
946d6c48c2a7: Pull complete
bc7277e579f0: Pull complete
2508cbcde94b: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:0c01b5105fc57b5eb8b7bb1d697b9dc5602022f69a0a33bf282b117e7a754a91
Status: Downloaded newer image for library/ubuntu:latest

# docker pull tomcat
Using default tag: latest
Pulling from library/tomcat
5040bd298390: Pull complete
a3ed95caeb02: Pull complete
fce5728aad85: Pull complete
c42794440453: Pull complete
9789263043d1: Pull complete
6c6ea13aad15: Pull complete
55336e5423a8: Pull complete
228d33a53bdd: Pull complete
3a1cfabb401c: Pull complete
b5f79327b275: Pull complete
bcbb902619eb: Pull complete
ad3d36b3fbaa: Pull complete
Digest: sha256:c3a1781843b319547da95c02c3d4c5a428059702fe17d01005093f4dd4f1b87c
Status: Downloaded newer image for library/tomcat:latest
```

**Comment by mark49808** [comment]
That seems to work better. I cannot reproduce the panic after many tries. Unfortunately I'm not unable to connect this VCH via Admiral. I get the following error:

Error connecting to 10.12.133.15:2376 : Service https://10.12.133.15:2376/v1.19/_ping returned error 400 for GET. id 8539

client version 1.19 is too old. Minimum supported API version is 1.23, please upgrade your client to a newer version

I'm guessing i'm off any supported path here.

**Comment by mdubya66** [comment]
@mark49808 what version of VIC Engine did you use? What version of Admiral?

**Comment by mdubya66** [comment]
ah, you used the build caglar gave you :). We've rev'd the API to 1.25 (1.13 Docker) in our latest engine code. It looks like Admiral is using Docker 1.9. We'll need to dig into this.

**Comment by mdubya66** [comment]
I was just able to deploy the admiral container (buildNumber 0.9.2 (183)) to my VCH (v0.8.0-8080-9aa14fc) and then use it to deploy an ubuntu container from it to the same VCH. So, something else may be going on. 

```(mwilliamson) ib-aus-office-96:~/Downloads/vic $  docker -H 172.16.127.204:2376 --tls version
Client:
 Version:      1.13.1
 API version:  1.24 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      0.8.0
 API version:  1.25 (minimum version )
 Go version:   go1.7.5
 Git commit:   9aa14fc
 Built:        Fri Feb 17 23:43:14 2017
 OS/Arch:      linux/amd64
 Experimental: true

(mwilliamson) ib-aus-office-96:~/Downloads/vic $  docker -H 172.16.127.204:2376 --tls ps -a
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                           NAMES
d00fdde5c825        library/ubuntu:latest   "/bin/bash"         5 minutes ago       Up 5 minutes                                        ubuntu-mcm27_36279842924
3a0d26c65191        vmware/admiral          "/entrypoint.sh"    8 minutes ago       Up 8 minutes        172.16.127.204:8282->8282/tcp   admiral```

**Comment by caglar10ur** [comment]
@mark49808 what about the original issue? Did you managed to pull images with no problem? If not, do you mind trying docker client to pull images that you were pulling before (like tomcat, nginx etc.)

**Comment by mark49808** [comment]
Yes as mentioned in my response above it works fine now. "That seems to work better. I cannot reproduce the panic after many tries"

**Comment by mark49808** [comment]
@mdubya66 are you running caglar10ur's build?  With it I can deploy admiral just fine, but trying to manage the VCH with it yields the error in the attached screenshot.

Server:
 Version:      0.8.0
 API version:  1.25
 Go version:   go1.8
 Git commit:   3afc753
 Built:        Wed Feb 22 17:43:40 2017
 OS/Arch:      linux/amd64
 Experimental: true

![image](https://cloud.githubusercontent.com/assets/25615777/23304998/3fc9891e-fa62-11e6-9a7e-099aaabb2424.png)

**Comment by mdubya66** [comment]
I was not. I was using Build 8158 from https://bintray.com/vmware/vic-repo/build. I'll try again once we get a build with Caglar's fix.

**Comment by caglar10ur** [comment]
@mark49808 @mdubya66 the changes are in the repo. I will also try admiral to make sure master is OK and if not will create an issue to track it
