### ISSUE TITLE
Docker API: Images List

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#387]
Implement the docker images operation in the engine-api server and integrate with storage port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#list-images
https://docs.docker.com/engine/reference/commandline/images/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by jzt** [comment]
This issue will be on hold until the port layer is updated to provide more data to populate the image structs that we provide back to the caller. Specifically, creation time and size. cc @fdawg4l 

It may also rely on the metadata component, so I'm cc'ing @cgtexmex too.

**Comment by sflxn** [comment]
https://github.com/docker/docker/blob/master/image/spec/v1.md

**Comment by jzt** [comment]
The v1 metadata of an image is defined by [this interface](https://github.com/docker/docker/blob/07f580489908bf6a3373daac1473045406e1130d/image/image.go#L21), of which the [`Size`](https://github.com/docker/docker/blob/07f580489908bf6a3373daac1473045406e1130d/image/image.go#L44) member is defined as being `the total size of the image including all layers it is composed of`. We need to track that running total when we write size metadata for an image, as we currently are not doing so:

`docker images -a` using the docker backend with only `library/tomcat` pulled:

```
vagrant@vagrant:~/go/src/github.com/vmware/vic$ docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
tomcat              latest              4b841eee8613        9 days ago          357.3 MB
<none>              <none>              b03113766210        9 days ago          357.3 MB
<none>              <none>              144cc457ebd7        9 days ago          357.3 MB
<none>              <none>              a725617cbc90        9 days ago          344.2 MB
<none>              <none>              daa283ff188d        9 days ago          344.2 MB
<none>              <none>              4cd64b60fdc9        10 days ago         344.2 MB
<none>              <none>              4242b893da9f        10 days ago         344.2 MB
<none>              <none>              c742cd313dd7        10 days ago         344.1 MB
<none>              <none>              020991c79298        10 days ago         344.1 MB
<none>              <none>              f9989a3fd068        10 days ago         344.1 MB
<none>              <none>              5f20fd3dd28c        10 days ago         344.1 MB
<none>              <none>              63db1d3e3c2a        11 days ago         344.1 MB
<none>              <none>              2b19c26dffa8        11 days ago         170.5 MB
<none>              <none>              60aa2c08d599        11 days ago         170.5 MB
<none>              <none>              aa12b2ef318b        11 days ago         170.5 MB
<none>              <none>              d792bfd7ef56        11 days ago         170.5 MB
<none>              <none>              01c48606610e        11 days ago         170.5 MB
<none>              <none>              e37211b690fb        11 days ago         170.5 MB
<none>              <none>              004814f54a9a        11 days ago         169.3 MB
<none>              <none>              32f2a4cccab8        11 days ago         125.1 MB
<none>              <none>              70e9a6907f10        11 days ago         125.1 MB
```

It appears that some v1 metadata being written on the portlayer storage side is either omitting the `Size` attribute altogether (causing it to default to 0 when unmarshaled into a [`V1Image`](https://github.com/docker/docker/blob/07f580489908bf6a3373daac1473045406e1130d/image/image.go#L21) struct), or writing it as `0` when it should not be:

`docker images` using the vic backend with only `library/tomcat` pulled:

```
vagrant@vagrant:~/go/src/github.com/vmware/vic$ DOCKER_HOST=tcp://localhost:2376 docker --tls --tlscert='cert.pem' --tlskey='key.pem' images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
REPO_NAME           TEST_TAG            a82a7c0a1277        9 days ago          0 B
REPO_NAME           TEST_TAG            9d8bd2efff01        11 days ago         44.28 MB
REPO_NAME           TEST_TAG            eded8b202a86        10 days ago         0 B
REPO_NAME           TEST_TAG            cb95d7424123        10 days ago         0 B
REPO_NAME           TEST_TAG            2726f048959c        11 days ago         0 B
REPO_NAME           TEST_TAG            59cdc0d67b30        11 days ago         0 B
REPO_NAME           TEST_TAG            ebdf1ae79215        11 days ago         173.6 MB
REPO_NAME           TEST_TAG            c9620fa9c974        10 days ago         0 B
REPO_NAME           TEST_TAG            8e31ca71fb03        9 days ago          0 B
REPO_NAME           TEST_TAG            d1cc0e6af849        11 days ago         0 B
REPO_NAME           TEST_TAG            ebf89852e971        11 days ago         1.172 MB
REPO_NAME           TEST_TAG            5af4d14f9deb        11 days ago         0 B
REPO_NAME           TEST_TAG            5d7b142af910        10 days ago         0 B
REPO_NAME           TEST_TAG            ec1691f8cf2d        9 days ago          0 B
REPO_NAME           TEST_TAG            430e8c6b6fad        9 days ago          0 B
REPO_NAME           TEST_TAG            6b8a1ecb2364        11 days ago         125.1 MB
REPO_NAME           TEST_TAG            dc6e39d71018        10 days ago         0 B
REPO_NAME           TEST_TAG            c413c2479409        9 days ago          13.1 MB
REPO_NAME           TEST_TAG            39663c8c9e8b        11 days ago         87 B
REPO_NAME           TEST_TAG            09e45f1c837d        11 days ago         0 B
REPO_NAME           TEST_TAG            ef6492bc5ac5        10 days ago         114.3 kB
```

cc @fdawg4l

**Comment by jzt** [comment]
The output of `docker images` should be sorted on `CREATED` from most recent to least recent.

**Comment by caglar10ur** [comment]
We also realized docker and vic are showing different ids for the same layer, further investigation showed that docker uses a chain id (instead of jst using that layers id). https://github.com/docker/docker/blob/4a7bd7eaef0038b006cf23adface84081e5aab3b/layer/layer.go#L82

So we should be doing the same so that we can be consistent between systems. One question is who needs to do that. imagec during WriteImage phase or docker personality while creating/tagging etc.

**Comment by jzt** [comment]
TODO:
- [ ] make image IDs consistent with Docker
- [ ] implement repo tags and digests once metadata component is available
- [ ] implement some or all of -a and --dangling=true, --filters and -q

**Comment by jzt** [comment]
This issue is currently paused while we flesh out #498. I am adding tests around it now in the meantime.

**Comment by jzt** [comment]
Now that we are targeting docker 1.11, this no longer works. I suspect it's because we are using vendored docker code from < 1.11. Looking into this.

**Comment by cgtexmex** [comment]
The issue in 1.11 is caused by a hardcoded value in the convertV1ImageToDockerImage function of the following file:

https://github.com/vmware/vic/blob/master/apiservers/engine/backends/image.go

The < & > are illegal characters for the RepoTags and cause the client to abort.
