### ISSUE TITLE
Docker API: Image Inspect

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#388]
Implement the docker images operation in the engine-api server and integrate with storage port layer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#inspect-an-image
https://docs.docker.com/engine/reference/commandline/inspect/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by sflxn** [comment]
This operation was part of docker attach so it had to be implemented.  Currently, we are just returning a cached version of the metadata that is a union of the metadata we get from docker and the metadata overrides from the CLI during docker create.

We are not yet going to the portlayer to rebuild that data.  This is a pass we must address to make it more robust.  We also need to update this metadata with events (docker events, vch events, etc).  That will come later.

**Comment by hickeng** [comment]
@sflxn please open an additional issue for the reconstruction from portlayer - there is an entire milestone for dealing with appliance restart as it has impact across the entire codebase.

**Comment by sflxn** [comment]
I am splitting this task into two task.  One for Inspect Image and one for Inspect Container.  Container Inspect relies on portlayer work that involves @cgtexmex.

**Comment by sflxn** [comment]
This is done.  PR and waiting for comments.
