### ISSUE TITLE
Check arguments are valid before installing

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#390]
The installer currently takes the arguments and passes them through to the VCH components without validation. The only portions that are validated are those that are used as part of the install itself.

The installer should validate that the values supplied for arguments are correct prior to embarking on actual installation tasks.

This is a short term item, however it could significantly reduce the incidence of people installing with invalid args and then seeing the VCH break as a result.

**Comment by emlin** [comment]
Move back cause this should be done after installer refactory

**Comment by hickeng** [comment]
assigning to emma as milestone lead - this can be reassigned to a specific person when it moves to in progress
