### ISSUE TITLE
Install and configure Harbor

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#3900]
User statement: Install and configure Harbor to investigate current Identity/User Management features.

Detail: Harbor is a component in the VIC product. Long term goal of this Epic is to integrate the Identity/User Management infrastructure for Harbor and Admiral. The first step is to get Harbor up and running to investigate its Identity/User Management features.

Acceptance criteria:
Harbor should be successfully installed and configured. A few basic commands should be executed against it. Documentation of specific issues encountered during the installation/configuration is required. When necessary issues should be opened against Harbor.

**Comment by rajanashok** [comment]
@lcastellano not sure what needs to be verified here, can you please update the issue with more details so I can close this? thanks.

**Comment by lcastellano** [comment]
Admiral has been installed and configured. During this activity we noticed that Admiral and LW have port conflicts on 443. Activity to resolve the port conflict is still on going.

Notes about this activity.

https://onevmw-my.sharepoint.com/personal/lcastellano_vmware_com/_layouts/15/guestaccess.aspx?guestaccesstoken=8nLl2QRpcnDX0SAwC4BAMjed%2fsxOm6GYQtQkfOqJJjU%3d&docid=2_164c7235aa2a543a2860aa22375e87205&rev=1

**Comment by rajanashok** [comment]
Thanks @lcastellano, closing this.
