### ISSUE TITLE
Admiral installation and configuration

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#3901]
User statement: Install and configure Admiral to investigate current Identity/User Management features.

Detail: Admiral is a component in the VIC product. Long term goal of this Epic is to integrate the Identity/User Management infrastructure for Harbor and Admiral. The first step is to get Admiral up and running to investigate its Identity/User Management features.

Acceptance criteria:
Admiral should be successfully installed and configured. A few basic commands should be executed against it. Documentation of specific issues encountered during the installation/configuration is required. When necessary issues should be opened against Admiral.

**Comment by lcastellano** [comment]
Admiral has been installed and configured. 

Notes about this activity.

https://onevmw-my.sharepoint.com/personal/lcastellano_vmware_com/_layouts/15/guestaccess.aspx?guestaccesstoken=8nLl2QRpcnDX0SAwC4BAMjed%2fsxOm6GYQtQkfOqJJjU%3d&docid=2_164c7235aa2a543a2860aa22375e87205&rev=1

**Comment by mhagen-vmware** [comment]
assignee?  milestone?  I assume @lcastellano is the assignee and should this be in the current sprint?

**Comment by mdubya66** [comment]
this should fall under the authz and authn Epic for 1.2. once we have agreement on approach from the admiral team we can start development.

**Comment by mdubya66** [comment]
also, we should move the comments in the sharepoint file into the issue. no need to keep them internal or in a separate doc.

**Comment by mhagen-vmware** [comment]
@lcastellano ^^^?

**Comment by lcastellano** [comment]
This story is actually finished. No need to move it the new Epic in 1.2. It consisted in installing and investigating Authn/Authz in the current version of Admiral (the one included in 1.1). There are new stories in the Authn/Authz unification Epic (https://github.com/vmware/vic/issues/4433).
