### ISSUE TITLE
Investigation of Identity/User Management in Admiral

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#3902]
User statement: Investigate current Identity/User Management features in Admiral, look for integration points with Lightwave.

Detail: Admiral is a component in the VIC product. Long term goal of this Epic is to integrate the Identity/User Management infrastructure for Harbor and Admiral. This issue tracks the investigation of Identity/User Management in Admiral with special considerations for integration with Lightwave. Code inspection may also be necessary.

Acceptance criteria:
Write a document that contains a description of Identity/User Management in the current version of Admiral. The document should also contain a proposal of integration with Lightwave within VIC product.

**Comment by lcastellano** [comment]
Here's a note describing the result of this investigation. An issue has been open against Admiral.

https://onevmw-my.sharepoint.com/personal/lcastellano_vmware_com/_layouts/15/guestaccess.aspx?guestaccesstoken=8nLl2QRpcnDX0SAwC4BAMjed%2fsxOm6GYQtQkfOqJJjU%3d&docid=2_164c7235aa2a543a2860aa22375e87205&rev=1

**Comment by rajanashok** [comment]
Thanks for the update @lcastellano, closing this.
