### ISSUE TITLE
Investigation of Identity/User Management in Harbor

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#3903]
User statement: Investigate current Identity/User Management features in Harbor, look for integration points with Lightwave.

Detail: Admiral is a component in the VIC product. Long term goal of this Epic is to integrate the Identity/User Management infrastructure for Harbor and Admiral. This issue tracks the investigation of Identity/User Management in Harbor with special considerations for integration with Lightwave. Code inspection may also be necessary.

Acceptance criteria:
Write a document that contains a description of Identity/User Management in the current version of Harbor. The document should also contain a proposal of integration with Lightwave within VIC product.

**Comment by lcastellano** [comment]
The result of this investigation is captured in this note. An issue have been opened against Harbor.

https://onevmw-my.sharepoint.com/personal/lcastellano_vmware_com/_layouts/15/guestaccess.aspx?guestaccesstoken=8nLl2QRpcnDX0SAwC4BAMjed%2fsxOm6GYQtQkfOqJJjU%3d&docid=2_164c7235aa2a543a2860aa22375e87205&rev=1

**Comment by rajanashok** [comment]
Thanks @lcastellano, closing this.
