### ISSUE TITLE
Addition and Configuration of Lightwave in VIC-OVA

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#3907]
User statement: Lightwave should be part of the VIC-OVA. Assist with the implementation and testing of the addition and configuration of LW to VIC-OVA.

Detail: The details of this activity depends on which approach is taken to build the VIC-OVA. Ansible Scripts to install and configure LW on GCE were developed as part of the Cello project. Most likely the scripts will have to be adapted to work in the VIC-OVA environment. Estimate will depend on the chosen approach.

Acceptance criteria:
A set of scripts or directives to include/configure/customize LW inside the VIC-OVA.

**Comment by mdubya66** [comment]
This was pulled into sprint 3 by accident. It is dependent on the research for including lightwave. #3899. Also making priority low since this is not a April release (1.1) topic.

**Comment by lcastellano** [comment]
We have more details now, this activity should be replaced by 4107, 4108, 4079. We consider this one finished.

**Comment by mhagen-vmware** [comment]
Should this be in Sprint 4 milestone?
