### ISSUE TITLE
Architecture design for Unified installer OVA

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#3912]
**User Statement:** An architecture for the unified installer OVA has to be created.

**Details:** Requires specifics on properties to be passed during OVA deploy and how those translates into Harbor and Admiral configuration files/scripts.

**Acceptance Criteria:** 

- Must document all the working parts of the OVA
- Must specify what the end result should look like

**Comment by mdubya66** [comment]
Marking high for inclusion in the next sprint

**Comment by frapposelli** [comment]
Document link: https://gist.github.com/frapposelli/0e445bfd428ed394b4b7fb6755ed7b70

**Comment by frapposelli** [comment]
Spec has been circulated with the PMs for approval

**Comment by frapposelli** [comment]
Closed by #4242
