### ISSUE TITLE
Investigate OVF properties required to support OVA installer use case

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#3913]
**User Statement:** As developer of the OVA, I need full access to the OVF properties provided by the underlying vSphere infra.

**Acceptance Criteria:** 
- Must be able to read pertinent `guestinfo.*` properties from inside the GOS used in the OVA.
- Must support Phone Home (VAC) with granular properties about what is currently installed in the appliance

**Comment by mdubya66** [comment]
If this doesn't capture setting the guest_full_name for phone home (VAC) purposes we should add one that does. See https://github.com/vmware/vic/issues/3645

**Comment by frapposelli** [comment]
VAC support will require a research spike in the next sprint

**Comment by frapposelli** [comment]
Tracking VAC requirement in #4250

**Comment by frapposelli** [comment]
Rest of the story completed with #4240
