### ISSUE TITLE
Create integration test for OVA Unified Installer

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#3914]
**User Statement:** As developer we want to be able to test all the code drops for the VIC components in a nightly build.

**Details:** Create a test that builds the OVA and deploys it on a vSphere environment.

**Acceptance Criteria:** A test that builds the OVA artifact and deploys to a vSphere infrastructure and performs some sanity check (ip address, services running, etc...)

**Comment by maplain** [comment]
blocked by #3677

**Comment by maplain** [comment]
blocked by #3677

**Comment by mhagen-vmware** [comment]
This isn't blocked by #3677, you can add this into the manual section and add it into our nightlies if you want.

**Comment by mhagen-vmware** [comment]
@maplain If you put the term 'fixes: #3914' into the PR body then this will close automatically with the PR next time.

**Comment by maplain** [comment]
ok... next time I'll know
