### ISSUE TITLE
Initial build of OVA artifact

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#3916]
**User Statement:** As a developer of Harbor and Admiral, I need an OVA to test my code the way it's going to be installed.

**Details:** Need to provide an OVA with OVF parameters for configuration of services.

**Acceptance Criteria:** Have a OVA ready for integration tests

**Comment by mdubya66** [comment]
Prioritizing High for inclusion in sprint 3.

**Comment by rajanashok** [comment]
PR merged and verified the OVA creation from the sprint demo.
