### ISSUE TITLE
Unified OVA Installer

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#3917]
**User Statement:** As a customer of vSphere Integrated Containers, I want an easy way to install all the product components on my vSphere infrastructure, with a single download, and using a familiar workflow that leverages my competencies on vSphere. When an upgrade or a patch is released, I want to follow a simple guide to perform the upgrade of one or more components of vSphere Integrated Containers.

**Details:** to accomplish these goals, we need to create a single OVA that installs all the VIC components and performs their configuration using OVF properties, resulting in a running service that can be accessed by the vSphere admin for further configuration.

**Acceptance Criteria:**

1. The vSphere administrator downloads the  VIC Management OVA from a known location 
2. The vSphere administrator deploys the VIC Management OVA from the vSphere client, provides values for Harbor and Admiral configuration options
3. The deployment should also tie the Harbor and Admiral instances together
4. Once deployed the vSphere administrator should be able to 
    - Access the Admiral / Harbor integrated UI
    - SSH into the machine to run vic-machine commands
5. The vSphere administrator should also be able to mount the VIC Management OVA onto their local machine to run vic-machine commands

**Comment by mdubya66** [comment]
This is high as it needs to be pulled in ASAP to meet the 1.1 deliverables.

**Comment by mdubya66** [comment]
Need to add the ability to track installations via the vSphere phone home mechanisms.

**Comment by mdubya66** [comment]
Keeping this Epic tight for 1.1 release so I removed #4250

**Comment by mhagen-vmware** [comment]
closing as all stories are complete, if we need to do more unified OVA work for future releases please create a new epic.

**Comment by frapposelli** [comment]
🎉
