### ISSUE TITLE
configure systemd to log to debug serial port

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#392]
so that we can see errors in the datastore file.

**Comment by hickeng** [comment]
This should be done soon if it's a real issue - #306 is about removing systemd from the container completely.

**Comment by hickeng** [comment]
lowish priority - don't think it's crucial for GA as the only systemd issues we've been suspicious of are the DHCP ones.

**Comment by mdubya66** [comment]
please assign @hickeng
