### ISSUE TITLE
NFS client + NFS volume PL integration

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3925]
User statement:
As an engineer, I need to allow for the creation of nfs shared volume stores during the init cycle of the portlayer server. Once this is done the targets provided by vic-machine can be consumed.

Details: This ticket should most likely be worked on in conjunction with #3810 because there must be a way to communicate nfs targets to the portlayer `configure` api handler at boot time of the portlayer server. This is where the vsphere volume stores are made and this is where the nfs volume stores should also be created. This means that we must explore where we want to put the nfs targets to be read in at init time of the portlayer. Vic-machine will need to facilitate the persistence of these targets to the portlayer. This work has been marked separately from the `VolumeStore` implementation piece since it relies on both the VolumeStore being implemented and vic-machine passing in the appropriate targets to consume. This is also the main area where we will distinguish between a nfs and vsphere volume store. 

Acceptance criteria: Successful creation of volumestores on targeted nfs servers after the portlayer has finished it's init process and is waiting to serve requests.

**Comment by fdawg4l** [comment]
@matthewavery I'm not following what changes you're describing.  What handlers specifically?  And what changes do they need?

The way we handle volumes for vsphere and nfs should be identical from the point of view of the PL REST API.  They should not need to change. 

If you specifically mean the `Configure` operation in the portlayer server which bootstraps the storage layer, then we should reword the summary of this issue.

**Comment by fdawg4l** [comment]
Fixed by https://github.com/vmware/vic/pull/4154 and https://github.com/vmware/vic/pull/4173.
