### ISSUE TITLE
Delete vsan dom objects in vic-machine delete and image/volume delete

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3931]
As a customer, I don't want to leak storage resources after use VCH, no matter it's docker rmi, docker volume rm or vic-machine delete. I need the storage used by VCH is deleted cleanly.

Related to this story, we need to add following code:
- [ ] in vic-machine delete, call vsan dom cache to clean all orphan dom objects, which mean vmdk is deleted, but dom still exists.
- [ ] in storage portlayer, call vsan dom cache to delete dom object related to specific vmdk file
- [ ] move image storage parent namespace creation from portlayer to vic-machine, like volume did, and record the namespace path, instead of the dir alias, which is not retrievable in vsan dom cache.

depends on PR #3929, additional work for #3787

**Comment by dougm** [comment]
As mentioned in the planning meeting, I am taking the path of doing file deletes without leaking DOM objects.  The DOM object cache idea uses internal APIs all labeled with "WARNING": http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.VsanInternalSystem.html
We can still use these APIs outside of the VCH runtime (upcoming govc datastore.vsan commands) to verify we are not leaking in CI tests.

Currently we only leak objects on vSAN when using FileManager to delete disks.  Using FileManager to remove empty directories does not leak, nor does using FileManager to remove plain files such as `metadata.json`.

We can use VirtualDiskManager.DeleteVirtualDisk to remove disks without leaking, unless the vmdk has `ddb.deletable=false`.  The only way (using public APIs) to delete these files without using FileManager is to attach them to a VM and either `ReconfigVM` to delete the device *and* destroy the backing files, or `DestroyVM` with the disk devices still attached.  Taking this approach would require creating an additional VM(s) in the inventory.

There are a few internal APIs that use `VpxaVmprov::MarkDiskAsDeletable` to set this flag to **true** before removing.  Such as OperationCleanupManager (too complex for our needs) and one that's internal to the vpxa API endpoint.   LowLevelDeleteFiles seemed promising, while internal, has a simple API.  However, contrary to the vmodl definition, it does not return any errors if file(s) cannot be deleted.  Worse, it is possible to crash vpxd if the input paths aren't properly formed.

@fdawg4l suggested modifying the .vmdk directly to remove the flag, I think it is the best option at this point:

* The .vmdk file is just a small text file, with attributes such as the ddb.deletable flag and pointer to disk that contains the data.

* We can use the datastore HTTP interface to replace the .vmdk with `ddb.deletable=false` removed

* After which, we can use VirtualDiskManager.DeleteVirtualDisk and no DOM objects are leaked

I have an upcoming DatastoreFileManager for gomvomi that combines FileManager and VirtualDiskManager to remove files properly when we can, and apply a hack in the case of disks with `ddb.deletable=false`.
Where hack is currently the internal LowLevelDeleteFiles, I'm in the process of changing it to update the .vmdk file.  We can change the hack to something else (such as using a dummy VM), and of course remove when the vSAN fix is released.  But it'll be in one place and transparent to the caller.
The DatastoreFileManager is useful without the hack underneath too.

**Comment by dougm** [comment]
PR: vmware/govmomi#672

vic PR will follow and should be a small change other than the vendor update.

**Comment by dougm** [comment]
Summary of the workaround:

- Remove the ddb.deletable=false flag from the .vmdk via the datastore HTTP interface (GET + POST)

- Use DeleteVirtualDisk_Task to delete

Note that we're only hitting this code path via:

- 'docker rmi' where our backend has validated the image is not in use

- 'vic-machine delete' where we've validated that container VMs no longer exist or user has specified to -force remove them

And, the POST to remove  ddb.deletable=false only applies to images, we don't need to for the volumes with user data since the flag is not set.

**Comment by emlin** [comment]
verified
