### ISSUE TITLE
Clean leaked dom object in vsan datastore

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3932]
As a customer, if there is any vsan dom object leaked for I used old version's VCH, I need a way to clean up all left over DOM objects, without impact my other workload, and current active VCHs.

As we already have dom cleanup code, it's easy to extend the function to help user clean up their env. So one possible approach is to add following command option:

```
vic-machine debug --cleanLeakingDom --datastore ...
```
Implementation is to call vsan dom cache to clean orphan dom objects, just need to be careful with the errors
Depends on PR #3929 . Additional work for #3787

**Comment by mlh78750** [comment]
We'll resolve this another way. Closing.

**Comment by dougm** [comment]
Note that govc is getting new commands to detect DOM object leaks and clean them up.  To list orphan object uuids + datastore path:

`govc datastore.vsan.ls -l -o`

To clean:

`govc datastore.vsan.ls -o | xargs -r govc datastore.vsan.rm`

With #3931 we won't leak anymore, but these commands could be used by CI/robot to verify and repair if needed.
