### ISSUE TITLE
vic is leaking dom objects on vsan

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3938]
With simple image pull, and then delete VCH, there will have dom objects leaking on vsan datastore. At the same time, even we do not delete VCH, docker rmi will leak dom object as well, but it's hard to differentiate, so here just list the reproduce steps with vic-machine delete.

- Install VCH, with vsan datastore as image-store. It'd be better to be one clean vsan datastore, no any dom objects on that.
- Run docker pull busybox
- Delete VCH through vch
- Login to VC web UI, and check vsan datastore files. There should not have any files at this time.
- Login to one ESXi host, attached with the vsan datastore
- Run ```cmmds-tool find -t DOM_OBJECT```, there will have few dom objects not deleted

**Comment by stuclem** [comment]
Added the following to the release notes for 0.9:

----

- <b>vSphere Integrated Containers leaks DOM objects on VMware vSAN. [#3938](https://github.com/vmware/vic/issues/3938)</b><br>When using a VMware vSAN datastore as the image store, if you pull an image and then delete the VCH, DOM object leaking occurs on the datastore. Running docker rmi without deleting the VCH has the same issue.

   Workaround: Run `cmmds-tool find -t DOM_OBJECT` to see the list of undeleted DOM objects.

----

**Comment by stuclem** [comment]
@dougm, @emlin says that you might have a proper workaround for this issue. Can you help?

**Comment by dougm** [comment]
The fix (#3787) will be in the next release.

It is possible to use govc to list and remove leaked objects:
https://github.com/vmware/govmomi/blob/v0.13.0/govc/USAGE.md#datastorevsandomls
https://github.com/vmware/govmomi/blob/v0.13.0/govc/USAGE.md#datastorevsandomrm

List leaked objects:
```
govc datastore.vsan.dom.ls -l -o
```

Remove leaked objects:
```
govc datastore.vsan.dom.ls -o | xargs govc datastore.vsan.dom.rm
```

**Comment by stuclem** [comment]
Thanks @dougm. Updated the workaround:

-----

- <b>vSphere Integrated Containers leaks DOM objects on VMware vSAN. [#3938](https://github.com/vmware/vic/issues/3938)</b><br>When using a VMware vSAN datastore as the image store, if you pull an image and then delete the VCH, DOM object leaking occurs on the datastore. Running `docker rmi` without deleting the VCH has the same issue.

   Workaround: Use `govc` to [list](https://github.com/vmware/govmomi/blob/v0.13.0/govc/USAGE.md#datastorevsandomls) and [remove](https://github.com/vmware/govmomi/blob/v0.13.0/govc/USAGE.md#datastorevsandomrm) leaked objects:

  - List leaked objects: `govc datastore.vsan.dom.ls -l -o`
  - Remove leaked objects: `govc datastore.vsan.dom.ls -o | xargs govc datastore.vsan.dom.rm`

------

This was a copy-paste job, so I think that it's safe to remove kind/note now.

**Comment by stuclem** [comment]
And since the issue won't be present in 1.1, there is no need for additional doc.
