### ISSUE TITLE
Create user docs referencing versions of VIC to Docker API and CLI version

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3949]
As a user of VIC, I should be able to find documentation that tells me which version of VIC correspond to which version of the Docker API and CLI.

----

Acceptance Criteria:  User documentation in our repo.

**Comment by stuclem** [comment]
@sflxn I think that we have this already. See the opening paragraph of https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md, which is for 0.8. We update accordingly for each tagged release.

Does this cover it?

**Comment by stuclem** [comment]
Dup of #3419
