### ISSUE TITLE
Add restricted ops-user to CI systems

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3951]
**Story**
As a VIC developer I want my CI system to reflect real world usage as much as possible, including secure deployments.

**Detail**
The current CI deployment uses --ops-user, however they are not using restricted credentials. We should be configuring an ops user that has limited RBAC privileges configured as per #3947.
Ideally this should be combined with some negative testing when the ops-user specified does **not** have access to assets specified in the vic-machine arguments - this should be caught in validation but likely is not.

**Acceptance**
VCHs deployed in CI should use a restricted ops-user

**Comment by stuclem** [comment]
@mhagen-vmware, as a part of the testing of `--ops-user` with restricted permissions, please can someone from QE verify the procedure at https://github.com/vmware/vic/blob/08-docs/doc/user_doc/vic_installation/set_up_ops_user.md

Thanks!

**Comment by hickeng** [comment]
I believe that #4817 is likely a privilege misconfig where we are missing a privilege from [the ops-user docs](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/set_up_ops_user.html)
Now that I'm inspecting those privileges again I think we're also missing `Virtual Machine->Configuration->Rename` now that @chengwang86 has added that support.

The only way to stop this happening repeatedly is to address this issue, which likely requires addressing #4306

**Comment by mhagen-vmware** [comment]
moving back into 1.2 per @corrieb

**Comment by lcastellano** [comment]
Moved to: https://github.com/vmware/vic/issues/6502
