### ISSUE TITLE
Spike: vApp restart

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3969]
We need to figure out what happens on vApp restart, specifically do we restart just the appliance or the container VMs as well.

**Comment by lgayatri** [comment]
On vApp shutdown, the containers running within will get powered off.
On vApp powerOn, the containers running within will get powered On.

**Comment by hmahmood** [comment]
@lgayatri we have settled on the following behavior for vApp restart:
1. On vApp shutdown, container VMs and the appliance VM will be powered off
2. On vApp startup, only the appliance VM will be powered on

(2.) follows default docker behavior at the moment, so is the easiest path to follow.
