### ISSUE TITLE
Docker 1.13 client claims API version downgraded from 1.25 when calling docker version

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3985]
As a user of VIC and docker CLI 1.13, I should see the correct API versions showing 1.25 and minimum API version if I issue 'docker version' with CLI 1.13.

Acceptance criteria:  Updated docker version robot script calling docker version and checks the correct API version and minimum version in both the client and server section of the output.  The robot scripts should check with both docker1.11 and docker1.13.

---

Expected with docker 1.13:
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      0.8.0
 API version:  1.25 (minimum version 1.23)
 Go version:   go1.7.3
 Git commit:   f6e48c9
 Built:        Fri Feb 17 01:24:47 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

Expected with docker 1.11:
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990-unsupported
 Built:        Wed Aug 17 19:08:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      0.8.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   f6e48c9
 Built:        Fri Feb 17 01:24:47 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

Actual with docker 1.13:
```
Client:
 Version:      1.13.0
 API version:  1.24 (downgraded from 1.25)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      0.8.0
 API version:  1.25 (minimum version )
 Go version:   go1.7.3
 Git commit:   a502802
 Built:        Fri Feb 17 02:12:11 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by sflxn** [comment]
There are now two locations that versions are handled from the server *sigh*.  They're both used by the CLI to display version data.  Prior to Docker 1.13, version was handled by the system backend.  It simply replied back with APIVersion.  With Docker 1.13, the system backend also replies back with MinAPIVersion.

On top of that, Docker 1.13 has a best attempt version hint for the CLI.  This includes server version, default version, and minimum version.  This is handled by a version middleware.  I believe this version is returned in the HTTP header.

Anyway, there is a PR for it.

**Comment by mabushey** [comment]
```
Client:
 Version:      17.05.0-ce
 API version:  1.24 (downgraded from 1.25)
```

How do we upgrade to 1.25?
