### ISSUE TITLE
Virtual Container Host as a Service! - VCHAAS! 

### ISSUE THREAD

**Issue by vmwarelab** [vmware/vic#3987]
I have been playing with vSphere Integrated Containers for a while now and deploying and deleting the VCH Endpoint so many freaking time was so painful since the command line has many options and can be a bit drastic. During all this time I had to save the entire command line in a text file with all its parameters, so I can simply copy and past what I need so i don't  have to type it over and over every single time I decide to deploy the Virtual Container Host or delete it. Having in mind our main use case for vRA and that is **IT Automating IT** I had to find a way I can somehow provide this as a service in my home lab and I did today my first draft/attempt and I m excited to share that with you!  

So let  me Explain...

In vRO I managed to leverage the Guest Script Manager (http://www.vcoteam.info/articles/learn-vco/272-leveraging-the-guest-script-manager-package.html)  to take the command line with most of its parameters and automate it by creating the desired workflows ( Basically the Create and Delete VCH process ) then use these workflows for XaaS blueprints to essentially present it as an item catalogs in vRA where I can easily request to create a new VCH or delete an existing one.  

This is so great on many levels since now you can easily entitle development groups for example, that really don't have to know how VIC works and simply have access to a docker API to provision Containers,   you can wrap approval / governance around it which vRA can easily provide and have all the parameter's values available in drop-down list format so the requester don't have to scratch his head when filling the forms.

I tested both XaaS blueprints ( Create and Delete VCH ) and both works like a charm. I still though have to clean it up a bit then I will be more than happy to share both the vRO package and the XaaS blueprints here on the thread for others to use it or build on top of it and make it even better since I am not an expert when it comes to vRO. For now here are some of the screen shots I captured for requesting a Virtual Container Host.

Would love to know everyone feed back on this!  Thank you.

![screenshot-1](https://cloud.githubusercontent.com/assets/19843322/23049610/4115eb0a-f48b-11e6-966f-6555a08cdd63.jpg)
![screenshot-2](https://cloud.githubusercontent.com/assets/19843322/23049611/44519bb6-f48b-11e6-8329-c0aaf5af8f24.jpg)
![screenshot-3](https://cloud.githubusercontent.com/assets/19843322/23049613/46b4ca5e-f48b-11e6-90f2-534b01e2c220.jpg)
![screenshot-4](https://cloud.githubusercontent.com/assets/19843322/23049615/48bb30ae-f48b-11e6-9e29-ce8808e14bc8.jpg)
![screenshot-5](https://cloud.githubusercontent.com/assets/19843322/23049619/4c328fd4-f48b-11e6-860b-04b2fff5e180.jpg)
![screenshot-6](https://cloud.githubusercontent.com/assets/19843322/23049622/4f211800-f48b-11e6-8318-53af640feab5.jpg)
![screenshot-7](https://cloud.githubusercontent.com/assets/19843322/23049623/51237dc8-f48b-11e6-9c22-58d7ea77099b.jpg)

**Comment by mdubya66** [comment]
Thanks for sharing @vmwarelab. This is great.

**Comment by Luckeyd** [comment]
I hate to necro post, but I saw this and was wondering if you have had any recent updates or changes?  I would love to replicate this in my lab as well and if you had any refinements or improvements, I would be interested!
