### ISSUE TITLE
Components are using ProperyCollector wrong

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#3995]
We are using the DefaultCollector referenced by the Service.Content. Instead we should be creating a new collector - for each call we initiate - using CreatePropertyCollector and then call DestroyPropertyCollector when we are done with it. Otherwise we could end up with a truncated result which leads to all kinds of undefined behaviors. Two concurrent calls with the same version would provide roughly the same information. And if the versions are different, the call with the later version will return a subset of the information returned by the call with the earlier version. Furthermore, WaitForUpdates returns only diffs, and in most cases the client needs to keep aggregating the sequence of diffs to reconstruct the latest values. Last but not least, with WaitForUpdatesEx the version may indicate a truncated result and this makes concurrent calls even less meaningful.

Spotted the potential issue while working on https://github.com/vmware/vic/issues/3868 and confirmed with vmcore team.
 
The underlying issue that this addresses is that any call to WaitForUpdates, CheckForUpdates, or WaitForUpdatesEx does updates on all the filters created on a given PropertyCollector on a given session.  This means that multiple calls to WaitForUpdates, CheckForUpdates, or WaitForUpdatesEx made to the same PropertyCollector on the same session on different threads of the same client, or even on different clients that share the same session are still handled on the server serially. Use of different PropertyCollector instances allows the server to handle these calculations in parallel.

- Code base needs to be audited and all instances of DefaultCollector needed to be replaced.
- All tests needs to pass with it
- Need to provide a custom build to original reporter to see whether this improves their life

**Comment by dougm** [comment]
Note that we do use Create/Destroy within the property.Wait() method, that's where any WaitForUpdates should be happening.  We aren't using CheckForUpdates anywhere that I know of.

Is using DefaultCollector for RetrieveProperties an issue?

**Comment by dougm** [comment]
For reference, while DefaultCollector is passed as a param to property.Wait(), it is only used to Create/Destroy a new instance, along with the filter: https://github.com/vmware/govmomi/blob/master/property/wait.go#L39-L46

**Comment by caglar10ur** [comment]
@dougm good to know! I was planning to take a look at what's happening under the cover, caught up on some threads on slack :) This suggests that my initial assumption is wrong, I'll take a look at VIC codebase to make sure that we are not doing something weird and then close this issue.

**Comment by caglar10ur** [comment]
@dougm as far as I see API documentation has no special case for RetrieveProperties/RetrievePropertiesEx like WaitForUpdates/WaitForUpdatesEx. I asked to vmcore team to make sure, will update the here when I hear something.

**Comment by cgtexmex** [comment]
FWIW I spent some time looking at this last year -- I wanted to make sure things were kosher and after some testing and writing a small test program I was convinced we were using it as intended / appropriately.

**Comment by caglar10ur** [comment]
@dougm vmcore confirmed that RetrieveProperties/RetrievePropertiesEx concurrent safe and it is OK to use same PropertyCollector for them
@cgtexmex you are right, looks like govmomi does everything right and I got fooled by the DefaultCollector name

Closing this as it turns out to we are using ProperyCollector right :)
