### ISSUE TITLE
docker stop reports wrong exitcode when process returns non-zero after SIGTERM received

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#3996]
**User Statement:**

I expect VIC to have `docker stop` functional parity. If I call `docker stop` on a process that traps the signal and returns a custom exit code, the container's exit code should be the same as the exit code of the child process.

**Details:**

The `ExecConfig` that's inspected by `docker ps` appears to lose this information, or maybe it's never assigned, in the case that the process receives a `SIGTERM`. I have been able to see the exit code get reported properly, but it either does not get written to ExtraConfig or gets overwritten with an invalid value (`0`) before the `stop` process is complete 

**Acceptance Criteria:**
These procedures should produce the same outputs on VIC and on Docker:
`docker run -it busybox`
`$ trap "exit 22" SIGTERM; while true; do sleep 1; done`

Then in a new shell, `docker stop $container_from_above`
Then check `docker ps -a` and see `Exited (22)` in the output.

**Comment by hickeng** [comment]
The core issue here is fixed by #5532, however this needs a test to confirm the function.
I've edited the original description to use an error code that packs cleanly into the available bits - original was `1111` which overflows.

**Comment by corrieb** [comment]
I believe we can close this as a dup of #5610 at this time
