### ISSUE TITLE
Update the user docs to specify the next version of VIC only supports compose format 3

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#4007]
As a user of VIC, I should be able to find out which version of the compose file format and compose binary version that VIC supports by reading the user docs.

Docker-compose 1.10 and up
Compose file format 3 and up

Best effort to use docker-compose binary 1.9.0

**Comment by stuclem** [comment]
From https://github.com/vmware/vic/issues/4023#issuecomment-284602587, it seems that we are revising the support statement:

-----

- VIC supports compose file format 2 and 2.1 only, minus keywords we do not support
- VIC supports compose CLI binary 1.9.0 only

We do best effort to support other file format and binary CLI version, but the above is our agreed upon support line.

-----

**Comment by stuclem** [comment]
Updated [Supported Docker Commands](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md) with the support statement above.
