### ISSUE TITLE
Upgrade integration test fails

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#4015]
During a full ci build, the upgrade test failed.  I ran the same build twice with upgrade failure in both times.  Log zip file too big to upload.  Link here:

https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_8130_f6f5083c2576f268078dcdec5932c718ac7fd273.zip?authuser=1

**Comment by anchal-agrawal** [comment]
This failed to due a container's exit code being not as expected in `docker ps -a` after `docker stop`. Related to #3800 and #3996.

<img width="1168" alt="exitcode" src="https://cloud.githubusercontent.com/assets/4361620/23266677/10872620-f9ae-11e6-9d45-481fea268c04.png">

@gigawhitlocks, could you take a look at this? We got an exit code of 143 and the test expected 0.


[Test-Cases.Group11-Upgrade.11-01-Upgrade-VCH-8130-7716-container-logs.zip](https://github.com/vmware/vic/files/796972/Test-Cases.Group11-Upgrade.11-01-Upgrade-VCH-8130-7716-container-logs.zip)

**Comment by gigawhitlocks** [comment]
Test is wrong, output from `ps` is correct

**Comment by gigawhitlocks** [comment]
Tests for upgrade must've been written while the bug was present.
