### ISSUE TITLE
Container name and ID are conflated for container naming

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#4020]
**VIC version:**

master

**Steps to reproduce:**

```
$ sudo docker run -itd busybox
6fa54b2d087a2322ad8aaafd9c541636891a6f6c7d737c7ca059d5f024d62030
$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
6fa54b2d087a        busybox             "sh"                2 seconds ago       Up 2 seconds                            cocky_goldstine
$ sudo docker run -itd --name=6fa busybox
0a21a9ee8306bb400ec457c4ac1ffd3e6f0bb4fa83a1d467fdea9a539d95bd64
```

**Actual behavior:**

```
$ sudo docker create --name=6fa busybox
Error response from daemon: Conflict. The name "6fa" is already in use by container 6fa54b2d087a2322ad8aaafd9c541636891a6f6c7d737c7ca059d5f024d62030. You have to remove (or rename) that container to be able to re use that name.
```

**Expected behavior:**

```
$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
0a21a9ee8306        busybox             "sh"                37 seconds ago       Up 36 seconds                           6fa
6fa54b2d087a        busybox             "sh"                About a minute ago   Up About a minute                       cocky_goldstine
```

**Additional details as necessary:**

This issue was found due to a container name collision in an integration test, where a container's name prefix-matched with a previous container's ID. This is a valid scenario, however, and the second container should be created successfully.

See below for previous issue description.

---

_We should review names of containers in our robot files and make them more specific to avoid failures due to name collisions._

_Seen in https://ci.vmware.run/vmware/vic/8130:_

<img width="1105" alt="collision" src="https://cloud.githubusercontent.com/assets/4361620/23266332/1d40fd38-f9ad-11e6-9d78-c6809ee3aa6c.png">

**Comment by cgtexmex** [comment]
if we have tests that are configured w/conflicting container names wouldn't we see this all the time and not intermittently?

**Comment by anchal-agrawal** [comment]
The above is a very narrow case where `abe` prefix-matched with an auto-generated container ID `abed9ed53e83b47b744da835d97ff41c137c1cc19df28e6676ebc7548ce64b09`. Changing `abe` to something like `abeContainer` should alleviate the issue.

**Comment by hickeng** [comment]
Could someone confirm what the correct behaviour should be - I agree that there's an ambiguity if "abe" is permitted and there's a container ID that collides, but I'm unsure it actually qualifies as a name collision.
WDDD? (what does docker do?)

**Comment by anchal-agrawal** [comment]
```
$ sudo docker run -itd busybox
6fa54b2d087a2322ad8aaafd9c541636891a6f6c7d737c7ca059d5f024d62030
$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
6fa54b2d087a        busybox             "sh"                2 seconds ago       Up 2 seconds                            cocky_goldstine
$ sudo docker run -itd --name=6fa busybox
0a21a9ee8306bb400ec457c4ac1ffd3e6f0bb4fa83a1d467fdea9a539d95bd64
$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
0a21a9ee8306        busybox             "sh"                37 seconds ago       Up 36 seconds                           6fa
6fa54b2d087a        busybox             "sh"                About a minute ago   Up About a minute                       cocky_goldstine
```

That's interesting - looks like we're conflating the container's name and ID, while Docker isn't.

**Comment by chengwang86** [comment]
This is because we check whether the containerName exists or not here https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/container.go#L449
```
if exists := cache.ContainerCache().GetContainer(config.Name); exists != nil {
		err := fmt.Errorf("Conflict. The name %q is already in use by container %s. You have to remove (or rename) that container to be able to re use that name.", config.Name, exists.ContainerID)
		log.Errorf("%s", err.Error())
		return containertypes.ContainerCreateCreatedBody{}, derr.NewRequestConflictError(err)
	}
```
In containerCache.go, 
```
func (cc *CCache) getContainer(nameOrID string) *container.VicContainer {
	// get the full ID if we only have a prefix
	if cid, err := cc.idIndex.Get(nameOrID); err == nil {
		nameOrID = cid
	}

	if container, exist := cc.containersByID[nameOrID]; exist {
		return container
	}

	if container, exist := cc.containersByName[nameOrID]; exist {
		return container
	}
	return nil
}
```
We check the existence of the containerName assuming it is either a name or an ID. But actually we should not be checking the following during container creation
```
if container, exist := cc.containersByID[nameOrID]; exist {
		return container
	}
```

**Comment by anchal-agrawal** [comment]
I've updated the issue to track this as a bug.

**Comment by kreamyx** [comment]
Another thing that needs to be handled here is that full name matching should take precedence over id prefix matching. 
For example, assume container A with id `6fa54b2d087a` and container B with name `6fa`

`docker inspect 6fa` should inspect container B

**Comment by stuclem** [comment]
Since @anchal-agrawal says this is a very narrow case, and since I am the one who added kind/note (no idea why), I propose that we do not doc this in the release notes. Feel free to protest!
