### ISSUE TITLE
Research what version of compose file we currently and should support

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#4023]
As a user of VIC and a VIC developer, I should understand what version of docker-compose file format that VIC currently support and what it should support.

Acceptance Criteria:
   1. A matrix of support and root cause for diff between VIC and standard docker.
   2. If there is a mismatch between VIC and standard docker, a new github issue for fixing it and new integration tests to verify the various compose file format.

---

We need a matrix of our current support and what docker support.  If our support is a mismatch, we need to understand why.

**Comment by sflxn** [comment]
This is the version mapping for compose binary, docker daemon, and compose file format:

| Compose CLI | Docker Daemon | Compose File |
| --- | --- | --- |
| 1.6.0 | 1.9.1 | 1 |
| 1.7.0 | 1.10.0 | 2 |
| 1.9.0 | 1.12.0 | 2.1 |
| 1.10.0 | 1.13.0 | 3 |

**Comment by sflxn** [comment]
Compose 1.6.0 will run with compose file format 1.
Compose 1.6.0 has trouble running with compose file format 2 because VIC doesn't yet support disconnecting containers from networks.

**Comment by sflxn** [comment]
@stuclem @karthik-narayan Here's updated info on docker-compose binary and file format version compatibility with VIC 0.9.0.

**Comment by sflxn** [comment]
I spoke with @karthik-narayan today about compose version support.  He is fine with supporting the compose versions supported by docker daemon 1.13.  Given that Docker does support backwards compatibility with compose, we should say

- VIC supports compose file format 1, 2, 2.1, and 3, minus keywords we do not support
- VIC supports compose binary 1.9.0 and above

@karthik-narayan Any comments?

**Comment by karthik-narayan** [comment]
This looks good to me.

**Comment by sflxn** [comment]
related to #3635

**Comment by sflxn** [comment]
Per our conversation on Slack with @karthik-narayan, @mdubya66, and @corrieb, we've come to the final support message for compose:

- VIC supports compose file format 2 and 2.1 only, minus keywords we do not support
- VIC supports compose CLI binary 1.9.0 only

We do best effort to support other file format and binary CLI version, but the above is our agreed upon support line.

**Comment by sflxn** [comment]
Added issue #4158 to add support for DisconnectContainerFromNetwork issue.

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mdubya66** [comment]
@stuclem for documentation purposes
