### ISSUE TITLE
static vmw-guestinfo library

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#403]
This is a subissue of #229 

We use guestinfo to configure most of the components in the system, and this includes the tether. The tether needs to be a static binary to function reliably in the context of an arbitrary container filesystem and that means we need all libraries that it includes to be static.

For vmw-guestinfo this means either reimplementing it as pure Go (preferred for longer term as it makes it OS independent - if Go can target the OS it'll work), or using a mechanism such as:
http://blog.madewithdrew.com/post/statically-linking-c-to-go/

**Comment by caglar10ur** [comment]
Just to note that some images are not shipping sh so our wrapping the tether binary with a tether script is not working for them,
