### ISSUE TITLE
Research spike- Design docker cp

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#4050]
**User Statement:**

As a vic user, I want to be able to copy files into and out of my container vm using the `docker cp` command.

**Details:**

This spike will detail (in a design spec) how to implement the components and API for `docker cp`.

**Acceptance Criteria:**

The result of this spike will be a design specification including definitions of the interfaces needed in the components and the control flow of how to call them in order to copy files into and out of container vms.

**Comment by anchal-agrawal** [comment]
@fdawg4l please set the priority and any other labels, thanks!

**Comment by anchal-agrawal** [comment]
Done in https://github.com/vmware/vic/pull/5397.
