### ISSUE TITLE
Add regression test for vsan leaking dom objects

### ISSUE THREAD

**Issue by emlin** [vmware/vic#4051]
Needs automation test on vSAN env, to do following steps:

Run the following before vch-machine create, there should be no output

govc datastore.vsan.dom.ls -ds vsanDatastore -l -o

If there is orphan objects, run following commands to clean
govc datastore.vsan.dom.ls -o | xargs govc datastore.vsan.dom.rm

Run the regression tests, or anything that does:

    vic-machine create
    docker pull busybox
    docker pull nginx (or any images)
    docker run busybox
    docker rmi busybox

Check no leaking using govc datastore.vsan.dom.ls -ds vsanDatastore -l -o

    vic-machine delete

Check no leaking again

**Comment by rajanashok** [comment]
Attaching the original issue for reference #3787

**Comment by dougm** [comment]
Note that we'll need a vic-test docker image update to include a new govc release that has the new vsan.dom commands.

**Comment by mhagen-vmware** [comment]
@dougm Is there a story to capture the image update yet?

**Comment by dougm** [comment]
@mhagen-vmware I didn't create a story to update the image.  But I did release govc 0.13 last week, which includes the new vsan.dom commands.
