### ISSUE TITLE
Do you have a plan of design for REST API ?

### ISSUE THREAD

**Issue by kakakikikeke** [vmware/vic#4060]
Currently I know that a cli command is provided to create a virtual container host (vch).
But, I think that users will want to create with the REST API.

As you know, vSphere 6.5 provides the JSON REST API.
For example, to create a VM you can call the api `/vcenter/vm POST`.

I hope that it would be good to be able to create vch with such REST API.
(ex. `/vcenter/vch POST`)
Does VMware vSphere plan to offer a REST API for vch ?

Also if you have a plan for interface definition of it already, I would like to see it.

Thanks.

**Comment by zjs** [comment]
It looks like this issue got lost in the backlog. We now have an API! It's not yet complete, but may support the functionality you're interested in.

There's a slightly-out-of-date tutorial here: https://github.com/vmware/vic-product/tree/master/tutorials/api
