### ISSUE TITLE
Lockdown all physical esxi servers 

### ISSUE THREAD

**Issue by jakedsouza** [vmware/vic#4067]
**User Statement:**

As a vic engineer, I want to prevent non authorized users from gaining access to server resources in the datacenter.  

**Acceptance Criteria:**
1. Lockdown access to all nodes. 
2. Access should be allowed via pki over vpn

**Comment by jakedsouza** [comment]
Verified password login is disabled on all boxes.

**Comment by mhagen-vmware** [comment]
lgtm
