### ISSUE TITLE
typo in certificate creation during vic-machine create

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#4078]
**VIC version:**

x.y.z / master / commit ID

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

**Steps to reproduce:**
During vic-machine create

ERRO[2017-02-28T21:32:08+01:00] --------------------
ERRO[2017-02-28T21:32:08+01:00] Failed to create client for validaiton of operations credentials: Post xxx/sdk: x509: certificate signed by unknown authority
ERRO[2017-02-28T21:32:08+01:00] Create cannot continue: configuration validation failed
ERRO[2017-02-28T21:32:08+01:00] --------------------
ERRO[2017-02-28T21:32:08+01:00] vic-machine-linux failed: validation of configuration failed

**Actual behavior:**
ERRO[2017-02-28T21:32:08+01:00] Failed to create client for validaiton of operations credentials: Post xxx/sdk: x509: certificate signed by unknown authority

**Expected behavior:**
ERRO[2017-02-28T21:32:08+01:00] Failed to create client for validation of operations credentials: Post xxx/sdk: x509: certificate signed by unknown authority

**Logs:**

**Comment by andrewtchin** [comment]
I'll put this in with PR #4068

**Comment by andrewtchin** [comment]
ok nvm
