### ISSUE TITLE
Resolve the nightlies test failures

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#4089]
As QE engineers, we rely on the nightly test results to expose quality issues, sometimes the test itself fails not due to a product related issue but due to nimbus infrastructure or vsphere setup/configuration issues. This needs to be resolved so to have confidence on the nightly runs.

Acceptance criteria:
The nightly tests fails only due to a product bug, and reports stable nightly runs.

**Comment by rajanashok** [comment]
[functional_logs_02_27_18_31_vic_8252.zip](https://github.com/vmware/vic/files/811339/functional_logs_02_27_18_31_vic_8252.zip)

**Comment by mhagen-vmware** [comment]
One resolution to this story: #4152

**Comment by mhagen-vmware** [comment]
The vmotion tests do not have enough information to debug, so in the PR that should resolve the heterogeneous failure I have fixed the log collection.
