### ISSUE TITLE
Investigation to include Lightwave in the VIC OVA

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4102]
User Statement: Lightwave should be installed and configured in the VIC ova. Use OVA configuration environment to include Lightwave as a container. This first issue tracks an investigation on how to structure installing, configuring and starting the Lightwave container as systemd service.

Details: Investigate VIC ova environment, look at current examples. Collect all the different software components that are required to install Lightwave. Investigate how to structure the systemd units and unit files to properly install, configure and start Lightwave.

Deliverables: A note that describes how Lightwave will fit into the VIC ova environment. Definition of the different systemd files and unit files and their role.

**Comment by frapposelli** [comment]
Closing as no longer relevant for SSO work
