### ISSUE TITLE
toolbox support for guest file manager operations

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4103]
**Story**
As a user of toolbox I want to be able to transfer files to and from the guest

**Detail**
Guest Operations provides the following for guest file manipulation: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.guest.FileManager.html
The govmomi side of FileManager should already be available.

The capabilities we're primarily interested in adding to toolbox are:
* InitiateFileTransferFromGuest
* InitiateFileTransferToGuest

**Acceptance**
Able to round trip a file to the guest via govc

**Comment by dougm** [comment]
I have the vix/hgfs protocol sorted out, still working on the functionality in between, testing error paths, etc. Expect to open a PR this afternoon.
