### ISSUE TITLE
integrate toolbox filemanager support into tether

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4105]
**Story**
As a VIC developer I want tether to support transfer of files/directories to and from the guest

**Detail**
This should build on #4103 to allow transfer of files to and from the guest. This needs to be able to handle directory copy as well as singular files, so is likely to involve a mime type and tar/untar.

**Acceptance**
Able to roundtrip binary file to/from containerVM
Able to copy directory from containerVM
Able to copy directory to containerVM and retrieve single file from containerVM

**Comment by dougm** [comment]
Part 1 is in review (#5436), which completes the guest FileManager methods.  I'll implement the auto tar/untar in a separate PR.  cc @matthewavery @sflxn
