### ISSUE TITLE
Portlayer: copy API

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4106]
**Story**
As a Port Layer caller I want a copy API that doesn't require knowledge of target state
As a Port Layer caller I want to be able to copy files to a target container
As a Port Layer caller I want to be able to copy files from a target container

**Comment by mhagen-vmware** [comment]
Please provide some more details, estimate of work and priority then move to backlog.

**Comment by hickeng** [comment]
Current sizing is for the decomposition and expansion.

**Comment by matthewavery** [comment]
@hickeng I would like to be involved in the discussion of this ticket. I have put some thought into it in the past. I have also talked with @fdawg4l about this in the past. I would like to make the planning and execution of this piece as easy and efficient as possible.

**Comment by matthewavery** [comment]
An important aspect of this is that symlinks are always followed on the copy from the container.

**Comment by matthewavery** [comment]
Creating and adding a ticket for the portlayer request and response model design. As well as endpoint design for the copys.
