### ISSUE TITLE
Lightwave implementation as part of VIC OVA

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4107]
User Statement: Lightwave should be installed and configured in the VIC ova. Use OVA configuration environment to include Lightwave as a container. This issue tracks the actual implementation and testing of Lightwave as part of the VIC ova.

Details: Implement Lightwave as a service in VIC OVA. This requires the implementation of several systemd units, unit files. This activity should also include writing of basic unit tests.

Acceptance criteria: Lightwave should install as part of VIC OVA. The Lightwave GUI should work along with its rest apis.

**Comment by frapposelli** [comment]
Closing as no longer relevant for SSO work
