### ISSUE TITLE
Add trigger for tether reload

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4109]
**Story**
As a VIC developer I want to be able to cause tether to reload its configuration

**Detail**
Add a toolbox message to cause a reload of the configuration and add a portlayer method for sending toolbox reload message.
This is very similar to the Signal path.

This may require completion of the tether reorg work to provide a tether reference to toolbox for calling reload.

**Comment by caglar10ur** [comment]
Estimating as 2 - without bringing in tether reorg, otherwise this is multi sprint effort

**Comment by mhagen-vmware** [comment]
i think the fixes statement in you PR needs to be on 2 separate lines to auto close
