### ISSUE TITLE
Add support for the Docker compose compatibility test suite to our CI

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#4159]
As a user of VIC and docker compose, I should know what file format keywords have been tested against VIC.

Acceptance Criteria:  Robot scripts that verifies the Docker compose test fixtures (test compose files) works with VIC.

---

Compose test files are in github.com/docker/compose/tests.  The fixtures subfolder contains all the compose files.  There is a chance this will greatly increase our CI run time.  We may want to creating a new test suite to run these tests.  The goal is to verify compatibility.  Not all keywords are supported.

**Comment by rajanashok** [comment]
Link to the docker compose test fixtures.
https://github.com/docker/compose/tree/master/tests/fixtures
