### ISSUE TITLE
container output handler doesn't release output stream

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#4171]
The portLayer makes use of a custom handler to facilitate streaming to the client.  This [ContainerOutputHandler's](https://github.com/vmware/vic/blob/master/lib/apiservers/portlayer/restapi/handlers/interaction_handlers.go#L488) `WriteResponse` func will never release the output stream.  Even if the client closes the transport. This will eventually cause issues for the portLayer API.

The [EventHandler](https://github.com/vmware/vic/blob/master/lib/apiservers/portlayer/restapi/handlers/event_handlers.go#L114) makes use of a similar custom handler that will release the output stream when the client closes the transport.  

I suggest we refactor this bit of code to create a reusable streaming handler that that will be available to any portLayer handler that needs to stream data.  At a minimum the ContainerOutputHandler should be updated to release the stream.

**Comment by mhagen-vmware** [comment]
Please prioritize and move to backlog when ready.

**Comment by cgtexmex** [comment]
I will most likely fix this as part of my work on stats #3964 in sprint 4

**Comment by cgtexmex** [comment]
fixed by #4413
