### ISSUE TITLE
Security: VIC does not respect USER in Dockerfile

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4172]
Simple Dockerfile:

```
FROM debian:jessie

RUN useradd -d /home/vmware -m -s /bin/bash vmware
USER vmware
```

Run this on regular Docker:

```
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/dev-release$ docker run -it 10.118.69.100/test/noob-base
vmware@848f6fdf0e5b:/$ 
```

Run this on VIC:

```
vagrant@ubuntu-1604-vmware:~/test/noob$ docker run -it 10.118.69.100/test/noob-base
root@840603cf7882:/# 
```

It is recommendation 4.1 in https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.12.0_Benchmark_v1.0.0.pdf that containers should run as a non-root user. 

There are at least three scenarios where this is potentially problematic:

1) A base image is used containing data that should either not be read or executed by child images. VIC would run this, but with compromised security. 

2) VIC container creates output as root, rather than a specified user, which is then not accessible by other processes/loggers.

3) Container process in VIC overwrites data it shouldn't be able to

What's worse is that the customer may not be aware that we're ignoring this important directive.

**Comment by mhagen-vmware** [comment]
Please prioritize and estimate and move to backlog.

**Comment by corrieb** [comment]
I've made this high priority, because this has the potential to either be a security exposure for customers, or it may simply not run certain Docker Images because of permissions errors.

Guesstimated as a 3, since this should be a question of reading the metadata from the Image and getting Tether to run the process as the specified user.

**Comment by hickeng** [comment]
The user field is already present - this involves:
1. creating a user & group entry
2. create a home directory - could we use the configured working dir?
3. set the user in the container spec

We already launch appliance components as non-root user, but that's because we can control 1 & 2 easily.

**Comment by hmahmood** [comment]
@hickeng aren't (1.) and (2.) done in the docker file separately? Don't think if you just USER in docker file, we are expected to create and set up the user.

**Comment by hickeng** [comment]
@hmahmood Updated my prior comment to note the consistency requirements.
To answer your question, maybe - last time I looked at it was before the user mapping code went into docker.

Requiring consistency with IDs for volume permissions still needs to be addressed, no matter how this is done.

**Comment by hmahmood** [comment]
For consistency with volume permissions, that doesn't seem like something we should address -- it sounds like the dockerfile writer should be cognizant of that, and if the uids/gids are not consistent, then we just have fail gracefully. What particular use case do you have in mind?

**Comment by emlin** [comment]
Opened #4380 to track user creation requirement

**Comment by sflxn** [comment]
I think we need both #4380 and the check in Emma's PR to close this issue.  After chatting with Emma, without the creation part, docker will likely return an error as the user and group do not exist.

**Comment by corrieb** [comment]
@sflxn I'm not clear on the implications of what you're saying. I can't see anywhere in the Docker documentation on --user or USER that a user or group is created by the command.

**Comment by corrieb** [comment]
Long slack chat with @slfxn and I think we need to clarify exactly what's happening here.

USER in a Dockerfile presumes that a user has already been created in the Docker image that's being run. If not, you get the following error:
``docker: Error response from daemon: linux spec user: unable to find user vmware: no matching entries in passwd file.``

Docker run --user is the same. The user needs to exist already in the Docker image, or you'll get an error.

This is consistent with Docker's documentation. All we're aiming for here is feature parity with Docker engine behavior.

Trying out @emlin's fix, it works fine for the scenario described at the top of the issue, other than we try to run root's .bashrc, rather than the vmware one. In this example, /home/vmware/.bashrc exists, so I think we should be running it.

docker run -it 10.118.69.100/test/noob-base
bash: /root/.bashrc: Permission denied
vmware@86b7687942ea:/$

**Comment by corrieb** [comment]
Spoke to @hickeng about the /root/.bashrc issue. He said that it's because it's unclear what behavior we should be doing with respect to setting the HOME env var. There should be a wider discussion about this, because user HOME can be set in a variety of different ways. It would be better if we did set the HOME and ran the .bashrc, but that's a separate and far less urgent requirement.

**Comment by emlin** [comment]
thanks @corrieb for the clarification
