### ISSUE TITLE
Switch the CI default registry to a local harbor instance

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4181]
User statement: As an engineer on VIC, I would like us to be dog food testing our own products and improve the reliability and speed of our CI builds by having a local registry in which to pull images from

Details: Need to set up a Harbor instance with each of the images used in testing pushed into it, need to modify the install script to add the harbor instance as a whitelisted repo, then need to modify each of the tests to pull from the new registry

Acceptance criteria: CI build passes with most, if not all, of the tests pulling from the local harbor instance

**Comment by sflxn** [comment]
I updated priority to high as we need preinstalled Harbor instance in order to bring the whitelist tests into the automatic set (#5243).  That test dynamically installs Harbor, and I've seen that step take a very long time.  I did not add that test to the automatic set because I was afraid it would time out our CI runs.

**Comment by mhagen-vmware** [comment]
The initial work for this has been done in #4076 .  I am assigning myself for this as a placeholder, but I am going to have our new QE work on this when she starts on Tues. The only thing left for her is to go through the existing tests and switch them to pulling from our harbor instance.  @sflxn You can use the existing harbor now, but I believe you have both https and http tests?  So we will still need another harbor instance for http.  Although I am not sure how much we really want to do with that since as a company we have taken a stance that we don't support http anymore...
