### ISSUE TITLE
Move integration image from bintray to google cloud

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4182]
User statement: As an engineer on VIC, I need the integration image to be hosted in a location that is accessible and supported.

Details: We want to consolidate where we store our images and data, google cloud has been chosen.  We need to push the image over to google cloud and update all the links in the yml files and the secrets file

Acceptance criteria: All instances of the integration image are being pulled from google cloud.

**Comment by mdubya66** [comment]
let's confirm with @karthik-narayan that we want to do this.

**Comment by karthik-narayan** [comment]
@mhagen-vmware Is there a reason we are looking to make this change? Let's chat over email.

**Comment by mhagen-vmware** [comment]
@jakedsouza Once the PR is verified by QE and merged, the story can be closed.
