### ISSUE TITLE
Work up a doc on our agile process in the internal confluence page

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4184]
User statement: As an engineer on VIC, I would like an accessible location to learn and review our current agile process that we have agreed to and are using.

Details:  Put it in the engineering operations space in confluence under the VIC category.

Acceptance criteria: Our agile process is documented in confluence.

**Comment by rogeliosanchez** [comment]
Doc is now here: https://confluence.eng.vmware.com/display/VICP/Agile+for+VIC+Engine

**Comment by mhagen-vmware** [comment]
lgtm, nice job!
@rajanashok can you verify too please?

**Comment by rajanashok** [comment]
Nicely laid out, lgtm.
