### ISSUE TITLE
Move our existing internal google docs on CI information to our internal confluence

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4185]
User statement: As an engineer working on VIC, I would like an accessible location for our documents explaining the current CI infra

Details: Making this a larger story to capture: nightly, longevity, secrets, etc. Plus making a new arch doc that houses the rest of the docs and provides a brief explanation of the overall arch of our CI.

Acceptance criteria:  All CI related docs are now in our internal confluence

**Comment by rogeliosanchez** [comment]
Moved six documents to this space: https://confluence.eng.vmware.com/display/VICP/Continuous+Integration in confluence.

**Comment by mhagen-vmware** [comment]
lgtm, just needs the vpn info updated.   @rajanashok Can you give this a review as well please?

**Comment by rajanashok** [comment]
lgtm, @rogeliosanchez can we also add the nightly doc from this location pls?
https://docs.google.com/document/d/1M-oYglOyFJrnT1GOmBYzSvmJwvEX6QqBpw1UVm5uspw/edit

**Comment by rogeliosanchez** [comment]
Added the nightly builds doc this morning.

**Comment by mhagen-vmware** [comment]
lgtm
