### ISSUE TITLE
Move raw secrets file to our internal git repo

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4186]
User statement:  As an engineer on VIC, I want a place for our raw secrets file that can be properly versioned and eliminates some of the problems we have faced with multiple engineers overwriting the secrets improperly

Details: We have an internal git repo now that can house this.  Use the vic-internal one that Andrew setup.

Acceptance criteria: Raw secrets file is now housed on git and no longer can be found in google docs.

**Comment by anchal-agrawal** [comment]
#4030 is likely a dup of this.

**Comment by mhagen-vmware** [comment]
Hey @jakedsouza , sorry for the whiplash but as the secrets file will be going away with the move to drone .5 anyways this story only buys us a couple weeks of change.  After discussing with Matt, it is probably not worth spending any time at all on.

**Comment by jakedsouza** [comment]
@mhagen-vmware While 0.5 will not require us to manage this file. I think we should still complete this task for the following reasons 

1. 0.5 is still a few weeks away and this change will add some consistency to how we manage the secrets 
2. Even with 0.5, it is still nice to have an up-to-date secrets file for secrets that need to change. Drone secrets management does not let us see the secret values. E.g our test url list, this information needs to be documented somewhere other than in drone 
3. It is easy to do

**Comment by mhagen-vmware** [comment]
Agreed, good points!

**Comment by jakedsouza** [comment]
secrets are not hosted on internal repo.
