### ISSUE TITLE
Use a dedicated host for UI integration tests for Ubuntu and macOS

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#4190]
As a UI engineer I would like to have persistent Selenium Grids for integration testing. Currently I run UI tests against Windows and Ubuntu which are hosted on Nimbus. Now that there's a Mac Mini dedicated for testing VIC UI on macOS, I would like to put more tests into the matrix as well as move away from Nimbus to use a Ubuntu 16.04 VM on the Mac Mini.

Acceptance Criteria:
1. For testing against Ubuntu, I should get the same results on the Mac Mini as the current Ubuntu VM hosted on Nimbus
2. For testing against macOS, I should successfully launch tests for Firefox and Chrome. There is a restriction in Safari that doesn't allow the SafariDriver to bypass a unsigned SSL certificate. This could be resolved by using Apple Script but it will be addressed in another PR later.

**Comment by mhagen-vmware** [comment]
Why is this not in Sprint 4 milestone?  Nor does it have an estimate.

**Comment by jooskim** [comment]
Well, I originally had a feature to be implemented in Sprint 4 and that got blocked for a constraint from the H5 Client. I had to make a change of plan to instead working on test infra for UI.

**Comment by jooskim** [comment]
FYI, all test stuff is not even part of vmware/vic repo. It's under a private repo as Matt suggested before. I simply had to make this PR to update two lines in the robot file.

**Comment by jooskim** [comment]
For the sake of consistency I could take this back to backlog now if it works for you.

**Comment by mhagen-vmware** [comment]
Nope, if you are working on it - then it should be in the sprint.
