### ISSUE TITLE
container hostname - implement docker run -h

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#4195]
User statement:  As a customer of VIC, I would like to set a custom hostname on a container a runtime using docker run -h option.

Details: Is it possible to define the hostname of the container during docker run instead of the 12 character UUID? Note the container is attached to a container network (i.e. vch created with --cn) and it receives an ip (i.e. vch created with --cnr)from the predefined range.

Pardon me if this has been answered elsewhere. I did search before posting here...

Acceptance criteria:  Implemented and robot test cases that cover integration testing of the new feature.

**Comment by mhagen-vmware** [comment]
Are you asking us to implement docker run -h myhostname?

**Comment by malikkal** [comment]
Would be great if docker run -h 'myhostname' works. But, if feature implementation takes time, could you suggest a workaround, please? We are going live in productions soon; real soon.. and this would be good to have for certain applications...

**Comment by malikkal** [comment]
passing hostname as an argument during docker run using --entrypoint and using this in the entrypoint shell script helps. But, is this right to do this?

docker -H IP:2376 --tls run -itd --cpuset-cpus 8 --memory 16g --name myname --entrypoint /home/user/myentry.sh --net mynet01 IP:443/library/image:version tsthstnm001

#!/bin/sh

if [ $# -eq 0 ]
   then
      echo "No arguments supplied; will use default container id as hostname."
   else
      echo "Setting hostname..."
      echo "127.0.0.1   localhost    localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
      echo "::1         localhost    localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
      hostname $1
      echo $1 > /etc/hostname
fi

**Comment by mhagen-vmware** [comment]
Yea, unfortunately there isn't a great way to do it in docker outside of the entrypoint script like you have done since we have not implemented -h just yet.

@hmahmood Can you help me estimate the effort involved in implementing docker run -h?

**Comment by mhagen-vmware** [comment]
If you just want to interact with them between containers, you can also use --name on the container then you can ping that name from a different container. Like here:
https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot#L68

https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot#L75

**Comment by hmahmood** [comment]
@mhagen-vmware 3 seems fine for this.

**Comment by malikkal** [comment]
Thank you. I understand that we could use --name for resolution between containers. In the interim, I will use the --entrypoint script to pass argument for setting hostname.

**Comment by casualjim** [comment]
There are other tools that depend on the content of /etc/hostname being right

**Comment by stuclem** [comment]
@mhagen-vmware according to @malikkal in https://github.com/vmware/vic/issues/4228, `docker run -h` now works in 1.3. Was this implemented afterall? Thanks!

**Comment by hmahmood** [comment]
@stuclem it looks like it was: https://github.com/vmware/vic/pull/6074

**Comment by anchal-agrawal** [comment]
Looks like this is implemented (see https://github.com/vmware/vic/issues/4228#issuecomment-359977533). Closing since the acceptance criteria has been satisfied.

**Comment by stuclem** [comment]
Doc update is in https://github.com/vmware/vic-product/pull/1326
