### ISSUE TITLE
Investigate options and benefits of diskless appliance

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#42]
The appliance must be capable of being restarted while containers are running. The raises a number of questions about the impact this has: 
- Interactivity with the containers - what control points should continue to work?
- Whether the appliance can be stateless (see diskless discussion)
- What state the appliance must re-discover and how/where it gets it from
- What if the appliance has migrated to a new ESX host? 
- How does it re-authenticate?
- Do custom attributes on the VM have a role to play?

The Bonneville appliance has a local disk as well as a ramdisk. It may be beneficial to see if we can make the VIC appliance "diskless" - have it boot off the ISO and then have everything else written into memory. The main question marks around this are:
- What are the benefits? What do we write to the local disk today and does it need to be persisted?
- Can we go stateless with the appliance? When it gets restarted, can it discover everything it needs?
- Where does Docker container / image metadata live?

**Comment by mdubya66** [comment]
@hickeng I think this one can be closed?
