### ISSUE TITLE
Group8-vsphere integration - all the tests have govc calls that need to test for VC

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4202]
```
18:58:38.735 	INFO 	Running command 'govc vm.ip VCH-0-1854 2>&1'. 	
18:58:38.822 	INFO 	${ip} = govc: vm 'VCH-0-1854' not found
```

All of these calls need to be modified to work for VC.

**Comment by dougm** [comment]
@mhagen-vmware they should not need changes with govc 0.13 - it looks inside Folders and VApps for VMs by default now.

**Comment by mhagen-vmware** [comment]
resolved with update to govc
