### ISSUE TITLE
network create

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#421]
The ability to create a network scope via the `docker network create` command.

This encompasses the creation of the default 'bridge' network by Docker personality if not already present.
Thought should be given during implementation to how to use existing network if this is VCH restart, but is not core to the epic.

Target:
 Docker API support for network create
 Port Layer API support for network.create
 Basic IPAM mechanism with IPAM config stored in guestinfo (#402)

**Comment by hickeng** [comment]
@hmahmood is this complete now the child issues are closed?

**Comment by mdubya66** [comment]
Adding to Docker Command Epic #889
