### ISSUE TITLE
Nginx container stuck in Starting mode

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4212]
#For bug reports, please include the information below:

**VIC version:**v0.8.0-0-8575c8c

master, commit id: e29e98c

Nginx stuck in starting mode:

[lcastellano(718) vic (props)]$ docker ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                          NAMES
26c7c4efc9c7        nginx                "nginx -g daemon off;"   15 minutes ago      Starting            10.192.48.162:9080->80/tcp     docker-nginx
d4ab933c7853        vmware/admiral:dev   "/entrypoint.sh"         26 minutes ago      Up 26 minutes       10.192.48.162:8282->8282/tcp   admiral

[logs (1).zip](https://github.com/vmware/vic/files/832814/logs.1.zip)
[container-logs (1).zip](https://github.com/vmware/vic/files/832815/container-logs.1.zip)

**Comment by anchal-agrawal** [comment]
From a glance at the portlayer logs, this looks similar to #3315.

**Comment by lcastellano** [comment]
I just saw this message scrolling back in my window: 

docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.192.44.113/sdk: context deadline exceeded.

**Comment by anchal-agrawal** [comment]
@lcastellano This looks like a dup of #3315; I'm closing it. Thanks!
