### ISSUE TITLE
Root Password expired when trying to remote access to a VCH after setting debug mode

### ISSUE THREAD

**Issue by fduranti** [vmware/vic#4214]
I've enabled the debug mode, enabled ssh and setup a root password but I'm not able to login to the vic. It seems that the password is not recognized.
I've tried to send an "authorized_keys" file for my user to be able to login without password but I get asked for a password to be changed so it seems that the VCH root password expire and the debug command is not able to automatically change it.
I've also done  a reboot of the VCH.

command to setup: 
```
[] # vic-machine-linux debug --target 'vcenter'/'Datacenter' --user 'admin@domain' --password 'adminpw' --compute-resource 'Cluster'/'Resource Pool' --thumbprint 'thumbprint' --name 'vchhostname' --authorized-key authorized_keys -pw 'root' --enable-ssh
INFO[2017-03-10T12:22:42+01:00] ### Configuring VCH for debug ####           
INFO[2017-03-10T12:22:43+01:00]                                              
INFO[2017-03-10T12:22:43+01:00] VCH ID: VirtualMachine:vm-115919             
INFO[2017-03-10T12:22:43+01:00]                                              
INFO[2017-03-10T12:22:43+01:00] Installer version: v0.8.0-7315-c8ac999       
INFO[2017-03-10T12:22:43+01:00] VCH version: v0.8.0-7315-c8ac999             
INFO[2017-03-10T12:22:43+01:00]                                              
INFO[2017-03-10T12:22:43+01:00] SSH to appliance:                            
INFO[2017-03-10T12:22:43+01:00] ssh root@ip
INFO[2017-03-10T12:22:43+01:00]                                              
INFO[2017-03-10T12:22:43+01:00] VCH Admin Portal:                            
INFO[2017-03-10T12:22:43+01:00] https://ip:2378                     
INFO[2017-03-10T12:22:43+01:00]                                              
INFO[2017-03-10T12:22:43+01:00] Published ports can be reached at:           
INFO[2017-03-10T12:22:43+01:00] ip                                  
INFO[2017-03-10T12:22:43+01:00]                                              
INFO[2017-03-10T12:22:43+01:00] Docker environment variables:                
INFO[2017-03-10T12:22:43+01:00] DOCKER_HOST=ip:2375                 
INFO[2017-03-10T12:22:43+01:00]                                              
INFO[2017-03-10T12:22:43+01:00] Connect to docker:                           
INFO[2017-03-10T12:22:43+01:00] docker -H ip:2375 info              
INFO[2017-03-10T12:22:43+01:00] Completed successfully                       

[] # ssh ip
You are required to change your password immediately (password aged)
Last login: Fri Mar 10 10:48:25 2017 from -----------
Changing password for root.
(current) UNIX password: 
Connection to ip closed.
```

**VIC version:**

v0.8.0-7315-c8ac999       

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

**Steps to reproduce:**
Not sure as the problem arise after the root password expire (not sure how it's setup)

**Actual behavior:**
When logging in with ssh using authorized_keys I get asked to change password. 
Changing password with vic-machine don't work (the password I set is not recognized).

**Expected behavior:**
Begin able to login to vic with ssh or console.

** Logs **
Running the command to setup ssh/enable authorization_keys/changing root password I get this output in the initialization & watchdog logs:
```
time="2017-03-10T11:37:14Z" level=error msg="Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n" 
time="2017-03-10T11:37:14Z" level=error msg="Failed to enable shell: Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n" 
time="2017-03-10T11:37:14Z" level=info msg="Attempted to start ssh service:\n %s{[] 0 [0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0}" 
time="2017-03-10T11:37:14Z" level=error msg="Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n" 
time="2017-03-10T11:37:14Z" level=error msg="Failed to enable shell: Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n" 
```

**Comment by mdubya66** [comment]
I am also unable to change the password on my ESX running in fusion. VIC Engine GA 0.8.0 version. 

```(mwilliamson) ib-aus-office-137:~/Downloads/vic-ga $  ./vic-machine-darwin debug -target 172.16.127.196 -user root --password 'password' --thumbprint FA:41:58:37:DB:11:C9:6A:74:64:73:28:1F:F9:40:CF:10:35:5F:C3 --ssh --name vic-ga
INFO[2017-03-10T13:09:10-06:00] ### Configuring VCH for debug ####
INFO[2017-03-10T13:09:10-06:00]
INFO[2017-03-10T13:09:10-06:00] VCH ID: VirtualMachine:130
INFO[2017-03-10T13:09:10-06:00]
INFO[2017-03-10T13:09:10-06:00] Installer version: v0.8.0-7315-c8ac999
INFO[2017-03-10T13:09:10-06:00] VCH version: v0.8.0-7315-c8ac999
WARN[2017-03-10T13:09:11-06:00] Unable to identify address acceptable to host certificate
INFO[2017-03-10T13:09:11-06:00]
INFO[2017-03-10T13:09:11-06:00] SSH to appliance:
INFO[2017-03-10T13:09:11-06:00] ssh root@172.16.127.211
INFO[2017-03-10T13:09:11-06:00]
INFO[2017-03-10T13:09:11-06:00] VCH Admin Portal:
INFO[2017-03-10T13:09:11-06:00] https://172.16.127.211:2378
INFO[2017-03-10T13:09:11-06:00]
INFO[2017-03-10T13:09:11-06:00] Published ports can be reached at:
INFO[2017-03-10T13:09:11-06:00] 172.16.127.211
INFO[2017-03-10T13:09:11-06:00]
INFO[2017-03-10T13:09:11-06:00] Docker environment variables:
INFO[2017-03-10T13:09:11-06:00] DOCKER_HOST=172.16.127.211:2376
INFO[2017-03-10T13:09:11-06:00]
INFO[2017-03-10T13:09:11-06:00] Connect to docker:
INFO[2017-03-10T13:09:11-06:00] docker -H 172.16.127.211:2376 --tls info
INFO[2017-03-10T13:09:11-06:00] Completed successfully
(mwilliamson) ib-aus-office-137:~/Downloads/vic-ga $ ssh root@172.16.127.211
The authenticity of host '172.16.127.211 (172.16.127.211)' can't be established.
ECDSA key fingerprint is SHA256:0cE1/Hw44GExTaF5L16zxlWyc4E0aT4bFY6i4AOq9X4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.16.127.211' (ECDSA) to the list of known hosts.
Password:
You are required to change your password immediately (password aged)
Changing password for root.
(current) UNIX password:
New password:
BAD PASSWORD: it is based on a dictionary word

Password:
Password:
root@172.16.127.211's password:
You are required to change your password immediately (password aged)
Changing password for root.
(current) UNIX password:
Connection to 172.16.127.211 closed.
(mwilliamson) ib-aus-office-137:~/Downloads/vic-ga $```

[container-logs.zip](https://github.com/vmware/vic/files/834910/container-logs.zip)

**Comment by mdubya66** [comment]
debug login works on with VIC B8351.  The v0.9.0 candidate.

(mwilliamson) ib-aus-office-137:~/Downloads/vic-8351 $  ./vic-machine-darwin debug -target 172.16.127.196 -user root --password 'password' --thumbprint FA:41:58:37:DB:11:C9:6A:74:64:73:28:1F:F9:40:CF:10:35:5F:C3 --ssh --name vic-v09
Mar 10 2017 13:17:12.248-06:00 INFO  ### Configuring VCH for debug ####
Mar 10 2017 13:17:12.411-06:00 INFO  Validating target
Mar 10 2017 13:17:12.465-06:00 WARN  Disabling ha-host hostd.log collection (ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.)
Mar 10 2017 13:17:12.465-06:00 INFO
Mar 10 2017 13:17:12.465-06:00 INFO  VCH ID: VirtualMachine:131
Mar 10 2017 13:17:12.474-06:00 INFO
Mar 10 2017 13:17:12.474-06:00 INFO  Installer version: v0.8.0-8351-f5d2542
Mar 10 2017 13:17:12.474-06:00 INFO  VCH version: v0.8.0-8351-f5d2542
Mar 10 2017 13:17:12.867-06:00 WARN  Unable to identify address acceptable to host certificate
Mar 10 2017 13:17:12.867-06:00 INFO
Mar 10 2017 13:17:12.867-06:00 INFO  SSH to appliance:
Mar 10 2017 13:17:12.867-06:00 INFO  ssh root@172.16.127.212
Mar 10 2017 13:17:12.867-06:00 INFO
Mar 10 2017 13:17:12.867-06:00 INFO  VCH Admin Portal:
Mar 10 2017 13:17:12.867-06:00 INFO  https://172.16.127.212:2378
Mar 10 2017 13:17:12.867-06:00 INFO
Mar 10 2017 13:17:12.867-06:00 INFO  Published ports can be reached at:
Mar 10 2017 13:17:12.867-06:00 INFO  172.16.127.212
Mar 10 2017 13:17:12.867-06:00 INFO
Mar 10 2017 13:17:12.867-06:00 INFO  Docker environment variables:
Mar 10 2017 13:17:12.867-06:00 INFO  DOCKER_HOST=172.16.127.212:2376
Mar 10 2017 13:17:12.867-06:00 INFO
Mar 10 2017 13:17:12.867-06:00 INFO  Connect to docker:
Mar 10 2017 13:17:12.867-06:00 INFO  docker -H 172.16.127.212:2376 --tls info
Mar 10 2017 13:17:12.867-06:00 INFO  Completed successfully
(mwilliamson) ib-aus-office-137:~/Downloads/vic-8351 $ ssh root@172.16.127.212
The authenticity of host '172.16.127.212 (172.16.127.212)' can't be established.
ECDSA key fingerprint is SHA256:8JspmTT1+JkvS4MZ0y8zECYLjDTBDz5sH5BE3PHeZVE.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.16.127.212' (ECDSA) to the list of known hosts.
Password:
root@vic-v09 [ ~ ]#

[container-logs (1).zip](https://github.com/vmware/vic/files/834923/container-logs.1.zip)

**Comment by mdubya66** [comment]
This appears to be resolved in 
https://bintray.com/vmware/vic/Download/v0.9.0 or https://bintray.com/vmware/vic/Download/v1.1.0-rc2

Keeping this open for root causing the original issue in v0.8.0 and for testing purposes @mhagen @hickeng

**Comment by mdubya66** [comment]
This might not be resolved. Current thinking from @hickeng is this is related to the password aging due to the date the iso's are generated. He will dig in further. 

``` ./vic-machine-darwin debug -target 172.16.127.196 -user root --password 'password' --thumbprint FA:41:58:37:DB:11:C9:6A:74:64:73:28:1F:F9:40:CF:10:35:5F:C3 --name vic-ga --rootpw password3```

generated this in the tether.debug log

```time="2017-04-06T17:33:55Z" level=error msg="Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n"
time="2017-04-06T17:33:55Z" level=error msg="Failed to enable shell: Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n"
time="2017-04-06T17:33:55Z" level=warning msg="Reaped zombie process PID 307"
time="2017-04-06T17:34:03Z" level=error msg="Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n"
time="2017-04-06T17:34:03Z" level=error msg="Failed to enable shell: Expected line to end with /bin/bash: root:x:0:0:root:/root:/bin/false\n"
time="2017-04-06T17:34:03Z" level=info msg="Attempted to start ssh service:\n %s{[] 0 [0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0}"```

**Comment by mdubya66** [comment]
This is definitely not fixed in the latest releases. @hickeng suspected the forced password aging so I set my ESXi host date to March 14, 2018 and re-ran against v.1.1.0-rc2 and ran into the same issue seen in v0.8.0.

```mwilliamson) dubs:~/Downloads/vic-rc2 $ ssh root@172.16.127.214
The authenticity of host '172.16.127.214 (172.16.127.214)' can't be established.
ECDSA key fingerprint is SHA256:AcPVktUd/kSvk1hIOIiGOC/eqVFmIAhvblZ3454mLy4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.16.127.214' (ECDSA) to the list of known hosts.
Password:
You are required to change your password immediately (password aged)
Changing password for root.
(current) UNIX password:```

**Comment by hickeng** [comment]
The portion of the command that's failing is enabling a login shell for the user:
```
chsh: PAM: Authentication token is no longer valid; new one required
```

The code fails past this and attempts to set the password anyway when using `--rootpw` but even `chpasswd` gives the same error:
```
root@ [ ~ ]# /sbin/chpasswd root:password
You are required to change your password immediately (password aged)
chpasswd: PAM: Authentication token is no longer valid; new one required
```
