### ISSUE TITLE
Document docker run -h

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#4228]
Per https://github.com/vmware/vic/issues/4195

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #508](https://github.com/vmware/vic-product/issues/508) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stuclem** [comment]
@malikkal that's very odd. I was convinced that we updated the doc. I will investigate whether that change failed to merge.

**Comment by stuclem** [comment]
@malikkal actually, I spoke too soon. It looks like this was not implemented in 1.3.0. The engineering effort is tracked in https://github.com/vmware/vic/issues/4195, which is still open.

**Comment by malikkal** [comment]
Thanks @stuclem. interesting though, it works on 1.3.x.

**Comment by stuclem** [comment]
@malikkal strange. I asked for an update in https://github.com/vmware/vic/issues/4195.

**Comment by anchal-agrawal** [comment]
@malikkal Indeed - PR https://github.com/vmware/vic/pull/6074 was supposed to close the `docker run -h` [issue](https://github.com/vmware/vic/issues/4195) (https://github.com/vmware/vic/pull/6074#issuecomment-324034694). We've also got integration test for this: https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot#L180.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #1325](https://github.com/vmware/vic-product/issues/1325) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stuclem** [comment]
Doc update is in https://github.com/vmware/vic-product/pull/1326
