### ISSUE TITLE
Move node install code from the drone.yml into the integration image

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4230]
This is slowing down builds installing every time:

      - curl -sL https://deb.nodesource.com/setup_7.x | bash -
      - apt-get install -yq nodejs

**Comment by mhagen-vmware** [comment]
@jakedsouza Why did you re-open this?

**Comment by jakedsouza** [comment]
@mhagen-vmware  the issue got closed by github, I moved it to the verify pipeline.

**Comment by mhagen-vmware** [comment]
@jakedsouza Ok, np.  But once you have me or Ashok LGTM on the PR you can let github close the parent issue or close it yourself. Thanks!
