### ISSUE TITLE
Receive and integrate events from VIC engine into containerd runtime plugin.

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#4236]
Containerd expects to receive events from container when something happens to container: CREATED, RUNNING, STOPPED, DELETED. Recently, related functionality has been added into port layer, so container runtime plugin can listen to those events and update container status accordingly so systems stays consistent.

Due to containerd event subsystem is incomplete, it might be hard to get any useful results and it may lead to extra development in containerd side.

Acceptance criteria
-------------------

Containerd runtime listens to events from portlayer and changes container status accordingly.

**Comment by mhagen-vmware** [comment]
@vburenin Please migrate this to new project that we discussed
