### ISSUE TITLE
container with multiple networks

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#424]
Create a container that is attached to multiple networks and can communicate with containers on each of those networks successfully. The networks should not have overlapping scopes to ensure that we're correctly configuring routing in the container.

**Comment by corrieb** [comment]
@hmahmood By the looks of it, we should be good to get this in for onsite. Is there a clear plan for the integration tests that will be needed to test this?

**Comment by hmahmood** [comment]
@corrieb #693 should cover the integration tests portion.

**Comment by mdubya66** [comment]
Moving to Doc for GA as that is the only remaining issue
