### ISSUE TITLE
Failed to write to image store parentMap.tmp was not found

### ISSUE THREAD

**Issue by vivek-parikh** [vmware/vic#4243]
docker: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc42095ef08 Message:File /vmfs/volumes/53061925-77305773-73ad-74867ae3d1ae/VCH02/VIC/564d9379-ab62-acac-5931-06df153c5794/parentMap.tmp was not found}.

#For bug reports, please include the information below:

**VIC version:**

v0.8.0-7315-c8ac999

**Deployment details:**

./vic-machine-linux create --user root -t '10.112.200.227' --name VCH02 --no-tlsverify --no-tls --force

**Steps to reproduce:**
docker -H 10.112.201.244:2375 run -it bash

**Actual behavior:**
bash should run, container should be created

**Expected behavior:**
Error. Container is not getting created

**Logs:**

[vicadmin.txt](https://github.com/vmware/vic/files/841195/vicadmin.txt)
[docker-personality.txt](https://github.com/vmware/vic/files/841198/docker-personality.txt)
[init.txt](https://github.com/vmware/vic/files/841196/init.txt)
[port-layer.txt](https://github.com/vmware/vic/files/841197/port-layer.txt)

**Additional details as necessary:**

**Comment by fdawg4l** [comment]
@vivek-parikh can you tell us a bit more about your installation? Are you using vcenter?  What kind of datastore is this (iscsi, nfs, etc)?  From the logs, it looks like this is a new VIC instance that was just installed but I'm seeing some files already exist so I'm not certain.  

Also, if you could grab the log bundle from the admin interface (it will download a zip file which includes the vmware.log of the virtual container host), and attach it here, that would be great.  Thanks!

**Comment by vivek-parikh** [comment]
I'm not using vcenter.  Datastore is of type nfs. 
Yes the vic was just installed. Already existing files might be due to past vic installations and re-installations

I did not find vmware.log file in logs.zip or container-logs.zip (downloaded through vic web interface)

**Comment by vivek-parikh** [comment]
Had to create a silly workaround:

I manually uploaded parentMap.tmp to VCH01/VIC/ID directory but it was getting renamed to parentMap and hence a complaint of .tmp not being found. I placed a shell script there(through sshing into ESX) which did this:

`#!/bin/sh
while [ true ]
do
    touch parentMap.tmp
done
`
No errors after that. +1 for race condition. 

Also I believe this might have something to do with the datastore name that we have, "datastore (1)"

**Comment by fdawg4l** [comment]
@vivek-parikh you, obvioulsy, shouldn't need to create a shell script to do that.  Clearly something is amiss either in our code, the API we're using, or something else.

In any case, the `.tmp` file is a temporary file and is moved to it's final location after the upload to the datastore is complete.  The loop which is complaining is uploading the tmp file, then complaining the file it just uploaded can't be found.  We don't mount the datastore and have to use the webservice to get to it.  Effectively it's

`touch file && ls -l file`

but with the webservice doing the filesystem indirection.  I'm suspecting esx is doing the upload operation asynchronously from the other. Or, like you suggest, the datastore path name including a parenthesis is having a weird affect on pathing.

I'll try to recreate your setup using the same datastore name and get back to you.

**Comment by fdawg4l** [comment]
```
$ ./vic-machine-linux create -t $GOVC_URL --tls-cname 10.118.67.227 --thumbprint=XXXXX --image-store datastore1\ \(1\)/images -k
Mar 15 2017 14:35:52.994-07:00 INFO  ### Installing VCH ####
...
Mar 15 2017 14:36:17.395-07:00 INFO  Installer completed successfully

$ docker -H 10.118.67.222:2375 info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: v0.8.0-0-5f81072
Storage Driver: vSphere Integrated Containers v0.8.0-0-5f81072 Backend Engine
VolumeStores: 
vSphere Integrated Containers v0.8.0-0-5f81072 Backend Engine: RUNNING
 VCH CPU limit: 3770 MHz
 VCH memory limit: 12.72 GiB
 VCH CPU usage: 0 MHz
 VCH memory usage: 0 B
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.5.0
Execution Driver: <not supported>
Plugins: 
 Volume: 
 Network: bridge
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 3770
Total Memory: 12.72 GiB
Name: virtual-container-host
ID: vSphere Integrated Containers
Docker Root Dir: 
Debug mode (client): false
Debug mode (server): false
Registry: registry-1.docker.io


$ docker -H 10.118.67.222:2375 pull busybox
Using default tag: latest
Pulling from library/busybox
7520415ce762: Extracting [==================================================>] 677.6 kB/677.6 kB
a3ed95caeb02: Download complete 
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:File /vmfs/volumes/58c9a7ad-5956a4bb-3f8f-000c29fc3e5f/images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/parentMap.tmp was not found}
```

Looks like I can repro this locally.  And when using a datastore name without paranthesis, it works as expected.

**Comment by fdawg4l** [comment]
@vivek-parikh the workaround for now is to use a datastore without a parenthesis in the name until we can get a code fix in to avoid the issue.

**Comment by fdawg4l** [comment]
```
# find .

./images
./images/VIC
./images/VIC/564d3516-8e79-491b-79d2-caa5effef36b
./images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images
./images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images/scratch
./images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images/scratch/imageMetadata
./images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images/scratch/scratch-flat.vmdk
./images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images/scratch/scratch.vmdk
./(1)] images
./(1)] images/VIC
./(1)] images/VIC/564d3516-8e79-491b-79d2-caa5effef36b
./(1)] images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images
./(1)] images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images/scratch
./(1)] images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/images/scratch/manifest
./(1)] images/VIC/564d3516-8e79-491b-79d2-caa5effef36b/parentMap.tmp
```

Looks like the datastore helper is rooting all of the files in the mangled images directory.

**Comment by fdawg4l** [comment]
Found it.  This is....  embarrassing.

https://github.com/vmware/vic/blob/master/pkg/vsphere/datastore/datastore.go#L327
```
326 // Return the root of the datastore path (without the [datastore] portion)                                                                                                                                                                                                                                                                                                                                                           
327 func (d *Helper) rootDir() string {                                                                                                                                                                                                                                                                                                                                                                                                  
328 »···return strings.SplitN(d.RootURL, " ", 2)[1]                                                                                                                                                                                                                                                                                                                                                                                      
329 } 
```

**Comment by mhagen-vmware** [comment]
What is the state of this issue?  It looks like the code has already been merged but neither I nor Ashok verified?

**Comment by fdawg4l** [comment]
@mhagen-vmware That's right. Code is merged and I thought you may want to verify it.

**Comment by mhagen-vmware** [comment]
Well, the process is actually to verify before merging.. In this case, I think that the 2 unit tests mods look good enough.  Thanks!
