### ISSUE TITLE
Research Spike: VAC integration for OVA appliance

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4250]
User Statement: Want to track usage of the OVA Appliance, if the user has given consent.

Acceptance Criteria: Design for supporting Phone Home (VAC) with granular properties about what is currently installed in the appliance

**Comment by mdubya66** [comment]
Given this is our last sprint for 1.1 features I asked @mhagen-vmware to lower this priority. We will need to pull it into the 1.2 release.

**Comment by andrewtchin** [comment]
Need to figure out how to have a property collector process running in OVA

**Comment by mdubya66** [comment]
Not sure this is a 1.2 topic. I don't see it in the PM ask. Let's make it opportunistic.

**Comment by andrewtchin** [comment]
That's true, removed 1.2 label

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #911](https://github.com/vmware/vic-product/issues/911) via [**ZenHub**](https://www.zenhub.com/)
