### ISSUE TITLE
Create small web app for vic-machine download and vic-ui hosting for OVA appliance

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4254]
User Statement: 

- Want to be able to download current `vic-machine` installer locally, without internet access.
- Want to be able to install vic-ui easily.

Acceptance Criteria: Must support download of the vic-machine version shipped with the OVA, must support install workflow of the vic-ui plugin via vCenter

**Comment by jooskim** [comment]
Additional requirements:

Web server should always use HTTPS connection with its SHA-1 fingerprint handy. This could be hardcoded into the installer script, or even more advanced solution is that `vic-ui install` will all take care of it so that there will be no need for any shell scripts.

**Comment by andrewtchin** [comment]
Which installer script needs the fingerprint? I don't think it could be hardcoded because that would mean every install would have the same cert
Customers would probably also want to be able to use their own cert as an option

**Comment by jooskim** [comment]
Fingerprint has to be supplied as a flag for extension registration with VC. `--thumbprint` for `vic-ui` to be specific. So that's going to be based off of the certificate of the OVA appliance I suppose.

**Comment by andrewtchin** [comment]
- [ ] Create webserver to display directory listing of `vic-machine`, `vic-ui`, `plugin-packages/com.vmware.vic-0.8.0.zip`, and `vsphere-client-serenity/om.vmware.vic.ui-0.8.0.zip`
- [ ] Modify OVA to put binaries on the filesystem
- [ ] Use self signed certs
