### ISSUE TITLE
libnetwork with NSX

### ISSUE THREAD

**Issue by casualjim** [vmware/vic#4255]
As a user I want to be able to create networks for docker libnetwork which are backed by NSX
As an admin I want to be able set security policies for networks managed through libnetwork

We want to create a docker swarm and have them connect the nodes to overlay networks managed by NSX

* Create a docker swarm 
* Run a helloworld service with 2 or 3 replicas on a private network segment
* Have every container show up as an individual segment
* Run a load balancer that exposes the containers through a routable IP

**Comment by mhagen-vmware** [comment]
No assignees or milestone in the backlog, and needs a priority please.  Looks like medium.

**Comment by casualjim** [comment]
this was executed, closing
