### ISSUE TITLE
Maintenance mode should not shut down container with active attach sessions

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#4258]
As a VIC admin, I want to be able to put hosts into maintenance mode and have container workloads vMotioned off that host, regardless of the attach status of the container.

As a VIC user, I don't want my containers to shut off without my knowledge.

Problem Statement
Problem currently is that an open serial port inhibits vMotion of a VM. When a user attaches to a containerVM, they open a connection to the serial port. Once vMotion is triggered, there is no way to re-configure the VM to detach the connection. Even if the user detaches, the pending vMotion still prevents disconnection of the serial port. To solve that issue we introduced auto shutdown on the maintenance event (63fd97ed5864bfa78a2dad1f7c203a2c65566ad1). That patch needs to be reverted

Acceptance Criteria:

Show that putting host a maintenance mode does not shut down container with attach sessions and instead blocks the maintenance mode

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
please don't merge things before they are verified.
