### ISSUE TITLE
Add internal disk manager call to get parents to govmomi

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#4259]
I don't remember the call name.  Will add it when I find it again.  It's an internal method and returns all of the information for a given vmdk which includes its lineage of parents.

**Comment by dougm** [comment]
vmware/govmomi#686

**Comment by mhagen-vmware** [comment]
What is the state of this issue?  It looks like the code has already been merged but neither I nor Ashok verified?

**Comment by fdawg4l** [comment]
@mhagen-vmware the merged code is internal to our product. Verifying externally won't be possible.

**Comment by dougm** [comment]
Both this change and the previous vendor/govmomi update (for metrics) can be verified, but only with govc commands and bats tests - since there isn't VIC code calling the new APIs yet.  What do you prefer to do in these cases @mhagen-vmware ?

**Comment by mhagen-vmware** [comment]
In this case, just tagging our story where we plan on using the new calls would be good.  Thanks!
