### ISSUE TITLE
Migrate from using parentMap to using internal disk method for parents

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#4261]
We're using the parentMap in the vsphere storage layer to keep track of which disk delta disks are children of which parent.  This was a temporary solution, but in order to get away from direct datastore access via GET/PUT, using the vsphere disk apis to get this information is preferable.

**Comment by fdawg4l** [comment]
This epic will avoid #4243 all together.

**Comment by hickeng** [comment]
@fdawg4l Thought you said this was done in conversation yesterday - can you close it if so, with reference to the PR. If it's still open then please add enough detail to get this or sub-issues into backlog to be worked on.

**Comment by fdawg4l** [comment]
#4367
