### ISSUE TITLE
Container logs are not displayed in Admiral

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4265]
**User Statement:**
Since we are not implementing the container log option "--since", we need a workaround for Admiral to display the log content.

**Details:**
The workaround can either be implemented in Admiral (retry without --since) or VIC (ignore the --since flag). In either case Admiral and VIC need to be tested in combination.

**Acceptance Criteria:**
Admiral should display container logs for containers running on a VCH

**Comment by AntonioFilipov** [comment]
#https://github.com/vmware/admiral/issues/59

**Comment by anchal-agrawal** [comment]
`docker logs --since` was implemented in https://github.com/vmware/vic/pull/5340.
