### ISSUE TITLE
Implement test for vmwarecna/nginx

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4274]
User statement:
As a customer of VIC, I would like to know that VMware's version of nginx image with photon OS splash screen has been tested and works with VIC.

Details:
docker pull vmwarecna/nginx

Acceptance Criteria:
1. New test is implemented and runs in either nightly or CI.

**Comment by mhagen-vmware** [comment]
related #4285

**Comment by lateagain** [comment]
It already fails to start if you install all the updates to photon. 
Downgrade linux and initramfs to the original versions and it'll run again.

**Comment by mhagen-vmware** [comment]
doesn't appear to be supported anymore, no need to ensure this works
