### ISSUE TITLE
Ensure that runblocking is configured anew for each container start

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4296]
**Story**
As a docker API user calling start I expect the container process to launch when the container starts
As a docker API user calling attach before start I expect to receive _all_ of the container process output

**Detail**
We have a mechanism called runblocking that inhibits the container process from starting until an attach is performed. This is triggered by the following API call ordering:
1. attach
2. start

If calling attach after start then no blocking occurs. This is implemented via a flag that suppresses launching of the container process until that attach has occurred (or a timeout triggers IIRC - need to confirm).
I'm raising this issue because I don't think there's a test the covers the following case:
1. attach
2. start
3. stop
4. start
-> check that process launched without blocking

Estimated at 5 for the case where behavioural changes are needed - if after investigation the behaviour is correct and only a test is needed this should be a 2.

**Acceptance**
- [ ] container process launches without blocking on the second `docker start <id>` having been launched previously with `docker run -i` (i.e. runblocking enabled)

**Comment by hickeng** [comment]
Confirmed that the following does not function correctly (although this is on my exec branch):
```
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker run -it busybox
/ # exit
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
13455e027fc5        busybox             "sh"                About an hour ago   Exited (0) 8 seconds ago                       modest_feynman
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker start 13455e027fc50e415b81f5d7ed0aaf0b758f963caab6744decd8f2d04ceee111

```

The container hangs at this point and presumably we'll then hit the 3min timeout and it will be left as "Starting".
This differs from #4289 as the ssh connection to the container does actually occur, but we never unblock the main process - this is because the interaction session has never been explicitly requested (correct behaviour!)

We need to ensure that runblocking is freshly configured every start, and that there's an in-container timeout of some kind to catch HA style edge cases.

**Comment by chengwang86** [comment]
@hickeng Did you test it on VC or local ESXi? I tried your example on my local ESXi but the second `docker start` didn't hang and everything worked well.

**Comment by hickeng** [comment]
@chengwang86 this should be run against the exec branch that caglar is working on - otherwise it's pointless.
If I recall the test I ran was against local ESX. The crucial piece is the lack of `-ai` on the start call which would cause unblocking.

**Comment by emlin** [comment]
@hickeng as this issue is pulled in this sprint, do you know if it is reproducible in current master?

**Comment by hickeng** [comment]
@emlin I do not - however I see no reason why it wouldn't be. If runblocking is configured with the VM powered off (and that's what should occur if attach is called before start - the case with docker run) then it'll be a persistent value.

**Comment by emlin** [comment]
@hickeng @caglar10ur in first run, attach and start works well. The start will establish connection successfully because the container attribute is set to attachable.
While the container is stopped, we just unbound the network, instead of the serial ports used for attach.
So next time start is called, the container vm serial port is still connected, so even the runblock still holds container start, until the connection between portlayer and container is established, but that will succeed.
I also tried the vm migration while the container is started and stopped, both start and attach works well, cause we've support vm migration.
So in current master branch, this function works. If you still have other case is not covered by my test, please let me know.

And as @hickeng mentioned that this problem is reproduced in @caglar10ur branch, I can also try that branch if necessary. But please let me know which one I should use.

**Comment by emlin** [comment]
Talked with @hickeng from slack. This issue is meant to reproduce the problem container stuck in starting status, and no be able to do anything after that, including delete.
Will find other reproducing steps.

**Comment by emlin** [comment]
Found two scenarios that might cause the container stuck in starting status.
- Container is not powered on for whatever errors, resource is not enough, or task is canceled
- Container is configured to run attach, but serial port is disconnected, so then tether cannot create connection between container and VCH

Currently in this situation, that container has to be removed manually from vCenter, because no any operation is allowed from persona

**Comment by hickeng** [comment]
While #4840 addresses the personality side of the problem it doesn't address either of the following:
* configuring runblocking per launch #4296
* the full set of issues in #4269

**Comment by hickeng** [comment]
The test is now in place but I think, as per [this comment](https://github.com/vmware/vic/issues/4296#issuecomment-290761599) that we'll have issues when #4263 is merged. It's possible that it was a point-in-time issue I observed but I want confirmation with recent exec before closing this.

@caglar10ur I'm assigning to you for verification with the exec changes.

**Comment by emlin** [comment]
@hickeng for the #4269, with this fix, user can stop the container first, and then delete it, or even use docker rm -f to delete it.

**Comment by emlin** [comment]
Had PR to fix the persona part, to make sure the container in starting status can be stopped and removed.
After @caglar10ur code is in, we still need to address following comments:
-  configuring runblocking per launch #4296
-  the full set of issues in #4269

**Comment by emlin** [comment]
in master, I tried docker exec as following process:
1. docker run -it
2. disconnect serial port
3. docker exec -it

Step 3 succeeds without any issue. From container log, we can see if serial connection is required, portlayer will reconfigure vm to connect serial port, and in container log, vm is waiting for runblock is cleared before it launch process.

@hickeng is there other scenario, you want me to try?

**Comment by hickeng** [comment]
@emlin The original scenario - which is nothing to do with exec:
1. docker run -it busybox      # this configures the container for runblocking
2. # exit
3. docker start <cid>            # without -ai we're not calling attach.
4. <should start cleanly without blocking>

**Comment by emlin** [comment]
```
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls create -it --name test busybox
b4337ef96529b6668b78fa592f457809905899c0a94b636c39e7e1e0d293b73c
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls attach test
You cannot attach to a stopped container, start it first
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls start test
test
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                     PORTS               NAMES
b4337ef96529        busybox             "sh"                About a minute ago   Up 32 seconds                                  test
4ccb8da63477        busybox             "/bin/sh"           2 minutes ago        Exited (0) 2 minutes ago                       flamboyant_goldwasser
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls stop test
test
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                        PORTS               NAMES
b4337ef96529        busybox             "sh"                About a minute ago   Exited (143) 31 seconds ago                       test
4ccb8da63477        busybox             "/bin/sh"           3 minutes ago        Exited (0) 2 minutes ago                          flamboyant_goldwasser
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls start test
test
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ docker -H 10.192.163.85:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
b4337ef96529        busybox             "sh"                2 minutes ago       Up 33 seconds                                  test
4ccb8da63477        busybox             "/bin/sh"           4 minutes ago       Exited (0) 3 minutes ago                       flamboyant_goldwasser
vagrant@vagrant:~/gopath/src/github.com/vmware/vic$ 
```

**Comment by emlin** [comment]
Here the difference between what you said and the output is the attach actually failed because vm is stopped.
But if we run docker run -it, it will run attach, and start, exactly as what you said. And then that work as well. So I still didn't get your concern.

**Comment by hickeng** [comment]
@emlin apologies - I was blending API calls, yes the first part should be done with `docker run` or `docker start -ai`.

The important bit is the 2nd start.
