### ISSUE TITLE
Add --detect-server-thumbprint to vic-ui

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#4304]
**User Statement:**

As a UI engineer I would want to improve the VIC UI installer for better user experience. As per #4254, the VIC UI plugin zip files would eventually be served in a web server running on the OVA appliance. This makes it possible to make the UI installer much leaner and more secure in a couple aspects such as not having to SSH into the VC with the root credentials. One change this new approach would demand though is a new flag of the `vic-ui` command that makes it easier to retrieve the SHA-1 thumbprint of the web server serving the VIC UI plugins.

**Details:**
By default the vSphere Client always uses a secure HTTP connection to retrieve the plugin from the server, so we can safely assume that we will always need to provide `--server-thumbprint` with the `vic-ui-$platform` command. The server thumbprint is currently to be fetched manually. By indicating through a flag like `--detect-server-thumbprint` while running `vic-ui-$platform install`, it will talk to the server, prompt the user for confirmation and proceed with the retrieved thumbprint. 

**Acceptance Criteria:**
1. `vic-ui-$platform` supports a new flag that does what it's expected to do
2. It should warn the user and prompts for confirmation if they want to accept the thumbprint

**Comment by jooskim** [comment]
Looping in @andrewtchin

**Comment by andrewtchin** [comment]
This looks good. We should be able to reuse thumbprint code from `vic-machine`

**Comment by jooskim** [comment]
Closing this issue as it was addressed in #5609
