### ISSUE TITLE
Design: plan out changes to integration tests to allow single VCH use across majority of test suite

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4305]
**Story** - these inherit from the epic
As a VIC developer I want my CI to find issues likely to occur in customer production scenarios
As a VIC customer I want to use multiple VCHs within a VC as a tenancy/partitioning mechanism for my compute resources.

**Detail**
Our primary deployment scenario for VIC is into a vCenter environment with supporting multiple VCHs providing tenant boundaries. This should encompass concurrent vic-machine operations, concurrent VCH operation, and hetrogeneous VCH versions.

This portion of the work is most likely running through the tests and utility functions to:
a. reuse an existing VCH _OR_ deploy a new one based on whether a VCH is currently available, functional and assigned to the test run
b. identify those tests that _fundamentally_ require deployment of a new VCH and prevent them from acting on an existing VCH assigned to the test run

This work should consider that we will wish to run tests from a single job in parallel. Two main approaches come to mind:
1. structure naming of containers in a manner that doesn't assume a non-shared environment
2. identification of tests that do not support shared use of a VCH and a reservation mechanism/demand deployment of a new VCH as needed (builds off (a) - examples of these tests would be those tests that ensure `ps` reports _only_ the expected containers)

My guess for parallelism would be that we should start with (2) and rework tests to allow for (1) over time, removing whatever flag notes that a reserved VCH is required. 

**Acceptance**
Design doc for updates to test scripts and utility functions to allow reuse of an existing VCH.

Related: #3891

**Comment by mhagen-vmware** [comment]
completed in https://github.com/vmware/vic/pull/6481
