### ISSUE TITLE
Design: plan out changes to CI setup to allow use of a single shared VC for test jobs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4306]
**Story** - these inherit from the epic
As a VIC developer I want my CI to find issues likely to occur in customer production scenarios
As a VIC customer I want to use multiple VCHs within a VC as a tenancy/partitioning mechanism for my compute resources.

**Detail**
Our primary deployment scenario for VIC is into a vCenter environment with supporting multiple VCHs providing tenant boundaries. This should encompass concurrent vic-machine operations, concurrent VCH operation, and hetrogeneous VCH versions.

This portion of the work is most likely running through the infra scripts and determining (do not assume this is an exhaustive list):
a. changes needed to target a VC
b. a means to generate unique image & volume store names
c. how to disable or change the scope of the cleanup scripts.

**Acceptance**
Design doc for updates to CI scripts and systems to allow multiple VCHs from multiple CI jobs to run concurrently in a shared VC environment.

Related: #3891

**Comment by mhagen-vmware** [comment]
https://github.com/vmware/vic/pull/6481

**Comment by mhagen-vmware** [comment]
VC will be coming in other work
