### ISSUE TITLE
Fix `vic-machine` recommendations for compute, datastore, and network

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4312]
**Story**
As a viadmin deploying a VCH I want vic-machine to provide a list of valid choices for compute, storage, and networking values

**Detail**
Changes to govmomi finder resulted in our "recommendation" logic being broken and #3557 broke the detection of absolute inventory paths in some cases.
This is a follow on from #4203.

We attempt to provide "recommendations" for compute resources and datastores - this is basically a folder listing based on the leading path fragment provided, e.g.
If specifying `--compute-resource=/cluster/poolA/poolB` when `poolA` exists, but `poolB` doesn't, we list the available resource pools nested under `poolA`.
We also attempt to allow for some fuzziness in how compute paths are specified - e.g.
`/cluster/poolA/poolB`, or if there's only one cluster `poolA/poolB`

If an absolute inventory path is specified then the guessing as to the leading path segments are suppressed and we just validate the existence of the path and, if that fails, walk up the supplied path until we find a match then provide the listing as described above.

This issue is to:
1. fix the basic recommendation mechanism we had previously
2. fix the detection of absolute paths in the case of empty datastore
2. add vcsim based tests to ensure that it's not broken again

This does _not_ include adding extra logic to improve the recommendations that are made. 

**Acceptance**
vcsim testing for recommendations and validation covering both positive and negative cases

**Related**
#3975 #4203

**Comment by hickeng** [comment]
@dougm Did you fix this with your follow up to the finder change? If so please close this issue.

**Comment by dougm** [comment]
Fixed in #4392
