### ISSUE TITLE
docker-compose has issues with tls and VIC

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#4317]
As a user of VIC, I should be able to use TLS with docker-compose against VIC.

Acceptance criteria:  Have robot scripts that can execute docker-compose --tls without getting the following,

```
ERROR: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by sflxn** [comment]
I was seeing this issue a lot on my local drone CI runs.  I thought it was just drone, but I've been able to reproduce it locally (outside of drone).

```
bin/vic-machine-linux create --debug 1 --name=vic-tls --target=10.118.69.15  --thumbprint=87:CA:19:C0:FB:C1:61:F0:C0:06:05:7E:09:C3:A8:5A:2E:0D:BE:8C --user=root --image-store=datastore --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=xxxx --force=true --bridge-network=vic-network --public-network='VM Network' --compute-resource=/ha-datacenter/host/office2-sfo2-dhcp121.eng.vmware.com/Resources --timeout 60s --volume-store=datastore/test:default --no-tlsverify
```

```
loc@Devbox:~/go/src/github.com/vmware/vic$ docker -H 10.118.69.171:2376 --tls ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
loc@Devbox:~/go/src/github.com/vmware/vic$ docker-compose -H 10.118.69.171:2376 --tls -f link-compose.yml up
ERROR: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

As we can see above, docker works fine with --tls, but docker-compose does not.  There are a lot of reports of this issue in both github issue and from a casual google of this topic.  It's currently unclear what the issue is just yet.  However, all the issues I've seen are from people having docker with tls work and docker-compose with tls giving the same verify error.

**Comment by sflxn** [comment]
I've tracked down the issue.  It's both an issue with docker-compose and a need to make some changes to our robot scripts to handle TLS with compose properly.  Here are the issues:

1) docker-compose does not seem to allow specifying TLS version on the command line.  They allow this version set via an environment variable.  However, there is a github issue in the compose repo that claims that you must use either command line option OR environment variables but cannot mix.

**Comment by sflxn** [comment]
To get docker-compose working with VIC, set the following env variables:

COMPOSE_TLS_VERSION=TLSv1_2
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=<path of your cert files>

The cert file path must have CA.pem, client_key.pem, and client cert.pem.  Docker-compose can then be executed as so,

docker-compose -H <vch addr> -f <compose file> up

A note about the above command.  If a user installs a VCH with vic-machine and specifies --tls-cname, vic-machine will do dns reverse lookups on the VCH IP and returns the dns name for the VCH.  This dns name MUST be used as the vch addr above.

**Comment by stuclem** [comment]
Added the following to the release notes for 0.9:

------

- <b>`docker-compose` does not allow you to specify the TLS version on the command line. [#4317](https://github.com/vmware/vic/issues/4317)</b><br>`docker-compose` only allows you to set the TLS version by using environment variables. For more information, see [`docker-compose` issue 4651](https://github.com/docker/compose/issues/4651). Furthermore, `docker-compose` has a limitation that requires you to set TLS options either by using command line options or by using environment variables. You cannot use a mixture of both command line options and environment variables.

   Workaround:  When using vSphere Integrated Containers with TLS, do not use TLS command line arguments with `docker-compose`. To use `docker-compose` with vSphere Integrated Containers and TLS, set the following environment variables:
   <pre>
   COMPOSE_TLS_VERSION=TLSv1_2
   DOCKER_TLS_VERIFY=1
   DOCKER_CERT_PATH="<i>path to your cert files</i>"</pre>

   The certificate file path must lead to `CA.pem`, `client_key.pem`, and `client cert.pem`. You can run `docker-compose` with the following command:<pre>docker-compose -H <i>vch_address</i> -f up</pre>

------

@sflxn does this cover it? Since this is related to an issue with `docker-compose` itself, should this should also be included in the core doc for 1.1?

**Comment by sflxn** [comment]
@stuclem I would add more to this.

VIC supports TLS 1.2.  To use docker-compose with VIC, users must tell docker-compose to use TLS 1.2 and that can only be done with environment variable.  Also, add that this applies only if users install a VCH that uses TLS.  It is possible to install a VCH without TLS (--no-tls).

**Comment by stuclem** [comment]
Thanks @sflxn. Reworded as follows:

------

- <b>`docker-compose` does not allow you to specify the TLS version on the command line. [#4317](https://github.com/vmware/vic/issues/4317)</b><br>vSphere Integrated Containers supports TLS v1.2. You must configure `docker-compose` to use TLS 1.2. However, `docker-compose` only allows you to set the TLS version by using environment variables. For more information, see [`docker-compose` issue 4651](https://github.com/docker/compose/issues/4651). Furthermore, `docker-compose` has a limitation that requires you to set TLS options either by using command line options or by using environment variables. You cannot use a mixture of both command line options and environment variables. To use `docker-compose` with vSphere Integrated Containers and TLS, set the following environment variables:
   <pre>
   COMPOSE_TLS_VERSION=TLSv1_2
   DOCKER_TLS_VERIFY=1
   DOCKER_CERT_PATH="<i>path to your cert files</i>"</pre>

   The certificate file path must lead to `CA.pem`, `client_key.pem`, and `client cert.pem`. You can run `docker-compose` with the following command:<pre>docker-compose -H <i>vch_address</i> -f up</pre>


-------

Opened https://github.com/vmware/vic-product/issues/109 to add this to the core doc for 1.1.

Regarding the entry about `-d`, yes, this is just for 0.9.

**Comment by anchal-agrawal** [comment]
Reopening as #4349 was reverted (#4356).

**Comment by sflxn** [comment]
@stuclem That sounds a lot better.

**Comment by stuclem** [comment]
@sflxn thanks!

**Comment by tompscanlan** [comment]
+1 also seeing this error, and came to report it.

**Comment by omnidepp** [comment]
> I was seeing this issue a lot on my local drone CI runs. I thought it was just drone, but I've been able to reproduce it locally (outside of drone).
> 
> bin/vic-machine-linux create --debug 1 --name=vic-tls --target=10.118.69.15 --thumbprint=87:CA:19:C0:FB:C1:61:F0:C0:06:05:7E:09:C3:A8:5A:2E:0D:BE:8C --user=root --image-store=datastore --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=xxxx --force=true --bridge-network=vic-network --public-network='VM Network' --compute-resource=/ha-datacenter/host/office2-sfo2-dhcp121.eng.vmware.com/Resources --timeout 60s --volume-store=datastore/test:default --no-tlsverify
> 
> ```
> loc@Devbox:~/go/src/github.com/vmware/vic$ docker -H 10.118.69.171:2376 --tls ps
> CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
> loc@Devbox:~/go/src/github.com/vmware/vic$ docker-compose -H 10.118.69.171:2376 --tls -f link-compose.yml up
> ERROR: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
> ```
> 
> As we can see above, docker works fine with --tls, but docker-compose does not. There are a lot of reports of this issue in both github issue and from a casual google of this topic. It's currently unclear what the issue is just yet. However, all the issues I've seen are from people having docker with tls work and docker-compose with tls giving the same verify error.

This is still an issue. I need to use docker-compose with a --no-tlsverify VCH and it does not seem possible. Docker works with the --tls parameter, docker-compose does not.
