### ISSUE TITLE
compose scale

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#432]
Use `docker compose scale` commands to scale container numbers in specific compose service.

Breaks down into the following staged deliveries:
- Scale up
- Scale down
- Scale down to zero (if supported)

**Comment by hickeng** [comment]
While I think this is likely trivial once #431 is implemented it's also not critical for initial release, so icebox.

**Comment by mdubya66** [comment]
requested for 1.1, listed as partial. making medium for now
