### ISSUE TITLE
Implement test to run and verify the proper working behavior of the top 15 containers in docker hub

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4324]
User statement:  As a user of VIC, I would like to know that VIC works with and has been tested with the top most popular containers.

Details:  
https://hub.docker.com/explore/
Wouldn't normally say that many, but this story originated from postgresql problems, which is number 12 on the list, so now we get to do the top 15!

Each one probably just needs to be:
docker run <container> followed by a curl or something other confirmation that the service is actually up and running or even just docker logs and verify no errors were thrown.

Acceptance criteria:
Test for top 15 containers is implemented in the CI and executing.

**Comment by corrieb** [comment]
I would honestly just keep expanding the list over time. There are all sorts of quirks in various Dockerfiles and given that we don't have explicit function tests for all the Dockerfile grammar, the more we can verify real function, the better

**Comment by corrieb** [comment]
I'd really like to see progress on this FWIW. I know we don't have a great way of prioritizing things, but verifying basic compatibility is super important.
