### ISSUE TITLE
Doc: Error in firewall rule topic

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#4325]
Per the following comment on Slack, there is at least one error in the topic on opening the firewall port:

-----

Lakshmi Gayatri [7:01 PM] 
@sclements , on https://vmware.github.io/vic-product/assets/files/html/0.8/vic_installation/ts_firewall_error.html the firewall rule needs to be corrected. 
1. The service id should be in "" instead of ''
2. <port type='dst'>2377</port> should be on two separate lines as <porttype>dst</porttype>
     <port>2377</port>

-----

I need to check the second point, as this came up before, the other way around. Might have been related to ESX versions.

Fixes need to go into the 0.8 and 0.9 docs, but are probably not required for 1.1 because of https://github.com/vmware/vic-product/issues/45.

**Comment by lgayatri** [comment]
@stuclem , I checked https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2008226 and noticed that point#2 applies for legacy hosts of 5.5 and 6.0 as well.

**Comment by stuclem** [comment]
@lgayatri, thanks for doing that. So, the doc is currently correct for 6.5, but not for 6.0.

**Comment by mhagen-vmware** [comment]
@stuclem Are you still working on this issue?

**Comment by mdubya66** [comment]
Moved to new repo. Closing.
