### ISSUE TITLE
html5 webclient plugin

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#434]
Deploy vCenter plugin for basic VIC data presentation in the [html5 vsphere client](http://blogs.vmware.com/vsphere/2016/03/vmware-vsphere-html5-web-client-fling.html).

 HTML5 plugin skeleton code in github
 Build self-contained plugin blob
 Install plugin via VIC installer

**Comment by hickeng** [comment]
Moving this to icebox as we're not using the html5 client directly for initial release

**Comment by mdubya66** [comment]
feature requested for 1.1, marking medium
