### ISSUE TITLE
Attaching multiple times to the same containers does not work as expected

### ISSUE THREAD

**Issue by kreamyx** [vmware/vic#4348]
**User Statement:**

As a VIC user, I should be able to attach multiple times to my container.

**Details:**
Currently, `docker attach` does not work as expected in the following scenario
- `docker run --name test /bin/top`
- `docker attach test`
- After being attached, hit Ctrl^C. The container should exit.
- Start the container `docker start test`
- Try to attach again, this attach request will return without attaching

**Acceptance Criteria:**
Follow the steps above while being able to correctly attach to container `test`

**Comment by hickeng** [comment]
Closing in favour of #4367 which has a good identification of the origin of the problem
