### ISSUE TITLE
initial binary installer

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#435]
The initial binary installer - this translates the current [install script](install/install.sh) into Go, adding support for vCenter.

What the installer has to do is relatively straight forward, but initial approach has to bear in mind:
* authority delegation/self-provisioning workflows
* update/upgrade and rollback
* diagnostic inspection of any VM involved in a VCH
* installation of UI plugin and creation of users/RBAC configuration.

**Comment by emlin** [comment]
Requirements from discussion with George:

1. configuration of the VCH is via extraConfig and guestinfo
2. the installer is actually the VIC cli client and will be used for updating VCH config, upgrade, inspection of current config (VCH and containers)
3. should be written with the authority delegation/self-provisioning workflow as the primary goal (viadmin deployment is degenerative case)

detail request:
I want one `-compute` flag to describe where the VCH runs, not the mix of pool, host, cluster, datacenter, etc that we had with bonneville - everyone was confused about what to specify when. We will have to process the `compute` path and do different things with it based on VC topology, but we should hide that from users.

**Comment by mdubya66** [comment]
This epic spans milestones. removing the milestone initial vCenter support

**Comment by hickeng** [comment]
I've removed the VC task element - it's a nice to have at this point.
I've also removed the EULA aspect - it's unclear whether that's a legal requirement or not now.
