### ISSUE TITLE
Milestone: docker rm

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#436]
Delete an existing, stopped container.

The low level port layer implementation should not delete attached named volumes, but likely should delete attached anonymous volumes - this maps much more closely to an intuitive behaviour than the orphaned volume behaviour with docker.

For a conservative initial implementation we don't delete any directly.
We can construct the docker semantics in the personality.

#688 will implement a minimal subset of this function

**Comment by corrieb** [comment]
Since #364 is the only remaining issue for this epic, right now, assigning to @matthewavery

**Comment by matthewavery** [comment]
this is complete, all issues related to this epic have been completed.
