### ISSUE TITLE
switch CI to use docker 1.13 as default

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4368]
As discussed in the last sprint demo meeting, now that we have support for it, we want to make docker 1.13 the default for all of our CI tests.

**Comment by anchal-agrawal** [comment]
#4322 should be addressed before this.

**Comment by jakedsouza** [comment]
This can happen with moving to a new drone env #4267

**Comment by jakedsouza** [comment]
Blocked by 
#4561   #4560 #4559 #4564
