### ISSUE TITLE
Milestone: docker rmi

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#437]
Delete images, failing if they are not leaves of the tree or are in an image store that the VCH isn't directly managing.

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-12-Docker-RMI.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by corrieb** [comment]
@fdawg4l assigning this to you to co-ordinate with @sflxn. Is it realistic to be targeting onsite with this? I note that #253 is targeted at GA

**Comment by fdawg4l** [comment]
@corrieb I don't see this happening in the next 5days.

**Comment by corrieb** [comment]
@hickeng @mdubya66 note this is moving out of onsite to GA

**Comment by mdubya66** [comment]
GA feature from SSOD

**Comment by mdubya66** [comment]
Only Documentation remains, moving to Doc milestone

**Comment by stuclem** [comment]
Doc is done. Closed https://github.com/vmware/vic/issues/835.

**Comment by hickeng** [comment]
Re-opening until robot rmi tests are re-enabled.
@fdawg4l @vburenin 

I tried simply un-commenting them and deleting the check however they fail. It doesn't seem like it's a simple matter of updated expected strings (although the error messages are quite horrific as they stand).

The primary functional failure is `rmi -f <id>` which returns exactly the same message as `rmi <id>`:
```
<msg timestamp="20161009 08:12:39.261" level="INFO">Running command 'docker -H 192.168.78.230:2376 --tls rmi -f busybox 2&gt;&amp;1'.</msg>
<msg timestamp="20161009 08:12:39.280" level="INFO">${rc} = 1</msg>
<msg timestamp="20161009 08:12:39.280" level="INFO">${output} = Error response from daemon: [DELETE /storage/{store_name}/info/{id}][423] deleteImageLocked  &amp;{Code:0xc420314550 Message:image 9967c5ad88de8c101809f7f22d4774b6791fe46ac3033d57abf7ebb1dd8e36ee in use b...</msg>
```

**Comment by fdawg4l** [comment]
```
$ ag -r deleteImageLocked *
lib/apiservers/portlayer/restapi/operations/storage/delete_image_responses.go
89:swagger:response deleteImageLocked

lib/apiservers/portlayer/client/storage/delete_image_responses.go
127:    return fmt.Sprintf("[DELETE /storage/{store_name}/info/{id}][%d] deleteImageLocked  %+v", 423, o.Payload)

lib.gas
134:  > fmt.Sprintf("[DELETE /storage/{store_name}/info/{id}][%d] deleteImageLocked  %+v", 423, o.Payload
```

**Comment by fdawg4l** [comment]
Oh, I see, it's the `423` default response.  I'll take care of this.
