### ISSUE TITLE
Support name resolution for renamed running containers

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#4375]
**User Statement:**

As a user of VIC, I should be able to rename a running container (`c1`) and use the new name to create a link to or ping from another container (`c2`) without restarting container `c1`.

**Details:**

We need to update the alias and any name resolution metadata for the container during its rename operation. This is a follow-up of #4082, whose scope includes support for name resolution for containers that are restarted after renaming them, and containers that are created, renamed and then started. Renaming a running container *will work* after #4082 is closed, but name resolution for it won't.

**Acceptance Criteria:**

Passing tests for the following use cases:

```
# Container link
$ docker run -dit --name c1 busybox
$ docker rename c1 c11
$ docker run --link c11:c11alias busybox ping -c2 c11alias
...
2 packets transmitted, 2 packets received...

# Ping by name for containers on the same network
$ docker run -dit --name c1 busybox
$ docker rename c1 c11
$ docker run busybox ping -c2 c11
...
2 packets transmitted, 2 packets received...
```

**Comment by anchal-agrawal** [comment]
Need an estimate from @hmahmood - I suspect this will be no less than a 3.

**Comment by anchal-agrawal** [comment]
There's an integration test in `Group1-Docker-Commands/1-36-Docker-Rename` tagged against this issue.

**Comment by hickeng** [comment]
This has been found by @smaliakkal - the necessity for rename in this specific scenario would be eliminated, and come with a performance improvement and complexity reduction, by adding naming convention support for containerVMs. The epic #773 references the naming conventions, both for inventory folders and cVMs, but I didn't find a dedicated issue for the cVM specifically.

**Comment by renmaosheng** [comment]
closing per previous comment, please reopen if you think otherwise.

**Comment by luwang-vmware** [comment]
Update the CI scripts and get PASS https://ci-vic.vmware.com/vmware/vic/20826. Close it now.
