### ISSUE TITLE
Milestone: docker stop

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#438]
Stop a container.

This covers:
* the polite case where the container stops on request
* mapping of stop to appropriate signal
* aggressive killing of container - should this map to immediate power off, or should this aggressively kill the process in the container so that sync can be performed and clean OS shutdown to prevent filesystem corruption?

**Comment by hickeng** [comment]
#688 will address the basics of the docker API side, but that's mapping to only the aggressive killing of the container. The rest needs to be addressed in PL and tether.

**Comment by mdubya66** [comment]
We need to add another issue to this epic to finish the stop portion.

**Comment by mdubya66** [comment]
Moving this to Done. Needs docs.

**Comment by corrieb** [comment]
@dougm given that you appear to own just about every issue referred to here, it makes sense for you to own this epic. Can we realistically expect to get this epic closed for onsite d'you think?

**Comment by dougm** [comment]
@corrieb yes, expecting the 2 remaining issues to be done for onsite.

**Comment by mdubya66** [comment]
Closing. Doc issue is open.
