### ISSUE TITLE
OVA installer webserver should not run as root

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#4382]
**User Statement:**
As a person, I do not want the OVA installer webserver to run as root.

**Details:**
Don't run as root
`installer/fileserver/server.go`
`installer/engine_installer/server.go`

**Acceptance Criteria:**
- [ ] Getting Started Page webserver doesn't run as root
- [ ] Demo VCH Installer Wizard webserver doesn't run as root

**Comment by andrewtchin** [comment]
Also `engine_installer`

**Comment by andrewtchin** [comment]
Bugzilla 1953874

**Comment by anchal-agrawal** [comment]
Issue moved to [vmware/vic-product #827](https://github.com/vmware/vic-product/issues/827) via [**ZenHub**](https://www.zenhub.com/)
