### ISSUE TITLE
Improve integration test 11-03 to test with an actual registry

### ISSUE THREAD

**Issue by jakedsouza** [vmware/vic#4403]
#For stories, please include the information below:

**User Statement:**

As a vic engineer, I want to ensure that upgrade of VIC to the latest version updates the insecure registries correctly 

**Details:**
For issue #4388 we have an integration test 11-03-Upgrade-InsecureRegistry which tests that an insecure registry added to an older version of vic is updated correctly during an upgrade 
Currently the test checks guestinfo information to validate that the upgrade was successful
We should test against an actual insecure registry, instead of relying on guestinfo 
 
**Acceptance Criteria:**
 Update test `11-03-Upgrade-InsecureRegistry` to use an actual insecure registry

1. Deploy harbor as an insecure registry both https with untrusted certs and on http
2. Deploy an older VCH with the registry created in step1
3. Do a docker pull from the registries  
4. Upgrade the VCH to the latest 
5. Do a docker pull again

**Comment by mhagen-vmware** [comment]
Thanks Jake, I am going to keep this high as this needs to go into next sprint.
