### ISSUE TITLE
Pull vic-ui build into makefile

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#4405]
As a developer I want to be able to build a VIC bundle that includes all tools needed to deploy VIC Engine. 

Currently the vic-ui portion can only be built with Drone which makes it hard to test locally. 

Acceptance criteria:
- [x] move `vicui` from `.drone.yml` into a make target
- [x] able to build full bundle with OVA installer make targets
- [x] document steps to build

**Comment by hickeng** [comment]
I honestly think that we should be splitting the UI into a separate repo.

It's not tightly tied to a VIC release version (hetrogenous versions of VIC should be supported within a single ESX/VC), and it's got very different concerns.

What we should have, and don't, is a tightly defined data contract that we abide by, and tests in the VIC repo to enforce that.

**Comment by mdubya66** [comment]
Not critical to 1.1 or 1.2

**Comment by andrewtchin** [comment]
Added #4440 for George's concerns
