### ISSUE TITLE
networking mapping

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#441]
We need to be able to map an existing vSphere level network into `docker network` so that we can explicitly provide a container with a route to the outside world, that is not via the VCH appliance.

This likely has two stages:
1. map the network such that `docker create -net=...` can reference it - this starts with vic-machine
2. add firewall rules such that only exposed ports are accessible

**Comment by mdubya66** [comment]
Adding GA milestone as remaining issue is GA targeted

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.
