### ISSUE TITLE
docker network and storage stats

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#4422]
Docker stats was partially implemented with #4413 by providing CPU & Memory stats.  Network and storage stats still need to be implemented.

**Comment by chengwang86** [comment]
Update:

For this feature, here is an example of the output we expect to see
```
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
ec                  0.00%               528 KiB / 3.84 GiB   0.01%               2.77 kB / 1.25 kB   32.8 kB / 0 B       1
```
For NET I/O:
- the first number is **average amount of data received per second** (aggregated from all network devices), which can be obtained by `govc metric.sample -n 1 -instance="" vm-path net.bytesRx.average` with the unite of `KBps`
- the second number is **average amount of data transmitted per second**, which can be obtained by `govc metric.sample -n 1 -instance="" vm-path net.bytesTx.average` with the unit of `KBps`
- Reference: https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/network_counters.html

For BLOCK I/O:
- the first number is the **average number of kilobytes read from the disk each second** during the collection interval, which can be obtained by `govc metric.sample -n 1 -instance="" vm-path disk.read.average` with the unite of `KBps`
- the second number is **the average number of kilobytes write to the disk each second** during the collection interval, which can be obtained by `govc metric.sample -n 1 -instance="" vm-path disk.write.average` with the unit of `KBps`
- Reference: https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/disk_counters.html

**Comment by cgtexmex** [comment]
I've done the research, have the design and was planning on implementing in this sprint.  @chengwang86 are you now taking?

**Comment by chengwang86** [comment]
About docker stats api:

Here is an example from docker's api docs: https://docs.docker.com/engine/api/v1.26/#operation/ContainerStats

It seems like `docker stats` api would return network I/O stats for different devices separately (e.g., eth0 vs. eth5). However, from the output of `docker stats` cli I only observe a single line of stats for each container.

```
govc metric.sample -n 1 /ha-datacenter/vm/vch-1/cranky* net.bytesRx.average
cranky_beaver-805ec0925bb8  -       net.bytesRx.average    3  KBps
cranky_beaver-805ec0925bb8  vmnic1  net.bytesRx.average    0  KBps
cranky_beaver-805ec0925bb8  vmnic0  net.bytesRx.average    0  KBps
cranky_beaver-805ec0925bb8  4000    net.bytesRx.average    3  KBps
```
Here `4000` represents `eth0` in vsphere.

@cgtexmex Any comments on this? Should we (1) return the aggregated stats for all network devices for `docker stats` cli and (2) return per-device stats separately for docker API call?
