### ISSUE TITLE
Move OVA installer and packaging to vic-product repo

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4424]
**Story**
As a VIC engine developer I want the repo code base to be as small and as simple as possible to accomplish required engine behaviour
As a VIC engine developer I want build times on PRs and merges to be as low as possible
As a VIC engine developer I want build failures to be pertinent to the component on which I'm working
`<repeat all of the above for VIC product developer> `

**Details**
The OVA work does not belong in the VIC engine repo - it was placed here as an accelerator to avoid having to set up a new repo in CI. Now that it's established, let's move it to it's own repo and have it build in a separate build.

**Comment by hickeng** [comment]
@frapposelli Feel free to be more eloquent in the description ;)

**Comment by mdubya66** [comment]
Lowering the priority. I also think the estimate is off.

**Comment by frapposelli** [comment]
I would bring it back as `medium` as going forward our testing is going to require a different set of needs and it shouldn't bog down engine builds (and viceversa).

This story should also have an upstream dependency on the Drone 0.5 work, given the `.drone.yml` is going to be brand new I want it to be tailored to the new version already.

**Comment by frapposelli** [comment]
the more I think of this, the more it makes sense to move it off `vmware/vic` ASAP, @mdubya66 I would classify this as high priority for 1.2.

**Comment by mdubya66** [comment]
We can chat about it but until we have a CI system in place that can adequately meet the testing requirements it needs to remain.

**Comment by hickeng** [comment]
I consider this debt - it's currently location is a decision based on expediency only.

**Comment by frapposelli** [comment]
After a conversation with @jakedsouza and the progress of the new Drone 0.5 install I believe this could very well be in scope for 1.2

**Comment by stuclem** [comment]
You'll be most welcome in `vic-product`. @alextopuzov and I are lonely in there!

**Comment by andrewtchin** [comment]
Related to https://github.com/vmware/vic/issues/4809

**Comment by andrewtchin** [comment]
Jason and I have moved everything from `installer` directory to `vic-product/installer`. The makefile works inside the installer directory for the `ova-release` target.

**Comment by andrewtchin** [comment]
Also when the build uploads the ova, please see if you can have it upload as `-latest.ova` also

**Comment by rajanashok** [comment]
Merged the ova changes as part of the PR 438. https://github.com/vmware/vic-product/pull/438

1. Simplified the commit by adding a .drone.local.yml to support the OVA builds locally.
2. The .drone.yml still has the unified-ova-builds commented out so we don't invoke the OVA builds on the CI until we have the OVA building within drone.
3. Also, added the ova_secrets.yml to the vic-internal repo to kickoff the local OVA builds using drone exec command
