### ISSUE TITLE
Investigate work needed for k8 support for VIC

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#4426]
**User Statement:**
As a VIC developer I want to know what needs to be done for k8 support in VIC

**Details:**
This issue tracks the investigation into k8 support and should result in a set of issues added to the parent epic #4427. 

**Acceptance Criteria:**
A list of issues added to #4427 that describes the work needed to support k8 in the next release of VIC.

**Comment by casualjim** [comment]
Not doing this on vic
