### ISSUE TITLE
Work items for k8 support for VIC 1.2

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#4427]
**User Statement:**
As a VI admin I want an easy way to provision and manage Kubernetes clusters for my users.
As a Kubernetes user I want to use a supported Kubernetes cluster deployed on vSphere.

**Details:**
This epic is to track investigation and work items for our initial support of Kubernetes for VIC. 
The initial issue in this epic is an investigation that will result in additional user stories being added to this epic.

**Acceptance Criteria:**
Successful implementation of the acceptance criteria of the child issues.

**Comment by mlh78750** [comment]
Need to reconcile this with #105 as well.

**Comment by mlh78750** [comment]
And #3829.

**Comment by mdubya66** [comment]
#3940  was also investigation towards k8
Other related isues #3942, #4099, #3941, #3785

**Comment by mdubya66** [comment]
moved to vmware/kov
