### ISSUE TITLE
Investigate common RBAC Project model for Harbor and Admiral

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4429]

**Comment by lcastellano** [comment]
This investigation has been started and it is currently in progress. Here are a few links to design docs and functional specs.

https://confluence.eng.vmware.com/pages/viewpage.action?pageId=216835445

https://confluence.eng.vmware.com/plugins/gliffy/editor.action?inline=false&pageId=216843081&name=UI%20Copy&attachmentId=216843082&ceoid=216843081&key=MCS&lastPage=%2Fpages%2Fviewpage.action%3FpageId%3D216843081

**Comment by lcastellano** [comment]
Closing as this has been superseded by #4712.
