### ISSUE TITLE
Investigate Lightwave configuration via OVF properties

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4430]

**Comment by lcastellano** [comment]
This issue has been moved back to Not Ready as the plan of record is to use PSC as the Identity Provider.

https://onevmw-my.sharepoint.com/personal/lcastellano_vmware_com/_layouts/15/WopiFrame.aspx?sourcedoc=%7BDA369CE4-AB0B-4AE6-9F18-0EA64F36255A%7D&file=IdentityProviderVIC.docx&action=default

**Comment by frapposelli** [comment]
Not needed anymore, cleaning up
