### ISSUE TITLE
Investigate OpenID Connect between Harbor/Admiral and Lightwave

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4431]

**Comment by lcastellano** [comment]
This activity is in collaboration with Admiral team.

https://onevmw-my.sharepoint.com/personal/lcastellano_vmware_com/_layouts/15/WopiFrame.aspx?sourcedoc=%7BDA369CE4-AB0B-4AE6-9F18-0EA64F36255A%7D&file=IdentityProviderVIC.docx&action=default
https://confluence.eng.vmware.com/plugins/gliffy/editor.action?inline=false&pageId=216843081&name=UI%20Copy&attachmentId=216843082&ceoid=216843081&key=MCS&lastPage=%2Fpages%2Fviewpage.action%3FpageId%3D216843081

**Comment by lcastellano** [comment]
Closing this story as SAML appears to be the best choice for authentication for Portal/Admiral and PSC.
