### ISSUE TITLE
Investigate PSC/LW Local User management when not connected to upstream LDAP

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4432]

**Comment by lcastellano** [comment]
I have created a local user in PSC. The user was not assigned any role in VC and therefore it was not able to access any of the VC resources. However the user was able to authenticate successfully. Here's a part of the SAML Assertion that attests the ability to log in successfully.

<saml2:Subject>
  <saml2:NameID 
    Format="http://schemas.xmlsoap.org/claims/UPN">luca@vsphere.local</saml2:NameID>
  <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
    <saml2:SubjectConfirmationData InResponseTo="_da71f534dcfab161c1c7939c901b8dfd" 
     NotOnOrAfter="2017-04-17T23:38:26.989Z" Recipient="https://office1-sfo2-
     dhcp152.eng.vmware.com/ui/saml/websso/sso"/>
  </saml2:SubjectConfirmation>
</saml2:Subject>

This confirms the ability to create VIC specific local users in PSC with no VSphere roles.

**Comment by mhagen-vmware** [comment]
LGTM

**Comment by mhagen-vmware** [comment]
@lcastellano Are you waiting on anything else to close this?
