### ISSUE TITLE
Single AuthZ/AuthN model for Harbor and Admiral through PSC/LW

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4433]
Desired outcome of this Epic is a breakdown of the body of work required for VIC 1.2 concerning AuthZ/AuthN in VIC Product, stories created from this research spike will track implementation work for 1.2.

**Comment by lcastellano** [comment]
This activity was conducted with the Admiral and Harbor teams. I have attached a couple of pointers to design docs that were the result of the common investigation. 

https://confluence.eng.vmware.com/plugins/gliffy/editor.action?inline=false&pageId=216843081&name=UI%20Copy&attachmentId=216843082&ceoid=216843081&key=MCS&lastPage=%2Fpages%2Fviewpage.action%3FpageId%3D216843081

https://confluence.eng.vmware.com/plugins/gliffy/editor.action?inline=false&pageId=216843081&name=UI%20Copy&attachmentId=216843082&ceoid=216843081&key=MCS&lastPage=%2Fpages%2Fviewpage.action%3FpageId%3D216843081

https://confluence.eng.vmware.com/pages/viewpage.action?pageId=216835445
