### ISSUE TITLE
Associate switch/port groups to port layer network scopes

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#444]
Currently info about the networks created is stashed in the guestinfo for the VCH (see https://github.com/vmware/vic/blob/master/install/install.sh#L282). The port layer's networking layer currently does not know about these networks; specifically switch or port group names need to be associated with network scopes.

**Comment by hickeng** [comment]
This has a dependency on #402 for basic access to the VCH configuration.

**Comment by hickeng** [comment]
in /sys/class/net/eth0/device/label you'll find a value such as Ethernet0 or Ethernet1
those labels are ordered in the same order as the NICs appear in the config spec

it's not my preferred approach as it's fragile if the devicechange array in the configspec ever gets re-ordered, but it may be an alternative if you're having issues generating the PCI bus address from the spec slot/unit numbers

**Comment by andrewtchin** [comment]
We determined that the PCI slot number value isn't present in what govc/govmomi returns when querying devices. The path under /sys can be determined from some values in the config (vmx), but those aren't present before the VM is powered on. Hasan's going to try to specify these values explicitly when creating the config.
