### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by dougm** [vmware/vic#4443]
As a developer, I want CI to run static code analysis on the VIC code base and report the results.

VIC currently has a 'make gas' target to run [gas](https://github.com/GoASTScanner/gas) against the code base.

We should look at the current results and determine:

- [x] Which warnings can/should be acted upon

- [x] Which rules should be disabled, if any

- [x] Decide if/when to make CI fail based on gas results

**Comment by dougm** [comment]
See also #906

**Comment by anchal-agrawal** [comment]
Regarding the second item in this issue's description:

All rules in https://github.com/GoASTScanner/gas#available-rules are fairly applicable to our code base, so it's good to include all of them. We can evaluate all issues reported by gas and choose whether to address them on a case-by-case basis (#4587).

**Comment by anchal-agrawal** [comment]
Regarding item 3, we can [annotate our code](https://github.com/GoASTScanner/gas#annotating-code) to have `gas` ignore issues that have been verified manually, however, that will add a lot of noise to the code base. 

There are currently 52 total `gas` issues (after including #4587's changes) in the `lib`, `cmd` and `pkg` directories that we check as part of our build. We have two options:

* Annotate the code in all reported places and make the build fail if a change causes a new issue to be reported (`gas` returns with exit code 1) - we can then address the issue or annotate that change.
* Keep our `gas` check as-is - don't fail the build and have developers inspect the reports manually.

The former is the best long term solution but will litter our code quite a bit.
