### ISSUE TITLE
Response to test/dev use case PRD

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4455]
As an engineer working on VIC, I need a set of defined stories in the area of how to advance the usability of VIC in test/dev use-cases.

Output of sprint: User stories resulting from the PRD.

**Comment by corrieb** [comment]
Let's enumerate what's in this PRD for 1.2 and link to relevant issues:

1. Basic DinV support. These requirements simply cover deployment, connection and documentation of deployment.

They don't cover any aspects around security, lifecycle management, upgrade, support for DinV in DockerHub, rolling your own, signal handling, Harbor integration or any of the other things listed in the Dev section of #4832. As such, this is a _very_ low bar as it stands.

We should be able to deliver this for 1.2 simply by implementing #4860. There is a lot more we could/should be aiming for in this space.

2. Documentation, best practices and examples for various specific usage scenarios:

- Use VIC to spin up a Jenkins cluster (use compose support?) #4868
- MSSQL server Linux is certified for use with VIC #(not sure that really belongs here??)
- Show how VIC can exist at the end of a Docker publish pipeline #(needs clarity - same as the accenture CI pipeline?)
- Integrate with the Accenture CI pipeline benchmark #4871

3. Support for some additional Docker commands

- Exec #3649
- Stats #4422
- Logs --since #4748
- Cp #769
- Diff #4742
- Commit #4743
- Push #4744
- Build: Proposal for an integrated build slave solution here: #4859

4. Ticketless infrastructure

- Only concrete proposal here is to investigate a framework for allowing users to define the shape of an application beyond what's available using Compose or Admiral. Terraform? InfraKit? #4867

5. Evangelism section

- There is nothing actionable here in terms of creating Issues. "The team should create content" is the extent of it. This will happen organically.

6. Docker machine integration

This is captured in #4854

**Comment by mhagen-vmware** [comment]
7. Test: As final verification, we should be able to:
   - build the top 10 containers
   - run the top 10 containers off the image we built
   - execute the compose tests that we integrated here:
       https://github.com/vmware/vic/blob/master/tests/test-cases/Group3-Docker-Compose/3-04-Docker-Compose-Fixtures.robot

@corrieb LGTM, if you agree with the test section I have added, please close this issue out. Thanks!

**Comment by mhagen-vmware** [comment]
documented in the final EPIC my test request
