### ISSUE TITLE
Response to nested Docker integration PRD

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4458]
As an engineer working on VIC, I need a set of defined stories in the area of how to integrate Docker's Moby release in creating nested Docker hosts in VIC and the necessary SDDC integrations implied.

Output of sprint: User stories resulting from the PRD.

**Comment by corrieb** [comment]
Note that what we previously called "Moby" is now "LinuxKit".

Response to this part of the Dev/Test PRD is here: https://github.com/vmware/vic/issues/4832

**Comment by mhagen-vmware** [comment]
same test suggestions apply to this story as to #4455 , lgtm

**Comment by mhagen-vmware** [comment]
documented in the working EPIC
