### ISSUE TITLE
vCenter: image operations not working on restarted VCH

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#4469]
**VIC version:**

master / ee1c09a

**Deployment details:**

vCenter 6.5.0 b4602587 with 3 ESX 6.5.0 b4564106 hosts deployed with https://github.com/vmware/vic/blob/master/tests/resources/Nimbus-Util.robot#L140

**Steps to reproduce:**

1. Deploy VCH
2. `docker pull busybox`
3. Power off and then power on vApp from vSphere web client
4. `docker pull alpine`
5. `docker images`
6. `docker rmi alpine`
7. `docker run alpine ls`
8. `docker run busybox ls`
9. `docker rmi busybox`

**Actual behavior:**

4.
```
Using default tag: latest
Pulling from library/alpine
627beaf3eaaf: Extracting [==================================================>] 1.905 MB/1.905 MB
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:parent (scratch) doesn't exist in http:///storage/images/4201b0f7-08ec-3440-b957-c40f4688984e: A specified parameter was not correct: dc}
```
5.
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              00f017a8c2a6        2 weeks ago         1.11 MB
alpine              latest              4a415e366388        3 weeks ago         3.98 MB
```

6.
```
Error response from daemon: [DELETE /storage/{store_name}/info/{id}][404] deleteImageNotFound  &{Code:404 Message:file does not exist}
```
7.
```
docker: Error response from daemon: Server error from portlayer: Invalid configuration for device '1'..
See 'docker run --help'.
```

8. Succeeds

8.
```
Error response from daemon: [DELETE /storage/{store_name}/info/{id}][500] DeleteImage default  &{Code:500 Message:A specified parameter was not correct: dc}
```

**Expected behavior:**

Image operations shouldn't be affected by a VCH restart

**Logs:**

[container-logs.zip](https://github.com/vmware/vic/files/882954/container-logs.zip)

Integration test `Group10-VCH-Restart/10-01-VCH-Restart` also fails at an image pull operation on this setup. Logs: 
* [10-01-VCH-Restart-VCH-0-1703-container-logs.zip](https://github.com/vmware/vic/files/882890/10-01-VCH-Restart-VCH-0-1703-container-logs.zip) 
* [log.html.zip](https://github.com/vmware/vic/files/882901/log.html.zip)

**Comment by dougm** [comment]
Is rmi working before restarting the VCH?
Looks like we need to set the dc param when calling QueryVirtualDiskInfo() https://github.com/vmware/vic/blob/master/pkg/vsphere/disk/disk_manager.go#L218

**Comment by anchal-agrawal** [comment]
@dougm Yes, `rmi` is working before a restart.

**Comment by dougm** [comment]
Might be the case that `QueryVirtualDiskInfo` is only used after a restart, since the initial image disk chains were tracked in memory, @fdawg4l can say for sure.  But, the dc param is required for  `QueryVirtualDiskInfo` against VC and optional against ESX.

**Comment by fdawg4l** [comment]
Yeah, @dougm is right.  We track relationships in memory until we reboot and have to rebuild that index.  And since our CI doesn't include VC and my local dev env doesn't either, this slipped through.

**Comment by fdawg4l** [comment]
Fix was trivial.  PR incoming.  Tried this against 65 VC w/ VSAN.

```
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker pull tomcat
Using default tag: latest
Pulling from library/tomcat
6d827a3ef358: Pull complete 
a3ed95caeb02: Pull complete 
2726297beaf1: Pull complete 
d6e483851652: Pull complete 
0ab260573986: Pull complete 
b7c48cee0b2b: Pull complete 
1368ab15aa1c: Pull complete 
e4b9c85c3e06: Pull complete 
ee3dc5d1e4c7: Pull complete 
e101174ccdbd: Pull complete 
c2314a094b7b: Pull complete 
a9d5ec3c3ff3: Pull complete 
Digest: sha256:a45d6a36ed6e66d7cd485cfec97a2b54254924542038802323fa42a74e9423b0
Status: Downloaded newer image for library/tomcat:latest
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ govc ls vm
/dc1/vm/fahmed-vc65-20174230
/dc1/vm/vsanRMI
/dc1/vm/vic-docker
/dc1/vm/Discovered virtual machine
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ govc vm.power -reset=true fahmed-vc65-20174230
Reset VirtualMachine:vm-153... OK
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
tomcat              latest              2da861e12a55        8 days ago          356.8 MB
tomcat              <none>              2da861e12a55        8 days ago          356.8 MB
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker rmi tomcat

fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ 

```
