### ISSUE TITLE
vic-machine create --container-network cannot take a network name with a space

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4479]
Simple problem:

``vic-machine create --public-network "ExternalNetwork" --container-network "ExternalNetwork"`` 
works

``vic-machine create --public-network "External Network"`` 
works

``vic-machine create --public-network "External Network" --container-network "External Network"`` 
does not work:

vic-machine error output:

``Mar 30 2017 21:02:19.420Z ERROR Unable to create appliance VM: A specified parameter was not correct: config.extraConfig["guestinfo.vice./network/container_networks|External Network/Common/ExecutionEnvironment"]
Mar 30 2017 21:02:19.420Z INFO  Collecting ha-host hostd.log
Mar 30 2017 21:02:19.444Z ERROR Creating the appliance failed with A specified parameter was not correct: config.extraConfig["guestinfo.vice./network/container_networks|External Network/Common/ExecutionEnvironment"]. Exiting...
Mar 30 2017 21:02:19.444Z ERROR --------------------
Mar 30 2017 21:02:19.444Z ERROR vic-machine-linux create failed: Creating the appliance failed with A specified parameter was not correct: config.extraConfig["guestinfo.vice./network/conta``

Given that one parameter deals correctly with the space, but the other doesn't ... plus the fact that the error message is ugly, we should fix this if it's easy.

**Comment by mhagen-vmware** [comment]
please prioritize, label and estimate and move to backlog

**Comment by mdubya66** [comment]
This appears to be fixed with this PR https://github.com/vmware/vic/pull/5351. Closing.
