### ISSUE TITLE
vCenter testbed for CI

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#448]
We need a vCenter 6.0u2 cluster with shared storage to run integration tests against.  Starting the basic setup including:

* VCSA

* 3 ESXi hosts (nested)

* vSAN cluster / datastore

* DVS (with internal/external port groups)

**Comment by emlin** [comment]
skinner.eng.vmware.com
 administrator@vsphere.local/ca$hc0w

This VC includes three physical hosts in Austin cluster, and DRS is enabled.

**Comment by hickeng** [comment]
No internal username/passwords in github issues please.

**Comment by emlin** [comment]
Removed. Will have a place for these internal information.

**Comment by dougm** [comment]
Removed 'internal' as we have since found an external solution (details to follow).  We will be able to reuse most of the bonneville-infra scripts to automate the install/config.

**Comment by dougm** [comment]
New version of the scripts are working fine.  However, since switching from PXE to stateless iso for ESX, we lost the ability to configure a static IP.  And we don't have DHCP setup for the new testbed yet.  I plan to get this sorted out today.

**Comment by dougm** [comment]
The VMs also need to use a virtual MAC address which is generated by the provider.  And a different netmask than the esx host itself.  VC still fails to configure the network.  I can get a VM screenshot, but have not been able to get console access (timeout).  Putting this on hold get #479 into PR.

**Comment by dougm** [comment]
Automation is merged.  We'll need to wait until Drone is migrated to the new DC to make use of it via CI.  That work is happening outside of the vic repo, so closing this issue.
