### ISSUE TITLE
vCenter CI testing

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#449]
General capability to test on various vSphere deployment topologies.
Should eventually cover all scenarios in the #97

**Comment by hickeng** [comment]
Moved this under #662 for reference - even if it gets closed the referenced issues can valuable commentary.

**Comment by hickeng** [comment]
@mhagen-vmware please decide whether this has use independent of the other high level testing epics, and close if not.

**Comment by mdubya66** [comment]
Closing as sub-issue is closed
