### ISSUE TITLE
Update vic-machine inspect with DOCKER_CERT_PATH for tlsverify configurations

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4490]
**Story**
As a user of vic-machine I expect `vic-machine inspect` to provide the information I require to access a VCH

**Details**
Inspect is not returning a certificate path - this is because it's potentially hard to do so without some foreknowledge - however it's also not warning about the fact that necessary data is missing.
With the actual output you cannot connect to the docker API as you do not have the client cert.

Actual:
```
vagrant@devbox:~/vic$ vic-inspect
Mar 31 2017 14:21:10.319Z INFO  ### Inspecting VCH ####
Mar 31 2017 14:21:10.517Z INFO  Validating target
Mar 31 2017 14:21:10.675Z WARN  Disabling ha-host hostd.log collection (ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.)
Mar 31 2017 14:21:10.676Z INFO
Mar 31 2017 14:21:10.676Z INFO  VCH ID: VirtualMachine:874
Mar 31 2017 14:21:10.691Z INFO
Mar 31 2017 14:21:10.691Z INFO  Installer version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO  VCH version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO
Mar 31 2017 14:21:10.692Z INFO  VCH upgrade status:
Mar 31 2017 14:21:10.692Z INFO  Installer has same version as VCH
Mar 31 2017 14:21:10.692Z INFO  No upgrade available with this installer version
Mar 31 2017 14:21:10.812Z INFO
Mar 31 2017 14:21:10.814Z INFO  VCH Admin Portal:
Mar 31 2017 14:21:10.814Z INFO  https://192.168.78.127:2378
Mar 31 2017 14:21:10.814Z INFO
Mar 31 2017 14:21:10.814Z INFO  Published ports can be reached at:
Mar 31 2017 14:21:10.814Z INFO  192.168.78.127
Mar 31 2017 14:21:10.825Z INFO
Mar 31 2017 14:21:10.825Z INFO  Docker environment variables:
Mar 31 2017 14:21:10.826Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_HOST=192.168.78.127:2376
Mar 31 2017 14:21:10.826Z INFO
Mar 31 2017 14:21:10.826Z INFO  Connect to docker:
Mar 31 2017 14:21:10.826Z INFO  docker -H 192.168.78.127:2376 --tlsverify  info
Mar 31 2017 14:21:10.826Z INFO  Completed successfully
```

Expected (cert path is specific to the actual environment):
```
vagrant@devbox:~/vic$ vic-inspect
Mar 31 2017 14:21:10.319Z INFO  ### Inspecting VCH ####
Mar 31 2017 14:21:10.517Z INFO  Validating target
Mar 31 2017 14:21:10.676Z INFO
Mar 31 2017 14:21:10.676Z INFO  VCH ID: VirtualMachine:874
Mar 31 2017 14:21:10.691Z INFO
Mar 31 2017 14:21:10.691Z INFO  Installer version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO  VCH version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO
Mar 31 2017 14:21:10.692Z INFO  VCH upgrade status:
Mar 31 2017 14:21:10.692Z INFO  Installer has same version as VCH
Mar 31 2017 14:21:10.692Z INFO  No upgrade available with this installer version
Mar 31 2017 14:21:10.812Z INFO
Mar 31 2017 14:21:10.814Z INFO  VCH Admin Portal:
Mar 31 2017 14:21:10.814Z INFO  https://192.168.78.127:2378
Mar 31 2017 14:21:10.814Z INFO
Mar 31 2017 14:21:10.814Z INFO  Published ports can be reached at:
Mar 31 2017 14:21:10.814Z INFO  192.168.78.127
Mar 31 2017 14:21:10.825Z INFO
Mar 31 2017 14:21:10.825Z INFO  Docker environment variables:
Mar 31 2017 14:21:10.826Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_HOST=192.168.78.127:2376 DOCKER_CERT_PATH=~/localtls/
Mar 31 2017 14:21:10.826Z INFO
Mar 31 2017 14:21:10.826Z INFO  Connect to docker:
Mar 31 2017 14:21:10.826Z INFO  docker -H 192.168.78.127:2376 --tlsverify  info
Mar 31 2017 14:21:10.826Z INFO  Completed successfully
```

**Acceptance**
- [ ] check the following locations for suitable certs
  - $PWD
  - directory named for the target VCH in the vic-machine location
  - $HOME/.docker
- [ ] do not display the .docker cert path (or any path) if the ccerts found in it are not appropriate 
- [ ] if no valid certificate can be found, then add `DOCKER_CERT_PATH=${DOCKER_CERT_PATH:?certificate path must be provided in environment, or certificates specified individually via CLI arguments}`

**Comment by emlin** [comment]
@hickeng 
talked with @gigawhitlocks for this issue as well. How do you think we add one additional option in inspect command to dump out certificate files if not be able to find the original one?

**Comment by emlin** [comment]
vic-machine inspect should try to load certificate from --cert-path or vch name, if not found, dump to the expected directory.
set env similar to vic-machine create did.

**Comment by hickeng** [comment]
@emlin If we're dumping the full configuration, sure, but that's more on the reconfigure side and would require us to decrypt the server certificate key.

In this specific case the only time dumping the certs would help is if we need to get the public server cert to add to the trusted pool of the client in the case that it's self-signed. I don't think the docker client makes use of a self-signed `server-cert.pem` as a means of remote validation if present (but we could confirm), so value would be limited.

The certs that we need in cert path are the following and none of these are stored on the VCH:
* certificate authority to validate the VCH's certificate
* client `cert.pem` & `key.pem` for TLSVERIFY configurations

**Comment by emlin** [comment]
@hickeng thought we persisted the client certificate as well. But this behavior is reasonable.
@anchal-agrawal forget about this suggestion, and keep the original description
