### ISSUE TITLE
vic-machine reconfigure: Update vCenter server credentials

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4495]
**User Statement:**

As a VIC operation user, I need the ability to update the server credentials (username, password/SSO token and server thumbprint) for the appliance, in case the vCenter server credentials have been changed. See one example here #1879.

**Details:**
- supported operations:
  - update username
  - update password
  - update thumbprint
- hot update:
  - no; need to restart the VCH to make the changes take effect.
- input/output data format:
  - input: plain text, e.g., `--username=new-username -- password=new-pwd -- thumbprint=new-thumbprint`
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: The changes will be persisted to the vmx file of the VCH. Then the portlayer will need to reload the VCH configure from the vmx file during VCH restart. 
  - containerVMs: no
- is upgrade needed: 
   -  no, since no VCH configuration changes. 

**Acceptance Criteria:**
-  add the ability to update the server credentials such as username, password/SSO token and server thumbprint though `vic-machine reconfigure`; and the changes will be applied after VCH restart
- add relevant test cases

**Comment by emlin** [comment]
The vCenter user password and host certificate are secret configuration, encrypted with same key.
To support this update, we'll need to load encryption key from ovfenv. Depends on #4516

**Comment by emlin** [comment]
@chengwang86 btw, the major point of this update is for operation user, instead of admin user used by vic-machine, please update the option names
