### ISSUE TITLE
vic-machine reconfigure: Rename the VCH

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4496]
**User Statement:**

As a VIC operation user, I need the ability to rename the vsphere display name of a VCH after it is created.

**Example Use Case**
After creating a VCH, I want to rename it to incorporate the VIC version number for better management.

**Details:**
- supported operation:
  - VCH rename
- hot update:
  - yes; no need to restart the VCH
- input/output data format
  - input: `--name newName`
  - output: N/A
- suggested UX command: 
  - `vic-machine update --modify --name NewName`
- impact on VCH/containerVMs:
  - VCH: We should update (1) the VCH's vsphere display name (2) `common/name` in ExtraConfig (3) vApp/Resource Pool name, (4) server tls certifcate folder name (VCHName by default) and env file name (VCHName by default) and the values in the env file. We do not update the datastore folder name of the VCH. 
  - containeVM: no
- is upgrade related:
  - no

**Acceptance Criteria:**
- add the ability to update the VCH's name. After rename, check that (1)~(4) are updated.
- add relevant test cases
- vic-machine is still able to find and use the VCH certificates after rename (also see #4490)

**Comment by chengwang86** [comment]
For vicadmin, I suspect that the VCH name on the web portal would be updated to the latest name upon page refresh, via calling vsphere API. Need to verify this.

**Comment by chengwang86** [comment]
@hickeng @emlin Currently we use the VCH name as the name and folder name of the TLS certificates. When doing rename, I think these names should also be updated. Any comments?

**Comment by emlin** [comment]
The display name can be used to generate certificate if not specified, but the certificate should still work well after vch rename. (worth to try it to make sure we do not have a wrong assumption)

But if the certificate dir still there, we could rename the certificate folder to the new display name, so that it's easier for vic-machine to find the certificate file during inspect.

**Comment by chengwang86** [comment]
Verified that the vicadmin is able to obtain the latest VCH name after renaming the VCH from vsphere UI.

**Comment by chengwang86** [comment]
if I create a VCH with the name `vch-1`, all the TLS certificates will be stored in a folder `vch-1` under the current directory (where you run the vic-machine cmd), with the following files under `vch-1`:
```
ca-key.pem  ca.pem  cert.pem  cert.pfx  key.pem  server-cert.pem  server-key.pem  vch-1.env
```
The content of vch-1.env is 
```
DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/home/cheng/go/src/github.com/vmware/vic/vch-1 DOCKER_HOST=192.168.144.150:2376
```
**After renaming `vch-1` to `vch-2`, everything works fine even without changing the TLS certificate folder. **

However, to avoid the folder being used by a new VCH named `vch-1` and maintain consistency, vic-machine should be able to `mv vch-1 vch-2`, `mv vch-2/vch-1.env vch-2/vch-2.env`, and also update the `DOCKER_CERT_PATH` in `vch-2.env`.

**Comment by hickeng** [comment]
Agreed that we should do what we can to update certificate directory names - we *must* confirm that the certificates in the directory we find for a given name match those currently configured before the rename.
We should warn the user if the certificate contains the old name and it cannot be updated and is not going to be regenerated.

Discussion about regenerating/replacing server certificates should be associated with that portion of the `reconfigure` work (#4515)

**Comment by emlin** [comment]
@chengwang86 please add the folder and file name change into the description

**Comment by zjs** [comment]
Closing as we've received no user requests for this feature.
