### ISSUE TITLE
Breakdown the Vulnerability scanning PRD into underlying issues. 

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#4505]
As a VIC team member I need to understand the level of effort to meet the requirements spelled out in the PRD. 

**Details:**
The vulnerability scanning PRD contains details on what is requested from PM to meet the customer expectations. These need to be captured so the team can estimate how many sprints it will take to meet the requirements. 
**Acceptance Criteria:**
All issues for the Vulnerability scanning feature are decomposed with estimates added.

**Comment by kreamyx** [comment]
Done!

**Comment by mdubya66** [comment]
Cleaning up this. The Epic should not be in the Sprint, The issue to fill the epic should be.
