### ISSUE TITLE
Certificate Unknown Authority

### ISSUE THREAD

**Issue by lalegre** [vmware/vic#4506]
Suddenly VIC 0.8.0 and 0.9.0 stopped working with the error of the x509 certificate unknown authority.

Can somebody please tell me why this could be?

Thanks in advance.

**Comment by anchal-agrawal** [comment]
@lalegre Is this during installing a VCH or running Docker commands? Please post the commands and logs. Thanks!

**Comment by lalegre** [comment]
Already resolved just needed a reboot
