### ISSUE TITLE
vic-machine reconfigure: Update the TLS certificate for the Virtual Container Host

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4515]
**User Statement:**

As a VIC operation user, I need the ability to update the TLS certificate for the VCH. See here https://vmware.github.io/vic-product/assets/files/html/latest/vic_installation/vch_installer_options.html#adv-security for reference.

**Details:**
- supported operations:
  - update `key` (will be renamed to `tls-server-key`)
  - update `cert` (will be renamed to `tls-server-cert`)
- hot update:
  - no; need to restart the VCH to make the changes take effect.
- input/output data format:
  - input: `--tls-server-key path_to_key_file/key_file_name.pem --tls-server-cert path_to_certificate_file/certificate_file_name.pem`
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: The client will need to use the updated TLS certificate to issue docker commands against the VCH. 
  - containerVMs: no
- is upgrade needed: 
   -  no. The TLS certificate could be updated/reloaded after restarting the VCH. 

**Acceptance Criteria:**
-  add the ability to update the TLS certificate for the VCH; and the changes will be applied after VCH restart
- add relevant test cases

**Comment by emlin** [comment]
@karthik-narayan 
Do we need to support new certificate generation? Or anytime, user wants to update certificate, he/she needs to provide one certificate?

**Comment by gigawhitlocks** [comment]
>We should also rename the keys --cert and --key to --tls-server-cert and --tls-server-key 

I am so ready to make this change.

**Comment by emlin** [comment]
@gigawhitlocks the certificate regeneration will need new option introduced in vic-machine configure, and no customer requires that atm, so let's do the custom certificate reconfiguration only in this story.

**Comment by emlin** [comment]
closed by mistake, just meant to leave a comment

**Comment by gigawhitlocks** [comment]
@emlin I'm going to do the above change because I want to use the new `--tls-server-key` and `--tls-server-cert` arguments in `configure` and not the old `--key` and `--cert` as to not knowingly create debt and also in order to have the arguments match.

**Comment by gigawhitlocks** [comment]
@emlin I won't do any extra work for the generation but I think we're going to get it "for free" with the approach I'm taking in addressing this
