### ISSUE TITLE
vic-machine reconfigure: update DNS servers

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4517]
**User Statement:**

As a VIC operation user, I need the ability to update the dns servers. 

**Example Use Case**
The default dns server is `8.8.8.8`. Now I want to switch to my own dns server.

**Details:**
- supported operations:
  - restore default dns servers (--reset-dns-server)
  - replace existing DNS servers (this corresponds to remove existing servers first and then add new servers. For example, if only one dns server is specified, all the existing dns servers will be replaced by this single one dns server ) (--dns-server)
- hot update:
  - no; need to restart the VCH to make the changes take effect.
- input/output data format:
  - input: e.g., `--clear-dns-server ` or `--dns-server 172.16.10.10 --dns-server 172.16.11.11`
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: The VCH will reload the dns configuration upon VCH restart. 
  - containerVMs: no
- is upgrade needed: 
   -  no

**Acceptance Criteria:**
-  add the ability to update the DNS servers 
- add relevant test cases

**Comment by chengwang86** [comment]
@hmahmood If the newly added DNS server is unreachable, will the VCH try to use the default `8.8.8.8` or just gives up?

**Comment by emlin** [comment]
I think we're able to support modify dns as well, so if user already set a dns server, and wants to change to another one, it's still doable.
