### ISSUE TITLE
vic-machine reconfigure: Update the image datastore

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4519]
**User Statement:**

As a VIC operation user, I need the ability to update the image datastore used for my VCH.

**Details:**
- supported operations:
  - **Since currently VIC does not support multiple image datastores, we will not allow the user to update the image datastore.**
- hot update:
  - no; 
- input/output data format:
  - input: e.g., `--image-store datastore1`
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: no.  
  - containerVMs: no
- is upgrade needed: 
   -  no, since no VCH configuration changes. 

**Acceptance Criteria:**
-  If a user calls vic-machine update function to update the image datastore, he/she will find error messages, e.g., `VIC does not support updating image datastore`
- add relevant test cases

**Comment by chengwang86** [comment]
Although we disallow adding/removing the image datastore in general, there are two corner cases where we might be able to allow updating the image datastore.

**Case I**:
If the existing image datastore that is being used is **empty or the VCH does not have any images yet (only the scratch file)** and the user wants to switch to another image datastore, vic-machine could delete the old image datastore and add the new image datastore specified by the user to its VCH.

**Case II**
If the user wants to switch to a larger image datastore since the old one might be out of capacity, vic-machine could copy all the existing image files to the new image datastore and then delete the old one.

**Comment by emlin** [comment]
The preference so far, is not to do anything for the two scenario @chengwang86 mentioned. 

The first case means user does not have anything yet. In this case, recreate a new VCH is easy.

For the second case, the better technical solution should be leveraging datastore cluster, or multiple image store, cause data copy or move between datastores will significantly impact data I/O on both datastores, we'd better to have some intelligence here, to avoid impact existing container workload, and other vSphere workload sharing the same datastores.

**Comment by zjs** [comment]
Because we don't support multiple image stores, it will be hard to provide a good user experience without a lot of overhead. For now, we recommend creating a new VCH in order to switch the image store. If we were to implement this, we should consider supporting storage pods and SDRS instead.
