### ISSUE TITLE
vic-machine reconfigure: Add the container network settings

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4527]
**User Statement:**

As a VIC operation user, I need the ability to add or remove the container network settings.

**Details:**
- supported operations:
  - add container network. If the container network `label` has been used by existing container networks, vic-machine throws an error msg and the `add` operation will fail.
- hot update:
  - no; need to restart the VCH to make the changes take effect.
- input/output data format:
  - input: `--container-network cont-net-1:net1` (`net1` is the network label)
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: the VCH should be able to allocate new containers which can be connected to the newly added container network.
  - containerVMs: no. 
- is upgrade needed: 
   -  no, since no VCH configuration changes. 

**Acceptance Criteria:**
- add the ability to add the container network settings.
- add relevant test cases

**Comment by emlin** [comment]
To remove container network, vic-machine need to check if there is container attached to that network.
So far, without portlayer, vic-machine is not able to get the connection info, cause that is persisted in key/value store.
Another way is to loop all containers, to check if there is a vnic in that portgroup. If there are many containers, the update becomes more time consuming.

In addition, docker does not support network delete as well.

So in first step, would suggest to add container network only (still in p2). @corrieb @karthik-narayan
