### ISSUE TITLE
vic-machine reconfigure: Enable or disable the debug state

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4530]
**User Statement:**
As a VIC operation user, I need the ability to enable or disable the debug state. Currently the VCH debug state is disabled by default. So I don't have enough log information when failures occur. It will be very helpful if I can switch to debug state (or a higher debug level with more information) to diagnose the failure/error.
This story does not include changing debug level for existing container. That can be down through govc (#4645)

**Example Use Case**
I deployed a VCH with the debug state disabled. A failure occurred in the portlayer and I would like to collect useful logs from the VCH by enabling the debug state.

**Details:**
- supported operations:
  - update the debug state of the VCH
- hot update:
  - no. Need to restart the VCH
- input/output data format:
  - input: e.g., ` --debug 1` (`debug=0` means disabling the debug state)
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: The VCH will produce more log messages for debugging.
  - containerVMs: After we update the debug level of the VCH, new containers will automatically have the new debug level whereas the existing containers (created before vic-machine update) still have the previous debug level.
- is upgrade needed: 
   -  no, since no VCH configuration changes. 

**Acceptance Criteria:**
- add the ability to update the debug state.
- add relevant test cases

**Comment by emlin** [comment]
This change also needs vch restart

**Comment by emlin** [comment]
@corrieb @karthik-narayan @hickeng 
This change is related to container VM. If we enable or disable debug in VCH, the new container will naturally get the new debug level, but for the old containers is still not changed, unless vic-machine update all existing containers.
Is this critical to update existing container's debug state?

**Comment by hickeng** [comment]
I think we can document the steps necessary to manually update a containers debug level and trigger a reload (`govc` or direct editing).

@emlin You have `--debug-level` whereas `vic-machine create` has `--debug` - please be consistent with the argument names

**Comment by emlin** [comment]
@hickeng the issue is still updating. @chengwang86 will update that to be consistent
