### ISSUE TITLE
Tasks Console view in VIC UI workspace

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#4538]
User Statement:

As a UI engineer, I would like to replicate the Tasks Console view from the H5 Client to a reasonable detail.

Details:

The Tasks Console view is part of [PRD 1.2](https://onevmw-my.sharepoint.com/personal/aluther_vmware_com/_layouts/15/WopiFrame.aspx?sourcedoc=%7Bb123251c-42f7-4adc-a1f1-b83d794071d1%7D&action=default) and its UX mockup can be found [here](https://vmware.invisionapp.com/share/P9A37332G#/screens/210384816). Since this view is not part of the public SDK of H5 Client unlike the portlet view, I need to port the H5 Client code myself, which is in AngularJS (or Angular 1) to Angular 2, or 4.

Acceptance Criteria:
1. In the VIC workspace, the Tasks view should display a data grid that looks reasonably the same as the Tasks Console view accessible from the left navigation pane.
2. Tasks view should display all VCH and Container related tasks and refresh itself when a global refresh is issued.

**Comment by mhagen-vmware** [comment]
please estimate and move to backlog when ready

**Comment by jooskim** [comment]
Merged this epic into an existing epic
