### ISSUE TITLE
Map existing vsphere network in installer

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#454]
It is up to the viadmin to determine which vsphere networks are available to a VCH for direct use - meaning that containers can be attached to them directly. All configuration of this type is done via vic-machine, aka the installer.
To reflect default docker behaviour we should enable mapping of the VCH 'external' network by default - this is as close as we can come to -net=host.

On completion:
* the VCH 'external' network is present in 'docker network ls' and containers can reference it via '-net=host'
  * net=host is simply the obvious naming to me - feel free to object/propose alternatives

**Comment by hickeng** [comment]
This has a dependency on #686 or a hack that will then need migrating. My recommendation would be to wait if at all possible and keep in touch with @emlin about when it'll be complete. There are various tests that can be written to validate visibility and reachability of containers in same/different scopes that can be written ahead of time that are not blocked.

**Comment by emlin** [comment]
#686 is replaced by #594, which will be finished this morning.
