### ISSUE TITLE
Test 6-07 create network: bridge network - vcenter none

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4547]
```
    ${output}=  Run  bin/vic-machine-linux create --name=%{VCH-NAME} --target="%{TEST_USERNAME}:%{TEST_PASSWORD}@%{TEST_URL}" --thumbprint=%{TEST_THUMBPRINT} --image-store=%{TEST_DATASTORE} ${vicmachinetls}
    Should Contain  ${output}  FAILURE
```
failure does not exists here, should be looking for:
Apr 3 2017 17:20:37.205-05:00 ERROR An existing distributed port group must be specified for bridge network on vCenter: network 'VCH-0-7850' not found

**Comment by chengwang86** [comment]
I tried it on my VC but I got the expected error msg. Are you able to reproduce this issue?

**Comment by mhagen-vmware** [comment]
My test was on VC 6.0 and RC2 build of VIC, was your test the same?

**Comment by chengwang86** [comment]
VC 6.5 and latest master branch.
