### ISSUE TITLE
tether support for multiple NICs and endpoints

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#455]
The tether currently has code to "Apply" an endpoint (metadata/network_interface.go currently) but no support for actually processing endpoints specified in it's config. The configuration needs to be supplied (#402) and parsed.

Acceptance:

* tether assigns ip address in network specified on the docker create command line to the correct interface in the container
* tether assigns ip address specified on the docker create command line to the correct interface in the container
* stretch: link and mac address for the new endpoint in the container are returned at the port layer. There may be no way to do this at the moment, since the tether only operates on container start, but we should at least investigate if this is possible

**Comment by hickeng** [comment]
@hmahmood returning the MAC prior to power on isn't possible when using generated MACs, because the MAC isn't assigned by VC until then. The reason we're currently using generatedMACs is because they're guaranteed unique - I believe across the entire VC, but definitely across a distributed port group.
I do not know what the consequences would be of moving to explicitly assigning MACs - it should be viable within the bridge networks that we control, but beyond basic possibility I don't know.

What does 'link' mean in this context?

**Comment by hmahmood** [comment]
Well that's a bummer. "link" is the interface's name, e.g. eth0.

**Comment by hmahmood** [comment]
We could also use locally administered mac addresses: https://en.wikipedia.org/wiki/MAC_address#Address_details

**Comment by hickeng** [comment]
@hmahmood read the article but same issue as with VCH managed - I don't know what the impact on VC would be - can you ask the guys in your office for a contact who could definitively answer?
regarding link, that's something I think it makes sense for the VCH to supply - that way the symbolic names of networks are easily mapped to interfaces. My assertion is the primary use for that interface name is allowing the application to selectively listen on specific networks, so naming them appropriately seems an obvious mapping.

**Comment by hickeng** [comment]
Example:
```
$ # map pci slot 32 to a pci bus address
$ cat /sys/bus/pci/slots/32/address
0000:02:00
$ # map the pic bus address to a MAC address - this assumes the device is a network device
$ cat /sys/bus/pci/devices/0000:02:00.0/net/*/address
00:0c:29:01:eb:27
```

Checking that the net/*/address path exists is a good sanity check for the pci slot.

There is a function in the tether [here](https://github.com/vmware/vic/blob/master/cmd/tether/utils_linux.go#L93) to get an interface by it's address
