### ISSUE TITLE
Make vicadmin respect proxy settings

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#4557]
Proxy settings are not applied to the applianceVM as a whole, so the settings must be read out of the environment (stored in an env var) and passed into the Golang HTTP client that does the health checks in vicadmin so that those health checks respect the proxy settings used elsewhere in the application.

**Comment by mdubya66** [comment]
is there a workaround? Should we release note this?

**Comment by gigawhitlocks** [comment]
I don't think there is a workaround. There is definitely not a simple one.

**Comment by gigawhitlocks** [comment]
That being said, it should also not be a terribly difficult bugfix (famous last words).

**Comment by mdubya66** [comment]
@mhagen-vmware this was found by an early adopter customer, wtih no workaround. Should we consider it for 1.1?

**Comment by mdubya66** [comment]
bugzilla 1839818
deferring to 1.2, marking medium

**Comment by stuclem** [comment]
Proposed release note

-----

- <b>VCH Admin portal does not respect proxy settings. [#4557](https://github.com/vmware/vic/issues/4557)</b>

-----

Not really sure what else to say. @gigawhitlocks please feel free to expand.

**Comment by stuclem** [comment]
Added "This affects is the internet connectivity status on the VCH Admin portal, which does not use the proxy used by the rest of the VCH" per suggestion from @gigawhitlocks.

**Comment by morris-jason** [comment]
https://github.com/morris-jason/vic/blob/5066/container-network-validation/lib/vicadmin/validate.go#L174

One of these checks is HTTP and one is HTTPS. If the user enables a HTTP_PROXY on vic-machine, will the HTTPS check fail, and vice versa? @gigawhitlocks

**Comment by morris-jason** [comment]
Supplying a HTTP proxy on vch creation succeeds and works perfectly. However, vic-admin fails to contact vSphere because of a tls issue. @sgairo 
```bash
May 23 2017 21:37:07.092Z WARN  Unable to connect: Failed to connect to 192.168.213.129: Post https://192.168.213.129/sdk: x509: cannot validate certificate for 192.168.213.129 because it doesn't contain any IP SANs
May 23 2017 21:37:07.092Z WARN  192.168.213.1:55622 failed to authenticate 
May 23 2017 21:37:07.153Z INFO  No authentication token: map[]
```

**Comment by sgairo** [comment]
@morris-jason could you attach the full output please :)
