### ISSUE TITLE
docker client 1.13 always returns 0 with VIC

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#4561]
Steps to reproduce:
1. `docker run busybox false` should return 1, but returns 0

**Comment by hmahmood** [comment]
Maybe related to #4504

**Comment by hmahmood** [comment]
Client does not seem to be calling container wait anymore, which is how VIC sends back the exit code. Very likely events are used for this now, and we are not putting the exit code in the events we send back from the port layer.

**Comment by cgtexmex** [comment]
@hmahmood yes events used in place of container wait by 1.13 client.  @sflxn mentioned the need for data to be added to some events, but not sure if that was ever facilitated -- I'm confident I didn't do anything with it.

**Comment by cgtexmex** [comment]
Made the estimate a 5 because it _might_ involve changes to both PortLayer and Persona...at a minimum it's a 3.
