### ISSUE TITLE
need to make the best of build servers

### ISSUE THREAD

**Issue by maplain** [vmware/vic#4569]
#For stories, please include the information below:

**User Statement:**

In CI environment, we want to make sure build servers are not overburdened. But the current way to ensure that often results in less builds running than the number of drone servers.

This problem is more problematic than I initially thought. In essence, there are two sets of resources: drone workers and esxi build servers. The former runs the jobs defined by .drone.yml, one of which is integration-test which requires vc or esxi, so the latter runs that part of jobs. This problem is essentially how to allocate the latter resource for the former ones. We need a simple but practically efficient way to achieve this without race conditions.

**Details:**
Current implementation to decide whether to continue the job pipeline on drone: check whether the job-$(current_job_number - num_drone_servers) is running.
and round-robin in deciding which server to run integration-test.

If number_drone_servers is an odd number, it may happen that all builds are running in even job number and all odd numbers job are killed or cancelled thus the number of builds that are running is actually not restrained by the number of drone servers;
if it is an even number, like what we have now, in most of the cases, less number of builds are running than the number of drone servers.

**Acceptance Criteria:**
every available drone server gets its job whenever needed, and every server is not overloaded

**Comment by maplain** [comment]
hold off on it until next sprint

**Comment by hickeng** [comment]
I think this may be superseded by #4295 but will leave open for now as this is more quickly achievable.

**Comment by mhagen-vmware** [comment]
covered by @mdharamadas1 in https://github.com/vmware/vic/issues/6108
