### ISSUE TITLE
Portlayer handle passing and commit

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#457]
We have two options for the separated portions of the port layer to operate on the same container:
1. the execution component creates it in vSphere and hands back a mo-ref - the storage and network portions would then perform reconfigure operations on that VM
2. all the components hand around a complex handle (config spec) - this is opaque to the personality but is modified by the components

The former has the perk that all port layer component interactions are essentially atomic from the personalities perspective but comes at the cost of multiple vSphere API calls which significantly impacts start time. Another cost is the presence of a partially configured container in the infrastructure which has to be dealt with if appliance restart occurs during creation.

The latter allows us to avoid remote API calls, but also requires a method for the personality to state when the configuration is complete and should be committed. This allows us to avoid multiple vSphere API calls, but a personality interaction with a port layer component is not transactional - for example the handle will have to be passed around the components to release tentatively reserved resources if commit fails. There is no issue here with appliance restart during

**Comment by fdawg4l** [comment]
@hickeng To restate-  the ask here sounds like make an opaque that consists of a vm spec which we only need to call `reconfigure` for a given vm once.  Is that right?

**Comment by hmahmood** [comment]
Yes that is correct.

**Comment by hickeng** [comment]
Assigning to me for additional review - this will either get closed or lead to some follow up issues.
