### ISSUE TITLE
VIC with Docker client 1.13 returns incorrect error message on non-existing object

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4573]
**VIC version:**

Server:
 Version:      0.8.0
 API version:  1.25 (minimum version 1.19)
 Go version:   go1.8
 Git commit:   866fae4
 Built:        Mon Apr  3 22:25:08 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Steps to reproduce:**

Run the following docker command with docker 1.13 client:

docker inspect fake

where **fake** is non existent object

the output is:

_Error response from daemon: vSphere Integrated Containers does not yet support Docker Swarm_

**Actual behavior:**

Both the old and the new client connect to the server to look up different object types that can match **fake**, the last lookup is for a _service_ object. In both cases the VCH returns

_Error response from daemon: vSphere Integrated Containers does not yet support Docker Swarm_

The 1.12 client overrides the server message with the following:

_Error: No such image, container or task: fake_

The 1.13 client does not, therefore the incorrect server error message is returned.

The docker-ce client (Version 17.03.1-ce) against the VCH has a different behavior. In this case the lookup for a "service" is not executed.

**Expected behavior:**

When running against the Docker server with the 1.13 client the output of the command is:

_Error: No such object: fake_

**Logs:**

**This issue is currently blocking: https://github.com/vmware/vic/issues/4368**
[log bundle test 1.23.zip](https://github.com/vmware/vic/files/894865/log.bundle.test.1.23.zip)

**Comment by anchal-agrawal** [comment]
This is similar to #4322. To fix this, we should change https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/swarm.go#L47 to

```go
return types.Swarm{}, nil
```

**Comment by jakedsouza** [comment]
> This is similar to #4322. To fix this, we should change https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/swarm.go#L47 to
> 
> return types.Swarm{}, nil

Changing this makes other swarm tests fail.

**Comment by anchal-agrawal** [comment]
@jakedsouza can you point me to the build link and logs?

**Comment by jakedsouza** [comment]
@anchal-agrawal Build https://ci.vmware.run/vmware/vic/9529  https://vic-logs.vcna.io/9529/

**Comment by anchal-agrawal** [comment]
The only related test failure I see is `Docker swarm join-token` in `1-35-Docker-Swarm`. We can update the test to expect the output to be `Error: No such node:`.

Once that works, we should open a new issue for implementing `docker swarm inspect` (see #4464) and tag that issue in the Robot test.

**Comment by stuclem** [comment]
@mhagen-vmware we don't support swarm in 1.1. Why does this need to go into the release notes?

**Comment by mhagen-vmware** [comment]
While the error message is accurate in that we don't support swarm, it is inaccurate for the command that was run and confusing to the user because swarm doesn't have anything to do with the actual error.
i.e. 
user: I want to eat an apple.
response: sorry, I don't support you eating oranges.

**Comment by stuclem** [comment]
Nice example, @mhagen-vmware. Here's a writeup:

-----

- <b>Docker client 1.13 returns an incorrect error message on non-existent objects. [#4573](https://github.com/vmware/vic/issues/4573)</b><br> If you run a Docker command against a non-existent object, for example `docker inspect fake`, where `fake` is an object that does not exist, vSphere Integrated Containers Engine reports `Error response from daemon: vSphere Integrated Containers does not yet support Docker Swarm`. The error message should be `Error: No such image, container or task: fake`.

-----

Does this cover it? Thanks!

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @mhagen-vmware
