### ISSUE TITLE
Installing UI plug-in reports success when it fails

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#4580]
**VIC version:**

OVA installer: `vic-v1.1.0-rc2-81820686.ova`

**Deployment details:**

Attempting to install the VIC UI plug-in to the vSphere 6.5 HTML5 client for a VC instance running on Windows.

**Steps to reproduce:**

1. Deployed OVA successfully
2. Downloaded and unpacked `vic-engine-v1.1.0-rc2-81820686.tar.gz`
3. Updated vic/ui/vCenterForWindows/configs as shown below:
  ```
REM Enter the IP of the server running vCenter for Windows
SET target_vcenter_ip=10.153.199.35

REM Change the following line to the full URL of the path where the zip files are located
REM For example, if vic-ui.zip is available at https://192.168.1.5/vic-ui-plugins/vic-ui.zip, type in: https://192.168.1.5/vic-ui-plugins/
REM Note: each uploaded zip file will be accessed only once when the user logs into vSphere Web Client for the first time after successful installation
SET vic_ui_host_url=https://10.153.199.189:9443

REM If line 11 starts with "https", enter the SHA-1 thumbprint of the web server hosting the zip files
REM The fingerprint should be in the format of A0:B1:C2:... In case you retrieved the fingerprint from Google Chrome make sure to replace spaces with colons (:)
SET vic_ui_host_thumbprint=16:16:8F:5F:4F:E8:78:56:07:80:F4:66:E4:F5:90:7C:9A:93:AA:B4

REM If you are installing the Flex plugin for vSphere Web Client, please update the value to 6.0, otherwise please leave the value as-is
SET target_vc_version=6.5
```
4. Ran install.bat

**Actual behavior:**
![ui_error](https://cloud.githubusercontent.com/assets/16718369/24702276/559ecb44-19fe-11e7-8f30-427d52ae5732.png)

**Expected behavior:**
The installer should not say Installation of UI plugin succeeded, because it did not succeed. Looking at Extension Manager MOB for the VC, `com.vmware.vic.ui` has not been registered as an extension.

**Additional details as necessary:**

The reason why the deployment is failing with the message about not being able to find the specified path needs more troubleshooting before I log an issue about that (it's probably user error, and highly probably certificate-related). This issue is about the misleading success message. 

Mentioning @jooskim @andrewtchin at the request of @frapposelli.

**Comment by stuclem** [comment]
Also of interest to @alextopuzov

**Comment by jooskim** [comment]
It's been a while since I last worked on `install.bat`. Will reproduce this and fix it soon.

**Comment by stuclem** [comment]
@jooskim I am also consistently seeing this error about the specified path not being found when I attempt to deploy the plug-in to a VC on Windows. Can you see anything wrong with the `configs` file that I posted in the initial description of this issue?

**Comment by jooskim** [comment]
This issue was caused by a recent change in how plugin manifest file is created. I've fixed it and now PR is out for your review.
