### ISSUE TITLE
Update doc link in output of `systemctl status harbor/admiral/fileserver`

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#4581]
**VIC version:**

OVA installer: `vic-v1.1.0-rc2-81820686.ova`

**Deployment details:**

N/A

**Steps to reproduce:**

SSH into the appliance VM and run  `systemctl status harbor/admiral/fileserver`

**Actual behavior:**
Output inludes links to the docs.

Registry: `Docs: http://github.com/vmware/harbor`
Portal: `Docs: https://github.com/vmware/admiral`
Engine: `Docs: https://github.com/vmware/vic`

**Expected behavior:**

Now that I am unifying the docs, it would be better if the link were to https://vmware.github.io/vic-product/index.html#getting-started in all cases.

**Comment by mdubya66** [comment]
Issue moved to [vmware/vic-product #1007](https://github.com/vmware/vic-product/issues/1007) via [**ZenHub**](https://www.zenhub.com/)
