### ISSUE TITLE
create table of docker functions

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#460]
This is a manually curated table of docker function that provides at a glance compatibility, completeness and focus areas. I'd like to have those high level areas map to epics so that users interested in a specific function can subscribe to notifications on that epic and be notified when our support statement changes.

**Comment by hickeng** [comment]
assigning to loc as milestone owner

**Comment by sflxn** [comment]
I've created an initial swag at this list of functionality.  I need input from more people.

https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/CLI-COMPATIBILITY.md

**Comment by sflxn** [comment]
I have created a list of Docker compose file option support.  Waiting on feedback.

https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/COMPOSE-COMPATIBILITY.md

**Comment by sflxn** [comment]
I just did a PR, #511
