### ISSUE TITLE
Update nightlies to use the latest drone

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#4602]
There is a 1 hr hard set default timeout that kills the test, some of the nightlies take longer than an hour. By updating to the latest drone we should be able to configure a timeout larger than 60 min, so tests can finish without timing out.

Acceptance criteria:
Nightlies don't get timeout error after an hour.

**Comment by anchal-agrawal** [comment]
Superseded by https://github.com/vmware/vic/issues/6519 - closing.
