### ISSUE TITLE
Failing nightlies tests leaks VMs causing test instability

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#4603]
Each nightlies test suppose to cleanup the VM resources it creates, so we can efficiently use the nimbus quota. During test failures, the cleanup does not work as expected and the nimbus quota is exceeded after few nighlty runs. We need to cleanup resources efficiently even during test failures.

Acceptance criteria:
The VMs are cleanup after each nightly tests even if the test fails.

**Comment by kreamyx** [comment]
@rajanashok are there logs or anything I can look at so I can zero in on the actual tests that are having clean-up issues?

**Comment by rajanashok** [comment]
v-motion test leaks for sure, but you can look at the past nightly logs from below for more details.

https://console.cloud.google.com/storage/browser/vic-ci-logs/?project=eminent-nation-87317&pli=1&authuser=1&prefix=functional_logs

**Comment by kreamyx** [comment]
@rajanashok As far as I can tell from the logs, I didn't see more nightly tests leaking VMs other than the vMotion ones. If you come across more of them, please reopen this issue or start a new one
