### ISSUE TITLE
Accounts should lock out for at least 15 minutes after 5 invalid password attempts 

### ISSUE THREAD

**Issue by ywk253100** [vmware/vic#4608]
According the security testing criteria, accounts should lock out for at least 15 minutes after 5 invalid password attempts. But on admin portal for VCH, I can try to login over 5 times with invalid password.

**Comment by gigawhitlocks** [comment]
We should add a brief timeout between login attempts as well, to further combat distributed brute force attempts where a botnet is used and requests are not necessarily all originating from the same IP.

**Comment by hickeng** [comment]
The admin portal goes to vCenter directly for validation of the supplied credentials, so we will be reflecting the vCenter configuration. Closing as this is pass-through for a VCH.
