### ISSUE TITLE
[VCH Admin Portal] Credentials are not encoded in the HTTP request.

### ISSUE THREAD

**Issue by wy65701436** [vmware/vic#4609]
I can get the password with the developer tool in the http request(Please refer to the screen shot). It should be encoded.
![d2d6e9ee-1af2-11e7-9a73-9cb8ec94f803](https://cloud.githubusercontent.com/assets/6599778/24763728/d980e4b0-1ab7-11e7-9ee0-cd485442db11.png)

**Comment by hmahmood** [comment]
This is done over https, so this should be OK, but will keep this open for evaluation.

**Comment by gigawhitlocks** [comment]
Yeah, it's encrypted before it's sent over the wire because it's happening as POSTed form data over https. I don't see any advantage to encoding it, as that field will only ever be visible on the system from which the authentication request occurred.

**Comment by hmahmood** [comment]
I don't think this is a problem since credentials are sent over https.
