### ISSUE TITLE
[VCH Admin Portal] Default passwords should be required to be changed at first logon.

### ISSUE THREAD

**Issue by wy65701436** [vmware/vic#4610]
There is not wizard to tell me to change the default password. But according to security testing criteria, it's required.

**Comment by gigawhitlocks** [comment]
The VCH Admin Portal uses vSphere credentials and doesn't store passwords or set them. This requirement is handled via vSphere when the admin creates the credentials used for the VCH

**Comment by hmahmood** [comment]
Tackled in #4631
