### ISSUE TITLE
Sign installer ova and other released binaries

### ISSUE THREAD

**Issue by jakedsouza** [vmware/vic#4635]
As per security checklist all Binaries are signed before being distributed out. 

Expectation: 
Introduce a process to sign official releases of the installer OVA along with all other binaries released.

**Comment by andrewtchin** [comment]
See if we can use the same process Photon team uses to sign RPMs

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #883](https://github.com/vmware/vic-product/issues/883) via [**ZenHub**](https://www.zenhub.com/)
