### ISSUE TITLE
Multiple processes are run as root

### ISSUE THREAD

**Issue by shadjiiski** [vmware/vic#4639]
**Vic version**
vic-engine-v1.1.0-rc2-dc7c489e

**Details**
According to the Security Testing Criteria, processes should be run with as least privileges as possible. However, there are some processes on a VCH (e.g. vic-init, docker-engine-s, port-layer-serv) that are run as root. These probably should be run with another user(s) (for example, vicadmin process is run by the vicadmin user)

**Comment by hickeng** [comment]
Duplicate of https://github.com/vmware/vic/issues/4316
