### ISSUE TITLE
document how to change the debug state/level of an existing container

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4645]
**User Statement:**

As a VIC user, after I change the debug state of my VCH, new containers created by the VCH will take the updated debug state for logging. However, existing containers will still use the previous debug state. We need documentation on how to use `govc` or direct editing to update the debug state for such existing containers when needed. 

**Acceptance Criteria:**
- I should be able to update the debug state of an existing container following the instructions from the documentation.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #510](https://github.com/vmware/vic-product/issues/510) via [**ZenHub**](https://www.zenhub.com/)
