### ISSUE TITLE
port-layer commit

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#465]
This will live as part of the execution component for now as it's integral to the create and start workflows.

The commit call takes a config spec, possibly for a completely new VM, possibly for reconfiguring an existing VM, and actually performs the vSphere operation.

It's probably that most calls mapping to a reconfigure are going to be updating only the ExtraConfig array.

**Comment by fdawg4l** [comment]
Can you expound on this?  Briefly, what is the ask?

**Comment by hickeng** [comment]
@hmahmood is this covered by the PR you're currently working on? If so please assign it to yourself and move it to InProgress.
