### ISSUE TITLE
resource leak(and potential race conditions) in integration-test servers

### ISSUE THREAD

**Issue by maplain** [vmware/vic#4651]
**User Statement:**

If drone job were killed or some test groups failed, there are chances that vch or other resources created by tests are not cleaned up, which may prevent following tests running in other jobs succeeding. Tests also may share some resources like network or disk, which could also give rise to contentions or performance degradation.

**Details:**
there may have following sources of leakage right now:
1. some keywords in robot don't cleanup the resources they created;
2. test teardown, suite teardown may not work as expected under some conditions;
3. drone job is directly killed;

there may have following sources of contention right now:
1. share default network;
2. share the same files on disk;
3. other resource names(eg: vm) that are not parameterized;

**Acceptance Criteria:**
1. able to differentiate leaked resource and resource being used;
2. eliminate resource contention as much as possible, eg: every test creates its own network, and install vic to different path on datastore;
3. tests have clear-defined behaviors, and resource-creating keywords should have their corresponding resource-destroying companions;

This may relate to resource usage: https://github.com/vmware/vic/issues/4569

**Comment by mhagen-vmware** [comment]
While we definitely need to make sure any tests cleanup after themselves we have this in order to avoid leakage:
https://github.com/vmware/vic/blob/master/tests/resources/VCH-Util.robot#L159-L163

**Comment by maplain** [comment]
resources here may refer to a broader meaning. It can mean any file created during the test which may impact negatively on following tests, for example, a certificate fetched from a deployed harbor(datastore1 is the default value) or some daemon process since all our integration tests run in one container(on drone) which share the same environment, for example a dockerd or it could even be some environmental variables which are widely used and modified dynamically, still because all integration tests run in one container and one process. This is just based on my past limited personal experience, trying to make test environment more predictable, writing tests easier and more straightforward.

**Comment by mhagen-vmware** [comment]
AFAIK, all leakage has an equivalent cleanup at this point.
