### ISSUE TITLE
Nightly vSphere 6.0 heterogenous test fails to add host to VC

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#4655]
```KEYWORD Vsphere-Util . Add Host To VCenter ${esx3-ip}, root, ha-datacenter, e2eFunctionalTest
Start / End / Elapsed:	20170409 09:46:41.721 / 20170409 09:54:41.963 / 00:08:00.242
00:08:00.239FOR ${idx} IN RANGE [ 1 | 4 ]
Start / End / Elapsed:	20170409 09:46:41.722 / 20170409 09:54:41.961 / 00:08:00.239
00:02:40.411VAR ${idx} = 1
Start / End / Elapsed:	20170409 09:46:41.723 / 20170409 09:49:22.134 / 00:02:40.411
00:02:40.387KEYWORD ${out} = OperatingSystem . Run govc cluster.add -hostname=${host} -username=${user} -dc=${dc} -password=${pw} -noverify=true
Documentation:	
Runs the given command in the system and returns the output.
Start / End / Elapsed:	20170409 09:46:41.723 / 20170409 09:49:22.110 / 00:02:40.387
09:46:41.738	INFO	Running command 'govc cluster.add -hostname=10.192.217.112 -username=root -dc=ha-datacenter -password=e2eFunctionalTest -noverify=true 2>&1'.	
09:49:22.110	INFO	${out} = 
[K[09-04-17 14:46:42] adding 10.192.217.112 to cluster /ha-datacenter/host/cls... 
[K[09-04-17 14:46:42] adding 10.192.217.112 to cluster /ha-datacenter/host/cls... (0%)
[K[09-04-17 14:46:42] addi...	
00:00:00.022KEYWORD ${status} = BuiltIn . Run Keyword And Return Status Should Contain, ${out}, OK
Documentation:	
Runs the given keyword with given arguments and returns the status as a Boolean value.
Start / End / Elapsed:	20170409 09:49:22.111 / 20170409 09:49:22.133 / 00:00:00.022
00:00:00.019KEYWORD BuiltIn . Should Contain ${out}, OK
09:49:22.133	INFO	${status} = False	
00:00:00.001KEYWORD BuiltIn . Return From Keyword If ${status}
00:02:39.830VAR ${idx} = 2
00:02:39.997VAR ${idx} = 3
00:00:00.001KEYWORD BuiltIn . Fail Failed to add the host to the VC in 3 attempts
Documentation:	
Fails the test with the given message and optionally alters its tags.
Start / End / Elapsed:	20170409 09:54:41.962 / 20170409 09:54:41.963 / 00:00:00.001
09:54:41.963	FAIL	Failed to add the host to the VC in 3 attempts

**Comment by rajanashok** [comment]
This only repros on a vSphere6.0 nightly runs.
[5-5-Heterogenous-ESXi.zip](https://github.com/vmware/vic/files/908683/5-5-Heterogenous-ESXi.zip)

**Comment by rajanashok** [comment]
Able to manually repro this issue. The testbed is available to debug.

govc cluster.add -hostname=10.192.169.117 -username=root -dc=ha-datacenter -password=e2eFunctionalTest -thumbprint 1B:FB:77:69:9C:3D:4B:77:CC:57:8A:C0:BC:48:0C:88:B4:0F:8C:FE
[12-04-17 08:55:01] adding 10.192.169.117 to cluster /ha-datacenter/host/cls... Error: A general system error occurred: Timed out waiting for vpxa to start
govc: A general system error occurred: Timed out waiting for vpxa to start

**Comment by dougm** [comment]
Problem is that vCenter version is 6.0, but ESX version is 6.5

VC: VMware vCenter Server 6.0.0 build-3634794
ESX: VMware ESXi 6.5.0 build-4240417

Command fails with "A general system error occurred: Timed out waiting for vpxa to start"

vpxa logs on the ESX host:

```
govc logs -log vpxa

2017-04-12T16:05:48.241Z error vpxa[A832B70] [Originator@6876 sub=SoapAdapter] Unsupported version URI "urn:vpxa3/6.0"
```

Solution: use ESX version 6.0

**Comment by rajanashok** [comment]
Thanks Doug, will add a VC version check to the test.

**Comment by chengwang86** [comment]
6.0
[5-5-Heterogenous-ESXi.zip](https://github.com/vmware/vic/files/1059219/5-5-Heterogenous-ESXi.zip)

**Comment by mhagen-vmware** [comment]
I will capture a fix for this again in my PR for the other hetero test work I am doing.

**Comment by mhagen-vmware** [comment]
@chengwang86 Also, unless the original issue wasn't fixed, please don't open old bugs.  While this is essentially the same issue, it is a new instantiation of it - since we updated to the newer versions of 6.0/6.5 our original logic to prevent adding a 6.5 ESX to a 6.0 VC is no longer valid.  But the original bug fix was valid and worked, so we should not reopen a bug like this we should open a new bug.
