### ISSUE TITLE
[OVA] Admiral container should define a volume to persist the logs there

### ISSUE THREAD

**Issue by sergiosagu** [vmware/vic#4680]
Within the OVA for 1.1 we need Admiral container to define a volume to persist the logs there, otherwise the container logs are lost when, for example, the VA is restarted and (a new) Admiral container is recreated.

**Steps to reproduce:**
Deploy VIC 1.1 OVA.
Do some operation in Admiral (e.g. add host, add certificate, whatever), and check that it will generate some logs.
Restart the VA and check whether the old logs are there.

**Actual behavior:**
Admiral container logs are brand new after restarting the VA.

**Expected behavior:**
Admiral container logs are brand new after restarting the VA, but the logs from previous Admiral containers runs are kept somewhere and are accessible.

**Additional details as necessary:**
cc @frapposelli @tgeorgiev

**Comment by frapposelli** [comment]
We do persist admiral logs using systemd (`journalctl -u admiral.service`) so we're not losing logs at restart.

Moving to priority low

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #885](https://github.com/vmware/vic-product/issues/885) via [**ZenHub**](https://www.zenhub.com/)
