### ISSUE TITLE
vic-machine output and generated env is wrong if --cert-path specified

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4683]
If you run vic-machine with --cert-path and ask it to generate certificates into the path specified, it does that fine. However, the .env file it creates and the helpful output produced by vic-machine does not take the --cert-path into account and shows the default path.

Example:

```
vic-machine-linux create --tls-cname *.eng.vmware.com --cert-path=/certs --thumbprint=F2:97:19:09:64:0A:06:3C:67:57:F7:CB:B5:3A:21:50:30:46:A0:54 --name=dev-cert --target=10.118.69.238 --user=Administrator@vsphere.local --image-store=iSCSI-nas-2 --password='xxxxxxxx' --bridge-network=dev-bridge --public-network=ExternalNetwork --compute-resource=iSCSI --timeout 60s --volume-store=iSCSI-nas-2/dev:default --container-network=ExternalNetwork
```

The above cmd-line generates certs into the right place, but the instructions from VIC machine and the output of the env file are wrong:

```
Apr 11 2017 16:00:22.309Z INFO  Docker environment variables:
Apr 11 2017 16:00:22.309Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/home/vagrant/vic/src/github.com/vmware/dev-release/vic/dev-cert DOCKER_HOST=office2-sfo2-dhcp335.eng.vmware.com:2376
Apr 11 2017 16:00:22.310Z INFO  
Apr 11 2017 16:00:22.310Z INFO  Environment saved in /certs/dev-cert.env

> cat /certs/dev-cert.env 
DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/home/vagrant/vic/src/github.com/vmware/dev-release/vic/dev-cert DOCKER_HOST=office2-sfo2-dhcp335.eng.vmware.com:2376
```

**Comment by corrieb** [comment]
Assessment: Using certificates will be the default mode in production for companies and this will be an annoying and highly visible problem for them.

**Comment by hickeng** [comment]
Looks like the specific file paths used are correct in `lib/install/management/inspect.go:GetDockerAPICommand` however the cert path option was never integrated into that logic.
This may be a little more involved to fix than might be assumed as this code is used for `vic-machine inspect` and leveraged in `vic-machine create` - inspect does not have a `--cert-path` option and shouldn't need one.

If we cannot find the certificates for a VCH that needs them then the `inspect` output should reflect that lack with a warning.

**Comment by hickeng** [comment]
Incorrect output from vic-machine is a significant UX issue for us atm and should be addressed asap.

**Comment by stuclem** [comment]
@corrieb and @hickeng, does this need a release note in 1.1?

**Comment by gigawhitlocks** [comment]
@stuclem yes this does need a release note; I just saw your question and IDK if anyone gave you an answer
