### ISSUE TITLE
OVA Should print the URL to download VIC on the console screen like the other links

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4684]
Currently only prints container registry and management portal URLs, we should also print the URL for downloading UI and engine.

IP:9443

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic/blob/master/installer/ovatools/vic-ova-ui/main.go#L98

**Comment by andrewtchin** [comment]
Also display a link to the VIC Engine Installer service in the console.

**Comment by andrewtchin** [comment]
Dup of #4734 closing.

**Comment by andrewtchin** [comment]
Er misread, not a dup reopening

**Comment by stuclem** [comment]
A link to the doc might be nice too.
