### ISSUE TITLE
OVA should redirect http requests to https requests

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4685]
If I don't explicitly specify https protocol I get an ERR_EMPTY_RESPONSE page

We should add an auto redirect to https or at least a better error than that.

**Comment by andrewtchin** [comment]
What URL/port is this for? This won't be possible for the webserver on 9443 because that socket is already using TLS
We would only be able to redirect if the initial dest port is using HTTP then we can redirect to a TLS port

**Comment by andrewtchin** [comment]
Something like this might be possible with nginx

**Comment by andrewtchin** [comment]
Run nginx on port 80 and redirect to 9443

**Comment by andrewtchin** [comment]
Jason implemented the redirect from 80 to 9443, leaving this open to see if we can catch http requests to the services listening for https and redirect them to https

**Comment by mdubya66** [comment]
Issue moved to [vmware/vic-product #1005](https://github.com/vmware/vic-product/issues/1005) via [**ZenHub**](https://www.zenhub.com/)
