### ISSUE TITLE
design doc: portlayer component communication

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#469]
Port layer design doc. This covers API style as well as the details of the communications between components.

**Comment by hickeng** [comment]
https://github.com/hickeng/vic/tree/469

**Comment by hickeng** [comment]
removed from single network container - this was to support #457 which has been tentatively merged.

**Comment by corrieb** [comment]
There's no much point tackling this until #1043 and #755 are being tackled. These are both GA target. I would suggest we also move this to GA.

**Comment by mdubya66** [comment]
making medium based on port-layer re-design
