### ISSUE TITLE
Create malformed image layer

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4690]
**Story**
As a VIC developer I want to have access to malformed images in a registry to test image validation

**Detail**
Create an image manifest with mismatched JWS signature and load/inject it in into a registry (docker distribution or otherwise) in a manner that can be automated within CI testing.

**Acceptance**
- [ ] repeatable image injection that fails docker-engine manifest validation.

**Comment by gigawhitlocks** [comment]
Easiest approach will likely be borrowing resources used by this test to do something similar https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-02-Docker-Pull.robot#L242
