### ISSUE TITLE
Create malformed image manifest

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4691]
**Story**
As a VIC developer I want to have access to malformed images in a registry to test image validation

**Detail**
Create a layer and load/inject it in into a registry with a digest that doesn't match it's blobSum, in a manner that can be automated within CI testing.

**Acceptance**
- [ ] repeatable layer injection that fails docker-engine layer digest validation.

**Comment by gigawhitlocks** [comment]
Easiest approach will likely be borrowing resources used by this test to do something similar https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-02-Docker-Pull.robot#L242
