### ISSUE TITLE
RBAC integration for Admiral and Harbor

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4708]
**User Statement:**
Admiral+PM (Project Manager) should provide a single Access Control mechanism based on Roles. 

**Details:**
PRD requirement: [2.1.3] P0-1: Multiple projects per Developer
PRD requirement: [2.1.5] P0-3: Auditing Authentication & Authorization (Authorization Auditing)

Admiral+PM will implement RBAC for both Admiral and Harbor. Harbor will call as set of API served by PM. This epic has three major threads:

- Provide assistance/feedback to the Admiral team during the design and early testing phase,
- Migration of existing Harbor data (i.e. projects) into the new integrated environment (tools to be provided by the Admiral/Harbor teams), the migration should occur during the VIC product upgrade process
- Modify VIC OVA to account for the tight integration between PM, Admiral and Harbor.

**Acceptance Criteria:**
The RBAC model implemented by Admiral+PM should satisfy VIC product needs. VIC product upgrade should work across the restructuring of Harbor. This should extend to Harbor deployments where replication is enabled among instances. VIC OVA should deploy integrated PM/Admiral/Harbor.

**Comment by hsluoyz** [comment]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

So please consider using casbin when vic implements RBAC security. Also let me know if there's any question :)

**Comment by lcastellano** [comment]
Hi Yang, thanks for your suggestion. Casbin looks very interesting, however our RBAC functionality is implemented inside Admiral (Xenon/Java code base).  If that implementation moves to GO Casbin will be definitely at the top of the list.
