### ISSUE TITLE
Investigation and testing of OIDC support in PSC

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4709]
**User Statement:**
Plan of record is for Admiral to use PSC for implementation of OIDC based Authentication. This activity consists in exploring OIDC configuration in PSC  6.5 and verifying OAuth flows (Authz-Token and User Credentials).

**Details:**
The consumer of the OIDC APIs implemented by PSC 6.5 is Admiral/Procject-Manager, however the VIC team in PA and SF has had extensive experience using Lightwave. The purpose of this activity is to explore usage of OAuth/OIDC with a pre-installed PSC (instead of a custom LW) and provide support (early investigation) for the Admiral/PM team.

**Acceptance Criteria:**
Collect and publish OAuth/OIDC configuration for PSC, try some basic authentication flows.

**Comment by lubronzhan** [comment]
Here is the investigation I've taken.
https://confluence.eng.vmware.com/display/EO/Investigation+and+testing+of+OIDC+support+in+PSC

OIDC authentication with PSC 6.5 is feasible.

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
@lubronzhan Are you waiting on anything else to close this?

**Comment by lubronzhan** [comment]
Oh thanks for reminding. I'll close it right away
