### ISSUE TITLE
OIDC-RBAC design review in Admiral/PM

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4712]
**User Statement:**
The Admiral/PM team is designing and implementing OIDC based Authentication and RBAC for the VIC product. VIC-OVA team needs to be deeply involved in the design of this shared component.

**Details:**
PRD requirement [2.1.3] P0-1: Multiple projects per Developer
PRD requirement [2.1.5] P0-3: Auditing Authentication & Authorization

This activity should include working closely with the Admiral+PM team on the design of the RBAC services. This is an ongoing, non full time activity. 

**Acceptance Criteria:**
RBAC and OIDC design documents from Admiral/PM.

**Comment by lcastellano** [comment]
The new RBAC system will be imlemented in Admiral, here is the repository of the design docs:

https://confluence.eng.vmware.com/pages/viewpage.action?pageId=216835445

**Comment by mhagen-vmware** [comment]
verified
