### ISSUE TITLE
[UI] The layout issue on the Existing Registries Data Grid.

### ISSUE THREAD

**Issue by wy65701436** [vmware/vic#4713]
Please see the screen shot. My browser is Chrome, Version 57.0.2987.133

![image](https://cloud.githubusercontent.com/assets/2841473/24938250/8ecf52de-1f68-11e7-892f-758304705b99.png)

**Comment by mdubya66** [comment]
Thanks for raising the issue. The Registry issues are tracked on the harbor github. Please open this issue in https://github.com/vmware/harbor/issues

**Comment by wy65701436** [comment]
@steven-zou is this owned by harbor? Can you help to confirm?
