### ISSUE TITLE
Broadcast ARP when binding IP address

### ISSUE THREAD

**Issue by douggie** [vmware/vic#4715]
**User Statement:**

As a customer of VIC, I would like to set a leverage external networks and have a container be routable from other hosts by updating it's default gateways routing table via an ARP.

**Details:**
Once a container has bound an external IP address it should  broadcast an ARP so that the nearest router can update it's ARP cache with the new mac so that traffic can now be routed to the container on the given external IP address. Current work around is to issues ARP's via a script.
arping -A -c 1 -I eth0 $my_ip 2>&1
arping -U -c 1 -I eth0 $my_ip 2>&1

**Acceptance Criteria:**
Create a container on a external/container network with a given IP address, then delete that container, create a new container with the same IP address, the new container should be accessible from a host on another vLAN.

**Comment by hmahmood** [comment]
This has already been done in https://github.com/vmware/vic/issues/2932

**Comment by hmahmood** [comment]
@douggie what is the original problem that you're seeing?

**Comment by hickeng** [comment]
confirmed issue - closing in favour of reopened #2932
