### ISSUE TITLE
VIC-OVA configuration changes for Admiral/PM

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4724]
**User Statement:**
In VIC 1.2 Admiral/Project-Manager will implement SSO and RBAC for both Admiral and Harbor. There will be new options/parameters to configure Admiral/PM. Those should be exposed in the VIC OVA.

**Details:**
Various new options (e.g. Identity Provider address) should be included in the configuration options for the Admiral/PM.

**Acceptance Criteria:**
New configuration options/parameters should be supported. Basic unit tests included.

**Comment by lcastellano** [comment]
This issue depends on a design document that finalizes the init configuration parameters for Admiral within the VIC OVA. Could not find a correspondent issue in the Admiral set.

**Comment by andrewtchin** [comment]
Confirmed with Sergio and Luca that the OVA deploy wizard doesn't need new parameters for Admiral at this time.
