### ISSUE TITLE
Integration tests for VIC-OVA config changes: Admiral/PM

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4725]
**User Statement:**
New integration tests are needed to test the new configuration options for Admiral/PM

**Details:**
Admiral/PM will have new configuration options (e.g. Identity Provider), that need to have integration tests.

**Acceptance Criteria:**
VIC-OVA integration tests, positive and negative test cases.

**Comment by lcastellano** [comment]
Depends on https://github.com/vmware/vic/issues/4724

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #887](https://github.com/vmware/vic-product/issues/887) via [**ZenHub**](https://www.zenhub.com/)
