### ISSUE TITLE
VIC-OVA support for Harbor migration to common RBAC model

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4726]
**User Statement:**
In VIC 1.2 Harbor will use Admiral/PM to support Authentication and RBAC. VIC-OVA needs to apply the proper migration tools.

**Details:**
Harbor stores entities like Projects in its own DB. Projects are likely to be moved into Admiral/PM with the new shared architecture. Admiral/Harbor team should provide a tool to support the data migration. VIC-OVA should apply the tool when performing the upgrade. Particular attention should be focused on installation when image replication is enabled on Harbor.

**Acceptance Criteria:**
- [ ] OVA implements procedures to properly upgrade Harbor including database updates and data migration to Admiral
- [x]  remove the Harbor link from the OVA console screen

**Comment by lcastellano** [comment]
Harbor Projects are stored in Harbor in VIC 1.1 but are stored in Admiral in VIC 1.2. During an upgrade of Harbor the projects should be migrated into Admiral. This requires running a "migration" script during the upgrade, the script should be part of the OVA and must run during upgrade. It has to be integrated with the initialization of Admiral and Harbor (must occur after Admiral has been properly setup and it has started). This depends on https://github.com/vmware/harbor/issues/2582

**Comment by andrewtchin** [comment]
Admiral and Harbor will be merged into one UI and use one service for SSO/project management.  Harbor UI will be disabled so remove the Harbor link from the OVA console screen

**Comment by andrewtchin** [comment]
Updated to make this clear this issue covers all aspects of Harbor migration including database migration and data migration to Admiral
