### ISSUE TITLE
VIC-OVA configuration support for Harbor in the unified SSO/RBAC environment

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4727]
**User Statement:**
In VIC 1.2 Harbor should use Admiral/PM for SSO and RBAC. New configuration parameters might be necessary (e.g. TLS) to support this tightly integrated configuration.

**Details:**
New configuration parameters along with a re-factoring of the install/upgrade procedure will be necessary to support the common SSO/RBAC environment. Admiral and Harbor must be able to communicate with each other and be properly configured for that goal.

**Acceptance Criteria:**
Support for new config parameters/options in Harbor. Basic unit tests.

**Comment by reasonerjt** [comment]
As per my understanding, the "registry admin password" should be removed.

And Harbor may need the information for communication with RBAC service and Project management service, such as endpoint url, cert, .etc.

**Comment by lcastellano** [comment]
Until some level of detailed integration is achieved between Admiral and Harbor I don't see how can we reasonably assume that this issue is going to be resolved during the next sprint. Many initialization issues are still being worked out by the Amiral/Harbor teams. I believe we'll have a clearer picture when the Harbor engineer (Steven) will be here in Sofia at the begging July.

**Comment by andrewtchin** [comment]
WIP branch including removal of registry admin password is at https://github.com/andrewtchin/vic-product/tree/4727/harbor-upgrade

**Comment by andrewtchin** [comment]
We discussed having passwords for database and clair autogenerated and added to `harbor.cfg` during startup. 
@reasonerjt  Let me know the key in the config for each of these values and if there are any length/complexity requirements for the generated passwords.
