### ISSUE TITLE
Integration tests for VIC-OVA config changes: Harbor

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4728]
User Statement:
New integration tests are needed to test the new configuration options for Harbor

Details:
Harbor will have new configuration options (e.g.TLS configuration), that need to have integration tests.

Acceptance Criteria:
VIC-OVA integration tests, positive and negative test cases.

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #888](https://github.com/vmware/vic-product/issues/888) via [**ZenHub**](https://www.zenhub.com/)
