### ISSUE TITLE
[ova] Create OOTB local users

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4729]
PRD 1.1
* A default cloud-admin, a project admin and a developer are created 
* Their usernames should be cloudadmin, projectadmin and developer. 
* The password for all three local users should be “changeme” and they should be prompted in the first login attempt to change the password

**Comment by andrewtchin** [comment]
This means create users in Admiral

**Comment by andrewtchin** [comment]
There is currently no support for logins in Admiral. Needs to be deferred until there is or implemented with PSC integration.

**Comment by andrewtchin** [comment]
If we use `dir-cli` this will require SSHing into the vCenter and storing the admin credentials to execute commands with `dir-cli`

**Comment by andrewtchin** [comment]
If this needs to be Java code in Admiral with an API, we can merge the API first then call that from the OVA web installer

**Comment by andrewtchin** [comment]
Deprioritizing and replacing with #5456 until Admiral provides a REST API to create person users in the PSC
When we have that API, the demo installer can add these users @sergiosagu 
Also requirements are amended to not require changing password after user creation. The demo installer should prompt for what the password should be set as.

**Comment by mdubya66** [comment]
Removing from 1.2, replaced by #5456

**Comment by mhagen-vmware** [comment]
@lcastellano should this be in verify column?

**Comment by mhagen-vmware** [comment]
closing based on merging of the PR above

**Comment by anchal-agrawal** [comment]
From @lcastellano's PR (https://github.com/vmware/vic-product/pull/582#issuecomment-322569106):

> Yes, it implements most of the functionality. The only difference is that the passwords are not "changeme" and the user is not prompted to replace them. The password (one for all the three users) is chosen as part of the OVA config. The users are "local" PSC users. To change the password you have to go through the VSphere UI.

@lcastellano @frapposelli Should we re-open this issue and move it out of the 1.2 release since most of the functionality has been implemented? Or should we open follow-up issues? Thanks.

**Comment by lcastellano** [comment]
We are using PSC (vsphere.local) as the Identity Provider for the out-of-the-box users. As far as I know there is no way to have the user created with a temporary password that is changed at the first login in. That flow is just no supported by the PSC. I suggest we close this issue until a new Identity Provider is added to Vic-Product.
