### ISSUE TITLE
[ova] Create a default project

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4730]
PRD 2.2
* A default project with the name “Default project” should be created in the system 
* The Project admin for the project should be set to to the user “projectadmin” 
* The developer for the project should be set to the user “developer” 
* The default repository with the “Hello-world” image should be added to the project

**Comment by andrewtchin** [comment]
Depends on/concurrent with #4729

**Comment by andrewtchin** [comment]
@karthik-narayan Admiral doesn't seem to have a concept of Project - could you clarify what this should do?
Looks like this also depends on #4736 for the hello world image

**Comment by karthik-narayan** [comment]
@andreiw Let me start a thread with the Admiral team to see when they plan on enabling this. It's slated for 1.2.

**Comment by andrewtchin** [comment]
Default project is already being created by Admiral
```
root@localhost [ ~ ]# curl -k https://10.192.169.112:8282/projects/default-project
{
  "isPublic": false,
  "administratorsUserGroupLink": "/core/authz/user-groups/f56a2e11a0b788755517804b6b368",
  "membersUserGroupLink": "/core/authz/user-groups/f56a2e11a0b788755517804b72c82",
  "id": "default-project",
  "name": "default-project",
  "documentVersion": 0,
  "documentEpoch": 0,
  "documentKind": "com:vmware:admiral:auth:project:ProjectService:ProjectState",
  "documentSelfLink": "/projects/default-project",
  "documentUpdateTimeMicros": 1496950800144000,
  "documentUpdateAction": "POST",
  "documentExpirationTimeMicros": 0,
  "documentOwner": "9b7e546a-8cd4-4745-b2fa-d92b0afe1305",
  "documentAuthPrincipalLink": "/core/authz/system-user"
```

**Comment by andrewtchin** [comment]
Closing this since the default project exists. Moved additional requirements that can't be fulfilled yet because requirements don't exist yet to the relevant open issues.
