### ISSUE TITLE
[ova] Create a default VCH

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4731]
PRD 2.3
* A default VCH with the name “Default VCH” should be created

**Comment by andrewtchin** [comment]
This will be heavily environment dependent - user would need to configure image store, networks, etc.

**Comment by andrewtchin** [comment]
@karthik-narayan what are the UX expectations for this feature?
We don't really have a way to provide feedback from `vic-machine create` if the install fails and the parameters that would be taken from the OVA install wizard would be easy to enter incorrectly.

**Comment by karthik-narayan** [comment]
The idea here is to ensure that the install and configure step should leave the admin with a setup that they can use right away. I'm very open to how you want to accomplish this, but where possible I'd like to avoid asking the user for the same information. 

As we go through this process, we might determine the need for some additional/ missing features from other components and if so we can call them out. 

Setting aside engineering validation, here are a couple of acceptable ways to accomplish this IMO. The assumption I've made is that we re-use the datastore, compute and networking options of the OVA to create the VCH. For the bridge network, we create a "default VCH bridge network".

1. As a part of the OVA install, the user checks a "Create a default" VCH option. When selected, we re-use the info we have and kick off a vic-machine command, display the output along with the command that was kicked off. 

2. A less acceptable solution would be that at the end of the install process, we call generate a vic-machine command that the admin can copy and paste to create a VCH. Again, we re-use the VCH data to fill things out. 

3. Another option, which will need some research is the ability for Admiral to create a new VCH. We have a VRO workflow that someone has created and our solution could be to use that. 

At the end of the day, we should reduce the number of steps / things that an admin has to perform post-install to get to a working default VCH. This VCH will be for demo purposes only and can be configured with restricted settings if necessary. 

Hope that helps.

**Comment by andrewtchin** [comment]
@stuclem This needs a doc, we'll send a draft for you

**Comment by morris-jason** [comment]
# Using the Demo VCH Installer

A web service is automatically started on the VIC OVA upon successful installation. This web service, the **Demo VCH Installer,** allows you to install a VCH without using the CLI, albeit with limited options.

Only the Bridge Network, Public Network, Image Store, and Compute Resource options are currently supported, as those are the requirements for a bare-minimum vCenter install. This is not meant to be a full-featured installer and does not include tls support. For advanced usage please use the vic-machine create CLI.

### Usage

Once your OVA is installed, navigate to `https://<OVA-IP>:1337` in your browser and trust the certificate. The webservice contains two pages - a login page and an execution page. 

##### Login

In the Login page you should enter the IP, Username, and Password of the vCenter instance that's running the OVA. If your credentials are valid you'll be directed to the next page. 

##### Execution
Once on the Execution page you'll find a series of drop downs boxes and text fields for VCH creation options. All fields should be populated *with the exception of the target thumbprint*. 

Select the appropriate options - leaving thumbprint blank - and press Execute. The Execution Output should contain a thumbprint of the vCenter target, which you can copy and paste into the thumbprint field. Press Execute again and your vic-machine create command should start running. 

You can scroll down as more output logs are appended. It is advised to stay on the Installer page until command completion - your logs may stop streaming if you switch tabs or windows. 

The vic-machine create command output upon execution may be copied a cli and used there as well.

### Admiral Integration

The OVA Appliance also runs instances of Harbor and Admiral. Upon successful creation of the VCH, the Demo Installer web service will attempt to add the new VCH to the Admiral instance running on the OVA. You can check the VCHs attached to Admiral at `https://<OVA-IP>:8282`

**Comment by morris-jason** [comment]
@stuclem doc'd. Let me know if you need more info.

**Comment by stuclem** [comment]
@morris-jason and @andrewtchin thank you for this, and apologies for only seeing it now. Created https://github.com/vmware/vic-product/issues/296 to document this.

**Comment by ali5ter** [comment]
I am just learning about this. So some questions:
1. Are the pages designed for the 1337 web app? If there are, how do I see them?
2. If the vCloud Admin selects to install this 'default VCH', @karthik-narayan how do you imagine this affects the Appliance landing page experience? Seems like the Admin will just go straight into Admiral and start adding containers to the Host no?

**Comment by andrewtchin** [comment]
@ali5ter for 2 we will have to document that the admin is required to go to the OVA Initialization page after powering on the OVA VM because some features will not function if we don't start them, which requires admin credentials from the OVA Initialization service
