### ISSUE TITLE
[ova] Package a Hello world appliance (Docker Image) with the Harbor deployment

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4736]
PRD 2.8
* A “Hello world” image is available as a default image for deployment 
* A cloud administrator who wants to deploy a sample image is able to use the “Hello world” image to deploy it

**Comment by andrewtchin** [comment]
Adding from #4730 since this image isn't included yet:
* The default repository with the “Hello-world” image should be added to the project

**Comment by zjs** [comment]
Closing as value is unclear; we have a DCH if just a container image is needed.
