### ISSUE TITLE
[CI] Should be able to generate log bundle when the tests timeouts

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#4738]
Right now it is killing it and generating nothing so there is no way to debug and fix the problem.

**Comment by morris-jason** [comment]
Is there a way to run a ci step after the build has terminated?

**Comment by mhagen-vmware** [comment]
requires modification of drone

**Comment by mhagen-vmware** [comment]
This is actually already done here:
https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-01-Docker-Info.robot#L20

All tests should have a reasonable timeout parameter here, which will kill the test and still generate a log bundle.
