### ISSUE TITLE
docker commit

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#4743]
Implement `docker commit`

https://docs.docker.com/v1.13/engine/reference/commandline/commit/

**Comment by sflxn** [comment]
For VIC 1.2, we all agreed to implementing docker commit on stopped containers.  Handling commit for running containers will require docker pause/unpause support and we've pushed this out for the future.  We should make sure the personality server checks the running state and provide an appropriate warning.

@karthik-narayan was in agreement with the stopped container restriction.

**Comment by emlin** [comment]
Finished all issues inside
