### ISSUE TITLE
Research spike: Answer design questions around implementation of docker logs --since

### ISSUE THREAD

**Issue by jzt** [vmware/vic#4747]
`docker logs --since` requires tailing the log starting from the appropriate timestamp. Currently, our log tailing and following functionality is handled by govmomi code, but only our `LogReader` currently knows how to decode log headers in order to learn the timestamp of each entry. We need to come up with a way to learn what line to tail from based on the timestamp using the `LogReader` that can hopefully satisfy performance and correctness requirements. There are implications around log size and performance, as well as correctness of the approach since we will need to either make multiple calls, or perhaps implement our own tail functionality. Both have drawbacks, hopefully there is a third, faster/more correct option.

**Comment by jzt** [comment]
Some (painful) approaches that don't require altering govmomi code (in no particular order):

1. Alter the `LogReader` such that a call with `--since` specified will start at the top of the file, skipping lines until the desired timestamp is encountered, at which point we begin copying to the underlying `Read` buffer. This solution seems to break down in cases where the user suppled the `--tail` option, because `docker logs --since` is essentially a `tail` where the starting line is one with a particular timestamp. If the starting time begins, say, 100 lines from the end, but the user supplied a `--tail` value of 50, we would have to skip the first 50 lines of output. Of course, we have no idea where the end of the file is since we are streaming the log, so it makes more sense to pass `DatastoreFile.Tail()` a line number than to try to infer on our own where we are in the file during streaming (probably a deal breaker for this approach).

2. Using VC datastore operations, download the entire log file, find the starting timestamp and then (perhaps) doing the `Read` locally, instead of streaming it from the datastore. Doing so would allow us to handle the `--tail` option without the same limitation described in (1), although it would make `--follow`ing the log require additional (potentially deal-breaking) complexity as we'd have to make a separate call and attempt to pick up where we left off.

3. Same as (2), but, once we find the starting point, we initiate a normal streaming call as we currently do, supplying the starting line number to the govmomi `DatastoreFile.Tail()` function instead. Like (1), this breaks down if the user supplies the `--tail` option.

4. Write log entry metadata into a separate file, where each line maps 1:1 to lines in the logfile. This would preclude us from having to alter the log data as we currently are (prepending headers to each entry), which may be of some benefit in terms of reducing complexity within the `LogReader` and `LogWriter` logic. The metadata/index file would be (in theory) much smaller than the log file itself, so finding the appropriate starting timestamp would (again, in theory) be faster. It would require an extra serial port and likely additional (possibly complex) logic in order to deal with two files instead of one.

All of these make me want to curl into a ball on the floor in the running shower because I'll never feel clean again, but that's all I can think of at the moment, unless we want to implement our own tail/follow logic and/or consider this architecture from an entirely different direction. Additionally, all of this may be rendered moot if we ever implement remote logging (@hmahmood), or logging to something other than the datastore, etc.

Tagging @dougm @hickeng for ideas.

**Comment by dougm** [comment]
Since `DatastoreFile.Tail` is just a way to seek to a position within the file, I think it'd be fine to extend it to support since.  Would could add a new method, something like:

```go
func (f *DatastoreFile) TailFunc(include func(line int, message string) bool) error
```

Where `include` returns `false` when we've gone past the desired line.

We move the existing Tail method body to TailFunc and change Tail to just:

```go
func (f *DatastoreFile) Tail(n int) error {
    return f.TailFunc(func (line int, _) bool { return n <= line })
}
```

Then VIC does something like:
```go
err = f.TailFunc(func (line int, message string) bool {
   if n > line {
       return false
   }

   if SomeLogParseMethod(message).Timestamp < since {
       return false
   }

   return true
})
```

TailFunc would need to reset the seek position to the previous line, which is a little clunky, but shouldn't be too much trouble.

**Comment by jzt** [comment]
Awesome, thanks @dougm!

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by sgairo** [comment]
lgtm
