### ISSUE TITLE
encrypt containerVM configuration

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#475]
It's quite possible that there are secrets or data injected into contianers via container configuration that must **not** be visible to the administrators of the underlying vSphere infrastructure.

There should be a mechanism supplied to allow encryption of this configuration while persisted in the VMX.

**Comment by hickeng** [comment]
Moving this into icebox - it's a nice to have and a good extension of our security story, but not critical to basic function. This is related to the inverse problem of not leaking vSphere secrets when exporting VMs (see the encrypted Namespace mechanisms corresponding to guestinfo mechanisms).

**Comment by stuclem** [comment]
Not in 1.4.x

**Comment by zjs** [comment]
This is still a legitimate feature request, but is unlikely to get addressed as a one-off request. If desired, a new issue should be opened with information about specific use cases to better guide prioritization.
