### ISSUE TITLE
[CI] Everything should be automated/scripted

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#4761]
This includes creating the whole CI infra from scratch, installing drone and friends, generating our build images etc. Nothing should require manual steps which are proven to be error prone

**Comment by jakedsouza** [comment]
Lets break-down `everything` into specifics here so we can check them off as done 

Some of the things in the list would be 
1. Rebuild and push the integration test image when the docker file changes 
2. Ensure the ansible scripts are upto date and work as expected

**Comment by mhagen-vmware** [comment]
This was never define beyond the image creation task, so closing this. If we have better defined requirements in the future we can re-open or create a new Epic for the large effort, but the image creation task is well defined and already prioritized on its own.
