### ISSUE TITLE
[optimization] GzippedEmptyTar requires special treatment

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#477]
Anything that doesn't produce a fs level change [env, volume, cmd etc.] ends up using the special GzippedEmptyTar (sum is a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4). 

We can potentially skip creating vmdk creation process and only put metadata. It could be half of the layers  (like postgres or mongo).

/cc @hickeng & @fdawg4l

**Comment by hickeng** [comment]
Keeping this one in the base product as we have to be aware of the layer cap in diskchains and this could be a very effective way of helping to mitigate it.

**Comment by mdubya66** [comment]
@hickeng please review and assign or icebox

**Comment by hickeng** [comment]
This looks like a dup of #4168 - @fdawg4l please confirm and close if I'm correct.

**Comment by fdawg4l** [comment]
yes.
