### ISSUE TITLE
vApp restart should not restart container VMs

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#4779]
Out of band starts of container VMs are not supported by the VCH currently. However, a vApp restart does cause out of band starts of the container VMs which results in the VCH being out of sync with the container VM states. 

The vApp restart behavior should be changed so that only the VCH restarts, and the container VMs remain stopped. Container VMs can only be started from the docker command line. This behavior is consistent with default docker container restart behavior, which is to not restart a stopped container -- this is the only configuration we support currently.

**Comment by corrieb** [comment]
I strongly agree with this statement. This results in two serious UX problems - one is that containers are started when they should not be - who knows what the impact of this might be. The second is that we subsequently don't report correct information. 

@hmahmood the question of whether this is a must-fix depends on what scenarios we expect customers to need to power-cycle the vApp. We don't support that operation anyway, right?

**Comment by hmahmood** [comment]
@karthik-narayan do you think this is a high enough priority to be in 1.2? My understanding is that most customers don't restart the vApp.

**Comment by andrewtchin** [comment]
We've already moved away from vApp, closing.
https://github.com/vmware/vic-product/issues/1523
