### ISSUE TITLE
mocked vmomi gateway

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#479]
Mocking the vmomi gateway is going to be the most involved portion and the most central - this will allow components use the normal paths for communication with VC, unaltered.

Can govmomi be used to deserialize wsdl back into structures, or does the vmomi gateway need to be an rpc API gateway? What's the answer to this question for a non-mock gateway?

This could easily be extended to use a system model that can do arbitrarily sophisticated modelling of the VM placement, resource allotment, et al, for when autoscaling becomes a factor. It's also an effective way of testing high level logical network configuration.

**Comment by dougm** [comment]
Will start by implementing the initial framework:

- [ ] Listener to unmarshal SOAP sdk requests

- [ ] Dispatcher to handle responses

- [ ] RetrieveServiceContent method impl

- [ ] CurrentTime method impl

After these are functional, will start looking at the more involved methods, such as PropertyCollector.RetrieveProperties

Adding this to the vCenter milestone for now, we will end up with a separate milestone to cover the #481 epic

**Comment by dougm** [comment]
First pass is functional: https://github.com/dougm/vic/commit/f028dda4698c1b01688f0173654a84eb3d1125d9

Going to do some minor cleanup & test improvements before submitting a PR.

**Comment by dougm** [comment]
Separate issues will follow to add more functionality.
