### ISSUE TITLE
'vic-machine delete --force' failed when specifying volume-store == image-store (ESX)

### ISSUE THREAD

**Issue by maplain** [vmware/vic#4794]
related to: https://github.com/vmware/vic/issues/4478

➜  vic git:(volume-loss) ✗ bin.back/vic-machine-darwin create --force --target 10.192.174.183 --password "" --thumbprint A0:3C:5E:1B:36:68:34:25:99:12:41:E9:AB:A5:DF:D8:84:3A:57:0E --name dev --user root --image-store=datastore1 --volume-store=datastore1/dev:default  --bridge-network DPortGroup --no-tlsverify --no-tls
Apr 13 2017 19:59:02.704-07:00 INFO  ### Installing VCH ####
Apr 13 2017 19:59:02.705-07:00 WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Apr 13 2017 19:59:02.705-07:00 WARN  Configuring without TLS - all communications will be insecure
Apr 13 2017 19:59:02.705-07:00 WARN  iso file "/Users/fangyuanl/development/go/src/github.com/vmware/vic/bin.back/appliance.iso" version "v1.1.0-rc2-0-2e59684" inconsistent with installer version "v1.1.0-rc2-10000-72eee33"
Apr 13 2017 19:59:02.706-07:00 WARN  iso file "/Users/fangyuanl/development/go/src/github.com/vmware/vic/bin.back/bootstrap.iso" version "v1.1.0-rc2-0-2e59684" inconsistent with installer version "v1.1.0-rc2-10000-72eee33"
Apr 13 2017 19:59:02.881-07:00 INFO  Validating supplied configuration
Apr 13 2017 19:59:03.158-07:00 INFO  Firewall status: DISABLED on "/ha-datacenter/host/sc2-rdops-vm05-dhcp-174-183.eng.vmware.com/sc2-rdops-vm05-dhcp-174-183.eng.vmware.com"
Apr 13 2017 19:59:03.173-07:00 WARN  Firewall configuration on "/ha-datacenter/host/sc2-rdops-vm05-dhcp-174-183.eng.vmware.com/sc2-rdops-vm05-dhcp-174-183.eng.vmware.com" may prevent connection on dst 2377/tcp outbound with allowed IPs: [10.162.202.209 10.166.2.128 10.162.202.177 10.162.202.120]
Apr 13 2017 19:59:03.173-07:00 WARN  Unable to fully verify firewall configuration due to DHCP use on management network
Apr 13 2017 19:59:03.173-07:00 WARN  VCH management interface IP assigned by DHCP must be permitted by allowed IP settings
Apr 13 2017 19:59:03.173-07:00 WARN  Firewall configuration may be incorrect if firewall is reenabled on hosts:
Apr 13 2017 19:59:03.173-07:00 WARN  	"/ha-datacenter/host/sc2-rdops-vm05-dhcp-174-183.eng.vmware.com/sc2-rdops-vm05-dhcp-174-183.eng.vmware.com"
Apr 13 2017 19:59:03.173-07:00 INFO  Firewall must permit dst 2377/tcp outbound to the VCH management interface if firewall is reenabled
Apr 13 2017 19:59:03.191-07:00 WARN  Evaluation license detected. VIC may not function if evaluation expires or insufficient license is later assigned.
Apr 13 2017 19:59:03.191-07:00 INFO  License check OK
Apr 13 2017 19:59:03.191-07:00 INFO  DRS check SKIPPED - target is standalone host
Apr 13 2017 19:59:03.269-07:00 INFO
Apr 13 2017 19:59:04.009-07:00 INFO  Creating Resource Pool "dev"
Apr 13 2017 19:59:04.037-07:00 INFO  Creating directory [datastore1] dev
Apr 13 2017 19:59:04.144-07:00 INFO  Datastore path is [datastore1] dev
Apr 13 2017 19:59:04.144-07:00 INFO  Creating appliance on target
Apr 13 2017 19:59:04.153-07:00 INFO  Network role "client" is sharing NIC with "public"
Apr 13 2017 19:59:04.153-07:00 INFO  Network role "management" is sharing NIC with "public"
Apr 13 2017 19:59:04.586-07:00 INFO  Uploading images for container
Apr 13 2017 19:59:04.587-07:00 INFO  	"/Users/fangyuanl/development/go/src/github.com/vmware/vic/bin.back/appliance.iso"
Apr 13 2017 19:59:04.587-07:00 INFO  	"/Users/fangyuanl/development/go/src/github.com/vmware/vic/bin.back/bootstrap.iso"
Apr 13 2017 19:59:16.162-07:00 INFO  Waiting for IP information
Apr 13 2017 19:59:30.748-07:00 INFO  Waiting for major appliance components to launch
Apr 13 2017 19:59:30.862-07:00 INFO  Obtained IP address for client interface: "10.192.182.24"
Apr 13 2017 19:59:30.862-07:00 INFO  Checking VCH connectivity with vSphere target
Apr 13 2017 19:59:30.980-07:00 INFO  vSphere API Test: https://10.192.174.183 vSphere API target responds as expected
Apr 13 2017 19:59:35.026-07:00 INFO  Initialization of appliance successful
Apr 13 2017 19:59:35.026-07:00 INFO
Apr 13 2017 19:59:35.026-07:00 INFO  VCH Admin Portal:
Apr 13 2017 19:59:35.026-07:00 INFO  https://10.192.182.24:2378
Apr 13 2017 19:59:35.026-07:00 INFO
Apr 13 2017 19:59:35.027-07:00 INFO  Published ports can be reached at:
Apr 13 2017 19:59:35.027-07:00 INFO  10.192.182.24
Apr 13 2017 19:59:35.027-07:00 INFO
Apr 13 2017 19:59:35.027-07:00 INFO  Docker environment variables:
Apr 13 2017 19:59:35.027-07:00 INFO  DOCKER_HOST=10.192.182.24:2375
Apr 13 2017 19:59:35.027-07:00 INFO
Apr 13 2017 19:59:35.027-07:00 INFO  Connect to docker:
Apr 13 2017 19:59:35.027-07:00 INFO  docker -H 10.192.182.24:2375 info
Apr 13 2017 19:59:35.027-07:00 INFO  Installer completed successfully

➜  vic git:(volume-loss) ✗ bin.back/vic-machine-darwin delete --force  --target 10.192.174.183 --password "" --thumbprint A0:3C:5E:1B:36:68:34:25:99:12:41:E9:AB:A5:DF:D8:84:3A:57:0E --name dev --user root
Apr 13 2017 20:00:32.731-07:00 INFO  ### Removing VCH ####
Apr 13 2017 20:00:32.863-07:00 INFO  Validating target
Apr 13 2017 20:00:32.991-07:00 WARN  Disabling ha-host hostd.log collection (ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.)
Apr 13 2017 20:00:32.991-07:00 INFO
Apr 13 2017 20:00:32.991-07:00 INFO  VCH ID: VirtualMachine:12
Apr 13 2017 20:00:33.013-07:00 INFO  Removing VMs
Apr 13 2017 20:00:33.078-07:00 INFO  Removing image stores
Apr 13 2017 20:00:33.605-07:00 INFO  Removing volume stores
Apr 13 2017 20:00:33.605-07:00 INFO  Deleting volume store "default" on Datastore "datastore1" at path "dev"
Apr 13 2017 20:00:34.103-07:00 INFO  Removing appliance VM network devices
Apr 13 2017 20:00:34.863-07:00 INFO  No network device attached
Apr 13 2017 20:00:34.863-07:00 INFO  Bridge network was not created during VCH deployment, leaving it there
Apr 13 2017 20:00:35.013-07:00 ERROR Failed to destroy VM "VirtualMachine:12": Failed to delete the virtual machine, '/vmfs/volumes/58eeb854-3ef83196-2448-020036049385/dev/dev.vmx'. then failed to unregister VM: ServerFaultCode: The object 'vim.VirtualMachine:12' has already been deleted or has not been completely created
Apr 13 2017 20:00:35.013-07:00 ERROR --------------------
Apr 13 2017 20:00:35.013-07:00 ERROR vic-machine-darwin delete failed: delete failed

**Comment by maplain** [comment]
if delete with --force, delete will fail, leaving dev folder in datastore including only one appliance.iso not deleted;
if delete without --force, delete will success, everything will be removed including volumes folder as pointed out here: https://github.com/vmware/vic/issues/4478

**Comment by matthewavery** [comment]
I am not for certain, but I believe in the docs we state that this making the image store the target of a volumestore is not advised at the moment. We definitely need to catch that edge case, and perhaps either clean up volume stores in a different way, or bar people from assigning the image store as a volume store.

**Comment by matthewavery** [comment]
I defer to @emlin

**Comment by emlin** [comment]
Added comments to #4478.
For this issue, --force means delete volume store, and no --force means leave volume store there. We might address this issue after #4478

**Comment by mdubya66** [comment]
This appears to be fixed. Closing. 

```
(mwilliamson) ib-aus-office-124:~/Downloads/vic_1.2.0 $  ./vic-machine-darwin create --target 172.16.127.223 -user root --password password --no-tlsverify --volume-store datastore1/as:default --thumbprint 24:E9:16:3A:49:91:3E:C4:DD:FE:AA:67:1A:66:9F:2D:DF:A8:6F:88 --name force-test --force --image-store=datastore1 --bridge-network DPortGroup
Oct 30 2017 13:55:23.287-05:00 INFO  ### Installing VCH ####
Oct 30 2017 13:55:23.288-05:00 WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Oct 30 2017 13:55:23.288-05:00 INFO  Generating self-signed certificate/key pair - private key in force-test/server-key.pem
Oct 30 2017 13:55:23.777-05:00 WARN  Configuring without TLS verify - certificate-based authentication disabled
Oct 30 2017 13:55:23.877-05:00 INFO  Validating supplied configuration
Oct 30 2017 13:55:24.081-05:00 INFO  Firewall status: DISABLED on "/ha-datacenter/host/localhost.localdomain/localhost.localdomain"
Oct 30 2017 13:55:24.088-05:00 INFO  Firewall configuration OK on hosts:
Oct 30 2017 13:55:24.088-05:00 INFO  	"/ha-datacenter/host/localhost.localdomain/localhost.localdomain"
Oct 30 2017 13:55:24.105-05:00 INFO  License check OK
Oct 30 2017 13:55:24.105-05:00 INFO  DRS check SKIPPED - target is standalone host
Oct 30 2017 13:55:24.139-05:00 INFO
Oct 30 2017 13:55:24.197-05:00 INFO  Creating Resource Pool "force-test"
Oct 30 2017 13:55:24.204-05:00 INFO  Creating VirtualSwitch
Oct 30 2017 13:55:24.258-05:00 INFO  Creating Portgroup
Oct 30 2017 13:55:24.310-05:00 INFO  Creating appliance on target
Oct 30 2017 13:55:24.323-05:00 INFO  Network role "management" is sharing NIC with "client"
Oct 30 2017 13:55:24.328-05:00 INFO  Network role "public" is sharing NIC with "client"
Oct 30 2017 13:55:24.433-05:00 INFO  Creating directory [datastore1] as
Oct 30 2017 13:55:24.445-05:00 INFO  datastore root [datastore1] as already exists
Oct 30 2017 13:55:24.445-05:00 INFO  Datastore path is [datastore1] as
Oct 30 2017 13:55:24.571-05:00 INFO  Uploading images for container
Oct 30 2017 13:55:24.572-05:00 INFO  	"bootstrap.iso"
Oct 30 2017 13:55:24.572-05:00 INFO  	"appliance.iso"
Oct 30 2017 13:55:37.632-05:00 INFO  Waiting for IP information
Oct 30 2017 13:55:50.312-05:00 INFO  Waiting for major appliance components to launch
Oct 30 2017 13:55:50.416-05:00 INFO  Obtained IP address for client interface: "172.16.127.251"
Oct 30 2017 13:55:50.416-05:00 INFO  Checking VCH connectivity with vSphere target
Oct 30 2017 13:55:50.842-05:00 INFO  vSphere API Test: https://172.16.127.223 vSphere API target responds as expected
Oct 30 2017 13:55:54.901-05:00 INFO  Initialization of appliance successful
Oct 30 2017 13:55:54.901-05:00 INFO
Oct 30 2017 13:55:54.901-05:00 INFO  VCH Admin Portal:
Oct 30 2017 13:55:54.901-05:00 INFO  https://172.16.127.251:2378
Oct 30 2017 13:55:54.901-05:00 INFO
Oct 30 2017 13:55:54.901-05:00 INFO  Published ports can be reached at:
Oct 30 2017 13:55:54.901-05:00 INFO  172.16.127.251
Oct 30 2017 13:55:54.901-05:00 INFO
Oct 30 2017 13:55:54.901-05:00 INFO  Docker environment variables:
Oct 30 2017 13:55:54.901-05:00 INFO  DOCKER_HOST=172.16.127.251:2376
Oct 30 2017 13:55:54.901-05:00 INFO
Oct 30 2017 13:55:54.901-05:00 INFO  Environment saved in force-test/force-test.env
Oct 30 2017 13:55:54.901-05:00 INFO
Oct 30 2017 13:55:54.901-05:00 INFO  Connect to docker:
Oct 30 2017 13:55:54.901-05:00 INFO  docker -H 172.16.127.251:2376 --tls info
Oct 30 2017 13:55:54.901-05:00 INFO  Installer completed successfully
(mwilliamson) ib-aus-office-124:~/Downloads/vic_1.2.0 $

(mwilliamson) ib-aus-office-124:~/Downloads/vic_1.2.0 $  ./vic-machine-darwin delete --target 172.16.127.223 -user root --password password --thumbprint 24:E9:16:3A:49:91:3E:C4:DD:FE:AA:67:1A:66:9F:2D:DF:A8:6F:88 --name force-test --force
Oct 30 2017 13:57:16.678-05:00 INFO  ### Removing VCH ####
Oct 30 2017 13:57:16.776-05:00 INFO  Validating target
Oct 30 2017 13:57:16.843-05:00 WARN  Disabling ha-host hostd.log collection (ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.)
Oct 30 2017 13:57:16.843-05:00 INFO
Oct 30 2017 13:57:16.843-05:00 INFO  VCH ID: VirtualMachine:78
Oct 30 2017 13:57:16.856-05:00 INFO  Removing VMs
Oct 30 2017 13:57:16.881-05:00 INFO  Removing image stores
Oct 30 2017 13:57:17.051-05:00 INFO  Removing volume stores
Oct 30 2017 13:57:17.051-05:00 INFO  Deleting volume store "default" on Datastore "datastore1" at path "as"
Oct 30 2017 13:57:17.162-05:00 INFO  Removing appliance VM network devices
Oct 30 2017 13:57:17.469-05:00 INFO  Removing Portgroup "DPortGroup"
Oct 30 2017 13:57:17.475-05:00 INFO  Removing VirtualSwitch "DPortGroup"
Oct 30 2017 13:57:17.735-05:00 INFO  Removing Resource Pool "force-test"
Oct 30 2017 13:57:17.751-05:00 INFO  ----------
Oct 30 2017 13:57:17.751-05:00 INFO  If firewall changes were made for VIC during install, they were not reverted during delete
Oct 30 2017 13:57:17.751-05:00 INFO  To modify firewall rules see vic-machine update firewall --help
Oct 30 2017 13:57:17.751-05:00 INFO  ----------
Oct 30 2017 13:57:17.751-05:00 INFO  Completed successfully
(mwilliamson) ib-aus-office-124:~/Downloads/vic_1.2.0 $
```
