### ISSUE TITLE
mac user docs: setup ca.crt for VCH

### ISSUE THREAD

**Issue by tompscanlan** [vmware/vic#4798]
**User Statement:**

As a mac user, connecting to existing VCH, I want to be able to docker login and docker push.  

Running docker login fails with `Error response from daemon: Head https://harbor.yyy.org/v2/: x509: certificate signed by unknown authority`

**Details:**

Add mac specific details at: 
https://vmware.github.io/vic-product/assets/files/html/latest/vic_installation/deploy_vch_harbor.html

something like: sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain harbor-ca.crt

may do the trick.

Alternatively, indicate that making a new VCH with the registry ca.crt achieves the same goal.

**Acceptance Criteria:**

A mac user with a pre-existing VCH can read the doc and successfully do a `docker login && docker push ...`

**Comment by frapposelli** [comment]
moving this to `vic-product`

**Comment by frapposelli** [comment]
Issue moved to [vmware/vic-product #167](https://github.com/vmware/vic-product/issues/167) via [**ZenHub**](https://www.zenhub.com/)
