### ISSUE TITLE
Admiral push to gcr improvement

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4806]
User statement:  As an engineer managing the build process for the unified OVA installer, we need admiral to push to gcr in order to simplify and unify our build process so that all products are being pulled from a unified location.

Details:

Acceptance Criteria:
1. When admiral builds, it pushed to GCR repo (doesn't preclude it from pushing elsewhere as well)

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #882](https://github.com/vmware/vic-product/issues/882) via [**ZenHub**](https://www.zenhub.com/)
