### ISSUE TITLE
OVA .drone development

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4807]
User statement: As an engineer on VIC, I want a unified OVA installer process using our existing infrastructure, so we need a .drone file that manages the builds process for the unified installer OVA

Details:

Acceptance Criteria:
1.  A .drone.yml file is present and drone now builds the unified installer process

**Comment by jakedsouza** [comment]
@mhagen-vmware Why are we going with a new drone file vs adding an additional build step in the existing build process?

**Comment by mhagen-vmware** [comment]
@jakedsouza Because this is going to move to github/vic-product eventually and the three sub projects will trigger this.  We want it to be independently triggered by all three sub-projects.

**Comment by jakedsouza** [comment]
Cool got it. Thanks
