### ISSUE TITLE
Unified OVA Test v1.2

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4808]
User statement:  As an engineer and customer of VIC, I want to know that the unified installer OVA has gone through at least a minimal set of testing so as to be reliable and known to work in some scenarios

Details:

Acceptance Criteria:
1. Tests are documented in .md files in the repo
2. Tests are implemented in robot files in the repo

**Comment by rajanashok** [comment]
Able to install the unified OVA from the script. Currently working on getting the HARBOR IP (seems to be not that straight forward) getting some help with Fabio on that right now.
