### ISSUE TITLE
Downstream triggers from engine, harbor, admiral to OVA

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4809]
User statement: As an engineer on VIC, I want the unified installer OVA to be triggered when a new build from the underlying components is completed.

Details:

Acceptance Criteria:
1. A push or merge to master on engine, admiral, harbor causes a build to trigger on OVA installer

**Comment by frapposelli** [comment]
ref:

Drone Downstream plugin ([0.5 Version](https://github.com/drone-plugins/drone-downstream), [0.4 Version](https://github.com/drone-plugins/drone-downstream/tree/release/0.4))

**Comment by mhagen-vmware** [comment]
Engine is done here: #5227

**Comment by mhagen-vmware** [comment]
harbor is done here:
https://github.com/vmware/harbor/tree/drone

**Comment by mhagen-vmware** [comment]
admiral is done, just waiting on contributor status so that I can merge and make a PR.

**Comment by mhagen-vmware** [comment]
admiral is here:
https://github.com/vmware/admiral/pull/117

**Comment by mhagen-vmware** [comment]
finished and demo'd in Sprint 11
