### ISSUE TITLE
Create the OVA Installer Build Process and Test

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4810]
User statement:
As an engineer on VIC, I want a unified, cohesive build process for the installer OVA that automatically pulls the latest code from each component, builds a unified installer OVA, and runs through a series of tests to verify that it is working.

Details:

Acceptance Criteria:
1. OVA installer is published to GCR via automatic CI build process in which 
2. Unified OVA installer tests are documented and implemented

**Comment by mdubya66** [comment]
All 1.2 issues are resolved, removing from the release

**Comment by mdharamadas1** [comment]
@andrewtchin and I discussed the CI part of this and following are the notes:

- Setup on existing Drone CI itself (we think it will be good given we now have 14 workers)
- Build should be triggered on any successful build of vic, vic-ui, harbor, admiral
- The repo which triggers should pass the artifact / build name to this build to pick up that exact artifact version (to avoid race condition which may skip some artifacts)
- The build should pick the latest from the rest of the 3 artifacts
- Need setup to trigger ad-hoc builds such as release builds, manually (pass specific versions / artifact names to the build as parameters / variables)
- Need vCenter (may try nested in ESX)
- Not clear yet on how tests would be run as we don't have vCenter on CI yet, so one option we discussed is to run tests outside of CI and update github PR with the results later.
- Once the build is successful and tests pass, upload OVA to GCR

@andrewtchin pls feel free to correct / add, if any.

**Comment by andrewtchin** [comment]
@jak-atx do you have any comments on this related to the UI plugin build?

**Comment by mdubya66** [comment]
All high priority issues are resolved. Removing high label

**Comment by mdubya66** [comment]
what's the status of this. Should we move the remaining items to a new Epic? @mdharamadas1

**Comment by mdharamadas1** [comment]
@mdubya66 closing this after removing couple of issues from this epic and closing one as its already fixed.
