### ISSUE TITLE
PSC SAML investigation for SSO

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4811]
**User Statement:**

Investigation of SAML based SSO in VIC product 1.2.

**Details:**
PSC/LW supports SAML authentication standard in both 6.0 and 6.5. For this reason it appears like SAML would be the appropriate choice for SSO authentication in Portal/Admiral. By using SAML Admiral/PSC interacts directly with PSC/LW. PSC/LW can then be configured to use Local an LDAP server or an Active Directory server as the ultimate Identity Provider Source.

**Acceptance Criteria:**
A document that explains the SAML initialization and authentication flows when interacting with PSC.

**Comment by lcastellano** [comment]
The first part of the investigation is concluded. Here's a note that describes the different alternatives that we have explored.

https://onevmw-my.sharepoint.com/personal/lcastellano_vmware_com/_layouts/15/guestaccess.aspx?guestaccesstoken=7hp9yNnFcexDWR1Nx4zMpRCK5l53ZhSi9DGILvMIvYs%3d&docid=2_1eef786e3c0f6423ca08095802f9e2dac&rev=1

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
closing, reopen if there is more verification that needs to be done
