### ISSUE TITLE
Public Slack link to join no longer works. 

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic#4812]
Info page http://vmware.github.io/vic/ link to get slack invite no longer works.
The link https://code.vmware.com/slack page loads as "Sorry, the page you requested was not found."

From section "For general questions, visit the vSphere Integrated Containers Engine channel on Slack.com. If you do not have an @vmware.com or @emc.com email address, sign up at https://code.vmware.com/slack to get an invitation."

Found that the following links are currently good for new account invites to slack https://code.vmware.com/web/code/join or https://code.vmware.com/home.

**Comment by mdubya66** [comment]
The correct short link to use is https://code.vmware.com/join

https://github.com/vmware/vic/blob/master/CONTRIBUTING.md also needs to be changed.
