### ISSUE TITLE
Implement GetImage in the vsphere PL storage implementation which uses FCD

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#482]
We're currently keeping track of parent -> child image relationships by persisting them in the port layer.  This _should_ be stateless, but the `vmomi` API (currently) doesn't have the ability to get an existing disk's spec (with the parent vmdk's ID).  

[First Class Disk](https://wiki.eng.vmware.com/FCD) has the appropriate APIs to do this.  See the following.
-[To get the spec](https://opengrok.eng.vmware.com/source/xref/storage-main.perforce.1666/bora/vim/vmodl/vim/vslm/host/VStorageObjectManager.java#268)
-[To create/attach an FCD](https://opengrok.eng.vmware.com/source/xref/storage-main.perforce.1666/vcqe/VC/src/main/java/com/vmware/vcqa/vim/VirtualMachine.java#15136)

The only implication of using FCD is that the VM version needs to be current.

**Comment by fdawg4l** [comment]
cc @hickeng

**Comment by hickeng** [comment]
@fdawg4l what's the minimum vSphere version for FCD? If it's not in 6.0 please move this to Icebox and raise an issue for tracking it via datastore file - moving that relationship out of the portlayer is necessary for #427

**Comment by fdawg4l** [comment]
When I last spoke to them, they said vsphere 2016.  Does that mean 6.0?

**Comment by mdubya66** [comment]
2016 is 6.5. Moving to Icebox

**Comment by mdubya66** [comment]
making low for now, needs review with portlayer work @fdawg4l

**Comment by hickeng** [comment]
The core complaint here is addressed by #4261 - @fdawg4l could you split out the FCD support into a separate issue (that references #2928) and close this one if parentMap change is merged.

**Comment by hickeng** [comment]
@dougm We've been talking about FCD as a fix for #2928 - can you update the viability of this as a solution?

**Comment by dougm** [comment]
I tried it out, creating a first class disk using `VStorageObjectManager.CreateDisk_Task` and attaching to a VM using `VirtualMachine.AttachDisk_Task`.  When deleting the VM with `VirtualMachine.Destroy_Task` with the disk still attached, the disk is also deleted - just as a disk created with `VirtualDiskManager.CreateVirtualDisk_Task` is.  I haven't tried with linked clones yet, but I'd expect the same behavior there too.  There might be a tag or flag somewhere to prevent a FCD from being destroyed along with the VM, but I haven't found it yet.

**Comment by fdawg4l** [comment]
:-(
