### ISSUE TITLE
3-5x slowdown in parallel docker creates

### ISSUE THREAD

**Issue by carlsone** [vmware/vic#4826]
We are measuring the latency of 10 and 50 parallel docker CLI calls to "docker create -it ubuntu sleep 20000" against various VIC builds installed on ESX 6.5.
 
In VIC build 9735 (and before), we see parallel docker creates taking about 1.5 sec for 10 parallel creates, and about 5.5 sec for 50 parallel docker creates.
 
In VIC build 9824 (and after), we see parallel docker creates taking 6.3 sec for 10 parallel creates, and 35 sec for 50 parallel docker creates.
 
There are no other testable builds between 9735 and 9824 on https://bintray.com/vmware/vic-repo/build

VIC version: 1.2 build 9824

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

vic-machine-linux create --target <hostname> --image-store datastore1 --name vic_9824 --compute-resource /ha-datacenter/host/*/Resources --no-tls --force --timeout 10m0s --user root --password <censored>

**Steps to reproduce:**

1) Install vic build 9824
2) start your stop watch
3) Run 10 or 50 creates in a backgrounded loop:
docker pull ubuntu
for i in `seq 1 50`; do
   docker create -it ubuntu sleep 20000 &
done
4) stop your stop watch
5) Repeat with vic build 9735 to see a shorter stopwatch time.

**Actual behavior:**

In VIC build 9824 (and later), we see the following latencies:
 
docker_create_esx_0010_median  | 5.763 sec
docker_create_esx_0010_average | 5.814 sec
docker_create_esx_0010_stdev   | 0.776 sec
docker_create_esx_0010_min     | 4.545 sec
docker_create_esx_0010_max     | 7.085 sec
docker_create_esx_0010_total | 7.09627318382 sec
 
docker_create_esx_0050_median  | 30.386 sec
docker_create_esx_0050_average | 29.990 sec
docker_create_esx_0050_stdev   | 1.501 sec
docker_create_esx_0050_min     | 25.111 sec
docker_create_esx_0050_max     | 32.399 sec
docker_create_esx_0050_total | 32.407148838 sec

**Expected behavior:**

In VIC build 9735 (and before), we see the following latencies:

docker_create_esx_0010_median  | 1.280 sec
docker_create_esx_0010_average | 1.265 sec
docker_create_esx_0010_stdev   | 0.046 sec
docker_create_esx_0010_min     | 1.150 sec
docker_create_esx_0010_max     | 1.306 sec
docker_create_esx_0010_total | 1.31524515152 sec

docker_create_esx_0050_median  | 4.091 sec
docker_create_esx_0050_average | 4.134 sec
docker_create_esx_0050_stdev   | 0.847 sec
docker_create_esx_0050_min     | 2.699 sec
docker_create_esx_0050_max     | 5.465 sec
docker_create_esx_0050_total | 5.46961903572 sec

**Logs:**

slow case:

[vic9824_container-logs.zip](https://github.com/vmware/vic/files/931332/vic9824_container-logs.zip)

[vic9824_hostd.log.gz](https://github.com/vmware/vic/files/931337/vic9824_hostd.log.gz)

fast case:

[vic9735_container-logs.zip](https://github.com/vmware/vic/files/931344/vic9735_container-logs.zip)

[vic9735_hostd.log.gz](https://github.com/vmware/vic/files/931349/vic9735_hostd.log.gz)

**Comment by mdubya66** [comment]
@chengwang86 Please triage.

**Comment by chengwang86** [comment]
It seems like there might be something wrong with the docker-personality:
Here is the full log from docker-persona of 9824 (same behavior on 9735)
``` 
Apr 18 2017 21:53:13.864Z INFO  Launching docker personality pprof server on 127.0.0.1:6062
Apr 18 2017 21:53:14.001Z INFO  Waiting for portlayer to come up
Apr 18 2017 21:53:16.002Z INFO  Portlayer is up and responding to pings
Apr 18 2017 21:53:16.002Z INFO  Refreshing repository cache
Apr 18 2017 21:53:16.002Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.NewRepositoryCache:131]
Apr 18 2017 21:53:16.002Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] repositories
Apr 18 2017 21:53:16.003Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.InitializeLayerCache:69]
Apr 18 2017 21:53:16.003Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] layers
Apr 18 2017 21:53:16.003Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.InitializeImageCache:86]
Apr 18 2017 21:53:16.003Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] images
Apr 18 2017 21:53:16.004Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [1.351358ms] repositories
Apr 18 2017 21:53:16.004Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.NewRepositoryCache:131] [1.401598ms] 
Apr 18 2017 21:53:16.004Z INFO  Repository cache updated successfully
Apr 18 2017 21:53:16.004Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [1.701065ms] layers
Apr 18 2017 21:53:16.004Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.InitializeLayerCache:69] [1.749949ms] 
Apr 18 2017 21:53:16.004Z INFO  Layer cache initialized successfully
Apr 18 2017 21:53:16.005Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [2.09209ms] images
Apr 18 2017 21:53:16.005Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.InitializeImageCache:86] [2.134003ms] 
Apr 18 2017 21:53:16.005Z INFO  Image cache initialized successfully
Apr 18 2017 21:53:16.006Z INFO  Container cache updated successfully
Apr 18 2017 21:53:16.006Z INFO  Creating image store
Apr 18 2017 21:53:16.183Z ERROR Failed to create image store
Apr 18 2017 21:53:16.183Z FATAL failed to initialize backend: [POST /storage][500] CreateImageStore default  &{Code:500 Message:The operation is not allowed in the current state.}
```

**Comment by chengwang86** [comment]
From the portlayer log, I can find the following (by `grep CreateHandler`):
- in build 9824, `createHandler` takes 11s to 21s for creating 50 containers in parallel
- in buld 9735, the same operation takes 500ms to 1.7s
- however, in our portlayer log, there is not enough information re: where (in which function) most of the time duration was spent

Similar behavior was observed via `grep Commithandler`.

**Comment by hickeng** [comment]
@chengwang86 please monitor the levels of entropy in the endpointVM (`/proc/sys/kernel/random/entropy_avail`) during the batch creation tests - we're running `haveged` to help ensure we don't deplete entropy to the point where we're blocking on it, but if versions have changed in PhotonOS repo then an updated configuration may be required.
A very quick check of the logs suggests that we may be spending ~1s generating container private keys when we're creating many in parallel. That's not enough to account for the full performance degradation but could easily contribute.

**Comment by anishmehta1** [comment]
Please prioritize this bug. The perf team and probably the scale test team characterize this as a blocker.

**Comment by hickeng** [comment]
Updated priority to reflect `blocker` status from perf team.

**Comment by anchal-agrawal** [comment]
I compared the diff in the container create code path between builds 9735 and 9824 - the only relevant change is in `lib/apiservers/portlayer/restapi/handlers/containers_handlers.go`:

```diff
88c88
< 	privateKey, err := rsa.GenerateKey(rand.Reader, 512)
---
> 	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
```

I made the above change in commit 6bfa21727027f330056d8af95c8394b9df698481 as part of static code analysis improvements to our code.

I ran the performance test from this issue's description on both builds and the results are below.

Nimbus 6.5 ESX:

No. of parallel creates | b9824 | b9735
------------ | ------------ | -------------
50 | 21.084s | 6.35s 
10 | 12.415s | 2.62s

Nimbus VC with 3 ESX hosts:

No. of parallel creates | b9824 | b9735
------------ | ------------ | -------------
50 | 39.893s | 18.598s 
10 | 7.69s | 4.46s

**Comment by hickeng** [comment]
@anchal-agrawal if you run that test having reverted to a 512 byte key does the performance deficit go away? In fact I'd be curious if we get a gain from dropping down to the lowest key size that's functional.
This is going to be directly relevant to #2849 where we've been told we should be generating per container keys (which we are) AND validating them (which we are not) at both ends.

If there is a major performance delta with scaling issues then we need to look at approaches to high performance key generation that don't tax /dev/urandom so heavily.
Of note is the following from the getrandom man page - although even if reading only 256 we could still block in the case of depleted entropy:
> If the urandom source has been initialized, reads of up to 256 bytes
will always return as many bytes as requested and will not be
interrupted by signals.  No such guarantees apply for larger buffer
sizes.  For example, if the call is interrupted by a signal handler,
it may return a partially filled buffer, or fail with the error
EINTR.

**Comment by anchal-agrawal** [comment]
@hickeng the **b9735** column in the table above shows the performance with a 512 bit key. While running the batch parallel creates, available entropy on the endpointVM before generating the key is always upwards of 1000 bits regardless of the key bit size, so I don't think entropy is the bottleneck.

However, with key size 2048, CPU usage hits 100% most of the time while the parallel creates are running. With 512, that is not the case. I also ran a go test benchmark for `rsa.GenerateKey()` with sizes 512 and 2048 on the endpointVM:

```
root@ [ ~ ]# go test -v -bench .
testing: warning: no tests to run
Benchmark2048            5     256150129 ns/op
Benchmark512           300       4663143 ns/op
PASS
ok      _/root    5.011s
root@ [ ~ ]# go test -v -bench . -benchtime=5s
testing: warning: no tests to run
Benchmark2048           50     249252998 ns/op
Benchmark512          2000       4841569 ns/op
PASS
ok      _/root    22.786s
```

Side note: for the benchmark test, I installed Go on the endpointVM with tdnf and the Go version was 1.7.4.

**Comment by hickeng** [comment]
@anchal-agrawal *b9735* shows the figures for the build prior to the regression. I'm wondering if we have a build from the codebase _after_ the regression, but with the key size restored to 512 to confirm that this is the sole factor. It's definitely a contributing factor but I'd like to know there was anything else.

**Comment by anchal-agrawal** [comment]
Here are the test results.

Nimbus 6.5 ESX:

No. of parallel creates | b9824 with key size 512 |
------------ | ------------ 
50 | 13.3s 
10 | 2.44s 

The only other code change in the container create path between b9735 and b9824 is 6c0f1ccfa2c16bd26e5f097bdd1deb494de457d4, which modified the container cache lookup mechanism without adding something that would increase container create time.

**Comment by hickeng** [comment]
@anchal-agrawal Thanks - looks like we've confirmed it. Given we're not validating the key until #2849 I'm fine with dropping it back to 512 - please note in #2849 that we need to find a less blocking (would prefer more efficient, but..) key generation approach as part of that work.
