### ISSUE TITLE
DinV Dev: Provide vmware/photon:dind-<ver> supported DockerHub image(s)

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4852]
**User statement**

As a developer using VIC, I need a simple and easy way to get hold of a VIC image that runs vanilla Docker so that I can do simple development or build tasks. My company would prefer me to use an image provided by VMware than build my own. I would like to be able to choose from various versions, but docker pull vmware/photon:dind should pull the latest.

**Details**

There is already work done here: https://github.com/corrieb/bensdoings/tree/master/dind/photon to provide such an image. However, there will be additional work we want to do to ensure that it is secure and well-tested. 

I should be assumed that the consumption model for the image is to expose a remote Docker API either via a port mapping or on a public network. The nested Docker can then be referred to either using:

docker run -H <vch-host-ip:mapped-port> or
docker run -H <dhcp-ip:defined-port>

In particular we should make sure that:

- There is no issue with zombie processes, given the way we're initializing dockerd.
- That the image responds to appropriate signals - Eg. ``docker stop``, shutting the image down cleanly
- That if the image is killed and then restarted, that it works correctly (delete PID file)
- That it functions correctly in Admiral
- That if a VIC volume is mapped to /var/lib/docker, that it correctly persists state
- That there is a simple way to configure TLS authentication for the nested daemon
- That file permissions in the image conform to the recommendations described here: https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.12.0_Benchmark_v1.0.0.pdf

There is also a build dependency here. Every time Photon comes out with support for a new Docker engine, we'll need to update the vmware/photon:dind images. We should make this a part of the VIC build process. It should test for a PhotonOS update and trigger a DinV build, test and push.

**Acceptance Criteria**

In addition to conforming to the above requirements, we should run system tests against the image ensuring that it is able to handle a substantial build job and various system tests such as Wordpress.

**Comment by frapposelli** [comment]
Tracking progress:

- [ ] There is no issue with zombie processes, given the way we're initializing dockerd.
- [ ] That the image responds to appropriate signals - Eg. docker stop, shutting the image down cleanly
- [ ] That if the image is killed and then restarted, that it works correctly (delete PID file)
- [ ] That it functions correctly in Admiral
- [ ] That if a VIC volume is mapped to /var/lib/docker, that it correctly persists state
- [ ] That there is a simple way to configure TLS authentication for the nested daemon
- [ ] That file permissions in the image conform to the recommendations described here: https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.12.0_Benchmark_v1.0.0.pdf
