### ISSUE TITLE
DinV Build: Design for transparent integration of nested build slave

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4859]
**User Statement:**

As a Docker developer, I want to be able to use VIC to in my development pipeline to build Docker images. It's not important to me how this works under the covers, but it needs to be a simple consumption model that gives me a good user experience.

**Details:**

By far the simplest way to deliver Docker build functionality in VIC is to delegate to a nested Docker engine. The main downsides to this approach are:

- The build process won't happen in a VIC container, rather it will happen in a regular Docker container. That means that there will be a limited number of cases where it's not possible to build a particular image using regular Docker, because a VIC container is potentially able to run things that a regular Docker container is not. Kernel modules would be one example of this.

- The build process may not be as transparent, depending on the implementation. For example, the output of ``docker build`` may not appear in the image cache of the target VCH. 

However, the benefit of covering the vast majority of use-cases in a transparent manner with integration into the rest of VIC product is high compared to the cost of implementation.

There are three approaches we could consider here:

1) Integrate a Docker engine into the endpoint VM.

Personally I don't think this is the best idea, but we should be able to articulate why. Sure it's well-integrated, but it would increase the size of the download, it significantly complicates the operation of what should be a very simple stateless VM and it potentially makes upgrade more complicated by tying the version of the build slave to the version of VIC. Additionally it would mean VIC redistributing Docker Engine which would carry its own implications. 

That said, if the proposed endpoint VM plugin model also needs to make use of a nested Docker engine, it may tip the balance toward a design where everything in the endpoint VM is a container. As such, we shouldn't discount this idea completely.

2) Spin up a sealed "build slave" VM on a ``docker build``. 

The idea here is that there would be a separate DinV VM that's spun up specifically to do a build. In the spirit of ephemerality and resource consumption, it would be better if it operated on a slave-per-build basis where the build slave is only running during the time it needs to process the build. This then opens up the potential for running multiple builds concurrently in multiple build slaves in a single VCH.

The User experience is that ``docker build`` command in the VIC Docker personality would be proxied to the build slave which would work hand-in-hand with the endpoint VM to pull dependencies and create the VMDKs. VMDK creation should be possible by going through the same code-path as a pull, but using the build slave's output as input.

If a VCH is used exclusively for builds, there's no reason it shouldn't be possible to keep build slaves running as a pool. That would have to be a configuration option somewhere (like if you start a build slave manually, the VCH uses it, but doesn't shut it down).

This approach would likely be the most secure, since the build slaves would be completely sealed appliances. It would also be the most performant, since the build slave would be able to cache intermediate layers on its local filesystem which could be persisted in a VIC volume, or simply by using stop/start instead of deleting post-build.

However, this approach is easily as complex to implement as (1), particularly if the Docker personality needs to schedule to multiple slaves. 

3) Add a simple capability to the DinV deployment tool (#4854) so that builds can be done using a secured nested remote API. 

The advantage of this is the simplicity - there is no proxying involved. The main disadvantage is that the output of the build would have to be pushed to a registry and pulled back in again before it could be run. However, the intermediate cache layers could still be persisted in the build slave.

The other advantage of the simplicity of this approach is that it can reuse whatever standard DinV image we provide as vmware/photon:dinv (#4852) or whatever tools we provide for developers/enterprises to roll their own.

**Acceptance Criteria:**

The output of this issue should be a recommendation for which of the three approaches we should take and a draft design for how we should approach it. That will require consultation with user-experience teams, the PM team, @hickeng and ideally some customers actively doing PoCs.

**Comment by corrieb** [comment]
Note that https://github.com/vmware/vic/issues/4741 covers implementation of native docker build in VIC. These issues are mutually exclusive, so there needs to be a sizing of both in order for a sensible choice to be made.

**Comment by frapposelli** [comment]
Closed by #5412
