### ISSUE TITLE
DinV Build: Document how to use DinV image remote API for builds

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4860]
**User Statement:**

As a Docker developer using VIC, in the absence of a well-integrated docker build option, I would like to know how to use the VMware DinV image to manually run a build, push the output and deploy to production.

**Details:**

This is a simple near-term goal to support #4852 and ahead of an implementation of #4859.

We simply need to make sure that we document how to use the VMware DinV image remote API to go through a simple build process of build, push and pull. It would be worth covering how to use commit and push also.

In addition to the basic workflow, the document should discuss

how to use the DinV image in stateful and stateless modes (persist the image cache in a VIC volume) with a discussion of the benefits
how to easily integrate the DinV slave with a secure Harbor instance
examples of how to integrate with popular build tools such as Jenkins

**Acceptance Criteria:**

A comprehensive document on how to use the Photon DinV image in #4852 for manually building docker images, that meets the requirements above.

**Comment by stuclem** [comment]
@corrieb can I move this one to the vic-product repo, or do you need to keep it here?

**Comment by frapposelli** [comment]
vmware/vic-product#418
