### ISSUE TITLE
syslog support for container logs

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#4862]
Redirect container logs (i.e. stdout/stderr of the container payload) to a syslog endpoint. 

Acceptance:
* endpoint specified by vic-machine option added by #4861 should be used
* container stdout/stderr should show up on the syslog server as long it is routable from the container

**Comment by hickeng** [comment]
@fdawg4l this will need to integrate with the container firewall rules to allow access to the syslogd endpoint.

**Comment by fdawg4l** [comment]
@hickeng will it?  From the issue, it looks like the CVM will connect to a syslog server.  That would make the cVM a client in this case.  We only need to add ports for services exposed to the external network on the cVM.

Also, if we were to expose a service on the cVM itself, the workflow is the same;  add the needed ports to the Ports[] field of the container.
