### ISSUE TITLE
CI fails intermittently at vic/lib/apiservers/engine/backends/convert

### ISSUE THREAD

**Issue by maplain** [vmware/vic#4869]
See this once for a while, most of the times a rerun will get rid of it.

**Details:**
--- FAIL: TestContainerNotRunningNoStream (1.00s)
    assertions.go:225:
                       
    Error Trace:    stats_test.go:247
        
    Error:        Should be false
        
FAIL
coverage: 91.3% of statements
FAIL    github.com/vmware/vic/lib/apiservers/engine/backends/convert    7.162s
Makefile:261: recipe for target ‘test-job-github.com/vmware/vic/lib’ failed
make: *** [test-job-github.com/vmware/vic/lib] Error 1
make: *** Waiting for unfinished jobs....

**Comment by cgtexmex** [comment]
fixed with #4874
