### ISSUE TITLE
Build a bootstrap iso for k8s host

### ISSUE THREAD

**Issue by maplain** [vmware/vic#4889]
As a developer of the kov I want to have a bootstrap iso to bring up k8s master and nodes

Acceptance criteria:

- with required packaged installed
- disables password expiration for root and adds a docker group
- boot sequence is correctly configured

**Comment by mhagen-vmware** [comment]
@maplain Not sure where the verifiable item is here? Can you please indicate where you put the bootstrap iso?

**Comment by maplain** [comment]
@mhagen-vmware oh sorry. I forgot to link the PR. it's now moved to next sprint. I'll put it back to backlog.
