### ISSUE TITLE
Populate scratch with the minimum OS structure

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#489]
There are some core files and directories that need to exist for the containers to function correctly.
For Linux these are:
/etc/hostname
/etc/hosts
/etc/resolv.conf
/proc
/sys
/lib/modules - needed for bindmount of appropriate kernel modules for insmod
/usr/lib/iptables - possibly needed, but needs confirmation

/.tether

These should be created on scratch so that their presence doesn't show up in image diffs.
The files are present so that they can be used as bindmount targets, not to be populated with specific data.

**Comment by fdawg4l** [comment]
@hickeng, `hosts`, `hostname`, and `resolve.conf`, I'm guessing, are not the same for all containers.  If my understanding is correct, what decides their values when scratch is created?

**Comment by hickeng** [comment]
This is post-GA. Necessary when we allow commit.

**Comment by mdubya66** [comment]
Moving to Icebox as id'd as post GA

**Comment by chengwang86** [comment]
so far my understanding of what needs to be done for this ticket is:

1. When creating the `scratch` in the image-store, also create folders/files specified above within the scratch disk, such that later on `docker diff` does not consider adding these basic folders/files as changes to the image

2. when creating a container from an image, `bootstrap` (https://github.com/vmware/vic/blob/master/isos/bootstrap/bootstrap) needs to copy the above folders/files from the image to the container filesystem under the `/.tether` folder

@jzt I think there might be something wrong with my second point. Could you please add a comment to clarify? Is it just a matter of adding something like `cp /etc/host {MOUNTPONT}/.tether`?

**Comment by hickeng** [comment]
@chengwang86 The only files & directories that need to be present in scratch are those that are used as targets for bind mounts. We already copy all necessary files into the container in https://github.com/vmware/vic/blame/master/isos/bootstrap/bootstrap

I've updated the original description to add two more directories, one of which I'm unsure is necessary but is needed given current bootstrap file.

There's no need to copy hosts, hostname, resolv.conf to `/.tether`. Those are created and maintained by tether itself ( @hmahmood added this if you need details ).

`/.tether`/ is a tmpfs meaning anything created on there will not show up on the container filesystem when we run an offline diff so it's only the `/.tether` directory that's needed in scratch as a mount point.

**Comment by chengwang86** [comment]
@hickeng Where did you see this `/usr/lib/iptables`? I can only find `iptables` dir on my `ubuntu` VM under `usr/share/iptables`

**Comment by chengwang86** [comment]
@hickeng I find that if we want the `bind-mount` to persist across reboots, we need to also update `/etc/fstab` with the bind mount. [Here ](https://backdrift.org/how-to-use-bind-mounts-in-linux)is an example. Do you think if we need this?

**Comment by chengwang86** [comment]
@hickeng the files `/etc/hosts, /etc/hostname, /etc/resolv.conf` are created by tether after this line https://github.com/vmware/vic/blob/master/isos/bootstrap/bootstrap#L82

So I cannot `bind-mount` the those files from the image file-system (created in `scratch`) to the same files in the container file-system, right?

**Comment by hickeng** [comment]
@chengwang86 you're not wanting to bind mount to the files that exist in /etc prior to the switch-root as that data is useless. You're wanting the following - this is an example in the context of the bootstrap script you linked:
```
${MOUNTPOINT}/.tether/etc/hosts ${MOUNTPOINT}/etc/hosts
```

You can try adding those mounts in the bootstrap script, but you may need to do it in tether after the switch-root to eliminate the path reference to the iniramfs filesystem (the rootfs prior to switchroot). 

The purpose of the bind-mount for these files is so the _data_ in them is written to a tmpfs and doesn't show up in diffs.

**Comment by chengwang86** [comment]
@hickeng @jzt  Here is the workflow of how tether generates `/etc/hosts`: it first creates a temp file (e.g., /etc/host32523532) and writes hosts info into that temp file. Then tether calls[ `os.Rename()` ](https://github.com/vmware/vic/blob/master/lib/etcconf/etcconf.go#L104)(similar to `mv /etc/host3253232 /etc/host`)to replace the existing /etc/host. This is done such that the original `/etc/hosts` remains unchanged even if tether fails writing host info.

However, if I do `mount --bind /.tether/etc/hosts /etc/hosts` **before** the above process, `os.Rename()` will throw an error `device or resource busy` and then the containerVM will fail to start (powered off). 

If I do `bindmount` **after** the above process, new data will not be written to `/.tether/etc/hosts`; instead, `/etc/hosts` will become empty.

**Comment by chengwang86** [comment]
@hickeng Do we just want to `bind-mount` the following:
- /etc/hosts
- /etc/hostname
- /etc/resolv.conf

or all the files/folers listed in your original post? E.g., mount --bind /.tether/proc /proc

**Comment by chengwang86** [comment]
@hickeng @jzt  If an image-store is created by an older-version VCH, it may not have these min os files/folders even after VCH upgrade. In this case, diff will output wrong results (no matter upgrade is done or not).

**Comment by chengwang86** [comment]
Based on my discussion with @emlin , for backward compatibility we need to investigate the following:

When initializing the VCH, if the `scratch` disk already exists (meaning we are performing VCH upgrade/configure/restart), can we further check whether the `scratch` has the minimum OS structure and add necessary files (e.g., `/etc/hosts`) to the scratch disk if it does not have these files?

If yes, docker diff should work normally on new containers. Otherwise, docker diff may show wrong results on new containers created using the old `scratch` .

**Comment by chengwang86** [comment]
@jzt proposed the following possible solution (please correct me if something's wrong):

During VCH upgrade, we create another scratch disk (let's say `scratch_1`) as the child of the original scratch. 
- New containers created by the upgraded VCH will use `scratch_1` which has all the necessary files for minimum OS structure.
- Old running containers still use the original scratch. 
- Old stopped containers, if being restarted, should switch to `scratch_1`

**Comment by hickeng** [comment]
@chengwang86 You cannot re-parent an image like that with a block based overlayer. We would have to re-extract all of the image layers on top of the new scratch, which means depending on the ability to commit containers.

We can:
a. document that there's runtime management files that will show up in a diff 
b. provide a mask for those files and skip them - this will actually provide comparable behaviour because, unless someone messes with the bindmounts which basically voids behavioural assumptions, there'll be no data in any files where we're bind mounting (which is the entire purpose of the bind mount).
