### ISSUE TITLE
Suggestions for the UI install Document

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic#4898]
After a few UI plugin installs I have some feedback about the install docs. 

Feedback is for Document Links:
https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/plugins_vcsa.html
https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/plugins_vc_windows.html

The install requirements are not clear saying to perform install steps on the system the install was downloaded too.  This could be anything which is problematic. For example the install.sh cannot be run from ESXi due to not having curl to pass the check_prerequisite (), but based on how the docs are written it should work. Looking around I did not find any details of what OS can run the installer on other pages or where to run the installer from. Looking at each install.sh and install.bat, these look like they are easiest run on the vCenters directly and not from an external machine. Also I am seeing what looks like compatibility issues installing the UI to the VCSA from a windows box or installing the UI to a windows vCenter from a linux or Darwin OS. I hope to get a chance to test these later. 
Even so probably easier have the instructions linear showing a dependable example and as copy paste friendly as reasonable. For the sake of clarity draw the line in the sand of install from the vCenter being the go to as that is a fairly dependable configuration and installed set of packages. 

Windows vCenter:
First step is confusing both suggesting non vCenter system and using incorrect windows file syntax. 
Current - "1. On the Windows system on which you have downloaded and unpacked vSphere Integrated Containers Engine, open the \vic\ui\vCenterForWindows\configs file in a text editor."
Suggestion 
"1. On the vCenter Server open a browser to https://vic_appliance_address:9443. Download the vic 1.1.0.tar.zip and unpack the files to the desktop. Open the file %USERPROFILE%\Desktop\vic\ui\vCenterForWindows\configs in notepad."

**C:\WINDOWS\system32> notepad %USERPROFILE%\Desktop\vic\ui\vCenterForWindows\configs**

Suggesting to include a CLI way to get thumbprint for step 4. Then the current step 4 becomes step 5.

**C:\WINDOWS\system32> echo | "%VMWARE_OPENSSL_BIN%" s_client -connect vic_appliance_address:9443 | "%VMWARE_OPENSSL_BIN%" x509 -fingerprint -sha1 -noout**

In step 6 breaks syntax of previous examples. Would be more clear to use the full example of "SET target_vc_version=6.5" and "SET target_vc_version=6.0" respectively and keep a cleaner look over "6.5" and "6.0.

For copy/paste ability step 7. would update to something like "Open the Windows command prompt as administrator and run the install.sh. installer" with the follow for the sample.

**C:\WINDOWS\system32> %USERPROFILE%\Desktop\vic\ui\vCenterForWindows\install.bat**

In step 8. could help jog the end user's memory to include the example default user "administrator@vsphere.local" . Many users have a lot of administrator accounts for different parts of multiple VMware product offerings that things can get confusing. 

In step 9. suggest to also include step to restart web-client service as well if logging out and logging in does not activate the plugin. Often I find a newly registered plugin doesn't load as it should without starting up with the web client services start up processes.

**C:\WINDOWS\system32> "C:\Program Files\VMware\vCenter Server\bin\service-control" --stop vspherewebclientsvc
C:\WINDOWS\system32> "C:\Program Files\VMware\vCenter Server\bin\service-control" --start vspherewebclientsvc**

Last on the windows instructions, looking a the HTML5 there does not seem to be a compatible HTML5 installer the only one is bash. I do not have a windows 6.5 lab to test yet and would open separate issue if this turns out to be a problem.

VCSA:
Suggest including links the vCenter Bash Shell directions in the "Prerequisites" to the vSphere documents might help here in case this changes again. For example 6.0 originally had to enable Bash from DCUI, the vami was added in a later update (U1 I think).
6.0
http://pubs.vmware.com/vsphere-60/topic/com.vmware.vsphere.vcsa.doc/GUID-B259B969-3E5D-4576-8256-D3BED54B89AF.html
6.5
http://pubs.vmware.com/vsphere-65/topic/com.vmware.vsphere.vcsa.doc/GUID-B259B969-3E5D-4576-8256-D3BED54B89AF.html

Similar concerns for the first step as windows installer first step in having vague direction. Suggestion is to change the wording to be specific to the VCSA. For example.

1. SSH to the VCSA and download the vic ui installer and unpack the installer. 

**~# curl -k -o https://https://vic_appliance_address:9443/vic_1.1.0.tar.gz
~# tar -zxf vic_1.1.0.tar.gz** Name needs validation not 100% on the "_". I suppose the user could just download all three which wouldn't hurt. 

For each of the variables could also have a "sed" example as it is a bit more copy paste friendly for users who are not comfortable with VI due to the VCSA being the only linux VM like some Windows shops have. In this example all three config file locations can be updated from any previous value to the desired value in one command each.

**~ # sed -i 's#^\(VCENTER_IP=\).*$#\1"10.0.1.2"#' ~/vic/ui/*/configs
~ # sed -i 's#^\(VIC_UI_HOST_URL=\).*$#\1"https://vic_appliance_address:9443"#' ~/vic/ui/*/configs**

Recommend adding the CLI way to get thumbprint for step 4. The current step 4 becomes step 5. Although similar to the windows version '|&' is incompatible with Windows CLI.  

**~# echo | openssl s_client -connect vic_appliance_address:9443 |& openssl x509 -fingerprint -sha1 -noout**

Step 6 is confusing in the VCSA installer instruction. Suggest removing this step. If I am not mistaken even with the value change in vic/ui/HTML5Client/install.sh command prompt mentioned in step 7. will fail on the check due to having curl on windows. PowerShell has a curl alias, but my research is not showing bash to work on Windows in general. My initial testing with command prompt and PowerShell both fail to handle the install.sh.

Step 7 reference command prompt which is confusing seeing how this would be linux based instructions for most users. Maybe update to something like: 
"Run the install.sh installer"
_Flex Plugin_
**~# ~/vic/ui/VCSA/install.sh**
_HTML5 Plugin_
**~# ~/vic/ui/HTML5Client/install.sh**

Lastly would it be useful to have a note mentioning to check the performance of the web client is handling the additional load from plugin correctly? I have seen performance be factor for a plugin working or not. It is semi-common to see under sized vCenters and every so often the additional plugin load is the tipping point to start hitting data service timeouts. Section of possible interest "vSphere Web Clients" page 60 https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/techpaper/vmware-perfbest-practices-vsphere6-0-white-paper.pdf The one for 6.5 does not seem to have been release yet.

**Comment by dbarkelew** [comment]
@stuclem You might be interested in the above feedback.

**Comment by stuclem** [comment]
@dbarkelew I certainly am. Thank you for the very detailed feedback. I'm moving this issue to the `vic-product` repo, which is where we track doc updates.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #180](https://github.com/vmware/vic-product/issues/180) via [**ZenHub**](https://www.zenhub.com/)
