### ISSUE TITLE
docker-compose fails with volume dependency

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#4899]
engine version: v1.1.0-9852-e974a51

steps to reproduce: deploy simple wordpress with mariadb.

```
ERROR: for mysql  Cannot create container for service mysql: Server error from portlayer: ServerFaultCode: Permission to perform this operation was denied.
ERROR: Encountered errors while bringing up the project.

```

**Comment by malikkal** [comment]
Apr 26 2017 12:43:59.009Z DEBUG unexpected soap fault on task retry : types.NoPermission{SecurityError:types.SecurityError{RuntimeFault:types.RuntimeFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, Object:types.ManagedObjectReference{Type:"VirtualApp", Value:"resgroup-v52282"}, PrivilegeId:"VirtualMachine.Config.AddExistingDisk"}
Apr 26 2017 12:43:59.009Z DEBUG unexpected error on task retry : soap.soapFaultError{fault:(*soap.Fault)(0xc4209fbae0)}
Apr 26 2017 12:43:59.009Z ERROR An error occurred while waiting for a creation operation to complete.

**Comment by hickeng** [comment]
@malikkal Did updating the role with this privilege address this specific issue?

@stuclem Hey Stuart - could you update the docs with the `VirtualMachine.Config.AddExistingDisk` for the `VCH - endpoint` role.

@mhagen-vmware customers are hitting this class of issue, so we need to prioritize #4444  - it's the only way to ensure the future changes don't invalidate docs. We will need #3951 soon as well to support #1689

**Comment by malikkal** [comment]
@hickeng Yes, it helped resolve. Thank you.

**Comment by mhagen-vmware** [comment]
@stuclem Just checking in, were you able to add the doc change that George requested above?

**Comment by stuclem** [comment]
@mhagen-vmware yes, I added it in https://github.com/vmware/vic-product/pull/194, which is merged to `vic-product/master`. I just published the update to https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/set_up_ops_user.html.

**Comment by mhagen-vmware** [comment]
Perfect, thanks!
