### ISSUE TITLE
OVA Installer: Update installer with new components

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4902]
**User Statement:**

As a user of VIC, I want to make sure the OVA installer carries all the required components at the right version.

**Details:**

Update the installer with updated bits and make sure install procedures are correctly executed during the provisioning phase.

**Acceptance Criteria:**

- VIC OVA should be successfully built using components versions > 1.1
- Output OVA artifact should be installable and in perfect working conditions

**Comment by andrewtchin** [comment]
Verified Harbor v1.1.1-rc4, VIC Engine v1.1.1-rc2, Admiral 1.1.1-7989 included in vic-v1.1.1-rc2-1f1711a0.ova
