### ISSUE TITLE
OVA Installer: Ensure upgrade works from 1.1 to 1.2

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4903]
**User Statement:**

As a user of VIC, I want to be able to update my currently deployed VIC 1.1 install to be upgraded to a later version without losing configuration and data.

**Details:**

Update should be performed in-place by detach/attach of the data disk used by VIC 1.1 onto newly deployed VIC 1.2 appliance with no further manual intervention from the user side.

**Acceptance Criteria:**

- Deploy a VIC OVA >1.1, attach disks from a 1.1 install, all the data is correctly picked up by the OVA components.

**Comment by andrewtchin** [comment]
verified this works with v1.1.1
