### ISSUE TITLE
VCSA Plugin Install - failed to find target plugin (com.vmware.vicui.Vicui)

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#4906]
**User Statement:** As an engineer, I want to be able to install the VCSA client plugin on a vCenter Server Appliance

**Details**:  Following this guide: [Install the Client Plug-Ins on a vCenter Server Appliance](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/plugins_vcsa.html) I get this error:

`failed to find target plugin (com.vmware.vicui.Vicui)
Reading plugin-package.xml...
./install.sh: line 125: ../vsphere-client-serenity/-/vc_extension_flags: No such file or directory
File -.zip does not exist!
`
when following the steps under the "Procedure" section on step 7.  
**Running the `./install.sh` command produces this error.**

When looking at the root directory under /vic/bin/ui, I do not see the `com.vmware.vicui.Vicui-X.Y.Z` folder.  I do see the HTML5Client, plugin-packages, vCenterForWindows, VCSA, and vsphere-client-serentity folders plus the plugin-manifest file.

**Acceptance Criteria:**
1.) `com.vmware.vicui.Vicui-X.Y.Z` folder needs to be present or code needs to point to the correct directory.

**VIC version:** 1.1.0 - [Product Binaries](https://my.vmware.com/en/web/vmware/details?downloadGroup=VIC110&productId=614&rPId=15884)

**Deployment details:**
./vic-machine-linux create -t "ip was here" -u administrator@vsphere.local -p "password was here" --image-store vsanDatastore --bridge-network bridge --public-network vm-network --registry-ca ca.crt --no-tlsverify --force

**Comment by jooskim** [comment]
This relates to https://github.com/vmware/vic-product/issues/180#issuecomment-297426649. I'll work on a fix off of this issue.

**Comment by jooskim** [comment]
FYI, we used to have plugin ZIP files in the vic-engine tar ball file, but they are not only available under the OVA appliance. The script that threw an error above was supposed to be updated such that it no longer finds those files, but I forgot to do.

**Comment by vmwarelab** [comment]
@jooskim Hi Josh i have the same issues with VIC 1.1
any chance you guys found a fix ?

**Comment by jooskim** [comment]
Hey @vmwarelab, this issue is exactly same as what you are experiencing. Sorry for the inconvenience.

**Comment by stuclem** [comment]
Added as a resolved issue in https://github.com/vmware/vic/releases/tag/v1.1.1-rc2

**Comment by spadeq** [comment]
When executing ./install.sh, it still prompts "failed to find target plugin (com.vmware.vicui.Vicui). This problem is not resolved at all in v1.1.1.

**Comment by jooskim** [comment]
@spadeq the installer first checks up if there is what's now a outdated version (pre 1.0 release) installed on the VC, and if does it tries to remove that before installing the latest VIC UI. So if you get the error message this is not something to worry about. I simply had to make sure that any user that happens to be using the old version (whose key is `com.vmware.vicui.Vicui`) gets it removed. However, it is bad user experience that you see the message so I'll improve that on later releases.
