### ISSUE TITLE
Nightlies 6.0 5-4-HA test fails on teardown and other places

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#4924]
Build# 9992
vSphere v6.0

`Suite teardown failed:
Several failures occurred:

1) Environment variable '%{VCH-NAME}' not found.

2) Environment variable '%{VIC-ADMIN}' not found.

3) Environment variable '%{VIC-ADMIN}' not found.

4) Environment variable '%{VCH-NAME}' not found.

5) TypeError: argument of type 'NoneType' is not iterable

6) Environment variable '%{HOST_TYPE}' not found.`

**Comment by rogeliosanchez** [comment]
[5-4-High-Availability.zip](https://github.com/vmware/vic/files/959951/5-4-High-Availability.zip)

**Comment by jzt** [comment]
[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1354271/5-4-High-Availability.zip)

**Comment by mhagen-vmware** [comment]
fixed with #6530
