### ISSUE TITLE
UI plugin is broken for the Flex plugin

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#4948]
**User Statement:**
As a UI engineer I want to make sure the plugins (both the Flex and HTML5 ones) always work as expected.

**Expected behavior:**
Plugins should appear in their respective platform.

**Actual behavior:**
The Flex client plugin doesn't show up in the Flex client. Plugin is registered fine and didn't throw any error in the log message, but portlets are not visible. This is because of Cheng's change a couple weeks ago that changed some key names in extraConfig that the portlets were using. Although I made an according change for the HTML5 Client I forgot to do the same for the Flex client plugin.

**Acceptance Criteria:**
Flex client should be back up.

**Comment by stuclem** [comment]
Added as a resolved issue in https://github.com/vmware/vic/releases/tag/v1.1.1-rc2
