### ISSUE TITLE
Container shows as running under the Admiral web UI when stopped using a linux command instead of the web ui; takes about an hour to update. 

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#4953]
**User Statement:**
As an engineer, I want the Admiral Web UI to display current container information when using the linux command line instead of the web ui.

**Details:**
The Admiral web ui is not displaying a container as stopped when the container was stopped using a docker command through the linux CLI.  The web ui will display correct status info if the container was stopped using the web ui (the requests and event log tabs will show the correct info as well).  However, the requests and event log tabs in the web ui will not show anything related with the docker stop command if using the linux CLI.

**Acceptance Criteria:**
Admiral web ui should display the correct/current status of a container under its deployments->containers web ui section.

**VIC version:** 1.1.0 - [Product Binaries](https://my.vmware.com/en/web/vmware/details?downloadGroup=VIC110&productId=614&rPId=15884)

**Deployment details:**
./vic-machine-linux create -t "ip was here" -u administrator@vsphere.local -p "password was here" --image-store vsanDatastore --bridge-network bridge --public-network vm-network --registry-ca ca.crt --no-tlsverify --force

**Steps to reproduce:**
(assuming you have a working Admiral/Harbor setup):
1.) Using the linux command line, start a container
    ` docker -H [vch ip]:2376 --tls run -itd busybox top`
2.) Verify that the container started through the Admiral web ui and through the command line using the docker command:
    `docker -H [vch ip]:2376 --tls ps -a`
3.) Stop the container
    `docker -H [vch ip]:2376 --tls stop [container id]`
4.) Verify container stopped through the command line using 
    `docker -H [vch ip]:2376 --tls ps -a`
5.) Notice that the Admiral web ui does not update.  Also, check the event log and requests tabs for verification that the web ui did not catch the stop command.
The container status box will still state 'Running for X sec/min/hours' even though the ps -a command will show that it has stopped.

**Actual behavior:**
Displaying container as "running" instead of stopped.

**Expected behavior:**
Should display current "stopped" status.

**Comment by rogeliosanchez** [comment]
![screen shot 2017-04-27 at 4 53 28 pm](https://cloud.githubusercontent.com/assets/26554503/25507589/8cb8e1ac-2b72-11e7-9bf1-611640a95c5f.png)

**Comment by rogeliosanchez** [comment]
![screen shot 2017-04-27 at 4 52 25 pm](https://cloud.githubusercontent.com/assets/26554503/25507594/932429de-2b72-11e7-8337-c7c596413b16.png)

**Comment by rogeliosanchez** [comment]
![screen shot 2017-04-27 at 5 11 41 pm](https://cloud.githubusercontent.com/assets/26554503/25507603/9f7feea2-2b72-11e7-8df7-b590283bc70b.png)
vSphere shows the container as powered off.

**Comment by cgtexmex** [comment]
This appears to be a bug in admiral, so why do we have an issue here?  Is this used to keep status of a bug in their tracker of choice?

**Comment by rogeliosanchez** [comment]
Issue moved to [vmware/admiral #93](https://github.com/vmware/admiral/issues/93) via [**ZenHub**](https://www.zenhub.com/)
