### ISSUE TITLE
Container usage stats displays unreadable cpu and memory stats info when stopped using a linux command instead of the web ui

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#4956]
**User Statement:**
As an engineer, I want to be able to get current and readable CPU and Memory usage stats for a container using the Admiral Web UI.

**Details:**
The Admiral web UI is not displaying readable usage stats for CPU and Memory when the container is stopped using a docker command in the linux CLI.

**Acceptance Criteria:**
Container usage stats info should be in a readable format and use meaningful information when the container is stopped using the linux CLI.

**VIC version:** 1.1.0 - [Product Binaries](https://my.vmware.com/en/web/vmware/details?downloadGroup=VIC110&productId=614&rPId=15884)

**Deployment details:**
./vic-machine-linux create -t "ip was here" -u administrator@vsphere.local -p "password was here" --image-store vsanDatastore --bridge-network bridge --public-network vm-network --registry-ca ca.crt --no-tlsverify --force

**Steps to reproduce:**
(assuming you have a working Admiral/Harbor setup):
1.) Using the linux command line, start a container
    `docker -H [vch ip]:2376 --tls run -itd busybox top`
2.) Verify that the container started through the Admiral web ui and through the command line using the docker command:
    `docker -H [vch ip]:2376 --tls ps -a`
3.) Stop the container
    `docker -H [vch ip]:2376 --tls stop [container id]`
4.) Verify container stopped through the command line using
    `docker -H [vch ip]:2376 --tls ps -a`
5.) Check the container's cpu and memory usage stats in the Admiral web UI.  Deployments -> Containers -> "container name".
Notice that the information displayed here is unreadable and the formatting is off.

**Comment by rogeliosanchez** [comment]
Related to #4953

**Comment by rogeliosanchez** [comment]
![screen shot 2017-04-27 at 4 53 28 pm](https://cloud.githubusercontent.com/assets/26554503/25508017/110480b8-2b75-11e7-85cc-cab580c2403a.png)

**Comment by rogeliosanchez** [comment]
![screen shot 2017-04-27 at 4 56 04 pm](https://cloud.githubusercontent.com/assets/26554503/25508026/152489cc-2b75-11e7-943c-3ca6f26ee759.png)

**Comment by cgtexmex** [comment]
This appears to be a bug in admiral, so why do we have an issue here?  Is this used to keep status of a bug in their tracker of choice?

**Comment by rogeliosanchez** [comment]
Issue moved to [vmware/admiral #94](https://github.com/vmware/admiral/issues/94) via [**ZenHub**](https://www.zenhub.com/)
