### ISSUE TITLE
Nightlies 6.5 vMotion-VCH-Appliance fails with `Didn't find VM "VCH-0-XXXX" in resource pool`

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#4963]
Build#9992
vSphere v6.5

```
Apr 27 2017 09:04:15.221Z INFO  Connect to docker:
Apr 27 2017 09:04:15.221Z INFO  docker -H sc2-rdops-vm07-dhcp-240-7.eng.vmware.com:2376 --tlsverify --tlscacert="VCH-0-7372/ca.pem" --tlscert="VCH-0-7372/cert.pem" --tlskey="VCH-0-7372/key.pem" info
Apr 27 2017 09:04:15.221Z INFO  Installer completed successfully
Apr 27 2017 09:18:25.027Z INFO  ### Removing VCH ####
Apr 27 2017 09:18:26.331Z INFO  Validating target
Apr 27 2017 09:18:27.146Z ERROR Didn't find VM "VCH-0-7372" in resource pool "VirtualApp:resgroup-v58"
Apr 27 2017 09:18:27.147Z ERROR Failed to get Virtual Container Host VCH-0-7372
Apr 27 2017 09:18:27.147Z ERROR Didn't find VM "VCH-0-7372" in resource pool "VirtualApp:resgroup-v58"
Apr 27 2017 09:18:27.147Z ERROR --------------------
Apr 27 2017 09:18:27.147Z ERROR vic-machine-linux delete failed: delete failed
```

**Comment by rogeliosanchez** [comment]
[13-1-vMotion-VCH-Appliance.zip](https://github.com/vmware/vic/files/964980/13-1-vMotion-VCH-Appliance.zip)

**Comment by rogeliosanchez** [comment]
Seen in build 9992 05/07/17
[13-1-vMotion-VCH-Appliance.zip](https://github.com/vmware/vic/files/984808/13-1-vMotion-VCH-Appliance.zip)

**Comment by chengwang86** [comment]
Update:

I just grabbed the log bundle for a successful run of the same test, and I observed **exactly the same error msg in vic-machine.log.**

My guess is that this error msg is `expected`. But we still need to figure out where/why this `vic-machine delete` cmd (as shown in the error msg) is called in the test script.

**Comment by sgairo** [comment]
Step 5 (where the delete happens) was recently commented out.

**Comment by sgairo** [comment]
Seems that this failed delete is expected.

**Comment by chengwang86** [comment]
Yes this is expected. I think there might be a bug in our test file. After vMotion the VCH, we reset the %{VCH-NAME} to `%{VCH-NAME} (1)`. Then when we try to delete the dangling VMs, we used the old vch name which still existed in the inventory but couldn't be found in the resource pool. I will try this test manually and see what is (not) expected.

**Comment by chengwang86** [comment]
The original error msg occurs here https://github.com/vmware/vic/blob/master/tests/resources/VCH-Util.robot#L302, which is called within the keyword of `Cleanup dangling VMs on Test Server`, while the latter is used within `Install VIC Appliance To Test Server` https://github.com/vmware/vic/blob/master/tests/manual-test-cases/Group13-vMotion/13-1-vMotion-VCH-Appliance.robot#L69 

This error occurs in 13-1-vMotion-VCH-Appliance all the time, but it is ignored by `Run Keyword And Ignore Error  Cleanup Dangling VMs On Test Server`.

In this test, after VM migration, `govc ls vm` shows (below is just one example when the VCH migrated is `VCH-0-8749`)
```
/vcqaDC/vm/VCH-0-8749
/vcqaDC/vm/VCH-0-8749 (1)
/vcqaDC/vm/Discovered virtual machine
```
When we try to delete the dangling VM `VCH-0-8749`, an error msg `ERROR Didn't find VM "VCH-0-8749" in resource pool "VirtualApp:resgrou...` is thrown (but ignored) and the rest of the VMs are not deleted.

**Comment by chengwang86** [comment]
Steps to reproduce the error:

1. set up a vsan cluster

2. create a VCH `vch-1`

3. `govc vm.migrate -host cls/new_esx_ip -pool cls/Resources vch-1/vch-1`   (`new_esx_ip` should be difference from the original `esx_ip` where the vch is deployed on)

4. `vic-machine delete --name=vch-1` and `vic-machine delete --name="vch-1 (1)"`

Observations:
- (a) the vch was renamed to `vch-1 (1)` and it was moved out of the original vapp `vch-1` 

- (b) the VCH still functions well and the new containers created would still be under the vapp `vch-1` 

- (c) `govc ls vm` shows that both `vch-1` and `vch-1 (1)` exist whereas the vsanDatastsore only has a folder for `vch-1`. 

- (d) `vic-machine delete` cannot delete `vch-1` and `vch-1 (1)`
  - Error msg when deleting `vch-1`: `Didn't find VM "vch-1" in resource pool "VirtualApp:resgroup-v58"`
  - Error msg when deleting `vch-1 (1)`: `Failed to get VCH resource pool "/vcqaDC/host/cls/Resources/vch-1 (1)": resource pool '/vcqaDC/host/cls/Resources/vch-1 (1)' not found`

**Comment by chengwang86** [comment]
Based on my discussion with @dougm , here are comments about these observations:

- (a) expected with the current test script: we move the `vch-1` to resource pool `cls/Resources` where there is an existing vApp named `vch-1`, so vc renames the vch to `vch-1 (1)`
- (b) expected with the current test script
- (c) expected with the current test script
- (d) expected (but this is a bug in our test script) because we move the VCH outside of the original resource pool (`cls/Resources/vapp_name`) by `govc vm.migrate .... -pool cls/Resources`, whereas `vic-machine delete` still assumes that the vch is under the original resource pool.

To fix, remove `-pool` from `govc vm.migrate`.
