### ISSUE TITLE
[bug] port-layer-server dies with "ERROR: SystemError"

### ISSUE THREAD

**Issue by inkysea** [vmware/vic#497]
**VIC Version:**

0.1 / master / commit ID

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**  
Port-layer-server should start successfully after install VIC.

**Actual behavior:**
A fresh install of VIC from .1 binaries results in an error when starting the port-layer-server.  Error in the port-layer-server.log is below

Launching /sbin/port-layer-server --host=localhost --port=8080 --insecure --sdk=root:XXXXX@10.25.27.13 --datacenter=ha-datacenter --cluster=/ha-datacenter/host/* --datastore=/ha-datacenter/datastore/ssd-13 --network=/ha-datacenter/network/VM Network --vch=vic2
time="2016-04-11T12:43:55Z" level=fatal msg="ERROR: SystemError" 
Component /sbin/port-layer-server has died - relaunching

VIC was installed using the following command. Output of the command was successful and matched output of README example.
./install.sh -g -t 'root:XXXXX@10.25.27.13' -i ssd-13  vic2

**Comment by inkysea** [comment]
Update on ESX information:

ESX Build:  VMware ESXi, 6.0.0, 2809209
vCenter:  6.0   with vROPs 6+ and NSX 6+
VM Network working on Standard Network.  vCH is network addressable on VM Network

**Comment by hickeng** [comment]
@inkysea is there anything of note in the other logs?
If not, try using the -f flag to the installer - that will force cleanup of an existing image store which could cause this - we're not yet handling reload of image store state.

**Comment by inkysea** [comment]
@hickeng I tried it with the -f flag and got the same results.  It's important to note that my previous attempts were with unique names for the VCH.  I don't see any other information in the logs.  I've included the output of my install below and everything looks normal.

_[11-04-16 15:39:10] Uploading... OK
# Creating vSwitch
# Creating Portgroup
# Creating the Virtual Container Host appliance
# Adding network interfaces
# Setting component configuration
# Configuring TLS server
# Powering on the Virtual Container Host
# Setting network identities
# Waiting for IP information
# 
# SSH to appliance (default=root:password)
# root@10.25.27.93
# 
# Log server:
# https://10.25.27.93:2378
# 
# Connect to docker:
docker -H 10.25.27.93:2376 --tls --tlscert='vic1-cert.pem' --tlskey='vic1-key.pem'

DOCKER_OPTS="--tls --tlscert='vic1-cert.pem' --tlskey='vic1-key.pem'"
DOCKER_HOST=10.25.27.93:2376_

Could it be my version of ESX?

**Comment by dougm** [comment]
Let's have a look at the logs, can you attach https://10.25.27.93:2378/logs.tar.gz ?

**Comment by inkysea** [comment]
[logs.tar.gz](https://github.com/vmware/vic/files/214328/logs.tar.gz)

**Comment by inkysea** [comment]
Just to rule out vSphere version. I upgraded to the latest version of ESX 6.0 update 2.  The problem still occurs in my environment with the latest ESX version.

**Comment by inkysea** [comment]
I replicated this in a One Cloud pod with vCenter and NSX.  I ran govc logs.download on the host.    The log bundle was too big to upload so I've included this link to download the bundle:  https://drive.google.com/open?id=0B9fFgEzcaLObckVrZ01TM0h4YUE

**Comment by inkysea** [comment]
I disconnected the host from vCenter and removed a distributed port group from the host.  After that the problem goes away.    It appears at the least, if a distributed port group is on the host then it does not work.

**Comment by cgtexmex** [comment]
Thanks for troubleshooting and providing details.  We are currently working on vSphere support -- as of now VIC has been tested with stand alone ESXi hosts.  I'll leave this issue open until that functionality is implemented and tested.

**Comment by dougm** [comment]
vCenter support will be in the upcoming 0.2 release.  Let's revisit then if there are still issues against @inkysea 's environment.
