### ISSUE TITLE
ERROR vic-machine-linux create failed: Invalid public network gateway: Provided gateway IP address is not valid: 20.26.24.1/24

### ISSUE THREAD

**Issue by gonghuahill** [vmware/vic#4973]
This script is ok in vic-machine-linux version v0.8.0-7315-c8ac999 ,but can't run on vic-machine-linux version v1.1.0-9852-e974a51
root@photon-Zzw3wkzzl [ /vic11 ]# ./vic-machine-linux -v
vic-machine-linux version v1.1.0-9852-e974a51
root@photon-Zzw3wkzzl [ /vic11/sh ]# more c_zj.sh
../vic-machine-linux create  --target 20.26.24.254 --force --image-store cssds05_10  --user administr
ator@vsphere.local --bridge-network dvPortGroup-bridge-c5   --compute-resource  cluster05 -p XXXXXX
 --no-tls --public-network dvPortGroup-ext-c5 --public-network-ip 20.26.24.102/24 --public-network-ga
teway 20.26.24.1/24  --management-network dvPortGroup-ext-c5  --client-network dvPortGroup-ext-c5  --
dns-server 20.26.24.100 -name vch11_1  -vs cssds05_10/vch-vm:default
root@photon-Zzw3wkzzl [ /vic11/sh ]# ./c_zj.sh
Apr 27 2017 14:32:57.737Z INFO  ### Installing VCH ####
Apr 27 2017 14:32:57.737Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Apr 27 2017 14:32:57.737Z ERROR --------------------
Apr 27 2017 14:32:57.737Z ERROR vic-machine-linux create failed: Invalid public network gateway: Provided gateway IP address is not valid: 20.26.24.1/24

**Comment by rogeliosanchez** [comment]
@gonghuahill , we don't support a network mask in --public-network-gateway assignments.  

Please remove the '/24' from the `--public-network-gateway 20.26.24.1/24` assignment.

Searching for `public-network-gateway` in this document under "Advanced Options" in [VCH Deployment Options](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_options.html#advanced) will provide an explanation on how to assign a public network gateway.
