### ISSUE TITLE
Comma-separated DNS list in OVA is an unreported misconfiguration

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4987]
I wasted hours trying to understand why my VIC OVA deployment with static IP appeared to have deployed correctly, but was in fact misconfigured. 

Everything appeared to work, except I couldn't add Harbor to Admiral in the UI.

It was all down to the fact that I comma separated the DNS servers in the OVA deploy. It does say "space separated", but most other VMware things I've installed expect comma separation. 

Unfortunately the OVA does not or cannot validate the correct formatting of these fields.

I would recommend we both:
- Auto-correct commas to spaces when we install
- Test that DNS servers, gateway and other static IP settings are correct and if not, report as such

**Comment by andrewtchin** [comment]
@stuclem documentation might be required for the new screen that shows the status
@morris-jason please provide stuart screenshots showing good and degraded status

**Comment by stuclem** [comment]
OK, thanks @morris-jason and @andrewtchin
