### ISSUE TITLE
Nightlies 6.0 VSAN Simple and VSAN Complex fail on Should Contain ${line}  .vcva-${VC_VERSION}' is up.

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#4989]
Build 9992 - 05/01/17 vSphere 6.0

There are many instances of this error in the output.xml file.  This happens right after deploying a nimbus testbed.  Both VSAN Simple and VSAN Complex share this issue.

VSAN Simple Error:
`<msg timestamp="20170502 13:35:34.347" level="FAIL">'2017-05-02 06:12:27 -0700: Loading plugin /mts/git/nimbus/lib/testframeworks/test-vpx ...' does not contain '.vcva-3634791' is up. IP:'</msg>`

VSAN Complex Error:
`<msg timestamp="20170502 14:51:21.530" level="FAIL">'2017-05-02 07:12:24 -0700: Loading plugin /mts/git/nimbus/lib/testframeworks/test-vpx ...' does not contain '.vcva-3634791' is up. IP:'</msg>`

**Comment by rogeliosanchez** [comment]
[5-6-1-VSAN-Simple.zip](https://github.com/vmware/vic/files/972164/5-6-1-VSAN-Simple.zip)
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/972165/5-6-2-VSAN-Complex.zip)

**Comment by matthewavery** [comment]
I have looked through the brief logs here. Looks like the connection on the other side of the upload fell over. I will be discussing a possible change to the nightly tests to account for this kind of behavior with @mhagen-vmware . I will also talk to @jzt about watching for how common this kind of  issue is becoming during this sprint of nightlies.

**Comment by matthewavery** [comment]
from the logs for VSAN_SIMPLE : `Upload failed for "bin/appliance.iso": Put https://10.160.149.73/folder/7c8b0859-dc59-14c8-bf5f-02000af0ebdb/V1.1.0-RC3-9992-8F0526F-appliance.iso?dcPath=%2FvcqaDC&dsName=vsanDatastore: write tcp 172.17.0.3:35238->10.160.149.73:443: write: connection reset by peer`

Looks like the connection fell over during the upload to nimbus. We may want to implement a simple retry to see if the connection reappears after a few seconds.

**Comment by matthewavery** [comment]
The vic-machine.log file for VSAN-COMPLES is missing, so it cannot be determined if this issue was the same. It appears though atleast for the Simple tests that a network drop occurred and reset the upload mid stream, it is possible that it was only temporary but caused the test to fail.

**Comment by jzt** [comment]
Seen in [5-4-High-Availability.zip](https://github.com/vmware/vic/files/1011424/5-4-High-Availability.zip)

**Comment by mhagen-vmware** [comment]
The simple failure is due to the ISO upload failure ultimately fixed with #5115 , the complex is due to a govc timeout trying to create the dvs for testing. That already has a remediation in it, if the VC is up and refuses to respond to a tcp connection for 30 minutes I am not sure there is much more we can do.   I have an outstanding question to the nimbus slack channel.  This is the error:
Post https://10.192.195.64/sdk: dial tcp 10.192.195.64:443: i/o timeout
