### ISSUE TITLE
OVA can't get DHCP IP when deployed on ESX without vCenter

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4993]
When deploying OVA on ESX without vCenter the `guestinfo.ovfEnv` properties that are not populated during deployment contain the string `null` instead of being empty, this triggers the network configuration script which tries to set a static ip.

As a developer of VIC I'd like to be able to deploy the OVA on ESX without requiring vCenter.

**Comment by mdubya66** [comment]
adding to 1.2. approved for 1.1.1 patch pending QA agreement

**Comment by ali5ter** [comment]
Workaround: Entering a space for each field under the Network Properties section of the Additional  Settings step during OVA deployment allows DHCP alloc of IP.
