### ISSUE TITLE
VC is not showing the actual IP address of integrated OVA 

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#4995]
**User Statement:**

Post deployment of the integrated OVA and subsequent power on, the IP address is not displayed correctly on VC.

**Details:**
Please see the attached screenshots.
![vic-1 1 1-correct-console-ip](https://cloud.githubusercontent.com/assets/25006749/25651486/faefa1c8-3000-11e7-8f1b-cf93a57937d0.PNG)
. 

![vic-1 1 1-ip-not-displayed](https://cloud.githubusercontent.com/assets/25006749/25651337/2bd40d70-3000-11e7-82a5-cb0f8e89861a.PNG)

The actual IP address of the integrated OVA can be seen from its console. The same IP address is not shown from the VC under the IP addresses section. It is important to show the console IP address in the IP addresses section for better user experience and ease of automation.

**Acceptance Criteria:**
Show the console IP address of OVA in its VM Summary: IP addresses section

**Comment by lgayatri** [comment]
![corrected](https://cloud.githubusercontent.com/assets/25006749/25658200/4ffad85e-301f-11e7-9a5d-5c7b0a589337.PNG)
Corrected the screenshot.

**Comment by rogeliosanchez** [comment]
@lgayatri ...  Spoke with @frapposelli about this and found out that the IP is listed in VC, but it's in there with the rest of the other IPs published by docker.  It looks like we can't push this IP to the top right now, but there is an enhancement coming soon which will return the IP in the OVA details in the VM summary.

**Comment by lgayatri** [comment]
In my case it did not show up anywhere even when I scrolled down the IPs listed by VC.

**Comment by rogeliosanchez** [comment]
@lgayatri , ah ok.  Thanks for pointing that out.

**Comment by frapposelli** [comment]
@lgayatri I was able to reproduce, unfortunately it's a display limitation of the vCenter UI, the enhancement that @rogeliosanchez is talking about will solve this issue

**Comment by andrewtchin** [comment]
To investigate: We may be able to put the IP in the OVA info portlet https://github.com/vmware/vic/blob/master/installer/packer/vic-unified.ovf#L179-L183

**Comment by andrewtchin** [comment]
Put the IP into guestinfo

**Comment by frapposelli** [comment]
This is going to be fixed alongside #5639
