### ISSUE TITLE
docker ps does not pick up shut down container

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4997]
from:
https://ci.vmware.run/vmware/vic/10236

After about 30 seconds the docker create ls container still had not exited. From my investigation though, it looks like it ran to completion within a reasonable amount of time:
/brave_goldwasser-af72af66d7f6/vmware.log
```
2017-05-03T04:07:44.893Z| vmx| I125: Log for VMware ESX pid=1982267 version=6.0.0 build=build-5224934 option=Release
```
snip
```
2017-05-03T04:07:50.087Z| vmx| W115: VMX has left the building: 0.
```
Less than 6 seconds, so seemingly our follow up docker ps somehow didn't pick that up for over 20 seconds after that.

[integration_logs_10236_59d19f32a0bfddd194852d3a292ed70d74f69d49.zip](https://github.com/vmware/vic/files/973432/integration_logs_10236_59d19f32a0bfddd194852d3a292ed70d74f69d49.zip)

**Comment by hickeng** [comment]
#4872 may well be the same thing.

**Comment by cgtexmex** [comment]
This container will power off when the `ls` operation is complete.  Powering off generates a vSphere event that should be captured by the portlayer and in response the portlayer will set the status to stopped.  In the case of this containerVM the portlayer never sees the powerOff event.

The event appears to have been generated by vSphere given this hostd.log entry:
```
2017-05-03T04:07:50.141Z info hostd[71780B70] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 105717 : brave_goldwasser-af72af66d7f6 on  ns539599.ip-144-217-72.net in ha-datacenter is powered off
```
Typically the portlayer receives that event _before_ it appears in the hostd.log -- in the following example the first two lines are from the portLayer log and the last line is the hostd log:

```
May  3 2017 04:08:23.408Z DEBUG Found 2 subscribers to vsphere.VMEvent: boring_blackwell-61e2105538ba on  ns539599.ip-144-217-72.net in ha-datacenter is powered off
May  3 2017 04:08:23.435Z DEBUG Container(61e2105538ba1969b8fd8ed875a7881183f3d6654e4f071d8efd8bf995eace3f) state set to Stopped via event activity
2017-05-03T04:08:24.010Z info hostd[6E880B70] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 105733 : boring_blackwell-61e2105538ba on  ns539599.ip-144-217-72.net in ha-datacenter is powered off
```
So it appears that we are missing events for some reason....which is most concerning.

**Comment by cgtexmex** [comment]
I've bumped up the estimate because I fear recreating the situation will be difficult...suggestions welcome. :)

**Comment by cgtexmex** [comment]
Same failure w/the new code -- appears that an event was missed.  Will dig into it tomorrow.

https://ci.vcna.io/vmware/vic/10686

**Comment by anchal-agrawal** [comment]
Also seen in https://ci.vcna.io/vmware/vic/10830.
