### ISSUE TITLE
11-03-Upgrade-InsecureRegistry: failing and need more information

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4999]
https://ci.vmware.run/vmware/vic/10236
https://ci.vmware.run/vmware/vic/10237
https://ci.vmware.run/vmware/vic/10238

Unfortunately, because of:
Also teardown failed:
Variable '${handle}' not found.

We don't have any logs.  From the logging that we do have it is failing here:
```
    ${rc}  ${output}=  Run And Return Rc And Output  ${docker} -H ${default_local_docker_endpoint} login --username ${registry_user} --password ${registry_password} ${registry_ip}
    Should Be Equal As Integers  ${rc}  0
    Should Contain  ${output}  Login Succeeded
```
We need to:
1. Fix the teardown so that it doesn't rely on the previous steps passing in order to get a log bundle
2. Re-run the test and repro the error
3. Fix it

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic/pull/5200
