### ISSUE TITLE
Locate VIC configuration management service

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5001]
**Story**
As a Vic developer I need a way to locate the API endpoint that provides dynamic configuration for a VCH

**Details**
As part of both content trust and vulnerability scanning the VCH needs to acquire dynamic configuration elements for registry whitelist and image blacklist respectively.
There needs to be a way for the VCH to obtain both the location of this API and appropriate certificates to verify its authenticity. If the IP of the API endpoint can be DHCP based then we need an alternative means of identification and a process by which we can map the ID to an address.

Acceptance:
* VCH can lookup the OVA VM by a tag

**Comment by hickeng** [comment]
@hmahmood I suggest you look at the VC tagging API - it's the only way I'm aware of to avoid scanning the entire inventory to find the OVA VMs. That said I'm unaware of whether it's possible to tag a VM when deploying via an OVA, which would be the other necessary piece; I'd much rather not have this as an obligatory doc only step. @frapposelli do you know if an OVA can express tags?
@emlin has already written a Go package to access the tags API for Bonneville - IIRC it's not the same API endpoint as the SDK.

**Comment by hmahmood** [comment]
@emlin can you point me to the Go package in question?

**Comment by emlin** [comment]
@hickeng it's through rest API.
@hmahmood this is the code to set tag in bonneville: 
https://enatai-gerrit.eng.vmware.com/gitweb?p=bonneville-daemon.git;a=blob;f=daemon/modules/vmware/tags.go;h=e1c2cea0603b5d714398a0bc9fb7f2a57b2f35d1;hb=refs/heads/master

**Comment by hmahmood** [comment]
@frapposelli can you comment on if tagging a VM is possible during the OVA install process?

**Comment by frapposelli** [comment]
@hmahmood definitely not possible through the OVA deployment process.

**Comment by hmahmood** [comment]
@hickeng @frapposelli @andrewtchin perhaps through a startup script then?

**Comment by hmahmood** [comment]
@emlin that link is not working.
