### ISSUE TITLE
Integrate dynamic config with whitelist check

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5003]
This is for the integration of #5001, #5002, and #3586.

This encompasses actually obtaining the dynamic config fragment from the location determined via #5001. 

Acceptance:
* at the start of docker pull, docker personality locates the OVA VM using a tag (specified during vic-machine create)
* docker personality pulls out cert/token from OVA VM guestinfo to present to configuration management endpoint
* docker personality uses token/cert to authenticate with config endpoint, which is located at the OVA's IP, and pulls config
* personality applies config

**Comment by mhagen-vmware** [comment]
closing with PR - #5574
