### ISSUE TITLE
redis-slave exits using this compose file

### ISSUE THREAD

**Issue by pescerosso** [vmware/vic#5004]
#For bug reports, please include the information below:

**VIC version:**

1.1

**Deployment details:**

vic-machine-windows.exe create --target vcsa-01a.corp.local --user "Administrator@vsphere.local" --password VMware1! --compute-resource RegionA01-COMP01 --no-tls --bridge-network containers-internal --public-network VM-RegionA01-vDS-COMP --volume-store RegionA01-ISCSI01-COMP01:default --name vchnotls

**Steps to reproduce:**

just run this cmd against VCH
COMPOSE_HTTP_TIMEOUT=200 docker-compose -f docker-guestbook.yml up -d

content of docker-guestbook.yml

version: "2"
services:
  redis-master:
    image: morellatosimone/redis:e2e
    ports:
      - "6379"
  redis-slave:
    image: morellatosimone/gb-redisslave:v1
    ports:
      - "6379"
    environment:
      - GET_HOSTS_FROM=dns
  frontend:
    image: morellatosimone/gb-frontend:v4
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns

The original compose file was this, whith images coming from the google container registry:

cat docker-guestbook.yml 

version: "2"

services:
  redis-master:
    image: gcr.io/google_containers/redis:e2e
    ports:
      - "6379"
  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    ports:
      - "6379"
    environment:
      - GET_HOSTS_FROM=dns
  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns

So I first deployed this compose file on my mac and the tag and push the images to my docker hub:

For example:

docker tag e2b3e8542af7 morellatosimone/gb-frontend:v4
docker push morellatosimone/gb-frontend:v4

**Actual behavior:**

redis-slave container exits

docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS                             NAMES
ee5ef5b08aa7        morellatosimone/redis:e2e          "redis-server /etc..."   15 hours ago        Up 15 hours                 192.168.100.109:32768->6379/tcp   root_redis-master_1
ccc0f4c3d58a        morellatosimone/gb-redisslave:v1   "/entrypoint.sh /b..."   15 hours ago        Exited (137) 12 hours ago   192.168.100.109:32769->6379/tcp   root_redis-slave_1
f8fbcf7f489a        morellatosimone/gb-frontend:v4     "apache2-foreground"     15 hours ago        Up 12 hours                 192.168.100.109:80->80/tcp        root_frontend_1

**Expected behavior:**

it should not exit

**Logs:**

[container-logs.zip](https://github.com/vmware/vic/files/974109/container-logs.zip)

**Additional details as necessary:**

**Comment by rogeliosanchez** [comment]
@jzt @sflxn @cgtexmex CC-ing you guys on this one as well since it may be related to #4985 and/or #5012.

**Comment by corrieb** [comment]
This may well be #2929. Will investigate

**Comment by corrieb** [comment]
Tested with the latest master and the containers have been up for over an hour. Will continue to monitor.

**Comment by corrieb** [comment]
This has run for 24 hours now with no problems with the latest master builds. Closing.
