### ISSUE TITLE
Docker API: Get Tarball for all Images in a respository

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#501]
Add docker get tarball operation to our engine-api server and integrate that with the interaction portlayer.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#get-a-tarball-containing-all-images-in-a-repository
https://docs.docker.com/v1.6/reference/commandline/cli/#save

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by sflxn** [comment]
Matt, this is a good operation to work on and get your feet wet with Docker, swagger, and the portlayer.

**Comment by fdawg4l** [comment]
@sflxn This isn't so straight forward.  The storage layer needs to provide the tarball and to do that, it needs to attach the vmdk.  We have stubs for this (currently only being done in a unit test), but it would need to be exposed in a consistent (wrt to locking) manner.

You may want to break this up into subtasks.
- Add function to storage port layer to attach existing images to the appliance VM via an RO non persistent image.
- Add ability to *diff* between child and parent to get a list of differing files (inodes)
- Tar result of diff into tarbal to be streamed by REST API to client.

The 2nd bullet is really not trivial.  There is a diff implementation in b'ville, but it's not the most optimal.  We have a better way in mind to handle this using change block tracking on vmdks and the `e2fs` utils to map the block to the inode.

**Comment by fdawg4l** [comment]
I would strongly consider holding off on this for a later milestone.  You can draft behind `commit` once we've implemented that since it's effectively what needs to be done here.  Cc @hickeng

**Comment by matthewavery** [comment]
This is a Tarball of the entire disk for the target image. It is not flattened so all the layers and their ID's are preserved in this tarball. We should not need to diff one layer against another, we only need to follow the historical dependencies of the target layer.

**Comment by hickeng** [comment]
@matthewavery it's the lack of flattening that's actually the problem - if it was a flattened tarball then we'd only need to attach the leaf disk and tar up it's contents. The disks are block overlays, not file overlays, so are meaningless outside of the context of that full disk chain, all the way back to the root.

**Comment by sflxn** [comment]
@matthewavery I wasn't aware of the actual intricacies of this operation.  Even our original estimates were off.  Let's find an issue with a smoother path to ramping you up on these components.

**Comment by zjs** [comment]
Closing as this is unlikely to be addressed, except as a part of a comprehensive project (in which case a new issue can be created).
