### ISSUE TITLE
VIC Engine files not upgraded when upgrading VIC appliance from 1.1.0 to 1.1.1

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#5013]
**VIC version:**

vic-v1.1.1-rc1-a1f00c54.ova

**Deployment details:**

Deployed 1.1.0 then upgraded it to 1.1.1.

**Steps to reproduce:**

1. Deploy the 1.1.0 GA appliance.
2. Do some stuff with 1.1.0, e.g. create some projects/users in Registry.
3. Deploy the 1.1.1 appliance, and attach the data disk from the 1.1.0 appliance to it (standard upgrade procedure)
4. Log in to Registry and go to admin > About
4. Go to https://_ova_address_:9443

**Actual behavior:**

- The console for the new appliance shows version 1.1.1
- Registry shows version 1.1.1 and includes the projects/users from 1.1.0 (successful upgrade).
- All files on  https://_ova_address_:9443 are version 1.1.0

**Expected behavior:**

All files on  https://_ova_address_:9443 should be version 1.1.1

**Additional details as necessary:**

If you deploy the 1.1.1 OVA without upgrading from 1.1.0, the VIC Engine files are at the correct version.

**Comment by stuclem** [comment]
Upgraded 1.1.1 appliance:

![wrongversion](https://cloud.githubusercontent.com/assets/16718369/25698899/1dbd1918-30c1-11e7-979a-481918134236.png)

Freshly installed 1.1.1 appliance: 

![rightversion](https://cloud.githubusercontent.com/assets/16718369/25698894/1744c310-30c1-11e7-97ea-5fb97be17bf0.png)

**Comment by frapposelli** [comment]
This requires moving the vic engine artifacts into the system disk and out of the persistent disk.

**Comment by mdubya66** [comment]
Required for 1.1.1
