### ISSUE TITLE
Additional logging in vSphere Session

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#502]
Provide additional logging in the vSphere session pkg.  Specifically supply additional logging during the Populate method that actively interrogates vSphere and cache's data.

Related to #497

**Comment by cgtexmex** [comment]
@dougm I've added additional logging in my fork:

https://github.com/cgtexmex/vic/blob/logme/pkg/vsphere/session/session.go

One thing that might be good to implement after initial vsphere login would be an environment interrogation and log that info.  The items to log would need to be identified and it would probably make sense to do that in a new issue, but could be useful.

**Comment by dougm** [comment]
Let's also add some INFO logging that includes some of the About info, so we can see if we're talking to ESX or VC and version/build.
