### ISSUE TITLE
Generate certificates for VCH

### ISSUE THREAD

**Issue by emlin** [vmware/vic#503]
This is to generate SSL certificate keys for VCH during installation, and then set the certificate into VM guest info.
This function exists in installer.sh

**Comment by hickeng** [comment]
There is a pretty good example of how to use the Go certificate packages here:
https://www.socketloop.com/tutorials/golang-create-x509-certificate-private-and-public-keys

That generates you the three necessary elements:
https://www.socketloop.com/tutorials/golang-create-x509-certificate-private-and-public-keys

**Comment by gigawhitlocks** [comment]
@hickeng your second copy/paste appears to have failed. Also I am reticent to turn off my ad-blocker in order to view that link.

**Comment by dougm** [comment]
Plenty of examples out there and the tests for the go crypto packages are helpful too.  Here's an example from govmomi: https://github.com/vmware/govmomi/blob/master/govc/extension/setcert.go#L79

**Comment by gigawhitlocks** [comment]
Initial implementation is here: https://github.com/emlin/vic/pull/1 as a pull request against @emlin 's repository & branch. Comments welcome.
