### ISSUE TITLE
HTML5 Plugin displays wrong port number when using --no-tls

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic#5036]
When creating a VCH with the --no-tls option, HTML5 plugin displays wrong port number (2376 instead of 2375). I attached a screenshot.

May  5 2017 13:06:57.777Z INFO  ### Installing VCH ####
May  5 2017 13:06:57.778Z INFO  vSphere password for administrator@corp.local:
May  5 2017 13:07:01.063Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
May  5 2017 13:07:01.063Z WARN  Configuring without TLS - all communications will be insecure
May  5 2017 13:07:01.064Z INFO  Loaded registry CA from /etc/docker/certs.d/192.168.100.104/ca.crt
May  5 2017 13:07:01.492Z INFO  Validating supplied configuration
May  5 2017 13:07:02.017Z INFO  vDS configuration OK on "Bridge01-RegionA01-vDS-COMP"
May  5 2017 13:07:02.118Z INFO  Firewall status: ENABLED on "/RegionA01/host/RegionA01-COMP01/esx-01a.corp.local"
May  5 2017 13:07:02.184Z INFO  Firewall status: ENABLED on "/RegionA01/host/RegionA01-COMP01/esx-02a.corp.local"
May  5 2017 13:07:02.250Z INFO  Firewall status: ENABLED on "/RegionA01/host/RegionA01-COMP01/esx-03a.corp.local"
May  5 2017 13:07:02.272Z INFO  Firewall configuration OK on hosts:
May  5 2017 13:07:02.272Z INFO          "/RegionA01/host/RegionA01-COMP01/esx-01a.corp.local"
May  5 2017 13:07:02.272Z INFO          "/RegionA01/host/RegionA01-COMP01/esx-02a.corp.local"
May  5 2017 13:07:02.273Z INFO          "/RegionA01/host/RegionA01-COMP01/esx-03a.corp.local"
May  5 2017 13:07:02.783Z INFO  License check OK on hosts:
May  5 2017 13:07:02.783Z INFO    "/RegionA01/host/RegionA01-COMP01/esx-01a.corp.local"
May  5 2017 13:07:02.790Z INFO    "/RegionA01/host/RegionA01-COMP01/esx-02a.corp.local"
May  5 2017 13:07:02.790Z INFO    "/RegionA01/host/RegionA01-COMP01/esx-03a.corp.local"
May  5 2017 13:07:02.801Z INFO  DRS check OK on:
May  5 2017 13:07:02.802Z INFO    "/RegionA01/host/RegionA01-COMP01"
May  5 2017 13:07:02.913Z INFO
May  5 2017 13:07:03.164Z INFO  Creating virtual app "virtual-container-host"
May  5 2017 13:07:03.277Z INFO  Creating directory [RegionA01-ISCSI01-COMP01] VIC
May  5 2017 13:07:03.323Z INFO  Datastore path is [RegionA01-ISCSI01-COMP01] VIC
May  5 2017 13:07:03.323Z INFO  Creating appliance on target
May  5 2017 13:07:03.406Z INFO  Network role "management" is sharing NIC with "client"
May  5 2017 13:07:03.445Z INFO  Network role "public" is sharing NIC with "client"
May  5 2017 13:07:06.264Z INFO  Uploading images for container
May  5 2017 13:07:06.265Z INFO          "bootstrap.iso"
May  5 2017 13:07:06.267Z INFO          "appliance.iso"
May  5 2017 13:07:24.474Z INFO  Waiting for IP information
May  5 2017 13:07:53.688Z INFO  Waiting for major appliance components to launch
May  5 2017 13:07:53.843Z INFO  Obtained IP address for client interface: "192.168.100.106"
May  5 2017 13:07:53.843Z INFO  Checking VCH connectivity with vSphere target
May  5 2017 13:07:54.127Z INFO  vSphere API Test: https://vcsa-01a.corp.local vSphere API target responds as expected
May  5 2017 13:08:10.187Z INFO  Initialization of appliance successful
May  5 2017 13:08:10.188Z INFO
May  5 2017 13:08:10.188Z INFO  VCH Admin Portal:
May  5 2017 13:08:10.189Z INFO  https://192.168.100.106:2378
May  5 2017 13:08:10.189Z INFO
May  5 2017 13:08:10.189Z INFO  Published ports can be reached at:
May  5 2017 13:08:10.190Z INFO  192.168.100.106
May  5 2017 13:08:10.190Z INFO
May  5 2017 13:08:10.191Z INFO  Docker environment variables:
May  5 2017 13:08:10.192Z INFO  DOCKER_HOST=192.168.100.106:2375
May  5 2017 13:08:10.192Z INFO
May  5 2017 13:08:10.193Z INFO  Connect to docker:
May  5 2017 13:08:10.193Z INFO  docker -H 192.168.100.106:2375 info
May  5 2017 13:08:10.193Z INFO  Installer completed successfully

![screen shot 2017-05-05 at 09 08 52](https://cloud.githubusercontent.com/assets/8586715/25746781/f156b746-3172-11e7-8788-ee1c7aaa78a1.png)

**VIC version:**

1.1.0

**Deployment details:**

vic-machine-linux create --target vcsa-01a.corp.local \
--user administrator@corp.local \
--compute-resource RegionA01-COMP01 \
--image-store RegionA01-ISCSI01-COMP01 \
--volume-store RegionA01-ISCSI01-COMP01:default \
--public-network VM-RegionA01-vDS-COMP \
--bridge-network Bridge01-RegionA01-vDS-COMP \
--name virtual-container-host \
--registry-ca=/etc/docker/certs.d/192.168.100.104/ca.crt \
--no-tls

**Steps to reproduce:**

**Actual behavior:**

HTML5 plugin displays DOCKER_HOST=192.168.100.106:2376

**Expected behavior:**

HTML5 plugin should display DOCKER_HOST=192.168.100.106:2375

**Logs:**

**Additional details as necessary:**

I am able to reproduce this in my lab if needed.

**Comment by rogeliosanchez** [comment]
@jooskim Pinging for triage.

**Comment by jooskim** [comment]
Acknowledged. Will work on this and #5022 as top priority
