### ISSUE TITLE
Deploy Vsphere 6.5 on OVH

### ISSUE THREAD

**Issue by jakedsouza** [vmware/vic#5048]
**User Statement:**

As a vic engineer, I want to ensure my changes are tested on vSphere 6.5 

**Details:**
Deploy a vSphere 6.5 with a vSan cluster on OVH to run tests 
 
**Acceptance Criteria:**
1.  Deployed vSphere 6.5 with a vSan cluster with a valid domain and a test admin user
2. Accessible via private lan network on OVH

**Comment by kreamyx** [comment]
Done! kov-vsphere.ci.drone.local
