### ISSUE TITLE
Investigate kubernetes e2e testing

### ISSUE THREAD

**Issue by jakedsouza** [vmware/vic#5049]
#For stories, please include the information below:

**User Statement:**

As a vic engineer, I want to ensure that my k8s deployment is tested against kubernetes e2e tests 

**Details:**
1. Investigate k8s e2e tests 
2. Integrate running k8s e2e tests with drone 
3. Initially the build should not fail for failing e2e tests, but should log all failures 
4. Cleanup after a test run 

**Acceptance Criteria:**
1. For each PR, k8s e2e tests should be run on a deployed cluster 
2. The tests should not fail the build but should log all errors 
3. The test should cleanup after its self

**Comment by kreamyx** [comment]
@jakedsouza Should this wait until we have a kovd implementation that actually creates a kubernetes cluster?

**Comment by jakedsouza** [comment]
Issue moved to [vmware/kov #65](https://github.com/vmware/kov/issues/65) via [**ZenHub**](https://www.zenhub.com/)
