### ISSUE TITLE
switch build to use photon as base

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#506]
There have been some issues with rpmdb inconsistency in the final appliance that prevent tdnf from working correctly. This is primarily an issue for dev as there's no intent to have a package manager in the appliance for release.
A recent fix and switching the build to use vmware/photon as a base should address this problem.

The way I'd like to do this is add a check for tdnf, fall back on yum, and if neither are present use apt-get to acquire yum, to acquire tdnf. This should let devs with most linux variants build un-sandboxed if necessary and adds negligible complexity.

Drone will be switched to use vmware/photon for the ISO packaging portions of the build.
Until the vmware/photon image has been updated the first step must be `tdnf upgrade -y tdnf`

Example use: https://github.com/vmware/photon/blob/615f2667a403bad1d17f8b6b60742ea571b678e8/support/dockerfiles/photon/make-docker-image.sh

**Comment by hickeng** [comment]
@matthewavery sorry to throw you under the bus again - this is not urgent, but should be done in the next couple of weeks as being able to deploy packages to the appliance will become more essential for debugging as we progress.

**Comment by ppadmavilasom** [comment]
One way is to solve this as follows - assuming you are looking to create rootfs with some packages installed in a chroot
Use a photon-build docker image which can be built temporarily 
For eg: 
https://github.com/vmware/photon/blob/dev/support/dockerfiles/photon/Dockerfile 
and use sudo docker build --no-cache --tag photon-build <path to the above dockerfile>
then use tdnf from the above docker image to install pkgs to a chroot and create rootfs 
For eg:
https://github.com/vmware/photon/blob/dev/support/dockerfiles/photon/make-docker-image.sh

**Comment by matthewavery** [comment]
I will be taking a look at this now. As I do not think it will take long.

**Comment by matthewavery** [comment]
I took a look at this late last week, I plan to try and wrap it up this week. I may need some further investigation. It looks like tdnf installs go1.4.2 so I will also need to grab the 1.6.2 version of go(and setup the environment) after detecting that we are on photon. We will also need more packages suchas as `make` but all of these can be installed on a conditional bases that we are in a photon env.

**Comment by hickeng** [comment]
@matthewavery Is this something we should get ken to look at? I don't know his githib id.

**Comment by matthewavery** [comment]
@hickeng How are we feeling about this issue? I do not think this is an issue anymore tbh. I am advocating that we close this issue, but I will wait to see what you think.

**Comment by hickeng** [comment]
The only reason to do this would be if tdnf could do unprivileged install to a specific install root. It cannot at this time.
Closing.
