### ISSUE TITLE
VCHs and Containers created with --use-rp are not reflected in VIC section properly

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#5063]
**Details:**
In the very first page of the vSphere Integrated Containers section in the H5C, the numbers of VCHs and Containers are displayed for vApp-based VCH appliances and Container VMs, but not for resource pool based ones. This bug impacts feature PRs such as the Virtual Container Host section.

For example in this case, there should be 6 VCHs reported
![image](https://cloud.githubusercontent.com/assets/3834071/25870055/52327034-34c8-11e7-8597-8792e10704d7.png)

**Expected behavior:**
In the VIC section there should be 6 VCHs

**Actual behavior:**
Only 5 VCHs are reported
![image](https://cloud.githubusercontent.com/assets/3834071/25870108/86ba989a-34c8-11e7-9ce1-e99892abb873.png)

**Acceptance Criteria:**
No matter what resource pool type the VCH appliance is based on vic-service should correctly collect VCH and Container VMs information from vSphere.

**Comment by jooskim** [comment]
https://github.com/vmware/vic/tree/master/doc/design/telemetry for reference.

**Comment by corrieb** [comment]
@jooskim Do you think we'll get this in for 1.2?

**Comment by jooskim** [comment]
@corrieb I forgot to track this issue, but it's already addressed. I'll close it now.
