### ISSUE TITLE
create a mechanism to generate a bootstrap token file

### ISSUE THREAD

**Issue by casualjim** [vmware/vic#5064]
The output is a csv file, but instead of urandom it should make use of securerandom and not be a bash script.

```shell
BOOTSTRAP_TOKEN=$(head -c 16 /dev/urandom | od -An -t x | tr -d ' ')
cat > token.csv <<EOF
${BOOTSTRAP_TOKEN},kubelet-bootstrap,10001,"system:kubelet-bootstrap"
EOF
```

This file needs to make it into /var/lib/kubernetes on the kubelet and should be included in the archive from #5062

**Comment by maplain** [comment]
Issue moved to [vmware/kov #73](https://github.com/vmware/kov/issues/73) via [**ZenHub**](https://www.zenhub.com/)
