### ISSUE TITLE
vic-machine create container-network validation

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5066]
```
--container-network value, --cn value            vSphere network list that containers can use directly with labels, e.g. vsphere-net:backend. Defaults to DCHP - see advanced help (-x).
```

Providing `--container-network port_group` without name is not caught during validation (should be `--container-network port_group:network_name`)

Acceptance criteria:
- [ ] Fail install when user fails to provide network name for `--container-network`

**Comment by andrewtchin** [comment]
@stuclem this probably could use a warning in the docs

**Comment by stuclem** [comment]
Thanks @andrewtchin, I just spotted this. Created https://github.com/vmware/vic-product/issues/247, so removing kind/user-doc from this issue.
