### ISSUE TITLE
vic-machine create container-network-ip help is wrong

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5067]
```
--container-network-ip-range value, --cnr value  IP range for the container network in CONTAINER-NETWORK:IP-RANGE format, e.g. vsphere-net:172.16.0.0/24, vsphere-net:172.16.0.10-20.
```

Should be 
```
--container-network-ip-range value, --cnr value  IP range for the container network in CONTAINER-NETWORK:IP-RANGE format, e.g. vsphere-net:172.16.0.0/24, vsphere-net:172.16.0.10-172.16.0.20
```

Acceptance criteria:

- [ ] Update help

**Comment by stuclem** [comment]
Since I sometimes use `vic-machine help` when writing the user docs, I just checked the doc at https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_options.html#adv-container-net and I think that it reflects the correct version.
