### ISSUE TITLE
Research Spike: Decide on Overlay Networking Solution for Kubernetes on Vsphere

### ISSUE THREAD

**Issue by amandafeng001** [vmware/vic#5068]
**User Statement:**

As a customer, I need my pods across my K8S nodes to communicate. 

**Acceptance Criteria:**
Comparison of the popular pod networking add-ons: Flannel, Weave, Calico...etc,
decide on which one we will use.

**Comment by rogeliosanchez** [comment]
@amandafeng001, can you move this over to "backlog" if it is ready to be moved?

**Comment by amandafeng001** [comment]
We will use Weave Net which provides pod networking and network policy support out of box. Related spec has committed.
