### ISSUE TITLE
Research Spike: Network Policy Support on Kubernetes on Vsphere

### ISSUE THREAD

**Issue by amandafeng001** [vmware/vic#5069]
**User Statement:**

As a user, I want to apply network policies to secure my pods.

**Acceptance Criteria:**
Comparison of different network policy support solutions for K8s: Calico, Weave Net.
Verify if Calico can work with Flannel or Weave Net.

**Comment by rogeliosanchez** [comment]
@amandafeng001, can you move this over to "backlog" if it is ready to be moved?

**Comment by amandafeng001** [comment]
We will use Weave Net which provides pod networking and network policy support out of box. Related spec has committed.
