### ISSUE TITLE
Firewall rules are too agressive

### ISSUE THREAD

**Issue by casualjim** [vmware/vic#5071]
#For bug reports, please include the information below:

**VIC version:**

master

**Deployment details:**

```shell
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
datastore="${GOVC_DATASTORE}/${1-kov}"
publicnet="${PUBLIC_NETWORK-PublicNetwork}"
internalnet="${PRIVATE_NETWORK-InternalNetwork}"
fingerprint="$("$dir/get-fingerprint.sh" "$GOVC_URL" | cut -d '=' -f2)"

"$dir/../.bin/vic-machine-$(uname | tr '[:upper:]' '[:lower:]')" create \
  --name "${1-kov}" \
  --target "$GOVC_URL" \
  --thumbprint "$fingerprint" \
  --user "$GOVC_USERNAME" \
  --image-store "$datastore" \
  --password "$GOVC_PASSWORD" \
  --container-network "$publicnet" \
  --bridge-network "$internalnet" \
  --public-network "$publicnet" \
  --compute-resource "$GOVC_CLUSTER" \
  --timeout "10m" \
  --volume-store "${datastore}:default" \
  --tls-cname "kov-vch" \
  --debug 0 \
  --force
```

**Steps to reproduce:**

Deploy a container with a service running that listens on a port

curl the service on the port
exec into the container and curl it on loopback

**Actual behavior:**

the curl never succeeds

**Expected behavior:**

the curl succeeds and iptables shows an entry that allows all traffic on loopback as first entry

**Comment by hickeng** [comment]
@casualjim It's unclear how you were running the container. Am I correct in assuming that it was on a container-network? If so you need to provide a declaration that a port is available, e.g. `-p 8080`, the same as with NAT. This is to avoid accidentally exposing services to anything on the open container-network in the case that you're only wanting to consume via that network and not publish.

We don't yet support `-P`/`EXPOSE` #3000

**Comment by corrieb** [comment]
@casualjim Ivan, we will assume this was due to the change that George is referring to above where Container network ports need to be explicitly opened. Please re-open if this is not the case.
