### ISSUE TITLE
kov cli crashed because of 'function "appendIfNotPresent" not defined'

### ISSUE THREAD

**Issue by maplain** [vmware/vic#5076]
➜  kov bin/kov-darwin-amd64/kov
panic: template: top:2: function "appendIfNotPresent" not defined

goroutine 1 [running]:
text/template.Must(0x0, 0x17b1f40, 0xc4202c9aa0, 0x0)
    /usr/local/go/src/text/template/helper.go:23 +0x54
github.com/supervised-io/kov/vendor/github.com/spf13/cobra.tmpl(0x17b2c40, 0xc42000c020, 0x1574f69, 0x3d2, 0x1551e60, 0xc420418480, 0x14a0ca0, 0xc4202c98dd)
    /go/src/github.com/supervised-io/kov/vendor/github.com/spf13/cobra/cobra.go:75 +0xc1
github.com/supervised-io/kov/vendor/github.com/spf13/cobra.(*Command).UsageFunc.func1(0xc420418480, 0x1577ba0, 0xc4204e3c38)
    /go/src/github.com/supervised-io/kov/vendor/github.com/spf13/cobra/command.go:226 +0xad
github.com/supervised-io/kov/vendor/github.com/spf13/cobra.(*Command).Usage(0xc420418480, 0x0, 0x0)
    /go/src/github.com/supervised-io/kov/vendor/github.com/spf13/cobra/command.go:238 +0x3e
main.(*Cli).usage(0xc42015ab40, 0x1554c3c, 0x4)
    /go/src/github.com/supervised-io/kov/cmd/kov/cli.go:145 +0x33
main.(*Cli).usageRunner.func1(0xc42015ab40, 0x14a0ca0, 0x0)
    /go/src/github.com/supervised-io/kov/cmd/kov/cli.go:182 +0x2b
main.(*Cli).runner.func1(0xc420418480, 0x18165c8, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/supervised-io/kov/cmd/kov/cli.go:156 +0x84
github.com/supervised-io/kov/vendor/github.com/spf13/cobra.(*Command).execute(0xc420418480, 0xc42000e3b0, 0x0, 0x0, 0xc420418480, 0xc42000e3b0)
    /go/src/github.com/supervised-io/kov/vendor/github.com/spf13/cobra/command.go:622 +0x3f8
github.com/supervised-io/kov/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420418480, 0x15221c0, 0x14a6201, 0xc42015ac60)
    /go/src/github.com/supervised-io/kov/vendor/github.com/spf13/cobra/command.go:701 +0x339
github.com/supervised-io/kov/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420418480, 0x1000, 0x1000)
    /go/src/github.com/supervised-io/kov/vendor/github.com/spf13/cobra/command.go:660 +0x2b
main.(*Cli).Run(0xc42015ab40)
    /go/src/github.com/supervised-io/kov/cmd/kov/cli.go:137 +0xae
main.main()
    /go/src/github.com/supervised-io/kov/cmd/kov/main.go:8 +0x2f

builds: https://storage.googleapis.com/kov-builds/kov_ca28139_ca28139.tar.gz

**Comment by rogeliosanchez** [comment]
@maplain, can you move this over to "backlog" if it is ready to be moved?

**Comment by jakedsouza** [comment]
This is fixed on master. Closing
