### ISSUE TITLE
Unable to use datastore after adding storeage

### ISSUE THREAD

**Issue by douggie** [vmware/vic#5078]
#For stories, please include the information below:

**User Statement:**

As a VIC administrator I would like to be able to add storage to the default data store assigned to a given VIC without needing to restart or re deploy the VCH or containers.

**Details:**

**Acceptance Criteria:**
create data store
create vch
create volumes in datastore
create containers with new volumes
add storage to data store
create new volumes in expanded data store

#For bug reports, please include the information below:

**VIC version:**

x.y.z / master / commit ID

**Deployment details:**

 ./vic-machine-linux  create --target [] --user [user] --password [pass] --no-tlsverify --force --appliance-memory=1048 --volume-store Default:default --public-network Labs-Public-Network --public-network-gateway 10.128.204.30/27  --public-network-ip 10.128.204.26  --container-network Labs-Network:Labs-Network  --container-network-gateway Labs-Network:10.128.205.254/24  --container-network-ip-range Labs-Network:10.128.205.90-250  --container-network-dns Labs-Network:8.8.8.8  --bridge-network Labs-Bridge  --compute-resource Lab-iommdh  --name labs.org  --image-store Labs  --registry-ca=/vagrant/vic/ca.crt  --base-image-size 0GB --debug 1

create new container
docker -H  [host]:2376 --tls  run -d --net=Labs-Network --ip=10.128.205.119 images.ducotech.io/dataplatform/sshd
**Steps to reproduce:**

**Actual behavior:**
Once the datastore has been expanded you cannot create new containers.
Log attached.

**Expected behavior:**
Update data store and continue to create new containers
**Logs:**

**Additional details as necessary:**

**Comment by douggie** [comment]
[vhc.txt](https://github.com/vmware/vic/files/989637/vhc.txt)

**Comment by rogeliosanchez** [comment]
CC-ing @matthewavery @emlin for triaging/extra info.

**Comment by fdawg4l** [comment]
```time=2017-05-10T11:45:46.947138934Z level=info msg=op=244.43 (delta:1.247508355s): Create/attach vmdk [DucoLabs] dmz.ducotech.io/VIC/421363ea-fc33-952a-16c0-b8917dfc25ca/images/c1f289015adc769ea22989117661dda573844e8d60712df04
6c83232a5248dd0/c1f289015adc769ea22989117661dda573844e8d60712df046c83232a5248dd0.vmdk from parent [DucoLabs] dmz.ducotech.io/VIC/421363ea-fc33-952a-16c0-b8917dfc25ca/images/scratch/scratch.vmdk 
time=2017-05-10T11:45:46.960769867Z level=debug msg=op=244.43 (delta:1.261138641s): Attach reconfigure task=Task:task-27963 
time="2017-05-10T11:45:47Z" level=debug msg="unexpected fault on task retry : &types.InvalidDeviceSpec{InvalidVmConfig:types.InvalidVmConfig{VmConfigFault:types.VmConfigFault{VimFault:types.VimFault{MethodFault:types.MethodFau
lt{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, Property:\"virtualDeviceSpec.device.backing.parent.fileName\"}, DeviceIndex:0}```

@douggie Can you grab a support bundle from the web ui and attach it here?

**Comment by fdawg4l** [comment]
Mentioned on slack, but echo'ing here.  

```--base-image-size 0GB``` isn't supported.  Was this intentional?

**Comment by fdawg4l** [comment]
The `0` base image size looks like the issue with the error in the log.  Can you retry with a size greater than 0?  Omitting that flag defaults to 8GB and should get deal with the error mentioned at least.

**Comment by sgairo** [comment]
Are you able to reproduce this error when base image size is not 0?

**Comment by sgairo** [comment]
@stuclem Is it possible to document that we do not support a 0 base image size? I didn't see base image size in the VCH inputs documentation yet, thanks :)

**Comment by fdawg4l** [comment]
@sgairo Is it possible to add a change to the installer that doesn't allow base image sizes of less than some same default? I think 1GB is a good start. Our disks are thin so the images only occupy as much data as is written to them. So arbitrarily large base sizes should be fine.

**Comment by sgairo** [comment]
@fdawg4l yes, I created an issue to do so. #5193
