### ISSUE TITLE
get kov CLI use keypair generated in ova to talk to kovd

### ISSUE THREAD

**Issue by maplain** [vmware/vic#5088]
Get kov CLI to use keypair generated here https://github.com/vmware/vic/issues/4930.

Acceptance Criteria
CLI uses whatever keypair provided by fileserver(admiral in future) to talk to kovd

**Comment by lubronzhan** [comment]
Issue moved to [vmware/kov #74](https://github.com/vmware/kov/issues/74) via [**ZenHub**](https://www.zenhub.com/)
