### ISSUE TITLE
Creation of VCH fails with "Could not run VCH vSphere API target check due to ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).  but the VCH may still function normally"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5100]
**User Statement:**

Creation of VCH fails with "Could not run VCH vSphere API target check due to ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).  but the VCH may still function normally"

**Details:**
Here is my setup:

VC , VCH and client are all in different subnets
I updated /etc/resolv.conf with the DNS entries for all three setups.

nslookup from client VM to VCH, VC IP works fine.

VCH creation fails with below commands with and without dns-server:

./vic-machine-linux create --force -t administrator@vsphere.local:'Admin!23'@w3-stras-db06.eng.vmware.com/Datacenter -r Cluster/Resources -i Datastore-d2616 -b DPortGroup -n U-VIC-0001  --no-tlsverify --timeout 30m --public-network-ip 10.197.37.90/23 --public-network-gateway 10.197.37.253

./vic-machine-linux create --force -t administrator@vsphere.local:'Admin!23'@w3-stras-db06.eng.vmware.com/Datacenter -r Cluster/Resources -i Datastore-d2616 -b DPortGroup -n U-VIC-001  --no-tlsverify --timeout 30m --public-network-ip 10.197.37.^C/23 --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21

/etc/resolv..conf snippet
nameserver 10.142.7.21
nameserver 10.132.71.1
nameserver 10.146.7.1
search eng.vmware.com

**Acceptance Criteria:**
VCH creation should have worked as all Ips are resolvable through FQDN.

Live setup can be provided/accessed.

**Comment by mdubya66** [comment]
Is this 1.1.1 @lgayatri?

**Comment by emlin** [comment]
@lgayatri is the command failed for that problem, or just printed out the error message, and still moving forward?
There is possibility that vic-machine is conflict with vch initialization, but vch initialization will continue or retry for that problem, so in theory, even you get this error, vch should work without any problem.
You might run vic-machine inspect to get back VCH information, and then the docker command to see if vch actually works or not.

**Comment by hmahmood** [comment]
@lgayatri can you resolve the fqdn of the VC from the VCH?

**Comment by hmahmood** [comment]
#3417 #3724 look similar

**Comment by lgayatri** [comment]
@mdubya66 Yes, this was on 1.1.1 
@emlin , the command just waits to hit the timeout specified and bails out
@hamhmood, I filed a ticket for the same. 
Will update status in a day.

**Comment by mdubya66** [comment]
System/Scale test blocker, marking high priority

**Comment by dougm** [comment]
Fixed in #5348

**Comment by lgayatri** [comment]
Did not see this issue after the fix on build vic-v1.1.1-11340-4029cbe6.ova.
