### ISSUE TITLE
Longevity Tests - Creating an image failed: [POST /storage/{store_name}][500] WriteImage default

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#5103]
`May 10 2017 21:09:42.914Z DEBUG Creating an image failed: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:Post https://blinky.eng.vmware.com/sdk: dial tcp: lookup blinky.eng.vmware.com on 10.118.81.1:53: read udp 10.17.109.7:42709->10.118.81.1:53: i/o timeout}`

**This error is fatal and is blocking longevity testing.**

**Comment by rogeliosanchez** [comment]
[container-logs.zip](https://github.com/vmware/vic/files/997457/container-logs.zip)

**Comment by sgairo** [comment]
Appears portlayer can't reach the DNS server

**Comment by mhagen-vmware** [comment]
Running longevity on the newly installed cluster.  Will close this towards the end of the sprint if we don't see this issue again.

**Comment by mhagen-vmware** [comment]
Haven't seen this in 3 different runs of longevity, closing now.  Please reopen if we see this again.
