### ISSUE TITLE
Investigate using specific ethernet interface for pod overlay for kov

### ISSUE THREAD

**Issue by amandafeng001** [vmware/vic#5113]
**User Statement:**

As a user, I would like to have another port for pod overlay networking, so that my data plane and management plane traffic can be separated.

**Acceptance Criteria:**
Find the way to specify a port to set up Weave Net on worker nodes.

**Comment by amandafeng001** [comment]
Issue moved to [vmware/kov #70](https://github.com/vmware/kov/issues/70) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kreamyx** [comment]
Issue moved to [vmware/kov #72](https://github.com/vmware/kov/issues/72) via [**ZenHub**](https://www.zenhub.com/)
