### ISSUE TITLE
Remove the --rp setting from vic-machine

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic#5117]
The vApp in itself is backed by a resource pool and the --rp seems redundant. This came up in a UX review and the ask is to remove this option from the CLI.

**Comment by emlin** [comment]
@karthik-narayan I didn't see a --rp option in vic-machine create option, do you mean `--use-rp` option?

**Comment by karthik-narayan** [comment]
That's what I meant. Sorry.

**Comment by emlin** [comment]
@karthik-narayan the --use-rp is using resource pool instead of vApp to create VCH. That's one experimental option for us, to see if user actually prefer not to use vApp in vSphere.
And this option is in advanced help already. Do you think we should remove this option, and keep the vApp behavior?

**Comment by hickeng** [comment]
Turns out this is needed and works around concurrency issues in Workflow Manager resulting in vpxd backtraces when powering on large numbers of VMs concurrently in a vApp. #6272 is open to confirm/add full support for that option in vic-machine.
