### ISSUE TITLE
Investigate how to make the docker-engine-server to be compliant with Docker 1.11

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#512]
Figure out how to incorporate containerd into VIC.

**Comment by hickeng** [comment]
@sflxn I'm going to move this to icebox - doesn't mean we don't keep noting possible approaches in here, but I don't think we're going to have containerd integration in 1.0RC timeframe.

**Comment by mdubya66** [comment]
Is this still relevant? @sflxn

**Comment by hickeng** [comment]
We're still working on containerd, but this issue doesn't track any of those efforts. Closing as we're now 1.13 client compatible.
