### ISSUE TITLE
Investigate how to connect another VM node to pod overlay network of kov

### ISSUE THREAD

**Issue by amandafeng001** [vmware/vic#5121]
**User Statement:**

To expose a service or a pod to the internet, we will connect another VM node to the pod overlay network which provides NAT and routing.

**Acceptance Criteria:**
A document or script on how to connect another VM node to pod network of kov.

**Comment by kreamyx** [comment]
Issue moved to [vmware/kov #69](https://github.com/vmware/kov/issues/69) via [**ZenHub**](https://www.zenhub.com/)
