### ISSUE TITLE
Safe Deletion of VCH and re-use of volumes

### ISSUE THREAD

**Issue by douggie** [vmware/vic#5124]
User statement: As a customer of VIC, I would like to be able to delete a VCH, create a new VCH and use existing volumes that were used in the old VCH in the new VCH.

Details: There are times when a VCH might be un-responsive on unable to mount volumes, in such situations it would be handy to remove the VCH and recreate but without losing any data used by the containers by being able to re-use the original volumes.

Actual behaviours: When trying to remove a VCH from the command line the following error occurs:
ERRO[2017-05-16T10:21:07Z] Failed to browse folder "[DucoLabs] man.ducotech.io/kvStores": Post https://10.2.2.2/sdk: net/http: request canceled while waiting for connection
Post https://10.2.2.2/sdk: net/http: request canceled while waiting for connection
Post https://10.2.2.2/sdk: net/http: request canceled while waiting for connection 

Expected behavior:
Ability to delete VCH and re-use the disks

Logs:
Vic-machine log attached.

**Comment by douggie** [comment]
[vic-machinelog.txt](https://github.com/vmware/vic/files/1004000/vic-machinelog.txt)

**Comment by sgairo** [comment]
Could you attach vic-machine log, please?

**Comment by matthewavery** [comment]
@douggie As long as you are not doing a `vic-machine-linux --force` the volumestores should not get cleaned up. This means that any volumes you make should still exist and will still have the same data as before. `--force` on vic-machine triggers a cleanup of volumes and is required to explicitly remove volume stores. If you have found that this is not working for you, I would love to see the logs for both the VCH and the vic-machine command used.

**Comment by karthik-narayan** [comment]
@douggie Checking to see if you have any updates for us

**Comment by matthewavery** [comment]
Closing this as resolved. This functionality exists, and we have not seen any problems with it in awhile.
