### ISSUE TITLE
Document support for Dockerfile commands

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#5144]
**User Statement:**

As a VIC user / docker developer, I need to understand which Dockerfile commands work with VIC and which are partially supported or not supported. I want to understand the impact of the commands that are not yet supported and whether there are any workarounds. 

**Details:**

We know that there are some Dockerfile commands that are not yet supported, USER being an example (although that's now fixed) #4172. We need to make sure that the customer understands the impact, particularly if there are security implications.

It's important to distinguish between Dockerfile syntax that is specific to the build process (Eg. FROM) and those that create metadata in the Image and correspond to commands when the image is run (Eg. VOLUME). We don't need to list the former.

**Acceptance Criteria:**

Docs are updated appropriately

**Comment by stuclem** [comment]
Moving this one to the `vic-product` repo.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #236](https://github.com/vmware/vic-product/issues/236) via [**ZenHub**](https://www.zenhub.com/)
