### ISSUE TITLE
Analyze API dependency for each page

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#5147]
**User Statement:**
As a UI developer I need to figure out first which APIs the VCH CLI creation wizard will rely on. This task eventually involves having conversations with the H5C team to discuss implementation details.

**Acceptance Criteria:**
1. List any necessary APIs required per page
2. Get details on how to use them
3. Check with H5C if use of H5C API endpoints is plausible

**Comment by jzt** [comment]
@jooskim can you add an estimate & labels to this and move it to the backlog?

**Comment by jooskim** [comment]
https://confluence.eng.vmware.com/display/CPBU/API+dependency+analysis+for+VCH+CLI+creation+wizard
