### ISSUE TITLE
VCH lifecycle UI - Create

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#5150]
**User Statement:**
As a UI engineer, I would like to ensure every critical step (be it a research spike, dev or test) for the VCH CLI creation wizard is captured and tracked. The mockups are continuously updated at this moment but can be accessed [here](https://vmware.invisionapp.com/share/P9A37332G#/screens/231553267).

**Acceptance Criteria:**
1. By going through the wizard steps, users can generate a `vic-machine create` command easily that they can copy and paste to deploy a VCH appliance.
2. The wizard should be accessible from 1) the vSphere Integrated Containers section and 2) Cluster action context menu in the Hosts and Clusters view.

**Comment by jzt** [comment]
@jooskim can you add an estimate to this and move it to the backlog?

**Comment by jooskim** [comment]
@jzt we've just started reviewing specs and requirements with Karthik, Louis and Brad and things are quite moving fast back and forth so i probably need a few more days before i can come up with some better numbers. i will definitely fill those in as soon as possible.

**Comment by ali5ter** [comment]
VIC VCH deployment wizard prototype starts at https://vmware.invisionapp.com/share/TBBZ93Y3M

**Comment by zjs** [comment]
I know we've already done some work to decompose this issue. Can we try to reflect that here in GitHub by creating issues within this Epic?
