### ISSUE TITLE
VCH creation/deletion fails with "context deadline exceeded"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5156]
**User Statement:**

Command used:
./vic-machine-linux delete -f -t administrator@vsphere.local:Admin!23@10.146.13.36/Datacenter -r Cluster/Resources --thumbprint B8:88:73:E7:07:44:C4:CD:CC:3D:B8:A2:0C:15:64:18:53:B9:D0:22 -n U-VIC-0001

**Details:**
May 18 2017 00:59:26.941-04:00 INFO  ### Removing VCH ####
May 18 2017 00:59:27.856-04:00 INFO  Validating target
May 18 2017 00:59:29.105-04:00 INFO
May 18 2017 00:59:29.105-04:00 INFO  VCH ID: VirtualMachine:vm-259
May 18 2017 00:59:29.174-04:00 INFO  Removing VMs
May 18 2017 01:02:26.990-04:00 ERROR Unable to get vm config: Post https://10.146.13.36/sdk: context deadline exceeded
May 18 2017 01:02:26.990-04:00 ERROR Unable to get vm config: Post https://10.146.13.36/sdk: context deadline exceeded
May 18 2017 01:02:26.990-04:00 ERROR Unable to get vm config: Post https://10.146.13.36/sdk: context deadline exceeded
May 18 2017 01:02:26.990-04:00 ERROR Unable to get vm config: Post https://10.146.13.36/sdk: context deadline exceeded
...
May 18 2017 01:02:27.008-04:00 INFO  Specify --force to force delete
May 18 2017 01:02:27.008-04:00 INFO  Collecting b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
May 18 2017 01:02:27.009-04:00 ERROR Failed to collect b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log: Post https://10.146.13.36/sdk: context deadline exceeded
May 18 2017 01:02:27.009-04:00 WARN  No log data for b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
May 18 2017 01:02:27.009-04:00 ERROR Failed to fetch guest info of appliance vm: Post https://10.146.13.36/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://10.146.13.36/sdk: context deadline exceeded
...
May 18 2017 01:02:27.009-04:00 ERROR --------------------
May 18 2017 01:02:27.009-04:00 ERROR vic-machine-linux delete failed: Delete timed out: use --timeout to add more time

**Acceptance Criteria:**

Expected VCH to get deleted successfully.

#For bug reports, please include the information below:

**VIC version:**

./vic-machine-linux --version
vic-machine-linux version v1.1.1-rc2-0-56a309f

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

**Steps to reproduce:**

I have created VCH using VIC1.1.1 and created containers. The containers were in running state when I attempted force delete as containers will get powered off and then cleanup as part pf VCH delete.

Logs : vic-machine.log and vpxd.log attached.

[VCH-Delete.zip](https://github.com/vmware/vic/files/1009877/VCH-Delete.zip)

**Comment by lgayatri** [comment]
Every VCH deletion sees this bug:

root@Ubuntu-VIc:/home/vmlib/VIC/VIC-111/vic# ./vic-machine-linux delete -t administrator@vsphere.local:'Admin!23'@w3-stras-db06.eng.vmware.com/Datacenter --name U-VIC-00010 --force
May 26 2017 08:36:49.710-04:00 INFO  ### Removing VCH ####
May 26 2017 08:36:49.933-04:00 INFO  Validating target
May 26 2017 08:36:50.162-04:00 INFO
May 26 2017 08:36:50.162-04:00 INFO  VCH ID: VirtualMachine:vm-673
May 26 2017 08:36:50.179-04:00 INFO  Removing VMs
May 26 2017 08:40:19.711-04:00 ERROR Unable to get vm config: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
May 26 2017 08:40:19.711-04:00 ERROR Unable to get vm config: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
May 26 2017 08:40:19.712-04:00 ERROR Unable to get vm config: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
May 26 2017 08:40:19.712-04:00 ERROR Unable to get vm config: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
May 26 2017 08:40:19.712-04:00 INFO  Specify --force to force delete
May 26 2017 08:40:19.712-04:00 INFO  Collecting b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
May 26 2017 08:40:19.712-04:00 ERROR Failed to collect b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
May 26 2017 08:40:19.712-04:00 WARN  No log data for b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
May 26 2017 08:40:19.712-04:00 ERROR Failed to destroy VM "VirtualMachine:vm-1953": Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded then failed to unregister VM: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded
May 26 2017 08:40:19.712-04:00 ERROR --------------------
May 26 2017 08:40:19.712-04:00 ERROR vic-machine-linux delete failed: Delete timed out: use --timeout to add more time

Hope to see the fix soon.

**Comment by lgayatri** [comment]
Even creation of VCH at times is failing with this error on build
 ./vic-machine-linux --version
vic-machine-linux version v1.1.0-rc3-10888-bc67e17

Jun  1 2017 01:28:39.202-04:00 INFO  Docker API endpoint check failed: context deadline exceeded
Jun  1 2017 01:28:39.202-04:00 INFO  Collecting b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
Jun  1 2017 01:28:39.216-04:00 INFO  Docker API endpoint check failed: context deadline exceeded
Jun  1 2017 01:28:39.216-04:00 INFO  Collecting b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
Jun  1 2017 01:28:39.326-04:00 INFO     API may be slow to start - try to connect to API after a few minutes:
Jun  1 2017 01:28:39.326-04:00 INFO             Run command: docker -H 10.197.37.180:2376 --tls info
Jun  1 2017 01:28:39.326-04:00 INFO             If command succeeds, VCH is started. If command fails, VCH failed to install - see documentation for troubleshooting.
Jun  1 2017 01:28:39.326-04:00 ERROR --------------------
Jun  1 2017 01:28:39.326-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 30m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target

Jun  1 2017 01:28:39.334-04:00 INFO     API may be slow to start - try to connect to API after a few minutes:
Jun  1 2017 01:28:39.334-04:00 INFO             Run command: docker -H 10.197.37.170:2376 --tls info
Jun  1 2017 01:28:39.334-04:00 INFO             If command succeeds, VCH is started. If command fails, VCH failed to install - see documentation for troubleshooting.
Jun  1 2017 01:28:39.334-04:00 ERROR --------------------
Jun  1 2017 01:28:39.334-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 30m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target

Jun  1 2017 01:28:42.219-04:00 INFO  Docker API endpoint check failed: context deadline exceeded
Jun  1 2017 01:28:42.219-04:00 INFO  Collecting b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
Jun  1 2017 01:28:42.338-04:00 INFO     API may be slow to start - try to connect to API after a few minutes:
Jun  1 2017 01:28:42.338-04:00 INFO             Run command: docker -H 10.197.37.169:2376 --tls info
Jun  1 2017 01:28:42.338-04:00 INFO             If command succeeds, VCH is started. If command fails, VCH failed to install - see documentation for troubleshooting.
Jun  1 2017 01:28:42.338-04:00 ERROR --------------------
Jun  1 2017 01:28:42.338-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 30m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target

This bug is blocking me to scale up, please look into asap.

**Comment by mdubya66** [comment]
Test Blocker

**Comment by emlin** [comment]
@lgayatri looks like you're deleting VCH concurrently, and all the timeout is default 3m. If you have a large VC environment, the vsphere operation might take longer time, and especially while you're running vic-machine concurrently.
Did you try to use a larger timeout to run your test?
Btw, in your case, cause the delete failed for context exceeded error, there might have left over in your environment, which will block your next creation, which happens in #5441. In that case, you will need to cleanup vApp manually.

**Comment by lgayatri** [comment]
@emlin, yes VCHs are deleted in concurrency(part of test). I will increase the timeout for the next tear down and update.

**Comment by lgayatri** [comment]
@emlin  I tried with 10m as --timeout but still seeing the issue. There are no errors on the VC side . 
...
Failed to fetch guest info of appliance vm: Post https://10.146.13.36/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://10.146.13.36/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://10.146.13.36/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://10.146.13.36/sdk: context deadline exceeded
Failed to fetch guest info of appliance vm: Post https://10.146.13.36/sdk: context deadline exceeded
Jun 19 2017 06:36:32.593-04:00 ERROR --------------------
Jun 19 2017 06:36:32.593-04:00 ERROR vic-machine-linux delete failed: Delete timed out: use --timeout to add more time

**Comment by emlin** [comment]
@lgayatri is there any improvement using 10m timeout? I mean if there are more VCHs deleted, even there still have left over.
Do you still have the vic-machine.log for 10m timeout?

**Comment by lgayatri** [comment]
@emlin, I tried to create 50 VCH concurrently and there is no success even with 1h timeout at the time of VCH creation.

Jun 21 2017 08:25:06.239-04:00 ERROR Failed to collect b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log: ServerFaultCode: The session is not authenticated.
Jun 21 2017 08:25:06.239-04:00 ERROR --------------------
Jun 21 2017 08:25:06.239-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 1h0m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target
Jun 21 2017 08:24:49.199-04:00 ERROR Failed to collect b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log: ServerFaultCode: The session is not authenticated.
Jun 21 2017 08:24:49.199-04:00 ERROR --------------------
Jun 21 2017 08:24:49.199-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 1h0m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target
Jun 21 2017 08:25:37.796-04:00 ERROR Failed to collect b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log: ServerFaultCode: The session is not authenticated.
Jun 21 2017 08:25:37.796-04:00 ERROR --------------------
Jun 21 2017 08:25:37.796-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 1h0m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target
Jun 21 2017 08:24:57.186-04:00 ERROR Failed to collect b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log: ServerFaultCode: The session is not authenticated.
Jun 21 2017 08:24:57.186-04:00 ERROR --------------------
Jun 21 2017 08:24:57.186-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 1h0m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target
Jun 21 2017 08:25:43.587-04:00 ERROR Connection failed with error: i/o timeout
Jun 21 2017 08:25:43.600-04:00 ERROR Failed to collect b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log: ServerFaultCode: The session is not authenticated.
Jun 21 2017 08:25:43.600-04:00 ERROR --------------------
Jun 21 2017 08:25:43.600-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 1h0m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target
Jun 21 2017 08:25:47.618-04:00 ERROR Connection failed with error: i/o timeout
...

**Comment by lgayatri** [comment]
I am hitting this issue on every build, can this be fixed soon.
7/50 VCH creations failed on the current test bed.

**Comment by lgayatri** [comment]
With OVA 12202 also seeing the issue:
...
Timeout is 20min

Jul 25 2017 05:41:50.369-04:00 INFO  Unregistered VM to cleanup after failed destroy: "VirtualMachine:vm-1869"
Jul 25 2017 05:41:55.908-04:00 INFO  Specify --force to force delete
Jul 25 2017 05:41:55.908-04:00 INFO  Collecting da2ca126-f532-4bc0-9b6d-b7cc879b569e vpxd.log
Jul 25 2017 05:41:55.908-04:00 ERROR Failed to collect da2ca126-f532-4bc0-9b6d-b7cc879b569e vpxd.log: Post https://vic-st-h2-191.eng.vmware.com/sdk: context deadline exceeded
Jul 25 2017 05:41:55.908-04:00 WARN  No log data for da2ca126-f532-4bc0-9b6d-b7cc879b569e vpxd.log
Jul 25 2017 05:41:55.908-04:00 ERROR Failed to destroy VM "VirtualMachine:vm-3314": Post https://vic-st-h2-191.eng.vmware.com/sdk: context deadline exceeded then failed to unregister VM: Post https://vic-st-h2-191.eng.vmware.com/sdk: context deadline exceeded
Jul 25 2017 05:41:55.908-04:00 ERROR --------------------
Jul 25 2017 05:41:55.908-04:00 ERROR vic-machine-linux delete failed: Delete timed out: use --timeout to add more time

**Comment by emlin** [comment]
I saw this error: `ERROR Unable to get vm config: Post https://w3-stras-db06.eng.vmware.com/sdk: context deadline exceeded`
This is the same thing described in PR #5784, we had too many property collector created to create/delete VCH.

@caglar10ur 
I think your PR #5784 will help on this issue as well. Could you please help to confirm?

**Comment by caglar10ur** [comment]
I don't think 5784 is going to help this, it wasn't for context deadline errors it is for connection refused one

**Comment by emlin** [comment]
hmm... Didn't get debug information from the above description for what caused the context deadline issue. But it is the property collector returned error. I still think limit concurrency will help this issue.

@lgayatri could you please attach the whole vic-machine log with debug = 1 during create/delete. I'd like to see if there is any other message printed before the context deadline exceeded.
Also please still run with longer timeout.

**Comment by gigawhitlocks** [comment]
re: concurrency limit, I can go ahead and implement that @emlin and maybe we just shouldn't have a default timeout on `delete`, or perhaps have it scale w/ the number of containers that need to be deleted? Shouldn't be too hard to count the existing containerVMs and generate a heuristic so that `vic-machine delete` will have a default timeout that makes sense depending on the size of its workload.

**Comment by gigawhitlocks** [comment]
Placing back in Todo until #5784 is merged

**Comment by lgayatri** [comment]
@emlin I am not seeing this issue since build vic-28d18602-dev.ova. I have a timeout of 20 minutes.

**Comment by caglar10ur** [comment]
We started to delete VMs in parallel as of https://github.com/vmware/vic/commit/d158c1982c3b813164c1f1b1d594a8b612106e56 

We can't delete faster than the infrastructure so there can be still timeouts but at least we are now deleting them in parallel.

Closing this now...
