### ISSUE TITLE
Implement a base Clarity Wizard instance

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#5162]
User Statement:
As a UI engineer I would like to scaffold the wizard such that the following story items, which are actual dev work for each section, will be straightforward 

Acceptance Criteria:
1. Have all sidebar items. 
2. Create dummy components for each content section

**Comment by mdubya66** [comment]
Removing this from 1.2. Not required.

**Comment by jooskim** [comment]
Agreed. This and its sibling stories are for 1.3

**Comment by jooskim** [comment]
Moving this topic back into backlog in favor of #5552 which is of higher priority for 1.2 release.
