### ISSUE TITLE
1.1.1 OVA deployment displays version 1.1.0.0

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#5189]
**VIC version:**

vic-v1.1.1_56a309fb.ova, downloaded from VMware.com

**Deployment details:**

Deploying the OVA in the vSphere Web Client.

**Steps to reproduce:**

Deploy the OVA.

**Actual behavior:**

On the Review details page, the version is 1.1.0.0:

![ova-version](https://cloud.githubusercontent.com/assets/16718369/26251391/5bb8eb3c-3cad-11e7-8522-1a8d58100e2f.png)

**Expected behavior:**

Should be 1.1.1.0.

**Comment by stuclem** [comment]
Console shows the correct version:

![ova-screen](https://cloud.githubusercontent.com/assets/16718369/26252092/9d381f72-3caf-11e7-9ecd-393d00e11f62.png)

**Comment by sgairo** [comment]
Good catch, we should automate this :)

**Comment by andrewtchin** [comment]
Thanks, opened #5192
