### ISSUE TITLE
Nimbus cleanup failure on 6.5 nightly test

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5191]
Log collection failure:
```
Environment variable '%{VIC-ADMIN}' not found.	
```

[5-13-Invalid-ESXi-Install.zip](https://github.com/vmware/vic/files/1014651/5-13-Invalid-ESXi-Install.zip)

**Comment by mhagen-vmware** [comment]
This is actually working as expected. If the test passes,  then the VCH did not get installed so you can't gather logs off of it.  Looking at the timing, it didn't hang at all on the clean, so I am inclined to leave it like it is.
