### ISSUE TITLE
Nightly 6.0 multiple datacenters test w/various failures

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5206]
No logs other than log.html and output.xml. log.html doesn't show any red, but output.xml has many failures. @mhagen-vmware can you take a look?
[5-10-Multiple-Datacenter.zip](https://github.com/vmware/vic/files/1019748/5-10-Multiple-Datacenter.zip)

**Comment by mhagen-vmware** [comment]
This is working completely as expected.
1. We utilize wait until keyword succeeds and run keyword and continue/ignore failure in many cases when we expect there to be failures or recoverable failures.
2. output.xml is the entirety of all options within our scripts, so every time we expect something and it could possibly fail, the full decision tree can be found within the output.xml file so we expect the word fail to be seen riddled through the file even if the test is a complete pass.
