### ISSUE TITLE
CI build breaks on go install error

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5230]
`go install github.com/vmware/vic/vendor/github.com/docker/docker/pkg/idtools: build output "/go/pkg/linux_amd64/github.com/vmware/vic/vendor/github.com/docker/docker/pkg/idtools.a" already exists and is not an object file`

A great doctor once said "...we have a build dependency problem exasperated by the -j9 parallelism."

**Comment by mhagen-vmware** [comment]
Going to close this for now as fixed by #5256 please reopen if we see again.
