### ISSUE TITLE
Docker Push: Research and decompose docker push

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5239]
**User Statement:**

As a vic user, I want to be able to push images/layers/repositories into a registry/repository using the docker push command.

**Details:**

This will detail in a design spec how to implement the components and API for docker push.

**Acceptance Criteria:**

The result of this will be a design specification including definitions, possible dependencies, issues are written up for docker push and added to the epic.

**Comment by sgairo** [comment]
For 1.2, docker push will be done on stopped containers only. After further investigation, completion of the docker push epic will depend on the portlayer portion of the docker diff work.  
There are three main pieces to this feature:
1. registry authorization/ http push
2. Construction of the image
3. Retrieving the layer tars

Some work that was done for docker pull can be recycled to accomplish the registry authorization/ http push.

The Construction of the image is expected to be the most involved piece (id calculation, history creation, configs handling).

The layer tars will be handled by docker diff, through a routine for all components to be able to get all diffs. Until the portlayer portion of docker diff is done, mock data and an imagec binary will be created in order to have a functioning docker push of a simple tagged image. 

The epic has been updated with appropriate issues and necessary integration tests. The goal is demonstrable stages of docker push for both Sprint 11 and Sprint 12.

**Comment by rogeliosanchez** [comment]
lgtm
