### ISSUE TITLE
Reinstall longevity/stress system with 6.0U3

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5244]
User statement:  As an engineer on VIC, I need a reliable/working system in order to test longevity/stress on the latest 6.0 builds

Details:
Need to reinstall each of the host systems with new ESX, need to create a new VC vm (bart), and ubuntu executor vm (willie)
ESX - 5251623
VC - 5326079

Acceptance Criteria:
Longevity can be run on willie on bart that is running 6.0U3 ESX and VC

**Comment by vmware-vic** [comment]
test

**Comment by vmware-vic** [comment]
test

**Comment by vmware-vic** [comment]
test

**Comment by mhagen-vmware** [comment]
lgtm
