### ISSUE TITLE
After container exits VIC is still reporting in as running.

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#5245]
**VIC version:**
v0.8.0-100000-bcddf87
master

**Deployment details:**
VCH deployed on Nimbus

**Steps to reproduce:**
Create 10 short lived containers concurrently. 

docker create busybox /bin/ls
docker .. start

**Actual behavior:**
1 or 2 containers are still marked as running, however the correspondent VMs are powered off.
Those containers cannot be cleaned-up.

**Expected behavior:**
All containers should be powered off and ready for removal.

**Logs:**
[container-logs.zip](https://github.com/vmware/vic/files/1029700/container-logs.zip)

**Additional details as necessary:**

**Comment by anchal-agrawal** [comment]
This issue is captured in https://github.com/vmware/vic/issues/5235 and https://github.com/vmware/vic/issues/4997. Closing.
