### ISSUE TITLE
Docker Commit:  Research and decompose docker commit

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5253]
As a VIC developer, I need to know all the issues needed to implement docker commit.

Acceptance Criteria: Issues are written up for docker commit and added to the epic.

**Comment by sflxn** [comment]
I don't think this is happening for VIC 1.2.  There are a bunch of dependencies that need to be in place before we can fully implement docker commit.  Docker Pause and maybe Docker Diff.

There maybe other dependencies that I have not thought of yet.  Docker commit allows users to modify and dockerfile parameter and create a new layer and image.  We need to review every dockerfile parameter and determine how that affects VIC and whether we need to add additional support before we can estimate how long it will take to do docker commit.

**Comment by sflxn** [comment]
After studying what docker does for commit, this is actually not going to be a lot of work.  In addition, since docker diff will create the RW layer diff tar and imagec currently has a path to create a VMDK from a tar, the work for commit is actually quite simple.  Assuming we use docker's code to merge config.  We may have to refactor the imagec code to allow us to push a tar file into the storage layer.

**Comment by sflxn** [comment]
We had a meeting and @karthik-narayan agreed that we will do docker commit on stopped containers only.  I've done the research on docker commit and written up all the new issues for commit so I believe this concludes this research sprint.

**Comment by mdubya66** [comment]
LGTM. Verified. Thanks @sflxn

**Comment by mdubya66** [comment]
oh, add a test story to the epic @sflxn
