### ISSUE TITLE
Container gets created with 2 vCPUs despite mentioning 1 vCPU in the command

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5264]
Build: vic-1.1.1-rc2
I used the below command:
docker -H 10.197.37.187:2376 --tls create busybox --cpus 1 sleep 1h
5ac643d9d8bbeb174fcb4ea8e7688f702e32ca05de01d961fa7e90d7de6db338
 and expected the container to be created with 1 cpu as per https://vmware.github.io/vic-product/assets/files/html/1.1/vic_app_dev/container_operations.html  but instead the container got created with 2 vCPUs which is the default.
Accepted criterion: Container should get created with the user input cpu rather than default always.

This is important for us to be able to accommodate more containers on a given physical host.

**Comment by anchal-agrawal** [comment]
@lgayatri have you tried the `--cpuset-cpus` flag? The doc doesn't claim support for `--cpus` explicitly.

**Comment by lgayatri** [comment]
Yes, docker -H 10.197.37.187:2376 --tls create busybox --cpuset-cpus 1 sleep 1h and still the same result.

**Comment by anchal-agrawal** [comment]
@lgayatri the correct format for the command is:

```
docker create --cpuset-cpus 1 busybox sleep 1h
```

If `--cpuset-cpus` is specified after `busybox`, it's parsed as the command to run in the container instead. I tried the above command on my setup and it works as intended:

<img width="500" alt="cpu" src="https://cloud.githubusercontent.com/assets/4361620/26501982/c21780e8-4200-11e7-9e26-7464bfe252e8.png">


Please re-open the issue and attach the logs if you're still able to repro. Thanks!
