### ISSUE TITLE
vm-support on VCH should include Harbor logs as well which are under /var/log/harbor

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5265]
**User Statement:**

The support bundle that gets generated on VCH with vm-support should include Harbor logs 

**Details:**
vm-support on VCH contains only vmware-* files from /var/log and does not include log folder harbor which is needed to debug harbor issues

**Acceptance Criteria:**
Extracted vm-support bundle of VCH, and found only below logs
root@vic-st-h2-132 [ /var/log/harbor/2017-05-26/tmp/vm-support.qabKha/var/log ]# ls
vmware-vgauthsvc.log.0  vmware-vmsvc.1.log  vmware-vmsvc.2.log  vmware-vmsvc.3.log  vmware-vmsvc.4.log  vmware-vmsvc.log

ls /var/log contains:

root@vic-st-h2-132 [ /var/log ]# ls
btmp            harbor         installer.log  lastlog                 vmware-vmsvc.1.log  vmware-vmsvc.3.log  vmware-vmsvc.log
cloud-init.log  journal        vmware-vgauthsvc.log.0  vmware-vmsvc.2.log  vmware-vmsvc.4.log  wtmp

Missing log folder is "harbor"

Please include harbor log folder in the support bundle.

**Comment by anchal-agrawal** [comment]
@lgayatri Looks like this is the OVA applianceVM, not the VCH endpointVM. Ping @andrewtchin and @frapposelli for adding an estimate for the work involved.

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #884](https://github.com/vmware/vic-product/issues/884) via [**ZenHub**](https://www.zenhub.com/)
