### ISSUE TITLE
Co-locate all required logs of harbor,admiral under /var/log/vmware/

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5266]
Currently on VCH, we see logs 
root@vxxx-1xx [ /var/log ]# ls
btmp            harbor         journal  vmware-vgauthsvc.log.0  vmware-vmsvc.2.log  vmware-vmsvc.4.log  wtmp
cloud-init.log  installer.log  lastlog  vmware-vmsvc.1.log      vmware-vmsvc.3.log  vmware-vmsvc.log

We should follow our standard folder structure to have all logs moved under /var/log/vmware to have that of both admiral and harbor.

**Comment by anchal-agrawal** [comment]
@lgayatri Looks like this is the OVA applianceVM, not the VCH endpointVM. Ping @andrewtchin and @frapposelli for adding an estimate and priority for the work involved.

**Comment by lgayatri** [comment]
Thanks @anchal-agrawal , I pinged @andrewtchin and @frapposelli for the same.

**Comment by andrewtchin** [comment]
Related to https://github.com/vmware/vic-product/issues/225 and https://github.com/vmware/vic/issues/4680
We need to get the admiral logs off of the container

**Comment by andrewtchin** [comment]
Closing this in favor of https://github.com/vmware/vic-product/issues/225
