### ISSUE TITLE
223K instances of "[ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow." found in vmware-vmsvc logs

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5267]
VCH is deployed with 1.1.1rc2 release build

root@vic-st-h2-132 [ /var/log ]# cat vmware-vmsvc.* | grep " GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow." | wc -l
223947
I have just 5 logs of vmware-vmsvc* and they are filled with these messages.

Snippet:
[May 26 11:48:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.081] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.083] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.083] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.083] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.

Every 30 seconds, 6 entries are being made to the log file.
AFAIK, this message needs no user action. Can we suppress this?

Found similar stack trace in: https://github.com/vmware/open-vm-tools/issues/128

Logs attached.
[vmsvc.tar.gz](https://github.com/vmware/vic/files/1031728/vmsvc.tar.gz)

Expected:
Avoid filling logs with this message for better log readability.

**Comment by dougm** [comment]
Wasn't aware of this limit.  We can either cap what we send here at 16 or filter out interfaces with no IP addresses.

**Comment by dougm** [comment]
We also shouldn't send the NIC info so often, we can skip if it hasn't changed.

**Comment by cbonte** [comment]
Hi @dougm,
> And consider filtering out interfaces with no IP address

I went into a similar thought :
https://github.com/vmware/open-vm-tools/issues/128#issuecomment-303056218
