### ISSUE TITLE
VM container portlet

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#527]
Portlet to display the docker container details.

Portlet will show up on the VM Summary within Hosts and Clusters tree and will display the following info:
Title: Container
Data:
-Name
-Image
-Port mapping

UX Comp:
http://ue-sandbox.eng.vmware.com/vic/HTML/#p=vm_in_hosts_and_clusters_tree

This data will be extracted from the VM config via extraConfig.guestInfo

**Comment by jooskim** [comment]
Done except for port mapping. Will include it after onsite beta

**Comment by jooskim** [comment]
This issue is closed as the initial container VM portlet is now in place. To be referenced with #854 later for displaying port mapping information.
