### ISSUE TITLE
Virtual container hosts portlet

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#528]
VCH portlet view.

Portlet will show up on the VCH vApp Summary within Hosts and Clusters tree and will display the following info:
Title: Virtual Container Host
Data:
-Docker API endpoint
-Docker log url (link)

UX Comp:
http://ue-sandbox.eng.vmware.com/vic/HTML/#p=vch_summary_in_vms_and_templates_tree&g=1

**Comment by stuclem** [comment]
The docs need to mention where this information is displayed, so added the user-doc label.

**Comment by jooskim** [comment]
This is now implemented. Closing the issue.
