### ISSUE TITLE
proc/*/cgroup should show containerID inside the container

### ISSUE THREAD

**Issue by techvoltage** [vmware/vic#5282]
**VIC version:**
v1.1.0-rc3-0-771b504

**Deployment details:**

`~/vic/bin/vic-machine-linux create --user root -t $esxip --name $vchname --no-tlsverify --no-tls --force`

**Steps to reproduce:**
1. `~/vic/bin/vic-machine-linux create --user root -t $esxip --name $vchname --no-tlsverify --no-tls --force`
2. `cat /proc/1/cgroup`  #inside container

**Actual behavior:**
`cat /proc/pid/cgroup` shows ```1:name=systemd:/init.scope```
**Expected behavior:**
`cat /proc/pid/cgroup` should show something like ```1:name=systemd:/docker/25160ba187f2cf0b91d1b7e7878a527f5d1b97e0edee7324d6f86f712952bc59```

**Comment by anchal-agrawal** [comment]
Pinging @hickeng for the estimate and scope of this issue.

**Comment by techvoltage** [comment]
Any help? 
Was it a design decision not to expose the cgroup path(containing the container ID) inside the container?

**Comment by hickeng** [comment]
@techvoltage We are not using cgroups to isolate or control the container process - the VM is the isolation boundary. The container process is running in the same cgroup as the actual pid 1 (tether) - i.e. if you kill pid 1 you'll get a kernel panic. If you want to you can kexec within a containerVM, but it's not something we test.

The fact the cgroup is called `name=systemd:/init.scope` is an artifact of us still leveraging systemd-udevd in bootstrap.iso to populate `/dev/disk/by-label`. This naming is rather misleading as there's no systemd involved after /dev initialization and we intend to remove it from the bootstrap eventually (#306).
There was no design decision to hide cgroup path as there's no manipulation of cgroups involved.

Does that address the question?

**Comment by techvoltage** [comment]
@hickeng Yes it does. Thanks!
