### ISSUE TITLE
Logger thread for vpxd.log seems to have got killed after OVA reboot

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5283]
Observation.

I have an integrated OVA and a ubuntu client machine on which vic has been setup. On May18th the OVA got rebooted after which the vpxd.log stopped getting updated. Looks like the logger thread got killed?

OVA got rebooted at
 cat *.log | grep -i "CPU reset: soft"
...
2017-05-18T06:55:32.348Z| vcpu-1| I125: CPU reset: soft (mode 0)

and on the client machine logging to vpxd.log stopped at the exact same time.
ls -ltrh 
...-rw-r--r-- 1 root root 7.2K May 18 02:56 vpxd.log
The time zone representation is EDT on client and UTC on OVA.
Current time on client - Mon May 29 06:46:39 EDT 2017
Current time on OVA   - Mon May 29 10:54:06 UTC 2017
EDT and UTC have 4 hours diff with UTC being ahead

while vpxd.log does not get updated, vic-machine.log is up to date.

Logs attached: vpxd and vic-machine.log from client and vm-support bundle of OVA

[vm-2017-05-29.13831.tar.gz](https://github.com/vmware/vic/files/1035625/vm-2017-05-29.13831.tar.gz)
[vic-machine.zip](https://github.com/vmware/vic/files/1035627/vic-machine.zip)

**Comment by anchal-agrawal** [comment]
Ping @frapposelli for the estimate and priority so we can move this into the backlog.

**Comment by frapposelli** [comment]
I'm not sure what's the expected outcome here, we're not logging to vpxd.log directly in any way.

**Comment by lgayatri** [comment]
@frapposelli , what is the purpose of this log file ? If it is not needed, we don't have to create it.

**Comment by frapposelli** [comment]
@lgayatri we're not creating it, and I'm not sure why it is on your OVA either, `vpxd.log` is the log for the vCenter daemon.

Ping @andrewtchin for further investigation.

**Comment by andrewtchin** [comment]
I'm pretty sure this is for VIC Engine - when collecting the log bundle with container logs from vicadmin, we collect vpxd.log.
@lgayatri where on the OVA did you find `vpxd.log`?

**Comment by lgayatri** [comment]
@andrewtchin, not on the OVA but vpxd.log is on the client machine at the same dir level as the vic executables.

root@Ubuntu-VIc:/home/vmlib/VIC/VIC-111/vic# ls | grep vp
vpxd.log

**Comment by andrewtchin** [comment]
Ok I'm pretty sure that's `vic-machine` then - did the `vic-machine create` command you tried fail?

**Comment by lgayatri** [comment]
No, vic-machine-linux create succeeded, just created one.

May 31 2017 00:38:37.093-04:00 INFO  Docker environment variables:
May 31 2017 00:38:37.093-04:00 INFO  DOCKER_HOST=10.197.37.133:2376
May 31 2017 00:38:37.103-04:00 INFO
May 31 2017 00:38:37.103-04:00 INFO  Environment saved in U-VIC-0001/U-VIC-0001.env
May 31 2017 00:38:37.103-04:00 INFO
May 31 2017 00:38:37.103-04:00 INFO  Connect to docker:
May 31 2017 00:38:37.103-04:00 INFO  docker -H 10.197.37.133:2376 --tls info
May 31 2017 00:38:37.103-04:00 INFO  Installer completed successfully

BUt vpxd.log does not get updated.

**Comment by andrewtchin** [comment]
@emlin can you see if this is a bug? I'm not sure what we do with `vpxd.log`

**Comment by emlin** [comment]
vic-machine just collect vpx.log while vic-machine command failed, it's not an updated log synced with VC log files.
If the vpxd.log file is generated by vic-machine, then it's not a bug, if vic-machine succeeds.

**Comment by anchal-agrawal** [comment]
Per @emlin, we don't keep a synced `vpxd.log` alongside VIC logs. The scenario described in the issue description is not a bug.

**Comment by lgayatri** [comment]
Thanks @emlin for the detail. So vpxd.log on the client will not be synced with that of VCSA unless there is a failure.

**Comment by emlin** [comment]
tbh, I'm not sure where the file is come from. But if that's generated by a failed vic-machine operation, then yes, you're right.
