### ISSUE TITLE
Configure/Persist Proxy for Admiral connections to external registry

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic#5285]
**User Statement:**

As a Cloud Admin, when I deploy the VIC-Product OVA, I want to configure a Proxy for Admiral to connect to an external registry. I also want that configuration to persist after an OVA reboot.

**Details:**

Many customers force outgoing internet connections to go through a Proxy. Without Proxy configuration, user cannot add external registry to Admiral (for example a private Repo on DockerHub): connection times out.

Admiral added this to config.properties file. This also needs to be added to the OVA deployment and provide a way for the configuration to persist.

**Acceptance Criteria:**

OVA option to add http and https proxies.
Proxy configuration persists after OVA reboot.

**Comment by anchal-agrawal** [comment]
Pinging @andrewtchin and @frapposelli for the estimate and priority.

**Comment by ckotte** [comment]
this should be fixed asap. Nearly every enterprise restricts internet access via a proxy.. Is there a workaround available? 
I tried to add proxy config to /data/admiral/custom.conf, but without success:
registry.proxy=https://<FQDN>:<port>
registry.no.proxy.list=localhost, 127.0.0.1, <domain1>,  <domain2>

**Comment by andrewtchin** [comment]
@ckotte for support with the workaround, you may want to try https://gitter.im/project-admiral/Lobby or through GitHub issues for the Admiral project

**Comment by sergiosagu** [comment]
@andrewtchin - Is it issue still in your radar to be planned and/or executed? As described above, Admiral provides a way to configure such proxy (see https://github.com/vmware/admiral/wiki/Configuration-guide#configure-access-to-registries-behind-a-proxy), probably it's needed just to expose it in a easy way within the OVA settings somehow.

**Comment by andrewtchin** [comment]
Thanks for reminding me. I'll move this to vic-product and put it in 1.4.

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #1258](https://github.com/vmware/vic-product/issues/1258) via [**ZenHub**](https://www.zenhub.com/)
