### ISSUE TITLE
Add ability to convert a layer diff tar to a vmdk

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5298]
As a VIC developer, I expect imagec to be able to create a new layer from the modified RW layer used in a container.

Acceptance Criteria:  Unit tests that can take a tar of the RW layer and create the proper metadata merging and IDs.

---

This assumes docker diff will return a tar file with the difference in the container image layers and the RW layer.  The imagec library can use docker diff to get a tar and the existing docker pull path to create the new VMDK.  Imagec does not have to do the metadata merging or tagging.  It simply runs the tar through  pull's vmdk creation path.

**Comment by sflxn** [comment]
I set this as a 5 as I do not know how much work it should take to create the vmdk with the content diff.  This work doesn't involve modification to the docker commit code.

**Comment by hickeng** [comment]
I don't know if imagec needs to be involved. I was expecting this to look conceptually like:
1. deltaTar := pl.ReadImage(store, containerID, parentID, true) // get the diff with data
  --> We have some work to do here to return the checksum for the tar to the caller - may need to add it as a tailing entry to the archive that gets stripped by caller for now
2. metadata := pl.InspectImage(store, parentID) // get the base metadata
3. metadata2 := merge(commitMsg, metadata) // add the commit message to the existing metadata
4. pl.WriteImage(store, id, metadata, checksum, deltaTar)

Is that what you're thinking with the imagec reference? I'm insufficiently familiar with that code to make the assumption.

**Comment by hickeng** [comment]
There is a potential fast path using the VirtualDiskManager.CopyDisk that sidesteps the entire call path above, however it's unclear whether there's unknowns on that path.

**Comment by emlin** [comment]
As portlayer does not have enough image and layer meta information, we should not run CopyDisk in portlayer directly.
Now the decision is to query container r/w layer diff, and rewrite that diff together with image/layer metadata as a new image. So basically the previous function used in docker pull can be used here to create new image layer. So close this issue as finished already.
