### ISSUE TITLE
Add commit logic to personality server

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5299]
As a VIC user user, I should be able to commit changes to a container.

Acceptance Criteria:  Docker commit is implemented and robot scripts to confirm it works.

---

For the first pass, maybe we can ignore running containers and do this for non-running containers since we do not have pause/unpause.  This would should leverage a lot of docker code to merge config changes. and then call the code to create the layer.

**Comment by emlin** [comment]
@mhagen-vmware after this feature is in, you could also merge your PR with a couple of minor update

**Comment by emlin** [comment]
#5719 fixed this issue
