### ISSUE TITLE
UI Plugin dev build process

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#530]
#Determine and document build process for UI plugin. We need to have an automated deployment via Jenkins and possibly gobuild (See Etienne on how they do this for host client).

Questions to answer:
How and where do we deploy the artifacts?
Is it automated and how?

Acceptance criteria: Developers are able to run a script and/or follow steps to build and deploy the VIC ui plugin

**Comment by jooskim** [comment]
Hey Josh, just checking in to ask a question. [Documentation](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wcsdk.pg.doc/ModulesAndPackages_Chapter.14.4.html#993584) says a plug-in could be deployed to a vSphere Server, which will then install the plugin to vSphere Web Client instances. Does this process involve Jenkins or other gobuild stuff somehow?

**Comment by jooskim** [comment]
Confirmed Vladimir's code working fine with our test environment. There are some catches to note which I will document into a Word file.

**Comment by jooskim** [comment]
Will start working with Andrew next week (after TP3 deadline) to talk about steps we need to get the UI plugin build process to work in the Drone environment.

**Comment by jooskim** [comment]
Q. How and where do we deploy the artifacts?
A. Given several limitations, we are giving the user options to 1) host our deliverable (e.g. vic-ui.zip) on their web server that VC can access, 2) install our plugin directly to VC Web Client's cache folder. For detailed instruction, refer to /ui/installer/instruction.docx on branch "ui" in forked repo jooskim/vic. 

Q. Is it automated and how?
A. VIC UI source code will be compiled as part of Drone CI such that once packaing is done the tar ball file will have VIC binaries as well as the /ui folder with some meta information generated during the build process.
