### ISSUE TITLE
Enabled AES on chip encryption

### ISSUE THREAD

**Issue by douggie** [vmware/vic#5302]
#For stories, please include the information below:

**User Statement:**

As a user of VIC, I would like to use LUKS to encrypted my data volumes using aes encryption that leverages hardware acceleration.

**Details:**
uname -a
Linux 93152a0bb54e 4.4.31-esx #1-photon SMP Tue Nov 22 15:06:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

modprobe -v aesni_intel
modprobe: FATAL: Module aesni_intel not found.

**Acceptance Criteria:**
support aesni_intel module
- [ ] test to ensure module is available and loads as expected

**Comment by matthewavery** [comment]
Customer is expecting kmods `aesni_intel` and `aes_x86_64` to be present for this functionality to work.

**Comment by hickeng** [comment]
https://github.com/vmware/photon/commit/747815dff6615c93773b013eaee4a8e0c639a394 has been committed to build the aesni module - this will be picked up as soon as Photon publishes the updated kernel package to the public repo. I've requested an ETA from the Photon team.

**Comment by hickeng** [comment]
Estimate is for adding regression test after Photon update.

**Comment by douggie** [comment]
wow very quick. thanks for the update.

**Comment by hickeng** [comment]
Rough ETA for updated linux-esx is middle of this coming week

**Comment by douggie** [comment]
Wow! Excited to try it out!

**Comment by douggie** [comment]
HI,
Just wondered if there were any thoughts on how I could pick up the new photon build and run it in vcenter to test out the AES support.

**Comment by hickeng** [comment]
Waiting on an answer from the photon team as to whether it's in the 1.1 public packages.

**Comment by hickeng** [comment]
@douggie AES is now in the latest builds (just built from master):
```
/lib/modules/4.4.71-1.ph1-esx # modprobe aesni-intel
/lib/modules/4.4.71-1.ph1-esx # lsmod
<snip>
ansi_cprng 4566 1 - Live 0x0000000000000000 (E)
aesni_intel 157107 1 - Live 0x0000000000000000 (E)
aes_x86_64 7439 1 aesni_intel, Live 0x0000000000000000 (E)
```

**Comment by mdubya66** [comment]
Closing. @douggie please re-open if you find it's not working.

**Comment by douggie** [comment]
all working great!

**Comment by matthewavery** [comment]
@douggie We are very glad to hear that! As always we are only a github issue or a slack message away if you have other problems :)
