### ISSUE TITLE
21-1-Whitelist test failure: Harbor setup

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#5308]
```
Running command 'ovftool --noSSLVerify --acceptAllEulas --datastore=datastore1 --name=harbor-https --net:"Network 1"='VM Network' --diskMode=thin --powerOn --X:waitForIp --X:injectOvfEnv --X:enableHiddenProperties --prop:root_pwd=<> --prop:harbor_admin_password=<> --prop:db_password=<> --prop:auth_mode=db_auth --prop:verify_remote_cert=off --prop:protocol=https harbor_0.5.0-9e4c90e.ova 'vi://root:<>@192.168.31.4 /host/govc: Post https://192.168.31.4/sdk: dial tcp 192.168.31.4:443: i/o timeout/Resources' 2>&1'.	
05:03:12.003	INFO	${out} = Opening OVA source: harbor_0.5.0-9e4c90e.ova
The manifest validates
Error: Host name (192.168.31.4%20) resolve failed
Completed with errors

'Opening OVA source: harbor_0.5.0-9e4c90e.ova
The manifest validates
Error: Host name (192.168.31.4%20) resolve failed
Completed with errors' does not contain 'Received IP address:'
```

Logs:
6.5 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1042649/21-1-Whitelist.zip)
6.0 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1042648/21-1-Whitelist.zip)

**Comment by anchal-agrawal** [comment]
6.5 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1045897/21-1-Whitelist.zip)
6.0 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1045898/21-1-Whitelist.zip)

**Comment by anchal-agrawal** [comment]
6.5 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1049702/21-1-Whitelist.zip)
6.0 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1049703/21-1-Whitelist.zip)

**Comment by anchal-agrawal** [comment]
6.5 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1049862/21-1-Whitelist.zip)
6.0 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1049861/21-1-Whitelist.zip)

**Comment by anchal-agrawal** [comment]
6.5 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1050617/21-1-Whitelist.zip)
6.0 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1050618/21-1-Whitelist.zip)

**Comment by anchal-agrawal** [comment]
6.5 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1053337/21-1-Whitelist.zip)
6.0 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1053338/21-1-Whitelist.zip)

**Comment by anchal-agrawal** [comment]
6.5 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1056191/21-1-Whitelist.zip)
6.0 - [21-1-Whitelist.zip](https://github.com/vmware/vic/files/1056190/21-1-Whitelist.zip)

**Comment by chengwang86** [comment]
6.5 
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1059202/21-1-Whitelist.zip)

6.0
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1059203/21-1-Whitelist.zip)

**Comment by chengwang86** [comment]
6.5 
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1062178/21-1-Whitelist.zip)
6.0
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1062179/21-1-Whitelist.zip)
