### ISSUE TITLE
Initial plugin tests

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#531]
Determine, write, document initial set of test procedures for UI plugin

**Comment by jooskim** [comment]
Test procedure is documented here:
https://docs.google.com/document/d/19Naz-E-u4BuJ0f8xbzWcp-UOTGksvOvhf1MI_u4rzuk

Finished:
1. Installing and configuring NGC test framework for vCenter 6.5
2. Writing Test 1, 2.1, 2.2, 2.3 and testing them on vCenter 6.5

Todo:
1. Writing Test 3
2. Installing and configuring NGC test framework for vCenter 6.0
3. Confirming that the tests work fine
4. Integrating the test procedure into Drone CI

**Comment by jooskim** [comment]
According to Mike Hagen NGC testing cannot run on the current test environment because of internal dependencies that the test framework references. He said a new internal test environment is being set up. Closing the issue until it's ready.
