### ISSUE TITLE
Implement portlayer api & related logic for GetImageTar (diff)

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5319]
This will handle the incoming call from the docker persona. This logic will need to get a handle to the child layer associated with the supplied container ID, as well as that child layer's specified ancestor layer (potentially empty, implying `scratch`). These will be passed into the storage layer's `ReadImage()` method (see #5320).

The endpoint placeholder has already been defined in the [`GetImageTar` handler](https://github.com/vmware/vic/blob/9870b81e1468f0ebe320204b20116637449c0f05/lib/apiservers/portlayer/swagger.json#L451), though some params will need to be adjusted/added (see #5320).

Acceptance criteria:
- [ ] `GetImageTar` in the swagger spec is adjusted to take the needed parameters required by [`ReadImage`](https://github.com/vmware/vic/issues/5320). Those additional parameters are:
- ancestor ID (string)
- data flag (bool)
- [ ] the `GetImageTar` handler is implemented to call storage's `GetImageTar` method which will then call [`ReadImage`](https://github.com/vmware/vic/issues/5320) and return the result

**Comment by hickeng** [comment]
It's expected that the `Read` call will eventually take a filespec argument (header only tar) that defines which files/directories to include in the result. This will be needed to implement CopyFrom - it's not directly in scope for the Read impl supporting diff.

**Comment by jzt** [comment]
This is being closed in favor of a centralized portlayer `ExportArchive` function that is already being included in @sflxn's changes.
