### ISSUE TITLE
Technical documentation for UI plugin

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#532]
Draft initial versions of functional spec, build process, and testing documents for the UI plugin

**Comment by jak-atx** [comment]
Gathering all current documentation for the UI plugin

**Comment by mdubya66** [comment]
what's the status of this issue?

**Comment by mhagen-vmware** [comment]
@jooskim Can we clean this up? Is this still valid, does it just need to be closed?

**Comment by jooskim** [comment]
@mhagen-vmware The original intent of this document was to keep a good reference point for ourselves (UI devs), and thus the deliverable of this task is to be consumed only internally. We could still work on it but it probably does not need to stay open. @jak-atx What do you think? Also, is there any document you've been working on I could take over?
