### ISSUE TITLE
Implement ReadImage in the storage portlayer

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5320]
As a developer, I need a way to gather the list of filesystem changes between a layer and one of its ancestors. This will open the door for functionality like `diff` and `export`.

Details:

A `ReadImage()` function has been proposed as follows:

`ReadImage(op trace.Operation, store url.URL, ID, ancestor string, filespec archive, data bool) (io.Reader, error)`

The function will take a pointer to an image store, the child layer ID, as well as an ID associated with an ancestor of the child layer. It will return the actual layer archive data as an `io.Reader`, and an error. The tar archive will initially only contain headers describing the files within (to include "whiteout" files to represent deletions). If the `data` flag is set, the archive will contain the filesystem data in addition to the headers.

A separate call to the storage portlayer's `Inspect` method will be required to obtain the image metadata.

The implementation should mount the two corresponding vmdks and perform a naive filesystem diff between the two, building the archive as it goes. Note: the VMDKs (if unattached) will need to be attached to the VCH as non-persistent as no changes are intended.

Basic flow:

1. A call to `Read` is made with the supplied parameters
2. `store` is located/validated
3. `child` ID is used to lookup and mount the child layer VMDK
4. `ancestor` ID is used to lookup and mount the ancestor layer VMDK. If empty, `scratch` is assumed (unless a filespec is specified - in which case no ancestor is required)
5. A naive filesystem diff is performed between the `child` and `ancestor` disks (unless a filespec is specified)
6. A tar archive is constructed containing headers describing these files (if `data` is true, we add the data to the tar archive for each file), or the set provided in filespec if present

Notes:
- Files that have been removed in the child are added to the tar archive as whiteout files (named with a `.wh.` prefix in the header)
- Whiteout files are naturally omitted in the case when the `ancestor` is omitted, as we are ultimately just archiving the entire filesystem from `scratch` to the child layer

Acceptance criteria:
- [ ] `ReadImage` is implemented
- [ ] `ReadImage` unit and integration tests are implemented where appropriate
- [ ] Tar containing data for modified files is available - this is to support the commit & push cases even if not core to the docker diff command.

**Comment by hickeng** [comment]
It's expected that the Read call will eventually take a filespec argument (header only tar) that defines which files/directories to include in the result. This will be needed to implement CopyFrom - it's not directly in scope for the Read impl supporting diff.
