### ISSUE TITLE
Create container folders on datastore with the display name as created and shown in webclient instead of ID

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5324]
**User Statement:**

1. Create a container using docker command.
2. Automatically display name is picked and container gets created
3. On the compute datastore this display name is not retained but the folders are created with the ID

This is very inconvenient to look for container specific logs on the underlying datastore.

**Details:**

Screenshot attached : Container-Display-name.png which shows the display name of the container created.
container-display-name.PNG - Folder structure on the datastore on which the container got created
![containerfolder-on-ds](https://cloud.githubusercontent.com/assets/25006749/26668112/d94265b6-46c5-11e7-900c-d855a1f24c51.PNG)

![container-display-name](https://cloud.githubusercontent.com/assets/25006749/26667895/fcc92746-46c4-11e7-81db-254a7eb35ed9.PNG)

**Acceptance Criteria:**
Container folder that gets created on the datastore should have the same name as the display name in webclient for better usability.

#For bug reports, please include the information below:

**VIC version:**
./vic-machine-linux --version
vic-machine-linux version v1.1.0-rc3-10888-bc67e17

**Comment by anchal-agrawal** [comment]
Pinging @chengwang86 for input - this is related to https://github.com/vmware/vic/issues/3972.

**Comment by chengwang86** [comment]
@lgayatri The reason we only use `containerID` as the datastore folder name of the containerVM is due to the need of `docker rename`. 

Originally we were using `containerName-containerID` as the folder name (as you requested in this ticket). After `docker rename`, the containerName is changed; however, we can not update the datastore folder name of the same containerVM with the new containerName while the container is running. Therefore, there will be inconsistency between the datastore folder name `containerOldName-ID` and the container display name `containerNewName-ID`. Finally, we decided to go with simply using `containerID` as the datastore folder name. You can find our design doc here https://github.com/vmware/vic/blob/master/doc/design/docker-rename.md#the-problem.

**Comment by anchal-agrawal** [comment]
@chengwang86 given that `docker rename` relies on this, should we close this issue or pull it into the backlog? For the latter, can you add an estimate?

**Comment by chengwang86** [comment]
@lgayatri @anchal-agrawal I think we should close this issue since it is our design decision to make it `containerID`. Do you agree?

**Comment by anchal-agrawal** [comment]
It is a vSphere admin UX issue as @lgayatri pointed out, but the use-case of accessing the containerVM's datastore folder isn't as significant as `docker rename`, IMO. I think we can close this issue for now and revisit it if needed. Thanks for reporting, @lgayatri!

**Comment by lgayatri** [comment]
@chengwang86 @anchal-agrawal 
From the vSphere Admin point of view, it will be difficult to identify the container's folder on the datastore with its ID. I have 2500 containers and felt extremely difficult which container log I need to look into. 
Once the container is created(powered on or powered off), is there a way to get its ID? 
Also, in case of a VM rename scenario, the folder on the datastore does not get renamed.

**Comment by anchal-agrawal** [comment]
Re: identifying a container's datastore folder - you can search using the container's short ID which is part of the display name (format: `name-shortID`).

You can get a container's short ID with the `docker ps -a` command. To obtain the full ID, you can use `docker inspect`.

**Comment by chengwang86** [comment]
@lgayatri 

Once the VM is renamed, the folder on the datastore does not get renamed. So if we have `containerName-container` as the folder name, it is still very difficult for the vi admin to figure out where the datastore folder is after it is renamed.
