### ISSUE TITLE
Assigned name of a container gets appended with substring of ID

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5325]
**User Statement:**

I created a container using 
docker -H 10.197.37.131:2376 --tls run --cpuset-cpus 1 --name LG -d photon sleep 5d
eacc0a64edbed403af7610c696ccdc6afdd5e7c84d6d396757d0da56c2d2e371
and expected to see a container getting created with name as "LG", but instead I see the container's name as LG-eacc0a64edbe in which eacc0a64edbe is the substring of its ID. Screen shot attached. container-name-gets-appended.png

![container-name-gets-appended](https://cloud.githubusercontent.com/assets/25006749/26668386/241a339c-46c7-11e7-8b95-7101152f9c70.PNG)

**Acceptance Criteria:**
Expected to see the container getting created with the same name that was passed as an argument to the command.

**VIC version:**

./vic-machine-linux --version
vic-machine-linux version v1.1.0-rc3-10888-bc67e17

**Comment by anchal-agrawal** [comment]
This is by design. We use the `name-shortID` format to avoid name collisions and make it easy to locate containers with their name and ID.
