### ISSUE TITLE
Unable to set memory on a container

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5326]
**User Statement:**
I wanted to create a container with 1GB RAM and tried as below:

 docker -H 10.197.37.131:2376 --tls run --memory 1024 --memory-reservation 1024 --cpuset-cpus 1  --name LG6 -d photon sleep 5d

But seeing that memory is still taken as the default 2GB. Screenshot attached.
![mem-limit](https://cloud.githubusercontent.com/assets/25006749/26672704/c6fd60ec-46d7-11e7-95d3-8a4f61e79286.PNG)

**Acceptance Criteria:**
Command needs to work as expected and the memory value should be set as parsed from command line

**VIC version:**
./vic-machine-linux --version
vic-machine-linux version v1.1.0-rc3-10888-bc67e17

**Comment by anchal-agrawal** [comment]
@lgayatri VIC supports specifying a container's memory with the `-m` or `--memory` option. `--memory-reservation` is unsupported. Also, the command in the issue description is incorrect - in typical usage the memory unit is also specified. Valid usage examples of `-m`:

`-m 1g` for 1GB
`-m 512m` for 512MB

The unit defaults to bytes if unspecified. `-m 1024` implies 1024 bytes which falls below the minimum memory needed - so VIC defaults to 2GB which is what you're seeing.

Please see the usage of `-m` at https://docs.docker.com/engine/admin/resource_constraints/#memory and review the supported Docker commands and options at https://vmware.github.io/vic-product/assets/files/html/1.1/vic_app_dev/container_operations.html. Thanks!
