### ISSUE TITLE
Add imagec binary build back into VIC for dev purposes

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5330]
Acceptance criteria:

- [ ] Update makefile so we can test the transfer component of docker push while we wait for docker diff to complete.

---

Docker push has a dependency on docker diff.  We cannot do the image construction part of push without diff.  If we reassembled the imagec binary, we can at least test docker push on a tagged image or at least work on that transfer code while we wait for docker diff to complete.

**Comment by chengwang86** [comment]
I will get back to this once I finish #489
