### ISSUE TITLE
Mock up fake diff data in imagec

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5331]
Acceptance criteria:

- [ ] Create mock data that can be used to work on image construction in imagec while we wait for the completion of docker diff.

---

Docker push cannot complete without docker diff.  While we wait for the completion of docker diff, we can use docker save to create us an image tar and hand create diff layer tars to mock up the data that docker diff would have returned.  This will allow docker push's image construction work to proceed.

**Comment by sgairo** [comment]
Need to know: 'docker save -o busybox.tar busybox' generates a tar with manifest file and layers represented by folders. Do we only use the layer tars as the mock data or also the manifest generated? We will eventually need to generate a manifest, but for this purpose is it necessary?

**Comment by sgairo** [comment]
Docker save might not be what we need because its a flat file system and the config doesn't track any changes.

**Comment by sgairo** [comment]
Initial approach of a unit test will not work as we are not supposed to merge binaries into the code base. Instead, I have created a new integration test in Group1-Docker-Commands that performs a vanilla docker pull and docker save of busybox then calls an imagec push. As this test will not completely work until imagec is finished being reverted to a binary, I will not commit it. Instead I will close this issue and begin using the mock data to implement PushImage in imagec. This approach is towards #4755.

**Comment by sgairo** [comment]
@rogeliosanchez could you look this over plz :)

**Comment by rogeliosanchez** [comment]
lgtm
