### ISSUE TITLE
Admiral should store authentication Token for VCH in OVA guestinfo

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#5332]
**User Statement:**
The VCH needs to be able to authenticate itself to Admiral.  This activity requires coordination with the Admiral team.

**Details:**
Design and implement the best approach for Admiral to create/generate a Token (SAML/OIDC or another type of Token) and store it in the guestinfo for the OVA. The Token should be stored under a specific key in the guestinfo. The Token should be rotated frequently. The VCH should have a predefined role in Admiral for operation relative to content-trust.

**Acceptance Criteria:**
VCH should be able to properly identify itself to Admiral.

**Comment by hmahmood** [comment]
We also need to put the URI for the Admiral projects API in guestinfo so VCH can call it. Or at least the IP address where Admiral is listening for requests.

**Comment by lcastellano** [comment]
Here's the current proposal as discussed with Sergio in the Admiral Team:

- Admiral will provide a command to create three Solution Users one of them will be used for VCH  access,
- Admiral will log in the VCH solution user into PCS and save the returned Token into a specially mounted volume (Admiral runs inside a Docker container)
- The OVA will contain a systemd time based script to read the Token from the mounted volume and transfer that into the guestinfo.

If everybody is in agreement we can close this issue and open two:
1) Call the Admiral provided command to create the solution users in the OVA before installing starting Admiral (this could be part of the issue tracking changes to the OVA for Admiral)
2) Create the Systemd based time script to copy the Token into the Guestinfo area

**Comment by hmahmood** [comment]
@lcastellano this sounds fine. Could you please open the issues? Thanks.

**Comment by hmahmood** [comment]
#5551 and #5554 created
