### ISSUE TITLE
Missing scope in bearer auth challenge when fetching from private repository

### ISSUE THREAD

**Issue by volak** [vmware/vic#5338]
I'm using both the remote docker client and the management portal to try to pull images from my private artifactory repository but I'm getting

```
sudo docker -H 192.168.X.X:2376 --tls pull company-docker.jfrog.io/image:latest
Error response from daemon: Failed to obtain OAuth endpoint: missing scope in bearer auth challenge
```

Which I believe is the same issue reported in a different project here:
https://github.com/rkt/rkt/issues/2248

The fix they merged in is here:
https://github.com/appc/docker2aci/pull/126

There is very similar code in this project here: https://github.com/vmware/vic/blob/5a932c8d88d46db7c497762ebb545f98213dc39f/pkg/fetcher/fetcher.go#L452

If you can look at the change and possibly merge it into the project that would be of great help to me and others using private repositories like quay.io or artifactory

**Comment by volak** [comment]
Workaround until fixed:

```
docker pull company-docker.jfrog.io/image:latest
docker tag company-docker.jfrog.io/image:latest vsphere.company/library/image:latest
docker push vsphere.company/library/image:latest

docker -H 192.168.X.X:2376 --tls run vsphere.company/library/image:latest
```

Basically just pull from private, push to vsphere's vic registry, and run from that.  
Hoping for a quick fix!

**Comment by hickeng** [comment]
I've just discovered this and am bumping to high given it's evidently fallen through cracks for the 1.2 release. If it's as simple as in the referenced commit then our main overhead is confirming function afterwards against artifactory - we have an instance available internally to validate against, however I do not recall the version.

**Comment by sflxn** [comment]
Setting up Artifactory test server in my environment.  I'm not sure how we'll test once I fix it.  Artifactory OSS doesn't come with a docker registry.  Artifactory Pro does, but I can only get a test license for it.  We'll need to have an artifactory environment to test this with in CI.

**Comment by volak** [comment]
@sflxn  You can test with a free quay.io account too - I only mentioned artifactory since thats what I use.  The original issue I mentioned on rkt is the same issue and they were using quay

**Comment by sflxn** [comment]
I found the problem with artifactory.  Their docker registry doesn't respond with the header we expected when we query for the auth server.  We were using an HTTP HEAD to get that, and that worked with dockerhub and VMWare's Harbor.  For artifactory, we can only get the information if we use an HTTP GET.
