### ISSUE TITLE
Loss of vsphere events after re-establishment of dropped SDK connection

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5343]
**Story**
As a user I expect my VCH to report consistent state
As a user I expect my VCH to report whether status is stale (i.e. no connection to vSphere)

**Details**
We rely on vSphere events to trigger state transitions in the VCH when those transitions are not caused by a VCH operation. This results in the following requirements:
* report in VCH info if the event stream is not currently live, resulting in potentially stale status
* re-establishment of event stream if dropped
* invalidation of recorded state if event stream is dropped

**Acceptance**
- [ ] event collector modified to re-establish event stream after re-authentication
- [ ] test added to confirm the three main points above - use `govc` to delete the active session for the VCH, causing NotAuthenticated errors

**Notes**
Opened as result of log bundle analysis for #4872

**Comment by hickeng** [comment]
Confirmed hypothesis on local ESX:

delete the session:
```
vagrant@devbox:~$ govc session.ls
Key                                   Name   Time              Idle  Host            Agent
5205d6a3-cec7-4285-5809-e977cd61f488  root   2017-05-22 17:51  old   192.168.78.1    VMware vSphere Client/6.0.0
5289cda9-a0af-ca6d-5208-619b7389d27d  drone  2017-05-22 17:52  old   192.168.78.127  vic-engine/1.1.0-rc3
528ec039-fa5a-a968-2b52-51772b1f1e57  drone  2017-05-30 20:02    .   192.168.78.215  govc/0.12.1
52a03205-521e-2ff1-2e5a-0e4758713557  dcui   2017-05-22 14:45  old   127.0.0.1       VMware-client/5.1.0
52b04430-245c-b906-5523-9f6e3a54f57d  root   2017-05-22 14:41  old   127.0.0.1
52febecf-6663-d7f6-ecd1-9b0a0fe78e30  root   2017-05-30 19:33  old   192.168.78.127  vic-admin/1.1.0-rc3
vagrant@devbox:~$ govc session.rm 5289cda9-a0af-ca6d-5208-619b7389d27d
vagrant@devbox:~$ govc session.ls
Key                                   Name   Time              Idle  Host            Agent
5205d6a3-cec7-4285-5809-e977cd61f488  root   2017-05-22 17:51  old   192.168.78.1    VMware vSphere Client/6.0.0
52a03205-521e-2ff1-2e5a-0e4758713557  dcui   2017-05-22 14:45  old   127.0.0.1       VMware-client/5.1.0
52accfa4-9952-2764-7b26-ca06a92e8987  drone  2017-05-30 20:35    .   192.168.78.215  govc/0.12.1
52b04430-245c-b906-5523-9f6e3a54f57d  root   2017-05-22 14:41  old   127.0.0.1
```

info is unable to get correct data, and docker ps prompts reconnection
```
vagrant@devbox:~$ docker info
Containers: 46
 Running: 1
 Paused: 0
 Stopped: 45
Images: 96
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 430
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: devbox
ID: VJ3L:SV4H:I2I3:NBML:3FHI:BO46:FDGP:VIEB:PSBF:XX5S:RSPY:NZDA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
vagrant@devbox:~$ DOCKER_TLS_VERIFY=1 DOCKER_HOST=192.168.78.127:2376 docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
35c3b9e62ed0        busybox             "sh"                11 days ago         Up 8 days                               amazing_lamport
```

We see that the session has been re-established (`5281b8d2-9f5b-6108-2662-8f09d54c052a`)
```
vagrant@devbox:~$ govc session.ls
Key                                   Name   Time              Idle  Host            Agent
5205d6a3-cec7-4285-5809-e977cd61f488  root   2017-05-22 17:51  old   192.168.78.1    VMware vSphere Client/6.0.0
52592f9d-c2a9-2f7d-b812-63ea80a67b1a  drone  2017-05-30 20:35  old   192.168.78.215  vic-machine/1.1.0-rc3
5281b8d2-9f5b-6108-2662-8f09d54c052a  drone  2017-05-30 20:37  old   192.168.78.127  vic-engine/1.1.0-rc3
529f2842-e546-9408-39fc-b442e6c7c5b0  drone  2017-05-30 20:35  old   192.168.78.215  vic-machine/1.1.0-rc3
52a03205-521e-2ff1-2e5a-0e4758713557  dcui   2017-05-22 14:45  old   127.0.0.1       VMware-client/5.1.0
52accfa4-9952-2764-7b26-ca06a92e8987  drone  2017-05-30 20:35    .   192.168.78.215  govc/0.12.1
52b04430-245c-b906-5523-9f6e3a54f57d  root   2017-05-22 14:41  old   127.0.0.1

power off the VM directly now the SDK connection's re-established and we see that the container is still reported as up:
```
vagrant@devbox:~$ govc vm.power --off amazing_lamport-35c3b9e62ed0
Powering off VirtualMachine:1496... OK
vagrant@devbox:~$ DOCKER_TLS_VERIFY=1 DOCKER_HOST=192.168.78.127:2376 docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
35c3b9e62ed0        busybox             "sh"                11 days ago         Up 8 days                               amazing_lamport
```

port-layer log for the operations:
```
May 30 2017 20:35:37.507Z DEBUG Error configuring vSphere Event Collector: ServerFaultCode: The object has already been deleted or has not been completely created
May 30 2017 20:36:36.802Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:286]
May 30 2017 20:36:36.802Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:493] 35c3b9e62ed0e26b673ef6c52e1d4e7400aace6c403bf627448caf34423de21d
May 30 2017 20:36:36.802Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:493] [52.642µs] 35c3b9e62ed0e26b673ef6c52e1d4e7400aace6c403bf627448caf34423de21d
May 30 2017 20:36:36.802Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:286] [436.154µs] 
May 30 2017 20:36:36.804Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).VolumeStoresList:330] storage_handlers.VolumeStoresList
May 30 2017 20:36:36.804Z DEBUG op=253.11 (delta:11.745µs): [NewOperation] op=253.11 (delta:7.755µs) [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).VolumeStoresList:332]
May 30 2017 20:36:36.805Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).VolumeStoresList:330] [268.631µs] storage_handlers.VolumeStoresList
May 30 2017 20:37:57.635Z WARN  session keepalive error: ServerFaultCode: The session is not authenticated.
May 30 2017 20:37:57.679Z INFO  session keepalive re-authenticated
May 30 2017 20:38:40.264Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:286]
May 30 2017 20:38:40.265Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:493] 35c3b9e62ed0e26b673ef6c52e1d4e7400aace6c403bf627448caf34423de21d
May 30 2017 20:38:40.265Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:493] [49.162µs] 35c3b9e62ed0e26b673ef6c52e1d4e7400aace6c403bf627448caf34423de21d
May 30 2017 20:38:40.265Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:286] [192.855µs] 
May 30 2017 20:40:35.585Z DEBUG connection read: EOF
May 30 2017 20:40:35.586Z INFO  Closing the connection
May 30 2017 20:40:35.586Z DEBUG connection loop write-side closed
May 30 2017 20:40:35.586Z DEBUG data handler closed
May 30 2017 20:40:35.586Z INFO  telnet connection closed
May 30 2017 20:40:35.586Z DEBUG (vspc) detected closed connection for VM 52279e7d00b53024-e81107bd7eaf2bab
May 30 2017 20:40:35.586Z DEBUG (vspc) closing connection to the AttachServer
May 30 2017 20:40:35.586Z DEBUG (vspc) deleting vm records from the vm manager 52279e7d00b53024-e81107bd7eaf2bab
May 30 2017 20:40:35.586Z INFO  FSM closed
May 30 2017 20:40:35.587Z INFO  (vspc) remote system connection closed: read tcp 127.0.0.1:53240->127.0.0.1:2379: use of closed network connection
May 30 2017 20:40:49.698Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:286]
May 30 2017 20:40:49.698Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:493] 35c3b9e62ed0e26b673ef6c52e1d4e7400aace6c403bf627448caf34423de21d
May 30 2017 20:40:49.698Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:493] [54.344µs] 35c3b9e62ed0e26b673ef6c52e1d4e7400aace6c403bf627448caf34423de21d
May 30 2017 20:40:49.698Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:286] [350.161µs] 
```

**Comment by hickeng** [comment]
Build is available at https://storage.googleapis.com/vic-engine-builds/vic_11222.tar.gz

**Comment by malikkal** [comment]
@hickeng Many thanks for the quick hotfix.

The version numbering is a bit confusing for me. should I proceed with a normal upgrade? Please see below.

![image](https://cloud.githubusercontent.com/assets/16984768/26772187/9860275c-49f6-11e7-93c6-bef5f2ae4077.png)

**Comment by emlin** [comment]
@malikkal I tried to run upgrade using the binary @hickeng attached above, from a recent build to this one, with default installation, the upgrade works well.
so what is the old version of your VCH? and what is the configuration?
This issue is closed with @hickeng 's fix, so if you're able to reproduce the upgrade issue, we'll need a new issue to track that problem

**Comment by hickeng** [comment]
@malikkal The upgrade shouldn't have needed to be forced and the version is confusing for me as well.

@emlin The version of his VCH is `v1.1.1-rc1-10186-a1f00c5` (see the output from ls in the comment). I tried an unforced upgrade from that build and it worked for me. Can you check that you've got logging on the upgrade path that would identify what's happening in the `AddDeprecatedFields` and if not create a PR for it that can be used.

**Comment by emlin** [comment]
@hickeng I didn't see any logging for vic-machine. If cannot get more information, might just add some logging into vic-machine
