### ISSUE TITLE
Choose your own kernel...

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#5352]
This is an item in the wish list. Would it be possible to choose a kernel version (matching a chosen distribution) other than the current standard Photon Linux Kernel? Thanks.

**Comment by anchal-agrawal** [comment]
Pinging @hickeng and @matthewavery for input.

**Comment by corrieb** [comment]
This is something we have previously identified as a customer ask. We have yet to come to a decision about how we would go about facilitating this, whether it's a roll-your-own approach or whether we would take on support for different kernels.

Can you provide some more input on what you'd like to see and why. That would really help in scoping this.

**Comment by malikkal** [comment]
@corrieb, Thanks for considering.

We have standard OS builds available; mostly CENTOS/RHEL 6.x and 7.x. Most of of the new applications are encouraged to go to 7.x. However, there are still applications (especially vendor driven) who run on older distributions, citing they are only tested and certified in those versions.

This becomes a challenge during support discussions; where, they could simply refuse to support, as its not tested in Photon Linux or the said kernel version. We could push small vendors or in-house development; but, usually not the case with larger application vendors.

I am thinking of a workaround for this by having custom bootstrap ISOs matching a specific distribution's kernel version, where such issues could be addressed. In our case RHEL would be the most appropriate.

Hope this clarifies.

**Comment by corrieb** [comment]
Thanks for the clarification. It seems from other discussions we've had that RHEL is the most obvious need for support reasons.

Custom ISOs is really the only technical way to achieve this. The key is building an ISO with the minimum set of dependencies and adding the tether process in there. Technically doable. Not sure what the implications would be from a Red Hat licensing perspective though

**Comment by malikkal** [comment]
Thanks. Can we have some guidance (simple steps) to develop the custom ISO? I would like to try this out ASAP.

Licensing should be our responsibility. In our case, we have CPU socket based licensing; so, this is not an issue.

**Comment by hickeng** [comment]
@malikkal I think the easiest way to express what's needed in a custom ISO is to define the necessary end state after boot and the switch-root into the container filesystem. The essence of it is going to be:
* switch-root into disk identified by label `containerfs`
* dev & sys mounted
* dev/disk/by-label populated
* /dev/ttyS{0,1,2} present
* tmpfs mounted on `/.tether`, containing the tether binary and libraries needed for iptables
* `tether` binary running from the `/.tether` location
* nothing managing network interfaces except for tether

We have an in-house requirement to be able to support co-existence of systemd and tether from a network management perspective but that's for the future.
The code that transitions from initial boot environment to container environment is [here](https://github.com/vmware/vic/blob/master/isos/bootstrap/bootstrap).

@caglar10ur when you're done with #5422 and related can you validate the above and add anything I've missed.

**Comment by hickeng** [comment]
#6714 is much more involved than CLI support as it has to allow for upload/staging/management of custom ISOs in the appliance, listing of the options. Possibly RBAC around the images, etc.

**Comment by renmaosheng** [comment]
we have provided the alternative linux kernel in vic 1.5. closing this.
