### ISSUE TITLE
6.5 5-6-2-VSAN-Complex: vic-machine create failure while parsing datastore path

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#5354]
```
Running command 'bin/vic-machine-linux create --debug 1 --name=VCH-0-2044 --target=<> 
--thumbprint=<>  --user=<> --image-store="vsanDatastore (1)" --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=<> 
--force=true --bridge-network=bridge --public-network=vm-network --compute-resource=cluster-vsan-1 --timeout 30m 
--insecure-registry harbor.ci.drone.local --volume-store="vsanDatastore (1)"/test:default --tls-cname=*.eng.vmware.com  2>&1'
```
Output:
```
...
Jun  3 2017 04:28:19.210Z ERROR error parsing datastore path: parse ds://vsanDatastore%20%281%29/test: invalid URL escape "%20"
Jun  3 2017 04:28:19.210Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:257] [170.726µs] 
Jun  3 2017 04:28:19.210Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).Validate:282] [13.9943954s] 
Jun  3 2017 04:28:19.210Z ERROR Create cannot continue: configuration validation failed
Jun  3 2017 04:28:19.210Z ERROR --------------------
Jun  3 2017 04:28:19.210Z ERROR vic-machine-linux create failed: validation of configuration failed
' does not contain 'Installer completed successfully'
```

Logs:
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1049712/5-6-2-VSAN-Complex.zip)

**Comment by anchal-agrawal** [comment]
vSphere 6.5:
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1049874/5-6-2-VSAN-Complex.zip)

**Comment by chengwang86** [comment]
6.5
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1062239/5-6-2-VSAN-Complex.zip)

**Comment by rogeliosanchez** [comment]
After speaking with @matthewavery, we found that the `datastoreHelper` and the `storage` function (which is the main function used for storage validation are most likely the cause of this issue.
From Matt Avery:

> It is messing up because we are passing an escaped `Path` string to the `DatastoreHelper` function which is then trying to parse it as a raw URL again. Naturally, this fails because the path is no longer raw, it is escaped at this point. Proposed fix would be to simply pass the raw url back into DatastoreHelper. This will allow the parse function to avoid breaking. An alternative will be to refactor the `DatastoreHelper` function. This was avoided in the past as the function works well, though the double url parsing that is occurring is redundant and should be avoided in the future.

**Comment by chengwang86** [comment]
Seen in vsphere 6.5
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1075533/5-6-2-VSAN-Complex.zip)

**Comment by corrieb** [comment]
Still seeing this bug.
