### ISSUE TITLE
vic-machine should logout after operation is complete

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5355]
**User Statement:**
As a viadmin I expect vSphere clients not to leak sessions

**Details:**
Currently vic-machine does not clean up it's sessions after exit, meaning they are left lying around in `old` state until session timeout occurs and they are collected. `session.Logout` should be called on the exit paths.

**Acceptance Criteria:**
`govc session.ls` does not show sessions associated with vic-machine after vic-machine has exited

**Comment by anchal-agrawal** [comment]
Marking medium priority, please re-assess if necessary.

**Comment by corrieb** [comment]
This was specifically raised during the architecture review - sessions are expensive and if vic-machine is leaking sessions, it could have a wider impact on the control plane - even denying other users access.

This should be high priority IMHO.

**Comment by corrieb** [comment]
This was previously raised as #3496. I'll lose that one as dup

**Comment by mhagen-vmware** [comment]
@gigawhitlocks Should this be in new issues?
