### ISSUE TITLE
Remove unnecessary packages from bootstrap

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5359]
**User Statement:**
As a viadmin I want to use as little memory and disk for a given function as possible.
As a vic developer I want the resulting product package to be as small as possible.

**Details:**
The packages installed into bootstrap should be just the bare minimum needed. There are still two packages installed into the general base that are solely for debugging and _cannot_ be leveraged in a normal build. The following should be removed from bootstrap-staging.sh:
* tdnf
* vim

**Acceptance Criteria:**
- [ ] only the most minimal set of packages are installed during bootstrap staging
- [ ] debug packages should be installed during the following step and gated on the `debug` variable as per [this check](https://github.com/vmware/vic/blob/master/isos/bootstrap.sh#L74)

**Comment by morris-jason** [comment]
@hickeng Do you recommend cutting the debug portion or bootstrap-staging.sh (lines 77-94) completely and moving it into bootstrap.sh? If so, should I keep the installs for tdnf and vim in the debug install?
This way we can remove the debug flag an from bootstrap-staging and have a single mechanism for controlling debug options.

**Comment by morris-jason** [comment]
1) tdnf and vim are installed under the debug flag in boostrap-staging.sh. 
2) Should I move the debug package installs from boostrap-staging to the code you linked in boostrap.sh?

**Comment by hickeng** [comment]
@morris-jason This was an erroneous issue on my party - as you say they're already gated by the debug check.
