### ISSUE TITLE
Logs show up empty for a running container

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5361]
![nologs](https://cloud.githubusercontent.com/assets/25006749/26777538/3b3502f0-49fb-11e7-91ca-cbdd9ec2ed7a.PNG)

I can see the memory and CPU utilization of a running container but not its Logs. Screenshot attached.
Live setup available for 2 days: https://10.197.37.132:8282/#/containers/7ec18d808aa8c475550e290825da2 admin/Admin!23

Please do let me know what logs are needed, so that UI can upload.

**Comment by chengwang86** [comment]
@lgayatri Could you please confirm if the container is created by `docker run -d busybox sleep 5d`? I tried this command on regular docker and it didn't show any outputs. Probably we don't expect any logs from this container.

**Comment by malikkal** [comment]
Are they same? https://github.com/vmware/vic/issues/4265

**Comment by anchal-agrawal** [comment]
Admiral's `Logs` pane shows the output from the container. The container's running `sleep 5d` which produces no output.

**Comment by anchal-agrawal** [comment]
@malikkal AFAIK, Admiral currently populates the `Log` panel for VIC containers using `docker logs --tail` (https://github.com/vmware/admiral/commit/2db8476b330722287e4f636b9b6bc64d6d87eed1). Our implementation for `docker logs --since` is currently in review: https://github.com/vmware/vic/pull/5340

**Comment by malikkal** [comment]
@anchal-agrawal Thank you. While testing 0.8.x I couldn't get the logs visible in Admiral; cannot remember the scenarios. Thought it was a bug or something wrong with my deployment and later happened to see this in Admiral. I will test again in future...

**Comment by lgayatri** [comment]
Thanks @anchal-agrawal , @malikkal .

If the logs are populated using docker logs --tail ... then I do not expect to see anything for this containers.
We should enhance this log display to show the running log. Say if the log was not written after 6/6 6:00 AM, then in the console, we should show till that time. Showing empty lines wont carry any meaningful message.
