### ISSUE TITLE
Docker Push: Investigate image construction and Docker requirements

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5364]
**User Statement:**

As a vic developer, I need to understand the intricacies of constructing an image in order to move forward with Docker Push implementation.

**Acceptance Criteria:**
A design specification is created to use as a guideline moving forward.

**Comment by sgairo** [comment]
Need to know: Are we expected to authenticate per layer? Or just per image?

**Comment by chengwang86** [comment]
We need to figure out whether docker pushes each layer separately (one-by-one) or altogether in one tarball.

**Comment by sgairo** [comment]
Need to know: Manifest format expected by DockerHub

**Comment by sgairo** [comment]
We only support the docker v1 image @anchal-agrawal please confirm this.

**Comment by anchal-agrawal** [comment]
We support V2 images too, but only those with schema 1 manifests. See https://docs.docker.com/registry/spec/manifest-v2-1. The schema 1 manifest for V2 images provides backward compatibility to V1 images. See https://github.com/vmware/vic/issues/5187 for more details.

**Comment by sgairo** [comment]
Thanks!

**Comment by chengwang86** [comment]
@jzt @sflxn Here https://github.com/moby/moby/tree/master/distribution
I find that vanilla docker supports `docker pull image` from both v1 and v2 registries. Do we support both or just `v1 registry`?

**Comment by chengwang86** [comment]
Based on our understanding of docker's `push_v1.go` and `push_v2.go`,  

1. `push()` obtains a list of image layers to be transferred to the registry with layer dependencies
2. for each layer, docker contacts the registry endpoint to see if the layer already exists or not
3. If the layer already exists,  skip
4. otherwise, push the layer to the repository
5. also push the checksum of the layer to the repository for verification

**Comment by sgairo** [comment]
"After assembling the image manifest, the client must first push the individual layers. When the layers are fully pushed into the registry, the client should upload the signed manifest."

**Comment by sgairo** [comment]
We will be using schema 2 on push. Conversation for reference below:
Loc Nguyen [7:53 PM] 
https://github.com/moby/moby/blob/master/plugin/backend_linux.go#L456
based on https://github.com/moby/moby/blob/master/distribution/push_v2.go#L177
looks like we must use schema2
[7:56] 
on linux, RequireSchema2 is forced to true
and if we fail to push up the manifest, docker gives a warning and exits

**Comment by sgairo** [comment]
Layer ordering for schema 2 manifest should be reverse of schema 1, meaning layers should start with the base image.

**Comment by sgairo** [comment]
Format of manifest that will be created. Note: All mediaTypes should generally be the same for each image. 

{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "config": {
        "mediaType": "application/vnd.docker.container.image.v1+json",
        "size": 7023,
        "digest": "sha256:b5b2b2c507a0944348e0303114d8d93aaaa081732b86451d9bce1f432a537bc7"
    },
    "layers": [
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 32654,
            "digest": "sha256:e692418e4cbaf90ca69d05a66403747baa33ee08806650b51fab815ad7fc331f"
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 16724,
            "digest": "sha256:3c3a4604a545cdc127456d94e421cd355bca5b528f4a9c1905b15da2eb4a4c6b"
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 73109,
            "digest": "sha256:ec4b8955958665577945c89419d1af06b5f7636b4ac3da7f12184802ad867736"
        }
    ]
}

**Comment by sgairo** [comment]
Authentication is only required initially on not as part of every layer upload process.

**Comment by sgairo** [comment]
@rogeliosanchez will you take a look please :)

**Comment by rogeliosanchez** [comment]
lgtm
