### ISSUE TITLE
Fix rendering on test plans

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5370]
As seen here, it appears that github has modified their markdown rendering engine:

https://github.com/vmware/vic/pull/5369

We need to go through the rest of our test plan and and make sure that it is rendered properly in a browser and fix it if it isn't

**Comment by anchal-agrawal** [comment]
@mhagen-vmware should this be high priority based on our criteria? Marking as medium since this is debt - please re-address if necessary.

**Comment by mhagen-vmware** [comment]
I just put it as high to remember to get @singhshwetaQE to work on it next sprint.
