### ISSUE TITLE
vic-machine upgrade to patch failed

### ISSUE THREAD

**Issue by emlin** [vmware/vic#5379]
Here is the message copied from #5343 

I went with a forced upgrade; but, it did not succeed. Below snippet from vic-machine.log.
```
goroutine 1 [running]:
runtime/debug.Stack(0xfadf39, 0x2f, 0xc042460ee0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.main.func1(0xc04201bba0, 0xc0420041d0)
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:142 +0x184
panic(0xd8d880, 0x1677c80)
	/usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/vmware/vic/lib/install/validate.(*Validator).AddDeprecatedFields(0xc042062480, 0x16540a0, 0xc0421de680, 0xc04206c380, 0xc0421af800, 0x0)
	/go/src/github.com/vmware/vic/lib/install/validate/validator.go:778 +0x241
github.com/vmware/vic/cmd/vic-machine/upgrade.(*Upgrade).Run(0xc042197990, 0xc0421d0000, 0x0, 0x0)
	/go/src/github.com/vmware/vic/cmd/vic-machine/upgrade/upgrade.go:198 +0xd01
github.com/vmware/vic/cmd/vic-machine/upgrade.(*Upgrade).Run-fm(0xc0421d0000, 0x10101010100, 0xc0421d0000)
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:93 +0x3b
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xd430e0, 0xc0421979f0, 0xc0421d0000, 0xc042031300, 0x0)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xdb
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xf71a98, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf95e2e, 0x1d, 0x0, ...)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/command.go:193 +0xb79
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc04201bba0, 0xc0420360d0, 0xd, 0xd, 0x0, 0x0)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/app.go:250 +0x7d7
main.main()
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:146 +0x1dad
```

**Comment by emlin** [comment]
@malikkal @hickeng please leave upgrade related message in this issue

**Comment by emlin** [comment]
will have a dev build few hours later

**Comment by malikkal** [comment]
I tried an unforced upgrade too, but failed with the same error. :(

**Comment by emlin** [comment]
@malikkal Thanks for try it, that's the one with my workaround.
Would you mind to give us the vic-machine log? So we could have more insight for what's happening.

**Comment by malikkal** [comment]
@emlin Thanks. I have uploaded the log files to the ftpsite.

vic-machine-failure-11222.log
vic-machine-success-11278.log

**Comment by emlin** [comment]
@malikkal Thanks for trying our product and help to upload the log files.
I checked the vic-machine log, but it will be better if you execute the command with --debug 1, that will reveal more information to me.
As you passed the upgrade anyway, I can continue to work on the issue with some environment assumption. While you get chance to execute the upgrade again, please use --debug 1, and let us know the log.

**Comment by emlin** [comment]
This issue is reproduced. Actually, while run upgrade/configure using VCH ID, instead of resource path and VCH name, this will be reproduced. Will have a fix for it.
