### ISSUE TITLE
Large inventory in VC will cause long delay for vic-machine install

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#5382]
**User Statement:**

As a VI admin with a large VC inventory I expect vic-machine to take a reasonable amount of time.

**Details:**
Large inventory in VC will cause vic-machine to take a long time as it does not cache information about an endpoint and iterates through the inventory via the API.   

**Acceptance Criteria:**
An install should be close to the same amount of time between an empty inventory and a very big inventory.

#For bug reports, please include the information below:

**VIC version:**

1.1.1

**Comment by anchal-agrawal** [comment]
Pinging @emlin for input - please add an estimate and priority so we can pull this into the backlog. We should tag this as `kind/investigation` if it should be a research spike.

**Comment by renmaosheng** [comment]
will revisit if customer has complaint in new VIC version.
