### ISSUE TITLE
Create container VM in resource pool

### ISSUE THREAD

**Issue by emlin** [vmware/vic#539]
Now the installer will create resource pool for VCH, but the container VM is still created out of that resource pool

**Comment by gigawhitlocks** [comment]
If the command line provided Resource Pool does not exist at runtime, should the installer create it? I assume so, but want to verify. Right now the installer simply bails if the Resource Pool does not exist

**Comment by hickeng** [comment]
@gigawhitlocks There are two resource pools that are involved in install:
a. the parent pool of the VCH - this must exist already and it's a user error if it doesn't
b. the vApp or resource pool that the appliance is deployed in - this *is* the VCH in almost every sense and should always be created by the installer - if it already exists then it's a user error.

(b) could be softened if we're specifying `-force` or similar to overwrite what is already there but that's very much short hand for uninstall then install.
