### ISSUE TITLE
Move Go vcsim to govmomi

### ISSUE THREAD

**Issue by dougm** [vmware/vic#5392]
As a developer, I want to use pkg/vsphere/simulator in projects outside of VIC, without vendoring the vmware/vic repo.

The plan all along was to incubate the Go vcsim in vic and move to govmomi at some point.

There are teams outside of VIC-Engine currently using govcsim, such as @vmware/kov-maintainers and we want to finally get rid of the 5.5 VC-sim used in govmomi tests.

Acceptance Criteria:

vmware/vic/pkg/vsphere/simulator moves to vmware/govmomi/simulator

vmware/cmd/vcsim moves to vmware/govmomi/vcsim

VIC and kov are updated to use the simulator from vendored govmomi.

**Comment by hickeng** [comment]
Sounds good to me. Perhaps we can also use the change to make more progress on expanding the capabilities.

**Comment by dougm** [comment]
vmware/govmomi#750
