### ISSUE TITLE
Port forwarding in the containerVM for container-networks

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5401]
**Story**
As a VIC user I want to be able to directly use container networks
As a VIC user I want to be able to expose my application on any port, not just the one the container image hardcodes

**Detail**
This is for implementing the port forwarding portion (1b) of the EPIC:
> configure firewall to support port forwarding directly, e.g. 80 -> 8080

**Acceptance**
- [x] tomcat container on container-network is accessible on port 80 with run with -p 80:8080

**Comment by zjs** [comment]
Fixed by #6557. Remaining work tracked by #5776.
