### ISSUE TITLE
Error reading remote info: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by fcorfdir** [vmware/vic#5403]
VIC version: 1.1

fresh deploy on VCH on a vsphere 6.5 cluster.

when I try to connect to the VCH I got the following issue

root@vic [ ~ ]# docker -H 172.17.101.51:2378 --tls info
Error reading remote info: invalid character '<' looking for beginning of value

I have try from the docker client on windows and from the docker client on the virtual appliance integrated containers engine. with exacly the same error

thanks for your help

**Comment by chengwang86** [comment]
@fcorfdir Could you please also provide information re: the `vic-machine create` cmd you used to create the VCH and any log bundle you can obtain from the vicadmin webpage?

**Comment by chengwang86** [comment]
This is the line of code which prints the error msg: https://github.com/vmware/vic/blob/master/vendor/github.com/docker/docker/client/info.go#L22

It might be possible that the returned value from vic for `docker info` contained certain special character which corrupted the `Decode` function.

**Comment by chengwang86** [comment]
Set the initial estimate to 2 since things might be clearer after we obtain the full log bundle.

**Comment by fcorfdir** [comment]
the vic-machine-create

c:\vic>vic-machine-windows.exe create --target vsphere-ca.test.syscom.nc --user administrator@ca.local --password P##### --name vch2 --compute-resource Cluster --image-store vsanDatastore --bridge-network InternalNetwork --client-network ExternalNetwork --no-tls --thumbprint=16:71:AB:4F:26:90:A4:88:CB:80:DE:D8:DE:56:DA:7B:15:CB:D1:25 --public-network ExternalNetwork


the log bundle from the https://172.17.101.51:2378
[logs.zip](https://github.com/vmware/vic/files/1062356/logs.zip)

**Comment by fcorfdir** [comment]
hello chengwang,

Do you find something for my issue ?

regards

**Comment by chengwang86** [comment]
@fcorfdir I don't find any error msg in the log bundle you provided. 

Do you still see the same error when you deploy another VCH or restart (power off/on) the VCH? 

With the same VCH, do you see any error if you perform other docker commands, e.g. `docker run/create/start/ps/pull`

**Comment by chengwang86** [comment]
@fcorfdir In your cmd `docker -H 172.17.101.51:2378 --tls info`, you were hitting the vicadmin endpoint via port `2378`; but actually you should use `docker -H 172.17.101.51:2375 info` or `docker -H 172.17.101.51:2376 --tls info`, depending on whether you specify `--no-tls --no-tlsverify` in `vic-machine create`.
