### ISSUE TITLE
Implement OVA installer tests

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5406]
**User Statement:**
As a developer I want to validate that services on the OVA start.

**Details:**
Deploy and test the OVA after it builds

**Acceptance Criteria:**

- [ ] Set up Robot for `vic-product` repo
- [ ] Deploy the OVA to a vCenter (no VC on CI yet, so the test won't be enabled on CI)
- [ ] Get the IP of the OVA and verify that web services are running (`admiral`, `harbor`, `fileserver`, `engine_installer`)

**Comment by mdharamadas1** [comment]
@mhagen-vmware Looks like we need robot setup for `vic-product` repo and vCenter for these tests. What do you think how we should approach this?
