### ISSUE TITLE
docker restart tests

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5414]
User statement: As a customer of VIC, I would like to know that docker restart has been thoroughly tested  so that I can have confidence in it's function

Details:
https://docs.docker.com/engine/reference/commandline/restart/

Acceptance criteria:
1. Docker restart tests are documented and implemented within VIC CI system.

**Comment by mhagen-vmware** [comment]
@hickeng @cgtexmex

**Comment by cgtexmex** [comment]
I'm creating these as part of #5399
