### ISSUE TITLE
HTML5 Plugin displays wrong IP Information when using static IP for Client Network

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic#5421]
HTML5 Plugin displays wrong information when using a static IP for Client network.

![screen shot 2017-06-08 at 16 47 57](https://user-images.githubusercontent.com/8586715/26950050-587edf0e-4c6a-11e7-8ff3-a54f3818bdf8.png)

**VIC version:**

version v1.1.1-10711-56a309f

**Deployment details:**

./vic-machine-linux create --target vcsa-01a.corp.local \
--user administrator@corp.local \
--compute-resource RegionA01-COMP01 \
--image-store RegionA01-ISCSI01-COMP01 \
--volume-store RegionA01-ISCSI01-COMP01:default \
--public-network VM-RegionA01-vDS-COMP \
--public-network-ip 192.168.100.22/24 \
--public-network-gateway 192.168.100.1 \
--dns-server 192.168.110.10 \
--container-network VM-RegionA01-vDS-COMP:routable \
--bridge-network Bridge01-RegionA01-vDS-COMP \
--name virtual-container-host \
--registry-ca=/etc/docker/certs.d/registry.corp.local/ca.crt \
--no-tls

**Steps to reproduce:**

Create a VCH using a static client IP in CIDR format.

**Actual behavior:**

See above

**Expected behavior:**

Correct IP is displayed in the HTML5 UI

**Comment by chengwang86** [comment]
@jooskim Do you have an idea of what might have happened in this issue? Could you please add an estimate?

**Comment by jooskim** [comment]
@chengwang86 I was just about to triage this now. I had a conversation with Patrick and am aware of what's causing this issue.

**Comment by jooskim** [comment]
The issue was caused by inconsistent formatting of IP representation stored in VC. When a VCH is deployed using DHCP, `vic-machine` stores IP in the IPv4 format in VC, but when a static IP is specified in the CIDR format, IP is stored in the IPv6 format, which causes the UI logic to misinterpret it.
