### ISSUE TITLE
Add k8s base vmdk to ova

### ISSUE THREAD

**Issue by maplain** [vmware/vic#5429]
**User Statement:**

As a developer for kov, we need k8s cluster node base vmdk on ova for kovd

**Details:**
Deploy and test the kovd sees base vmdk

**Acceptance Criteria:**
- [ ] Deploy the OVA to a vCenter
- [ ] Get the IP of the OVA and verify that kovd are running, and it sees base vmdk.

**Comment by mdubya66** [comment]
moved to vic-product
