### ISSUE TITLE
running docker command with --net fails with process error. 

### ISSUE THREAD

**Issue by kabuataya** [vmware/vic#5431]
VIC Version 1.1.1

command to create a VCH with NSX Networks. 

vic-machine-windows.exe create --name VCH02 -t vCenter.kay.local --user "administrator@vsphere.local" --password "P@ssw0rd" --compute-resource Lab-Cluster --public-network vxw-dvs-21-virtualwire-6-sid-5004-containers_external --image-store DS-VM-01 --volume-store DS-VM-02:default --dns-server 192.168.1.106 --public-network-ip 10.10.50.10/24 --public-network-gateway 10.10.50.1 --container-network vxw-dvs-21-virtualwire-8-sid-5006-Container_Network --bridge-network vxw-dvs-21-virtualwire-7-sid-5005-containers_bridge --insecure-registry containers.kay.local --force --no-tlsverify --timeout 9m

creation of the VCH is successful. NSX Has DHCP Configured correctly. 

listing the network in VCH

root@containers [ ~ ]# docker --tls network ls
NETWORK ID          NAME                                                  DRIVER              SCOPE
6b0629a411a4        bridge                                                bridge
bcdc110715be        vxw-dvs-21-virtualwire-8-sid-5006-Container_Network   external

running the docker run command result in the error shown below. 

root@containers [ ~ ]# docker --tls run --network=vxw-dvs-21-virtualwire-8-sid-5006-Container_Network tomcat
Unable to find image 'tomcat:latest' locally
Pulling from library/tomcat
10a267c67f42: Pull complete
a3ed95caeb02: Pull complete
fb5937da9414: Pull complete
f131c9b3ecc4: Pull complete
f59cc3b26f35: Pull complete
63df868a0518: Pull complete
83282147e192: Pull complete
b9595cab9382: Pull complete
df2d57cc0364: Pull complete
8a47266b20c0: Pull complete
3ceed6847899: Pull complete
df2f38f223b6: Pull complete
bbd58b601cc8: Pull complete
08a39c8509ab: Pull complete
3560d2bf18a1: Pull complete
Digest: sha256:835b6501c150de39d2b12569fd8124eaebc53a899e2540549b6b6f8676538484
Status: Downloaded newer image for library/tomcat:latest
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://vCenter.kay.local/sdk: context deadline exceeded.

The virtual machine created to run the containers gets the IP Address from DHCP Server correctly. tried multiple images like nginx,  vmwarecna/nginx and tomcat and they all result in the same error. 

[container-logs.zip](https://github.com/vmware/vic/files/1064376/container-logs.zip)
[logs.zip](https://github.com/vmware/vic/files/1064377/logs.zip)

**Additional details as necessary:**

**Comment by hmahmood** [comment]
@kabuataya does this work if you use the "bridge" network instead of the container network?

**Comment by kabuataya** [comment]
@hmahmood if i run the stand VCH commands with bridge networks. things work fine without any issues. i start to face this issue only when i deploy the VMs in the container network.
