### ISSUE TITLE
Change VCH hostname to anything but Photon

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#544]
The VCH hostname is currently `photon`.  There's also an image in hub called `photon`.  So, since our URI scheme in the storage layer is `http://<hostname>/storage/<image store name>/<image name>`, and we're currently only supporting 1 image store (defaulted to the VCH hostname), the URI of a photon image becomes `http://photon/storage/photon/photon`.  Fairly confusing.

Rename the default VCH hostname to anything but photon :-).  How about `vicvch` or `container-host`.  Literally anything else is fine.

**Comment by hickeng** [comment]
Agreed - this should really be the name supplied for the VCH. This may well get closed without effort when #746 is complete.

**Comment by mdubya66** [comment]
Seems to be fixed with docker-appliance 
root@docker-appliance [ ~ ]# uname -a
Linux docker-appliance 4.4.8-esx #1-photon SMP Tue Jun 7 08:04:49 UTC 2016 x86_64 GNU/Linux
