### ISSUE TITLE
OVA signed with SHA256 breaks PowerCLI

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5443]
The VIC 1.1.1 OVA has been signed using a SHA256 hash (yet VIC 1.1.0 was using SHA1), which is not supported by PowerCLI 6.5.1 yet.
I hope you don’t release VIC 1.2 with a SHA256 until the PowerCLI Ovf-GetConfiguration supports it. It makes automating deploying difficult.
```
Get-OvfConfiguration : 10/06/2017 23:56:14      Get-OvfConfiguration            PowerCLI doesn't support SHA256 hash codes in OVF manifest. Use Force parameter to ignore hash validation on the imported files.
At line:1 char:1
+ Get-OvfConfiguration -Ovf "D:\VMware_ova\vic-v1.1.1_56a309fb.ova"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ParserError: (:) [Get-OvfConfiguration], ViError
+ FullyQualifiedErrorId : ViCore_Ovf_OvfManifest_ParseContent_Unsupported_HashAlgorithm,VMware.VimAutomation.ViCore.Cmdlets.Commands.OVF.GetOvfConfiguration
```

**Comment by jm0477** [comment]
@andrewtchin to workaround this issue, you can simple download a VMWARE OVA Tool. and convert it to SHA1 from SHA256.
'C:\Program Files\VMware\VMware OVF Tool\ovftool.exe' --shaAlgorithm=SHA1 vic-v1.2.1-4104e5f9.ova vic-v1.2.1-4104e5f9.ova
Tool link:
https://www.vmware.com/support/developer/ovf/

**Comment by andrewtchin** [comment]
Awesome thanks @jm0477

**Comment by t-tsvetkov** [comment]
As of PowerCLI 10.1 you can now import appliances with SHA-256 and SHA-512 manifest file digests.

**Comment by andrewtchin** [comment]
@t-tsvetkov Awesome thanks for your report!
