### ISSUE TITLE
vic-machine inspect: dump raw command options

### ISSUE THREAD

**Issue by emlin** [vmware/vic#5446]
As vic admin, I would like to have a way to dump VCH configuration in command line option format, without any additional information in there, so that I could easily pip the output to another vic-machine command, to help me create script for VCH management.

Command definition:`vic-machine inspect config --format raw`, discussion is tracked in #5418 

Acceptance:

- vic-machine inspect can dump command options as expected
- integration test for inspect

This issue is separated from #4617 , to track the requirement for a command line raw output, instead of a manifest file.

**Comment by emlin** [comment]
Based on our discussion in #4617, open this new issue and move this into 1.2 sprint11, and move #4617 back to backlog

**Comment by willsherwood** [comment]
Implemented by #5418
