### ISSUE TITLE
OVA startup adds vSphere admin user to Admiral roles

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5456]
**User Statement:**
As a user I want to have OOTB demo functionality by providing a username to be given certain role(s) in the management portal

**Details:**
This story will be in place of #4729 since we won't be able to create PSC users in this release.
Depends on Admiral API to add user to a given role @sergiosagu 

**Acceptance Criteria:**
- [ ] Determine what roles the user should be added to
- [ ] Demo web installer has option to add admin user to Admiral
- [ ] Demo installer calls Admiral API to add provided admin user to certain roles in Admiral

**Comment by andrewtchin** [comment]
TODO check on API status with Sergio by June 16

**Comment by andrewtchin** [comment]
From #4730 
* The Project admin for the project should be set to to the user “projectadmin”
* The developer for the project should be set to the user “developer”

**Comment by lcastellano** [comment]
There should be no need to add the VC admin user to Admiral roles. The VC admin belongs to the Administrators group and Admiral will treat any users belonging to the VC Administrators group as having Admin role in Admiral. Therefore the VC admin user should have the appropriate Admiral admin role. Closing this one.
