### ISSUE TITLE
OVA fileserver UI enhancement

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5458]
**User Statement:**
As a user I want a web interface to initialize the OVA.

**Details:**
Repurpose the webserver now called "fileserver" into the OVA landing page to accept admin credentials and initialize processes as needed 

**Acceptance Criteria:**'
- [x] Fileserver repurposed as landing page
- [x] Apply the look and feel designed by Alister
- [x] Landing page provides user information on what to do with the bundle
- [x] Landing page has a link to the docs
- [ ] ~~Document that the previous directory listing view can be seen under `:9443/files`~~
- [x] show error message when entering wrong credentials
- [x] Time out/show error when entering invalid vCenter server e.g. `1.1.1.1`
- [x] Add server side substitution of correct address for any download links
- [x] Update all links to work

**Comment by ali5ter** [comment]
Was posting mockups to https://github.com/vmware/vic-product/issues/311

**Comment by ali5ter** [comment]
Rev'ed mockup at: https://vmware.invisionapp.com/share/85C9KS2KZ

**Comment by andrewtchin** [comment]
@ali5ter Should the title for the right box be something different since it talks about both harbor and admiral?

**Comment by stuclem** [comment]
@andrewtchin we need to identify a standard way to refer to the new common Admiral/Harbor UI.

@karthik-narayan we should stop making a distinction between Registry and MP when we refer to the common UI. However, what should we call it now?  Is this now simply the **vSphere Integrated Containers Management Portal**?

Adding @alextopuzov as this is of interest to him too.

**Comment by stuclem** [comment]
@ali5ter I have looked at this again and the box on the right definitely needs overhauling.

I think that the  text in the box should be something like:

"Go to the vSphere Integrated Containers Management Portal to manage VCHs and registries, provision containers, and create projects and manage users. " 

@alextopuzov and I are currently in the process of reorganizing the docs to correspond to the merging of the old Harbor/Admiral UIs, so the doc links for the registry and management portal will no longer be valid in 1.2.

**Comment by ali5ter** [comment]
@stuclem great will update and post back here. Just provide me with the content you think suitable for v1.2 and we should make sure that the UI dev who takes this on understands what the URLs are.

**Comment by ali5ter** [comment]
@stuclem is the following what you described? ... https://vmware.invisionapp.com/share/85C9KS2KZ

**Comment by stuclem** [comment]
@ali5ter yes indeed.

**Comment by ali5ter** [comment]
Here's the workflow complete with content updates from @stuclem
https://vmware.invisionapp.com/share/9HCCN1WCK

Some links will change in Sprint 13 as the docs are updated but we will update the link annotations to make sure they reflect this.

**Comment by andrewtchin** [comment]
@ali5ter When would screen 1 vs screen 2 be shown?

**Comment by andrewtchin** [comment]
TODO
- [ ] show error message when entering wrong credentials
- [ ] Time out/show error when entering invalid vCenter server e.g. `1.1.1.1`

**Comment by ali5ter** [comment]
@andrewtchin The idea is that the simple screen that contains one card about the management portal is the default screen. Clicking on the 'Admin' button take you to the more complex layout. This talks to @karthik-narayan concern about presenting all admin info to a non admin user.

@karthik-narayan can you comment please

**Comment by andrewtchin** [comment]
When the OVA is first deployed, when they visit this page should they see the login info prompt? After the prompt, they should then see the one card view?

**Comment by ali5ter** [comment]
After the login dialog, they should return to the more complex 'admin' layout since the user at that point in highly likely to be the vSphere Admin. 

BTW, my assumption was that you can tell if the OVA is tagged or not, so we don't keep showing the login dialog. Is that correct?

**Comment by andrewtchin** [comment]
No we can't tell that without the admin credentials
We can tell if it's the first boot of the OVA and show something different if you think that's better than always showing the login

**Comment by jooskim** [comment]
I worked on static contents based on the latest [mockup](https://vmware.invisionapp.com/share/9HCCN1WCK#/screens/240561467). You could find the updated HTML code and resources at my [branch](https://github.com/jooskim/vic-product/tree/5458/static-contents/installer/fileserver/html)

**Comment by andrewtchin** [comment]
Awesome! I updated the tasks to reflect what's left after Josh's work on the static HTML resources.
