### ISSUE TITLE
--insecure-registry server not showing up in docker -H info

### ISSUE THREAD

**Issue by cwb124** [vmware/vic#5497]
Not sure if this is an issue with the --insecure-registry flag or how the info is pulled, but I have successfully created a VCH host using the following syntax:
`vic-machine-linux create --target VCENTER-APPLIANCE --user USER --password PASSWORD --insecure-registry 'https://hub.mycompany.net/' etc etc etc`

Builds successfully.  However when I do a docker -H 192.168.1.5:2376 --tls info it still shows the registry as the default one:  Registry: registry-1.docker.io

It's not changed to my private one and because this environment has no internet access I can't grab any images.  

I've also tried --insecure-registry with http and without the http:// and without single quotes.  Same result.

**Comment by stuclem** [comment]
Hi @cwb124, have you configured the Docker client with the registry's certificate, per https://vmware.github.io/vic-product/assets/files/html/1.1/vic_app_dev/configure_docker_client.html#registry?

**Comment by chengwang86** [comment]
I can reproduce this bug using our current code repo. `vic-machine inspect --conf` is able to show the correct value for `--insecure-registry`. It might be a bug in our code for `docker info`. However, it should not affect the functionality of pulling images from the insecure registry.

@cwb124 can you make the same deployment in an environment where your VCH is able to connect to the insecure-registry? I just want to confirm that `pull image` works even if `docker info` shows incorrect results.

**Comment by chengwang86** [comment]
Set the initial estimate to 2 if it is just a bug in `docker info`.

**Comment by frapposelli** [comment]
I've just validated that build 12685 has this bug solved.

VCH Created with:

```console
$ ./vic-machine-darwin create --target ***** --user ***** --password ***** --image-store vsanDatastore --tls-cname '*.eng.vmware.com' --force --volume-store vsanDatastore:default --cn PublicNetwork --bridge-network InternalNetwork --insecure-registry 10.160.213.153:8443 --name vic-engine-12685
```

`docker info` against the VCH shows:

```console
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: v1.1.0-rc3-12685-d914744
Storage Driver: vSphere Integrated Containers v1.1.0-rc3-12685-d914744 Backend Engine
VolumeStores: default
vSphere Integrated Containers v1.1.0-rc3-12685-d914744 Backend Engine: RUNNING
 VCH CPU limit: 67212 MHz
 VCH memory limit: 27.49 GiB
 VCH CPU usage: 832 MHz
 VCH memory usage: 13.38 GiB
 VMware Product: VMware vCenter Server
 VMware OS: linux-x64
 VMware OS version: 6.5.0
 Insecure Registries: 10.160.213.153:8443     <==== INSECURE REGISTRY SET
 Registry Whitelist Mode: disabled.  All registry access allowed.
Plugins:
 Volume: vsphere
 Network: PublicNetwork bridge
 Log:
Swarm: inactive
Operating System: linux-x64
OSType: linux-x64
Architecture: x86_64
CPUs: 67212
Total Memory: 27.49GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry-1.docker.io
Experimental: false
Live Restore Enabled: false
```

The other setting (`Registry:`) is not tuneable and it's the default registry that is tried if no registry host is specified in the command.

As an example:

```console
$ docker pull vmware/photon
```

is going to automatically resolve to:

```console
$ docker pull registry-1.docker.io/vmware/photon
```

while specifying the registry host is making docker go direct to that host:

```console
$ docker pull 10.160.213.153:8443/vmware/photon
```

**Comment by mdubya66** [comment]
closing based on the last input
