### ISSUE TITLE
Provisioning of mariadb, postgres,mysql, crate  fails with "Unparseable JSON body: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path "

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5498]
**User Statement:**

https://10.197.37.132:8282/#/templates has template for mariadb which I tried to provision. Provisioning from Admiral UI hit the below error:
Unparseable JSON body: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $

**Details:**
![mariadb](https://user-images.githubusercontent.com/25006749/27224176-54c273c4-52b1-11e7-945c-0396233cb2a3.PNG)

docker-personality.log says
Jun 16 2017 09:53:48.543Z INFO  anonymous Volumes : []string{"/data"}
Jun 16 2017 09:53:48.543Z INFO  Processed volume arguments: backends.volumeFields{ID:"b1ca550a-5279-11e7-8a81-0050569dd196", Dest:"/data", Flags:"rw"}
Jun 16 2017 09:53:48.543Z INFO  Finalized Volume list : []backends.volumeFields{backends.volumeFields{ID:"b1ca550a-5279-11e7-8a81-0050569dd196", Dest:"/data", Flags:"rw"}}
Jun 16 2017 09:53:48.543Z INFO  Finalized model for volume create request to portlayer: &models.VolumeRequest{Capacity:-1, Driver:"vsphere", DriverArgs:map[string]string{"flags":"rw", "container":"crate-mcm793-45999646603", "image":"library/crate:latest"}, Metadata:map[string]string{"DockerMetaData":"{\"Driver\":\"vsphere\",\"DriverOpts\":{\"container\":\"crate-mcm793-45999646603\",\"flags\":\"rw\",\"image\":\"library/crate:latest\"},\"Name\":\"b1ca550a-5279-11e7-8a81-0050569dd196\",\"Labels\":null,\"AttachHistory\":[\"crate-mcm793-45999646603\"],\"Image\":\"library/crate:latest\"}"}, Name:"b1ca550a-5279-11e7-8a81-0050569dd196", Store:"default"}
Jun 16 2017 09:53:48.545Z ERROR Handler for POST /v1.24/containers/create returned error: No volume store named (default) exists
Jun 16 2017 09:53:49.162Z INFO  volumes found:
...
Jun 16 2017 10:03:18.457Z INFO  anonymous Volumes : []string{"/var/lib/mysql"}
Jun 16 2017 10:03:18.457Z INFO  Processed volume arguments: backends.volumeFields{ID:"057c4ca9-527b-11e7-8a81-0050569dd196", Dest:"/var/lib/mysql", Flags:"rw"}
Jun 16 2017 10:03:18.457Z INFO  Finalized Volume list : []backends.volumeFields{backends.volumeFields{ID:"057c4ca9-527b-11e7-8a81-0050569dd196", Dest:"/var/lib/mysql", Flags:"rw"}}
Jun 16 2017 10:03:18.457Z INFO  Finalized model for volume create request to portlayer: &models.VolumeRequest{Capacity:-1, Driver:"vsphere", DriverArgs:map[string]string{"flags":"rw", "container":"mysql-mcm799-45999651038", "image":"library/mysql:latest"}, Metadata:map[string]string{"DockerMetaData":"{\"Driver\":\"vsphere\",\"DriverOpts\":{\"container\":\"mysql-mcm799-45999651038\",\"flags\":\"rw\",\"image\":\"library/mysql:latest\"},\"Name\":\"057c4ca9-527b-11e7-8a81-0050569dd196\",\"Labels\":null,\"AttachHistory\":[\"mysql-mcm799-45999651038\"],\"Image\":\"library/mysql:latest\"}"}, Name:"057c4ca9-527b-11e7-8a81-0050569dd196", Store:"default"}
Jun 16 2017 10:03:18.459Z ERROR Handler for POST /v1.24/containers/create returned error: No volume store named (default) exists
Jun 16 2017 10:03:18.459Z INFO  Container CPU count: 2
Jun 16 2017 10:03:18.459Z INFO  Container memory: 2048 MB
Jun 16 2017 10:03:18.495Z INFO  Specified Volumes : []string{}
Jun 16 2017 10:03:18.495Z INFO  anonymous Volumes : []string{"/var/lib/mysql"}
Jun 16 2017 10:03:18.495Z INFO  Processed volume arguments: backends.volumeFields{ID:"05822391-527b-11e7-8a81-0050569dd196", Dest:"/var/lib/mysql", Flags:"rw"}
Jun 16 2017 10:03:18.495Z INFO  Finalized Volume list : []backends.volumeFields{backends.volumeFields{ID:"05822391-527b-11e7-8a81-0050569dd196", Dest:"/var/lib/mysql", Flags:"rw"}}
Jun 16 2017 10:03:18.496Z INFO  Finalized model for volume create request to portlayer: &models.VolumeRequest{Capacity:-1, Driver:"vsphere", DriverArgs:map[string]string{"flags":"rw", "container":"mariadb-mcm796-45999648818", "image":"library/mariadb:latest"}, Metadata:map[string]string{"DockerMetaData":"{\"Driver\":\"vsphere\",\"DriverOpts\":{\"container\":\"mariadb-mcm796-45999648818\",\"flags\":\"rw\",\"image\":\"library/mariadb:latest\"},\"Name\":\"05822391-527b-11e7-8a81-0050569dd196\",\"Labels\":null,\"AttachHistory\":[\"mariadb-mcm796-45999648818\"],\"Image\":\"library/mariadb:latest\"}"}, Name:"05822391-527b-11e7-8a81-0050569dd196", Store:"default"}
Jun 16 2017 10:03:18.497Z ERROR Handler for POST /v1.24/containers/create returned error: No volume store named (default) exists

port-layer

Jun 16 2017 10:03:18.399Z INFO  set log file name to: [CPBU_2TB_01] 5ca03ec60cb4df1858b6372e93b3161cc8a23a0688c4c6287434b26cce578a7b/tether.debug
Jun 16 2017 10:03:18.399Z INFO  set log file name to: [CPBU_2TB_01] 5ca03ec60cb4df1858b6372e93b3161cc8a23a0688c4c6287434b26cce578a7b/output.log
Jun 16 2017 10:03:18.401Z ERROR storagehandler: VolumeCreate error: storage.VolumeStoreNotFoundError{Msg:"volume store (http:///storage/volumes/default) not found"}
Jun 16 2017 10:03:18.457Z INFO  set log file name to: [CPBU_2TB_01] 1a90bc6368448d2d769aed214b5a7020d67855dc740fb0795f4b29fa9fc89352/tether.debug
Jun 16 2017 10:03:18.457Z INFO  set log file name to: [CPBU_2TB_01] 1a90bc6368448d2d769aed214b5a7020d67855dc740fb0795f4b29fa9fc89352/output.log
Jun 16 2017 10:03:18.458Z ERROR storagehandler: VolumeCreate error: storage.VolumeStoreNotFoundError{Msg:"volume store (http:///storage/volumes/default) not found"}
Jun 16 2017 10:03:18.495Z INFO  set log file name to: [CPBU_2TB_01] b1a44c3a9a0f99446d8df0b2f175e85eb8fe2cfc99175251fbc3d63b2d1d5149/tether.debug
Jun 16 2017 10:03:18.495Z INFO  set log file name to: [CPBU_2TB_01] b1a44c3a9a0f99446d8df0b2f175e85eb8fe2cfc99175251fbc3d63b2d1d5149/output.log
Jun 16 2017 10:03:18.497Z ERROR storagehandler: VolumeCreate error: storage.VolumeStoreNotFoundError{Msg:"volume store (http:///storage/volumes/default) not found"}

I enabled SSH for any additional log information needed. Attaching logs as well.

command used: ..VIC-11340/vic# ./vic-machine-linux debug -t administrator@vsphere.local:'Admin!23'@w3-stras-db06.eng.vmware.com/Datacenter -r Cluster/Resources --thumbprint B8:88:73:E7:07:44:C4:CD:CC:3D:B8:A2:0C:15:64:18:53:B9:D0:22 -n U-VIC-00046 --timeout 30m --enable-ssh --rootpw 'Admin!23'

VCH IP ;  10.197.37.178 
[VCH Logs.zip](https://github.com/vmware/vic/files/1080583/VCH.Logs.zip)

**Comment by chengwang86** [comment]
```
Jun 16 2017 09:53:48.545Z ERROR Handler for POST /v1.24/containers/create returned error: No volume store named (default) exists
```
It seems that the container requires a default volume-store tagged as `default`. 

@lgayatri Could you please provide the `vic-machine create` cmd you used to deploy the VCH? You may have to specify `--volume-store=your_datastore/volume_name:default` in `vic-machine-create`.

**Comment by lgayatri** [comment]
@chengwang86 , 
Please let me know if the below command is correct. 
./vic-machine-linux create --force -t administrator@vsphere.local:Admin\!23@w3-stras-db06.eng.vmware.com/Datacenter -r Cluster/Resources -i CPBU_2TB_01 -b vxw-dvs-47-virtualwire-50-sid-5049-VCH-LS-50 -n U-VIC-00051 --no-tlsverify --timeout 30m --public-network-ip 10.197.37.182/23 --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21 --management-network DPortGroup --public-network DPortGroup --volume-store=CPBU_2TB_01/volume_name:default --registry-ca=/etc/docker/certs.d/10.197.37.132/ca.crt 
...
Jun 19 2017 03:07:04.639-04:00 INFO  Checking VCH connectivity with vSphere target
Jun 19 2017 03:08:39.892-04:00 WARN  vSphere API Test: https://w3-stras-db06.eng.vmware.com vSphere API target failed to respond to the query
...

**Comment by chengwang86** [comment]
@lgayatri Is that vsphere target ` https://w3-stras-db06.eng.vmware.com` reachable by the VCH? What is the full vic-machine.log when running `vic-machine create`?

**Comment by lgayatri** [comment]
Yes, it was reachable. But I saw below error yesterday

Jun 19 2017 03:08:39.892-04:00 WARN  vSphere API Test: https://w3-stras-db06.eng.vmware.com vSphere API target failed to respond to the query

Jun 19 2017 03:36:50.207-04:00 INFO  Docker API endpoint check failed: context deadline exceeded
Jun 19 2017 03:36:50.207-04:00 INFO  Collecting b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
Jun 19 2017 03:36:50.604-04:00 INFO     API may be slow to start - try to connect to API after a few minutes:
Jun 19 2017 03:36:50.604-04:00 INFO             Run command: docker -H 10.197.37.182:2376 --tls info
Jun 19 2017 03:36:50.604-04:00 INFO             If command succeeds, VCH is started. If command fails, VCH failed to install - see documentation for troubleshooting.
Jun 19 2017 03:36:50.604-04:00 ERROR --------------------
Jun 19 2017 03:36:50.604-04:00 ERROR vic-machine-linux create failed: Creating VCH exceeded time limit of 30m0s. Please increase the timeout using --timeout to accommodate for a busy vSphere target

Today when I tried again, the same command worked.  Attached vic-machine.log for your perusal.
[vic-machine.zip](https://github.com/vmware/vic/files/1087979/vic-machine.zip)
...
Jun 20 2017 07:00:58.760-04:00 INFO
Jun 20 2017 07:00:58.760-04:00 INFO  Connect to docker:
Jun 20 2017 07:00:58.760-04:00 INFO  docker -H 10.197.37.182:2376 --tls info
Jun 20 2017 07:00:58.760-04:00 INFO  Installer completed successfully

Attempt to provision mariadb failed with Service https://10.197.37.178:2376/v1.24/containers/create?name=mariadb-mcm808-46351238786 returned error 500 for POST. id 40651977 message No volume store named (default) exists; Reason: {"message":"No volume store named (default) exists"}
in a minute.

Admiral is trying to place the template on an incompatible VCH. 10.197.37.182 is the VCH with "default" volume store but Admiral picked 10.197.37.178. I filed https://github.com/vmware/admiral/issues/118 .

AS a next step, I will remove incompatible VCHs from the Admiral and retry

**Comment by lgayatri** [comment]
After I removed the incompatible VCHs and had one VCH with volume-store defined, I was able to deploy successfully.
![image](https://user-images.githubusercontent.com/25006749/27368669-74c3a800-5671-11e7-8983-0c4cd2ef761e.png)
Thanks @chengwang86

**Comment by lgayatri** [comment]
Admiral UI should throw a more relavant ERROR message that throwing Unparseable: JSON body

**Comment by chengwang86** [comment]
Close this issue since the problem was resolved
