### ISSUE TITLE
nightly test 5-11-Multiple-cluster failed at fetching ESXi host IP - unknown host

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#5517]
Seen on vpshere 6.5

[5-11-Multiple-Cluster.zip](https://github.com/vmware/vic/files/1082844/5-11-Multiple-Cluster.zip)

From log.html
```
Executing command 'nimbus-ctl ip svc.victestuser-ESX-1958 | grep svc.victestuser-ESX-1958'
Command exited with return code 0.
${out} = sc-prd-vc016: svc.victestuser-ESX-1958: unknown
```
The test didn't catch this error though. Later on when the test executed 
```
Set Environment Variable GOVC_URL, root:@${ip}
Run govc host.account.update -id root -password ${NIMBUS_ESX_PASSWORD}
```
it threw an error `no such host` because the ip was set to `unknown`.

**Comment by chengwang86** [comment]
also seen in test-5-4-HA on vsphere 6.5
[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1092227/5-4-High-Availability.zip)

**Comment by rajanashok** [comment]
This is now resolved from Mikke's PR to add a timestamp to avoid naming conflict.

[5-11-Multiple-Cluster.zip](https://github.com/vmware/vic/files/1180191/5-11-Multiple-Cluster.zip)

https://github.com/vmware/vic/pull/5797
