### ISSUE TITLE
nightly test 5-3-ELM failed to deploy testbed

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#5520]
on vsphere 6.5 (not nimbus timeout issue)

[5-3-Enhanced-Linked-Mode.zip](https://github.com/vmware/vic/files/1083228/5-3-Enhanced-Linked-Mode.zip)

from log.html
```
sshpass -p pwd ssh -o ... 'nimbus-testbeddeploy --lease=1 --noStatsDump --noSupportBundles --plugin test-vpx --testbedName test-vpx-m2n2-vcva-3esx-pxeBoot-8gbmem --vcvaBuild ob-4602587 --esxPxeDir ob-4564106 --runName els-9061'
...
Waiting for process to complete.
Process completed.
${output} = <result object with rc 1>
```

**Comment by mhagen-vmware** [comment]
I have completely re-worked this test in a later code push.  With the existing logging (none) it is impossible to know why the deploy failed.  But with the latest code, we log the errors before checking RC, so if we hit something like this again we can debug further.
