### ISSUE TITLE
Seeing "Delete file" errors while creating VCH using VIC-11340(regression from 10888)

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5523]
**User Statement:**
Build : vic-v1.1.1-11340-4029cbe6.ova

This is a regression from vic-v1.1.1-10888-cc08c100.ova build.
On build 11340, I created VCH using 

./vic-machine-linux create --force -t administrator@vsphere.local:Admin\!23@w3-stras-db06.eng.vmware.com/Datacenter -r Cluster/Resources -i CPBU_2TB_01 -b vxw-dvs-47-virtualwire-50-sid-5049-VCH-LS-50 -n U-VIC-00052 --no-tlsverify --timeout 30m --public-network-ip 10.197.37.183/23 --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21 --management-network DPortGroup --public-network DPortGroup --registry-ca=/etc/docker/certs.d/10.197.37.132/ca.crt 
...
Jun 19 2017 04:56:40.829-04:00 INFO  Connect to docker:
Jun 19 2017 04:56:40.829-04:00 INFO  docker -H 10.197.37.183:2376 --tls info
Jun 19 2017 04:56:40.829-04:00 INFO  Installer completed successfully

![10888-pass](https://user-images.githubusercontent.com/25006749/27277498-127d270a-54fc-11e7-920b-cfa9931bb0fb.PNG)
![11340-error](https://user-images.githubusercontent.com/25006749/27277509-1b48a8d2-54fc-11e7-8e57-1854df871118.PNG)

VCH creation is successful, however in the VCSA's webclient I am seeing two errors fro "Delete file" task as shown in the screenshot attached . The same command works without reporting any UI errors with 10888.
Logs attached:
[vic-machine (2).zip](https://github.com/vmware/vic/files/1084388/vic-machine.2.zip)

On the same client VM I had extracted both 10888 and 11340 in different locations to compare. Hence concluding as regression from previous build.

**Comment by chengwang86** [comment]
@frapposelli @andrewtchin Any initial thoughts?

**Comment by emlin** [comment]
This problem should be related to @matthewavery 's change to retry image upload. It will try to remove the file if it exists, but if it's not, nothing wrong will happen.

This does not make any function problem except the error message generated in vsphere. Is that a high priority issue?
@matthewavery @mdubya66 @mhagen-vmware

**Comment by lgayatri** [comment]
Right, functionality is not impacted but vpxd.log reports an ERROR

2017-06-20T09:44:48.606Z info vpxd[37033] [Originator@6876 sub=Default opID=eb30333] [VpxLRO] -- ERROR task-126529 -- FileManager -- vim.FileManager.deleteFile: vim.fault.FileNotFound:
--> Result:
--> (vim.fault.FileNotFound) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = <unset>,
-->    file = "[CPBU_2TB_01] U-VIC-00052/V1.1.0-RC3-11340-9317B18-appliance.iso"
-->    msg = "Received SOAP response fault from [<cs p:00007f34b01d4de0, TCP:w2-hs2-d2612.eng.vmware.com:443>]: Delete
--> "
--> }
--> Args:
-->
--> Arg name:
--> "[CPBU_2TB_01] U-VIC-00052/V1.1.0-RC3-11340-9317B18-appliance.iso"
--> Arg datacenter:
--> 'vim.Datacenter:datacenter-21'

I think we should check if file exists before attempting to delete it to avoid this error.

**Comment by lgayatri** [comment]
Verified, no such errors are being seen.
![image](https://user-images.githubusercontent.com/25006749/29450957-693d76de-841e-11e7-8949-901622fe40d9.png)
