### ISSUE TITLE
State race when updating container config 

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5533]
Follow on from #5445 

The work delivered for #5445 significantly reduces the probability of hitting this scenario, but requires a vSphere fix to completely resolve, or moving off guestinfo (probably to #4062 but that itself has a similar potential issue in #4064).

This issue is to track the eventual vSphere solution to the problem, bug1898149

Estimate set to 1 - should be revised if vSphere response is working as designed.

@mdubya66 We need a label or similar for tracking product issues that impact us, or would this be `product/vsphere`?

**Comment by hickeng** [comment]
Bug1985862 may deal with this via other means - by preventing existing keys from becoming volatile irrespective of power state.

**Comment by renmaosheng** [comment]
bugzilla bug is resolved. we can close this.

**Comment by hickeng** [comment]
bug1898149 has been closed but it was closed as "not a bug" meaning vSphere is functioning as expected. That just means that the vSphere semantics do not match what we require for VIC, not that the problem has been resolved.
bug1985862 was fixed but not backported past 6.5 so we cannot rely on the fix until 6.0 goes out-of-service, and that fix does *not* address the state race.

I'm not reopening this bug for now but am noting the the root cause has not been fixed.
