### ISSUE TITLE
Create a new status check in github that prevents merges to master when builds are failing

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5545]
User statement:  As an engineer on VIC, I don't always know when we have a build break and shouldn't be merging to master so it would be nice to have an automated mechanism to prevent merges when in this state

Details:  Need to implement a new github status check and make it mandatory.  Needs to have a mechanism to override in case of emergency/need to merge the actual fix into master.

Acceptance criteria:
1. When a failure occurs, the status check will flag all further PRs as not-mergeable until it is fixed/someone manually overrides.

**Comment by caglar10ur** [comment]
gandalf is doing this now, will close this once I merge it into the repo
