### ISSUE TITLE
Remove plaintext password in ovfenv

### ISSUE THREAD

**Issue by RobTiki** [vmware/vic#5549]
Troubleshooting my issue where the vic portlet is not showing in html5 ui.  I stumbled on the config scripts for ova-webserver aka the fileserver process and ovfenv in the bin directory.  Running ovfenv list all the variables that were entered during the vic ova deployment.  passwords are in plain text.

Please find a way to encrypt the below password fields!

```
[appliance.root_pwd]
[registry.db_password]
[registry.admin_password]
```

file details:
```
root@vic-docker01 [ ~ ]# type ovfenv
ovfenv is hashed (/usr/bin/ovfenv)

root@vic-docker01 [ ~ ]# file $(which ovfenv)
/usr/bin/ovfenv: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped

root@vic-docker01 [ ~ ]# stat $(which ovfenv)
  File: '/usr/bin/ovfenv'
  Size: 2325184         Blocks: 4544       IO Block: 4096   regular file
Device: 801h/2049d      Inode: 274541      Links: 1
Access: (0750/-rwxr-x---)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-06-20 22:14:06.971691943 +0000
Modify: 2017-05-19 00:09:08.451079763 +0000
Change: 2017-05-19 00:09:08.451079763 +0000
 Birth: -

```

**Comment by chengwang86** [comment]
@frapposelli @andrewtchin Any initial comments?

**Comment by andrewtchin** [comment]
I'm not sure if we can store them hashed from the OVA deploy wizard. It sounds to me like we either need to unset these after use (not sure if that's possible) or have them instead entered into the initial setup screen (currently the demo VCH installer, later to be the OVA configuration service) after the OVA VM is powered on. The second option will have further impacts on how we start services since we won't be able to start Harbor until after the user input.

**Comment by hickeng** [comment]
there is password support in ovfEnv - don't recall what the subpath is, but it prevents retrieval in some circumstances. As Andrew has noted, these passwords should be purged from the ovfEnv once they've been applied.

**Comment by mdubya66** [comment]
This is a must fix for 1.2

**Comment by andrewtchin** [comment]
The root password can be erased from guestinfo after first boot

**Comment by andrewtchin** [comment]
Registry admin and db password will be removed by #4727. This issue should cover clearing `root_pwd`
