### ISSUE TITLE
Run admiral setup command at OVA startup

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#5551]
Admiral will provide a command that will:
* Setup OIDC/SAML-WS-TRUST for Admiral against the PSC,
* Create a few (most likely 3) “solution-users” in the PSC (Admiral, Harbor, VCH-content-trust), their ID and (potentially )keys will be outputted by this command. The generated output files should be stored on a volume which is accessible by the OVA init script and by the containers running Admiral/Harbor. It is not clear yet how many files will be generated (I believe there might be a couple of files per user)

This command needs to be run on OVA first run.

Acceptance:
* Admiral provided command runs at OVA first run

**Comment by andrewtchin** [comment]
Need to determine if this API will require creds

**Comment by hmahmood** [comment]
@andrewtchin it definitely does ... I think @lcastellano mentioned that in his email.

**Comment by anchal-agrawal** [comment]
Merged PR https://github.com/vmware/vic-product/pull/415 covers:
* registering Admiral with PSC to create PSC config and cert files
* not starting Admiral and Harbor until the above

The next steps are:
* starting Admiral in the OVA with the said PSC config file as a parameter (waiting on implementation details from Admiral)
* running the PSC tool's `get-token` command to create token files - this can be done with systemd unit(s)
* based on our discussions, Harbor startup should be blocked until the token file is generated.
