### ISSUE TITLE
Implement systemd script to periodically update solution user token in guestinfo

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#5554]
The OVA will create solution users via a cli tool provided by Admiral, with the certs put in a predefined location on disk (see #5551). In order for the VCH to utilize these users for authenticating against Adrmiral, they must be logged in to PSC, and the resulting token placed in guestinfo. The cli previously mentioned will provide the login functionality into PSC, and must be run periodically to renew the auth token, and put it in guestinfo. 

Acceptance:
- [ ] systemd script that runs periodically to acquire/renew token, and put it in guestinfo at a known key

**Comment by andrewtchin** [comment]
Working on the systemd updates to support this

**Comment by andrewtchin** [comment]
from @hmahmood:
add the admiral endpoint URL to guestinfo
would be nice to update guestinfo also if the ip changes
