### ISSUE TITLE
Update demo VCH installer to be interim OVA initialization service

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5561]
**User Statement:**
As a user I want to initialize the OVA after powering it on. 

**Details:**
Several initialization operations require vCenter credentials, which are only available after the user inputs them into a web service. Repurpose `engine_installer` to handle these tasks for 1.2

After the user enters their credentials, perform the initialization steps, and on the second screen provide feedback at the top if needed and display the Demo VCH setup fields.

Other tasks that require these credentials will then need to be added in a modular way to `engine_installer` so that they can be reused when we revamp the OVA initialization service for 1.3

**Acceptance Criteria:**
- [ ] Update demo VCH installer (`engine_installer`) branding to reflect new purpose (work with UX for naming)
- [ ] Document that this is a required step after OVA power on

**Comment by ali5ter** [comment]
@karthik-narayan please could you comment on this workflow and where (or if) it fits with the Appliance landing page experience. 

@andrewtchin where can I read more about this feature? I assume this is for v1.2. Is there an implementation (or video of the implementation) I can look at?

**Comment by ali5ter** [comment]
I am just learning about this and was reading https://github.com/vmware/vic/issues/4731

Some questions:
1. @andrewtchin  Are the pages designed for the 1337 web app? If there are, how do I see them?
2. If the vCloud Admin selects to install this 'default VCH', @karthik-narayan how do you imagine this affects the Appliance landing page experience? Seems like the Admin will just go straight into Admiral and start adding containers to the Host no?

**Comment by andrewtchin** [comment]
@ali5ter Yes see the sprint 10 recording starting at 10 min https://confluence.eng.vmware.com/display/CNA/Engine+Sprint+Demos

**Comment by ali5ter** [comment]
@andrewtchin Thanks, this is very informative. So this is an interim soln, to get a limited function VCH installed so an Admin can 'kick the tires' so to speak. However, it's yet another hidden URL which could be put in appliance console and described and linked from the Appliance landing page experience. Also, there's quite a bit that could be done to clean up the interactions, layout and information in the 1337 app.

**Comment by andrewtchin** [comment]
Yes this is until we get the full OVA initialization service in 1.3. The URL is in the appliance console already and they don't have to execute the create demo VCH step if they don't want - they can enter the admin credentials and click next to do the initialization steps we need without creating the VCH

**Comment by ali5ter** [comment]
@andrewtchin and I just talked about a requirement for the vSphere Admin to supply their vSphere credential after standing up the Appliance (OVA) so as to make the vSphere API call to tag the VM to make it findable to achieve Docker content trust. 

This is done in the demo VCH installer UI but we need this to happen outside of that workflow since the demo VCH installer may not be the critical path to installation for v1.2.

### suggested soln for v1.2

The 'getting started' page is the Appliance landing page fills the workflow gap between OVA installation and post activities to deploy VCH/Kube and explain the configuration activities in the Management Portal. 

For v1.2, as part of the post activites, we could include an interaction that asks the user for the vSphere credential and performs the tagging API call.

@karthik-narayan @stuclem ^

**Comment by andrewtchin** [comment]
@ali5ter Yes that is correct. Let us know where you would like us to accept the credentials for this (i.e. should the demo installer on port 1337 do this, or should the demo installer remain standalone and we add a screen to accept credentials on the fileserver on port 9443 and add the landing page there)

**Comment by ali5ter** [comment]
@andrewtchin  Let's keep the demo installer standalone for v1.2. I'd like to make this specific action of providing the vSphere Admin's password as minimal as possible in the 'getting started' page if possible.

To Brad's point on a call last week, where this 'getting started' page is hosted is an implementation detail.

**Comment by andrewtchin** [comment]
It is an implementation detail, but one that needs UX feedback since we have 2 places we can run it so sounds like we'll be using the fileserver. I'm cool with keeping the demo installer standalone for 1.2.

**Comment by ali5ter** [comment]
this is still work-in-progress since I'm still working with @stuclem on content, but the 'getting started' workflow incl. the requirement to ask the user for their vSphere credentials can be see at: https://vmware.invisionapp.com/share/MGCBUOV4N
(also posted to slack channel #vic-ux)

**Comment by andrewtchin** [comment]
Looks good thanks @ali5ter

**Comment by ali5ter** [comment]
@andrewtchin regarding where this page is hosted, there appear to be two options:
1. Make sure we have httpd running behind port 80 on the appliance IP or
2. Host this at the existing httpd on port 9443 and redirect from port 80

While the experience is slightly cleaner for 1, the second options works well too.
Now that the page will include the smarts to tag the OVA VM, I'd have to defer to you which option is doable for v1.2.

**Comment by andrewtchin** [comment]
Currently we're not listening on 80 so we can redirect HTTP requests there to HTTPS on 9443, but the redirect probably won't happen in 1.2 https://github.com/vmware/vic/issues/4685
The primary location should continue to be 9443 since we have to serve over TLS and we can add the redirect to improve UX later

**Comment by ali5ter** [comment]
Here's the workflow complete with content updates from @stuclem 
https://vmware.invisionapp.com/share/9HCCN1WCK

Some links will change in Sprint 13 as the docs are updated but we will update the link annotations to make sure they reflect this.

**Comment by andrewtchin** [comment]
Looks good this is the right place. I'm not sure about our UI skills so we may need some help from @jooskim

**Comment by jooskim** [comment]
@andrewtchin It seems to me that the page content should be different based on the logged in user's persona. Content-wise, it doesn't really need to be a single page application, so how about rendering different HTML pages from the web server based on the role of the user?

**Comment by jooskim** [comment]
Sorry I haven't been following this topic very closely recently. Even if this is just a simple landing page for getting started documents where authentication or user validation logic is unnecessary, I don't see more than two simple HTML pages to be rendered.

**Comment by andrewtchin** [comment]
Yes it should only be 2 pages so far. This issue will cover getting backend functionality then we can do the UI under #5458
