### ISSUE TITLE
portlayer: lazy disk detach operations

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5565]
We have two orthogonal disk interfaces, one for IO interaction and another for lifecycle operations:
```go
type Archive interface {
   // Import data into a specific storage object
   Import(...)
   // Export data from a specific storage object
   Export(...)
```
The lifecycle operations are basically pure CRUD:
```go
type Store interface {
   // Create a storage object in the implementing store
   Create(...)
   // Inspect details of a specific storage object
   Read(...)
   // Modify core details of a specific storage object, e.g. max size,
   Update(...)
   // Delete a specific storage object
   Delete(...)
}
```
To support an efficient implementation of the existing `WriteImage` call using this interface separation we need to move to a deferred detach of disks from the endpointVM - this means that a detach call doesn't necessarily take immediate effect. The detach should take effect when:
1. a reconfigure is invoked for another operation - the easy opportunistic path - or 
2. a VM that references the disk has an event or operation performed on it - avoid locking a disk that may now be needed by a different VM - or
3. a given delay has lapsed - avoid a disk being held indefinitely and to support dual mode management

To support (1) in conjunction with a `pull` operation we need to confirm whether a single reconfigure operation can:
* detach disk A
* create and attach disk B where B is a child of A

If we can use a composite reconfigure operation for (1) then it will halve the number of vSphere calls for pulling of a given image.

Estimate is for initial check of composite reconfigure behaviour.

**Comment by caglar10ur** [comment]
@hickeng the short answer is yes, lazy detach works. For the long answer see the PR as I added a test case for that to make sure ESXi behaves as expected.
