### ISSUE TITLE
Integration tests for docker cp

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5566]
Acceptance Criteria:

- [ ] robot scripts to verify various docker cp scenarios to validate our design

---
The docker cp design we have is rather involved.  We need extensive robot scripts to tests these scenarios.

**Comment by matthewavery** [comment]
related ticket to this is #5562 This should be considered here as well

**Comment by jialin-li** [comment]
Most integration tests are merged in feature/docker-cp branch, not closing yet since we may add more tests before cp completes.

**Comment by jialin-li** [comment]
Integration tests merged in feature/docker-cp.
