### ISSUE TITLE
badge links from README failing

### ISSUE THREAD

**Issue by gliptak** [vmware/vic#5569]
https://coverage.vmware.run/vmware/vic

https://ci.vcna.io/vmware/vic

**Comment by corrieb** [comment]
These links both work for me. You need to authenticate via GitHub. I think you need to be added as a contributor to be able to auth, although I'm not sure. I can check that

Are you seeing an authentication error?

**Comment by willsherwood** [comment]
As far as I can tell, our CI and coverage apps are not visible to the public. And yet, we link to them as badges at the top of the README. I think that is the issue @gliptak is bringing, if I parsed it correctly.

**Comment by gliptak** [comment]
I see. Yes both of those are connected to Github OAuth without being a contributor.

The first one gets https://coverage.vmware.run/login?error=closed_regitration (note the misspelling)

I see build after logging in at https://ci.vcna.io/vmware/vic

But these being public repos, could their results be viewed without login? Are there settings an admin can change over there?

Thanks

**Comment by corrieb** [comment]
Yep I understand. It's a good question. I'm going to follow up...
