### ISSUE TITLE
Container connected to container-network: unable to get an IP address from DHCP server

### ISSUE THREAD

**Issue by guillierf** [vmware/vic#5591]
VIC 1.1

I am trying to instantiate a container connected to a NSX logical switch - but the operation fails because the container is unable to get an IP address from DHCP server.

VCH instantiation:
$ ./vic-machine-darwin create --target 10.40.206.23 --user administrator@vsphere.local --password VMware1! --public-network DPortGroup-VCH --bridge-network DPortGroup-CONTAINERS --compute-resource Cluster-VIC --image-store vsanDatastore --volume-store vsanDatastore:default --registry-ca=/tmp/ca.crt --container-network vxw-dvs-28-virtualwire-1-sid-5000-LS-WEB --name VCH-NSX --no-tlsverify --force
 

Container instantiation:
$ docker --tls run -d --network=vxw-dvs-28-virtualwire-1-sid-5000-LS-WEB ubuntu 
Unable to find image 'ubuntu:latest' locally
Pulling from library/ubuntu
75c416ea735c: Pull complete 
c6ff40b6d658: Pull complete 
a7050fc1f338: Pull complete 
f0ffb5cf6ba9: Pull complete 
be232718519c: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:a0ee7647e24c8494f1cf6b94f1a3cd127f423268293c25d924fbe18fd82db5a4
Status: Downloaded newer image for library/ubuntu:latest
edc23cf39e50016e7b64d0edb19dc16e13dc893893c9263176e409eb8f81dc6d
                              
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.40.206.23/sdk: context deadline exceeded.

on the console on the container, I can see:
INFO failed to find primary IP

notes:
-I have checked the DHCP server is working fine by using a standard UBUNTU VM connected on the same logical switch (the VM gets successfully a DHCP IP Address)
-I performed an another test using a DVS P-G (instead of a NSX LS) and same issue occurred

thanks in advance

**Comment by corrieb** [comment]
@guillierf Thanks for reporting. It would be really useful if you could use the vicadmin server to get a log bundle and attach it to the issue. 

@hmahmood Could you take a glance at this and see if there's anything obvious or known here. Thanks.

**Comment by hmahmood** [comment]
It looks like the VCH has trouble reaching the VC/ESX to create the container VM; don't think this is networking related. @guillierf are you sure your VCH is attached is attached to a network that can reach the VC IP 10.40.206.23? The management network default to DPortGroup-VCH; you may have to explicitly specify a different network with `--management-network` when creating the VCH.

**Comment by guillierf** [comment]
@corrieb As requested, attached is the log bundle.
[logs.zip](https://github.com/vmware/vic/files/1106755/logs.zip)

**Comment by hmahmood** [comment]
Routing table on vch:
```
default via 10.40.206.253 dev client 
10.40.206.128/25 dev client  proto kernel  scope link  src 10.40.206.245 
172.16.0.0/16 dev bridge  proto kernel  scope link  src 172.16.0.1 
```
With that network, 10.40.206.23 will go out the default route. So I think the vch networking config is not correct. @guillierf you will need to connect the VCH to another network that can route 10.40.206.23.

**Comment by guillierf** [comment]
@hmahmood there is no network connectivity issue between VCH and VC/ESX. I can successfully create a container connected to the bridge-network. Something like this works fine: docker --tls run -p 8081:80 nginx.

As mentioned in the initial case, issue occurs when creating a container connected to the container-network (NSX logical switch - or even - DVS Port-Group)

It would help me if you could confirm this scenario has been tested. Thanks in advance!

**Comment by hmahmood** [comment]
The container VM may encountered some error, which would in that error too. Can you post the container logs as well? The earlier bundle did not have them.

**Comment by guillierf** [comment]
here it is
[container-logs.zip](https://github.com/vmware/vic/files/1106974/container-logs.zip)

for info, I just made a new test before the logs are generated:

$ docker --tls run -d --network=vxw-dvs-28-virtualwire-1-sid-5000-LS-WEB ubuntu
fdb68aeb9eb76d02b5a7259fb2a1595391e91ac27925330fbbbb93c101666953
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.40.206.23/sdk: context deadline exceeded.

**Comment by hmahmood** [comment]
@guillierf is there a dhcp server available on vxw-dvs-28-virtualwire-1-sid-5000-LS-WEB? From the logs it looks like no dhcp request is being sent, and since no ip range was specified for the network (with `--container-network-ip-range` the container is coming up with no ip.

**Comment by guillierf** [comment]
yes, there is a DHCP server available on vxw-dvs-28-virtualwire-1-sid-5000-LS-WEB.
To make sure it works, I instantiated a UBUNTU VM (standard VM) on it - and it successfully get an IP address from DHCP server

**Comment by hmahmood** [comment]
Do you see the container VM connected to right port group in the VC UI?

**Comment by guillierf** [comment]
yes - I have checked this (and status is connected).
on the container console, I can see "INFO failed to find primary IP"

**Comment by hmahmood** [comment]
This is puzzling. Would you mind recreating your VCH with `--debug 3`, creating the container, and posting the container logs here again? Thanks.

**Comment by guillierf** [comment]
here it is
[container-logs-pb-container-network.zip](https://github.com/vmware/vic/files/1113819/container-logs-pb-container-network.zip)

**Comment by renmaosheng** [comment]
vic 1.5 now support nsx-t please try the new version, and reopen this if you still hit issues.
