### ISSUE TITLE
Specify Docker Machine integration for VCH creation

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#56]
Docker Machine will be one of the ways in which a VCH can be created. We need to understand how flexible the plug-in model is so that we can come up with a specification for how Docker Machine might be able to drive both vSphere admin tasks and user tasks.

**Comment by hickeng** [comment]
@karthik-narayan @mdubya66 Is this considered critical for 1.0? If not please move it to the icebox.

**Comment by mdubya66** [comment]
IIRC we said it was not critical and would vote to put it in the icebox. @karthik-narayan should confirm.

**Comment by karthik-narayan** [comment]
Not critical for 1.0
