### ISSUE TITLE
Move tether out of vic/cmd/tether

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#560]
This is a code cleanup task.

Not everything in tether belongs in the `main` package.  This needs to be split up such that `main()` actually lives in `package main` and the rest of the code lives elsewhere.  I suggest moving everything that doesnt belong in `package main` to `vic/tether`.

Also there's a bit of test code (code that is only called from tests) living in `package main` and not in `_test.go`.  This needs to be pruned and  files renamed/repackaged appropriately.

**Comment by fdawg4l** [comment]
This is likely a dup and subsumed by something more useful.  Enjoy!

**Comment by hickeng** [comment]
@fdawg4l closing as this should be addressed by the tether lib/cmd split.
