### ISSUE TITLE
share templates across VCHs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#563]
When using vmfork enabled VCHs as a tenancy mechanism in large numbers it's necessary to share the vmfork templates between those VCHs using the same bootstrap versions. This allows amortization of the template overhead across all containerVMs and not just those within a single VCH.

This is a core scenario for service provider usage and for on-prem dev/test.

This requires a mechanism for discovering templates and performing reference counting of some kind. As an initial implementation it's acceptable to have the location of templates specified by the admin, however we should still manage template versions within that location or the upgrade paths become problematic.

**Comment by hickeng** [comment]
@higebu is strongly in favour of having templates shared across VCHs

**Comment by fdawg4l** [comment]
@hickeng what is the tradeoff in sharing vs having a 1:1 mapping?
