### ISSUE TITLE
Implement offline containerstatpath

### ISSUE THREAD

**Issue by jialin-li** [vmware/vic#5632]
**User Statement:**

As a developer I want containerstatpath() to return file stat given a path. This should work when the path belongs to an offline container.

**Details:**
Cases: 
path points to a r/w layer of an offline container
path points to a volume of an offline container
path points to a shared volume of an offline container and some other containers

Problem: 
If path points to a shared volume and is in use, cannot mount that volume to stat the path.

**Acceptance Criteria:**
Show that file stat will be returned.

**Comment by hickeng** [comment]
Using the DataSource approach this should easily apply to the online case as well as the offline case.

**Comment by jialin-li** [comment]
this is merged into the feature/docker-cp branch, implementation is done.
