### ISSUE TITLE
Cannot see vic downloadables on :9443 despite registering with VCSA

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5638]
![image](https://user-images.githubusercontent.com/25006749/27872495-9a1c3724-61c6-11e7-8200-66e915c66518.png)

But the service is running
root@vic-st-h2-132 [ ~ ]# systemctl status fileserver
● fileserver.service - VIC Unified Installer Web Server
   Loaded: loaded (/usr/lib/systemd/system/fileserver.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-07-05 03:52:51 UTC; 11h ago
     Docs: https://github.com/vmware/vic
 Main PID: 830 (start_fileserve)
    Tasks: 8
   Memory: 24.0M
      CPU: 1.878s
   CGroup: /system.slice/fileserver.service
           ├─830 /usr/bin/bash /etc/vmware/fileserver/start_fileserver.sh
           └─856 /usr/local/bin/ova-webserver --addr :9443

Jul 05 10:51:59 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:51:59Z" level=info msg="render: html/index.html"
Jul 05 10:51:59 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:51:59Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 05 10:51:59 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:51:59Z" level=info msg="render: html/index.html"
Jul 05 10:51:59 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:51:59Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 05 10:52:37 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:52:37Z" level=info msg="server URL: {  Administrator%40vsphere.loca...e  }\n"
Jul 05 10:52:37 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:52:37Z" level=info msg="validation succeeded"
Jul 05 10:52:38 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:52:38Z" level=info msg="render: html/index.html"
Jul 05 10:52:38 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:52:38Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 05 10:52:38 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:52:38Z" level=info msg="render: html/index.html"
Jul 05 10:52:38 vic-st-h2-132.eng.vmware.com start_fileserver.sh[830]: time="2017-07-05T10:52:38Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Hint: Some lines were ellipsized, use -l to show in full.

Build: https://storage.googleapis.com/vic-product-ova-builds/vic-v1.1.1-11983-dff78ac0.ova

**Comment by morris-jason** [comment]
@andrewtchin @jialin-li 
I don't see downloadable links here: https://github.com/vmware/vic-product/blob/master/installer/fileserver/html/index.html
There's only a login validation check.

**Comment by morris-jason** [comment]
Looks like the downloadables are being hosted at `https://<ova-ip>:9443/files/`

**Comment by andrewtchin** [comment]
Files are under the route Jason described, closing.

**Comment by lgayatri** [comment]
@andrewtchin , is this temporary location or is :9443/files going to be the location for us to pick?

**Comment by lgayatri** [comment]
If this is not an interim location, then we should let @stuclem know that this needs documentation update for 1.2

**Comment by andrewtchin** [comment]
This is permanent. We have work in 1.2 that will obsolete the need for the user to directly view the directory listing of files, but I did put a note to document the new location as part of that work.

**Comment by lgayatri** [comment]
Ok, thanks @andrewtchin

**Comment by lgayatri** [comment]
@andrewtchin BTW, why is this "Getting Started" blank?

**Comment by jialin-li** [comment]
@lgayatri I believe that page is still being finalized and the UI discussion for it is under this issue #5458
