### ISSUE TITLE
Add OVA initialization API

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5639]
**User Statement:**
As a tester I want to be able to non-interactively provide vSphere credentials so the newly deployed OVA can be initialized.

**Details:**
Add a route that can accept the vSphere admin credential and then run the same initialization steps as the UI based landing page.

**Acceptance Criteria:**
- [ ] API is served over TLS only
- [ ] API performs OVA initialization after accepting vSphere credentials

**Comment by lgayatri** [comment]
I agree with @andrewtchin. With OVA power on itself, we need its serviceability. It is difficult to open browser of each OVA and present the VCSA FQDN and creds

**Comment by andrewtchin** [comment]
Lack of this will block system testing
