### ISSUE TITLE
vmfork based appliance

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#564]
There is no inherent reason why the VCH applianceVM cannot be forked from the containerVM template, further reducing the VCH overheads. This does add some additional fragility to VCH reboot as the template has to come up and fork successfully, prior to the applianceVM being able to power on.

I'm unsure if this additional dependency can be expressed in vApp dependency rules so it may be necessary to have vic-machine involved in a reboot in this scenario - may imply that standard vSphere FT cannot be used with the appliance in this deployment model.

**Comment by fdawg4l** [comment]
@hickeng can you fill this in? What does this mean, how is it different from the appliance now, and what's the use case? Thanks!

**Comment by hickeng** [comment]
@fdawg4l You're way too fast this morning - I was still filling in the descriptions when your comment appeared!
