### ISSUE TITLE
Unable to deploy a vch instance

### ISSUE THREAD

**Issue by upuvvad1** [vmware/vic#5645]
Hi All,
I am new to the VIC world, and am trying to setup a simple environment with 4 hosts.
I am trying to create a vch host from the linux machine as follows.

` ./vic-machine-linux create --target https://172.20.0.1/GenScale -u administrator@vsphere.local -p Password-1  --bridge-network vic-bridge --no-tlsverify --image-store vic_ds --force --compute-resource BDW_SUT --no-tls`

Jul  5 2017 21:25:20.501Z INFO  ### Installing VCH ####
Jul  5 2017 21:25:20.501Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Jul  5 2017 21:25:20.501Z WARN  Configuring without TLS - all communications will be insecure
Jul  5 2017 21:25:30.633Z ERROR Create cannot continue: failed to create validator
Jul  5 2017 21:25:30.634Z ERROR --------------------
Jul  5 2017 21:25:30.634Z ERROR vic-machine-linux create failed: Failed to connect to 172.20.0.1: Post https://172.20.0.1/sdk: net/http: TLS handshake timeout

Even though, I triggered the vch deployment with notls verify, the create command fails with tls handshake timeout.

Can someone throw light on this issue.

**Comment by emlin** [comment]
`--target https://172.20.0.1/GenScale`
The target is the address of your vSphere, could ESXi or VC. Looks like this address is unreachable from your desktop. Is that the correct address?
btw, you don't have to write https there, the format is `<ip/fqdn of vSphere>/datacenter`

**Comment by corrieb** [comment]
@upuvvad1 did this solve your problem? You'll find a lot of useful info here: https://www.youtube.com/watch?v=7WRFhJLZHJI

**Comment by mdubya66** [comment]
Closing this issue. Reopen if it's seen again.
