### ISSUE TITLE
vmfork base container VMs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#565]
Anything and everything relating to getting vmfork based containerVMs up and running in an efficient fashion, including base function that was present in Bonneville.

**Comment by higebu** [comment]
Please do not create template VMs by each VCH.

**Comment by fdawg4l** [comment]
@higebu Thanks for taking in interest in VIC!  

Can you explain the requirement from your perspective?  What is your concern relating to template VMs per VCH?

**Comment by higebu** [comment]
The reason was explained by @hickeng on #563. Thanks.

**Comment by mdubya66** [comment]
needs review given the state of vmfork

**Comment by hickeng** [comment]
@mdubya66 still relevant, although the detail of the mechanism may have changed.
Some of the detail for this should be addressed by #3636 in the checkpoint considerations and sample workflows.
