### ISSUE TITLE
Update project's README.md with new features

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#5668]
Our current README (particularly, the`Project Status` section) has not been updated in quite a while. We should add updates from our latest release(s) to it.

Estimated as a 2 since the work involved spans the entire project and will need input from all component owners.

**Acceptance Criteria:**
* [x] The `Project Status` section is updated with major features
* [x] Other sections are checked for validity and corrected if necessary

**Comment by corrieb** [comment]
Agreed. I would recommend that project status be its own section where each release has its major features called out. This is where we can link to upcoming features too.

**Comment by anchal-agrawal** [comment]
#6974 covers this - closing.
