### ISSUE TITLE
Drone build cleanup images

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#567]
Drone workers frequently run out of space
`ApplyLayer exit status 1 stdout:  stderr: write /go/src/github.com/vmware/vic/bin/vic_637.tar.gz: no space left on device`

Cleanup images that are left behind from build.

**Comment by sgairo** [comment]
Are you looking to just clean up all images after each build? Or a more specific approach?

**Comment by mdubya66** [comment]
Closing. We have a completely new CI setup now.
