### ISSUE TITLE
OVA VM should have a Guest OS name similar to that of VCH or Container VM

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#5678]
**User Statement:**
As a UI engineer I'd like to ensure that the VCH creation wizard always talks to the latest OVA appliance endpoint.

**Details:**
(Note: This story discusses 1.3 features that are not yet fully designed/implemented, but an initial discussion already took place with @andrewtchin and @emlin)

After the user clicks on the 'deploy' button in the final step of VCH creation wizard, the wizard will make a request to the VCH installer API which is served on the OVA appliance. For this, the UI needs to know the IP address to the correct OVA appliance.

vSphere Web Services API provides a mechanism to filter objects which is already used [here](https://github.com/vmware/vic/blob/master/ui/vic-ui-h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java#L240) to distinguish VCH and Container VMs from other VMs. Same could be done for the OVA appliance, as the appliance's Guest OS name currently shows up as `Other 3.x or later Linux (64-bit)`, which is not unique to distinguish it from others. Following the convention set forth [here](https://github.com/vmware/vic/blob/e6619e378e85f129466c82675dcd4d3ea39c7e4a/doc/design/telemetry/README.md), this could be renamed to something like `Photon - vSphere Integrated Containers appliance, build #, commit hash`. It will also make it possible to easily detect what the latest version of the OVA is in case there are multiple VIC OVA appliances on the target VC.

**Acceptance Criteria:**
VIC OVA appliance should have a guest OS name that looks like `Photon - vSphere Integrated Containers appliance, build #, commit hash`

**Comment by jooskim** [comment]
@ali5ter @lweitzman if we have multiple OVA appliances deployed, do you think it makes more sense to ask the user, in the VCH creation wizard, which version of VCH they want to deploy, or is it ok to just to proceed with the latest OVA version found in the target VC?

**Comment by andrewtchin** [comment]
@hmahmood

**Comment by lweitzman** [comment]
@jooskim @ali5ter i think defaulting to the latest and not having to bother the user is the right think to do. would there be a use case where a user would want to use a previous version? if thats the case then we could provide a drop down of versions that defaults to the latest. but i would think thats a P1 or P2

**Comment by hmahmood** [comment]
@jooskim agree with @lweitzman . The OVA appliance does have unique tags that can be used to "discover" it. See https://github.com/vmware/vic-product/pull/365

**Comment by jooskim** [comment]
@hmahmood I did try that yesterday, but the problem is that the tag didn't show up in MOB which is what I use to validate data I get from the vSphere Web Services API. It seems that the API doesn't seem to tags properly, as I can still see the tag in the H5 Client and Flex Client.

**Comment by hmahmood** [comment]
We're using the VC REST tag API; have you tried that?

**Comment by jooskim** [comment]
@lweitzman Thanks Louis. That's what I feel too. @karthik-narayan, please let us know your thoughts on how multiple OVA deployments should be taken into consideration for VCH creation wizard.

**Comment by jooskim** [comment]
I don't think UI service doesn't support that for object filtering, as what you used seem to be coming from the vSphere Automation SDK. FYI, this is how I filter vSphere objects in the service using the vSphere Web Services API: https://github.com/vmware/vic/blob/master/ui/vic-ui-h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java#L240

**Comment by jooskim** [comment]
Tag shows up in H5C as follows:
![image](https://user-images.githubusercontent.com/3834071/28077060-38120d60-6626-11e7-81d6-334477f26e99.png)

However, the MOB shows `tag` as empty:
![image](https://user-images.githubusercontent.com/3834071/28077103-607e36b6-6626-11e7-98e9-2c1feb229b09.png)

**Comment by hmahmood** [comment]
So H5C is using the automation api. The api itself is pretty simple; there is an "explorer" available at `/apiexplorer`. It may not be as much work as you think.

**Comment by jooskim** [comment]
So I am looking for a method for VM that allows me to filter VMs by tag, but I can't find any. Which method should I used for that? `/rest/com/vmware/cis/tagging/tag` doesn't seem to offer what I want.

**Comment by jooskim** [comment]
Not sure how tagging through this REST API alone makes it possible VIC OVAs discoverable when the vSphere Web Services API is not aware of it. Also I would like to stay away as much as possible from mixing two APIs.

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #920](https://github.com/vmware/vic-product/issues/920) via [**ZenHub**](https://www.zenhub.com/)
