### ISSUE TITLE
SECURITY: Populating /dev/random entropy should be built-in

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#5680]
**User Statement:**

As a container developer, I need a dynamically populated entropy pool when the container starts so that calls to /dev/random don't block.

**Details:**

When a container VM starts, it has zero entropy. As a result, it can take Tomcat server minutes to start while it waits for sufficient entropy. This is not the only problem inherent in low entropy. The quality of the entropy pool has a direct impact on the quality of SSL/TLS and other block ciphers.

User impact of this is that they have to either wait for minutes until their application is usable, they can switch to /dev/urandom (less secure) or they can install haveged and try to figure out how to make it run as a daemon process. 

This latter solution is the most "correct" approach, but containers are not designed to run multiple processes, so this forces the user to either start haveged with docker exec or to create a script that correctly deals with the signal handling. Both these options are pug ugly.

We already copy haveged into bootstrap.iso, but we never actually initialize and run it. I would strongly suggest that we investigate what it would take to do this, because I can guarantee that a customer is going to run into this issue and it will suck for them.

Long-run, this should be handled by para-virtualization and @hickeng has make this request. We cannot afford to wait for this capability before coming up with a reasonable solution.

**Acceptance Criteria:**

A container VM should have a dynamically populated entropy pool when it starts up.

**Comment by corrieb** [comment]
Added the user-doc label too as we should document this

**Comment by stuclem** [comment]
Tracking doc update for 1.3 in https://github.com/vmware/vic-product/issues/511. Removing user-doc label.
