### ISSUE TITLE
VIC Port layer reporting socket: too many open files

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic#5685]
When using Admiral with VCH endpoint seeing messages in the logs similar to:

**Port-layer.log**
ServerFaultCode: A specified parameter was not correct: spec.url

accept4: too many open files; retrying in 5ms

**Docker-personality.log**
ERROR Handler for GET /v1.21/volumes returned error: error from portlayer server: Get http://127.0.0.1:2377/storage/volumes: dial tcp 127.0.0.1:2377: socket: too many open files

ERROR Handler for GET /v1.21/containers/json returned error: Error invoking GetContainerList: Get http://127.0.0.1:2377/containers/list?all=true: dial tcp 127.0.0.1:2377: socket: too many open files

**Version**: `1.1.1`

bug-ref 1912860

**Comment by vburenin** [comment]
Could you please login to VCH and get an output of ```netstat -ap```?

You will need to install netstat util following these steps:
```
rpm --rebuilddb
tdnf install net-tools
```

**Comment by vburenin** [comment]
Output can be really long due to many opened files, it might be better to attach it as a file.

**Comment by hmahmood** [comment]
Also `lsof` output. You can install `lsof` with `tdnf install lsof`.

**Comment by dbarkelew** [comment]
"ServerFaultCode: A specified parameter was not correct: spec.url" Found this was due to the url using vMotion IP instead of the ESXi management IP. Resolved by placing host in maintenance mode, remove esxi from vcenter and add back to vCenter. 

Still experiencing other symptoms.

**Comment by hickeng** [comment]
I'm finding that with this fix, following logs gets dropped after a short time. This is observed on the #5700 branch which includes a fix on the close path of the stream_handlers which may be relevant. I've not verified one way or another on unmodified master.
