### ISSUE TITLE
docker network create fails after creating and deleting 15 networks: "could not find IP range for mask ffff0000"

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#5694]
**User Statement:**

As a VCH user, I need to be able to run applications which may create and delete networks. Once a network is deleted, the resources should be available for re-use.

**Details:**

```
#!/bin/bash

for i in $(seq 1 20); do
   docker network create foo
   docker network rm foo
done
```
This works for 15 networks and then you cannot create any more. The only option available at this point is to delete and recreate the VCH.

The error output is:

`could not find IP range for mask ffff0000`

It would seem that maybe we're maybe incrementing through IP ranges and we run out at some point? It's one thing to have a maximum number of networks created at once, but this is an absolute limit of the number of networks that can be created for the lifetime of the VCH.

**Acceptance Criteria:**

Due to the unrecoverable nature of the error, this is a high priority bug without question.

**Comment by sflxn** [comment]
Hey, there was a similar bug found back in VIC 1.1, #4157

**Comment by mdubya66** [comment]
Closing as a dupe of the older issue and removing from 1.2. We should look at this for 1.3
