### ISSUE TITLE
Remove container VMs created by VCH during forcing re-install

### ISSUE THREAD

**Issue by emlin** [vmware/vic#570]
vic-machine will remove existing VCH if that name exists already, but the delete operation does not remove existing containers.
After the VCH is redeployed, those container VMs will lose control from VCH.

**Comment by hickeng** [comment]
This definitely needs to occur, and should not be dependent on using the docker API to list the containers to delete.
This should iterate over the children of the resource pool/vApp of the VCH and delete the child VMs.

For now we can assume that all VMs in that pool are managed by the VCH, but it would be sensible to check for the presence of the containerVM extraconfig entries and, if a VM is found that doesn't have them, refuse to delete anything without -force. This will hopefully prevent us from deleting non-managed VMs in the case where someone has misunderstood the RP structure or misplaced a VM.

**Comment by emlin** [comment]
Had function in vic-machine delete, and removed force reinstall.
