### ISSUE TITLE
vic-machine: fails to delete image store fully

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5701]
**Story**
As a VIC user I expect to be able to delete a VCH then create a functioning new VCH in the same location
As a viadmin I expect vic-machine to either clean or or warn about any residual state from an old VCH that a new VCH cannot handle

**Detail**
If deleting a VCH with an image VMDK attached to the endpointVM the image store is not fully deleted. The vmdks are left, but the manifests and metadata are deleted. This is a state from which the storage portlayer cannot currently recover.

Symptoms - on a freshly deployed VCH:
```
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
27144aa8f1b9: Extracting [==================================================>] 699.2 kB/699.2 kB
a3ed95caeb02: Download complete
docker: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:parent (scratch) doesn't exist in http:///storage/images/564d1419-3188-ef2d-c147-e384c085ddb0: cannot stat '[datastore1] image/path/VIC/564d1419-3188-ef2d-c147-e384c085ddb0/images/scratch/manifest': No such file}.
See 'docker run --help'.
```

**Acceptance**
- [ ] vic-machine create/reconfigure checks the target image store to ensure it either doesn't exist or is functional
- [ ] vic-machine delete detaches disks from the endpointVM before attempting to delete images

**Comment by hickeng** [comment]
Adding to 1.2 as the odds of this occurring increase with the addition of cp/diff/commit/push.

**Comment by corrieb** [comment]
@hickeng Does a subsequent call to vic-machine create clean up? If not, does the user have to go and clean up the datastore manually? If so, I'd say this is a higher priority.

**Comment by gigawhitlocks** [comment]
Note that this issue occurs only while the disk is attached to the _appliance_, so this is during diff/cp/commit/push/pull operations, but not after they're completed & the disk is attached to the container vm. After the disk has been attached to the container vm, delete functions normally.

**Comment by hickeng** [comment]
I believe the problem is that:
a. we try to delete the manifests/metadata first instead of the potentially locked vmdk
b. the vmdk is locked because it's attached to the powered on applianceVM, so we should ensure all disks are detached from the applianceVM before we delete images, same as we should do for containerVMs before we delete them to avoid volume deletion.
