### ISSUE TITLE
Once Container is in error state will not return to running state

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic#5704]
Once a container is in a error state due to health check failure the container will not change out of the error state.

This can be reproduced by reboot the the VIC VCH that deployed the container or disconnecting the network that admiral is on temporarily.

bug-ref 1914805

**Comment by dbarkelew** [comment]
https://github.com/vmware/admiral/issues/127

**Comment by corrieb** [comment]
We need more information about how this might be reproduced. What is the "health check" in reference to here? How is an "error state" induced and how is it defined? How do you demonstrate that the container doesn't return to running state.

If you can list a series of steps or commands that can reproduce the problem and/or provide a log bundle, that would be v helpful. Thx

**Comment by hickeng** [comment]
@dbarkelew Is this still current?

**Comment by dbarkelew** [comment]
@hickeng The way that health check flow is handled was changed. Updating Admiral to get the changes resolved this issue. The issue can be closed.
