### ISSUE TITLE
Add proper check for locked VMDK in NewDataSource/Sink paths

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5713]
Applies to #5700 

Currently the check for whether the VMDK is locked simply returns `true` and fails over to the online path irrespective of actual failure.
Even if we want to keep the assured failover, we should correctly check.

The error we're looking for appears in reason chain:
```
types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.fileio.lock", Arg:[]types.KeyAnyValue(nil), Message:"Failed to lock the file"}
```

Implementation is in `vmdk.go:IsLockedError`

**Comment by jialin-li** [comment]
Fixed this with [this commit](https://github.com/jialin-li/vic/commit/a62deb5b47c0778fa178f9fb1364d7f481f8a280), can merge once #5700 is in
