### ISSUE TITLE
Add tether support for label relative paths

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5715]
Applies to #5700 

To support online copy to volumes, we locate the current owner of a volume to perform the copy. There is no assurance that this is the container by which the command was initiated (that container could be offline and the volume in use by another), or that the path on which the volume is mounted is the same.
As such we will address the volume via `label://disk-label/sub/path/on/volume` and the tether should understand this construction.

The toolbox already has URL support for the file transfer paths and can switch implementations based on scheme.

**Comment by dougm** [comment]
@hickeng does this need to be a new scheme/handler or can label just be a query param?  Ideally the latter, which would make it easier to re-use the existing archive handler.  For example:
```
/archive:/sub/path/on/volume?label=my-volume
```
Inside that converts to:
```
$(readlink -f /dev/disk/by-label/$label)/sub/path/on/volume
```

**Comment by hickeng** [comment]
@morris-jason I think this has been done if we've got functioning online copy for volumes. Can you close with reference to PR that added the function.

**Comment by morris-jason** [comment]
This will be functionally complete with the merge of #5835. Closing after PR merge in the morning.
