### ISSUE TITLE
Ensure Useful errors are propagated to the client on copy failure

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5717]
Applies to #5700 

Currently a copy failure may result in silent return (presumably a missing error return somewhere in the DataSink Import path), or a singularly useless error about Server internal error calling "archive reader" or "archive writer" returning an error.

If the error is anything user remediable then the user should get a useful message, for example:
* no such directory
* permission denied
* no such file

This may well include returning usefully typed errors from the portlayer swagger calls, e.g. 422 in the case of a failure to decode the filter spec.

**Comment by jialin-li** [comment]
Fix is merged in feature/docker-cp
