### ISSUE TITLE
Problem curl'ing port layer log

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5729]
I've observed two issues in this build (#5700): https://ci.vcna.io/vmware/vic/12327

1. Group0-Bugs.5343
2. Group9-VIC-Admin.9-02-VICAdmin-CertAuth

Both of these relate to not finding expected content in the port layer log. The second provides a really good hint at why the first failed:

```
Get Portlayer Log                                                     | FAIL |
'<!DOCTYPE html>
<html itemscope="" itemtype="http://schema.org/Organization" lang="en-US">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>VIC: VCH-12327-8972</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="stylesheet" href="css/clarity-ui.min.css">
    <link rel="stylesheet" href="css/fontello.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
    [ Message content over the limit has been removed. ]
                  <div class="sixty"><a href="/logs/init.log">Initialization & watchdog</a></div>
                  <div class="forty"><a href="/logs/tail/init.log">Live Log</a></div>
                </div>
                <div class="row">
                  <div class="sixty"><a href="/logs/vicadmin.log">Admin Server</a></div>
                  <div class="forty"><a href="/logs/tail/vicadmin.log">Live Log</a></div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  </body>
</html>' does not contain 'Launching portlayer server'
```

It looks like we've got the index page instead of the portlayer log. Took a look at vicadmin log, but didn't see an obvious cause, however I'm unfamiliar with normal for that log. Did wonder why there's so many Authenticated blocks in a row when we start.

Most likely unrelated is why we're not gathering profile data on any of the pprof endpoints:
```
Jul 16 2017 00:24:18.899Z DEBUG [BEGIN] [main.urlReader.open:292] http://127.0.0.1:6060/debug/pprof/profile
Jul 16 2017 00:24:20.899Z DEBUG [ END ] [main.urlReader.open:292] [2.000216475s] http://127.0.0.1:6060/debug/pprof/profile
Jul 16 2017 00:24:20.899Z WARN  error reading vic-init/profile(http://127.0.0.1:6060/debug/pprof/profile): Get http://127.0.0.1:6060/debug/pprof/profile: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by corrieb** [comment]
@hickeng Anything to do with serviceability should be fixed before release, right? Please make high priority if you agree.

**Comment by chengwang86** [comment]
Also seen here https://ci.vcna.io/vmware/vic/12615 in test 9-01-VICAdmin-ShowHTML: get port layer log

**Comment by chengwang86** [comment]
See again here https://ci.vcna.io/vmware/vic/13129

**Comment by chengwang86** [comment]
Set it to high priority for at least investigation purpose. We may need to add more logs for debugging. 

P.S.: is it possible that we were hitting the correct curl url but somehow it was redirected to the vicadmin page due to reasons such as login failure or session timeout?

**Comment by emlin** [comment]
https://ci.vcna.io/vmware/vic/13152

**Comment by mdubya66** [comment]
Just hit this in my browser on a VCH with a CDE happening in the portlayer. See #6004.

![screen shot 2017-08-14 at 11 29 56 am](https://user-images.githubusercontent.com/15821624/29281333-406346d6-80e4-11e7-86d2-ef78341fc26e.png)

**Comment by morris-jason** [comment]
Investigating. Repro. with the following
```bash
for i in $(seq 1 $2); do
    curl -sk $1/authentication -XPOST -F username=root -F password=password -D /tmp/cookies-vch
    output=$(curl -sk $1/logs/port-layer.log -b /tmp/cookies-vch)
    if [[ $output != *"Launching portlayer server"* ]]; then
        echo "failed to get pl log for $i"
        echo $output
        exit 1
    fi
done
```
