### ISSUE TITLE
Unable to start Admiral and Harbor Services even after successful VCSA registration

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5737]
OVA build: https://storage.googleapis.com/vic-product-ova-builds/vic-v1.1.1-12146-7a1d15da.ova

**User Statement:**
Deployed the given OVA build and registered with VCSA
![image](https://user-images.githubusercontent.com/25006749/28284605-34a755ee-6b4f-11e7-9a0e-3a5f115f786a.png)

Admiral and Harbor services fail to start 

root@vic-st-h2-132 [ /var/log ]# systemctl status admiral
● admiral.service - Admiral is a highly scalable and very lightweight Container Management platform for deploying and managing container based applications.
   Loaded: loaded (/usr/lib/systemd/system/admiral.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://github.com/vmware/admiral
root@vic-st-h2-132 [ /var/log ]# systemctl start admiral
root@vic-st-h2-132 [ /var/log ]# systemctl status admiral
● admiral.service - Admiral is a highly scalable and very lightweight Container Management platform for deploying and managing container based applications.
   Loaded: loaded (/usr/lib/systemd/system/admiral.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-07-17 18:48:02 UTC; 260ms ago
     Docs: https://github.com/vmware/admiral
  Process: 861 ExecStopPost=/usr/bin/docker rm vic-admiral (code=exited, status=1/FAILURE)
  Process: 853 ExecStop=/usr/bin/docker stop vic-admiral (code=exited, status=1/FAILURE)
  Process: 844 ExecStart=/etc/vmware/admiral/start_admiral.sh (code=exited, status=125)
 Main PID: 844 (code=exited, status=125)

Jul 17 18:48:02 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Control process exited, code=exited status=1
Jul 17 18:48:02 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Unit entered failed state.
Jul 17 18:48:02 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Failed with result 'exit-code'.

Harbor:

root@vic-st-h2-132 [ /var/log ]# systemctl status harbor
● harbor.service - Harbor Container Registry
   Loaded: loaded (/usr/lib/systemd/system/harbor.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: http://github.com/vmware/harbor
root@vic-st-h2-132 [ /var/log ]# systemctl start harbor
root@vic-st-h2-132 [ /var/log ]# systemctl status harbor
● harbor.service - Harbor Container Registry
   Loaded: loaded (/usr/lib/systemd/system/harbor.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-07-17 18:50:47 UTC; 1s ago
     Docs: http://github.com/vmware/harbor
  Process: 1721 ExecStopPost=/usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml rm -f (code=exited, status=1/FAILURE)
  Process: 1715 ExecStop=/usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml down -v (code=exited, status=1/FAILURE)
  Process: 1706 ExecStart=/etc/vmware/harbor/start_harbor.sh (code=exited, status=1/FAILURE)
 Main PID: 1706 (code=exited, status=1/FAILURE)

Jul 17 18:50:47 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Unit entered failed state.
Jul 17 18:50:47 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Failed with result 'exit-code'.
root@vic-st-h2-132 [ /var/log ]#

KoV is running succesfully
root@vic-st-h2-132 [ /var/log ]# systemctl status kov
● kov.service - Kubernetes on vSphere
   Loaded: loaded (/usr/lib/systemd/system/kov.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-07-17 17:57:48 UTC; 58min ago
     Docs: https://github.com/vmware/kov
  Process: 445 ExecStartPre=/etc/vmware/kov/configure_kov.sh (code=exited, status=0/SUCCESS)
 Main PID: 673 (kovd)
    Tasks: 8
   Memory: 59.2M
      CPU: 8.826s
   CGroup: /system.slice/kov.service
           └─673 /usr/bin/kovd --tls-port=5643 --tls-host=0.0.0.0 --tls-certificate /data/kov/cert/server.crt --tls-key /data/kov/cert/server.key --base-image-path /etc/vmware/kov/base_dev.vmdk ...

...

OVA IP : 10.197.37.132- root/Admin!23
 Logs did not get created as services failed to start.

**Comment by lgayatri** [comment]
@mhagen-vmware @andrewtchin @mdubya66

**Comment by andrewtchin** [comment]
Could you provide the results of `journalctl -u fileserver`? 

This build was tested to work - the output should look like this:
```
root@localhost [ ~ ]# journalctl -u fileserver
-- Logs begin at Tue 2017-07-18 15:55:40 UTC, end at Tue 2017-07-18 15:56:28 UTC. --
Jul 18 15:56:15 localhost.localdomain systemd[1]: Started VIC Unified Installer Web Server.
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Current UID/GID = 0/0"
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Loading certificate /opt/vmware/fileserver/cert/server.crt and key /opt/vmware/fileserver/cert/server.key"
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Loaded certificate"
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Starting fileserver server on :9443"
Jul 18 15:56:21 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:21Z" level=info msg="render: html/index.html"
Jul 18 15:56:21 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:21Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 18 15:56:22 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:22Z" level=info msg="render: html/index.html"
Jul 18 15:56:22 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:22Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
```

After inputting the credentials to the landing page, we see that the login succeeded and then Harbor and Admiral start
```
root@localhost [ ~ ]# journalctl -u fileserver
-- Logs begin at Tue 2017-07-18 15:55:40 UTC, end at Tue 2017-07-18 15:57:03 UTC. --
Jul 18 15:56:15 localhost.localdomain systemd[1]: Started VIC Unified Installer Web Server.
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Current UID/GID = 0/0"
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Loading certificate /opt/vmware/fileserver/cert/server.crt and key /opt/vmware/fileserver/cert/server.key"
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Loaded certificate"
Jul 18 15:56:15 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:15Z" level=info msg="Starting fileserver server on :9443"
Jul 18 15:56:21 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:21Z" level=info msg="render: html/index.html"
Jul 18 15:56:21 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:21Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 18 15:56:22 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:22Z" level=info msg="render: html/index.html"
Jul 18 15:56:22 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:22Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 18 15:56:57 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:57Z" level=info msg="server URL: 10.192.233.38\n"
Jul 18 15:56:57 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:57Z" level=info msg="validation succeeded"
Jul 18 15:56:58 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:58Z" level=info msg="version: 6.5"
Jul 18 15:56:58 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:58Z" level=info msg="tenant: vsphere.local"
Jul 18 15:56:58 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:58Z" level=info msg="vcHostName: sc2-rdops-vm07-dhcp-233-38.eng.vmware.com"
Jul 18 15:56:58 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:58Z" level=info msg="vmIP: 10.160.166.158"
Jul 18 15:56:58 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:56:58Z" level=info msg="admiralPort: 8282"
Jul 18 15:57:01 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:57:01Z" level=info msg="render: html/index.html"
Jul 18 15:57:01 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:57:01Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 18 15:57:01 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:57:01Z" level=info msg="render: html/index.html"
Jul 18 15:57:01 localhost.localdomain start_fileserver.sh[689]: time="2017-07-18T15:57:01Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
root@localhost [ ~ ]# systemctl status admiral
● admiral.service - Admiral is a highly scalable and very lightweight Container Management platform for deploying and managing container based applications.
   Loaded: loaded (/usr/lib/systemd/system/admiral.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-07-18 15:57:03 UTC; 9s ago
     Docs: https://github.com/vmware/admiral
 Main PID: 1069 (start_admiral.s)
    Tasks: 7
   Memory: 8.5M
      CPU: 24ms
   CGroup: /system.slice/admiral.service
           ├─1069 /usr/bin/bash /etc/vmware/admiral/start_admiral.sh
           └─1073 /usr/bin/docker run -p 8282:8282 --name vic-admiral -e ADMIRAL_PORT=8282 -e JAVA_OPTS=-Ddcp.net.ssl.trustStore=/tmp/trusted_certificates.jks -Ddcp.net.ssl.trustStorePassword=changeit -e XENON_OPTS=--port=-1 --securePort=8282 --certifica...

Jul 18 15:57:08 localhost.localdomain start_admiral.sh[1069]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Jul 18 15:57:08 localhost.localdomain start_admiral.sh[1069]: [9][I][2017-07-18T15:57:08.626Z][1][8282][startImpl][ServiceHost/3dfe5929 listening on https://172.17.0.2:8282]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [10][I][2017-07-18T15:57:09.356Z][1][8282][start][Setting authorization context ...]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [11][I][2017-07-18T15:57:09.356Z][1][8282][startCommonServices][Common service starting ...]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [12][I][2017-07-18T15:57:09.369Z][1][8282][startServices][Start initializing common services]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [13][I][2017-07-18T15:57:09.383Z][1][8282/config/cluster-monitoring][handleStart][handleStart]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [14][I][2017-07-18T15:57:09.469Z][1][8282][checkPragmaAndRegisterForAvailability][(80) Registering for /config/props/harbor.tab.url to become available on owner 56d99e6a-dd9d-...456-baa7ef1e5700]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [15][I][2017-07-18T15:57:09.892Z][13][ConfigurationService][getConfigurationProperties][Commit id : 51104ebaf34957312ccba4f1702082cd2ef90164]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [16][I][2017-07-18T15:57:09.893Z][13][ConfigurationService][getConfigurationProperties][Build number : 9997]
Jul 18 15:57:09 localhost.localdomain start_admiral.sh[1069]: [17][I][2017-07-18T15:57:09.966Z][12][8282/core/node-groups/default][mergeRemoteAndLocalMembership][State updated, merge with 56d99e6a-dd9d-4866-a456-baa7ef1e5700, self 56d99e...1500393429966001]
Hint: Some lines were ellipsized, use -l to show in full.
root@localhost [ ~ ]# systemctl status harbor 
● harbor.service - Harbor Container Registry
   Loaded: loaded (/usr/lib/systemd/system/harbor.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-07-18 15:57:06 UTC; 11s ago
     Docs: http://github.com/vmware/harbor
 Main PID: 1159 (start_harbor.sh)
    Tasks: 14
   Memory: 51.4M
      CPU: 800ms
   CGroup: /system.slice/harbor.service
           ├─1159 /usr/bin/bash /etc/vmware/harbor/start_harbor.sh
           ├─1167 /usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml up
           └─1168 /usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml up

Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: Attaching to harbor-log, harbor-adminserver, notary-db, harbor-db, registry, notary-signer, harbor-ui, harbor-jobservice, notary-server, nginx
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: harbor-adminserver | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: notary-db        | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: registry         | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: harbor-db        | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: notary-signer    | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: harbor-ui        | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: harbor-jobservice | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: notary-server    | WARNING: no logs are available with the 'syslog' log driver
Jul 18 15:57:13 localhost.localdomain start_harbor.sh[1159]: nginx            | WARNING: no logs are available with the 'syslog' log driver
```

**Comment by lgayatri** [comment]
@anchal-agrawal , my test bed went down today due to VCSA upgrade failure. Rebuilding now. Will provide the info soon.

**Comment by lgayatri** [comment]
My Test bed came up partially, and here is the output on build 12202

root@vic-st-h2-132 [ /var/log ]# systemctl status admiral
● admiral.service - Admiral is a highly scalable and very lightweight Container Management platform for deploying and managing container based applications.
   Loaded: loaded (/usr/lib/systemd/system/admiral.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://github.com/vmware/admiral

root@vic-st-h2-132 [ /var/log ]# journalctl -u fileserver > 5737.txt
root@vic-st-h2-132 [ /var/log ]# cat 5737.txt
-- Logs begin at Sun 2017-07-23 14:07:56 UTC, end at Mon 2017-07-24 11:47:46 UTC. --
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com systemd[1]: Started VIC Unified Installer Web Server.
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Current UID/GID = 0/0"
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Loading certificate /opt/vmware/fileserver/cert/server.crt and key /opt/vmware/fileserver/cert/server.key"
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Loaded certificate"
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Starting fileserver server on :9443"
Jul 24 09:30:19 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T09:30:19Z" level=info msg="render: html/index.html"
Jul 24 09:30:19 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T09:30:19Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"

Attempted to start with systemctl but the process eventually died
 systemctl status admiral
● admiral.service - Admiral is a highly scalable and very lightweight Container Management platform for deploying and managing container based applications.
   Loaded: loaded (/usr/lib/systemd/system/admiral.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-07-24 11:50:50 UTC; 3s ago
     Docs: https://github.com/vmware/admiral
  Process: 1961 ExecStopPost=/usr/bin/docker rm vic-admiral (code=exited, status=1/FAILURE)
  Process: 1950 ExecStop=/usr/bin/docker stop vic-admiral (code=exited, status=1/FAILURE)
  Process: 1943 ExecStart=/etc/vmware/admiral/start_admiral.sh (code=exited, status=125)
 Main PID: 1943 (code=exited, status=125)

Jul 24 11:50:50 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Control process exited, code=exited status=1
Jul 24 11:50:50 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Unit entered failed state.
Jul 24 11:50:50 vic-st-h2-132.eng.vmware.com systemd[1]: admiral.service: Failed with result 'exit-code'.

**Comment by anchal-agrawal** [comment]
@lgayatri I logged in to the OVA and didn't see any PSC files in `/etc/vmware/admiral` - this likely indicates that the PSC register command that runs after entering VC credentials at `https://$OVA-VM-IP:9443` didn't run. Also, I looked at the logs of that service (`journalctl -u fileserver`) and I don't see evidence of a login attempt:

```
-- Logs begin at Sun 2017-07-23 14:07:56 UTC, end at Mon 2017-07-24 14:42:10 UTC. --
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com systemd[1]: Started VIC Unified Installer Web Server.
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Current UID/GID = 0/0"
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Loading certificate /opt/vmware/fileserver/cert/server.crt and key /opt/vmware/fileserver/cert/server.key"
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Loaded certificate"
Jul 23 14:08:22 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-23T14:08:22Z" level=info msg="Starting fileserver server on :9443"
Jul 24 09:30:19 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T09:30:19Z" level=info msg="render: html/index.html"
Jul 24 09:30:19 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T09:30:19Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
```

I'm closing this issue as the OVA build https://storage.googleapis.com/vic-product-ova-builds/vic-v1.1.1-12146-7a1d15da.ova used here is not the latest and is missing PSC work that has been added recently. Please contact me directly if you need a stable dev OVA build for testing.

**Comment by andrewtchin** [comment]
@lgayatri Based on the fileserver log, the vSphere admin credentials were not properly entered on the UI. I believe this is causing Admiral to fail to start and since you issued `systemctl start admiral` and `systemctl start harbor` manually but the initialization was not completed, those processes failed. Additionally, those units need to start after their respective startup units that perform configuration.
If you want to continue trying to get this current appliance working, login through the Getting Started page at `:9443` and check that the fileserver log matches mine. Admiral and Harbor should then configure and start in the proper order.
I would recommend destroying and redeploying this appliance, logging into the Getting Started page, and checking the fileserver logs for successful auth. A user should never have to manually start any units after deploying the OVA.

**Comment by lgayatri** [comment]
@anchal-agrawal  @andrewtchin 
I think I found the Issue .The VCSA build I have is not supported by admiral.
Steps:
1. Registered again
![image](https://user-images.githubusercontent.com/25006749/28536886-ab0cea24-70c6-11e7-880d-b9b92cdca89c.png)
2.journalctl -u fileserver says
Jul 24 17:44:45 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: 2017/07/24 17:44:45 http: TLS handshake error from 10.104.6.12:60233: EOF
Jul 24 17:46:51 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:46:51Z" level=info msg="render: html/index.html"
Jul 24 17:46:51 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:46:51Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 24 17:46:53 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:46:53Z" level=info msg="render: html/index.html"
Jul 24 17:46:53 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:46:53Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 24 17:47:52 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:52Z" level=info msg="server URL: vic-st-h2-191.eng.vmware.com\n"
Jul 24 17:47:52 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:52Z" level=info msg="validation succeeded"
Jul 24 17:47:53 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:53Z" level=info msg="version: 6.6"
Jul 24 17:47:53 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:53Z" level=info msg="tenant: vsphere.local"
Jul 24 17:47:53 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:53Z" level=info msg="vcHostName: vic-st-h2-191.eng.vmware.com"
Jul 24 17:47:53 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:53Z" level=info msg="vmIP: 10.197.37.132"
Jul 24 17:47:53 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:53Z" level=info msg="admiralPort: 8282"
Jul 24 17:47:54 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:54Z" level=info msg="Error running PSC register command: [0][I][2017-07-24
T17:47:54.278Z][1][PscCommand][register][Initializing...]\nException in thread \"main\" java.lang.IllegalArgumentException: Unsupported version '6.6'! Please, select 6.
0 or 6.5.\n\tat com.vmware.admiral.auth.idm.psc.util.PscCommand$PscCommandSettings.validateRegisterSettings(PscCommand.java:80)\n\tat com.vmware.admiral.auth.idm.psc.ut
il.PscCommand.register(PscCommand.java:172)\n\tat com.vmware.admiral.auth.idm.psc.util.PscCommand.execute(PscCommand.java:158)\n\tat com.vmware.admiral.auth.idm.psc.uti
l.PscCommand.main(PscCommand.java:226)\n"
Jul 24 17:47:54 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:54Z" level=info msg="render: html/index.html"
Jul 24 17:47:54 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:54Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Jul 24 17:47:55 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:55Z" level=info msg="render: html/index.html"
Jul 24 17:47:55 vic-st-h2-132.eng.vmware.com start_fileserver.sh[719]: time="2017-07-24T17:47:55Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
This means the VCSA version I am using is not supported. I have 6.6 while the product is asking for 6.5 or 6.0.

Can you please reopen the bug?

**Comment by anchal-agrawal** [comment]
@lgayatri re this error:

```
T17:47:54.278Z][1][PscCommand][register][Initializing...]\nException in thread "main" java.lang.IllegalArgumentException: Unsupported version '6.6'! Please, select 6.0 or 6.5.
```

The version field is purely meant as input to the PSC command developed by the Admiral team. In the latest OVA code (not in the build you're using), we've pinned the version to 6.0 (https://github.com/vmware/vic-product/pull/449) regardless of the vSphere version being used, because for VIC 1.2 we intend to use SAML auth for both vSphere 6.0 and 6.5. Your 6.6 setup might still work with the OVA, but I'm not sure if we plan to support 6.6 for VIC 1.2.

Please use a newer OVA dev build - I'll leave this issue as closed since this build doesn't include the latest OVA initialization workflow.

**Comment by lgayatri** [comment]
@anchal-agrawal , we are supporting 6.6 with VIC 1.2. I confirmed with Brian Armer today.

**Comment by mdubya66** [comment]
We should work with any version greater than 6.0. Supported or not. If this is fixed in a newer version let's get lakshmi one and confirm. Also, please start filing issues that are related to the OVA in the vic-product repo.

**Comment by anchal-agrawal** [comment]
@lgayatri https://storage.googleapis.com/vic-product-ova-builds/vic-e68f9101.ova is a newer OVA dev build that doesn't have the issue you described above. The PSC workflow will work for any vSphere version >= 6.0. However, this build has an issue where the Admiral UI doesn't come up because the Admiral container run command needs to be updated with PSC params. I'm working on addressing that.
