### ISSUE TITLE
Container VM notes portlet

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#575]
**THIS PORTLET IS NOW OBSOLETE  AS WE ARE SHOWING THIS INFO ON THE "CONTAINER" PORTLET**

This portlet will be shown on a Container VM (Summary) that has a docker endpoint.

Title: Notes
Data (example):
  Use via:
    DOCKER_HOST=tcp://10.17.109.153:2376 docker

  Appliance admin:
    http://10.17.109.153:2378/

UX Comp:
TBD (will update once UX adds this view)

**Comment by stuclem** [comment]
The docs need to mention where this information is displayed, so added the user-doc label.

**Comment by jak-atx** [comment]
THIS PORTLET IS NOW OBSOLETE AS WE ARE SHOWING THIS INFO ON THE "CONTAINER" PORTLET - CLOSING THIS.
