### ISSUE TITLE
docker exec following rm -f causing temporary issues.

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#5785]
Steps to reproduce

1. `docker -H IP:port --tls exec -d --user <user> <container> sh /path/to/script`
2. `docker -H IP:port --tls rm -f <container>`
3. `docker -H IP:port --tls volume rm <name>`

Failed to remove container (<name>): An error occurred trying to connect: EOF
Cannot connect to the Docker daemon. Is the docker daemon running on this host? 

Adding a wait time between steps [1] and [2] would help sort this.

**Comment by chengwang86** [comment]
@malikkal Could you please upload container logs if any?

**Comment by malikkal** [comment]
@chengwang86 I am sorry, I failed to capture logs at the time. I will try to reproduce.

**Comment by morris-jason** [comment]
I am not able to reproduce this using the latest master build.
Can you please verify this is an active issue, and repro. with logs if possible?

**Comment by morris-jason** [comment]
@malikkal does this snippet look like something that would've caused your failure?
```
docker run --rm -v vol1:/mnt/vol1 --name bb -itd quay.io/jasonm/5785-test-image
docker exec -d --user root bb sh /etc/test-script.sh
docker rm -f bb
docker volume rm vol1
```

**Comment by morris-jason** [comment]
Not reproducible on master or v1.1.1. Closing.

**Comment by hickeng** [comment]
This was observed again, hence re-opening. The context as part of the concurrency set: #6391 
Suggest attempting a recreate using a style similar to that in https://github.com/vmware/vic/issues/6263 or as done by @cgtexmex in https://github.com/vmware/vic/issues/6341

**Comment by sflxn** [comment]
Without logs, it's hard to know for sure, but from the description of the issue, this sounds like a panic that caused the persona to crash.

**Comment by sflxn** [comment]
I wrote 3 scripts to try and reproduce this issue:

_docker-rm:_
```
docker -H $1 volume create vol$2 2>&1
docker -H $1 run -d --name box$2 -v vol$2:/vol busybox /bin/top 2>&1
docker -H $1 exec -d box$2 -c 'sleep 3600' 2>&1
docker -H $1 rm -f box$2 2>&1
docker -H $1 volume rm vol$2 2>&1
```

_serial-rm.sh:_
```
for i in $(seq 30);
do
    ./docker-rm.sh $1 $i
done
```

_parallel-rm.sh:_
```
for i in $(seq 30);
do
    ./docker-rm.sh $1 $i &
done
wait
```

I tried with our latest code and a nested VC setup.  I was not able to reproduce the original issue.  I've found other issues (in the parallel case) that I intend to write up new issues, but they may be related to my nested environment so I want to try on a physical VC environment first.

I still stand by my initial speculation that the original issue is a panic, and is unrelated to concurrency issue.  However, concurrency might have made it more producible.

**Comment by sflxn** [comment]
I just tried this with VIC 1.1.1 for a sequence of 10 and sequence of 30 and was unable to reproduce this issue.  The logs do not show any EOF.

I wrote up a new issue #6672 for the concurrent issues that I did find.  With no way to reproduce the original issue nor any logs, I am going to close this issue as unable to repro.
