### ISSUE TITLE
Incorrect IP address reported by ovftool

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5788]
Potentially related to:
https://github.com/vmware/vic/issues/4995

Powering on VM: VIC-mike
Task Completed                        
Received IP address: 172.17.0.1
Completed successfully

172.17.0.1 is definitely not the right address...

**Comment by mhagen-vmware** [comment]
@frapposelli tagging you

**Comment by frapposelli** [comment]
this is a dup of #4995 going to be fixed in the current sprint

**Comment by frapposelli** [comment]
Closed by vmware/vic-product#456
