### ISSUE TITLE
Vote for Intern Posters

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic#5793]
This is the highest priority issue for Sprint 13.
You can vote for any number of posters, but only once for each poster.

Jialin and Jason, Docker CP - https://submissions.eng.vmware.com/intern-poster-session-2017/submissions/8878

Will, Container Network Firewalls - https://submissions.eng.vmware.com/intern-poster-session-2017/submissions/8919

Nishad: https://submissions.eng.vmware.com/intern-poster-session-2017/submissions/8937

**Comment by willsherwood** [comment]
lgtm

**Comment by rogeliosanchez** [comment]
ship it

**Comment by dougm** [comment]
voted :+1: 

but - online file copy does not use a serial port, it uses vmx guest RPC (ESX host <-> VM guest).
also, disable toolbox.Trace and it'll be faster!

**Comment by Alphasite** [comment]
Hey... what about me? 

Nishad: https://submissions.eng.vmware.com/intern-poster-session-2017/submissions/8937

**Comment by corrieb** [comment]
Voted for all 3 of you. Great use of GitHub to get our attention :)

**Comment by dacherer** [comment]
Voted for all 3.  Great job!
