### ISSUE TITLE
Support docker cp to copy content of a directory using /.

### ISSUE THREAD

**Issue by jialin-li** [vmware/vic#5796]
As a user, I expect the docker cp command to copy the content of `dir` by specifying src path as `/path/to/dir/.` 

Expect behavior:
`docker cp test/. cid:/tmp`  and `docker cp cid:/tmp/. newdir/` 
should work for both offline and online containers

**Comment by hickeng** [comment]
@jialin-li Will use of https://golang.org/pkg/path/#Clean address this when constructing the include filters? Directory copy already functions so I think this is just about the `.`.

**Comment by jialin-li** [comment]
@hickeng We would need to use path.Clean() but we would also have to change other part of the filter spec to make sure the directory is not included in the header.
