### ISSUE TITLE
Nightly Test 5-7-NSX host cant access datastores

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5800]
Seen on 6.5:
[5-7-NSX.zip](https://github.com/vmware/vic/files/1170528/5-7-NSX.zip)

From vic-machine.log:
```Jul 23 2017 03:30:44.419Z DEBUG Configuring without client verification due to empty certificate authorities
Jul 23 2017 03:30:44.419Z DEBUG URL: https://harbor.ci.drone.local/v2/
Jul 23 2017 03:30:54.419Z DEBUG URL: http://harbor.ci.drone.local/v2/
Jul 23 2017 03:30:54.420Z WARN  Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.
Jul 23 2017 03:30:54.420Z INFO  Insecure registries = harbor.ci.drone.local
Jul 23 2017 03:30:55.058Z ERROR --------------------
Jul 23 2017 03:30:55.058Z ERROR No single host can access all of the requested datastores. Installation cannot continue.
Jul 23 2017 03:30:55.058Z ERROR Create cannot continue: configuration validation failed
Jul 23 2017 03:30:55.058Z ERROR --------------------
Jul 23 2017 03:30:55.058Z ERROR vic-machine-linux create failed: validation of configuration failed
```

Also possible (but not likely or confirmed) relation to https://github.com/vmware/vic/issues/3525

**Comment by sgairo** [comment]
Seen on 6.5 7/24 Report:
[5-7-NSX.zip](https://github.com/vmware/vic/files/1173809/5-7-NSX.zip)

**Comment by sgairo** [comment]
It appears that the firewall configuration is the suspect

**Comment by sgairo** [comment]
From the last passing nightly test it appears that the firewall status is **disabled**:

`Jul 13 2017 03:56:08.512Z INFO  Firewall status: DISABLED on "/vcqaDC/host/cls/10.160.8.168"
Jul 13 2017 03:56:08.620Z DEBUG filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc42044ddc0}]
Jul 13 2017 03:56:08.620Z DEBUG filtered IPs: [10.162.202.242 10.160.31.199] networks: [] allIP: false rule: nfsClient
Jul 13 2017 03:56:08.620Z DEBUG fw unknown (dhcp) with fw disabled "/vcqaDC/host/cls/10.160.8.168"
Jul 13 2017 03:56:08.620Z WARN  Firewall configuration on "/vcqaDC/host/cls/10.160.8.168" may prevent connection on dst 2377/tcp outbound with allowed IPs: [10.162.202.242 10.160.31.199]
Jul 13 2017 03:56:08.824Z INFO  Firewall status: DISABLED on "/vcqaDC/host/cls/10.160.0.151"
Jul 13 2017 03:56:08.932Z DEBUG filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc420422280}]
Jul 13 2017 03:56:08.932Z DEBUG filtered IPs: [10.162.202.65 10.160.31.199] networks: [] allIP: false rule: nfsClient
Jul 13 2017 03:56:08.932Z DEBUG fw unknown (dhcp) with fw disabled "/vcqaDC/host/cls/10.160.0.151"
Jul 13 2017 03:56:08.932Z WARN  Firewall configuration on "/vcqaDC/host/cls/10.160.0.151" may prevent connection on dst 2377/tcp outbound with allowed IPs: [10.162.202.65 10.160.31.199]
Jul 13 2017 03:56:09.139Z INFO  Firewall status: DISABLED on "/vcqaDC/host/cls/10.160.6.152"
Jul 13 2017 03:56:09.242Z DEBUG filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc4202f7780}]
Jul 13 2017 03:56:09.242Z DEBUG filtered IPs: [10.162.203.80 10.160.31.199] networks: [] allIP: false rule: nfsClient
Jul 13 2017 03:56:09.242Z DEBUG fw unknown (dhcp) with fw disabled "/vcqaDC/host/cls/10.160.6.152"
Jul 13 2017 03:56:09.242Z WARN  Firewall configuration on "/vcqaDC/host/cls/10.160.6.152" may prevent connection on dst 2377/tcp outbound with allowed IPs: [10.162.203.80 10.160.31.199]
Jul 13 2017 03:56:09.446Z INFO  Firewall status: DISABLED on "/vcqaDC/host/cls/10.160.6.248"
Jul 13 2017 03:56:09.558Z DEBUG filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc4205ab240}]
Jul 13 2017 03:56:09.558Z DEBUG filtered IPs: [10.162.202.157 10.160.31.199] networks: [] allIP: false rule: nfsClient
Jul 13 2017 03:56:09.558Z DEBUG fw unknown (dhcp) with fw disabled "/vcqaDC/host/cls/10.160.6.248"
Jul 13 2017 03:56:09.558Z WARN  Firewall configuration on "/vcqaDC/host/cls/10.160.6.248" may prevent connection on dst 2377/tcp outbound with allowed IPs: [10.162.202.157 10.160.31.199]
Jul 13 2017 03:56:09.558Z WARN  Unable to fully verify firewall configuration due to DHCP use on management network
Jul 13 2017 03:56:09.558Z WARN  VCH management interface IP assigned by DHCP must be permitted by allowed IP settings
Jul 13 2017 03:56:09.558Z WARN  Firewall configuration may be incorrect if firewall is reenabled on hosts:
Jul 13 2017 03:56:09.558Z WARN  	"/vcqaDC/host/cls/10.160.8.168"
Jul 13 2017 03:56:09.558Z WARN  	"/vcqaDC/host/cls/10.160.0.151"
Jul 13 2017 03:56:09.558Z WARN  	"/vcqaDC/host/cls/10.160.6.152"
Jul 13 2017 03:56:09.558Z WARN  	"/vcqaDC/host/cls/10.160.6.248"
Jul 13 2017 03:56:09.558Z INFO  Firewall must permit dst 2377/tcp outbound to the VCH management interface if firewall is reenabled
Jul 13 2017 03:56:10.080Z INFO  License check OK on hosts:
Jul 13 2017 03:56:10.081Z INFO    "/vcqaDC/host/cls/10.160.8.168"
Jul 13 2017 03:56:10.081Z INFO    "/vcqaDC/host/cls/10.160.0.151"
Jul 13 2017 03:56:10.081Z INFO    "/vcqaDC/host/cls/10.160.6.152"
Jul 13 2017 03:56:10.081Z INFO    "/vcqaDC/host/cls/10.160.6.248"
Jul 13 2017 03:56:10.140Z INFO  DRS check OK on:
Jul 13 2017 03:56:10.140Z INFO    "/vcqaDC/host/cls"
Jul 13 2017 03:56:10.141Z DEBUG Configuring without client verification due to empty certificate authorities
Jul 13 2017 03:56:10.141Z DEBUG URL: https://harbor.ci.drone.local/v2/
Jul 13 2017 03:56:20.142Z DEBUG URL: http://harbor.ci.drone.local/v2/
Jul 13 2017 03:56:20.142Z WARN  Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.
Jul 13 2017 03:56:20.142Z INFO  Insecure registries = harbor.ci.drone.local
Jul 13 2017 03:56:20.788Z DEBUG Datacenter: "vcqaDC", Cluster: "ClusterComputeResource:domain-c7", Resource Pool: "/vcqaDC/host/cls/Resources"
Jul 13 2017 03:56:20.788Z INFO  
Jul 13 2017 03:56:24.106Z INFO  Creating virtual app "VCH-0-4901"
Jul 13 2017 03:56:24.238Z INFO  Creating appliance on target`

But for all of the proceeding failures, the status **does not** report as disabled:

`Jul 24 2017 03:30:03.511Z DEBUG Checking firewall with management network IP {<nil> <nil>}
Jul 24 2017 03:30:04.016Z INFO  DRS check OK on:
Jul 24 2017 03:30:04.016Z INFO    "/vcqaDC/host/cls"
Jul 24 2017 03:30:04.019Z DEBUG Configuring without client verification due to empty certificate authorities
Jul 24 2017 03:30:04.019Z DEBUG URL: https://harbor.ci.drone.local/v2/
Jul 24 2017 03:30:14.019Z DEBUG URL: http://harbor.ci.drone.local/v2/
Jul 24 2017 03:30:14.020Z WARN  Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.
Jul 24 2017 03:30:14.020Z INFO  Insecure registries = harbor.ci.drone.local
Jul 24 2017 03:30:14.670Z ERROR --------------------
Jul 24 2017 03:30:14.670Z ERROR No single host can access all of the requested datastores. Installation cannot continue.
Jul 24 2017 03:30:14.670Z ERROR Create cannot continue: configuration validation failed
Jul 24 2017 03:30:14.670Z ERROR --------------------
Jul 24 2017 03:30:14.670Z ERROR vic-machine-linux create failed: validation of configuration failed`

**Comment by sgairo** [comment]
Seen on 6.5 7/25 report:
[5-7-NSX.zip](https://github.com/vmware/vic/files/1177506/5-7-NSX.zip)

**Comment by sgairo** [comment]
Seen on 6.5 7/27 Report:
[5-7-NSX.zip](https://github.com/vmware/vic/files/1183551/5-7-NSX.zip)

**Comment by sgairo** [comment]
Seen on 6.65 7/30 report:
[5-7-NSX.zip](https://github.com/vmware/vic/files/1188048/5-7-NSX.zip)

**Comment by sgairo** [comment]
It was noted that the hosts on the cluster are disconnected due to an expired license. Following up with how to renew them while making sure the NSX setup doesnt get rebuilt.

**Comment by sgairo** [comment]
@mhagen-vmware has updated the licenses, will report back with results of the tests.

**Comment by rajanashok** [comment]
@sgairo @mhagen-vmware The VC license was still set to eval. Updated the VC license and reconnected the hosts, the nightly test is passing now.
