### ISSUE TITLE
Destination Port Unreachable for 1.1.1 containers

### ISSUE THREAD

**Issue by douggie** [vmware/vic#5801]
User Statement:

As a user of VIC, I expect to be able to create containers that are attached and pingable on an external network.

Details:
When a VCH is created with 0.8 using the following command:
`vic-machine-linux create  --target 10.2.2.2 --user [user] --password [pass]  --no-tlsverify --name client2.ea.ducotech.io --public-network-gateway 10.128.205.254/24  --public-network-ip 10.128.205.30 --compute-resource Duco-Lab-iommdh --image-store DucoLabs --volume-store DucoLabs/ea/client2:default --bridge-network Container-Bridge-Network --public-network Labs-Man-Network --container-network Labs-Man-Network --container-network-gateway Labs-Man-Network:10.128.205.254/24 -thumbprint=A1:20:7A:D4:21:CA:4F:A4:30:85:EF:90:A7:B7:0A:37:33:C9:06:34 --registry-ca="../vic/harbour/ca.crt"`

I can create a new container and ping/ssh etc to it:
`docker -H 10.128.205.30:2376 --tls run -d --net=Labs-Man-Network [image]`

However if I create a VCH using 1.1.1 Vic machine 
`./vic-machine-linux create  --target 10.2.2.2 --user [user] --password [pass]  --no-tlsverify --name client3.ea.ducotech.io --public-network-gateway 10.128.205.254  --public-network-ip 10.128.205.31/24 --compute-resource Duco-Lab-iommdh --image-store DucoLabs --volume-store DucoLabs/ea/client3:default --bridge-network Container-Bridge-Network --public-network Labs-Man-Network --container-network Labs-Man-Network --container-network-gateway Labs-Man-Network:10.128.205.254/24 -thumbprint=A1:20:7A:D4:21:CA:4F:A4:30:85:EF:90:A7:B7:0A:37:33:C9:06:34 --registry-ca="../vic/harbour/ca.crt"`

When I create a new container using 
`docker -H 10.128.205.31:2376 --tls run -d --net=Labs-Man-Network [image]`

I get:
`Request timeout for icmp_seq 474
92 bytes from 10.128.205.112: Destination Port Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 6221   0 0000  3f  01 6f0b 10.1.200.139  10.128.205.112 `

Acceptance Criteria:
Containers created using VIC 1.1.1 should be accessible from external networks just as those created with VIC 0.8

**Comment by douggie** [comment]
Attaching log bundles
[v1.1.0-rc3-logs.zip](https://github.com/vmware/vic/files/1170578/v1.1.0-rc3-logs.zip)
[0.8-logs.zip](https://github.com/vmware/vic/files/1170579/0.8-logs.zip)

**Comment by hmahmood** [comment]
@douggie the log bundle above does not include the container logs; could you please upload a bundle with those included? Thanks.

**Comment by douggie** [comment]
Hopefully bundle has them all in.

[0.8-log-bundle.zip](https://github.com/vmware/vic/files/1171350/0.8-log-bundle.zip)
[Uploading v1.1.0-rc3-log-bundle.zip…]()

**Comment by douggie** [comment]
Hi, further to slack comments -p [port] is needed to explictly open ports as all ports blocked by default.

docker -H [vch]:2376 --tls run -d -p 22  --net=[net work] -e [image]
