### ISSUE TITLE
Remove toolbox trace line from tether logging before we build 1.2 release build

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#5809]
`toolbox.Trace = true` should be removed before we do the release build for 1.2. This is just a reminder ticket so that it is tracked somewhere. it can be found in `lib/tether/toolbox.go` in the `NewToolbox()` funciton.

**Comment by morris-jason** [comment]
Closing, Tracing should not be merged to master. It is not currently in the CP feature branch.
