### ISSUE TITLE
Warning: VirtualMachine Snapshot Size

### ISSUE THREAD

**Issue by tschwaller** [vmware/vic#5815]
After deploying an application with VIC and running it for 4 days the following warning shows up in the vSphere Web Client. We used the VIC_12447 version. Is there an known explanation for this warning?

<img width="290" alt="image" src="https://user-images.githubusercontent.com/6458940/28562058-21e50550-7121-11e7-9a3b-d770ec8c7c4d.png">

**Comment by sgairo** [comment]
Hi there @tschwaller, do you happen to have any logs for this? Thanks!

**Comment by sgairo** [comment]
Hi @tschwaller, do you happen to have any logs for this?
