### ISSUE TITLE
Nightly Test 21-1 Whitelist suite setup and teardown failed

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5822]
Seen in 6.5: 
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1174007/21-1-Whitelist.zip)

from log: 
`Parent suite setup failed: Source file '/drone/src/github.com/vmware/vic/getcert' does not exist.  Also parent suite teardown failed: Several failures occurred:  1) Environment variable '%{VCH-NAME}' not found.  2) Environment variable '%{VIC-ADMIN}' not found.  3) Environment variable '%{VIC-ADMIN}' not found.  4) Environment variable '%{VCH-NAME}' not found.  5) TypeError: argument of type 'NoneType' is not iterable`

**'/drone/src/github.com/vmware/vic/getcert' does not exist** the file is not being generated. @mhagen-vmware is this because harbor just didnt deploy, or was it some recent test changes?

**Comment by sgairo** [comment]
would be fixed by #5698

**Comment by sgairo** [comment]
Seen in 6.5 7/27/ report:
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1183575/21-1-Whitelist.zip)

**Comment by mhagen-vmware** [comment]
this will be moot once #5243 is closed.  Going to close this for now as a dupe/won't fix then.
