### ISSUE TITLE
Nightly Test 5-6-1 VSAN Simple GOVC_URL setup failed

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5823]
Seen in 6.0:
[5-6-1-VSAN-Simple.zip](https://github.com/vmware/vic/files/1174080/5-6-1-VSAN-Simple.zip)

From log:
`Resolving variable '${vc-ip}' failed: Variable '${vc}' not found.`

Could just be from the nimbus issues we've been seeing.

**Comment by rogeliosanchez** [comment]
@mhagen-vmware @rajanashok @singhshwetaQE 
Looks like the fix I was going to implement has been already implemented sometime after this log was collected.
Mike may file a ticket agains Nimbus for an issue with there being several "ip is up" messages in the output of a successful deployment.

**Comment by mhagen-vmware** [comment]
:+1:
