### ISSUE TITLE
Nightly Test 5-21 Datastore-Path certificates expired  

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5824]
Seen in 6.0:
[5-21-Datastore-Path.zip](https://github.com/vmware/vic/files/1174141/5-21-Datastore-Path.zip)

From vic-machine.log:
`Jul 24 2017 15:20:19.441Z WARN  Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.
Jul 24 2017 15:20:19.441Z INFO  Insecure registries = harbor.ci.drone.local
Jul 24 2017 15:20:20.086Z ERROR --------------------
Jul 24 2017 15:20:20.086Z ERROR Failed to create client for validation of operations credentials: Post https://10.192.99.229/sdk: x509: certificate has expired or is not yet valid
Jul 24 2017 15:20:20.086Z ERROR Create cannot continue: configuration validation failed
Jul 24 2017 15:20:20.086Z ERROR --------------------
Jul 24 2017 15:20:20.086Z ERROR vic-machine-linux create failed: validation of configuration failed`

**Comment by sgairo** [comment]
Seen in 6.0 7/31/17 nightly report:
[5-21-Datastore-Path.zip](https://github.com/vmware/vic/files/1191156/5-21-Datastore-Path.zip)

**Comment by rajanashok** [comment]
Closing it, as we not seeing this issue on the latest nightly runs.

**Comment by anchal-agrawal** [comment]
Seen:
```
Date: August 27
Engine build: 13421
vSphere version: 6.0
Test: 5-21-Datastore-Path
```

Logs:

vic-machine create
```
Aug 27 2017 11:01:21.895Z ERROR --------------------
Aug 27 2017 11:01:21.895Z ERROR Failed to create client for validation of operations credentials: Post https://10.161.123.88/sdk: x509: certificate has expired or is not yet valid
Aug 27 2017 11:01:21.896Z ERROR Create cannot continue: configuration validation failed
Aug 27 2017 11:01:21.944Z ERROR --------------------
Aug 27 2017 11:01:21.944Z ERROR vic-machine-linux create failed: validation of configuration failed
```

[log.html.zip](https://github.com/vmware/vic/files/1254661/log.html.zip)
[vic-machine.log.zip](https://github.com/vmware/vic/files/1254662/vic-machine.log.zip)

**Comment by sgairo** [comment]
This expiration hasn't been seen in nearly two weeks. Additionally, it occurs as a blip without any reoccurring pattern before/after. It doesn't appear to be caused by VIC.

**Comment by jzt** [comment]
[5-21-Datastore-Path.zip](https://github.com/vmware/vic/files/1350197/5-21-Datastore-Path.zip)

**Comment by jzt** [comment]
[5-21-Datastore-Path.zip](https://github.com/vmware/vic/files/1350484/5-21-Datastore-Path.zip)

**Comment by jzt** [comment]
[5-21-Datastore-Path.zip](https://github.com/vmware/vic/files/1354284/5-21-Datastore-Path.zip)

**Comment by hickeng** [comment]
Commenting solely on the error: `Failed to create client for validation of operations credentials: Post https://10.161.123.88/sdk: x509: certificate has expired or is not yet valid`

This is likely due to clock skew within the environment - in this case between the machine running `vic-machine` and the vCenter. I recommend that all of the systems in the environment be configured with the same ntp server if they are not already.
If the VMs are configured for time sync with the host then it implies that either that is not occurring as expected, or that there's timeskew between the low level hosts.
