### ISSUE TITLE
docker exec causing init customizations to revert

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#5833]
Steps to reproduce; using Build: v1.1.0-rc3-**12176**-7738cb5

1. Customize /etc/hosts file, hostname in entrypoint script.
2. /etc/init.d/iptables stop in entrypoint script.
3. docker -H IP:port --tls exec -d <container> sh /path/to/**any**script
4. /etc/hosts and hostname revert to defaults and iptables service back online.

**Comment by caglar10ur** [comment]
Looks like we repeat our initialization logic on tether reloads which is triggered by exec. Working on it...

**Comment by caglar10ur** [comment]
hey @malikkal do you mind sharing me why you are changing hosts file and stopping the iptables? Asking to learn whether we can provide an alternative solution to the problem that you are trying to solve.

**Comment by caglar10ur** [comment]
ping @malikkal it would be really great if you can share why do you need to change hostname/hosts file and iptables manually. I've been spending some time on the code and it is clear that our assumption is those autogenerated files will only be touched by the vic

**Comment by malikkal** [comment]
@caglar10ur my apologies for the delay. Please refer #4195 and #5426.

**Comment by caglar10ur** [comment]
OK, looks like the missing piece is supporting -h flag and once we do that you no longer need to modify those files manually with 1.2, is my understanding correct @malikkal ?

I started to implement hostname support and hoping to finish before we freeze the code.

**Comment by malikkal** [comment]
may I know about --add-host, --dns etc?

/etc/hosts are taken care by --add-host and /etc/resolv.conf using --dns?

**Comment by caglar10ur** [comment]
We don't have --add-host support (#4716). Is that something you need? This issue only mentions hostname (and iptables) so it was out of my radar.
