### ISSUE TITLE
Nightly Test 5-1-Distributed-Switch regression tests failing

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5836]
Seen in 6.5: 
[5-1-Distributed-Switch.zip](https://github.com/vmware/vic/files/1177191/5-1-Distributed-Switch.zip)

From log: 
![image](https://user-images.githubusercontent.com/19394901/28630399-cc1746d6-71ef-11e7-8f5f-7cc1ce0d0a36.png)

Not much can be seen from the logs. Potential Dockerhub issue seen by @mdubya66:
`Jul 24 2017 23:59:47.417Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:124] [2m27.329891733s] https://registry-1.docker.io/v2/library/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Jul 24 2017 23:59:47.418Z INFO  diffID for layer e3826c3cb1d4d62965bfac0246560764c8fbe13b8bc22253b667f7340bfb843a: sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Jul 24 2017 23:59:47.418Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.FetchImageBlob:168] [2m27.330574942s] library/busybox/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Jul 25 2017 00:01:38.349Z DEBUG Download failed, retrying: not authorized
Jul 25 2017 00:01:43.353Z DEBUG Setting user-agent to vic/v1.1.0-rc3
Jul 25 2017 00:03:54.438Z DEBUG Download failed, retrying: not authorized
Jul 25 2017 00:04:04.441Z DEBUG Setting user-agent to vic/v1.1.0-rc3
Jul 25 2017 00:04:06.115Z DEBUG Download failed, retrying: not authorized
Jul 25 2017 00:04:21.115Z DEBUG Setting user-agent to vic/v1.1.0-rc3
Jul 25 2017 00:04:24.985Z DEBUG Download failed, retrying: not authorized
Jul 25 2017 00:04:44.989Z DEBUG Setting user-agent to vic/v1.1.0-rc3
Jul 25 2017 00:04:45.579Z DEBUG Hit max download attempts. Download failed: not authorized`

**Comment by mdubya66** [comment]
dockerhub issue. closing. reopen if seen again
