### ISSUE TITLE
Nightly Test 5-1 Distributed Switch cant add host to dvs

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5864]
Seen in 6.5:
[5-1-Distributed-Switch.zip](https://github.com/vmware/vic/files/1183534/5-1-Distributed-Switch.zip)

From log:
![screen shot 2017-07-28 at 10 41 05 am](https://user-images.githubusercontent.com/19394901/28724908-5b58bdf6-7381-11e7-9eb8-2b45870533c8.png)

**Comment by sgairo** [comment]
This hasn't been seen since its initial reporting on 7/27. Seems to be a blip. @singhshwetaQE after looking at this do you feel comfortable closing it?

**Comment by singhshwetaQE** [comment]
@sgairo I have also noticed same thing during my investigation but I am putting a retry for Add Host To Distributed Switch to make test more robust. I will add that fix soon.
