### ISSUE TITLE
Update CI systems and longevity systems for 1.2 release

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5868]
We have 4 CI systems and 1 longevity/stress running 6.0 and 4 CI + 1 longevity/stress running 6.5.  We need to update each of these to the latest GA release prior to final 1.2 release testing. At least the 6.5 systems need to be 6.5U1 - the most recent release.

**Comment by mhagen-vmware** [comment]
Please make sure as part of this ticket that our ESX and VC version in nightlies is appropriate as well.

**Comment by rogeliosanchez** [comment]
All 6.5 ESXs have been updated to build 5969303.
This includes 4 CI machines and the 4 in our longevity system.

VC for 6.5 longevity system updated to build 5973321

--------------------------------------

All 6.0 ESXs have been updated to build 5572656
This includes 4 CI machines and the 4 in our longevity system.

VC for 6.0 longevity system updated to build 5318172
