### ISSUE TITLE
Nightly Test 21-1 Whitelist "out of resources"

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#5888]
Seen in 6.0:
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1191140/21-1-Whitelist.zip)

from output:
`2017-07-31 12:41:07 -0700: Writing deployment results...
2017-07-31 12:41:07 -0700: Terminating VIM connection ...
2017-07-31 12:41:11 -0700: Exception: NimbusEsxPxeLoadError: ***SCREEN TEXT***
PXE Deploy ESX 5.0 bora-ob-5251623 (release)                                                                                    
Compressed MD5: 5d8c4da6b081e4dd9910bc15aa90ac2b                                                                                
Decompressed MD5: 00000000000000000000000000000000                                                                              
Fatal error: 10 (Out of resources)' does not contain 'To manage this VM use'`

**Comment by gigawhitlocks** [comment]
Is there anything we can actually do about this? Looks like Nimbus just 💩 ed

**Comment by sgairo** [comment]
@rogeliosanchez I agree, Im comfortable closing this issue out.

**Comment by rogeliosanchez** [comment]
I agree.  I'll close it out.
