### ISSUE TITLE
Document our CI/CD pipeline and architecture in our confluence pages

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5896]
User statement:  As an engineer on VIC, I would like to have our entire CI/CD pipeline well documented so that anyone on the team can easily understand and see how to configure and repair the pipeline when necessary.

Details:  Details were provided to @mdharamadas1 

Should be documented here:
https://confluence.eng.vmware.com/display/CNA/Continuous+Integration

Acceptance criteria:
CI/CD pipeline is fully documented within our confluence page

**Comment by mdharamadas1** [comment]
All, there is no code change for this, so please review the following wiki doc and let me know your comments if any. Make sure to checkout "How-To" section, which I plan to keep expanding as I come across such scenarios.
https://confluence.eng.vmware.com/pages/viewpage.action?pageId=240872362

**Comment by mhagen-vmware** [comment]
@mdharamadas1 This looks great, only thing I would like to see added is a server inventory of the ESXi servers as well, similar to this:
https://confluence.eng.vmware.com/pages/viewpage.action?pageId=242254588

**Comment by mdharamadas1** [comment]
@mhagen-vmware yes, I plan to do that soon. Thanks!

**Comment by mhagen-vmware** [comment]
@mdharamadas1 Also, on thinking on it more.  I really want the whole team to have VPN access to OVH, I don't want engineers messaging us in a panic at random times saying something is wrong with the CI system and they don't have the ability to fix it themselves. So as part of this process please start working on making sure they all have access.

**Comment by mdharamadas1** [comment]
sure, sounds good @mhagen-vmware

**Comment by mdharamadas1** [comment]
Im closing this, we can open up new issues as needed.
