### ISSUE TITLE
Adding Harbor as a registry in VIC standalone appliance failes

### ISSUE THREAD

**Issue by vmwarelab** [vmware/vic#5901]
Harbor is set up and can push/pull images to it from a container or OS, so I’m assuming at least that works.
When I try to add it to Admiral via the management console I get the following error(s):
 
Operation for registry https://x.x.x.x:443 failed: Ping attempts failed with errors: Service https://x.x.x.x:443/v1/_ping returned error 404 for GET. id #
Service https://x.x.x.x:443/v2/_catalog?n=1 returned error 401 for GET. id #
 
Trying to directly access those pages gives the same errors.
We’re currently using ver. 1.1.1 of the VIC ova, and other than giving it IP addresses and passwords, there is not much to set up, so I can’t figure out where the problem is coming from.
Since Harbor and Admiral are in the same container, just using different ports, it should be fairly straightforward communications.
 
Any help/thoughts would be greatly appreciated.

**Comment by sflxn** [comment]
@vmwarelab This issue would best be addressed to the Admiral team as it appears to be either an Admiral or Harbor issue.

https://github.com/vmware/admiral/issues

vmware/vic is actually the vic container engine.

**Comment by sflxn** [comment]
Issue moved to [vmware/admiral #141](https://github.com/vmware/admiral/issues/141) via [**ZenHub**](https://www.zenhub.com/)
