### ISSUE TITLE
Nightly 21-1: VCH creation failed due to robot lopping off command string

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5904]
8/1, Build 12824, vSphere 6.0 and 6.5

Whitelist test reports VCH creation failure.  Looking at the CI logs and output.xml, there is something odd going on with robot?

```
KEYWORD OperatingSystem . Run ${vic-machine} create --debug 1 --name=%{VCH-NAME} --target=%{TEST_URL}%{TEST_DATACENTER} --thumbprint=%{TEST_THUMBPRINT} --user=%{TEST_USERNAME} --image-store=%{TEST_DATASTORE} --appliance-iso=${appliance-iso} --bootstrap-iso=${bootstrap-iso} --password=%{TEST_PASSWORD} --force=true --bridge-network=%{BRIDGE_NETWORK} --public-network=%{PUBLIC_NETWORK} --compute-resource=%{TEST_RESOURCE} --timeout %{TEST_TIMEOUT} --insecure-registry harbor.ci.drone.local --volume-store=%{TEST_DATASTORE}/%{VCH-NAME}-VOL:${vol} ${vicmachinetls} ${additional-args}
```

What we actually attempt is,
```
Start / End / Elapsed:	20170802 11:15:05.917 / 20170802 11:15:05.927 / 00:00:00.010
11:15:05.922	INFO	Running command '--registry-ca=./ca.crt create --debug 1 --name=VCH-0-9498 --target=10.192.40.58  --thumbprint=C9:A8:DB:FC:61:82:0E:80:A1:D0:D0:77:CE:AE:55:22:78:33:C2:4A --user=root --image-store=datastore1 --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=e2eFunctionalTest --force=true --bridge-network=VCH-0-9498-bridge --public-network='VM Network' --compute-resource=/ha-datacenter/host/sc2-rdops-vm01-dhcp-40-58.eng.vmware.com/Resources --timeout 30m --insecure-registry harbor.ci.drone.local --volume-store=datastore1/VCH-0-9498-VOL:default --tls-cname=*.eng.vmware.com  2>&1'.	
11:15:05.927	INFO	${output} = 	
00:00:00.003
```

Perhaps there was a change to the _Install VIC Appliance To Test Server_ function?
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1195523/21-1-Whitelist.zip)

**Comment by sflxn** [comment]
Occurred again 8/6, build 12979, vSphere 6.5
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1206592/21-1-Whitelist.zip)

**Comment by sflxn** [comment]
Occurred again 8/7, build 12978, vSphere 6.5
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1212557/21-1-Whitelist.zip)

btw, this is occurring in the test 'Check Login to Insecure Registry (http)'

**Comment by gigawhitlocks** [comment]
This change added `${additional-args}` as an argument to the keyword being called and I suspect it's the reason for this failure. Honestly I'm surprised there aren't other failures related.

Line 159 in VCH-Util.robot, first bit is the commit hash:
```159-7f555692 (Jason Morris   2017-05-31 16:00:51 -0500 159)     [Arguments]  ${vic-machine}=bin/vic-machine-linux  ${appliance-iso}=bin/appliance.iso  ${bootstrap-iso}=bin/bootstrap.iso  ${certs}=${true}  ${vol}=default  ${cleanup}=${true}  ${additional-args}=  
```

**Comment by gigawhitlocks** [comment]
Although that change is pretty old so maybe I'm wrong...

**Comment by sflxn** [comment]
8/8, build 13042, vSphere 6.5, same test.

**Comment by sflxn** [comment]
Occurred again 8/9, build 13080, vSphere 6.5, same test.

**Comment by gigawhitlocks** [comment]
Reopen this issue if the failure is seen on the 8/11 test run
