### ISSUE TITLE
Implement reasonable timeouts for nimbus in the nightly tests

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5908]
Anytime we are waiting for nimbus deploys, we should have a reasonable timeout placed upon the call so that we don't always hit the drone timeout and we can get logs from the nimbus call:

+    ${output}=  Wait For Process  ${pid-vc}  timeout=40 minutes  on_timeout=terminate

**Comment by mdharamadas1** [comment]
@mhagen-vmware looks like `DRONE_TIMEOUT` is set to `30m` then why do you think this wait timeout should be `40m`?

**Comment by mhagen-vmware** [comment]
timeout should be 1hr

**Comment by mhagen-vmware** [comment]
we implemented nightly timeouts awhile ago
