### ISSUE TITLE
Nightly 13-1: vMotion tests fails at the end of steps 6-9

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5916]
8/2, Build build 12824, vSphere 6.0
[13-1-vMotion-VCH-Appliance.zip](https://github.com/vmware/vic/files/1198992/13-1-vMotion-VCH-Appliance.zip)

At the end of steps 6-9, after the unwinding of the tests, post tear down and scanning for leaked secrets, the tests reports critical but pass at the same time.  Unsure if the failure occurs in this section of the test or the next section, steps 10-13.

**Comment by mdubya66** [comment]
may be a drone time out but needs investigation as to why the results are clipped.

**Comment by mhagen-vmware** [comment]
This was a test timeout and it is fixed in: https://github.com/vmware/vic/pull/6005
