### ISSUE TITLE
Inconsistent naming of Demo VCH wizard

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#5920]
In the latest build of the OVA (vic-28d18602-dev.ova, from 3rd August), we see different names for the demo VCH deployment wizard in different places.

OVA Installer calls it the "VIC Engine Install Wizard": 

![vic-wizard-ova](https://user-images.githubusercontent.com/16718369/28968192-29477908-791f-11e7-85a4-7050d1c33859.png)

VM console calls it the "Demo VCH installer":

![vic-wizard-console](https://user-images.githubusercontent.com/16718369/28968196-30376ef8-791f-11e7-8117-e255f58baea8.png)

Getting Started page calls it the "web installer to deploy a demo VCH"

![vic-wizard-gs](https://user-images.githubusercontent.com/16718369/28968428-31f11c16-7920-11e7-8132-7a0f07bd7412.png)

In the doc, we refer to this as the interactive VCH installer and the demo VCH. We need to settle on a single term, and use it consistently.

My suggestions are:

- **Web-based VCH installer** 
- **Web-based demo VCH installer** 
- **VCH installer wizard**
- **Demo VCH installer wizard**

I think that it's reasonably clear that the console and getting started pages are referring to the same thing, but the OVA installer text sounds like it's a different thing. At the very least we need to update the OVA installer text.

**Comment by stuclem** [comment]
Actually, this issue should probably be in vic-product....

**Comment by morris-jason** [comment]
Issue moved to [vmware/vic-product #551](https://github.com/vmware/vic-product/issues/551) via [**ZenHub**](https://www.zenhub.com/)
