### ISSUE TITLE
Nightly 5-6-1: VCH creation with context deadline exceeded

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5939]
8/6, build 12979, vSphere 6.5
[5-6-1-VSAN-Simple.zip](https://github.com/vmware/vic/files/1206474/5-6-1-VSAN-Simple.zip)

CDE error during VCH install in the VSAN Simple nightly tests.

```
Aug  7 2017 02:50:27.159Z DEBUG Error was expected to be ECONNREFUSED: 0x6e
Aug  7 2017 02:50:27.159Z DEBUG Components not yet initialized, retrying
Aug  7 2017 02:51:44.646Z DEBUG Unhandled net error type: context.deadlineExceededError{}
```

**Comment by mdubya66** [comment]
Looks to be test infrastructure issue. Lowering the Priority. Timeout after 15 minutes.

**Comment by mdubya66** [comment]
Same build has been used in every nightly since 2/23. Closing.
