### ISSUE TITLE
Migrate vic-machine to pkg/vsphere/extraconfig

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#594]
vic-machine currently has to construct the extraconfig/guestinfo configuration for the VCH through a manual process of mapping data to guestinfo keys.

pkg/vsphere/extraconfig is now sufficiently functional to serialize the primary config structures directly to the ExtraConfig array in a config spec. Until the other _migration_ issues in this epic are completed this cannot work directly, so may entail an update to the launcher.sh script that generates the CLI arguments if not done as a single PR.

**Comment by emlin** [comment]
Not started yet. Need more discussion for it, so move back to TODO
