### ISSUE TITLE
Nightly 5-22: NFS volume removal failed because in use

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5943]
8/6, build 12979, vSphere 6.5
[5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1206565/5-22-NFS-Volume.zip)

Test 'Volume rm tests'.  Very first test.

```
Error response from daemon: volume 3267fc6c-20a1-46eb-b756-ee0fe881d939 in use by 4b312973d580e04b972a4f4fdda677672157c090f329d442d77ced9001824475
```

**Comment by rajanashok** [comment]
The test has been consistently passing on the past couple of nightly runs, and also verified this test from a local nightly run and the test is passing. Closing this issue.
