### ISSUE TITLE
Migrate portlayer to pkg/vsphere/extraconfig

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#595]
The portlayer should be getting it's configuration directly from guestinfo via extraconfig package instead of through the command line.

Consider moving to a single global `session` as part of this work, avoiding the function signature pollution from passing them around everywhere. This will position us better for moving to a vmomi gateway in the mid-term.

**Comment by hmahmood** [comment]
We will use the struct here for serializing/deserializing the port layer config from guestinfo: https://github.com/vmware/vic/blob/master/metadata/virtual_container_host.go#L35 . The port-layer specific options will be split out into their own struct, and there will be global objects in the port layer package to access this config and a session object.

**Comment by hickeng** [comment]
This is happening slowly as we have to make changes to where we source this information.This should be done for GA for cleanliness purposes.
