### ISSUE TITLE
Container disks not presenting at start time when linux-esx is removed from bootstrap.iso

### ISSUE THREAD

**Issue by goreshmusalay** [vmware/vic#5969]
i deployed  vic appliance  ova as per the documentation,

https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/installing_vic.html

 tried to install the VCH on the vsphere 
sudo ./vic-machine-linux create --user 'Administrator@vsphere.local' -t '10.172.147.46' --name VCH02 --no-tlsverify --no-tls --force --bi bootstrap.iso  --bridge-network DPortGroup --image-store datastore2

it was successful

post it i tred to execute the docker info command

sudo  docker -H  tcp://10.172.146.213:2376 --tls info
but i got the following error
Cannot connect to the Docker daemon at tcp://10.172.146.213:2376. Is the docker daemon running?

**Comment by mdubya66** [comment]
What eversion of vic? 

% vic-machine --version

pleases include the output from the vic-machine create command. 

Do you see the VM from the vSphere UI? Is it running? 

Also, go to the VCH Admin Portal at https://172.16.127.213:2378 and download the Log Bundle with container logs and attach those.

**Comment by goreshmusalay** [comment]
sudo ./vic-machine-linux --version
vic-machine-linux version v1.1.1-10711-56a309f

yes the vm is visible on the vc with the name VCH02 
yes its power on and running

[container-logs.zip](https://github.com/vmware/vic/files/1214391/container-logs.zip)
[logs.zip](https://github.com/vmware/vic/files/1214393/logs.zip)

**Comment by sflxn** [comment]
Segmentation fault in the storage portlayer during startup.  Persona cannot finish initializing because it's waiting on data from portlayer server.

From Portlayer logs:

```
Aug  9 2017 10:50:34.052Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).VolumeStoresList:330] storage_handlers.VolumeStoresList
Aug  9 2017 10:50:34.052Z DEBUG op=259.5 (delta:7.796µs): [NewOperation] op=259.5 (delta:3.103µs) [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).VolumeStoresList:332]
Aug  9 2017 10:50:34.052Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*StorageHandlersImpl).VolumeStoresList:330] [49.534µs] storage_handlers.VolumeStoresList
Aug  9 2017 10:50:34.080Z DEBUG The VCH stats are: [-1 -1 0 0]
Aug  9 2017 10:50:34.087Z DEBUG The VCH stats are: [17382 85830 1493 40181432320]
Aug  9 2017 11:07:45.336Z INFO  connection received
Aug  9 2017 11:07:45.338Z INFO  sending WILL 1
Aug  9 2017 11:07:45.338Z DEBUG entered write loop
Aug  9 2017 11:07:45.339Z DEBUG Sending command: 251 1
Aug  9 2017 11:07:45.339Z INFO  sending WILL 0
Aug  9 2017 11:07:45.339Z DEBUG Sending command: 251 0
Aug  9 2017 11:07:45.339Z INFO  sending WILL 3
Aug  9 2017 11:07:45.340Z DEBUG Sending command: 251 3
Aug  9 2017 11:07:45.340Z INFO  sending DO 0
Aug  9 2017 11:07:45.340Z DEBUG Sending command: 253 0
Aug  9 2017 11:07:45.341Z INFO  sending DO 3
Aug  9 2017 11:07:45.341Z DEBUG Sending command: 253 3
Aug  9 2017 11:07:45.341Z INFO  sending DO 232
Aug  9 2017 11:07:45.341Z DEBUG (vspc) fsm read 121 bytes from the containerVM
Aug  9 2017 11:07:45.341Z ERROR vspc datahandler cannot find the vm with the provided data
Aug  9 2017 11:07:45.341Z DEBUG data handler closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe748a2]

goroutine 84 [running]:
github.com/vmware/vic/lib/vspc.(*handler).dataHdlr(0xc420444910, 0x7f12c90c1890, 0xc420444030, 0xc42076c600, 0x2, 0x600, 0xc420d40000)
	/drone/src/github.com/vmware/vic/lib/vspc/handlers.go:42 +0x52
github.com/vmware/vic/lib/vspc.(*handler).(github.com/vmware/vic/lib/vspc.dataHdlr)-fm(0x7f12c90c1890, 0xc420444030, 0xc42076c600, 0x2, 0x600, 0xc420d40000)
	/drone/src/github.com/vmware/vic/lib/vspc/vspc.go:135 +0x66
github.com/vmware/vic/pkg/telnet.(*Conn).dataHandlerWrapper(0xc420d40000, 0x7f12c90c1890, 0xc420444030, 0x7f12c90c18b8, 0xc42039a150)
	/drone/src/github.com/vmware/vic/pkg/telnet/connection.go:214 +0x183
created by github.com/vmware/vic/pkg/telnet.(*Server).Accept
	/drone/src/github.com/vmware/vic/pkg/telnet/server.go:95 +0x262
```

**Comment by goreshmusalay** [comment]
![untitled](https://user-images.githubusercontent.com/6419898/29202934-4a160e7c-7e8a-11e7-8eb2-22254bc0086a.png)

I tried to  compile the vmware/vic code, and deployed the VCH
the vch was deployed successfully
Still i am hitting into the same issue,

docker -H 10.172.147.177:2375 run  busybox --rm --it
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.172.147.175/sdk: context deadline exceeded.


gmusalay@photon-machine [ ~/vic/bin ]$ docker -H 10.172.147.177:2375 info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: v1.1.0-rc3-0-8704a15
Storage Driver: vSphere Integrated Containers v1.1.0-rc3-0-8704a15 Backend Engine
VolumeStores:
vSphere Integrated Containers v1.1.0-rc3-0-8704a15 Backend Engine: RUNNING
 VCH CPU limit: 77069 MHz
 VCH memory limit: 102.8 GiB
 VCH CPU usage: 5127 MHz
 VCH memory usage: 67.98 GiB
 VMware Product: VMware vCenter Server
 VMware OS: linux-x64
 VMware OS version: 6.5.0
 Registry Whitelist Mode: disabled.  All registry access allowed.
Plugins:
 Volume:
 Network: bridge
Swarm: inactive
Operating System: linux-x64
OSType: linux-x64
Architecture: x86_64
CPUs: 77069
Total Memory: 102.8 GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry.hub.docker.com
Experimental: false
Live Restore Enabled: false
gmusalay@photon-machine [ ~/vic/bin ]$

**Comment by mdubya66** [comment]
Thanks for the updates. We've marked this as a stopper for the next release.

**Comment by mdubya66** [comment]
I also notice the Volume information is missing from docker info. @matthewavery @jzt 

(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker --tls info
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 1
Server Version: v1.1.0-rc3-13058-0b12e65
Storage Driver: vSphere Integrated Containers v1.1.0-rc3-13058-0b12e65 Backend Engine
VolumeStores: default
vSphere Integrated Containers v1.1.0-rc3-13058-0b12e65 Backend Engine: RUNNING
 VCH CPU limit: 2942 MHz
 VCH memory limit: 1.264 GiB
 VCH CPU usage: 49 MHz
 VCH memory usage: 1.433 GiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.5.0
 Registry Whitelist Mode: disabled.  All registry access allowed.
Plugins:
 Volume: vsphere
 Network: bridge
 Log:
Swarm: inactive
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 2942
Total Memory: 1.264GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 0
 Goroutines: 21
 System Time: 2017-08-10T10:44:16.17224418Z
 EventsListeners: 0
Registry: registry.hub.docker.com
Experimental: false
Live Restore Enabled: false

**Comment by goreshmusalay** [comment]
Is there any workaround for this, like a hack that can keep things going for this moment? and we can chip in the fix later?

**Comment by matthewavery** [comment]
@goreshmusalay it would be ideal to see the output from the vic-machine install process as well. I see you are using `--force` which could be masking an issue during the install as well.

**Comment by matthewavery** [comment]
Further investigation: looks like some of the errors thrown right before the seg fault come from our `vspc`(virtual serial port connector) server. `pkg/telnet/connection.go` contains the logging and functions running right before the segfault. @kreamyx was last to touch this section of the code and might have even more insight into what happened here. @goreshmusalay I did not catch what version of VC you are running. Can you please provide that. As it stands, if you hit this consistently I do not know of a workaround right away without digging further.

**Comment by goreshmusalay** [comment]
@matthewavery  the setup which i reported the issue is cleaned off, as i wanted to try out the stuff and was running out of resource
Explaining here is the exact steps that i followed
1) clone vic source  from git hub
git clone https://github.com/vmware/vic ~/vic
2) updated base.sh under ~/vic/isos/base.sh +75  to 
yum_cached -c $cache -u -p $PKGDIR install filesystem coreutils linux --nogpgcheck -y
3) used go-lang 1.8 to compile vic and generate iso
docker run -v $(pwd):/go/src/github.com/vmware/vic -w /go/src/github.com/vmware/vic golang:1.8 make all -j `nproc` --trace
4) created vch using vic-machine
./vic-machine-linux  create --target 10.112.203.213 --user root --name VCHVMXSettings01 --no-tlsverify  --image-store 'datastore1 (2)' --thumbprint '26:0D:27:FB:7D:80:64:9E:0C:F6:D7:49:72:FA:69:62:8B:2D:13:CF'
Aug 15 2017 11:22:50.863Z INFO  ### Installing VCH ####
Aug 15 2017 11:22:50.863Z INFO  vSphere password for root:
Aug 15 2017 11:22:52.614Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Aug 15 2017 11:22:52.619Z INFO  Loaded server certificate VCHVMXSettings01/server-cert.pem
Aug 15 2017 11:22:52.619Z WARN  Configuring without TLS verify - certificate-based authentication disabled
Aug 15 2017 11:22:57.721Z INFO  Validating supplied configuration
Aug 15 2017 11:23:05.012Z INFO  Firewall status: DISABLED on "/ha-datacenter/host/pnq1-vm-eng-dhcp-203-213.eng.vmware.com/pnq1-vm-eng-dhcp-203-213.eng.vmware.com"
Aug 15 2017 11:23:05.498Z WARN  Firewall configuration will be incorrect if firewall is reenabled on hosts:
Aug 15 2017 11:23:05.498Z WARN          "/ha-datacenter/host/pnq1-vm-eng-dhcp-203-213.eng.vmware.com/pnq1-vm-eng-dhcp-203-213.eng.vmware.com"
Aug 15 2017 11:23:05.498Z INFO  Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
Aug 15 2017 11:23:05.771Z WARN  Evaluation license detected. VIC may not function if evaluation expires or insufficient license is later assigned.
Aug 15 2017 11:23:05.771Z INFO  License check OK
Aug 15 2017 11:23:05.772Z INFO  DRS check SKIPPED - target is standalone host
Aug 15 2017 11:23:08.389Z INFO
Aug 15 2017 11:23:11.607Z INFO  Creating Resource Pool "VCHVMXSettings01"
Aug 15 2017 11:23:11.875Z INFO  Creating VirtualSwitch
Aug 15 2017 11:23:12.412Z INFO  Creating Portgroup
Aug 15 2017 11:23:13.153Z INFO  Creating appliance on target
Aug 15 2017 11:23:14.116Z INFO  Network role "client" is sharing NIC with "public"
Aug 15 2017 11:23:14.116Z INFO  Network role "management" is sharing NIC with "public"
Aug 15 2017 11:23:19.560Z INFO  Uploading images for container
Aug 15 2017 11:23:19.561Z INFO          "bootstrap.iso"
Aug 15 2017 11:23:19.561Z INFO          "appliance.iso"
Aug 15 2017 11:24:56.993Z INFO  Waiting for IP information
Aug 15 2017 11:25:06.977Z INFO  Waiting for major appliance components to launch
Aug 15 2017 11:25:10.151Z INFO  Obtained IP address for client interface: "10.112.202.38"
Aug 15 2017 11:25:10.151Z INFO  Checking VCH connectivity with vSphere target
Aug 15 2017 11:25:11.861Z INFO  vSphere API Test: https://10.112.203.213 vSphere API target responds as expected
Aug 15 2017 11:25:17.904Z INFO  Initialization of appliance successful
Aug 15 2017 11:25:17.905Z INFO
Aug 15 2017 11:25:17.906Z INFO  VCH Admin Portal:
Aug 15 2017 11:25:17.906Z INFO  https://10.112.202.38:2378
Aug 15 2017 11:25:17.907Z INFO
Aug 15 2017 11:25:17.907Z INFO  Published ports can be reached at:
Aug 15 2017 11:25:17.907Z INFO  10.112.202.38
Aug 15 2017 11:25:17.908Z INFO
Aug 15 2017 11:25:17.908Z INFO  Docker environment variables:
Aug 15 2017 11:25:17.908Z INFO  DOCKER_HOST=10.112.202.38:2376
Aug 15 2017 11:25:17.909Z INFO
Aug 15 2017 11:25:17.909Z INFO  Environment saved in VCHVMXSettings01/VCHVMXSettings01.env
Aug 15 2017 11:25:17.909Z INFO
Aug 15 2017 11:25:17.910Z INFO  Connect to docker:
Aug 15 2017 11:25:17.910Z INFO  docker -H 10.112.202.38:2376 --tls info

5) run info command to check the installation
docker -H 10.112.202.38:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: v1.1.0-rc3-0-02b4c0a
Storage Driver: vSphere Integrated Containers v1.1.0-rc3-0-02b4c0a Backend Engine
VolumeStores:
vSphere Integrated Containers v1.1.0-rc3-0-02b4c0a Backend Engine: RUNNING
 VCH CPU limit: 12275 MHz
 VCH memory limit: 20.07 GiB
 VCH CPU usage: 362 MHz
 VCH memory usage: 3.8 GiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.5.0
 Registry Whitelist Mode: disabled.  All registry access allowed.
Plugins:
 Volume:
 Network: bridge
Swarm: inactive
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 12275
Total Memory: 20.07 GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry.hub.docker.com
Experimental: false
Live Restore Enabled: false

6) tried to build container
docker -H 10.112.202.38:2376 --tls run -it busybox                                                                               Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
9e87eff13613: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4
Status: Downloaded newer image for library/busybox:latest
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.112.203.213/sdk: context deadline exceeded.

7) hit into the above Error
[container-logs.zip](https://github.com/vmware/vic/files/1224894/container-logs.zip)
[logs.zip](https://github.com/vmware/vic/files/1224895/logs.zip)
 
Attaching logs for more input.

**Comment by matthewavery** [comment]
Found this in the `Hostd` log:

**Comment by matthewavery** [comment]
@goreshmusalay I suspect that the previous problem you were experiencing was #4493 which was fixed in #4501 . That fix did not make it into 1.1.1, by building from latest master above you were able to avoid that issue since the fix is in master.

**Comment by goreshmusalay** [comment]
@matthewavery 
tried up the from the release build of vmware esx,
build number 5310538 (GA)

still hitting into the same issue

**Comment by mhagen-vmware** [comment]
Hi @goreshmusalay 
I executed:
```
nimbus-esxdeploy ESX-test --disk=48000000 --ssd=24000000 --memory=8192 --lease=1 --nics 2 ob-5310538
```

Followed by:
```
./vic-machine-linux create -t 10.192.40.188 -u root --name VCHVMXSettings01 --no-tlsverify --image-store datastore1 --thumbprint D8:1A:7A:EB:44:E6:FC:0C:AC:DE:F8:25:80:09:9D:0A:7D:0E:5F:45
```

And then it succeeded for me:
```
docker -H 10.192.36.26:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
9e87eff13613: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4
Status: Downloaded newer image for library/busybox:latest
/ # 
```

Are you saying that series of steps doesn't work for you?

**Comment by goreshmusalay** [comment]
yes it didnt work for me,
may be the issue is not with the esx but the bootstrap.iso that is generated post compiling the vic source 
after the alteration in base.sh

./vic-machine-linux create --user  root -t 10.192.149.124 --name VCH02 --no-tlsverify --image-store datastore1 --thumbprint 'EB:23:B9:D9:FB:06:4A:9B:8D:6B:DC:CC:6C:D8:D3:B3:FE:B6:B2:50'
Aug 17 2017 05:43:47.138Z INFO  ### Installing VCH ####
Aug 17 2017 05:43:47.139Z INFO  vSphere password for root:
Aug 17 2017 05:43:49.847Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Aug 17 2017 05:43:49.890Z INFO  Loaded server certificate VCH02/server-cert.pem
Aug 17 2017 05:43:49.890Z WARN  Configuring without TLS verify - certificate-based authentication disabled
Aug 17 2017 05:43:50.844Z INFO  Validating supplied configuration
Aug 17 2017 05:43:51.128Z INFO  Firewall status: ENABLED on "/ha-datacenter/host/sc2-rdops-vm04-dhcp-149-124.eng.vmware.com/sc2-rdops-vm04-dhcp-149-124.eng.vmware.com"
Aug 17 2017 05:43:51.154Z INFO  Firewall configuration OK on hosts:
Aug 17 2017 05:43:51.154Z INFO          "/ha-datacenter/host/sc2-rdops-vm04-dhcp-149-124.eng.vmware.com/sc2-rdops-vm04-dhcp-149-124.eng.vmware.com"
Aug 17 2017 05:43:51.250Z WARN  Evaluation license detected. VIC may not function if evaluation expires or insufficient license is later assigned.
Aug 17 2017 05:43:51.251Z INFO  License check OK
Aug 17 2017 05:43:51.251Z INFO  DRS check SKIPPED - target is standalone host
Aug 17 2017 05:43:51.312Z INFO
Aug 17 2017 05:43:51.513Z INFO  Creating Resource Pool "VCH02"
Aug 17 2017 05:43:51.526Z INFO  Creating VirtualSwitch
Aug 17 2017 05:43:51.592Z INFO  Creating Portgroup
Aug 17 2017 05:43:51.685Z INFO  Creating appliance on target
Aug 17 2017 05:43:51.832Z INFO  Network role "management" is sharing NIC with "client"
Aug 17 2017 05:43:51.842Z INFO  Network role "public" is sharing NIC with "client"
Aug 17 2017 05:43:53.760Z INFO  Uploading images for container
Aug 17 2017 05:43:53.792Z INFO          "appliance.iso"
Aug 17 2017 05:43:53.792Z INFO          "bootstrap.iso"
Aug 17 2017 05:44:23.899Z INFO  Waiting for IP information
Aug 17 2017 05:44:53.734Z INFO  Waiting for major appliance components to launch
Aug 17 2017 05:44:54.269Z INFO  Obtained IP address for client interface: "10.192.153.238"
Aug 17 2017 05:44:54.269Z INFO  Checking VCH connectivity with vSphere target
Aug 17 2017 05:44:54.677Z INFO  vSphere API Test: https://10.192.149.124 vSphere API target responds as expected
Aug 17 2017 05:45:02.758Z INFO  Initialization of appliance successful
Aug 17 2017 05:45:02.758Z INFO
Aug 17 2017 05:45:02.758Z INFO  VCH Admin Portal:
Aug 17 2017 05:45:02.759Z INFO  https://10.192.153.238:2378
Aug 17 2017 05:45:02.759Z INFO
Aug 17 2017 05:45:02.759Z INFO  Published ports can be reached at:
Aug 17 2017 05:45:02.759Z INFO  10.192.153.238
Aug 17 2017 05:45:02.760Z INFO
Aug 17 2017 05:45:02.760Z INFO  Docker environment variables:
Aug 17 2017 05:45:02.761Z INFO  DOCKER_HOST=10.192.153.238:2376
Aug 17 2017 05:45:02.762Z INFO
Aug 17 2017 05:45:02.763Z INFO  Environment saved in VCH02/VCH02.env
Aug 17 2017 05:45:02.763Z INFO
Aug 17 2017 05:45:02.763Z INFO  Connect to docker:
Aug 17 2017 05:45:02.763Z INFO  docker -H 10.192.153.238:2376 --tls info
Aug 17 2017 05:45:02.764Z INFO  Installer completed successfully
root@photon-machine [ ~/vic/bin ]# docker -H 10.192.153.238:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: v1.1.0-rc3-0-02b4c0a
Storage Driver: vSphere Integrated Containers v1.1.0-rc3-0-02b4c0a Backend Engine
VolumeStores:
vSphere Integrated Containers v1.1.0-rc3-0-02b4c0a Backend Engine: RUNNING
 VCH CPU limit: 15824 MHz
 VCH memory limit: 42.4 GiB
 VCH CPU usage: 2188 MHz
 VCH memory usage: 751.5 MiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.5.0
 Registry Whitelist Mode: disabled.  All registry access allowed.
Plugins:
 Volume:
 Network: bridge
Swarm: inactive
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 15824
Total Memory: 42.4 GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry.hub.docker.com
Experimental: false
Live Restore Enabled: false
root@photon-machine [ ~/vic/bin ]# docker -H 10.192.153.238:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
9e87eff13613: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4
Status: Downloaded newer image for library/busybox:latest
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.192.149.124/sdk: context deadline exceeded.

[container-logs (1).zip](https://github.com/vmware/vic/files/1230230/container-logs.1.zip)
[logs (1).zip](https://github.com/vmware/vic/files/1230229/logs.1.zip)

**Comment by mhagen-vmware** [comment]
Can you send me the base.iso and appliance.iso that you have built?

**Comment by mhagen-vmware** [comment]
So to be clear you are changing:
yum_cached -c $cache -u -p $PKGDIR install filesystem coreutils linux-esx --nogpgcheck -y
to
yum_cached -c $cache -u -p $PKGDIR install filesystem coreutils linux --nogpgcheck -y

And that is not going to work, we need the linux-esx libraries for our operation.

**Comment by goreshmusalay** [comment]
@mhagen-vmware 
"Can you send me the base.iso and appliance.iso that you have built?"
the nimbus setup created will have the iso as vch is deployed

"And that is not going to work, we need the linux-esx libraries for our operation."

The reason that I am modifying the line is I want additional config enabled kernel, can you point me out how can I have additional config parameter enabled for the bootstrap.iso

**Comment by mhagen-vmware** [comment]
@goreshmusalay If you need the linux package installed, then you should be able to add linux to the bootstrap build line (it will make the image quite a bit bigger) but don't remove linux-esx package.  I am trying to test that right now, but I am having issues right now building VIC locally.  Let me know if that works for you.  That build directive should now be:
yum_cached -c $cache -u -p $PKGDIR install filesystem coreutils linux-esx linux --nogpgcheck -y

**Comment by goreshmusalay** [comment]
okies, ill try at my end and update with the result,
I guess that linux-esx and linux option in base.sh wont go hand in hand
I assumed it to be either or options
will try using them together and let you know if any success

**Comment by goreshmusalay** [comment]
@mhagen-vmware  i tried it a couple of times each time it stuck with following error

Transaction Summary
================================================================================
Install      15 Packages

Total download size: 51 M
Installed size: 103 M
/var/tmp/rpm-tmp.8PqsoZ: line 3: cp: command not found

Installed:
  coreutils.x86_64 0:8.25-2.ph1         filesystem.x86_64 0:1.0-10.ph1
  linux.x86_64 0:4.4.82-1.ph1           linux-esx.x86_64 0:4.4.82-1.ph1

Dependency Installed:
  bash.x86_64 0:4.3.30-10.ph1           glibc.x86_64 0:2.22-13.ph1
  gmp.x86_64 0:6.0.0a-3.ph1             kmod.x86_64 0:21-4.ph1
  libgcc.x86_64 0:5.3.0-4.ph1           libstdc++.x86_64 0:5.3.0-4.ph1
  ncurses.x86_64 0:6.0-5.ph1            pkg-config.x86_64 0:0.28-2.ph1
  readline.x86_64 0:6.3-5.ph1           xz.x86_64 0:5.2.2-2.ph1
  zlib.x86_64 0:1.2.8-5.ph1

mv: target '/tmp/tmp.VkHHFbhkIW/bootfs/boot/vmlinuz64' is not a directory
Makefile:359: recipe for target 'bin/.iso-base.tgz' failed
make: *** [bin/.iso-base.tgz] Error 1

**Comment by mhagen-vmware** [comment]
This appears to be actually a bug in either:
1. the version of photon that we are using
2. the way we are cacheing the packages

If I manually run these commands in the latest photon container it actually works.

**Comment by mhagen-vmware** [comment]
When we roll over to the next release cycle in the next couple of weeks, I will be updating our packages to the latest in the photon repo.  This might be fixed by that.

**Comment by hickeng** [comment]
@goreshmusalay There is a branch in my repo (https://github.com/hickeng/vic/tree/custom-iso) which is a work in progress towards supporting RHEL based bootstrap iso.
This branch is updated to make use of Photon-2.0 beta but I've not got the appliance functional using those yet - the bootstrap was. Some details in the commit message: https://github.com/hickeng/vic/commit/ec986415673d22c25b2be6cf893bee028ac6e862

I would not expect a cVM to boot successfully if you just dropped `linux-esx` - you'd no longer be installing the kernel into the image - however if the `linux` package is an unmodified kernel package then you should just be able to switch them. You could also check that the kernel args line in isolinux.cfg doesn't contain anything the kernel doesn't understand.

For debugging the custom kernel config in this branch I've switched out the init process to /bin/bash so you can use the VM console interactively - https://github.com/hickeng/vic/blob/custom-iso/isos/bootstrap.sh#L111

Something you might be hitting with the regular kernel package is a need to explicitly load certain kernel modules - I've been building up a small manual steps set here to seed my custom bootstrap during debugging: https://github.com/hickeng/vic/blob/custom-iso/isos/bootstrap/rhel69-bootstrap
You may also need to poke the pvscsi driver once to trigger further receipt of paravirtual events (observed with vmfork, don't know if it'll apply after initial module load) with `echo "- - -" > /sys/class/scsi_host/host0/scan`

Regardless, unless the resulting bootstrap image is entirely non-functional, switching the init to bash should be enough to get you `dmesg` output and some manual diagnosis options.

It would be good to know what you're trying to accomplish that has lead you to customizing the bootstrap.iso

**Comment by hickeng** [comment]
Closing due to no reply. Can reopen if needed.
