### ISSUE TITLE
Migrate imgec to pkg/vsphere/extraconfig

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#598]
There are `Migrate X to pkg/vsphere/extraconfig` for most of the components, however imagec is something of a special case:

1. I'd like it to remain a general purpose utility that could be easily consumed by non-VIC use cases
2. It's invoked anew each time we pull an image - it's unlikely that this is frequently enough that gathering guestinfo data is going to hurt performance, but that's something we do need to verify.

At the very least this needs to have an alternative data source available to it for non-VIC usage.

**Comment by mdubya66** [comment]
please assign @hickeng
