### ISSUE TITLE
Set up new drone worker VMs and corresponding ESXs

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#5984]
**User Statement:**

Currently, we have 8 drone workers with 8 ESXi servers to run our CI builds. We are running out of workers every day, so we could use additional workers.

**Details:**
We will make use of existing 9 servers from kov infrastructure, so possibly we can double our workers capacity.
This may include upgrade to ESXi.

**Acceptance Criteria:**
~~CI runs more than 8 builds concurrently.~~
New drone worker VMs and ESXs are created.

**Comment by mdharamadas1** [comment]
@mhagen-vmware @rogeliosanchez this is complete, no code changes in vic project.. if you could verify.

**Comment by mdharamadas1** [comment]
@mhagen-vmware I'm just going to reopen this to re-config worker VMs and add them back to CI.

**Comment by sgairo** [comment]
@mdharamadas1 what's your best estimate for this issue?

**Comment by mdharamadas1** [comment]
I already spent some time on this one and was working on and off since a week and another 2 pointer of work is needed to complete this. I would say total 5 points.

**Comment by mdharamadas1** [comment]
@mhagen-vmware I reconfigured drone worker VMs to increase root partition. I didn't add this workers yet to our CI and plan to do that in a separate ticket later after the release. Please verify and let me know if you see anything missing.
There are total 6 worker VMs, 3 each in the following 2 servers:
https://builds-17.vcna.io/ui
https://builds-18.vcna.io/ui

```
192.168.31.3  containername=vic-drone-worker-9
192.168.31.4  containername=vic-drone-worker-10
192.168.31.5  containername=vic-drone-worker-11
192.168.31.6  containername=vic-drone-worker-12
192.168.31.7  containername=vic-drone-worker-13
192.168.31.8  containername=vic-drone-worker-14
```
