### ISSUE TITLE
"vic-machine inspect config" only works if "config" is the last command-line argument 

### ISSUE THREAD

**Issue by zjs** [vmware/vic#5985]
**VIC version:** 

vic-machine-linux version v1.1.0-rc3-0-2dbf098

**Steps to reproduce:**

Run a command like:
```
bin/vic-machine-linux inspect config --target=10.160.153.157 --user=root --password=e2eFunctionalTest --thumbprint=20:60:4D:2C:DC:38:95:97:56:C3:18:9C:B7:8C:F9:D4:62:57:DB:46 --id=8
```

**Actual behavior:**

```
Incorrect Usage: flag provided but not defined: -target

NAME:
   vic-machine-linux inspect config - Show VCH configuration options

USAGE:
   vic-machine-linux inspect config [command options] [arguments...]

OPTIONS:
   --format value  Determine the format of configuration output. Supported formats: raw, verbose (default: "verbose")
```

**Expected behavior:**

The command operates the same as if `config` is at the end of the argument list.

**Additional details as necessary:**

We should add a test similar to the one here, but with config near the beginning of the argument list.

https://github.com/vmware/vic/blob/master/tests/test-cases/Group6-VIC-Machine/6-09-Inspect.robot#L30

**Comment by willsherwood** [comment]
This is typically the way that CLI subcommands are implemented. The arguments following `inspect` are bound to the inspect target, and _then_ the arguments following `config` are bound to the config target. Ultimately all control is transferred to the "config" target, and it is given the choice to call the inspect target or access its flags.

Take git for example. `git remote -v show` is a valid command that applies a verbose flag to the remote command, and `git remote show -v` is *not* a valid command that tries to apply a nonexistent verbose flag to the show subcommand.

**Comment by stuclem** [comment]
This is documented in [Obtain Virtual Container Host Configuration Information](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/inspect_vch_config.md):

"You must specify the `vic-machine inspect --target`, `--thumbprint`, `--name` or `--id`, and possibly `--compute-resource` options before you include  `config` in the command."

**Comment by zjs** [comment]
If this is the behavior we want, then the help output needs to be changed to reflect that. Currently, it says: `vic-machine-linux inspect config [command options] [arguments...]`.

Note that this means `vic-machine inspect config` and `vic-machine update firewall` seem to behave differently to the user (presumably because all arguments to `vic-machine update firewall` are arguments to the `firewall` subcommand).

**Comment by emlin** [comment]
now the command help is as following. 
```
./bin/vic-machine-linux inspect --help
NAME:
   vic-machine-linux inspect - Inspect VCH

USAGE:
   vic-machine-linux inspect command [command options] [arguments...]

COMMANDS:
     config  Show VCH configuration options

OPTIONS:
   --target value, -t value            REQUIRED. ESXi or vCenter connection URL, specifying a datacenter if multiple exist e.g. root:password@VC-FQDN/datacenter (default: <nil>) [$VIC_MACHINE_TARGET]
   --user value, -u value              ESX or vCenter user [$VIC_MACHINE_USER]
   --password value, -p value          ESX or vCenter password (default: <nil>) [$VIC_MACHINE_PASSWORD]
   --thumbprint value                  ESX or vCenter host certificate thumbprint [$VIC_MACHINE_THUMBPRINT]
   --id value                          The ID of the Virtual Container Host, e.g. vm-220
   --name value, -n value              The name of the Virtual Container Host (default: "virtual-container-host")
   --compute-resource value, -r value  Compute resource path, e.g. myCluster
   --timeout value                     Time to wait for inspect (default: 3m0s)
   --tls-cert-path value               The path to check for existing certificates. Defaults to './<vch name>/'
   --help, -h                          show help
```

The current display of command usage is
The intuition for this result is that the command will look like
`./bin/vic-machine-linux inspect config [options]`
Need to look at the CLI framework for how to improve it

**Comment by emlin** [comment]
This problem is because `vic-machine inspect config` does not accept all of those options, so they have to be specified before the sub command.

Will change the sub command `config` options, to make it honor all options in `inspect` command.

There still have limitations even with this solution. If user specified command options before the sub command `config`, the command still fail for missing those options. The reason is because the option processing is not perfect.
I'm not going to change that at this moment, cause that will impact all other vic-machine commands. And cause even with that, the error message is straight forward, user can easily fix the problem by adding options after the command `config`
