### ISSUE TITLE
Nightly 5-6-2: govc check for returns non empty datastore

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5986]
8/8, build 13042, vSphere 6.5
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1213143/5-6-2-VSAN-Complex.zip)

Last check in the complex VSAN test, 5-6-2, failed.  This failure occurred before the VCH was installed.

```
'56258959-e853-8567-82e2-02001038269a  vmnamespace  standalone-912fc40f0-esx.1-vm.0' should be empty.
```

Appears to be a test setup issue.

**Comment by sflxn** [comment]
Occurred again, 8/10, build 13104, vSphere 6.5, test 5-6-1-VSAN-Simple

[Manual-Test-Cases.Group5-Functional-Tests.5-6-1-VSAN-Simple-VCH-0-1825-container-logs.zip](https://github.com/vmware/vic/files/1223060/Manual-Test-Cases.Group5-Functional-Tests.5-6-1-VSAN-Simple-VCH-0-1825-container-logs.zip)

**Comment by mdubya66** [comment]
Same build has been used in every nightly since 2/23. Closing.
