### ISSUE TITLE
gateway is missing from docker inspect

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic#6010]
#For bug reports, please include the information below:

**VIC version:**

Different results for release 1.1.1 and build 13118

**Deployment details:**

 ./vic-machine-linux create --target vcsa-01a.corp.local --user administrator@corp.local --compute-resource RegionA01-COMP01 --image-store RegionA01-ISCSI01-COMP01 --volume-store RegionA01-ISCSI01-COMP01:default --public-network VM-RegionA01-vDS-COMP --container-network VM-RegionA01-vDS-COMP:routable --bridge-network Bridge02-RegionA01-vDS-COMP --name virtual-container-host-13118 --registry-ca=/etc/docker/certs.d/registry.corp.local/ca.crt --no-tls --thumbprint=F7:68:F0:93:F4:EC:B7:FE:C1:02:00:00:AB:62:1A:50:E8:9A:0E:85

**Steps to reproduce:**

Provision a container attached to an external container-network ("routable" in the example above) using DHCP. Gateway is not populated when displaying "docker inspect" and container is not available on the network.

docker run -d --net routable httpd

on 1.1.1:

![image](https://user-images.githubusercontent.com/8586715/29288465-de19752c-8106-11e7-951f-1ff6530ebf6c.png)

on build-13118:

![image](https://user-images.githubusercontent.com/8586715/29288719-c9aaaa92-8107-11e7-8616-7e1008672206.png)

**Actual behavior:**

1.1.1 behaves as expected, connecting the container to the external network and the service on port 80 is reachable.

build-13118 has some missing information in docker inspect (see "Gateway" field) and the service is not available, even on the same network.

**Expected behavior:**

Expect same behavior between releases for container-network.

**Logs:**

**Additional details as necessary:**

I can reproduce in my lab and gather more information if needed.

**Comment by willsherwood** [comment]
As documented [here](https://github.com/vmware/vic-product/blob/ccad13cf0a5e0a5f97a78e21eca5ca9ba1c95ebb/docs/user_doc/vic_vsphere_admin/vch_installer_options.md#--container-network-firewall--), when configuring container networks to use vSphere portgroups, a level of trust can be configured. The default from 1.1 to 1.2 has changed from *open* to *published*. This means that by default, if you want to access a port group's "80" port, you need to supply `-p 80` to the `docker create/run` command.

This is unrelated to the fact that the gateway is no longer populated in the network endpoint. 

You should be able to either add `--container-network-firewall routable:open` to make the `routable` network completely open on all ports, or add `-p 80` to `docker run` to specifically open port 80 on the port group.

**Comment by stuclem** [comment]
Thanks @willsherwood, this definitely needs to be documented. Opened https://github.com/vmware/vic-product/issues/575 for the doc.

**Comment by mdubya66** [comment]
after talking to @pdaigle the gateway works but is missing from the inspect output. adding kind/note

**Comment by hmahmood** [comment]
This could be worked around with specifying the gateway with `--container-network-gateway`. @pdaigle does the `routable` network have DHCP enabled on it?

**Comment by pdaigle** [comment]
@hmahmood Yes, `routable` network has DHCP which is why I do not provide IP/Gateway/DNS information in `vic-machine` above. Note that only container network seems to have that issue. 

Check out the screenshot below of a container with 2 interfaces (one container network and one user-defined bridge network): only the container has the gateway info missing:

![image](https://user-images.githubusercontent.com/8586715/29538436-d2ee8826-8693-11e7-8a22-8cf24db860d4.png)

**Comment by hmahmood** [comment]
The problem is indeed just the output from inspect. The gateway is correctly set in the container itself. Additionally, as @willsherwood suggested, using `-p 80` does result in the `curl` command succeeding.

**Comment by anchal-agrawal** [comment]
@hmahmood Please add an estimate to this issue, thanks!

**Comment by stuclem** [comment]
An attempt at a release note:

----

- <b>Gateway information is missing from `docker inspect`. [#6010](https://github.com/vmware/vic/issues/6010)</b><br>If you configured the `--container-network-gateway` option on a VCH, the gateway is created correctly but does not show up in the output of `docker inspect` commands that are run on containers on that network.

-----

@hmahmood @anchal-agrawal does this cover it? Thanks!

**Comment by hmahmood** [comment]
@stuclem the problem will only occur if the container network is using DHCP, and `--container-network-gateway` is not specified.

**Comment by stuclem** [comment]
Thanks @hmahmood. Updated to:

---

- <b>Gateway information is missing from `docker inspect`. [#6010](https://github.com/vmware/vic/issues/6010)</b><br>If you configured a containernetwork on a VCH, if this network uses DHCP, and if you did not specify `--container-network-gateway`, the gateway is created correctly but does not show up in the output of `docker inspect` commands that are run on containers on that network.

----

Is this OK now?

**Comment by hmahmood** [comment]
@stuclem "... the gateway is configured correctly ...". All else looks OK.

**Comment by stuclem** [comment]
Done, thanks @hmahmood

**Comment by mdubya66** [comment]
not a requirment for 1.3, removing. @pdaigle please add it back if you think it's correct
