### ISSUE TITLE
extraconfig requires special code to handle net.IPNet

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#602]
Types requires some special handling as they may have unexported fields but in the IPNet case the struct is already flat

```
    30	type IP []byte
    31	
    32	// An IP mask is an IP address.
    33	type IPMask []byte
    34	
    35	// An IPNet represents an IP network.
    36	type IPNet struct {
    37		IP   IP     // network number
    38		Mask IPMask // network mask
    39	}
```
yet we still required https://github.com/vmware/vic/pull/600

**Comment by hickeng** [comment]
Added it to the migration epic as that's where we'll likely hit these problems.
