### ISSUE TITLE
Creating an image failed: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:timeout waiting for layer to present in /sys/bus/pci/devices/0000:03:00.0/host0/subsystem/devices/0:0:0:0/block}

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6039]
Looks like a dupe of #2340 :

Seen in build:
https://ci.vcna.io/vmware/vic/13162

From personality log:
```
Aug 14 2017 18:06:02.239Z DEBUG Creating an image failed: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:timeout waiting for layer to present in /sys/bus/pci/devices/0000:03:00.0/host0/subsystem/devices/0:0:0:0/block}
```

[integration_logs_13162_a479cf7fc35636a58e705d82842409deaae3553b.zip](https://github.com/vmware/vic/files/1223793/integration_logs_13162_a479cf7fc35636a58e705d82842409deaae3553b.zip)

**Comment by dougm** [comment]
yeah, this is a dup of #2340 - I'm going to reopen that as there is more history there.
