### ISSUE TITLE
Improve vic-machine error message when adding --container-network-dns before --container-network

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic#6048]
**VIC version:**

build-13202

**Deployment details:**

`vic-machine-linux create --target vcsa-01a.corp.local/dc01-east --user administrator@vsphere.local --compute-resource cluster01 --image-store iscsiDatastore1 --volume-store iscsiDatastore1:default --public-network dvPortGroup01 --dns-server 10.10.0.10 --container-network-dns dvPortGrou01:10.10.0.10 --container-network dvPortGroup01:routable --container-network-firewall dvPortGroup01:open --bridge-network vch1-bridge --name virtual-container-host-13202 --no-tls`

**Steps to reproduce:**

Run command above ensuring that `--container-network-dns` is defined before `--container-network`

**Actual behavior:**

The error message displayed is not helpful:

`Aug 16 2017 15:19:29.726Z ERROR The following container network dns is set, but CONTAINER-NETWORK cannot be found. Please check the --container-network and --container-network-dns settings
Aug 16 2017 15:19:29.726Z ERROR 	dvPortGrou01:[10.158.204.3], "dvPortGrou01" should be a vSphere network name
Aug 16 2017 15:19:29.726Z ERROR --------------------
Aug 16 2017 15:19:29.726Z ERROR vic-machine-linux create failed: Inconsistent container network configuration.`

This hints at a misconfiguration where the issue is caused by the order in which the arguments are defined.

**Expected behavior:**

Parse/validate the complete list of command line arguments before generating the error. Ordering of arguments should not matter.

- OR - 

Add information to the error advising the user to define `--container-network` before `--container-network-dns`

**Comment by anchal-agrawal** [comment]
@pdaigle The `vic-machine create` command uses `--container-network-dns dvPortGrou01:10.10.0.10`, where `dvPortGrou01` looks like a typo and shows up in the error message as well: `ERROR dvPortGrou01:[10.158.204.3], "dvPortGrou01" should be a vSphere network name`.

I've verified that the order in which the container network args are specified doesn't matter. Please re-open if you're still seeing the ordering issue.
