### ISSUE TITLE
VIC Engine cannot add static routes

### ISSUE THREAD

**Issue by gucarreira** [vmware/vic#6060]
In my environment I need to add some static routes because my default gateway doesn't know my NSX LAB. 

**Details:**
VIC Engine is a Photon OS, but every time when I change /etc/systemd/network/09-vic.network and when restart network, my file is overwritten.

**Acceptance Criteria:**
I add some properties in vAPP Options and change /etc/vmware/network-config.sh to add two static routes.

Can add this feature in future releases, one or more static routes.

**VIC version:**
vic-v1.1.1_56a309fb.ova, downloaded from my.vmware.com

**Comment by anchal-agrawal** [comment]
Pinging @morris-jason since he's worked on this component recently.

**Comment by morris-jason** [comment]
Can you clarify your issue please? Are you having trouble using a static gateway in the ova, meaning that the current network config is broken, or is this a feature request for multiple static routes in the future?

**Comment by gucarreira** [comment]
This issue is a future request for multiple static routes.
Static default gateway in OVA properties works fine.
The problem is OVA properties doesn't have fields to add static routes.
thanks

**Comment by anchal-agrawal** [comment]
Issue moved to [vmware/vic-product #606](https://github.com/vmware/vic-product/issues/606) via [**ZenHub**](https://www.zenhub.com/)
