### ISSUE TITLE
Write integration test for https://github.com/vmware/vic/pull/5483

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6065]
We need a negative integration test for #5483

**Comment by willsherwood** [comment]
I have a comment on that PR that may be helpful to this issue, so I'll quote it here.

> Closing this prior to leaving: pending an integration test. The Harbor robot utility package currently does not function properly to copy server certificates since the removal of Harbor UI. When Admiral provides the necessary API for accessing Harbor instances, the test should be trivial to write:
> 
> Start an instance of harbor, or use an existing one
Login with an incorrect password and verify that an 'invalid username or password' message is shown, and not another obscure error.
Login with a correct password and verify that we can correctly pull a private image.

**Comment by sflxn** [comment]
It looks like @willsherwood added the negative testing.

https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-27-Docker-Login.robot#L29
https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-27-Docker-Login.robot#L32

**Comment by mhagen-vmware** [comment]
agreed, that should satisfy our requirements.
