### ISSUE TITLE
Separate integration test environment

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#607]
The build is slow!
Separate out the integration tests from our Drone build.

Currently proposed solution:
Setup Jenkins
Run integration tests for each PR
Remove integration tests from Drone build

Jenkins will be run on our local ESX for now - not publicly accessible

**Comment by frapposelli** [comment]
We have a separate drone instance set up for integration/end-to-end tests (living at https://e2e.ci.vmware.run), so integration can be run in parallel (and eventually report another status back into github PRs).

Also, I see you are using plain `golang` containers to run your builds, if those require package installs at runtime they will significantly and negatively impact build times, our approach is to build a separate container `FROM golang` adding all the required packages in it and use the resulting container as the starting point for the CI job.

**Comment by hickeng** [comment]
@frapposelli does that mean separate repo for the integration tests? I couldn't see a sane way to have more than one .drone.yml file for the different facets of build/test (or a way to invoke specific build steps).

**Comment by frapposelli** [comment]
@hickeng not a separate repo, just a separate file, the https://e2e.ci.vmware.run instance will look for `.drone-e2e.yml` in the repo (and respective `.drone-e2e.sec` secrets file). This setup is also supported when running local `drone exec` builds (with a `--yaml` flag that directs drone to the right build).

**Comment by casualjim** [comment]
we changed drone and that change was accepted upstream to have more than one drone.yml file

https://github.com/vmware/cello/blob/master/.drone-e2e.yml

I'm also deploying a bunch of new instances tonight because we're getting more customers to use this infrastructure. So the latency that was reported by @fdawg4l earlier this week should hopefully largely disappear after this because we're not collocating builds on instances anymore.

**Comment by emlin** [comment]
@frapposelli so you're building the build container first from one yaml file, and then run test based on the binary from, e.g. bintray through another yaml file?
I'm looking for the solution and issue #579 filed that.

**Comment by emlin** [comment]
The local jenkins env is ready, and will run each job in one docker container.
Current test passed with following scenario:
- Pull source code from github vic master branch
- Build source code
- Run integration tests based on ESXi env
- Run test again on VC env

The target of this issue to make the test run based on bintray binary, and execute periodically. So please make sure to check the build env manually, before we can actually post information back to github pull request.

**Comment by andrewtchin** [comment]
Integration test build is running hourly and will email dev alias upon failed build. Following work is in #646
