### ISSUE TITLE
docker create failed in VC

### ISSUE THREAD

**Issue by emlin** [vmware/vic#608]
~/go/src/github.com/vmware/vic isw/right-rp-vc
❯ docker -H 10.17.109.70:2376 --tls --tlscert='./ian-vch-cert.pem' --tlskey='./ian-vch-key.pem' pull busybox
Using default tag: latest
latest: Pulling from library/busybox
385e281300cc: Already exists 
a3ed95caeb02: Already exists 
Status: Image is up to date for library/busybox:latest

~/go/src/github.com/vmware/vic isw/right-rp-vc
❯ docker -H 10.17.109.70:2376 --tls --tlscert='./ian-vch-cert.pem' --tlskey='./ian-vch-key.pem' create busybox
Error response from daemon: No such image: bc744c4ab376115cc45c610d53f529dd2d4249ae6b35e5d6e7a96e58863545aa

**Comment by fdawg4l** [comment]
@emlin, this is from the top of master, right? Can you retry create using the hash for busy box? I think there may be a bug in the image store cache and want to confirm.

**Comment by emlin** [comment]
Sorry for the confusion here. After I clean up the VIC directory from datastore, the docker create works well in VC.
I think you might changed the file structure in datastore. So I'll close this bug.
