### ISSUE TITLE
Delete container from UI should stop the container and delete instead of throwing "You cannot remove a running container. Stop the container before attempting removal or use -f"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#6087]
![image](https://user-images.githubusercontent.com/25006749/29607527-222f9e30-880f-11e7-88d4-065e8d633b24.png)
OVA : vic-4d3812aa-dev.ova

I matched few 1000 containers by name and attempted to delete from UI. Few of the containers got deleted with this error. 980 containers are in RUNNING state of the selection made.

UI anyway asks for confirmation before delete, hence the option should poweroff the container and delete, instead of asking the user to take action.

Log says:
Aug 23 08:47:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: [64011][I][2017-08-23T08:47:51.111Z][6452][8282/request/resource-removal-operations/e185b3a951f2b07555767bead3680][validateStageTransitionAndState][Moving from STARTED(ERROR) to FAILED(ERROR). Caller: [https://10.197.37.132:8282/request/resource-removal-operations/e185b3a951f2b07555767bead3680]]
Aug 23 08:47:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: [64012][W][2017-08-23T08:47:51.112Z][6452][8282/request/resource-removal-operations/e185b3a951f2b07555767bead3680][handleFailedStagePatch][Task failed with: Service https://10.197.37.158:2376/v1.24/containers/82bce94b61759071c19c2601d926ef7167204b7ad013dd58150d485c3cc4bd7f?v=1&force=1 returned error 409 for DELETE. id 6260710 message You cannot remove a running container. Stop the container before attempting removal or use -f; Reason: {"message":"You cannot remove a running container. Stop the container before attempting removal or use -f"}
Aug 23 08:47:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: ]
Aug 23 08:47:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: [64013][I][2017-08-23T08:47:51.122Z][6452][8282/request/resource-removal-operations/e185b3a951f2b07555767bead3680][notifyCallerService][Callback to [/requests/e185b3a951f2b07555767bead3680] with state [FAILED]]
Aug 23 08:47:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: [64014][I][2017-08-23T08:47:51.124Z][6449][8282/requests/e185b3a951f2b07555767bead3680][validateStageTransitionAndState][Moving from STARTED(ALLOCATING) to FAILED(ERROR). Caller: [https://10.197.37.132:8282/request/resource-removal-operations/e185b3a951f2b07555767bead3680]]
Aug 23 08:47:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: [64015][W][2017-08-23T08:47:51.130Z][32][8282/requests/e185b3a951f2b07555767bead3680][handleFailedStagePatch][Task failed with: Service https://10.197.37.158:2376/v1.24/containers/82bce94b61759071c19c2601d926ef7167204b7ad013dd58150d485c3cc4bd7f?v=1&force=1 returned error 409 for DELETE. id 6260710 message You cannot remove a running container. Stop the container before attempting removal or use -f; Reason: {"message":"You cannot remove a running container. Stop the container before attempting removal or use -f"}
Aug 23 08:47:51 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: ]

**Comment by lgayatri** [comment]
Even when matched with STOPPED status and deleting containers, operations says
"https://10.197.37.166:2376/v1.24/containers/fda916f1d0e7a9548e49410b56512d12e8559f4d06af7572efbc5efd547f3d2b?v=1&force=1 returned error 409 for DELETE. id 8793776 message You cannot remove a running container. Stop the container before attempting removal or use -f; Reason: {"message":"You cannot remove a running container. Stop the container before attempting removal or use -f"}"
![image](https://user-images.githubusercontent.com/25006749/29611169-328df492-881a-11e7-8057-12f4fd0db5ae.png)

**Comment by cgtexmex** [comment]
@lgayatri I am unable to recreate this issue with the same build you've referenced.  I successfully deleted multiple containers in various states (stopped & running) without any errors.

In future issues please provide the relevant VCH Logs -- as an example for this issue the logs for `10.197.37.166` would have been helpful.

If you are able to recreate then reopen this issue and provide the relevant logs.
