### ISSUE TITLE
Deleting 1000+ containers threw   "VCH being marked as DISABLED"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#6088]
![image](https://user-images.githubusercontent.com/25006749/29609726-af67738a-8815-11e7-9c6a-babc720c473b.png)
...
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: [84572][W][2017-08-23T09:33:24.064Z][21][8282/adapters/docker-service][lambda$processDeleteContainer$40][Failure while removing container [/resources/containers/e185b3a951f2b0755576563092b6e] of host [/resources/compute/e185b3a951f2b0755576562fe36b1]]
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: [84573][W][2017-08-23T09:33:24.065Z][21][8282/adapters/docker-service][fail][Fail: java.lang.Exception: null; Reason: {"stackTrace":["com.vmware.xenon.common.Operation.fail(Operation.java:1233)","com.vmware.xenon.common.http.netty.NettyHttpServiceClient.failExpiredRequests(NettyHttpServiceClient.java:846)","com.vmware.xenon.common.http.netty.NettyHttpServiceClient.handleMaintenance(NettyHttpServiceClient.java:793)","com.vmware.admiral.adapter.docker.service.RemoteApiDockerAdapterCommandExecutorImpl.handlePeriodicMaintenance(RemoteApiDockerAdapterCommandExecutorImpl.java:142)","com.vmware.admiral.adapter.docker.service.AbstractDockerAdapterService.handlePeriodicMaintenance(AbstractDockerAdapterService.java:103)","com.vmware.xenon.common.StatelessService.handleMaintenance(StatelessService.java:267)","com.vmware.xenon.common.ServiceMaintenanceTracker.lambda$performServiceMaintenance$1(ServiceMaintenanceTracker.java:175)","com.vmware.xenon.common.ServiceHost.executeRunnableSafe(ServiceHost.java:5190)","com.vmware.xenon.common.ServiceHost.lambda$schedule$58(ServiceHost.java:5184)","java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)","java.util.concurrent.FutureTask.run(FutureTask.java:266)","java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)","java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","java.lang.Thread.run(Thread.java:748)"],"statusCode":408,"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.admiral.adapter.docker.service.AbstractDockerAdapterService.fail(AbstractDockerAdapterService.java:374)
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.admiral.adapter.docker.service.DockerAdapterService.lambda$processDeleteContainer$40(DockerAdapterService.java:1248)
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.xenon.common.Operation.completeOrFail(Operation.java:1317)
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.xenon.common.Operation.fail(Operation.java:1295)
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.xenon.common.Operation.fail(Operation.java:1223)
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.fail(NettyHttpServiceClient.java:725)
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.xenon.common.http.netty.NettyHttpServiceClient.lambda$sendHttpRequest$1(NettyHttpServiceClient.java:580)
Aug 23 09:33:24 vic-st-h2-132.eng.vmware.com start_admiral.sh[810]: at com.vmware.xenon.common.Operation.lambda$nestCompletion$1(Operation.java:1348)

[log.zip](https://github.com/vmware/vic/files/1244970/log.zip)

**Comment by lgayatri** [comment]
portlayer.log from 10.197.37.157
[container-logs (3).zip](https://github.com/vmware/vic/files/1245001/container-logs.3.zip)

Aug 23 2017 09:33:41.563Z INFO  Reconfigure: committed update to d1c7815f04350c02a6c2605944dd315cb3844acf5c0aaf7ef5d43ee8b49cd514 with change version: 2017-08-22T11:49:42.104875Z
Aug 23 2017 09:33:41.563Z WARN  container and handle PowerStates do not match: poweredOn != poweredOff
Aug 23 2017 09:33:42.541Z ERROR op=291.429: unexpected fault on task retry: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:"poweredOn", ExistingState:"poweredOff"}
Aug 23 2017 09:33:46.166Z ERROR op=291.427: unexpected fault on task retry: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:"poweredOn", ExistingState:"poweredOff"}
Aug 23 2017 09:33:46.227Z WARN  power off 5a930d1f0aecf002017456787d468e1b4d81c07b97f3b250051b087b51dabd79 task skipped (state was already poweredOff)
Aug 23 2017 09:33:46.240Z INFO  Reconfigure: committed update to 809c8fb1dfdff64d78f4500086aa12337c28379f8795527c586ef8740f3fdc47 with change version: 2017-08-22T11:37:47.544688Z
Aug 23 2017 09:33:46.241Z WARN  container and handle PowerStates do not match: poweredOn != poweredOff
Aug 23 2017 09:33:46.248Z ERROR op=291.436: unexpected fault on task retry: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:"poweredOn", ExistingState:"poweredOff"}

**Comment by cgtexmex** [comment]
@lgayatri `Host[...] has been marked [DISABLED]..` is an error from Admiral -- I looked at the provided `container-logs(3)` and see no errors in that VCH log.  I think you'll need to pull someone in from the Admiral team to help...

**Comment by cgtexmex** [comment]
I'm closing this for now -- if it is found out to be an issue with vic then reopen and provide the the steps taken to encounter the issue and upload _all_ relevant VCH logs.
