### ISSUE TITLE
Clean up image manifests and image folders from the VCH's /tmp after docker pull 

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#6093]
**User Statement:**

As a vic admin, I don't want to have these image manifest files and obsoleted image folders (e.g., `https/registry.hub.docker.com/v2/library/busybox`) in the `/tmp` directory on my VCH.

**Details:**
The image manifest files are stored in `/tmp` of the VCH as temporary files. They will be cleared after the VCH is restarted. 

Here is the content under `/tmp` 
```
root@ [ /tmp ]# ls -al
drwxrwxrwt  8 root root  280 Aug 16 21:19 .
drwxr-xr-x 16 root root  440 Aug 15 15:59 ..
-rw-------  1 root root  527 Aug 15 15:59 202444564
-rw-------  1 root root 7426 Aug 16 02:27 381251435
-rw-------  1 root root  527 Aug 16 02:20 568379272 (image manifest)
drwxr-xr-x  3 root root   60 Aug 15 15:59 https
```
```
root@ [ /tmp ]# ls -al https/registry.hub.docker.com/v2/library/busybox/
drwxr-xr-x 2 root root 40 Aug 15 15:59 .
drwxr-xr-x 3 root root 60 Aug 16 02:28 ..
```

**Acceptance Criteria:**
- `/tmp` should not contain image manifest files and related folders

**Workaround**
- restart VCH

**Comment by hickeng** [comment]
See in https://github.com/vmware/vic/issues/3624#issuecomment-409868336.

**Comment by wjun** [comment]
The empty image folders under tmp cannot be removed as there may have parallel image pull requests.
