### ISSUE TITLE
Dependency on awk causes plugin install/upgrade to fail

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic#6094]
**VIC version:**

vic dev-build 13338

**Steps to reproduce:**

Run the vCenter Plugin install/upgrade (vic/ui/VCSA/[install.sh,upgrade.sh] on a system with `awk` missing, the install.sh and upgrade.sh scripts fails.

![image](https://user-images.githubusercontent.com/8586715/29634661-8ec74e68-8818-11e7-9473-8c5b5505ad90.png)

**Actual behavior:**

The install.sh and upgrade.sh scripts fail.

While the output states `./install.sh: line 129: awk: command not found`, the actual error message being printed is unclear (caused by the thumbprint field being blank).

**Additional details:**

`awk` is not part of the default Photon OS install and needs to be added with `tdnf install gawk`.

**Comment by jooskim** [comment]
Just confirmed with @pdaigle that `cut` does come with default Photon OS. Will replace `awk` with it in the future release
