### ISSUE TITLE
set debug to 1 by default

### ISSUE THREAD

**Issue by emlin** [vmware/vic#6096]
As a VIC user, if any error happens, I want to download log bundle with enough information immediately, so that I don't have to enable debug and reproduce the issue once again.

**Comment by emlin** [comment]
The reason to have this issue filed is based on the experience we deal with customer reported issue. For what ever failure happened, we'll need debug log to triage the issue, but by default we disabled the debug.
This means user will need to enable debug through vic-machine configure, which involves one power cycle of VCH, and it will impact other running containers. And then user will need to redo the operation to reproduce that issue, that usually is not doable because the issue might related to some vSphere operations, HA, VM migration, etc.
But the downside of this approach is that for a normal VCH, more log will be generated. So please @hickeng and @mhagen-vmware leave your comments for it

**Comment by emlin** [comment]
@mdubya66 ^^^

**Comment by emlin** [comment]
Also @stuclem , after this issue is fixed, we'll need to update document, thanks

**Comment by anchal-agrawal** [comment]
@emlin Can we set the priority and other labels and update the pipeline if this is in progress?
