### ISSUE TITLE
Change the "not yet supported" messaging the Docker API server that is generated by Swagger

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#61]
Currently, the message that is generated by a Docker API server, generated from the swagger spec in go-swagger has the following wording:

office1-sfo2-dhcp96:~ locn$ curl -i http://127.0.0.1:51434/v1.21/_ping
HTTP/1.1 501 Not Implemented
Content-Type: application/json
Date: Fri, 05 Feb 2016 21:02:17 GMT
Content-Length: 51

"operation misc.Ping has not yet been implemented"

We should consider a different wording in the message part (the one in quotes not the HTTP header).

**Comment by hickeng** [comment]
no longer using swagger generated personality
