### ISSUE TITLE
Provide alternate / short names for installer commands

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#610]
Provide short names for the various vic-machine install options.

**Comment by hickeng** [comment]
@cgtexmex Can you furnish some examples?

If we split datacenter out into a separate option then I'll consider renaming  compute-resource to pool, however my experience has been that short options are not great for usability or consumption. I'd much rather add tab completion mechanisms where possible.

**Comment by hickeng** [comment]
@stuclem @cgtexmex closing this as the switch to urfav/cli should provide this. If not, as per above comment, it provides little additional value for users.
