### ISSUE TITLE
Management Interface - Add hosts

### ISSUE THREAD

**Issue by gucarreira** [vmware/vic#6103]
**Details:**
After provision VCH then using VIC Management interface to add host, I can't add description name.
I add host.

![image](https://user-images.githubusercontent.com/26637254/29674088-7a4e95c2-88c7-11e7-92b0-059e32e4d406.png)

After added
![image](https://user-images.githubusercontent.com/26637254/29674159-aec82ab6-88c7-11e7-94b1-c772e0da882b.png)

Edit and change IP name to description.

![image](https://user-images.githubusercontent.com/26637254/29674263-061b469a-88c8-11e7-9971-b9b587d10469.png)

**VIC version:**
VIC Build number 1.1.1-7989

**Deployment details:**
./vic-machine-linux create --target snedevops01 --user 'administrator@vsphere.local' -p ******* \
--no-tlsverify \
--no-tls \
--insecure-registry harbor.devops \
--thumbprint 4B:D6:72:EA:F2:1C:80:6C:D3:E6:32:90:B7:16:31:12:17:14:69:CA \
--name VCH-dev-NoBridged \
--compute-resource 'DevOps Cluster 6x' \
--image-store ds_nfs-ephemeral-01/vch-dev-nobridged \
--volume-store ds_nfs-ephemeral-01/vch-dev-nobridged:default \
--dns-server 10.171.162.24 \
--bridge-network 'Template' \
--public-network 'vxw-dvs-84-virtualwire-9-sid-500007-External' \
--public-network-ip 192.168.50.251/24 \
--public-network-gateway '192.168.50.1' \
--client-network 'vxw-dvs-84-virtualwire-9-sid-500007-External' \
--management-network 'vxw-dvs-84-virtualwire-9-sid-500007-External' \
--https-proxy https://squid.devops:8080 \
--force \
--container-network FE-NLB-620_10.171.162:FE-NLB-620_10.171.162 \
--container-network-gateway FE-NLB-620_10.171.162:10.171.162.21/24 \
--container-network-ip-range FE-NLB-620_10.171.162:10.171.162.250-254 \
--container-network-dns FE-NLB-620_10.171.162:10.171.162.24

**Comment by mdubya66** [comment]
Moving to admiral

**Comment by mdubya66** [comment]
Issue moved to [vmware/admiral #184](https://github.com/vmware/admiral/issues/184) via [**ZenHub**](https://www.zenhub.com/)
