### ISSUE TITLE
Installer should utilize govc env variables if available

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#611]
Allow the vic-machine installer to utilize govc environment variables (URL, Datastore, etc..) when available

**Comment by hickeng** [comment]
This is not the right fix - this introduces massive potential confusion for a convenience use case that is almost unique to the vic dev team. This could easily be accomplished with a very simple wrapper script around vic-machine.

The design doc for vic-machine mentions a manifest which is how I'd like us to consume partial/saved VCH configs.
