### ISSUE TITLE
Demo VCH has no volume store - deployment of any container that declares a volume fails

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#6145]
**User Statement:**

As a user of VIC, if I deploy a demo VCH, I expect to be able to deploy some simple containers to it without error.

**Details:**

Many of the most popular container images in DockerHub specify a volume in the Dockerfile. When deployed, VIC will try to create an anonymous volume using the default volume store. The fact that the Demo VCH doesn't present the option to create a default volume store eliminates a significant percentage of the most popular images from deploying successfully.

This makes for a problematic first user experience, because to have the knowledge to match the error to the fact that the VCH didn't have sufficient configuration isn't easy.

I'm not sure what the reasoning was for not allowing for the specification of a default volume store, given that we specify an image store. If there's no obviously good reason, I suggest we add that in.

At the very least, we need to clearly document this in our caveats about the demo VCH. We should clearly display the error message, we should suggest some popular containers that could be deployed that don't need Volumes and we should link to how to use vic-machine configure to add a Volume store.

**Comment by corrieb** [comment]
The error you get from Admiral is "No volume store named (default) exists; Reason: {"message":"No volume store named (default) exists"}"

**Comment by stuclem** [comment]
Removed kind/user-doc from this one as we no longer document the demo VCH wizard. @mdubya66 shouldn't we close this one, since we don't even ship it any more?
