### ISSUE TITLE
Networks lose name resolution function after endpoint power cycle

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#6157]
**User Statement:**

As a Cloud Admin, if I upgrade a VCH or re-configure it, I expect the networks to come back up functional in such a way that my containers can continue to resolve each other.

**Details:**

I discovered today that if you have two containers on a network you've created that can resolve each other by name, if you power cycle the VCH (upgrade / re-configure), when it comes back up, the containers have lost the ability to resolve each other by name.

Worse than that, new containers deployed to that network cannot resolve each other by name either.

This is using rc1 build on a VC setup

```
docker network create foo
docker run -d --net foo --name c1 debian sleep 1000
docker run -d --net foo --name c2 debian sleep 1000
docker exec c1 ping c2
(should work fine)
docker exec c2 ping c1
(should work fine)

```
Now power-cycle the VCH endpoint and run the following tests:
```
docker exec c1 ping c2
(hangs)
docker exec c2 ping c1
(hangs)
docker stop c1 c2
docker rm c1 c2
docker run -d --net foo --name c1 debian sleep 1000
docker run -d --net foo --name c2 debian sleep 1000
docker exec c1 ping c2
(hangs)
```

**Comment by hickeng** [comment]
Very quick investigation showed:
* rebooting VCH breaks name resolution on non-default bridge networks
* gateway ip alias for those networks has not been applied in the endpoint VM
* running `ip addr add 172.17.0.1/16 dev bridge` corrected the problem

**Comment by hickeng** [comment]
@hmahmood @caglar10ur this is urgent
@mdubya66 we should try to get this into 1.2. I honestly cannot see how reconfigure or upgrade can be considered functional without fixing this.

**Comment by hmahmood** [comment]
We're not adding the gateway ip address to the bridge interface on the vch when loading the scope info from the kv store at startup. As @hickeng pointed out adding the address to the interface fixes the problem.

**Comment by mdubya66** [comment]
we'll pull this into rc3 on friday.
