### ISSUE TITLE
Update drone workers to run one build at a time

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6169]
Currently, `DOCKER_MAX_PROCS` is not set to any value on drone agent, which might be running more than one build concurrently. This might cause unnecessary issues with builds, so we need to make sure one worker runs one build at a time.

Details:
I tried setting `DOCKER_MAX_PROCS=1` on all the drone workers and it doesn't seem to work as expected in the sense that a lot of builds started queuing up with just 2-3 builds running (we have at least 8 workers). This needs to be tested thoroughly.

**Comment by mdharamadas1** [comment]
@zjs this belongs to team COBD and not cops.

**Comment by sgairo** [comment]
@mdharamadas1 what are your thoughts on an estimate? Once estimated, this can be moved to the backlog.

**Comment by mdharamadas1** [comment]
I'm not sure how much effort this would require. The actual change itself is like 1-2 pointers but take more effort to verify it. Last time I did this change broke our CI, so need to careful. I may have to have my own drone setup to verify this before doing it on production CI, so in that case it would be 5 pointers.

**Comment by mdharamadas1** [comment]
@mhagen-vmware This is complete, pls verify.

**Comment by mdharamadas1** [comment]
This change failed verification, so reverted. We tried twice to do this update with Drone `v0.5` without success, so instead we are going to focus on updating drone version to latest. Closing this for now.
