### ISSUE TITLE
Analyze and decompose docker search effort

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6171]
As a VIC user, I want to be able to search images on docker hub.

Acceptance Criteria:

- [x] A new epic for Docker search
- [x] Tasks for implementing docker search.

**Comment by anchal-agrawal** [comment]
Epic: https://github.com/vmware/vic/issues/6221

**Comment by anchal-agrawal** [comment]
Ping @rajanashok and @sflxn for verification.

**Comment by rajanashok** [comment]
Reviewed the Epic #6221 on docker search.
