### ISSUE TITLE
Analyze and decompose docker history effort

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6174]
As a user of VIC, I want to be able to look at the history of an image.

https://docs.docker.com/engine/reference/commandline/history/

Acceptance Criteria:

- [ ] Create an epic for docker history
- [ ] Add tasks to the epic

**Comment by chengwang86** [comment]
According to https://docs.docker.com/engine/reference/commandline/history/#description, `docker history` supports options such as `--format, --human, --no-trunc, --quiet`.

Currently we only support docker client 1.13, which however does not support `--format`. 

@sflxn Do we need to consider features that are not compatible with 1.13?

**Comment by chengwang86** [comment]
Here is the api definition of `docker (image) history` https://docs.docker.com/engine/api/v1.25/#operation/ImageHistory

**Comment by chengwang86** [comment]
For `image history`, docker 1.13 requires the following information for each layer:
```
ID
Created
CreatedBy
Size
Comment
Tags
```
What we currently have are: 
```
ID
Created
CreatedBy
Comment
```

For `Size`, we need to augment the current ImageMetaData for a layer to incorporate the size of a layer during `image pull` and `image commit`.

For `Tags`, currently this information does not show up in the screen output. I suspect that docker collects this information for future use, but not now. 
In vic, we don't store the `tags` for each layer. I think the slice of `tags` might indicate that fact that multiple images (with different tags) could share the same layer.

**Comment by chengwang86** [comment]
Update:

By adding debug logs to vanilla docker,  it is confirmed that the `tags` indicate the images that share a layer.

**Comment by rajanashok** [comment]
@chengwang86 Verified, Looks good. Please close the issue.
