### ISSUE TITLE
Analyze and decompose docker health check effort

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6177]
As a user of VIC, I should be able to check the health of a VIC container via docker CLI's healthcheck.

Acceptance Criteria:

- [ ] Create a new epic for docker health check
- [ ] Add #5367 to the epic
- [ ] Add #406 to the epic
- [ ] decompose and add further tasks to the epic

---

I've done some analysis in the vic-planning issue, https://github.com/vmware/vic-planning/issues/2.

This tasks also includes heart beat status for vSphere HA, which is not part of the vic-planning issue, but is important.

**Comment by emlin** [comment]
epic: #6223

**Comment by sflxn** [comment]
I reviewed the epic.  It looks good.
