### ISSUE TITLE
Unable to download VIC tar from Ubuntu VM using wget

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#6188]
root@Ubuntu-VIc:/home/vmlib/VIC/VIC-43c30f96-rc3# wget https://10.197.37.132:9443/files/vic_13396.tar.gz --no-check-certificate
--2017-09-01 02:44:59--  https://10.197.37.132:9443/files/vic_13396.tar.gz
Connecting to 10.197.37.132:9443... connected.
WARNING: cannot verify 10.197.37.132's certificate, issued by ‘CN=Self-signed by VMware\\, Inc.,OU=Containers on vSphere,O=VMware\\, Inc.,L=Palo Alto,ST=California,C=US’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 404 Not Found
2017-09-01 02:44:59 ERROR 404: Not Found.

Build:
https://storage.googleapis.com/vic-product-ova-builds/vic-43c30f96-dev.ova
Admiral aade1955c87d
Engine vic_1.2.0-rc1.tar.gz
Harbor harbor-offline-installer-v1.2.0-rc3.tgz

**Comment by anchal-agrawal** [comment]
Issue moved to [vmware/vic-product #719](https://github.com/vmware/vic-product/issues/719) via [**ZenHub**](https://www.zenhub.com/)

**Comment by anchal-agrawal** [comment]
@lgayatri Please open OVA-related issues in the vic-product repo.
