### ISSUE TITLE
Investigation of VMCA/PSC for certificate signing

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#6189]
**User Statement:**
We are currently generating self signed certificate for the various services in the VIC-OVA and the VCHs, we should offer an option to have the certificates signed by VMCA (Certificate Authority Component of PSC).

**Details:**
In many deployments the VMCA is connected to the enterprise CA. Having the VMCA signing the server certificates for the various OVA components and the VCHs will allow secure client to connect without creating security exceptions. In addition to Server Certificates signing, we should explore the possibility of having the VCMA sign the Client Certificates used by the DOCKER cli to provide client authentication.

**Acceptance Criteria:**
A document describing the option/challenges of using the VMCA to sign Server and Client Certificates.

**Comment by lcastellano** [comment]
Investigation has concluded, the VMCA included in the PSC appears not to be a good choice for VIC. This document provides the details:

https://confluence.eng.vmware.com/display/~lcastellano/VMCA+cert+singing+investigation+for+VIC#

**Comment by sgairo** [comment]
@lcastellano is it safe to close this investigation then?
