### ISSUE TITLE
Logging policy enforcement

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#6215]
**User Statement:**
As a developer, I want to be sure that I don't merge any code that doesn't comply with the team's logging policy.

**Details:**
Investigate whether this should be a tool that blocks merges on build or if this could be achieved by proper socialization of the policy and stopped during code review.

**Acceptance Criteria:**
Either a tool as suggested above or proper documentation.

**Comment by hmahmood** [comment]
I don't believe we have a logging "policy". Can you elaborate what such a policy would mean?

**Comment by sgairo** [comment]
I believe @mdubya66 might have some better insight here. At the very least, I'm told there is/should be one

**Comment by mdubya66** [comment]
We need to create one. Some best practice for adding log information and the log level and then enforcing it via automated means if possible since doing so via code reviews allows us to slip.

Examples of some best practices, etc:
https://www.loggly.com/blog/think-differently-about-what-to-log-in-go-best-practices-examined/ 
https://logmatic.io/blog/our-guide-to-a-golang-logs-world/

**Comment by hmahmood** [comment]
I have never had to deal with a logging policy. And I am not sure automating enforcement of any such thing is a good idea. I would be in favor of having a set of guidelines, and best practices. In the end its code, and code reviews are there for a reason; reviewers should be enforcing the guidelines.

**Comment by mdubya66** [comment]
that might be acceptable. the areas i'm most concerned with are tether since logging seems to have a significant impact. maybe unit tests or some kind of perf test can do the same. feel free to close this as folly.

**Comment by hmahmood** [comment]
I think once we have the logging api/framework situation figured out a little, there may be room to write a guidelines doc that lays out how to use it, and when/where we expect people to use it. There may also be guidelines on how to write our APIs, like the fact that a `context.Context` object may be required for all new APIs.
