### ISSUE TITLE
Analyze and decompose VCH storage quota support

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6233]
As a user of VIC, I should be able to specify maximum storage quota for a VCH that will limit space provided for container images and container VMs.

Acceptance Criteria:

- [ ] New epic created for VCH storage quota
- [ ] Break down of both vic-machine and engine tasks
- [ ] Integration testing is part of the epic

---

https://github.com/vmware/vic-planning/issues/43

**Comment by sgairo** [comment]
@zjs what information is missing from this issue?
