### ISSUE TITLE
login to VIC Appliance not possible

### ISSUE THREAD

**Issue by Tschili** [vmware/vic#6235]
Hello,

i have the ova 1.1.1 downloaded from VMware.
i am not able to login to the VIC Appliance.

the Password is set in the ova setting,
but is not working. Username is root or not?

Thanks for help

**Comment by mhagen-vmware** [comment]
@Tschili Sorry you are having problems using the product.
1. Are you trying to ssh?
2. Are you trying to login via the web ui?
3. What is the error message when you try to login, but it fails?
Thanks!

**Comment by Tschili** [comment]
@mhagen-vmware 

i trying ssh. 
Error message is: Access Denied

only for info, is not the vic Maschine, is the ova vm

Thanks

**Comment by mhagen-vmware** [comment]
Username should be root, is that what you tried?  If you cannot ssh into the VM, can you login from the console screen in the vsphere server?

**Comment by Tschili** [comment]
@mhagen-vmware 
both are not working. via ssh and vsphere Server. 
Is look like the Password from the ova Setting is not set

**Comment by mhagen-vmware** [comment]
I tried both on my install and I am able to get in via both means.  On initial SSH login it forces a password reset, did you or someone else maybe change the password on initial SSH login to something else?  Have you tried reinstalling and/or installing a 2nd OVA and still cannot login?

**Comment by Tschili** [comment]
i redeployed the  ova 1.1.1 many times. no change to login.
![1](https://user-images.githubusercontent.com/29960858/30181895-27d5fdc2-9415-11e7-9ae2-9a86ba3a2dc3.PNG)
![2](https://user-images.githubusercontent.com/29960858/30181894-27d5dbc6-9415-11e7-8706-5d18b1ef42c8.PNG)

**Comment by mhagen-vmware** [comment]
@anchal-agrawal @andrewtchin Any ideas guys?

**Comment by mhagen-vmware** [comment]
@Tschili Have you tried with a really simple password, no special characters?

**Comment by Tschili** [comment]
yes, 12345678 or abcdefgh

**Comment by andrewtchin** [comment]
HI @Tschili if you just deployed the 1.1.1 OVA there is a known issue that will be resolved in the 1.2 release.
For now try `2RQrZ83i79N6szpvZNX6` as the password
You can see https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/ts_appliance_password_refused.md for further information
Please be aware that logging into the appliance is only to be used for support purposes under the direction of VMware GSS and any other uses are unsupported

**Comment by Tschili** [comment]
thanks works... you can close the case.

**Comment by andrewtchin** [comment]
Awesome thanks for using VIC!
