### ISSUE TITLE
Failure on docker stop ${container} "Error response from daemon: Conflict error from portlayer... collision of concurrent operations"

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#6236]
**VIC version:**
vic_13602

VCH-0-5249 is still up on "blinky" and responding to docker commands.

**Logs:**
[longevity_6-5_VCH-0-5249.zip](https://github.com/vmware/vic/files/1284020/longevity_6-5_VCH-0-5249.zip)

**Additional details as necessary:**
<img width="916" alt="screen shot 2017-09-07 at 3 38 09 am" src="https://user-images.githubusercontent.com/26554503/30154421-71df5e5e-937f-11e7-9378-5c747ca76dc9.png">

**Comment by mhagen-vmware** [comment]
Container logs:
[container-logs.zip](https://github.com/vmware/vic/files/1284853/container-logs.zip)

**Comment by chengwang86** [comment]
PL
```
Sep  7 2017 02:02:48.228Z INFO  sending kill -TERM 3139841
Sep  7 2017 02:02:48.364Z INFO  waiting 10s for 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f to power off
Sep  7 2017 02:02:58.230Z WARN  timeout (10s) waiting for 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f to power off via SIGTERM

Sep  7 2017 02:02:58.230Z INFO  sending kill -KILL 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f
Sep  7 2017 02:02:58.246Z WARN  sending kill -KILL 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f: ServerFaultCode: The attempted operation cannot be performed in the current state (Powered off).
Sep  7 2017 02:02:58.246Z INFO  waiting 10s for 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f to power off
Sep  7 2017 02:03:08.232Z WARN  timeout (10s) waiting for 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f to power off via SIGKILL


Sep  7 2017 02:03:08.232Z WARN  stopping 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f via hard power off due to: failed to shutdown 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f via kill signals [TERM KILL]



Sep  7 2017 02:03:08.586Z DEBUG vSphere Event elated_clarke-31398417bcc4 on  quimby.eng.vmware.com in stress-datacenter is stopping for eventID(1543527) ignored by the event collector

Sep  7 2017 02:03:56.656Z ERROR op=296.272 (delta:48.424601958s): unexpected fault on task retry: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:"poweredOn", ExistingState:"poweredOff"}
Sep  7 2017 02:03:56.663Z WARN  power off 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f task skipped (state was already poweredOff)

Sep  7 2017 02:03:56.663Z DEBUG Update: refreshing from change version 2017-09-07T02:02:40.290443Z
Sep  7 2017 02:03:56.663Z DEBUG get vm properties [config runtime] of vm VirtualMachine:vm-34300


Sep  7 2017 02:03:56.675Z INFO  Reconfigure: attempting update to 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f with change version "2017-09-07T02:02:40.290443Z" (poweredOn)
Sep  7 2017 02:03:56.675Z WARN  Reconfigure: collision of concurrent operations - expected power state poweredOff, found poweredOn

Sep  7 2017 02:03:56.684Z DEBUG Found 2 subscribers to id: 0 - events.ContainerEvent: Container 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f Stopped

Sep  7 2017 02:03:57.587Z DEBUG vSphere Event Cannot power off elated_clarke-31398417bcc4 on quimby.eng.vmware.com in stress-datacenter: The attempted operation cannot be performed in the current state (Powered off). for eventID(1543529) ignored by the event collector
Sep  7 2017 02:03:57.592Z DEBUG Found 2 subscribers to id: 1543530 - vsphere.VMEvent: elated_clarke-31398417bcc4 on  quimby.eng.vmware.com in stress-datacenter is powered off
```


hostd:
```
2017-09-07T02:02:49.986Z info hostd[89DC890] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/vsan:52b432a675d2bf59-7168e072a499aad9/b9a8b059-d4bb-bac3-9b2a-000af7996070/elated_clarke-31398417bcc4.vmx] State Transition (VM_STATE_ON -> VM_STATE_OFF)

2017-09-07T02:03:09.219Z error hostd[32481B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/vsan:52b432a675d2bf59-7168e072a499aad9/b9a8b059-d4bb-bac3-9b2a-000af7996070/elated_clarke-31398417bcc4.vmx opID=78edd79a-6-f743 user=vpxuser:VSPHERE.LOCAL\Administrator] Invalid transition requested (VM_STATE_OFF -> VM_STATE_POWERING_OFF): Invalid state


2017-09-07T02:03:09.219Z info hostd[32481B70] [Originator@6876 sub=Default opID=78edd79a-6-f743 user=vpxuser:VSPHERE.LOCAL\Administrator] AdapterServer caught exception: vim.fault.InvalidPowerState

2017-09-07T02:03:09.219Z info hostd[32481B70] [Originator@6876 sub=Vimsvc.TaskManager opID=78edd79a-6-f743 user=vpxuser:VSPHERE.LOCAL\Administrator] Task Completed : haTask-10973-vim.VirtualMachine.powerOff-1216712 Status error

2017-09-07T02:03:15.858Z info hostd[32481B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/vsan:52b432a675d2bf59-7168e072a499aad9/b9a8b059-d4bb-bac3-9b2a-000af7996070/elated_clarke-31398417bcc4.vmx] Turning off heartbeat checker

2017-09-07T02:03:57.513Z info hostd[329C1B70] [Originator@6876 sub=VsanSimsStubImpl opID=5fa5f727] Calling vim.host.VsanSystemEx.GetVsanRuntimeInfo
2017-09-07T02:03:57.513Z warning hostd[329C1B70] [Originator@6876 sub=PropertyProvider opID=5fa5f727] It took 60686742 microseconds to get property runtime for vim.HostSystem:ha-host

2017-09-07T02:03:57.582Z info hostd[329C1B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/vsan:52b432a675d2bf59-7168e072a499aad9/b9a8b059-d4bb-bac3-9b2a-000af7996070/elated_clarke-31398417bcc4.vmx opID=78edd79a-6-f751 user=vpxuser:VSPHERE.LOCAL\Administrator] State Transition (VM_STATE_OFF -> VM_STATE_NAMESPACE_CHANGE)

2017-09-07T02:03:57.583Z error hostd[329C1B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/vsan:52b432a675d2bf59-7168e072a499aad9/b9a8b059-d4bb-bac3-9b2a-000af7996070/elated_clarke-31398417bcc4.vmx opID=78edd79a-6-f751 user=vpxuser:VSPHERE.LOCAL\Administrator] Namespace 'ovf' not found.

2017-09-07T02:03:57.583Z info hostd[329C1B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/vsan:52b432a675d2bf59-7168e072a499aad9/b9a8b059-d4bb-bac3-9b2a-000af7996070/elated_clarke-31398417bcc4.vmx opID=78edd79a-6-f751 user=vpxuser:VSPHERE.LOCAL\Administrator] State Transition (VM_STATE_NAMESPACE_CHANGE -> VM_STATE_OFF)
```

**Comment by chengwang86** [comment]
Docker-personality:
```
Sep  7 2017 02:02:48.228Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CommitContainerHandle:575] 358551e5f52b8f3aaad910b6a7d22a1b
Sep  7 2017 02:03:56.675Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CommitContainerHandle:575] [1m8.447162252s] 358551e5f52b8f3aaad910b6a7d22a1b
Sep  7 2017 02:03:56.675Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Stop:755] [1m8.522289892s] 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f
Sep  7 2017 02:03:56.675Z ERROR Will stop trying again. Operation failed with errors.apiError{error:(*errors.errorString)(0xc4214d0260), statusCode:409}
Sep  7 2017 02:03:56.675Z DEBUG [ END ] [github.com/vmware/vic/pkg/retry.DoWithConfig:73] [1m8.52230874s] 
Sep  7 2017 02:03:56.675Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStop:1216] [1m8.522319916s] 31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f
Sep  7 2017 02:03:56.675Z ERROR Handler for POST /v1.23/containers/31398417bcc4d22aca5ceb76b5d0971856710a069b9c17257d94252d3f73925f/stop returned error: Conflict error from portlayer: [PUT /containers/{handle}][409] commitConflict  &{Code:0 Message:Reconfigure: collision of concurrent operations - expected power state poweredOff, found poweredOn}
```

**Comment by chengwang86** [comment]
According to discussion with @emlin and @hmahmood , the fix would be

1.  In `backend/container.go:ContainerStop()`, replace `retry.Do()` with `retry.DoWithConfig()` and set the maxelapsetime to `2min`

2. Improve the error msg for the `conflict error`, so that the user gets the suggestion that `Please retry docker stop`

**Comment by sflxn** [comment]
We should do the retry in the portlayer.  Base.go.  Retry WaitForPowerState().  The stop issue is popping up more.  The VM is stopped but VC hasn't updated it's power state.  We need to provide more time for VC to update it's state before returning back to commit().

**Comment by chengwang86** [comment]
@sflxn The problem for retry is: until when should we stop retrying? We shouldn't be retrying forever. Some numbers, e.g., 1min, 2min, sound like they are out of thin air. In this case, we sent the `SIGTERM` signal at `02:02:48` but received the `VMPOWEREDOFF` event at `02:03:57`. Blindly retrying `waitForPowerState()` for 10 more seconds may not help.

**Comment by sflxn** [comment]
About the error messsage.  I agree we need to fix the error message.  Move the concurrent access error out of commit().  George added this error for an actual hypothesized concurrent access error, but by putting this error in commit(), we receive this error for all cases where the power states do not match up.  All docker stop failure in non-concurrent scenarios now gets this error, and it's wrong.  Put the concurrent error at the source of detection.  For docker stop, we can change the error at the source (in base.go).

**Comment by sflxn** [comment]
@chengwang86 Yes, retrying for 10 more seconds will not help.  We need to put in a limit.  Unfortunately, there is not much we can do.  We rely on VC's state to get synced up to determine powerstate.  A more reliable way would be to retrieve the state ourselves, but I'm not sure we have that option.

**Comment by rogeliosanchez** [comment]
Longevity failed again with the same error on iteration 5 this time.  I started this test around noon today (9/7/17) and failed sometime before 10pm.

[longevity_6-5_VCH-0-7362.zip](https://github.com/vmware/vic/files/1286781/longevity_6-5_VCH-0-7362.zip)

[container-logs_longevity_6-5.zip](https://github.com/vmware/vic/files/1286783/container-logs_longevity_6-5.zip)
![screen shot 2017-09-07 at 11 34 21 pm](https://user-images.githubusercontent.com/26554503/30196402-fe019a5e-9425-11e7-9433-70abef5954f4.png)

**Comment by matthewavery** [comment]
Please see here: https://github.com/vmware/vic/issues/6252

**Comment by matthewavery** [comment]
@rogeliosanchez should we fix this immediately? fixing this is not too difficult tbh, we just need to not return `c.poweroff(ctx)` directly from `exec/base.go:stop()`. Instead we should check for the state info in the error and if there is an error, but it contains the "Powered Off" state. Then we should not return an error from that function.

**Comment by mdubya66** [comment]
@stuclem needs a release note to try the docker operatoin again

**Comment by stuclem** [comment]
Attempt at a release note. The workaround is clear to me but the problem is not:

-----

- <b>'docker stop' fails with error about collision of concurrent operations.[#6236](https://github.com/vmware/vic/issues/6236)</b><br> 'Error response from daemon: Conflict error from portlayer... collision of concurrent operations.'

   Workaround: Retry the Docker operation.

-----

@chengwang86 can you please provide a short description of the problem? Thanks!

**Comment by chengwang86** [comment]
@stuclem 

Short description (feel free to improve):
- This error is due to the fact that the portlayer doesn't obtain the up-to-date power state of the containerVM from the vCenter sever in a slow environment. The containerVM is already powered off while the vCenter server still assumes that it is running (thus the conflict error). Eventually the portlayer will be able to obtain the latest power state of the containerVM after some time. So retry `docker stop` may help resolve this issue.

**Comment by rogeliosanchez** [comment]
Longevity failed again with the same error on iteration 44 this time.

[container-logs_6236.zip](https://github.com/vmware/vic/files/1296566/container-logs_6236.zip)

[longevity_6-5_VCH-0-9381_1.zip](https://github.com/vmware/vic/files/1296586/longevity_6-5_VCH-0-9381_1.zip)

![screen shot 2017-09-12 at 10 54 35 am](https://user-images.githubusercontent.com/26554503/30335980-5e439ee0-97a9-11e7-9c84-57c761a25984.png)

**Comment by stuclem** [comment]
Thanks @chengwang86. Updated the RN to:

----

- <b>`docker stop` fails with error about collision of concurrent operations.[#6236](https://github.com/vmware/vic/issues/6236)</b><br> `Error response from daemon: Conflict error from portlayer... collision of concurrent operations.` This error is due vSphere Integrated Containers Engine not obtaining the up-to-date power state of the container VM from vCenter Sever in a slow environment. The container VM is already powered off but vCenter Server assumes that it is running, which causes the conflict error. vSphere Integrated Containers Engine obtains the latest power state of the container VM after some time. 

   Workaround: Retry the `docker stop` operation after a few minutes.

-----
