### ISSUE TITLE
Activate new drone workers on CI

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6239]
#5984 added new drone worker VMs and corresponding ESXs in OVH using existing kov infra. Using those VMs, activate new drone workers with corresponding ESXs in our CI.

New workers VMs:
```
192.168.31.3  containername=vic-drone-worker-9
192.168.31.4  containername=vic-drone-worker-10
192.168.31.5  containername=vic-drone-worker-11
192.168.31.6  containername=vic-drone-worker-12
192.168.31.7  containername=vic-drone-worker-13
192.168.31.8  containername=vic-drone-worker-14
```

New ESXs:
```
192.168.31.52
192.168.31.54
192.168.31.55
192.168.31.56
192.168.31.57
192.168.31.96
```

**Comment by mdharamadas1** [comment]
@sgairo FYI, added this to current sprint and I think this is like 1-2 pointer.

**Comment by mdharamadas1** [comment]
@mdubya66 when do you think is the right time to make this change?

**Comment by mhagen-vmware** [comment]
lgtm, @mdharamadas1 The right time to make this change -> the first minute after we release 1.2.0. AKA Monday.

**Comment by mdharamadas1** [comment]
@mhagen-vmware sure, will look into ESX license.

**Comment by mdharamadas1** [comment]
@mhagen-vmware I have assigned license to new ESX servers. So closing #5984, please let me know if you see anything else. Thanks!

**Comment by mdharamadas1** [comment]
@mhagen-vmware this is completed, pls verify.

**Comment by mhagen-vmware** [comment]
lgtm
