### ISSUE TITLE
Investigate Docker Tests not passing against VIC

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#624]
Currently we are trying to measure our compatibility with the docker cli and remote api. When we run the docker tests against our apiserver we fail all tests. This should not be the case since we have start, images, and create functioning. 

Investigation and triage are needed to figure out where our responses are not meeting the expectations of the test

**Comment by matthewavery** [comment]
One issue, is that currently the devbox for our common environment is ubuntu 15.04, which is not supported by docker anymore. Docker version 1.9.1-0 is the last supported version of docker for ubuntu 15.04. an update to 16.04 is in progress now.

**Comment by sflxn** [comment]
Matt, can you list all the individual integration tests and list the explanation as to why they're failing?

**Comment by matthewavery** [comment]
I am working on investigating why the tests are failing it has taken me longer than I anticipated since we have also changed the vendor code to 1.11 and I am learning to use `dlv` more effectively.

**Comment by matthewavery** [comment]
Primarily I am investigating why the tests fail with messages like `not supported by vic` calls. The initial calls to create only make `Create` calls which we have implemented. So I am stepping through both the docker test code and the `engineapi` code trying to understand why this is happening.

**Comment by mdubya66** [comment]
Closed. Completed. Docker integration tests running in robot.
