### ISSUE TITLE
Investigate running CI tests against VirtualCenter

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6244]
It looks like running tests on vCenter will be a challenge. An architecture needs to be built such that:

1) Tests can run against 1 or more vCenter endpoint. If tests can run in parallel against an ESX endpoint maybe we can get away with only one vCenter endpoint.
2) Tests should be as isolated as possible so that running two test suites at the same time is deterministic. 
3) vCenter needs to be able to be replaced/restored to a known state with as little manual intervention as possible. No intervention necessary is ideal, but we'll see if that's feasible.

Deliverable:

Write (an) issue(s) with clearly defined tasks to step us towards an implemented solution such that CI can run against vCenter instead of plain ESXi.

**Comment by gigawhitlocks** [comment]
1. Make sure tests run against VC
2. Add tag to allow running against this VC
3. Pull out one  CI host and install VC

**Comment by mdubya66** [comment]
removing the high. the individual stories should have priorities.

**Comment by mhagen-vmware** [comment]
done
