### ISSUE TITLE
Deprecate Drone

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6245]
Drone's architecture imposes a number of restrictions on our capabilities. The general consensus is a preference for Jenkins over Drone, however this should be a relatively small and low-priority change compared to the architectural overhaul seen elsewhere in the encompassing epic.

**Comment by sgairo** [comment]
Moving to Not Ready until we are ready to address this formally and more discussion is had on this issue.

**Comment by mdubya66** [comment]
Per the team, closing this
