### ISSUE TITLE
CIv2 Architecture Spike

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6246]
Investigatory spike to determine what is necessary to have a robust and replicable CI system which can run tests in parallel against VC, can be restored to a known state should an anomaly occur with minimal manual intervention, and takes advantage of the hardware we have available for testing on bare metal. 

The deliverable for this story should include:
1) A plan for how CIv2 will operate end-to-end (it will likely be similar if not identical to what exists, as far as developer usage is concerned)
2) A plan for the aforementioned improvements: how to provision VC so it's ready to receive tests, how to provision workers/scripts to do so, a final choice for end-game CI orchestration software (e.g. Jenkins)
3) A plan for migrating to the new CI with minimal downtime in order to affect developers as little as possible 
4) Security considerations (e.g., no running tests in containers run with privileged mode)
5) A plan for integrating dogfood into the new CI (run tests in VIC containers -> upgrade VCH after clean `master` builds)

**Comment by mhagen-vmware** [comment]
To add to the above desires, in order to get to where we want with VIC 1.3 release:
1.  reliable nightlies
2. VC + VSAN within our CI
3. Implement our existing automation backlog
4. Jenkins server for nightlies and longevity
5. Automate security tests
