### ISSUE TITLE
Monitoring and Statistics from CI

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6248]
quoting @chengwang86 : 

> I think monitoring of CI test stats is also worth improving. @jakedsouza had a database and GUI to collect and display the ci test stats, e.g., which sub-test takes the longest time to run, which test suite fails most frequently. It definitely needs improvement. For example, we need documentation on how to query the database and generate stat graphs; we also need to be able to collect stats over a moving window instead of always starting from the first time we run the ci tests.

This story is to track investigation/design of a dashboard or something similar to allow us to see the health of the CI system itself as well as the health of the tests that have run, see what's failing occasionally/repeatedly at a glance, etc. There are a number of off-the-shelf software solutions for this, I believe. Deliverable will be (an) issue(s) that outline exactly which software we want to use, where it will be deployed, etc.

**Comment by jakedsouza** [comment]
The database is created using the dbbot tool from robotframework 

Database info 
https://github.com/robotframework/DbBot/blob/master/doc/robot_database.md
https://github.com/robotframework/DbBot/blob/master/doc/robot_database.png

**Comment by mdubya66** [comment]
not a requirment for 1.3, removing

**Comment by mhagen-vmware** [comment]
this is already done in via Jake. If you need to know where the vic dashboard is, then ask me or Manjunath or MattW
