### ISSUE TITLE
Checking enable content trust, but not checking prevent vuln images from running results in notary errors

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6259]
```
Error while pulling image manifest: download failed: Unexpected http code: 412 (Precondition Failed), URL: https://10.161.107.186:443/v2/definitely-not-default/ubuntu/manifests/test, Message: The image is not signed in Notary.
```

My understanding is that content trust should just be whitelist and the prevent vuln image should be the notary check? Independent?

**Comment by mhagen-vmware** [comment]
@reasonerjt Is this as expected?

**Comment by stuclem** [comment]
@mhagen-vmware I see the kind/note flag, but isn't this covered by https://github.com/vmware/vic/issues/6258?

**Comment by mhagen-vmware** [comment]
Nope, 6258 is just dealing with enabling whitelisted mode, this issue is about whitelist/notary interaction. We have 2 check boxes. The first should just enable/disable whitelist, the second should just enable/disable vulnerability scanning. Right now the first one enables both.

**Comment by mhagen-vmware** [comment]
Issue moved to [vmware/harbor #3202](https://github.com/vmware/harbor/issues/3202) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mhagen-vmware** [comment]
moved this to harbor as that is the appropriate repo
