### ISSUE TITLE
Do not snapshot memory for VCH endpointVM

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6264]
There is little value in creating a snapshot that includes memory for the endpointVM as we're going to have to purge caches, DHCP addresses, et al on restore anyway as we cannot determine if they are still valid. Preserving the memory only increases the odds of breakage and the size of the snapshot. Use the `memory` parameter to CreateSnapshot_Task to skip the memory.

**Comment by emlin** [comment]
tried to change this today, with some small changes related to VM power status, but the problem is that after reverted snapshot, cannot delete it again.
need more work to figure out what's wrong.

**Comment by hickeng** [comment]
Adding this as a 1.3.1 candidate as it may well be impacting upgrade in busy environments when the VCH is configured with a sizable amount of memory.
