### ISSUE TITLE
vSphere errors in docker cp to running container: failed to add disk 'scsi0:0'

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#6274]
Copying a simple file with docker cp takes a long time and results in task errors when trying to copy a file to a container running in VC. It works fine if the container is stopped. Note that the copy does eventually succeed, but the reconfiguration tasks seem to cause issues.

This is the 1.2 GA.

Below is the more detailed task error when you hover over the message:

![screen shot 2017-09-11 at 11 15 37 am](https://user-images.githubusercontent.com/1699842/30289962-b3e4578a-96e2-11e7-91bb-3f08705dfcb7.png)

**Comment by corrieb** [comment]
[container-logs (11).zip](https://github.com/vmware/vic/files/1293586/container-logs.11.zip)

**Comment by corrieb** [comment]
Steps to reproduce:

```
$ docker create debian sleep 1000
$ touch /tmp/hello
$ docker cp /tmp/hello ba0:/tmp/hello          <--- this works
$ docker start ba0
ba0
$ touch /tmp/hello2
$ docker cp /tmp/hello2 ba0:/tmp/hello2      <--- this takes a long time and gives errors

**Comment by hickeng** [comment]
Trusts one single error iirc, and is from a single reconfigure operation. We don't have access to the disk lock state, so the only non racy approach is to try an attach to the appliance speculatively. This will then block container power on if successful. If not it fails over to live copy.

You're probably configured with debug=something - we might still have verbose logging on live copy - we shouldn't except at debug > 3 but ...

**Comment by corrieb** [comment]
Not quite sure what you're saying here @hickeng. Sounds like you're saying we have to try something speculatively which results in the error? 

FWIW I'm actually seeing two task errors per copy. Also this particular VCH is configured with debug=0.

**Comment by matthewavery** [comment]
@corrieb Would you mind providing some information on the VC setup you used with this deployment as well? mainly 6.0 vs 6.5? and is vSAN involved? I have seen this lately with another issue from @pdaigle and it involved vSAN. I am looking into this as time permits. I am wondering what is happening with this disk backing. From what I have seen there error message you posted above was actually preceded with a failure to hotadd an iscsi device(additional message to follow with that detail). I would like to see if you experienced the same as @pdaigle as I suspect this might involve something with vSAN and the way we interact with vSAN. 

Additional Note: I have noted that in this instance as well as with @pdaigle the disks in question were both part of the ImageStore and thus they were part of the DiskChain. I have not confirmed yet if they are R/W layers or an actual image layer(these normally should be read only but we do not do that yet I think).

**Comment by matthewavery** [comment]
```
types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.disk.hotadd.Failed", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"scsi0:0"}}, Message:"Failed to add disk 'scsi0:0'."}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.disk.hotadd.poweron.failed", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"scsi0:0"}}, Message:"Failed to power on 'scsi0:0'. "}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.disk.noBackEnd", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"/vmfs/volumes/5727fe90-1aaae6f7-7179-005056018fc3/380959dfd4078e357899c34915c47710a0f390c3c69aed399ab8eed788846b57/380959dfd4078e357899c34915c47710a0f390c3c69aed399ab8eed788846b57.vmdk"}}, Message:"Cannot open the disk '/vmfs/volumes/5727fe90-1aaae6f7-7179-005056018fc3/380959dfd4078e357899c34915c47710a0f390c3c69aed399ab8eed788846b57/380959dfd4078e357899c34915c47710a0f390c3c69aed399ab8eed788846b57.vmdk' or one of the snapshot disks it depends on. "}
```
above is the error that preceded the "LookUpAndOpen" style errors from @pdaigle 's issue that @jzt is looking into. I will take a look in the logs you have posted to look for this as well. But this indicates that it may not be the actual disk we are attempting to hotadd as well. I will need more time to investigate before I am able to give any kind of definitive answer.
