### ISSUE TITLE
Seperate drone servers for VIC projects

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6275]
**Details:**
Currently, we have just one drone server shared among four repos (vic, vic-product, harbor, admiral ). Out of these 4 repos, only "vic" needs ESX as part of the CI build for robot tests. Also, for vic repo we would like to set just one concurrent build per drone worker whereas for other repos we can run multiples without issues.

So I would like to suggest to have two drone servers instead, one supporting the repos which need ESX as part of the build and the other supporting repos which do not need ESX. Going by the below table, we can keep existing drone server ( https://ci.vcna.io ) for vic repo alone and create a new drone server to support rest of the 3 repos ( harbor, vic-product, admiral ). Total we have 14 workers and 14 ESX inventory, but if we don't need ESX for the second drone server then we can add some extra workers.

```
		need ESX
	        ----------
vic               yes
vic-product 	  no
harbor		  no
admiral		  no
```

**Acceptance Criteria:**
Two active drone servers, one for vic repo only and the other shared among rest of the 3 repos ( harbor, vic-product, admiral ).

**Comment by mdharamadas1** [comment]
@mhagen-vmware any thoughts on this? I think this will also reduce some burden on existing server.

**Comment by hmahmood** [comment]
Doesn't vic-product need an ESX to build?

**Comment by mdharamadas1** [comment]
@hmahmood Looking at its [`.drone.yml`](https://github.com/vmware/vic-product/blob/master/.drone.yml) doesn't seem like its using ESX.

**Comment by hmahmood** [comment]
@mdharamadas1 It doesn't do much right now, but it will need it in the future: https://github.com/vmware/vic-product/blob/master/.drone.yml#L60

**Comment by mdharamadas1** [comment]
Yes, thats right but it will need vCenter as well which is different from existing setup. Anyways, irrespective of repo, I think we need two drone servers to differentiate between the CI infrastructure needs.

**Comment by mhagen-vmware** [comment]
I am not aware that the server is really under any sort of load...

**Comment by mdharamadas1** [comment]
@mhagen-vmware This is primarily to separate the CI based on infra needs. Currently, it would be challenging to set the CI to run one concurrent build per done worker as it will apply to all repos. With this change, we can have it set to just vmware/vic repo.

**Comment by mdharamadas1** [comment]
Based on discussions with @mhagen-vmware , we won't be doing this (at least for now) and instead we will increase num of drone workers to 14 on current server and set one concurrent build per worker.
