### ISSUE TITLE
Optimize CI Group 1 test suite to one VCH

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6301]
As a VIC developer, I should not have to wait forever for the group 1 CI test suite to run.

Acceptace Criteria:

- [ ] Majority of the CI Group 1 (docker commands) test suite should use one common VCH
- [ ] Individual robot files should still run normally.  It should still install it's own VCH and clean up.
- [ ] Document how the optimization works and best practices for future test writing, including md files in the VIC repo
- [ ] Ensure the logs files are still collected when running in "one VCH" mode

**Comment by vburenin** [comment]
One of the major test improvements would be a targeted longevity API testing. 

As example, image management. We should have a set of tests which could run for a  long time just to create a delta disk images, unpack content, make a diff, download diff.
This testing should be happening using many simultaneously running goroutines so we insure that target VC deployment can sustain stressful I/O and CPU usage. Whatever problem that occurs should be either fixed, if not fixable retried, if not retriable reported to VC team.
I expect that we can see lots of concurrency related issues especially for two different instances of PortLayer talking to the same storage. Our goal is to make it possible to run many instances of Portlayer with no issues - so we can scale horizontally when needed.
