### ISSUE TITLE
Remove created objects when install fails

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#631]
If install via vic-machine fails and vsphere objects have been created they are left in place.  I would expect the installer to clean up after itself in the case of a failure, so remove any of the objects it has created as part of the failed run.

**Comment by emlin** [comment]
@cgtexmex currently, it is by design. User need to explicitly run vic-machine delete to delete anything created by one failed deployment.
If there is anything cannot be removed by vic-machine delete, think that's a bug. But for this, it is by design.
