### ISSUE TITLE
Metabase server is down on CI

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6315]
**Details:**
Metabase server (https://vic-dashboard.vcna.io/) seems down and also see following error in build logs:
`sqlite3.DatabaseError: database disk image is malformed`

**Acceptance Criteria:**
Metabase is up and running
No 'sqlite3.DatabaseError' errors in build log

**Comment by mdharamadas1** [comment]
@mhagen-vmware I have restarted metabase containers and also cleared some old logs. Its up and running, please check and let me know if you see any issue.

**Comment by mhagen-vmware** [comment]
LGTM, thanks!
