### ISSUE TITLE
Generate VCH key after ValidateConfiguration

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#632]
Currently the vic-machine will load or generate a VCH key prior to validating the configuration options supplied.  I believe that validation should happen first and then key load / generation.  Changing the order will prevent an unnecessary write to disk if validation fails and generate cert is specified.

**Comment by hickeng** [comment]
Should address #749 if not already fixed.While this isn't critical the proliferation of generated certs is very visible to the user so this goes to backlog.

**Comment by mdubya66** [comment]
has some user experience impacts. making medium for now as there have been customer concerns around this.
