### ISSUE TITLE
Ensure current CI tests pass against VC

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6328]
Running our integration tests against vCenter to establish which ones already work and which will need further tender love & care in order to run against vC

**Comment by anchal-agrawal** [comment]
Assigned medium priority - please reassess if needed.

**Comment by gigawhitlocks** [comment]
# Test Suites That Passed

-   10-01-VCH-Restart
-   1-01-Docker-Info
-   1-02-Docker-Pull
-   1-03-Docker-Images
-   1-05-Docker-Start
-   1-07-Docker-Stop
-   1-08-Docker-Logs
-   1-09-Docker-Attach
-   11-02-Upgrade-Exec
-   11-03-Upgrade-InsecureRegistry
-   11-04-Upgrade-UpdateInProgress
-   11-05-Configure
-   1-12-Docker-RMI
-   1-14-Docker-Kill
-   1-15-Docker-Network-Create
-   1-16-Docker-Network-LS
-   1-17-Docker-Network-Connect
-   1-18-Docker-Network-RM
-   1-19-Docker-Volume-Create
-   12-01-Delete
-   1-20-Docker-Volume-Inspect
-   1-21-Docker-Volume-LS
-   1-22-Docker-Volume-RM
-   1-26-Docker-Hello-World
-   1-28-Docker-Secret
-   1-29-Docker-Checkpoint
-   13-01-VAC-GuestFullName
-   1-30-Docker-Deploy
-   1-31-Docker-Node
-   1-32-Docker-Plugin
-   1-33-Docker-Service
-   1-34-Docker-Stack
-   1-35-Docker-Swarm
-   1-37-Docker-USER
-   1-38-Docker-Exec
-   1-39-Docker-Stats
-   1-40-Docker-Restart
-   1-42-Docker-Diff
-   1-43-Docker-CP-Offline
-   1-44-Docker-CP-Online
-   2-01-Docker-Archive
-   22-01-nginx
-   22-02-redis
-   22-03-registry
-   22-04-mysql
-   22-05-mongo
-   3-03-Docker-Compose-Basic
-   3-04-Docker-Compose-Fixtures
-   3858
-   4-01-Docker-Integration
-   4367
-   4817
-   5343
-   6-01-Help
-   6-02-Default
-   6-03-Delete
-   6-06-Create-Datastore
-   6-10-List
-   6-11-Debug
-   6-12-Version
-   6-16-Config
-   7-01-Regression
-   8-01-GuestTools
-   9-01-VICAdmin-ShowHTML
-   9-02-VICAdmin-CertAuth
-   9-03-VICAdmin-Log-Failed-Attempts


<a id="orgc6131b8"></a>

# Suites With Failures


<a id="orga08fa44"></a>

## 1-04-Docker-Create

teardown failed ?


<a id="org1bfbc65"></a>

## 1-06-Docker-Run

-   Docker run linked containers


<a id="orgb3a5584"></a>

## 1-08-Docker-Logs

hangs halfway through during one of the `tail` tests. `output.xml` truncated.


<a id="org47a06b7"></a>

## 11-01-Upgrade

-   Upgrade VCH


<a id="org883462c"></a>

## 1-10-Docker-PS

-   Docker ps last container
-   Docker ps last container with size
-   Docker ps Remove container OOB
-   Docker ps two containers


<a id="org7e945c2"></a>

## 1-11-Docker-RM

-   Remove a container deleted out of band


<a id="orgd924180"></a>

## 1-13-Docker-Version

-   Docker1.13 Version Format Client API Version


<a id="org6664f40"></a>

## 1-23-Docker-Inspect

-   Docker inspect image specifying incorrect type


<a id="orgf5d7d7d"></a>

## 1-24-Docker-Link

-   Link and alias


<a id="orgc67fff9"></a>

## 1-25-Docker-Port-Map

-   Container to container traffic via VCH public interface


<a id="orgde335c6"></a>

## 1-27-Docker-Login

-   Docker login and pull from docker.io


<a id="orgb849400"></a>

## 1-36-Docker-Rename

-   Name resolution for a created container after renaming+starting it
-   Name resolution for a running container after renaming+restarting it


<a id="org82c5835"></a>

## 1-41-Docker-Commit

-   Commit nano to image


<a id="org4deaeae"></a>

## 3-01-Docker-Compose-LEMP

-   Compose LEMP Server


<a id="org7ef972b"></a>

## 3-02-Docker-Compose-Voting-App

-   Compose Voting App


<a id="orgcdb7fd1"></a>

## 6-04-Create-Basic

-   Create VCH - Existing VM name


<a id="orge4ec644"></a>

## 6-05-Create-Validation

-   Trailing slash works as expected
-   Custom image datastore
-   Default image datastore
-   Whitelist registries - allowed registry fqdn
-   Whitelist registries - allowed registry wildcard domain
-   Whitelist registries - blocked registry ip address of valid registry fqdn
-   Whitelist registries - blocked registry wildcard domain


<a id="org9b97a1c"></a>

## 6-07-Create-Network

-   Reset VCH doesn't cause unintentionally exposed ports from container network
-   Public network - default
-   Management network - valid
-   Container Firewalls
-   Bridge network - valid
-   Container network - space in network name valid


<a id="org2d92187"></a>

## 6-09-Inspect

-   Inspect VCH Configuration with Container Networks


<a id="org9481083"></a>

## 6-13-TLS

-   Create VCH - defaults custom cert path
-   Create VCH - Invalid keys
-   Create VCH - Reuse keys
-   Create VCH - Server certificate with multiple blocks
-   Create VCH - Server cert with trusted CA
-   Create VCH - Server cert with untrusted CA
-   Create VCH - defaults with &#x2013;no-tls


<a id="org37357d7"></a>

## 6-14-Update-Firewall

-   Enable and disable VIC firewall rule


<a id="org0e7d837"></a>

## 6-15-Syslog

-   Verify VCH remote syslog


<a id="org0507436"></a>

## 6-17-Configure-TLS

-   Configure VCH - Replace certificates with self-signed certificate using &#x2013;no-tlsverify
-   Configure VCH - Server cert with trusted CA
-   Configure VCH - Server cert with untrusted CA
-   Configure VCH - Run Configure Without Cert Options & Ensure Certs Are Unchanged


<a id="org7da1ee4"></a>

## 6-18-Container-Name-Convention

-   Container name convention with id
-   Container name convention with name


<a id="org23c4f08"></a>

## 8-02-OOB-VM-Register

-   Verify VIC Still Works When Different VM Is Registered


<a id="org24d748d"></a>

## Group22 Docker Apps

whole suite failed outright.. it's the only one that did that

**Comment by gigawhitlocks** [comment]
Issues for above incoming.

**Comment by gigawhitlocks** [comment]
https://github.com/vmware/vic/issues/6424
