### ISSUE TITLE
Create tag to allow selectively running tests against VC

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6330]
While we begin to transition to a CI based on vCenter, once we're able to do that, before we switch everything over, we would like to have a tag to selectively perform a test run against vCenter instead of ESXi.

**Comment by anchal-agrawal** [comment]
Assigned medium priority - please reassess if needed.

**Comment by mhagen-vmware** [comment]
not needed, we will be moving to VC entirely when we move to HaaS
