### ISSUE TITLE
Support docker run --restart

### ISSUE THREAD

**Issue by emlin** [vmware/vic#6335]
As a docker user, I'd like to define container restart policy during docker run, so that I could set docker restart policy differently for containers in one VCH.
If restart policy is not disable, unhealthy container detected by health check will be restarted as well.

Here is the document for docker run --restart:
https://docs.docker.com/engine/reference/run/#restart-policies-restart

This feature is mentioned by @hickeng in health check https://github.com/vmware/vic-planning/issues/2, but it's wider scope than normal vSphere HA functions, so assume we'll need to support it in VIC engine.

It is related to health check #6223 

@pdaigle @corrieb @hickeng for how to align this feature with vSphere HA, and priority

**Comment by anchal-agrawal** [comment]
@emlin We have an issue for `docker create/run --restart` support: https://github.com/vmware/vic/issues/4033 - please close either, thanks!

**Comment by emlin** [comment]
thanks @anchal-agrawal for let me know it. 
I'll close this issue as duplicated with #4033, let's add more discussion into that issue.
