### ISSUE TITLE
Longevity 6.5 - docker pull ${busybox} failed with "Tag latest not found in repository library/busybox"

### ISSUE THREAD

**Issue by singhshwetaQE** [vmware/vic#6337]
VIC version:
v1.2.1-rc1

Longevity failed within zero iteration (loop).

Logs:
[VCH-0-1363.zip](https://github.com/vmware/vic/files/1304493/VCH-0-1363.zip)

[container-logs.zip](https://github.com/vmware/vic/files/1304494/container-logs.zip)

Additional details as necessary:
![image](https://user-images.githubusercontent.com/29071304/30454571-642fea88-9962-11e7-903b-882065fb9827.png)

**Comment by anchal-agrawal** [comment]
From persona logs:

```
Sep 14 2017 19:28:08.484Z INFO  image tag not found: Not found: 404, URL: https://registry.hub.docker.com/v2/library/busybox/manifests/latest
```

A 404 for the manifest is a non-retryable error, so this is expected behavior. Not sure why we got a 404 here - looks like a blip since the same `pull busybox` operation succeeded on the four earlier regression test runs.

**Comment by singhshwetaQE** [comment]
Closing this issue, it's not reproducible
