### ISSUE TITLE
Duplicate docker names when running concurrent create

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#6338]
When running `docker create --name..` or `docker run -d --name..` it is relatively easy to create duplicated container names.  This will cause issues for any function that addresses the container by name.

To duplicate the container name the following command was run in quick succession on linux:
`docker run -d --name jojo busybox top &`
Once both tasks have completed `docker ps` returns the following:
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
4f06b332691c        busybox             "top"               About an hour ago   Up About an hour                        jojo
de9fa278729e        busybox             "top"               About an hour ago   Up About an hour                        jojo
```

The user is only able to remove one container by name and the remaining container will need to be removed by ID.

To minimize this possibility we should reserve the name in the persona cache as vSphere is creating the container.  This should follow the same container name reservation utilized in `docker rename`

Environment details:
vSphere 6.0 u3 (nimbus)
ESXi 6.0 u3
vic 1.2.1 deployed to resource pool via `--use-rp`
Reproducibility: easy

**Comment by hickeng** [comment]
Closing as dup of #6261
