### ISSUE TITLE
upgrade --force does not bypass the version check

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6344]
**VIC version:**
1.2.1-rc1 - version to upgrade to

**Deployment details:**
1.2.1-dev-99999 - currently there's a local development build deployed

**Steps to reproduce:**
vic-machine upgrade <args> --force=true

**Actual behavior:**
`--force` does not ignore a higher version number (dev build was done with 999999 to make it obvious it's dev build and to permit upgrade).

**Expected behavior:**
`--force` ignores version requirement as per CLI help

**Comment by anchal-agrawal** [comment]
@hickeng Please add an estimate, thanks!
