### ISSUE TITLE
Incorrect construction of target URL string for tag service

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6347]
The targetURL is being incorrectly constructed with a populated UserInfo structure before the assignment to BasicAuth for the actual request.
Either the credentials should be stored differently or the URL should be sanitized before being passed to NewRequest:
```go
  target := *c.endpoint
  target.User = nil
```

https://github.com/vmware/vic/blob/master/pkg/vsphere/tags/rest_client.go#L160

**Comment by anchal-agrawal** [comment]
Ping @hmahmood.
