### ISSUE TITLE
RegistryCheck should have a much lower timeout and failure modes should be different

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6348]
**Story**
As a user I expect commands such as `docker login`, `docker pull`, and `docker info` (see #6346 ) to respond in a timely fashion

**Details**
We had a scenario where the tag service was completely unresponsive (vcsupport bundle via other means) and caused complete unresponsiveness in the following commands until we hit a timeout:
- login
- pull
- info

The timeout in question appears to be passed in via the docker router code and used without adjustment by us. It's unclear what that value actually is from the logs, but it's on the order of 35-40min looking at the logs. https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/backends.go#L362

The timeout for the RegistryCheck needs to be much, much lower, and to return a useful error, if any, to the user - see the behaviours described in Acceptance.
Currently the timeout triggers #6347 (high severity)

Estimate is for reducing timeout only - follow up issues should be opened for changing behaviours.
Priority is high for timeout adjustment.

**Acceptance**
* a VCH that is not already linked with an admiral should not block or delay `login` or `pull` if vCenter tag service cannot be accessed or if an admiral is slow to respond.
* a VCH that is already linked should continue with it's saved configuration and note in `docker info` that the configuration is stale.
* content trust checkbox should inspect the `docker info` from VCHs in the project to confirm acceptance before confirming that content trust is enabled.

Related: #6346

**Comment by anchal-agrawal** [comment]
@hickeng Please add an estimate, thanks!
