### ISSUE TITLE
Nightly Test 5-3 Enhanced Link Mode timesout

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#6349]
Seen in 9/14 Nightly report 6.5:
[5-3-Enhanced-Linked-Mode.zip](https://github.com/vmware/vic/files/1306958/5-3-Enhanced-Linked-Mode.zip)
`Executing nightly test 5-3-Enhanced-Linked-Mode vSphere 6.5                                                               
Deploying Nimbus Testbed: els-2357
Deploying Nimbus ESXi server: ESX-17581.095736
Deploying Nimbus ESXi server: ESX-95961.097777
Deploying Nimbus ESXi server: ESX-35731.099632
Successfully deployed new ESXi server - 10.160.173.178
Disable TLS on the host
Nimbus ESXi server IP: 10.160.173.178
Successfully deployed new ESXi server - 10.192.195.65
Disable TLS on the host
Nimbus ESXi server IP: 10.192.195.65
Successfully deployed new ESXi server - 10.161.49.170
Disable TLS on the host
Nimbus ESXi server IP: 10.161.49.170
[info] Timeout request received, killing process
[info] build failed (exit code 137)
[DRONE] finished job #1
[DRONE] exit code 137
[DRONE] job #1 failed
[DRONE] build failed
Failed
mv: cannot stat '*.log': No such file or directory
mv: cannot stat '*.zip': No such file or directory`

I will monitor the next set of nightlies in order to better characterize this failure.

**Comment by sgairo** [comment]
**Seen in 9/16 nightly report on vSphere 6.5:**
[5-3-Enhanced-Linked-Mode.zip](https://github.com/vmware/vic/files/1311956/5-3-Enhanced-Linked-Mode.zip)

**and on 9/17 nightly report on vSphere 6.5:**
[5-3-Enhanced-Linked-Mode.zip](https://github.com/vmware/vic/files/1311961/5-3-Enhanced-Linked-Mode.zip)

Though it passed the 9/18 nightly report. All seem to be making it varying lengths before timing out.

**Comment by anchal-agrawal** [comment]
`Timeout request received, killing process` - this would indicate the drone client timeout of one hour.

**Comment by mhagen-vmware** [comment]
fixed with #6530
