### ISSUE TITLE
Milestone: service account for VCH user

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#635]
Create a service account configured with appropriate RBAC limits for use by VCH.
This may well get promoted to an epic.

This can start with the following for ESX, but we need to find the equivilent for vCenter.
http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.host.LocalAccountManager.html

**Comment by gigawhitlocks** [comment]
Going to capture some notes from a Slack conversation with @hickeng here mostly for my own reference, but might be useful for others too later:

> The 6.0 docs center (http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.ssosdk.pg.doc/sso_pg_usage.3.2.html) has some useful information about SSO, however we may be best off asking for guidence from the PSC (platform services controller) team as that's the SSO implementation in 6.0+ iirc.
> 
> For the API details, this is a good place to start: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.pg.doc/PG_Authenticate_Authorize.8.1.html
> 
> The user models for vCenter and ESX are somewhat different. From an implementation perspective, while we can fall back to asking the viadmin to create a service account for a VCH we shouldn't ask them to supply the SSO token,  so that's our implementation priority.

**Comment by hickeng** [comment]
Moving this to onsite as it's not feasible for TP3.

**Comment by mdubya66** [comment]
Moving to backlog.

**Comment by corrieb** [comment]
@hickeng Everything this relates to seems to be either in icebox or untargeted. I know we want to prioritize this kind of stuff, but seems like there's no way this is making onsite.

**Comment by lcastellano** [comment]
Replaced by: https://github.com/vmware/vic/issues/6488
