### ISSUE TITLE
Nightly Test 5-6-1 VSAN simple fails furing delete with timeout

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#6351]
**Seen in 9/14 nightly report on vSphere 6.0:**
[5-6-1-VSAN-Simple.zip](https://github.com/vmware/vic/files/1307154/5-6-1-VSAN-Simple.zip)

**From console output:**
`Installing VCH to test server...
Installer completed successfully: VCH-0-5072...
Gathering logs from the test server VCH-0-5072
Deleting the VCH appliance VCH-0-5072
[info] Timeout request received, killing process
[info] build failed (exit code 137)
[DRONE] finished job #1
[DRONE] exit code 137
[DRONE] job #1 failed
[DRONE] build failed
Failed`

I will monitor future nightlies for this, appears to be external factors.

**Comment by anchal-agrawal** [comment]
`Timeout request received, killing process` - this would indicate the drone client timeout of one hour.

**Comment by mdubya66** [comment]
not seen recently. closing for now as cnr.
