### ISSUE TITLE
Nightly Test 13-2 vMotion Container sees context deadline exceeded

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#6352]
**Seen in 9/14 nightly report on vSphere 6.0:**
[13-2-vMotion-Container.zip](https://github.com/vmware/vic/files/1307161/13-2-vMotion-Container.zip)

**From personality:**
`Sep 14 2017 21:53:27.366Z ERROR Handler for POST /v1.25/containers/ce56ede16bc15b47ee5b011836e900585c3914a9b086363270cb9d8850e1c517/start returned error: Server error from portlayer: unable to wait for process launch status: Post https://10.161.3.156/sdk: context deadline exceeded`

**From portlayer:** 
`Sep 14 2017 21:53:27.312Z ERROR CommitHandler error on handle(685d2363f49d6e1458f5cf4a6ab729e2) for ce56ede16bc15b47ee5b011836e900585c3914a9b086363270cb9d8850e1c517: &errors.errorString{s:"unable to wait for process launch status: Post https://10.161.3.156/sdk: context deadline exceeded"}
Sep 14 2017 21:53:37.923Z DEBUG vSphere Event The host "sc-licf-vsphere.eng.vmware.com:514" has become unreachable.  Remote logging to this host has stopped. for eventID(916) ignored by the event collector`

**Comment by jzt** [comment]
Saw this in 13-1-vMotion-VCH-Appliance as well:

[13-1-vMotion-VCH-Appliance.zip](https://github.com/vmware/vic/files/1372604/13-1-vMotion-VCH-Appliance.zip)

**Comment by mdubya66** [comment]
closing as no repro

**Comment by rajanashok** [comment]
Seen on 13-1-vMotion-VCH-Appliance 6.0 nightly.
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-09-20-32-56.zip?authuser=1

```Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.161.169.114/sdk: context deadline exceeded
Error: failed to start containers: b0c9ca680a84b14c8a74c1da7c098365a44dbcce882d3374edd1b6a4e4769519```

**Comment by hickeng** [comment]
#6379 is the issue open specifically for the failure in the prior comment. See https://github.com/vmware/vic/issues/6379#issuecomment-380177450
