### ISSUE TITLE
Document integration testing procedures

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#6355]
_From @jak-atx on September 12, 2017 17:25_

#For stories, please include the information below:

**User Statement:**

As a developer I need to know how to set up my environment for testing, how to run the tests, and how to write test cases for the H5C plugin. 

**Details:**
Any details of what you want that might clarify for the developer how to approach the implementation.

**Acceptance Criteria:**
Document that shows the procedures for developers to be able to write and run E2E tests on all major browsers/platforms.

_Copied from original issue: jooskim/vic#70_

**Comment by jooskim** [comment]
WIP: https://confluence.eng.vmware.com/display/CPBU/Integration+Testing
