### ISSUE TITLE
Error message points to VIC host URL and not vCenter

### ISSUE THREAD

**Issue by Thynsiia** [vmware/vic#6380]
https://github.com/vmware/vic/blob/ee3c5379a2fb9aa97df4908dc7d647af4eda6b18/ui/installer/VCSA/install.sh#L250

Error message does not reflect that the issue is with the $VIC_UI_HOST_URL and not with the vCenter Information previously provided.

**Comment by anchal-agrawal** [comment]
@jooskim Please take a look - thanks!

**Comment by jooskim** [comment]
Agreed that it could be misleading to users without specifying what the "host" exactly is.  Rephrasing the message to the following would hopefully make more sense:

Error! Could not resolve the host at $VIC_UI_HOST_URL. Please make sure vSphere Integrated Containers Appliance is powered on and reachable from where you are running the script

**Comment by anchal-agrawal** [comment]
Prioritized and estimated.

**Comment by rickespada** [comment]
Is there a workaround for this problem?

I'm following this https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/plugins_vcsa.html 


I see that the config file did not populate correctly. Contains wrong information, or did I do something wrong during the deployment?

# WARNING: This file no longer should be edited by the user manually
# If you see VIC_UI_HOST_URL and/or VIC_UI_HOST_THUMBPRINT empty,
# please file an issue at https://github.com/vmware/vic

# Change the VIC_UI_HOST_URL variable to the URL to the path where
# the plugin zip files are located. For example, if com.vmware.vic-v1.1.0.zip is
# available at https://192.168.1.5/com.vmware.vic-v1.1.0.zip,
# simply type in https://192.168.1.5/
VIC_UI_HOST_URL="https://domain.lab:9443"  **<WRONG it should have been vic.domain.lab**

# Enter the SHA-1 thumbprint of the web server hosting the plugin files.
# Taking an example above, it should be the SHA-1 thumbprint of
# the SSL certificate on https://192.168.1.5
#
VIC_UI_HOST_THUMBPRINT="94:F8:EA:9F:49:A5:01:FF:E1:28:E2:14:9F:13:37:41:4F:BC:36:A8"

Thanks!

**Comment by jooskim** [comment]
@emlin: @rickespada 's comment leads me to think there might be a bug in OVA startup script that updates the `configs` file wherein sub domain "vic" was dropped after it had been processed by`sed`

**Comment by jooskim** [comment]
@rickespada could you send me what `hostnamectl status --static` outputs after SSHing into the OVA appliance as root?

**Comment by jooskim** [comment]
@rickespada it seems that what you're experiencing is a separate issue and I just moved it to https://github.com/vmware/vic/issues/6678

**Comment by jooskim** [comment]
@rickespada one more question here: did you update the hostname for the VIC OVA appliance after you deployed it?

**Comment by jooskim** [comment]
It's also worth adding comments into the `configs` file that if for any reason the hostname of the VIC appliance has changed after the VIC appliance is powered on, the VIC_UI_HOST_URL should be updated manually to reflect the change.
