### ISSUE TITLE
Containers connected to non-bridge networks should issue gratuitous ARP broadcast 

### ISSUE THREAD

**Issue by faillax23** [vmware/vic#6385]
I want to re-open issue #2932
I think in release 1.2 is not resolved, i have the same exact problem described in #2932
I have containers attached to a physical port group, but ARP on the switch is not updated.

Ath the moment I resolved the problem using arping inside docker file of my containers

**Comment by anchal-agrawal** [comment]
@hmahmood #2932 was closed in https://github.com/vmware/vic/pull/3581 - if it's still not resolved we should re-open it.

**Comment by hmahmood** [comment]
@faillax23 did you end up doing this inside your containers: https://github.com/vmware/vic/pull/3581/files#diff-7b08724f327c785442d04b5b0e3185efR5 ?

**Comment by hmahmood** [comment]
@faillax23 did you end up doing this inside your containers: https://github.com/vmware/vic/pull/3581/files#diff-7b08724f327c785442d04b5b0e3185efR5 ?

**Comment by faillax23** [comment]
No i ended up using "arping" command in the dockerfile 
https://github.com/vmware/vic/issues/4715

Inviato da iPhone

**Comment by hickeng** [comment]
I have reopened #2932 - I've confirmed that while `arp_notify` is set it's not updating the gateways in an environment I'm in at the moment.
