### ISSUE TITLE
docker: Error response from daemon: Conflict error from portlayer: device vol1 in use.

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6386]
Test steps:
```
${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} volume create --name=vol1
Should Be Equal As Integers  ${rc}  0
${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} run -d --rm -v vol1:/mydata ${busybox} sh -c "echo 'Initial log message' > /mydata/my.log"
Should Be Equal As Integers  ${rc}  0
${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} run --name log2 -dit -v vol1:/logs logstash -e 'input { file { path => "/logs/my.log" start_position => "beginning" } } output { stdout { } }'
Log  ${output}
Should Be Equal As Integers  ${rc}  0
Wait Until Keyword Succeeds  10x  6s  Check logstash logs  log2  Initial log message

${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} run -d --rm -v vol1:/mydata ${busybox} sh -c "echo 'Another exciting log message' >> /mydata/my.log"
Should Be Equal As Integers  ${rc}  0
Wait Until Keyword Succeeds  10x  6s  Check logstash logs  log2  Another exciting log message
```
It looks like it failed on the last step of echo'ing a 2nd log message into the container.

[container-logs.zip](https://github.com/vmware/vic/files/1311311/container-logs.zip)

**Comment by mhagen-vmware** [comment]
Had to issue a kill command to the docker run process from another terminal in order to get out of that.
```
anon     15198  0.0  0.0   4512   848 pts/2    S+   10:45   0:00 sh -c docker -H 192.168.254.199:2376 --tls run -d --rm -v vol1:/mydata busybox
anon@anon-Latitude-E7450:~/vic$ kill 15198
```

**Comment by hickeng** [comment]
Leaving as high for triage - could be related to #6252, #6340, #6341 or #6342 given the use of `run --rm`.

**Comment by matthewavery** [comment]
Problem container in logs: 3b05ddf85ea33b6162cb276404ffaa46d5232519f51a5e72dc94aa964f019867

##Personality error message:

```
Sep 18 2017 15:43:26.961Z ERROR Handler for POST /v1.21/containers/3b05ddf85ea33b6162cb276404ffaa46d5232519f51a5e72dc94aa964f019867/start returned error: Conflict error from portlayer: device vol1 in use
```

##Portlayer error message:

we see this situation repeatedly. 

Sep 18 2017 15:42:05.263Z ERROR op=310.108 (delta:1.918070956s): unexpected fault on task retry: &types.GenericVmConfigFault{VmConfigFault:types.VmConfigFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage{types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.fileio.lock", Arg:[]types.KeyAnyValue(nil), Message:"Failed to lock the file"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.disk.noBackEnd", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"/vmfs/volumes/573f3c77-f5dc6515-f2ad-000c2938cb96/VCH-0-4457-VOL/volumes/vol1/vol1.vmdk"}}, Message:"Cannot open the disk '/vmfs/volumes/573f3c77-f5dc6515-f2ad-000c2938cb96/VCH-0-4457-VOL/volumes/vol1/vol1.vmdk' or one of the snapshot disks it depends on. "}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.moduletable.powerOnFailed", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:"1", Value:"Disk"}}, Message:"Module Disk power on failed. "}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:"msg.vmx.poweron.failed", Arg:[]types.KeyAnyValue(nil), Message:"Failed to start the virtual machine."}}}}}, Reason:"Failed to lock the file"}

indicating that someone else still holds the lock on a disk that is not the virtual machine that is attempting a power on. 

Looks like the previous owner of the disk was never powered off potentially. 


Setting container 74f6c36c068b4b58bb11494aa7f49c72ef8455cdadf74739ebdeb400a1683c2b state: Starting

Looks like this is the last event change for this container(ALSO KNOWN AS `log2`). This container owns the volume `vol1` currently and was never shutdown. It may indicate that the application command never terminates. 

command used to create and run `log2`: 

`Run And Return Rc And Output  docker %{VCH-PARAMS} run --name log2 -dit -v vol1:/logs logstash -e 'input { file { path => "/logs/my.log" start_position => "beginning" } } output { stdout { } }'`

**Comment by matthewavery** [comment]
Looks like the test needs to be adjusted. this is not expected to succeed until we change the second echo to an `exec` call.
