### ISSUE TITLE
Understand - VIC with Docker Host

### ISSUE THREAD

**Issue by lalegre** [vmware/vic#6404]
Hello to all.

I want to understand how to properly deploy a docker host utilizing vic. I was doing a lot of testings and i cannot deploy a Docker Host as an independent virtual machine and run containers inside of it.

Always i have to deploy a VCH and reference docker to the VCH's URL. Maybe is a misunderstood from me. 

Can please anybody explain briefly how to do it or send me a link to any document.

Thanks in advance

**Comment by malikkal** [comment]
May be the below could help

1. https://github.com/vmware/vic-product/tree/master/dinv
2. https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/deploy_vch_dchphoton.html
3. https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/build_push_images.html

**Comment by corrieb** [comment]
@lalegre We've added support for running nested Docker hosts in VIC by shipping the "dch-photon" image in VIC 1.2. However, to be clear, that is to be used for build tasks and development tasks, not production containers. Putting containers into production in nested Docker hosts requires a significant amount of focus and attention to security. See CIS Docker 1.12 benchmark for reference. 

I will also stress that this is not how VIC is designed to work - just in case there's misunderstanding. It is designed to deploy container workloads as first class citizens directly to vSphere, bypassing the need for a Docker host.

**Comment by lalegre** [comment]
Thanks you very much for the clarification. I will close this post.
