### ISSUE TITLE
1-04-Docker Create fails against vCenter

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6425]
Suite teardown failed -- may have been a one-off issue in my environment. Logs attached.

**Comment by gigawhitlocks** [comment]
[1-04-Docker-Create.tar.gz](https://github.com/vmware/vic/files/1331181/1-04-Docker-Create.tar.gz)

**Comment by sflxn** [comment]
This failure will likely be nullified by PR to optimize the group 1 test to a single VCH.  https://github.com/vmware/vic/pull/6481

**Comment by anchal-agrawal** [comment]
Teardown failure is https://github.com/vmware/vic/issues/6079.

**Comment by anchal-agrawal** [comment]
No other test failures on vCenter - closing.
