### ISSUE TITLE
Integrate jenkins integration test with each pull request

### ISSUE THREAD

**Issue by emlin** [vmware/vic#646]
For we don't have a ESXi test bed for drone, we setup a local test env, but that's not executed for each pull request.
To prevent bad check in, we'd better run all tests before the pull request is merged. So the target for this issue is as following:
- for each pull request, drone will run build for the changes. After build passed, do not upload binaries, instead trigger test in jenkins.
- jenkins job pull binaries from drone test.
- jenkins job executes integration tests based on drone generated binaries.
- jenkins post job execution result back to github pull request.
- then post tested binaries to bintray

**Comment by hickeng** [comment]
Given #752 is in progress and will address this in drone CI I'm closing this.
