### ISSUE TITLE
Portlayer REST infrastructure for attach

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#647]
Add the Swagger/REST code to support attach.  This is different from the code that connects to the tether sessions.

This is setting up the Swagger server, performing the hijack, and attaching the streams.  Other than the Swagger code, most of this will be similar to what the docker api server is doing with the CLI.

**Comment by sflxn** [comment]
I've added Swagger infrastructure for Attach and Resize to the new interaction handler.  I'm now hooking up the hijack code.  In the process of doing this, I realize our Attach handler (via Swagger) will not work.  The current version of Swagger requires us to handle hijacking via an HTTP middleware.  However, we need to pass on the streams to the handlers, but Swagger provides no method of handling this.  Therefore, we're going to have to bypass the standard Swagger handling for this milestone and handle Attach completely in the middleware.

@casualjim has told me the latest version of Swagger adds a few parameters to every handler that may allow us to perform the hijack within the handler itself.  Right now, we just have no bandwidth to migrate to the current version of go-swagger.  We'll just have to implement attach via a middleware now, perform a go-swagger update (post milestone), and then reevaluate.

**Comment by hickeng** [comment]
@sflxn Should this be closed?
