### ISSUE TITLE
vic-machine: set vpxd.SerialPort.PersistNetworkBacking to true

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6473]
**Story**
As a viadmin I expect to be able to reboot vCenter without damaging containerVM function

**Details**
@matthewavery please sanity check me - I seem to have omitted when this occurred from my notes so going off vague recollections from internal storage...
This occurs when rebooting a vCenter and containerVMs are configured with a vSPC connection. After reboot the VM cannot be configured to reconnect to the vSPC on the endpointVM, manually or otherwise. Newly created VMs are fine.
The 'damaged' containerVMs show vSPC as as Unsupported and attempts to reconfigure them with correct settings fail.

The fix is to set the following `config.vpxd.SerialPort.PersistNetworkBacking` advanced vCenter option - this only applies to newly created VMs after that point but functions as desired.

The always awesome @lamw has [a perl script](https://github.com/lamw/vghetto-scripts/blob/master/perl/vCenterAdvSettingMgmt.pl#L60) which has led me to the [service content->setting](http://pubs.vmware.com/vsphere-6-0/index.jsp#com.vmware.wssdk.apiref.doc/vim.ServiceInstanceContent.html) field as the probable target for automatically updating this setting.

**Acceptance**
I've broken this out into two distinct behaviours because I have little knowledge about programmatic setting of VC advanced config - only the notes above:
- [x] vic-machine checks that this value is set appropriately
- [x] vic-machine sets the value if not set (optional)
- [ ] docker attach/exec function is confirmed after vCenter restart in VC restart tests

@malikkal

**Comment by andrewtchin** [comment]
To set this manually:
- https://<vcenter_ip>/mob/?moid=VpxSettings&method=updateValues
- Set value to:
```
<changedValue>
   <key>config.vpxd.SerialPort.PersistNetworkBacking</key>
   <value xsi:type="xsd:string">true</value>
</changedValue>
```
- `Invoke Method`
- Should return void with no errors
