### ISSUE TITLE
Add IP address to VCH bridge interface

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#648]
VCH currently has an interface on the default bridge, but we need to assign it an IP address to enable port forwarding as container VMs would need to route back through the VCH

**Comment by hickeng** [comment]
This should be addressed by #746 but that does not touch on the wider question of whether we will have port forwarding by default, or whether the external network mapping is sufficient.

**Comment by hickeng** [comment]
This is addressed by #746 - #938 addresses the other questions
