### ISSUE TITLE
Boot vic 1.2 not possible

### ISSUE THREAD

**Issue by Tschili** [vmware/vic#6483]
Hello,

i have problem to boot the vic after deploying

![boot](https://user-images.githubusercontent.com/29960858/31075268-fc648ece-a774-11e7-946f-82ac1f9fdcdf.PNG)

We have ESX "VMware ESXi, 6.5.0, 5969303"

Thanks for help

**Comment by anchal-agrawal** [comment]
Hi @Tschili, thanks for reporting!

Could you share details about how your deployment? Did you install a Virtual Container Host (VCH) (if so, please share the `vic-machine create` command) or deploy the VIC Appliance OVA? Thanks.

**Comment by Tschili** [comment]
Hello,

I deployed the OVA from the vmware download page. This picture is direct after the deployment.

Thanks

**Comment by anchal-agrawal** [comment]
Thanks @Tschili - did you deploy to a vCenter instance? We don't support VIC Appliance OVA deployments directly to an ESX.

We've documented the deployment steps at https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/deploy_vic_appliance.html.

**Comment by Tschili** [comment]
Yes, to a vcenter, with 3 esx Hosts. The version of the hosts are in the first message.

**Comment by anchal-agrawal** [comment]
With regards to the screenshot above, did that appear after following all the steps in the OVA deployment wizard and powering on the OVA VM? Could you share more details about the settings used while deploying the OVA? Thanks!

**Comment by Tschili** [comment]
Hello,
I set only the password and leave the all other as default. I also unpacked the ova and deployed with the 2 vdmk and 1 ova file.

**Comment by anchal-agrawal** [comment]
@Tschili The OVA file from downloaded from www.vmware.com/go/download-vic, `vic-v1.2.1-4104e5f9.ova`, can be deployed directly (without unpacking) with the `Deploy OVF Template` option in the vCenter client.

**Comment by Tschili** [comment]
Hello, i also tried it with the new OVA. 
I get the same error like "The checksum (s) of the specified manifest file does not match / match the contents of the file (s)", when i unpack the OVA i can install but the same screen as in the first message. It's look like the first disk of the OVA or GRUB is currupt. Thanks

**Comment by anchal-agrawal** [comment]
I don't follow "unpacking" the downloaded OVA artifact - please help clarify this. As mentioned in my previous comment, the downloaded file can be deployed directly without any extra steps. Thanks!

**Comment by Tschili** [comment]
Hello, when I deploy direct I get the error “The checksum of the specified manifest are not correct”

**Comment by anchal-agrawal** [comment]
I see, thanks. Where are you seeing this error? Please provide a screenshot or logs and the file name of the OVA artifact as downloaded.

**Comment by renmaosheng** [comment]
please try to use vic 1.5. see if you still has the problem.
