### ISSUE TITLE
Nightly 5-6-2-VSAN-Complex fails to delete VCH

### ISSUE THREAD

**Issue by jzt** [vmware/vic#6485]
The nightly 5-6-2-VSAN-Complex tries 6x5s times for the `vic-machine-delete` command to finish, for a total of 30 seconds, resulting in:
```
'standalone-d7d4d2cef-esx.2-vm.0
d291cf59-67dc-39f4-0116-02001f21322d
f291cf59-626b-062c-fe3f-02001f835bde
a292cf59-30bd-a524-0c2d-02001f21322d
standalone-d7d4d2cef-esx.0-vm.0
VCH-0-9571
standalone-d7d4d2cef-esx.1-vm.0
e291cf59-4d2e-6ad3-67a2-02001f4507a4' contains 'VCH-0-9571'
```
Perhaps we should make that wait longer in cases of heavy load?

**Comment by jzt** [comment]
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1350171/5-6-2-VSAN-Complex.zip)

**Comment by andrewtchin** [comment]
Reopen if it happens again
