### ISSUE TITLE
vic-machine validation: invalid resource pool path is not reported correctly

### ISSUE THREAD

**Issue by emlin** [vmware/vic#649]
for example, specify -compute-resource with "/ha-datacenter/host/localhost.eng.vmware.com", installation will succeed, but port-layer-server is not started for failed to find this resource pool.

the correct resource pool should be like "/ha-datacenter/host/localhost.eng.vmware.com/Resources"

**Comment by gigawhitlocks** [comment]
Can reproduce -- working to find the root cause
