### ISSUE TITLE
Modify CI to run with restricted ops-user ( --ops-user)

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#6502]
**User Statement:**
The VCH should be configured to use a ops-user ( --ops-user ) in our CI enviroment. Currently the CI runs with vCenter administrator credentials.

**Details:**
The CI should be modified to use the ops-user ( --ops-user ) instead of the vCenter administrator credentials. 

**Acceptance Criteria:**
CI runs creates VCH and runs test using the ops-user.

**Comment by anchal-agrawal** [comment]
@lcastellano Please add a priority and team label(s), thanks.

**Comment by lcastellano** [comment]
Manually closing this. PR references: #6709, #6774
