### ISSUE TITLE
Implementation of create/validate/repair of vSphere roles for ops-user

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#6504]
**User Statement:**
When the VCH is created the VIC should check that the appropriate roles for the ops-user are in place in vCenter. If not it should either create or repair the roles.
**Details:**
This issue should cover:
- APIs to create/validate/repair vSphere roles for ops-user
- Unit test
- Manual integration test against an instance of vCenter
**Acceptance Criteria:**
Code and tests implemented.

**Comment by anchal-agrawal** [comment]
@lcastellano Please add a priority and team label(s), thanks.
