### ISSUE TITLE
VCH-Update: implementation of create/validate/repair of vSphere Permissions for ops-user and VCH resources

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#6505]
**User Statement:**
When a VCH is updated the ops-user should have Permissions on the various vSphere resources used by the VCH.
**Details:**
During VCH update the set of vSphere Permissions should be added for the appropriate Roles of the ops-user should be updated as well. The Permissions are applied to different vSphere managed resources that the VCH need to access and modify. The issue should track:

- Implementation of the code that updates the right Permission given the set of resources and the ops-user username,
- Unit tests,
- Manual basic integration testing with vCenter

**Acceptance Criteria:**
Code and tests should be implemented.

**Comment by anchal-agrawal** [comment]
@lcastellano Please add a priority and team label(s), thanks.
