### ISSUE TITLE
Refine patterns used for vic-machine service end-to-end tests

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6508]
The vic-machine service product is establishing new patterns for organization of end-to-end test code. Towards the end of the project, we should revisit the results and make sure it's what we want to merge to `master`.

See https://github.com/vmware/vic/pull/6475#pullrequestreview-66940252 for more context.

**Comment by anchal-agrawal** [comment]
@zjs Please add an estimate and priority, thanks.

**Comment by zjs** [comment]
Fixed by #6666
