### ISSUE TITLE
Assigning container network IP via DHCP causes /etc/hosts customisation to revert

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#6515]
VIC Engine - vic_1.2.1-rc2, vic_1.2.1

User statement: As a customer of VIC, I would like to set custom entries in /etc/hosts due to application expectations.

Details: Current versions do not implement run --add-host. However, this is tweaked using a workaround; refer https://github.com/vmware/vic/issues/4195#issuecomment-285645969. You may also refer #5833 .

Issue Description: This worked fine so long as the VCH was built with --cnr <range>. However, switching to DHCP fails this immediately. /etc/hosts are reverted to original within few seconds of editing.

Easily reproducible. Refer screenshot.

![image](https://user-images.githubusercontent.com/16984768/31210452-ed0dbb24-a9c4-11e7-8016-ecc1ee976cef.png)

@hickeng

**Comment by hickeng** [comment]
Concerns around IP addressing and resolution:
1. Update /etc/hosts writer to blend tether entries with existing entries
2. Add triggers to detect:
  a. events that invalidate DHCP leases, e.g. link down, link up
  b. explicitly assignment of address to an interface
  c. hostname being set - ideally this would be added as an alias for loopback
3. IP aliases
  a. support publishing multiple IP addresses per interface
  b. support setting multiple IP addresses per interface

**Comment by hickeng** [comment]
Should also look at binding `hostname` against non-loopback IP by preference.

**Comment by hickeng** [comment]
Having looked into binding the hostname to a non-local address it's problematic in the scenario of multiple non-local networks: https://github.com/vmware/vic/issues/6271#issuecomment-335985412
We *should* bind it to both IPv4 and IPv6 loopback however.

**Comment by stuclem** [comment]
Opened https://github.com/vmware/vic-product/issues/987 for the doc update, so removing `kind/user-doc` from this one.
