### ISSUE TITLE
Display VM-ID as part of the vic-machine create output.

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#6517]
VIC Engine - Any

User statement: As a customer of VIC, I would like to see the vm-id as part of the vic-machine-{OS} output, once the "INFO  Installer completed successfully" message.

Details: This would help avoid a rerun of the vic-machine-{OS} ls to just note down the vm-id for debug or any other vic-machine-{OS} operations.

Thanks.

**Comment by hickeng** [comment]
I'd suggest that we also return the following in inspect (which is also used to present data at the end of `vic-machine create`):
* IP addresses for the other interfaces

**Comment by mdubya66** [comment]
@zjs for create api purposes

**Comment by zjs** [comment]
I think this is worth a release note, as it was a customer-requested enhancement.
