### ISSUE TITLE
Install VC into a pilot cluster of the new servers

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6520]
Need to successfully install and document the process of getting a VC installed on the new servers.  Targeting a cluster of 4 ESXi with VC installed on one of them and VSAN on them.

**Comment by mhagen-vmware** [comment]
@mdharamadas1 Please review:
https://confluence.eng.vmware.com/display/CNA/Add+new+VC+worker

New server can be tested here:
192.168.31.43

**Comment by mdharamadas1** [comment]
@mhagen-vmware I can't access `192.168.31.43`. Could you pls check?

**Comment by mhagen-vmware** [comment]
definitely still available.. using it now.  Are you on the VPN?

**Comment by mdharamadas1** [comment]
Ah, VPN! Sorry, I can access it.

**Comment by mdharamadas1** [comment]
@mhagen-vmware lgtm!
