### ISSUE TITLE
Setup Jenkins server for scheduling our nightlies and longevity

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6521]
Need to use jenkins as these are jobs that need to be schedule based on time not commits.

**Comment by mhagen-vmware** [comment]
Still needs some tweaks, but we have been using for nightly and longevity for the last couple of weeks.

@mdharamadas1 please verify and close this if you agree:
http://10.17.109.200:8080

**Comment by mdharamadas1** [comment]
@mhagen-vmware LGTM but should we at least have some minimal user control to avoid mostly accidental changes? I see I have permissions like delete projects / agents.

**Comment by mhagen-vmware** [comment]
yea, we have several things that we need to do still, but this should do for now... thanks!

**Comment by mhagen-vmware** [comment]
Current plan, security through nobody knowing we have the server ;)
