### ISSUE TITLE
Setting an absolute cVM limit per VCH

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#6529]
VIC Engine - Any

User statement: As a customer of VIC, I would like set an absolute limit of cVMs per VCH, regardless of the resource pool limit set. This could be a parameter to vic-machine-{os} create.

Details: Resource limits are only applicable while cVMs are running. However a failed entrypoint and a poorly written plugin / script could keep retrying the create / run operation that would result in large number of stale (powered off) cVMs. 

Thanks.

Edit by @anchal-agrawal:

An additional acceptance criteria for this issue is to write test plans for CI and implement them. The tests can borrow logic from the ROBO tests for the container VM limit feature.

**Comment by hickeng** [comment]
Adding this to the ROBO epic as well given that environment has a license limit on the number of VMs - we should endeavour to provide limiters to ensure that we don't exhaust _any_ vSphere limits completely.

**Comment by malikkal** [comment]
Could we have this prioritized, please? production incident today. Thanks

@hickeng

**Comment by malikkal** [comment]
Yes, please, as the overall storage consumption could be low; however, vCenter inventory gets affected by stale container entries. Thanks.
