### ISSUE TITLE
VCH creation API request hangs

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6550]
The VCH creation API seems to hang, after creating the VCH, in at least some scenarios.

cc @cristianfalcone

**Comment by zjs** [comment]
@cristianfalcone: After my recent batch of PRs, I'm no longer seeing POST requests hang in my environment. Can you let me know if you see this again after syncing past commit 4cc1a61c5c8c8b6780e6629b660932d2a76c26fe?

**Comment by cristianfalcone** [comment]
@zjs I tried it from browser and it is no longer hanging. Also, I used a custom server cert and key in the payload, and it no longer panics either.
