### ISSUE TITLE
Add basic validation of API availability to first step of VCH creation wizard

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6553]
This will be especially important if the customer is using self-signed certificates that they need to manually accept.

The version endpoint (`/container/version`) can be queried without authentication and should be useful for this.

cc @jak-atx, @ali5ter, @hickeng

**Comment by andrewtchin** [comment]
show error if version endpoint value is invalid or nonexistent
handle self signed cert

**Comment by zjs** [comment]
@jak-atx: I see that this is marked closed. Is there a commit I could look at that adds this functionality?
