### ISSUE TITLE
Automate OVA artifacts versioning

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6555]
**User Statement:**
As a developer, I would like to see that proper version standards are applied to the published OVA artifacts from CI builds. 
This also includes consumption of correct versions of other artifacts from vic, admiral and harbor.

**Details:**
Includes only dev builds.

**Acceptance Criteria:**
OVA artifact versions are as expected.

**Comment by andrewtchin** [comment]
includes naming artifacts the correct version when published

**Comment by mdharamadas1** [comment]
I believe we already have expected versioning.
