### ISSUE TITLE
vic-machine-server should generate request logs

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#6571]
**User Statement:**

As a user I want to specify a log file for vic-machine-server. 

**Details:**

**Acceptance Criteria:**
- [ ] vic-machine-server accepts a log file argument
- [x] able to configure log rotation or set a max log size
- [x] update Dockerfile as needed (for volume to store logs)

**Comment by andrewtchin** [comment]
start with webserver style logs

**Comment by zjs** [comment]
https://elmiko.github.io/2016/07/11/go-swagger-logging.html

**Comment by morris-jason** [comment]
>update Dockerfile as needed (for volume to store logs)

This is not needed. Instead, vmware/vic-product#944 will use a `docker run -v` flag.
