### ISSUE TITLE
Print drone worker name in CI builds

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6574]
**User Statement:**

As a developer, I should be able to see drone worker name in the logs on which the CI build executed.

**Details:**
This is already done in #6108, separating out so we can merge this, which is very useful in debugging CI build issues.

**Acceptance Criteria:**
Drone worker / agent name on which build ran is printed in the logs.

**Comment by mdharamadas1** [comment]
@andrewtchin FYI, I'm adding this in current sprint instead of #6108, which is blocked until we upgrade drone itself.

**Comment by mdharamadas1** [comment]
@mhagen-vmware could you pls verify this?

**Comment by mhagen-vmware** [comment]
lgtm, you could have just done fixes #6574 in your PR.

**Comment by mdharamadas1** [comment]
@mhagen-vmware noted, I'm still getting used to GitHub.
