### ISSUE TITLE
Nightly 5-3 Enhanced Linked Mode Failure

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6576]
Seen 10/17/17, looks like an incorrect argument was passed to Nimbus
`2017-10-16 05:03:35 -0700: Exception spawning testbed: RuntimeError: Couldn't find official build of vcfvt testware on vsphere65u1`

![screenshot-2017-10-18 manual-test-cases test log](https://user-images.githubusercontent.com/3743903/31732765-41a604ea-b3ff-11e7-9739-eed9f5920e94.png)

**Comment by gigawhitlocks** [comment]
https://storage.cloud.google.com/vic-ci-logs/functional_logs_10_16_06_09_vic_14037.tar.gz.zip?authuser=1

**Comment by matthewavery** [comment]
Fixed with @mhagen-vmware retry logic around nimbus setup
