### ISSUE TITLE
Nightly 13-2 vMotion Container

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6579]
![screen shot 2017-10-18 at 12 58 46 pm](https://user-images.githubusercontent.com/3743903/31734398-324f64be-b404-11e7-80da-f430f46d4094.png)

Test setup failed. No vic-machine.log available in log bundle.

**Comment by gigawhitlocks** [comment]
This failure can be seen in the 6.5 section of the log bundle https://storage.cloud.google.com/vic-ci-logs/functional_logs_10_16_06_09_vic_14037.tar.gz.zip?authuser=1

**Comment by sgairo** [comment]
Will bring this up with nimbus/infrastrucuture

**Comment by sgairo** [comment]
Submitted bugzilla issue
