### ISSUE TITLE
Nightlies 5-4 High Availability Update Output Check

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6580]
Related to a change in code in PR #6511 
Looks like the software is behaving as expected, but the test needs to be updated. Should be real simple.

![screen shot 2017-10-18 at 1 00 56 pm](https://user-images.githubusercontent.com/3743903/31734505-8d0a4fea-b404-11e7-91d9-7b72177471e3.png)

**Comment by sflxn** [comment]
This is related to #6263.

**Comment by mhagen-vmware** [comment]
should have closed with #6786
