### ISSUE TITLE
In Robot files, tag `secret` not secret

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6583]
Seen here, the `Keyword` `Run Secret SSHPass Command` has tag `secret` but the password is included in test logs:

![screen shot 2017-10-18 at 1 52 46 pm](https://user-images.githubusercontent.com/3743903/31737710-fb4a3ab6-b40d-11e7-9ac7-d5df027bea1d.png)

**Comment by mhagen-vmware** [comment]
You have to actually run it as we do in the CI in order to remove the secrets:
```pybot *--removekeywords TAG:secret* --exclude skip tests/test-cases```

**Comment by mhagen-vmware** [comment]
I assume you intend the scope of this bug to include nightlies?  #6591

**Comment by gigawhitlocks** [comment]
Yes, sorry @mhagen-vmware I wasn't aware it was related to how it was run. This was indeed seen in nightlies.
