### ISSUE TITLE
VIC 1.2.1 vic-machine-<OS> create --help :: doesn't has  ops-user help string

### ISSUE THREAD

**Issue by kumuduh** [vmware/vic#6588]
**VIC version:**

x.y.z / master / commit ID
1.2.1
**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

**Steps to reproduce:**
help from VIC machine create 
root@Docker_client [ ~/vic121/vic ]# ./vic-machine-linux create --help |grep -i ops-user

**Actual behavior:**
It should be similar to vic machine configure 

root@Docker_client [ ~/vic121/vic ]# ./vic-machine-linux configure --help |grep -i ops-user
   **--ops-user** value                                 The user with which the VCH operates after creation. Defaults to the credential supplied with target (default:

**Expected behavior:**

**Logs:**
root@Docker_client [ ~/vic121/vic ]# ./vic-machine-linux create --help |grep -i ops-user
root@Docker_client [ ~/vic121/vic ]# ./vic-machine-linux configure --help |grep -i ops-user
   --ops-user value                                 The user with which the VCH operates after creation. Defaults to the credential supplied with target (default: <nil>)

**Comment by anchal-agrawal** [comment]
Hi @kumuduh - you can use the `-x` or `--extended-help` flag in `vic-machine-linux create` to view the help doc for the `--ops-user` option:

```
$ bin/vic-machine-linux create --extended-help | grep -i ops-user  
   --ops-user value                                 The user with which the VCH operates after creation. Defaults to the credential supplied with target (default: <nil>)

$ bin/vic-machine-linux create -x | grep -i ops-user
   --ops-user value                                 The user with which the VCH operates after creation. Defaults to the credential supplied with target (default: <nil>)
```

The reason why `--ops-user` doesn't show up in the main help option (`--help`) is that `vic-machine create` has lots of options and `--help` shows the major ones (including `-x` to view the extended help section).
