### ISSUE TITLE
Implement IP lookup for VCH create endpoint

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#6595]
**Details:**
We need to implement the findings from this issue https://github.com/vmware/vic/issues/6551 regarding the H5C VCH wizard being able find the correct IP of vic-machine-service.

**Acceptance Criteria:**
Demonstrate ability to deploy OVA with vic-machine-service and have the H5C vch wizard be able to find the correct API endpoint and get a successful response.

**Comment by andrewtchin** [comment]
need to find an API that can view a VM's tags https://github.com/vmware/vic-product/blob/master/installer/tagvm/tagvm.go
alternatively, find some other way the appliance can identify itself that is visible to the H5C

**Comment by jooskim** [comment]
After a discussion with @andrewtchin, it seems that we can use the `value` property as another way of tagging of VIC OVA appliance. This functionality is tracked in https://github.com/vmware/vic-product/issues/1018, and once available, I could modify the vic-service Java project to discover VIC OVA VM based on that information, and expose the IP address of it through a REST endpoint so the Angular app can consume it.

**Comment by jooskim** [comment]
Issue moved to [vmware/vic-ui #26](https://github.com/vmware/vic-ui/issues/26) via [**ZenHub**](https://www.zenhub.com/)
