### ISSUE TITLE
Enable logging to local file for vic-machine API handlers

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6599]
**User Statement:**

As a user, I would like to have the vic-machine API handlers log to a local file.

**Details:**

**Acceptance Criteria:**

- [ ] Define a logic that sets up a logger that logs to a local file when every API handler fires
- [ ] Make all API handlers log to the local file
- [ ] Ensure that the create API handler still logs to datastore folder

**Comment by andrewtchin** [comment]
Close as duplicate of #6571
