### ISSUE TITLE
Write docker registry validation for login and pull against Artifactory

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6602]
As a VIC user, I expect VIC to work against Artifactory's docker registry.

Acceptance Criteria:
- [ ]  Nightly validation tests to verify Artifactory's compatibility

---
Issue was resolved in #5338.  We need validation scripts.

**Comment by sflxn** [comment]
This require us to set up an Artifactory instance with their docker registry.  VMware has an internal Artifactory service so as soon as we can get an account on it, we can write these tests.  Unfortunately, Artifactory does not offer a free version of their docker registry so we need to use the VMware's internal service.  I've submitted an internal bugzilla issue, requesting this.  Bugzilla issue 1983719.

**Comment by mhagen-vmware** [comment]
Inherit priority and release from parent Epic. This issue should no longer be blocked, it looks like the VMware internal Artifactory is setup and available to us now based on the thread in the bugzilla ticket, just need to write a test now.

**Comment by mdubya66** [comment]
Blocked by #6738?

**Comment by mdubya66** [comment]
Priority raised due to key requirement for a customer
