### ISSUE TITLE
[CI] gandalf needs to be running in a machine controlled by CI env.

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#6625]
Right now it is running on a personal server @ GCE...

**Comment by caglar10ur** [comment]
Running it requires slack and github token

```SLACK_TOKEN="..." GITHUB_TOKEN="..." ./gandalf```

@anchal-agrawal ping me so that I can give you those secrets

**Comment by mdharamadas1** [comment]
gandalf is migrated to CI server (`192.168.31.246`, same one which runs drone server).
