### ISSUE TITLE
VCH proxy needs bypass option

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#6629]
@philosifer commented on [Thu Sep 07 2017](https://github.com/vmware/vic-product/issues/746)

**VIC Product version:**

vic-v1.1.1.56a309fb.ova

**Deployment details:**

VSCA 6.5 u1 and ESXi 6.5u1

**Steps to reproduce:**

vic-machine create http and https proxy options need the ability to specify bypass for local sub-networks to allow for situations where the proxy can't proxy back to internal servers.

**Actual behavior:**

After enabling proxy options on a vic-machine create it is not possible to login to the VCH admin interface on port 2378. This applies to both vcenter login credentials and local esxi root credentials. Recreating the VCH without the proxy options the admin login works fine.

**Expected behavior:**

The admin pages state "The proxy is used only when pulling images, and not for any other purpose." so configuring a proxy should not interfere in other functions such as the admin login process.

In addition, though i haven't managed to get this far in my setup yet, configuring a proxy for internet access to images shouldn't automatically result in requests to an internal registry being proxied. For example the proxy on my corporate network is not aware of my lab subnet and hence it can't redirect requests back to me.

**Comment by zjs** [comment]
Is this the same as #5862?

**Comment by renmaosheng** [comment]
it is the same as #5862 which is confirmed in #5862
