### ISSUE TITLE
Milestone: vic-machine: extraconfig refactoring

### ISSUE THREAD

**Issue by emlin** [vmware/vic#664]
This refactor is to leverage common libraries, and cleanup functions following self-provisioning process. Currently it is still function call between different go methods, but in the future, while vic-machine really works in self-provisioning model, those functions will be separated to different modules.

The detailed requirement
- Add command line parameters to internal data structure. (Already there, need to change only when the command line parameter is changed)
- Validation function should connect to ESXi or vCenter, to validate internal data structure. After validation, translate internal data structure to VirtualContainerHostConfigSpec.
- Dispatcher package should be refactored to use pkg/vsphere/spec package, to create VM spec.
- Set guestinfo using pkg/vsphere/extraconfig/ package to serialize configuration data.
- Use mob-id instead of object name in configuration, e.g. use network-101, instead of network name.
- Modify launcher.sh if necessary.

Stretch goal for the refactor is to use tether configuration format to configure VCH services. This function rely on VCH services refactor, so can be postponed if cannot be finished in one milestone.

**Comment by hickeng** [comment]
Rather than create a separate epic for the milestone I've used this one and just altered the labels.

> - Validation function should connect to ESXi or vCenter, to validate internal data structure. After validation, translate internal data structure to VirtualContainerHostConfigSpec.

I suggest doing the validation _as_ you translate from pure symbolic strings to the internal structure - you will need end up retrieving the moref or uuids for the various config elements as part of the validation.

**Comment by mdubya66** [comment]
All the issues are closed. Moving this to done.
