### ISSUE TITLE
Traffic from containers to hosts in VCH subnet is sent to default gateway

### ISSUE THREAD

**Issue by mattstocum** [vmware/vic#6647]
**Description:**
All traffic from containers to external hosts is sent out from the VCH via the default gateway of the public interface, regardless of destination IP. Traffic destined to a host in the same subnet as the public interface of the VCH should be sent directly to the destination host, bypassing the gateway.

**VIC version:**
1.2.0 / master

**Deployment details:**
What was the vic-machine create command used to deploy the VCH?

```vic-machine-linux create --name vch --image-store VMFS --compute-resource R610/Resources/VCH --public-network admin --public-network-ip XXX.YYY.235.1/22 --public-network-gateway XXX.YYY.235.254 --dns-server XXX.YYY.24.20 --dns-server XXX.YYY.24.10```

**Steps to reproduce:**
1. Create VCH as described above
2. Run ```docker run --rm busybox traceroute XXX.YYY.235.2``` where XXX.YYY.235.2 is an IP address in the same subnet as the VCH public interface

**Actual behavior:**
```
traceroute to XXX.YYY.235.2 (XXX.YYY.235.2), 30 hops max, 46 byte packets
 1  172.16.0.1 (172.16.0.1)  1.675 ms  1.249 ms  0.708 ms
 2  XXX.YYY.235.254 (XXX.YYY.235.254)  0.690 ms  1.053 ms  0.739 ms
 3  XXX.YYY.235.2 (XXX.YYY.235.2)  0.843 ms  1.104 ms  0.740 ms
```

**Expected behavior:**
```
traceroute to XXX.YYY.235.2 (XXX.YYY.235.2), 30 hops max, 46 byte packets
 1  172.16.0.1 (172.16.0.1)  1.215 ms  0.126 ms  32.674 ms
 2  XXX.YYY.235.2 (XXX.YYY.235.2)  1.011 ms  0.293 ms  1.437 ms
```

**Additional details as necessary:**
What seems to be happening is the lines
```
# add a routing table for traffic from bridge that is not destined
# for a local address
echo 201 bridge.out >> /etc/iproute2/rt_tables
ip rule add fwmark 1 table bridge.out
```
in /etc/systemd/scripts/nat-setup on the VCH is creating a new routing table named bridge.out, but not adding any routes. I believe the table inherits the system default route, but nothing else. 

```
root@ [ /etc/systemd/scripts ]# ip route show table bridge.out
default via XXX.YYY.235.254 dev public
```

Since there is only a single entry in this table, all packets get forwarded to the gateway, even those that are in the same subnet as the public IP (XXX.YYY.235.1/22 in the example above).

**Workaround:**
On the VCH run
```
ip route add XXX.YYY.232.0/22 dev public table bridge.out
```
to add a route for the local subnet. At this point traffic to the local subnet is now sent directly to the destination host, bypassing the gateway, as expected.

**Comment by mlh78750** [comment]
@corrieb @hickeng The intermittent network issues we've seen with container connectivity to networks could be related to this issue. The routing it wrong for NATed traffic from the container bridge networks routed to a L2 adjacent network of the VCH. Instead, those packets are sent to the gateway. And if they gateway then forwards back to the intended host is not a reliable. The GW technical doesn't have to and security minded GW will not.

**Comment by hickeng** [comment]
This change can easily be added to the following:
https://github.com/vmware/vic/blob/8467a20abe4daed1cd51ae63a3080efa9ae6a4f7/lib/tether/ops_linux.go#L459

It's of note that the bridge table modifications should really be in `cmd/vic-init/ops_linux.go` instead of in `lib/tether/ops_linux.go`

**Comment by hickeng** [comment]
Some prelim work in https://github.com/hickeng/vic/tree/6647 - however @vburenin has noted that this seems to no longer be an issue since a recent update to the Photon packages.
I'm not happy with not knowing precisely why something has started working without direct intervention so he will follow up with Photon team to see what could have changed.

**Comment by hickeng** [comment]
Ignore my previous update - forgot to add the routing table to inspect to the command.
Doesn't explain why @vburenin 's traceroute didn't have the extra hop when confirming.

**Comment by vburenin** [comment]
On bare metal setup the issue is easy to reproduce. On a virtual nested environment the routing issue is not the case.
