### ISSUE TITLE
Nightly Failure 6.5 5-7 NSX : Error adding container network "public": "VM Network" is not a Distributed Port Group

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#6653]
Date: 10-28-2017
Engine Build: 14245
vsphere version: 6.5
test N/a - Failed at the `Vic Machine Installation` step.
logs:   [5-7-NSX.zip](https://github.com/vmware/vic/files/1427922/5-7-NSX.zip)

**Comment by mhagen-vmware** [comment]
fixed with: https://github.com/vmware/vic/pull/6643
