### ISSUE TITLE
Refactor vic-mache: use mob-id, instead of name in configuration

### ISSUE THREAD

**Issue by emlin** [vmware/vic#666]
This issue has dependency on VCH service changes, so put it back to backlog temporarily.

**Comment by andrewtchin** [comment]
Currently in VirtualContainerHostConfigSpec we store string representations of the names of certain resources. We should phase in using the mob-id for these resources.

Attributes that need to be converted to ManagedObjectReferences are:

DatacenterName
ClusterPath
ResourcePoolPath
PortGroupName
ImageStores
VolumeLocations
ContainerStores

**Comment by andrewtchin** [comment]
Also refactor to validate all input and return a list of errors instead of returning the first error we reach and immediately exiting.

**Comment by hickeng** [comment]
I ended up doing the remainder of #665, #686 and #666 in PR #1127 for #746. Updating the estimate appropriately.
