### ISSUE TITLE
Nightly Failure 11/2/2017 NFS-Volume: Portlayer fails to power on after reboot due to a hung NFS mount attempt via the go-nfs-client

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#6677]
seen 11/2/2017
on: VC 6.0
Engine Build: 14352
Test Failure: obtain docker mount data after reboot
logs here: 
[5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1438520/5-22-NFS-Volume.zip)

Further important log information and analysis.

* Personality fails to present due to portlayer inability to initialize.

* Portlayer fails to initialize due to hung nfs mount attempt 
seen here

```
Nov  2 2017 07:20:37.646Z INFO  op=298.6 (delta:1.416013754s): Getting metadata volumes/2fcc0ea2-bf9e-11e7-a054-000c29e4a3c3/imageMetadata/DockerMetaData
Nov  2 2017 07:20:37.695Z INFO  Volumestore: Found vol 2fcc0ea2-bf9e-11e7-a054-000c29e4a3c3 on store http:///storage/volumes/default.
Nov  2 2017 07:20:37.695Z INFO  op=298.6 (delta:1.465297984s): Registering importer: ds://datastore1/%5Bdatastore1%5D%20VCH-0-9472-VOL => *vsphere.VolumeStore
Nov  2 2017 07:20:37.695Z INFO  op=298.6 (delta:1.465311048s): Registering exporter: ds://datastore1/%5Bdatastore1%5D%20VCH-0-9472-VOL => *vsphere.VolumeStore
Nov  2 2017 07:20:37.695Z INFO  op=298.6 (delta:1.465319168s): Registering importer: http:///storage/volumes/default => *vsphere.VolumeStore
Nov  2 2017 07:20:37.695Z INFO  op=298.6 (delta:1.465323557s): Registering exporter: http:///storage/volumes/default => *vsphere.VolumeStore
Nov  2 2017 07:20:37.696Z INFO  op=298.6 (delta:1.465334581s): Creating nfs volumestore nfsVolumeStore on nfs://10.161.242.84/store?uid=0&gid=0
Nov  2 2017 07:20:37.696Z DEBUG op=298.6 (delta:1.465339094s): Mounting nfs://10.161.242.84/store?uid=0&gid=0
```
These are the last lines in the portlayer log and the `docker info` command is reattempted 20 times in the test. 

suspected related ticket for a potential fix: https://github.com/vmware/vic/issues/6620

there is a reference PR out for this now here: https://github.com/vmware/vic/pull/6656 (currently failing due to build error in go-nfsclient)

**Comment by matthewavery** [comment]
This ticket will require some work toward the `go-nfs-client` as well. Which is why this is marked as a 5

**Comment by matthewavery** [comment]
incorrectly linked #6677 should be linked to #6616 because the container itself is hung in the tether.

**Comment by andrewtchin** [comment]
[5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1519007/5-22-NFS-Volume.zip)

**Comment by matthewavery** [comment]
Two changes have been made to help mitigate this issue in the nightlies. 

1) all nfs infra that is deployed will now be deployed to the same pod. We still need a `testbed` for the nfs tests to ensure a timely and reliable POD placement. But what we have now is solid. See https://github.com/vmware/vic/pull/6802 

2) We now correctly wait for the VCH to initialize and then we grab the correct IP after it comes back up. This is for the tests which are checking for reliability after a VCH restart. See https://github.com/vmware/vic/pull/6891
