### ISSUE TITLE
Drone does not always actually run against the most recent commit in a PR

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6695]
Several times this week I've experienced an issue where I push a new commit to a branch that has an open PR and drone triggers a new CI run, but that new run does not actually include the new commit (despite the proper hash being listed at the top of the page). This seems to happen regardless of whether I do a normal push, a force push, or a force push with a lease. Forking the run (or even simply immediately cancelling and restarting) sometimes fixes the issue.

PR #6693 was experiencing this issue consistently and has been preserved in its current state.

As a concrete change we could make to lessen the impact and aid in identifying the issue: drone seems to grab `refs/pull/<pr>/merge`, without verifying that the resulting `HEAD` matches the commit it thinks it's testing. Can we add a check very early in the CI process to fail if it doesn't get the bits it expected?

When that happens, the results are worse than useless; they're actively misleading and can cause you to believe a change has resulted in a build which still works when in reality you've broken something or vice versa.

cc @mdharamadas1

**Comment by morris-jason** [comment]
I’ve experienced this a number of times the past week as well.
Looks like it’s been reported before: https://github.com/drone-plugins/drone-git/issues/41

**Comment by anchal-agrawal** [comment]
Also see https://github.com/vmware/vic/issues/3897.

**Comment by zjs** [comment]
> Also see #3897.

Thanks for linking that. I'll close this as a duplicate.

**Comment by zjs** [comment]
> I’ve experienced this a number of times the past week as well.
> Looks like it’s been reported before: drone-plugins/drone-git#41

I'm not sure the issue I'm seeing is entirely a drone issue; I think GitHub may be a least partly to blame.

If I check `git fetch --tags origin +refs/pull/.../head` locally immediately after pushing, I get the up-to-date commit, but `git fetch --tags origin +refs/pull/.../merge` seems to sometimes lag behind (even if the merge is trivial).

¯\\\_(ツ)\_/¯
