### ISSUE TITLE
VCH Creation API: Ensure an ID can be used to specify any valid type of compute resource

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6711]
Currently, the `buildCreate` method used by the VCH creation API handlers contains logic to look up the name of compute resources specified by ID. That logic may be specific to resource pools. This should be investigated, and corrected. All types of compute resources which would be valid with the CLI should be valid with the API.

**Comment by zjs** [comment]
Names work today. IDs are less clear.

We must be able to deploy to a cluster by clicking on a cluster in the UI, but internally we always deploy to a resource pool (in the case of a cluster, it would be the top-level resource pool in that cluster, typically called "Resources"; in the case of a host, it would be the resource pool for that host, typically "hosts/.../Resources").

This issue may simply require ensuring that the UI is doing the right thing.

**Comment by zjs** [comment]
The UI currently uses names: https://github.com/vmware/vic-ui/blob/7529a4b3facad31992485fd7344c0c7e03d44684/h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts#L235

**Comment by javierfz1980** [comment]
I can confirm that VCH Creation API is partially working using an ID to specify any valid type of compute resource.

I've tried selecting Cluster, Host and ResourcePool from the UI wizard and this are the results:

Cluster (not working)
![cluster-fail](https://user-images.githubusercontent.com/36636787/41994359-8463cb46-7a24-11e8-9bdd-3f1520d86d5b.png)

Host (not working)
![host-fail](https://user-images.githubusercontent.com/36636787/41994375-8eb4c99c-7a24-11e8-91b9-101b51849ce5.png)

ResourcePool
![resourcepool-works](https://user-images.githubusercontent.com/36636787/41994518-0f2dcd9e-7a25-11e8-9edd-a4f599b985f8.png)

Right now this is blocking https://github.com/vmware/vic-ui/issues/514

**Comment by javierfz1980** [comment]
Guys, I'm reopening this because I've tested `vic-dev-v1.5.0-dev1-5553-81261247.ova` and it seems like api is not working as expected….

PoolResources are still working fine, but Hosts are not working and Cluster are partially working.

On Clusters the vch is being created, but is no creted inside a PoolResource as usual... the VM is created as a stand alone VM inside the cluster

On Hosts the vch is not created at all, the request is returning the following error, take a look at screenshots please.

<img width="1316" alt="host-fail" src="https://user-images.githubusercontent.com/36636787/42285784-f135841e-7f86-11e8-9ce7-d90e75b27f9f.png">

<img width="1301" alt="cluster-fail" src="https://user-images.githubusercontent.com/36636787/42285789-f6f68bc8-7f86-11e8-9d52-9fc4d851e281.png">

**Comment by hickeng** [comment]
@javierfz1980 I'll leave @zjs to comment on the single host case.

I do have some follow up questions:
1. does the VCH get created in a resource pool on the standalone host when that is working?
  - @zjs we should add a test case for this standalone host scenario if not already present as the ROBO updates could have changed behavior
2. does `Cluster within folder` have DRS enabled? If DRS _is_ enabled it suggests we have an error path where we should have failed but did not.

@zjs we should consider vcsim tests for this change given the breakage. I do not know if it currently allows DRS/no-DRS toggling but it should suffice for the basic topology facet.

**Comment by javierfz1980** [comment]
@hickeng @zjs you are totally right, cluster with DRS is working as expected (vch is created inside a rp), so Clusters and PoolResources are working as expected, so we only have to fix Hosts behavior

Regarding to your 1st question... yes, the VCH get created in a resource pool on the standalone host when that is working fine ( you can see 'test-tree3' and 'test-tree4' the following screenshot)
<img width="432" alt="host-rp" src="https://user-images.githubusercontent.com/36636787/42575061-24f9afae-84f6-11e8-96a8-ca5d3ce4c9ef.png">


I've tried again selecting stand alone hosts, and still the same error:
<img width="1069" alt="host-fail1" src="https://user-images.githubusercontent.com/36636787/42574737-866ba536-84f5-11e8-89f7-fe51a53a8ae1.png">

<img width="1066" alt="host-fail2" src="https://user-images.githubusercontent.com/36636787/42574748-8a63ebe4-84f5-11e8-873f-84dcd8dfbf15.png">

**Comment by zjs** [comment]
The root cause of the issue with hosts seems to be that govmomi does not return the expected path for standalone hosts.

This series of calls results in a path like `/Datacenter1/host/10.161.96.106/10.161.96.106` instead of `/Datacenter1/host/10.161.96.106`:

https://github.com/vmware/vic/blob/ef7abe0341341fbb97337b5a1e96b685d506f546/lib/apiservers/service/restapi/handlers/decode/references.go#L34-L38

https://github.com/vmware/vic/blob/ef7abe0341341fbb97337b5a1e96b685d506f546/vendor/github.com/vmware/govmomi/find/finder.go#L276-L288

https://github.com/vmware/vic/blob/ef7abe0341341fbb97337b5a1e96b685d506f546/vendor/github.com/vmware/govmomi/find/finder.go#L92-L128

Manually hacking the [line that returns the path](https://github.com/vmware/vic/blob/ef7abe0341341fbb97337b5a1e96b685d506f546/lib/apiservers/service/restapi/handlers/decode/references.go#L38) to return only the IP address of the host (`return strings.Split(element.Path, "/")[4], nil`) or to strip the duplicated IP address (`return strings.Join(strings.Split(element.Path, "/")[:4], "/"), nil`) seems to work around the issue.
