### ISSUE TITLE
VCH Creation API: Decide what to do if RoutingDestinations is empty

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6715]
Currently, the `fromGateway` method used by the VCH creation API handlers is unclear about the behavior if the supplied `RoutingDestinations` are empty. We should determine what work, if any, is required here.

**Comment by andrewtchin** [comment]
determine when routingdestinations is required (should match cli) and figure out if we can use swagger features for validation

**Comment by andrewtchin** [comment]
Related #6400

**Comment by zjs** [comment]
Relevant lines from the `vic-machine-*` CLI help output:
```
   --client-network-gateway value                   Gateway for the VCH on the client network, including one or more routing destinations in a comma separated list, e.g. 10.1.0.0/16,10.2.0.0/16:10.0.0.1
   --public-network-gateway value                   Gateway for the VCH on the public network, e.g. 10.0.0.1
   --management-network-gateway value               Gateway for the VCH on the management network, including one or more routing destinations in a comma separated list, e.g. 10.1.0.0/16,10.2.0.0/16:10.0.0.1
   --container-network-gateway value, --cng value   Gateway for the container network's subnet in CONTAINER-NETWORK:SUBNET format, e.g. vsphere-net:172.16.0.1/16
```

Based on this, it would appear that the CLI's requirements differ slightly depending on the type of network:
 * Client: one or more
 * Public: zero
 * Management: one or more
 * Container: exactly one
