### ISSUE TITLE
Capture log output on test failure in Jenkins or new Drone

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#672]
The integration tests need to be modified to capture the log output from the vicadmin server after execution but before the VCH is destroyed in order to provide context when the tests fail. Modifications will be made in addition to artifacting that output (a tarball) in Jenkins on test failure.

Additionally this will be exercising our log collection facilities which, to quote George, "has its own value"

**Comment by mdubya66** [comment]
fyi, fabio is in austin today and we are looking at moving back to drone for Integration tests and to leverage the HaaS infrastructure in the new DC.

**Comment by fdawg4l** [comment]
Do we need to use drone in order to use HaaS?  Can we put jenkins on HaaS and make it public?

**Comment by dougm** [comment]
Let's not get into Jenkins vs Drone here.  The main change we need from @gigawhitlocks here is for the integration test to capture the VCH logs.  This will both test some of the vicadmin code paths and provide debugging info when running the tests locally, independent of CI.  The CI portion will just archive these logs as job artifacts.

**Comment by gigawhitlocks** [comment]
Yep @dougm has it -- biggest change is actually capturing the logs inside of tests. Whether we use Drone or Jenkins in the long run, it doesn't really matter as far as this story is concerned.

**Comment by gigawhitlocks** [comment]
Changes needed to test are done but changes will be made to Drone after https://github.com/vmware/vic/pull/707 is merged, rather than spending any more time on Jankins

**Comment by gigawhitlocks** [comment]
Placing back in TODO until #707 is merged since #698 is merged so the last part of this will be configuring Drone

**Comment by hickeng** [comment]
@gigawhitlocks Can this be closed now #752 is closed?
