### ISSUE TITLE
VCH Creation Log APIs: simplify getAllLogFilePaths

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6733]
See https://github.com/vmware/vic/pull/6665#discussion_r149573903:
> If you look at the implementation of `helper.Ls` it would be trivial to change it so that you can actually provide a pattern instead of a static name. There is already a MatchPattern defined as part of the search spec.
> That would basically eliminate the need for this function.

**Comment by andrewtchin** [comment]
deferrable, removed from release 1.3

**Comment by AngieCris** [comment]
@zjs @hickeng 
It seems that the `helper.Ls` function doesn't take in a pattern as an argument:
https://github.com/vmware/vic/blob/master/pkg/vsphere/datastore/datastore.go#L182-L189
```
func (d *Helper) Ls(ctx context.Context, p string) (*types.HostDatastoreBrowserSearchResults, error) {
	spec := types.HostDatastoreBrowserSearchSpec{
		MatchPattern: []string{"*"},
		Details: &types.FileQueryFlags{
			FileType:  true,
			FileOwner: types.NewBool(true),
		},
	}

	b, err := d.ds.Browser(ctx)
	if err != nil {
		return nil, err
	}

	task, err := b.SearchDatastore(ctx, path.Join(d.RootURL.String(), p), &spec)
```
It constructs a search pattern with only `*` character (`MatchPattern: []string{"*"}`), and the argument `p` provided is only treated as a path: `b.SearchDatastore(ctx, path.Join(d.RootURL.String(), p), &spec)`
Does this mean that the `helper.Ls` function can only list all files under a relative path?
