### ISSUE TITLE
Cannot specify static IP: "Server error from portlayer: could not find IP range."

### ISSUE THREAD

**Issue by msweetser** [vmware/vic#6751]
I've used the following on ESXi 6.5 standalone to create my VIC:

./vic-machine-darwin create --target 10.0.1.252 --user root --no-tls --image-store datastore-titan/docker-image --volume-store datastore-titan/docker-volume:default --container-network docker-containers:docker-container-network --container-network-gateway docker-containers:10.0.1.1/24 --container-network-ip-range docker-containers:10.0.1.0/24 --container-network-dns docker-containers:10.0.1.10 --container-network-dns docker-containers:10.0.1.11 --thumbprint 6C:28:18:EB:2F:13:B7:DF:3E:19:73:D9:49:4D:2E:6E:D2:D1:7B:52

And the following to create a nginx container:

docker run -d -p 80:80 --ip 10.0.1.12 --name nginx1 nginx

But receive the following error:

docker: Error response from daemon: Server error from portlayer: could not find IP range.

What am I doing wrong?

**Comment by mhagen-vmware** [comment]
Can you please include the container-logs ( login to VCH admin page and click download container logs ), and the vic-machine.log from the install?

**Comment by mhagen-vmware** [comment]
@msweetser Please reopen this bug if you can reproduce the issue and include the container logs so that we can debug further
