### ISSUE TITLE
--volume-store doesn't permit DS's with whitespace in name

### ISSUE THREAD

**Issue by ddisisto** [vmware/vic#6766]
**VIC version:**

vic-machine-linux version v1.2.0-13652-9d146bc

**Deployment details:**

What was the vic-machine create command used to deploy the VCH? Yes

**Steps to reproduce:**

1. Have a datastore with whitespace or other 'special' (but legal) characters in its name
2. Attempt to mount a volume-store on such a datastore

**Actual behavior:**

```
ddisisto@neptune:~$ vic-machine-linux configure --id vm-172185 --volume-store 'VIC 01/VIC/:default'
Nov 15 2017 15:28:13.907+11:00 ERROR --------------------
Nov 15 2017 15:28:13.907+11:00 ERROR vic-machine-linux configure failed: volume store input must be in format <datastore url w/ path>:label or nfs://<host>/<url-path>?<mount option as query parameters>:<label>
```

**Expected behavior:**

The volume-store mounts successfully

**Additional details as necessary:**

After renaming the above datastore in vSphere to no longer include the space, the volume store can be created. In our environment there are also datastores with parentheses, etc in their names, which work fine for --image-store option, just not for --volume-store

**Comment by zjs** [comment]
Based on [the documentation](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/volume_stores.html#example-vic-machine-commmand-), it appears that you may need to quote the datastore name, and not the full argument to `--volume-store`:

> `--volume-store 'datastore 1'/volumes:default`

This seems counter-intuitive; I think most people (myself included) would expect that quoting the whole argument would work.

**Comment by mhagen-vmware** [comment]
@ddisisto Does that example above work for you?

**Comment by mhagen-vmware** [comment]
@ddisisto please reopen if that workaround did not work for you. Thanks!
