### ISSUE TITLE
--https-proxy setting does not permit http:// URI

### ISSUE THREAD

**Issue by ddisisto** [vmware/vic#6767]
**VIC version:**

vic-machine-linux version v1.2.0-13652-9d146bc

**Deployment details:**

What was the vic-machine create command used to deploy the VCH? Yes

**Steps to reproduce:**

1. Have a proxy that only listens on http/8080, but is capable of proxying both http + https traffic
2. Attempt to configure that proxy for both --http-proxy + --http**s**-proxy

**Actual behavior:**

```
ddisisto@neptune:~$ vic-machine-linux configure --id vm-172185 --https-proxy=http://proxy.gsoa.ddau:8080
Nov 15 2017 16:43:40.942+11:00 ERROR --------------------
Nov 15 2017 16:43:40.942+11:00 ERROR vic-machine-linux configure failed: Could not parse HTTPS proxy - expected format https://fqnd_or_ip:port: http://proxy.gsoa.ddau:8080
```

**Expected behavior:**

The configuration is updated

bug2157829

**Comment by ddisisto** [comment]
I've SSHd to the VCH VM in the hopes of finding where this is configured for the docker engine so that I could manually update it in-place until this is resolved. I have not been able to find it anywhere, and so remain unable to make any https connections from the docker engine.

**Comment by mhagen-vmware** [comment]
@ddisisto I am a bit confused... you said it is only listening on http/80? but in your example you are doing port 8080?
Have you tried the --http-proxy?  Does that not give you what you want?

**Comment by ddisisto** [comment]
@mhagen-vmware My mistake, proxy is at http/8080 (fixed in initial comment now), which in docker and elsewhere in this environment I would always set as both `HTTP_PROXY` & `HTTPS_PROXY`. Setting only the `--http-proxy` does works fine, and maybe this is all that's needed for the docker engine to use proxy for both HTTP & HTTPS traffic, but I'm used to always just setting both to be sure.

To my knowledge, these two lines should both accept EITHER http or https schemes to be defined -
https://github.com/vmware/vic/blob/d649a8a59393eab939fac20cb80634087e2ec517/cmd/vic-machine/common/proxy.go#L56
https://github.com/vmware/vic/blob/d649a8a59393eab939fac20cb80634087e2ec517/cmd/vic-machine/common/proxy.go#L64

As the scheme used to connect to a proxy does not need to be the same as that of traffic that will be passed through it.

**Comment by mhagen-vmware** [comment]
Thanks @ddisisto I am glad that using http-proxy seems to work for you! We will review your recommendation as you have suggested.  Thanks!

**Comment by hickeng** [comment]
Added into 1.4.2 due to bug2157829 and explicit impediment in real usage.

**Comment by zjs** [comment]
I think this is worth a release note, as it was a customer-reported issue.

**Comment by stuclem** [comment]
Added as a resolved issue in https://github.com/vmware/vic/releases/tag/v1.4.3
