### ISSUE TITLE
Only harbor registry should be used once content trust is enabled

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6778]
**Story**
As a cloudadmin when I check the _content trust_ checkbox I expect only signed images to be allowed to run.

**Details**
With the addition of docker hub to the defined registry set in Admiral we need to be more prescriptive about which registries we pull from the config to use as the VCH whitelist.

We currently use the following query:
```
/config/registries?expand=true
```

We need to switch to
```
/config/registries/default-vic-registry
```
or
```
/config/registries?$filter=documentSelfLink eq '/config/registries/default-vic-registry'&expand=all
```

Note: the following would give _all but the default Docker Hub instance_:
/config/registries?$filter=documentSelfLink ne '/config/registries/default-registry'&expand=all

Queries provided by Sergio.

Estimate is for the change and should include an update to the integration test plan.

**Comment by hickeng** [comment]
I believe that this is as simple as the following but I've not confirmed:
```diff
index cabbc57..703881d 100644
--- a/lib/config/dynamic/admiral/source.go
+++ b/lib/config/dynamic/admiral/source.go
@@ -352,7 +352,7 @@ func (a *source) whitelist(ctx context.Context, c *client.Admiral, hostProjs []s
                return nil, nil
        }

-       regs, err := c.ConfigRegistries.GetConfigRegistries(config_registries.NewGetConfigRegistriesParamsWithContext(ctx).WithExpand(&trueStr))
+       regs, err := c.ConfigRegistries.GetConfigRegistriesID(config_registries.NewGetConfigRegistriesIDParamsWithContext(ctx).WithID("default-vic-registry"))
        if err != nil {
                return nil, err
        }

```

**Comment by hickeng** [comment]
Spoke with @mlh78750 and @mhagen-vmware and pulling this back into the release.
Requirement is tests in addition to code code, not just a manual check.

**Comment by anchal-agrawal** [comment]
@sergiosagu Is `default-vic-registry` (the registry ID) configurable by the user? I see in the UI that it is also the **name** and I can change it:

Initial screen:
<img width="865" alt="default" src="https://user-images.githubusercontent.com/4361620/33583016-c6289d66-d91d-11e7-8e66-8b3b858acd7b.png">

Change the name:
<img width="862" alt="harbor" src="https://user-images.githubusercontent.com/4361620/33583018-c64aaed8-d91d-11e7-9ffe-d9812c786696.png">

After making this change, `default-vic-registry` still returned the Harbor instance so the `/config/registries/default-vic-registry` is functioning as expected, which leads me to believe that `default-vic-registry` is a non-configurable ID for Harbor (and it is also named `default-vic-registry` in the UI).

**I wanted to confirm that if the user changes the name of the Harbor registry in the UI and/or names a different registry as `default-vic-registry` through the UI, the `default-vic-registry` endpoint will still function as expected.**

Thanks!

**Comment by sergiosagu** [comment]
@anchal-agrawal - That's correct, by default the id is `default-vic-registry` and it can't be changed (because that would break the integration with the default Harbor instance). On the other hand the default name is the same like the id, but it can be edited by the user if he wants.
