### ISSUE TITLE
What does "bad scheme provided for datastore" mean?

### ISSUE THREAD

**Issue by sderungs** [vmware/vic#6796]
> [ ] Questions are best asked and answered on Slack
>     https://vmwarecode.slack.com/messages/vic-engine (see  https://github.com/vmware/vic/blob/master/CONTRIBUTING.md#community for details)

_--> This does not work - I cannot sign up as I don't have an @vmware.com address and I can only sign up if I had one. So my question lands here._

I'm trying to get the Demo VCH to run from the "Default VCH Installer".

The created command is:
`/opt/vmware/engine_installer/vic/vic-machine-linux create --no-tlsverify --target 10.195.7.3 --user removed@vsphere.local --password ******** --name demo-vch --public-network /DC1/network/VCH Networks/PublicNetwork --bridge-network /DC1/network/VCH Networks/ALMT-VCH-1-Bridge --compute-resource /DC1/host/zrhvm891.removed.com/Resources/_REMOVED --image-store zrhvm891:datastore2 --insecure-registry 10.195.7.80:443 --thumbprint 0B:FD:46:8B:60:AE:0D:67:69:FB:5E:01:03:67:DB:FF:F8:21:DB:C4`

The output of the executed command is:

> Nov 20 2017 08:21:16.742Z INFO  ### Installing VCH ####
> Nov 20 2017 08:21:16.742Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
> Nov 20 2017 08:21:16.743Z INFO  Loaded server certificate demo-vch/server-cert.pem
> Nov 20 2017 08:21:16.743Z WARN  Configuring without TLS verify - certificate-based authentication disabled
> Nov 20 2017 08:21:16.833Z INFO  Validating supplied configuration
> Nov 20 2017 08:21:16.912Z INFO  vDS configuration OK on "/DC1/network/VCH Networks/ALMT-VCH-1-Bridge"
> Nov 20 2017 08:21:16.912Z ERROR Firewall check SKIPPED
> Nov 20 2017 08:21:16.912Z ERROR   datastore not set
> Nov 20 2017 08:21:16.912Z ERROR License check SKIPPED
> Nov 20 2017 08:21:16.912Z ERROR   datastore not set
> Nov 20 2017 08:21:16.912Z ERROR DRS check SKIPPED
> Nov 20 2017 08:21:16.912Z ERROR   datastore not set
> Nov 20 2017 08:21:16.919Z INFO  Insecure registries = 10.195.7.80:443
> Nov 20 2017 08:21:16.919Z ERROR Compatibility check SKIPPED
> Nov 20 2017 08:21:16.919Z ERROR   datastore not set
> Nov 20 2017 08:21:16.919Z ERROR --------------------
> Nov 20 2017 08:21:16.919Z ERROR bad scheme "zrhvm891" provided for datastore
> Nov 20 2017 08:21:16.919Z ERROR Firewall check SKIPPED
> Nov 20 2017 08:21:16.919Z ERROR License check SKIPPED
> Nov 20 2017 08:21:16.919Z ERROR DRS check SKIPPED
> Nov 20 2017 08:21:16.919Z ERROR Compatibility check SKIPPED
> Nov 20 2017 08:21:16.919Z ERROR Create cannot continue: configuration validation failed
> Nov 20 2017 08:21:16.924Z ERROR --------------------
> Nov 20 2017 08:21:16.924Z ERROR vic-machine-linux create failed: validation of configuration failed
> Create failed with error: exit status 1

What does the above error message "bad scheme provided for datastore" mean and how do I resolve it?

**Comment by anchal-agrawal** [comment]
Hi @sderungs, thanks for reporting!

Regarding `--image-store zrhvm891:datastore2` in your `vic-machine-linux create` command, what is `zrhvm891`? If `datastore2` is a vSphere-backed datastore in your environment, you can simply say `--image-store datastore2`.


You can read more about the `--image-store` option here: https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/image_store.html.

**Comment by mhagen-vmware** [comment]
@sderungs Please reopen this issue, if specifying datastore as Anchal has indicated does not work.  Thank you!

**Comment by sderungs** [comment]
When doing --image-store datastore2 I get the following:

> Nov 21 2017 08:12:49.294+01:00 INFO  Validating supplied configuration
> Nov 21 2017 08:12:49.369+01:00 INFO  Suggesting valid values for --image-store based on "datastore2"
> Nov 21 2017 08:12:49.371+01:00 INFO  Suggested values for --image-store:
> Nov 21 2017 08:12:49.371+01:00 INFO    "zrhvm891:datastore2"
> Nov 21 2017 08:12:49.372+01:00 INFO    "zrhvm891:datastore1"

zrhvm891 is an ESXi host (actually the only one) and has local storage. The whole environment is integrated into a vCenter instance (10.195.7.3); and 10.195.7.80 is the VIC appliance.

**Comment by anchal-agrawal** [comment]
Thanks for the update @sderungs - what is the name of the datastore you're using? Is it `zrhvm891:datastore2` or `datastore2`?

From your above comment, it looks like the name is actually `zrhvm891:datastore2` - if this is the case, please rename the datastore to not include the `:` character - something like `zrhvm891-datastore2` or `zrhvm891_datastore2` should do. Please see the following note in the `Storage Requirements and Limitations` section at https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/vch_storage.html:

> vSphere Integrated Containers Engine supports all alphanumeric characters, hyphens, and underscores in datastore paths and datastore names, but no other special characters.

**Comment by gigawhitlocks** [comment]
As a workaround it might be possible to provide the datastore name as `ds://zrhvm891:datastore2` -- I'm not 100% sure that will work, but the issue is that our URL parser is interpreting `zrhvm891` as a URL scheme, and I believe only what appears before the first colon is considered the scheme, so specifying the scheme `ds://` as part of the datastore URL may cause it to parse properly.

Otherwise renaming the datastore as @anchal-agrawal suggested will work.

**Comment by sderungs** [comment]
Renaming the datastores with underscores instead of colons resolved the issue. Many thanks!

**Comment by carloreggiani** [comment]
I'm fighting the last 2 days with this issue trying to deploy a vic-1.5! Why in documentation is it not CLEARLY specify to not use colon????? ARGHHHH :(
