### ISSUE TITLE
Boot optimizations

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#68]
When disabling fork we should skip the fork calls and the corresponding specialization w.r.t setting clocks, unloading and loading vmxnet3 modules, et al.
If wanting to do further optimization this presentation has some possibly useful items in it: http://elinux.org/images/9/97/Boot_one_second_altenberg.pdf

**Comment by hickeng** [comment]
This is extremely specific to our previous use of the bonneville bootstrap image and the specifics addressed in this issue are no longer relevant. Closing.
