### ISSUE TITLE
Log streaming during VCH creation can fail, resulting in "Failed to write to log, unexpected EOF" spam

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6801]
During VCH creation, we upload a log to the datastore using `govmomi`:

https://github.com/vmware/vic/blob/ceb9a4be3128763f66a9299f41211372b9655502/lib/install/vchlog/vchlogger.go#L63

Sometimes, the `Close()` method on the supplied `pipe` is called by the client code:

```
github.com/vmware/vic/lib/install/vchlog.(*BufferedPipe).Close(0xc4201f9680, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/install/vchlog/buffered_pipe.go:89 +0x11a
net/http.(*Request).closeBody(0xc42006e100)
	/usr/local/go/src/net/http/request.go:1295 +0x43
net/http.(*Client).Do.func1(0x188c0a0, 0xc420014140, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:507 +0x59
net/http.(*Client).Do(0xc420094630, 0xc42006e100, 0xc42003ac28, 0xfa4275, 0x18)
	/usr/local/go/src/net/http/client.go:602 +0x3d2
github.com/vmware/vic/vendor/github.com/vmware/govmomi/vim25/soap.(*Client).Upload(0xc420094630, 0x188c2e0, 0xc4201f9680, 0xc4201fa080, 0xc4201e5860, 0x0, 0x0)
	/go/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/vim25/soap/client.go:580 +0x242
github.com/vmware/vic/vendor/github.com/vmware/govmomi/object.Datastore.Upload(0xc4202a99a0, 0x1b, 0xc42047cb00, 0xc4202b0aa0, 0x9, 0xc4202b0b00, 0xc, 0xc42029710c, 0x4, 0x1896aa0, ...)
	/go/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/object/datastore.go:287 +0x14b
github.com/vmware/vic/lib/install/vchlog.(*VCHLogger).Run(0xc4201c9fc0)
	/go/src/github.com/vmware/vic/lib/install/vchlog/vchlogger.go:63 +0x2bc
created by github.com/vmware/vic/cmd/vic-machine/create.(*Create).Run
	/go/src/github.com/vmware/vic/cmd/vic-machine/create/create.go:676 +0x30d
```

The result is that uploaded log is truncated and "Failed to write to log, unexpected EOF" is printed to users of the `vic-machine` CLI once for each message.

Following the stack trace, we see that `datastore.go` delegates the upload to `client.go`:
https://github.com/vmware/vic/blob/ceb9a4be3128763f66a9299f41211372b9655502/vendor/github.com/vmware/govmomi/object/datastore.go#L281-L288

Which performs the actual upload:
https://github.com/vmware/vic/blob/ceb9a4be3128763f66a9299f41211372b9655502/vendor/github.com/vmware/govmomi/vim25/soap/client.go#L550-L593

The problem comes from the call to `Client.Do` on the underlying `net/http.Client`, [which calls `closeBody()` on the supplied `Request` if an error occurs](https://github.com/golang/go/blob/release-branch.go1.8/src/net/http/client.go#L507).

cc @matthewavery

**Comment by andrewtchin** [comment]
noted as ship stopper for 1.3
