### ISSUE TITLE
Documentation for ops-user vic-machine option needs to be updated

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#6822]
**User Statement:**
With the introduction of Resource Pools and the ops-grant-perms option the documented procedure to set Roles and Permissions needs to be updated.

**Details:**
Resource Pools are now the only option in VCH create. The Roles and Permissions previously documented in the Appliance mode cannot longer be applied. In general new Permissions are needed at the Data Center level. The current documentation should be updated.
The new create/configure option --ops-grant-perms also needs to be documented.

**Acceptance Criteria:**
Documentation has been updated.

**Comment by stuclem** [comment]
Thanks for the info @lcastellano. Moving this to the vic-product repo.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #1157](https://github.com/vmware/vic-product/issues/1157) via [**ZenHub**](https://www.zenhub.com/)
