### ISSUE TITLE
Automation & integration tests for OVA and vic-ui plugin install

### ISSUE THREAD

**Issue by jzt** [vmware/vic#6829]
**User Statement:**

As a developer, I would like to be able to test the OVA deploy and UI plugin installation in an automated fashion.

**Details:**

Currently, the workflow for testing changes to the vic-ui installer are very inefficient. It requires the developer to hand-craft a tar archive containing the vic-ui binaries and the vic-ui plugins, then hand-craft an OVA using that tar archive as the option to `--vicengine`. Once that is complete, the OVA then must be deployed via upload to our GCS bucket and subsequently into VC (if on the VPN), or directly to a VC in nimbus and then manually powered on.  After this, the developer must manually trigger the `Getting Started` step, and then manually download and run the installer against the OVA and the VC in which the OVA is running.

It would be far more efficient if the dev process could automate this process.

Pushes to forks at `vmware/vic-ui`, `vmware/vic`, and `vmware/vic-product` should automatically and independently generate the required artifacts to test (vic ui plugin, vic engine, and ova artifacts, respectively). Dependencies should be configurable such that triggering of a particular artifact build could include specific artifacts to be used as dependencies (for example, I could, in my PR, indicate that my commit `1234abcd` to `vmware/vic/cmd/vic-ui` requires a new OVA to be built that uses build `1234abcd` of vic-engine instead of the latest from `master`.

Integration tests should be capable of downloading the corresponding artifacts and automatically testing them in the same way that a user would.

**Acceptance Criteria:**
- Automatic, configurable artifact creation 
- Automatic retrieval by CI of specific artifacts for deployment within a testing scenario
- Automatic OVA fileserver configuration, installer download/extract/execution

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-product #1122](https://github.com/vmware/vic-product/issues/1122) via [**ZenHub**](https://www.zenhub.com/)
