### ISSUE TITLE
Regression in our vic-machine logging

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6836]
Nightly test failure in `5-13-Invalid-ESXi-Install` test.
This is due to the test expecting plain quotes but receiving escaped quotes.

The output robot sees is formatted for machine parsing/log entry.
From @mhagen-vmware 
> It looks like we have a regression in our stdout output for vic-machine. The vic-machine.log is correct, but stdout shows a bunch of new non-printing characters like \, ", \n, etc.

From output.xml:
```
<msg timestamp="20171121 19:36:39.633" level="FAIL">'time="2017-11-21T19:36:36-06:00" level=info msg="### Installing VCH ####" 
time="2017-11-21T19:36:36-06:00" level=warning msg="Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)" 
time="2017-11-21T19:36:36-06:00" level=warning msg="Configuring without TLS - all communications will be insecure" 
time="2017-11-21T19:36:38-06:00" level=info msg="Validating supplied configuration" 
time="2017-11-21T19:36:39-06:00" level=info msg="Suggesting valid values for --image-store based on \"*\"" 
time="2017-11-21T19:36:39-06:00" level=info msg="Suggested values for --image-store:" 
time="2017-11-21T19:36:39-06:00" level=info msg="  \"datastore1\"" 
time="2017-11-21T19:36:39-06:00" level=info msg="  \"build-storage61.eng.vmware.com_0\"" 
time="2017-11-21T19:36:39-06:00" level=info msg="  \"scm-trees.eng.vmware.com_0\"" 
time="2017-11-21T19:36:39-06:00" level=info msg="  \"build-ob.eng.vmware.com_0\"" 
time="2017-11-21T19:36:39-06:00" level=info msg="  \"build-apps.eng.vmware.com_0\"" 
time="2017-11-21T19:36:39-06:00" level=info msg="  \"bugs.eng.vmware.com_0\"" 
time="2017-11-21T19:36:39-06:00" level=info msg="  \"build-toolchain.eng.vmware.com_0\"" 
time="2017-11-21T19:36:39-06:00" level=error msg="Firewall check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="  datastore not set" 
time="2017-11-21T19:36:39-06:00" level=error msg="License check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="  datastore not set" 
time="2017-11-21T19:36:39-06:00" level=error msg="DRS check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="  datastore not set" 
time="2017-11-21T19:36:39-06:00" level=error msg="Compatibility check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="  datastore not set" 
time="2017-11-21T19:36:39-06:00" level=error msg=-------------------- 
time="2017-11-21T19:36:39-06:00" level=error msg="Target is managed by vCenter server \"10.160.152.253\", please change --target to vCenter server address or select a standalone ESXi" 
time="2017-11-21T19:36:39-06:00" level=error msg="datastore empty" 
time="2017-11-21T19:36:39-06:00" level=error msg="Firewall check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="License check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="DRS check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="Compatibility check SKIPPED" 
time="2017-11-21T19:36:39-06:00" level=error msg="Create cannot continue: configuration validation failed" 
time="2017-11-21T19:36:39-06:00" level=error msg=-------------------- 
time="2017-11-21T19:36:39-06:00" level=error msg="vic-machine-linux create failed: validation of configuration failed\n" ' does not contain 'Target is managed by vCenter server "10.160.152.253", please change --target to vCenter server address or select a standalone ESXi'</msg>
```

**Comment by zjs** [comment]
You'll only get this format if piping the CLI output to a file. (Even using `tee` should avoid this.)

Can you confirm the log file matches the old format and TTY format is nicely formatted?

**Comment by hickeng** [comment]
I think this is likely because robot I/O doesn't present as a shell so we're not getting an output rendered for TTY.
I _think_ we've hit this before - perhaps it was @hmahmood that was working on it.

**Comment by sgairo** [comment]
@zjs vic-machine.log format: `Target is managed by vCenter server "10.192.198.26", please change --target to vCenter server address or select a standalone ESXi`

log.html: `"Target is managed by vCenter server \"10.160.152.253\", please change --target to vCenter server address or select a standalone ESXi" `

**Comment by zjs** [comment]
Silver lining: this format is much more machine-readable (as lines are consistently parseable, which isn't true when logs include raw newlines).

**Comment by andrewtchin** [comment]
so is the fix to update what the tests expect?

**Comment by sgairo** [comment]
I dont believe so, because it still renders incorrectly

**Comment by andrewtchin** [comment]
@zjs so should the nightlies tests use `tee` to get the expected format?

**Comment by zjs** [comment]
> it still renders incorrectly

It renders differently than it used to, and differently than our tests expect. I don't think the new rendering is _incorrect_. With this format, a log entry with multiple lines is captured with newlines escaped... and I think that's a good thing.

Currently, this new key-value format should only be used when writing to something other than an interactive terminal. In most "real world" use cases, I think that would mean `vic-machine` is being invoked from a script of some sort. For those use cases, the new format seems _better_ as it is easier to parse in a reliable way.

As an example, here's a cross-language regex to parse each log entry, with named matching groups for the "required" portion of the log line:
```regex
^time=(?P<time>"[^"]*"|[^"]*)\s+level=(?P<level>"[^"]*"|[^"]*)\s+msg=(?P<msg>"[^"\\]*(?:\\.[^"\\]*)*"|[^"]*)(\s+([^=]+)=("[^"\\]*(?:\\.[^"\\]*)*"|[^"]*))?\s*$
```

`msg` may be string containing `\n` characters, which can be interpreted by the script parsing the output and rendered appropriately. (As a simple example, passing a raw `msg` value to `/bin/echo -e` will do the right thing with both quotes and newline characters.)

With the old format, you can end up with output like this:
```
Nov 19 2017 11:21:28.286-08:00 INFO  op=10828.1: VCH ID: VirtualMachine:vm-548
Nov 19 2017 11:21:28.500-08:00 INFO  op=10828.1: Removing VMs
Nov 19 2017 11:21:28.991-08:00 INFO  op=10828.1: Removing image stores
Nov 19 2017 11:21:30.356-08:00 WARN  op=10828.1: Since --force was not specified, the following volume stores will not be removed. Use the vSphere UI or supplied nfs targets to delete content you do not wish to keep.
 vsphere volumestores:
        default: [sharedVmfs-1] VCH-0-5215-VOL

 NFS volumestores:


Nov 19 2017 11:21:30.356-08:00 INFO  op=10828.1: Removing appliance VM network devices
```

This is _okay_ (but, I'd argue, undesirable) for our log files, but worse; a script invoking `vic-machine` can't easily capture and propagate the `WARN` entry, as it spans lines unpredictably.

> is the fix to update what the tests expect?

That's what I would propose.

I'm not sure if robot makes it easy to parse a line of key-value pairs, but that's essentially what this new format is. Parsing it that way should address the escaped characters.

Worst case, for now we can just escape double quote characters in our expectations.

**Comment by zjs** [comment]
> so should the nightlies tests use `tee` to get the expected format?

I'm not sure `tee` would work for the nightlies. In the case of an actual user, `tee` works because there's still a real  TTY in the picture. That's not the case in Drone.

**Comment by zjs** [comment]
One option might be to use `script`: https://stackoverflow.com/a/1402389

**Comment by zjs** [comment]
As an aside, but because we're talking about log formatting:

It's worth noting that we lose information with the format we currently use for `vic-machine.log`. Lines like this are actually _supposed_ to include a bunch of information:
```
Nov 19 2017 18:28:15.579Z DEBUG Session Environment Info: 
```

TTY example:
```
DEBU[0001] Session Environment Info:                     API Type=VirtualCenter API Version=6.5 Build=5973321 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=5ce25bfe-2960-40ac-a9a8-87a370f84f0f Vendor="VMware, Inc." Version=6.5.0
```

Non-TTY example:
```
time="2017-11-22T17:25:15-05:00" level=debug msg="Session Environment Info: " API Type=VirtualCenter API Version=6.5 Build=5973321 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=5ce25bfe-2960-40ac-a9a8-87a370f84f0f Vendor="VMware, Inc." Version=6.5.0 
```
