### ISSUE TITLE
Refactor vic-machine: use vsphere/extraconfig to encode guestinfo

### ISSUE THREAD

**Issue by emlin** [vmware/vic#686]

**Comment by hickeng** [comment]
This looks like a duplicate of #594

**Comment by emlin** [comment]
Duplicate with #594, so close this one

**Comment by mdubya66** [comment]
removed from milestone

**Comment by hickeng** [comment]
I ended up doing the remainder of #665, #686 and #666 in PR #1127 for #746. Updating the estimate appropriately.
