### ISSUE TITLE
vic-machine-server does not log server panics

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6860]
**User Statement:**

As a user, I would like the server panics logged to vic-machine-server log file as well.

**Details:**
Currently when vic-machine-server panics during an vic-machine API call, the http request to the API returns nothing:
``` 
curl: (52) Empty reply from server
```
And the panic and stack trace are printed in server stderr.
But when examining the vic-machine-server log file under `/var/log/vic-machine-server` on server machine, the panic message is not logged in the file.

**Acceptance Criteria:**
- [ ] Add a middleware to vic-machine API to log panics to vic-machine-server log file

**Useful Reference**

Go HTTP middleware that catches panics and serves proper error message: https://github.com/dre1080/recover
go-swagger panic handling middleware: https://github.com/go-swagger/go-swagger/blob/master/docs/use/middleware.md#add-logging-and-panic-handling

**Comment by zjs** [comment]
We must log panics which occur during the handling of a request to the vic-machine-server log file.

We should minimize the size and scope of this fix for 1.3.0. If the correct fix is large, complex, or risky,  we should do something simpler and make a complete fix on master as high priority post-1.3 work.

If post-1.3 work is necessary, an issue referencing this one should be opened to track that work.
