### ISSUE TITLE
VCH Deletion API fails when the version of a VCH is different than the version of the API server

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6862]
**VIC version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Steps to reproduce:**

Deploy a VCH using an old version of the CLI or API. Attempt to delete it through the API.

**Actual behavior:**

The deletion fails with a 400 Bad Request:
```json
{
  "message": "VCH version \"-0-\" is different than API version v1.2.0-rc1-15115-18841ed"
}
```

**Expected behavior:**

Deletion succeeds.

**Additional details as necessary:**

vmware/vic-ui#128 makes this much worse.

**Comment by andrewtchin** [comment]
release note, not ship stop

**Comment by zjs** [comment]
This will not be fixed for 1.3.0, but should be release noted. We should treat this as a high-priority post-1.3 fix.

@stuclem: A release note for this should explain that only VCHs created using 1.3 (via the UI or CLI) can be deleted via the UI. All other VCHs will need to be deleted using the CLI.

**Comment by stuclem** [comment]
Created https://github.com/vmware/vic-product/issues/1193 for the doc update. Removing kind/note.

**Comment by stuclem** [comment]
I just tested this with a VCH created with an older 1.3 build than the build of the OVA/plugin. Delete failed as expected. I then upgraded the VCH with the VIC engine bundle downloaded from new OVA, and delete still failed, even though the VCH should now be at the same version as the OVA. Not sure that this is expected, but thought it worth mentioning.
