### ISSUE TITLE
VCH Management UI doesn't allow picking "VM Network"

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6873]
As a VIC developer, I am accustom to using vic-machine CLI.  When using the CLI, I've never specify public network.  By default, the CLI appears to automatically chose VM Network.

The Management UI creation wizard requires choosing a public network but does not list VM Network.  I am not sure if this intentional.

**Comment by zjs** [comment]
Closing as a duplicate of vmware/vic-ui#124.

See also: https://vmware.slack.com/archives/C6VGCAJ73/p1511998622000416
