### ISSUE TITLE
Instructions to install the VIC plugin should be ready for copy/paste

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#6880]
**VIC version:**
vic-v1.3.0-rc2-2628-9e2a95b6.ova
**Deployment details:**
Nimbus deployment, no VCH
**Steps to reproduce:**
Follow instructions to install the plugin
**Actual behavior:**
The docs specify a set of bash commands that have italics to represent customizable parts (e.g. the OVA IP address). This is problematic as a user cannot simply copy and paste and it is error prone. 
**Expected behavior:**
Since these are all bash command it would be a lot better to have something like this:

_export OVA_IP_ADDRES=<IP_ADDRESS>_
_export VIC_VERSION=<VIC_VERSION>_

and then:

_curl -kL  http://${OVA_IP_ADDRESS}:9443/files/${VIC_VERSION}.tar.gz -o ${VIC_VERSION}.tar.gz_

**Comment by mdubya66** [comment]
Issue moved to [vmware/vic-product #1194](https://github.com/vmware/vic-product/issues/1194) via [**ZenHub**](https://www.zenhub.com/)
