### ISSUE TITLE
Directory permissions for volume mounts

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6881]
**Story**
As a VCH user I expect to be able to use volumes as a non-root user without issue

**Details**
We currently have the following behavioural deviations:
1. `MkdirAll("/volume/mount/point")` should be creating any missing directories with `0755` instead of `0644`
2. The permissions of the mount point should be preserved once the volume is mounted. Currently if we have `/mnt/vol` with `0775` then it gets changed to `0755` when the volume is mounted.

I'm unclear on the exact semantics of (2) with regular docker - it looks like `chown/chmod` are used every time the volume is mounted (even if in use else where) and the permissions are updated in some conditional fashion.

Sample - vo6 is a new volume. `voltest` is from the following Dockerfile:
```
FROM busybox
RUN mkdir -p /volumes/user && chmod 775 /volumes/user && chown 2001 /volumes/user
```
result:
```
vagrant@devbox:/tmp/tmp$ docker run  -v vo6:/volumes/user -it busybox
/ # ls -l /volumes
total 4
drwxr-xr-x    2 root     root          4096 Nov 30 19:04 user
/ # vagrant@devbox:/tmp/tmp$ #detached
vagrant@devbox:/tmp/tmp$ docker run  -v vo6:/volumes/user -it voltest
/ # ls -l /volumes
total 4
drwxrwxr-x    2 2001     root          4096 Nov 30 19:04 user
/ # exit
vagrant@devbox:/tmp/tmp$ docker ps
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS              PORTS                    NAMES
24a67b033af1        busybox                                                 "sh"                     32 seconds ago      Up 31 seconds                                gracious_mestorf
vagrant@devbox:/tmp/tmp$ docker attach gracious_mestorf
/ # ls -l /volumes
total 4
drwxrwxr-x    2 2001     root          4096 Nov 30 19:04 user
/ #
```
as can be see the owner of the volume was changed to `2001` for all containers, however it's not reset to `root` when using `docker run  -v vo6:/volumes/user -it busybox` after the above.

The necessary code changes are likely simple, but we need to confirm the appropriate conditional syntax for applying permissions a user/group ownership.

**Comment by mlh78750** [comment]
This is the way NFS shares work. If you change uid/gid on a NFS share it persist. I am not sure this is a bug. What would you expect to happen? And this has customer found, was this affecting a deployment? How does it manifest itself as a problem to the user?

**Comment by mdubya66** [comment]
Adding to 1.3 for triage

**Comment by hickeng** [comment]
@mlh78750 This _has been found_ by a customer during blackduck use.

There are two problems with VCH in this context:
1. mount paths that do not exist are created with excessively strict permissions (should be 755).
2. VCH does *not* use the permissions of the mount target directory - you currently get the permissions from the _mounted_ filesystem. This means there's no way for a container with non-root user to be sure they can access anything on a volume. It _should_ be possible to set the permissions on the VOLUME target directory in the Dockerfile to ensure at least access to the top level of the mounted filesystem.

**Comment by mlh78750** [comment]
I think this userID mapping issue for shared volumes is pretty well understood and docker-engine has the same issues. There is a patchset against the kernel to add support for mapping in the kernel namespace to avoid this type of problem, but it's going to get complicated pretty quick in production. This is why I think the use of shared volumes has always been limited in docker.

**Comment by mhagen-vmware** [comment]
Deferred after discussion with @mlh78750

**Comment by vburenin** [comment]
The permission for the mounted volume are taken from the volume itself. 
If the volume permissions are set to 777, they will be used. So, let say if I create a volume "test1", by default root permissions are 755. Inside a container I can set them to 777. Then stop the container, create a new container from the same image pointing to the same image, mounted permission will be 777.

Docker behavior is the same. Checked on Docker version 17.09.0-ce.

**Comment by vburenin** [comment]
I am putting this issue on hold second part of this issue. Mount process semantics are inline with typical mount procedure expectations, if there are changes needed to give an access to non root users
The first part in regard of directory permissions still needs to be addressed.

**Comment by stuclem** [comment]
@mlh78750 do we need to include this in the release notes?

**Comment by mlh78750** [comment]
@stuclem I don't think so.

**Comment by sflxn** [comment]
I just tried this myself to see if I can understand this issue.

**vanilla docker**
```
loc@devbox:~/tests/vol-perm$ docker run -v vol8:/volumes/user -it busybox
/ # ls -l /volumes/
total 4
drwxr-xr-x    2 root     root          4096 Jan  9 23:58 user
/ # exit
loc@devbox:~/tests/vol-perm$ docker run -v vol8:/volumes/user -it voltest
/ # ls -l /volumes/
total 4
drwxrwxr-x    2 2001     root          4096 Jan  9 23:58 user
/ # exit
loc@devbox:~/tests/vol-perm$ docker run -v vol8:/volumes/user -it busybox
/ # ls -l /volumes/
total 4
drwxrwxr-x    2 2001     root          4096 Jan  9 23:58 user
/ # exit 
```

**vic**
```
loc@devbox:~/go/src/github.com/vmware/vic$ docker -H 192.168.218.134:2375 run -v vo9:/volumes/user -it busybox
/ # ls -l /volumes/
total 4
drwxr-xr-x    2 root     root          4096 Jan  9 23:57 user
/ # exit
loc@devbox:~/go/src/github.com/vmware/vic$ docker -H 192.168.218.134:2375 run -v vo9:/volumes/user -it victest/voltest
/ # ls -l /volumes
total 4
drwxr-xr-x    2 2001     root          4096 Jan  9 23:57 user
/ # exit
loc@devbox:~/go/src/github.com/vmware/vic$ docker -H 192.168.218.134:2375 run -v vo9:/volumes/user -it busybox
/ # ls -l /volumes/
total 4
drwxr-xr-x    2 2001     root          4096 Jan  9 23:57 user
/ # exit
```

**Comment by vburenin** [comment]
oh, there is a big difference in that. If you use actual volume, not a local directory it sets permissions according of the target mount point. If I use a local file system directory as a volume source it uses source permissions. Interesting.

**Comment by sflxn** [comment]
To support what @vburenin is saying, here is a run with vanilla docker.  With locally mapped folders, it doesn't use the permissions or uid from the dockerfile.  It's just an interesting note.  It doesn't affect our issue with volumes.

```
loc@devbox:~/tests/vol-perm$ docker run -v /home/loc/tests:/volumes/user -it voltest
/ # ls -l /volumes/
total 4
drwxrwxr-x    3 1000     1000          4096 Jan  9 22:59 user
/ # exit
```

**Comment by stuclem** [comment]
Thanks @mlh78750. Removing kind/note.

**Comment by vburenin** [comment]
VIC also ignores RO permission that can be set for the volume.

**VIC**

```
vmware/vic [volume-mount-permission-fix●] » docker run -ti -v tt1:/test/test/test:ro busybox
/ # mount | grep test
/dev/disk/by-label/2e4277d05272b6ed on /test/test/test type ext4 (rw,noatime,data=ordered)
/ # cd /test/test/test/
/test/test/test # touch testfile
/test/test/test # ls -la
total 8
drwx------    2 root     root          4096 Jan 10 16:31 .
drwxr-xr-x    3 root     root          4096 Jan 10 16:30 ..
-rw-rw-rw-    1 root     root             0 Jan 10 16:00 testdata
-rw-rw-rw-    1 root     root             0 Jan 10 16:31 testfile
-rw-rw-rw-    1 root     root             0 Jan 10 16:29 ttt
#
```
**vanilla**
```
~ » docker run -ti -v vv:/test/test:ro busybox
/ # cd /test/
/test # ls -la
total 12
drwxr-xr-x    3 root     root          4096 Jan 10 16:25 .
drwxr-xr-x   20 root     root          4096 Jan 10 16:25 ..
drwxr-xr-x    2 root     root          4096 Jan 10 16:25 test
/test # cd test/
/test/test # ls -la
total 8
drwxr-xr-x    2 root     root          4096 Jan 10 16:25 .
drwxr-xr-x    3 root     root          4096 Jan 10 16:25 ..
/test/test # touch tt
touch: tt: Read-only file system
```

**Comment by mlh78750** [comment]
@vburenin Do you think we should create new issues for each of these? and create and epic to track? or just convert this issue to cover all of the issues? 

We need to put some tests in place to prevent regressions when we correct this as well.

**Comment by hickeng** [comment]
@vburenin has opened #7064 and #5303 has been open for a while. Additionally we have #4174 which is for the root filesystem but basically the same function.

My preference is for an overarching epic relating to volumes which should encompass detail work, including stub entries for future work:
* NFSv4
* CIFS
* Non-persistent shared volumes
* VVOL

. This will help keep issues organised as an orthogonal mechanism to the storage component label which primarily gets used for the low level items.
