### ISSUE TITLE
Port Layer: container stop

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#689]
Add Stop to the exec interface
Add Stop to the swagger spec
Minimal implementation of interface that powers of VM with no attempt at clean shutdown

**Comment by sflxn** [comment]
This has been added by @matthewavery when he added stop to the api server.

**Comment by matthewavery** [comment]
Important to note that the minimal solution has been implemented and more work will need to be done moving forward.

**Comment by mdubya66** [comment]
it functions, it's just very impolite
