### ISSUE TITLE
Fully automate UI plugin install by moving functionality into the fileserver

### ISSUE THREAD

**Issue by jzt** [vmware/vic#6890]
**User Statement:**

As a VIC user, I would like the UI plugin install process to be fully automated.

**Details:**

The current method of installing the vic UI plugins requires the following (assuming the OVA has already been deployed to VC):

- The user browses to the OVA's Getting Started page, enters the VC host & admin credentials, and then the Getting Started process kicks off (register with PSC, start Harbor/Admiral containers and any other dependencies).
- The user downloads the VIC Engine artifact after the "Getting Started" step is complete.
- The user extracts the archive, and runs the `install.sh` script.
- The script prompts for the VC host/IP, admin credentials, and finally asks the user to verify the thumbprint of the VC.
- If everything checks out, the UI plugins are installed and the OVA's `ManagedByInfo` is configured so that the OVA can be managed by the VIC UI plugin.

Ideally, at Getting Started time, all the necessary information is known in order to fully automate this process. We could remove the step requiring user intervention by changing the flow:

- The user browses to the Getting Started page, and enters the VC host & admin credentials.
- At this point, the VC thumbprint is acquired and presented to the user for verification. Once the thumbprint is verified, the Getting Started process kicks off (register with PSC, start Harbor/Admiral containers and any other dependencies). 
- At this point, all the necessary information is currently known: the admin credentials, the VC host, the OVA appliance IP, and the (verified) VC thumbprint.
- The fileserver can use this information to install the UI plugins to VC as well as configure the `ManagedByInfo` of the OVA without the need for user intervention.

**Acceptance Criteria:**
- [ ] fileserver is updated to automatically fetch and present the VC thumbprint for user verification
- [ ] Code currently specific to github.com/vmware/vic/cmd/vic-ui is refactored into a shared `lib` directory and included in the fileserver so that the fileserver can install the plugin without calling out to a binary
- [ ] Documentation updated to remove extraneous step that is no longer necessary
- [ ] A button added to the Getting Started page to trigger re-installation of the UI plugins

**Comment by lweitzman** [comment]
the user workflow that illustrates the submission of the vcenter credentials and confirmation of the thumbprint can be viewed by clicking on the Application Initialization on the first card from here https://vmware.invisionapp.com/share/VBDLQ5QYQ#/254613570_Project_TOC

**Comment by andrewtchin** [comment]
Closing as tracked in https://github.com/vmware/vic-product/issues/1432
