### ISSUE TITLE
Fix archive unpack symlink handling - docker cp (online)

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6895]
like #6863 but online copy
given the following scenario

running container -> shared volume A
stopped container -> shared volume A

run docker cp against the _stopped_ container which shares a volume with the running container using the same kind of symlink in the archive as in #6863 and observe that the file gets copied to the _running_ container

**Comment by anchal-agrawal** [comment]
Not sure if this should be high or medium priority. Moving to Not Ready for now and adding assignees.
