### ISSUE TITLE
Investigate the behavior changed by using the force flag during VCH upgrade and rollback and design a granular alternative to the flag for the API

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6896]
From #6900:
> Additionally, the `--force` flag may be used to cause the CLI to skip version checks. As with other aspects of the API, we should avoid a "blanket" equivalent to the `--force` flag and implement fine-grained functionality if necessary (i.e., something to just skip the version check). As with other aspects of the CLI, `--force` may have hidden functionality; if so, we may wish to support that as well.

**Comment by andrewtchin** [comment]
decide if we should update CLI or only expose granular changes through API after this investigation

**Comment by zjs** [comment]
Force is currently used in two ways during `vic-machine upgrade`.

https://github.com/vmware/vic/blob/e934d68568dc54755305dbad65ee3d30e4f37e84/cmd/vic-machine/upgrade/upgrade.go#L116

Here, the value is passed into the code which checks that the checks the supplied image's version. This is the documented use of the flag; when it is not set, the upgrade can fail with an error that the ISO file has a version which does not match the `vic-machine` version.

In the API, this could eventually be better captured as an argument to explicitly skip the version check. However, the ISO is currently bundled with the `vic-machine-server`, so it's not clear what the use case for this flag would be (currently).

https://github.com/vmware/vic/blob/e934d68568dc54755305dbad65ee3d30e4f37e84/cmd/vic-machine/upgrade/upgrade.go#L134

Here, the value is passed into the session-management code. This ignores VC certificate validation issues. This behavior is not relevant for the API.
