### ISSUE TITLE
Integration test failed randomly

### ISSUE THREAD

**Issue by emlin** [vmware/vic#690]
Integration test failed randomly for docker daemon is not connectable. 

Here is the failure message:
20:25:56 ok 17 vic-machine image-store is missing
20:27:03 not ok 18 vic-machine deployment and docker commands
20:27:03 # (from function `assert_success' in file ./helpers/bats-assert/src/assert.bash, line 114,
20:27:03 #  in test file ./vic-machine.bats, line 128)
20:27:03 #   `assert_success' failed
20:27:03 # /go/src/github.com/vmware/vic/tests/../bin/vic-machine -target 10.17.109.150 -name VCH-2704 -user root -compute-resource /ha-datacenter/host/localhost.eng.vmware.com/Resources -image-store datastore
20:27:03 # INFO[2016-05-16T20:26:28Z] docker -H 10.17.109.72:2376 --tls --tlscert='./VCH-2704-cert.pem' --tlskey='./VCH-2704-key.pem' info
20:27:03 # INFO[2016-05-16T20:26:28Z] Installer completed successfully...
20:27:03 # docker_cmd= -H 10.17.109.72:2376 --tls --tlscert='./VCH-2704-cert.pem' --tlskey='./VCH-2704-key.pem'
20:27:03 # Containers: 0
20:27:03 # /go/src/github.com/vmware/vic/tests/../bin/vic-machine -target 10.17.109.150 -name VCH-2704 -user root -compute-resource /ha-datacenter/host/localhost.eng.vmware.com/Resources -image-store datastore -force -key ./VCH-2704-key.pem -cert ./VCH-2704-cert.pem
20:27:03 # INFO[2016-05-16T20:27:01Z] Installer completed successfully...
20:27:03 # 
20:27:03 # -- command failed --
20:27:03 # status : 1
20:27:03 # output : Cannot connect to the Docker daemon. Is the docker daemon running on this host?
20:27:03 # --
20:27:03 # 
20:27:03 # Clear VCH deployments if exists
20:27:03 Makefile:178: recipe for target 'integration-tests' failed
20:27:03 make: *** [integration-tests] Error 1
20:27:03 Build step 'Execute shell' marked build as failure
20:27:03 Sending e-mails to: mwilliamson-staff-adl@vmware.com
20:27:04 Finished: FAILURE

I fails without any code change after a successful test. Might because the sleeping time is fixed in 5 seconds.
Doug is working on #683, let's see if it still fail after that.

**Comment by mdubya66** [comment]
BATS issue. Closing.
