### ISSUE TITLE
Nightly 6.5 5-22-NFS-Volume - Docker Inspect Mount Data after Reboot

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#6909]
I'm not sure what's going on here, but docker info failed.
```
docker -H 10.161.243.113:2376 --tls info 2>&1
${rc} = 1
```
vSphere v6.5 - VIC Build 15175.tar.gz
https://storage.cloud.google.com/vic-ci-logs/functional_logs_12_01_12_03_vic_15175.tar.gz.zip?authuser=1

**Comment by mhagen-vmware** [comment]
this is potentially fixed with this PR:
https://github.com/vmware/vic/pull/6891

**Comment by andrewtchin** [comment]
i hope so

**Comment by hickeng** [comment]
closing this as no reports of it in the last month
