### ISSUE TITLE
Nightly 6.0 5-4-High-Availability - Wait For VCH Initialization

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#6912]
Looks like during the HA test we're supposed to wait for the VCH to come back up but that doesn't happen so we skip the rest of the test steps here.

Seen on vSphere v6.0 - VIC Build 15175
https://storage.cloud.google.com/vic-ci-logs/functional_logs_12_01_12_03_vic_15175.tar.gz.zip?authuser=1
[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1528799/5-4-High-Availability.zip)

**Comment by cgtexmex** [comment]
The VCH eventually initialized (as demonstrated by the execution of the regression tests), but not in a time frame that was acceptable to the test.  

The HA event reduced the cluster size by 33% and the host the VCH was migrated to became unresponsive.  Once the host connectivity issues resolved (thank you vSphere) the VCH was operational.

I believe this is the only example of such a failure, so I'm closing this issue w/o any changes to the test.
