### ISSUE TITLE
Implement container migration from vApp -> resource pool on upgrade

### ISSUE THREAD

**Issue by jzt** [vmware/vic#6914]
**User Statement:**

As a VIC user, when I upgrade from 1.2.1 to 1.3, I would like containers running in a vApp that were 
 created in VIC v1.2.1 to be migrated to the resource pool used by v1.3.

**Details:**

Currently, when upgrading from VIC 1.2.1 (vApp) to 1.3, the resulting 1.3 VCH exhibits the following traits:
- No resource pool is created for the new VCH
- The original vApp sticks around, and all running containers remain in said vApp
- Newly-created containers in 1.3 are deployed into the existing vApp that was created in 1.2.1

Expected behavior:
- A resource pool is created during the upgrade from 1.2.1 to 1.3 (iff VIC 1.2.1 was deployed in a vApp, otherwise the existing resource pool is reused)
- Containers running in the 1.2.1 vApp are moved into the resource pool
- The vApp created in 1.2.1 is deleted
- The compute resource persisted in the VCH configuration is changed from the vApp to the newly created resource pool (iff VIC 1.2.1 was deployed in a vApp, otherwise NOP)

**Acceptance Criteria:**

- [ ] `vic-machine upgrade` updated to move running vApp containers into a newly-created resource pool
- [ ] `vic-machine upgrade` updated to delete old vApp once containers are moved over
- [ ] `vic-machine upgrade` updated to reconfigure the VCH compute resource to point to the resource pool instead of the (now deleted) vApp
- [ ] integration tests (both updated and added) to exercise this flow

**Comment by hickeng** [comment]
I'm unclear why this occurs - the image store path should remain the same and given we're not recreating the VM the UUID should also remain constant. To my knowledge, you will only get the `_X` prefix if creating a new VM - simply creating a folder would give you `ErrExists`.

Please can you confirm why we end up down the path of creating a new image store:
* A new image store directory is created, named in the form <VCH name>_1
* The image store and all image data pulled in 1.2.1 remain, resulting in orphaned image data unused by 1.3 (any container deploy in 1.3 using an image that was pulled with 1.2.1 will result in a new image pull and duplicate image data)

**Comment by jzt** [comment]
@hickeng Removing this behavior from the description as I'm unable to reproduce. I'm puzzled as to how I saw this behavior when testing for what to capture in this issue.

**Comment by andrewtchin** [comment]
I talked with @pdaigle and @yeshwantbabar and we are good with documenting a migration process. Closing this.
https://github.com/vmware/vic-product/issues/1523
