### ISSUE TITLE
VC name may not work for --target in VCH wizard

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#6918]
@lcastellano commented on [Mon Dec 04 2017](https://github.com/vmware/vic-ui/issues/181)

**VIC version:**
vic 1.3 rc2

**Deployment details:**
Name of VC is: localhost.localdom.eng.vmware.com (not a valid DNS name)

**Steps to reproduce:**
Use the wizard to create the VCH

**Actual behavior:**
The VCH creation fails with: 
_Error creating VCH_ 

**Expected behavior:**
VCH should succeed then wizard should be able to use the IP address of VC as target.

**Comment by zjs** [comment]
I'm unable to reproduce this issue with a _valid_ FQDN.
