### ISSUE TITLE
Research and Enumerate multi container VMs (wolfpack) approaches

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6920]
This is a research oriented epic to investigate and design a method for VIC to create a multi-container VM.  The result of this epic should be a document showing the various approaches.  The following will need to be addressed.

1. Interface for communicating to outside world and other callers
2. Bind mount handling (include info on how certain operations such as docker cp will be handled)
3. External volume handling
4. Network attachments
5. Explain how the interoperability with the VIC persona/portlayer for docker command access
6. Logs
7. Healthcheck

**Comment by anchal-agrawal** [comment]
@sflxn mentioned above that this should be an epic. We should tag it as so and remove the estimate, as the estimate total will come from the sub-issues in this epic. Epics shouldn't be in a milestone either.

**Comment by sgairo** [comment]
How is the progress on this being broken down into actionable, trackable, issues?
