### ISSUE TITLE
Discrepancy between ps and inspect command when the container is run with a sleep command

### ISSUE THREAD

**Issue by AntonioFilipov** [vmware/vic#6921]
#For bug reports, please include the information below:

**VIC version:**

Build: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc2-2628-9e2a95b6.ova

**Steps to reproduce:**

Provision a container (photon in my case) with a sleep command (`sleep 45m`)
**Actual behavior:**

The container does not exit. The `ps` command shows that it is UP, whereas the `inspect` command shows that it is exited.
[ps.txt](https://github.com/vmware/vic/files/1535314/ps.txt)
[inspect.txt](https://github.com/vmware/vic/files/1535316/inspect.txt)

**Expected behavior:**

After that time, the container should exit. 

cc: @lgayatri could you provide more info of the setup, if needed. Thanks.

**Comment by lgayatri** [comment]
Please refer to https://github.com/vmware/admiral/issues/231 for the complete detail. I have live access as of now.

**Comment by anchal-agrawal** [comment]
@lgayatri Are there logs from when this issue was seen? The setup mentioned in vmware/admiral#231 doesn't have the two containers that showed up as running in `ps` output. I checked the log bundle as well, no dice.

**Comment by lgayatri** [comment]
@anchal-agrawal , Yesterday early morning RC3 build was ready so I picked it up on this test bed. Hence you do not see the old inventory any more.
The log set from RC2 OVA is > 10MB hence cannot attach here, sent you as PM.

**Comment by sgairo** [comment]
@anchal-agrawal would you mind giving this issue an estimate please?

**Comment by anchal-agrawal** [comment]
Re https://github.com/vmware/vic/issues/6921#issuecomment-350422340: the log bundle didn't have VIC engine logs. Judging by the nature of the issue, it _could_ be related to https://github.com/vmware/vic/issues/6823 and https://github.com/vmware/vic/issues/6342. I can't estimate or triage this issue further without logs, so I propose we close this issue and re-open with logs if seen again. @AntonioFilipov do you still have the logs for this issue, by any chance? Thanks.
