### ISSUE TITLE
Test cross network routing in container

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#693]
We need to confirm that visibility and reachability are as expected when a container is attached to multiple networks. This requires at least three scenarios:

1. two containers on the same network scope, each with multiple networks, can talk directly with one another.
2. two containers on different network scopes cannot talk directly, despite knowledge of one another's IPs.
3. a combination of the first two scenarios where a containerVM acts as a bridge between two others - this is the essence of the multiple tier app model.

**Comment by hmahmood** [comment]
(1.) and (2.) already work. Not sure about (3.). What use case are we solving with that one? The one I had in mind was port-forwarding through the VCH.

**Comment by hickeng** [comment]
This should just be validation at this point.

**Comment by corrieb** [comment]
@mhagen-vmware I'd definitely like to have this in for onsite, given the required focus we need to have on quality.
