### ISSUE TITLE
5-2-Cluster: nightly test fails on docker start with portlayer commit handler context deadline exceeded

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6936]
VC 6.5, nightly 12/07/17, 5-2-Cluster, Docker regression test, command docker start

nightly log:
`Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.161.35.105/sdk: context deadline exceeded`

port-layer.log, two `context deadline exceeded`, one in `WaitForSession`, another in `CommitHandler error`:
```
Dec  7 2017 02:36:48.436Z DEBUG vSphere Event Warning message on heuristic_panini-84d6463bee9c on 10.162.9.49 in ha-datacenter: Virtual device 'ide0:0' will start disconnected.
 for eventID(659) ignored by the event collector
.......
Dec  7 2017 02:37:49.406Z DEBUG vSphere Event Alarm 'Virtual machine memory usage' on heuristic_panini-84d6463bee9c changed from Gray to Green for eventID(670) ignored by the event collector
Dec  7 2017 02:39:48.217Z ERROR op=303.27: vic/pkg/trace.(*Operation).Err: WaitForSession error: context deadline exceeded
vic/lib/portlayer/exec.(*Container).start:423 WaitForSession
vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:218 commit handle(f077a7a329196354c00e4b52cf832051)
Dec  7 2017 02:39:48.232Z DEBUG [ END ] op=303.27 [vic/lib/portlayer/exec.(*containerBase).waitForSession:404] [3m0.007319661s] 84d6463bee9cec5abb677a351ae507099eedf66e8e9e3f77df3ae126f4541111
Dec  7 2017 02:39:48.232Z DEBUG [ END ] op=303.27 [vic/lib/portlayer/exec.(*Container).start:396] [3m1.471909927s] 84d6463bee9cec5abb677a351ae507099eedf66e8e9e3f77df3ae126f4541111
Dec  7 2017 02:39:48.232Z DEBUG op=303.27: Update: updated change version from handle: 2017-12-07T02:36:45.677169Z
Dec  7 2017 02:39:48.232Z DEBUG [ END ] op=303.27 [vic/lib/portlayer/exec.Commit:34] [3m1.880346696s] 84d6463bee9cec5abb677a351ae507099eedf66e8e9e3f77df3ae126f4541111
Dec  7 2017 02:39:48.232Z ERROR op=303.27: CommitHandler error on handle(f077a7a329196354c00e4b52cf832051) for 84d6463bee9cec5abb677a351ae507099eedf66e8e9e3f77df3ae126f4541111: unable to wait for process launch status: Post https://10.161.35.105/sdk: context deadline exceeded
```

hostd log:
```
2017-12-07T02:34:36.673Z warning hostd[F681B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5a28a368-3773f114-08a9-020020c7a0e6/VCH-0-7631/VCH-0-7631.vmx opID=2285.1-62-01-e6-d932 user=vpxuser:VSPHERE.LOCAL\Administrator] CannotRetrieveCorefiles: VM is in an invalid state
...
2017-12-07T02:34:36.694Z warning hostd[F681B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5a28a368-3773f114-08a9-020020c7a0e6/VCH-0-7631/VCH-0-7631.vmx opID=2285.1-62-01-e6-d932 user=vpxuser:VSPHERE.LOCAL\Administrator] File - failed to get objectId, '/vmfs/volumes/5a28a368-3773f114-08a9-020020c7a0e6/VCH-0-7631/VCH-0-7631.vmx': One of the parameters supplied is invalid.
```
The `VM is in an invalid state` is present in hostd log file for successful test cases as well. But the `one of the parameters supplied is invalid` only presents in hostd log file for test cases failed with `portlayer context deadline exceeded` (afaik)

Log bundle:
[5-2-Cluster.zip](https://github.com/vmware/vic/files/1543924/5-2-Cluster.zip)

**Comment by AngieCris** [comment]
Seen again in nightly 12/07/17, 13-1-vMotion-VCH-Appliance, docker start gives: 
`Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.192.83.44/sdk: context deadline exceeded`

port-layer.log looks pretty much the same:
```
Dec  7 2017 15:48:33.543Z ERROR op=296.29: vic/pkg/trace.(*Operation).Err: WaitForSession error: context deadline exceeded
vic/lib/portlayer/exec.(*Container).start:423 WaitForSession
vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:218 commit handle(de911113ad687298dfc31cf52bb5260a)
Dec  7 2017 15:48:33.554Z DEBUG [ END ] op=296.29 [vic/lib/portlayer/exec.(*containerBase).waitForSession:404] [3m0.011024563s] 8f301cb5c8cef042d92d6d254082c84c46ee597d4238db4e6d541e95e5025973
Dec  7 2017 15:48:33.554Z DEBUG [ END ] op=296.29 [vic/lib/portlayer/exec.(*Container).start:396] [3m5.68515747s] 8f301cb5c8cef042d92d6d254082c84c46ee597d4238db4e6d541e95e5025973
Dec  7 2017 15:48:33.554Z DEBUG op=296.29: Update: updated change version from handle: 2017-12-07T15:45:26.81288Z
Dec  7 2017 15:48:33.554Z DEBUG [ END ] op=296.29 [vic/lib/portlayer/exec.Commit:34] [3m6.302139567s] 8f301cb5c8cef042d92d6d254082c84c46ee597d4238db4e6d541e95e5025973
Dec  7 2017 15:48:33.554Z ERROR op=296.29: CommitHandler error on handle(de911113ad687298dfc31cf52bb5260a) for 8f301cb5c8cef042d92d6d254082c84c46ee597d4238db4e6d541e95e5025973: unable to wait for process launch status: Post https://10.192.83.44/sdk: context deadline exceeded
```

hostd debug does not contain `one of the arguments supplied is invalid` error like last time, but it includes:
```
2017-12-07T14:58:29.041Z info hostd[800E890] [Originator@6876 sub=OsfsClient opID=14694.1-ad-49-dc34 user=vpxuser:VSPHERE.LOCAL\Administrator] Delete VMDKs in /vmfs/volumes/vsan:52baf88292af6683-f3e07bbb69b6b367/3956295a-b6cd-970c-7ca6-02002c9c802e/a79b9cf019c8222fc4ffc84eea6168642d73d207ba395259f228e708f4d36f50.vmdk
2017-12-07T14:58:29.041Z error hostd[800E890] [Originator@6876 sub=OsfsClient opID=14694.1-ad-49-dc34 user=vpxuser:VSPHERE.LOCAL\Administrator] Object search failed: N7Vmacore24InvalidArgumentExceptionE(Invalid argument)
```

Log bundles:
[13-1-vMotion-VCH-Appliance.zip](https://github.com/vmware/vic/files/1544004/13-1-vMotion-VCH-Appliance.zip)

**Comment by AngieCris** [comment]
this might be related: https://github.com/vmware/vic/issues/6352
Same failure message

**Comment by matthewavery** [comment]
I am noting that all of the log files for the container mentioned originally are empty as well. Which means we were never able to write to the serial port.

**Comment by matthewavery** [comment]
additional analysis of hostd shows evidence of VMX corruption/inconsistency... see the following. 

`2017-12-07T02:36:45.544Z error hostd[A2C1B70] [Originator@6876 sub=Default opID=303.25-21-01-8d-da85 user=vpxuser:VSPHERE.LOCAL\Administrator] An error occurred while loading configuration "/vmfs/volumes/5a28a368-3773f114-08a9-020020c7a0e6/84d6463bee9cec5abb677a351ae507099eedf66e8e9e3f77df3ae126f4541111/84d6463bee9cec5abb677a351ae507099eedf66e8e9e3f77df3ae126f4541111.vmsd",not all entries are being read. It is strongly encouraged that you manually inspect the file and fix any corruptions.`

**Comment by AngieCris** [comment]
Seen again in nightly 12/15/17 group 5-8 DRS.
![image](https://user-images.githubusercontent.com/6562128/34076675-e0572974-e2b3-11e7-8dd0-a2596448321c.png)

Log: [5-8-DRS.zip](https://github.com/vmware/vic/files/1565327/5-8-DRS.zip)

**Comment by anchal-agrawal** [comment]
Backlog items must have a priority.

**Comment by AngieCris** [comment]
Seen again on 12/26/17 nightly, test 5-22-NFS-Volume
In step `Docker Read and Remove File`, portlayer CDE
![image](https://user-images.githubusercontent.com/6562128/34415758-06f431a2-ebb6-11e7-8870-260b6f2b5452.png)
[5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1591551/5-22-NFS-Volume.zip)

**Comment by AngieCris** [comment]
Seen again in VC 6.5, nightly 12/28/17, 5-11-Multiple-Cluster, Regression test:

```
Running command 'docker -H 10.192.178.70:2376 --tls start 3461426ec3bb770bab8bfc339652405ff686e559f7982a2e12140384163f2a7d 2>&1'.
${output} = Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.162.51.19/sdk: context deadline exceeded
Error: failed to start containers: 3461426ec...
```

[5-11-Multiple-Cluster.zip](https://github.com/vmware/vic/files/1596532/5-11-Multiple-Cluster.zip)

**Comment by anchal-agrawal** [comment]
Also seen in this instance: https://github.com/vmware/vic/issues/6910#issuecomment-353899223

**Comment by AngieCris** [comment]
Seen again on nightly 02/22/18
VC version: 6.5
Test suite: 5-22-NFS-Volume

Before VCH reboot, running docker command:
```
docker -H 10.192.226.17:2376 --tls run -v nfs-volume_VCH-0-6907:/mydata busybox sh -c "cat mydata/test_nfs_file.txt
```
failed with error:
```
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.192.225.68/sdk: context deadline exceeded
```

PL log shows attach connector context deadline exceeded:
```
Feb 23 2018 09:31:06.910Z INFO  op=285.168: Reconfigure: attempting update to 44ea7b671341a536c0f35411c9ef59791fe2d48c6069264da7815553ede04737 with change version "2018-02-23T09:31:06.619273Z" (poweredOff)
Feb 23 2018 09:31:07.227Z ERROR attach connector: Connection not found error for id:c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a: context deadline exceeded
Feb 23 2018 09:31:07.227Z DEBUG [ END ]  [vic/lib/portlayer/attach/communication.(*Connector).interaction:133] [50.060733252s] c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a
Feb 23 2018 09:31:07.227Z DEBUG [ END ]  [vic/lib/portlayer/attach/communication.(*Connector).Interaction:116] [50.060751437s] c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a
Feb 23 2018 09:31:07.227Z DEBUG [ END ]  [vic/lib/portlayer/attach/communication.(*Server).Interaction:104] [50.060763289s] c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a
Feb 23 2018 09:31:07.227Z ERROR attach connector: Connection not found error for id:c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a: context deadline exceeded
Feb 23 2018 09:31:07.227Z DEBUG [ END ]  [vic/lib/apiservers/portlayer/restapi/handlers.(*InteractionHandlersImpl).ContainerCloseStdinHandler:228] [50.060785991s] c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a
Feb 23 2018 09:31:07.228Z DEBUG attach connector:  Giving up on connection for c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a
```

Some time before attach connector CDE showed up in PL log, tether debug for the VCH before reboot shows container attach `CloseStdin` CDE:
```
Feb 23 2018 09:30:17.791Z DEBUG * stdout attach end Fri Feb 23 09:30:17 UTC 2018
Feb 23 2018 09:30:17.791Z INFO  container attach: stdout (c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a) done
Feb 23 2018 09:30:17.791Z INFO  container attach: stderr (c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a) done
Feb 23 2018 09:30:17.791Z ERROR CloseStdin failed with context canceled
Feb 23 2018 09:30:17.791Z INFO  container attach: stdin (c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a) done
Feb 23 2018 09:30:17.791Z INFO  cleaned up connections to c7bec9a03d239306302e23c2e25e3452926b1e19db11327f0225861e75a8af1a. Checking errors
```

container logs before reboot:
[Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-6907-container-logs-before-reboot.zip](https://github.com/vmware/vic/files/1752881/Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-6907-container-logs-before-reboot.zip)
container logs after reboot:
[Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-6907-container-logs.zip](https://github.com/vmware/vic/files/1752883/Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-6907-container-logs.zip)
tether debug and vmware log bundle:
[VCH-0-6907.zip](https://github.com/vmware/vic/files/1752886/VCH-0-6907.zip)
nightly log:
[Suites.Group5-Functional-Tests.5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1752888/Suites.Group5-Functional-Tests.5-22-NFS-Volume.zip)

**Comment by mdubya66** [comment]
Same build has been used in every nightly since 2/23. Closing.

**Comment by andrewtchin** [comment]
**VIC version:**

V1.4.0-DEV-17572-42375AA

**Deployment details:**

Nightly 6.0 2018-03-16
5-22-NFS-Volume Kill NFS Server

**Logs:**

```
Running command 'docker -H 10.160.131.187:2376 --tls run -d -v nfs-volume_VCH-0-2996:/mydata busybox sh -c "while true; do echo 'Still here... ' >> /mydata/test_nfs_kill.txt; sleep 2; done"'.
${rc} = 125
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-16-20-32-56.zip?authuser=1

**Comment by hickeng** [comment]
The prior comment should actually be for Nightly 6.0 2018-03-**15** based on the nightly results from around that date, with the following log link (the one in the above comment doesn't include the quoted error).
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-15-20-32-56.zip?authuser=1

In this case it's actually another instance of #7541 - the test is failing to determine that the VCH was not contactable after a reboot and continued running.
Closing this again as the comment associated with the reopening was in error.
