### ISSUE TITLE
Issue log collection links no longer work

### ISSUE THREAD

**Issue by RGrider** [vmware/vic#6957]
These links, which are part of the vic issues documentation describing how to collect log bundles, no longer work.
https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html

**Comment by AngieCris** [comment]
@RGrider Are these what you're looking for: 
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/log_bundles.html ?
This is the link for accessing VCH log bundles in the documentation for VIC 1.2 release.
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/vch_ssh_access.html
And this is the link for authorizing SSH access to VCH in the 1.2 release doc

**Comment by RGrider** [comment]
Yes, please update the new issue default text on github.
