### ISSUE TITLE
Intermittent failure in 23-08-VCH-Delete: Delete the correct VCH

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6958]
![image](https://user-images.githubusercontent.com/408880/33969164-a12de85e-e020-11e7-8953-d7256326a13a.png)

As the failure occurred during validation of preconditions, it's very likely that this is the result of a of race. This test, and perhaps others in the group, should probably be updated to wait and retry (briefly) for preconditions like this one to succeed.

**Comment by anchal-agrawal** [comment]
Not Ready items should have assignee(s) - assigning to the reporter for now.

**Comment by zjs** [comment]
Closing as I haven't seen this failure since it was first reported.
