### ISSUE TITLE
docker logs / docker exec does not work

### ISSUE THREAD

**Issue by RGrider** [vmware/vic#6971]
**VIC version:**

1.2.1

**Deployment details:**

./vic-machine-darwin create 
--compute-resource /DC/host/ordos12.eng.vmware.com/Resources 
--no-tlsverify 
--no-tls 
--thumbprint [my thumbprint]
--target 10.115.68.198 
--user administrator@vsphere.local 
--name WV-vch-2 
--image-store Unity600-Lun4 
--volume-store Unity600-Lun4:default 
--bridge-network /DC/network/VCH1BridgeNetwork 
--client-network /DC/network/Testbed 
--public-network /DC/network/Testbed 
--management-network /DC/network/Testbed 
--container-network /DC/network/Testbed:cn1 
--dns-server 192.168.10.101 
--public-network-ip 192.168.10.100/24 
--public-network-gateway 192.168.10.101 
--endpoint-cpu 1 
--endpoint-memory 2048 
--insecure-registry 10.115.68.163:443 

**Steps to reproduce:**
export DOCKER_HOST=192.168.10.100:2375
docker logs <container name or id>
or 
docker exec -ti <container name or id> bash
or
docker exec d /clearAfterStart.sh

**Actual behavior:**

For: docker logs <container name or id> or docker exec -ti <container name or id> bash
No output is provided and the user is returned to the command prompt.

docker exec d /script.sh:
Server error from portlayer: [GET /interaction/{id}/stderr][404] containerGetStderrNotFound

**Expected behavior:**

Docker logs are provided or the command is executed in the container.

**Logs:**

[init.log](https://github.com/vmware/vic/files/1563990/init.log)
[port-layer.log](https://github.com/vmware/vic/files/1563991/port-layer.log)
[vicadmin.log](https://github.com/vmware/vic/files/1563992/vicadmin.log)
[container-logs.zip](https://github.com/vmware/vic/files/1563993/container-logs.zip)
[docker-personality.log](https://github.com/vmware/vic/files/1563994/docker-personality.log)

**Additional details as necessary:**
Could you please check my logs and see what could be causing this behavior? Thank you

**Comment by mdubya66** [comment]
Assigning to @cgtexmex for triage.

**Comment by cgtexmex** [comment]
@RGrider In the `vic-machine` command you supplied `--management-network /DC/network/Testbed` and it appears that `Testbed` network doesn't have access to your vSphere environment.

In the provided `port-layer.log` you'll see:
```
Dec 13 2017 16:59:23.116Z WARN  session keepalive error: Post https://10.115.68.198/sdk: read tcp 192.168.10.100:42538->10.115.68.198:443: read: no route to host
```
So it appears the deployed `vic` appliance at 192.168.10.100 can't access vcenter / esxi.  Do you know if the `Testbed` network can access the `10.115.68.x` network?  If it can't then you'll need to deploy the appliance with a  `--management-network` that has access to the `10.115.68.x` network.

If it's a network route issue then I'm bothered by the fact that it's not more obvious to the user or in the logs.  If it's not a network configuration issue then we'll need to do a bit more investigation.

**Comment by RGrider** [comment]
Hi @cgtexmex, that is correct that the Testbed network doesn't have access to the vSphere environment which is 10.115.68.*.

However, my gateway and DNS server 192.168.10.101  is configured as a router to enable access from the VCH 192.168.10.100 to the public network 10.115.68.*. 

I enabled ssh on the VCH, sshed into the VCH, and was able to ping vCenter 10.115.68.198.

**Comment by RGrider** [comment]
I wanted to add that on running "docker exec", I had two different errors output at different points in time.

[root@AuctionDriver1 ~]# docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                             NAMES
1df4e24459aa        griderr/weathervane-mongodb:1.0.17      "/entrypoint.sh mo..."   2 days ago          Up 2 days           192.168.10.100:32783->27017/tcp   AuctionNosql1D
d234540ca1b2        griderr/weathervane-postgresql:1.0.17   "/entrypoint.sh"         2 days ago          Up 2 days           192.168.10.100:32782->5432/tcp    AuctionDb1D

Two days ago, where clearAfterStart.sh is the script in the container I want to run:
[root@AuctionDriver1 ~]# docker exec d /clearAfterStart.sh
No such interaction connection for container: 1191a660fa48680e62067b801165770de8ef90673614651921e9beacb1ff000d

Today:
[root@AuctionDriver1 ~]# docker exec d /clearAfterStart.sh
Server error from portlayer: [GET /interaction/{id}/stderr][404] containerGetStderrNotFound 

I didn't change anything in the environment in between.

**Comment by cgtexmex** [comment]
Is this a stand-alone host being managed by Virtual Center?  Or are you deploying directly to ESXi?

**Comment by cgtexmex** [comment]
I spoke with @RGrider today and we worked thru the issue.  The router between the appliance and the management network needed to be updated to allow communication on port 2377.  u
