### ISSUE TITLE
5-6-2-VSAN-Complex nightly fail: govc datastore.vsan.dom.ls panic: nil pointer dereference 

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6972]
nightly 12/16/17 test group 5-6-2-VSAN-Complex

After VCH cleanup, running `govc datastore.vsan.dom.ls -ds "vsanDatastore" -l -o 2>&1` gives `invalid memory address or nil pointer dereference`:

![image](https://user-images.githubusercontent.com/6562128/34076614-0dcb8078-e2b2-11e7-8d4b-94a79cb1bb49.png)

Where the panic happens according to the stack trace:
https://github.com/vmware/govmomi/blob/master/object/datastore.go#L410

Log: 
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1565321/5-6-2-VSAN-Complex.zip)

@dougm

**Comment by AngieCris** [comment]
PR: https://github.com/vmware/govmomi/pull/969

**Comment by dougm** [comment]
Note that the govc change does **not** fix the problem here, it just changes the panic to an error, the test would have still failed.  Normally the task `info` would never be nil (the possible panic had been there for years), so something unexpected happened with the network or hostd for example.

**Comment by anchal-agrawal** [comment]
Needs a priority - putting in Not Ready.

**Comment by hickeng** [comment]
Adding the vmomi-gateway tag to issues that can/should be caught and handled below the level of the core product code. I'm still hopefully that we actually split out that component for isolation and much more targeted testing.

**Comment by mdubya66** [comment]
Same build has been used in every nightly since 2/23. Closing.
