### ISSUE TITLE
nightly 5-1-Distributed-Switch: Install VCH fails in validation: Post to https://VC_IP/sdk:EOF

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6973]
VCH installation fails in one of the validation steps, with error `Post https://10.162.28.135/sdk: EOF`.
`10.162.28.135` is the VC IP according to the log (`--target=https://10.162.28.135`)
So this looks like it just lost connection to nimbus all of a sudden. 

Where exactly in the validation step it fails is hard to know. Sometimes when there's an error during validation, the error is not going to log immediately. They're collected and printed out when validation of everything else finishes. This error falls in this case. All the logs during validation do not show any apparent failure. 

From `vic-machine.log`: 
```
time="2017-12-16T05:48:54-06:00" level=info msg="  \"/ha-datacenter/host/10.160.227.177/10.160.227.177\"" 
time="2017-12-16T05:48:54-06:00" level=info msg="DRS check SKIPPED - target is standalone host" 
Dec 16 2017 05:48:54.674-06:00 DEBUG URL: https://harbor.ci.drone.local/v2/
Dec 16 2017 05:48:59.678-06:00 DEBUG URL: http://harbor.ci.drone.local/v2/
time="2017-12-16T05:49:04-06:00" level=warning msg="Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time." 
time="2017-12-16T05:49:04-06:00" level=info msg="Insecure registries = harbor.ci.drone.local" 
time="2017-12-16T05:49:05-06:00" level=error msg=-------------------- 
time="2017-12-16T05:49:05-06:00" level=error msg="Post https://10.162.28.135/sdk: EOF" 
time="2017-12-16T05:49:05-06:00" level=error msg="Create cannot continue: configuration validation failed" 
time="2017-12-16T05:49:05-06:00" level=error msg=-------------------- 
time="2017-12-16T05:49:05-06:00" level=error msg="vic-machine-linux create failed: validation of configuration failed\n" ' does not contain 'Installer completed successfully'
```

Log bundle: [5-1-Distributed-Switch.zip](https://github.com/vmware/vic/files/1565340/5-1-Distributed-Switch.zip)

**Comment by anchal-agrawal** [comment]
Needs a priority - putting in Not Ready.

**Comment by hickeng** [comment]
This cannot be diagnosed further without vCenter logs. Removing high-priority as it's now just an input into the improvements needed in log collection.

**Comment by andrewtchin** [comment]
Closing as no repro since test is currently passing. Reopen if we see it again.
