### ISSUE TITLE
VCH create leaves dangling vApp or Resource Pool

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6975]
**Deployment Details**
I tried to create a VCH named `angie-test` using create wizard, and it failed with 500 internal server error due to misconfigured network setting:
`{"message":"Failed to create VCH: Creating the appliance failed with The resource vim.dvs.DistributedVirtualPort is not available in vim.dvs.DistributedVirtualPortgroup DVUplinks-RegionA01-vDS-COMP.. Exiting..."}`

After it failed, I switched to a different network and tried to create again with the same name `angie-test`

**Actual Behavior**
The create failed with error `There is already a VirtualApp or ResourcePool that exists with the same name`:
![screen shot 2017-12-18 at 10 55 59 am](https://user-images.githubusercontent.com/6562128/34117890-b799b2f6-e3e2-11e7-98e3-fd09c3a47bd8.png)

This is not because of already created VCH, since it does not show up on the VCH inventory list:
![screen shot 2017-12-18 at 10 56 19 am](https://user-images.githubusercontent.com/6562128/34117964-f85f22da-e3e2-11e7-9eaf-e2886f33f488.png)

It might be that on the API side, the failed create leaves a dangling vApp or Resource Pool.

**Expected Behavior**
The create should succeed or at least failed with a different error not concerning existing vApp or resource pool

Cc: @zjs

**Comment by anchal-agrawal** [comment]
Needs a priority - putting in Not Ready.

**Comment by mdubya66** [comment]
If we have a PR merged by Jan 17 then we can take this fix for 1.3.1

**Comment by AngieCris** [comment]
If VCH creation fails after pool is created, API and CLI both leave trailing pool behind. Any later VCH creation with the same name goes thru without problem. However the wizard aborts the creation at step 1.
