### ISSUE TITLE
Fix VCH list tests

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6976]
Following 2 tests in Group23 - 23-02-VCH-List are failing after returning 401 instead of 200 and needs to be fixed.

```
Get VCH List Using Session
Get VCH List Within Datacenter Using Session
```

**Comment by AngieCris** [comment]
Cc: @zjs

**Comment by anchal-agrawal** [comment]
Needs an estimate - putting in Not Ready.

**Comment by zjs** [comment]
@mdharamadas1: Are these still failing for you? Could you provide logs? I'm not able to reproduce this behavior.

**Comment by mdharamadas1** [comment]
@zjs This is created as part of https://github.com/vmware/vic/pull/6970 which isn't valid anymore, so closing.
