### ISSUE TITLE
update docs to reflect CI improvements.

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#700]
from @frapposelli 
if you don’t need CI to run, just add `[ci skip]` or `[skip ci]` to the commit message. useful when you’re changing docs or non-code stuff

**Comment by stuclem** [comment]
Good to know. Thanks @mdubya66.

**Comment by hickeng** [comment]
@andrewtchin assigning this to you for update when #752 is complete.

**Comment by andrewtchin** [comment]
I documented most in https://github.com/vmware/vic/pull/707, I'll add `ci-skip` to the doc later
