### ISSUE TITLE
nightly 12/25/17 5-22-NFS-Volume: install VCH failed with "Failed to get network backing info: Post https://10.161.230.254/sdk: EOF"

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7006]
In step `VIC Appliance Install with Correct NFS Server`
installing VCH fails in getting network backing info for appliance spec
The error message says posting to VC SDK results in EOF
Might be a VC outage?

From vic-machine.log:
```
Dec 27 2017 23:39:51.330-06:00 ERROR op=17875.1: Creating the appliance failed with Failed to get network backing info for "Network:HaNetwork-VM Network @ /ha-datacenter/network/VM Network": Post https://10.161.230.254/sdk: EOF. Exiting...
```

Log: [5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1591624/5-22-NFS-Volume.zip)

**Comment by mdubya66** [comment]
Same build has been used in every nightly since 2/23. Closing.
