### ISSUE TITLE
nightly 12/26/17 5-12-Multiple-VLAN, VCH creation failed: govmomi datastore stat error when uploading image isos

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7007]
![image](https://user-images.githubusercontent.com/6562128/34417437-2d2b49fc-ebbe-11e7-98ce-4ffb70404f1c.png)

From the log output in the screenshot above, it looks like an error. From the stack trace, it's from the call to govmomi `ds.Stat`when uploading image isos during VCH installation https://github.com/vmware/vic/blob/master/lib/install/management/create.go#L139
```
				isoTargetPath := path.Join(d.vmPathName, key)
				// check iso first
				_, err := ds.Stat(d.op, isoTargetPath)
				if err != nil {
					switch err.(type) {
					case object.DatastoreNoSuchFileError:
						// if not found, do nothing
					default:
						// otherwise force delete
						d.op.Debugf("target delete path = %s", isoTargetPath)
						err := fm.Delete(d.op, isoTargetPath)
						if err != nil {
							d.op.Debugf("Failed to delete image (%s) with error (%s)", image, err.Error())
							return err
						}
					}
				}
```

The stack trace is truncated in the html. `vic-machine.log` does not include the error message, it's just truncated right after uploading image isos (we might want to change that for vic-machine to log panic messages):
```
Dec 27 2017 20:32:09.166-06:00 INFO  op=14608.1: Uploading images for container
Dec 27 2017 20:32:09.167-06:00 INFO  op=14608.1: 	"bin/bootstrap.iso"
Dec 27 2017 20:32:09.167-06:00 DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Dec 27 2017 20:32:09.167-06:00 INFO  op=14608.1: 	"bin/appliance.iso"
Dec 27 2017 20:32:09.167-06:00 DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Dec 27 2017 20:32:13.561-06:00 DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [4.394224454s] 
Dec 27 2017 21:14:01.869-06:00 DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [41m52.701977543s] 
Dec 27 2017 21:18:27.166-06:00 INFO  op=14851.1: ### Removing VCH ####
.......
```

Cc: @dougm

**Comment by dougm** [comment]
Similar to https://github.com/vmware/vic/issues/6972#issuecomment-352263186 , the test would have still failed, but will be an error instead of panic when vic includes vmware/govmomi#969

**Comment by andrewtchin** [comment]
add logging
