### ISSUE TITLE
Clock skew between client and VCH causes upgrade test failure

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7012]
Build: https://ci.vcna.io/vmware/vic/15520
Suite: `11-01-Upgrade`
Test: `Upgrade VCH`

output.xml fragment for create and check of new container. As can be seen the timestamp for creation of the container is ~2seconds in the future from the time the create/inspect commands are issued. This implies there is a time skew between the VCH and the system running the test.
The relative time output from `docker ps` is phrased in the context of the local system time for the client, not for the server.
```
<msg timestamp="20171229 05:54:06.777" level="INFO">Running command 'docker -H 192.168.31.138:2376 --tls create harbor.ci.drone.local/library/busybox 2&gt;&amp;1'.</msg>
<msg timestamp="20171229 05:54:07.333" level="INFO">${rc} = 0</msg>
<msg timestamp="20171229 05:54:07.333" level="INFO">${newc} = b65633683f7462478d9461b3109cc63d23077e55a30b5d4be08d0bb40e846a23</msg>
<status status="PASS" endtime="20171229 05:54:07.333" starttime="20171229 05:54:06.771"></status>
...
<msg timestamp="20171229 05:54:07.442" level="INFO">Running command 'docker -H 192.168.31.138:2376 --tls inspect b65633683f7462478d9461b3109cc63d23077e55a30b5d4be08d0bb40e846a23 | jq -r '.[0].Created' 2&gt;&amp;1'.</msg>
<msg timestamp="20171229 05:54:07.571" level="INFO">${rc} = 0</msg>
<msg timestamp="20171229 05:54:07.571" level="INFO">${newoutput} = 2017-12-29T05:54:09.20110296Z</msg>
```

The test needs to be updated to account for possible skew between client and server.

**Comment by anchal-agrawal** [comment]
Also seen in https://ci.vcna.io/vmware/vic/15898.

**Comment by anchal-agrawal** [comment]
Also seen in the upgrade test suite in https://ci.vcna.io/vmware/vic/16270.

**Comment by zjs** [comment]
Do we have NTP configured for the hosts? Are we configuring periodic clock synchronization via VMware Tools for the guests?

If we've configured things properly, it seems like we should have a reasonably small upper bound for clock skew in our environment.

---

https://github.com/vmware/vic/blob/4718986e06b142ee0f70b007e737eab4e117ec1e/tests/test-cases/Group11-Upgrade/11-01-Upgrade.robot#L183

What is the purpose of this check? Would increasing the sleep duration render it useless?

**Comment by zjs** [comment]
Downgrading to `priority/p1`. (See https://github.com/vmware/vic/pull/7475#issuecomment-371895507)

**Comment by mhagen-vmware** [comment]
closing, our systems are all on NTP now and we don't see this issue anymore
