### ISSUE TITLE
Delete VCH from wizard in multi-dc environment fails with "Failed to find image datastore"

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7013]
Steps to reproduce:

1. Deploy a VCH using wizard, with all minimal settings, no tls verify, no container networks.
The create params I used to create the VCH:
```
{"name":"angie-test-delete-multi-dc","compute":{"cpu":{"limit":{"units":"MHz","value":0}},"memory":{"limit":{"units":"MiB","value":0}},"resource":{"name":"/ha-datacenter/host/Cluster1"}},"storage":{"image_stores":["datastore1"],"base_image_size":{"units":"GiB","value":8}},"network":{"bridge":{"ip_range":"172.16.0.0/12","port_group":{"name":"bridge"}},"public":{"port_group":{"name":"vm-network"}}},"auth":{"client":{"no_tls_verify":true},"server":{"generate":{"size":{"value":2048,"units":"bits"},"organization":["angie-test-1"],"cname":"angie-test-1"}}},"container":{},"debug":0,"endpoint":{"operations_credentials":{"user":"Administrator@vsphere.local","password":"Admin!23"}},"registry":{}}
```
2. Add a datacenter to the VC to make it a multi-dc environment
3. Delete the VCH created from the wizard.
The delete failed with error: 
```
Error trying to delete the VCH. Failed to delete VCH: Failed to find image datastore "datastore1"
```
Screenshot: 
![image](https://user-images.githubusercontent.com/6562128/34465459-51cc21fc-ee73-11e7-9787-439a04f6760c.png)

From the inspect network tab, the create request is sent to the URL:
```
https://10.161.124.226:8443/container/target/sc-rdops-vm10-dhcp-50-133.eng.vmware.com/vch/vm-48?thumbprint=A8:6A:54:54:68:8B:DB:B9:26:FF:82:9B:84:82:D9:75:13:4C:4D:AA
```
The response is:
```
{"message":"Failed to delete VCH: Failed to find image datastore \"datastore1\""}
```

After I delete the new datacenter I created, and the VC now has only one datacenter, I delete the VCH again from the wizard and it succeeds.

I tested deleting VCH with standalone API under multi-dc env using dc-specific endpoint, delete succeeds with no errors. But when I delete using non-dc-specific endpoint, the delete fails with exactly the same response:
```
{"message":"Failed to delete VCH: Failed to find image datastore \"datastore1\""}
```

@zjs @jooskim @jak-atx  
If we have multi-dc, I guess we should send the delete request to dc-specific API endpoint?
But it doesn't look like that's what we're doing. From the network tab the URL we sent the delete to is this:
```
https://10.161.124.226:8443/container/target/sc-rdops-vm10-dhcp-50-133.eng.vmware.com/vch/vm-48?thumbprint=A8:6A:54:54:68:8B:DB:B9:26:FF:82:9B:84:82:D9:75:13:4C:4D:AA
```
which is non-dc specific endpoint.

**Comment by jak-atx** [comment]
Issue moved to [vmware/vic-ui #271](https://github.com/vmware/vic-ui/issues/271) via [**ZenHub**](https://www.zenhub.com/)
