### ISSUE TITLE
VCH created by wizard with static public network fails to initialize 

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7017]
Found by @pdaigle 

Create a VCH using the wizard with static public network (instead of DHCP)
The VCH created fails to connect to docker endpoint, and admin page is not able to authenticate.

Create params:
```
{"name":"virtual-container-host","compute":{"cpu":{"limit":{"units":"MHz","value":0}},"memory":{"limit":{"units":"MiB","value":0}},"resource":{"name":"/RegionA01/host/RegionA01-COMP01"}},"storage":{"image_stores":["RegionA01-ISCSI01-COMP01"],"base_image_size":{"units":"GiB","value":8},"volume_stores":[{"datastore":"RegionA01-ISCSI01-COMP01","label":"default"}]},"network":{"bridge":{"ip_range":"172.16.0.0/12","port_group":{"name":"Bridge01-RegionA01-vDS-COMP"}},"public":{"port_group":{"name":"VM-RegionA01-vDS-COMP"},"static":"192.168.100.22/24","gateway":{"address":"192.168.100.1"},"nameservers":["192.168.110.10"]},"container":[{"port_group":{"name":"VM-RegionA01-vDS-COMP"},"alias":"routable","firewall":"open"}]},"auth":{"client":{"no_tls_verify":true},"server":{"generate":{"size":{"value":2048,"units":"bits"},"organization":["virtual-container-host"],"cname":"virtual-container-host"}}},"container":{},"debug":0,"endpoint":{"operations_credentials":{"user":"administrator@vsphere.local","password":"VMware1!"}},"registry":{}}
```

From the broken VCH, docker persona hangs waiting for portlayer to come up:
```
time="2018-01-02T19:00:03Z" level=info msg="Launching docker personality pprof server on 127.0.0.1:6062" 
Jan  2 2018 19:00:03.843Z ERROR Unable to load CAs for registry access in config
Jan  2 2018 19:00:03.849Z INFO  Waiting for portlayer to come up
```

Portlayer fails to connect to VC:
```
time="2018-01-02T19:00:03Z" level=info msg="Launching portlayer server pprof server on 127.0.0.1:6063" 
time="2018-01-02T19:00:03Z" level=info msg="{Formatter:0xc42011bde0 Level:info Syslog:<nil>}" 
Jan  2 2018 19:00:19.102Z FATAL configure_port_layer ERROR: Failed to connect to vcsa-01a.corp.local: Post https://vcsa-01a.corp.local/sdk: dial tcp: lookup vcsa-01a.corp.local: no such host
```

VCH log: [vch-logs-20180102.zip](https://github.com/vmware/vic/files/1598579/vch-logs-20180102.zip)

Cc: @zjs

**Comment by hickeng** [comment]
Given the "no such host" error I suspect we will find in the vic-machine logs for the VCH that the vSphere API connectivity check failed with a similar message.

I suspect that either:
1. no DNS has been supplied, or 
2. the DNS we do have doesn't have that host registered.

Checking in init.log I see `Added nameservers: [8.8.8.8 8.8.4.4 8.8.8.8 8.8.4.4]` which are the default set, meaning we've not supplied a DNS server that can resolve the vCenter address supplied.

This does raise, again, the issue of structured error reporting from the VCH - this is a configuration that's not going to succeed and we should be able to downcheck the VCH in the UI extension and provide a vSphere health alert that the configuration is invalid.

**Comment by hickeng** [comment]
Having dug further into this (and discovering that I'd missed the dns arguments in the json fragment) this *is* a functional issue and should be stop-ship. We are not applying the DNS configuration correctly in the `vic-machine-service`.
