### ISSUE TITLE
Fix report-coverage CI step

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#7018]
Step `report-coverage` is failing with below error and needs to be fixed. Until that it will be disabled on CI.

https://ci.vcna.io/vmware/vic/15526
`This is an outdated version of Coverage and is expired. Please upgrade.Unable to authenticate user. Error fetching user. GET https://api.github.com/user: 401 Bad credentials []`

**Comment by mhagen-vmware** [comment]
https://github.com/vmware/vic/issues/4960
