### ISSUE TITLE
Set up vCenters with ESX servers for CI on HaaS

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#7021]
We need vCenters with ESX servers for following projects:
- `vic`
- `vic-product`

This involves:
- Setup ESX and its networking
- Install vCenter and add ESX servers to it

How many?

**Comment by mdharamadas1** [comment]
@mhagen-vmware Pls verify VC1 - VC7, details can be found in the following wiki under "vCenters" section:
https://confluence.eng.vmware.com/display/CNA/HaaS+-+Inventory

**Comment by mhagen-vmware** [comment]
lgtm
