### ISSUE TITLE
portLayer enforces creation of containers in inventory folder

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#7025]
**User Story**

See Parent issue.

**Details:**
The VCH should discern the folder path it is under and find the parent of endpointVMs folder location(be careful not to use the compute resource path). By gathering the Folder path in this manner we will have a more dynamic mechanism for determining the Folder path for the cVM creation. This path should be used to perform a folder specific VM creation operation. This should effectively namespace cVMs under a VCH resource folder. 

**Acceptance Criteria:**
VIC is able to create cVMs under a folder path. And there is a test to confirm this behavior.
  
- [x] VCH creates cVMs in the same namespaced folder as it exists in. 
- [x] Test to show this behavior

**Comment by cgtexmex** [comment]
Currently if we create a VCH in resourcePool A and then move the VCH to resourcePool B -- all containerVMs created after the move will _still_ be in resourcePool A.  I would expect inventory folders to work in the same manner -- so I don't believe the following is needed:
- [ ] Additional test for the potential moving of the endpointVM. This would need to ensure the cVMs are created in the new folder location of the VCH.

We need to fix the current behavior, but would prefer to do it as it's own task.  It needs the proper design, testing, etc...

Given the fact that we store the folder in the session object...I'm assuming this task will be drop dead easy.
