### ISSUE TITLE
Move smithers-jenkins server into our onecloud instance

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#7028]
In order to increase the reliability of our test infrastructure we need to move smithers to a supported infrastructure in onecloud instead of our on prem server.

As long as onecloud is functioning properly, this should as simple as installing an ubuntu VM and configuring jenkins - then copy over the existing jobs and turn off the old smithers.  Only tricky part might be networking/name and whether we can can get smither.eng.vmware.com to point to the new server.

**Comment by mdharamadas1** [comment]
Looks great!
