### ISSUE TITLE
Implement docker network connect

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#703]
`docker create` does not allow creating a container that is connected to more than one network, which is required for a container to act as a bridge between two networks. The only way to do that in docker is the `network connect` command.

**Comment by hickeng** [comment]
On the port layer side there's no change - it uses the same Join/Commit workflow as is the case when originally creating the container. We do need to check that Bind correctly handles multiple networks on Start.

This should not encompass adding networks to a running container at this time. I have opened #742 to trigger the configuration reload within the tether that's necessary for hotadd.

**Comment by mdubya66** [comment]
Added to Docker Command Epic #889
