### ISSUE TITLE
vic-machine create / delete supports folders

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#7032]
**User Statement:**
See Parent Issue.

**Details:**
When creating a VCH we should create a Folder (that will display in the VMs & Folders view), named for the VCH by default as with the resource pool. The endpointVM and all containerVMs it creates should be placed in this folder.

Decision needed - how is the Folder specified in CLI arguments?
1. as part of the Path element of the `--target` URL
 2. as a separate `--folder` option

Irrespective of this choice the semantics should be the same as for `--compute-resource` in that a folder will be created _under_ the specified folder with a name corresponding to the VCH.

**Acceptance Criteria:**
- [x] A folder is created, named as the VCH, _under_ the folder specified
- [x] The endpointVM is present in the folder
- [x] All containerVMs are removed from the folder as part of delete

**Comment by hickeng** [comment]
I'm in favour of a separate argument. `target` was limited to only specifying the datacenter and not the compute resource path specifically because the datacenter is the top level namespace mechanism that controls the scoping of all other arguments.
Inventory folders have no impact on whether a value for other options is valid or not so shouldn't be part of the target.

**Comment by cgtexmex** [comment]
In a ROBO environment the `folder` flag cannot be optional -- we _must_ place the VCH and resulting containerVMs in a folder.  Do we want a default value?  Or do we simply make it required for a ROBO environment?

cc @pdaigle

**Comment by cgtexmex** [comment]
For this initial release we will **not** provide a `vic-machine` flag for the folder creation -- instead we will create the folder in the `vm folders` directory of VC with the same name as the VCH.  Then as containerVMs are created we will place those VMs in the same folder.  In the future we can iterate on this implementation and provide more flexibility.

cc @matthewavery @pdaigle
