### ISSUE TITLE
Failure in Group23-VIC-Machine-Service.23-01-Metadata

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#7051]
looks like the sleep for 1 second for the service to come up wasn't enough, but I can't really find any logs for the vic-machine service to debug further, but shortly after not responding to get version it did respond to get hello

As part of whatever fix we might implement here, we need to make sure we are capturing the log within our log bundle or at least within the test.

Here is the build:
https://ci.vcna.io/vmware/vic/15572

Here is our log bundle:
https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_15572_4c17da525ab5a5422c018ddd6f505769ddd71f1c.zip?authuser=1

**Comment by AngieCris** [comment]
curl returns error code 7 (can't connect to service) when sending get request to version endpoint. It looks like the service wasn't up yet. Cc @zjs It's hard to see what went wrong without vic-machine-server.log, we might want to include it in the log bundle (I didn't find an open ticket for it. Do we want one?)

**Comment by mdubya66** [comment]
nothing wrong with using the issue for the PR to gather the appropriate logs

**Comment by AngieCris** [comment]
@mdubya66 Sorry didn't see your comment earlier and I just filed another one: https://github.com/vmware/vic/issues/7052

**Comment by AngieCris** [comment]
PR up adding vic-machine-server log in integration test log bundle and adding retries in 23-01-Metadata test: https://github.com/vmware/vic/pull/7059
