### ISSUE TITLE
Include vic-machine-server log in integration test log bundle

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7052]
When running vic-machine-service, the log file is located in server machine at /var/log/vic-machine-server/vic-machine-server.log, but it's not included in the integration test bundle. It's hard to debug from integration test result if there is a failure during Group 23 vic-machine-service tests.

**Comment by AngieCris** [comment]
We might want to take this pr in too to make the debugging from log file actually effective: https://github.com/vmware/vic/pull/6944

**Comment by mdubya66** [comment]
Should we also consider changing the test to use the wait for vs timeout?

**Comment by zjs** [comment]
> Should we also consider changing the test to use the wait for vs timeout?

This would be tracked by #7051.

**Comment by AngieCris** [comment]
@zjs I added the retries in the same PR: https://github.com/vmware/vic/pull/7059. It's a very small fix altogether

**Comment by AngieCris** [comment]
PR adding vic-machine-server log in integration test log bundle and adding retries in 23-01-Metadata test: https://github.com/vmware/vic/pull/7059
