### ISSUE TITLE
VCH create with option --ops-grant-perms fails on OneCloud VC setup

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#7054]
**VIC version:**

Vic 1.3 GA Release Candidate

**Deployment details:**
Deployment created in OneCloud. VC has an additional identity source: local AD. The PSC might have been deployed separately than VC.

**Steps to reproduce:**
Try creating a VCH with an ops-user, also select the --ops-grant-perms option which should assign the right permission set to the ops user.

**Actual behavior:**
VCH creation appears to fail with the following message:

_ERRO[0014] Cannot init ops-user permissions, failure: ServerFaultCode: The object or item referred to could not be found.. Exiting...
ERRO[0014] --------------------
ERRO[0014] vic-machine-linux create failed: Cannot init ops-user permissions, failure: ServerFaultCode: The object or item referred to could not be found.. Exiting..._

The VCH is created.

**Expected behavior:**
The VCH creation should be successful.

**Logs:**
From the vpxd logs:

_Directory -- vim.UserDirectory.retrieveUserGroups -- 52c5b7b5-b23e-4793-12e4-cdafbdd267f5(524a2481-636c-3825-6e44-5cc30a691e8f)
2018-01-09T00:41:26.127Z error vpxd[7F02E85AE700] [Originator@6876 sub=[SSO] opID=1542338.1-46] [UserDirectorySso] SearchUsers exception: N7Vmacore9Authorize17AuthUserExceptionE(User Administrators)
--> [context]zKq7AVECAAAAAAomUQAUdnB4ZAAADJQrbGlidm1hY29yZS5zbwAABE8bAGqXGAGnrP12cHhkAAHlsv0Bo8r9ATvn/QFh6f0B+Fb9gvP+BAFsaWJ2aW0tdHlwZXMuc28AAUSXdAGTj3MBCIVzAZeocwHI+3MAL+IjABblIwD36ysDVHQAbGlicHRocmVhZC5zby4wAAQtjg5saWJjLnNvLjYA[/context]
2018-01-09T00:41:26.131Z error vpxd[7F02E85AE700] [Originator@6876 sub=Default opID=1542338.1-46] Error accessing directory: User, group or domain not found: User Administrators
2018-01-09T00:41:26.132Z info vpxd[7F02E85AE700] [Originator@6876 sub=vpxLro opID=1542338.1-46] [VpxLRO] -- FINISH lro-1532706
2018-01-09T00:41:26.132Z info vpxd[7F02E85AE700] [Originator@6876 sub=Default opID=1542338.1-46] [VpxLRO] -- ERROR lro-1532706 -- UserDirectory -- vim.UserDirectory.retrieveUserGroups: vim.fault.NotFound:
--> Result:
--> (vim.fault.NotFound) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = <unset>
-->    msg = ""
--> }
--> Args:
-->
--> Arg domain:
--> "vsphere.local"
--> Arg searchStr:
--> "foo"
--> Arg belongsToGroup:
--> "Administrators"
--> Arg belongsToUser:
-->
--> Arg exactMatch:
--> true
--> Arg findUsers:
--> true
--> Arg findGroups:
--> false_

**Additional details as necessary:**
Although the presence of the Active Directory makes the setup more complex, it does not have an effect on the problem. I tried removing it from the VC configuration and vic-machine still fails.

**Comment by lcastellano** [comment]
I have asked Lakshimi to test this issue in a configuration where the PSC is deployed separately from VC. The grant permission option works fine in that environment. So the issue is not related to the PSC configuration. Another peculiar characteristic of this environment is the presence of an Active Directory Internal service as an Identity Source. This requires the PSC to be domain joined with the AD server. I tested removing AD as Identity Source and I still got the error. So perhaps the domain joining is causing the issue. I have sent an email to the team responsible for this set of APIs in VC and awaiting for an answer. Next step would be to open a bugzilla issue.

**Comment by lcastellano** [comment]
Lakshmi confirmed that this is not an issue with a deployment with a separate PSC. So this appears to be connected to the addition of Active Directory as an identity source.

**Comment by cgtexmex** [comment]
@lcastellano we have also experienced this at a customer site -- will connect with you later today.

**Comment by mdubya66** [comment]
setting medium for now. might need to be raised depending on workaround.

**Comment by mdubya66** [comment]
flagging for 1.3.1 for now.

**Comment by stuclem** [comment]
Entry for the Resolved Issues of the 1.3.1 release notes:

- <b>Using `vic-machine create --grant-ops-perms` option causes VCH deployment to fail. [#7054](https://github.com/vmware/vic/issues/7054)</b><br>This issue occured when the Platform Services Controller is connected to an Active Directory identity source, and has been fixed.

@lcastellano @lgayatri does this cover it? Thanks!
