### ISSUE TITLE
Write a new infra upgrade test

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#7055]
**Story**
As a viadmin I want to be able to upgrade my infrastructure from 6.0u3 to 6.5uLatest and expect my VCHs to continue working without issue

**Details**
We have various upgrade tests already in place, but do not have a major version upgrade test in place that I'm aware of. The main concern for me (@hickeng) is around mutability of mo-refs and the use of the resource pool mo-ref.
The 6.0->6.5 is non-trivial so this may be a manual test.

**Acceptance**
A VCH and it's containers deployed in vSphere 6.0 still functions correctly after an upgrade to vSphere 6.5, including standard regression sets:
- [ ] after VCH endpoint reboot
- [ ] after VCH upgrade (after vSphere upgrade)
- [ ] vic-machine list/inspect/delete function as expected with a hetrogeneous mix of VCHs deployed before/after vSphere upgrade
- [ ] verification of application function in cVMs post upgrade.

**Comment by zjs** [comment]
Sending this back to "Not Ready" for estimation by the team. Additionally, it would be helpful to explain the problem being solved.

**Comment by hickeng** [comment]
I've added customer-found because I'm not sure that `pm/customer-question` will show up in regularly used searches. Added to 1.4.1 as a p1 as that's our window to fix any significant issues that impact a 6.0->6.5 upgrade.

**Comment by mdubya66** [comment]
@lgayatri Can you take this on? Could you please document the steps you take and work with @mhagen-vmware for future automation? Let's confirm with @pdaigle and @hickeng on the requirements, but to start let's use 1.3.1 since that's what the customer is currently on. We need this completed by 25-May.

**Comment by lgayatri** [comment]
@mdubya66 - Yes.

**Comment by mdubya66** [comment]
For 1.4.1 this can be manual testing. For 1.5 we would need it automated.

**Comment by renmaosheng** [comment]
@lgayatri have you got a chance to automate this? thanks.

**Comment by lgayatri** [comment]
@renmaosheng, this is in plan for 1.5. Upgrade will be for VCSA and ESX as well.

**Comment by renmaosheng** [comment]
please close the issue once it is done ,thanks.

**Comment by lgayatri** [comment]
We are doing this testing once in a milestone.
