### ISSUE TITLE
Integration test cleanup VCH delete leaves trailing datastore

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7065]
CI build https://ci.vcna.io/vmware/vic/15603

Test case 6-05-Create-Validation, in test cleanup, VCH delete command succeeded but there's a trailing datastore named `VCH-15603-6778_1`. Since `VCH-15603-6778` is the name of the VCH being deleted, the test failed.

![image](https://user-images.githubusercontent.com/6562128/34785149-edb8a4a8-f5f5-11e7-93b2-0b7d1d08f582.png)

Log bundle: https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_15603_22825c079dca8f8d1ff700c00a60b35cb3dd3a27.zip?authuser=1

**Comment by mhagen-vmware** [comment]
It was actually a combination of a collision with another test that does not cleanup properly:
6-04-Create-Basic - Create VCH - Existing VM name

The creates a dummy VM with the same name, then uses vic-machine create to create another VCH with the same name, it automatically gets renamed to <VCH-NAME>_1 on ESX.

**Comment by AngieCris** [comment]
@mhagen-vmware Do we cleanup the _1 datastore? 
In the test case I didn't see we do that using govc:
```
    ${rc}  ${output}=  Run And Return Rc And Output  govc vm.destroy %{VCH-NAME}
    Should Be Equal As Integers  ${rc}  0
    Cleanup VCH Bridge Network  %{VCH-NAME}
```

**Comment by mhagen-vmware** [comment]
It isn't cleaned up at all, it only cleans up if the test fails.
`Test Teardown  Run Keyword If Test Failed  Cleanup VIC Appliance On Test Server`

Otherwise it just cleans up the original dummy VM

**Comment by AngieCris** [comment]
@mhagen-vmware Do we want to add a cleanup process in this test case to prevent such collision?

**Comment by mhagen-vmware** [comment]
yes we do, to resolve this issue
