### ISSUE TITLE
Tests in 1-18-Docker-Network-RM fail due to already-existing network

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7066]
**VIC version:**

`v1.3.0-rc1-15605-89bc7c9` (not actually RC1)

**Deployment details:**

https://ci.vcna.io/vmware/vic/15605

**Actual behavior:**

1. `Basic network remove` reported "Error response from daemon: network test-network already exists"
2. `Remove already removed network` failed with "'Error response from daemon: test-network has active endpoints' does not contain 'Error response from daemon: network test-network not found'"
3. `Remove network with running container` reported "Error response from daemon: network test-network already exists"

**Expected behavior:**

* The tests pass.
* The tests do not depend on another in a way that causes cascading failures like this.

**Logs:**

[Test-Cases.Group1-Docker-Commands.1-18-Docker-Network-RM-VCH-15605-9279-container-logs.zip](https://github.com/vmware/vic/files/1619960/Test-Cases.Group1-Docker-Commands.1-18-Docker-Network-RM-VCH-15605-9279-container-logs.zip)

**Additional details as necessary:**

![image](https://user-images.githubusercontent.com/408880/34788430-68d454a4-f5ef-11e7-8c4c-a1e21b811e27.png)

**Comment by vburenin** [comment]
did we start running tests in parallel? Start time for each of those failed tests varies in milliseconds.

**Comment by mhagen-vmware** [comment]
tests are sequential as they always have been

**Comment by anchal-agrawal** [comment]
This is likely a dup of https://github.com/vmware/vic/issues/7137 and has been fixed - @vburenin we can confirm and close this.

**Comment by vburenin** [comment]
Fixed in #7137
