### ISSUE TITLE
Deploy CI services (other than Drone) on HaaS

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#7070]
These include following which needs to be migrated to HaaS:
- Harbor (OVA using VC)
- Yum repo

**Comment by mdharamadas1** [comment]
@mhagen-vmware Could you pls verify and close this if all looks good? I verified these with drone builds.
Harbor: wdc-harbor-ci.eng.vmware.com
Yum: wdc-yum-builder-ci.eng.vmware.com

**Comment by mhagen-vmware** [comment]
lgtm
