### ISSUE TITLE
CI doesn't pick up new builds on the first try

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#7076]
Steps: 
1) open a PR
2) push changes to the PR
3) notice that the build failed
4) click on the build

Usually I get this:
<img width="952" alt="screen shot 2018-01-10 at 4 20 22 pm" src="https://user-images.githubusercontent.com/3743903/34798587-4859fb9c-f622-11e7-9153-f2cae889e3e0.png">

But sometimes I also get this:
<img width="985" alt="screen shot 2018-01-10 at 4 19 49 pm" src="https://user-images.githubusercontent.com/3743903/34798596-50236908-f622-11e7-963a-cfd31ed2d2b1.png">

Clicking restart lets the build run successfully. In the above case, I got the second error, clicked restart, got the first error, clicked restart, and now it's running.

**Comment by anchal-agrawal** [comment]
Related: https://github.com/vmware/vic/issues/3897

**Comment by gigawhitlocks** [comment]
Yes, #3897 is definitely related. For the record I just reproduced this behavior again -- pushed a new commit (no rebase) and the build failed immediately. Realized I forgot to rebase, did that, force-pushed to my branch (as per usual), and that build ran.

Although actually in this case I would've killed the first build so in this instance it was a feature!

**Comment by gigawhitlocks** [comment]
For the above, build #15645 is the one that failed to check out the code properly. #15646 is the one that worked.

**Comment by zjs** [comment]
I believe this has been fixed.
