### ISSUE TITLE
2 Issues installing the VIC 1.3 OVA using the HTML Client ( vSphere Client )

### ISSUE THREAD

**Issue by vmwarelab** [vmware/vic#7081]
Testing the the new release of VIC 1.3 and while installing the OVA using the HTML client ( vSphere Client ) I encountered two issues : 

1. The password requirement for the example users is set to be not less than 128 Characters :) .. 

![image](https://user-images.githubusercontent.com/19843322/34846022-e30eaa62-f6e4-11e7-8163-d2a77cfae31a.png)

2. While I choose to skip the creation of the example users . the deployment always failed with this error Invalid value 'true' specified for property appliance.permit_root_login.  when i check that i want root to be able to ssh into the VIC appliance 

![image](https://user-images.githubusercontent.com/19843322/34846190-615a59d4-f6e5-11e7-8fd4-c40455e3ff36.png)

the workaround was to simple use the Flash Client ( Web Client )

**Comment by mdubya66** [comment]
Issue moved to [vmware/vic-product #1308](https://github.com/vmware/vic-product/issues/1308) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mdubya66** [comment]
Moving to the vic-product repo.
