### ISSUE TITLE
VIC Engine v1.3.0 - Inspect too informational

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#7091]
VIC Engine v1.3.0-15556-473375a

As part of the inspect output for containers attached to external vSphere networks, earlier versions used to produce concise out as below

```
"HostConfig": {
...
"PortBindings": {},
...
}
```

however, this version produces as below:

```
"PortBindings": {
                "0/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ],

```
for all the 65535 ports! producing an 11M output :-(

This is probably intended and accurate, but that makes the output unreadable or dynamically parse-able.

May I know what would be better way? does explicit use of Expose during build or -p during run would have an effect? On a quick test with -p during docker run didn't help though..

**Comment by hickeng** [comment]
@AngieCris 
I suggest this is seen using container-networks if you do not see it on bridge networks. This is also likely to be related to #7084.

Hypothesis for these two issues is that a pre 1.3.0 container has a port config that has been interpreted to mean that _**all**_ ports are being forwarded - that would explain both why we see this giant inspect output and also the port exhaustion in #7084.
I am unclear on what that config would be at this time.

This could be related to #6557 - I was doing follow on work for that in #6641 but didn't have time to complete it.

**Comment by AngieCris** [comment]
@malikkal Do you happen to have the configuration info of the original container?

**Comment by malikkal** [comment]
@AngieCris I will share it via email to George, as it contains some internal IP details.

However, you could easily reproduce this via an nginx image on an older VCH version and observe the difference in inspect output in the newer VCH, while they are *connected to an external network*. I noticed that this is not the case with when you use NAT via VCH.

**Comment by mdubya66** [comment]
Moving this to 1.4.0 as it's an enhancement.
