### ISSUE TITLE
Milestone: vSAN support

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#710]
Add support & integration tests for vSAN datastores.

**Comment by corrieb** [comment]
@fdawg4l #711 is targeted for GA, but this epic is targeted for onsite. Please update on what our expectations should be for onsite WRT this epic.

**Comment by fdawg4l** [comment]
@bcorrie functionality is complete. We just need integration tests.

**Comment by corrieb** [comment]
To clarify per slack with @fdawg4l, #711 isn't complete and won't make onsite. However, there are integration tests that should be added for the existing work that's been done.

@fdawg4l to add tests for onsite, then we'll move this epic to GA
