### ISSUE TITLE
Test vicadmin in isolated network configuration

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7102]
**Story**
As a viadmin I expect to be able to use vicadmin to collect VCH logs when it cannot connect to the internet

**Details**
vicadmin validation currently checks connectivity to wider network and to docker hub. This is a somewhat legitimate test until #5260 is addressed, but we MUST NOT gate other function on an assumption that internet connectivity is available.
We have had an issue where vicadmin will enter a login loop when not internet access is available and we require a test that assures this does not occur again.

**Comment by andrewtchin** [comment]
@mhagen-vmware Why is this p1?

**Comment by mhagen-vmware** [comment]
because it is a customer found escape issue

**Comment by andrewtchin** [comment]
create port group that does not have internet connectivity
deploy vch connected to that pg
login to vch and try to download logs
verify this with george
