### ISSUE TITLE
Test failed install of VCH

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#7129]
From: https://github.com/vmware/vic/issues/6975

Should be simple nightly test, just don't hook the virtual switch up to a NIC.  Verify at a minimum that cleanup happens properly.

**Comment by mhagen-vmware** [comment]
@hickeng We discussed this somewhere, but I can't remember where so I want to document our discussion here.  I have the PR above done, but it is currently failing because we leave behind the VCH when it fails to install.  My understanding is that this is intentional. Do we really want to make any changes here or just close this ( and my PR )?

**Comment by zjs** [comment]
We deliberately preserve resources when a failure occurs to allow for effective investigation.
