### ISSUE TITLE
Run syslog server as drone service

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#7135]
Currently, syslog service runs in one of the OVH servers. As it is used for tests and not for CI infra, so it should be part of test code.

A/C:
- Syslog server container running as drone service
- Related tests pass on CI 

If this isn't possible than we are just going to run syslog server on one of the ESX VMs in HaaS server.

**Comment by mdharamadas1** [comment]
@mhagen-vmware I have setup common syslog server on a VM host in HaaS. Please find the details in the following wiki to verify:
https://confluence.eng.vmware.com/display/CNA/HaaS+-+Inventory

**Comment by mhagen-vmware** [comment]
lgtm
