### ISSUE TITLE
Milestone: container name resolution

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#714]
Being able to resolve the symbolic names of a container from within another container is a core capability and a prerequisite for _link_ support.

This *does not* include:
* aliases
* IPv6 support
* service discovery

**Comment by hickeng** [comment]
#84 contains some initial work towards this, but is targeted at full links support so not added as a child. This needs specific low level issues adding

**Comment by hickeng** [comment]
@caglar10ur Think we're going to get this done for TP3? What's left in the impl side?

**Comment by mdubya66** [comment]
Closing this. #430 is covering this. Also addressed in a PR from Caglar
