### ISSUE TITLE
Cannot create 1.3 VCH using vic-machine-linux on vRO 7.3

### ISSUE THREAD

**Issue by virtualhobbit** [vmware/vic#7157]
**VIC version:**

1.3.0-15556-473375a

**Deployment details:**

The following command was used:

/etc/vco/app-server/vic/vic-machine-linux create --target vcsa.xyz.com --user admin@xyz.com --password fake_password --name vch2.xyz.com --compute-resource "Compute - Development" --image-store DS_Compute_Development_01 --volume-store DS_Compute_Development_01:default --bridge-network "Compute - Development - VIC-bridge" --bridge-network-range x.x.100.0/16 --container-network "Compute - Development - VLAN50":container-network --container-network-gateway "Compute - Development - VLAN50":x.x.50.254/24 --container-network-dns "Compute - Development - VLAN50":x.x.30.1 --container-network-dns "Compute - Development - VLAN50":x.x.30.2 --container-network-ip-range "Compute - Development - VLAN50":x.x.50.101-200 --public-network "Compute - Development - VLAN30" --public-network-ip x.x.30.142/24 --public-network-gateway x.x.30.254 --dns-server x.x.30.1 --thumbprint 93:AA:D7:BB:3C:CC:8B:DD:12:EE:D1:FF:00:AA:8F:BB:D0:CC:66:DD --timeout 15m0s --no-tlsverify --force

**Steps to reproduce:**

Run the above command on a vRealize Orchestrator 7.3 appliance

**Actual behavior:**

VCH fails to create. Receive the following error:

ERRO[0001] --------------------
ERRO[0001] Failed to create client for validation of operations credentials: Post https://vcsa.xyz.com/sdk: x509: failed to load system roots and no roots provided
ERRO[0001] Create cannot continue: configuration validation failed
ERRO[0001] --------------------
ERRO[0001] vic-machine-linux create failed: validation of configuration failed

**Expected behaviour:**

VCH should be created successfully

**Additional details as necessary:**

This is to enable VCH-as-a-Service, as documented in https://blogs.vmware.com/cloudnative/2017/11/07/using-vrealize-automation-deploy-vmware-virtual-container-hosts/

**Comment by virtualhobbit** [comment]
Issue also exists in v1.3.1-16055-afdab46.

**Comment by mdubya66** [comment]
The response from the vRA team.

====
I think the issue is not particular to vRO. It’s a general certificate error caused by missing/incorrect configuration. If the certificates being used are CA certificates then they must be added to vRO. In our testing, the issue did not occur on VIC.
 
Has the user tried executing the command outside vRO? I know Alka had asked this question before.
====

**Comment by virtualhobbit** [comment]
I have resolved this by placing the SSL certificate chain on the vRO server (/etc/ssl/certs) and then running the following command  - _c_rehash /etc/ssl/certs_.
