### ISSUE TITLE
trace package unable to utilize remote syslog

### ISSUE THREAD

**Issue by jzt** [vmware/vic#7169]
**User Statement:**
As a developer, I would like trace/operation logging to appear in all places that normal logging messages appear.

**Details:**
Currently, the `trace` package uses its own logger that is configured in a special way to stop output from going to stdout. This was initially inteded to make vic machine logging cleaner since the trace info did not serve any purpose to a user. A side effect of this specially-configured logger is that output will never go to syslog along with the default VIC logger output. The initial problem has since been fixed (@hickeng `!fact_check()`), so lack of syslog support in the trace package should be fixed for consistency and for log analysis tools (such as Log Insight).

We can either:
- remove the customization in the trace package and allow it to use the same hooks as the global VIC-configured logger
- add the syslog hook to the trace logger in any/all particular packages that may need it (not ideal)

**Acceptance Criteria:**
`trace` package level logger output goes to remote syslog server when appropriate.

**Comment by lcastellano** [comment]
7236 (portlayer, personality), 7254 (vic-admin)
