### ISSUE TITLE
Unable to shutdown VCH

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic#7188]
**VIC version:**

Seeing this on:

1.2.1
1.3.0-rc6
1.3.0

**Deployment details:**

./vic-machine-linux create \
--target vcsa-01a.corp.local \
--user administrator@corp.local \
--compute-resource RegionA01-COMP01 \
--image-store RegionA01-ISCSI01-COMP01 \
--volume-store RegionA01-ISCSI01-COMP01:default \
--public-network VM-RegionA01-vDS-COMP \
--public-network-ip 192.168.100.22/24 \
--public-network-gateway 192.168.100.1 \
--dns-server 192.168.110.10 \
--container-network VM-RegionA01-vDS-COMP:routable \
--container-network-firewall VM-RegionA01-vDS-COMP:open \
--bridge-network Bridge01-RegionA01-vDS-COMP \
--name virtual-container-host-1.2.1 \
--tls-cname=vch1.corp.local \
--registry-ca=/etc/docker/certs.d/registry.corp.local/ca.crt \
--whitelist-registry registry.corp.local \
--whitelist-registry registry.hub.docker.com \

**Steps to reproduce:**

Created VCH with the command above, they tried to shutdown from vSphere client. Both the HTML5 and Flex clients produce the same result.

**Actual behavior:**

VCH fails to shut down and generates the error `A general system failure occurred: Invalid fault`

If I forcibly stop the VM using Stop instead of Shutdown, when I power it back on, the services (API endpoint and vicadmin page) do not come back up.

**Expected behavior:**

I expect to be able to gracefully shutdown VCH.

I expect that the VCH should come back up even after an unplanned outage.

**Logs:**

Logs attached.
[container-logs.zip](https://github.com/vmware/vic/files/1674398/container-logs.zip)

Error displayed in vCenter

![image](https://user-images.githubusercontent.com/8586715/35538944-99c10296-051d-11e8-89cd-78f7e6013d5e.png)

**Additional details as necessary:**

This 100% reproducible in my lab. I can provide access if necessary.

**Comment by zjs** [comment]
> VCH fails to shut down and generates the error `A general system failure occurred: Invalid fault`

I'm able to reproduce this behavior near the head of `master` (against nimbus).

**Comment by AngieCris** [comment]
Reproduce-able on my nimbus environment for all VCHs I created recently and VCHs a while back into 1.3 rc1

**Comment by AngieCris** [comment]
According to @hickeng, we don't support guest OS shutdown yet so the `A general system failure occurred: Invalid fault` is expected. This PR fixes it: https://github.com/vmware/vic/pull/6943
However from the logs you provided in the ticket, it seems like all the services come back up after restart normally

**Comment by AngieCris** [comment]
https://github.com/vmware/vic/issues/7204 filed to track the update of vicadmin page error message.
Closing this issue now.
