### ISSUE TITLE
ROBO support

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7225]
**User Statement:**
As a vSphere customer with ROBO sites I want to be able to deploy container based application to those sites.

**Details:**
Initial delivery of ROBO Advanced support:
* Basic placement support in lieu of DRS.
* Distributed vSwitch - assumed to be present given Advanced condition.
* Adjustment of license checks to be feature checks
* Confirmation of vSPC support
* Address issues introduced by WAN link between VCH and VC
* Scale considerations and testing for distributed sites

**Acceptance Criteria:**
Refer to original PM issue: vmware/vic-planning/issues/62

**Comment by cgtexmex** [comment]
This Epic's issue and point total can be confusing..or was to me...since there are 6 sub epics and those totals don't add up to this epic's total.  That's because it's smart enough to count unique issues -- We have nested epics and issues assigned to multiple epics...thus my confusion.

**Comment by mdubya66** [comment]
It should, we should check with zenhub if a bug exists

**Comment by mdubya66** [comment]
Re-opening as there are points remaining
