### ISSUE TITLE
Create VC Enterprise test environment with DRS configured as it would be with ROBO

### ISSUE THREAD

**Issue by jzt** [vmware/vic#7227]
**User Statement:**

As a VIC developer, I would like to test ROBO support against a ROBO environment that is configured to emulate a customer deployment in the real world, starting immediately.

**Details:**

Until an appropriate ROBO version (6.5u2 or greater) is available we will use an Enterprise licensed VC with DRS configured as per ROBO (disabled).

**Acceptance Criteria:**
- [ ] Nimbus testbed consisting of Enterprise VC + DRS disabled [confirmed DRS should be disabled]

**Comment by anchal-agrawal** [comment]
@jzt Please add an estimate and priority, thanks!

**Comment by cgtexmex** [comment]
We discussed this issue during a planning meeting today -- this is intended to be a stop gap until we have the required vSphere version and ROBO licenses.  As such I'm estimating as a 3 because we could do this in a day or two.

@jzt @hickeng please update if you have concerns.
