### ISSUE TITLE
Automate ROBO testbed deployment

### ISSUE THREAD

**Issue by jzt** [vmware/vic#7228]
**User Statement:**

As a developer, I would like the ability to automate the deployment of ROBO testbeds.

**Details:**

#7226 and #7227 detail the two testbeds we need for testing changes while adding ROBO support. This story is strictly about automating the deployment of the two different testbeds. Currently, we are planning to use Robot to handle the automation, both within CI and without.

**Acceptance Criteria:**
- [x] Robot utility code to deploy a ROBO test environment that emulates customer deployment (see #7226)
- [x] Robot utility code to deploy a Enterprise+ VC + DRS disabled/manual to be used for ROBO testing (see #7227)

**Comment by anchal-agrawal** [comment]
@jzt Please add an estimate and priority, thanks!
