### ISSUE TITLE
Migrate Gandalf service

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#7230]
Currently, Gandalf, which is our git repo status bot, is running on OVH inside the VM 192.168.31.246, along side drone server container.

A/C:
- Set up VM in HaaS server with VIC env
- Build and run gandalf
- Verify it works

**Comment by mdharamadas1** [comment]
@mhagen-vmware Gandalf is moved to HaaS, pls verify and close this if all looks good.

**Comment by mhagen-vmware** [comment]
verified
