### ISSUE TITLE
Use DRS aware power on placement when target is vCenter

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7237]
**Story**
As a viadmin I expect containerVMs to be distributed across my cluster in a sane and load aware manner when DRS semi-auto or auto is enabled.

**Details**
There is a separate call necessary to power on a VM in a way to allow DRS to provide intelligent placement at a sub-sample interval. vmware/govmomi#1026 is open to add support for the call into the library.
Why this seems to be intermittent or environment specific is unclear.

This issue will be fixed by consuming the govmomi update, adding whatever switching logic necessary (hopefully none if @dougm is happy with my request for intelligent switching based on target type in object.VirtualMachine.PowerOn), and adding appropriate testing to ensure wide distribution of power-on operations.

@lgayatri Is power on clustering something you have observed in scale testing? Is it something you have a way of quantifying as a metric so we can detect regressions? If not we should ask the perf team if they have a usable measure. 

Estimate is for code fix and basic test, excluding govmomi work and scale/stress metrics/tests.

**Comment by lgayatri** [comment]
@hickeng , I use DRS in Automatic mode  and will check to quantify the power On operations. 
![image](https://user-images.githubusercontent.com/25006749/35721383-b75587f8-0817-11e8-99fc-806af1ec27ca.png)

**Comment by dougm** [comment]
PR: vmware/govmomi#1031

**Comment by mdubya66** [comment]
Marking kind bug. bz 2050415

**Comment by hickeng** [comment]
Asked @jzt do make a small focused change in with the feature/robo branch to use the `datacenter.PowerOnMultiVM` and run full-ci against it. Wanting an early insight into whether there's more work here outside of the robo changes.
