### ISSUE TITLE
Research metrics requirements

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#7245]
Research metrics requirements for the wolfpack daemon.  Determine which metrics should come from vSphere, the resource pool, or the containers running in the wolfpack vm.

Acceptance Criteria:
- [ ] A table mapping metrics with the source
- [ ] An early design of how to gather the metrics (wolfpack daemon, tether, or 3rd party component)

**Comment by sgairo** [comment]
@sflxn same for this issue, when you get a better understanding of the issue, please will in the user story and acceptance criteria, thanks!

**Comment by sflxn** [comment]
I didn't realize I had an issue already and wrote up a new one.  Closed this one as the new one has all the details.
