### ISSUE TITLE
vSphere H5 UI - incorrect option inside CLI command

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#7253]
Version	v1.3.0.533

Create VCH > End Wizard > Copy CLI command; output is --volume-store**s** should be --volume-store

I am not sure if this should go in the issues under vic-product. Regardless, filing here as it is a vic-machine-os option.

Thanks.

**Comment by mdubya66** [comment]
Thanks for the report. This appears to be a duplicate of https://github.com/vmware/vic-ui/issues/251 which is merged to master and the 1.3.1 branch.
