### ISSUE TITLE
extraconfig.encode: unexpected warning message

### ISSUE THREAD

**Issue by emlin** [vmware/vic#726]
If encode structure with skipped attribute tag as: `vic:"0.1" recurse:"depth=0"`, extraconfig.Encode will log out warning message as following.
WARN[2016-05-18T23:06:32-05:00] Skipping  (unknown scope [])

If call this library in CLI, e.g. vic-machine, the message will be print out. Which is useless, and misleading.

**Comment by hickeng** [comment]
@emlin Is this addressed? The problem was not specifying a scope - the error message wasn't ideal.
Please close this or expand on what needs to be addressed.

**Comment by dougm** [comment]
@emlin ping

**Comment by hickeng** [comment]
@emlin I'm going to close this and open another issue about using different logging for vic-machine - that's our user facing component and the errors and so forth are still useful - they just need to be routed to a log. We should have a separate logger for output to user vs logging to log.
