### ISSUE TITLE
Investigate mounting VIC container images onto the wolfpack VM

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#7263]
We've kicked around the idea of a content addressable stackable wolfpack vm image.  However, that's a long term optimization that we won't get around to till after all the prototypes.  For the prototype, we should investigate approaches to mounting VIC container images onto the wolfpack vm.  Investigate two approaches in the storage portlayer:

1. Add the ability for the storage portlayer to mount other disk images as a volume.  In this case, a VIC container image.  We should be able to tell the portlayer here is a disk image and here is a mount point.
2. Instead of directly telling the portlayer to mount the disk image as a mount point, we can cause the same result to happen via configuration during container create.  The portlayer will just indirectly do the necessary work to let the tether know to mount the disk image to a mount point.

Option 1 is direct operation from the portlayer.  Option 2 is indirect and all the work is hidden from the portlayer client.

Acceptance criteria:
- [ ] Recommendation on which approach is cleaner and most appropriate for the wolfpack project.

**Comment by hickeng** [comment]
I'm not actually clear on the distinction between the two - basic call flow examples perhaps? From my perspective the implementation portions are:
1. Add the ability for the storage portlayer to use the image store as a volume store
2. Update image disk labelling schemes so that not all images have the same label.

**Comment by sflxn** [comment]
George has actually completed this work, and I merged it into the wolfpack feature branch.
