### ISSUE TITLE
5-22 NFS Nightly Test Failure: device in use

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#7264]
Seen in 2/5 nightly run for 6.5:
[Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-7270-container-logs.zip](https://github.com/vmware/vic/files/1699791/Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-7270-container-logs.zip)

logs before reboot:
[Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-7270-container-logs-before-reboot.zip](https://github.com/vmware/vic/files/1699795/Suites.Group5-Functional-Tests.5-22-NFS-Volume-VCH-0-7270-container-logs-before-reboot.zip)

```ERROR Handler for POST /v1.25/containers/d7e39c768a776025456b88d415db7b5749d66e598a37c24c6626b796c8ff3164/start returned error: Conflict error from portlayer: device nfs-volume_VCH-0-7270 in use```

**Comment by sgairo** [comment]
@matthewavery Will you confirm whether or not this is a duplicate of https://github.com/vmware/vic/issues/5819 or not? Thanks!

**Comment by mdubya66** [comment]
Same build has been used in every nightly since 2/23. Closing.
