### ISSUE TITLE
extraconfig.encodeWithPrefix: prefix is added with unexpected '/'

### ISSUE THREAD

**Issue by emlin** [vmware/vic#727]
with method: extraconfig.EncodeWithPrefix(extraconfig.MapSink(cfg), conf, "vch"), to encode metadata.VirtualContainerHostConfigSpec, will get following key:
"guestinfo./vch/datacenter_name"

but "guestinfo.vch/datacenter_name" is expected

**Comment by hickeng** [comment]
This is because datacenter_name is read-only. As mentioned previously, any time invested in trying to use extraconfig to generate specific guestinfo layout it pointless - simply update the launcher.sh script to use the generated keys if the component isn't yet migrated to use extraconfig directly.
