### ISSUE TITLE
vic-machine to provide license and feature check

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7275]
vic-machine create facilitates a license check to ensure VCH compliance.  This will need to be augmented to include the feature checks that will be identified in #7278.  

- [x] vic-machine create ensures license and feature compliance
- [ ] CI Test Plan
- [ ] CI Tests

**Comment by hickeng** [comment]
@dougm Any chance of a "ROBO" license for vcsim?

**Comment by dougm** [comment]
You can call `LicenseManager.AddLicense` to add one, see the `EvalLicense` for an example structure: https://github.com/vmware/govmomi/blob/81743157fb5ccf548d6bd5088c25ee6156a359ee/simulator/license_manager.go#L40-L61

Tests can also modify `simulator.EvalLicense` directly, to change the `EditionKey`, `Properties`, etc.  I've never seen a ROBO license before, so not sure how exactly it would look.

**Comment by cgtexmex** [comment]
If DRS is disabled then there are no resource pools and the following flags must be ignored:
```
   --memory value, --mem value                      VCH resource pool memory limit in MB (unlimited=0) (default: <nil>)
   --memory-reservation value, --memr value         VCH resource pool memory reservation in MB (default: <nil>)
   --memory-shares value, --mems value              VCH resource pool memory shares in level or share number, e.g. high, normal, low, or 163840 (default: <nil>)
   
   --cpu value                                      VCH resource pool vCPUs limit in MHz (unlimited=0) (default: <nil>)
   --cpu-reservation value, --cpur value            VCH resource pool reservation in MHz (default: <nil>)
   --cpu-shares value, --cpus value                 VCH VCH resource pool vCPUs shares, in level or share number, e.g. high, normal, low, or 4000 (default: <nil>)
```
We will warn the user that they are not applicable to the current configuration and ignore them.
