### ISSUE TITLE
VM placement algorithm

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7279]
When DRS is not available in a vSphere cluster vic will need to specify the host for VM placement.  That host recommendation will _not_ be attempting to identify the best host, but simply to avoid picking a _wrong_ host.  

An algorithm will be created that will make the recommendation based on identified inputs.  This will require tight collaboration with #7327  

- [x] document design
- [x] gather host metrics for the cluster
- [x] sort hosts based on weighted metrics
- [x] identify least _loaded_ host based on weighted metrics
- [x] unit tests

**Comment by hickeng** [comment]
@dougm FYI vcsim

**Comment by jzt** [comment]
Pretty much done (in verify), but will likely be tweaked over time as we learn during testing.
