### ISSUE TITLE
vic-machine to utilize placement library

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7280]
In environments where DRS isn't required vic-machine will need to create the VCH on a specific host. That host recommendation will be provided via #7279 but vic-machine will need to implement the usage of said recommendation.

- [x] verify license and features require vic placement
- [x] target specific host based on vic placement recommendation
- [x] CI Test Plan
- [x] CI Tests

**Comment by anchal-agrawal** [comment]
Thanks @jzt

**Comment by jzt** [comment]
Closing - Now that`vic-machine` calls directly into the placement logic by way of `vm.PowerOn`, the testing component of this issue is already covered by https://github.com/vmware/vic/pull/7531.
