### ISSUE TITLE
vic-machine: validation failed if dvSwitch exists in ESXi target

### ISSUE THREAD

**Issue by emlin** [vmware/vic#729]
root [ ~/vic/bin ]# ./vic-machine -target esxi-hp-08.rainpole.com -user root -passwd VMware123! -compute-resource /ha-datacenter/host/esxi-hp-08.rainpole.com/Resources -image-store esxi-hp-08-local -management-network "VM Network"
INFO[2016-05-19T11:49:38Z] ### Installing VCH ####
INFO[2016-05-19T11:49:38Z] Generating certificate/key pair - private key in ./docker-appliance-key.pem
INFO[2016-05-19T11:49:38Z] Validating supplied configuration
ERRO[2016-05-19T11:49:40Z] Unable to get network: SystemError
FATA[2016-05-19T11:49:40Z] Validating supplied configuration failed. Exiting...

[6:57] 
In the hostd.log, I see the following:

[6:57] 
2016-05-18T15:23:51.346Z error hostd[32EC4B70] [Originator@6876 sub=PropertyProvider opID=328016ee user=root] Unexpected fault reading property: vim.DistributedVirtualSwitch, GetNetworkResourcePool: N5Vmomi5Fault12NotSupported9ExceptionE(vmodl.fault.NotSupported)
2016-05-18T15:23:51.346Z error hostd[32EC4B70] [Originator@6876 sub=PropertyProvider opID=328016ee user=root] Unexpected fault reading property: vim.DistributedVirtualSwitch, GetRuntime: N5Vmomi5Fault12NotSupported9ExceptionE(vmodl.fault.NotSupported)

[7:00] 
Could we get a better error message bubble up to vic-machine? Probably something along the lines of “VIC cannot use an ESXi host as a target when a DVS is present” or something to that effect

**Comment by dougm** [comment]
Sounds like we should detect if the ESX host is managed by a VC and exit 1 with a friendly error message, before the installer would even get to this point.

**Comment by emlin** [comment]
This sounds good. Is there interface in govmomi?

**Comment by hickeng** [comment]
This can occur even if the ESX is not managed by VC - you can have residual config on the ESX in various scenarios.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by corrieb** [comment]
@emlin. I don't believe this is still an issue. Let's close if not.

**Comment by emlin** [comment]
@corrieb I didn't test it atm, but as comment above, this can occur even if there is left over in ESXi which ever is managed by VC.

@andrewtchin did you ever touch this?
If not, we'd leave it open

**Comment by andrewtchin** [comment]
I have not tested this
