### ISSUE TITLE
VIC builds on new drone infra

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#7293]
There are few changes as part of Drone 0.8. This is to investigate those changes and make necessary updates. Also, this will involve making sure all drone secrets are updated and all build steps run as expected.

A/C:
- VIC build steps run on new drone infra as expected

**Comment by sgairo** [comment]
@mdharamadas1 Would you mind adding an estimate for the investigation work and then move to the backlog? Thanks!

**Comment by mdharamadas1** [comment]
@sgairo We do a team estimation and this will be done in the next planning meeting.
