### ISSUE TITLE
ROBO Support - Test Coverage

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7295]
ROBO support will introduce new features and complexity that will require new / unique tests to be created.  We will use this epic to track the overall testing progress as well as cross reference specific feature tests to their feature epic.

- [ ] Produce Test Plan providing high-level comprehensive testing
- [ ] Breakout individual test cases in issues tracked here and their relevant feature epic

**Comment by mdubya66** [comment]
All issues completed. Closing.
