### ISSUE TITLE
23-2-Future-ISO-Install Nightly Test Failure: connection failure, bad certificate

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#7309]
Seen in 6.0 and 6.5 nightly test run on 2/6.
There are no logs other than console output since installer never completed.
[stdout.txt](https://github.com/vmware/vic/files/1717148/stdout.txt)

**Comment by hickeng** [comment]
The log output explicitly notes that this can related to clock skew:
```
time="2018-02-07T02:55:31Z" level=error msg="Connection failed with TLS error \"bad certificate\" - check for clock skew on the host" 
```
It would have to be quite significant clock skew as we generate the certificates to be valid from 1 day in the past explicitly so minor skews don't cause "certificate is not yet valid" errors.

Only real way to determine what happened here is:
* hit the endpoint with `openssl s_client`.
* hit vicadmin with a browser and looking at the browsers diagnostics for the cert.
* look at the generated certificates directly and compare with timestamps from client, host, and VCH VM.

**Comment by mdubya66** [comment]
Same build has been used in every nightly since 2/23. Closing.
