### ISSUE TITLE
Milestone: vcsim based image management test

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#731]
Add testing of the portlayer storage component via vcsim. The storage model should reflect vSAN frontend behaviours:
* uuid based paths, not symbolics
* only blobs permitted in the root of the datastore (no raw files or directories)

Chosing vSAN is because if the various manipulations we require are written to work with vSAN then they will work on VMFS, but not visa versa.

**Comment by mdubya66** [comment]
Only one issue in this epic. Closing it.
