### ISSUE TITLE
dinv -local and network

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#7316]
May I know how do I start dinv with both -H `tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock` , please?

```
....
INFO[0001] API listen on /var/run/docker.sock
INFO[0001] API listen on [::]:2375

```
if I use dinv -local /usr/bin/dockerd listens only on unix:///var/run/docker.sock.

`INFO[0001] API listen on /var/run/docker.sock`

and while using without it, I can only connect from outside (i.e. -H IP) and cannot use `/var/run/docker.sock:/var/run/docker.sock` for running a container from within.

Early days of using dinv and building a use case around it. My apologies, if I am missing something obvious. 

Thank you.

**Comment by sgairo** [comment]
@andrewtchin Would you take a look at this, perhaps we should open an issue to expand dinv testing? Thanks!

**Comment by malikkal** [comment]
Hi

Not sure if this is the right way.

But, I was impatient and changed the following lines of code and rebuild the image.

```
if !local {
                log.Debug("Let docker listen on all ips")
                dockerArgs = append(dockerArgs, "-H", fmt.Sprintf("tcp://0.0.0.0:%d", port))
        }

to

```
if !local {
                log.Debug("Let docker listen on all ips")
                dockerArgs = append(dockerArgs, "-H", fmt.Sprintf("tcp://0.0.0.0:%d", port))
                dockerArgs = append(dockerArgs, "-H", "unix:///var/run/docker.sock")
        }
```

It works now.

**Comment by andrewtchin** [comment]
Thanks @malikkal we will investigate this.

**Comment by zjs** [comment]
@yuyangbj: Was this fixed as a part of your previous DCH changes?

**Comment by yuyangbj** [comment]
@zjs no, we do not fix it, do you need to add the support in 1.5?

**Comment by zjs** [comment]
I think we should try to include the support; it's a very small change.

**Comment by yuyangbj** [comment]
@zjs ok, will add it today.

**Comment by yuyangbj** [comment]
@malikkal In VIC 1.5 release, I tried to reproduce your problem, but I did not see it. My steps are below, please correct me if i am wrong.

1> Deploy a VCH
2> Deploy a dch-photon with docker 17.06. You can see container 8a294670d136 is started without -local param.

yuyangbj@yuyangbj-vic:~/GoProjects/src/github.com/yuyangbj/vic/bin$ docker --tls ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS                           NAMES
91965d323adf        vmware/dch-photon   "/dinv -tls -local"   18 hours ago        Up 17 hours         10.193.32.178:12378->2375/tcp   kickass_carson
db2e480ba60c        vmware/dch-photon   "/dinv -tls -local"   18 hours ago        Up 18 hours         10.193.32.178:12377->2376/tcp   determined_boyd
8a294670d136        vmware/dch-photon   "/dinv -tls"          19 hours ago        Up 18 hours         10.193.32.178:12376->2376/tcp   quizzical_heyrovsky

3> Log in container 8a294670d136 using command: docker --tls exec -it 8a bash

4> Deploy busybox using command: docker --tls run -v /var/run/docker.sock:/var/run/docker.sock -d --name txtxtx busybox sleep 60

Based on your test, I assume it should be failed, but I deployed busybox successfully.

**Comment by yuyangbj** [comment]
@malikkal Even though I did not reproduce your problem, but I enhanced the code to force to start dockerd with local unix socket, this will create /var/run/docker.sock file every time. But I am still want to see how do you reproduce the problem you mentioned.

https://github.com/vmware/vic-product/pull/2256

**Comment by yuyangbj** [comment]
We support it in VIC 1.5
