### ISSUE TITLE
volume inspect always yields null options

### ISSUE THREAD

**Issue by shadjiiski** [vmware/vic#7325]
`docker volume inspect <volume-name>` always reports `null` for `Options`. It should report the volume options (if any).

**VIC version:**
```
$ ./vic-machine-windows.exe version
vic-machine-windows.exe version v1.3.0-15556-473375a
```

**Deployment details:**

VCH 1.3.0 provisioned on ESX (no vSphere):
```
./vic-machine-windows.exe create \
--target $ESX_IP \
--force \
--user "$ESX_ROOT_USER" \
--password "$ESX_ROOT_PASS" \
--no-tls \
--image-store datastore1 \
--volume-store datastore1:default \
--name vch-1.3.0
```

**Steps to reproduce:**
Create the volume
```
$ docker volume create -d vsphere --opt Capacity=200MB test-volume
test-volume
```
Then inspect it
```
$ docker volume inspect test-volume
[
    {
        "Driver": "vsphere",
        "Labels": {},
        "Mountpoint": "2ba23b48e510520f",
        "Name": "test-volume",
        "Options": null,
        "Scope": ""
    }
]
```
**Actual behavior:**
`Options` are null in the inspect output
**Expected behavior:**
`Options` should be something like
```
"Options": {
    "Capacity": "200MB"
}
```

**Logs:**
[logs.zip](https://github.com/vmware/vic/files/1724219/logs.zip)

**Comment by vburenin** [comment]
Options field is never filled. No option information is preserved when volume is created including volume capacity.
