### ISSUE TITLE
Milestone: vcsim based container creation

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#733]
The most involved portion of vcsim testing is the creation of containerVMs - this depends on previous vcsim milestones that add support for 'image' management, and also 'boot' of a given VM config.

In this scenario we also have to configure the tether to use direct connection rather than serial - this is a config that is already supported in the attach tests, but as with guestinfo may need a mocking build rather than shipping binaries.

**Comment by mdubya66** [comment]
Closing this as both issues are done
