### ISSUE TITLE
nightly 13-2-vMotion-Containers: docker stop "no such container" after migrate

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7338]
Nightly 02/16/18
VC version: 6.0
Test suite: 13-2-vMotion-Container 

[Suites.Group13-vMotion.13-2-vMotion-Container.zip](https://github.com/vmware/vic/files/1734306/Suites.Group13-vMotion.13-2-vMotion-Container.zip)

**Failure Details**
Two failures occurred in this test suite:
1. After migrating container VMs, docker stop on one of the contaienrs gives error `No such container`:
![image](https://user-images.githubusercontent.com/6562128/36347030-565d970e-1412-11e8-90c0-e1cf2bf7ce82.png)
2. During test teardown, after vic-machine delete succeeds, there's trailing datastore. `govc datastore.ls` gives:
```
silly_northcutt-3b41dc31b38a
VCH-0-2468
dc98875a-65ba-86cf-4f74-0200446c668e
2999875a-eb59-dbc8-e284-02004431651b
``` 
and this list contains `VCH-0-2468`

**Rough Investigation**

The failed container ID is `3b41dc31b38a`. docker persona log shows a VM powerOff event, and immediately follows the error from docker stop:
```
Feb 17 2018 02:55:30.147Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:220] [8.712µs] Event Monitor received eventID(297.74) for container(ffdc32afac66) - PoweredOff
Feb 17 2018 02:55:30.442Z DEBUG Calling GET /_ping
Feb 17 2018 02:55:30.476Z DEBUG Calling POST /v1.25/containers/3b41dc31b38a7032965c3bf59ce5cd124daa5cc8335fa656519a19c1f0b2ec3e/stop
...
Feb 17 2018 02:55:30.476Z ERROR Handler for POST /v1.25/containers/3b41dc31b38a7032965c3bf59ce5cd124daa5cc8335fa656519a19c1f0b2ec3e/stop returned error: No such container: 3b41dc31b38a7032965c3bf59ce5cd124daa5cc8335fa656519a19c1f0b2ec3e
```

From portlayer log, after the container VM is powered off, migration of this VM failed. The error message says `Cannot complete operation due to concurrent modification by another operation`:
```
Feb 17 2018 02:54:47.090Z DEBUG Found 2 subscribers to 297.56: events.ContainerEvent - Container 3b41dc31b38a7032965c3bf59ce5cd124daa5cc8335fa656519a19c1f0b2ec3e Removed
...
Feb 17 2018 02:54:47.319Z ERROR op=297.55: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Feb 17 2018 02:54:47.325Z ERROR op=297.55: Reconfigure: failed update to 3b41dc31b38a7032965c3bf59ce5cd124daa5cc8335fa656519a19c1f0b2ec3e with change version 2018-02-17T02:53:35.407629Z: Cannot complete operation due to concurrent modification by another operation.
Feb 17 2018 02:54:47.325Z ERROR op=297.55: Reconfigure: failed update to 3b41dc31b38a7032965c3bf59ce5cd124daa5cc8335fa656519a19c1f0b2ec3e due to ConcurrentAccess, our change version 2018-02-17T02:53:35.407629Z
Feb 17 2018 02:54:47.325Z DEBUG [ END ] op=297.55 [vic/lib/portlayer/exec.Commit:34] [235.038792ms] 3b41dc31b38a7032965c3bf59ce5cd124daa5cc8335fa656519a19c1f0b2ec3e
Feb 17 2018 02:54:47.325Z ERROR op=297.55: Failed to commit handle after getting Migrated event for container VirtualMachine:vm-61: Cannot complete operation due to concurrent modification by another operation.
```

Tracking it down, vmware.log for the appliance VM around the time when docker stop fails shows an rpc call timeout, and the log terminates. Something's down?
```
2018-02-17T02:53:22.657Z| vmx| I125: VigorTransport_ServerSendResponse opID=297.20-2c-97-a28a seq=2158: Completed HotPlugManager request.
2018-02-17T02:53:48.575Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
2018-02-17T02:54:00.801Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
2018-02-17T02:54:05.207Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
2018-02-17T02:54:14.913Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
```

container log bundle:
[Suites.Group13-vMotion.13-2-vMotion-Container-VCH-0-2468-container-logs.zip](https://github.com/vmware/vic/files/1734301/Suites.Group13-vMotion.13-2-vMotion-Container-VCH-0-2468-container-logs.zip)
VCH appliance tether debug and vmware log bundle:
[VCH-0-2468.zip](https://github.com/vmware/vic/files/1734302/VCH-0-2468.zip)
vic-machine.log:
[vic-machine.log](https://github.com/vmware/vic/files/1734303/vic-machine.log)

**Comment by hickeng** [comment]
May well be #6342.
@cgtexmex iirc there was a second issue related to fixvm and a changing moref but I couldn’t dig it up via mobile. Could you add it or correct my recollection

**Comment by cgtexmex** [comment]
There was an issue previously we suspected of the same thing -- it was very intermittent with that issue, so it was closed.  I can't recall the issue number, but if #6342 is addressed I believe it will address this issue as well.

**Comment by anchal-agrawal** [comment]
Needs an estimate - putting in Not Ready.

**Comment by sgairo** [comment]
Seen in 6.0 tests on 3/2:
[Suites.Group13-vMotion.13-1-vMotion-VCH-Appliance-VCH-0-6408-container-logs.zip](https://github.com/vmware/vic/files/1781780/Suites.Group13-vMotion.13-1-vMotion-VCH-Appliance-VCH-0-6408-container-logs.zip)
[VCH-0-6408-vmware.log](https://github.com/vmware/vic/files/1781782/VCH-0-6408-vmware.log)
[VCH-0-6408-tether.debug.zip](https://github.com/vmware/vic/files/1781785/VCH-0-6408-tether.debug.zip)
[vic-machine.log](https://github.com/vmware/vic/files/1781787/vic-machine.log)

**Comment by anchal-agrawal** [comment]
Setting to p1 for now - this has been reported twice and seems to be related to #6342 (from the comments above). #6342 is also marked p1.

**Comment by mdubya66** [comment]
Unseen in a while. Closing.
