### ISSUE TITLE
Incorrect Documentation: We do not support providing `proto` for nfs volume store creation

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#7343]
Currently this link: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/volume_stores.html

states that this: `nfs://datastore_address/path_to_share_point?uid=1234&gid=5678&proto=tcp:nfs_volume_store_label` is a valid input to the nfs volume store creation. 

While this command will not fail. the `proto=tcp` is ignored and not supported. We want to avoid confusing customers into thinking this will work so any mention of setting mount communication protocol should be removed from the documentation.

**Comment by morris-jason** [comment]
@matthewavery proto seems like a commonly supplied option. If we are removing it from the docs, we need to specify why Vic doesn't parse it, and any impact that has on the user.

**Comment by matthewavery** [comment]
@morris-jason the only reason it is not supplied is that we attempt tcp always right now. This is partly due to us just not parsing the option. and partly due to some investigation needed on our go-nfs-client surrounding how we would specify that.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #1438](https://github.com/vmware/vic-product/issues/1438) via [**ZenHub**](https://www.zenhub.com/)
