### ISSUE TITLE
vic-machine install query mode

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#739]
Implement a query mode for vic-machine install. This mode should show all of the legal options for the install parameters for a VCH. This will enhance interactive creation of a VCH when you're not sure what is configured in the cluster or ESX.

**Comment by hickeng** [comment]
I've been planning something like this. The options are:
1. tab autocomplete - requires an additional script on linux, unsure if it's available on windows
2. interactive shell implemented by vic-machine
3. dry-run option to vic-machine and structured validation of inputs.

**Comment by dougm** [comment]
In the meantime, for the cluster/esx related path options, you can use 'govc ls' to browse in the inventory.  For example:
```
$ govc ls
/dc1/vm
/dc1/network
/dc1/host
/dc1/datastore

$ govc ls -l datastore
/dc1/datastore/vsanDatastore (Datastore)

$ govc ls -l network
/dc1/network/VM Network (Network)
/dc1/network/DSwitch (VmwareDistributedVirtualSwitch)
/dc1/network/DSwitch-DVUplinks-9 (DistributedVirtualPortgroup)
/dc1/network/ExternalNetwork (DistributedVirtualPortgroup)
/dc1/network/InternalNetwork (DistributedVirtualPortgroup)

$ govc ls -l host
/dc1/host/cluster1 (ClusterComputeResource)

$ govc ls -l host/*
/dc1/host/cluster1/Resources (ResourcePool)
/dc1/host/cluster1/10.143.2.208 (HostSystem)
/dc1/host/cluster1/10.143.2.213 (HostSystem)
/dc1/host/cluster1/10.143.2.216 (HostSystem)
```

**Comment by bradmeiseles** [comment]
I like this query mode idea. @stuclem we also need to include the syntax in the documentation so users can compose the paths themselves.

**Comment by stuclem** [comment]
Yep, @bradmeiseles, we have a doc issue open to track this: https://github.com/vmware/vic/issues/851.

**Comment by emlin** [comment]
What about wrap few options from govc to vic-machine? something like vic-machine ls-resources. vic-machine browse-datastore, etc.

What my concern is that we're creating more format. So far the datastore and network are simple name only, but we plan to add file directory into datastore configuration, and add network alias, ip range into network. Those will not be govc format only.

**Comment by emlin** [comment]
Currently, we already support multiple compute resource format, and has resource suggesting if that parameter is wrong, do we still need this resource query feature?  @hickeng @mdubya66

**Comment by mdubya66** [comment]
medium for discussion and UX purposes.

**Comment by emlin** [comment]
UX should not rely on that, cause they could search from VC API directly

**Comment by zjs** [comment]
Given that we now have a UI for VCH creation, is this still functionality we'd want to expose on the command line? If so, is it still `priority/medium`?
