### ISSUE TITLE
Tether stream handling tests - close, detach, reattach

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#740]
The tether needs to support the following - this is breaking out some of the remainder of test scenarios from #439:
- [ ] propagation of close(stdin) - this should cause programs such as cat to exit.
- [ ] the client detaching should cause the channel to be closed so we're not unnecessarily copying data, but must leave the stdi/o file handles for the process open (if they were previously).
- [ ] connection dropped - should be handled in the same way as detach when detected
- [ ] reattach after detach or drop should succeed

This is supporting work for PR #681

**Comment by mdubya66** [comment]
Needs an estimate

**Comment by caglar10ur** [comment]
Closing this (completed)
