### ISSUE TITLE
Milestone: docker attach

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#741]
This covers the end-to-end establishment of an interactive session between the user and the container process.

This traverses:
* docker client
* docker personality
* port layer interaction component
* tether

**Comment by corrieb** [comment]
@sflxn Everything other than the testing seems to be done for this Epic. Are there any other issues that should be associated with it?

**Comment by sflxn** [comment]
Not sure why the epic continues to say 5 of 8 issues complete.  Looked at every one of them, and they are closed, done, or merged.

**Comment by mdubya66** [comment]
reopening this as #740 is not complete.
