### ISSUE TITLE
Move overrideArchiveWrite and overrideArchiveRead to cmd/tether

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#7414]
`lib/tether/toolbox.go` contains functions that are relevant only to the tether as it runs inside of containers and should be moved to `cmd/tether/toolbox.go`, specifically `overrideArchiveWrite` and `overrideArchiveRead`.

**Comment by matthewavery** [comment]
@gigawhitlocks I believe @morris-jason has already taken an issue to do this and had a PR(maybe?) awhile back...

**Comment by matthewavery** [comment]
Yep here you are @gigawhitlocks 
#5933

**Comment by gigawhitlocks** [comment]
Nice
