### ISSUE TITLE
Add documentation surrounding container users for NFS volume support

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#7442]
We will need to add some more information surrounding NFS share point(exports) permissions. After talking to @dbarkelew it is necessary to document that the user running the container will effect the container's ability to r/w/x on the container based on the unix permissions of items within the nfs volume. I am capturing the full result of the conversation with @dbarkelew below.

```
Documentation explaining that the container mounts with root, then access with the user that runs entrypoint.sh or `-u` would help. If nothing more acknowledge different users need to be accounted.
```

The above statement is requesting documentation that right now the tether will mount the volume as root(since the tether runs as root tmk). This means that root must be a valid uid/gid for mounting the export. Additionally, if the container is running with a non root user then the export must allow that non root user(via permissions) to r/w/x into the share.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #1464](https://github.com/vmware/vic-product/issues/1464) via [**ZenHub**](https://www.zenhub.com/)
