### ISSUE TITLE
Migrate appliance to tether

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#746]
The tether is used to:
* configure networks
* launch processes with specific arguments and environment
* handle process exit, relaunch, and status reporting

This is the same set of requirements that we have for the appliance, currently handled by the launcher.sh script.

This issue covers:
- [x] update of the appliance iso to package and launch the tether
- [x] update of the tether to handle component relaunch on death
- [ ] consolidation between bootstrap and appliance isos where available
- [ ] launching of the appliance processes via the tether, and status reporting to vic-machine (see portlayer start blocking)
- [ ] trigger of configuration reload via vsphere event on extraconfig (see portlayer start blocking). Depends on #742 
- [ ] update of the tether to handle component configuration change - this one is tentative as I'm unsure which of the implementation approaches is preferable at this time.

**Comment by hickeng** [comment]
This touches on a lot on milestone #747 but not with the same level of structure required. We may find that #747 is partially addressed by this.

**Comment by hickeng** [comment]
Using the tether makes sense, but setting up the serial devices and so on does not - logging is handled differently for the appliance.
This is tracked in #756

**Comment by dougm** [comment]
Opened a PR to support hydrating a ManagedObjectReference to object.Reference with InventoryPath set: https://github.com/vmware/govmomi/pull/527

**Comment by hickeng** [comment]
The core of this is in place in [my branch](https://github.com/hickeng/vic/tree/746) - however the remaining items need to be addressed:
- [ ] component relaunch
- [ ] update to state/status reporting
- [ ] unit tests for vic-machine changes
- [ ] testing of vic-machine against vCenter

**Comment by hickeng** [comment]
This has taken significantly longer than anticipated due to having to complete additional work needed in vic-machine (see #665, #666, #686)

**Comment by hickeng** [comment]
The update to status/state from the less concrete started/exitstatus values will not go in in with this fix.
