### ISSUE TITLE
VSAN based docker volumes can be created but not attached to containers

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#7481]
@steviestainz commented on [Thu Mar 08 2018](https://github.com/vmware/vic-product/issues/1468)

Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: **Version 6.5.0.13000 Build 7801515**
- Embedded or external PSC: **Embedded**
- Filename of the OVA you deployed: **vic-v1.3.1-3409-132fb13d.ova**
- Does the VIC appliance receive configuration by DHCP? **yes**
- What stage of the Appliance Lifecycle is the VIC appliance in? **Running**

- Attach the VIC appliance support bundle 

VIC appliance log bundle: [vic_appliance_logs_2018-03-08-14-13-43.tar.gz](https://github.com/vmware/vic-product/files/1793437/vic_appliance_logs_2018-03-08-14-13-43.tar.gz)
Virtual container host log bundle: [logs.zip](https://github.com/vmware/vic-product/files/1793424/logs.zip)

OPTIONAL, but helpful:

- IP address of VIC appliance: **192.168.0.187**
- Hostname of VIC appliance: **photon**
- IP address of vCenter Server: **192.168.0.111**
- Hostname of vCenter Server: **vcenter**
- IP address of virtual container host: 192.168.0.193

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?

Deploying simple docker container from docker hub fails, with the following error:

Command line input: 

vic steve$ `docker -H 192.168.0.193:2376 --tls run -v shaggy:/tmp tutum/hello-world:latest`

> docker: Error response from daemon: Server error from portlayer: ServerFaultCode: Permission to perform this operation was denied.

Log file snippet (port-layer.log): 
`https://192.168.0.193:2376/v1.24/containers/create?name=hello-world-mcm734-68815303181 returned error 500 for POST. id 1430239 message Server error from portlayer: ServerFaultCode: Permission to perform this operation was denied.; Reason: {"message":"Server error from portlayer: ServerFaultCode: Permission to perform this operation was denied."}`

The wider context within this log file includes the following output:

[port-layer-excerpt.log](https://github.com/vmware/vic-product/files/1793490/port-layer-excerpt.log)

**User Statement:**

I have completed a clean (and otherwise fully functioning) build lab environment based around a three host VSAN cluster (FTT=1) using ESXi 6.5 U1 and latest vCenter 6.5. My first installation attempt of VIC 1.3.1 has been straight forward and I am able to successfully deploy/destroy container hosts and tested with many containers without any problems. However whenever docker is asked to attach a volume to a container image which doesn't use persistent storage, or when a docker file includes references to volumes the above issue occurs. Manually creating and removing volumes from the command line is always successful - it just seems to be the attaching which fails.

Please see the excerpt above which relates to the simple command line deployment of a tutum/hello-world container. I can successfully deploy the container if I don't specify a volume e.g. `-v shaggy:/tmp`

I have compared the ops-user role and permissions in vCenter with the VIC documentation and these are all correct, however I'm not able to figure out which permissions/role is lacking during this error scenario. I had originally noticed that the hostd logs for each of the hosts were empty in the attached log bundle and assumed that this could be caused by using non-persistent scratch partition/logging and have since retested using a persistent iSCSI based scratch location - to no effect - however it seems like this might be a known issue in VIC [#3397](https://github.com/vmware/vic/issues/3397).

Happy to provide remote access to the environment, as I'm currently completing a rehearsal for production installation and need to understand this problem better. Thanks!

---

@AngieCris commented on [Thu Mar 08 2018](https://github.com/vmware/vic-product/issues/1468#issuecomment-371550711)

Cc: @anchal-agrawal ?
(also this ticket should probably be moved to vmware/vic repository?)

---

@anchal-agrawal commented on [Thu Mar 08 2018](https://github.com/vmware/vic-product/issues/1468#issuecomment-371553734)

Yes, thanks Angie!

@steviestainz thanks for the detailed bug report! I'm moving this to the vmware/vic repo and we will triage it further there.

**Comment by anchal-agrawal** [comment]
Ping @matthewavery - let's triage this further when we can.

**Comment by hickeng** [comment]
@steviestainz I recently ran into something very similar. I found it necessary to add a privilege to the `VCH - datacenter` role that is not stated in our documentation. Copied from my finding:

```
1. Add Virtual Machine->Configuration->Add Existing Disk to the Datacenter role
2. Add Global->Enable/Disable Method to the Endpoint role
3. Add code comments or implement - if DVS is in a network folder:
  a. apply read-only role to the folder and propagate (we need DVS properties)
  b. Datacenter role does NOT need to propagate (propagation is to gain read access to DVS properties).
```

The one I think is impacting you is (1) in that list. (2) is _sort of optional_ in that it will disable the `Delete From Disk` option in the UI/API to prevent deletion of containerVMs while they still have volume or image disks attached. This is done to prevent accidents but the lack of the permission does not prevent function.

**Comment by steviestainz** [comment]
Thanks @hickeng, your explanation above worked perfectly. I'm afraid that the documentation is so clear in this respect that you could easily believe everything to be set up correctly but yet miss the need to create a folder for the dvswitch and grant read-only permissions to the operations user. Perhaps this is the real cause of the issue since creating the volume itself is always successful, somehow the attachment of the container to the volume requires some dvswitch visibility. I'm really pleased to have got this resolved and move past the issue. Who takes care of updating the documentation and the code to fix up the permissions?

**Comment by hickeng** [comment]
@steviestainz There are two PRs open for the respective doc updates.
[Open - note about network folders](https://github.com/vmware/vic-product/pull/1458/files?short_path=3f0e85a#diff-3f0e85aece22f5100022746885a50907)

[Merged - correction of datacenter privileges](https://github.com/vmware/vic-product/commit/7cb72f753c8793bf7c8f5c74b449cf5d2b8fac9b?short_path=3f0e85a#diff-3f0e85aece22f5100022746885a50907)

Our docs are a work in progress, as all documentation is! If you find areas that are unclear, need rewording, need a diagram, are using unexpected terminology, etc please do open an issue against vmware/vic-product or a pull request with proposed updates.

@stuclem is our arbiter of documentation and if there's anything that requires live conversation over github issues then there's vmwarecode.slack.com/messages/vic-product.

I'm closing this issue but please comment further for @stuclem regarding doc clarity if needed.

**Comment by stuclem** [comment]
@hickeng and @steviestainz I have made a doc update in https://github.com/vmware/vic-product/pull/1458/commits/ad902ee333aa97534cec1d887a21fb6c0b2e4c65. Hopefully this clarifies matters!
