### ISSUE TITLE
vic-machine upgrade supports inventory folders

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7497]
vic-machine has been updated to support folders for create and delete.  The support of folders needs to be extended to upgrade.

This is primarily needed for VCHs deployed prior to 1.4 and the folder support.  The following approach can be utilized:
- After successful upgrade of the appliance VM
- Determine VCH parent folder
- if not the vm folder, then no additional processing - upgrade complete
- create a uniquely named folder (not the same name as appliance: i.e. `/vm/temp-vch-001`)
- move the VCH appliance and all VCH containerVMs into newly created folder
- rename folder to match the VCH appliance name
- upgrade complete

- [ ] update upgrade logic
- [ ] ensure backward compatability
- [ ] update / add to ci upgrade tests

**Comment by anchal-agrawal** [comment]
This issue has several integration tests tagged against it. Those tests must be enabled and addressed before closing this issue. See #7523

**Comment by cgtexmex** [comment]
`vic-machine` configure and upgrade are very much intertwined -- if either one are to support folders then they both need to support folders.
