### ISSUE TITLE
5-6-2 VSAN Complex Nightly Test Failure: Keyword timeout 1 hour 50 minutes exceeded.

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#7512]
Need to be sure to make this terminate gracefully so we can collect the logs.

**Comment by sgairo** [comment]
Seen in 5-5 test on 3/13 as well.

**Comment by sgairo** [comment]
5-6-2 logs:
[Suites.Group5-Functional-Tests.5-6-2-VSAN-Complex-VCH-0-3698-container-logs.zip](https://github.com/vmware/vic/files/1812898/Suites.Group5-Functional-Tests.5-6-2-VSAN-Complex-VCH-0-3698-container-logs.zip)
[VCH-0-3698-vmware.log](https://github.com/vmware/vic/files/1812900/VCH-0-3698-vmware.log)
[vic-machine.log](https://github.com/vmware/vic/files/1812901/vic-machine.log)
[VCH-0-3698-tether.debug.zip](https://github.com/vmware/vic/files/1812902/VCH-0-3698-tether.debug.zip)

**Comment by sgairo** [comment]
5-5 logs:
[stdout.txt](https://github.com/vmware/vic/files/1812915/stdout.txt)
[vpxd.log](https://github.com/vmware/vic/files/1812917/vpxd.log)
[log.html.zip](https://github.com/vmware/vic/files/1812920/log.html.zip)

**Comment by sgairo** [comment]
For 5-5, I think we should decrease the timeout so that our retry to doesnt terminate on the 110 minute timeout, should fail quicker than 40 minutes.

**Comment by sgairo** [comment]
5-6-2 logs:
[stdout.txt](https://github.com/vmware/vic/files/1815985/stdout.txt)
[log.html.zip](https://github.com/vmware/vic/files/1815987/log.html.zip)
[vic-machine.log](https://github.com/vmware/vic/files/1815989/vic-machine.log)

**Comment by rogeliosanchez** [comment]
Re-opening

Seen in Nightly 6.0 - 2018-04-19

5-6-2-VSAN-Complex
Deploy Nimbus Testbed
![screen shot 2018-04-20 at 4 29 34 pm](https://user-images.githubusercontent.com/26554503/39074687-0f757ab0-44b8-11e8-8ae3-c5427de1af3b.png)

Vic machine 
[vic-machine.log](https://github.com/vmware/vic/files/1933738/vic-machine.log)

Nightly Summary
[60.zip](https://github.com/vmware/vic/files/1933742/60.zip)

Link to logs
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-19-20-32-56.zip?authuser=1

**Comment by mhagen-vmware** [comment]
p1 priority for the test improvement and that this is rarely seen
