### ISSUE TITLE
3/13/18 5-3 ELM nightly failure: unknown target, no such host

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#7513]
```govc: Post https://unknown/sdk: dial tcp: lookup unknown on 10.118.81.1:53: no such host```

While trying to deploy multiple esxi servers in parallel, one came up with an unknown ip which then caused the above failure when trying to set a password. 

[Suites.Group5-Functional-Tests.5-3-Enhanced-Linked-Mode.zip](https://github.com/vmware/vic/files/1811741/Suites.Group5-Functional-Tests.5-3-Enhanced-Linked-Mode.zip)
[vic-machine.log](https://github.com/vmware/vic/files/1811743/vic-machine.log)

**Comment by andrewtchin** [comment]
Closing no repro, nimbus networking issue
