### ISSUE TITLE
Improve basic positive and negative integration testing for the VCH List API

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7515]
This issue tracks improving the integration test coverage for the VCH List API's basic functionality.

This includes at least the following tests:
- [x] Without creating any VCHs, verify that an empty list is properly returned 
- [ ] Create two VCHs, power one of them off, and verify both are returned in the list, with correct information for each 
- [ ] Ensure that a VCH in one datacenter is not returned when listing the VCHs in another datacenter

As a part of this work, the "Basic Validation" and "Negative Cases" portions of `23-02-VCH-List.md` should be updated to document the implementation details of the tests.

**Comment by singhshwetaQE** [comment]
As per discussion with Angie and Zach:
Create two VCHs, power one of them off, and verify both are returned in the list, with correct information for each - Power on/off functionality has not been implemented. (test case skipped)

 Ensure that a VCH in one datacenter is not returned when listing the VCHs in another datacenter (this test cannot be implemented as part of CI test, need to write manual test for this scenario)

**Comment by andrewtchin** [comment]
Should we leave this issue open or open a new issue to track the remaining test cases that are needed?

**Comment by singhshwetaQE** [comment]
I think we can close this issue and open new issue to track the remaining test cases
