### ISSUE TITLE
Improve basic positive and negative integration testing for the VCH Inspect API

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7517]
This issue tracks improving the integration test coverage for the VCH Inspect API's basic functionality.

This includes at least the following tests:
- [x] Create a simple VCH and verify that its settings can be accurately inspected
- [ ] Create a complex VCH and verify that its settings can be accurately inspected 
- [x] Attempt to inspect a VCH in an invalid datacenter
- [x] Attempt to inspect a VCH in with an invalid ID
- [ ] Attempt to inspect a VCH which has been deleted
- [ ] Attempt to inspect a non-VCH VM by supplying its ID as if it were a VCH 

As a part of this work, the "Basic Validation" and "Negative Cases" portions of `23-04-VCH-Inspect.md` should be updated to document the implementation details of the tests.

**Note**: It is possible that some coverage of this functionality is provided as a part of `23-03-VCH-Create.robot`. The best way to address this may involve simply adjusting that suite to formally cover both create and inspect, and enhancing those tests to cover the above scope.

**Comment by AngieCris** [comment]
Old ticket about inspect API e2e tests: https://github.com/vmware/vic/issues/6031
PR containing some minimal inspect API tests: https://github.com/vmware/vic/pull/7290

**Comment by AngieCris** [comment]
@rogeliosanchez I'll try getting #7290 in first so that there's some minimal testing as a starting point
