### ISSUE TITLE
Integrate integration tests to continuous integration

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#752]
Use new drone instance for end to end testing

For all PRs:
* Build
* Unit test
* Integration test
    * Save logs to GC storage even if tests fail

After PR is merged, on `vic/master`:
* Repeat above
* Report coverage
* Create artifact `vic_$BUILD.tar.gz`
* Upload artifact to bintray

**Comment by hickeng** [comment]
This should close #672 when complete.

**Comment by andrewtchin** [comment]
Resolved with https://github.com/vmware/vic/pull/707
