### ISSUE TITLE
Nightly 6.0 - 5-22-NFS-Volume - 2018-03-15 - Inspect failed due to no IP address

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#7541]
**VIC version:**

V1.4.0-DEV-17572-42375AA

**Deployment details:**

Nightly 6.0
5-22-NFS-Volume Docker Inspect Mount Data after Reboot

**Logs:**

```
time="2018-03-16T04:35:03Z" level=info msg="### Inspecting VCH ####" 
time="2018-03-16T04:35:03Z" level=info msg="Validating target" 
time="2018-03-16T04:35:04Z" level=warning msg="Disabling ha-host hostd.log collection (ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.)" 
time="2018-03-16T04:35:04Z" level=info
time="2018-03-16T04:35:04Z" level=info msg="VCH ID: VirtualMachine:3" time="2018-03-16T04:35:04Z" level=info 
time="2018-03-16T04:35:04Z" level=info msg="Installer version: v1.4.0-dev-17572-42375aa" 
time="2018-03-16T04:35:04Z" level=info msg="VCH version: v1.4.0-dev-17572-42375aa" 
time="2018-03-16T04:35:04Z" level=info 
time="2018-03-16T04:35:04Z" level=info msg="VCH upgrade status:" 
time="2018-03-16T04:35:04Z" level=info msg="Installer has same version as VCH" 
time="2018-03-16T04:35:04Z" level=info msg="No upgrade available with this installer version" 
time="2018-03-16T04:35:04Z" level=error msg="No client IP address assigned" 
time="2018-03-16T04:35:04Z" level=error msg="No client IP address assigned" 
time="2018-03-16T04:35:04Z" level=error msg=-------------------- 
time="2018-03-16T04:35:04Z" level=error msg="vic-machine-linux inspect failed: inspect failed\n" 
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-15-20-32-56.zip?authuser=1

@hickeng edit for additional search terms:
endpointVM tether.debug:
```
Mar 16 2018 04:35:49.630Z WARN  no addresses set on client interface
2018/03/16 04:35:49 failed to find primary IP
```
```
retrying "DHCP request": errno=11, error=resource temporarily unavailable
```
vmware.log - sigificant delay after full boot before VMXNET3 entries are present:
```
2018-03-18T01:55:33.521Z| vcpu-0| I125: VMXNET3 user: Ethernet0 Driver Info: version = 17041408 gosBits = 2 gosType = 1, gosVer = 0, gosMisc = 0
```

**Comment by hickeng** [comment]
Looking at this bundle I see that the following tests failed, due to failure to initialize new VCH in a timely manner:
Suite: `5-21-Datastore-Path`
Tests: `Datastore - DS Scheme Specified in Volume Store`, `Datastore - Space in Path with Scheme `

**Datastore - DS Scheme Specified in Volume Store**
VCH-0-8724 - for whatever reason we did not collect logs for this install failure.

**Datastore - Space in Path with Scheme**:
This eventually got an IP address but a retry was required  (VCH-0-3700) and there's a 200s delay:
```
Mar 17 2018 03:10:16.648Z DEBUG [BEGIN]  [vic/lib/tether.(*BaseOperations).Apply:606] applying endpoint configuration for public
Mar 17 2018 03:10:16.652Z DEBUG got link name: "eth0"
Mar 17 2018 03:10:16.654Z INFO  Renaming link eth0 to public
Mar 17 2018 03:10:16.657Z DEBUG got link name: "public"
Mar 17 2018 03:10:16.665Z DEBUG &{Common:{ExecutionEnvironment: ID:1184 Name:public Notes:} Static:false IP:<nil> Assigned:{IP:<nil> Mask:<nil>} Network: DHCP:<nil> Ports:[] Internal:false configured:false}
<snip>
Mar 17 2018 03:10:16.716Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).discoverPacket:155] [15.869854ms] 
Mar 17 2018 03:10:20.244Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).requestPacket:162]
Mar 17 2018 03:10:20.248Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).setOptions:378]
Mar 17 2018 03:10:20.252Z DEBUG opts=dhcp4.Options{0x32:[]uint8{0xa, 0xa1, 0xf1, 0xe5}, 0x36:[]uint8{0xa, 0xa2, 0xcc, 0x1}, 0x37:[]uint8{0x1, 0x3, 0x6}, 0x3d:[]uint8{0xff, 0x1, 0xbe, 0x7, 0x7a, 0x0, 0x2, 0x0, 0x0, 0x1a, 0xdc, 0x9a, 0x69, 0x7c, 0xc2, 0xca, 0xaf, 0x9, 0x5c}, 0x35:[]uint8{0x3}}
Mar 17 2018 03:10:20.263Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).setOptions:378] [14.37877ms] 
Mar 17 2018 03:10:20.268Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).requestPacket:162] [24.025202ms] 
Mar 17 2018 03:13:41.913Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).request:187] [3m25.21590886s] 
Mar 17 2018 03:13:41.917Z DEBUG retrying "DHCP request": errno=11, error=resource temporarily unavailable
Mar 17 2018 03:13:41.920Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).request:187]
Mar 17 2018 03:13:41.923Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).discoverPacket:155]
Mar 17 2018 03:13:41.926Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).setOptions:378]
Mar 17 2018 03:13:41.929Z DEBUG opts=dhcp4.Options{0x37:[]uint8{0x1, 0x3, 0x6}, 0x35:[]uint8{0x1}, 0x3d:[]uint8{0xff, 0x1, 0xbe, 0x7, 0x7a, 0x0, 0x2, 0x0, 0x0, 0x1a, 0xdc, 0x9a, 0x69, 0x7c, 0xc2, 0xca, 0xaf, 0x9, 0x5c}}
Mar 17 2018 03:13:41.935Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).setOptions:378] [9.40074ms] 
Mar 17 2018 03:13:41.939Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).discoverPacket:155] [16.172336ms] 
Mar 17 2018 03:13:44.958Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).requestPacket:162]
Mar 17 2018 03:13:44.961Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).setOptions:378]
Mar 17 2018 03:13:44.964Z DEBUG opts=dhcp4.Options{0x32:[]uint8{0xa, 0xa1, 0xf1, 0xe5}, 0x35:[]uint8{0x3}, 0x37:[]uint8{0x1, 0x3, 0x6}, 0x3d:[]uint8{0xff, 0x1, 0xbe, 0x7, 0x7a, 0x0, 0x2, 0x0, 0x0, 0x1a, 0xdc, 0x9a, 0x69, 0x7c, 0xc2, 0xca, 0xaf, 0x9, 0x5c}, 0x36:[]uint8{0xa, 0xa2, 0xcc, 0x1}}
Mar 17 2018 03:13:44.973Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).setOptions:378] [11.760687ms] 
Mar 17 2018 03:13:44.976Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).requestPacket:162] [18.477057ms] 
Mar 17 2018 03:13:44.984Z DEBUG OpCode: 2, HType: 1, HLen: 6, Hops: 0, XId: [84 27 67 54], Secs: [0 0], Flags: [128 0], CIAddr: 0.0.0.0, YIAddr: 10.161.241.229, SIAddr: 10.162.220.9, GIAddr: 10.161.255.251, CHAddr: 00:0c:29:91:d6:f3, Cookie: [99 130 83 99], Broadcast: true
<snip>
Mar 17 2018 03:13:45.048Z INFO  setting ip address 10.161.241.229/19 for link public
```
We gave up waiting in vic-machine about 45s before the address was acquired.

**Comment by andrewtchin** [comment]
Off by one day ;-) updated link

**Comment by anchal-agrawal** [comment]
I'm inclined to mark this as a p1 as it seems to be caused due to network difficulties in the infra.

**Comment by hickeng** [comment]
Given there's a 3 min delay during virtual hardware initialization, there is a high confidence probability that this is either nimbus/nested issue or a hypervisor issue. More concerning is the #7542 failure where the vmxnet3 NIC **never** reported initialized in the vmware.log.

**Comment by hickeng** [comment]
I've moved this to backlog - it should be followed up on, but at this point we need a vcsupport bundle and a bugzilla opened against ESX.

**Comment by rogeliosanchez** [comment]
Seen on Nightly 6.5 - 2018-04-16 - 5-4-High-Availiability.

VIC version:  v1.4.0-dev-0-b6c0988

5-4-High-Availiabilty: Wait For VCH Initialization

- error msg="No client IP address assigned" ' does not contain 'DOCKER_HOST=
- Keyword 'VCH Docker Info' failed after retrying 12 times. The last error was: Cannot set variables: Expected 2 return values, got 1

![screen shot 2018-04-17 at 2 27 40 pm](https://user-images.githubusercontent.com/26554503/38903160-32ce767a-4269-11e8-8c0d-5533943bc0a5.png)

Vic-machine
[vic-machine.log](https://github.com/vmware/vic/files/1921891/vic-machine.log)

VCH Logs
[vch-0-3329.zip](https://github.com/vmware/vic/files/1921892/vch-0-3329.zip)

Nightly Summary
[65.zip](https://github.com/vmware/vic/files/1921893/65.zip)

Link to logs:
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-16-03-54-06.zip?authuser=1

**Comment by rogeliosanchez** [comment]
Seen on Nightly 6.7 - 2018-04-16

VIC version: v1.4.0-dev-0-b6c0988

5-4-High-Availiabilty: Wait For VCH Initialization

- error msg="No client IP address assigned" ' does not contain 'DOCKER_HOST=
- Keyword 'VCH Docker Info' failed after retrying 12 times. The last error was: Cannot set variables: Expected 2 return values, got 1

Vic machine
[vic-machine.log](https://github.com/vmware/vic/files/1922022/vic-machine.log)

VCH Logs
[vch-0-6861.zip](https://github.com/vmware/vic/files/1922020/vch-0-6861.zip)

Nightly Summary
[67.zip](https://github.com/vmware/vic/files/1922023/67.zip)

Link to logs:
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-16-09-16-12.zip?authuser=1

**Comment by hickeng** [comment]
Checking the vmware.log for the endpointVM for the 2018-04-16 set we have an **8 minute** delay before the second NIC initializes, and that's why we have not reported an IP address in that time:

From VCH-0-6861-vmware.log:
```
2018-04-16T17:23:27.520Z| vcpu-0| I125: Tools: Changing running status: 2 => 1.
2018-04-16T17:23:29.069Z| vcpu-0| I125: VMXNET3 user: Ethernet1 Driver Info: version = 17041408 gosBits = 2 gosType = 1, gosVer = 0, gosMisc = 0
2018-04-16T17:23:43.756Z| vmx| I125: VigorTransportProcessClientPayload: opID=HB-SpecSync-host-24@93-441c8af-f8-b7e8 seq=466: Receiving Sched.SetResourceGroup request.
2018-04-16T17:23:43.756Z| vmx| I125: VigorTransport_ServerSendResponse opID=HB-SpecSync-host-24@93-441c8af-f8-b7e8 seq=466: Completed Sched request.
2018-04-16T17:31:41.762Z| vcpu-0| I125: VMXNET3 user: Ethernet0 Driver Info: version = 17041408 gosBits = 2 gosType = 1, gosVer = 0, gosMisc = 0
2018-04-16T17:31:42.462Z| vcpu-0| A100: ConfigDB: Setting guestinfo.vice..init.sessions|vicadmin.detail.starttime = <not printed>
2018-04-16T17:31:42.706Z| vcpu-0| A100: ConfigDB: Setting guestinfo.vice..init.sessions|docker-personality.detail.starttime = <not printed>
2018-04-16T17:31:42.856Z| vcpu-0| A100: ConfigDB: Setting guestinfo.vice..init.sessions|port-layer.detail.starttime = <not printed>
```

Enquiring with @dbarkelew as to whether this is something GSS is aware of and if not, which group to open it against.

**Comment by zjs** [comment]
Issue unsolved; work should be done in the Epic (instead of investigating this specific test failure).
