### ISSUE TITLE
vic-machine delete fails if there are pulled images

### ISSUE THREAD

**Issue by isyarov** [vmware/vic#7549]
Running vic-machine-{os} delete fails every time if there are pulled images.
The VCH is created with the vic-machine command using a vCenter server as a target
After the command fails the VM and resource pool remain in place, the VM is in off state. The command succeeds if there are no images pulled.

Steps to reproduce:

1.Create a VCH with minimal configuration 
```
./vic-machine-linux create --target {vcenter-ip} --user {username} --password {password} --bridge-network vch-bridge --image-store datastore0 --volume-store datastore0/volumes:default --no-tlsverify --thumbprint {vcenter-cert-thumbprint} --name virtual-container-host
```
2.Pull an image with a docker client
```
docker --tls -H {VCH-IP}:2376 pull alpine
```
3.Try to delete the VCH
```
./vic-machine-linux delete --target {vcenter-ip} --user {username} --password {password} --force --name virtual-container-host
```

The command output with **--debug 3** is as follows:
```
INFO[0000] ### Removing VCH ####
DEBU[0000] Accepting host "###" thumbprint ###
DEBU[0000] Creating VMOMI session with thumbprint ###
DEBU[0000] Session Environment Info:                     API Type=VirtualCenter API Version=6.5 Build=7092793 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=d7548279-cca9-4d40-859b-177c379cce90 Vendor="VMware, Inc." Version=6.5.0
DEBU[0000] vSphere resource cache populating...
DEBU[0000] Cached dc:
DEBU[0000] Cached cluster:
DEBU[0000] Cached host:
DEBU[0000] Cached pool:
DEBU[0000] Cached folders:
DEBU[0000] Error count populating vSphere cache: (1)
DEBU[0000] new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
INFO[0000] Validating target
DEBU[0000] Using default resource pool for compute resource: "/vcqaDC/host/cls/Resources"
DEBU[0000] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0000] Cannot find image stores from configuration; attempting to find from vm datastore
DEBU[0000] properties: [datastore summary.runtime.connectionState]
INFO[0001]
INFO[0001] VCH ID: VirtualMachine:vm-34
DEBU[0001] properties: [config.extraConfig summary.runtime.connectionState]
INFO[0001] Removing VMs
DEBU[0001] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0001] No disks found attached to VM
INFO[0001] Removing image stores
DEBU[0001] Failed to delete "[datastore0] virtual-container-host/VIC": Cannot delete file [datastore0] virtual-container-host/VIC
DEBU[0001] Attempt to delete top level folder [datastore0] virtual-container-host/VIC failed. Remove the children files instead.
DEBU[0006] Failed to delete "[datastore0] virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk": File /vmfs/volumes/5aaf8a69-8f102c7e-9616-02001c4697c8/virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk was not found
DEBU[0006] Image store parent directory not empty, leaving in place.
INFO[0006] Removing volume stores
DEBU[0006] Provided datastore URL: "[datastore0] volumes"
DEBU[0006] Parsed volume store path: "volumes"
INFO[0006] Deleting volume store "default" on Datastore "datastore0" at path "volumes"
INFO[0006] Removing appliance VM network devices
DEBU[0007] Remove network is not supported for vCenter
INFO[0007] Collecting d7548279-cca9-4d40-859b-177c379cce90 vpxd.log
ERRO[0007] File /vmfs/volumes/5aaf8a69-8f102c7e-9616-02001c4697c8/virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk was not found
ERRO[0007] --------------------
ERRO[0007] vic-machine-linux delete failed: delete failed
```

**Comment by zjs** [comment]
Thank you for the bug report, @isyarov.

Could you also provide the output of `./vic-machine-linux --version`?

**Comment by AngieCris** [comment]
@isyarov Thanks for reporting it.

From the log, the file that failed to delete is a `-sesparse.vmdk` file, which is the snapshot format for disk of large size. Actually when vic-machine delete removes the original `.vmdk` disk file, the `-sesparse.vmdk` file (also any other kinds of `-flat.vmdk`, `-delta.vmdk` snapshot files) will be automatically removed altogether too by vSphere, so we never have to delete `-sesparse.vmdk` file explicitly. 
However, it's indeed a bug in our code that we never skip the `-sesparse.vmdk` file. When this file is already removed when deleting the original vmdk disk, the operation failed with an not found error.

For other kinds of snapshot files like `-flat.vmdk` and `-delta.vmdk`, vic-machine delete will skip them and let the vSphere `DeleteVirtualDisk_Task` handle the deletion of all. This should be done with `-sesparse.vmdk` file as well.

I'll put up a fix for it. PR coming up.

**Comment by isyarov** [comment]
@zjs 
vic-machine-linux version v1.4.0-dev-17635-0fecfdd
@AngieCris thanks for looking into it and for the detailed explanation

**Comment by AngieCris** [comment]
@isyarov The fix #7566 is merged, let me know if it still doesn't work for you.

Did you take a snapshot of a container VM or endpoint VM? The `-sesparse.vmdk` file the default snapshot format for vSphere 6.5. It doesn't look like it's part of the files generated by docker pull (but it could be if the default format for delta disk under VMFS6 or above is sesparse).

**Comment by isyarov** [comment]
@AngieCris just pulled/built it and it seems to work fine now, thanks for the quick fix!
And I did not take any snapshots. Just:
1.Create a vch
2.Pull an image (alpine)
3.Delete the vch

**Comment by AngieCris** [comment]
@isyarov Thanks for confirming!
If it's not a snapshot, it must be that the default backing disk (delta disk) format is sesparse for some VC version, or the image is very large so the delta disk is converted to space efficient sparse disk. I'll try to reproduce on my environment as well.
What's your VC version?

**Comment by isyarov** [comment]
@AngieCris 
vCneter - 6.5.0.62614, build 7092793
ESXi - 6.5.0.60711, build 4564106
