### ISSUE TITLE
Portlayer API interfaces

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#755]
Only the Storage portion of the portlayer has a defined interface and there's little to no sharing of common objects such as session.Session or config objects.

This issue is to:
- [ ] make the interfaces for the other portions of the port layer explicit
- [ ] aggregate those into an interface for the PL as a whole in it's colocated form (portlayer/portlayer.go)
- [ ] use the structure implementing that interface to hold shared objects if they cannot simply be global

**Comment by hickeng** [comment]
Hey Ben, is this a dup of something you're working on?

**Comment by corrieb** [comment]
Yes, it's very much related to #1043. Having lost all of these week to release management, this is not going to make onsite though.

**Comment by corrieb** [comment]
I'm going to close this as a dup of #1043
