### ISSUE TITLE
Update vic-machine create to support VM-Host Affinity

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7559]
This is essentially using a DRS VM Group based on the VCH name supplied by the user instead of the hard-coded value used to enable the portlayer work to proceed. It does not include allowing the user to specify the DRS VM Group, which is tracked by #7567.

This includes both tagging the VCH Endpoint VM itself during creation as well as persisting the DRS VM Group so that container VMs are tagged as well.

This includes changes to both the CLI (which will probably take a rule name) and API (which will probably accept either a rule name or identifier).

This requires validation that the DRS VM Group does not already exist, validation that the operations user has the necessary `Host.Inventory.EditCluster` privilege, and creation of the DRS VM Group.

This should include end-to-end testing of both the CLI and API, which will require additional investigation to establish a pattern for configuring the prerequisites (DRS Host Group, DRS VM Group, VM-Host Affinity Rule) from robot.

**Comment by andrewtchin** [comment]
> Testing is to encompass that we don't mess things up for ESX
- George
