### ISSUE TITLE
Update vic-machine configure to support VM-Host Affinity

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7561]
Allow the user to toggle use of a DRS VM Group, including retroactively associating or disassociating the VCH Endpoint VM and any existing container VMs. This does not include allowing the user to specify the DRS VM Group, which is tracked by #7567.

This requires validation that the operations user has the necessary right when performing any configure which introduces a DRS VM Group.

There may be complexity around ensuring the atomicity of this operation (https://github.com/vmware/vic/issues/6461#issuecomment-374366308).

**Comment by andrewtchin** [comment]
One update operation should be able to update both groups

**Comment by mdubya66** [comment]
I recommend this for cherry pick if we do a 1.4.1
