### ISSUE TITLE
Update the operations user grant flow to support Host.Inventory.EditCluster

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7562]
The operations user "grant permissions" logic will need to be updated to include granting `Host.Inventory.EditCluster` on the VCH's cluster when a VCH will be using VM-Host Affinity.

We should then leverage this grant functionality in some of the testing for the feature as a way of validating that it works as intended.

**Comment by andrewtchin** [comment]
this should apply during create, configure, and upgrade if a vm group is being used
