### ISSUE TITLE
pl.RemoveContainer should tolerate transient error TaskInProgress

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7569]
Longevity: https://vic-jenkins.eng.vmware.com/job/longevity-65/ws/vic-longevity-test-output-2018-03-20T15_29+0000/

We get the following error when removing the cVM `e85736de`:
```
Mar 20 2018 16:09:10.283Z DEBUG op=300.420: [NewOperation] op=300.420 [vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:235]
Mar 20 2018 16:09:10.283Z DEBUG [BEGIN] op=300.420 [vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:236] e85736deecabc15bc66b6dadf685a116447cfbc83b1f46554095ccdcffd0b9ed
Mar 20 2018 16:09:10.283Z DEBUG [BEGIN] op=300.420 [vic/lib/portlayer/exec.(*Container).Remove:576] e85736deecabc15bc66b6dadf685a116447cfbc83b1f46554095ccdcffd0b9ed
Mar 20 2018 16:09:10.283Z DEBUG op=300.420: Updating container e85736deecabc15bc66b6dadf685a116447cfbc83b1f46554095ccdcffd0b9ed state: Stopped->Removing
Mar 20 2018 16:09:10.283Z DEBUG [BEGIN] op=300.420 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:544] VM(VirtualMachine:vm-108849) Properties([config.files.vmPathName])
Mar 20 2018 16:09:10.283Z DEBUG op=300.420: properties: [config.files.vmPathName summary.runtime.connectionState]
Mar 20 2018 16:09:10.297Z DEBUG [ END ] op=300.420 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:544] [13.10126ms] VM(VirtualMachine:vm-108849) Properties([config.files.vmPathName])
Mar 20 2018 16:09:10.611Z DEBUG op=300.420: Unhandled fault while attempting to destroy vm e85736deecabc15bc66b6dadf685a116447cfbc83b1f46554095ccdcffd0b9ed: &types.TaskInProgress{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, Task:types.ManagedObjectReference{Type:"Task", Value:"haTask-28584-vim.ManagedEntity.reload-166985904"}}
Mar 20 2018 16:09:10.611Z DEBUG op=300.420: Updating container e85736deecabc15bc66b6dadf685a116447cfbc83b1f46554095ccdcffd0b9ed state: Removing->Stopped
Mar 20 2018 16:09:10.611Z DEBUG [ END ] op=300.420 [vic/lib/portlayer/exec.(*Container).Remove:576] [327.600587ms] e85736deecabc15bc66b6dadf685a116447cfbc83b1f46554095ccdcffd0b9ed
Mar 20 2018 16:09:10.611Z DEBUG [ END ] op=300.420 [vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:236] [327.621883ms] e85736deecabc15bc66b6dadf685a116447cfbc83b1f46554095ccdcffd0b9ed
```

We are not handling TaskInProgress in the [Remove path](https://github.com/vmware/vic/blob/779fe27783b0d091ed504ce157fd51b1edf7ca9b/lib/portlayer/exec/container.go#L622) and we should be. It's possible that this is an issues exposed or introduced by #7409 if this was never seen previously. It's also possible that we just haven't seen it before - it's unclear why there's another task running against this VM at this time - vMotion maybe?

@AngieCris thoughts?

**Comment by AngieCris** [comment]
The only related change to the logic of removing container VM in #7409 is that now`DeleteExceptDisks` re-enables VM destroy if it returns MethodDisabled error. 

Since PL explicitly calls `EnableDestroy` on the VM first, the behavior of `DeleteExceptDisks` should be the same as before. The only change would be that now `WaitForResult` in inside of `DeleteExceptDisks` around calling VM destroy, instead of wrapping around `DeleteExceptDisks` itself.

I'm not sure what to do with `TaskInProgress` case...it makes sense that it errors out

**Comment by mdubya66** [comment]
Seen again in https://vic-jenkins.eng.vmware.com/job/longevity-65/ws/vic-longevity-test-output-2018-03-22T20_06+0000/
```
Mar 22 2018 21:58:37.268Z DEBUG [BEGIN] op=301.483 [vic/lib/portlayer/exec.(*Container).Remove:576] 1aed8f7b328d31146ea0da81ecf56119b328cbe4c430a139c3e5c54b23c9af6c
Mar 22 2018 21:58:37.268Z DEBUG op=301.483: Updating container 1aed8f7b328d31146ea0da81ecf56119b328cbe4c430a139c3e5c54b23c9af6c state: Stopped->Removing
Mar 22 2018 21:58:37.268Z DEBUG [BEGIN] op=301.483 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:544] VM(VirtualMachine:vm-109187) Properties([config.files.vmPathName])
Mar 22 2018 21:58:37.268Z DEBUG op=301.483: properties: [config.files.vmPathName summary.runtime.connectionState]
Mar 22 2018 21:58:37.294Z DEBUG [ END ] op=301.483 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:544] [25.991638ms] VM(VirtualMachine:vm-109187) Properties([config.files.vmPathName])
Mar 22 2018 21:58:37.653Z DEBUG op=301.483: Unhandled fault while attempting to destroy vm 1aed8f7b328d31146ea0da81ecf56119b328cbe4c430a139c3e5c54b23c9af6c: &types.TaskInProgress{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, Task:types.ManagedObjectReference{Type:"Task", Value:"haTask-39381-vim.ManagedEntity.reload-231067988"}}
Mar 22 2018 21:58:37.653Z DEBUG op=301.483: Updating container 1aed8f7b328d31146ea0da81ecf56119b328cbe4c430a139c3e5c54b23c9af6c state: Removing->Stopped
Mar 22 2018 21:58:37.653Z DEBUG [ END ] op=301.483 [vic/lib/portlayer/exec.(*Container).Remove:576] [384.99272ms] 1aed8f7b328d31146ea0da81ecf56119b328cbe4c430a139c3e5c54b23c9af6c
Mar 22 2018 21:58:37.653Z DEBUG [ END ] op=301.483 [vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:236] [385.022923ms] 1aed8f7b328d31146ea0da81ecf56119b328cbe4c430a139c3e5c54b23c9af6c
````

**Comment by mdubya66** [comment]
marking p0 as this is now a blocker for longevity

**Comment by mdubya66** [comment]
another failure in longevity. 
https://vic-jenkins.eng.vmware.com/job/longevity-65/ws/vic-longevity-test-output-2018-03-30T14_58+0000/

This might be a different issue though. It's doing a docker ps and getting an empty list. A docker ps just after the test failure shows the container existing.

![screen shot 2018-03-30 at 10 52 42 am](https://user-images.githubusercontent.com/15821624/38143988-93095e0c-3408-11e8-93b9-e9e220d6183c.png)

```
(mwilliamson) ib-aus-office-195:~ $ docker -H 10.197.37.210:2376 --tls ps
CONTAINER ID        IMAGE                                   COMMAND             CREATED             STATUS              PORTS               NAMES
ca6ded6e4297        vic-executor1.vcna.io/library/busybox   "/bin/top"          About an hour ago   Up 50 minutes                           friendly_jennings
```

**Comment by AngieCris** [comment]
I'm wondering if the changes in the PR I checked in 3 weeks ago (link https://github.com/vmware/vic/pull/7409/files#diff-818b18702ad1cb5203eeaccc54071e09) with regards to `DeleteExceptDisks` function contributes to the recent occurrences of `TaskInProgress` race.
Before the change, the whole process of both `vm.RemoveDevice` and `vm.Destroy` is wrapped in `waitForResult`, so the whole thing is asynchronous (right?). 
But after the change, only `vm.Destroy` is asynchronous but `removeDevice` is not. Which means that we're waiting for VM destroy to finish, but we might not wait for device removal to finish before we jump to something else. This might be the reason why `TaskInProgress` race happens more often than it did before. I can't say that for sure, since we don't have historic reference - we used to wrap them in `waitForResult` retries as well so any `TaskInProgress` automatically retries so we don't see them being reported.
Cc: @hickeng

**Comment by vburenin** [comment]
Wrapping all block was not necessary it can lead to other issues. Each operation is "atomic".

**Comment by mdubya66** [comment]
I cleaned up the longevity system and removed a bunch of dangling container vm's from the datastore. The test is running now at https://vic-jenkins.eng.vmware.com/job/longevity-65/22/ and has not hit the original pl issue. I do notice that the test is now filling the VC back up with those dangling container vm's. Not sure what is leaking these yet, that needs further investigation. 

![screen shot 2018-03-30 at 4 06 43 pm](https://user-images.githubusercontent.com/15821624/38153861-7819a864-3434-11e8-83a5-db42b5339ceb.png)
![screen shot 2018-03-30 at 4 06 56 pm](https://user-images.githubusercontent.com/15821624/38153865-7bdb515a-3434-11e8-8656-97e1bd10bb91.png)

**Comment by vburenin** [comment]
I am reopening this issue since as it was expected it was not fully fixed, however, since we have more logs we can make this fix better to the point we can.
Unfortunately it is still not going to be fully fixed since, there is a VC bug we hit with this issue that will not be possible to address in this scope.

**Comment by AngieCris** [comment]
@vburenin Do you mean that it's potentially VC's problem that it can't remove device for VCH?
I would feel that if we still see this failure even after we retry on `TaskInProgress`, it would more likely be VC's problem. 
Do we have a ticket/bugzilla related to the VC bug?

**Comment by mdubya66** [comment]
there is a vc issue submitted.

**Comment by AngieCris** [comment]
@mdubya66 Do we have the link to the bugzilla ticket?
