### ISSUE TITLE
Incorrect output when attempting to pull a non-existant image

### ISSUE THREAD

**Issue by jzt** [vmware/vic#757]
Docker:

```
vagrant@devbox ~/g/s/g/v/vic ❯❯❯ docker pull ibm/os2warp
Using default tag: latest
Pulling repository docker.io/ibm/os2warp
Error: image ibm/os2warp not found
```

VIC:

```
vagrant@devbox /U/z/g/s/g/v/vic ❯❯❯ docker $DOCKER_OPTS pull ibm/os2warp
Using default tag: latest
Error response from daemon: exit status 1
```

**Comment by caglar10ur** [comment]
WARP FOREVER : http://www.techrepublic.com/article/os2-resurrected-blue-lion-becomes-arcaos-details-emerge-for-upcoming-release/

**Comment by caglar10ur** [comment]
We won't be able to show "not found" error as we only support v2 registry servers so I'm closing this "WITHOUT FIXING" it. Hub only returns 401 errors even though their API doc says otherwise and docker code simply fallbacks to v1 to catch 404 errors (https://github.com/docker/docker/blob/master/distribution/pull_v2.go#L83)

**Comment by mhagen-vmware** [comment]
@karthik-narayan Does this make sense? Is it ok?

@stuclem This is potentially a doc item.

**Comment by hickeng** [comment]
@caglar10ur I think `not found` is actually a better message, even in the case of 401 response, but we can also go with: `not found or not authorized`...
The current error message is really ugly however and gives no indication as to whether it's an internal server issue or a user mistake.

**Comment by hickeng** [comment]
Regardless we need a message that makes it seem less like something went wrong with VIC

**Comment by karthik-narayan** [comment]
I agree with @hickeng we need a better message and with @mhagen-vmware that it needs to be doc'd

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-2-Docker-Pull.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by stuclem** [comment]
This issue is included as a known issue in the release notes for TP3.

**Comment by anchal-agrawal** [comment]
Investigating. We have a different error message now:

```
$ docker -H <host> --tls pull foo/bar
Using default tag: latest
Error while pulling image manifest: Unexpected http code: 401, URL: https://registry-1.docker.io/v2/foo/bar/manifests/latest
```

**Comment by jzt** [comment]
The `Www-Authenticate` header returned from hub for a nonexistent image with a valid token includes `error="insufficient_scope"`, but for an existent image with an invalid token it uses `error="invalid_token"`. That could be used to differentiate between the two cases.

**Comment by caglar10ur** [comment]
Hmm that's good find @jzt, imagec could return different return codes based on that and personality could provide the expected error to the caller

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.
