### ISSUE TITLE
Update VSAN testbed

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#7590]
Testbed used in 5-6-2-VSAN-Complex needs to be updated

Compare https://github.com/vmware/vic/blob/master/tests/resources/nimbus-testbeds/vic-vsan.rb to ./lib/testframeworks/testng/testbeds/vsan.rb and figure out what we need to update.

**Comment by rajanashok** [comment]
Seen again on 6.7 run 3/28
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-28-04-59-58.zip?authuser=1

**Comment by rajanashok** [comment]
3/29 6.7 5-6-2-VSAN-Complex
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-29-04-41-17.zip?authuser=1

**Comment by rajanashok** [comment]
Seen again on 04/03 6.7 run
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-02-05-50-10.zip?authuser=1

**Comment by mdubya66** [comment]
lowering this to p1. It is blocked by the issue open against nimbus. 2087969
