### ISSUE TITLE
VIC plugin throws a parsing error when customer tries to specify only the gateway for management network. 

### ISSUE THREAD

**Issue by yeshwantbabar** [vmware/vic#7602]
![screen shot 2018-03-22 at 12 53 13 pm](https://user-images.githubusercontent.com/33335970/38094979-e2201a46-3334-11e8-9779-7689b6a9c241.png)
When you provide a gateway for the management network, it's mandatory to provide at least one routing destination. UI Plugin doesn't reflect that. It has two separate fields for Gateway and Routing destinations. If the customer doesn't provide both the fields properly, plugin throws a weird parsing error [Refer to the screenshot]. 

There should be just one text field, Routing Destinations:Gateway along with a tooltip/help which explains this configuration. 

The same thing applies to client network configurations as well.

**Comment by mdubya66** [comment]
is there a workaround for this and if so let's document and lower to a p2

**Comment by stuclem** [comment]
Proposed release note:

- <b>Create Virtual Container Host wizard plugin throws a parsing error when you specify only the gateway for the management or client networks. [#7602](https://github.com/vmware/vic/issues/7602)</b><br>When you provide a gateway for the management or client network, it is mandatory to provide at least one routing destination. The Create Virtual Container Host wizard does not conform to this behavior and has two separate fields for the Gateway and Routing destinations. If you do not fill in both the fields correctly, the wizard reports a parsing error.

I added this in both the `vic` and `vic-ui` release notes.

**Comment by zjs** [comment]
From discussion with @pdaigle: Management network should be restructured to make it clearer that the when a gateway is entered, one or more routing destinations must be entered. Client-side validation should be added to enforce this. This will be more consistent with the CLI.

**Comment by zjs** [comment]
Issue moved to [vmware/vic-ui #568](https://github.com/vmware/vic-ui/issues/568) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stuclem** [comment]
Moved in to resolved issues in https://github.com/vmware/vic/releases/edit/v1.4.3
