### ISSUE TITLE
Add longevity tests for 6.7 on system test infrastructure

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#7626]
Longevity needs to be covered on vSphere 6.7 for VIC 1.4 onwards.  This PR is to track the addition.

https://github.com/vmware/vic/blob/master/tests/longevity-tests/Dockerfile.foundation
https://github.com/vmware/vic/blob/master/tests/longevity-tests/Dockerfile.6.7

To point the env variables to the new ST setup.

**Comment by lgayatri** [comment]
https://github.com/vmware/vic/pull/7627/

**Comment by zjs** [comment]
Fixed in #7627.
