### ISSUE TITLE
Handle.Spec must be set in the Commit() function in /portlayer/exec/handle.go otherwise a nil pointer exception occurs

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#763]
Currently a work around exists where you SetSpec(nil)
```
        __h.SetSpec(nil)__
  	cfg := make(map[string]string)
  	extraconfig.Encode(extraconfig.MapSink(cfg), h.ExecConfig)
  	s := h.Spec.Spec()
```

however, this workaround prevents us from being able to actually do a reconfigure for the moment. without doing this any operation that does not need to reconfigure anything will cause a `Nil Pointer Exception`.

It is also not ideal to do an empty reconfigure since it would be wasted time for a command that does not need to do any reconfiguring.

**Comment by mdubya66** [comment]
Close as will not fix. Will be redone by revised portlayer API
