### ISSUE TITLE
API to create SSO accounts on Platform Service Controller

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#764]
Use the vSphere API to create a restricted user account that can interact with the VCH without using the VI Admin's credentials.

**Comment by hickeng** [comment]
@gigawhitlocks I suggest keeping the scope smaller initially - just create an account that isn't the built in admin one. We can add RBAC and role config later.

**Comment by gigawhitlocks** [comment]
Sure, that's the intended meaning of this issue. I only meant 'restricted' to mean 'not the VI admin's account' but that wording was likely misleading.

**Comment by gigawhitlocks** [comment]
There does not seem to be a good way to do this in an automated fashion. From the Platform Services Controller FAQ [knowledgebase](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2113115):

> Can I create or manage SSO users in the vSphere.local domain with PSC 6.0? With a command-line interface (CLI)? With an application program interface (API)?
> 
> You can now easily create and manage SSO Users using a new command-line utility that is included within the PSC 6.0 called dir-cli. For guidance on using dir-cli, see the dir-cli Command Reference section in the vSphere Security Guide.
> 
> **At this time, the APIs required to for this process are not publicly exposed**. For more information, see Overview of vSphere Command-Line Interfaces section in the vSphere 6.0 Command-Line Documentation Guide.

`dir-cli` ships as both a Windows exectuable and in an RPM which I've discovered to be called `vmware-afd` from the VECS project, so if we were to automate usage of the CLI tool we'd need to package and include this executable in the final `vic-machine` deliverable, which is non-trivial. 

I plan to schedule a meeting with the PSC team and see if they can support us shipping this binary or if there are private APIs available to automate this task, but for the time being I'm going to place this issue in the Icebox (especially with the information above added to the issue) while we evaluate our options. @hickeng if you could weigh in on our continued approach please do, and in the meantime I'm going to document the steps for a VIC user to create a service account manually and move on to implementing #635 by simply adding additional command line arguments to provide `vic-machine` with the service account credentials for a manually created account.

**Comment by gigawhitlocks** [comment]
Additionally, once the account is created, getting an SSO token for the account will require additions to govmomi to support [these four methods in the PSC SSO API](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.ssosdk.pg.doc/sso_pg_reference.4.2.html) so that authentication can take place.

**Comment by dougm** [comment]
We'll also need this API for testing the SSO work in epic #4703

**Comment by dougm** [comment]
There is still no API internal or otherwise that we can consume within VIC to create new SSO users.  Using dir-cli outside of VCSA isn't an option either, it has to be run locally on VCSA/PSC.  Firewall prevents outside access to lightwave/ldap/psc/etc.  I've heard there will be a public PSC admin API at some point, but no ETA.  Closing this for now as we can use dir-cli in CI.  We'll end up including a step in the customer workflow/docs to create SSO user(s) with dir-cli or the vSphere web client.
