### ISSUE TITLE
ESXi: Obtain credentials for service account authentication

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#765]

**Comment by mdubya66** [comment]
making medium for now, it may be lowered but needs to be reviewed for 1.1 inclusion

**Comment by hickeng** [comment]
@gigawhitlocks do you recall what this actually entailed? I cannot recall what the issue was actually intended for.

**Comment by dougm** [comment]
iirc, this was client certificate based authentication for ESXi that involved an internal API.  Given that we no longer support this with VC (removed used of extensions in #2993) and secrets are encrypted (#2931), let's close this.
