### ISSUE TITLE
Create Jenkins job for ROBO nightly testing

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#7655]
**Details:**

In order to regularly test against a DRS-disabled setup, we'd like to run a hand-picked set of test suites in a separate nightly Jenkins job. The job will use the work from https://github.com/vmware/vic/pull/7635 to deploy a static testbed in Nimbus and run tests against it. Per our discussion, the testbed will not be torn down at the end of each test run - this is fine as long as we don't leave dangling artifacts behind.

**Acceptance criteria:**

* [ ] A separate Jenkins job for running ROBO-specific test suites
* [ ] Before `feature/robo` is merged to master, the job will checkout the branch instead of the latest successful uploaded build

cc @mhagen-vmware

**Comment by mhagen-vmware** [comment]
@anchal-agrawal done, please verify the new jenkins vic-robo job.  Currently checks out vic-internal and feature/robo branches.  Next steps:
1. need to create a new secrets file in vic-internal: robo-secrets.list that has the manual test bed configuration in it
2. need to create a shell script with whatever tests you want to run in tests/robo/jenkins-robo-run.sh
3. press build button in jenkins
