### ISSUE TITLE
Local yum repo VM disk size too small

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#7668]
Looks like only about 14G of disk space, our yum repo image is almost 4.5G in size, after OS that only allows a single image at a time to be downloaded, which doesn't allow us to do a rapid in place upgrade.  Disk should probably be at least 40G if not 80G, we really don't need to be stingy either way..

**Comment by mdharamadas1** [comment]
Done. `/dev/mapper/ubuntu--vg-root` is now 37G.

**Comment by mhagen-vmware** [comment]
perfect, thanks!
