### ISSUE TITLE
Endpoint becomes unresponsive after several hours

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7680]
The following is seen in journalctl output:
```console
Mar 20 08:32:11 Linux systemd[1]: vic-init.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 20 08:32:11 Linux systemd[1]: vic-init.service: Unit entered failed state.
Mar 20 08:32:11 Linux systemd[1]: vic-init.service: Failed with result 'exit-code'.
```

Current speculation is that this is related to DHCP lease failure on the management network, but no clarity on why this would result in vic-init exit.

Speculative fix is to use `--asymmetric-routes` but that's pure speculation due to martian packets being logged.

Bug2084707 tracks this and contains the original details and logs.

**Comment by hickeng** [comment]
@dbarkelew Opened this issue for tracking. If you manage a recreate please let me know.

**Comment by hickeng** [comment]
Added to the release as we've had several customers run into this. We need a least a root cause and documentation covering it for 1.4 if not a code fix.

**Comment by gigawhitlocks** [comment]
Moving back to ToDo to pick up a higher priority issue, sorry for all the pipeline spam in the history of this ticket.

**Comment by hickeng** [comment]
Next step:
Modify [the dhcp client](https://github.com/vmware/vic/blob/ac22d9ebc2982b73c9bad281e6959e07966e996d/lib/dhcp/client/client.go#L68) to support `asymmetric routes`. `rp_filter` may be configured correctly for asymmetry but I suspect that given the dhcp client is listening on a specific interface we will not be getting the benefit of that.

This could also address bug2139912.

**Comment by zjs** [comment]
I think this is worth a release note, as it was a customer-reported issue.
