### ISSUE TITLE
Milestone: docker cp

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#769]
This has two very distinct parts:
1. stopped container - via portlayer storage
2. live container - via tether hgfs toolbox support

**Comment by hickeng** [comment]
Not fundamental to basic operations, but high on the list of necessary operational mechanisms

**Comment by mdubya66** [comment]
adding for consideration in 0.9.0

**Comment by corrieb** [comment]
I would like to add strong support for this to go into 0.9.0. I've spent the last two days playing with different use-cases for container VMs and time after time I find myself needing to get state into the container with no means of doing it other than SSHD.

**Comment by mdubya66** [comment]
ask for 1.1, current plan has it stretching out past deadline however.
