### ISSUE TITLE
Enable/disable method privileges missing in ops-user logic

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#7714]
### Note: this bug is on master

**Details:**

We need the `Global.EnableMethod` and `Global.DisableMethod` privileges - for example, to disable the `Destroy_VM` task on a containerVM to not allow VM delete from the vSphere UI (see https://github.com/vmware/vic/blob/master/pkg/vsphere/vm/vm.go#L672 and https://github.com/vmware/vic/blob/master/lib/portlayer/exec/commit.go#L77). These privileges are not present in our logic for granting ops-user permissions (see https://github.com/vmware/vic/blob/master/lib/install/opsuser/opsuser_conf.go). Per the [docs](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/ops_user_manual.html), these privileges need to be added to the `Endpoint` role.

**Acceptance Criteria:**
* [x] `Global.EnableMethod` and `Global.DisableMethod` privileges added to the appropriate role (I've noted that adding them to the Endpoint role does not fix the issue) Update - these privileges are needed at the vCenter-level (`vic-vch-vcenter` role, instead of `vic-vch-endpoint` as in the docs)
* [x] Integration test that simulates an out-of-band containerVM destroy and fails to do so in an env with an ops-user

**Comment by anchal-agrawal** [comment]
Added the kind/user-doc label - cc @stuclem for doc impact.

**Comment by stuclem** [comment]
Opened https://github.com/vmware/vic-product/issues/1604 for the doc update. Removing `kind/user-doc` from this one.
