### ISSUE TITLE
Add CI option to run tests using the ops user

### ISSUE THREAD

**Issue by jzt** [vmware/vic#7722]
**User Statement:**

As a developer, I would like to have the option for changes I make to the codebase to be exercised in integration tests with VIC appliances that enable the ops user and associated VC permissions.

**Details:**

Currently, our integration tests use the administrator account for all vSphere operations. We have seen issues where testing functionality that requires certain VC permissions fails if done using the ops user account. To guard against these gaps, we need an option to run integration tests using the ops user instead of administrator.

**Acceptance Criteria:**

- [ ] The ability to specify a keyword in your PR to run tests as ops user - `[ops user]` or something similar

**Comment by zjs** [comment]
>  An ops user account added to all VCs in our CI

For what it's worth, `5-25-OPS-User-Grant.robot` has a keyword (`Ops User Create`) which includes logic to dynamically create an operations user. This might be preferable to relying on an account to exist on each CI system, as it moves the setup logic into the test suite itself.

**Comment by mhagen-vmware** [comment]
Absolutely, this should be done dynamically with either that keyword or a similar one.
