### ISSUE TITLE
Create a nimbus environment that is a good representaion of a longer range latent environment 

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#7732]
We need a latent network between the VC and the ESXi hosts to simulate a more ROBO like environment. locality of the hosts in not as important as keeping the VCs and the ESXi's non local. The VC's should also be linked and have an infra VC backing them. Ideally we want a setup close to the standard testing environment for ROBO. This may also involve introducing `tc` between the hosts and the VC if the datacenter latency between datacenters is not sufficient enough. 

**Acceptance Criteria:**
- [ ] A ready to go preferably automatable(atleast followable) process for deploying a latent environement for ROBO support testing.

**Comment by zjs** [comment]
High-latency testing would be valuable, but is not a priority at this time.
