### ISSUE TITLE
Nightly-6.5-13-1-vMotion-VCH-Appliance docker stop returns 137 return code

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#7736]
```KEYWORD ${rc}, ${output} = OperatingSystem . Run And Return Rc And Output docker %{VCH-PARAMS} stop ${container}
Documentation:	
Runs the given command in the system and returns the RC and output.

Start / End / Elapsed:	20180410 15:15:55.681 / 20180413 09:58:03.145 / 66:42:07.464
15:15:55.686	INFO	Running command 'docker -H sc-rdops-vm14-dhcp-172-22.eng.vmware.com:2376 --tls stop 86cf7e0480c8d3729c8d931b21ea6b7031805fb03c08f26541bca21e70041759 2>&1'.	
09:58:03.144	INFO	${rc} = 137	
09:58:03.145	INFO	${output} = Killed
```
We also failed to curl up the logs due to a govc timeout.

```09:58:03.963	INFO	Running command 'govc vm.info VCH-0-9282 2>&1'.	
09:59:34.052	INFO	${rc} = 1	
09:59:34.053	INFO	${out} = govc: Post https://10.161.177.177/sdk: dial tcp 10.161.177.177:443: i/o timeout
```
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-10-14-42-22.zip?authuser=1

**Comment by mhagen-vmware** [comment]
I killed this manually, the bigger problem was that we missed a return code again, which I recall having a conversation with @hickeng somewhere else in regards to that but I can't recall exactly where... the client was stuck waiting for a return code from the docker stop command it issued for 66hrs

**Comment by mhagen-vmware** [comment]
closing, don't have a log for this as govc failed to connect.  Re-open to verify we sent return code properly if we can get the logs.
