### ISSUE TITLE
Running containers port mapped with UDP protocol fails "Server error from portlayer: error mapping ports"

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic#7751]
**VIC version:**
VIC 1.3.1

**Deployment details:**
vCenter 6.5 embedded PSC
ESXi 6.5

What was the vic-machine create command used to deploy the VCH?
./vic-machine-linux create \
--target https://vc1.gsslabs.org/Default-DC \
--user administrator@vsphere.local \
--password '********' \
--compute-resource Default-CL \
--bridge-network Bridge00-00_PortGroup \
--public-network Public-00 \
--public-network-ip 192.168.100.50/24 \
--public-network-gateway 192.168.100.254 \
--dns-server 192.168.0.10 \
--container-network Container-Net_192.168.110.0:Net-110 \
--container-network-gateway Container-Net_192.168.110.0:192.168.110.254/24 \
--container-network-ip-range Container-Net_192.168.110.0:192.168.110.0/24 \
--container-network-dns Container-Net_192.168.110.0:192.168.0.10 \
--container-network-firewall Container-Net_192.168.110.0:open \
--volume-store iSCSI-2/VCH00-00-vol:default \
--image-store iSCSI-2/VCH00-00-img \
--insecure-registry vicappliance00.gsslabs.org \
--insecure-registry 192.168.100.40 \
--no-tlsverify \
--thumbprint=B1:3B:26:61:B9:3B:92:1F:21:7E:75:B3:DA:02:D8:FE:FE:C3:39:81 \
--name VCH00-00

**Steps to reproduce:**
Run the following from the docker client Version: 18.03.0-ce API version: 1.37. IP set with DOCKER_HOST
```
docker --tls run -p 1111:80/udp nginx
```

**Actual behavior:**
Container fails to run with the following output.
```
# docker --tls run -p 1111:80/udp nginx Unable to find image 'nginx:latest' locally ... docker: Error response from daemon: Server error from portlayer: error mapping ports: port 1111 is not available.
```

**Expected behavior:**
Run the container with protocol UDP to port 80. 

**Logs:**
On request if needed.

**Additional details as necessary:**
Tracking issue

bug2101472

**Comment by mdubya66** [comment]
@hickeng udp expected to work with existing networking?

**Comment by mdubya66** [comment]
George Hicken [3 minutes ago]
@mwilliamson looks like a bug in the portmapper to me

Matt Williamson [2 minutes ago]
has it ever worked, i wonder?

George Hicken [1 minute ago]
nope - not as written. The way it's written is completely flawed for udp

Matt Williamson [< 1 minute ago]
thanks. it needs fixing and testing. i’ll add @pdaigle to it for prioritization.

George Hicken [< 1 minute ago]
It's relying on the connection based nature of tcp to determine whether a port is opened for use. Not going to work for udp or any other packet protocol

**Comment by Reedler01** [comment]
This is also an issue for us. Trying to spin up an ELK stack and ingest logs with logstash. No need for tcp as it would generate too much network traffic as we're ingesting around 70G a day.

**Comment by renmaosheng** [comment]
@Reedler01 what do you mean by 'generate too much network traffic', I am not sure changing to UDP can help you on this.

**Comment by Reedler01** [comment]
There's no reason for the protocol to error check and the back and forth communication for the amount of logs we're throwing at logstash.

**Comment by dbarkelew** [comment]
After setting docker-compose according to https://kb.vmware.com/s/article/54449 to prevent the connection pool from being over filled the issue can no longer be reproduced. Appears the issue was relating to a race condition between docker-compose operations completing before the next started due to timeouts when the connection pool is filled up.
