### ISSUE TITLE
Nightly 6.5 - 2018-04-16 - 5-27-Selenium-Grid: Selenium node chrome1 failed to start properly

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#7764]
VIC version:
v1.4.0-dev-0-b6c0988

Deployment details:
Nightly 6.5

5-27-Selenium-Grid

![screen shot 2018-04-17 at 1 35 05 am](https://user-images.githubusercontent.com/26554503/38852472-a592063e-41df-11e8-80d8-0f7ba227520b.png)

Vic-machine
[vic-machine.log](https://github.com/vmware/vic/files/1918352/vic-machine.log)

VCH logs
[vch-0-2626.zip](https://github.com/vmware/vic/files/1918363/vch-0-2626.zip)

Nightly Summary
[65.zip](https://github.com/vmware/vic/files/1918364/65.zip)

Link to logs:
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-16-03-54-06.zip?authuser=1

**Comment by hickeng** [comment]
Likely to be the same as #7682 - please confirm/refute and close as dup if necessary.

**Comment by rogeliosanchez** [comment]
Closing this out.  Tracking in #7682.
