### ISSUE TITLE
vic-machine creates VCH in wrong resource pool on ESXi

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7776]
`vic-machine create` determines the path to create a VCH -- specifically the resource pool where to create it.  `vic-machine create` should create a new resource pool for each VCH unless it's being installed to a DRS disabled cluster.  The logic to determine DRS setting for create doesn't take into account VC vs. Standalone ESXi.  

This results in a VCH being created in the ESXi default resource pool instead of it's own resource pool.  This is evidenced by the fact that `vic-machine ls` will not identify the vm as a VCH.

**Comment by mdubya66** [comment]
ESXi only. Not blocking a test. Making a P2

**Comment by cgtexmex** [comment]
@mdubya66 This is what's causing the nightlies to fail as well.  #7762 #7756

**Comment by mdubya66** [comment]
approved for merge to master. It's not a ship stopper for 1.4 now that we are passed FC.
