### ISSUE TITLE
Nightly 6.0 - 2018-04-17 - 5-25-OPS-User-Grant --> vic-machine create grants ops-user perms

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#7795]
VIC version 
v1.5.0-dev-18481-023de08

5-25-OPS-User-Grant
Should Not Be Equal As Integers
![screen shot 2018-04-19 at 4 16 58 pm](https://user-images.githubusercontent.com/26554503/39019046-9a63d4da-43ed-11e8-8619-eb8c8e206c01.png)

Vic machine
[vic-machine.log](https://github.com/vmware/vic/files/1929819/vic-machine.log)

VCH logs
[vch-0-5491.zip](https://github.com/vmware/vic/files/1929825/vch-0-5491.zip)

Nightly Summary
[60.zip](https://github.com/vmware/vic/files/1929826/60.zip)

Link to logs
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-17-20-32-56.zip?authuser=1

More logs
[Suites.Group5-Functional-Tests.5-25-OPS-User-Grant-VCH-0-5491-container-logs.zip](https://github.com/vmware/vic/files/1929827/Suites.Group5-Functional-Tests.5-25-OPS-User-Grant-VCH-0-5491-container-logs.zip)

**Comment by anchal-agrawal** [comment]
George brought up this particular failure over email - I've copied my email response below.

```
Thanks for bringing this up - this nightly run was based off Engine build 18481 (https://ci-vic.vmware.com/vmware/vic/18481) which does not include my change for adding method privileges (https://github.com/vmware/vic/pull/7752). This test failed because the nightly job

  1) checks out VIC engine's master branch, but
  2) uses CI-built VIC binaries

This can cause a "project code vs. test code mismatch" because the master branch from 1) may include code that didn't produce a successful CI build but will still include the latest test code in master. This issue has been seen earlier - https://github.com/vmware/vic/issues/4389#issuecomment-289139648.
```
