### ISSUE TITLE
Nightly 6.0 - 2018-04-18 - 5-25-OPS-User-Grant: 'Incorrect Usage: flag provided but not defined: -affinity-vm-group

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#7798]
VIC version
v1.5.0-dev-18481-023de08

5-25-OPS-User-Grant: Test with VM-Host Affinity
'Incorrect Usage: flag provided but not defined: -affinity-vm-group
![screen shot 2018-04-19 at 7 12 21 pm](https://user-images.githubusercontent.com/26554503/39024310-a9ae1a8c-4405-11e8-8d4a-99ac65682e4d.png)

![screen shot 2018-04-19 at 7 13 25 pm](https://user-images.githubusercontent.com/26554503/39024327-c41c259e-4405-11e8-8e4c-0a66576dba61.png)

Vic machine
[vic-machine.log](https://github.com/vmware/vic/files/1930148/vic-machine.log)

Nightly Summary
[60.zip](https://github.com/vmware/vic/files/1930151/60.zip)

Link to logs
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-18-20-32-56.zip?authuser=1

**Comment by zjs** [comment]
This failure doesn't seem possible. `affinity-vm-group` is definitely defined; I'm seeing a consistent 7/7 pass rate for `Group25-Host-Affinity.25-01-Basic` on `master` and `releases/1.4.0`.

Based on `vic-machine.log`, it looks like this is testing a build of 023de08 (from Monday, before the feature branch was merged).
