### ISSUE TITLE
docker -D info command not supported

### ISSUE THREAD

**Issue by hagenmt** [vmware/vic#780]
**VIC Version:**

master

**Code**

```
docker -H <VIC> info
docker -H <VIC> -D info
```

**Expected behavior:**
It is expected that additional debug information will be provided when passing the -D flag to info command.

**Actual behavior:**
The flag is ignored and prints the same output as it would without the flag.

**Comment by hagenmt** [comment]
Already discussed that we won't likely be supporting this in the near future, but creating this issue as a tag for my automation scripts.

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-1-Docker-Info.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please do it.

**Comment by anchal-agrawal** [comment]
It appears that `-D` is used to enable debug mode on the Docker client and not display more information for the `info` command. The only difference b/w `-D info` and `-info` on vanilla Docker is:

```
< Debug mode (client): true
---
> Debug mode (client): false
```

I think we should close this issue after removing/fixing the related integration test. The test as it is will pass currently.
