### ISSUE TITLE
Wolfpack daemon not deleting vms

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#7802]
Using the wolfpack cli, it appears to delete multicontainer vms, but the vms are actually not getting deleted on vsphere.

**Comment by lcastellano** [comment]
Turns out the leftovers VM are not POD VMs created by us but Kubeproxy VMs created by Kubernetes. One possible solution is to run the Virtual Kubelet with a taint to avoid scheduling of Kubeproxy.
