### ISSUE TITLE
Organize and separate concerns between Validator and Session structs in vic-machine

### ISSUE THREAD

**Issue by jzt** [vmware/vic#7840]
**User Statement:**

As a developer, I would like to avoid different structs sharing the same concerns. Specifically, in `vic-machine`, I would like the `Validator` and `Session` structs to be re-organized in such a way that they don't compete to hold specific data or otherwise overlap in a way that causes confusion that can lead to regressions.

**Details:**

The `session.Session` struct is becoming a monolithic catch-all for various responsibilities and for hanging on to data that is accessed particularly often. This can cause confusion in areas where it makes sense that a different object would be responsible for a separate set of concerns. Specifically tracked in this issue is [`validate.Validator`](https://github.com/vmware/vic/blob/master/lib/install/validate/validator.go#L56): we see several fields that are also shared with [`session.Session`](https://github.com/vmware/vic/blob/master/pkg/vsphere/session/session.go#L83)'s embedded [`Config`](https://github.com/vmware/vic/blob/master/pkg/vsphere/session/session.go#L59):

```go
type Config struct {
	// extra fields removed for space

	ClusterPath    string
	DatacenterPath string
	DatastorePath  string
	HostPath       string
	PoolPath       string
}
```
```go
type Validator struct {
	TargetPath        string
	DatacenterPath    string
	ClusterPath       string
	ResourcePoolPath  string
	ImageStorePath    string
	PublicNetworkPath string
	BridgeNetworkPath string
	BridgeNetworkName string

	Session *session.Session
	Context context.Context

	isVC   bool
	issues []error

	allowEmptyDC bool
}
```
Because of these overlapping fields, when using `Validator` and `Session` together, it becomes confusing when attempting to populate these structs. Populating these duplicate fields in both is wasteful and unnecessary, but leaving either unpopulated can potentially cause future consumers of either to use the wrong pattern leading to a regression (see [this discussion](https://github.com/vmware/vic/pull/7837#discussion_r183939909) for an example).

To make matters worse, there is even an entire `session.Session` contained in `Validator` leading to even more confusion and overlap.

Going forward, we should address this by cleanly separating these fields out into one or the other, but not both, and correct the pattern of usage so that the intended use is clearly visible when making future changes.

**Acceptance Criteria:**

- [ ] Design and implement a refactor that separates the concerns between `session.Session` and `validate.Validator`
- [ ] Update tests to exercise any new code resulting from this refactor

**Comment by zjs** [comment]
This seems to have been addressed by #7859; `Validator` now contains _only_ a `Session` and issue list.
