### ISSUE TITLE
Modify VM (container) Size

### ISSUE THREAD

**Issue by brockz** [vmware/vic#7847]
Hello

i tried different ways to get the vms created by vch in size of memory smaller without Success.
When i create an container via vch it is allways 2GB in Size:

![image](https://user-images.githubusercontent.com/25453305/39303787-c14ff596-4957-11e8-8b20-32fce10ca231.png)

How can i make the "VM" smaller on creation of the Container ?

**Comment by brockz** [comment]
?

**Comment by mdubya66** [comment]
vic-machine doesn't provide a way to limit the memory size on the individual container vm. That is done via docker --memory flag. 

For example: 
```
(mwilliamson) ib-aus-office-195:~/Downloads/vic_1.4.0-rc1 $ docker -H 172.16.127.128:2376 --tls run -t --memory 512M busybox
/ #
```
https://vmware.github.io/vic-product/assets/files/html/1.3/vic_app_dev/container_operations.html for other --memory options
