### ISSUE TITLE
Nightly 6.7 5-27-Selenium-Grid docker network create cannot validate certificate 

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7851]
04/26/18, VC 6.7
After installing VIC to test server

command:
```
docker -H 10.193.38.205:2376 --tls network create grid 2>&1
```
failed with:
`error during connect: Post https://10.193.38.205:2376/v1.25/networks/create: x509: cannot validate certificate for 10.193.38.205 because it doesn't contain any IP SANs`

Link to complete log: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-26-04-49-30.zip?authuser=1
Log bundle: [Suites.Group5-Functional-Tests.5-27-Selenium-Grid-VCH-0-9408-container-logs.zip](https://github.com/vmware/vic/files/1952641/Suites.Group5-Functional-Tests.5-27-Selenium-Grid-VCH-0-9408-container-logs.zip)

@mhagen-vmware Is this related to https://github.com/vmware/vic/issues/7682 or https://github.com/vmware/vic/issues/7614?

**Comment by AngieCris** [comment]
Marked p0 for now, might deprioritize

**Comment by zjs** [comment]
> might be related/duplicate: #7855
@hickeng also guesses that this might be a duplicate — can confirm by checking Subject Alt Names

**Comment by renmaosheng** [comment]
@zjs @hickeng can this be closed as per above comment?

**Comment by zjs** [comment]
Please re-open if we observe this failure again.
