### ISSUE TITLE
Nightly 04/27/18 5-12-Multiple-VLAN docker pull cannot validate certificate because it doesn't contain IP SANs

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7855]
Nightly 04/27/18
VC version: 6.7
Test suite: 5-12-Multiple-VLAN
Test step: regression test

command:
`docker -H 10.193.37.194:2376 --tls pull busybox 2>&1`

failed with output:
`Warning: failed to get default registry endpoint from daemon (error during connect: Get https://10.193.37.194:2376/v1.25/info: x509: cannot validate certificate for 10.193.37.194 because it doesn't contain any IP SANs). Using system default: https://index.docker.io/v1/
error during connect: Post https://10.193.37.194:2376/v1.25/images/create?fromImage=busybox&tag=latest: x509: cannot validate certificate for 10.193.37.194 because it doesn't contain any IP SANs`

Link to download logs: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-27-05-42-25.zip?authuser=1
container logs:
[Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-1287-container-logs.zip](https://github.com/vmware/vic/files/1955989/Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-1287-container-logs.zip)
[Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-5474-container-logs.zip](https://github.com/vmware/vic/files/1955990/Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-5474-container-logs.zip)
Logs for VCH appliance VMs:
[5-12 appliance logs.zip](https://github.com/vmware/vic/files/1955995/5-12.appliance.logs.zip)

**Comment by AngieCris** [comment]
Nightly 04/29/18, VC 6.5
Test suite: 5-12-Multiple-VLAN
Test step: regression test

command:
`docker -H 10.193.39.88:2376 --tls pull busybox 2>&1`

failed with:
`
Using default tag: latest Warning: failed to get default registry endpoint from daemon (error during connect: Get https://10.193.39.88:2376/v1.25/info: x509: cannot validate certificate for 10.193.39.88 because it doesn't contain any IP SANs). Using system default: https://index.docker.io/v1/ error during connect: Post https://10.193.39.88:2376/v1.25/images/create?fromImage=busybox&tag=latest: x509: cannot validate certificate for 10.193.39.88 because it doesn't contain any IP SANs
`

Link to log: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-29-00-41-08.zip?authuser=1
container logs: 
[Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-4438-container-logs.zip](https://github.com/vmware/vic/files/1961397/Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-4438-container-logs.zip)
[Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-5917-container-logs.zip](https://github.com/vmware/vic/files/1961398/Suites.Group5-Functional-Tests.5-12-Multiple-VLAN-VCH-0-5917-container-logs.zip)
appliance logs: 
[VCH-4438.zip](https://github.com/vmware/vic/files/1961401/VCH-4438.zip)
[VCH-5917.zip](https://github.com/vmware/vic/files/1961404/VCH-5917.zip)

**Comment by AngieCris** [comment]
Nightly 04/29/18, VC 6.5
Test suite: 5-15-NFS-Datastore
Test step: regression test

Same failure as before

Link: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-29-00-41-08.zip?authuser=1
container logs:
[Suites.Group5-Functional-Tests.5-15-NFS-Datastore-VCH-0-8475-container-logs.zip](https://github.com/vmware/vic/files/1961420/Suites.Group5-Functional-Tests.5-15-NFS-Datastore-VCH-0-8475-container-logs.zip)
appliance log:
[VCH-8475.zip](https://github.com/vmware/vic/files/1961421/VCH-8475.zip)

**Comment by hickeng** [comment]
If we’re specifying `—tls` then it’s likely this is a no-tlsverify deployment. If that’s the case then we do not expect to have a subjectAltName, dns or IP, because it’s a dhcp environment.

That said, unless there’s been a change to the Go 
client config in the docker client we should not be doing validation of the server cert in the no tls verify case. That inability to do server validation without full client auth has been an irritant since the beginning so perhaps there _has_ been a client change.
Otherwise I suggest checking to see if DOCKER_TLS_VERIFY has accidentally been set in this test path or env.

**Comment by AngieCris** [comment]
@hickeng Just checked, the VCH deployed is not using `no-tlsverify`, and there should be an IP SAN present.

**Comment by AngieCris** [comment]
seen again nightly 05/01/18, VC 6.0
Test suite: 13-2-vMotion-Container
Test step: right after installing VIC appliance, during docker pull busybox

command:
`docker -H 10.193.40.253:2376 --tls pull busybox 2>&1`
output:
`Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get https://10.193.40.253:2376/v1.25/info: x509: cannot validate certificate for 10.193.40...`

It's confirmed that the VCH is deployed with tls verify on. 

docker persona log shows tls error (bad cert):
```
May  2 2018 01:53:55.183Z DEBUG Registering POST, /plugins/create
May  2 2018 01:53:55.183Z INFO  API listen on 10.193.40.253:2376
2018-05-02 01:53:56.046978 I | http: TLS handshake error from 10.126.23.4:57329: remote error: tls: bad certificate
2018-05-02 01:53:58.347876 I | http: TLS handshake error from 10.126.23.4:57335: read tcp 10.193.40.253:2376->10.126.23.4:57335: read: connection reset by peer
```

Link to logs:
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-05-01-20-32-56.zip?authuser=1
container logs:
[Suites.Group13-vMotion.13-2-vMotion-Container-VCH-0-1879-container-logs.zip](https://github.com/vmware/vic/files/1972708/Suites.Group13-vMotion.13-2-vMotion-Container-VCH-0-1879-container-logs.zip)
appliance logs:
[VCH-0-1879.zip](https://github.com/vmware/vic/files/1972709/VCH-0-1879.zip)

**Comment by AngieCris** [comment]
Nightly 05/01/18, VC 6.0
Test suite: 5-25-OPS-User-Grant
Test cases:
vic-machine create grants ops-user perms
Test with VM-Host Affinity
vic-machine configure grants ops-user perms

Link to logs: 
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-05-01-20-32-56.zip?authuser=1
container logs and appliance logs: 
vic-machine create grants ops-user perms
[Suites.Group5-Functional-Tests.5-25-OPS-User-Grant-VCH-0-9616-container-logs.zip](https://github.com/vmware/vic/files/1972760/Suites.Group5-Functional-Tests.5-25-OPS-User-Grant-VCH-0-9616-container-logs.zip)
[VCH-0-9616.zip](https://github.com/vmware/vic/files/1972761/VCH-0-9616.zip)
Test with VM-Host Affinity
[Uploading Suites.Group5-Functional-Tests.5-25-OPS-User-Grant-VCH-0-8658-container-logs.zip…]()
[VCH-0-8658.zip](https://github.com/vmware/vic/files/1972763/VCH-0-8658.zip)
vic-machine configure grants ops-user perms
[Suites.Group5-Functional-Tests.5-25-OPS-User-Grant-VCH-0-5473-container-logs.zip](https://github.com/vmware/vic/files/1972764/Suites.Group5-Functional-Tests.5-25-OPS-User-Grant-VCH-0-5473-container-logs.zip)
[VCH-0-5473.zip](https://github.com/vmware/vic/files/1972769/VCH-0-5473.zip)

**Comment by sgairo** [comment]
Nimbus issue, closing as it hasnt been seen recently.

**Comment by hickeng** [comment]
Looking at the certificates from VCH-0-9616 we can see that it _does_ have a SAN, but doesn't have _IP SANs_ which is expected in a DHCP environment. Instead of the IP SAN it has a DNS SAN (using `openssl x509 -in server-cert.pem -noout -text`):
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            <snip>
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=
        Validity
            Not Before: May  1 03:32:06 2018 GMT
            Not After : May  2 03:32:06 2019 GMT
        Subject: O=, CN=*.eng.vmware.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                <snip>
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Key Agreement
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                <snip>
            X509v3 Authority Key Identifier:
                keyid:<snip>

            X509v3 Subject Alternative Name:
                DNS:*.eng.vmware.com
    Signature Algorithm: sha256WithRSAEncryption
         <snip>
```
Follow up question is why we're using the IP address as the `DOCKER_HOST` when we should be using the FQDN.

**Comment by mdharamadas1** [comment]
Todo:
- confirm DNS server is correct
- gather info on how often DNS lookup fails
- report probable DNS issue (to Nimbus team?)

**Comment by zjs** [comment]
Re-open (or file a new issue linking to this one) if this happens again.
