### ISSUE TITLE
Nightly 04/27/18 5-22-OPS-User-Grant: unable to wait for process launch status

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7857]
Nightly 04/27/18
Test suite: 5-22-OPS-User-Grant
Test case: Test with VM-Host Affinity
Test step: Run privilege-dependent docker operations

command: 
`docker -H sc-rdops-vm12-dhcp-96-232.eng.vmware.com:2376 --tls run -d --net public -v barVol:/dir busybox 2>&1`

failed with return code 125 and:
`docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.192.75.145/s...`

There're two problems here:
1. There is no logs gathered for container or VCH appliance. 
This is because when the test failed, the teardown keyword `Gather vSphere Logs` was run, and the later step `Cleanup VIC Appliance on Test Server` was never run, so logs are not gathered. We should fix this behavior. 
2. Since there is no log, it's hard to tell why portlayer CDE. 

We can close this ticket once problem 1 is addressed, and re-open if it reproduces. Then we would have the logs we need to investigate into the root cause.

Link to download complete log: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-27-00-50-14.zip?authuser=1

**Comment by AngieCris** [comment]
Seen again 04/29/18
5-22-OPS-User-Grant

still since the test didn't run the `Cleanup VIC Appliance on Test Server` as teardown, no logs are collected for this VCH

Link to complete log: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-29-00-41-08.zip?authuser=1

**Comment by sgairo** [comment]
Estimating at 1 for the collection of logs.

**Comment by sgairo** [comment]
okay will do, thanks @AngieCris
