### ISSUE TITLE
integration-test: failure vic-machine.bats#141

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#786]
The following test fragment is failing:
```
    # execute docker create/start command
    run "$docker" "${docker_cmd[@]}" create busybox /bin/date
    assert_success
    name="$output"

    run "$docker" "${docker_cmd[@]}" start "$name"
    assert_success

    run govc vm.destroy "$name"
    assert_success

    run govc datastore.rm -f "$name"
    assert_success
```
The failure is as follows:
```
#  in test file tests/vic-machine.bats, line 141)
#   `assert_success' failed
#
# -- command failed --
# status : 1
# output : /go/bin/govc: The attempted operation cannot be performed in the current state (Powered on).
# --
#
Makefile:186: recipe for target 'integration-tests' failed
```

I suggest adding a wait for the container vm to power off - not a sleep, but instead waiting on powered off status with a timeout

**Comment by hickeng** [comment]
@gigawhitlocks Needs to be owned by someone, and you get the honor this time. Can we have this fixed today please.

**Comment by gigawhitlocks** [comment]
@hickeng I *just* noticed that you assigned this to me :\ Is this still relevant? I think @mhagen-vmware has changes to remove all the bats tests & replace them w/ robot tests so I've been trying to avoid getting sucked back into fixing tests

**Comment by mdubya66** [comment]
BATS based. Closing
