### ISSUE TITLE
Resource pool issue

### ISSUE THREAD

**Issue by maxisam** [vmware/vic#7865]
#For stories, please include the information below:

We didn't have `Resource Pool` before we install VIC. But we created it when we tried to create VCH. However, the interface doesn't show any Resource Pool to select. And we can't create VCH successfully. It always shows error like 

>no permission to create a resource pool

If I use vic-machine-windows and assign the resource pool, I can bypass this issue.

**User Statement:**
Want to create VCH through UI

**Details:**

However, it doesn't really work in the end. There are some other errors, 
`"Docker API endpoint check failed: context deadline exceeded"`,
but I think can't assign Resource Pool is a bug.

#For bug reports, please include the information below:

**VIC version:**

 v1.3.1-rc2.687  (vic-machine-windows: v1.3.1-16055-afdab46)

What was the vic-machine create command used to deploy the VCH?

vic-machine-windows create --name CVCH01 --debug 1 --container-name-convention CVCH01{name} --compute-resource VCH-RESOURCE-POOL --image-store CHXDS01/ContainerImage --base-image-size 8GB --bridge-network VCH01PortGroup --bridge-network-range 172.16.0.0/12 --public-network DockerPortGroup1  --tls-cname CVCH01 --certificate-key-size 2048 --no-tlsverify --user admin@vsphere.local --thumbprint 5C:57:FA:68:E2:53:58:46:60: AD:1E:80:1D:BD:2A:64:9C:70:9C:13 --target test.domain.com/CDC01 --ops-user vic-ops-user@vsphere.local --dns-server 192.168.2.21

**Comment by mdubya66** [comment]
Issue moved to [vmware/vic-ui #455](https://github.com/vmware/vic-ui/issues/455) via [**ZenHub**](https://www.zenhub.com/)
