### ISSUE TITLE
Change VM name to prettyName-UUID

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#787]
Given a docker run command of:
`docker run -name sleepy_hibbert busybox`
resulting in a container ID of:
`DEADBEEF`

the containerVM name should be:
`sleepy-hibbert-DEADBEEF`

ghicken update: There are tokens already defined in virtual_container_host.go for replacement of id, name, and vm name.

**Comment by mdubya66** [comment]
This is needed for TP3.

**Comment by bradmeiseles** [comment]
Whoever works on this, be sure to be mindful of length limits. Is the sum of max length of docker name + UUID length + 1 less than or equal to max VM name length? If not, OK to truncate pretty name from the right and preserve the full UUID. That guarantees uniqueness and shouldn't impact usability.

**Comment by hickeng** [comment]
This should pull from the VirtualContainerHostConfigSpec.ContainerNameConvention - if that is blank then use a default.
We can invent a very trivial replacement format for that string with truncation to the max name length:
{n} - replaced with pretty name
{id} - replaced with ID

**Comment by corrieb** [comment]
This should be a relatively simple change. High marks for increased usability.

**Comment by emlin** [comment]
> This should pull from the VirtualContainerHostConfigSpec.ContainerNameConvention - if that is blank then use a default.

Currently, the ContainerNameConvention is not set by vic-machine yet. Do we need to add flag for that? And what is supposed to be set there?

**Comment by emlin** [comment]
Per @mdubya66 , this is not a high priority issue for OnSite. Will hold on additional decision.

**Comment by hickeng** [comment]
@emlin ContainerNameConvention would be set via vic-machine argument - the default that would provide the pretty name format described in the initial issue would be "{n}-{id}" if we follow the token replace method in my prior comment.
