### ISSUE TITLE
update 11-01-Upgrade to validate folder support

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7875]
The 11-01-Upgrade CI test should be updated to include validation that the folder structure (that began in 1.4) is present and all VMs (endpoint & cVMs) have been moved into the folder.

There is a keyword that can be used to help with validation: `Check VM Folder Exists`

Acceptance:
- [ ] upgrade from 1.2.1 (resource pool ONLY) or 1.3.1
- [ ] verify folder created with name matching endpoint VM
- [ ] verify endpoint VM is moved into newly created folder
- [ ] verify container VMs are moved into newly created folder

**Comment by renmaosheng** [comment]
@lgayatri are you maintaining the stress testing? is this still an issue? thanks.

**Comment by zjs** [comment]
@luwang-vmware this may overlap with other issues.

**Comment by luwang-vmware** [comment]
The latest vic-product version we supported is 1.5.2. And I think there is very few customer who will use the scenario as in the description. So close it for now.
