### ISSUE TITLE
vic-machine: add -applance-cpu and -appliance-memory to customize vch appliance VM

### ISSUE THREAD

**Issue by emlin** [vmware/vic#788]
These two parameters are useful if we want to debug in VCH appliance VM.
Feel free to comment on the name of these two parameters.

**Comment by fdawg4l** [comment]
@emlin how would more cpu/memory on the vch appliance help you debug?  Are you trying to compile on the appliance vm?

**Comment by emlin** [comment]
@fdawg4l It's from Loc, and he's trying to reboot the VM to add more CPU/Memory, but we're not working well currently for VCH reboot, cause lots of guestinfo configuration are lost after reboot.
So I think add back these parameters will be easy right now.

**Comment by fdawg4l** [comment]
@sflxn @emlin I'm not really sure we want to be able to twiddle these values.  Can you help me understand what you're doing on the appliance that requires more memory?  If I were to guess, I'd say you were attempting to compile something on it.

FYI, the guest info values are in the vmx.  You could just look at the vmx if you wanted to add those fields to devbox.  This is what I did when developing on devbox.

**Comment by fdawg4l** [comment]
cc @hickeng

**Comment by emlin** [comment]
Basically, it's easy to add one or two parameters into the vic-machine, to leave more customization to users.
My only concern is if these two parameters look good to end user.

**Comment by fdawg4l** [comment]
I'd wait for @hickeng to comment.  In my opinion, these two parameters aren't needed.  But I could be wrong.

**Comment by emlin** [comment]
Agree with you. Even these are needed, they might still be a lower priority.

**Comment by caglar10ur** [comment]
I'm not sure what was the result of this discussion but I added those two flags as it's less work than talking about it :)

We don't know the optimum solution right now (like whether we need more memory/cpu for supporting concurrent operations). Editing vmx is a solution but with those two we could experiment much more easily.
