### ISSUE TITLE
Cross device link error

### ISSUE THREAD

**Issue by hagenmt** [vmware/vic#789]
**VIC Version:**

master

**Code**

```ts
imagec -standalone -reference photon
```

**Expected behavior:**
Not sure if this is working as intended or not, but a basic Ubuntu install usually creates the home dir on a different partition from /tmp. This causes the below error when trying to run imagec as standalone. The work around is to make sure you always run imagec on the same device as /tmp directory.

**Actual behavior:**
time="2016-05-25T16:35:59Z" level=fatal msg="Failed to fetch image manifest: rename /tmp/690795478 images/https/registry-1.docker.io/v2/library/photon/latest/manifest.json: invalid cross-device link"

**Comment by fdawg4l** [comment]
@hagenmt The `standalone` flag is for development. In production we only have one device with 1 partition so this isn't an issue.

**Comment by hickeng** [comment]
@caglar10ur is this a quick fix? We will need something similar for #1147

**Comment by caglar10ur** [comment]
use -destination parameter (like ... -destination /tmp) as we use rename to atomically move files

**Comment by hickeng** [comment]
closing as usage error
