### ISSUE TITLE
Nightly 04/30/18 5-25-OPS-User-Grant docker pull returns 143

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7893]
04/30/18, VC 6.5, 5-25-OPS-User-Grant
Test case: vic-machine configure grants ops-user perms, Run privilege-dependent docker operations

command: 
```
docker -H sc2-rdops-vm08-dhcp-12-197.eng.vmware.com:2376 --tls pull busybox 2>&1
```

return code is 143. Output:
```
Using default tag: latest
latest: Pulling from library/busybox
f70adabe43c0: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
f70adabe43...
```

It seems that the container was unexpectedly stopped/exited. 

On that day PR https://github.com/vmware/vic/pull/7874 was not merged yet, so there was still a bug in the robot test that the container logs and appliance logs for the VCH were not collected. Without those logs, it's hard to diagnose what happened. We might want to de-prioritize this and wait until a re-pro. 

Link: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-30-00-29-07.zip?authuser=1

**Comment by sgairo** [comment]
Will wait for latest set of nightly triage to determine whether this is still an issue.

**Comment by renmaosheng** [comment]
this doesn't look like a p0 bug.

**Comment by zjs** [comment]
@luwang-vmware, please close this if it's no longer failing.

**Comment by luwang-vmware** [comment]
We did not see this issue in recent run, so close it for now.
