### ISSUE TITLE
Ensure upgrade moves all VCH containers into VCH Folder

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7930]
Version 1.4 introduced Inventory folder support for the VCH and it's containers.  When a VCH is deployed a folder is created and the folder contains the VCH endpoint and will contain future containers.

During upgrade from a pre 1.4 release to 1.4+ that same folder structure is created and all associated VMs (endpoint & containers) are moved into the newly created folder.  If there is a failure or roll back of the upgrade there is the potential that container VMs will not be moved into the folder.  This could result in the endpoint no longer identifying the containers as belonging to itself.  Subsequently docker CLI operations on the containers wouldn't be available and `vic-machine delete` would fail leaving behind these stranded containers.

Steps to reproduce:
1. Deploy vic 1.3.1, but deploy no containers once the endpoint is operational
2. Upgrade to 1.4
3. Either rollback to 1.3.1 (this could be accomplished via `vic-machine upgrade --rollback` or having step 2 fail with an artificially low timeout -- say 1s i.e. `vic-machine upgrade ... --timeout 1s`
4. Deploy container VMs with rolled back endpoint
> Step 2 resulted in the creation of a folder and the endpoint being placed in that folder.  Step 3 returned the endpoint to the 1.3.1 bits, which doesn't utilize folders.  Step 4 will create the container VMs in the default `vm-folder` and _not_ in the same folder as the endpoint.
5. Upgrade to 1.4
> Since the endpoint is already in a folder (due to step 2) there is no folder work initiated, so the containers created in Step 4 are not moved.  Those unmoved containers are now orphaned.  They will continue to work, but can no longer be administered via the CLI or removed on a `vic-machine delete`

Acceptance:
- [ ] Update inventory code to ensure that all containers are moved into the endpoint folder
- [ ] Update `11-01-Upgrade` to verify successful move

Marked as a `p0` since there currently is no regression testing for folder support during a `vic-machine upgrade`.

**Comment by luwang-vmware** [comment]
The latest vic-product version we supported is 1.5.2.  And I think there is very few customer who will use the scenario as in the description. So close it for now.
