### ISSUE TITLE
Add NSX-T support for the Nightlies

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#7934]
**User Statement:**
Goal is to validate the VIC engine workflow support on the latest NSX-T setup.

**Details:**
We need to add the NSX-T support to nightlies in addition to the NSX-v that we currently support. This is to ensure test support for VIC to consume NSX-T networks and NSX dynamic security policy integrations workflows.

**Acceptance Criteria:**
Nightlies running the NSX-T tests in addition to NSX-V

**Comment by rajanashok** [comment]
Created an NSX-t nimbus testbed and noticing what @lcastellano observed during his wolfpack investigation work. The nsx-t-network is showing as a opaque network in VC, and VIC expects a Distributed Port Group. Discussed this with @hickeng , seems like a trivial fix in the VIC Engine code to support NSX-T based networks in addition to supporting the network security policy workflows in VIC 1.5. Going to add a NSX-t based nightly test in the meantime.

**Comment by renmaosheng** [comment]
This is a dup of https://github.com/vmware/vic/issues/8331 , code is merged. closing this.
