### ISSUE TITLE
Investigate impact of Overlay Network (Flannel) on POD/VM for Wolfpack and Virtual Kubelet

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#7936]
**User Statement:**
Both Wolfpack and Virtual Kubelet try to decouple PODs from Kubernetes Nodes. This investigation tries to identify the Network-Overlay components that must be included in the decoupled PODs.

**Details:**
Overlay-Networks that are integrated with Kubernetes need to perform configuration operations where the PODs are running. Since both Wolfpack and the Virtual Kubelet separate the PODs from the Kubernetes (Minion) Nodes, some of the Overlay-Network configuration needs to happen within the decoupled POD. This investigation is particularly focused on Flannel and its components.

**Acceptance Criteria:**
A document that explains what need to be included or modified to make decoupled POD work with Flannel and Virtual Kubelet/Wolfpack.

**Comment by morris-jason** [comment]
@lcastellano will this include a larger investigation about CNI components, or is this only focused on Flannel?

**Comment by lcastellano** [comment]
This investigation is focused on Flannel. However, Weave has a similar architecture and is very likely to suffer from the same limitation. The following PDF document contains the results of the investigation and a proposal for Wolfpack networking. 

https://confluence.eng.vmware.com/display/CNA/Wolfpack+Networking
