### ISSUE TITLE
Incorrect output when pulling from a bad repository

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#794]
**VIC Version:**

master

**Code**

```ts
docker -H <vic> pull fakebadrepo.com:9999/ubuntu
```

**Expected behavior:**
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://fakebadrepo.com:9999/v0/
v2 ping attempt failed with error: Get https://fakebadrepo.com:9999/v2/: dial tcp: lookup fakebadrepo.com on 127.0.1.1:53: no such host
 v1 ping attempt failed with error: Get https://fakebadrepo.com:9999/v1/_ping: dial tcp: lookup fakebadrepo.com on 127.0.1.1:53: no such host

**Actual behavior:**
Using default tag: latest
Error response from daemon: exit status 1

**Comment by caglar10ur** [comment]
after #964
```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(807)] docker -H 192.168.218.144:2376 --tls --tlscert='./ZzZ-cert.pem' --tlskey='./ZzZ-key.pem' pull  fakebadrepo.com:9999/ubuntu
Using default tag: latest
Error while pulling image: Head https://fakebadrepo.com:9999/v2/: dial tcp: lookup fakebadrepo.com on 192.168.218.2:53: no such host
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(807)]
```
