### ISSUE TITLE
PSC fail to intialize with VIC

### ISSUE THREAD

**Issue by virtuosityyc** [vmware/vic#7962]
VIC Product version:

OVA version vic-v1.3

Deployment details:

Environment where the OVA is deployed
vCenter 6.5 

Steps to reproduce:
Deploy VIC from OVA - work ok
Start VIC - work OK
Try first Initiate VIC with vCenter 6.5 embedded PSC from www web page - error message

Actual behavior:
Recive information:
Failed to register with PSC. Please check the PSC settings provided and try again

Expected behavior:
Register VIC to vCenter no error message

Logs:
journalctl -u fileserver logs as below 

May 17 03:51:23 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:23Z" level=info msg="render: html/index.html"
May 17 03:51:23 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:23Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
May 17 03:51:24 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:24Z" level=info msg="render: html/index.html"
May 17 03:51:24 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:24Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=info msg="server URL: 10.188.97.100\n"
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Accepting host \"10.188.97.100\" thumbprint 9B:DE:20:F6:28:DF:54:DA:92:3C:
28:BE:92:9D:B2:36:FB:A0:A6:37"
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Creating VMOMI session with thumbprint 9B:DE:20:F6:28:DF:54:DA:92:3C:28:BE
:92:9D:B2:36:FB:A0:A6:37"
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Session Environment Info: " API Type=VirtualCenter API Version=6.5 Build=8
024368 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=2a8e1053-9cce-428d-a790-c5a4e8c9e77b Vendor="VMware, Inc." Version=6.5.0
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="vSphere resource cache populating..."
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Cached dc: "
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Cached cluster: "
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Cached host: "
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Cached pool: "
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Cached folders: "
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="Error count populating vSphere cache: (1)"
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=debug msg="new validator Session.Populate: Failure finding ds (): default datastore r
esolves to multiple instances, please specify"
May 17 03:51:37 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:37Z" level=info msg="Validation succeeded"
May 17 03:51:38 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:38Z" level=debug msg="successfully attached the product tag"
May 17 03:51:38 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:38Z" level=info msg="vCenter user: vmwarepoc@vsphere.local"
May 17 03:51:38 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:38Z" level=info msg="PSC instance: vctrbgipv02.portaldom.ent.intranet.rhbbank.com"
May 17 03:51:38 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:38Z" level=info msg="PSC domain: vsphere.local"
May 17 03:51:38 Photon start_fileserver.sh[805]: time="2018-05-17T03:51:38Z" level=info msg="PSC Out of the box users. CreateUsers: True, FoundCreateUsers: true, Prefix
: vic"
May 17 03:52:27 Photon start_fileserver.sh[805]: time="2018-05-17T03:52:27Z" level=info msg="Error running PSC register command for harbor: [0][I][2018-05-17T03:51:38.6
52Z][1][SsoPscCommand][register][Initializing...]\n[1][I][2018-05-17T03:51:38.663Z][1][SsoPscCommand][register][Registering...]\n[2][I][2018-05-17T03:51:38.702Z][1][Sso
PscCommand][deleteFile][Removal of file: '/etc/vmware/psc/harbor/psc-config.keystore' result: true]\nException in thread \"main\" com.vmware.admiral.auth.idm.psc.saml.s
so.admin.SsoAdminClientException: Can not retrieve the SSO SSL certificate chain.\n\tat com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createS
SOAdminClient(SsoAdminClientFactoryImpl.java:158)\n\tat com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminFacade.registerOrRetrieveSolutionUser(SsoAdminFacade.java
:172)\n\tat com.vmware.admiral.auth.idm.psc.saml.util.SsoPscCommand.register(SsoPscCommand.java:83)\n\tat com.vmware.admiral.auth.idm.psc.util.PscCommand.execute(PscCom
mand.java:37)\n\tat com.vmware.admiral.auth.idm.psc.util.PscCommand.main(PscCommand.java:47)\nCaused by: java.net.UnknownHostException: vctrbgipv02.portaldom.ent.intran
et.rhbbank.com\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n\tat j
ava.net.Socket.connect(Socket.java:589)\n\tat sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)\n\tat com.vmware.admiral.auth.idm.psc.saml.sso.platform.sec
urity.SslCertificateResolver.connect(SslCertificateResolver.java:96)\n\tat com.vmware.admiral.auth.idm.psc.saml.sso.admin.SsoAdminClientFactoryImpl.createSSOAdminClient
(SsoAdminClientFactoryImpl.java:105)\n\t... 4 more\n"
May 17 03:52:27 Photon start_fileserver.sh[805]: time="2018-05-17T03:52:27Z" level=debug msg="exit status 1"
May 17 03:52:27 Photon start_fileserver.sh[805]: time="2018-05-17T03:52:27Z" level=info msg="render: html/index.html"
May 17 03:52:27 Photon start_fileserver.sh[805]: time="2018-05-17T03:52:27Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
May 17 03:52:28 Photon start_fileserver.sh[805]: time="2018-05-17T03:52:28Z" level=info msg="render: html/index.html"
May 17 03:52:28 Photon start_fileserver.sh[805]: time="2018-05-17T03:52:28Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"

Additional details as necessary:
I try register VIC base on IP address and FQDN result is the same.

**Comment by mdubya66** [comment]
Issue moved to [vmware/vic-product #1765](https://github.com/vmware/vic-product/issues/1765) via [**ZenHub**](https://www.zenhub.com/)
