### ISSUE TITLE
UI integration for vic-machine

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#799]
vic-machine needs to be integrated with the UI.
Investigation will be needed, and discussion with the UI team to see what's necessary, as vic-machine operates differently than the old Bonneville installer.

**Comment by hickeng** [comment]
@gigawhitlocks I'm assuming you don't actually mean that vic-machine has to be intergrated with the webclient - but that this is for vic-machine installing a UI portlet. Am I correct? Please update the issue description with specific integration intent.

**Comment by andrewtchin** [comment]
Detailed proposal in #1101

**Comment by hickeng** [comment]
closing in favour of #1101 as that contains more details
