### ISSUE TITLE
Propagate opid to portlayer from caller

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7993]
**Story**
As a VCH developer I want to be able to easily correlate between different component logs, all the way from incoming API request through to ESX logs.

**Detail**
We current propagate opid from portlayer to vSphere so that it's easy to correlate between portlayer.log, vpxd.log, and hostd.log.
However we do not currently propagate from personality to portlayer, meaning we have the individual calls to the portlayer but no easy way of unifying/extract related calls from the portlayer logs.

I expect this to start via a header parameter being added to all port layer calls and client/server middleware to marshal/unmarshal, e.g.:
```diff
--- a/lib/apiservers/portlayer/swagger.json
+++ b/lib/apiservers/portlayer/swagger.json
@@ -15,6 +15,15 @@
        "schemes": [
                "http"
        ],
+       "parameters": {
+               "operationID": {
+                       "name": "OPERATION-ID-HEADER",
+                       "type": "string",
+                       "pattern": "[0-9]+\\.[0-9]+",
+                       "in": "header",
+                       "required": "true",
+               },
+       },
        "paths": {
                "/_ping": {
                        "get": {
```

**Acceptance**
An opid is assign to all incoming API requests, and can be easily extracted from all other component logs (portlayer and vSphere).
E.g. opId=X in personality, opID=X.1 then opID=X.2 for sub calls to the portlayer, and opID=X.1 et al in vSphere.

- [ ] INFO level logging on entry point in the docker back-end
- [ ] Extract Op object from Context before calling the port-layer in the proxies
- [ ] Modify swagger specs file to pass OpId to the port-layer

**Comment by lcastellano** [comment]
Closed by preceding PRs.
