### ISSUE TITLE
VCH create using vic-machine-windows.exe does not handle forward slashes

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#8001]
**vic version**
1.3

**Bugzilla  id**
2046866

```When using powershell with vic-machine-windows.exe forward slashes "/" are not handled for dvsPortGroups and suggested dvsPortGroups replace the forward slash with %2f```

Similarities with #6041 

Has workaround.

bug2046866

**Comment by renmaosheng** [comment]
we will suggest to use the workaround. won't fix this.
