### ISSUE TITLE
TDNF Support in ISO Build Scripts

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic#8019]
### Story
As a VIC developer I want to use the latest released version of photon using update build scripts for the makefile.

### Details

Upgrading to photon 2 requires updates to the iso scripts to use tdnf instead of yum.

### Acceptance Criteria
- [ ] Define abstraction approach for kernel specific elements
- [ ] Design a convenient custom repo spec
- [ ] Document use of a custom repo 
- [ ] Add Photon2.0 tdnf container build image
- [ ] Update script functions for caching and install for tdnf

**Comment by zjs** [comment]
@DanielXiao has this been addressed as a part of the Photon 2.0?

**Comment by DanielXiao** [comment]
It is already addressed.
