### ISSUE TITLE
Check validity of host configuration 

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#802]
For a host to be a valid container target it must:
* be attached to the shared storage for container, image and volume stores
* have a firewall configuration that allows for the backchannel
* be attached to the bridge DVS in vCenter
* be attached to any mapped vSphere networks 

This check should be made in the installer, but written in such a fashion that it can also be done in the appliance as hosts may be added dynamically after the fact. We should only place VMs onto the set of hosts that is valid, irrespective of other hosts in the cluster.
DRS can only help based on configuration at power on time which may or may not suffice.

We should generate a warning if only one host matches the criteria as that would mean vMotion cannot be performed.

**Comment by hickeng** [comment]
@emlin this is part of the validation checks needed in vic-machine

**Comment by hickeng** [comment]
Part of this is implemented already - however we still need checks for:
volume stores
bridge dvs
mapped networks

**Comment by mdubya66** [comment]
@andrewtchin please review all the validation Issues for duplicates and let's create an epic to track them all for GA

**Comment by andrewtchin** [comment]
created the epic, need to go through all the issues

**Comment by andrewtchin** [comment]
validations listed in this issue are resolved, closing
