### ISSUE TITLE
Parallel full CI failure: "Length of '[]' should be 2 but is 0." in "Connect container to a new network"

### ISSUE THREAD

**Issue by zjs** [vmware/vic#8041]
Full CI failure: "Connect container to a new network" in `1-17-Docker-Network-Connect`

> Length of '[]' should be 2 but is 0.

https://ci-vic.vmware.com/vmware/vic/19328/7

Judging solely by the error message and intermittent nature, this may be a concurrency issue resulting from parallel test execution.

![image](https://user-images.githubusercontent.com/408880/41274014-aec8e642-6dd0-11e8-8c20-c4fcf07c3902.png)

[Logs](https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_19328_f19a2f2f8142f91bb99690a867ae9aed8f597e52.zip)

**Comment by renmaosheng** [comment]
will reopen if we hit this again.
