### ISSUE TITLE
NFS VolumeStore FQDN not working

### ISSUE THREAD

**Issue by alatdev** [vmware/vic#8043]
**VIC version:**

1.4.0

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
vic-machine-windows create --name lvte11 --container-name-convention lvte11_{name} --compute-resource vmcl01 --image-store vmfs12_vmcl01 --base-image-size 8GB --volume-store vmfs12_vmcl01:vsphere --volume-store vmfs12_vmcl01:default --bridge-network lvte11-bridge --bridge-network-range 172.16.0.0/12 --public-network 10.10.x.x --public-network-ip 10.10.1.236/16 --public-network-gateway 10.10.0.10 --dns-server 10.1.44.40 --container-network 10.10.x.x:10.10.x.x --container-network-ip-range 10.10.x.x:10.10.2.230-10.10.2.235 --container-network-gateway 10.10.x.x:10.10.0.10/16 --container-network-dns 10.10.x.x:10.1.44.40 --container-network-firewall 10.10.x.x:published --tls-cname lvte11 --certificate-key-size 2048 --tls-ca Land_Salzburg_Trust_Sub-04_CA.crt --user xxx --thumbprint xxx --target lvvm02.land-sbg.gv.at --registry-ca registry_ca.crt --ops-user xxx --affinity-vm-group --volume-store nfs://lvte24.land-sbg.gv.at/lvte11:nfs

**Steps to reproduce:**
docker volume create --opt VolumeStore=nfs --name test_ubuntu
docker run -it -v test_ubuntu:/mnt/test --net=10.10.x.x lvte05.land-sbg.gv.at/default-project/alpine:latest

**Actual behavior:**
When using FQDN to the NFS-Share, the container won't start. I cannot set a DNS-Search-List.
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: container VM has unexpectedly powered off.

If I use the IP address, it works.

**Expected behavior:**
Container can reach NFS Share by FQDN.

**Logs:**

[container-logs_fqdn_notworking.zip](https://github.com/vmware/vic/files/2094534/container-logs_fqdn_notworking.zip)

bug2104495

**Comment by hickeng** [comment]
The error showing in the `tether.debug` file for the containerVM is:
```
Jun 12 2018 14:35:17.917Z ERROR mounting nfs://lvte24.land-sbg.gv.at/lvte11/volumes/test_ubuntu on /mnt/test failed: invalid argument
```
I have not confirmed, but believe that the mount syscall should be passed an IP address and not an unresolved name.

Starting point hint: https://github.com/vmware/vic/blob/346982a76e5947d62b6629c6826223a84881640c/lib/tether/ops_linux.go#L951

**Comment by zjs** [comment]
@stuclem: Could we consider retroactively adding this to the release notes or docs for 1.4? ([context](https://vmwarecode.slack.com/archives/C293W9V0A/p1544635210029100))

**Comment by stuclem** [comment]
@zjs I updated the release notes for all 1.4.x releases:
https://github.com/vmware/vic/releases/tag/v1.4.3#knownissues
https://github.com/vmware/vic/releases/tag/v1.4.1#knownissues
https://github.com/vmware/vic/releases/tag/v1.4.0#knownissues
