### ISSUE TITLE
Support creating container VMs with volumes

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#806]
Support `docker create` with anonymous volumes.

(Please convert to epic, add story points, reword, etc. as you see fit.)

**Comment by mdubya66** [comment]
@fdawg4l @matthewavery should this be closed?

**Comment by matthewavery** [comment]
Not quite yet, I am planning on contacting Nandita this morning about what needs to get done.

**Comment by corrieb** [comment]
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-4-Docker-Create.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by corrieb** [comment]
Latest update from Faiyaz: "for clarity, the images directory on the datastore should be specified via vic-machine and used in the port layer like we are for volumes.  volumes is A-OK". Sounds like this needs to remain open and move to onsite.

@matthewavery are you clear on what remains to be done here?

**Comment by fdawg4l** [comment]
I think this is done.  @matthewavery , what do you think?

**Comment by fdawg4l** [comment]
Closing this.  @matthewavery, please re-open if you don't feel this is done.
