### ISSUE TITLE
Update to govmomi/govc 0.8.0 release

### ISSUE THREAD

**Issue by dougm** [vmware/vic#809]
Planning a new release of govmomi/govc the week of 6/27 to incorporate the various VIC related enhancements.

**Comment by dougm** [comment]
Putting some time into this yesterday/today, mainly for:

- Changes in support of govcsim

- Starting to test govmomi/govc against govcsim, so there are some misc changes coming to pkg/vsphere/simulator

- Recursive Finder support (traverse into Folders)

- Poking at SDRS/Datastore Cluster (via nimbus)

**Comment by hickeng** [comment]
@dougm are you aware of any significant addition items to go into govmomi for TP3 timeframe (thursday)? If not, can we get this done by 6/28 so we've got a couple of days with it before release.

**Comment by dougm** [comment]
No major changes planned, but a minor one to revert the use of service ticket hostname for datastore access, mentioned in #1157 

I'll get that change in and do a tag+release of govmomi, followed by vendor update in vic (by 6/28)

**Comment by dougm** [comment]
#1230 should be the last code update for vendor/govmomi before making a 0.8.0 tag/release.  This will only change the vic/vendor/manifest so we point to the tagged commit.
