### ISSUE TITLE
vic-machine: ls

### ISSUE THREAD

**Issue by emlin** [vmware/vic#810]
vic-machine ls command will list all VCHs installed in VC/ESXi. And read VCH information from guestinfo.

Usage sample:
```
vic-machine ls
-FROM=https://root@****:vcenter/

ID        Path                                Notes
vm-239    mycluster/edw-pool/web/edw-web      Notes from the VCH config
vm-2372   mycluster/random/someother          Another VCH in the random pool
+vm-15    mycluster/xyz                       VCH in the root of the cluster
```

The following example lists VCHs under a specific resource
```
vic-machine ls
-FROM=https://root@****:vcenter/example-datacenter/host/mycluster/Resources/edw-pool/
```
Note: command line parameter is still working in progress.

**Comment by mdubya66** [comment]
no issues. removed the document issue and closed

**Comment by stuclem** [comment]
So, @mdubya66 and @emlin, is this not happening?

**Comment by mdubya66** [comment]
Closed by mistake. Re-opening. @emlin let's get an issue open for the dev portion of this so we don't have an epic with one item. This is a GA requirement.

**Comment by mdubya66** [comment]
GA feature from SSOD

**Comment by hickeng** [comment]
@emlin can this be closed?
