### ISSUE TITLE
Suspected parallelism issues in `3-03-Docker-Compose-Basic`

### ISSUE THREAD

**Issue by zjs** [vmware/vic#8130]
Build: https://ci-vic.vmware.com/vmware/vic/19563
Logs: https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_19563_b3a619231503620476d5553e59f70287972f1905.zip

Failed tests:
 * `Compose up -d with a new image`
 * `Compose up in foreground (attach path)`

Based on log.html, these tests seemed to be running concurrently, and the second test to start seems to have complained that `Found orphan containers (vic_web_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.`)

If this is not a parallelism issue, it may be a networking issue (the first test reports: `Couldn't connect to Docker daemon at https://dhcp-wdc-pod2-haas01-170.eng.vmware.com:2376 - is it running?`)

**Comment by luwang-vmware** [comment]
Close it now  we did not see this issue any more.
