### ISSUE TITLE
Docker pull on docker store fails

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#8138]
Docker pull on images on docker store fails.  For instance,

```
docker pull store/ibmcorp/db2wh_ce:v2.9.0-db2wh_client-linux
```

Internal bug 2152747.

**Comment by sflxn** [comment]
I found the cause of this issue.  We changed the default registry URL from registry-1.docker.io to registry.hub.docker.com as part of the content trust work.  I didn't work on that and have no knowledge of it, and the people who made the changes do not remember why we made the change.  In any case registry-1 is actually hardcoded in docker's code so I think we can just change it back and see if our ci build complains during the content trust tests.

I've also fixed a bug in the fetcher pertaining to interpretation of unauthorized access.  It was presenting an improper error message leading me down the wrong path during debugging.  We should now return access denied, which the docker registry code also returns.

**Comment by stuclem** [comment]
@sflxn do we need to document this?

**Comment by stuclem** [comment]
Sorry about the accident close!

**Comment by zjs** [comment]
> do we need to document this?

I think it's worth a release note, as it's something customers had reported as broken, but I don't think it needs to be mentioned in the user documentation.

**Comment by stuclem** [comment]
Added as a resolved issue in https://github.com/vmware/vic/releases/tag/v1.4.3

**Comment by dbarkelew** [comment]
https://kb.vmware.com/s/article/56634 will also need to be updated once the fix is available.
