### ISSUE TITLE
mssql container crashes on VIC

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#8141]
**Bugzilla Bug Number:**
2124217

**VIC version:**
 VIC master commit: fddf519

**Deployment details:**
--target=https://office2-sfo2-dhcp24.eng.vmware.com/vicdc
--name=vch-luca-1
--compute-resource=viccluster
--image-store=vsanDatastore
--volume-store=vsanDatastore/volumes:default
--bridge-network=BridgeNetwork
--tls-cname=*.eng.vmware.com
--insecure-registry=wdc-harbor-ci.eng.vmware.com
--syslog-address=tcp://10.161.191.14:514
--timeout=10m0s
--debug=2

**Steps to reproduce:**
run the following command:
```
docker -H VCH_IP:2376 --tls  run --name DEV05 -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=P@ssw0rd" -p 5533:1433 -d microsoft/mssql-server-linux:2017-latest
```
**Actual behavior:**
```
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:

       Reason: 0x00000003
      Message: result
   Stacktrace: 000055a653eab8e2 000055a653e488d7
      Process: 243 - sqlservr
       Thread: 247 (application thread 0x1000)
  Instance Id: f2faa9c2-0f91-412d-90bf-ed32cd10c199
     Crash Id: 8526decb-5b37-4f70-adb0-2e8444dd6538
  Build stamp: ee3d3882f1c48a7a7e590a620153012eaedc2f37143d485df945a079b9d4eeea

Capturing core dump and information...
No journal files were found.
No journal files were found.
Attempting to capture a dump with paldumper
```

**Expected behavior:**
The container should start up correctly.

**Logs:**
[clogs.zip](https://github.com/vmware/vic/files/2190715/clogs.zip)

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

**Comment by hickeng** [comment]
Details as to the cause can be found here: https://support.microsoft.com/en-us/help/4134638/sql-server-2017-terminates-and-generates-a-core-dump-on-rhel-7-4-when

This is not a crash, but is a failed assertion by `mssql` about the layout of the memory address space for the process. Additional notes in bug2124217.

**Comment by zjs** [comment]
I think this is worth a release note, as it was a customer-reported issue.
