### ISSUE TITLE
Add a --no-proxy option for the VCH

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#8144]
**Story**
As a viadmin with a proxy that does not allow hairpin traffic I need to be able to exclude certain traffic from being proxied.

**Detail**
The ability to defining an exclusion set for connections that should not be proxied is desirable in general and an absolute requirement in some networking configurations.

This issue is for adding a basic `no-proxy` exclusion set to complement the current https and http proxy settings. As part of this issue, the types and origins of traffic for which this configuration is used should be documented (e.g. does traffic on the management network honor the proxy config?).

This issue is _not_ expected to allow for per-network proxy configuration - that should be deferred until a manifest specification for a VCH is supported as adding more CLI options for niche/rare cases will only add to existing issues with complexity impacting ease-of-use.

This issue needs further refinement:
* design - which components should make use of the proxy settings and for which connections
* documentation - need to be explicit in the docs as to which connections will be proxied - include updates to network diagram with colouration to indicate connections that can/will be proxied.
* declaration of acceptance tests

bug2157829

**Comment by hickeng** [comment]
Added into 1.4.2 due to bug2157829 and explicit impediment in real usage.

**Comment by wjun** [comment]
The proxy settings are used by personality server and vicadmin process on VCH VM as the environment variables.

**Comment by hickeng** [comment]
Expanding on @wjun's comment, see https://github.com/vmware/vic/blob/22b36734fced2ab0c90e44deb96c2508310da392/lib/install/management/appliance.go#L573 and https://github.com/vmware/vic/blob/22b36734fced2ab0c90e44deb96c2508310da392/lib/install/management/appliance.go#L604

**Comment by zjs** [comment]
I think this is worth a release note, as it was a customer-requested enhancement.

**Comment by stuclem** [comment]
Added as a new feature in https://github.com/vmware/vic/releases/tag/v1.4.3 and documented fully in https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/vch_proxy.html
