### ISSUE TITLE
'docker kill' creates different behavior on VIC 1.4.0 and 1.2.1

### ISSUE THREAD

**Issue by RebeccaYo** [vmware/vic#8152]
**VIC version:**

1.4.0

**Deployment details:**

./vic-machine-linux create --debug 2 --name WV-VCH-2 --public-network-ip 192.168.10.95/24 --management-network PublicNetwork --insecure-registry 10.115.68.63:443 --compute-resource ordos12.eng.vmware.com --no-tlsverify --no-tls --thumbprint ... --target 10.115.68.198 --user administrator@vsphere.local --image-store Tegile-Lun0a --volume-store Tegile-Lun3a:default --volume-store Tegile-Lun1a:Tegile-Lun1a --volume-store Tegile-Lun1b:Tegile-Lun1b --bridge-network VCH1BridgeNetwork --client-network Testbed --public-network Testbed --container-network Testbed:cn1 --dns-server 192.168.10.101 --public-network-gateway 192.168.10.101 --endpoint-cpu 1 --endpoint-memory 2048

**Steps to reproduce:**

Running Weathervane log level 3 or higher. When the Weathervane stats collection starts for Dockerized services, the run harness sends a signal to the Docker container (SIGUSR1) using the `docker kill` command. This appears to cause the container's tomcat application server process to get killed.

**Actual behavior:**
The signal to the Docker container (SIGUSR1) using the 'docker kill' command appears to cause the container's tomcat application server process to be killed, as the timing coincides. This prevents the Weathervane application from running correctly. Is this expected behavior?
When running Weathervane with log level 2, the run harness does not issue the same command and Weathervane runs correctly.

**Expected behavior:**
On VIC 1.2.1 and previous versions, running with log level 3, Weathervane ran correctly.
I have not tested behavior on VIC versions between 1.2.1 and 1.4.0.

**Logs:**
See comment

**Comment by RebeccaYo** [comment]
[container-logs.zip](https://github.com/vmware/vic/files/2211970/container-logs.zip)

**Comment by lcastellano** [comment]
A recent change in the VIC source code sends signals to the process group of the main process rather than to the process itself. This could explain why the signal was delivered to the entry point bash script and to Tomcat. However, this would only happen if Tomcat were to join main process group, which may be unlikely. It would be helpful to have access to the image of this container (tomcat/weathervane) as the building process appears to be rather complex.

**Comment by RebeccaYo** [comment]
Thank you @lcastellano, the image can be found here: https://hub.docker.com/r/griderr/weathervane-tomcat/

**Comment by lcastellano** [comment]
Thanks @RebeccaYo. With the image you supplied I was able to recreate the issue. I was also able to confirm (docker exec -ti <container-id> /bin/bash inside the container) that "entrypoint.sh" and "java" were running within the same process group and therefore were both targeted by the kill command. Here the ps output before and after the kill command:

```
ps  xao pid,ppid,pgid,sid,comm
  PID  PPID  PGID   SID COMMAND
...
  307     1   307   307 entrypoint.sh
  325     1   307   307 java
...
```

after the kill

```
ps  xao pid,ppid,pgid,sid,comm
  PID  PPID  PGID   SID COMMAND
...
  307     1   307   307 entrypoint.sh
...
```
It should be possible to build a wrapper container image with a different version of "entrypoint.sh". Let me know if such workaround would be useful.

**Comment by RebeccaYo** [comment]
@lcastellano That's great. I'll ping the developer of Weathervane to see if this is something to move forward with.

**Comment by lcastellano** [comment]
I have created/pushed a wrapper image that should work. Let me know if you are interested.

**Comment by lcastellano** [comment]
That is the same approach I took when I built the wrapper image. Let me know how it goes.

**Comment by zjs** [comment]
Fixed in #8163.

**Comment by zjs** [comment]
I think this is worth a release note, as it corrects a previous regression in behavior.

**Comment by stuclem** [comment]
Added the following as a resolved issue in https://github.com/vmware/vic/releases/tag/v1.4.3

- <b>'docker kill' has different behavior in versions 1.4.0 and 1.2.1. [#8152](https://github.com/vmware/vic/issues/8152)</b><br>vSphere Integrated Containers Engine now behaves like the Docker server when dealing with `kill` and `stop` commands. When a `kill` command is sent to a container, only the top process receives the signal. When a `stop` command is sent to a container the stop signal is sent to the top process, and after 10 seconds a `SIGKILL` signal is sent to all the member of the process group.
