### ISSUE TITLE
Document Docker ps

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#816]
Add documentation for Docker ps to the document _Developing Container Applications with vSphere Integrated Containers_.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table](http://vmweb.vmware.com/~sclements/github-pages/assets/files/html/vic_app_dev/container_operations.htmll)

**Comment by stuclem** [comment]
Initial implementation of docker ps is in PR https://github.com/vmware/vic/pull/1324.
