### ISSUE TITLE
Suspected parallelism issues in `3-02-Docker-Compose-Voting-App`

### ISSUE THREAD

**Issue by zjs** [vmware/vic#8164]
Build: https://ci-vic.vmware.com/vmware/vic/19648
Logs: https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_19648_da545bafb9e06ffbbfac87898eacf3de5856aa44.zip

Failed tests:
 * `Compose Voting App`

![image](https://user-images.githubusercontent.com/408880/43419873-17ec5c70-93f7-11e8-95cf-df93707ea31d.png)

If not a parallelism issue, this is likely a duplicate of #7638.

**Comment by renmaosheng** [comment]
please close this if this doesn't occur any more.

**Comment by luwang-vmware** [comment]
Close it now  we did not see this issue any more.
