### ISSUE TITLE
"Could not find any VIC appliance VM" error on vcenter VIC plugin page

### ISSUE THREAD

**Issue by indreshmishra** [vmware/vic#8173]
I deployed VIC 1.4 on Vcenter 6.7 , after registering and installing plugin on vcenter , I get following error, even after trying couple of times. Can you please help in this regard.
 
VIC appliance has ProductVM tag, still on VIC plugin page on Vcenter , It's not getting identified.
please see screenshot from vcenter
<img width="695" alt="screen shot 2018-08-03 at 5 01 43 pm" src="https://user-images.githubusercontent.com/4045092/43660480-cb521bfa-977c-11e8-9bcb-b08be19351d3.png">

**Comment by hickeng** [comment]
Please can you collect the log bundle as per [this link](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.monitoring.doc/GUID-7E10C58F-16EA-44AB-8AA0-8D4A66399879.html). This will contain the logs from the UI backend java elements.

**Comment by indreshmishra** [comment]
[vsphere-ui.zip](https://github.com/vmware/vic/files/2258632/vsphere-ui.zip)
attaching html5 client ui logs,

**Comment by DanielXiao** [comment]
@indreshmishra Could you provide vCenter build number? I can not reproduce this issue on vCenter 6.7 8217866 and VIC v1.4.1.1262.

**Comment by javierfz1980** [comment]
I've been doing some test on the reported failing vc `10.161.139.223` and here are my findings:

reported VC https://10.161.139.223/ui is accessible however the vic machine `vic-v1.4.1
` inside `workcluster` is not reachable. I turned on the VM but the VM's ip `10.109.228.146` is not reachable... it always shows `The VIC Appliance is initializing` and doesn't start at all...

<img width="588" alt="initializing" src="https://user-images.githubusercontent.com/36636787/43962920-4f100058-9c8f-11e8-8cdf-c28f93977fcb.png">
<img width="702" alt="vic-ip" src="https://user-images.githubusercontent.com/36636787/43962921-4f3bec2c-9c8f-11e8-8bf0-f1da478cc082.png">

That could be the main reason for the UI to not been able to get access to the Appliance VM.

From the logs, bundles are deployed correctly:

> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:38.659Z] [INFO ] plugin-deploy9                <XF1000I> Deploying plugin package 'com.vmware.vic' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:40.234Z] [INFO ] fs-watcher                    <HD0001I> Hot deployer processing 'CREATED' event for file 'com.vmware.vic-1.4.1.1262.par'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.391Z] [INFO ] fs-watcher                    <DE0000I> Installing par 'com.vmware.vic' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.393Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.395Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.google.gson' version '2.3.1'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.396Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.vmware.wsvim25' version '6.0.2'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.405Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.ui' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.565Z] [INFO ] fs-watcher                    <DE0001I> Installed bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.566Z] [INFO ] fs-watcher                    <DE0001I> Installed bundle 'com.vmware.vic-1.4.1.1262-com.google.gson' version '2.3.1'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.566Z] [INFO ] fs-watcher                    <DE0001I> Installed bundle 'com.vmware.vic-1.4.1.1262-com.vmware.wsvim25' version '6.0.2'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.566Z] [INFO ] fs-watcher                    <DE0001I> Installed bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.ui' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.567Z] [INFO ] fs-watcher                    <DE0001I> Installed bundle 'com.vmware.vic-1.4.1.1262-synthetic.context' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.567Z] [INFO ] fs-watcher                    <DE0001I> Installed par 'com.vmware.vic' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.580Z] [INFO ] fs-watcher                    <DE0004I> Starting par 'com.vmware.vic' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:41.585Z] [INFO ] fs-watcher                    <DE0004I> Starting bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.046Z] [INFO ] fs-watcher                    <DE0004I> Starting bundle 'com.vmware.vic-1.4.1.1262-com.google.gson' version '2.3.1'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.061Z] [INFO ] start-signalling-2            <DE0005I> Started bundle 'com.vmware.vic-1.4.1.1262-com.google.gson' version '2.3.1'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.062Z] [INFO ] fs-watcher                    <DE0004I> Starting bundle 'com.vmware.vic-1.4.1.1262-com.vmware.wsvim25' version '6.0.2'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.063Z] [INFO ] start-signalling-2            <DE0005I> Started bundle 'com.vmware.vic-1.4.1.1262-com.vmware.wsvim25' version '6.0.2'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.069Z] [INFO ] fs-watcher                    <DE0004I> Starting bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.ui' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.070Z] [INFO ] start-signalling-2            <WE0000I> Starting web bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.ui' version '1.0.0' with context path '/ui/vic'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.097Z] [INFO ] fs-watcher                    <DE0004I> Starting bundle 'com.vmware.vic-1.4.1.1262-synthetic.context' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:43.104Z] [INFO ] start-signalling-1            <DE0005I> Started bundle 'com.vmware.vic-1.4.1.1262-synthetic.context' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:47.365Z] [INFO ] start-signalling-2            <WE0001I> Started web bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.ui' version '1.0.0' with context path '/ui/vic'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:19:47.366Z] [INFO ] start-signalling-2            <DE0005I> Started bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.ui' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:20:03.011Z] [INFO ] start-signalling-2            <DE0005I> Started bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' version '1.0.0'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:20:03.012Z] [INFO ] start-signalling-2            <DE0005I> Started par 'com.vmware.vic' version '1.4.1.1262'.
> ./vsphere-ui-runtime.log.stdout:[2018-08-03T11:20:03.012Z] [INFO ] plugin-deploy9                <XF1001I> Deployed plugin package 'com.vmware.vic' version '1.4.1.1262'.



I've also tried with a new fresh VC 67 deployment (same build `8170132` and same VIC 1.4 release `vic-v1.4.1-5547-ad7eb5f8` and everything is working as expected and vic Appliance VM is reacheable.

here are the screenshots
<img width="863" alt="containers-view" src="https://user-images.githubusercontent.com/36636787/43962767-eb341998-9c8e-11e8-8ad2-86528176bd0d.png">
<img width="972" alt="summary-view" src="https://user-images.githubusercontent.com/36636787/43962768-eb57562e-9c8e-11e8-9e67-116a768b58f2.png">
<img width="917" alt="vch-view" src="https://user-images.githubusercontent.com/36636787/43962770-eb83ed56-9c8e-11e8-9e4a-fa3c13722219.png">
<img width="920" alt="vic-machine" src="https://user-images.githubusercontent.com/36636787/43962772-eba87c52-9c8e-11e8-867b-7bcf923ab1a7.png">
<img width="1465" alt="appliance-vm" src="https://user-images.githubusercontent.com/36636787/43962866-2747f86e-9c8f-11e8-8631-0dd6e4575b04.png">

**Comment by zhoumeina** [comment]
This vc can not be reached now. @indreshmishra , does this problem still exsit?

**Comment by indreshmishra** [comment]
not reproducing now
