### ISSUE TITLE
vic-machine: registry-ca configure behaviour should replace instead of add

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#8176]
**Story**
As a VCH admin I want to be able to update registry CAs when they change.
As a VCH admin I want to be able to revoke registry CA if needed.

**Details**
The configure behaviour for `registry-ca` is to add rather than to replace (by report - unconfirmed). This is both counter to the behaviour of other configure options and prevents easy removal of currently configured registry CAs.

bug1991988

**Comment by renmaosheng** [comment]
let's provide a correct way of updating registry-ca method.

**Comment by YanzhaoLi** [comment]
I think `replace` registry-ca is not convenient for users when he/she wants to add multiple `registry-ca`s, in which case, he/she has to  provide all existing `registry-ca`s.
BTW, Is it necessary to delete existing `registry-ca`s

**Comment by YanzhaoLi** [comment]
The configure behavior is already `replace`, and supports multiple `--registry-ca` arguments.
I've tested, and code in `validator.go` line 670 `conf.RegistryCertificateAuthorities = input.RegistryCAs` can prove this too.
