### ISSUE TITLE
Document container DHCP support

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#820]
Per https://github.com/vmware/vic/issues/747.

**Comment by stuclem** [comment]
The fix for https://github.com/vmware/vic/issues/747 is in https://github.com/vmware/vic/pull/1256.

**Comment by stuclem** [comment]
Do we actually need to doc anything for this?

**Comment by stuclem** [comment]
@hmahmood, does https://github.com/vmware/vic/issues/747 (https://github.com/vmware/vic/issues/747) have any doc impact? Thanks!

**Comment by hmahmood** [comment]
This really does not have much doc impact, other than to simply add support for DHCP in containers. @stuclem: you have already documented this some with the --container-network options documentation. I think somewhere we also need to say that containers can be put on a network that has DHCP, and that they will acquire and maintain DHCP addresses.

**Comment by npakrasi** [comment]
Added to the Container Operations and Limitations topic.
