### ISSUE TITLE
Document HA support

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#821]
Per https://github.com/vmware/vic/issues/744 and https://github.com/vmware/vic/issues/406.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/744 and https://github.com/vmware/vic/issues/406 and in the Icebox, so moving this doc issue there too.

**Comment by stuclem** [comment]
Here's the doc snippet from the interop topic, for reinsertion once HA/FT support is restored.

----

You can apply vSphere High Availability and Fault Tolerance to both the container VMs and the virtual container host, so that containers and the virtual container host can power on or off independently of each other.

----

**Comment by stuclem** [comment]
#744 and #406 are still in the Icebox with no milestone, so leaving this one in icebox too.

**Comment by stuclem** [comment]
According to @hmahmood in https://github.com/vmware/vic/issues/406#issuecomment-286461378, HA works, so we can update the doc to claim support.

@hmahmood is this true for 0.9? Thanks!

**Comment by hmahmood** [comment]
@stuclem yes, with one bug outstanding: #4237

**Comment by hmahmood** [comment]
@stuclem I don't think my PR actually made it into 0.9 actually, so I guess we can't claim HA support in 0.9.

**Comment by stuclem** [comment]
Thanks @hmahmood. Leaving this one in the 1.1 milestone, in that case.

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#41
