### ISSUE TITLE
Document Docker attach

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#822]
Per https://github.com/vmware/vic/issues/741 and https://github.com/vmware/vic/issues/362.

**Comment by stuclem** [comment]
The implementation of this is in a massive pull request, https://github.com/vmware/vic/pull/681, which has not been merged yet.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/681 has now merged.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table] (https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md)
