### ISSUE TITLE
Document how to find container information in UI

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#823]
Per https://github.com/vmware/vic/issues/719, https://github.com/vmware/vic/issues/575 and https://github.com/vmware/vic/issues/527.

Also https://github.com/vmware/vic/issues/24 (Icebox).

**Comment by stuclem** [comment]
The initial VIC plugin is implemented in PR https://github.com/vmware/vic/pull/1194, which will not be merged until after TP3.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/575 is now obsolete.

**Comment by stuclem** [comment]
Added [Find Container Information in the vSphere Web Client](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/container_portlet_ui.md).

@jooskim is this OK? Thanks!

**Comment by jooskim** [comment]
* In 'Prerequisites' the first bullet point seems to omit the reference to another doc on how to pull a container.
* 4 in 'Procedure': it should be container VM not virtual container host VM. VCH VM contains the 'Virtual Container Host' portlet not the 'Container' portlet

**Comment by stuclem** [comment]
Thanks @jooskim - @npakrasi had already spotted the first one, and the second is sloppy cut-n-paste from the topic on the VCH portlet. Both fixed!
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/container_portlet_ui.md

**Comment by jooskim** [comment]
@stuclem Thanks!

**Comment by jooskim** [comment]
@stuclem Oh one more thing to the 'Result' section; it could show port mapping information if the user specified any port to be exposed.

![image](https://cloud.githubusercontent.com/assets/3834071/17983870/5aa2bae4-6ad4-11e6-98b2-ddb45dd01c1c.png)

**Comment by stuclem** [comment]
Thanks for the info, @jooskim. Reopening.

**Comment by stuclem** [comment]
Done: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/container_portlet_ui.md
