### ISSUE TITLE
Document container name resolution and link support

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#826]
Per https://github.com/vmware/vic/issues/714.

**Comment by stuclem** [comment]
This might belong in the Admin doc rather than in the app dev doc. TBD.

**Comment by stuclem** [comment]
Dev epic https://github.com/vmware/vic/issues/430 is done.

**Comment by stuclem** [comment]
No time to doc this in TP3. Will do so between TP3 and Onsite Beta.

**Comment by npakrasi** [comment]
Adding to the Limitations topic.

**Comment by stuclem** [comment]
I think that this is purely app dev stuff, so removed from the Admin Epic.
