### ISSUE TITLE
Document vSAN support

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#827]
Per https://github.com/vmware/vic/issues/710.

**Comment by stuclem** [comment]
Fix for https://github.com/vmware/vic/issues/710 is in PR https://github.com/vmware/vic/pull/1017.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/710 is moving to GA.

**Comment by stuclem** [comment]
This is hopefully just a case of getting the section on [VSAN interop](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/interop.md#vmware-virtual-san) approved by George and Ben.

**Comment by stuclem** [comment]
We currently state the following in the topic on [Interop](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/interop.md):

"The virtual container host maintains filesystem layers inherent in container images by mapping to discrete VMDK files, all of which can be housed in vSphere datastores on Virtual SAN, NFS, or local disks."

@mhagen-vmware, is this OK?

**Comment by mhagen-vmware** [comment]
That sounds fine to me.
