### ISSUE TITLE
Document vic-machine delete

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#828]
Per https://github.com/vmware/vic/issues/702, https://github.com/vmware/vic/issues/652, https://github.com/vmware/vic/issues/897, and https://github.com/vmware/vic/issues/919.

**Comment by stuclem** [comment]
See https://github.com/vmware/vic/blob/master/doc/design/vic once PR https://github.com/vmware/vic/pull/921/ is merged.

**Comment by stuclem** [comment]
Issue https://github.com/vmware/vic/issues/897 to create the vic-machine delete processor is in progress, so moving this one to To Do.

**Comment by stuclem** [comment]
Pending the implementation of vic-machine delete, I added a topic on how to manually remove a VCH:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/remove_vch.md

**Comment by emlin** [comment]
@stuclem Merged vic-machine delete code yesterday. There will not have functional change, but still might update flags based on usability requirement.

**Comment by stuclem** [comment]
Thanks @emlin.

See also PR https://github.com/vmware/vic/pull/1253, which contains the integration test for vic-machine delete.

**Comment by stuclem** [comment]
See also PR https://github.com/vmware/vic/pull/1302, which fixes issue https://github.com/vmware/vic/issues/1296.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/1290 grabs VCH logs before deleting the appliance. This might just be for internal testing, though. TBC with @mhagen-vmware.

**Comment by stuclem** [comment]
Added a topic on vic-machine delete in admin.

**Comment by stuclem** [comment]
Still need to write up full descriptions of the options for vic-machine delete.

**Comment by stuclem** [comment]
Added new topic that describes the vic-machine inspect options:

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/remove_vch.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/delete_vch_options.md

@emlin are these two topics OK? Thanks!

**Comment by stuclem** [comment]
Actually, I missed two options: force and timeout. @emlin please wait before reviewing.

**Comment by stuclem** [comment]
Have now added force and timeout to https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/delete_vch_options.md

**Comment by emlin** [comment]
@stuclem this looks good.

**Comment by stuclem** [comment]
Thanks!
