### ISSUE TITLE
Docker cp on running containers fails with connection reset by peer

### ISSUE THREAD

**Issue by wjun** [vmware/vic#8285]
#### Summary
Attempting to copy jenkins data tar file to a volume to then attach to a jenkins container, and during the copy the connection is reset by peer and the copy fails.

#### Environment information
docker-vic run -td --name jenkins-vic-data --volume jenkins-dev-data:/jenkins-data-tmp alpine dae2e1410442a13e8e7e9410f3a7683cb9ebbe8aa625911997b4fe031f4f5a4d 

docker-vic cp ~/jenkins-dev-data.tar.gz jenkins-vic-data:/jenkins-data-tmp 
 Error response from daemon: Post http://127.0.0.1:2377/archive?deviceID=jenkins-dev-data&filterSpec=eyJJbmNsdXNpb25zIjp7fSwiRXhjbHVzaW9ucyI6e30sIlJlYmFzZVBhdGgiOiIiLCJTdHJpcFBhdGgiOiIifQ%3D%3D&store=volume: write tcp 127.0.0.1:40792->127.0.0.1:2377: write: connection reset by peer 

##### VIC version
1.4.2 and still exist in 1.4.3

##### Steps to reproduce
Reproduced:
 docker --tls volume create --opt Capacity=5G 5Gvolume
 docker --tls run -id --volume 5Gvolume:/mnt/dockerfile busybox
 docker --tls cp ./vic-v1.4.2-5659-4ee49390.ova frosty_blackwell:/mnt/dockerfile

##### Actual behavior
Connection reset by peer.

##### Expected behavior
Copy file into the volume successfully.

#### Troubleshooting attempted
Found if the container is stopped, then copy is performed this works and starting the container the file is there. 
Could not reproduce with small files like certificates.

according to current implementation at https://github.com/vmware/vic/blob/78f20122e7ed86b817bd99f5902d008c93fbdb55/lib/portlayer/storage/vsphere/toolbox_datasink.go#L57, there is out of memory crash when the file is very large. We need to stop the container and docker cp large file to the volume.

Bugzilla #2200930

**Comment by dbarkelew** [comment]
KB drafted https://ikb.vmware.com/s/article/58926 and pending review and publishing

**Comment by dougm** [comment]
There vSphere API [FileManager.initiateFileTransferToGuest](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.guest.FileManager.html#initiateFileTransferToGuest) requires the `fileSize` param, which must also be the same as the `Content-Length`header when transfering the file.  Chunked encoding is not supported by the vSphere API (or vmx), hence not possible using govmomi.

The vic code above always reads the entire contents into memory here: https://github.com/vmware/vic/blob/78f20122e7ed86b817bd99f5902d008c93fbdb55/lib/portlayer/storage/vsphere/toolbox_datasink.go#L62-L63

If the `fileSize` is known, it can be set here via the `p.ContentLength` param: https://github.com/vmware/vic/blob/78f20122e7ed86b817bd99f5902d008c93fbdb55/lib/portlayer/storage/vsphere/toolbox_datasink.go#L70

If not set, govmomi attempts to derive based on the reader type, an `*os.File` type for example does not read all data into memory: https://github.com/vmware/govmomi/blob/24586273205365c9b7ef8048a40b5009f801ce94/guest/toolbox/client.go#L305-L320

**Comment by renmaosheng** [comment]
We have provided a workaround to customer by stop container first. Mark this as won't fix for now given the library limitation.
