### ISSUE TITLE
Photon 2.0 - Test VCH and cVM with photon 2.0 and Alternative Linux

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic#8289]
#### Summary
Perform test on VCH and cVM with photon 2.0 and Alternative Linux

#### Details
		a. Cover full regression test of VCH and cVM against Photon 2.0.  Ensure no regression in all docker operations. CI and nightly pass. 
		b. For cVM of CentOS 6.9, just perform manual sanity tests and below c and d tests, then let our customer to have a early try and get feedbacks.
		c. Add test cases to cover container network firewall configuration(iptables), Entropy agent running(tomcat), haveged running. 
		d. Add test cases to create at least 2 VCHs with different bootstrap ISOs.
e. For cVM of P1 OS, only perform sanity manual tests.

**Comment by renmaosheng** [comment]
Let's automate the centos 6.9 tests in Sprint 37 as we discussed.
