### ISSUE TITLE
Photon 2.0 - OVA appliance

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic#8290]
#### Summary
Switch OVA appliance to Photon 2.0.

#### Details
1. Develop build scripts to install photon 2.0 OS.  
2. Ensure no regression in OVA tests. CI and nightly pass(not include upgrade).  
3. Upgrade script development and test(All paths).

**Comment by zjs** [comment]
Issue moved to [vmware/vic-product #2103](https://github.com/vmware/vic-product/issues/2103) via [**ZenHub**](https://www.zenhub.com/)
