### ISSUE TITLE
Document instant clone support (VM fork)

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#830]
Per https://github.com/vmware/vic/issues/696.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/696 is in the Icebox, so moving this doc issue there too.

**Comment by stuclem** [comment]
Here's the snippet on instant clone from the interop topic, for reinsertion once instant clone is supported.

---

## vSphere Instant Clone
vSphere Integrated Containers Engine allows you to create and run multiple containers rapidly with minimal overhead using vSphere 6 Instant Clone technology, which provisions child VMs forked directly from a parent VM template running a Linux kernel. vSphere Integrated Containers Engine creates the kernel and a few supporting resources to run containers using Photon OS technology.

---

**Comment by stuclem** [comment]
#696 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by malikkal** [comment]
is VCH the parent VM template from where the jeVM (or container VMs) are forked? if yes, can I adjust the CPU and Memory of the spawned jeVMs rather than the default? P.S. I am aware the overall resources may be capped at the vApp level. Thanks.

**Comment by malikkal** [comment]
Okay, probably I found answer to my own question; should have searched more. Per #1695

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#98
