### ISSUE TITLE
VIC command to reconfigure storage quota

### ISSUE THREAD

**Issue by wjun** [vmware/vic#8306]
During the VCH configure, an administrator should be able to add an optional storage quota flag (--volume-storage-quota) to set or reconfigure the quota or for that VCH.

Acceptance Criteria:
Integration tests for this flag

**Comment by renmaosheng** [comment]
code is ready, but lacking backend code, push to Sprint 36.

**Comment by renmaosheng** [comment]
closing this and keeping the backend open for merging the node.
