### ISSUE TITLE
VIC backend to enable storage quota

### ISSUE THREAD

**Issue by wjun** [vmware/vic#8307]
This storage quota should count against all the images that have been downloaded and in addition all the container VMs that have been started.

This storage quota should not count against any base ISO images that are necessary for the base setup and creation of the VCH.

If the storage quota is exceeded, new Container VMs should not be allowed to be spun up and no new container images should be allowed to be downloaded to the VCH. A “Operation not allowed: Storage quota exceeded” message should be returned to the user.

A VI admin should be able to reconfigure the VCH with an updated storage quota post VCH creation. Since the enforcement happens only on pull / start, there will be no immediate effect if the newly specified storage quota is less than the space currently being consumed. No new pulls / starts should be allowed until enough space is made available.

**Comment by renmaosheng** [comment]
keep this open for merging the code, moving to sprint 39

**Comment by renmaosheng** [comment]
code is merged.
