### ISSUE TITLE
VIC command to support image storage quota

### ISSUE THREAD

**Issue by wjun** [vmware/vic#8308]
@wjun commented on [Wed Sep 26 2018](https://github.com/vmware/vic-planning/issues/121)

During the VCH creation, an administrator should be able to add an optional storage quota flag (--storage-quota) to set the quota for that VCH.

Acceptance Criteria:
Integration tests for this flag

---

@zjs commented on [Thu Sep 27 2018](https://github.com/vmware/vic-planning/issues/121#issuecomment-424808053)

Was this intentionally filed in vmware/vic-planning?

---

@renmaosheng commented on [Thu Sep 27 2018](https://github.com/vmware/vic-planning/issues/121#issuecomment-424907637)

I think we need to move it to vic repo.

**Comment by renmaosheng** [comment]
code is ready, but lacking backend code, push to Sprint 36.

**Comment by renmaosheng** [comment]
closing this and keeping the backend open for merging the node.
