### ISSUE TITLE
Document how to create a multi-tier app (docker compose up)

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#831]
Per https://github.com/vmware/vic/issues/691 and https://github.com/vmware/vic/issues/431.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/693.

**Comment by hickeng** [comment]
@stuclem We need some of this for onsite as this will be one of the core things we want to show.

**Comment by stuclem** [comment]
OK, thanks @hickeng, I have upped the priority.

**Comment by mhagen-vmware** [comment]
Some examples:
https://github.com/vmware/vic/tree/master/tests/test-cases/Group3-Docker-Compose

**Comment by stuclem** [comment]
Great, thanks @mhagen-vmware!

**Comment by corrieb** [comment]
George/Ben review: This is the roll-up of what, why and how of standing up a multi-tier application in a VIC environment. Should also update: https://github.com/vmware/vic/blob/master/doc/design/application-topologies.md

**Comment by stuclem** [comment]
@hickeng, we see that https://github.com/vmware/vic/issues/431 (docker compose up) is flagged for GA. So, what exactly do we need to write up for Onsite Beta? Thanks!

**Comment by stuclem** [comment]
We write up a procedure that uses the same Docker voting app as @mhagen-vmware uses in the [tests](https://github.com/vmware/vic/blob/master/tests/test-cases/Group3-Docker-Compose/3-2-Docker-Compose-Voting-App.md) (and that @corrieb mentions in the topologies doc) to demo that VIC can handle a multi-tier app.

**Comment by stuclem** [comment]
See also: https://github.com/sflxn/vic/blob/docker-support-docs/apiservers/engine/COMPOSE-COMPATIBILITY.md

**Comment by stuclem** [comment]
Examples for `docker compose up` will be included in https://github.com/vmware/vic/issues/2331.

**Comment by stuclem** [comment]
According to https://github.com/vmware/vic/issues/2358, we cannot use the standard docker voting app, so we will have to create a specialized version for VIC.

**Comment by stuclem** [comment]
The modified voting app is implemented in PR https://github.com/vmware/vic/pull/2554.

**Comment by stuclem** [comment]
Some doc about how to create a Dockerize app is added in PR https://github.com/vmware/vic/pull/2561.

**Comment by stuclem** [comment]
The modified voting app implemented in PR #2551 is now merged.

**Comment by stuclem** [comment]
The doc for the dockerized app is now merged in PR https://github.com/vmware/vic/pull/2561.

**Comment by stuclem** [comment]
An example YML for the LEMP example is in PR https://github.com/vmware/vic/pull/2635.

**Comment by stuclem** [comment]
More updates are in PR https://github.com/vmware/vic/pull/2680.

**Comment by stuclem** [comment]
This will not make it for 0.7, so moving back to backlog.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/blob/master/doc/application_workflow/webserving.md

**Comment by stuclem** [comment]
Created topics based on the voting app for VIC:

- [Creating a Multi-Tiered Application with vSphere Integrated Containers Engine](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/creating_multitier_app_with_vic.md)
- [Constraints of Using vSphere Integrated Containers Engine to Build Applications](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/constraints_using_vic.md)
- [Example of Building an Application with vSphere Integrated Containers Engine](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/build_app_with_vic.md)

@sflxn and @chengwang86 can you please review?

Thanks!

**Comment by chengwang86** [comment]
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/constraints_using_vic.md#building-container-images

> As a consequence, you must use regular Docker without vSphere Integrated Containers Engine to build a container and to push it to the global hub or to your private registry server.

This should be "... to build a container image and to push it ...."


https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/build_app_with_vic.md#deploy-the-application-to-a-vch

> In the procedure below, run the commands from the example-voting-app folder that contains the modified docker-compose-simple.yml file

--> The docker-compose-simple.yml file has to be renamed to "docker-compose.yml" (default name); otherwise you will need "-f" or "--file" option in the command to specify the alternative path and file name.

**Comment by stuclem** [comment]
Thanks @chengwang86 !

Made the modifications that you suggest above. Also changed "multi-tiered" to "containerized" just to be safe, following our Slack chat.

Incidentally, renaming the YML file was the one step that I was missing in order to get this example to work, which it now does, so thanks for that!

Changes are in https://github.com/stuclem/vic/commit/cf3c021b54f88510023e8b02fdf960b377428d76. Note that the top-level topic has changed name from `creating_multitier_app_with_vic.md` to [creating_containerized_app_with_vic.md](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/creating_containerized_app_with_vic.md)

@sflxn comments please!

**Comment by stuclem** [comment]
Actually, I spoke too soon. The voting app needs a default volume store, so I added this to the doc. The app now works for me.

Change is in https://github.com/stuclem/vic/commit/105fa7ba61934cc9c20c7d5c2ef71cc7d6b6d1cc.

**Comment by stuclem** [comment]
Also got a cert error when I ran the example with `--no-tlsverify`. Running with `--no-tls` works. Updated doc to remove TLS.

Change is in https://github.com/stuclem/vic/commit/378f9ff4a518c04aab13377a91f422a3fb7ba264.

**Comment by stuclem** [comment]
Want to make another pass over this, and probably expand.

**Comment by chengwang86** [comment]
@stuclem Do you want us to review this https://github.com/stuclem/vic/blob/378f9ff4a518c04aab13377a91f422a3fb7ba264/doc/user_doc/vic_app_dev/build_app_with_vic.md or a different file?

**Comment by stuclem** [comment]
@chengwang86 yes please!

**Comment by chengwang86** [comment]
@stuclem LGTM 👍

**Comment by stuclem** [comment]
Belated thanks @chengwang86. Closing this one as compose work will be tracked in other issues.
