### ISSUE TITLE
Cluster path should not be passed into port-layer-server or vicadmin

### ISSUE THREAD

**Issue by zjs** [vmware/vic#8315]
#### Summary
The path to the VCH's Cluster is currently explicitly passed into port-layer-server and vicadmin, instead of being dynamically determined relative to the Endpoint VM. This causes failures if a cluster is renamed, the VCH is reconfigured, and the Endpoint VM is subsequently restarted.

##### vSphere and vCenter Server version
6.5u1b

##### VIC version
1.3.x, 1.4.x

##### VCH configuration
N/A

#### Details
Re-configuring the VCH following the cluster rename is a viable short-term work-around. However, the change is lost when the Endpoint VM is restarted.

It is not immediately clear _why_ the restart causes the setting to be lost; subsequent restarts should be no different than the restart at the end of the reconfigure operation.

Regardless of the specific cause, we should stop passing information about the cluster as an argument to port-layer-sever and vicadmin. This is technical debt, dating back to before a VCH was able to identify itself in the vSphere inventory.

It may be of additional interest to check the VMX file at each step of the process to determine why the VCH begins working again after the reconfigure, but breaks after restart. Perhaps this is a symptom of an issue that will affect other operations.

##### Steps to reproduce
1. Create a cluster, `A`, with sufficient resources to deploy a VCH.
2. Deploy a VCH, `V`, into cluster `A`.
3. Rename cluster `A` to `B`.
4. Check the vicadmin and portlayer logs, note that a variety of warnings are displayed.
5. Reconfigure `V` to specify a compute-resource of `B`.
6.  Check the vicadmin and portlayer logs, note that new warnings are no longer displayed.
7. Restart `V`'s Endpoint VM
8. Note that the warnings re-appear.

##### Actual behavior
The VCH ceases to function.

##### Expected behavior
The VCH continues to work following the reconfigure operation and any subsequent restart.

#### See also
* bug2210484
* https://github.com/vmware/vic/blob/45a545aa83f76056e23813662e1f841f2399a3b2/lib/install/management/appliance.go#L613
* https://github.com/vmware/vic/blob/45a545aa83f76056e23813662e1f841f2399a3b2/lib/install/management/appliance.go#L687

#### Troubleshooting attempted

- [x] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [x] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [x] Searched for a relevant [VMware KB article][kb].
- [x] Reproduced in a separate environment.

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by wjun** [comment]
It looks we need to update session env->CS_PATH/POOL_PATH for portlayer service during configure. Maybe we need to update DC_PATH in case users modify datacenter name.

https://github.com/vmware/vic/blob/2cc54cbed96c280319fcd36b39fd773b6a4f3d46/cmd/vic-machine/configure/configure.go#L166

**Comment by renmaosheng** [comment]
the fix code is merged. closing the issue.
