### ISSUE TITLE
The docker inspect command output still shows container ID in the hostname field instead of the hostname as expected when deploying a container with hostname

### ISSUE THREAD

**Issue by yuyangbj** [vmware/vic#8318]
#### Summary

When deploying a container with hostname, the docker inspect does not show hostname in config.hostname field, it is still using container id.

##### VIC version
VIC 1.4.3

##### Steps to reproduce
docker --tls run -tid -h testhostnmame busybox sleep 300
docker --tls inspect <containerid>
##### Actual behavior
You will find the hostname is not set in hostname field.

        "Config": {
            "Hostname": "d8d716190796",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm"
            ],
            "Cmd": [
                "sleep",
                "300"
            ],
            "ArgsEscaped": true,
            "Image": "busybox",
            "Volumes": {},
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },

##### Expected behavior
testhostname is set correctly.
        "Config": {
            "Hostname": "testhostname",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "sleep",
                "600"
            ],
            "Image": "busybox",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },

Bug2213411

**Comment by hickeng** [comment]
Hostname support was added in #6074 - this should be a simple matter of changing where the inspect data is populated from to use https://github.com/vmware/vic/blob/master/lib/config/executor/container_vm.go#L212 (and domain if that should be present per docker semantics).

**Comment by yuyangbj** [comment]
Hi George,

Thanks for the reminding, I will take care it.
