### ISSUE TITLE
Document docker stop and docker rm

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#832]
Per https://github.com/vmware/vic/issues/688, https://github.com/vmware/vic/issues/363, and https://github.com/vmware/vic/issues/364 (merged).

**Comment by stuclem** [comment]
A minimal implementation of Docker rm is in PR https://github.com/vmware/vic/pull/939.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table] (https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md)

**Comment by npakrasi** [comment]
Added details of minimal implementation to docker stop and rm.
