### ISSUE TITLE
Document that VCH runs with a VC service account

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#833]
Per https://github.com/vmware/vic/issues/635.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/767.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/764 has been Iceboxed, but a simpler implementation is still in the plans, per https://github.com/vmware/vic/issues/635.

**Comment by stuclem** [comment]
Moved to backlog/onsite beta to match the parent dev Epic (https://github.com/vmware/vic/issues/635)

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/825 covered the current implementation as it is in TP3. Epic https://github.com/vmware/vic/issues/635 doesn't look like it's going to be in onsite beta. Leaving this one in onsite beta for now, pending decision on what happens to https://github.com/vmware/vic/issues/635.

**Comment by stuclem** [comment]
Comment from @gigawhitlocks via Slack: 

_You know I’m not really sure what the state of this is since we decided to use a vsphere extension for authentication. I know there are some more RBAC-related things that George wants to do, but I’m not 100% sure on what the timeline is on those

or how the design has changed, because initially we were going to create a user in vSphere to do VCH things and now that all happens through the extension instead — I know he still wants the admin to be able to create actual human SSO users that can do various things / have customizable permissions, but I’ll need to speak to him about what the specifics of that plan are_

Moving this to GA.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/635 has been iceboxed.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/635 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by hickeng** [comment]
@stuclem can this be closed given #3298 and the existing docs for #1689

**Comment by stuclem** [comment]
@hickeng yes it can.
