### ISSUE TITLE
Document docker stop

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#834]
See https://github.com/vmware/vic/issues/438 and https://github.com/vmware/vic/pull/772 (merged).

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md).

**Comment by stuclem** [comment]
Reopening as there are still some aspects of docker stop that will be added in time for onsite beta (see https://github.com/vmware/vic/issues/438).

**Comment by npakrasi** [comment]
Added details to Docker stop in the Supported Docker Commands table.
