### ISSUE TITLE
vic-machine command-line autocompletion not working on ubuntu

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic#8345]
#### Summary

On my ubuntu 16.04 VM, autocomplete feature is not working on vic-machine command line

#### Environment information
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
$ uname -a
Linux ubuntu 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### VIC version
VIC 1.4.3

$ ./vic-machine-linux -version
vic-machine-linux version v1.4.3-20031-fa9732d

#### Troubleshooting attempted

- [ ] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [ ] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [ ] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by zjs** [comment]
@arslanabbasi: Before I deploy an Ubuntu 16.04 VM to reproduce, could you give a full example of attempting to use autocomplete? That will help me rule out some common issues.

For example:
```
$ source autocomplete/bash/vic-machine-linux 
$ ./vic-machine-linux <TAB>
configure  debug      h          inspect    update     version    
create     delete     help       ls         upgrade
$ ./vic-machine-linux debug -<TAB>
--authorized-key    --name              -t
--compute-resource  -p                  --target
--debug             --password          --thumbprint
--enable-ssh        --pw                --timeout
--id                -r                  -u
--key               --rootpw            --user
-n                  --ssh               -v
```

This was on Ubuntu 18.04:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
$ uname -a
Linux shepherdz-devl 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ ./vic-machine-linux -version
vic-machine-linux version v1.4.3-20031-fa9732d
```

**Comment by arslanabbasi** [comment]
Hi @zjs ,

I tried again to get the output and it is working now. I am not sure what happened in the middle but I tried multiple times just to be sure before opening the bug.

Thanks for the help. You can close the ticket. I will let you know if I hit this issue again.

**Comment by zjs** [comment]
Thanks for re-trying. Tangentially related: I opened #8379 to make this a bit easier to use.
