### ISSUE TITLE
[Scenario][Test Scripts]5-13-Invalid-ESXi-Install: Environment variable '%{VCH-NAME}' not found.

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/vic#8360]
5-13-Invalid-ESXi-Install is consistently failed, due to Environment variable '%{VCH-NAME}' not found when suite is cleaning up nimbus env.

Robot output:
19:13:02.602 | FAIL | Resolving argument default values failed: Environment variable '%{VCH-NAME}' not found.

Logs:
https://vic-jenkins.eng.vmware.com/job/vic-master-scenario/52/robot/report/log.html#s1-s4-s5

**Comment by renmaosheng** [comment]
it seems the robot has truncated the vic-machine return value. 
> stevenr@stevenr-a01  ~/go/src/github.com/vmware/vic   fix-8168  ./bin/vic-machine-darwin create --target xxxx --user '***' --password '****' --no-tls --name invalid-VCH-sren  --force
INFO[0000] ### Installing VCH ####
WARN[0000] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
WARN[0000] Configuring without TLS - all communications will be insecure
WARN[0000] iso file "/Users/stevenr/go/src/github.com/vmware/vic/bin/appliance.iso" version "v1.5.0-dev-0-324e810" inconsistent with installer version "v1.5.0-dev-1-324e810"
WARN[0000] iso file "/Users/stevenr/go/src/github.com/vmware/vic/bin/bootstrap.iso" version "v1.5.0-dev-0-324e810" inconsistent with installer version "v1.5.0-dev-1-324e810"
INFO[0004] Validating supplied configuration
INFO[0008] Suggesting valid values for --image-store based on "*"
INFO[0009] Suggested values for --image-store:
INFO[0009]   "datastore1"
INFO[0009]   "scm-trees.eng.vmware.com_0"
INFO[0009]   "build-storage61.eng.vmware.com_0"
INFO[0009]   "build-ob.eng.vmware.com_0"
INFO[0009]   "build-toolchain.eng.vmware.com_0"
INFO[0009]   "build-apps.eng.vmware.com_0"
INFO[0009]   "bugs.eng.vmware.com_0"
ERRO[0010] vCenter settings check SKIPPED
ERRO[0010]   datastore not set
ERRO[0010] Set vCenter settings SKIPPED
ERRO[0010]   datastore not set
ERRO[0010] Firewall check SKIPPED
ERRO[0010]   datastore not set
ERRO[0010] vCenter settings check SKIPPED
ERRO[0010]   datastore not set
ERRO[0010] License check SKIPPED
ERRO[0010]   datastore not set
ERRO[0010] DRS check SKIPPED
ERRO[0010]   datastore not set
ERRO[0010] Compatibility check SKIPPED
ERRO[0010]   datastore not set
ERRO[0010] --------------------
ERRO[0010] Target is managed by vCenter server "10.162.61.61", please change --target to vCenter server address or select a standalone ESXi
ERRO[0010] datastore empty
ERRO[0010] vCenter settings check SKIPPED
ERRO[0010] Set vCenter settings SKIPPED
ERRO[0010] Firewall check SKIPPED
ERRO[0010] vCenter settings check SKIPPED
ERRO[0010] License check SKIPPED
ERRO[0010] DRS check SKIPPED
ERRO[0010] Compatibility check SKIPPED
ERRO[0010] Create cannot continue: configuration validation failed
ERRO[0010] --------------------
ERRO[0010] vic-machine-darwin create failed: validation of configuration failed
