### ISSUE TITLE
Document container logs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#837]
Per https://github.com/vmware/vic/issues/433.

**Comment by stuclem** [comment]
Need to establish whether Epic https://github.com/vmware/vic/issues/433 is for Beta or GA (see comment from corrieb in issue 433).

**Comment by npakrasi** [comment]
Added container logs command in the [Supported Docker Commands](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md) table.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/433  is actually for GA.

**Comment by stuclem** [comment]
Looks like this is in https://github.com/vmware/vic/issues/366.

**Comment by stuclem** [comment]
According to @sflxn in https://github.com/vmware/vic/issues/366, the docker kill --timestamps (also -t) and --since options will not work initially.

**Comment by stuclem** [comment]
Partial implementation of https://github.com/vmware/vic/issues/366 is in PR https://github.com/vmware/vic/pull/1765.

**Comment by stuclem** [comment]
Looks like  the `docker logs --timestamps` (also -t) and `--since` options will not work for GA, so this needs to be called out in the doc.

**Comment by stuclem** [comment]
Docker logs is merged in PR https://github.com/vmware/vic/pull/1931.

**Comment by stuclem** [comment]
Updated the table of supported Docker commands to include the caveat about the `--timestamps` and `--since` options:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md
