### ISSUE TITLE
Support "completion" subcommand in vic-machine

### ISSUE THREAD

**Issue by zjs** [vmware/vic#8379]
#### Summary
Many cloud native tools provide a consistent pattern for enabling shell completion: `source <(mycommand completion bash)`. Add support for this pattern to `vic-machine`.

#### User statement(s)
* As a user of `vic-machine`, I want to be able to enable shell completion in a familiar way.
   * For existing users, we should continue to provide the separate script files.
   * For users of other cloud native commands, we should support `vic-machine completion bash` and `vic-machine completion zsh`.
* As a user of `vic-machine`, I want to receive a useful message if I make a mistake attempting to enable shell completion (e.g., by specifying an unsupported shell).
* As a user of `vic-machine`, I want to be able to learn how to enable shell completion from the command `vic-machine` itself (i.e., without referring to the documentation).
* As a user of `vic-machine`, I want to be able to learn how to enable shell completion from the documentation.

**Comment by renmaosheng** [comment]
@zjs any left work required? thanks.

**Comment by renmaosheng** [comment]
We are not going to fix this in 1.5.4 and future release, will keep current behavior with 1.5.3 version.

**Comment by stuclem** [comment]
If we're keeping the same behaviour as in 1.5.3, there is no doc impact.
