### ISSUE TITLE
Document docker volumes operations

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#838]
Per https://github.com/vmware/vic/issues/429.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/806.

**Comment by stuclem** [comment]
Some of this is implemented in pull request https://github.com/vmware/vic/pull/989 (not merged yet).

**Comment by npakrasi** [comment]
Added Docker volume create, ls, rm to [Supported Docker Commands table](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md)
