### ISSUE TITLE
vic 1.5 ova can not deploy successfully, will have invalid value 'true' error. 

### ISSUE THREAD

**Issue by zhoumeina** [vmware/vic#8387]
When use vic 1.5 ova to deploy. 

ova url: https://storage.googleapis.com/vic-product-ova-builds/vic-dev-v1.5.0-dev1-6430-125712ba.ova

after finish the deploy ovf template. There is a error in the recent task

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/48687762-be7e4680-ebfd-11e8-9a7b-9a7a155e8f31.png)

**Comment by DanielXiao** [comment]
Verified it in both html5 and flex client. Closing
