### ISSUE TITLE
VCH log rotation

### ISSUE THREAD

**Issue by wjun** [vmware/vic#8399]
#### Summary
VCH root disk is full after turnovers of a bunch of containers during testing ELK and Selenium with rapid container deployment.

#### Environment information
VIC 1.4.3
 vCenter 6.7
 ESXi 6.5 u2
Docker-compose
Bamboo

#### Details
$ cat container-logs.zip-link/df
 Filesystem     1K-blocks    Used Available Use% Mounted on
 rootfs           5046104 5046104         0 100% /
 devtmpfs         5046116       0   5046116   0% /dev
 tmpfs            5111420       0   5111420   0% /dev/shm
 tmpfs            5111420     132   5111288   1% /run
 tmpfs            5111420       0   5111420   0% /sys/fs/cgroup
 tmpfs            5111420       0   5111420   0% /tmp
 ========End Output========

##### Expected behavior
Certainly have some sort of upper bound on the space consumed by log files.

Bugzilla#2238550

**Comment by renmaosheng** [comment]
Jun,
       Do we have any workaround for this issue? thanks.
