### ISSUE TITLE
2 container-vms have conflict IPs in one VCH in VIC1.5.0

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/vic#8405]
Steps:
1.  Create VCH using VIC1.5.0
2. Create one container named c-vm51 using bridge network and its ip is 172.16.0.2
3. Create 2nd container named c-vm52 using bridge network and its ip is 172.16.0.3
4. Power Off the c-vm51 through vSphere Client
5. Create 3rd container named c-vm53 using bridge network and its ip is **172.16.0.2**. 
6. Power on c-vm51 through vSphere Client and its ip is **172.16.0.2** as well.
In one VCH, we could see that 2 container vms have the same IP address with **172.16.0.2**
Details logs is 
[1.5.0_VCH_container-logs.zip](https://github.com/vmware/vic/files/2666277/1.5.0_VCH_container-logs.zip)

I also did the same steps as above using VIC1.4.3, the behavior is that 3rd container's ip is 172.16.0.4. And not IP conflicts. Details info as below. 
Steps
1. Create VCH using VIC1.4.3
2. Create one container named c-vm41 using bridge network and its ip is 172.16.0.2
3. Create 2nd container named c-vm42 using bridge network and its ip is 172.16.0.3
4. Power Off the c-vm41 through vSphere Client
5. Create 3rd container named c-vm53 using bridge network and its ip is 172.16.0.4
6. Power On the c-vm41 through vSphere Client and its ip is 172.16.0.2

**Comment by yuyangbj** [comment]
I reproduced the problem on both VIC 1.4.3 and VIC 1.5.

When container VM is powered off from vSphere client, the VIC will receive the vSphere poweredoff event, and address event in network.go below. So IP will be released.

https://github.com/vmware/vic/blob/master/lib/portlayer/network/network.go#L128

But interesting, the code does not address vSphere poweredon event for networking part. So when the container VM is powered on from vSphere client, as VIC does not reserve any IP address, so it will the previous IP address saved in VM.

Dec 12 2018 08:54:48.569Z DEBUG Found 2 subscribers to 1263: vsphere.VMEvent - DRS powered On test-578c6f793cc0 on 10.193.45.13 in dc1
Dec 12 2018 08:54:48.573Z DEBUG Event manager calling back to exec for Event(1263): vsphere.VMEvent
Dec 12 2018 08:54:48.573Z DEBUG Event manager calling back to logging for Event(1263): vsphere.VMEvent
Dec 12 2018 08:54:48.573Z DEBUG [BEGIN]  [vic/lib/portlayer/logging.eventCallback:58]
Dec 12 2018 08:54:48.573Z DEBUG [ END ]  [vic/lib/portlayer/logging.eventCallback:58] [6.164µs] 
Dec 12 2018 08:54:48.573Z DEBUG op=272.135: [NewOperation] op=272.135 [vic/lib/portlayer/exec.(*Container).OnEvent:718]
Dec 12 2018 08:54:48.573Z DEBUG [BEGIN] op=272.135 [vic/lib/portlayer/exec.(*Container).OnEvent:719] eventID(1263) received for event: PoweredOn
Dec 12 2018 08:54:48.573Z DEBUG op=272.135: Updating container 578c6f793cc01e31dd85b6275fe1c82ee3d1cd343ccf845ca0f42c9489a1fc57 state: Stopped->Running
Dec 12 2018 08:54:48.573Z DEBUG op=272.135: Container (578c6f793cc01e31dd85b6275fe1c82ee3d1cd343ccf845ca0f42c9489a1fc57) publishing event (state=Running, event=Started) from event PoweredOn
Dec 12 2018 08:54:48.573Z DEBUG [ END ] op=272.135 [vic/lib/portlayer/exec.(*Container).OnEvent:719] [23.312µs] eventID(1263) received for event: PoweredOn
Dec 12 2018 08:54:48.573Z DEBUG Found 2 subscribers to 272.135: events.ContainerEvent - Container 578c6f793cc01e31dd85b6275fe1c82ee3d1cd343ccf845ca0f42c9489a1fc57 Started
Dec 12 2018 08:54:48.573Z DEBUG Event manager calling back to netCtx(0xc420aeaba0) for Event(272.135): events.ContainerEvent
Dec 12 2018 08:54:48.573Z DEBUG Event manager calling back to PLE-530fa318dd2f7b3bb136d81a90ee8177b3275abdb46f975e4edf6859e90ffd2c for Event(272.135): events.ContainerEvent

**Comment by renmaosheng** [comment]
this is not a regression so removing the label, the issue exists in previous version as well, mark it as p2 as we are still discussing the best solution to fix the problem.
