### ISSUE TITLE
Document vic-machine inspect

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#841]
Per https://github.com/vmware/vic/issues/811.

**Comment by stuclem** [comment]
This is in progress on the dev side in https://github.com/vmware/vic/issues/1252.

**Comment by stuclem** [comment]
A first implementation is in PR https://github.com/vmware/vic/pull/1275.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/issues/1252 is now merged.

**Comment by stuclem** [comment]
Added a topic on vic-machine inspect in admin.

**Comment by stuclem** [comment]
Need to write up the options for vic-machine inspect.

**Comment by stuclem** [comment]
Added new topic that describes the vic-machine inspect options:

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/inspect_vch.md
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/inspect_vch_options.md

@emlin are these two topics OK? Thanks!

**Comment by emlin** [comment]
This looks good.
Just one minor question. We know that the options used in vic-machine delete and inspect, is same with vic-machine create. Suppose that will make customer's life easier.
Do we need to explicitly mention that in the document?

**Comment by stuclem** [comment]
You mean just doc them once for create and then cross-reference from delete and inspect? I prefer to list all of the options for each command, even if that leads to repetition.

**Comment by emlin** [comment]
no, I mean we might mention that the parameter of compute-resource and name is exactly same with the value used in vic-machine create

**Comment by stuclem** [comment]
Oh, I see. Yes, worth mentioning!

**Comment by stuclem** [comment]
Added the following to the topics on delete and inspect:

- Specify `--name` with exactly the same value that you used when you ran `vic-machine create`.
- Specify `--compute-resource` with exactly the same value that you used when you ran `vic-machine create`.

**Comment by emlin** [comment]
this looks good

**Comment by stuclem** [comment]
Thanks!
