### ISSUE TITLE
docker run --label supported?

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#8412]
As per documentation [here](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_app_dev/container_operations.html), it seems docker run --label is not supported. However, in practice it does seem to work. Please see below.

`docker run -itd --net=blah01 --label="traefik.enable=true" --label="traefik.frontend.rule=Host:blah.blue.com" --label="traefik.backend=nginx1" --label="traefik.port:80" --label="traefik.frontend.entryPoints=http" registry/project/nginx:1.13.5-alpine`

docker inspect <container>

```
  "Labels": {
                "com.docker.compose.config-hash": "b75471c855439f022fed77d3c950b7d674939853cd7496ebacf94765e1413f94",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "docker",
                "com.docker.compose.service": "web",
                "com.docker.compose.version": "1.22.0",
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
                "nginxcvm": "",
                "traefik.backend": "nginx1",
                "traefik.docker.network:blah01": "",
                "traefik.enable": "true",
                "traefik.enable:true": "",
                "traefik.frontend.entryPoints": "http",
                "traefik.frontend.passHostHeader": "true",
                "traefik.frontend.passHostHeader:true": "",
                "traefik.frontend.rule": "Host:blah.blue.com",
		"traefik.network:blah01": "",
                "traefik.port:80": "",
                "traefik.port:8001": ""
            }

```

May I know if this docker run --labels are officially supported, please? Thanks.

**Comment by aviratna** [comment]
Official Support for Docker label will be really helpful as we can use this field for many use cases like Chargeback, categorization, mapping, load balancing as mentioned by @malikkal  above.

**Comment by wjun** [comment]
Yes, --label or --label-file is officially supported in 'docker create' and 'docker run' commands since vic 1.0. Users can use 'docker inspect' to check labels or 'docker ps --filter="label=..." to filter out containers with certain labels. @stuclem   Could you please to update vic documents to include these 2 options into 'docker create' and 'docker run' commands? Thanks. Once the document completes, we can close it.

**Comment by meeximum** [comment]
it would be great, when the label option would be integrated in the GUI?

**Comment by stuclem** [comment]
Thanks @wjun and @meeximum. Moving this to the vic-product repo, now that this is a doc issue.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #2321](https://github.com/vmware/vic-product/issues/2321) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kkuphal** [comment]
Is it possible to set docker labels from the VIC GUI when provisioning a container from the repository or as a template?  The custom properties do not seem to correspond to docker labels.
