### ISSUE TITLE
Document vic-machine ls

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#842]
Per https://github.com/vmware/vic/issues/810.

**Comment by stuclem** [comment]
This is being implemented in https://github.com/vmware/vic/issues/1550

**Comment by stuclem** [comment]
This is still in progress on the dev side, so moving back to Backlog.

**Comment by stuclem** [comment]
vic-machine ls is merged in PR https://github.com/vmware/vic/pull/1858.

**Comment by stuclem** [comment]
Added new topics on `vic-machine ls`:
- [List Virtual Container Hosts and Obtain Their IDs](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/list_vch.md)
- [Virtual Container Host List Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/list_vch_options.md)

Added the new `id `option in the topics on the `vic-machine inspect` and `delete` options:

- [vic-machine inspect --id](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/inspect_vch_options.md#id)
- [vic-machine delete --id](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/delete_vch_options.md#id)

Mentioned in the relevant sections in the topics on the `vic-machine inspect` and `delete` options that if you specify `id `you don't need to specify `compute-resource` or `name`:

- [vic-machine inspect --compute-resource](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/inspect_vch_options.md#compute-resource)
- [vic-machine inspect --name](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/inspect_vch_options.md#name)
- [vic-machine delete --compute-resource](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/delete_vch_options.md#compute-resource)
- [vic-machine delete --name](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/delete_vch_options.md#name)

@emlin, does this cover it?
Thanks!

**Comment by emlin** [comment]
This looks good. 👍

**Comment by stuclem** [comment]
Thanks @emlin!
