### ISSUE TITLE
Document VCH upgrade.

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#843]
Per https://github.com/vmware/vic/issues/812.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/812 is in progress

**Comment by stuclem** [comment]
Draft ideas for upgrade are in PR https://github.com/vmware/vic/pull/1955

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/2031 adds versioning to ISO files, which is a step towards implementing VCH upgrade.

**Comment by stuclem** [comment]
Upgrade workflow is in https://github.com/vmware/vic/issues/2171, which is merged in PR https://github.com/vmware/vic/pull/2264.

**Comment by stuclem** [comment]
According to @emlin this functionality is still hidden, so moving back to backlog.

**Comment by stuclem** [comment]
`vic-machine upgrade` command will be exposed when PR https://github.com/vmware/vic/pull/2577 is merged.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/2577 is now merged.

**Comment by stuclem** [comment]
Comment from @dougm in https://github.com/vmware/vic/issues/2570#issuecomment-255000692:

-----

When using thumbprint based verification, updating the VC/ESX certificate will prevent VIC from managing existing container VMs, creating new ones, etc. However, existing container VMs will continue to run. User will need to use vic-machine to update.

-----

**Comment by stuclem** [comment]
Added topics on upgrade in the Admin doc:
- [Upgrade a Virtual Container Host](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/upgrade_vch.md)
- [Virtual Container Host Upgrade Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/upgrade_vch_options.md)

@emlin, are these two topics OK? Thanks!

I have opened https://github.com/vmware/vic/issues/2984 to address the question about what happens when VC/ESX certs change.

**Comment by emlin** [comment]
Upgrade:
* if --thumbprint not specified, vic-machine will print out the server's thumbprint to allow user confirm with it. If that's the correct one, which can be used to specify the thumbprint, instead of force the upgrade.
* vic-machine upgrade does not actually support upgrade from from 0.6.0, we might need to specify that

**Comment by emlin** [comment]
For the iso options, I think we don't support PATH fetch. We only look for current dir, and the dir where vic-machine is located. Sorry for the confusion in slack.

**Comment by stuclem** [comment]
Regarding "For the iso options, I think we don't support PATH fetch. We only look for current dir, and the dir where vic-machine is located", I tested this by running vic-machine from a different folder to the `/vic` folder, that includes the ISOs, and it worked. I assumed that this was because I have set the path to `/vic` in my PATH. Will try again after moving the ISOs elsewhere. Thanks!

**Comment by stuclem** [comment]
Regarding "_if --thumbprint not specified, vic-machine will print out the server's thumbprint to allow user confirm with it. If that's the correct one, which can be used to specify the thumbprint, instead of force the upgrade_", I had included this in the description of the options, but not in the topic on running `vic-machine upgrade`. I have now done so for all of the topics on running [`vic-machine upgrade`](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/upgrade_vch.md), [`delete`](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/remove_vch.md), [`ls`](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/list_vch.md), and [`inspect`](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/inspect_vch.md). I also broke that chunk of text into bullets, as it was too big.

Regarding "_vic-machine upgrade does not actually support upgrade from from 0.6.0, we might need to specify that_", I added a disclaimer to the top of both of the. [Upgrade VCH](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/upgrade_vch.md) and [VCH Upgrade Options](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/upgrade_vch_options.md).

Regarding the PATH question, I tested this by moving the ISOs and the upgrade failed. I have updated the descriptions of `--appliance-iso` and `--bootstrap-iso` accordingly, for both [`create`](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--appliance-iso) and [`upgrade`](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/upgrade_vch_options.md#--appliance-iso).

Changes are in https://github.com/vmware/vic/pull/2939/commits/48b3454f1db2d95accb56e81c7a203bccebfb28f. @emlin  is this OK now? Thanks!

**Comment by stuclem** [comment]
Reviewed by @emlin in https://github.com/vmware/vic/pull/2939.
