### ISSUE TITLE
After upgrade successfully, VCH display version number still is original version number.

### ISSUE THREAD

**Issue by ading007** [vmware/vic#8432]
After upgrade successfully, looking over VCH detail info via execute (govc vm.info \*) cmdline, display version number still is original version number, Instead of version number after upgrade. 

Failure testcase:
 tests/manual-test-cases/Group5-Functional-Tests/5-25-OPS-User-Grant.robot.

robot logs:
https://vic-jenkins.eng.vmware.com/job/vic-master-scenario/97/robot/report/log.html#s1-s4-s16

Related PR:
https://github.com/vmware/vic/pull/8427

**Comment by YanzhaoLi** [comment]
This issue didn't occur recently.  And we have CI test, in which this issue never occurs.
