### ISSUE TITLE
Hit failure in deleting VCH when 2 VCH are having the same selenium related containers.

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/vic#8435]
#### Summary

Hit issue when deleting 2 VCHs, which are having the some containers.

##### vSphere and vCenter Server version

vSphere 6.7

##### VIC version

1.5.0 version vic_20646

##### Steps to reproduce
1. Deploy a VC with 2 clusters and enable NSX-T env.
2. Create 3 different logical switches in NSXT named as vic-selenium-bridge-ls-1, vic-selenium-bridge-ls-2 and vic-container-ls
3. Create a VCH using vic-selenium-bridge-ls-1 as bridge network and vic-container-ls as container network
4. Create another VCH vic-selenium-bridge-ls-2 as bridge network and vic-container-ls as container network
5. In each VCH, we create a network
a). docker -H **:2376 --tls network create grid
b). Create selenium-hub
docker -H ***:2376 --tls run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub:3.9.1 2>&1
c). Create 3 selenium/node-chrome
docker -H ***:2376 --tls run -d --cpus 1 --memory 1G --net grid -e HOME=/home/seluser -e HUB_HOST=selenium-hub --name chrome-1 selenium/node-chrome:3.9.1
d). Create 3 selenium/node-firefox:3.9.1
docker -H ***:2376 --tls run -d --cpus 1 --memory 1G --net grid -e HOME=/home/seluser -e HUB_HOST=selenium-hub --name firefox-1 selenium/node-firefox:3.9.1 2>&1
6. Delete each VCH, and hit failure as below
>time="2018-12-27T07:31:13Z" level=info msg="Removing image stores" 
time="2018-12-27T08:03:17Z" level=info msg="Removing volume stores" 
time="2018-12-27T08:03:17Z" level=info msg="Deleting volume store \"default\" on Datastore \"vdnetSharedStorage\" at path \"VCH-0-2331-VOL\"" 
time="2018-12-27T08:03:17Z" level=info msg="Removing appliance VM network devices" 
time="2018-12-27T08:03:32Z" level=info msg="Collecting 95ea08ce-c497-4232-a21c-21fc64acc8a4 vpxd.log" 
time="2018-12-27T08:03:32Z" level=error msg="File /vmfs/volumes/ebad9d66-b8d8ee17/VCH-0-2331/VIC/422c6361-a3b6-016b-07b1-65afa326f343/images/e867a0cf417c5b0a91a6789dd0b2920763b5a37394c2b2d6412ce996ffbf8d25/e867a0cf417c5b0a91a6789dd0b2920763b5a37394c2b2d6412ce996ffbf8d25.vmdk was not found" 
time="2018-12-27T08:03:32Z" level=error msg=-------------------- 
time="2018-12-27T08:03:32Z" level=error msg="vic-machine-linux delete failed: delete failed\n" 

##### Expected behavior
Succeed to delete VCH

##### Logs
Robot log is https://vic-jenkins.eng.vmware.com/view/LuWang-Test/job/luwang_vic/49/robot/report/log.html.

**Comment by renmaosheng** [comment]
may be related to Vdnet environment. let's take a deep look tomorrow. thanks.

**Comment by renmaosheng** [comment]
could we close this one? @luwang-vmware

**Comment by luwang-vmware** [comment]
I will use Jun's local patch to validate it.

**Comment by luwang-vmware** [comment]
The issue is fixed and close it now.
