### ISSUE TITLE
After set storage quota for VCH, upgrade --rollback not work as expected

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/vic#8437]
#### Summary
After set storage quota for VCH, upgrade --revert operations can not revert VCH to the previous upgrade version.

##### Steps to reproduce
1. create VCH using vic 1.4.3
2. upgrade VCH to 1.5.0
3. use vic-machine-linux configure cmd to set storage quota
5. use vic-machine-linux upgrade --rollback cmd to rollback

##### Actual behavior use upgrade --rollback
in step5, upgrade --rollback does not revert VCH to 1.4.3 version.
VCH reverts back to storage quota unset status.

##### Expected behavior
in step5, upgrade --rollback should revert VCH to 1.4.3 version

**Comment by renmaosheng** [comment]
@luwang-vmware please close this if it is resolved.

**Comment by wjun** [comment]
After fixing --rollback for configure command, we can use "configure --rollback" before "upgrade --rollback" if users run configure commands after upgrade.
@stuclem please add --rollback parameter into vic-machine-{os} configure --rollback. Thanks.

**Comment by stuclem** [comment]
Thanks @wjun. I have created a doc issue to address this in the 1.5.3 docs.
