### ISSUE TITLE
Generated server certificate is not recognized as valid by browsers

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#8447]
Running the following command in OneCloud environment produces a VCH for which browsers cannot validate the server certificate when accessing vicadmin. The docker client can validate the cert and the VCH otherwise functions as expected:

```
./vic-machine-linux create \
--target vcsa-01a.corp.local \
--user administrator@vsphere.local \
--compute-resource RegionA01-COMP01 \
--image-store RegionA01-ISCSI01-COMP01 \
--volume-store RegionA01-ISCSI01-COMP01:default \
--public-network VM-RegionA01-vDS-COMP \
--public-network-ip 192.168.100.21/24 \
--public-network-gateway 192.168.100.1 \
--dns-server 192.168.110.10 \
--container-network VM-RegionA01-vDS-COMP:routable \
--container-network-firewall VM-RegionA01-vDS-COMP:open \
--bridge-network vxw-dvs-40-virtualwire-14-sid-5000-vch-01a-bridge \
--name vch-01a \
--tls-cname=vch-01a.corp.local \
--registry-ca=/etc/docker/certs.d/registry.corp.local/ca.crt \
--syslog-address tcp://vrli-01a.corp.local \
--affinity-vm-group \
--thumbprint=F7:68:F0:93:F4:EC:B7:FE:C1:02:3F:F3:AB:62:1A:50:E8:9A:0E:85
```

Simply removing the `--tls-cname` option seems to work around the problem, which suggests there's a flaw in how the certificate is currently being generated. 

Even with the `--tls-cname` option removed, Admiral complains about the certificate when adding the VCH. I'm unsure if this is simply because it's not got a trusted CA, or whether it thinks the cert is actually invalid - the error displayed says invalid.

For the functioning certificate we seem to have a rather messy Subject field. Chrome reports the Subject field as:
```
CN = 192.168.100.21
O = 192.168.100.21
O = 
```
and Admiral displays the subject separated into Common Name and Issuer:
```
Common name: 192.168.100.21
Issuer name: O= + O=192.168.100.21
Serial: 270632887007482579973725198986549431131
SHA Fingerprint: 61:0D:BA:26:88:EE:88:4A:60:EC:14:06:49:59:B1:B7:17:A7:8F:48
Valid since: Jan 9, 2019, 2:10:22 PM
Valid to: Jan 10, 2020, 2:10:22 PM
```

I believe the invalid certificate with `--tls-cname` is a regression, but have not confirmed at this time.

**Comment by wjun** [comment]
George, in your environment, the VCH server cert is signed by a CA cert. After I added the ca cert into the credential, and select it from 'Credentials" during "New Container Host" web page of Admiral, the browser can add it directly without certificate untrust message.

**Comment by hickeng** [comment]
@wjun The issue described with Admiral is only noted as an aside, and applies to the certs generated _without_ `--tls-cname` specified.

The primary issue is that the browser rejected the certificate as corrupted when generated with both `--public-network-ip` and `--tls-cname` specified. This was 100% recreatable in the pen test environment.

**Comment by wjun** [comment]
@hickeng do you have a screenshot when you mentioned "the browser rejected the certificate as corrupted"? because when we logged into the pen test env last time, and open the cert from browser when the cert box appears from Admiral, the CN name is vch-01a.corp.local instead of an ip address, and we can continue to add a VCH successfully.

**Comment by renmaosheng** [comment]
@hickeng Jun, me and Lu has looked into the pen test environment, we can successfully add the VCH, so I am going to close this.
