### ISSUE TITLE
VCH deployment log is truncated

### ISSUE THREAD

**Issue by zjs** [vmware/vic#8456]
@lgayatri commented on [Fri Oct 26 2018](https://github.com/vmware/vic-product/issues/2138)

Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version:                                   6.5U2
- Embedded or external PSC:                            Embedded PSC
- Filename of the OVA you deployed:               vic-dev-v1.4.4-dev-6326-5874a1d2.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): ovftool
- Does the VIC appliance recieve configuration by DHCP? Static IP
- What stage of the Appliance Lifecycle is the VIC appliance in? This from H5UI/ VIC shortcut

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?
VCH was created from H5 UI and the deployment log was showing truncated. I see the below content from H5 UI.

```
Oct 26 2018 06:14:23.887Z INFO Starting API-based VCH Creation. Version: "v1.4.3-20031-fa9732d"
...
Oct 26 2018 06:14:25.813Z DEBUG generating new config secret key
Oct 26 2018 06:14:26.017Z INFO Uploading ISO images
...
Oct 26 2018 06:14:36.054Z DEBUG vm compute resource: Cluster
Oct 26 2018 06:14:36.055Z DEBUG VirtualMachine:vm-16509 resides in a multi-host cluster: true
Oct 26 2018 06:14:36.055Z DEBUG DRS enabled: true
```
Logs stops at "DRS enabled: true"

This may not be a regression from 1.4.3 but I remember well that the log was in full display.

**Comment by yuyangbj** [comment]
Closing it due to not active.
