### ISSUE TITLE
Unable to create loop devices

### ISSUE THREAD

**Issue by douggie** [vmware/vic#8463]
#### Summary
When using ubuntu 16.04. the creation of loop devices is limited to privileged users via the docker engine, however the VIC docker API does not allow to run in a privileged mode.

#### Environment information
VIC 1.3.1 running on vcentre 6

##### vSphere and vCenter Server version
VIC 1.3.1 running on vcentre 6

##### VIC version
VIC 1.3.1 running on vcentre 6

##### Steps to reproduce
1) create an image in the container:
dd if=/dev/zero of=~/file.img bs=1MiB count=10
2) access image via loopback
losetup --find --show ~/file.img /dev/loop0

##### Actual behavior
losetup --find --show ~/file.img /dev/loop0
:/# losetup --find --show ~/file.img /dev/loop0
losetup: /file.img: failed to set up loop device: No such device or address
##### Expected behavior
/dev/loop0 should be created and mapped to  ~/file.img 

#### Troubleshooting attempted

- [ ] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [ ] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [ ] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by wjun** [comment]
@douggie  You can run "modprobe loop" inside the VCH containers to enable the loop devices and start to use them. Please let me know if this solve your issue or not.

**Comment by wjun** [comment]
Close it for now as I have tested "modprobe loop" and works.
