### ISSUE TITLE
VCH deletion fails with context deadline exceeded error or vmdk file not found error

### ISSUE THREAD

**Issue by zjs** [vmware/vic#8464]
@jitinkumar2018 commented on [Thu Nov 29 2018](https://github.com/vmware/vic-product/issues/2197)

**Bug Report Basic Information**
**REQUIRED**:

vCenter Server version: 6.5 p03
Embedded or external PSC: No
Filename of the OVA you deployed: vic-v1.4.4-6375-0a6da3d4
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Application
Vic Appliance Logs: Unable to upload Log bundle as it exceeded 10MB

**Bug Report Detailed Information**
What operation was being performed when the failure was noticed?
VCH deletion using vic-machine-linux delete CLI 

**DETAILS:**
- 10 VCH's were created with persistent volume store and left empty ( Did not create docker volume using the persistent volume) 
- 40  VCH's were created without persistent volume stores. 
- While performing concurrent VCH delete on all 50 VCH's, the VCH's that have persistent volume stores take much longer to delete than the rest of the VCH's
- It successfully deletes all except one VCH and throws context deadline exceeded error.
- Noticed failure in VCH delete only when VCH's are created with persistent volume store

@lgayatri @renmaosheng 

---

@renmaosheng commented on [Thu Nov 29 2018](https://github.com/vmware/vic-product/issues/2197#issuecomment-442878382)

Jitin,
      do you have the environment or logs for us to take a look? 

---

@jitinkumar2018 commented on [Thu Nov 29 2018](https://github.com/vmware/vic-product/issues/2197#issuecomment-442879561)

I shall send the vic_appliance_logs via slack. The environment was cleaned. I shall recreate it again and provide you the VC and VIC ip 

---

@wjun commented on [Thu Nov 29 2018](https://github.com/vmware/vic-product/issues/2197#issuecomment-443078152)

@hickeng @zjs Is there any reason the VCH deletion with volumes will take longer time?

---

@jitinkumar2018 commented on [Thu Nov 29 2018](https://github.com/vmware/vic-product/issues/2197#issuecomment-443114177)

I have recreated the testbed. 10 VCH's ( U-VIC-0001 - U-VIC-00010) have persistent volumes and the rest don't. We use a script that performs concurrent VCH deletion (50 threads that each perform vic-machine-linux delete).
Will send the VC and VIC login credentials to @wjun.

---

@wjun commented on [Mon Jan 07 2019](https://github.com/vmware/vic-product/issues/2197#issuecomment-452189717)

According to the logs, multiple VCH deletion fails sometimes either by some image vmdk files cannot be found error or by operation timeout. No matter the VCH has persistent volume or not. 

---

@jitinkumar2018 commented on [Mon Jan 07 2019](https://github.com/vmware/vic-product/issues/2197#issuecomment-452194429)

Thanks @wjun

**Comment by wjun** [comment]
@jitinkumar2018 I have a couple of fixes in master branch recently, and hopefully, this issue is fixed too. You may verify it in vic 1.5.2 or latest master codes.

**Comment by jitinkumar2018** [comment]
Thanks @wjun, I shall verify in VIC 1.5.2  when the build is available

**Comment by jitinkumar2018** [comment]
This issue seems to be fixed in VIC 1.5.2 GA.

**Comment by wjun** [comment]
I will close it for now.
