### ISSUE TITLE
VCH deletion cause containers inside resource pools to be pushed outside the resource pools, and not deleted

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic#8465]
**Bug Report Basic Information**
**REQUIRED:**
vCenter Server version: 6.5 p03
Embedded or external PSC: No
Filename of the OVA you deployed: vic-dev-v1.5.0-dev1-6723-dc7489d3
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Application
Vic Appliance Logs: 
[vic_appliance_logs_2018-12-21-08-43-57.tar.gz](https://github.com/vmware/vic-product/files/2702119/vic_appliance_logs_2018-12-21-08-43-57.tar.gz)

**Bug Report Detailed Information**
- Created 50 VCHs and deployed 50 containers in each VCH
- Initiated VCH delete using vic-machine-linux CLI with -f option
- Partial deletion of VCH's and containers took place
- Few containers (powered off state) were pushed out of the resource pool and not deleted

**Comment by yuyangbj** [comment]
@jitinkumar2018 any results for your tests? Do you reproduce it? I think the PR below could resolve your problem. Please using the build after this PR to try it. Thanks.

https://github.com/vmware/vic/pull/8453

**Comment by jitinkumar2018** [comment]
@yuyangbj I was not able to reproduce the issue. The issue seems to be resolved. Thanks

**Comment by yuyangbj** [comment]
@jitinkumar2018 thanks for the update.
