### ISSUE TITLE
Document docker run -name

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#848]
Per https://github.com/vmware/vic/issues/787. Applies to both the App Dev and vSphere Admin docs.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/787 has moved to onsite beta.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/787 has moved to GA.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/787 is implemented in PR https://github.com/vmware/vic/pull/1761.

**Comment by stuclem** [comment]
Added a line about container names in [Find Container Information in the vSphere Web Client](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/container_portlet_ui.md) in the Admin doc.

**Comment by npakrasi** [comment]
Added info on using prettyname-ID in the supported docker commands table.
