### ISSUE TITLE
vic-machine should detect port-layer-server starting failed.

### ISSUE THREAD

**Issue by YanzhaoLi** [vmware/vic#8494]
#### Symptom

vic-machine-xxx create vch, then endpointVM bootstrap. And then vic-machine-xxx would check whether port-layer-server has been started. The port-layer-server always restarted for nfs failure, but the vic-machine-xxx get `started successfully`.

#### Test case(s)

tests/manual-test-cases/Group5-Functional-Tests/5-22-NFS-Volume.robot

- fake  NFS
- ReadOnly NFS

**Comment by renmaosheng** [comment]
we can still look into the port-layer log to find the error, and delete VCH to do a re-try. mark this as won't fix.
