### ISSUE TITLE
Failed to write to image store

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic#8498]
#### Summary
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:A general system error occurred: Failed to add all requred permissions (68 of 69 applied)}

#### Environment information
Please let me know if you need access to environment

##### vSphere and vCenter Server version
vCenter: 6.5

##### VIC version
VIC 1.5.0

#### Details
docker pull vic.tpm.com/project-1/selenium
Using default tag: latest
latest: Pulling from project-1/selenium
7b8b6451c85f: Already exists
ab4d1096d9ba: Already exists
e6797d1788ac: Already exists
e25c5c290bde: Already exists
a3ed95caeb02: Download complete
b086d62b1fb6: Already exists
611296e21559: Already exists
1a748cd5960e: Already exists
216710bbf9fc: Already exists
c923d5a6ced0: Already exists
b60896522181: Already exists
4749c4095440: Already exists
c0a4ed2f25e7: Already exists
db57231b2b41: Already exists
8f15d88f38a0: Already exists
4fd611fe8016: Already exists
8645d21fbafc: Already exists
0fad046dbaa9: Already exists
44d0a2bac371: Already exists
1361376055a5: Already exists
c221b03c5ed4: Already exists
6acdaee75a13: Already exists
e18288975e10: Already exists
661f16049ef6: Already exists
e20ca4bdb323: Already exists
5b204f98fbbd: Already exists
6ad2cf02f2f2: Already exists
bcc83ad962af: Already exists
284c684712eb: Already exists
b513100959b6: Already exists
961bea8948fb: Already exists
f548ced71281: Already exists
cb45542466e9: Already exists
1a0e649abf3f: Already exists
a8f9fdaa4830: Already exists
b45493c8bdcb: Already exists
8f25bbd132d1: Already exists
a37594c05c75: Already exists
9a9865bf775f: Extracting [==================================================>]   5.57MB/5.57MB
f9fe7af7aa51: Download complete
2d3de3936498: Download complete
e27486ee856e: Download complete
f648161ddfc8: Download complete
af215cf490b5: Download complete
8095797e1ac6: Download complete
57c3b6f22f5e: Download complete
b1a112fac6d0: Download complete
11def44301c5: Download complete
d2a17cf8d99a: Download complete
4b7d9b7ae3be: Download complete
33048a459eeb: Download complete
2378f2663b1d: Download complete
9c1010ba0c15: Download complete
628b185a148c: Download complete
fd7bd2e96a24: Download complete
d9d581146156: Download complete
Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:A general system error occurred: Failed to add all requred permissions (68 of 69 applied)}

vic.tpm.com => 10.40.206.187

##### Steps to reproduce
You can add the "vic.tpm.com => 10.40.206.187" mapping in your /etc/hosts file and run "docker pull vic.tpm.com/project-1/selenium"

#### Logs

[container-logs.zip](https://github.com/vmware/vic/files/2963367/container-logs.zip)

#### Troubleshooting attempted

- [ ] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [ ] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [ ] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by wjun** [comment]
Close it for now which looks not related to image download directly.
