### ISSUE TITLE
Update docker and docker-compose version in our testing image

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/vic#8511]
CI/scenario testing image is using docker client 1.13 and docker-compose 1.11.2 version, which is too old. We need to upgrade them into the latest stable version.

**Comment by renmaosheng** [comment]
@luwang-vmware could you please update the version we used for CI and resolve this issue? so that Stuart can document what we tested? thanks.

**Comment by renmaosheng** [comment]
@luwang-vmware @ading007 could you please paste the testing result after upgrading the docker version? Given the short time of 1.5.3,  based on our discussion, we will keep the previous versions. if there is some customer hit some issue while using the latest version, we will fix it in on-demand manner.

**Comment by ading007** [comment]
Here is the docker and docker compose test result: 
[docker-releated-upgrade-test-result.xlsx](https://github.com/vmware/vic/files/3251678/docker-releated-upgrade-test-result.xlsx)

**Comment by ading007** [comment]
drone task url:
https://ci-vic.vmware.com/vmware/vic/21067

**Comment by renmaosheng** [comment]
closing this, as per above comments from wending.

**Comment by stuclem** [comment]
Doc updates tracked in https://github.com/vmware/vic-product/issues/2204
