### ISSUE TITLE
[FR] Support for docker-compose file format 3.0

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic#8513]
#### Summary

There has an increasing ask from the customers to use docker-compose version 3.0 with VIC. We need to add support for docker-compose v3.0.

**Comment by wjun** [comment]
@arslanabbasi I knew the official documentation mentioned we only support docker-compose file format 2, is there any blocker when using format 3?

**Comment by renmaosheng** [comment]
Hi Arslan, we have tried several v3 format docker-compose, listed https://github.com/vmware/vic/tree/master/demos/compose, it can work. if customer hits some issue, we can take a look on demand. thanks.
