### ISSUE TITLE
guest tools unavailable while performing vic configure

### ISSUE THREAD

**Issue by mohammadrezalk** [vmware/vic#8524]
Hi,
I'm using vic cli configure command to regenerate client certificate, During reconfiguration log reports "Guest tools unavailable, resorting to power off - sessions will be left open" while the VMtools (guest-managed) is in running status and it forces VM to power off instead of guest shutdown. has anybody faced with this issue?
thanks in advance

**Comment by wjun** [comment]
During configuration, VCH vm will restart during which Guest tools will be unavailable for a short time, and if there is any operation relying on Guest tools, it will show some warnings like that.
