### ISSUE TITLE
Restart policy drop down contains wrong value for on-failure

### ISSUE THREAD

**Issue by Sevyls** [vmware/vic#8527]
#### Summary

When trying to configure the Restart Policy of a container, the dropdown select box contains wrong values for on-failure, so it can't be selected and a validation message appears.
Only the values  "no" and "always" are selectable, "on-failure" is not selectable as the selectbox contains the camelcase "onFailure" and this is not expected by the service call.

##### vSphere and vCenter Server version
vSphere Client 6.5.0.10000

##### VIC version
v1.5.0.1462 Build No 397

##### Steps to reproduce
Create a template for a container, i.e. through applications
Go to tab "policy"
select restart policy dropdown and choose "on failure"
save container template

##### Actual behavior
a validation message appears "Restart policy must be one of no, on-failure, always."
"on failure" is not savable
##### Expected behavior
No validation message should appear, On failure should be savable/selectable

#### Details
The selectbox does contain the value as camelcase "onFailure", expected is "on-failure"

**Comment by shadjiiski** [comment]
Issue moved to [vmware/admiral #295](https://github.com/vmware/admiral/issues/295) via [**ZenHub**](https://www.zenhub.com/)

**Comment by shadjiiski** [comment]
As per my previous comment, I have moved the issue to Admiral and will fix it. I don't have permissions to close this instance, so please somebody do that for me :)

**Comment by Sevyls** [comment]
thanks for moving it to the right project.
