### ISSUE TITLE
Does "Open Source" mean I don't need an Enterprise Plus license? FAQ somewhat confusing on that topic...

### ISSUE THREAD

**Issue by alexrjs** [vmware/vic#8539]
#### Question
Does "Open Source" mean I don't need an Enterprise Plus license? FAQ somewhat confusing on that topic... Or, as my experiments shows me, "Open Source" doesn't mean no License required!?

I tried the vic 1.5.2 product from my.vmware.com and from Open-source vSphere Integrated Containers Engine project: https://storage.googleapis.com/vic-engine-releases/vic_v1.5.2.tar.gz
Both version do a license check, which fails on my free esxi standalone vmware host.
`ERRO[0000] License check FAILED:  

ERRO[0000]   "Host license missing feature \"serialuri\""`
#### See also
https://www.vmware.com/products/vsphere/integrated-containers.html#faqs
Is vSphere Integrated Containers Open Source?
Yes, all the components of vSphere Integrated Containers including Harbor, Admiral and vSphere Integrated Containers Engine are open sourced and available on Github.

**Comment by renmaosheng** [comment]
Hi,  

vSphere Integrated Containers depends on certain features that are included in the following vSphere Editions:

vSphere Enterprise Plus
vSphere Remote Office Branch Office (ROBO) Advanced
All of the ESXi hosts in a cluster require an appropriate license. Deployment of VCHs fails if your environment includes one or more ESXi hosts that have inadequate licenses.

       please refer to below content for license requirement:
       https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vi_reqs.html

**Comment by alexrjs** [comment]
Thanks... Not what I want to hear, but well if it is so, it is so... Hence, vmware is out, k3os it is... ;-)
