### ISSUE TITLE
Docker API: docker port

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#854]
Implementation of the docker port command. This data should be pulled from the network port layer, not from the container metadata - while the two should match (ports - IPs are not held in the metadata) the port layer pulls from the source of truth.

This ties in with #692

**Comment by corrieb** [comment]
@hickeng I very much doubt this will make onsite

**Comment by sflxn** [comment]
It will.  It's free.  Once we fill in the container info data structure on the portlayer side, the personality server's container inspect will return the correct values.  Docker port gets all the port data from container inspect.  It simply calls docker inspect.

**Comment by sflxn** [comment]
I was mistaken.  It is not free.  This is now done.  When container inspect was first started, I thought we needed to get this information in the port layer.  After @hmahmood implemented port mapping, we had a discussion about how the mapping metadata was used, and I also looked at the docker code for inspect again.  We don't really need to get any of this data from the portlayer at all.

**Comment by mdubya66** [comment]
GA feature from SSOD. needs to be tested.

**Comment by mdubya66** [comment]
I see this is closed. So docker port feature is working? is there a test? @sflxn @hickeng

**Comment by hmahmood** [comment]
Seems to be working:

```
hmahmood@ubuntu:~/go/src/github.com/vmware/vic$ docker -H 172.16.127.243:2376 --tls port insane_swirles
80/tcp -> 0.0.0.0:5003
```
