### ISSUE TITLE
Are OVA Installer, aso links outdated on document page?

### ISSUE THREAD

**Issue by alexrjs** [vmware/vic#8540]
#### Question
Is it possible that some of the links on https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/download_vic.html are outdated?

I found these outdated links 

- https://console.cloud.google.com/storage/browser/vic-engine-builds,
- https://console.cloud.google.com/storage/browser/vic-product-ova-builds 

on the above page.

#### See also
https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/download_vic.html

**Comment by wjun** [comment]
@stuclem  Could you please double check here? Thanks.

**Comment by renmaosheng** [comment]
> I found these outdated links
> 
> * https://console.cloud.google.com/storage/browser/vic-engine-builds,
> * https://console.cloud.google.com/storage/browser/vic-product-ova-builds
> 

I can still access above links. Those links include the dev-builds.

**Comment by stuclem** [comment]
@renmaosheng @wjun yes, I think that these links are still valid for the latest dev builds. However, since there are literally thousands of builds in each repo, you have to do a LOT of scrolling to get to the most recent ones...

**Comment by stuclem** [comment]
I did notice that we don't include the UI builds, though. I will add them.

**Comment by stuclem** [comment]
Moving this one to the `vic-product` repo.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #2456](https://github.com/vmware/vic-product/issues/2456) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alexrjs** [comment]
Ok, got it... Thanks for clarifing...
