### ISSUE TITLE
docker restart IP Address NIL Issue

### ISSUE THREAD

**Issue by aviratna** [vmware/vic#8546]
**Background**
Container IP Address is shown as NIL after docker restart

**vSphere and vCenter Server version**
vSphere 6.5

**VIC version**
VIC 1.5 (probably all versions in the past too)

**##### Steps to reproduce**
1. Docker stop <container id>
2. Docker start <container id>
3. Docker restart <container id>
4. docker ps -a 
    Container ip will be shown as NIL

We also observed same issue intermittent if we restart the container frequently.

**##### Actual behavior**
IP Address is not shown 

![image](https://user-images.githubusercontent.com/22312952/57268809-d8321e00-70b7-11e9-9e26-93883df017b6.png)

**##### Expected behavior**
IP Address should not not be NIL with docker restart or frequent start stop.

@malikkal

**Comment by yuyangbj** [comment]
We have fixed this issue in VIC  1.5.2? Could you please try it?

**Comment by aviratna** [comment]
@yuyangbj  Thanks for the response.
We tested with VIC 1.5.2, looks like its fixed. We will run some more test cases.

**Comment by wjun** [comment]
Close it for now.
