### ISSUE TITLE
Docker API: docker run

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#855]
The `docker run` command is a composite of the following:
* create
* start
* inspect
* attach
* rm
* resize
* wait
* kill

The implementation of those commands have their own issues (the api side of which are in #371), so this is for the testing of that composite behaviour, including all of the negative cases.

This should encompass tests of client logic such as:
create causes pull for unavailable image

**Comment by corrieb** [comment]
Ben/George review: This is kind of an epic. It should encompass new integration tests and shouldn't be closed until we're sure that run works.

**Comment by corrieb** [comment]
I am going to take on the responsibility for writing integration tests for this

**Comment by mdubya66** [comment]
GA feature from SSOD. Adding mhagen.

**Comment by mhagen-vmware** [comment]
Urg, really thought I commented on this already... not sure where is went.  We have the current docker run tests here, and I just partial implemented them: 
https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-6-Docker-Run.robot
