### ISSUE TITLE
Mount individual file from NFS share to container fails

### ISSUE THREAD

**Issue by omnidepp** [vmware/vic#8553]
#### Summary
When trying to mount an individual file that is stored on a nfs share, I get a Server Error from portlayer: Volume name XXX includes invalid characters.

##### vSphere and vCenter Server version
6.5

##### VIC version
1.5.2

#### Details
Docker command used to do this:
docker create -v nfs_share/config/configfile.yml:/usr/share/myprogram/configfile.yml:ro

##### Steps to reproduce
Mount any file in the nfs share instead of mounting the entire volume to a directory

##### Actual behavior
Fails in gui and cli. 

##### Expected behavior
Mounting individual files from nfs share to specific location in container.

#### Troubleshooting attempted

- [x ] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [x ] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [ x] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by renmaosheng** [comment]
Yanzhao, could you please take a look?

**Comment by YanzhaoLi** [comment]
@omnidepp vic doesn't support directly mount local file or folder into container. Vic only supports a mounting pre-created volume( whose backend can be vmdk datastore or nfs datastore). You can check the [vic doc](https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/volume_stores.html)
