### ISSUE TITLE
Docker API: docker version

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#856]
This should return the expected output - the primary variance being the data for the server version which should be "VIC <version>". Initially I was thinking we could use vSphere/<arch> in the OS/arch pair but it's quite possible that people will be parsing that given Windows docker support.

Sample version output from docker command line reference page:
```
Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f5bae0a
 Built:        Tue Jun 23 17:56:00 UTC 2015
 OS/Arch:      linux/amd64
```

current version output for server portion:
```
Server:
 Version:      0.0.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   -
 Built:        -
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mdubya66** [comment]
@anchal-agrawal give this one a go
