### ISSUE TITLE
Not being able to attach console to any deployed container. Server error from portlayer: no consumer: "text/html;charset=utf-8"

### ISSUE THREAD

**Issue by kitos9112** [vmware/vic#8563]
[container-logs(1).zip](https://github.com/vmware/vic/files/3282421/container-logs.1.zip)

#### Summary

Hi,

I'm trying to establish an interactive docker session from my dev docker VM against my shiny docker containers hosted in a VCH, however every single time I execute any command relatively simple and supported by VCH, it throws the same error.

The command I'm using is docker exec -it <container_id> <command> 
Interestingly, I'm able to fetch stdout/stderr from the containers when I connect to them using standard docker logs -f <container_id> -- Probably I'm missing something very obvious but I'm running out of ideas at the moment.
#### Environment information

This issue occurs from any reachable Docker client machine with the right set of certificates. Additionally, trying different docker versions and even from the VIC appliance itself. 
We're running a single management network and there are no ports being blocked in the middle, same broadcast and collision domain.
##### vSphere and vCenter Server version

vSphere and vCenter 6.5U2
##### VIC version

vic-v1.5.2-7206-92ebfaf5
##### VCH configuration

        --target=XX.XX.XX.:XXX
        --thumbprint=XX.XX.XX.:XXX
        --name=VIC-VCH-01
        --compute-resource=XX.XX.XX.:XXX
        --ops-user=vsphere.local\vic-ops
        --image-store=ds://hcs-iww-VNX-LUN-30
        --base-image-size=30GB
        --container-name-convention=VIC-{name}.docker
        --volume-store=ds://XXXX-VNX-LUN-30/volumes:default
        --dns-server=XX.XX.XX.:XXX
        --bridge-network=VIC-VCH-01-Bridge
        --public-network=WAHPB_Management2
        --public-network-gateway=10.25.81.33
        --public-network-ip=10.25.81.58/27
        --whitelist-registry=*.wahp.cww-hcs.com
        --https-proxy=https://XX.XX.XX.:XXX
        --http-proxy=http://XX.XX.XX.:XXX
        --no-proxy=0,1,2,3,4,5,6,7,8,9,XXXX
        --debug=3

##### Steps to reproduce
#> docker exec -it <container_id> <command>

##### Actual behavior
```
root@vic-mgmt-01 [ ~/.docker ]# docker --tlsverify --tlscacert=/root/.docker/ca.pem --tlscert=/root/.docker/cert.pem --tlskey=/root/.docker/key.pem -H=VIC-VCH-01.wahp.cww-hcs.com:2376 ps
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
75cfa75738f7        vic-mgmt-01XXXX.com:443/awx-vic/postgres:awx   "docker-entrypoint..."   50 seconds ago      Up 27 seconds                           postgres-mcm690-108748975048
b9161a25b158        vic-mgmt-01XXXX-hcs.com:443/awx-vic/rabbitmq:3     "docker-entrypoint..."   20 minutes ago      Up 20 minutes                           rabbitmq-mcm689-108747772705

root@vic-mgmt-01 [ ~/.docker ]# docker --tlsverify --tlscacert=/root/.docker/ca.pem --tlscert=/root/.docker/cert.pem --tlskey=/root/.docker/key.pem -H=VIC-VCH-01.XXXX:2376 exec -it 75cfa75738f7 /bin/bash
Server error from portlayer: no consumer: "text/html;charset=utf-8"
Error response from daemon: Server error from portlayer: no consumer: "text/html;charset=utf-8"

root@vic-mgmt-01 [ ~/.docker ]# docker --tlsverify --tlscacert=/root/.docker/ca.pem --tlscert=/root/.docker/cert.pem --tlskey=/root/.docker/key.pem -H=VIC-VCH-01.XXXX:2376 exec -it 75cfa75738f7 ls
Server error from portlayer: no consumer: "text/html;charset=utf-8"
Error response from daemon: Server error from portlayer: no consumer: "text/html;charset=utf-8"

```
##### Expected behavior

Interactive console attached to the container.

#### Logs

Log bundle is attached here.

#### Troubleshooting attempted

- [x] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [x] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [x] Searched for a relevant [VMware KB article][kb].
Haven't found any accurate existent GitHub issue...  

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by renmaosheng** [comment]
Yanzhao, could you please take a look? thanks.

**Comment by kitos9112** [comment]
Any help would be appreciated @renmaosheng @YanzhaoLi

**Comment by kitos9112** [comment]
Hello,

I am working with Jonathan Wilk (@doodlewilk) from VMware on this SR 19006818106
We found out this : 
SSH'd into VCH :
```
root@ [ ~ ]# ps -aux | grep dock
root 199 0.0 2.2 258612 46388 ? Ssl 08:22 0:02 /sbin/docker-engine-server -port=2376 -port-layer-port=2377
root 1347 0.0 0.0 4396 824 pts/0 S+ 10:37 0:00 grep --color=auto dock
root@ [ ~ ]# kill 199
Restart manually the "/sbin/docker-engine-server -port=2376 -port-layer-port=2377" and now it works!

```
What is happening..?
Thanks in advance!

**Comment by renmaosheng** [comment]
@kitos9112, we may need the logs to check why restart fix the issue, thanks.

**Comment by renmaosheng** [comment]
please provide more logs if we want to know why restarts help resolve the issue, closing it for now.
