### ISSUE TITLE
docker info

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#857]
This should return the docker specific data such as:
```
Containers: 14
 Running: 3
 Paused: 1
 Stopped: 10
Images: 52
Server Version: 1.9.0
```

It should also return some very basic capacity information: 
* memory available (resource pool limit or cluster capacity)
* cpu available (resource pool limit or cluster capacity)

Some customers expressly wanted information such as datastore hidden (pretty sure this was a service provider) so other data needs market research for inclusion.

It would be interesting to add the following elements as time allows:
* maximum cpu/memory for unreserved pools modified based on shares and current cluster utilization
* % available

#861 is open for exposing dynamic info about the execution environment but, as that issue notes, the static data in VCH config struct can be used as interim values.

**Comment by corrieb** [comment]
@sflxn please close if this is completed

**Comment by sflxn** [comment]
This is done but #1391 was opened for some of the remaining work.  There is a PR for 1391, but we held off on merging it due to CI issues at the time.

**Comment by hickeng** [comment]
and #1390 for the correct values of cpu and memory
