### ISSUE TITLE
UDP port cannot be exposed

### ISSUE THREAD

**Issue by Hedgehog57** [vmware/vic#8573]
#### Summary

Creating DNSCrypt-proxy container. Connect by Bridge network. 
Use DNS client with containerized dnscrypt-proxy server.

Need to expose ports 8053/TCP and 8053/UDP. From VIC HTTP interface cannot choose protocol at all. Only Port number can be entered. When port number is entered and container started one can see that only TCP port is exposed.

#### Environment information

Container: dnscrypt-proxy.

##### vSphere and vCenter Server version

ESXI 6.7U1 HP
VCenter 6.7U1
##### VIC version

vic-v1.5.3-7511-ba6b1644.ova
Have tested on 1.5.2 - same effect.
#### Details

Used Dockerfile
`FROM golang:1.11-alpine3.8 as build`

`ENV RELEASE_TAG 2.0.17`
`RUN apk --no-cache add git && \`
`    git clone https://github.com/jedisct1/dnscrypt-proxy /go/src/github.com/jedisct1/ && \`
`    cd /go/src/github.com/jedisct1/dnscrypt-proxy && \`
`    git checkout tags/${RELEASE_TAG} && \`
`    CGO_ENABLED=0 GOOS=linux go install -a -ldflags '-s -w -extldflags "-static"' -v ./...`

`FROM alpine:3.8`

`RUN apk --no-cache add ca-certificates`
`COPY --from=build /go/bin/dnscrypt-proxy /usr/local/bin/dnscrypt-proxy`
`ADD config /config`

`EXPOSE 53/udp`
`EXPOSE 53/tcp`

`CMD ["dnscrypt-proxy", "-config", "/config/dnscrypt-proxy.toml"]`

##### Steps to reproduce
Create container dnscrypt-proxy.
Connect to Brudge network.
Expose configured UDP and TCP ports.
Use VCH address and exposed port to resolv something.

##### Actual behavior

DNS doesn't work on UDP. Work like a charm on TCP.

##### Expected behavior
Resolving must work on exposed UDP port

#### Logs 
[menv@methone ~]$ dig google.com @192.168.160.86 -p 8053

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> google.com @192.168.160.86 -p 8053
;; global options: +cmd
;; connection timed out; no servers could be reached

[menv@methone ~]$ dig google.com @192.168.160.86 -p 8053 +tcp

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> google.com @192.168.160.86 -p 8053 +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6782
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
; OPT=12: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.)
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             2       IN      A       172.217.20.46

;; Query time: 116 msec
;; SERVER: 192.168.160.86#8053(192.168.160.86)
;; WHEN: Tue Jul 23 23:42:12 MSK 2019
;; MSG SIZE  rcvd: 128

#### Troubleshooting attempted

- [ ] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [ ] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [ ] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by Hedgehog57** [comment]
![created container DNSCrypt-proxy](https://user-images.githubusercontent.com/44364616/61747491-a5d6b980-ada6-11e9-9b53-774243441c99.jpg)

![container network configuration](https://user-images.githubusercontent.com/44364616/61747346-555f5c00-ada6-11e9-840d-e7d4372d1413.jpg)

**Comment by yuyangbj** [comment]
Could you please login VCH and show me the iptables -s nat -t results? Thanks

**Comment by Hedgehog57** [comment]
@yuyangbj I think I understand what do You mean.

root@ [ ~ ]# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DROP       all  --  anywhere             anywhere             ctstate INVALID
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:22
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     udp  --  anywhere             anywhere             udp dpt:68
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2375
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2376
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2377
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2378
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2380
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6060
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6061
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6062
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6063
ACCEPT     udp  --  anywhere             anywhere             udp dpt:53
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:53
REJECT     udp  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             anywhere             reject-with tcp-reset
REJECT     all  --  anywhere             anywhere             reject-with icmp-proto-unreachable

Chain FORWARD (policy DROP)
target     prot opt source               destination
VIC        all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain VIC (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:53
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:53

As I see 8053/UDP is not opened. But same can be told about 8053/TCP. 

This is from flex-kmz-vch1.kmz.ts

root@ [ ~ ]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: public: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:a5:03:d4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.160.86/25 scope global public
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea5:3d4/64 scope link
       valid_lft forever preferred_lft forever
3: bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:a5:a2:ac brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/16 scope global bridge
       valid_lft forever preferred_lft forever
    inet 172.17.0.1/16 scope global bridge
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea5:a2ac/64 scope link
       valid_lft forever preferred_lft forever

About requested informtaion:

root@ [ ~ ]# iptables -s nat
iptables v1.6.1: no command specified
Try `iptables -h' or 'iptables --help' for more information.
root@ [ ~ ]# iptables -s nat -t results
iptables v1.6.1: no command specified
Try `iptables -h' or 'iptables --help' for more information.

**Comment by Hedgehog57** [comment]
I'm back of vacations and can add additional requested (i suppose) information.
```
root@ [ ~ ]# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
VIC        all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
VIC        all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere
MASQUERADE  tcp  --  anywhere             172.17.0.2           tcp dpt:53

Chain VIC (2 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             anywhere             tcp dpt:8053 to:172.17.0.2:53
DNAT       tcp  --  anywhere             anywhere             tcp dpt:8053 ADDRTYPE match dst-type LOCAL to:172.17.0.2:53
```
As You can see there is a rule for TCP, but not UDP. I have modified rules on VCH in shell like this
```
root@ [ ~ ]# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
VIC        all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
VIC        all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere
MASQUERADE  tcp  --  anywhere             172.17.0.2           tcp dpt:53
MASQUERADE  udp  --  anywhere             172.17.0.2           udp dpt:53

Chain VIC (2 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             anywhere             tcp dpt:8053 to:172.17.0.2:53
DNAT       udp  --  anywhere             anywhere             udp dpt:8053 to:172.17.0.2:53
DNAT       tcp  --  anywhere             anywhere             tcp dpt:8053 ADDRTYPE match dst-type LOCAL to:172.17.0.2:53
DNAT       udp  --  anywhere             anywhere             udp dpt:8053 ADDRTYPE match dst-type LOCAL to:172.17.0.2:53
```
Now it works like a charm.
```
[menv@methone ~]$ dig google.com @192.168.160.86 -p 8053 +short
173.194.222.102
173.194.222.101
173.194.222.113
173.194.222.100
173.194.222.138
173.194.222.139
[menv@methone ~]$ dig google.com @192.168.160.86 -p 8053 +tcp +short
173.194.222.102
173.194.222.101
173.194.222.113
173.194.222.100
173.194.222.138
173.194.222.139
```
But there is no way to do it from VIC inteface.

**Comment by Hedgehog57** [comment]
Any information or progress?

We have created container network in addition to bridge and we see same problem on it. UDP ports cannot be exposed.

**Comment by yuyangbj** [comment]
Yeah, I will check the code and fix it in next release, the next release will be at next month.

**Comment by yuyangbj** [comment]
@Hedgehog57 could you help to confirm if you have similar logs in /var/log/vic/docker-personality.log on VCH. Thanks. That was the error for udp to create iptable rule.

Aug 14 2019 09:20:35.143Z DEBUG Adding indirect mapping for port 80/udp: {10.161.116.176 10001} (10001:80/udp)
Aug 14 2019 09:20:35.143Z DEBUG Mapping ports of "5a0de6418ecdd65627cec7c57c957e50c362b062f25e6b2bc2419f6b4112d22f" on endpoint webserver: map[80/udp:[{10.161.116.176 10001}]]
Aug 14 2019 09:20:35.143Z DEBUG UnmapPorts for 5a0de6418ecdd65627cec7c57c957e50c362b062f25e6b2bc2419f6b4112d22f: map[80/udp:[{10.161.116.176 10001}]]
Aug 14 2019 09:20:35.143Z DEBUG skipping already unmapped 10001

**Comment by Hedgehog57** [comment]
@yuyangbj Nope. 
```
root@ [ ~ ]# grep DEBUG /var/log/vic/docker-personality.log
root@ [ ~ ]#
```
It seems I need to enable DEBUG for that. Can do that but don't know how. Need advice. ;)

**Comment by coreydinkens** [comment]
@Hedgehog57 You should be able to use the following to enable debug on the VCH:

_Note: this is the vic-machine **configure** command, **not** vic-machine create debug_

`.\vic-machine-windows.exe configure --target <vcenter ip> --user "<vsphere admin user>" --password "<ADMINPASS>" --compute-resource "<resource pool name>" --name <vch name>  --thumbprint <vCenter Thumbprint> --debug 2`

Below are the debug level descriptions in case level 2 is not enough( [Full Docs link](https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_general_settings.html#debug) ):

> Level **1** - Provides verbosity in the logs, with no other changes to vic-machine behavior. This is the default setting.
> Level **2** - Exposes servers on more interfaces, launches pprof in container VMs.
> Level **3** - Disables recovery logic and logs sensitive data. Disables the restart of failed components and prevents container VMs from shutting down. Logs environment details for user application, and collects application output in the log bundle.

**Comment by Hedgehog57** [comment]
Thanks for an advice @coreydinkens 
Have enabled DEBUG 2

Recreated container from template in VIC. There may be one of the problem.
There is no way to configure UDP port binding. I cannot set

8053/udp -> 53/udp

Only 

8053 -> 53 
and set "Publish All ports"

In that case it looks like only tcp ports are published 

In "build history" of an image in VIC interface I can see 

7/19/19, 7:08 PM EXPOSE 53/udp
7/19/19, 7:08 PM EXPOSE 53/tcp

Will attach full docker-personality.log file.

[docker-personality.log](https://github.com/vmware/vic/files/3506324/docker-personality.log)

In the next reply I will try to start a new container by docker CLI (not from VIC) and publish udp and tcp ports.

**Comment by Hedgehog57** [comment]
Did it like this

docker -H flex-kmz-vch1.kmz.ts:2376 --tls run -p 8053:53/udp -p 8053:53/tcp vic.kmz.ts:443/oio/dnscrypt-proxy:latest 

Updated docker-personality.log is attached.

[docker-personality.log](https://github.com/vmware/vic/files/3506361/docker-personality.log)

interesting part:

```
Aug 15 2019 16:26:03.363Z DEBUG Adding indirect mapping for port 53/tcp: {192.168.160.86 8053} (8053:53/tcp)
Aug 15 2019 16:26:03.363Z DEBUG Adding indirect mapping for port 53/udp: {192.168.160.86 8053} (8053:53/udp)
Aug 15 2019 16:26:03.363Z DEBUG Mapping ports of "e0bf6cc64247be283d0f7e3bd8bd970764061c11c31f0b0291e8934854119839" on endpoint modest_meninsky: map[53/tcp:[{192.168.160.86 8053}] 53/udp:[{192.168.160.86 8053}]]
Aug 15 2019 16:26:03.363Z DEBUG /sbin/iptables, [--wait -A VIC -t nat -i public -p tcp -d 0/0 --dport 8053 -j DNAT --to-destination 172.16.0.4:53]
Aug 15 2019 16:26:03.367Z DEBUG /sbin/iptables, [--wait -A VIC -t nat -i bridge -p tcp --dport 8053 -j DNAT --to-destination 172.16.0.4:53 -m addrtype --dst-type LOCAL]
Aug 15 2019 16:26:03.372Z DEBUG /sbin/iptables, [--wait -A VIC -t filter -i public -o bridge -p tcp -d 172.16.0.4 --dport 53 -j ACCEPT]
Aug 15 2019 16:26:03.395Z DEBUG /sbin/iptables, [--wait -A POSTROUTING -t nat -p tcp -d 172.16.0.4 --dport 53 -j MASQUERADE]
Aug 15 2019 16:26:03.397Z DEBUG /sbin/iptables, [--wait -I VIC 1 -t filter -i bridge -o bridge -p tcp -d 172.16.0.4 --dport 53 -j ACCEPT]
Aug 15 2019 16:26:03.399Z DEBUG mapped port 8053 for container e0bf6cc64247be283d0f7e3bd8bd970764061c11c31f0b0291e8934854119839
Aug 15 2019 16:26:03.399Z DEBUG Skipping mapping for already mapped port 8053 for e0bf6cc64247be283d0f7e3bd8bd970764061c11c31f0b0291e8934854119839
Aug 15 2019 16:26:03.399Z DEBUG op=250.259: Commit container e0bf6cc64247be283d0f7e3bd8bd970764061c11c31f0b0291e8934854119839
```
It skip mapping because it thinks it is already mapped.

**Comment by Hedgehog57** [comment]
Hello again.

I have updated our infrastructure to VIC 1.5.4.

Now, UDP ports can be exposed by hands when creating new containers from docker command line.

```
docker -H flex-kmz-vch1.kmz.ts:2376 --tls run -p 8053:53/udp -p 8053:53/tcp vic.kmz.ts:443/oio/dnscrypt-proxy:latest
```
That command has created new container, and created NAT rules
```
Sep 30 2019 15:19:23.625Z DEBUG Adding indirect mapping for port 53/tcp: {192.168.160.86 8053} (8053:53/tcp)
Sep 30 2019 15:19:23.625Z DEBUG Adding indirect mapping for port 53/udp: {192.168.160.86 8053} (8053:53/udp)
Sep 30 2019 15:19:23.625Z DEBUG Mapping ports of "6d1ff1380fb383267172605e741252624cb640ac1b8cc1044f12738daf83c60f" on endpoint confident_lamport: map[53/tcp:[{192.168.160.86 8053}] 53/udp:[{192.168.160.86 8053}]]
Sep 30 2019 15:19:23.625Z DEBUG 8053/tcp
Sep 30 2019 15:19:23.625Z DEBUG /sbin/iptables, [--wait -A VIC -t nat -i client -p tcp -d 0/0 --dport 8053 -j DNAT --to-destination 172.16.0.3:53]
Sep 30 2019 15:19:23.632Z DEBUG /sbin/iptables, [--wait -A VIC -t nat -i bridge -p tcp --dport 8053 -j DNAT --to-destination 172.16.0.3:53 -m addrtype --dst-type LOCAL]
Sep 30 2019 15:19:23.639Z DEBUG /sbin/iptables, [--wait -A VIC -t filter -i client -o bridge -p tcp -d 172.16.0.3 --dport 53 -j ACCEPT]
Sep 30 2019 15:19:23.644Z DEBUG /sbin/iptables, [--wait -A POSTROUTING -t nat -p tcp -d 172.16.0.3 --dport 53 -j MASQUERADE]
Sep 30 2019 15:19:23.649Z DEBUG /sbin/iptables, [--wait -I VIC 1 -t filter -i bridge -o bridge -p tcp -d 172.16.0.3 --dport 53 -j ACCEPT]
Sep 30 2019 15:19:23.654Z DEBUG mapped port 8053 for container 6d1ff1380fb383267172605e741252624cb640ac1b8cc1044f12738daf83c60f with protocol tcp
Sep 30 2019 15:19:23.654Z DEBUG 8053/udp
Sep 30 2019 15:19:23.668Z DEBUG query port 8053 using netstat with error exit status 127
Sep 30 2019 15:19:23.668Z DEBUG output to query udp port: 
Sep 30 2019 15:19:23.668Z DEBUG /sbin/iptables, [--wait -A VIC -t nat -i client -p udp -d 0/0 --dport 8053 -j DNAT --to-destination 172.16.0.3:53]
Sep 30 2019 15:19:23.674Z DEBUG /sbin/iptables, [--wait -A VIC -t nat -i bridge -p udp --dport 8053 -j DNAT --to-destination 172.16.0.3:53 -m addrtype --dst-type LOCAL]
Sep 30 2019 15:19:23.722Z DEBUG /sbin/iptables, [--wait -A VIC -t filter -i client -o bridge -p udp -d 172.16.0.3 --dport 53 -j ACCEPT]
Sep 30 2019 15:19:23.727Z DEBUG /sbin/iptables, [--wait -A POSTROUTING -t nat -p udp -d 172.16.0.3 --dport 53 -j MASQUERADE]
Sep 30 2019 15:19:23.732Z DEBUG /sbin/iptables, [--wait -I VIC 1 -t filter -i bridge -o bridge -p udp -d 172.16.0.3 --dport 53 -j ACCEPT]
Sep 30 2019 15:19:23.736Z DEBUG mapped port 8053 for container 6d1ff1380fb383267172605e741252624cb640ac1b8cc1044f12738daf83c60f with protocol udp
```
iptables rules are created and DNS lookups works.
```
[menv@methone ~]$ dig  google.com @192.168.160.86 -p 8053 +short
173.194.222.113
173.194.222.138
173.194.222.139
173.194.222.100
173.194.222.102
173.194.222.101
```
But the problem is still there. 

There is no way to create new template in VIC web interface with exposed UDP ports. 

![image](https://user-images.githubusercontent.com/44364616/65893690-0985f000-e3b1-11e9-961b-8a8f98400b51.png)

if one enter 8053/udp instead 8053 and press save port binding will be simply creared.

**Comment by fabiogermann** [comment]
Just FYI - there is a workaround for anyone that is looking for this. Create a template in VIC (in library/templates), export it as docker compose and change the section:

```
ports:
  - "6060:6060"
```
to: 
```
ports:
  - "6060:6060/udp"
```
and re-import the template. The UDP port will be saved in the template and you can use it.
