### ISSUE TITLE
DRS: placement and vMotion of containerVMs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#859]
This is primarily a testing exercise to ensure that:
* we do not inhibit correctly placement of VMs during power on.
* fully auto DRS can still vMotion VMs as expected - this should be assessed against similarly loaded clusters with non containerVMs.

This has a performance facet - does the power on placement decision materially impact container start time?

**Comment by hickeng** [comment]
Estimate of 5 for basic automated validation of vMotion support - this does not encompass any performance/placement assessment.

**Comment by mhagen-vmware** [comment]
vMotion is being tested here: #2270 #2250 
And was initially implemented here: #2251 

DRS support testing to follow shortly.
