### ISSUE TITLE
UDP port expose cannot be configured from VIC HTTP interface.

### ISSUE THREAD

**Issue by Hedgehog57** [vmware/vic#8594]
#### Summary

UDP port expose cannot be configured from VIC HTTP interface.

##### vSphere and vCenter Server version

VSphere 6.7U3
ESXi 6.7U3
VCenter VCSA 6.7U3
##### VIC version

1.5.4
##### VCH configuration

vic-machine-windows.exe create --target vcenter --user username@domain --compute-resource vm-cluster --image-store esxi-store --volume-store esxi-store/vch1-name-volumes:default --name vch1-name --public-network network --containers 20 -b vch1-bridge --no-tlsverify --registry-ca ca-v3.crt 
##### Steps to reproduce
open https://vic-host.domain:8282
authorize
Library ->Templates -> Create template ->Add container ->choose anything  -> network -> port binding: <port number>/udp -> container number: <port number>udp ->save
##### Actual behavior
Edit container -> Network
port definitions are empty. 
![image](https://user-images.githubusercontent.com/44364616/65893690-0985f000-e3b1-11e9-961b-8a8f98400b51.png)
##### Expected behavior
ports must be saved with protocol. In the example I use UDP. Entering TCP leads to the same result. If no protocol is specified only TCP will be exposed.
#### Logs
After fixing issue #8573 on the VCH side everithing is OK. Creating container "by hand" from docker command line works fine.

#### Troubleshooting attempted

- [ ] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [ ] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [ ] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by renmaosheng** [comment]
I would suggest to use command line for UDP. we would not fix the UI. @yuyangbj we should document this, thanks.

**Comment by Hedgehog57** [comment]
Hello @renmaosheng 

What kind of CLI? docker CLI? But it mean that developer must create dockerfile on its own computer. There will be no way to modify image on VIC. And no way to share templates.
As of me its a very common usage. If You need to create DNS server, DNS proxy on any other UDP-based container You need not to use VIC, but docker.

Or did I miss something?

**Comment by yuyangbj** [comment]
@Hedgehog57 you can use the traditional docker CLI to specify protocol and expose port. I will document the UI cannot support it. Thanks.

**Comment by stuclem** [comment]
Hi @VinodJIsaac can you please work with @yuyangbj to get this documented? Thanks!

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #2542](https://github.com/vmware/vic-product/issues/2542) via [**ZenHub**](https://www.zenhub.com/)
