### ISSUE TITLE
Port layer: info

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#861]
Basic information about the backend system. This supports #857, providing a mechanism whereby the resource limits and availability can be determined. 

Until this live mechanism is available, the data can be pulled from the VCH configuration. This will be much less informative in the case on "unlimited" resources where there's no indication of actual capacity limits.

**Comment by hickeng** [comment]
Should try to have something here for onsite - we need to validate with customers how much infrastructure data should be leaked to users.

**Comment by corrieb** [comment]
@hickeng seems to fall into the bracket of "nice to have" for onsite, given the time constraints

**Comment by mdubya66** [comment]
In for 0.7.0.

**Comment by anchal-agrawal** [comment]
Closing via #2898.
