### ISSUE TITLE
VIC 1.5.X  OVA SSL Certificate Create issue.

### ISSUE THREAD

**Issue by Rajeshunix13** [vmware/vic#8610]
Hi,  Im trying to install VIC1.5.X on standalone esxi with enterprise license, post v'app import it is showing sha1 fingerprint issue and no ssl's are found in /storage/{admiral  certs  fileserver  harbor } locations. please help me to fix the issue.

**Comment by renmaosheng** [comment]
Wending,
      could you please first take a look? thanks.

**Comment by ading007** [comment]
Working on it.

**Comment by ading007** [comment]
Hi Rajeshunix13,
  Could you please provide to detail reproduce process?

**Comment by ading007** [comment]
Rajeshunix13,

I suspect you should deploy the vic appliance directly on ESX. If so, it is not supported.  you have to deploy it on the vsphere web client, for more details, please refer to https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/deploy_vic_appliance_ovftool.html, you can also deploy vch appliance via vsphere web client ui, as follows:

![image](https://user-images.githubusercontent.com/19757922/74398258-f9e3e100-4e51-11ea-8d57-88f0e8132a34.png)

**Comment by renmaosheng** [comment]
Hi Rajeshunix13,
       you need vcenter to deploy the whole stack, if you only have ESX host, you can use the vic-machine command only. thanks.
