### ISSUE TITLE
Port layer: inspect

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#862]
This is about how to obtain detailed information about a port layer object, given a handle or ID.
This is particularly relevant for containerVMs and networks, specifically the former. Storage is included as well as symmetry is valuable in an API.

If necessary the initial implementation can be limited to only exposing specific data about a containerVM. Generally this is exposing the data that makes up the config for the containerVM, but should also include the id and name of it's image - while this data is inherent in the disk hierarchy it needs to be present in information (rather than active) form so the portlets can display it.

The format by which this data is returned is not currently defined, but should likely reflect the parameter structure that is used to supply it during the create and join calls.

**Comment by hickeng** [comment]
@corrieb we have the ability to return a list of containers - that essentially provides this capability keyed off IDs only. Assigning to you for API conversation.

**Comment by corrieb** [comment]
@hickeng @cgtexmex we got inspect functionality in TP3. If this is mostly about cleaning up the port layer API, it's not going to make onsite. Moving to GA.

**Comment by corrieb** [comment]
Seems to me this this is incorporated into #1043. Adding a couple days to that to make sure that it meets the requirements laid out here

**Comment by hickeng** [comment]
This should be addressed in or under #1043
