### ISSUE TITLE
Deleting deployed application fails when docker bridge network is in use 

### ISSUE THREAD

**Issue by leander091** [vmware/vic#8625]
#### Summary
It is not possible to remove an application when there is an extra docker network attached in the template.  You will receive an error like this:
`Service https://VICHOST:2376/v1.24/networks/6f8585aa75f5ef6867b1b935eae51806ceaeb4daeeeddd4710e8fc815553a34a returned error 500 for DELETE. id 2358264 message NetBox_Network-mcm457-130877281260 has active endpoints; Reason: {"message":"NetBox_Network-mcm457-130877281260 has active endpoints"} `

The docker machines are correctly removed as the error occurs but the Networks and provisioned volumes will remain under the application section of VIC.   

#### Environment information
vCenter version: 6.7.0.42000
VIC: v1.5.4-7589
VCH: v1.5.4, 21221

##### VCH configuration
`./vic-machine-linux create --name Vch01 --compute-resource Intel-Cluster --cpu-reservation 1 --cpu-shares normal --memory-reservation 1 --memory-shares normal --endpoint-cpu 1 --endpoint-memory 2048 --image-store Datastore01 --base-image-size 8GB --volume-store Datastore01:Datastore01 --volume-store Datastore01:default  --volume-store "nfs://nfshost/data/datastore02?uid=0&gid=0:Datastore02" --bridge-network Vch-bridge01 --bridge-network-range 172.16.0.0/12  --public-network Access --public-network-ip 168.192.254.31/24 --public-network-gateway 168.192.254.1 --dns-server 168.192.254.2  --tls-cname vch01.example.com--certificate-key-size 4096 --registry-ca /etc/docker/certs.d/vic.example.com/ca.crt --user Administrator@VSPHERE.LOCAL --thumbprint 6B:43:26:6A:B8:49:35:88:1D:A9:FC:7D:A1:18:A5:AC:B3:8D:38:B9 --target vcenterhost.com/Datacenter --ops-user vic-ops@example.com--ops-grant-perms
`
I have removed some sensitive values in the configuration string above. 

##### Steps to reproduce
1. Create an application within the VIC interface and attach an docker network to it.
2. Deploy the application.
3. Remove de application within the VIC interface,

##### Actual behavior
Error during removal of application. 

`Service https://VICHOST:2376/v1.24/networks/6f8585aa75f5ef6867b1b935eae51806ceaeb4daeeeddd4710e8fc815553a34a returned error 500 for DELETE. id 2358264 message NetBox_Network-mcm457-130877281260 has active endpoints; Reason: {"message":"NetBox_Network-mcm457-130877281260 has active endpoints"} `

It is possible to work around this problem to restart the vch host. After restarting the remaining items will be removed correctly. 

##### Expected behavior

The machines and network will be removed without error messages. 

#### See also

https://kb.vmware.com/s/article/52615

#### Troubleshooting attempted

- [x] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [x] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [x] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by renmaosheng** [comment]
would the KB article you referenced not working? thanks.

**Comment by leander091** [comment]
Yes there is an workaround for this issue, but is not really practical to wait until to network information has been refreshed without any indication when that is going to be happen.  Is there an definitive solution or better workaround available?

**Comment by renmaosheng** [comment]
Hi Leander, sorry, there would be no concrete solution for this issue in near future.

**Comment by leander091** [comment]
@renmaosheng  Alright, thanks for  your time
