### ISSUE TITLE
Networking issues with Containers

### ISSUE THREAD

**Issue by andrewolinSMP** [vmware/vic#8627]
#### Summary
We have been experiencing intermittent network issues. Often when a container is built and started it is not able to ping out or ping the gateway, restarting the container up to 3 times generally solves the issue, but not always, and we have to test every container on every boot for network connectivity. It also seems like once a container that was connected to the network is stopped and started again, it will never be able to connect to the network again.

##### vSphere and vCenter Server version
vSphere/vCenter: 6.7

##### VIC version
VIC: v1.5.4.1536
VCH: v1.5.4, 21221, b3d3b06f

##### VCH configuration
created with vic-machin-windows.exe
bridge network on a distributed port group, /16 network

#### Logs
[user]@[user-machine]:/mnt/c/Users/[user]/Documents/docker_samples$ docker start docker_samples_ubuntu_client_1
docker_samples_ubuntu_client_1
[user]@[user-machine]:/mnt/c/Users/[user]/Documents/docker_samples$ docker exec -it docker_samples_ubuntu_client_1 sh
~ ping google.com
PING google.com (172.217.7.206) 56(84) bytes of data.
64 bytes from iad30s10-in-f14.1e100.net (172.217.7.206): icmp_seq=1 ttl=54 time=15.9 ms
64 bytes from iad30s10-in-f14.1e100.net (172.217.7.206): icmp_seq=2 ttl=54 time=16.0 ms
64 bytes from iad30s10-in-f14.1e100.net (172.217.7.206): icmp_seq=3 ttl=54 time=16.0 ms
64 bytes from iad30s10-in-f14.1e100.net (172.217.7.206): icmp_seq=4 ttl=54 time=16.0 ms
^C
--- google.com ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4005ms
rtt min/avg/max/mdev = 15.958/16.030/16.080/0.045 ms
~ exit
[user]@[user-machine]:/mnt/c/Users/[user]/Documents/docker_samples$ docker stop docker_samples_ubuntu_client_1
docker_samples_ubuntu_client_1
[user]@[user-machine]:/mnt/c/Users/[user]/Documents/docker_samples$ docker start docker_samples_ubuntu_client_1
docker_samples_ubuntu_client_1
[user]@[user-machine]:/mnt/c/Users/[user]/Documents/docker_samples$ docker exec -it docker_samples_ubuntu_client_1 sh
~ ping google.com
ping: google.com: Temporary failure in name resolution
~ ping 172.217.7.206
PING 172.217.7.206 (172.217.7.206) 56(84) bytes of data.
From 172.16.0.8 icmp_seq=1 Destination Host Unreachable
From 172.16.0.8 icmp_seq=2 Destination Host Unreachable
From 172.16.0.8 icmp_seq=3 Destination Host Unreachable
^C
--- 172.217.7.206 ping statistics ---
6 packets transmitted, 0 received, +3 errors, 100% packet loss, time 5096ms
pipe 4
~ ping 172.16.0.1
PING 172.16.0.1 (172.16.0.1) 56(84) bytes of data.
From 172.16.0.8 icmp_seq=1 Destination Host Unreachable
From 172.16.0.8 icmp_seq=2 Destination Host Unreachable
From 172.16.0.8 icmp_seq=3 Destination Host Unreachable
^C
--- 172.16.0.1 ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4094ms
pipe 4

This is a new technology for me, but the intermittent behavior is odd.

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

**Comment by renmaosheng** [comment]
Hi andrewolinSMP,
       Could you please check whether your environment might have IP conflicts issue? some times if you deploy VCH in a same vlan which 172.17.** is used by others, this might happen.
Thanks
Steven

**Comment by andrewolinSMP** [comment]
Hi Steven,
It doesn't look like we have any IP conflicts. We noticed though that the network failure happens when a container is started on a different host in our cluster. We have created the distributed port group like the documentation states, and added all of the hosts in our cluster to it. Is there something we are missing?

**Comment by andrewolinSMP** [comment]
I think we got it resolved. Configuration issue with our port group, seems to be working now. Thank you for the help!

**Comment by samized** [comment]
@andrewolinSMP Facing the same network problems, can you give me some more information about your configuration issue with your port group... Thanks

**Comment by viper93458** [comment]
Same trouble here, hopefully we will get an expansion of that the configuration issue was.

-William

**Comment by andrewolinSMP** [comment]
@samized @viper93458 Sorry guys! I hope that you were able to figure out the issue before now, but it's been a while so I don't remember exactly what the fix was. I believe it was an issue with a VLAN which was not routing between hosts in our cluster. The intermittent-ness of the issue was caused by the container-vm's migrating between hosts in the cluster. So if the container was on the same host as the VCH, everything worked, but when it was restarted, it was likely to be started on a different host in the cluster and then network connectivity dropped. I hope that this helps.

**Comment by samized** [comment]
@andrewolinSMP After some VLAN reconfiguration now everything works fine. Thanks
