### ISSUE TITLE
Document how putting a host into maintenance mode affects VIC

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#864]
Per https://github.com/vmware/vic/issues/860.

**Comment by stuclem** [comment]
This can go into the topic on [vSphere Interop](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/interop.md#vmware-virtual-san), in particular in cases in which VMs are vMotioned off a host when it goes into maintenance mode, per https://github.com/vmware/vic/issues/770.

**Comment by stuclem** [comment]
See https://github.com/vmware/vic/issues/2245 and https://github.com/vmware/vic/issues/2244

**Comment by stuclem** [comment]
@npakrasi can you please take a look?

**Comment by stuclem** [comment]
According to @cgtexmex in https://github.com/vmware/vic/issues/2245#issuecomment-260797416, apparently there are caveats:

----

In the case of a standalone host you must first power down the VCH (or any other VMs) before entering maintenance mode [...]

In a clustered vSphere environment with DRS set to automatic I was able to put a host into maintenance mode which hosted a running VCH. DRS will first migrate the VCH to another host in the cluster and then enter maintenance mode. Additionally, I tested with a host that was hosting a running container VM -- same result a successful migration and entry to maintenance mode.

----

**Comment by stuclem** [comment]
@cgtexmex, when you refer to a "standalone host" above, this applies both to a deployment directly to an ESXi host that is not managed by a VC, and to a host that is managed by a VC but that is not part of a cluster. Correct? 

Thanks!

**Comment by npakrasi** [comment]
Added this to the interop topic under VMware vSphere vMotion:

Hosts with container VMs can enter maintenance mode without manual intervention, with these exceptions:

- For a standalone host, you must first power down the virtual container host or any other VMs before entering maintenance mode. 
- In a clustered vSphere environment with DRS set to automatic, DRS first migrates the virtual container host to another host in the cluster and then enters maintenance mode. 
- For a host with a container VM running, DRS first migrates the VM to another host in the cluster and then enters maintenance mode.
