### ISSUE TITLE
Document docker run

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#866]
Per https://github.com/vmware/vic/issues/855.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md)

**Comment by stuclem** [comment]
Looks like work is still ongoing on docker run, according to https://github.com/vmware/vic/issues/855.

**Comment by npakrasi** [comment]
Added more composite commands to docker run in the Supported Docker Commands table.

**Comment by stuclem** [comment]
Reverting this one to To Do because PR https://github.com/vmware/vic/pull/2118 adds support for using `docker run` with custom registries. Worth mentioning in the big table of Supported Docker Commands.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/2154 completes the implementation, I think.

**Comment by npakrasi** [comment]
Added info on pulling images from private and custom registries to the Supported Docker Commands table.
