### ISSUE TITLE
Document docker port

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#867]
Per https://github.com/vmware/vic/issues/854.

**Comment by stuclem** [comment]
Looks like https://github.com/vmware/vic/issues/854 will make it for onsite.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md)

**Comment by stuclem** [comment]
Looks like port mapping (https://github.com/vmware/vic/issues/854) is implemented in PR https://github.com/vmware/vic/issues/1636.

**Comment by npakrasi** [comment]
Updated table with details that docker port is supported and displays port mapping data.
