### ISSUE TITLE
Document docker resize (TTY)

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#869]
Per https://github.com/vmware/vic/issues/680.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/680 is In Progress, so moving this to To Do.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md)
