### ISSUE TITLE
Document how VIC handles datastore renaming

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#872]
Per https://github.com/vmware/vic/issues/549.

**Comment by stuclem** [comment]
Moving to onsite beta.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/549 is implemented in PR https://github.com/vmware/vic/pull/1017.

**Comment by stuclem** [comment]
Added the following to the topic on `vic-machine create` options:

"The `vic-machine` utility allows you to specify the datastores in which to store container VM files, container image files, and the files for the virtual container host appliance. vSphere Integrated Containers fully supports VMware Virtual SAN datastores.

**NOTE**: When you deploy a virtual container host, even though you specify datastore names, `vic-machine create` obtains and uses the UUIDs for the datastores that you specify. As a result, if the name of a datastore changes after you have deployed a virtual container host, the virtual container host continues to function normally."

See https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#datastore

@fdawg4l, is this OK? Thanks!

**Comment by fdawg4l** [comment]
Hi @stuclem!  So we have a bit of a mismatch.  #549 and #1017 are specific to VSAN UUIDs which are not the same as Managed Object References used by VC to identify things like datastores, VMs, disks, etc.  Those Managed Object References are unique identifiers for all objects in vsphere.  The VSAN change I made is specific to VSAN and used to guard against eventual consistency of datastore directories.

In sort, the change doesn't involve datastore renaming or prevent it from breaking VIC.  Unfortunately.

However!  The verbiage you have is appropriate for when we cache the managed object references to datastores (which we have not done yet).  I'm sure we have an issue for this open and I'll link to it when i find it.

**Comment by stuclem** [comment]
Thanks @fdawg4l - so, should I just remove that NOTE and mothball for future reinclusion, once MOR reference caching is implemented?

**Comment by stuclem** [comment]
@fdawg4l, can we reinstate the blurb from my comment of Jun 19 above?

**Comment by fdawg4l** [comment]
We didn't get to it :-(.  Apologies.  We shouldn't include the blurb yet.

**Comment by stuclem** [comment]
OK, thanks @fdawg4l. Chucking this in the Icebox.

**Comment by stuclem** [comment]
Actually, @fdawg4l if this isn't implemented, should we say something along the lines of if you rename datastores after you deploy a VCH, then that VCH will not work any more?

**Comment by fdawg4l** [comment]
I think documenting that behavior is probably really useful.  Thanks for catching that.

**Comment by stuclem** [comment]
Added "VCHs do not support datastore name changes. If a datastore changes name after you have deployed a VCH that uses that datastore, that VCH will no longer function."

Change is in https://github.com/stuclem/vic/commit/f90f21bb01b02473391c476f620d226116e7bafc.

@fdawg4l is this OK? Moving this one out of GA and into Icebox pending the implementation of support for DS name changes.

**Comment by stuclem** [comment]
The issue of changing DS names might be covered on the dev side by https://github.com/vmware/vic/issues/1709. @fdawg4l is this the correct issue?

Regardless, https://github.com/vmware/vic/issues/1709 is  is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
This issue was moved to vmware/vic-product#108
