### ISSUE TITLE
Document docker images operations

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#880]
Per https://github.com/vmware/vic/issues/388 and https://github.com/vmware/vic/issues/387.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/387 is now closed, so it looks like images list is in the build.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table] (https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md)
