### ISSUE TITLE
Document docker container list

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#884]
Per https://github.com/vmware/vic/issues/369.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/369 is In Progress, so moving this one to To Do.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md) with a TBD to change to Yes when supported/implemented.
