### ISSUE TITLE
Document docker start

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#888]
Per https://github.com/vmware/vic/issues/302. There are probably other issues that relate to this.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/302 was merged into master in https://github.com/vmware/vic/pull/347, so moving this to To Do.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table] (https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md)
