### ISSUE TITLE
vic-machine: delete command processor

### ISSUE THREAD

**Issue by emlin** [vmware/vic#897]
Target of this task is to create vic-machine delete command, and process the input parameters.
The function to delete resources is not in this scope.

```
vic-machine delete
-target=<VC/ESXi URL>
-user=<user.
-passwd=<password>
-path=mycluster/edw-pool/web/edw-web // VCH resource pool path in govc format
```

**Comment by emlin** [comment]
Target of this task is to support subcommands in vic-machine, to make it support both create and delete commands, and in the future, to support more commands.

We might not leverage govc cli framework directly, cause there is no much value if flags are not reused, and it's unlikely to do that, cause vic-machine and govc should have different customer set.
As @dougm suggested, I'm looking at other CLI frameworks.

https://github.com/urfave/cli is used by docker machine, so it will be easier for us in the future to integrate with docker machine.
And it has all functions required by us right now, for example, custom flag types to support empty password, auto-completion, sub-commands, etc.

Will discuss with @dougm and @hickeng later today to finalize the solution, and likely this task will delay a couple of days.

**Comment by dougm** [comment]
Right, we don't want to adopt govc for just the cli framework itself.  There are several general purpose Go cli frameworks that are much better suited. At some point in the distant future will likely convert the govc cli to use one of them.  Personally I prefer https://github.com/spf13/cobra , used by the docker cli, etcd and kubernetes to name a few.  But urfave/cli (aka codegansta/cli) would be fine too, whichever meets your needs.  I don't want to delay moving forward, just wanted to avoid building new code on the govc cli framework and understand your needs better for a cli framework.

**Comment by emlin** [comment]
We decided go with [github.com/urfave/cli](http://github.com/urfave/cli)

**Comment by emlin** [comment]
Still need two days including today.
