### ISSUE TITLE
[security] Static Code Analysis

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#906]

**Comment by mdubya66** [comment]
GA feature from SSOD

**Comment by hickeng** [comment]
The only option I'm aware of here is to enable `-race` for all components. This is not what is intended by the static analysis portion of the security release processes, however it's what we have available for Go.

**Comment by hickeng** [comment]
https://github.com/HewlettPackard/gas - alpha analysis tool for Go AST
@caglar10ur should I be assigning this to you? ;)

**Comment by caglar10ur** [comment]
sure, I already created a report and looked at it this morning for fun. Nothing looked dangerous or wrong but we can still integrate it into Makefile I guess
