### ISSUE TITLE
docker volume ls

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#917]

**Comment by fdawg4l** [comment]
@matthewavery `VolumesList` in the volume cache works as expected, returning a list of `Volume`s.  Just create a list of ID from the returned `Volumes`, and that should be all you need to make the changes to the personality to support `docker volume ls`.

**Comment by matthewavery** [comment]
Yes this one is pretty much wrapped up opening a PR on it now. was very simple to get working. Just lacks some unit tests and this ticket is good to go.
