### ISSUE TITLE
vic-machine: deploy ESXi firewall configuration or ESXi agent vib

### ISSUE THREAD

**Issue by emlin** [vmware/vic#918]
During vch deployment, we need to make sure user's env works with VCH automatically, instead of requires user to modify firewall configuration manually.

Right now, we have several options for this.
* Use open ports for serial port by default, instead of current 2377.
* Change ESXi firewall configuration if the port is not open. This will need notification to user, cause that will change user's security plan. We might have one more option to let user pick up, change the configuration automatically, or just detect and warning if not opened.
* Deploy ESXi agent VIB. We had one VIB developed as @hickeng said, but that VIB is not signed by buildweb. This option has dependency, so might be less likely to happen in TP3.

**Comment by emlin** [comment]
After discussion with @hickeng and @andrewtchin, we decided to go with first option, and current preference is port 8080.

For this task, vic-machine should validate outbound port 8080 of the ESXi host is open, otherwise, warning user, with similar way used in bonneville-installer.

**Comment by hickeng** [comment]
Closing as dup of #801 given the approach we've decided on.
