### ISSUE TITLE
vic-machine binary for Windows

### ISSUE THREAD

**Issue by bradmeiseles** [vmware/vic#923]
We need a binary of vic-machine that runs on Windows since many vSphere users prefer Windows.

**Comment by emlin** [comment]
@mhagen-vmware Can we test in Windows?

**Comment by hagenmt** [comment]
Yep, robot framework is cross platform as well.

**Comment by emlin** [comment]
Cool. But can we have test infrastructure setup for Windows (drone slave)? So that we can test this vic-machine binary in Windows environment automatically.

**Comment by hagenmt** [comment]
Yep, there are a couple of different ways to tackle this - but robot also has a distributed agent that you can force run commands on different systems including windows boxes.

**Comment by emlin** [comment]
Great! Then would you have a task to support it? thanks

**Comment by hagenmt** [comment]
Yep, see #927
