### ISSUE TITLE
Test vic-machine windows support

### ISSUE THREAD

**Issue by hagenmt** [vmware/vic#927]
As a customer of VIC, many of my engineers might be using windows machines and want to control the VIC appliance so I need full, tested support for vic-machine in windows environments.

@karthik-narayan Which versions of Windows do we need to support?

**Comment by karthik-narayan** [comment]
Windows 7 and Windows 10 to being with.

**Comment by stuclem** [comment]
Sorry for the accidental pipeline changes - thought that I was in the doc issue referenced above.
