### ISSUE TITLE
Document docker volume create

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#932]
Per https://github.com/vmware/vic/issues/915

**Comment by stuclem** [comment]
Fix for https://github.com/vmware/vic/issues/915 is in PR https://github.com/vmware/vic/pull/1196.

**Comment by matthewavery** [comment]
I wanted to post a note here about the behavior of the `docker volume create --opt Capacity=<value>` flow. `<value>` is going to be in units of MB. Unless we decided against that the unit should be bumped up.

**Comment by stuclem** [comment]
Thanks @matthewavery. Assigning this to Nandita, who is documenting the supported docker commands.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/1548, which allows support for random volume names.

**Comment by npakrasi** [comment]
Added the note to the [Supported Docker Commands](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md) table.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1548 is implemented in PR https://github.com/vmware/vic/pull/1793

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/1758

**Comment by stuclem** [comment]
Reviewed by @matthewavery in https://github.com/vmware/vic/issues/1809.

**Comment by stuclem** [comment]
Merged in https://github.com/vmware/vic/pull/1809
