### ISSUE TITLE
WriteImage vmdks to tmp directory, then move to final location

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#933]
To guard against half writes or other inconsistencies, we should create the vmdk in `WriteImage` in a (unique) temp directory, then move the result after the data has been extracted and disk unmounted to the final location.

**Comment by fdawg4l** [comment]
Not a huge change, but needs to be done.

**Comment by fdawg4l** [comment]
This really needs to be done for GA. Will take this on in the next day or two.

**Comment by hmahmood** [comment]
The PR #1764 associated with the issue was reverted in #1927 . @fdawg4l is going to put up another PR for this, so reopening.
