### ISSUE TITLE
repository cache and vic integration

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#935]
docker has the notion of a repository cache that provides the repo (busybox), tag (latest, etc) and content addressable sha256 for image creation, modification and use.  

vic will require a similar cache.  This will primarily be used by imagec but will also influence the docker persona.

**Comment by hickeng** [comment]
@cgtexmex You say this will be "used" by imagec - do you mean that imagec will link against the code and do that mapping, or is it that the personality will use it to translate "busybox:latest" to a specific image before invoking imagec?

**Comment by cgtexmex** [comment]
We've opted to not create a distinct repository cache and to include this data in the image metadata that is currently being persisted.  So I'll close this issue as it's replaced by  [976](https://github.com/vmware/vic/issues/976) .
