### ISSUE TITLE
vic-machine `image-store` location used by images and by vms

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#945]
```
Usage of ./vic-machine:
<snip />
  -image-store string
         Image datastore name
<snip />
```

The flag `-image-store` is confusing.  Lets rename this to something like `-image-datastore`.

The datastore specified by this flag defines where images are downloaded to (via `docker pull`) AND where the container VMs are created.  There should likely be another flag to specify what datastore the container VMs should be created on.  If not a second flag, then the flag should be renamed to `-datastore`.

**Comment by emlin** [comment]
@fdawg4l There is another flag: **-container-store**, is meant to store container VMs, but that's not consumed by port-layer yet.
Is that what you want?

btw, will rename both flags to **-datastores.
