### ISSUE TITLE
Document how to create containers with multiple networks

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#951]
Per Epic https://github.com/vmware/vic/issues/424. Has an impact on both the App Dev and Admin docs.

The issues in the dev Epic that have a doc impact are https://github.com/vmware/vic/issues/938 and https://github.com/vmware/vic/issues/421.

**Comment by stuclem** [comment]
Docker network create (https://github.com/vmware/vic/issues/421) has been merged into master, so can be written up in App Dev. Port mapping (https://github.com/vmware/vic/issues/938) is slated for TP3.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/424 has moved to onsite beta.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/938 is implemented in PR https://github.com/vmware/vic/pull/1577.

**Comment by stuclem** [comment]
We have some use cases about networking in the [Network Overview](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/networks.md#use-cases) topic in Admin, which I think should actually move to the App Dev pub. Adding an example of a container using multiple networks would go alongside these existing examples.

**Comment by stuclem** [comment]
See also this socialcast post (VMware internal): https://vmware-com.socialcast.com/messages/31433553

**Comment by npakrasi** [comment]
Added use cases for multiple bridge networks and external networks.
