### ISSUE TITLE
Document docker container kill

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#954]
Per https://github.com/vmware/vic/issues/378.

**Comment by npakrasi** [comment]
Added to [Supported Docker Commands table](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md)

**Comment by stuclem** [comment]
According to email exchange between @mdubya66 and @karthik-narayan, docker kill won't make it into TP3, but will be in the onsite beta.

**Comment by stuclem** [comment]
Added issue https://github.com/vmware/vic/issues/1310 to track documenting the workaround for stopping containers in TP3.

**Comment by npakrasi** [comment]
Docker kill and workaround in [Supported Docker Commands](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md) table.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/378 is actually in GA.

**Comment by stuclem** [comment]
Initial implementation is in PR https://github.com/vmware/vic/pull/1737.

**Comment by npakrasi** [comment]
Added to the Supported Docker Commands table.

**Comment by stuclem** [comment]
`Docker wait` has been added to `docker kill` in PR https://github.com/vmware/vic/pull/2364 (not merged yet). Maybe this requires a doc update to say specifically that `kill `uses `wait`, so moving back into **In Progress** from **Done**.

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/2364 is now merged.
