### ISSUE TITLE
make isos broken

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#960]
> hmahmood@ubuntu:~/go/src/github.com/vmware/vic$ docker run -v $(pwd):/go/src/github.com/vmware/vic -w /go/src/github.com/vmware/vic golang:1.6.2 make isos
building /go/bin/swagger...
regenerating swagger models and operations for Portlayer API client...
2016/06/02 19:53:53 building a plan for generation
2016/06/02 19:53:53 planning definitions
2016/06/02 19:53:54 planning operations
2016/06/02 19:53:57 grouping operations into packages
2016/06/02 19:53:57 planning meta data and facades
2016/06/02 19:53:57 rendered model template: StoreUrl
2016/06/02 19:53:57 rendered model template: ContainerCreatedInfo
2016/06/02 19:53:57 rendered model template: NetworkConfig
2016/06/02 19:53:57 rendered model template: ScopeConfig
2016/06/02 19:53:57 rendered model template: Error
2016/06/02 19:53:57 rendered model template: ImageStore
2016/06/02 19:53:57 rendered model template: ContainerCreateConfig
2016/06/02 19:53:57 rendered model template: ContainerGetStateResponse
2016/06/02 19:53:57 rendered model template: Image
2016/06/02 19:53:57 rendered client parameters template: containers.CommitParameters
2016/06/02 19:53:57 rendered client responses template: containers.CommitResponses
2016/06/02 19:53:57 rendered client parameters template: containers.CreateParameters
2016/06/02 19:53:57 rendered client responses template: containers.CreateResponses
2016/06/02 19:53:57 rendered client parameters template: containers.GetParameters
2016/06/02 19:53:57 rendered client responses template: containers.GetResponses
2016/06/02 19:53:57 rendered client parameters template: containers.GetStateParameters
2016/06/02 19:53:57 rendered client responses template: containers.GetStateResponses
2016/06/02 19:53:57 rendered client parameters template: containers.StateChangeParameters
2016/06/02 19:53:57 rendered client responses template: containers.StateChangeResponses
2016/06/02 19:53:57 rendered operation group client template: containers.ContainersClient
2016/06/02 19:53:57 rendered client parameters template: interaction.ContainerJoinParameters
2016/06/02 19:53:57 rendered client responses template: interaction.ContainerJoinResponses
2016/06/02 19:53:57 rendered operation group client template: interaction.InteractionClient
2016/06/02 19:53:57 rendered client parameters template: misc.PingParameters
2016/06/02 19:53:57 rendered client responses template: misc.PingResponses
2016/06/02 19:53:57 rendered operation group client template: misc.MiscClient
2016/06/02 19:53:57 rendered client parameters template: scopes.AddContainerParameters
2016/06/02 19:53:57 rendered client responses template: scopes.AddContainerResponses
2016/06/02 19:53:57 rendered client parameters template: scopes.BindContainerParameters
2016/06/02 19:53:57 rendered client responses template: scopes.BindContainerResponses
2016/06/02 19:53:57 rendered client parameters template: scopes.CreateScopeParameters
2016/06/02 19:53:57 rendered client responses template: scopes.CreateScopeResponses
2016/06/02 19:53:57 rendered client parameters template: scopes.ListParameters
2016/06/02 19:53:57 rendered client responses template: scopes.ListResponses
2016/06/02 19:53:57 rendered client parameters template: scopes.ListAllParameters
2016/06/02 19:53:57 rendered client responses template: scopes.ListAllResponses
2016/06/02 19:53:57 rendered client parameters template: scopes.RemoveContainerParameters
2016/06/02 19:53:57 rendered client responses template: scopes.RemoveContainerResponses
2016/06/02 19:53:57 rendered client parameters template: scopes.UnbindContainerParameters
2016/06/02 19:53:57 rendered client responses template: scopes.UnbindContainerResponses
2016/06/02 19:53:58 rendered operation group client template: scopes.ScopesClient
2016/06/02 19:53:58 rendered client parameters template: storage.CreateImageStoreParameters
2016/06/02 19:53:58 rendered client responses template: storage.CreateImageStoreResponses
2016/06/02 19:53:58 rendered client parameters template: storage.GetImageParameters
2016/06/02 19:53:58 rendered client responses template: storage.GetImageResponses
2016/06/02 19:53:58 rendered client parameters template: storage.GetImageTarParameters
2016/06/02 19:53:58 rendered client responses template: storage.GetImageTarResponses
2016/06/02 19:53:58 rendered client parameters template: storage.ListImagesParameters
2016/06/02 19:53:58 rendered client responses template: storage.ListImagesResponses
2016/06/02 19:53:58 rendered client parameters template: storage.WriteImageParameters
2016/06/02 19:53:58 rendered client responses template: storage.WriteImageResponses
2016/06/02 19:53:58 rendered operation group client template: storage.StorageClient
2016/06/02 19:53:58 rendered client facade template: client.PortLayerClient
building imagec...
/bin/sh: 1: time: not found
Makefile:239: recipe for target 'bin/imagec' failed
make: *** [bin/imagec] Error 127

**Comment by machenbach** [comment]
make all is broken too.  Same error.

**Comment by machenbach** [comment]
Follow up comment:  This is an issue with the docker golang image.  If you start this interactively and install time, everything seems to work.
