### ISSUE TITLE
vSphere compatibility documentation

### ISSUE THREAD

**Issue by bradmeiseles** [vmware/vic#965]
When we release 1.0 we will have an official statement about supported versions very likely to be quite narrow. Something like "VIC is supported for use with vSphere 6.0, Enterprise Plus Edition." For our OSS bits where VMware isn't held to a support SLA, we don't need to be so restrictive. People are free to try VIC OSS with any version and edition of vSphere. We need a document somewhere in the github documentation that describes our feature dependencies on vSphere so experimenters are guided towards deployments that have a good chance of working. We should answer questions like these: 
- What features introduced in vSphere 6.0 do we rely on? When using vSphere 5.5, will VIC fail completely or will it operate as long as you don't try xyz? What about 5.1 and 5.0?
- What features of Enterprise Plus edition that are not available in Standard Edition or Essentials Edition do we rely on? In their absence will VIC fail completely of will it operate as long as you don't try xyz?
- Will VIC work with the free version of ESX or must a user have a licensed version?

**Comment by stuclem** [comment]
In TP3 we include the required licenses, list required features, and limit the version to 6.0:
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vic_installation_prereqs.md#supported-vsphere-configurations

If this is not enough, we'll expand the info for Onsite Beta.

**Comment by stuclem** [comment]
Compatibility with vSphere versions and features is being addressed in individual issues. Closing this one.
