### ISSUE TITLE
invalid character looking for beginning of value

### ISSUE THREAD

**Issue by hagenmt** [vmware/vic#968]
**VIC Version:**

7a756cc3bf311c17d25831ca855fcb4254923942

**Code**

```ts
docker -H 192.168.254.238:2376 --tls pull nginx
Using default tag: latest
latest: Pulling from library/nginx
51f5c6a04d83: Already exists 
a3ed95caeb02: Already exists 
51d229e136d0: Already exists 
bcd41daec8cc: Already exists 
invalid character 'p' looking for beginning of value

Return code is 1 as well.  Looks like this just started happening.
```

**Comment by hagenmt** [comment]
@caglar10ur I just re-read the slack channel, as I thought someone had mentioned this bug already.  Did you fix this somewhere?  It doesn't look like it is any later commits to master yet and I can't find any issue  for this.

**Comment by mhagen-vmware** [comment]
This is blocking integration testing currently.

**Comment by caglar10ur** [comment]
https://github.com/vmware/vic/pull/964

**Comment by mhagen-vmware** [comment]
Resolved on latest code
