### ISSUE TITLE
imagec should calculate, display and store image digest after pull

### ISSUE THREAD

**Issue by jzt** [vmware/vic#974]
We'll need to learn how to calculate or otherwise acquire the image digest if we don't know already. It's available in the schema 2 version of the manifest, so we can use that once docker hub supports it.

**Expected behavior:**

```
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
385e281300cc: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
Status: Downloaded newer image for busybox:latest
```

**Actual behavior:**
```
$ docker -H 192.168.218.219:2376 --tls --tlscert='./vic-docker-cert.pem' --tlskey='./vic-docker-key.pem' pull busybox
Using default tag: latest
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
385e281300cc: Pull complete
Status: Downloaded newer image for library/busybox:latest
```

**Comment by jzt** [comment]
Image digest is now being calculated and displayed at pull, but this ties into #976 it seems. @caglar10ur, do you think it would be possible to extend [imagec.go:ParseReference()](https://github.com/vmware/vic/blob/master/cmd/imagec/imagec.go#L165) to differentiate between the two? I was thinking perhaps differentiating between `options.digest` and a new `options.tag` and configuring the image metadata based on which one is being used, similar to how [docker is doing it](https://github.com/docker/docker/blob/master/daemon/images.go#L148).

**Comment by jzt** [comment]
Docker:

Pull by default tag (latest):
```
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
385e281300cc: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
Status: Downloaded newer image for busybox:latest
```
run `docker images --digests`:
```
$ docker images --digests
REPOSITORY          TAG                 DIGEST              IMAGE ID            CREATED             SIZE
busybox             latest              <none>              47bcc53f74dc        11 weeks ago        1.113 MB
```
Note the lack of a digest, but we have `busybox:latest` which points to `47bcc...`

Then pull busybox by digest:

```
$ docker pull busybox@sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92: Pulling from library/busybox
385e281300cc: Already exists
a3ed95caeb02: Already exists
Digest: sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
Status: Downloaded newer image for busybox@sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
```
Note that the layers already exist.

Then run `docker images --digests`:
```
$ docker images --digests
REPOSITORY          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
busybox             latest              <none>                                                                    47bcc53f74dc        11 weeks ago        1.113 MB
busybox             <none>              sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92   47bcc53f74dc        11 weeks ago        1.113 MB
```

Note that we now have an "image" with a name and a tag that points to `47bcc...` as well as an image with a name and a digest (no tag) that also points to `47bcc...`.

This could be made easier using a `repositories.json` metadata collection similar to docker's (that we can either persist to the port layer storage or just construct in memory from metadata during cache hydration).

The format of this file is like so:

```json
{
  "Repositories": {
    "busybox": {
      "busybox:latest": "sha256:47bcc53f74dc94b1920f0b34f6036096526296767650f223433fe65c35f149eb",
      "busybox@sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92": "sha256:47bcc53f74dc94b1920f0b34f6036096526296767650f223433fe65c35f149eb"
    }
  }
}
```
From the perspective of this file, it appears that the digest is treated as just another tag.

**Comment by caglar10ur** [comment]
I'm confused, if we calculate the digest at pull,then why we are still having this line https://github.com/vmware/vic/blob/master/cmd/imagec/imagec.go#L617 commented out :) ?

**Comment by caglar10ur** [comment]
And yeah we could change ParseReference to match what docker does

**Comment by jzt** [comment]
@caglar10ur no idea what you're [talking about](https://github.com/vmware/vic/pull/1016/files#diff-20cac0652b997c8f1ee1d0fb89688480L617)  :)  (my PR wasn't up yet)

**Comment by caglar10ur** [comment]
@jzt touché :)

**Comment by jzt** [comment]
I'm going to pick this up later after I consider the pros/cons between extending Docker's manifest struct and casting `digest.Digest` into string everywhere, or just using our own in general but using Docker's in tests (required by `imagec/docker.go:getManifestDigest()`). Should have a solution up tonight or early tomorrow.

**Comment by jzt** [comment]
I've settled on just adding a `Digest` field to our `Manifest` struct. I fixed the `TestFetchImageManifest` unit test by using manifest data from the busybox manifest pulled from docker hub (it now exercises `getManifestDigest()` properly).
