### ISSUE TITLE
imagec and our metadata design need to support multiple tags per image, including image digests

### ISSUE THREAD

**Issue by jzt** [vmware/vic#976]
We need a way to store a new tag in the ImageConfig metadata of an existing image. For example, when we already have `busybox:latest` and we pull `busybox:1.24.2` (also the latest busybox at the time of this writing), we should update the tags to reflect that `1.24.2` and `latest` are pointing to the same image.

Currently, imagec will realize that it has all the layers for a particular image and essentially perform a NOP (other than echoing that the images already exist).

**Expected behavior:**

Docker:
```
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
385e281300cc: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
Status: Downloaded newer image for busybox:latest

$ docker pull busybox:1.24.2
1.24.2: Pulling from library/busybox
385e281300cc: Already exists
a3ed95caeb02: Already exists
Digest: sha256:b820bb67cb60307e900f747edfca526fda133cf1c0868c516d9e695ef1f32067
Status: Downloaded newer image for busybox:1.24.2

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             1.24.2              47bcc53f74dc        11 weeks ago        1.113 MB
busybox             latest              47bcc53f74dc        11 weeks ago        1.113 MB
```
**Actual behavior:**

VIC:
```
$ docker $DOCKER_OPTS pull busybox
Using default tag: latest
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
385e281300cc: Pull complete
Status: Downloaded newer image for library/busybox:latest

$ docker $DOCKER_OPTS pull busybox:1.24.2
1.24.2: Pulling from library/busybox
385e281300cc: Already exists
a3ed95caeb02: Already exists
Status: Image is up to date for library/busybox:1.24.2

$ docker $DOCKER_OPTS images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              47bcc53f74dc        11 weeks ago        1.311 MB
```

**Comment by hickeng** [comment]
@cgtexmex @jzt Clint, you said you were persisting the tag data along with the image metadata - does that mean that "latest" gets special handling (it does seem more like a synthesized tag to me than the others - but that's possibly because I don't know if other tags can be updated in the same way).
If other tags can be updated to point to new images, does that mean we have to update the previously tagged image to remove the tag from it's metadata?

**Comment by corrieb** [comment]
This seems like as good a place as any to add the summary of the meeting we had today, in terms of action items and decisions made.

**Summary:** 

Zach is going to build a dictionary in the Docker Persona which queries the PortLayer for metadata when an image has been loaded. This will work based on the behavior Clint has already implemented, where image metadata is modified on the datastore. This dictionary will then support Docker ps, which Clint will then implement. At this point, the Dictionary will be functional, but it won't tolerate appliance restarts. 

This decision was made as it will be the most efficient way to expedite the ps functionality.

Concurrent with this, we will add a Key/Value API to the storage part of the Port Layer, which will ultimately provide for persistence of simple kv pairs. This will be the ultimate place where the tags, digests and other metadata extraneous to the metadata blob associated with a Docker image will be stored. This is a modification to the design where this was combined with the Docker image metadata in the image store. The modification is being justified as the right thing to do for the longer-term where image metadata is going to be immutable and each VCH keeps its own persistent metadata about images (such as tags). The KV store should also potentially have other uses.

The KV store should be implemented initially as very simple PortLayer API calls, backed by a trivial in-memory implementation. There will be a separate issue for this. We can add persistence to back this later on. Where this stuff should be persisted (guestInfo / datastore) is still a TBD.

Once we've moved the metadata into the KV store, we should then implement persistence for the KV store. Finally, we should implement re-hydration of the dictionary in the Docker Persona making it able to fully recover the image data on a restart.

**Support for multiple tags has been postponed until this work is completed**

**Next Steps:**

1) Clint to do enough to make the current implementation functional
2) Zach to create the dictionary in Docker Persona, which updates after imagec upload completion
3) Clint to implement Docker ps

Docker ps should now be functional

4) Ben/Faiyaz to spec up and implement KV API on the storage PortLayer and create trivial in-memory backing implementation
5) Modify imagec to push its metadata to the KV store (cease updating metadata in the datastore)

Docker ps should still work. Won't tolerate appliance restarts

6) Ben/Faiyaz to implement backing persistence for the KV store
7) Zach to implement re-hydration of the dictionary from the persisted KV

Docker ps should now work and should tolerate appliance restarts

**Use-cases**

1) Pull busybox:latest with an empty image store. Result: Store image and metadata
2) Pull busybox:latest with the correct image and same tag in the image store. Result: do nothing
3) Pull, but the latest tag on busybox now points to an updated image. Result: Store the new image with the latest tag. Remove the latest tag from the old image.
4) Pull busybox:<newtag> which points to the same image as busybox:latest which is in the store. Result: Add the tag to the metadata store.

**Comment by jzt** [comment]
@hickeng Right now, we can easily add support for a moving `latest` tag. It would entail adding the `latest` tag to the new image, and basically simply removing it from the old image. In the future, with the k/v store, we wouldn't need to do this. We'd basically update the value for the `latest` key to point to the new image ID. I believe that (in docker) all tag information is stored in `repositories.json`.

Docker behavior:
```
$ docker pull busybox:1.24.1                                                                                                      ⏎
1.24.1: Pulling from library/busybox

328210fcd5e0: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:c345d0402778a9e05e5e19961ff77eda820cf3a8ecf30117ec0451575b398877
Status: Downloaded newer image for busybox:1.24.1
$ docker tag 8b17efa7e876 busybox:latest
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             1.24.1              8b17efa7e876        3 months ago        1.113 MB
busybox             latest              8b17efa7e876        3 months ago        1.113 MB
$ docker rmi busybox:1.24.1
Untagged: busybox:1.24.1
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              8b17efa7e876        3 months ago        1.113 MB
```
Now we have an "old" `busybox:latest`.

To demonstrate what happens when `latest` moves:
```
$ docker pull busybox:latest
latest: Pulling from library/busybox
385e281300cc: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:4a731fb46adc5cefe3ae374a8b6020fc1b6ad667a279647766e9a3cd89f6fa92
Status: Downloaded newer image for busybox:latest
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              47bcc53f74dc        12 weeks ago        1.113 MB
<none>              <none>              8b17efa7e876        3 months ago        1.113 MB
```

BTW, this would not solve the multiple-tags-per-image issue, that will still be postponed.

**Comment by jzt** [comment]
Actually, I believe we would need @cgtexmex's most recent work to facilitate this.
