### ISSUE TITLE
Panic when trying to install appliance to vcenter with vic-machine-linux

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#987]
INFO[2016-06-06T15:54:02-05:00] ### Installing VCH ####                      
INFO[2016-06-06T15:54:02-05:00] Generating certificate/key pair - private key in ./docker-appliance-key.pem 
INFO[2016-06-06T15:54:03-05:00] Validating supplied configuration            
INFO[2016-06-06T15:54:06-05:00] Network network exists                       
INFO[2016-06-06T15:54:07-05:00] Creating a Resource Pool                     
INFO[2016-06-06T15:54:07-05:00] Creating appliance on target                 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4f7e08]

goroutine 1 [running]:
panic(0xfbef00, 0xc820014110)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/vmware/vic/lib/install/management.(*Dispatcher).createAppliance.func1(0x7fdf8109aad8, 0xc82040b020, 0x0, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/install/management/appliance.go:323 +0xe8
github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult(0x7fdf8109aad8, 0xc82040b020, 0xc82037dc18, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:66 +0x6a
github.com/vmware/vic/lib/install/management.(*Dispatcher).createAppliance(0xc8203febd0, 0xc8203eed80, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/install/management/appliance.go:324 +0x219
github.com/vmware/vic/lib/install/management.(*Dispatcher).Dispatch(0xc8203febd0, 0xc8203eed80, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/install/management/dispatcher.go:137 +0x2da
main.main()
	/drone/src/github.com/vmware/vic/cmd/vic-machine/install.go:283 +0x99a

**Comment by mhagen-vmware** [comment]
@emlin This is blocking me right now on trying to get the demo ready for tomorrow, can you take a look quick?

**Comment by hickeng** [comment]
@mhagen-vmware is this still an issue - if not please close this.

**Comment by mhagen-vmware** [comment]
Not seeing this anymore
