### ISSUE TITLE
persist container name to container vm metadata

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#997]
Assign a user friendly name to a newly created container and persist that to the container vms metadata

**Comment by hickeng** [comment]
I've got this change in as part of #746 - that's still in progress however.

**Comment by cgtexmex** [comment]
@hickeng  Ah...I thought someone had mentioned it before..but did a quick search and came up dry...if you're in flight I'll close this and reference yours.  If you need some assistance let me know.
